PARTIAL CLASS JBCOREQ
METHOD APPEND 
LOCAL nREQUISI AS DWORD	
SELF:SERVER:SETORDER(1)
SELF:SERVER:GoBottom()
nREQUISI:=SELF:SERVER:FIELDGET("REQUISI")
nREQUISI++
SUPER:Append()
SELF:SERVER:FIELDPUT("REQUISI",nREQUISI)	
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("TIPO","C")

METHOD buscaNUM( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTFGRP("PTO","BCO")	


METHOD cmdordenar( ) 
	  SELF:KeyFind()

METHOD cmdtipo( ) 
SELF:server:FIELDPUT("TIPO",SIMNAO(SELF:SERVER:FIELDGET("TIPO"),{"C","D"}))	

METHOD delete 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
SELF:server:delete()
SELF:server:skip(-1)
IF SELF:sERVER:BOF
   SELF:SERVER:GOTOP()	
ENDIF		

METHOD escFUN( ) 
LOCAL oESC AS XESCNUM	
//LOCAL aFORN AS ARRAY
LOCAL oSERVER AS USEFOLHA
oSERVER:=USEFOLHA{"FO_PES"}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oESC:=XESCNUM{SELF,,1,oSERVER}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("NUMERO",oESC:NUMERO)
ENDIF

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
