#region DEFINES
STATIC DEFINE JFO_PES_ADMITIDO := 107
STATIC DEFINE JFO_PES_BAIRRO := 113
STATIC DEFINE JFO_PES_BUSCANUM := 132
STATIC DEFINE JFO_PES_CCUSTO := 104
STATIC DEFINE JFO_PES_CEP := 116
STATIC DEFINE JFO_PES_CESTA := 146
STATIC DEFINE JFO_PES_CHAPA := 103
STATIC DEFINE JFO_PES_CHECKCNS := 203
STATIC DEFINE JFO_PES_CHECKCPF := 170
STATIC DEFINE JFO_PES_CHECKPIS := 194
STATIC DEFINE JFO_PES_CHECKRG := 169 
STATIC DEFINE JFO_PES_CHECKTIT := 201
STATIC DEFINE JFO_PES_CIDADE := 115
STATIC DEFINE JFO_PES_CMDBCO := 144
STATIC DEFINE JFO_PES_CMDBCO1 := 157
STATIC DEFINE JFO_PES_CMDBCO2 := 177
STATIC DEFINE JFO_PES_CMDCESTA := 145
STATIC DEFINE JFO_PES_CMDCESTA1 := 147
STATIC DEFINE JFO_PES_CMDCHECKUF := 149
STATIC DEFINE JFO_PES_CMDHORA := 131
STATIC DEFINE JFO_PES_CMDHORA1 := 164
STATIC DEFINE JFO_PES_CMDINSAL := 159
STATIC DEFINE JFO_PES_CMDORDENAR := 135
STATIC DEFINE JFO_PES_CMDPERIC := 158
STATIC DEFINE JFO_PES_CNS := 202
STATIC DEFINE JFO_PES_CPF := 171
STATIC DEFINE JFO_PES_DATTRANSF := 190
STATIC DEFINE JFO_PES_DEMITIDO := 108
STATIC DEFINE JFO_PES_DEPTO := 100
STATIC DEFINE JFO_PES_DEPTO2 := 192
STATIC DEFINE JFO_PES_ENDCOMPL := 184
STATIC DEFINE JFO_PES_ENDER := 112
STATIC DEFINE JFO_PES_ENDNUM := 183
STATIC DEFINE JFO_PES_ENDTIP := 187
STATIC DEFINE JFO_PES_ESCCDEM := 175
STATIC DEFINE JFO_PES_ESCCIVI := 178
STATIC DEFINE JFO_PES_ESCCOD := 133
STATIC DEFINE JFO_PES_ESCEXP := 173
STATIC DEFINE JFO_PES_ESCFUN := 139
STATIC DEFINE JFO_PES_ESCLOG := 188
STATIC DEFINE JFO_PES_ESCSITU := 180
STATIC DEFINE JFO_PES_ESCUF := 174
STATIC DEFINE JFO_PES_ESCUNID := 179
STATIC DEFINE JFO_PES_ESTADO := 114
STATIC DEFINE JFO_PES_ESTCIVIL := 167
STATIC DEFINE JFO_PES_FIXEDTEXT3 := 195
STATIC DEFINE JFO_PES_FIXEDTEXT4 := 206
STATIC DEFINE JFO_PES_FIXEDTEXT7 := 199
STATIC DEFINE JFO_PES_FIXEDTEXT8 := 197
STATIC DEFINE JFO_PES_FOTO := 143
STATIC DEFINE JFO_PES_FOTO1 := 141
STATIC DEFINE JFO_PES_FUNCAO := 109
STATIC DEFINE JFO_PES_HT := 111
STATIC DEFINE JFO_PES_HTT := 110
STATIC DEFINE JFO_PES_INSALUBRI := 161
STATIC DEFINE JFO_PES_MAE := 118
STATIC DEFINE JFO_PES_MODIRETA := 137
STATIC DEFINE JFO_PES_NASC := 204
STATIC DEFINE JFO_PES_NOME := 106
STATIC DEFINE JFO_PES_NUMEMPANT := 191
STATIC DEFINE JFO_PES_NUMERO := 129
STATIC DEFINE JFO_PES_OCOFGTS := 162
STATIC DEFINE JFO_PES_OCOFGTS1 := 176
STATIC DEFINE JFO_PES_PAI := 117
STATIC DEFINE JFO_PES_PERICULO := 160
STATIC DEFINE JFO_PES_PIS := 193
STATIC DEFINE JFO_PES_RG := 172
STATIC DEFINE JFO_PES_SALADM := 207
STATIC DEFINE JFO_PES_SC_ADMITIDO := 125
STATIC DEFINE JFO_PES_SC_ADMITIDO1 := 189
STATIC DEFINE JFO_PES_SC_BAIRRO := 153
STATIC DEFINE JFO_PES_SC_CEP := 150
STATIC DEFINE JFO_PES_SC_CEP1 := 163
STATIC DEFINE JFO_PES_SC_CHAPA := 123
STATIC DEFINE JFO_PES_SC_CHAPA1 := 134
STATIC DEFINE JFO_PES_SC_CHAPA2 := 136
STATIC DEFINE JFO_PES_SC_CHAPA3 := 138
STATIC DEFINE JFO_PES_SC_CHAPA5 := 186
STATIC DEFINE JFO_PES_SC_CIDADE := 151
STATIC DEFINE JFO_PES_SC_DEMITIDO := 127
STATIC DEFINE JFO_PES_SC_DEPTO := 120
STATIC DEFINE JFO_PES_SC_DESTINO2 := 142
STATIC DEFINE JFO_PES_SC_DESTINO3 := 140
STATIC DEFINE JFO_PES_SC_ENDERECO := 154
STATIC DEFINE JFO_PES_SC_ESTADO := 152
STATIC DEFINE JFO_PES_SC_FONE1 := 205
STATIC DEFINE JFO_PES_SC_HTT := 128
STATIC DEFINE JFO_PES_SC_NOME := 124
STATIC DEFINE JFO_PES_SC_NOME3 := 155
STATIC DEFINE JFO_PES_SC_NOME4 := 156
STATIC DEFINE JFO_PES_SC_NUMERO := 119
STATIC DEFINE JFO_PES_SC_SECAO := 121
STATIC DEFINE JFO_PES_SC_SETOR := 122
STATIC DEFINE JFO_PES_SC_SETOR1 := 185
STATIC DEFINE JFO_PES_SC_TIPO := 126
STATIC DEFINE JFO_PES_SC_TIPO1 := 165
STATIC DEFINE JFO_PES_SC_UF2 := 168
STATIC DEFINE JFO_PES_SC_UF3 := 182
STATIC DEFINE JFO_PES_SC_VALOR := 208
STATIC DEFINE JFO_PES_SECAO := 102
STATIC DEFINE JFO_PES_SERIE2 := 196
STATIC DEFINE JFO_PES_SETOR := 101
STATIC DEFINE JFO_PES_SEXO := 166
STATIC DEFINE JFO_PES_SITUACAO := 181
STATIC DEFINE JFO_PES_TIPO := 130
STATIC DEFINE JFO_PES_TITULO := 200
STATIC DEFINE JFO_PES_TITUZONA := 198
STATIC DEFINE JFO_PES_UNIFUN := 105
STATIC DEFINE JFO_PES_VT := 148
#endregion

PARTIAL CLASS JFO_PES INHERIT MYDataWindow
PROTECT oDBNUMERO AS DataColumn
PROTECT oDBNOME AS DataColumn
PROTECT oDBDEPTO AS DataColumn
PROTECT oDBSETOR AS DataColumn
PROTECT oDBSECAO AS DataColumn
PROTECT oDBADMITIDO AS DataColumn
PROTECT oDBDEMITIDO AS DataColumn
PROTECT oDBHT AS DataColumn
PROTECT oDCDEPTO AS rightSle
PROTECT oDCSETOR AS rightSle
PROTECT oDCSECAO AS rightSle
PROTECT oDCCHAPA AS rightSle
PROTECT oDCCCUSTO AS rightSle
PROTECT oDCUNIFUN AS rightSle
PROTECT oDCNOME AS SINGLELINEEDIT
PROTECT oDCADMITIDO AS DateSle
PROTECT oDCDEMITIDO AS DateSle
PROTECT oDCfuncao AS rightSle
PROTECT oDCHTT AS SINGLELINEEDIT
PROTECT oDCHT AS SINGLELINEEDIT
PROTECT oDCENDER AS SINGLELINEEDIT
PROTECT oDCBAIRRO AS SINGLELINEEDIT
PROTECT oDCESTADO AS SINGLELINEEDIT
PROTECT oDCCIDADE AS SINGLELINEEDIT
PROTECT oDCCEP AS SINGLELINEEDIT
PROTECT oDCPAI AS SINGLELINEEDIT
PROTECT oDCMAE AS SINGLELINEEDIT
PROTECT oDCSC_NUMERO AS FIXEDTEXT
PROTECT oDCSC_DEPTO AS FIXEDTEXT
PROTECT oDCSC_SECAO AS FIXEDTEXT
PROTECT oDCSC_SETOR AS FIXEDTEXT
PROTECT oDCSC_CHAPA AS FIXEDTEXT
PROTECT oDCSC_NOME AS FIXEDTEXT
PROTECT oDCSC_ADMITIDO AS FIXEDTEXT
PROTECT oDCSC_TIPO AS FIXEDTEXT
PROTECT oDCSC_DEMITIDO AS FIXEDTEXT
PROTECT oDCSC_HTT AS FIXEDTEXT
PROTECT oDCNUMERO AS SINGLELINEEDIT
PROTECT oDCTIPO AS SINGLELINEEDIT
PROTECT oCCcmdhora AS PUSHBUTTON
PROTECT oCCbuscaNUM AS PUSHBUTTON
PROTECT oCCesccod AS PUSHBUTTON
PROTECT oDCSC_CHAPA1 AS FIXEDTEXT
PROTECT oCCcmdordenar AS PUSHBUTTON
PROTECT oDCSC_CHAPA2 AS FIXEDTEXT
PROTECT oDCMODIRETA AS SINGLELINEEDIT
PROTECT oDCSC_CHAPA3 AS FIXEDTEXT
PROTECT oCCescfun AS PUSHBUTTON
PROTECT oDCSC_DESTINO3 AS FIXEDTEXT
PROTECT oCCfoto1 AS PUSHBUTTON
PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
PROTECT oCCfoto AS PUSHBUTTON
PROTECT oCCcmdbco AS PUSHBUTTON
PROTECT oCCcmdcesta AS PUSHBUTTON
PROTECT oDCCESTA AS SINGLELINEEDIT
PROTECT oCCcmdcesta1 AS PUSHBUTTON
PROTECT oDCVT AS SINGLELINEEDIT
PROTECT oCCCMDCHECKUF AS PUSHBUTTON
PROTECT oDCSC_CEP AS FIXEDTEXT
PROTECT oDCSC_CIDADE AS FIXEDTEXT
PROTECT oDCSC_ESTADO AS FIXEDTEXT
PROTECT oDCSC_BAIRRO AS FIXEDTEXT
PROTECT oDCSC_ENDERECO AS FIXEDTEXT
PROTECT oDCSC_NOME3 AS FIXEDTEXT
PROTECT oDCSC_NOME4 AS FIXEDTEXT
PROTECT oCCcmdbco1 AS PUSHBUTTON
PROTECT oCCcmdPERIC AS PUSHBUTTON
PROTECT oCCcmdINSAL AS PUSHBUTTON
PROTECT oDCPERICULO AS SINGLELINEEDIT
PROTECT oDCINSALUBRI AS SINGLELINEEDIT
PROTECT oDCOCOFGTS AS SINGLELINEEDIT
PROTECT oDCSC_CEP1 AS FIXEDTEXT
PROTECT oCCcmdhora1 AS PUSHBUTTON
PROTECT oDCSC_TIPO1 AS FIXEDTEXT
PROTECT oDCSEXO AS SINGLELINEEDIT
PROTECT oDCESTCIVIL AS SINGLELINEEDIT
PROTECT oDCSC_UF2 AS FIXEDTEXT
PROTECT oCCBTNcheckrg AS PUSHBUTTON
PROTECT oCCcheckcPF AS PUSHBUTTON
PROTECT oDCcpf AS rightSle
PROTECT oDCRG AS rightSle
PROTECT oCCescEXP AS PUSHBUTTON
PROTECT oCCescUF AS PUSHBUTTON
PROTECT oCCescCDEM AS PUSHBUTTON
PROTECT oDCOCOFGTS1 AS SINGLELINEEDIT
PROTECT oCCcmdbco2 AS PUSHBUTTON
PROTECT oCCescCIVI AS PUSHBUTTON
PROTECT oCCescunid AS PUSHBUTTON
PROTECT oCCescSITU AS PUSHBUTTON
PROTECT oDCSITUACAO AS SINGLELINEEDIT
PROTECT oDCSC_UF3 AS FIXEDTEXT
PROTECT oDCENDNUM AS rightSle
PROTECT oDCENDCOMPL AS rightSle
PROTECT oDCSC_SETOR1 AS FIXEDTEXT
PROTECT oDCSC_CHAPA5 AS FIXEDTEXT
PROTECT oDCENDTIP AS SINGLELINEEDIT
PROTECT oCCescLOG AS PUSHBUTTON
PROTECT oDCSC_ADMITIDO1 AS FIXEDTEXT
PROTECT oDCDATTRANSF AS DateSle
PROTECT oDCNUMEMPANT AS rightSle
PROTECT oDCDEPTO2 AS rightSle
PROTECT oDCPIS AS SINGLELINEEDIT
PROTECT oCCcheckPIS AS PUSHBUTTON
PROTECT oDCFixedText3 AS Hyperlink
PROTECT oDCSERIE2 AS SINGLELINEEDIT
PROTECT oDCFixedText8 AS FIXEDTEXT
PROTECT oDCTITUZONA AS SINGLELINEEDIT
PROTECT oDCFixedText7 AS FIXEDTEXT
PROTECT oDCTITULO AS rightSle
PROTECT oCCcheckTIT AS PUSHBUTTON
PROTECT oDCcns AS rightSle
PROTECT oCCcheckcns AS PUSHBUTTON
PROTECT oDCNASC AS SINGLELINEEDIT
PROTECT oDCSC_FONE1 AS FIXEDTEXT
PROTECT oDCFixedText4 AS Hyperlink
PROTECT oDCSALADM AS rightSle
PROTECT oDCSC_VALOR AS FIXEDTEXT

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS ADMITIDO
RETURN SELF:FieldGet( #ADMITIDO )

ASSIGN ADMITIDO( uValue )
SELF:FieldPut( #ADMITIDO , uValue )

ACCESS BAIRRO
RETURN SELF:FieldGet( #BAIRRO )

ASSIGN BAIRRO( uValue )
SELF:FieldPut( #BAIRRO , uValue )

ACCESS CCUSTO
RETURN SELF:FieldGet( #CCUSTO )

ASSIGN CCUSTO( uValue )
SELF:FieldPut( #CCUSTO , uValue )

ACCESS CEP
RETURN SELF:FieldGet( #CEP )

ASSIGN CEP( uValue )
SELF:FieldPut( #CEP , uValue )

ACCESS CESTA
RETURN SELF:FieldGet( #CESTA )

ASSIGN CESTA( uValue )
SELF:FieldPut( #CESTA , uValue )

ACCESS CHAPA
RETURN SELF:FieldGet( #CHAPA )

ASSIGN CHAPA( uValue )
SELF:FieldPut( #CHAPA , uValue )

METHOD checkPIS( ) 
valpis(SELF:SERVER:FIELDGET("PIS"),TRUE)


ACCESS CIDADE
RETURN SELF:FieldGet( #CIDADE )

ASSIGN CIDADE( uValue )
SELF:FieldPut( #CIDADE , uValue )

ACCESS cns
RETURN SELF:FieldGet( #cns )

ASSIGN cns( uValue )
SELF:FieldPut( #cns , uValue )

ACCESS cpf
RETURN SELF:FieldGet( #cpf )

ASSIGN cpf( uValue )
SELF:FieldPut( #cpf , uValue )

ACCESS DATTRANSF
RETURN SELF:FieldGet( #DATTRANSF )

ASSIGN DATTRANSF( uValue )
SELF:FieldPut( #DATTRANSF , uValue )

ACCESS DEMITIDO
RETURN SELF:FieldGet( #DEMITIDO )

ASSIGN DEMITIDO( uValue )
SELF:FieldPut( #DEMITIDO , uValue )

ACCESS DEPTO
RETURN SELF:FieldGet( #DEPTO )

ASSIGN DEPTO( uValue )
SELF:FieldPut( #DEPTO , uValue )

ACCESS DEPTO2
RETURN SELF:FieldGet( #DEPTO2 )

ASSIGN DEPTO2( uValue )
SELF:FieldPut( #DEPTO2 , uValue )

ACCESS ENDCOMPL
RETURN SELF:FieldGet( #ENDCOMPL )

ASSIGN ENDCOMPL( uValue )
SELF:FieldPut( #ENDCOMPL , uValue )

ACCESS ENDER
RETURN SELF:FieldGet( #ENDER )

ASSIGN ENDER( uValue )
SELF:FieldPut( #ENDER , uValue )

ACCESS ENDNUM
RETURN SELF:FieldGet( #ENDNUM )

ASSIGN ENDNUM( uValue )
SELF:FieldPut( #ENDNUM , uValue )

ACCESS ENDTIP
RETURN SELF:FieldGet( #ENDTIP )

ASSIGN ENDTIP( uValue )
SELF:FieldPut( #ENDTIP , uValue )

METHOD escLOG( ) 
LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"ELOG",SELF:SERVER:FIELDGET("ENDTIP")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("ENDTIP",oESC:cCODIGO)
ENDIF								

ACCESS ESTADO
RETURN SELF:FieldGet( #ESTADO )

ASSIGN ESTADO( uValue )
SELF:FieldPut( #ESTADO , uValue )

ACCESS ESTCIVIL
RETURN SELF:FieldGet( #ESTCIVIL )

ASSIGN ESTCIVIL( uValue )
SELF:FieldPut( #ESTCIVIL , uValue )

ACCESS funcao
RETURN SELF:FieldGet( #funcao )

ASSIGN funcao( uValue )
SELF:FieldPut( #funcao , uValue )

ACCESS HT
RETURN SELF:FieldGet( #HT )

ASSIGN HT( uValue )
SELF:FieldPut( #HT , uValue )

ACCESS HTT
RETURN SELF:FieldGet( #HTT )

ASSIGN HTT( uValue )
SELF:FieldPut( #HTT , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JFO_PES" , _GetInst()},iCtlID)

	SELF:oDCDEPTO := rightSle{SELF , ResourceID{ JFO_PES_DEPTO  , _GetInst() } }
	SELF:oDCDEPTO:FieldSpec := PADRAO_NUM_04{}
	SELF:oDCDEPTO:HyperLabel := HyperLabel{#DEPTO , "Dep" , NULL_STRING , "FO_PES_DEPTO"}

	SELF:oDCSETOR := rightSle{SELF , ResourceID{ JFO_PES_SETOR  , _GetInst() } }
	SELF:oDCSETOR:FieldSpec := PADRAO_NUM_04{}
	SELF:oDCSETOR:HyperLabel := HyperLabel{#SETOR , "Set" , NULL_STRING , "FO_PES_SETOR"}

	SELF:oDCSECAO := rightSle{SELF , ResourceID{ JFO_PES_SECAO  , _GetInst() } }
	SELF:oDCSECAO:FieldSpec := PADRAO_NUM_04{}
	SELF:oDCSECAO:HyperLabel := HyperLabel{#SECAO , "Sec" , NULL_STRING , "FO_PES_SECAO"}

	SELF:oDCCHAPA := rightSle{SELF , ResourceID{ JFO_PES_CHAPA  , _GetInst() } }
	SELF:oDCCHAPA:FieldSpec := PADRAO_NUM_04{}
	SELF:oDCCHAPA:HyperLabel := HyperLabel{#CHAPA , "Chapa:" , NULL_STRING , "FO_PES_CHAPA"}

	SELF:oDCCCUSTO := rightSle{SELF , ResourceID{ JFO_PES_CCUSTO  , _GetInst() } }
	SELF:oDCCCUSTO:FieldSpec := PADRAO_NUM_06{}
	SELF:oDCCCUSTO:HyperLabel := HyperLabel{#CCUSTO , "Chapa:" , NULL_STRING , "FO_PES_CHAPA"}

	SELF:oDCUNIFUN := rightSle{SELF , ResourceID{ JFO_PES_UNIFUN  , _GetInst() } }
	SELF:oDCUNIFUN:FieldSpec := PADRAO_char_10{}
	SELF:oDCUNIFUN:HyperLabel := HyperLabel{#UNIFUN , "Chapa:" , NULL_STRING , "FO_PES_CHAPA"}

	SELF:oDCNOME := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_NOME  , _GetInst() } }
	SELF:oDCNOME:FieldSpec := PADRAO_CHAR_60{}
	SELF:oDCNOME:HyperLabel := HyperLabel{#NOME , "Nome:" , NULL_STRING , "FO_PES_NOME"}

	SELF:oDCADMITIDO := DateSle{SELF , ResourceID{ JFO_PES_ADMITIDO  , _GetInst() } }
	SELF:oDCADMITIDO:FieldSpec := DATE_FIELD{}
	SELF:oDCADMITIDO:HyperLabel := HyperLabel{#ADMITIDO , "Admitido:" , NULL_STRING , "FO_PES_ADMITIDO"}

	SELF:oDCDEMITIDO := DateSle{SELF , ResourceID{ JFO_PES_DEMITIDO  , _GetInst() } }
	SELF:oDCDEMITIDO:FieldSpec := DATE_FIELD{}
	SELF:oDCDEMITIDO:HyperLabel := HyperLabel{#DEMITIDO , "Demitido:" , NULL_STRING , "FO_PES_DEMITIDO"}

	SELF:oDCfuncao := rightSle{SELF , ResourceID{ JFO_PES_FUNCAO  , _GetInst() } }
	SELF:oDCfuncao:FieldSpec := PADRAO_NUM_04{}
	SELF:oDCfuncao:HyperLabel := HyperLabel{#funcao , "Chapa:" , NULL_STRING , "FO_PES_CHAPA"}

	SELF:oDCHTT := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_HTT  , _GetInst() } }
	SELF:oDCHTT:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCHTT:HyperLabel := HyperLabel{#HTT , "Htt:" , NULL_STRING , "FO_PES_HTT"}

	SELF:oDCHT := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_HT  , _GetInst() } }
	SELF:oDCHT:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCHT:HyperLabel := HyperLabel{#HT , "Ht:" , NULL_STRING , "FO_PES_HT"}

	SELF:oDCENDER := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_ENDER  , _GetInst() } }
	SELF:oDCENDER:FieldSpec := padrao_char_40{}
	SELF:oDCENDER:TooltipText := "Endereço"
	SELF:oDCENDER:HyperLabel := HyperLabel{#ENDER , "Endereco:" , NULL_STRING , "MA01_ENDERECO"}

	SELF:oDCBAIRRO := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_BAIRRO  , _GetInst() } }
	SELF:oDCBAIRRO:FieldSpec := padrao_char_30{}
	SELF:oDCBAIRRO:TooltipText := "Bairro"
	SELF:oDCBAIRRO:HyperLabel := HyperLabel{#BAIRRO , "Bairro:" , NULL_STRING , "MA01_BAIRRO"}

	SELF:oDCESTADO := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_ESTADO  , _GetInst() } }
	SELF:oDCESTADO:FieldSpec := uf_field{}
	SELF:oDCESTADO:TooltipText := "Digite  o Estado"
	SELF:oDCESTADO:HyperLabel := HyperLabel{#ESTADO , "Numero:" , NULL_STRING , "MA01_NUMERO"}

	SELF:oDCCIDADE := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_CIDADE  , _GetInst() } }
	SELF:oDCCIDADE:FieldSpec := padrao_char_35{}
	SELF:oDCCIDADE:TooltipText := "Cidade"
	SELF:oDCCIDADE:HyperLabel := HyperLabel{#CIDADE , "Cidade:" , NULL_STRING , "MA01_CIDADE"}

	SELF:oDCCEP := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_CEP  , _GetInst() } }
	SELF:oDCCEP:FieldSpec := padrao_char_09{}
	SELF:oDCCEP:TooltipText := "CEP"
	SELF:oDCCEP:HyperLabel := HyperLabel{#CEP , "Cep:" , NULL_STRING , "MA01_CEP"}

	SELF:oDCPAI := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_PAI  , _GetInst() } }
	SELF:oDCPAI:FieldSpec := PADRAO_CHAR_60{}
	SELF:oDCPAI:HyperLabel := HyperLabel{#PAI , "Nome:" , NULL_STRING , "FO_PES_NOME"}

	SELF:oDCMAE := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_MAE  , _GetInst() } }
	SELF:oDCMAE:FieldSpec := PADRAO_CHAR_60{}
	SELF:oDCMAE:HyperLabel := HyperLabel{#MAE , "Nome:" , NULL_STRING , "FO_PES_NOME"}

	SELF:oDCSC_NUMERO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_NUMERO  , _GetInst() } }
	SELF:oDCSC_NUMERO:HyperLabel := HyperLabel{#SC_NUMERO , "Numero:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DEPTO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_DEPTO  , _GetInst() } }
	SELF:oDCSC_DEPTO:HyperLabel := HyperLabel{#SC_DEPTO , "Depto:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SECAO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_SECAO  , _GetInst() } }
	SELF:oDCSC_SECAO:HyperLabel := HyperLabel{#SC_SECAO , "Secao:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SETOR := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_SETOR  , _GetInst() } }
	SELF:oDCSC_SETOR:HyperLabel := HyperLabel{#SC_SETOR , "Setor:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CHAPA := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_CHAPA  , _GetInst() } }
	SELF:oDCSC_CHAPA:HyperLabel := HyperLabel{#SC_CHAPA , "Chapa:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_NOME  , _GetInst() } }
	SELF:oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME , "Nome:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ADMITIDO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_ADMITIDO  , _GetInst() } }
	SELF:oDCSC_ADMITIDO:HyperLabel := HyperLabel{#SC_ADMITIDO , "Admitido:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_TIPO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_TIPO  , _GetInst() } }
	SELF:oDCSC_TIPO:HyperLabel := HyperLabel{#SC_TIPO , "Tipo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DEMITIDO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_DEMITIDO  , _GetInst() } }
	SELF:oDCSC_DEMITIDO:HyperLabel := HyperLabel{#SC_DEMITIDO , "Demitido:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HTT := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_HTT  , _GetInst() } }
	SELF:oDCSC_HTT:HyperLabel := HyperLabel{#SC_HTT , "Horario" , NULL_STRING , NULL_STRING}

	SELF:oDCNUMERO := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_NUMERO  , _GetInst() } }
	SELF:oDCNUMERO:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNUMERO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCNUMERO:Font( oFont )
	SELF:oDCNUMERO:HyperLabel := HyperLabel{#NUMERO , "Numero:" , NULL_STRING , "FO_PES_NUMERO"}

	SELF:oDCTIPO := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_TIPO  , _GetInst() } }
	SELF:oDCTIPO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCTIPO:Font( oFont )
	SELF:oDCTIPO:HyperLabel := HyperLabel{#TIPO , "Tipo:" , NULL_STRING , "FO_PES_TIPO"}

	SELF:oCCcmdhora := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDHORA  , _GetInst() } }
	SELF:oCCcmdhora:HyperLabel := HyperLabel{#cmdhora , "M-es H-ora" , NULL_STRING , NULL_STRING}

	SELF:oCCbuscaNUM := PUSHBUTTON{SELF , ResourceID{ JFO_PES_BUSCANUM  , _GetInst() } }
	SELF:oCCbuscaNUM:Image := ico_find{}
	SELF:oCCbuscaNUM:HyperLabel := HyperLabel{#buscaNUM , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCesccod := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCCOD  , _GetInst() } }
	SELF:oCCesccod:Image := ICO_FIND{}
	SELF:oCCesccod:HyperLabel := HyperLabel{#esccod , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CHAPA1 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_CHAPA1  , _GetInst() } }
	SELF:oDCSC_CHAPA1:HyperLabel := HyperLabel{#SC_CHAPA1 , "CentroCusto" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdordenar := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDORDENAR  , _GetInst() } }
	SELF:oCCcmdordenar:Image := ico_az{}
	SELF:oCCcmdordenar:HyperLabel := HyperLabel{#cmdordenar , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CHAPA2 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_CHAPA2  , _GetInst() } }
	SELF:oDCSC_CHAPA2:HyperLabel := HyperLabel{#SC_CHAPA2 , "Unid.Funcional" , NULL_STRING , NULL_STRING}

	SELF:oDCMODIRETA := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_MODIRETA  , _GetInst() } }
	SELF:oDCMODIRETA:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCMODIRETA:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCMODIRETA:Font( oFont )
	SELF:oDCMODIRETA:HyperLabel := HyperLabel{#MODIRETA , "Chapa:" , NULL_STRING , "FO_PES_CHAPA"}

	SELF:oDCSC_CHAPA3 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_CHAPA3  , _GetInst() } }
	SELF:oDCSC_CHAPA3:HyperLabel := HyperLabel{#SC_CHAPA3 , "Funcao:" , NULL_STRING , NULL_STRING}

	SELF:oCCescfun := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCFUN  , _GetInst() } }
	SELF:oCCescfun:Image := ICO_FIND{}
	SELF:oCCescfun:HyperLabel := HyperLabel{#escfun , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO3 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_DESTINO3  , _GetInst() } }
	SELF:oDCSC_DESTINO3:HyperLabel := HyperLabel{#SC_DESTINO3 , "Foto Ver" , NULL_STRING , NULL_STRING}

	SELF:oCCfoto1 := PUSHBUTTON{SELF , ResourceID{ JFO_PES_FOTO1  , _GetInst() } }
	SELF:oCCfoto1:Image := ico_camera{}
	SELF:oCCfoto1:HyperLabel := HyperLabel{#foto1 , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO2 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_DESTINO2  , _GetInst() } }
	SELF:oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2 , "Foto Editar" , NULL_STRING , NULL_STRING}

	SELF:oCCfoto := PUSHBUTTON{SELF , ResourceID{ JFO_PES_FOTO  , _GetInst() } }
	SELF:oCCfoto:Image := ico_camera{}
	SELF:oCCfoto:HyperLabel := HyperLabel{#foto , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCcmdbco := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDBCO  , _GetInst() } }
	SELF:oCCcmdbco:HyperLabel := HyperLabel{#cmdbco , "Sim Nao " , NULL_STRING , NULL_STRING}

	SELF:oCCcmdcesta := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDCESTA  , _GetInst() } }
	SELF:oCCcmdcesta:HyperLabel := HyperLabel{#cmdcesta , "Cesta S/N/Vale" , NULL_STRING , NULL_STRING}

	SELF:oDCCESTA := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_CESTA  , _GetInst() } }
	SELF:oDCCESTA:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCCESTA:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCCESTA:Font( oFont )
	SELF:oDCCESTA:HyperLabel := HyperLabel{#CESTA , "Tipo:" , NULL_STRING , "FO_PES_TIPO"}

	SELF:oCCcmdcesta1 := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDCESTA1  , _GetInst() } }
	SELF:oCCcmdcesta1:HyperLabel := HyperLabel{#cmdcesta1 , "ValeTrans S/N" , NULL_STRING , NULL_STRING}

	SELF:oDCVT := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_VT  , _GetInst() } }
	SELF:oDCVT:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCVT:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCVT:Font( oFont )
	SELF:oDCVT:HyperLabel := HyperLabel{#VT , "Tipo:" , NULL_STRING , "FO_PES_TIPO"}

	SELF:oCCCMDCHECKUF := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDCHECKUF  , _GetInst() } }
	SELF:oCCCMDCHECKUF:HyperLabel := HyperLabel{#CMDCHECKUF , "Checar" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CEP := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_CEP  , _GetInst() } }
	SELF:oDCSC_CEP:HyperLabel := HyperLabel{#SC_CEP , "Cep:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CIDADE := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_CIDADE  , _GetInst() } }
	SELF:oDCSC_CIDADE:HyperLabel := HyperLabel{#SC_CIDADE , "Cidade:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ESTADO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_ESTADO  , _GetInst() } }
	SELF:oDCSC_ESTADO:HyperLabel := HyperLabel{#SC_ESTADO , "Estado:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_BAIRRO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_BAIRRO  , _GetInst() } }
	SELF:oDCSC_BAIRRO:HyperLabel := HyperLabel{#SC_BAIRRO , "Bairro:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ENDERECO := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_ENDERECO  , _GetInst() } }
	SELF:oDCSC_ENDERECO:HyperLabel := HyperLabel{#SC_ENDERECO , "Endereço:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME3 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_NOME3  , _GetInst() } }
	SELF:oDCSC_NOME3:HyperLabel := HyperLabel{#SC_NOME3 , "Pai" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME4 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_NOME4  , _GetInst() } }
	SELF:oDCSC_NOME4:HyperLabel := HyperLabel{#SC_NOME4 , "Mâe" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdbco1 := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDBCO1  , _GetInst() } }
	SELF:oCCcmdbco1:HyperLabel := HyperLabel{#cmdbco1 , "Direta Indireta Administracao Comercial" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdPERIC := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDPERIC  , _GetInst() } }
	SELF:oCCcmdPERIC:HyperLabel := HyperLabel{#cmdPERIC , "Periculosidade S/N" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdINSAL := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDINSAL  , _GetInst() } }
	SELF:oCCcmdINSAL:HyperLabel := HyperLabel{#cmdINSAL , "Insalubridade S/N" , NULL_STRING , NULL_STRING}

	SELF:oDCPERICULO := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_PERICULO  , _GetInst() } }
	SELF:oDCPERICULO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCPERICULO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCPERICULO:Font( oFont )
	SELF:oDCPERICULO:HyperLabel := HyperLabel{#PERICULO , "Tipo:" , NULL_STRING , "FO_PES_TIPO"}

	SELF:oDCINSALUBRI := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_INSALUBRI  , _GetInst() } }
	SELF:oDCINSALUBRI:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCINSALUBRI:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCINSALUBRI:Font( oFont )
	SELF:oDCINSALUBRI:HyperLabel := HyperLabel{#INSALUBRI , "Tipo:" , NULL_STRING , "FO_PES_TIPO"}

	SELF:oDCOCOFGTS := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_OCOFGTS  , _GetInst() } }
	SELF:oDCOCOFGTS:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCOCOFGTS:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCOCOFGTS:Font( oFont )
	SELF:oDCOCOFGTS:HyperLabel := HyperLabel{#OCOFGTS , "Htt:" , NULL_STRING , "FO_PES_HTT"}

	SELF:oDCSC_CEP1 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_CEP1  , _GetInst() } }
	SELF:oDCSC_CEP1:HyperLabel := HyperLabel{#SC_CEP1 , "Exposicao" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdhora1 := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDHORA1  , _GetInst() } }
	SELF:oCCcmdhora1:HyperLabel := HyperLabel{#cmdhora1 , "Homen Mulher" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_TIPO1 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_TIPO1  , _GetInst() } }
	SELF:oDCSC_TIPO1:HyperLabel := HyperLabel{#SC_TIPO1 , "Sexo" , NULL_STRING , NULL_STRING}

	SELF:oDCSEXO := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_SEXO  , _GetInst() } }
	SELF:oDCSEXO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCSEXO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCSEXO:Font( oFont )
	SELF:oDCSEXO:HyperLabel := HyperLabel{#SEXO , "Tipo:" , NULL_STRING , "FO_PES_TIPO"}

	SELF:oDCESTCIVIL := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_ESTCIVIL  , _GetInst() } }
	SELF:oDCESTCIVIL:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCESTCIVIL:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	SELF:oDCESTCIVIL:Font( oFont )
	SELF:oDCESTCIVIL:HyperLabel := HyperLabel{#ESTCIVIL , "Uf:" , NULL_STRING , "RHSEL_UF"}

	SELF:oDCSC_UF2 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_UF2  , _GetInst() } }
	SELF:oDCSC_UF2:HyperLabel := HyperLabel{#SC_UF2 , "Estado Civil" , NULL_STRING , NULL_STRING}

	SELF:oCCBTNcheckrg := PUSHBUTTON{SELF , ResourceID{ JFO_PES_BTNCHECKRG  , _GetInst() } }
	SELF:oCCBTNcheckrg:TooltipText := "Checar Numero Renavam"
	SELF:oCCBTNcheckrg:HyperLabel := HyperLabel{#BTNcheckrg , "Checar RG" , NULL_STRING , NULL_STRING}

	SELF:oCCcheckcPF := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CHECKCPF  , _GetInst() } }
	SELF:oCCcheckcPF:TooltipText := "Checar CPF"
	SELF:oCCcheckcPF:HyperLabel := HyperLabel{#checkcPF , "Checar CPF" , NULL_STRING , NULL_STRING}

	SELF:oDCcpf := rightSle{SELF , ResourceID{ JFO_PES_CPF  , _GetInst() } }
	SELF:oDCcpf:FieldSpec := padrao_char_14{}
	SELF:oDCcpf:TooltipText := "Digite o CPF"
	SELF:oDCcpf:Picture := "999.999.999-99"
	SELF:oDCcpf:HyperLabel := HyperLabel{#cpf , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCRG := rightSle{SELF , ResourceID{ JFO_PES_RG  , _GetInst() } }
	SELF:oDCRG:FieldSpec := PADRAO_CHAR_12{}
	SELF:oDCRG:TooltipText := "Digite o Numero RGCarteira de Identidade"
	SELF:oDCRG:HyperLabel := HyperLabel{#RG , "RG" , NULL_STRING , NULL_STRING}

	SELF:oCCescEXP := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCEXP  , _GetInst() } }
	SELF:oCCescEXP:Image := ICO_FIND{}
	SELF:oCCescEXP:HyperLabel := HyperLabel{#escEXP , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCescUF := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCUF  , _GetInst() } }
	SELF:oCCescUF:Image := ICO_FIND{}
	SELF:oCCescUF:HyperLabel := HyperLabel{#escUF , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCescCDEM := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCCDEM  , _GetInst() } }
	SELF:oCCescCDEM:Image := ICO_FIND{}
	SELF:oCCescCDEM:HyperLabel := HyperLabel{#escCDEM , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCOCOFGTS1 := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_OCOFGTS1  , _GetInst() } }
	SELF:oDCOCOFGTS1:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCOCOFGTS1:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCOCOFGTS1:Font( oFont )
	SELF:oDCOCOFGTS1:HyperLabel := HyperLabel{#OCOFGTS1 , "Htt:" , NULL_STRING , "FO_PES_HTT"}

	SELF:oCCcmdbco2 := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CMDBCO2  , _GetInst() } }
	SELF:oCCcmdbco2:HyperLabel := HyperLabel{#cmdbco2 , "Solteiro Casado Viuvo DesQuitado Divorciado Uniao estavel Outros seParado Marital" , NULL_STRING , NULL_STRING}

	SELF:oCCescCIVI := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCCIVI  , _GetInst() } }
	SELF:oCCescCIVI:Image := ICO_FIND{}
	SELF:oCCescCIVI:HyperLabel := HyperLabel{#escCIVI , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCescunid := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCUNID  , _GetInst() } }
	SELF:oCCescunid:Image := ICO_FIND{}
	SELF:oCCescunid:HyperLabel := HyperLabel{#escunid , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCescSITU := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCSITU  , _GetInst() } }
	SELF:oCCescSITU:Image := ICO_FIND{}
	SELF:oCCescSITU:HyperLabel := HyperLabel{#escSITU , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSITUACAO := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_SITUACAO  , _GetInst() } }
	SELF:oDCSITUACAO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCSITUACAO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	SELF:oDCSITUACAO:Font( oFont )
	SELF:oDCSITUACAO:HyperLabel := HyperLabel{#SITUACAO , NULL_STRING , NULL_STRING , "RHSEL_UF"}

	SELF:oDCSC_UF3 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_UF3  , _GetInst() } }
	SELF:oDCSC_UF3:HyperLabel := HyperLabel{#SC_UF3 , "Situacao" , NULL_STRING , NULL_STRING}

	SELF:oDCENDNUM := rightSle{SELF , ResourceID{ JFO_PES_ENDNUM  , _GetInst() } }
	SELF:oDCENDNUM:FieldSpec := PADRAO_char_10{}
	SELF:oDCENDNUM:HyperLabel := HyperLabel{#ENDNUM , "Chapa:" , NULL_STRING , "FO_PES_CHAPA"}

	SELF:oDCENDCOMPL := rightSle{SELF , ResourceID{ JFO_PES_ENDCOMPL  , _GetInst() } }
	SELF:oDCENDCOMPL:FieldSpec := PADRAO_char_30{}
	SELF:oDCENDCOMPL:HyperLabel := HyperLabel{#ENDCOMPL , "Chapa:" , NULL_STRING , "FO_PES_CHAPA"}

	SELF:oDCSC_SETOR1 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_SETOR1  , _GetInst() } }
	SELF:oDCSC_SETOR1:HyperLabel := HyperLabel{#SC_SETOR1 , "No." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CHAPA5 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_CHAPA5  , _GetInst() } }
	SELF:oDCSC_CHAPA5:HyperLabel := HyperLabel{#SC_CHAPA5 , "Compl" , NULL_STRING , NULL_STRING}

	SELF:oDCENDTIP := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_ENDTIP  , _GetInst() } }
	SELF:oDCENDTIP:FieldSpec := PADRAO_char_02{}
	SELF:oDCENDTIP:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	SELF:oDCENDTIP:Font( oFont )
	SELF:oDCENDTIP:HyperLabel := HyperLabel{#ENDTIP , "Uf:" , NULL_STRING , "RHSEL_UF"}

	SELF:oCCescLOG := PUSHBUTTON{SELF , ResourceID{ JFO_PES_ESCLOG  , _GetInst() } }
	SELF:oCCescLOG:Image := ICO_FIND{}
	SELF:oCCescLOG:HyperLabel := HyperLabel{#escLOG , ".." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ADMITIDO1 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_ADMITIDO1  , _GetInst() } }
	SELF:oDCSC_ADMITIDO1:HyperLabel := HyperLabel{#SC_ADMITIDO1 , "Transferencia" , NULL_STRING , NULL_STRING}

	SELF:oDCDATTRANSF := DateSle{SELF , ResourceID{ JFO_PES_DATTRANSF  , _GetInst() } }
	SELF:oDCDATTRANSF:FieldSpec := DATE_FIELD{}
	SELF:oDCDATTRANSF:HyperLabel := HyperLabel{#DATTRANSF , "Admitido:" , NULL_STRING , "FO_PES_ADMITIDO"}

	SELF:oDCNUMEMPANT := rightSle{SELF , ResourceID{ JFO_PES_NUMEMPANT  , _GetInst() } }
	SELF:oDCNUMEMPANT:FieldSpec := PADRAO_NUM_03{}
	SELF:oDCNUMEMPANT:HyperLabel := HyperLabel{#NUMEMPANT , "Dep" , NULL_STRING , "FO_PES_DEPTO"}

	SELF:oDCDEPTO2 := rightSle{SELF , ResourceID{ JFO_PES_DEPTO2  , _GetInst() } }
	SELF:oDCDEPTO2:FieldSpec := PADRAO_NUM_05{}
	SELF:oDCDEPTO2:HyperLabel := HyperLabel{#DEPTO2 , "NUMREGANT" , NULL_STRING , "FO_PES_DEPTO"}

	SELF:oDCPIS := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_PIS  , _GetInst() } }
	SELF:oDCPIS:FieldSpec := PADRAO_CHAR_11{}
	SELF:oDCPIS:HyperLabel := HyperLabel{#PIS , "Pis:" , NULL_STRING , "RHSEL_PIS"}

	SELF:oCCcheckPIS := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CHECKPIS  , _GetInst() } }
	SELF:oCCcheckPIS:TooltipText := "Checar PIS"
	SELF:oCCcheckPIS:HyperLabel := HyperLabel{#checkPIS , "PIS Checar" , NULL_STRING , NULL_STRING}

	SELF:oDCFixedText3 := Hyperlink{SELF , ResourceID{ JFO_PES_FIXEDTEXT3  , _GetInst() } }
	SELF:oDCFixedText3:HyperLabel := HyperLabel{#FixedText3 , "Qualificacao Cadastral duplo click mouse" , "www9.dataprev.gov.br/Esocial/pages/qualificacao/qualificar.xhtml" , NULL_STRING}

	SELF:oDCSERIE2 := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_SERIE2  , _GetInst() } }
	SELF:oDCSERIE2:FieldSpec := PADRAO_CHAR_03{}
	SELF:oDCSERIE2:HyperLabel := HyperLabel{#SERIE2 , "TITUSECA" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCFixedText8 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_FIXEDTEXT8  , _GetInst() } }
	SELF:oDCFixedText8:HyperLabel := HyperLabel{#FixedText8 , "Secao" , NULL_STRING , NULL_STRING}

	SELF:oDCTITUZONA := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_TITUZONA  , _GetInst() } }
	SELF:oDCTITUZONA:FieldSpec := PADRAO_CHAR_03{}
	SELF:oDCTITUZONA:HyperLabel := HyperLabel{#TITUZONA , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCFixedText7 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_FIXEDTEXT7  , _GetInst() } }
	SELF:oDCFixedText7:HyperLabel := HyperLabel{#FixedText7 , "Zona" , NULL_STRING , NULL_STRING}

	SELF:oDCTITULO := rightSle{SELF , ResourceID{ JFO_PES_TITULO  , _GetInst() } }
	SELF:oDCTITULO:FieldSpec := PADRAO_CHAR_14{}
	SELF:oDCTITULO:TooltipText := "Digite o Numero RGCarteira de Identidade"
	SELF:oDCTITULO:HyperLabel := HyperLabel{#TITULO , "TITULO" , NULL_STRING , NULL_STRING}

	SELF:oCCcheckTIT := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CHECKTIT  , _GetInst() } }
	SELF:oCCcheckTIT:TooltipText := "Checar Numero Renavam"
	SELF:oCCcheckTIT:HyperLabel := HyperLabel{#checkTIT , "Checar Titulo Eleitor" , NULL_STRING , NULL_STRING}

	SELF:oDCcns := rightSle{SELF , ResourceID{ JFO_PES_CNS  , _GetInst() } }
	SELF:oDCcns:FieldSpec := padrao_char_15{}
	SELF:oDCcns:TooltipText := "Digite o Pis"
	SELF:oDCcns:HyperLabel := HyperLabel{#cns , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCcheckcns := PUSHBUTTON{SELF , ResourceID{ JFO_PES_CHECKCNS  , _GetInst() } }
	SELF:oCCcheckcns:TooltipText := "Checar PIS"
	SELF:oCCcheckcns:HyperLabel := HyperLabel{#checkcns , "cns Checar" , NULL_STRING , NULL_STRING}

	SELF:oDCNASC := SINGLELINEEDIT{SELF , ResourceID{ JFO_PES_NASC  , _GetInst() } }
	SELF:oDCNASC:FieldSpec := DATE_FIELD{}
	SELF:oDCNASC:HyperLabel := HyperLabel{#NASC , "Fone:" , NULL_STRING , "RHSEL_FONE"}

	SELF:oDCSC_FONE1 := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_FONE1  , _GetInst() } }
	SELF:oDCSC_FONE1:HyperLabel := HyperLabel{#SC_FONE1 , "Nascimento" , NULL_STRING , NULL_STRING}

	SELF:oDCFixedText4 := Hyperlink{SELF , ResourceID{ JFO_PES_FIXEDTEXT4  , _GetInst() } }
	SELF:oDCFixedText4:HyperLabel := HyperLabel{#FixedText4 , "CNS portal duplo click mouse" , "https://portaldocidadao.saude.gov.br/portalcidadao/" , NULL_STRING}

	SELF:oDCSALADM := rightSle{SELF , ResourceID{ JFO_PES_SALADM  , _GetInst() } }
	SELF:oDCSALADM:FieldSpec := padrao_num_09_2{}
	SELF:oDCSALADM:HyperLabel := HyperLabel{#SALADM , "Valor" , NULL_STRING , "NFCC_VALOR"}

	SELF:oDCSC_VALOR := FIXEDTEXT{SELF , ResourceID{ JFO_PES_SC_VALOR  , _GetInst() } }
	SELF:oDCSC_VALOR:HyperLabel := HyperLabel{#SC_VALOR , "Salario Admissao:" , NULL_STRING , NULL_STRING}

	SELF:Caption := "Cadastro de Funcionarios"
	SELF:Menu := STANDARDSHELLMENU{}
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#JFO_PES , "Cadastro de Funcionarios" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBNUMERO := DataColumn{PADRAO_NUM_08{}}
	SELF:oDBNUMERO:Width := 8
	SELF:oDBNUMERO:HyperLabel := SELF:oDCNUMERO:HyperLabel
	SELF:oDBNUMERO:Caption := "Numero:"
	SELF:Browser:AddColumn(SELF:oDBNUMERO)

	SELF:oDBNOME := DataColumn{PADRAO_CHAR_60{}}
	SELF:oDBNOME:Width := 21
	SELF:oDBNOME:HyperLabel := SELF:oDCNOME:HyperLabel
	SELF:oDBNOME:Caption := "Nome:"
	SELF:Browser:AddColumn(SELF:oDBNOME)

	SELF:oDBDEPTO := DataColumn{PADRAO_NUM_04{}}
	SELF:oDBDEPTO:Width := 5
	SELF:oDBDEPTO:HyperLabel := SELF:oDCDEPTO:HyperLabel
	SELF:oDBDEPTO:Caption := "Dep"
	SELF:Browser:AddColumn(SELF:oDBDEPTO)

	SELF:oDBSETOR := DataColumn{PADRAO_NUM_04{}}
	SELF:oDBSETOR:Width := 6
	SELF:oDBSETOR:HyperLabel := SELF:oDCSETOR:HyperLabel
	SELF:oDBSETOR:Caption := "Set"
	SELF:Browser:AddColumn(SELF:oDBSETOR)

	SELF:oDBSECAO := DataColumn{PADRAO_NUM_04{}}
	SELF:oDBSECAO:Width := 6
	SELF:oDBSECAO:HyperLabel := SELF:oDCSECAO:HyperLabel
	SELF:oDBSECAO:Caption := "Sec"
	SELF:Browser:AddColumn(SELF:oDBSECAO)

	SELF:oDBADMITIDO := DataColumn{DATE_FIELD{}}
	SELF:oDBADMITIDO:Width := 10
	SELF:oDBADMITIDO:HyperLabel := SELF:oDCADMITIDO:HyperLabel
	SELF:oDBADMITIDO:Caption := "Admitido:"
	SELF:Browser:AddColumn(SELF:oDBADMITIDO)

	SELF:oDBDEMITIDO := DataColumn{DATE_FIELD{}}
	SELF:oDBDEMITIDO:Width := 10
	SELF:oDBDEMITIDO:HyperLabel := SELF:oDCDEMITIDO:HyperLabel
	SELF:oDBDEMITIDO:Caption := "Demitido:"
	SELF:Browser:AddColumn(SELF:oDBDEMITIDO)

	SELF:oDBHT := DataColumn{PADRAO_CHAR_40{}}
	SELF:oDBHT:Width := 4
	SELF:oDBHT:HyperLabel := SELF:oDCHT:HyperLabel
	SELF:oDBHT:Caption := "Ht:"
	SELF:Browser:AddColumn(SELF:oDBHT)

	SELF:ViewAs(#FormView)


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS INSALUBRI
RETURN SELF:FieldGet( #INSALUBRI )

ASSIGN INSALUBRI( uValue )
SELF:FieldPut( #INSALUBRI , uValue )

ACCESS MAE
RETURN SELF:FieldGet( #MAE )

ASSIGN MAE( uValue )
SELF:FieldPut( #MAE , uValue )

ACCESS MODIRETA
RETURN SELF:FieldGet( #MODIRETA )

ASSIGN MODIRETA( uValue )
SELF:FieldPut( #MODIRETA , uValue )

ACCESS NASC
RETURN SELF:FieldGet( #NASC )

ASSIGN NASC( uValue )
SELF:FieldPut( #NASC , uValue )

ACCESS NOME
RETURN SELF:FieldGet( #NOME )

ASSIGN NOME( uValue )
SELF:FieldPut( #NOME , uValue )

ACCESS NUMEMPANT
RETURN SELF:FieldGet( #NUMEMPANT )

ASSIGN NUMEMPANT( uValue )
SELF:FieldPut( #NUMEMPANT , uValue )

ACCESS NUMERO
RETURN SELF:FieldGet( #NUMERO )

ASSIGN NUMERO( uValue )
SELF:FieldPut( #NUMERO , uValue )

ACCESS OCOFGTS
RETURN SELF:FieldGet( #OCOFGTS )

ASSIGN OCOFGTS( uValue )
SELF:FieldPut( #OCOFGTS , uValue )

ACCESS OCOFGTS1
RETURN SELF:FieldGet( #OCOFGTS1 )

ASSIGN OCOFGTS1( uValue )
SELF:FieldPut( #OCOFGTS1 , uValue )

ACCESS PAI
RETURN SELF:FieldGet( #PAI )

ASSIGN PAI( uValue )
SELF:FieldPut( #PAI , uValue )

ACCESS PERICULO
RETURN SELF:FieldGet( #PERICULO )

ASSIGN PERICULO( uValue )
SELF:FieldPut( #PERICULO , uValue )

ACCESS PIS
RETURN SELF:FieldGet( #PIS )

ASSIGN PIS( uValue )
SELF:FieldPut( #PIS , uValue )

ACCESS RG
RETURN SELF:FieldGet( #RG )

ASSIGN RG( uValue )
SELF:FieldPut( #RG , uValue )

ACCESS SALADM
RETURN SELF:FieldGet( #SALADM )

ASSIGN SALADM( uValue )
SELF:FieldPut( #SALADM , uValue )

ACCESS SECAO
RETURN SELF:FieldGet( #SECAO )

ASSIGN SECAO( uValue )
SELF:FieldPut( #SECAO , uValue )

ACCESS SERIE2
RETURN SELF:FieldGet( #SERIE2 )

ASSIGN SERIE2( uValue )
SELF:FieldPut( #SERIE2 , uValue )

ACCESS SETOR
RETURN SELF:FieldGet( #SETOR )

ASSIGN SETOR( uValue )
SELF:FieldPut( #SETOR , uValue )

ACCESS SEXO
RETURN SELF:FieldGet( #SEXO )

ASSIGN SEXO( uValue )
SELF:FieldPut( #SEXO , uValue )

ACCESS SITUACAO
RETURN SELF:FieldGet( #SITUACAO )

ASSIGN SITUACAO( uValue )
SELF:FieldPut( #SITUACAO , uValue )

ACCESS TIPO
RETURN SELF:FieldGet( #TIPO )

ASSIGN TIPO( uValue )
SELF:FieldPut( #TIPO , uValue )

ACCESS TITULO
RETURN SELF:FieldGet( #TITULO )

ASSIGN TITULO( uValue )
SELF:FieldPut( #TITULO , uValue )

ACCESS TITUZONA
RETURN SELF:FieldGet( #TITUZONA )

ASSIGN TITUZONA( uValue )
SELF:FieldPut( #TITUZONA , uValue )

ACCESS UNIFUN
RETURN SELF:FieldGet( #UNIFUN )

ASSIGN UNIFUN( uValue )
SELF:FieldPut( #UNIFUN , uValue )

ACCESS VT
RETURN SELF:FieldGet( #VT )

ASSIGN VT( uValue )
SELF:FieldPut( #VT , uValue )

END CLASS
STATIC DEFINE JFO_PES_BTNCHECKRG := 169
