PARTIAL CLASS JFO_PMAN
METHOD APPEND 
SUPER:APPEND()
SELF:sERVER:FIELDPUT("DATOCO",Today()-1)	
SELF:SERVER:FIELDPUT("TIPOCO","T")

METHOD buscaNUM( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTFGRP("PTO","HOR")	


METHOD cmdordenar( ) 
	SELF:KeyFind()

METHOD cmdZER( ) 
SELF:server:FIELDPUT("ZERHOR",SIMNAO(SELF:SERVER:FIELDGET("ZERHOR")))	

METHOD delete 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
SELF:server:delete()
SELF:server:skip(-1)
IF SELF:sERVER:BOF
   SELF:SERVER:GOTOP()	
ENDIF		

METHOD escFUN( ) 
LOCAL oESC AS XESCNUM	
//LOCAL aFORN AS ARRAY
LOCAL oSERVER AS USEFOLHA
oSERVER:=USEFOLHA{"FO_PES"}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oESC:=XESCNUM{SELF,,1,oSERVER}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("NUMERO",oESC:NUMERO)
ENDIF

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
 FabCenterWindow( SELF )
 RETURN SELF

METHOD PushButton1( ) 
	SELF:server:FIELDPUT("TIPOCO",SIMNAO(SELF:SERVER:FIELDGET("TIPOCO"),{"S","N","1","2","T"}))

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
