PARTIAL CLASS JFO_PHOR
METHOD APPEND
LOCAL oJAN AS XDPHOR
LOCAL nORI AS DWORD
LOCAL dINI,dFIM AS DATE
LOCAL cOBS,cCOD AS STRING
oJAN:=XDPHOR{SELF}
oJAN:SHOW()	
IF ! OJAN:lOK
   RETURN .f.
ENDIF	
nORI:=Val(oJAN:VAL01)
cCOD:=oJAN:VAL03
cOBS:=oJAN:VAL04
dINI:=OjAN:dINI
dFIM:=oJAN:dFIM
IF Empty(nORI)
   alert("Numero Não Preenchido")
   RETURN .f.
ENDIF	
SELF:SERVER:GOTOP()
IF ! SELF:SERVER:SEEK(Str(nORI,8)+DToS(dINI))
   SUPER:APPEND()
   SELF:SERVER:FIELDPUT("NUMERO",nORI)
   SELF:SERVER:FIELDPUT("OCOINI",dINI)
   SELF:SERVER:FIELDPUT("OCOFIM",dFIM)
   SELF:SERVER:FIELDPUT("OCOCOD",cCOD)
   SELF:SERVER:FIELDPUT("OCOMOT",cOBS)	
ENDIF		

METHOD buscaNUM( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTFGRP("PTO","OCO")	


METHOD cmdordenar( ) 
	SELF:KeyFind()

METHOD delete 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
SELF:server:delete()
SELF:server:skip(-1)
IF SELF:sERVER:BOF
   SELF:SERVER:GOTOP()	
ENDIF		

METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"FOPTOHOR.DBF",SELF:SERVER:FIELDGET("OCOCOD")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("OCOCOD",oESC:CODIGO)
ENDIF				

METHOD escFUN( ) 
LOCAL oESC AS XESCNUM	
//LOCAL aFORN AS ARRAY
LOCAL oSERVER AS USEFOLHA
oSERVER:=USEFOLHA{"FO_PES"}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oESC:=XESCNUM{SELF,,1,oSERVER}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("NUMERO",oESC:NUMERO)
ENDIF

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
 FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
CLASS XDPHOR INHERIT DIAPAD
EXPORT lOK AS LOGIC	
EXPORT VAL01,VAL02,VAL03,VAL04

METHOD Cancelar( ) 
	LOK:=.F.
	SELF:EndWindow()

METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"FOPTOHOR.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:oDCcampo03:TEXTVALUE:=oESC:CODIGO
ENDIF				

CONSTRUCTOR(oOWNER) 
SUPER(oOWNER)
oDCtexto01:Caption:="Numero"
oDCtexto02:Caption:=""
oDCtexto03:Caption:="Horario"
odctexto04:Caption:="Obs/Motivo"
SELF:oDCcampo02:disable()
lOK:=.F.

METHOD OK( ) 
	LOCAL aRETU AS ARRAY
	lOK:=.T.
	aRETU:=pegcomp()
 	dINI:=ARETU[1]
    dFIM:=ARETU[2]
    VAL01:=ODCCAMPO01:TEXTVALUE
    VAL02:=ODCCAMPO02:TEXTVALUE
    VAL03:=ODCCAMPO03:TEXTVALUE
    VAL04:=ODCCAMPO04:TEXTVALUE
	SELF:EndWindow()


END CLASS
