PARTIAL CLASS Jfo_pon
METHOD APPEND() 
	alert("Operaçao Bloqueada")

METHOD buscaNUM( ) 
SELF:KeyFind()

METHOD cmdALM( ) 
SELF:server:FIELDPUT("ALMOCO",SIMNAO(SELF:SERVER:FIELDGET("ALMOCO"),{"A","B","C","D","E"," "}))	

METHOD cmdBCO( ) 
SELF:server:FIELDPUT("BCOSN",SIMNAO(SELF:SERVER:FIELDGET("BCOSN")))	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD cmdEXT( ) 
SELF:server:FIELDPUT("EXTSN",SIMNAO(SELF:SERVER:FIELDGET("EXTSN")))	

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD cmdFOL( ) 
SELF:server:FIELDPUT("FOLSN",SIMNAO(SELF:SERVER:FIELDGET("FOLSN")))	

METHOD CMDimprimir( ) 
SELF:XWRPTFGRP("PTO","")	


METHOD cmdordenar( ) 
	SELF:KeyFind()

METHOD cmdpas() 
LOCAL oJAN AS JESCREL
LOCAL oSERVER AS USEFOLHA
LOCAL cARQ,cPAS AS STRING
LOCAL nNUMERO AS DWORD
LOCAL dDATA AS DATE

nNUMERO:=SELF:SERVER:FIELDGET("NUMERO",8)
dDATA:=SELF:SERVER:FIELDGET("DATA")
oJAN:=JESCREL{SELF}
oJAN:SHOW()	
cARQ:=TARQREL(ZREL,.F.,"DIO")
oSERVER:=USEFOLHA{cARQ}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOTOP()
oSERVER:SEEK(Str(nNUMERO,8)+DToS(dDATA))
WHILE oSERVER:FIELDGET("NUMERO")=nNUMERO .AND. dDATA=oSERVER:FIELDGET("DATA") .AND. ! OSERVER:EoF
	cPAS+=StrZero(oSERVER:FIELDGET("HORA"),5,2)+"  "
	oSERVER:Skip()
ENDDO	
oSERVER:CLOSE()
IF Empty(cPAS)
   cPAS:="Sem Passagens"	
ENDIF	
alert(Cpas)

METHOD cmdRED( ) 
SELF:server:FIELDPUT("REDSN",SIMNAO(SELF:SERVER:FIELDGET("REDSN")))	

METHOD cmdVIR( ) 
SELF:server:FIELDPUT("VIRADA",SIMNAO(SELF:SERVER:FIELDGET("VIRADA")))	

METHOD DELETE() 
	alert("Operaçao Bloqueada")
	


METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"TABFALTA.DBF",SELF:SERVER:FIELDGET("COD")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("COD",oESC:CODIGO)
ENDIF				

METHOD ESCHOR( ) 
LOCAL oESC AS XESCCOD	
LOCAL aRETU AS ARRAY
oESC:=XESCCOD{SELF,"FOPTOHOR.DBF",SELF:SERVER:FIELDGET("CODREV")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("CODREV",oESC:CODIGO)
ENDIF				

aRETU:=PEGPTOHOR(SELF:SERVER:FIELDGET("CODREV"))
IF aRETU[6]=.T.
   SELF:SERVER:FIELDPUT("ENTREV",aRETU[1])	
   SELF:SERVER:FIELDPUT("ALIREV",aRETU[2])	
   SELF:SERVER:FIELDPUT("ALSREV",aRETU[3])	
   SELF:SERVER:FIELDPUT("SAIREV",aRETU[4])	
   SELF:SERVER:FIELDPUT("VIRADA",aRETU[5])	
ENDIF

METHOD ESCSUB( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"TABFALTA.DBF",SELF:SERVER:FIELDGET("SOD")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("SOD",oESC:CODIGO)
ENDIF					

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
 FabCenterWindow( SELF )
 RETURN SELF

METHOD PushButton12( ) 
//LOCAL oJAN AS JESCREL
LOCAL nNUMERO AS DWORD
LOCAL dDATA AS DATE
LOCAL cTMP AS STRING
LOCAL cPAS AS STRING
LOCAL cSQL AS STRING
LOCAL oCONN AS SQLConnection
LOCAL oSERVER AS SQLSelect

nNUMERO:=SELF:SERVER:FIELDGET("NUMERO",8)
dDATA:=SELF:SERVER:FIELDGET("DATA")


csql:="SELECT convert(varchar,mov_datahora,108) AS hora,"
csql+="       convert(VARCHAR(4),EQPI_NUMERO) AS RELOGIO"
csql+=" FROM Log_Credencial"
csql+=" WHERE MOV_DataHora>=convert(datetime, '"+DToC(dDATA)+"', 103)"
csql+="   AND MOV_DataHora<=convert(datetime, '"+DToC(dDATA+1)+"', 103)"
//csql+="     MOV_DataHora>='"+DToC(dDATA)+"'"
//csql+=" AND MOV_DataHora<'"+DToC(dDATA+1)+"'"
csql+=" AND PES_NUMERO="+Str(nNUMERO)


oConn := SQLConnection{}
 IF ! oConn:connect("wrel","","")
	  alert("Erro na Conecção")
 	  RETU SELF
ENDIF

oServer := SQLSelect{cSQL, oConn }
IF ! oServer:Execute()
   MemoWrit("C:\TEMP\cSQL.TXT",cSQL)
   alert("Erro na Consulta")
   RETU SELF
ENDIF	

WHILE ! OSERVER:EoF
	cTMP:=SubStr(oSERVER:FIELDGET("HORA"),1,5)+"/"+Trim(oSERVER:FIELDGET("RELOGIO"))
	IF At(cTMP,cPAS)=0
   	   cPAS+=cTMP+" "
   	ENDIF
	oSERVER:Skip()
ENDDO	
oSERVER:CLOSE()
IF Empty(cPAS)
   cPAS:="Sem Passagens"	
ENDIF	
alert(Cpas)	

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
