PARTIAL CLASS jfo_relhr
METHOD append 
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Incluir Funcionário","Digite Nº Funcionário"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   IF SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
   	  alert("Conta Ja cadastrada")
   ELSE
   	  SUPER:append()
   	  SELF:server:FIELDPUT("NUMERO",Val(oBUSCA:cBUSCA))
   	  SELF:PEGNOME()
   ENDIF	
ENDIF		

METHOD buscaNUM( ) 
SELF:KeyFind()

METHOD cmdALM( ) 
SELF:server:FIELDPUT("ALMoco",SIMNAO(SELF:SERVER:FIELDGET("ALMOCO"),{"A","B","C","D","E"," "}))	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD cmdESC( ) 
SELF:server:FIELDPUT("HFOL00",SIMNAO(SELF:SERVER:FIELDGET("HFOL00")))	

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTFGRP("PTO","HOR")	


METHOD cmdini( ) 
SELF:server:FIELDPUT("MARMES",SIMNAO(SELF:SERVER:FIELDGET("MARMES")))	

METHOD cmdMARALM( ) 
SELF:server:FIELDPUT("MARALM",SIMNAO(SELF:SERVER:FIELDGET("MARALM")))	

METHOD delete 
alert("Operacao Bloqueada")
		

METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
LOCAL oSERVER AS USEFOLHA
IF SELF:server:FIELDGET("HFOL00")<>"N"
   alert("Nao e horario fixo Semanal")
   RETURN SELF	
ENDIF	
oSERVER:=USEFOLHA{"FOPTOHRE"}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oESC:=XESCCOD{SELF,,SELF:SERVER:FIELDGET("HORREF"),1,oSERVER}
oESC:SHOW()	
IF ! Oesc:lok
   RETU SELF
ENDIF	
SELF:SERVER:FIELDPUT("HORREF",oESC:CODIGO)

METHOD escFUN( ) 
LOCAL oESC AS XESCNUM	
//LOCAL aFORN AS ARRAY
LOCAL oSERVER AS USEFOLHA
oSERVER:=USEFOLHA{"FO_PES"}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oESC:=XESCNUM{SELF,,1,oSERVER}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("NUMERO",oESC:NUMERO)
    SELF:server:FIELDPUT("nome",Oesc:nome)
ENDIF

METHOD pegnome 
LOCAL oSERVER AS USEFOLHA
oSERVER:=USEFOLHA{"FO_PES"}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOTOP()
IF oSERVEr:SEEK(SELF:SERVER:FIELDGET("NUMERO"))
   SELF:SERVER:FIELDPUT("NOME",oSERVEr:FIELDGET("NOME"))
ENDIF
oSERVER:CLOSE()	
	
	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
 FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
