PARTIAL CLASS JPtoEve
METHOD buscaNUM( ) 
	SELF:KeyFind()

METHOD cmdBCO( ) 
SELF:server:FIELDPUT("BCOSN",SIMNAO(SELF:SERVER:FIELDGET("BCOSN")))	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDDMAI 
IF Empty(SELF:SERVER:FIELDGET("MES"))
  SELF:SERVER:FIELDPUT("DIA",INCDEC(SELF:SERVER:FIELDGET("DIA"),1,1,7))	
ELSE	
  SELF:SERVER:FIELDPUT("DIA",INCDEC(SELF:SERVER:FIELDGET("DIA"),1,1,31))
ENDIF
SELF:SERVER:FIELDPUT("DIA",INCDEC(SELF:SERVER:FIELDGET("DIA"),1,1,31))

METHOD CMDDMEN 
IF Empty(SELF:SERVER:FIELDGET("MES"))
  SELF:SERVER:FIELDPUT("DIA",INCDEC(SELF:SERVER:FIELDGET("DIA"),-1,1,7))	
ELSE	
  SELF:SERVER:FIELDPUT("DIA",INCDEC(SELF:SERVER:FIELDGET("DIA"),-1,1,31))
ENDIF

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD cmdFOL( ) 
SELF:server:FIELDPUT("FOLSN",SIMNAO(SELF:SERVER:FIELDGET("FOLSN")))	

METHOD CMDimprimir( ) 
SELF:XWRPTFGRP("PTO","TAB")	


METHOD CMDMAIS 
SELF:SERVER:FIELDPUT("MES",INCDEC(SELF:SERVER:FIELDGET("MES"),1,0,12))

METHOD cmdmenos( ) 
SELF:SERVER:FIELDPUT("MES",INCDEC(SELF:SERVER:FIELDGET("MES"),-1,0,12))	

METHOD cmdordenar( ) 
	SELF:KeyFind()

METHOD cmdRED( ) 
SELF:server:FIELDPUT("REDSN",SIMNAO(SELF:SERVER:FIELDGET("REDSN")))	

METHOD delete 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
SELF:server:delete()
SELF:server:skip(-1)
IF SELF:sERVER:BOF
   SELF:SERVER:GOTOP()	
ENDIF		

METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"TABFALTA.DBF",SELF:SERVER:FIELDGET("CODIGO")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
ENDIF				

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
 FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
