PARTIAL CLASS jptohor
METHOD append 	
LOCAL oBUSCA AS XBUSCA
LOCAL nNUMERO AS DWORD
oBUSCA:=XBUSCA{SELF,"Localizar Codigo","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(2)
   SELF:SERVER:GOTOP()
   IF SELF:SERVER:SEEK(oBUSCA:cBUSCA)
   	  alert("Conta Ja cadastrada")
   ELSE
      SELF:SERVER:SETORDER(1)
      SELF:SERVER:GOBOTTOM()
      nNUMERO:=SELF:SERVER:FIELDGET("NUMERO")
      nNUMERO++
   	  SUPER:append()
   	  SELF:server:FIELDPUT("CODIGO",oBUSCA:cBUSCA)
   	  SELF:server:FIELDPUT("NUMERO",nNUMERO)
   ENDIF	
ENDIF		

METHOD buscaNUM( ) 
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Localizar Codigo","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(oBUSCA:cBUSCA)
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTFGRP("PTO","HOR")	


METHOD cmdordenar( ) 
	SELF:KeyFind()

METHOD cmdVIR( ) 
SELF:server:FIELDPUT("VIRADA",SIMNAO(SELF:SERVER:FIELDGET("VIRADA")))	

METHOD delete 
alert("Operacao Bloqueada")	


METHOD pegdes( ) 
LOCAL cDIZ AS STRING
cDIZ:=Str(SELF:SERVER:FIELDGET("ENT"),5,2)+" "
IF ! Empty(SELF:SERVER:FIELDGET("ALMI"))
   cDIZ+=Str(SELF:SERVER:FIELDGET("ALMI"),5,2)+" "
   cDIZ+=Str(SELF:SERVER:FIELDGET("ALMF"),5,2)+" "
ENDIF
cDIZ+=Str(SELF:SERVER:FIELDGET("SAI"),5,2)	
SELF:serveR:FIELDPUT("NOME",cDIZ)	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
