PARTIAL CLASS JFOPTO_REV
METHOD APPEND
LOCAL oJAN AS XDPREV
LOCAL X
LOCAL dINI,dFIM AS DATE
LOCAL cCOD,cGRP AS STRING
LOCAL aRETU AS ARRAY

oJAN:=XDPREV{SELF}
oJAN:SHOW()	
IF ! OJAN:lOK
   RETURN .f.
ENDIF	
cGRP:=Left(oJAN:VAL02,2)
cCOD:=Left(oJAN:VAL03,2)
dINI:=OjAN:dINI
dFIM:=oJAN:dFIM
IF Empty(cCOD)
   alert("Codigo Não Preenchido")
   RETURN .f.
ENDIF	
aRETU:=PEGPTOHOR(cCOD)
FOR X:= dINI TO DfIM
  SELF:SERVER:GOTOP()
  IF ! SELF:SERVER:SEEK(cGRP+DToS(X))
     SUPER:APPEND()
     SELF:SERVER:FIELDPUT("GRUPO",cGRP)
     SELF:SERVER:FIELDPUT("CODREV",cCOD)
     SELF:SERVER:FIELDPUT("DATA",X)
     IF aRETU[6]=.T.
   		SELF:SERVER:FIELDPUT("ENTREV",aRETU[1])	
	    SELF:SERVER:FIELDPUT("ALIREV",aRETU[2])	
	    SELF:SERVER:FIELDPUT("ALSREV",aRETU[3])	
	    SELF:SERVER:FIELDPUT("SAIREV",aRETU[4])	
	    SELF:SERVER:FIELDPUT("VIRADA",aRETU[5])	
     ENDIF
  ENDIF		
NEXT X

METHOD buscaNUM( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD cmdDO( ) 
	SELF:SERVER:FIELDPUT("CODREV","DO")
	SELF:CMDZERAR()

METHOD cmdDO1( ) 
	SELF:SERVER:FIELDPUT("CODREV","FE")
	SELF:CMDZERAR()	

METHOD cmdDO2( ) 
	SELF:SERVER:FIELDPUT("CODREV","SA")
	SELF:CMDZERAR()	

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD cmdFO( ) 
	SELF:SERVER:FIELDPUT("CODREV","FO")
	SELF:CMDZERAR()	

METHOD cmdfol( ) 
	SELF:server:FIELDPUT("FOLGASN",SIMNAO(SELF:SERVER:FIELDGET("FOLSN")))	

METHOD CMDimprimir( ) 
SELF:XWRPTFGRP("PTO","ESC")	


METHOD cmdordenar( ) 
	SELF:KeyFind()

METHOD cmdVIR( ) 
SELF:server:FIELDPUT("VIRADA",SIMNAO(SELF:SERVER:FIELDGET("VIRADA")))	

METHOD cmdzerar() 
SELF:Server:FIELDPUT("ENTREV",0)
SELF:Server:FIELDPUT("ALIREV",0)
SELF:Server:FIELDPUT("ALSREV",0)
SELF:Server:FIELDPUT("SAIREV",0)	

METHOD delete 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
SELF:server:delete()
SELF:server:skip(-1)
IF SELF:sERVER:BOF
   SELF:SERVER:GOTOP()	
ENDIF		

METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"TABFALTA.DBF"}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("CODREV",oESC:CODIGO)
ENDIF				

METHOD ESChor( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"FOPTOHOR.DBF"}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("CODREV",oESC:CODIGO)
   SELF:PEGHOR()
ENDIF				


METHOD PEGHOR 
LOCAL aRETU AS ARRAY
aRETU:=PEGPTOHOR(SELF:SERVER:FIELDGET("CODREV"))
IF aRETU[6]=.T.
   SELF:SERVER:FIELDPUT("ENTREV",aRETU[1])	
   SELF:SERVER:FIELDPUT("ALIREV",aRETU[2])	
   SELF:SERVER:FIELDPUT("ALSREV",aRETU[3])	
   SELF:SERVER:FIELDPUT("SAIREV",aRETU[4])	
   SELF:SERVER:FIELDPUT("VIRADA",aRETU[5])	
ENDIF

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
CLASS XDPREV INHERIT DIAPAD
EXPORT lOK AS LOGIC	
EXPORT VAL01,VAL02,VAL03,VAL04

METHOD Cancelar( ) 
	LOK:=.F.
	SELF:EndWindow()

METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"FOPTOHOR.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:oDCcampo03:TEXTVALUE:=oESC:CODIGO
ENDIF				

CONSTRUCTOR(oOWNER) 
SUPER(oOWNER)
oDCtexto01:Caption:=""
oDCtexto02:Caption:="Escala"
oDCtexto03:Caption:="Horario"
odctexto04:Caption:=""
SELF:oDCcampo01:disable()
SELF:oDCcampo04:disable()
lOK:=.F.

METHOD OK( ) 
	LOCAL aRETU AS ARRAY
	lOK:=.T.
	aRETU:=pegcomp()
 	dINI:=ARETU[1]
    dFIM:=ARETU[2]
    VAL01:=ODCCAMPO01:TEXTVALUE
    VAL02:=ODCCAMPO02:TEXTVALUE
    VAL03:=ODCCAMPO03:TEXTVALUE
    VAL04:=ODCCAMPO04:TEXTVALUE
	SELF:EndWindow()


END CLASS
