#region DEFINES
STATIC DEFINE JLC_BUSC03 := 126
STATIC DEFINE JLC_BUSCA := 103
STATIC DEFINE JLC_BUSCA01 := 118
STATIC DEFINE JLC_BUSCA02 := 121
STATIC DEFINE JLC_CDOCUMENTO := 120
STATIC DEFINE JLC_CMDHOJE01 := 102 
STATIC DEFINE JLC_CNOVODOC := 123
STATIC DEFINE JLC_CNUMERO := 127
STATIC DEFINE JLC_CTIPO := 125
STATIC DEFINE JLC_DATA := 109
STATIC DEFINE JLC_DOCUMENTO := 106
STATIC DEFINE JLC_GBOX := 128
STATIC DEFINE JLC_NOVODATA := 115
STATIC DEFINE JLC_NOVODOC := 114
STATIC DEFINE JLC_NUMCOMP := 108
STATIC DEFINE JLC_NUMERO := 107
STATIC DEFINE JLC_ORDEM := 102
STATIC DEFINE JLC_PASTA := 117
STATIC DEFINE JLC_SC_DATA := 105
STATIC DEFINE JLC_SC_DOCUMENTO := 100
STATIC DEFINE JLC_SC_NOVODATA := 111
STATIC DEFINE JLC_SC_NOVODOC := 110
STATIC DEFINE JLC_THEFIXEDTEXT10 := 116
STATIC DEFINE JLC_THEFIXEDTEXT4 := 119
STATIC DEFINE JLC_THEFIXEDTEXT5 := 122
STATIC DEFINE JLC_THEFIXEDTEXT6 := 101
STATIC DEFINE JLC_THEFIXEDTEXT7 := 124
STATIC DEFINE JLC_THEFIXEDTEXT8 := 112
STATIC DEFINE JLC_THEFIXEDTEXT9 := 104
STATIC DEFINE JLC_TIPO := 113
#endregion

PARTIAL CLASS JLC INHERIT MYDataWindow
PROTECT oDBDOCUMENTO AS DataColumn
PROTECT oDBNUMERO AS DataColumn
PROTECT oDBNUMCOMP AS DataColumn
PROTECT oDBDATA AS DataColumn
PROTECT oDBNOVODOC AS DataColumn
PROTECT oDBNOVODATA AS DataColumn
PROTECT oDCSC_DOCUMENTO AS FIXEDTEXT
PROTECT oDCtheFixedText6 AS FIXEDTEXT
PROTECT oCCordem AS PUSHBUTTON
PROTECT oCCbusca AS PUSHBUTTON
PROTECT oDCtheFixedText9 AS FIXEDTEXT
PROTECT oDCSC_DATA AS FIXEDTEXT
PROTECT oDCDOCUMENTO AS SINGLELINEEDIT
PROTECT oDCNUMERO AS SINGLELINEEDIT
PROTECT oDCNUMCOMP AS SINGLELINEEDIT
PROTECT oDCDATA AS SINGLELINEEDIT
PROTECT oDCSC_NOVODOC AS FIXEDTEXT
PROTECT oDCSC_NOVODATA AS FIXEDTEXT
PROTECT oDCtheFixedText8 AS FIXEDTEXT
PROTECT oDCTIPO AS COMBOBOX
PROTECT oDCNOVODOC AS SINGLELINEEDIT
PROTECT oDCNOVODATA AS SINGLELINEEDIT
PROTECT oDCtheFixedText10 AS FIXEDTEXT
PROTECT oDCPASTA AS SINGLELINEEDIT
PROTECT oCCBusca01 AS PUSHBUTTON
PROTECT oDCtheFixedText4 AS FIXEDTEXT
PROTECT oDCcDOCUMENTO AS SINGLELINEEDIT
PROTECT oCCBusca02 AS PUSHBUTTON
PROTECT oDCtheFixedText5 AS FIXEDTEXT
PROTECT oDCcNOVODOC AS SINGLELINEEDIT
PROTECT oDCtheFixedText7 AS FIXEDTEXT
PROTECT oDCcTIPO AS COMBOBOX
PROTECT oCCBUSC03 AS PUSHBUTTON
PROTECT oDCcNUMERO AS SINGLELINEEDIT
PROTECT oDCGBox AS GROUPBOX

// User code starts here (DO NOT remove this line)  ##USER##

METHOD BUSC03() 
LOCAL cBUSCA AS STRING
cBUSCA:=SELF:ODCCTIPO:VALUE+Str(cNUMERO,20)
SELF:server:setorder(3)
SELF:server:gotop()
SELF:server:seek(cBUSCA)
IF SELF:server:eof
    SELF:server:gotop()
ENDIF


METHOD busca( ) 
	SELF:KeyFind()

METHOD Busca01() 
SELF:server:setorder(1)
SELF:server:gotop()
SELF:server:seek(cDOCUMENTO)
IF SELF:server:eof
    SELF:server:gotop()
ENDIF

METHOD Busca02() 
SELF:server:setorder(2)
SELF:server:gotop()
SELF:server:seek(cNOVODOC)
IF SELF:server:eof
    SELF:server:gotop()
ENDIF


ACCESS cDOCUMENTO
RETURN SELF:FieldGet( #cDOCUMENTO )

ASSIGN cDOCUMENTO( uValue )
SELF:FieldPut( #cDOCUMENTO , uValue )

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("EN","")	


ACCESS cNOVODOC
RETURN SELF:FieldGet( #cNOVODOC )

ASSIGN cNOVODOC( uValue )
SELF:FieldPut( #cNOVODOC , uValue )

ACCESS cNUMERO
RETURN SELF:FieldGet( #cNUMERO )

ASSIGN cNUMERO( uValue )
SELF:FieldPut( #cNUMERO , uValue )

ACCESS cTIPO
RETURN SELF:FieldGet( #cTIPO )

ASSIGN cTIPO( uValue )
SELF:FieldPut( #cTIPO , uValue )

ACCESS DATA
RETURN SELF:FieldGet( #DATA )

ASSIGN DATA( uValue )
SELF:FieldPut( #DATA , uValue )

ACCESS DOCUMENTO
RETURN SELF:FieldGet( #DOCUMENTO )

ASSIGN DOCUMENTO( uValue )
SELF:FieldPut( #DOCUMENTO , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JLC" , _GetInst()},iCtlID)

	SELF:oDCSC_DOCUMENTO := FIXEDTEXT{SELF , ResourceID{ JLC_SC_DOCUMENTO  , _GetInst() } }
	SELF:oDCSC_DOCUMENTO:HyperLabel := HyperLabel{#SC_DOCUMENTO , "Documento:" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText6 := FIXEDTEXT{SELF , ResourceID{ JLC_THEFIXEDTEXT6  , _GetInst() } }
	SELF:oDCtheFixedText6:HyperLabel := HyperLabel{#theFixedText6 , "Numero" , NULL_STRING , NULL_STRING}

	SELF:oCCordem := PUSHBUTTON{SELF , ResourceID{ JLC_ORDEM  , _GetInst() } }
	SELF:oCCordem:TooltipText := "Ordenar Por Numero"
	SELF:oCCordem:Image := ico_az{}
	SELF:oCCordem:HyperLabel := HyperLabel{#ordem , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbusca := PUSHBUTTON{SELF , ResourceID{ JLC_BUSCA  , _GetInst() } }
	SELF:oCCbusca:Image := ICO_FIND{}
	SELF:oCCbusca:HyperLabel := HyperLabel{#busca , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText9 := FIXEDTEXT{SELF , ResourceID{ JLC_THEFIXEDTEXT9  , _GetInst() } }
	SELF:oDCtheFixedText9:HyperLabel := HyperLabel{#theFixedText9 , "Comp." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATA := FIXEDTEXT{SELF , ResourceID{ JLC_SC_DATA  , _GetInst() } }
	SELF:oDCSC_DATA:HyperLabel := HyperLabel{#SC_DATA , "Data:" , NULL_STRING , NULL_STRING}

	SELF:oDCDOCUMENTO := SINGLELINEEDIT{SELF , ResourceID{ JLC_DOCUMENTO  , _GetInst() } }
	SELF:oDCDOCUMENTO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCDOCUMENTO:TooltipText := "Numero do Documento"
	SELF:oDCDOCUMENTO:HyperLabel := HyperLabel{#DOCUMENTO , "Documento:" , NULL_STRING , "LC_DOCUMENTO"}

	SELF:oDCNUMERO := SINGLELINEEDIT{SELF , ResourceID{ JLC_NUMERO  , _GetInst() } }
	SELF:oDCNUMERO:FieldSpec := PADRAO_NUM_10{}
	SELF:oDCNUMERO:TooltipText := "Numero "
	SELF:oDCNUMERO:HyperLabel := HyperLabel{#NUMERO , "Numero:" , NULL_STRING , "LC_DOCUMENTO"}

	SELF:oDCNUMCOMP := SINGLELINEEDIT{SELF , ResourceID{ JLC_NUMCOMP  , _GetInst() } }
	SELF:oDCNUMCOMP:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCNUMCOMP:TooltipText := "Complemento"
	SELF:oDCNUMCOMP:HyperLabel := HyperLabel{#NUMCOMP , "Comp" , NULL_STRING , "LC_DOCUMENTO"}

	SELF:oDCDATA := SINGLELINEEDIT{SELF , ResourceID{ JLC_DATA  , _GetInst() } }
	SELF:oDCDATA:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCDATA:TooltipText := "Data"
	SELF:oDCDATA:HyperLabel := HyperLabel{#DATA , "Data:" , NULL_STRING , "LC_DATA"}

	SELF:oDCSC_NOVODOC := FIXEDTEXT{SELF , ResourceID{ JLC_SC_NOVODOC  , _GetInst() } }
	SELF:oDCSC_NOVODOC:HyperLabel := HyperLabel{#SC_NOVODOC , "Substituição/Atualização" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOVODATA := FIXEDTEXT{SELF , ResourceID{ JLC_SC_NOVODATA  , _GetInst() } }
	SELF:oDCSC_NOVODATA:HyperLabel := HyperLabel{#SC_NOVODATA , "Data" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText8 := FIXEDTEXT{SELF , ResourceID{ JLC_THEFIXEDTEXT8  , _GetInst() } }
	SELF:oDCtheFixedText8:HyperLabel := HyperLabel{#theFixedText8 , "Tipo" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPO := COMBOBOX{SELF , ResourceID{ JLC_TIPO  , _GetInst() } }
	SELF:oDCTIPO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCTIPO:TooltipText := "Tipo de Norma"
	SELF:oDCTIPO:HyperLabel := HyperLabel{#TIPO , "Tipo" , NULL_STRING , NULL_STRING}

	SELF:oDCNOVODOC := SINGLELINEEDIT{SELF , ResourceID{ JLC_NOVODOC  , _GetInst() } }
	SELF:oDCNOVODOC:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCNOVODOC:TooltipText := "Substituição/Atualizacao"
	SELF:oDCNOVODOC:HyperLabel := HyperLabel{#NOVODOC , "Sub/Alt" , NULL_STRING , "LC_NOVODOC"}

	SELF:oDCNOVODATA := SINGLELINEEDIT{SELF , ResourceID{ JLC_NOVODATA  , _GetInst() } }
	SELF:oDCNOVODATA:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCNOVODATA:TooltipText := "Data Sub/Alt"
	SELF:oDCNOVODATA:HyperLabel := HyperLabel{#NOVODATA , "Data" , NULL_STRING , "LC_NOVODATA"}

	SELF:oDCtheFixedText10 := FIXEDTEXT{SELF , ResourceID{ JLC_THEFIXEDTEXT10  , _GetInst() } }
	SELF:oDCtheFixedText10:HyperLabel := HyperLabel{#theFixedText10 , "Pasta" , NULL_STRING , NULL_STRING}

	SELF:oDCPASTA := SINGLELINEEDIT{SELF , ResourceID{ JLC_PASTA  , _GetInst() } }
	SELF:oDCPASTA:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCPASTA:TooltipText := "Pasta"
	SELF:oDCPASTA:HyperLabel := HyperLabel{#PASTA , "Numero:" , NULL_STRING , "LC_DOCUMENTO"}

	SELF:oCCBusca01 := PUSHBUTTON{SELF , ResourceID{ JLC_BUSCA01  , _GetInst() } }
	SELF:oCCBusca01:TooltipText := "Clique para Busca o Documento"
	SELF:oCCBusca01:HyperLabel := HyperLabel{#Busca01 , "Busca" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText4 := FIXEDTEXT{SELF , ResourceID{ JLC_THEFIXEDTEXT4  , _GetInst() } }
	SELF:oDCtheFixedText4:HyperLabel := HyperLabel{#theFixedText4 , "Documento:" , NULL_STRING , NULL_STRING}

	SELF:oDCcDOCUMENTO := SINGLELINEEDIT{SELF , ResourceID{ JLC_CDOCUMENTO  , _GetInst() } }
	SELF:oDCcDOCUMENTO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCcDOCUMENTO:TooltipText := "Digite o Codigo do Documento Para Busca"
	SELF:oDCcDOCUMENTO:HyperLabel := HyperLabel{#cDOCUMENTO , "Documento:" , NULL_STRING , "LC_DOCUMENTO"}

	SELF:oCCBusca02 := PUSHBUTTON{SELF , ResourceID{ JLC_BUSCA02  , _GetInst() } }
	SELF:oCCBusca02:TooltipText := "Clique para Buscar Sub/Atual"
	SELF:oCCBusca02:HyperLabel := HyperLabel{#Busca02 , "Busca" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText5 := FIXEDTEXT{SELF , ResourceID{ JLC_THEFIXEDTEXT5  , _GetInst() } }
	SELF:oDCtheFixedText5:HyperLabel := HyperLabel{#theFixedText5 , "Sub./Atual." , NULL_STRING , NULL_STRING}

	SELF:oDCcNOVODOC := SINGLELINEEDIT{SELF , ResourceID{ JLC_CNOVODOC  , _GetInst() } }
	SELF:oDCcNOVODOC:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCcNOVODOC:TooltipText := "Digite  A Sub/Atualização Para Busca"
	SELF:oDCcNOVODOC:HyperLabel := HyperLabel{#cNOVODOC , "Novodoc:" , NULL_STRING , "LC_NOVODOC"}

	SELF:oDCtheFixedText7 := FIXEDTEXT{SELF , ResourceID{ JLC_THEFIXEDTEXT7  , _GetInst() } }
	SELF:oDCtheFixedText7:HyperLabel := HyperLabel{#theFixedText7 , "Numero" , NULL_STRING , NULL_STRING}

	SELF:oDCcTIPO := COMBOBOX{SELF , ResourceID{ JLC_CTIPO  , _GetInst() } }
	SELF:oDCcTIPO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCcTIPO:TooltipText := "Digite O Tipo Para Busca"
	SELF:oDCcTIPO:HyperLabel := HyperLabel{#cTIPO , "Tipo" , NULL_STRING , NULL_STRING}

	SELF:oCCBUSC03 := PUSHBUTTON{SELF , ResourceID{ JLC_BUSC03  , _GetInst() } }
	SELF:oCCBUSC03:TooltipText := "Clique Para Busca Numero/tipo"
	SELF:oCCBUSC03:HyperLabel := HyperLabel{#BUSC03 , "Busca" , NULL_STRING , NULL_STRING}

	SELF:oDCcNUMERO := SINGLELINEEDIT{SELF , ResourceID{ JLC_CNUMERO  , _GetInst() } }
	SELF:oDCcNUMERO:FieldSpec := PADRAO_NUM_10{}
	SELF:oDCcNUMERO:TooltipText := "Digite o Numero"
	SELF:oDCcNUMERO:HyperLabel := HyperLabel{#cNUMERO , "Documento:" , NULL_STRING , "LC_DOCUMENTO"}

	SELF:oDCGBox := GROUPBOX{SELF , ResourceID{ JLC_GBOX  , _GetInst() } }
	SELF:oDCGBox:HyperLabel := HyperLabel{#GBox , "Busca" , NULL_STRING , NULL_STRING}

	SELF:Caption := "Controle de Normas"
	SELF:Menu := STANDARDSHELLMENU{}
	SELF:HyperLabel := HyperLabel{#JLC , "Controle de Normas" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBDOCUMENTO := DataColumn{PADRAO_CHAR_20{}}
	SELF:oDBDOCUMENTO:Width := 11
	SELF:oDBDOCUMENTO:HyperLabel := SELF:oDCDOCUMENTO:HyperLabel
	SELF:oDBDOCUMENTO:Caption := "Documento:"
	SELF:Browser:AddColumn(SELF:oDBDOCUMENTO)

	SELF:oDBNUMERO := DataColumn{PADRAO_NUM_10{}}
	SELF:oDBNUMERO:Width := 14
	SELF:oDBNUMERO:HyperLabel := SELF:oDCNUMERO:HyperLabel
	SELF:oDBNUMERO:Caption := "Numero:"
	SELF:Browser:AddColumn(SELF:oDBNUMERO)

	SELF:oDBNUMCOMP := DataColumn{PADRAO_CHAR_10{}}
	SELF:oDBNUMCOMP:Width := 13
	SELF:oDBNUMCOMP:HyperLabel := SELF:oDCNUMCOMP:HyperLabel
	SELF:oDBNUMCOMP:Caption := "Comp"
	SELF:Browser:AddColumn(SELF:oDBNUMCOMP)

	SELF:oDBDATA := DataColumn{PADRAO_CHAR_10{}}
	SELF:oDBDATA:Width := 11
	SELF:oDBDATA:HyperLabel := SELF:oDCDATA:HyperLabel
	SELF:oDBDATA:Caption := "Data:"
	SELF:Browser:AddColumn(SELF:oDBDATA)

	SELF:oDBNOVODOC := DataColumn{PADRAO_CHAR_40{}}
	SELF:oDBNOVODOC:Width := 18
	SELF:oDBNOVODOC:HyperLabel := SELF:oDCNOVODOC:HyperLabel
	SELF:oDBNOVODOC:Caption := "Sub/Alt"
	SELF:Browser:AddColumn(SELF:oDBNOVODOC)

	SELF:oDBNOVODATA := DataColumn{PADRAO_CHAR_10{}}
	SELF:oDBNOVODATA:Width := 10
	SELF:oDBNOVODATA:HyperLabel := SELF:oDCNOVODATA:HyperLabel
	SELF:oDBNOVODATA:Caption := "Data"
	SELF:Browser:AddColumn(SELF:oDBNOVODATA)

	SELF:ViewAs(#FormView)


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NOVODATA
RETURN SELF:FieldGet( #NOVODATA )

ASSIGN NOVODATA( uValue )
SELF:FieldPut( #NOVODATA , uValue )

ACCESS NOVODOC
RETURN SELF:FieldGet( #NOVODOC )

ASSIGN NOVODOC( uValue )
SELF:FieldPut( #NOVODOC , uValue )

ACCESS NUMCOMP
RETURN SELF:FieldGet( #NUMCOMP )

ASSIGN NUMCOMP( uValue )
SELF:FieldPut( #NUMCOMP , uValue )

ACCESS NUMERO
RETURN SELF:FieldGet( #NUMERO )

ASSIGN NUMERO( uValue )
SELF:FieldPut( #NUMERO , uValue )

METHOD ordem( ) 
	SELF:KeyFind()

ACCESS PASTA
RETURN SELF:FieldGet( #PASTA )

ASSIGN PASTA( uValue )
SELF:FieldPut( #PASTA , uValue )

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )         
     oDCTIPO:FillUsing({{"_","_"}})
     oDccTIPO:FillUsing({{"_","_"}})
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


ACCESS TIPO
RETURN SELF:FieldGet( #TIPO )

ASSIGN TIPO( uValue )
SELF:FieldPut( #TIPO , uValue )

END CLASS
