CLASS XINDEXAR INHERIT Indexar

CONSTRUCTOR(oOWNER) 
IF ! entramenu("ENG",5)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	

METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
CRIANTX({ZCURINI,"LC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"LCT.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()

END CLASS
CLASS XJLC INHERIT JLC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("ENG",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"LC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:USE(oSERVER)
SELF:SHOW()

 METHOD PEGTIPO 
 RETU PEGLTIPO("LCT.DBF")

END CLASS
CLASS XJLCT INHERIT JLCT

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("ENG",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"LCT.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF

SUPER(oOWNER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:USE(oSERVER)
SELF:SHOW()


END CLASS
