PARTIAL CLASS JCEM
METHOD APPEND() 
LOCAL nNUMERO AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:NUMERO
nNUMERO++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT(#NUMERO,nNUMERO)
SELF:SERVER:commit()
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
RETURN .t.

METHOD buscaNOME( ) 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Localizar","Digite o Nome"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(2)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(oBUSCA:cBUSCA)
ENDIF	

METHOD buscaNUMERO( ) 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Localizar","Digite o Numero"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RH","ESC")	

METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
   SELF:oSFJCEI:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJCEI:SERVER:gotop()
   WHILE ! SELF:oSFJCEI:SERVER:eof
	 	SELF:oSFJCEI:SERVER:delete()
	 	SELF:oSFJCEI:SERVER:skip()	
      ENDDO
	SELF:oSFJCEI:SERVER:resetnotification()
	SELF:oSFJCEI:SERVER:notify(notifyfilechange)
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD ESCCUR 
LOCAL oJAN AS XESCCUR
oJAN:=XESCCUR{SELF,ZCURINI,ZCURDIR,"CURSO.DBF"}
oJAN:SHOW()
IF oJAN:lOK
   SELF:oDCCURSO:TextValue:=oJAN:CODIGO
ENDIF

METHOD EXCLUIR 
IF  MDG("Apagar Registro") .AND. SELF:oSFJCEI:server:LockCurrentRecord()
    SELF:oSFJCEI:server:delete()
    SELF:oSFJCEI:server:unlock()
    SELF:oSFJCEI:server:skip(-1)
    IF SELF:oSFJCEI:server:BOF
       SELF:oSFJCEI:server:GOTOP()
    ENDIF
 ENDIF	

METHOD INCLUIR(oOWNER) 
LOCAL nNUMERO AS DWORD
LOCAL cCURSO AS STRING
LOCAL aCUR AS ARRAY
LOCAL oERRO AS ERRORBOX
nNUMERO:=SELF:SERVER:NUMERO
cCURSO:=SELF:CURSO
IF Empty(SELF:CURSO)
   oERRO:=ERRORBOX{oOWNER,"Codigo Curso em Branco"}
   oERRO:SHOW()
   RETU NIL
ENDIF
aCUR:=PEGCUR(SELF:CURSO)
IF aCUR[1]=.F.
   oERRO:=ERRORBOX{oOWNER,"Curso não Cadastrado"}
   oERRO:SHOW()
   RETU NIL
ENDIF
SELF:oSFJCEI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJCEI:SERVER:APPEND()
SELF:oSFJCEI:SERVER:NUMERO:=nNUMERO
SELF:oSFJCEI:SERVER:CURSO:=cCURSO
SELF:oSFJCEI:SERVER:DESCUR:=aCUR[2]
SELF:oSFJCEI:SERVER:commit()
SELF:oSFJCEI:SERVER:resetnotification()
SELF:oSFJCEI:SERVER:notify(notifyappend)

METHOD PORCOGNOME() 
SELF:server:setorder(2)
RETURN .t.

METHOD PORNUMERO() 
SELF:server:setorder(1)
RETURN .t.

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJCEI:Server:COMMIT()



END CLASS
