PARTIAL CLASS JCUR
METHOD ALTERAR  
SELF:oSFJCURGRP:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJCURGRP:SkipPrevious()
IF SELF:oSFJCURGRP:Server:bof
	SELF:oSFJCURGRP:SERVER:gotop()
ENDIF


METHOD APPEND() 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Incluir","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   IF SELF:SERVER:SEEK(oBUSCA:cBUSCA)
   	  alert("Curso Ja Cadastrado","Erro Cadastro")
   ELSE
      SUPER:Append()	
      SELF:SERVER:FIELDPUT("CURSO",oBUSCA:cBUSCA)
   ENDIF	
ENDIF	

METHOD ATUALIZA() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}	
	TROCADES("TREIN.DBF",SELF:SERVER:CURSO,SELF:SERVER:DESCUR,"CURSO","DESCUR")
	TROCADES("PT.DBF",SELF:SERVER:CURSO,SELF:SERVER:DESCUR,"CURSO","DESCUR")	
	TROCADES("MP04A.DBF",SELF:SERVER:CURSO,SELF:SERVER:DESCUR,"CURSO","DESCUR")
	TROCADES("MP04C.DBF",SELF:SERVER:CURSO,SELF:SERVER:DESCUR,"CURSO","DESCUR")	
SELF:POINTER:=POINTER{}		

METHOD buscacurso( ) 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Localizar","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(oBUSCA:cBUSCA)
ENDIF	

METHOD buscanome( ) 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Localizar","Digite o Nome"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(2)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(oBUSCA:cBUSCA)
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RH","CUR")	


METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()	
	SELF:server:skip(-1)
	IF SELF:SERVER:BOF
	   SELF:SERVER:GOTOP()	
    ENDIF		
ENDIF	

METHOD Editar( ) 
LOCAL oBUSCA AS xBUSCA
LOCAL nREG AS DWORD
nREG:=SELF:SERVER:RECNO
oBUSCA:=xBUSCA{SELF,"Alteraçao de Codigo","Digite o Novo Codigo",SELF:SERVER:FIELDGET("CURSO")}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   IF SELF:SERVER:SEEK(oBUSCA:cBUSCA)
   	  alert("Curso Ja Cadastrado","Erro Troca Código")
   ELSE
      SELF:SERVER:GOTO(nREG)
      SELF:SERVER:FIELDPUT("CURSO",oBUSCA:cBUSCA)
   ENDIF	
ENDIF	

METHOD ESCOLHER 
SELF:SERVER:FIELDPUT("GRUPO",SELF:oSFjcurgrp:SERVER:FIELDGET("GRUPO"))	


METHOD EXCLUIR 
SELF:oSFjcurgrp:SERVER:Delete()
SELF:oSFjcurgrp:SERVER:SKIP()
IF SELF:oSFjcurgrp:SERVER:EOF
   SELF:oSFjcurgrp:SERVER:GOTOP()
ENDIF	

METHOD mcur( ) 
	SELF:server:FIELDPUT("curso",Upper(SELF:server:FIELDGET("CURSO")))

METHOD NOVO 
SELF:oSFjcurgrp:SERVER:APPEND()


METHOD PORCURSO() 
SELF:server:setorder(1)
RETURN .t.



METHOD PORNOME() 
SELF:server:setorder(2)
RETURN .t.

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJCURGRP:SkipNext()
IF SELF:oSFJCURGRP:Server:Eof
	SELF:oSFJCURGRP:gobottom()
ENDIF

METHOD TABULAR  
SELF:oSFJCURGRP:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
FUNCTION TROCADES(cARQ,cCODIGO,cDESCRI,cCAMCUR,cCAMDES)	
LOCAL aDAD,aCOM AS ARRAY
LOCAL oSERVER AS USEREDE	
aDAD:={zCURINI,cARQ,zCURDIR}
aCOM:={zMES,zANO,ZEMPRESA}
//Init(aDAD, lShareMode, lReadOnlyMode, cDriver, aCOM)
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
    RETURN .f.
ENDIF	
oSERVER:GOTOP()
WHILE ! oSERVER:EOF
	IF cCODIGO=oSERVER:FIELDGET(cCAMCUR)
	   oSERVER:FIELDPUT(cCAMDES,cDESCRI)
	ENDIF	
    oSERVER:Skip()	
ENDDO
oSERVER:CLOSE()	




