CLASS xJTERH INHERIT JTERH
METHOD cmdvertrein1( ) 
LOCAL nNUMERO AS DWORD	
LOCAL oJTREIN AS jDIATREIN
AltD()
nNUMERO:=SELF:osfjMP04C:SERVER:FIELDGET("TREIN")
oJTREIN:=jDIATREIN{SELF,nNUMERO}
oJTREIN:SHOW()

METHOD cmdvertrein( ) 
LOCAL nNUMERO AS DWORD	
LOCAL oJTREIN AS jDIATREIN
AltD()
nNUMERO:=SELF:osfjMP04A:SERVER:FIELDGET("TREIN")
oJTREIN:=jDIATREIN{SELF,nNUMERO}
oJTREIN:SHOW()

END CLASS
