PARTIAL CLASS JPRO
METHOD ALTERAR  
SELF:oSFJCURGRP:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJCURGRP:SkipPrevious()
IF SELF:oSFJCURGRP:Server:bof
	SELF:oSFJCURGRP:SERVER:gotop()
ENDIF

METHOD APPEND() 
LOCAL oBUSCA AS BUSCA
oBUSCA:=BUSCA{SELF}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   IF SELF:SERVER:SEEK(oBUSCA:cBUSCA)
   	  alert("Curso Ja Cadastrado","Erro Cadastro")
   ELSE
      SUPER:Append()	
      SELF:SERVER:FIELDPUT("CURSO",oBUSCA:cBUSCA)
   ENDIF	
ENDIF	

METHOD buscacurso( ) 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Localizar","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(oBUSCA:cBUSCA)
ENDIF	

METHOD buscanome( ) 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,,"Localizar","Digite o Nome"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(2)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(oBUSCA:cBUSCA)
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RH","PRO")	


METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
	IF SELF:SERVER:BOF
		SELF:SERVER:GOTOP()
    ENDIF		
ENDIF	

METHOD ESCOLHER 
SELF:SERVER:FIELDPUT("GRUPO",SELF:oSFjcurgrp:SERVER:FIELDGET("GRUPO"))	


METHOD EXCLUIR 
SELF:oSFjcurgrp:SERVER:Delete()
SELF:oSFjcurgrp:SERVER:SKIP()
IF SELF:oSFjcurgrp:SERVER:EOF
   SELF:oSFjcurgrp:SERVER:GOTOP()
ENDIF	

METHOD NOVO 
SELF:oSFjcurgrp:SERVER:APPEND()

METHOD PORCURSO() 
SELF:server:setorder(1)
RETURN .t.

METHOD PORNOME() 
SELF:server:setorder(2)
RETURN .t.

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJCURGRP:SkipNext()
IF SELF:oSFJCURGRP:Server:Eof
	SELF:oSFJCURGRP:gobottom()
ENDIF

METHOD TABULAR  
SELF:oSFJCURGRP:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
