#region DEFINES
STATIC DEFINE JPT_ANO := 113
STATIC DEFINE JPT_ANTERIOR := 156
STATIC DEFINE JPT_APRODATA := 174
STATIC DEFINE JPT_APROVADA := 161
STATIC DEFINE JPT_AREA := 122
STATIC DEFINE JPT_BUSCAFUN := 157
STATIC DEFINE JPT_BUSCANUMERO := 153
STATIC DEFINE JPT_CARGA := 118
STATIC DEFINE JPT_CERT := 145
STATIC DEFINE JPT_CMDAPR := 163
STATIC DEFINE JPT_CMDVERTREIN := 172
STATIC DEFINE JPT_CMDVERTREIN1 := 173
STATIC DEFINE JPT_CNOME := 138
STATIC DEFINE JPT_CURSO := 119
STATIC DEFINE JPT_DATA := 110
STATIC DEFINE JPT_DATACUR := 115
STATIC DEFINE JPT_DATAFIM := 116
STATIC DEFINE JPT_DESCUR := 120
STATIC DEFINE JPT_DUPLICAR := 158
STATIC DEFINE JPT_ESCCUR := 151
STATIC DEFINE JPT_ESCESC := 150
STATIC DEFINE JPT_ESCINS := 149
STATIC DEFINE JPT_ESCINS1 := 171
STATIC DEFINE JPT_ESCO := 159
STATIC DEFINE JPT_ESCOLHER := 139
STATIC DEFINE JPT_ESCRES := 148
STATIC DEFINE JPT_ESCSOL := 169
STATIC DEFINE JPT_EXCLUIR := 130
STATIC DEFINE JPT_FT11 := 127
STATIC DEFINE JPT_FT12 := 135
STATIC DEFINE JPT_FT13 := 136
STATIC DEFINE JPT_FT14 := 146
STATIC DEFINE JPT_FT15 := 147
STATIC DEFINE JPT_FT16 := 162
STATIC DEFINE JPT_INSTRU := 126
STATIC DEFINE JPT_JPTI := 133
STATIC DEFINE JPT_JTREINF := 137
STATIC DEFINE JPT_MES := 112
STATIC DEFINE JPT_NESCOLA := 125
STATIC DEFINE JPT_NFUNC := 131
STATIC DEFINE JPT_NINSTU := 124
STATIC DEFINE JPT_NOMSOL := 166
STATIC DEFINE JPT_NOVO := 129
STATIC DEFINE JPT_NTREIN := 160
STATIC DEFINE JPT_NUMSOL := 168
STATIC DEFINE JPT_PARTI := 132
STATIC DEFINE JPT_PEGCURDES := 154
STATIC DEFINE JPT_PEGESC := 165
STATIC DEFINE JPT_PEGINS := 164
STATIC DEFINE JPT_PEGSOL := 170
STATIC DEFINE JPT_PORNUMERO := 152
STATIC DEFINE JPT_PRFIM := 114
STATIC DEFINE JPT_PRINI := 111
STATIC DEFINE JPT_PROXIMO := 155
STATIC DEFINE JPT_RADIOBUTTON4 := 141
STATIC DEFINE JPT_RADIOBUTTON5 := 142
STATIC DEFINE JPT_REFER := 121
STATIC DEFINE JPT_RESPO := 123
STATIC DEFINE JPT_SC_CARGA := 106
STATIC DEFINE JPT_SC_CURSO := 104
STATIC DEFINE JPT_SC_DATACUR := 101
STATIC DEFINE JPT_SC_DATACUR1 := 143
STATIC DEFINE JPT_SC_DATACUR2 := 144
STATIC DEFINE JPT_SC_DESCUR := 105
STATIC DEFINE JPT_SC_HORFIM := 103
STATIC DEFINE JPT_SC_HORINI := 102
STATIC DEFINE JPT_SC_NINSTU := 108
STATIC DEFINE JPT_SC_NINSTU1 := 167
STATIC DEFINE JPT_SC_PARTI := 128
STATIC DEFINE JPT_SC_REFER := 134
STATIC DEFINE JPT_SC_RESPO := 107
STATIC DEFINE JPT_SC_TREIN := 100
STATIC DEFINE JPT_TIPCUR := 117
STATIC DEFINE JPT_TIPDIS := 140
STATIC DEFINE JPT_TREIN := 109
#endregion

PARTIAL CLASS JPT INHERIT MYDataWindow
PROTECT oDBTREIN AS DataColumn
PROTECT oDBDATA AS DataColumn
PROTECT oDBMES AS DataColumn
PROTECT oDBANO AS DataColumn
PROTECT oDBDATACUR AS DataColumn
PROTECT oDCSC_TREIN AS FIXEDTEXT
PROTECT oDCSC_DATACUR AS FIXEDTEXT
PROTECT oDCSC_HORINI AS FIXEDTEXT
PROTECT oDCSC_HORFIM AS FIXEDTEXT
PROTECT oDCSC_CURSO AS FIXEDTEXT
PROTECT oDCSC_DESCUR AS FIXEDTEXT
PROTECT oDCSC_CARGA AS FIXEDTEXT
PROTECT oDCSC_RESPO AS FIXEDTEXT
PROTECT oDCSC_NINSTU AS FIXEDTEXT
PROTECT oDCTREIN AS SINGLELINEEDIT
PROTECT oDCDATA AS DateSle
PROTECT oDCPRINI AS DateSle
PROTECT oDCMES AS rightSle
PROTECT oDCANO AS rightSle
PROTECT oDCPRFIM AS DateSle
PROTECT oDCDATACUR AS DateSle
PROTECT oDCDATAFIM AS DateSle
PROTECT oDCTIPCUR AS SINGLELINEEDIT
PROTECT oDCCARGA AS rightSle
PROTECT oDCCURSO AS SINGLELINEEDIT
PROTECT oDCDESCUR AS SINGLELINEEDIT
PROTECT oDCREFER AS SINGLELINEEDIT
PROTECT oDCAREA AS COMBOBOX
PROTECT oDCRESPO AS SINGLELINEEDIT
PROTECT oDCNINSTU AS rightSle
PROTECT oDCNESCOLA AS rightSle
PROTECT oDCINSTRU AS SINGLELINEEDIT
PROTECT oDCFT11 AS FIXEDTEXT
PROTECT oDCSC_PARTI AS FIXEDTEXT
PROTECT oCCNovo AS PUSHBUTTON
PROTECT oCCEXCLUIR AS PUSHBUTTON
PROTECT oDCNFUNC AS rightSle
PROTECT oDCPARTI AS rightSle
PROTECT oSFJPTI AS JPTI
PROTECT oDCSC_REFER AS FIXEDTEXT
PROTECT oDCFT12 AS FIXEDTEXT
PROTECT oDCFT13 AS FIXEDTEXT
PROTECT oSFJTREINF AS JTREINF
PROTECT oDCCNOME AS SINGLELINEEDIT
PROTECT oCCEscolher AS PUSHBUTTON
PROTECT oDCTIPDIS AS RADIOBUTTONGROUP
PROTECT oCCRadioButton4 AS RADIOBUTTON
PROTECT oCCRadioButton5 AS RADIOBUTTON
PROTECT oDCSC_DATACUR1 AS FIXEDTEXT
PROTECT oDCSC_DATACUR2 AS FIXEDTEXT
PROTECT oDCCERT AS SINGLELINEEDIT
PROTECT oDCFT14 AS FIXEDTEXT
PROTECT oDCFT15 AS FIXEDTEXT
PROTECT oCCESCRES AS PUSHBUTTON
PROTECT oCCEscins AS PUSHBUTTON
PROTECT oCCESCESC AS PUSHBUTTON
PROTECT oCCesccur AS PUSHBUTTON
PROTECT oCCpornumero AS PUSHBUTTON
PROTECT oCCbuscanumero AS PUSHBUTTON
PROTECT oCCpegcurdes AS PUSHBUTTON
PROTECT oCCProximo AS PUSHBUTTON
PROTECT oCCAnterior AS PUSHBUTTON
PROTECT oCCbuscafun AS PUSHBUTTON
PROTECT oCCDuplicar AS PUSHBUTTON
PROTECT oCCEsco AS PUSHBUTTON
PROTECT oDCNTREIN AS rightSle
PROTECT oDCaprovada AS SINGLELINEEDIT
PROTECT oDCFT16 AS FIXEDTEXT
PROTECT oCCcmdapr AS PUSHBUTTON
PROTECT oCCPEGINS AS PUSHBUTTON
PROTECT oCCbtnPEGESC AS PUSHBUTTON
PROTECT oDCNOMSOL AS SINGLELINEEDIT
PROTECT oDCSC_NINSTU1 AS FIXEDTEXT
PROTECT oDCNUMSOL AS rightSle
PROTECT oCCESCSOL AS PUSHBUTTON
PROTECT oCCPEGSOL AS PUSHBUTTON
PROTECT oCCEscins1 AS PUSHBUTTON
PROTECT oCCcmdvertrein AS PUSHBUTTON
PROTECT oCCcmdvertrein1 AS PUSHBUTTON
PROTECT oDCAPRODATA AS DateSle

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS ANO
RETURN SELF:FieldGet( #ANO )

ASSIGN ANO( uValue )
SELF:FieldPut( #ANO , uValue )

ACCESS APRODATA
RETURN SELF:FieldGet( #APRODATA )

ASSIGN APRODATA( uValue )
SELF:FieldPut( #APRODATA , uValue )

ACCESS aprovada
RETURN SELF:FieldGet( #aprovada )

ASSIGN aprovada( uValue )
SELF:FieldPut( #aprovada , uValue )

ACCESS AREA
RETURN SELF:FieldGet( #AREA )

ASSIGN AREA( uValue )
SELF:FieldPut( #AREA , uValue )

ACCESS CARGA
RETURN SELF:FieldGet( #CARGA )

ASSIGN CARGA( uValue )
SELF:FieldPut( #CARGA , uValue )

ACCESS CERT
RETURN SELF:FieldGet( #CERT )

ASSIGN CERT( uValue )
SELF:FieldPut( #CERT , uValue )

METHOD cmdvertrein( ) 
LOCAL nNUMERO AS DWORD	
LOCAL oJTREIN AS jDIATREIN
nNUMERO:=SELF:SERVER:FIELDGET("NTREIN")
oJTREIN:=jDIATREIN{SELF,nNUMERO}
oJTREIN:SHOW()	

ACCESS CNOME
RETURN SELF:FieldGet( #CNOME )

ASSIGN CNOME( uValue )
SELF:FieldPut( #CNOME , uValue )

ACCESS CURSO
RETURN SELF:FieldGet( #CURSO )

ASSIGN CURSO( uValue )
SELF:FieldPut( #CURSO , uValue )

ACCESS DATA
RETURN SELF:FieldGet( #DATA )

ASSIGN DATA( uValue )
SELF:FieldPut( #DATA , uValue )

ACCESS DATACUR
RETURN SELF:FieldGet( #DATACUR )

ASSIGN DATACUR( uValue )
SELF:FieldPut( #DATACUR , uValue )

ACCESS DATAFIM
RETURN SELF:FieldGet( #DATAFIM )

ASSIGN DATAFIM( uValue )
SELF:FieldPut( #DATAFIM , uValue )

ACCESS DESCUR
RETURN SELF:FieldGet( #DESCUR )

ASSIGN DESCUR( uValue )
SELF:FieldPut( #DESCUR , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JPT" , _GetInst()},iCtlID)

	SELF:oDCSC_TREIN := FIXEDTEXT{SELF , ResourceID{ JPT_SC_TREIN  , _GetInst() } }
	SELF:oDCSC_TREIN:HyperLabel := HyperLabel{#SC_TREIN , "Programaçäo" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATACUR := FIXEDTEXT{SELF , ResourceID{ JPT_SC_DATACUR  , _GetInst() } }
	SELF:oDCSC_DATACUR:HyperLabel := HyperLabel{#SC_DATACUR , "Prg Inicial" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HORINI := FIXEDTEXT{SELF , ResourceID{ JPT_SC_HORINI  , _GetInst() } }
	SELF:oDCSC_HORINI:HyperLabel := HyperLabel{#SC_HORINI , "Inicio" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HORFIM := FIXEDTEXT{SELF , ResourceID{ JPT_SC_HORFIM  , _GetInst() } }
	SELF:oDCSC_HORFIM:HyperLabel := HyperLabel{#SC_HORFIM , "Fim" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CURSO := FIXEDTEXT{SELF , ResourceID{ JPT_SC_CURSO  , _GetInst() } }
	SELF:oDCSC_CURSO:HyperLabel := HyperLabel{#SC_CURSO , "Curso:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESCUR := FIXEDTEXT{SELF , ResourceID{ JPT_SC_DESCUR  , _GetInst() } }
	SELF:oDCSC_DESCUR:HyperLabel := HyperLabel{#SC_DESCUR , "Descrição:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CARGA := FIXEDTEXT{SELF , ResourceID{ JPT_SC_CARGA  , _GetInst() } }
	SELF:oDCSC_CARGA:HyperLabel := HyperLabel{#SC_CARGA , "Carga Horária:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RESPO := FIXEDTEXT{SELF , ResourceID{ JPT_SC_RESPO  , _GetInst() } }
	SELF:oDCSC_RESPO:HyperLabel := HyperLabel{#SC_RESPO , "Responsável:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NINSTU := FIXEDTEXT{SELF , ResourceID{ JPT_SC_NINSTU  , _GetInst() } }
	SELF:oDCSC_NINSTU:HyperLabel := HyperLabel{#SC_NINSTU , "No. Instrutor" , NULL_STRING , NULL_STRING}

	SELF:oDCTREIN := SINGLELINEEDIT{SELF , ResourceID{ JPT_TREIN  , _GetInst() } }
	SELF:oDCTREIN:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCTREIN:Background := Brush{ Color{ 253 , 254 , 220 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCTREIN:Font( oFont )
	SELF:oDCTREIN:HyperLabel := HyperLabel{#TREIN , "Trein:" , NULL_STRING , "TREIN_TREIN"}

	SELF:oDCDATA := DateSle{SELF , ResourceID{ JPT_DATA  , _GetInst() } }
	SELF:oDCDATA:FieldSpec := date_field{}
	SELF:oDCDATA:HyperLabel := HyperLabel{#DATA , "Data" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCPRINI := DateSle{SELF , ResourceID{ JPT_PRINI  , _GetInst() } }
	SELF:oDCPRINI:FieldSpec := date_FIELD{}
	SELF:oDCPRINI:HyperLabel := HyperLabel{#PRINI , "Horini:" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCMES := rightSle{SELF , ResourceID{ JPT_MES  , _GetInst() } }
	SELF:oDCMES:FieldSpec := PADRAO_NUM_02{}
	SELF:oDCMES:HyperLabel := HyperLabel{#MES , "MES" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCANO := rightSle{SELF , ResourceID{ JPT_ANO  , _GetInst() } }
	SELF:oDCANO:FieldSpec := PADRAO_NUM_04{}
	SELF:oDCANO:HyperLabel := HyperLabel{#ANO , "ANO" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCPRFIM := DateSle{SELF , ResourceID{ JPT_PRFIM  , _GetInst() } }
	SELF:oDCPRFIM:FieldSpec := DATE_FIELD{}
	SELF:oDCPRFIM:HyperLabel := HyperLabel{#PRFIM , "Horini:" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCDATACUR := DateSle{SELF , ResourceID{ JPT_DATACUR  , _GetInst() } }
	SELF:oDCDATACUR:FieldSpec := DATE_FIELD{}
	SELF:oDCDATACUR:HyperLabel := HyperLabel{#DATACUR , "DataCur" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCDATAFIM := DateSle{SELF , ResourceID{ JPT_DATAFIM  , _GetInst() } }
	SELF:oDCDATAFIM:FieldSpec := DATE_FIELD{}
	SELF:oDCDATAFIM:HyperLabel := HyperLabel{#DATAFIM , "Horfim:" , NULL_STRING , "TREIN_HORFIM"}

	SELF:oDCTIPCUR := SINGLELINEEDIT{SELF , ResourceID{ JPT_TIPCUR  , _GetInst() } }
	SELF:oDCTIPCUR:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPCUR:HyperLabel := HyperLabel{#TIPCUR , "Horini:" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCCARGA := rightSle{SELF , ResourceID{ JPT_CARGA  , _GetInst() } }
	SELF:oDCCARGA:FieldSpec := PADRAO_NUM_08_2{}
	SELF:oDCCARGA:HyperLabel := HyperLabel{#CARGA , "Carga:" , NULL_STRING , "TREIN_CARGA"}

	SELF:oDCCURSO := SINGLELINEEDIT{SELF , ResourceID{ JPT_CURSO  , _GetInst() } }
	SELF:oDCCURSO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCCURSO:HyperLabel := HyperLabel{#CURSO , "Curso:" , NULL_STRING , "TREIN_CURSO"}

	SELF:oDCDESCUR := SINGLELINEEDIT{SELF , ResourceID{ JPT_DESCUR  , _GetInst() } }
	SELF:oDCDESCUR:FieldSpec := PADRAO_CHAR_120{}
	SELF:oDCDESCUR:Background := Brush{ Color{ 253 , 254 , 220 } }
	SELF:oDCDESCUR:HyperLabel := HyperLabel{#DESCUR , "Descur:" , NULL_STRING , "TREIN_DESCUR"}

	SELF:oDCREFER := SINGLELINEEDIT{SELF , ResourceID{ JPT_REFER  , _GetInst() } }
	SELF:oDCREFER:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCREFER:HyperLabel := HyperLabel{#REFER , "Refer:" , NULL_STRING , "TREIN_REFER"}

	SELF:oDCAREA := COMBOBOX{SELF , ResourceID{ JPT_AREA  , _GetInst() } }
	SELF:oDCAREA:FillUsing( SELF:comboPEGMP05() )
	SELF:oDCAREA:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCAREA:HyperLabel := HyperLabel{#AREA , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCRESPO := SINGLELINEEDIT{SELF , ResourceID{ JPT_RESPO  , _GetInst() } }
	SELF:oDCRESPO:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCRESPO:Background := Brush{ Color{ 253 , 254 , 220 } }
	SELF:oDCRESPO:HyperLabel := HyperLabel{#RESPO , "Parti:" , NULL_STRING , "TREIN_RESPO"}

	SELF:oDCNINSTU := rightSle{SELF , ResourceID{ JPT_NINSTU  , _GetInst() } }
	SELF:oDCNINSTU:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNINSTU:HyperLabel := HyperLabel{#NINSTU , "Ninstu:" , NULL_STRING , "TREIN_NINSTU"}

	SELF:oDCNESCOLA := rightSle{SELF , ResourceID{ JPT_NESCOLA  , _GetInst() } }
	SELF:oDCNESCOLA:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNESCOLA:HyperLabel := HyperLabel{#NESCOLA , "Ninstu:" , NULL_STRING , "TREIN_NINSTU"}

	SELF:oDCINSTRU := SINGLELINEEDIT{SELF , ResourceID{ JPT_INSTRU  , _GetInst() } }
	SELF:oDCINSTRU:FieldSpec := PADRAO_CHAR_30{}
	SELF:oDCINSTRU:HyperLabel := HyperLabel{#INSTRU , "Instru:" , NULL_STRING , "TREIN_INSTRU"}

	SELF:oDCFT11 := FIXEDTEXT{SELF , ResourceID{ JPT_FT11  , _GetInst() } }
	SELF:oDCFT11:HyperLabel := HyperLabel{#FT11 , "Func." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PARTI := FIXEDTEXT{SELF , ResourceID{ JPT_SC_PARTI  , _GetInst() } }
	SELF:oDCSC_PARTI:HyperLabel := HyperLabel{#SC_PARTI , "Part." , NULL_STRING , NULL_STRING}

	SELF:oCCNovo := PUSHBUTTON{SELF , ResourceID{ JPT_NOVO  , _GetInst() } }
	SELF:oCCNovo:HyperLabel := HyperLabel{#Novo , "Novo" , NULL_STRING , NULL_STRING}

	SELF:oCCEXCLUIR := PUSHBUTTON{SELF , ResourceID{ JPT_EXCLUIR  , _GetInst() } }
	SELF:oCCEXCLUIR:HyperLabel := HyperLabel{#EXCLUIR , "Excluir" , NULL_STRING , NULL_STRING}

	SELF:oDCNFUNC := rightSle{SELF , ResourceID{ JPT_NFUNC  , _GetInst() } }
	SELF:oDCNFUNC:FieldSpec := padrao_NUm_08{}
	SELF:oDCNFUNC:HyperLabel := HyperLabel{#NFUNC , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCPARTI := rightSle{SELF , ResourceID{ JPT_PARTI  , _GetInst() } }
	SELF:oDCPARTI:FieldSpec := padrao_num_08{}
	SELF:oDCPARTI:HyperLabel := HyperLabel{#PARTI , "Programacao de Treinamentos" , NULL_STRING , "TREIN_PARTI"}

	SELF:oDCSC_REFER := FIXEDTEXT{SELF , ResourceID{ JPT_SC_REFER  , _GetInst() } }
	SELF:oDCSC_REFER:HyperLabel := HyperLabel{#SC_REFER , "Referente:" , NULL_STRING , NULL_STRING}

	SELF:oDCFT12 := FIXEDTEXT{SELF , ResourceID{ JPT_FT12  , _GetInst() } }
	SELF:oDCFT12:HyperLabel := HyperLabel{#FT12 , "Prg Final" , NULL_STRING , NULL_STRING}

	SELF:oDCFT13 := FIXEDTEXT{SELF , ResourceID{ JPT_FT13  , _GetInst() } }
	SELF:oDCFT13:HyperLabel := HyperLabel{#FT13 , "Escola" , NULL_STRING , NULL_STRING}

	SELF:oDCCNOME := SINGLELINEEDIT{SELF , ResourceID{ JPT_CNOME  , _GetInst() } }
	SELF:oDCCNOME:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCCNOME:FocusSelect := FSEL_HOME
	SELF:oDCCNOME:HyperLabel := HyperLabel{#CNOME , "Instru:" , NULL_STRING , "TREIN_INSTRU"}

	SELF:oCCEscolher := PUSHBUTTON{SELF , ResourceID{ JPT_ESCOLHER  , _GetInst() } }
	SELF:oCCEscolher:HyperLabel := HyperLabel{#Escolher , "Escolher" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPDIS := RADIOBUTTONGROUP{SELF , ResourceID{ JPT_TIPDIS  , _GetInst() } }
	SELF:oDCTIPDIS:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPDIS:HyperLabel := HyperLabel{#TIPDIS , "Tipo" , NULL_STRING , NULL_STRING}

	SELF:oCCRadioButton4 := RADIOBUTTON{SELF , ResourceID{ JPT_RADIOBUTTON4  , _GetInst() } }
	SELF:oCCRadioButton4:HyperLabel := HyperLabel{#RadioButton4 , "Anual" , NULL_STRING , NULL_STRING}

	SELF:oCCRadioButton5 := RADIOBUTTON{SELF , ResourceID{ JPT_RADIOBUTTON5  , _GetInst() } }
	SELF:oCCRadioButton5:HyperLabel := HyperLabel{#RadioButton5 , "Incorporado" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATACUR1 := FIXEDTEXT{SELF , ResourceID{ JPT_SC_DATACUR1  , _GetInst() } }
	SELF:oDCSC_DATACUR1:HyperLabel := HyperLabel{#SC_DATACUR1 , "Competencia" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATACUR2 := FIXEDTEXT{SELF , ResourceID{ JPT_SC_DATACUR2  , _GetInst() } }
	SELF:oDCSC_DATACUR2:HyperLabel := HyperLabel{#SC_DATACUR2 , "Data" , NULL_STRING , NULL_STRING}

	SELF:oDCCERT := SINGLELINEEDIT{SELF , ResourceID{ JPT_CERT  , _GetInst() } }
	SELF:oDCCERT:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCCERT:Background := Brush{ Color{ 253 , 254 , 220 } }
	SELF:oDCCERT:HyperLabel := HyperLabel{#CERT , "Horini:" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCFT14 := FIXEDTEXT{SELF , ResourceID{ JPT_FT14  , _GetInst() } }
	SELF:oDCFT14:HyperLabel := HyperLabel{#FT14 , "Certificado" , NULL_STRING , NULL_STRING}

	SELF:oDCFT15 := FIXEDTEXT{SELF , ResourceID{ JPT_FT15  , _GetInst() } }
	SELF:oDCFT15:HyperLabel := HyperLabel{#FT15 , "Interno/Externo" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES := PUSHBUTTON{SELF , ResourceID{ JPT_ESCRES  , _GetInst() } }
	SELF:oCCESCRES:HyperLabel := HyperLabel{#ESCRES , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCEscins := PUSHBUTTON{SELF , ResourceID{ JPT_ESCINS  , _GetInst() } }
	SELF:oCCEscins:HyperLabel := HyperLabel{#Escins , "Escolher Instrutor" , NULL_STRING , NULL_STRING}

	SELF:oCCESCESC := PUSHBUTTON{SELF , ResourceID{ JPT_ESCESC  , _GetInst() } }
	SELF:oCCESCESC:HyperLabel := HyperLabel{#ESCESC , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCesccur := PUSHBUTTON{SELF , ResourceID{ JPT_ESCCUR  , _GetInst() } }
	SELF:oCCesccur:HyperLabel := HyperLabel{#esccur , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCpornumero := PUSHBUTTON{SELF , ResourceID{ JPT_PORNUMERO  , _GetInst() } }
	SELF:oCCpornumero:Image := ico_az{}
	SELF:oCCpornumero:HyperLabel := HyperLabel{#pornumero , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscanumero := PUSHBUTTON{SELF , ResourceID{ JPT_BUSCANUMERO  , _GetInst() } }
	SELF:oCCbuscanumero:Image := ico_find{}
	SELF:oCCbuscanumero:HyperLabel := HyperLabel{#buscanumero , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCpegcurdes := PUSHBUTTON{SELF , ResourceID{ JPT_PEGCURDES  , _GetInst() } }
	SELF:oCCpegcurdes:HyperLabel := HyperLabel{#pegcurdes , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCProximo := PUSHBUTTON{SELF , ResourceID{ JPT_PROXIMO  , _GetInst() } }
	SELF:oCCProximo:Image := ico_next{}
	SELF:oCCProximo:HyperLabel := HyperLabel{#Proximo , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCAnterior := PUSHBUTTON{SELF , ResourceID{ JPT_ANTERIOR  , _GetInst() } }
	SELF:oCCAnterior:Image := ico_previous{}
	SELF:oCCAnterior:HyperLabel := HyperLabel{#Anterior , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscafun := PUSHBUTTON{SELF , ResourceID{ JPT_BUSCAFUN  , _GetInst() } }
	SELF:oCCbuscafun:Image := ico_find{}
	SELF:oCCbuscafun:HyperLabel := HyperLabel{#buscafun , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCDuplicar := PUSHBUTTON{SELF , ResourceID{ JPT_DUPLICAR  , _GetInst() } }
	SELF:oCCDuplicar:HyperLabel := HyperLabel{#Duplicar , "Duplicar" , NULL_STRING , NULL_STRING}

	SELF:oCCEsco := PUSHBUTTON{SELF , ResourceID{ JPT_ESCO  , _GetInst() } }
	SELF:oCCEsco:HyperLabel := HyperLabel{#Esco , "Escolher Ativos" , NULL_STRING , NULL_STRING}

	SELF:oDCNTREIN := rightSle{SELF , ResourceID{ JPT_NTREIN  , _GetInst() } }
	SELF:oDCNTREIN:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNTREIN:HyperLabel := HyperLabel{#NTREIN , "Refer:" , NULL_STRING , "TREIN_REFER"}

	SELF:oDCaprovada := SINGLELINEEDIT{SELF , ResourceID{ JPT_APROVADA  , _GetInst() } }
	SELF:oDCaprovada:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCaprovada:Background := Brush{ Color{ 253 , 254 , 220 } }
	SELF:oDCaprovada:HyperLabel := HyperLabel{#aprovada , NULL_STRING , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCFT16 := FIXEDTEXT{SELF , ResourceID{ JPT_FT16  , _GetInst() } }
	SELF:oDCFT16:HyperLabel := HyperLabel{#FT16 , "Aprovaçao" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdapr := PUSHBUTTON{SELF , ResourceID{ JPT_CMDAPR  , _GetInst() } }
	SELF:oCCcmdapr:HyperLabel := HyperLabel{#cmdapr , "SimNaoAguardoCancelado " , NULL_STRING , NULL_STRING}

	SELF:oCCPEGINS := PUSHBUTTON{SELF , ResourceID{ JPT_PEGINS  , _GetInst() } }
	SELF:oCCPEGINS:HyperLabel := HyperLabel{#PEGINS , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnPEGESC := PUSHBUTTON{SELF , ResourceID{ JPT_BTNPEGESC  , _GetInst() } }
	SELF:oCCbtnPEGESC:HyperLabel := HyperLabel{#btnPEGESC , "-->" , NULL_STRING , NULL_STRING}

	SELF:oDCNOMSOL := SINGLELINEEDIT{SELF , ResourceID{ JPT_NOMSOL  , _GetInst() } }
	SELF:oDCNOMSOL:FieldSpec := PADRAO_CHAR_30{}
	SELF:oDCNOMSOL:TooltipText := "Nome do Solicitabnte"
	SELF:oDCNOMSOL:HyperLabel := HyperLabel{#NOMSOL , "Instru:" , NULL_STRING , "TREIN_INSTRU"}

	SELF:oDCSC_NINSTU1 := FIXEDTEXT{SELF , ResourceID{ JPT_SC_NINSTU1  , _GetInst() } }
	SELF:oDCSC_NINSTU1:HyperLabel := HyperLabel{#SC_NINSTU1 , "Solicitante" , NULL_STRING , NULL_STRING}

	SELF:oDCNUMSOL := rightSle{SELF , ResourceID{ JPT_NUMSOL  , _GetInst() } }
	SELF:oDCNUMSOL:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNUMSOL:TooltipText := "Numero do Solicitante do Curso"
	SELF:oDCNUMSOL:HyperLabel := HyperLabel{#NUMSOL , "Ninstu:" , NULL_STRING , "TREIN_NINSTU"}

	SELF:oCCESCSOL := PUSHBUTTON{SELF , ResourceID{ JPT_ESCSOL  , _GetInst() } }
	SELF:oCCESCSOL:HyperLabel := HyperLabel{#ESCSOL , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCPEGSOL := PUSHBUTTON{SELF , ResourceID{ JPT_PEGSOL  , _GetInst() } }
	SELF:oCCPEGSOL:HyperLabel := HyperLabel{#PEGSOL , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCEscins1 := PUSHBUTTON{SELF , ResourceID{ JPT_ESCINS1  , _GetInst() } }
	SELF:oCCEscins1:HyperLabel := HyperLabel{#Escins1 , "Escolher Solicitante" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdvertrein := PUSHBUTTON{SELF , ResourceID{ JPT_CMDVERTREIN  , _GetInst() } }
	SELF:oCCcmdvertrein:TooltipText := "Visualizar Treinamento"
	SELF:oCCcmdvertrein:HyperLabel := HyperLabel{#cmdvertrein , "Ver Trei" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdvertrein1 := PUSHBUTTON{SELF , ResourceID{ JPT_CMDVERTREIN1  , _GetInst() } }
	SELF:oCCcmdvertrein1:HyperLabel := HyperLabel{#cmdvertrein1 , "Ver Treinamento" , NULL_STRING , NULL_STRING}

	SELF:oDCAPRODATA := DateSle{SELF , ResourceID{ JPT_APRODATA  , _GetInst() } }
	SELF:oDCAPRODATA:FieldSpec := date_field{}
	SELF:oDCAPRODATA:HyperLabel := HyperLabel{#APRODATA , "Data" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCTIPDIS:FillUsing({ ;
	                         {SELF:oCCRadioButton4, "A"}, ;
	                         {SELF:oCCRadioButton5, "I"} ;
	                         })

	SELF:Caption := "Programacao de Treinamentos"
	SELF:Menu := STANDARDSHELLMENU{}
	SELF:ClipperKeys := TRUE
	SELF:AllowServerClose := TRUE
	SELF:HyperLabel := HyperLabel{#JPT , "Programacao de Treinamentos" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBTREIN := DataColumn{PADRAO_NUM_08{}}
	SELF:oDBTREIN:Width := 7
	SELF:oDBTREIN:HyperLabel := SELF:oDCTREIN:HyperLabel
	SELF:oDBTREIN:Caption := "Trein:"
	SELF:Browser:AddColumn(SELF:oDBTREIN)

	SELF:oDBDATA := DataColumn{date_field{}}
	SELF:oDBDATA:Width := 12
	SELF:oDBDATA:HyperLabel := SELF:oDCDATA:HyperLabel
	SELF:oDBDATA:Caption := "Data"
	SELF:Browser:AddColumn(SELF:oDBDATA)

	SELF:oDBMES := DataColumn{PADRAO_NUM_02{}}
	SELF:oDBMES:Width := 5
	SELF:oDBMES:HyperLabel := SELF:oDCMES:HyperLabel
	SELF:oDBMES:Caption := "MES"
	SELF:Browser:AddColumn(SELF:oDBMES)

	SELF:oDBANO := DataColumn{PADRAO_NUM_04{}}
	SELF:oDBANO:Width := 8
	SELF:oDBANO:HyperLabel := SELF:oDCANO:HyperLabel
	SELF:oDBANO:Caption := "ANO"
	SELF:Browser:AddColumn(SELF:oDBANO)

	SELF:oDBDATACUR := DataColumn{DATE_FIELD{}}
	SELF:oDBDATACUR:Width := 9
	SELF:oDBDATACUR:HyperLabel := SELF:oDCDATACUR:HyperLabel
	SELF:oDBDATACUR:Caption := "DataCur"
	SELF:Browser:AddColumn(SELF:oDBDATACUR)

	SELF:ViewAs(#FormView)

	SELF:oSFJPTI := JPTI{SELF , JPT_JPTI }
	SELF:oSFJPTI:Show()
	SELF:oSFJTREINF := JTREINF{SELF , JPT_JTREINF }
	SELF:oSFJTREINF:Show()

	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS INSTRU
RETURN SELF:FieldGet( #INSTRU )

ASSIGN INSTRU( uValue )
SELF:FieldPut( #INSTRU , uValue )

ACCESS MES
RETURN SELF:FieldGet( #MES )

ASSIGN MES( uValue )
SELF:FieldPut( #MES , uValue )

ACCESS NESCOLA
RETURN SELF:FieldGet( #NESCOLA )

ASSIGN NESCOLA( uValue )
SELF:FieldPut( #NESCOLA , uValue )

ACCESS NFUNC
RETURN SELF:FieldGet( #NFUNC )

ASSIGN NFUNC( uValue )
SELF:FieldPut( #NFUNC , uValue )

ACCESS NINSTU
RETURN SELF:FieldGet( #NINSTU )

ASSIGN NINSTU( uValue )
SELF:FieldPut( #NINSTU , uValue )

ACCESS NOMSOL
RETURN SELF:FieldGet( #NOMSOL )

ASSIGN NOMSOL( uValue )
SELF:FieldPut( #NOMSOL , uValue )

ACCESS NTREIN
RETURN SELF:FieldGet( #NTREIN )

ASSIGN NTREIN( uValue )
SELF:FieldPut( #NTREIN , uValue )

ACCESS NUMSOL
RETURN SELF:FieldGet( #NUMSOL )

ASSIGN NUMSOL( uValue )
SELF:FieldPut( #NUMSOL , uValue )

ACCESS PARTI
RETURN SELF:FieldGet( #PARTI )

ASSIGN PARTI( uValue )
SELF:FieldPut( #PARTI , uValue )

ACCESS PRFIM
RETURN SELF:FieldGet( #PRFIM )

ASSIGN PRFIM( uValue )
SELF:FieldPut( #PRFIM , uValue )

ACCESS PRINI
RETURN SELF:FieldGet( #PRINI )

ASSIGN PRINI( uValue )
SELF:FieldPut( #PRINI , uValue )

ACCESS REFER
RETURN SELF:FieldGet( #REFER )

ASSIGN REFER( uValue )
SELF:FieldPut( #REFER , uValue )

ACCESS RESPO
RETURN SELF:FieldGet( #RESPO )

ASSIGN RESPO( uValue )
SELF:FieldPut( #RESPO , uValue )

ACCESS TIPCUR
RETURN SELF:FieldGet( #TIPCUR )

ASSIGN TIPCUR( uValue )
SELF:FieldPut( #TIPCUR , uValue )

ACCESS TIPDIS
RETURN SELF:FieldGet( #TIPDIS )

ASSIGN TIPDIS( uValue )
SELF:FieldPut( #TIPDIS , uValue )

ACCESS TREIN
RETURN SELF:FieldGet( #TREIN )

ASSIGN TREIN( uValue )
SELF:FieldPut( #TREIN , uValue )

END CLASS
STATIC DEFINE JPT_BTNPEGESC := 165
