PARTIAL CLASS JRHAB
METHOD cmdPERIC( ) 
SELF:server:FIELDPUT("JUSTIFICA",SIMNAO(SELF:SERVER:FIELDGET("JUSTIFICA"),{"S","N"," "}))	

END CLASS
PARTIAL CLASS JRHSEL
METHOD APPEND 
LOCAL oQUAL AS jqualfunc
LOCAL cNOME,cCPF,cPIS AS STRING
oQUAL:=jqualfunc {}
oQUAL:SHOW()

cNOME:=oQUAL:cNOME
cCPF:=formatcpf(oQUAL:cCPF)
cPIS:=oQUAL:cPIS
IF oQUAL:lOK
   SELF:server:setorder(2)
   SELF:server:gotop()
   IF ! SELF:server:seek(cNOME)
   	   SELF:server:setorder(4)
       SELF:server:gotop()
       IF ! SELF:server:seek(cCPF)
     	  SELF:server:setorder(5)
          SELF:server:gotop()
       	  IF Empty(cPIS) .OR. ! SELF:server:seek(cPIS)
		     SELF:SERVER:SUSPENDNOTIFICATION()
		     SUPER:append()	
		     SELF:SERVER:FIELDPUT("CPF",cCPF)
		     SELF:SERVER:FIELDPUT("PIS",cPIS)
		     SELF:SERVER:FIELDPUT("NOME",cNOME)
		     SELF:SERVER:FIELDPUT("NASC",CToD(oQUAL:dNASC))
		     SELF:SERVER:resetnotification()
			 SELF:SERVER:notify(notifyappend)
	     ELSE
      	    alert("PIS ja cadastrado")		
         ENDIF		
	  ELSE
    	  alert("CPF ja cadastrado")	
  	  ENDIF
  ELSE
  	  alert("Nome ja cadastrado")
  ENDIF	
ELSE
  alert("dados basicos nao preenchidos")
ENDIF




METHOD buscanom( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RH","")	


METHOD escfun( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"funcao.DBF"}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("FUNCAO",oESC:CODIGO)
ENDIF						

METHOD escfun1( ) 
	LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NUMERO",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("EMPRESA",ZEMPRESA)
ENDIF		


METHOD PEGMP02() 
RETU PEGCOMBO("MP02.DBF","NOME","CODIGO")

METHOD pornome( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
PARTIAL CLASS RHSELPAG01
METHOD CMDCHECKUF( ) 
		ufCheck(SELF:SERVER:FIELDGET("ESTADO"))

METHOD cmdhora1( ) 
		SELF:server:FIELDPUT("SEXO",SIMNAO(SELF:SERVER:FIELDGET("SEXO"),{"M","F"}))	

METHOD ESCANT( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NUMREGANT",oESCMP04:NUMERO)
ENDIF		

METHOD ESCIND( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("INDICADO",oESCMP04:NOME)
ENDIF		


METHOD ESCIND1( ) 
	LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("indiparAR",oESCMP04:NOME)
ENDIF		


END CLASS
PARTIAL CLASS RHSELPAG02
METHOD CMDCHECKUF( ) 
			ufCheck(SELF:SERVER:FIELDGET("CTPSUF"))

METHOD PEGRHESC() 
RETU PEGCOMBO("RHESC.DBF","DESCRI","CODIGO")


END CLASS
