#region DEFINES
STATIC DEFINE JRHSEL_BUSCANOM := 104 
STATIC DEFINE JRHSEL_CCUSTO := 118 
STATIC DEFINE JRHSEL_CODMP02 := 106 
STATIC DEFINE JRHSEL_EMPRESA := 109 
STATIC DEFINE JRHSEL_ESCFUN := 111 
STATIC DEFINE JRHSEL_ESCFUN1 := 114 
STATIC DEFINE JRHSEL_ESCUNID := 116 
STATIC DEFINE JRHSEL_FUNCAO := 112 
STATIC DEFINE JRHSEL_NOME := 102 
STATIC DEFINE JRHSEL_NUMERO := 107 
STATIC DEFINE JRHSEL_PORNOME := 105 
STATIC DEFINE JRHSEL_RHSELTAB := 100 
STATIC DEFINE JRHSEL_SC_CHAPA1 := 119 
STATIC DEFINE JRHSEL_SC_CHAPA2 := 117 
STATIC DEFINE JRHSEL_SC_CHAPA3 := 113 
STATIC DEFINE JRHSEL_SC_FUNCAO := 101 
STATIC DEFINE JRHSEL_SC_NOME := 103 
STATIC DEFINE JRHSEL_SC_NUMERO := 108 
STATIC DEFINE JRHSEL_SC_NUMERO1 := 110 
STATIC DEFINE JRHSEL_UNIFUN := 115 
STATIC DEFINE RHSELPAG01_ANONASC := 124 
STATIC DEFINE RHSELPAG01_APOSENT := 169 
STATIC DEFINE RHSELPAG01_APOSENTD := 128 
STATIC DEFINE RHSELPAG01_APOSENTSIMNAO := 168 
STATIC DEFINE RHSELPAG01_APROVADO := 108 
STATIC DEFINE RHSELPAG01_BAIRRO := 103 
STATIC DEFINE RHSELPAG01_CELULAR := 114 
STATIC DEFINE RHSELPAG01_CEP := 104 
STATIC DEFINE RHSELPAG01_CIDADE := 105 
STATIC DEFINE RHSELPAG01_CMDCHECKUF := 149 
STATIC DEFINE RHSELPAG01_CMDHORA := 164 
STATIC DEFINE RHSELPAG01_CMDHORA1 := 146 
STATIC DEFINE RHSELPAG01_COMPARECE := 107 
STATIC DEFINE RHSELPAG01_CONTATO := 116 
STATIC DEFINE RHSELPAG01_DATTRANSF := 118 
STATIC DEFINE RHSELPAG01_DEFICI := 178 
STATIC DEFINE RHSELPAG01_DEPTO2 := 120 
STATIC DEFINE RHSELPAG01_EMAIL := 117 
STATIC DEFINE RHSELPAG01_ENDCOMPL := 102 
STATIC DEFINE RHSELPAG01_ENDER := 100 
STATIC DEFINE RHSELPAG01_ENDNUM := 101 
STATIC DEFINE RHSELPAG01_ENDTIP := 159 
STATIC DEFINE RHSELPAG01_ESCIND := 145 
STATIC DEFINE RHSELPAG01_ESCIND1 := 152 
STATIC DEFINE RHSELPAG01_ESCLOG := 158 
STATIC DEFINE RHSELPAG01_ESCLOG1 := 182 
STATIC DEFINE RHSELPAG01_ESCLOG2 := 183 
STATIC DEFINE RHSELPAG01_ESCLOG3 := 184 
STATIC DEFINE RHSELPAG01_ESCSITU := 170 
STATIC DEFINE RHSELPAG01_ESCSITU1 := 173 
STATIC DEFINE RHSELPAG01_ESCSITU2 := 176 
STATIC DEFINE RHSELPAG01_ESCSITU3 := 179 
STATIC DEFINE RHSELPAG01_ESTADO := 151 
STATIC DEFINE RHSELPAG01_ESTCIVIL := 127 
STATIC DEFINE RHSELPAG01_EVINC := 181 
STATIC DEFINE RHSELPAG01_FIXEDTEXT15 := 143 
STATIC DEFINE RHSELPAG01_FONE := 113 
STATIC DEFINE RHSELPAG01_FONEREC := 115 
STATIC DEFINE RHSELPAG01_FOTO := 188 
STATIC DEFINE RHSELPAG01_FOTO1 := 186 
STATIC DEFINE RHSELPAG01_IBGE := 106 
STATIC DEFINE RHSELPAG01_INDICACAO := 111 
STATIC DEFINE RHSELPAG01_INDIPARAR := 112 
STATIC DEFINE RHSELPAG01_MAE := 126 
STATIC DEFINE RHSELPAG01_NASC := 121 
STATIC DEFINE RHSELPAG01_NASCIBGE := 122 
STATIC DEFINE RHSELPAG01_NASCPAIS := 123 
STATIC DEFINE RHSELPAG01_NUMEMPANT := 119 
STATIC DEFINE RHSELPAG01_OBS := 129 
STATIC DEFINE RHSELPAG01_PAI := 125 
STATIC DEFINE RHSELPAG01_PROCESSO := 109 
STATIC DEFINE RHSELPAG01_PROCOBS := 110 
STATIC DEFINE RHSELPAG01_RACS := 174 
STATIC DEFINE RHSELPAG01_SC_ADMITIDO1 := 153 
STATIC DEFINE RHSELPAG01_SC_BAIRRO := 131 
STATIC DEFINE RHSELPAG01_SC_CELULAR := 137 
STATIC DEFINE RHSELPAG01_SC_CEP := 133 
STATIC DEFINE RHSELPAG01_SC_CEP1 := 160 
STATIC DEFINE RHSELPAG01_SC_CEP2 := 161 
STATIC DEFINE RHSELPAG01_SC_CEP3 := 162 
STATIC DEFINE RHSELPAG01_SC_CEP4 := 163 
STATIC DEFINE RHSELPAG01_SC_CHAPA5 := 156 
STATIC DEFINE RHSELPAG01_SC_CIDADE := 132 
STATIC DEFINE RHSELPAG01_SC_CONTATO := 139 
STATIC DEFINE RHSELPAG01_SC_DESTINO2 := 187 
STATIC DEFINE RHSELPAG01_SC_DESTINO3 := 185 
STATIC DEFINE RHSELPAG01_SC_EMAIL := 140 
STATIC DEFINE RHSELPAG01_SC_ENDERECO := 130 
STATIC DEFINE RHSELPAG01_SC_ESTADO := 150 
STATIC DEFINE RHSELPAG01_SC_FONE := 136 
STATIC DEFINE RHSELPAG01_SC_FONE1 := 141 
STATIC DEFINE RHSELPAG01_SC_FONEREC := 138 
STATIC DEFINE RHSELPAG01_SC_INDICACAO := 134 
STATIC DEFINE RHSELPAG01_SC_INDICACAO1 := 144 
STATIC DEFINE RHSELPAG01_SC_INDICACAO2 := 154 
STATIC DEFINE RHSELPAG01_SC_INDICACAO3 := 155 
STATIC DEFINE RHSELPAG01_SC_OBS := 135 
STATIC DEFINE RHSELPAG01_SC_SETOR1 := 157 
STATIC DEFINE RHSELPAG01_SC_TIPO := 165 
STATIC DEFINE RHSELPAG01_SC_TIPO1 := 148 
STATIC DEFINE RHSELPAG01_SC_TIPO2 := 167 
STATIC DEFINE RHSELPAG01_SC_UF2 := 142 
STATIC DEFINE RHSELPAG01_SC_UF3 := 171 
STATIC DEFINE RHSELPAG01_SC_UF4 := 175 
STATIC DEFINE RHSELPAG01_SC_UF5 := 177 
STATIC DEFINE RHSELPAG01_SC_UF6 := 180 
STATIC DEFINE RHSELPAG01_SEXO := 147 
STATIC DEFINE RHSELPAG01_SITUACAO := 172 
STATIC DEFINE RHSELPAG01_TIPO := 166 
STATIC DEFINE RHSELPAG02_AGENCIA := 132
STATIC DEFINE RHSELPAG02_APF01 := 120
STATIC DEFINE RHSELPAG02_APF02 := 121
STATIC DEFINE RHSELPAG02_APF03 := 122
STATIC DEFINE RHSELPAG02_BANCO := 131
STATIC DEFINE RHSELPAG02_CATCNH := 111
STATIC DEFINE RHSELPAG02_CHECKCNS := 146
STATIC DEFINE RHSELPAG02_CHECKCPF := 145
STATIC DEFINE RHSELPAG02_CHECKPIS := 149
STATIC DEFINE RHSELPAG02_CHECKRG := 148 
STATIC DEFINE RHSELPAG02_CHECKTIT := 147
STATIC DEFINE RHSELPAG02_CMDCHECKUF := 143
STATIC DEFINE RHSELPAG02_CMDCHECKUF1 := 154
STATIC DEFINE RHSELPAG02_CNH := 110
STATIC DEFINE RHSELPAG02_CNS := 123
STATIC DEFINE RHSELPAG02_CONTA := 133
STATIC DEFINE RHSELPAG02_CONTAFGTS := 134
STATIC DEFINE RHSELPAG02_CPF := 139
STATIC DEFINE RHSELPAG02_CTPSDATA := 109
STATIC DEFINE RHSELPAG02_CTPSUF := 108
STATIC DEFINE RHSELPAG02_ESCLOG1 := 170
STATIC DEFINE RHSELPAG02_ESCLOG2 := 171
STATIC DEFINE RHSELPAG02_ESCRAIS := 114
STATIC DEFINE RHSELPAG02_EXPCNH := 112
STATIC DEFINE RHSELPAG02_FIXEDTEXT3 := 144
STATIC DEFINE RHSELPAG02_FIXEDTEXT4 := 152
STATIC DEFINE RHSELPAG02_FIXEDTEXT7 := 150
STATIC DEFINE RHSELPAG02_FIXEDTEXT8 := 151
STATIC DEFINE RHSELPAG02_FOR01 := 117
STATIC DEFINE RHSELPAG02_FOR02 := 118
STATIC DEFINE RHSELPAG02_FOR03 := 119
STATIC DEFINE RHSELPAG02_GROUPBOX1 := 141
STATIC DEFINE RHSELPAG02_GROUPBOX2 := 142
STATIC DEFINE RHSELPAG02_OC := 127
STATIC DEFINE RHSELPAG02_OCEMI := 128
STATIC DEFINE RHSELPAG02_OCEXP := 129
STATIC DEFINE RHSELPAG02_OCVAL := 130
STATIC DEFINE RHSELPAG02_PIS := 100
STATIC DEFINE RHSELPAG02_PROFIS := 106
STATIC DEFINE RHSELPAG02_RESECAT := 116
STATIC DEFINE RHSELPAG02_RESERV := 115
STATIC DEFINE RHSELPAG02_RG := 101
STATIC DEFINE RHSELPAG02_RGDATA := 105
STATIC DEFINE RHSELPAG02_RGEMIS := 102
STATIC DEFINE RHSELPAG02_RGTIP := 103
STATIC DEFINE RHSELPAG02_RGUF := 104
STATIC DEFINE RHSELPAG02_SC_CATEGORIA := 138
STATIC DEFINE RHSELPAG02_SC_CATEGORIA1 := 157
STATIC DEFINE RHSELPAG02_SC_CATEGORIA10 := 167
STATIC DEFINE RHSELPAG02_SC_CATEGORIA11 := 168
STATIC DEFINE RHSELPAG02_SC_CATEGORIA12 := 169
STATIC DEFINE RHSELPAG02_SC_CATEGORIA2 := 158
STATIC DEFINE RHSELPAG02_SC_CATEGORIA3 := 159
STATIC DEFINE RHSELPAG02_SC_CATEGORIA4 := 160
STATIC DEFINE RHSELPAG02_SC_CATEGORIA5 := 162
STATIC DEFINE RHSELPAG02_SC_CATEGORIA6 := 163
STATIC DEFINE RHSELPAG02_SC_CATEGORIA7 := 164
STATIC DEFINE RHSELPAG02_SC_CATEGORIA8 := 165
STATIC DEFINE RHSELPAG02_SC_CATEGORIA9 := 166
STATIC DEFINE RHSELPAG02_SC_CTPS := 135
STATIC DEFINE RHSELPAG02_SC_ESCOLA := 140
STATIC DEFINE RHSELPAG02_SC_SERIE := 136
STATIC DEFINE RHSELPAG02_SC_SERIE1 := 153
STATIC DEFINE RHSELPAG02_SC_SERIE2 := 155
STATIC DEFINE RHSELPAG02_SC_SERIE3 := 161
STATIC DEFINE RHSELPAG02_SC_UFCTPS := 137
STATIC DEFINE RHSELPAG02_SC_UFCTPS1 := 156
STATIC DEFINE RHSELPAG02_SERIE := 107
STATIC DEFINE RHSELPAG02_SERIE2 := 126
STATIC DEFINE RHSELPAG02_TITULO := 124
STATIC DEFINE RHSELPAG02_TITUZONA := 125
STATIC DEFINE RHSELPAG02_VALCNH := 113
STATIC DEFINE RHSELPAG03_EX01ADM := 104 
STATIC DEFINE RHSELPAG03_EX01AT1 := 107 
STATIC DEFINE RHSELPAG03_EX01AT2 := 108 
STATIC DEFINE RHSELPAG03_EX01DEM := 103 
STATIC DEFINE RHSELPAG03_EX01EMP := 100 
STATIC DEFINE RHSELPAG03_EX01FUN := 105 
STATIC DEFINE RHSELPAG03_EX01RAM := 101 
STATIC DEFINE RHSELPAG03_EX01TEL := 102 
STATIC DEFINE RHSELPAG03_EX01ULT := 106 
STATIC DEFINE RHSELPAG03_EX02ADM := 112 
STATIC DEFINE RHSELPAG03_EX02AT1 := 116 
STATIC DEFINE RHSELPAG03_EX02AT2 := 117 
STATIC DEFINE RHSELPAG03_EX02DEM := 113 
STATIC DEFINE RHSELPAG03_EX02EMP := 109 
STATIC DEFINE RHSELPAG03_EX02FUN := 114 
STATIC DEFINE RHSELPAG03_EX02RAM := 110 
STATIC DEFINE RHSELPAG03_EX02TEL := 111 
STATIC DEFINE RHSELPAG03_EX02ULT := 115 
STATIC DEFINE RHSELPAG03_EX03ADM := 121 
STATIC DEFINE RHSELPAG03_EX03AT1 := 124 
STATIC DEFINE RHSELPAG03_EX03AT2 := 125 
STATIC DEFINE RHSELPAG03_EX03DEM := 122 
STATIC DEFINE RHSELPAG03_EX03EMP := 118 
STATIC DEFINE RHSELPAG03_EX03FUN := 123 
STATIC DEFINE RHSELPAG03_EX03RAM := 119 
STATIC DEFINE RHSELPAG03_EX03TEL := 120 
STATIC DEFINE RHSELPAG03_EX03ULT := 134 
STATIC DEFINE RHSELPAG03_SC_EX01ADM := 130 
STATIC DEFINE RHSELPAG03_SC_EX01ADM1 := 138 
STATIC DEFINE RHSELPAG03_SC_EX01ADM2 := 146 
STATIC DEFINE RHSELPAG03_SC_EX01AT1 := 133 
STATIC DEFINE RHSELPAG03_SC_EX01AT2 := 139 
STATIC DEFINE RHSELPAG03_SC_EX01AT3 := 147 
STATIC DEFINE RHSELPAG03_SC_EX01DEM := 129 
STATIC DEFINE RHSELPAG03_SC_EX01DEM1 := 137 
STATIC DEFINE RHSELPAG03_SC_EX01DEM2 := 145 
STATIC DEFINE RHSELPAG03_SC_EX01EMP := 126 
STATIC DEFINE RHSELPAG03_SC_EX01EMP1 := 142 
STATIC DEFINE RHSELPAG03_SC_EX01EMP2 := 150 
STATIC DEFINE RHSELPAG03_SC_EX01FUN := 131 
STATIC DEFINE RHSELPAG03_SC_EX01FUN1 := 140 
STATIC DEFINE RHSELPAG03_SC_EX01FUN2 := 148 
STATIC DEFINE RHSELPAG03_SC_EX01RAM := 127 
STATIC DEFINE RHSELPAG03_SC_EX01RAM1 := 136 
STATIC DEFINE RHSELPAG03_SC_EX01RAM2 := 143 
STATIC DEFINE RHSELPAG03_SC_EX01TEL := 128 
STATIC DEFINE RHSELPAG03_SC_EX01TEL1 := 141 
STATIC DEFINE RHSELPAG03_SC_EX01TEL2 := 149 
STATIC DEFINE RHSELPAG03_SC_EX01ULT := 132 
STATIC DEFINE RHSELPAG03_SC_EX01ULT1 := 135 
STATIC DEFINE RHSELPAG03_SC_EX01ULT2 := 144 
STATIC DEFINE RHSELPAG04_FUNC01 := 100 
STATIC DEFINE RHSELPAG04_FUNC02 := 102 
STATIC DEFINE RHSELPAG04_OBSEN01 := 103 
STATIC DEFINE RHSELPAG04_OBSEN02 := 104 
STATIC DEFINE RHSELPAG04_OBSEN03 := 105 
STATIC DEFINE RHSELPAG04_SALARIO := 101 
STATIC DEFINE RHSELPAG04_SC_FUNC01 := 106 
STATIC DEFINE RHSELPAG04_SC_OBSEN01 := 108 
STATIC DEFINE RHSELPAG04_SC_SALARIO := 107 
#endregion

PARTIAL CLASS JRHSEL INHERIT MYDataWindow 

	PROTECT oDBNOME AS DataColumn
	PROTECT oDCRHSELTAB AS TABCONTROL
	PROTECT oTPRHSELPAG01 AS RHSELPAG01
	PROTECT oTPRHSELPAG02 AS RHSELPAG02
	PROTECT oTPRHSELPAG04 AS RHSELPAG04
	PROTECT oTPRHSELPAG03 AS RHSELPAG03
	PROTECT oDCSC_FUNCAO AS FIXEDTEXT
	PROTECT oDCNOME AS SINGLELINEEDIT
	PROTECT oDCSC_NOME AS FIXEDTEXT
	PROTECT oCCbuscanom AS PUSHBUTTON
	PROTECT oCCpornome AS PUSHBUTTON
	PROTECT oDCCODMP02 AS COMBOBOX
	PROTECT oDCNUMERO AS SINGLELINEEDIT
	PROTECT oDCSC_NUMERO AS FIXEDTEXT
	PROTECT oDCEMPRESA AS SINGLELINEEDIT
	PROTECT oDCSC_NUMERO1 AS FIXEDTEXT
	PROTECT oCCescfun AS PUSHBUTTON
	PROTECT oDCfuncao AS RIGHTSLE
	PROTECT oDCSC_CHAPA3 AS FIXEDTEXT
	PROTECT oCCescfun1 AS PUSHBUTTON
	PROTECT oDCUNIFUN AS RIGHTSLE
	PROTECT oCCescunid AS PUSHBUTTON
	PROTECT oDCSC_CHAPA2 AS FIXEDTEXT
	PROTECT oDCCCUSTO AS RIGHTSLE
	PROTECT oDCSC_CHAPA1 AS FIXEDTEXT
// 	instance NOME 
// 	instance CODMP02 
// 	instance NUMERO 
// 	instance EMPRESA 
// 	instance funcao 
// 	instance UNIFUN 
// 	instance CCUSTO 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS CCUSTO() 
RETURN SELF:FieldGet(#CCUSTO)


ASSIGN CCUSTO(uValue) 
SELF:FieldPut(#CCUSTO, uValue)
RETURN CCUSTO := uValue


ACCESS CODMP02() 
RETURN SELF:FieldGet(#CODMP02)


ASSIGN CODMP02(uValue) 
SELF:FieldPut(#CODMP02, uValue)
RETURN CODMP02 := uValue


ACCESS EMPRESA() 
RETURN SELF:FieldGet(#EMPRESA)


ASSIGN EMPRESA(uValue) 
SELF:FieldPut(#EMPRESA, uValue)
RETURN EMPRESA := uValue


METHOD escunid( ) 
	LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"UNID.DBF",SELF:SERVER:FIELDGET("UNIFUN")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("UNIFUN",oESC:CODIGO)
ENDIF				

ACCESS funcao() 
RETURN SELF:FieldGet(#funcao)


ASSIGN funcao(uValue) 
SELF:FieldPut(#funcao, uValue)
RETURN funcao := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[1] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JRHSEL",_GetInst()},iCtlID)

aFonts[1] := Font{,12,"Times New Roman"}
aFonts[1]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCRHSELTAB := TabControl{SELF,ResourceID{JRHSEL_RHSELTAB,_GetInst()}}
oDCRHSELTAB:HyperLabel := HyperLabel{#RHSELTAB,NULL_STRING,NULL_STRING,NULL_STRING}

oDCSC_FUNCAO := FixedText{SELF,ResourceID{JRHSEL_SC_FUNCAO,_GetInst()}}
oDCSC_FUNCAO:HyperLabel := HyperLabel{#SC_FUNCAO,"Funcao:",NULL_STRING,NULL_STRING}

oDCNOME := SingleLineEdit{SELF,ResourceID{JRHSEL_NOME,_GetInst()}}
oDCNOME:FieldSpec := PADRAO_CHAR_60{}
oDCNOME:HyperLabel := HyperLabel{#NOME,"Nome:",NULL_STRING,"RHSEL_NOME"}
oDCNOME:Font(aFonts[1], FALSE)
oDCNOME:BackGround := aBrushes[1]

oDCSC_NOME := FixedText{SELF,ResourceID{JRHSEL_SC_NOME,_GetInst()}}
oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME,"Nome:",NULL_STRING,NULL_STRING}

oCCbuscanom := PushButton{SELF,ResourceID{JRHSEL_BUSCANOM,_GetInst()}}
oCCbuscanom:Image := ico_find{}
oCCbuscanom:HyperLabel := HyperLabel{#buscanom,NULL_STRING,NULL_STRING,NULL_STRING}

oCCpornome := PushButton{SELF,ResourceID{JRHSEL_PORNOME,_GetInst()}}
oCCpornome:Image := ico_az{}
oCCpornome:HyperLabel := HyperLabel{#pornome,NULL_STRING,NULL_STRING,NULL_STRING}

oDCCODMP02 := combobox{SELF,ResourceID{JRHSEL_CODMP02,_GetInst()}}
oDCCODMP02:FieldSpec := PADRAO_CHAR_12{}
oDCCODMP02:HyperLabel := HyperLabel{#CODMP02,NULL_STRING,NULL_STRING,NULL_STRING}
oDCCODMP02:FillUsing(SELF:PEGMP02( ))

oDCNUMERO := SingleLineEdit{SELF,ResourceID{JRHSEL_NUMERO,_GetInst()}}
oDCNUMERO:FieldSpec := PADRAO_NUM_08{}
oDCNUMERO:HyperLabel := HyperLabel{#NUMERO,"Numero:",NULL_STRING,"FO_PES_NUMERO"}
oDCNUMERO:BackGround := aBrushes[1]
oDCNUMERO:Font(aFonts[1], FALSE)

oDCSC_NUMERO := FixedText{SELF,ResourceID{JRHSEL_SC_NUMERO,_GetInst()}}
oDCSC_NUMERO:HyperLabel := HyperLabel{#SC_NUMERO,"Numero:",NULL_STRING,NULL_STRING}

oDCEMPRESA := SingleLineEdit{SELF,ResourceID{JRHSEL_EMPRESA,_GetInst()}}
oDCEMPRESA:FieldSpec := PADRAO_NUM_08{}
oDCEMPRESA:HyperLabel := HyperLabel{#EMPRESA,"Numero:",NULL_STRING,"FO_PES_NUMERO"}
oDCEMPRESA:BackGround := aBrushes[1]
oDCEMPRESA:Font(aFonts[1], FALSE)

oDCSC_NUMERO1 := FixedText{SELF,ResourceID{JRHSEL_SC_NUMERO1,_GetInst()}}
oDCSC_NUMERO1:HyperLabel := HyperLabel{#SC_NUMERO1,"Empresa",NULL_STRING,NULL_STRING}

oCCescfun := PushButton{SELF,ResourceID{JRHSEL_ESCFUN,_GetInst()}}
oCCescfun:HyperLabel := HyperLabel{#escfun,"..",NULL_STRING,NULL_STRING}
oCCescfun:Image := ICO_FIND{}

oDCfuncao := rightSle{SELF,ResourceID{JRHSEL_FUNCAO,_GetInst()}}
oDCfuncao:FieldSpec := PADRAO_NUM_04{}
oDCfuncao:HyperLabel := HyperLabel{#funcao,"Chapa:",NULL_STRING,"FO_PES_CHAPA"}

oDCSC_CHAPA3 := FixedText{SELF,ResourceID{JRHSEL_SC_CHAPA3,_GetInst()}}
oDCSC_CHAPA3:HyperLabel := HyperLabel{#SC_CHAPA3,"Funcao:",NULL_STRING,NULL_STRING}

oCCescfun1 := PushButton{SELF,ResourceID{JRHSEL_ESCFUN1,_GetInst()}}
oCCescfun1:HyperLabel := HyperLabel{#escfun1,"..",NULL_STRING,NULL_STRING}
oCCescfun1:Image := ICO_FIND{}

oDCUNIFUN := rightSle{SELF,ResourceID{JRHSEL_UNIFUN,_GetInst()}}
oDCUNIFUN:FieldSpec := PADRAO_char_10{}
oDCUNIFUN:HyperLabel := HyperLabel{#UNIFUN,"Chapa:",NULL_STRING,"FO_PES_CHAPA"}

oCCescunid := PushButton{SELF,ResourceID{JRHSEL_ESCUNID,_GetInst()}}
oCCescunid:HyperLabel := HyperLabel{#escunid,"...",NULL_STRING,NULL_STRING}
oCCescunid:Image := ICO_FIND{}

oDCSC_CHAPA2 := FixedText{SELF,ResourceID{JRHSEL_SC_CHAPA2,_GetInst()}}
oDCSC_CHAPA2:HyperLabel := HyperLabel{#SC_CHAPA2,"Unid.Funcional",NULL_STRING,NULL_STRING}

oDCCCUSTO := rightSle{SELF,ResourceID{JRHSEL_CCUSTO,_GetInst()}}
oDCCCUSTO:FieldSpec := PADRAO_NUM_06{}
oDCCCUSTO:HyperLabel := HyperLabel{#CCUSTO,"Chapa:",NULL_STRING,"FO_PES_CHAPA"}

oDCSC_CHAPA1 := FixedText{SELF,ResourceID{JRHSEL_SC_CHAPA1,_GetInst()}}
oDCSC_CHAPA1:HyperLabel := HyperLabel{#SC_CHAPA1,"CentroCusto",NULL_STRING,NULL_STRING}

SELF:Caption := "Controle de Seleção"
SELF:HyperLabel := HyperLabel{#JRHSEL,"Controle de Seleção",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE
SELF:Menu := STANDARDSHELLMENU{}

IF !IsNil(oServer)
	SELF:Use(oServer)
ENDIF
SELF:Browser := DataBrowser{SELF}

oDBNOME := DataColumn{PADRAO_CHAR_60{}}
oDBNOME:Width := 25
oDBNOME:HyperLabel := oDCNOME:HyperLabel 
oDBNOME:Caption := "Nome:"
oDBNOME:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBNOME)


SELF:ViewAs(#FormView)
oTPRHSELPAG01 := RHSELPAG01{SELF, 0}
oDCRHSELTAB:AppendTab(#RHSELPAG01,"Basicos",oTPRHSELPAG01,0)
oTPRHSELPAG02 := RHSELPAG02{SELF, 0}
oDCRHSELTAB:AppendTab(#RHSELPAG02,"Documento/Escola",oTPRHSELPAG02,0)
oTPRHSELPAG04 := RHSELPAG04{SELF, 0}
oDCRHSELTAB:AppendTab(#RHSELPAG04,"Pretensões/Entrevista",oTPRHSELPAG04,0)
oTPRHSELPAG03 := RHSELPAG03{SELF, 0}
oDCRHSELTAB:AppendTab(#RHSELPAG03,"Ultimos Empregos",oTPRHSELPAG03,0)
oDCRHSELTAB:SelectTab(#RHSELPAG01)

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS NOME() 
RETURN SELF:FieldGet(#NOME)


ASSIGN NOME(uValue) 
SELF:FieldPut(#NOME, uValue)
RETURN NOME := uValue


ACCESS NUMERO() 
RETURN SELF:FieldGet(#NUMERO)


ASSIGN NUMERO(uValue) 
SELF:FieldPut(#NUMERO, uValue)
RETURN NUMERO := uValue


ACCESS UNIFUN() 
RETURN SELF:FieldGet(#UNIFUN)


ASSIGN UNIFUN(uValue) 
SELF:FieldPut(#UNIFUN, uValue)
RETURN UNIFUN := uValue


END CLASS
PARTIAL CLASS RHSELPAG01 INHERIT DATAWINDOW 

	PROTECT oDCENDER AS SINGLELINEEDIT
	PROTECT oDCENDNUM AS RIGHTSLE
	PROTECT oDCENDCOMPL AS RIGHTSLE
	PROTECT oDCBAIRRO AS SINGLELINEEDIT
	PROTECT oDCCEP AS SINGLELINEEDIT
	PROTECT oDCCIDADE AS SINGLELINEEDIT
	PROTECT oDCIBGE AS SINGLELINEEDIT
	PROTECT oDCCOMPARECE AS CHECKBOX
	PROTECT oDCAPROVADO AS CHECKBOX
	PROTECT oDCProcesso AS CHECKBOX
	PROTECT oDCPROCOBS AS SINGLELINEEDIT
	PROTECT oDCINDICACAO AS SINGLELINEEDIT
	PROTECT oDCindiparAR AS SINGLELINEEDIT
	PROTECT oDCFONE AS SINGLELINEEDIT
	PROTECT oDCCELULAR AS SINGLELINEEDIT
	PROTECT oDCFONEREC AS SINGLELINEEDIT
	PROTECT oDCCONTATO AS SINGLELINEEDIT
	PROTECT oDCEMAIL AS SINGLELINEEDIT
	PROTECT oDCDATTRANSF AS DATESLE
	PROTECT oDCNUMEMPANT AS RIGHTSLE
	PROTECT oDCDEPTO2 AS RIGHTSLE
	PROTECT oDCNASC AS DATESLE
	PROTECT oDCnascIBGE AS SINGLELINEEDIT
	PROTECT oDCnascPAIS AS SINGLELINEEDIT
	PROTECT oDCANONASC AS RIGHTSLE
	PROTECT oDCPAI AS SINGLELINEEDIT
	PROTECT oDCMAE AS SINGLELINEEDIT
	PROTECT oDCESTCIVIL AS SINGLELINEEDIT
	PROTECT oDCAPOSENTD AS DATESLE
	PROTECT oDCOBS AS SINGLELINEEDIT
	PROTECT oDCSC_ENDERECO AS FIXEDTEXT
	PROTECT oDCSC_BAIRRO AS FIXEDTEXT
	PROTECT oDCSC_CIDADE AS FIXEDTEXT
	PROTECT oDCSC_CEP AS FIXEDTEXT
	PROTECT oDCSC_INDICACAO AS FIXEDTEXT
	PROTECT oDCSC_OBS AS FIXEDTEXT
	PROTECT oDCSC_FONE AS FIXEDTEXT
	PROTECT oDCSC_CELULAR AS FIXEDTEXT
	PROTECT oDCSC_FONEREC AS FIXEDTEXT
	PROTECT oDCSC_CONTATO AS FIXEDTEXT
	PROTECT oDCSC_EMAIL AS FIXEDTEXT
	PROTECT oDCSC_FONE1 AS FIXEDTEXT
	PROTECT oDCSC_UF2 AS FIXEDTEXT
	PROTECT oDCFixedText15 AS FIXEDTEXT
	PROTECT oDCSC_INDICACAO1 AS FIXEDTEXT
	PROTECT oCCESCIND AS PUSHBUTTON
	PROTECT oCCcmdhora1 AS PUSHBUTTON
	PROTECT oDCSEXO AS SINGLELINEEDIT
	PROTECT oDCSC_TIPO1 AS FIXEDTEXT
	PROTECT oCCCMDCHECKUF AS PUSHBUTTON
	PROTECT oDCSC_ESTADO AS FIXEDTEXT
	PROTECT oDCESTADO AS SINGLELINEEDIT
	PROTECT oCCESCIND1 AS PUSHBUTTON
	PROTECT oDCSC_ADMITIDO1 AS FIXEDTEXT
	PROTECT oDCSC_INDICACAO2 AS FIXEDTEXT
	PROTECT oDCSC_INDICACAO3 AS FIXEDTEXT
	PROTECT oDCSC_CHAPA5 AS FIXEDTEXT
	PROTECT oDCSC_SETOR1 AS FIXEDTEXT
	PROTECT oCCescLOG AS PUSHBUTTON
	PROTECT oDCENDTIP AS SINGLELINEEDIT
	PROTECT oDCSC_CEP1 AS FIXEDTEXT
	PROTECT oDCSC_CEP2 AS FIXEDTEXT
	PROTECT oDCSC_CEP3 AS FIXEDTEXT
	PROTECT oDCSC_CEP4 AS FIXEDTEXT
	PROTECT oCCcmdhora AS PUSHBUTTON
	PROTECT oDCSC_TIPO AS FIXEDTEXT
	PROTECT oDCTIPO AS SINGLELINEEDIT
	PROTECT oDCSC_TIPO2 AS FIXEDTEXT
	PROTECT oCCaposentSIMNAO AS PUSHBUTTON
	PROTECT oDCAPOSENT AS SINGLELINEEDIT
	PROTECT oCCescSITU AS PUSHBUTTON
	PROTECT oDCSC_UF3 AS FIXEDTEXT
	PROTECT oDCSITUACAO AS SINGLELINEEDIT
	PROTECT oCCescSITU1 AS PUSHBUTTON
	PROTECT oDCRACS AS SINGLELINEEDIT
	PROTECT oDCSC_UF4 AS FIXEDTEXT
	PROTECT oCCescSITU2 AS PUSHBUTTON
	PROTECT oDCSC_UF5 AS FIXEDTEXT
	PROTECT oDCDEFICI AS SINGLELINEEDIT
	PROTECT oCCescSITU3 AS PUSHBUTTON
	PROTECT oDCSC_UF6 AS FIXEDTEXT
	PROTECT oDCEVINC AS SINGLELINEEDIT
	PROTECT oCCescLOG1 AS PUSHBUTTON
	PROTECT oCCescLOG2 AS PUSHBUTTON
	PROTECT oCCescLOG3 AS PUSHBUTTON
	PROTECT oDCSC_DESTINO3 AS FIXEDTEXT
	PROTECT oCCfoto1 AS PUSHBUTTON
	PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
	PROTECT oCCfoto AS PUSHBUTTON
// 	instance ENDER 
// 	instance ENDNUM 
// 	instance ENDCOMPL 
// 	instance BAIRRO 
// 	instance CEP 
// 	instance CIDADE 
// 	instance IBGE 
// 	instance COMPARECE 
// 	instance APROVADO 
// 	instance Processo 
// 	instance PROCOBS 
// 	instance INDICACAO 
// 	instance indiparAR 
// 	instance FONE 
// 	instance CELULAR 
// 	instance FONEREC 
// 	instance CONTATO 
// 	instance EMAIL 
// 	instance DATTRANSF 
// 	instance NUMEMPANT 
// 	instance DEPTO2 
// 	instance NASC 
// 	instance nascIBGE 
// 	instance nascPAIS 
// 	instance ANONASC 
// 	instance PAI 
// 	instance MAE 
// 	instance ESTCIVIL 
// 	instance APOSENTD 
// 	instance OBS 
// 	instance SEXO 
// 	instance ESTADO 
// 	instance ENDTIP 
// 	instance TIPO 
// 	instance APOSENT 
// 	instance SITUACAO 
// 	instance RACS 
// 	instance DEFICI 
// 	instance EVINC 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS ANONASC() 
RETURN SELF:FieldGet(#ANONASC)


ASSIGN ANONASC(uValue) 
SELF:FieldPut(#ANONASC, uValue)
RETURN ANONASC := uValue


ACCESS APOSENT() 
RETURN SELF:FieldGet(#APOSENT)


ASSIGN APOSENT(uValue) 
SELF:FieldPut(#APOSENT, uValue)
RETURN APOSENT := uValue


ACCESS APOSENTD() 
RETURN SELF:FieldGet(#APOSENTD)


ASSIGN APOSENTD(uValue) 
SELF:FieldPut(#APOSENTD, uValue)
RETURN APOSENTD := uValue


METHOD aposentSIMNAO( ) 
			SELF:server:FIELDPUT("APOSENT",SIMNAO(SELF:SERVER:FIELDGET("APOSENT"),{"S","N"," "}))	

ACCESS APROVADO() 
RETURN SELF:FieldGet(#APROVADO)


ASSIGN APROVADO(uValue) 
SELF:FieldPut(#APROVADO, uValue)
RETURN APROVADO := uValue


ACCESS BAIRRO() 
RETURN SELF:FieldGet(#BAIRRO)


ASSIGN BAIRRO(uValue) 
SELF:FieldPut(#BAIRRO, uValue)
RETURN BAIRRO := uValue


ACCESS CELULAR() 
RETURN SELF:FieldGet(#CELULAR)


ASSIGN CELULAR(uValue) 
SELF:FieldPut(#CELULAR, uValue)
RETURN CELULAR := uValue


ACCESS CEP() 
RETURN SELF:FieldGet(#CEP)


ASSIGN CEP(uValue) 
SELF:FieldPut(#CEP, uValue)
RETURN CEP := uValue


ACCESS CIDADE() 
RETURN SELF:FieldGet(#CIDADE)


ASSIGN CIDADE(uValue) 
SELF:FieldPut(#CIDADE, uValue)
RETURN CIDADE := uValue


METHOD cmdhora( ) 
	SELF:server:FIELDPUT("TIPO",SIMNAO(SELF:SERVER:FIELDGET("TIPO"),{"M","H"," "}))	

ACCESS COMPARECE() 
RETURN SELF:FieldGet(#COMPARECE)


ASSIGN COMPARECE(uValue) 
SELF:FieldPut(#COMPARECE, uValue)
RETURN COMPARECE := uValue


ACCESS CONTATO() 
RETURN SELF:FieldGet(#CONTATO)


ASSIGN CONTATO(uValue) 
SELF:FieldPut(#CONTATO, uValue)
RETURN CONTATO := uValue


ACCESS DATTRANSF() 
RETURN SELF:FieldGet(#DATTRANSF)


ASSIGN DATTRANSF(uValue) 
SELF:FieldPut(#DATTRANSF, uValue)
RETURN DATTRANSF := uValue


ACCESS DEFICI() 
RETURN SELF:FieldGet(#DEFICI)


ASSIGN DEFICI(uValue) 
SELF:FieldPut(#DEFICI, uValue)
RETURN DEFICI := uValue


ACCESS DEPTO2() 
RETURN SELF:FieldGet(#DEPTO2)


ASSIGN DEPTO2(uValue) 
SELF:FieldPut(#DEPTO2, uValue)
RETURN DEPTO2 := uValue


ACCESS EMAIL() 
RETURN SELF:FieldGet(#EMAIL)


ASSIGN EMAIL(uValue) 
SELF:FieldPut(#EMAIL, uValue)
RETURN EMAIL := uValue


ACCESS ENDCOMPL() 
RETURN SELF:FieldGet(#ENDCOMPL)


ASSIGN ENDCOMPL(uValue) 
SELF:FieldPut(#ENDCOMPL, uValue)
RETURN ENDCOMPL := uValue


ACCESS ENDER() 
RETURN SELF:FieldGet(#ENDER)


ASSIGN ENDER(uValue) 
SELF:FieldPut(#ENDER, uValue)
RETURN ENDER := uValue


ACCESS ENDNUM() 
RETURN SELF:FieldGet(#ENDNUM)


ASSIGN ENDNUM(uValue) 
SELF:FieldPut(#ENDNUM, uValue)
RETURN ENDNUM := uValue


ACCESS ENDTIP() 
RETURN SELF:FieldGet(#ENDTIP)


ASSIGN ENDTIP(uValue) 
SELF:FieldPut(#ENDTIP, uValue)
RETURN ENDTIP := uValue


METHOD escLOG( ) 
LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"ELOG",SELF:SERVER:FIELDGET("ENDTIP")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("ENDTIP",oESC:cCODIGO)
ENDIF									

METHOD escLOG1( ) 
LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"UF",SELF:SERVER:FIELDGET("ESTADO")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("ESTADO",oESC:cCODIGO)
ENDIF									

METHOD escLOG2( ) 
LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"ECIV",SELF:SERVER:FIELDGET("ESTCIVIL")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("ESTCIVIL",oESC:cCODIGO)
ENDIF									

METHOD escLOG3( ) 
LOCAL oESC AS XESCFO_TAB
AltD()
oESC:=XESCFO_TAB{SELF,"TSA2",SELF:SERVER:FIELDGET("TIPO")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("TIPO",oESC:cCODIGO)
ENDIF									
	
	
	
	

METHOD escSITU( ) 
LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"SITU",SELF:SERVER:FIELDGET("SITUACAO")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("SITUACAO",oESC:cCODIGO)
ENDIF	

METHOD escSITU1( ) 
	LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"RACS",SELF:SERVER:FIELDGET("RACS")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("RACS",oESC:cCODIGO)
ENDIF	

METHOD escSITU2( ) 
LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"DEFI",SELF:SERVER:FIELDGET("DEFICI")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("DEFICI",oESC:cCODIGO)
ENDIF	

METHOD escSITU3( ) 
	LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"EVIN",SELF:SERVER:FIELDGET("EVINC")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("EVINC",oESC:cCODIGO)
ENDIF	
	

ACCESS ESTADO() 
RETURN SELF:FieldGet(#ESTADO)


ASSIGN ESTADO(uValue) 
SELF:FieldPut(#ESTADO, uValue)
RETURN ESTADO := uValue


ACCESS ESTCIVIL() 
RETURN SELF:FieldGet(#ESTCIVIL)


ASSIGN ESTCIVIL(uValue) 
SELF:FieldPut(#ESTCIVIL, uValue)
RETURN ESTCIVIL := uValue


ACCESS EVINC() 
RETURN SELF:FieldGet(#EVINC)


ASSIGN EVINC(uValue) 
SELF:FieldPut(#EVINC, uValue)
RETURN EVINC := uValue


ACCESS FONE() 
RETURN SELF:FieldGet(#FONE)


ASSIGN FONE(uValue) 
SELF:FieldPut(#FONE, uValue)
RETURN FONE := uValue


ACCESS FONEREC() 
RETURN SELF:FieldGet(#FONEREC)


ASSIGN FONEREC(uValue) 
SELF:FieldPut(#FONEREC, uValue)
RETURN FONEREC := uValue


METHOD foto( ) 
LOCAL cDIRFOTO  AS STRING
LOCAL cCPF AS STRING
LOCAL cARQ AS STRING
LOCAL nFout AS PTR
cCPF:=SELF:SERVER:FIELDGET("CPF")
IF Valcpf(cCPF)
	cDIRFOTO :=PEGINIVAL(ZCURINI,"FOTOS","FUNJPGCPF")		
	cDIRFOTO+="$"+StrZero(Val(TIRAOUT(cCPF)),11)+".jpg"
ENDIF
cARQ:=PEGINIVAL(ZCURINI,"PATH","IMGJPG")
nFout := ShellExecute(SELF:owner:handle(),String2Psz("open"),String2Psz("IMGJPG"),String2Psz(CCODIGO+"#"+cDIRFOTO+"${IMGMP04CPF}"),String2Psz(carq),SW_SHOWNORMAL)
ShellExecuteErro(nFout) 
			

METHOD foto1( ) 
LOCAL OFOTOVIEW AS FOTOVIEW
LOCAL cDIRFOTO,cTITULO AS STRING
cDIRFOTO:=PEGINIVAL(ZCURINI,"FOTOS","FUNJPGCPF")		
cDIRFOTO:=cDIRFOTO+StrZero(Val(TIRAOUT(SELF:SERVER:FIELDGET("CPF"))),11)+".JPG"	
cTITULO:="CPF:"+SELF:SERVER:FIELDGET("CPF")+"-"+SELF:SERVER:FIELDGET("NOME")	
OFOTOVIEW:=fotoview{SELF,cDIRFOTO,cTITULO}
OFOTOVIEW:SHOW()		

ACCESS IBGE() 
RETURN SELF:FieldGet(#IBGE)


ASSIGN IBGE(uValue) 
SELF:FieldPut(#IBGE, uValue)
RETURN IBGE := uValue


ACCESS INDICACAO() 
RETURN SELF:FieldGet(#INDICACAO)


ASSIGN INDICACAO(uValue) 
SELF:FieldPut(#INDICACAO, uValue)
RETURN INDICACAO := uValue


ACCESS indiparAR() 
RETURN SELF:FieldGet(#indiparAR)


ASSIGN indiparAR(uValue) 
SELF:FieldPut(#indiparAR, uValue)
RETURN indiparAR := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[2] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"RHSELPAG01",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Times New Roman"}
aFonts[1]:Bold := TRUE
aFonts[2] := Font{,10,"Times New Roman"}
aBrushes[1] := Brush{Color{255,255,200}}

oDCENDER := SingleLineEdit{SELF,ResourceID{RHSELPAG01_ENDER,_GetInst()}}
oDCENDER:FieldSpec := PADRAO_CHAR_40{}
oDCENDER:HyperLabel := HyperLabel{#ENDER,"Endereco:",NULL_STRING,"RHSEL_ENDERECO"}

oDCENDNUM := rightSle{SELF,ResourceID{RHSELPAG01_ENDNUM,_GetInst()}}
oDCENDNUM:FieldSpec := PADRAO_char_10{}
oDCENDNUM:HyperLabel := HyperLabel{#ENDNUM,"Chapa:",NULL_STRING,"FO_PES_CHAPA"}

oDCENDCOMPL := rightSle{SELF,ResourceID{RHSELPAG01_ENDCOMPL,_GetInst()}}
oDCENDCOMPL:FieldSpec := PADRAO_char_30{}
oDCENDCOMPL:HyperLabel := HyperLabel{#ENDCOMPL,"Complemento",NULL_STRING,"FO_PES_CHAPA"}

oDCBAIRRO := SingleLineEdit{SELF,ResourceID{RHSELPAG01_BAIRRO,_GetInst()}}
oDCBAIRRO:FieldSpec := PADRAO_CHAR_20{}
oDCBAIRRO:HyperLabel := HyperLabel{#BAIRRO,"Bairro:",NULL_STRING,"RHSEL_BAIRRO"}

oDCCEP := SingleLineEdit{SELF,ResourceID{RHSELPAG01_CEP,_GetInst()}}
oDCCEP:FieldSpec := PADRAO_CHAR_09{}
oDCCEP:HyperLabel := HyperLabel{#CEP,"Cep:",NULL_STRING,"RHSEL_CEP"}

oDCCIDADE := SingleLineEdit{SELF,ResourceID{RHSELPAG01_CIDADE,_GetInst()}}
oDCCIDADE:FieldSpec := PADRAO_CHAR_30{}
oDCCIDADE:HyperLabel := HyperLabel{#CIDADE,"Cidade:",NULL_STRING,"RHSEL_CIDADE"}

oDCIBGE := SingleLineEdit{SELF,ResourceID{RHSELPAG01_IBGE,_GetInst()}}
oDCIBGE:FieldSpec := PADRAO_CHAR_07{}
oDCIBGE:HyperLabel := HyperLabel{#IBGE,"Cep:",NULL_STRING,"RHSEL_CEP"}

oDCCOMPARECE := CheckBox{SELF,ResourceID{RHSELPAG01_COMPARECE,_GetInst()}}
oDCCOMPARECE:HyperLabel := HyperLabel{#COMPARECE,"Compareceu",NULL_STRING,"RHSEL_COMPARECE"}
oDCCOMPARECE:FieldSpec := LOGIC_FIELD{}

oDCAPROVADO := CheckBox{SELF,ResourceID{RHSELPAG01_APROVADO,_GetInst()}}
oDCAPROVADO:HyperLabel := HyperLabel{#APROVADO,"Aprovado",NULL_STRING,"RHSEL_APROVADO"}
oDCAPROVADO:FieldSpec := LOGIC_FIELD{}

oDCProcesso := CheckBox{SELF,ResourceID{RHSELPAG01_PROCESSO,_GetInst()}}
oDCProcesso:HyperLabel := HyperLabel{#Processo,"Processo",NULL_STRING,"RHSEL_APROVADO"}
oDCProcesso:FieldSpec := LOGIC_FIELD{}

oDCPROCOBS := SingleLineEdit{SELF,ResourceID{RHSELPAG01_PROCOBS,_GetInst()}}
oDCPROCOBS:FieldSpec := PADRAO_CHAR_80{}
oDCPROCOBS:HyperLabel := HyperLabel{#PROCOBS,"Cidade:",NULL_STRING,"RHSEL_CIDADE"}

oDCINDICACAO := SingleLineEdit{SELF,ResourceID{RHSELPAG01_INDICACAO,_GetInst()}}
oDCINDICACAO:FieldSpec := PADRAO_CHAR_30{}
oDCINDICACAO:HyperLabel := HyperLabel{#INDICACAO,"Indicacao:",NULL_STRING,"RHSEL_INDICACAO"}

oDCindiparAR := SingleLineEdit{SELF,ResourceID{RHSELPAG01_INDIPARAR,_GetInst()}}
oDCindiparAR:FieldSpec := PADRAO_CHAR_40{}
oDCindiparAR:HyperLabel := HyperLabel{#indiparAR,"Indicacao:",NULL_STRING,"RHSEL_INDICACAO"}

oDCFONE := SingleLineEdit{SELF,ResourceID{RHSELPAG01_FONE,_GetInst()}}
oDCFONE:FieldSpec := PADRAO_CHAR_14{}
oDCFONE:HyperLabel := HyperLabel{#FONE,"Fone:",NULL_STRING,"RHSEL_FONE"}

oDCCELULAR := SingleLineEdit{SELF,ResourceID{RHSELPAG01_CELULAR,_GetInst()}}
oDCCELULAR:FieldSpec := PADRAO_CHAR_14{}
oDCCELULAR:HyperLabel := HyperLabel{#CELULAR,"Celular:",NULL_STRING,"RHSEL_CELULAR"}

oDCFONEREC := SingleLineEdit{SELF,ResourceID{RHSELPAG01_FONEREC,_GetInst()}}
oDCFONEREC:FieldSpec := PADRAO_CHAR_14{}
oDCFONEREC:HyperLabel := HyperLabel{#FONEREC,"Fonerec:",NULL_STRING,"RHSEL_FONEREC"}

oDCCONTATO := SingleLineEdit{SELF,ResourceID{RHSELPAG01_CONTATO,_GetInst()}}
oDCCONTATO:FieldSpec := PADRAO_cHAR_30{}
oDCCONTATO:HyperLabel := HyperLabel{#CONTATO,"Contato:",NULL_STRING,"RHSEL_CONTATO"}

oDCEMAIL := SingleLineEdit{SELF,ResourceID{RHSELPAG01_EMAIL,_GetInst()}}
oDCEMAIL:FieldSpec := email_field{}
oDCEMAIL:HyperLabel := HyperLabel{#EMAIL,"Email:",NULL_STRING,"RHSEL_EMAIL"}

oDCDATTRANSF := DateSle{SELF,ResourceID{RHSELPAG01_DATTRANSF,_GetInst()}}
oDCDATTRANSF:FieldSpec := DATE_FIELD{}
oDCDATTRANSF:HyperLabel := HyperLabel{#DATTRANSF,"Admitido:",NULL_STRING,"FO_PES_ADMITIDO"}

oDCNUMEMPANT := rightSle{SELF,ResourceID{RHSELPAG01_NUMEMPANT,_GetInst()}}
oDCNUMEMPANT:FieldSpec := PADRAO_NUM_03{}
oDCNUMEMPANT:HyperLabel := HyperLabel{#NUMEMPANT,"Dep",NULL_STRING,"FO_PES_DEPTO"}

oDCDEPTO2 := rightSle{SELF,ResourceID{RHSELPAG01_DEPTO2,_GetInst()}}
oDCDEPTO2:FieldSpec := PADRAO_NUM_05{}
oDCDEPTO2:HyperLabel := HyperLabel{#DEPTO2,"NUMREGANT",NULL_STRING,"FO_PES_DEPTO"}

oDCNASC := DateSle{SELF,ResourceID{RHSELPAG01_NASC,_GetInst()}}
oDCNASC:FieldSpec := DATE_FIELD{}
oDCNASC:HyperLabel := HyperLabel{#NASC,"Fone:",NULL_STRING,"RHSEL_FONE"}

oDCnascIBGE := SingleLineEdit{SELF,ResourceID{RHSELPAG01_NASCIBGE,_GetInst()}}
oDCnascIBGE:FieldSpec := PADRAO_CHAR_07{}
oDCnascIBGE:HyperLabel := HyperLabel{#nascIBGE,"Cep:",NULL_STRING,"RHSEL_CEP"}

oDCnascPAIS := SingleLineEdit{SELF,ResourceID{RHSELPAG01_NASCPAIS,_GetInst()}}
oDCnascPAIS:FieldSpec := PADRAO_CHAR_04{}
oDCnascPAIS:HyperLabel := HyperLabel{#nascPAIS,"Cep:",NULL_STRING,"RHSEL_CEP"}

oDCANONASC := rightSle{SELF,ResourceID{RHSELPAG01_ANONASC,_GetInst()}}
oDCANONASC:FieldSpec := PADRAO_NUM_04{}
oDCANONASC:HyperLabel := HyperLabel{#ANONASC,"NUMREGANT",NULL_STRING,"FO_PES_DEPTO"}

oDCPAI := SingleLineEdit{SELF,ResourceID{RHSELPAG01_PAI,_GetInst()}}
oDCPAI:FieldSpec := PADRAO_CHAR_60{}
oDCPAI:HyperLabel := HyperLabel{#PAI,"PAI",NULL_STRING,"RHSEL_INDICACAO"}

oDCMAE := SingleLineEdit{SELF,ResourceID{RHSELPAG01_MAE,_GetInst()}}
oDCMAE:FieldSpec := PADRAO_CHAR_60{}
oDCMAE:HyperLabel := HyperLabel{#MAE,"MAE",NULL_STRING,"RHSEL_INDICACAO"}

oDCESTCIVIL := SingleLineEdit{SELF,ResourceID{RHSELPAG01_ESTCIVIL,_GetInst()}}
oDCESTCIVIL:FieldSpec := PADRAO_CHAR_01{}
oDCESTCIVIL:HyperLabel := HyperLabel{#ESTCIVIL,"Uf:",NULL_STRING,"RHSEL_UF"}

oDCAPOSENTD := DateSle{SELF,ResourceID{RHSELPAG01_APOSENTD,_GetInst()}}
oDCAPOSENTD:FieldSpec := DATE_FIELD{}
oDCAPOSENTD:HyperLabel := HyperLabel{#APOSENTD,"Admitido:",NULL_STRING,"FO_PES_ADMITIDO"}

oDCOBS := SingleLineEdit{SELF,ResourceID{RHSELPAG01_OBS,_GetInst()}}
oDCOBS:FieldSpec := PADRAO_CHAR_80{}
oDCOBS:HyperLabel := HyperLabel{#OBS,"Obs:",NULL_STRING,"RHSEL_OBS"}

oDCSC_ENDERECO := FixedText{SELF,ResourceID{RHSELPAG01_SC_ENDERECO,_GetInst()}}
oDCSC_ENDERECO:HyperLabel := HyperLabel{#SC_ENDERECO,"Endereco:",NULL_STRING,NULL_STRING}

oDCSC_BAIRRO := FixedText{SELF,ResourceID{RHSELPAG01_SC_BAIRRO,_GetInst()}}
oDCSC_BAIRRO:HyperLabel := HyperLabel{#SC_BAIRRO,"Bairro:",NULL_STRING,NULL_STRING}

oDCSC_CIDADE := FixedText{SELF,ResourceID{RHSELPAG01_SC_CIDADE,_GetInst()}}
oDCSC_CIDADE:HyperLabel := HyperLabel{#SC_CIDADE,"Cidade:",NULL_STRING,NULL_STRING}

oDCSC_CEP := FixedText{SELF,ResourceID{RHSELPAG01_SC_CEP,_GetInst()}}
oDCSC_CEP:HyperLabel := HyperLabel{#SC_CEP,"Cep:",NULL_STRING,NULL_STRING}

oDCSC_INDICACAO := FixedText{SELF,ResourceID{RHSELPAG01_SC_INDICACAO,_GetInst()}}
oDCSC_INDICACAO:HyperLabel := HyperLabel{#SC_INDICACAO,"Indicacao:",NULL_STRING,NULL_STRING}

oDCSC_OBS := FixedText{SELF,ResourceID{RHSELPAG01_SC_OBS,_GetInst()}}
oDCSC_OBS:HyperLabel := HyperLabel{#SC_OBS,"Obs:",NULL_STRING,NULL_STRING}

oDCSC_FONE := FixedText{SELF,ResourceID{RHSELPAG01_SC_FONE,_GetInst()}}
oDCSC_FONE:HyperLabel := HyperLabel{#SC_FONE,"Fone:",NULL_STRING,NULL_STRING}

oDCSC_CELULAR := FixedText{SELF,ResourceID{RHSELPAG01_SC_CELULAR,_GetInst()}}
oDCSC_CELULAR:HyperLabel := HyperLabel{#SC_CELULAR,"Celular:",NULL_STRING,NULL_STRING}

oDCSC_FONEREC := FixedText{SELF,ResourceID{RHSELPAG01_SC_FONEREC,_GetInst()}}
oDCSC_FONEREC:HyperLabel := HyperLabel{#SC_FONEREC,"Fone Recados:",NULL_STRING,NULL_STRING}

oDCSC_CONTATO := FixedText{SELF,ResourceID{RHSELPAG01_SC_CONTATO,_GetInst()}}
oDCSC_CONTATO:HyperLabel := HyperLabel{#SC_CONTATO,"Contato:",NULL_STRING,NULL_STRING}

oDCSC_EMAIL := FixedText{SELF,ResourceID{RHSELPAG01_SC_EMAIL,_GetInst()}}
oDCSC_EMAIL:HyperLabel := HyperLabel{#SC_EMAIL,"Email:",NULL_STRING,NULL_STRING}

oDCSC_FONE1 := FixedText{SELF,ResourceID{RHSELPAG01_SC_FONE1,_GetInst()}}
oDCSC_FONE1:HyperLabel := HyperLabel{#SC_FONE1,"Nascimento",NULL_STRING,NULL_STRING}

oDCSC_UF2 := FixedText{SELF,ResourceID{RHSELPAG01_SC_UF2,_GetInst()}}
oDCSC_UF2:HyperLabel := HyperLabel{#SC_UF2,"Estado Civil",NULL_STRING,NULL_STRING}

oDCFixedText15 := FixedText{SELF,ResourceID{RHSELPAG01_FIXEDTEXT15,_GetInst()}}
oDCFixedText15:HyperLabel := HyperLabel{#FixedText15,"(S)olteiro (C)asado (V)iuvo Des(Q)uitado (D)ivorciado (U)niao estavel (O)utros se(P)arado (M)arital",NULL_STRING,NULL_STRING}

oDCSC_INDICACAO1 := FixedText{SELF,ResourceID{RHSELPAG01_SC_INDICACAO1,_GetInst()}}
oDCSC_INDICACAO1:HyperLabel := HyperLabel{#SC_INDICACAO1,"Parentesco",NULL_STRING,NULL_STRING}

oCCESCIND := PushButton{SELF,ResourceID{RHSELPAG01_ESCIND,_GetInst()}}
oCCESCIND:HyperLabel := HyperLabel{#ESCIND,"...",NULL_STRING,NULL_STRING}

oCCcmdhora1 := PushButton{SELF,ResourceID{RHSELPAG01_CMDHORA1,_GetInst()}}
oCCcmdhora1:HyperLabel := HyperLabel{#cmdhora1,"(M)asculino (F)eminino",NULL_STRING,NULL_STRING}

oDCSEXO := SingleLineEdit{SELF,ResourceID{RHSELPAG01_SEXO,_GetInst()}}
oDCSEXO:FieldSpec := PADRAO_CHAR_01{}
oDCSEXO:HyperLabel := HyperLabel{#SEXO,"Tipo:",NULL_STRING,"FO_PES_TIPO"}
oDCSEXO:BackGround := aBrushes[1]
oDCSEXO:Font(aFonts[1], FALSE)

oDCSC_TIPO1 := FixedText{SELF,ResourceID{RHSELPAG01_SC_TIPO1,_GetInst()}}
oDCSC_TIPO1:HyperLabel := HyperLabel{#SC_TIPO1,"Sexo",NULL_STRING,NULL_STRING}

oCCCMDCHECKUF := PushButton{SELF,ResourceID{RHSELPAG01_CMDCHECKUF,_GetInst()}}
oCCCMDCHECKUF:HyperLabel := HyperLabel{#CMDCHECKUF,"Checar",NULL_STRING,NULL_STRING}

oDCSC_ESTADO := FixedText{SELF,ResourceID{RHSELPAG01_SC_ESTADO,_GetInst()}}
oDCSC_ESTADO:HyperLabel := HyperLabel{#SC_ESTADO,"UF:",NULL_STRING,NULL_STRING}

oDCESTADO := SingleLineEdit{SELF,ResourceID{RHSELPAG01_ESTADO,_GetInst()}}
oDCESTADO:FieldSpec := uf_field{}
oDCESTADO:HyperLabel := HyperLabel{#ESTADO,"Numero:",NULL_STRING,"MA01_NUMERO"}
oDCESTADO:TooltipText := "Digite  o Estado"

oCCESCIND1 := PushButton{SELF,ResourceID{RHSELPAG01_ESCIND1,_GetInst()}}
oCCESCIND1:HyperLabel := HyperLabel{#ESCIND1,"...",NULL_STRING,NULL_STRING}

oDCSC_ADMITIDO1 := FixedText{SELF,ResourceID{RHSELPAG01_SC_ADMITIDO1,_GetInst()}}
oDCSC_ADMITIDO1:HyperLabel := HyperLabel{#SC_ADMITIDO1,"Transferencia",NULL_STRING,NULL_STRING}

oDCSC_INDICACAO2 := FixedText{SELF,ResourceID{RHSELPAG01_SC_INDICACAO2,_GetInst()}}
oDCSC_INDICACAO2:HyperLabel := HyperLabel{#SC_INDICACAO2,"PaI",NULL_STRING,NULL_STRING}

oDCSC_INDICACAO3 := FixedText{SELF,ResourceID{RHSELPAG01_SC_INDICACAO3,_GetInst()}}
oDCSC_INDICACAO3:HyperLabel := HyperLabel{#SC_INDICACAO3,"MAE",NULL_STRING,NULL_STRING}

oDCSC_CHAPA5 := FixedText{SELF,ResourceID{RHSELPAG01_SC_CHAPA5,_GetInst()}}
oDCSC_CHAPA5:HyperLabel := HyperLabel{#SC_CHAPA5,"Compl",NULL_STRING,NULL_STRING}

oDCSC_SETOR1 := FixedText{SELF,ResourceID{RHSELPAG01_SC_SETOR1,_GetInst()}}
oDCSC_SETOR1:HyperLabel := HyperLabel{#SC_SETOR1,"No.",NULL_STRING,NULL_STRING}

oCCescLOG := PushButton{SELF,ResourceID{RHSELPAG01_ESCLOG,_GetInst()}}
oCCescLOG:HyperLabel := HyperLabel{#escLOG,"..",NULL_STRING,NULL_STRING}
oCCescLOG:Image := ICO_FIND{}

oDCENDTIP := SingleLineEdit{SELF,ResourceID{RHSELPAG01_ENDTIP,_GetInst()}}
oDCENDTIP:FieldSpec := PADRAO_char_02{}
oDCENDTIP:HyperLabel := HyperLabel{#ENDTIP,"Uf:",NULL_STRING,"RHSEL_UF"}
oDCENDTIP:BackGround := aBrushes[1]
oDCENDTIP:Font(aFonts[2], FALSE)

oDCSC_CEP1 := FixedText{SELF,ResourceID{RHSELPAG01_SC_CEP1,_GetInst()}}
oDCSC_CEP1:HyperLabel := HyperLabel{#SC_CEP1,"ibge:",NULL_STRING,NULL_STRING}

oDCSC_CEP2 := FixedText{SELF,ResourceID{RHSELPAG01_SC_CEP2,_GetInst()}}
oDCSC_CEP2:HyperLabel := HyperLabel{#SC_CEP2,"ibge:",NULL_STRING,NULL_STRING}

oDCSC_CEP3 := FixedText{SELF,ResourceID{RHSELPAG01_SC_CEP3,_GetInst()}}
oDCSC_CEP3:HyperLabel := HyperLabel{#SC_CEP3,"PAIS",NULL_STRING,NULL_STRING}

oDCSC_CEP4 := FixedText{SELF,ResourceID{RHSELPAG01_SC_CEP4,_GetInst()}}
oDCSC_CEP4:HyperLabel := HyperLabel{#SC_CEP4,"AnoChegada",NULL_STRING,NULL_STRING}

oCCcmdhora := PushButton{SELF,ResourceID{RHSELPAG01_CMDHORA,_GetInst()}}
oCCcmdhora:HyperLabel := HyperLabel{#cmdhora,"M-es H-ora",NULL_STRING,NULL_STRING}

oDCSC_TIPO := FixedText{SELF,ResourceID{RHSELPAG01_SC_TIPO,_GetInst()}}
oDCSC_TIPO:HyperLabel := HyperLabel{#SC_TIPO,"Tipo:",NULL_STRING,NULL_STRING}

oDCTIPO := SingleLineEdit{SELF,ResourceID{RHSELPAG01_TIPO,_GetInst()}}
oDCTIPO:FieldSpec := PADRAO_CHAR_01{}
oDCTIPO:HyperLabel := HyperLabel{#TIPO,"Tipo:",NULL_STRING,"FO_PES_TIPO"}
oDCTIPO:BackGround := aBrushes[1]
oDCTIPO:Font(aFonts[1], FALSE)

oDCSC_TIPO2 := FixedText{SELF,ResourceID{RHSELPAG01_SC_TIPO2,_GetInst()}}
oDCSC_TIPO2:HyperLabel := HyperLabel{#SC_TIPO2,"Aposentado:",NULL_STRING,NULL_STRING}

oCCaposentSIMNAO := PushButton{SELF,ResourceID{RHSELPAG01_APOSENTSIMNAO,_GetInst()}}
oCCaposentSIMNAO:HyperLabel := HyperLabel{#aposentSIMNAO,"S-im N-ao",NULL_STRING,NULL_STRING}

oDCAPOSENT := SingleLineEdit{SELF,ResourceID{RHSELPAG01_APOSENT,_GetInst()}}
oDCAPOSENT:FieldSpec := PADRAO_CHAR_01{}
oDCAPOSENT:HyperLabel := HyperLabel{#APOSENT,"Tipo:",NULL_STRING,"FO_PES_TIPO"}
oDCAPOSENT:BackGround := aBrushes[1]
oDCAPOSENT:Font(aFonts[1], FALSE)

oCCescSITU := PushButton{SELF,ResourceID{RHSELPAG01_ESCSITU,_GetInst()}}
oCCescSITU:HyperLabel := HyperLabel{#escSITU,"...",NULL_STRING,NULL_STRING}
oCCescSITU:Image := ICO_FIND{}

oDCSC_UF3 := FixedText{SELF,ResourceID{RHSELPAG01_SC_UF3,_GetInst()}}
oDCSC_UF3:HyperLabel := HyperLabel{#SC_UF3,"Situacao",NULL_STRING,NULL_STRING}

oDCSITUACAO := SingleLineEdit{SELF,ResourceID{RHSELPAG01_SITUACAO,_GetInst()}}
oDCSITUACAO:FieldSpec := PADRAO_CHAR_01{}
oDCSITUACAO:HyperLabel := HyperLabel{#SITUACAO,NULL_STRING,NULL_STRING,"RHSEL_UF"}
oDCSITUACAO:BackGround := aBrushes[1]
oDCSITUACAO:Font(aFonts[2], FALSE)

oCCescSITU1 := PushButton{SELF,ResourceID{RHSELPAG01_ESCSITU1,_GetInst()}}
oCCescSITU1:HyperLabel := HyperLabel{#escSITU1,"...",NULL_STRING,NULL_STRING}
oCCescSITU1:Image := ICO_FIND{}

oDCRACS := SingleLineEdit{SELF,ResourceID{RHSELPAG01_RACS,_GetInst()}}
oDCRACS:FieldSpec := PADRAO_CHAR_01{}
oDCRACS:HyperLabel := HyperLabel{#RACS,NULL_STRING,NULL_STRING,"RHSEL_UF"}
oDCRACS:BackGround := aBrushes[1]
oDCRACS:Font(aFonts[2], FALSE)

oDCSC_UF4 := FixedText{SELF,ResourceID{RHSELPAG01_SC_UF4,_GetInst()}}
oDCSC_UF4:HyperLabel := HyperLabel{#SC_UF4,"Etinia",NULL_STRING,NULL_STRING}

oCCescSITU2 := PushButton{SELF,ResourceID{RHSELPAG01_ESCSITU2,_GetInst()}}
oCCescSITU2:HyperLabel := HyperLabel{#escSITU2,"...",NULL_STRING,NULL_STRING}
oCCescSITU2:Image := ICO_FIND{}

oDCSC_UF5 := FixedText{SELF,ResourceID{RHSELPAG01_SC_UF5,_GetInst()}}
oDCSC_UF5:HyperLabel := HyperLabel{#SC_UF5,"Necessidade Especial",NULL_STRING,NULL_STRING}

oDCDEFICI := SingleLineEdit{SELF,ResourceID{RHSELPAG01_DEFICI,_GetInst()}}
oDCDEFICI:FieldSpec := PADRAO_CHAR_01{}
oDCDEFICI:HyperLabel := HyperLabel{#DEFICI,NULL_STRING,NULL_STRING,"RHSEL_UF"}
oDCDEFICI:BackGround := aBrushes[1]
oDCDEFICI:Font(aFonts[2], FALSE)

oCCescSITU3 := PushButton{SELF,ResourceID{RHSELPAG01_ESCSITU3,_GetInst()}}
oCCescSITU3:HyperLabel := HyperLabel{#escSITU3,"...",NULL_STRING,NULL_STRING}
oCCescSITU3:Image := ICO_FIND{}

oDCSC_UF6 := FixedText{SELF,ResourceID{RHSELPAG01_SC_UF6,_GetInst()}}
oDCSC_UF6:HyperLabel := HyperLabel{#SC_UF6,"Vinculo",NULL_STRING,NULL_STRING}

oDCEVINC := SingleLineEdit{SELF,ResourceID{RHSELPAG01_EVINC,_GetInst()}}
oDCEVINC:FieldSpec := PADRAO_CHAR_01{}
oDCEVINC:HyperLabel := HyperLabel{#EVINC,NULL_STRING,NULL_STRING,"RHSEL_UF"}
oDCEVINC:BackGround := aBrushes[1]
oDCEVINC:Font(aFonts[2], FALSE)

oCCescLOG1 := PushButton{SELF,ResourceID{RHSELPAG01_ESCLOG1,_GetInst()}}
oCCescLOG1:HyperLabel := HyperLabel{#escLOG1,"..",NULL_STRING,NULL_STRING}
oCCescLOG1:Image := ICO_FIND{}

oCCescLOG2 := PushButton{SELF,ResourceID{RHSELPAG01_ESCLOG2,_GetInst()}}
oCCescLOG2:HyperLabel := HyperLabel{#escLOG2,"..",NULL_STRING,NULL_STRING}
oCCescLOG2:Image := ICO_FIND{}

oCCescLOG3 := PushButton{SELF,ResourceID{RHSELPAG01_ESCLOG3,_GetInst()}}
oCCescLOG3:HyperLabel := HyperLabel{#escLOG3,"..",NULL_STRING,NULL_STRING}
oCCescLOG3:Image := ICO_FIND{}

oDCSC_DESTINO3 := FixedText{SELF,ResourceID{RHSELPAG01_SC_DESTINO3,_GetInst()}}
oDCSC_DESTINO3:HyperLabel := HyperLabel{#SC_DESTINO3,"Foto Ver",NULL_STRING,NULL_STRING}

oCCfoto1 := PushButton{SELF,ResourceID{RHSELPAG01_FOTO1,_GetInst()}}
oCCfoto1:HyperLabel := HyperLabel{#foto1,"...",NULL_STRING,NULL_STRING}
oCCfoto1:Image := ico_camera{}

oDCSC_DESTINO2 := FixedText{SELF,ResourceID{RHSELPAG01_SC_DESTINO2,_GetInst()}}
oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2,"Foto Editar",NULL_STRING,NULL_STRING}

oCCfoto := PushButton{SELF,ResourceID{RHSELPAG01_FOTO,_GetInst()}}
oCCfoto:HyperLabel := HyperLabel{#foto,"...",NULL_STRING,NULL_STRING}
oCCfoto:Image := ico_camera{}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#RHSELPAG01,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS MAE() 
RETURN SELF:FieldGet(#MAE)


ASSIGN MAE(uValue) 
SELF:FieldPut(#MAE, uValue)
RETURN MAE := uValue


ACCESS NASC() 
RETURN SELF:FieldGet(#NASC)


ASSIGN NASC(uValue) 
SELF:FieldPut(#NASC, uValue)
RETURN NASC := uValue


ACCESS nascIBGE() 
RETURN SELF:FieldGet(#nascIBGE)


ASSIGN nascIBGE(uValue) 
SELF:FieldPut(#nascIBGE, uValue)
RETURN nascIBGE := uValue


ACCESS nascPAIS() 
RETURN SELF:FieldGet(#nascPAIS)


ASSIGN nascPAIS(uValue) 
SELF:FieldPut(#nascPAIS, uValue)
RETURN nascPAIS := uValue


ACCESS NUMEMPANT() 
RETURN SELF:FieldGet(#NUMEMPANT)


ASSIGN NUMEMPANT(uValue) 
SELF:FieldPut(#NUMEMPANT, uValue)
RETURN NUMEMPANT := uValue


ACCESS OBS() 
RETURN SELF:FieldGet(#OBS)


ASSIGN OBS(uValue) 
SELF:FieldPut(#OBS, uValue)
RETURN OBS := uValue


ACCESS PAI() 
RETURN SELF:FieldGet(#PAI)


ASSIGN PAI(uValue) 
SELF:FieldPut(#PAI, uValue)
RETURN PAI := uValue


ACCESS Processo() 
RETURN SELF:FieldGet(#Processo)


ASSIGN Processo(uValue) 
SELF:FieldPut(#Processo, uValue)
RETURN Processo := uValue


ACCESS PROCOBS() 
RETURN SELF:FieldGet(#PROCOBS)


ASSIGN PROCOBS(uValue) 
SELF:FieldPut(#PROCOBS, uValue)
RETURN PROCOBS := uValue


ACCESS RACS() 
RETURN SELF:FieldGet(#RACS)


ASSIGN RACS(uValue) 
SELF:FieldPut(#RACS, uValue)
RETURN RACS := uValue


ACCESS SEXO() 
RETURN SELF:FieldGet(#SEXO)


ASSIGN SEXO(uValue) 
SELF:FieldPut(#SEXO, uValue)
RETURN SEXO := uValue


ACCESS SITUACAO() 
RETURN SELF:FieldGet(#SITUACAO)


ASSIGN SITUACAO(uValue) 
SELF:FieldPut(#SITUACAO, uValue)
RETURN SITUACAO := uValue


ACCESS TIPO() 
RETURN SELF:FieldGet(#TIPO)


ASSIGN TIPO(uValue) 
SELF:FieldPut(#TIPO, uValue)
RETURN TIPO := uValue


END CLASS
PARTIAL CLASS RHSELPAG02 INHERIT DATAWINDOW
PROTECT oDCPIS AS SINGLELINEEDIT
PROTECT oDCRG AS SINGLELINEEDIT
PROTECT oDCRGEMIS AS SINGLELINEEDIT
PROTECT oDCRGTIP AS SINGLELINEEDIT
PROTECT oDCRGUF AS SINGLELINEEDIT
PROTECT oDCRGDATA AS DateSle
PROTECT oDCPROFIS AS SINGLELINEEDIT
PROTECT oDCSERIE AS SINGLELINEEDIT
PROTECT oDCCTPSUF AS SINGLELINEEDIT
PROTECT oDCCTPSDATA AS DateSle
PROTECT oDCcnh AS SINGLELINEEDIT
PROTECT oDCCATCNH AS SINGLELINEEDIT
PROTECT oDCEXPCNH AS DateSle
PROTECT oDCVALCNH AS DateSle
PROTECT oDCESCRAIS AS COMBOBOX
PROTECT oDCreserv AS SINGLELINEEDIT
PROTECT oDCRESECAT AS SINGLELINEEDIT
PROTECT oDCFOR01 AS SINGLELINEEDIT
PROTECT oDCFOR02 AS SINGLELINEEDIT
PROTECT oDCFOR03 AS SINGLELINEEDIT
PROTECT oDCAPF01 AS SINGLELINEEDIT
PROTECT oDCAPF02 AS SINGLELINEEDIT
PROTECT oDCAPF03 AS SINGLELINEEDIT
PROTECT oDCcns AS rightSle
PROTECT oDCTITULO AS rightSle
PROTECT oDCTITUZONA AS SINGLELINEEDIT
PROTECT oDCSERIE2 AS SINGLELINEEDIT
PROTECT oDCOC AS SINGLELINEEDIT
PROTECT oDCOCEMI AS SINGLELINEEDIT
PROTECT oDCOCEXP AS DateSle
PROTECT oDCOCVAL AS DateSle
PROTECT oDCbanco AS SINGLELINEEDIT
PROTECT oDCAgencia AS SINGLELINEEDIT
PROTECT oDCCONTA AS SINGLELINEEDIT
PROTECT oDCCONTAFGTS AS SINGLELINEEDIT
PROTECT oDCSC_CTPS AS FIXEDTEXT
PROTECT oDCSC_SERIE AS FIXEDTEXT
PROTECT oDCSC_UFCTPS AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA AS FIXEDTEXT
PROTECT oDCCPF AS SINGLELINEEDIT
PROTECT oDCSC_ESCOLA AS FIXEDTEXT
PROTECT oDCGroupBox1 AS GROUPBOX
PROTECT oDCGroupBox2 AS GROUPBOX
PROTECT oCCCMDCHECKUF AS PUSHBUTTON
PROTECT oDCFixedText3 AS Hyperlink
PROTECT oCCcheckcPF AS PUSHBUTTON
PROTECT oCCcheckcns AS PUSHBUTTON
PROTECT oCCcheckTIT AS PUSHBUTTON
PROTECT oCCbtncheckrg AS PUSHBUTTON
PROTECT oCCcheckPIS AS PUSHBUTTON
PROTECT oDCFixedText7 AS FIXEDTEXT
PROTECT oDCFixedText8 AS FIXEDTEXT
PROTECT oDCFixedText4 AS Hyperlink
PROTECT oDCSC_SERIE1 AS FIXEDTEXT
PROTECT oCCCMDCHECKUF1 AS PUSHBUTTON
PROTECT oDCSC_SERIE2 AS FIXEDTEXT
PROTECT oDCSC_UFCTPS1 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA1 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA2 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA3 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA4 AS FIXEDTEXT
PROTECT oDCSC_SERIE3 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA5 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA6 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA7 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA8 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA9 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA10 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA11 AS FIXEDTEXT
PROTECT oDCSC_CATEGORIA12 AS FIXEDTEXT
PROTECT oCCescLOG1 AS PUSHBUTTON
PROTECT oCCescLOG2 AS PUSHBUTTON

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS Agencia
RETURN SELF:FieldGet( #Agencia )

ASSIGN Agencia( uValue )
SELF:FieldPut( #Agencia , uValue )

ACCESS APF01
RETURN SELF:FieldGet( #APF01 )

ASSIGN APF01( uValue )
SELF:FieldPut( #APF01 , uValue )

ACCESS APF02
RETURN SELF:FieldGet( #APF02 )

ASSIGN APF02( uValue )
SELF:FieldPut( #APF02 , uValue )

ACCESS APF03
RETURN SELF:FieldGet( #APF03 )

ASSIGN APF03( uValue )
SELF:FieldPut( #APF03 , uValue )

ACCESS banco
RETURN SELF:FieldGet( #banco )

ASSIGN banco( uValue )
SELF:FieldPut( #banco , uValue )

ACCESS CATCNH
RETURN SELF:FieldGet( #CATCNH )

ASSIGN CATCNH( uValue )
SELF:FieldPut( #CATCNH , uValue )

METHOD checkcns( ) 
valcns(SELF:SERVER:FIELDGET("CNS"),TRUE)


METHOD checkcPF( ) 
SELF:SERVER:FIELDPUT("CPF",formatcpf(SELF:SERVER:FIELDGET("CPF")))	
Valcpf(SELF:SERVER:FIELDGET("CPF"),TRUE)


METHOD checkPIS( ) 
valpis(SELF:SERVER:FIELDGET("PIS"),TRUE)


METHOD btnCheckRG( ) 
	SELF:SERVER:FIELDPUT("RG",FormataRG(SELF:SERVER:FIELDGET("RG")))	
	CheckRG(SELF:SERVER:FIELDGET("rg"),TRUE)

METHOD checkTIT( ) 
CheckTitulo(SELF:SERVER:FIELDGET("TITULO"),TRUE)	



METHOD CMDCHECKUF1( ) 
				ufCheck(SELF:SERVER:FIELDGET("RGUF"))

ACCESS cnh
RETURN SELF:FieldGet( #cnh )

ASSIGN cnh( uValue )
SELF:FieldPut( #cnh , uValue )

ACCESS cns
RETURN SELF:FieldGet( #cns )

ASSIGN cns( uValue )
SELF:FieldPut( #cns , uValue )

ACCESS CONTA
RETURN SELF:FieldGet( #CONTA )

ASSIGN CONTA( uValue )
SELF:FieldPut( #CONTA , uValue )

ACCESS CONTAFGTS
RETURN SELF:FieldGet( #CONTAFGTS )

ASSIGN CONTAFGTS( uValue )
SELF:FieldPut( #CONTAFGTS , uValue )

ACCESS CPF
RETURN SELF:FieldGet( #CPF )

ASSIGN CPF( uValue )
SELF:FieldPut( #CPF , uValue )

ACCESS CTPSDATA
RETURN SELF:FieldGet( #CTPSDATA )

ASSIGN CTPSDATA( uValue )
SELF:FieldPut( #CTPSDATA , uValue )

ACCESS CTPSUF
RETURN SELF:FieldGet( #CTPSUF )

ASSIGN CTPSUF( uValue )
SELF:FieldPut( #CTPSUF , uValue )

METHOD escLOG1( ) 
LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"UF",SELF:SERVER:FIELDGET("RGUF")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("RGUF",oESC:cCODIGO)
ENDIF									

METHOD escLOG2( ) 
	LOCAL oESC AS XESCFO_TAB
oESC:=XESCFO_TAB{SELF,"UF",SELF:SERVER:FIELDGET("CTPSUF")}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("CTPSUF",oESC:cCODIGO)
ENDIF									

ACCESS ESCRAIS
RETURN SELF:FieldGet( #ESCRAIS )

ASSIGN ESCRAIS( uValue )
SELF:FieldPut( #ESCRAIS , uValue )

ACCESS EXPCNH
RETURN SELF:FieldGet( #EXPCNH )

ASSIGN EXPCNH( uValue )
SELF:FieldPut( #EXPCNH , uValue )

ACCESS FOR01
RETURN SELF:FieldGet( #FOR01 )

ASSIGN FOR01( uValue )
SELF:FieldPut( #FOR01 , uValue )

ACCESS FOR02
RETURN SELF:FieldGet( #FOR02 )

ASSIGN FOR02( uValue )
SELF:FieldPut( #FOR02 , uValue )

ACCESS FOR03
RETURN SELF:FieldGet( #FOR03 )

ASSIGN FOR03( uValue )
SELF:FieldPut( #FOR03 , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"RHSELPAG02" , _GetInst()},iCtlID)

	SELF:oDCPIS := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_PIS  , _GetInst() } }
	SELF:oDCPIS:FieldSpec := PADRAO_CHAR_11{}
	SELF:oDCPIS:HyperLabel := HyperLabel{#PIS , "Pis:" , NULL_STRING , "RHSEL_PIS"}

	SELF:oDCRG := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_RG  , _GetInst() } }
	SELF:oDCRG:FieldSpec := PADRAO_CHAR_12{}
	SELF:oDCRG:HyperLabel := HyperLabel{#RG , "Rg:" , NULL_STRING , "RHSEL_RG"}

	SELF:oDCRGEMIS := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_RGEMIS  , _GetInst() } }
	SELF:oDCRGEMIS:FieldSpec := PADRAO_CHAR_05{}
	SELF:oDCRGEMIS:HyperLabel := HyperLabel{#RGEMIS , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCRGTIP := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_RGTIP  , _GetInst() } }
	SELF:oDCRGTIP:FieldSpec := PADRAO_CHAR_03{}
	SELF:oDCRGTIP:HyperLabel := HyperLabel{#RGTIP , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCRGUF := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_RGUF  , _GetInst() } }
	SELF:oDCRGUF:FieldSpec := uf_field{}
	SELF:oDCRGUF:HyperLabel := HyperLabel{#RGUF , "Ufctps:" , NULL_STRING , "RHSEL_UFCTPS"}

	SELF:oDCRGDATA := DateSle{SELF , ResourceID{ RHSELPAG02_RGDATA  , _GetInst() } }
	SELF:oDCRGDATA:FieldSpec := DATE_FIELD{}
	SELF:oDCRGDATA:HyperLabel := HyperLabel{#RGDATA , "Fone:" , NULL_STRING , "RHSEL_FONE"}

	SELF:oDCPROFIS := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_PROFIS  , _GetInst() } }
	SELF:oDCPROFIS:FieldSpec := PADRAO_CHAR_07{}
	SELF:oDCPROFIS:HyperLabel := HyperLabel{#PROFIS , "Ctps:" , NULL_STRING , "RHSEL_CTPS"}

	SELF:oDCSERIE := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_SERIE  , _GetInst() } }
	SELF:oDCSERIE:FieldSpec := PADRAO_CHAR_05{}
	SELF:oDCSERIE:HyperLabel := HyperLabel{#SERIE , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCCTPSUF := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_CTPSUF  , _GetInst() } }
	SELF:oDCCTPSUF:FieldSpec := uf_field{}
	SELF:oDCCTPSUF:HyperLabel := HyperLabel{#CTPSUF , "Ufctps:" , NULL_STRING , "RHSEL_UFCTPS"}

	SELF:oDCCTPSDATA := DateSle{SELF , ResourceID{ RHSELPAG02_CTPSDATA  , _GetInst() } }
	SELF:oDCCTPSDATA:FieldSpec := DATE_FIELD{}
	SELF:oDCCTPSDATA:HyperLabel := HyperLabel{#CTPSDATA , "Fone:" , NULL_STRING , "RHSEL_FONE"}

	SELF:oDCcnh := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_CNH  , _GetInst() } }
	SELF:oDCcnh:FieldSpec := PADRAO_CHAR_11{}
	SELF:oDCcnh:HyperLabel := HyperLabel{#cnh , "Ctps:" , NULL_STRING , "RHSEL_CTPS"}

	SELF:oDCCATCNH := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_CATCNH  , _GetInst() } }
	SELF:oDCCATCNH:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCCATCNH:HyperLabel := HyperLabel{#CATCNH , "Categoria:" , NULL_STRING , "RHSEL_CATEGORIA"}

	SELF:oDCEXPCNH := DateSle{SELF , ResourceID{ RHSELPAG02_EXPCNH  , _GetInst() } }
	SELF:oDCEXPCNH:FieldSpec := DATE_FIELD{}
	SELF:oDCEXPCNH:HyperLabel := HyperLabel{#EXPCNH , "Fone:" , NULL_STRING , "RHSEL_FONE"}

	SELF:oDCVALCNH := DateSle{SELF , ResourceID{ RHSELPAG02_VALCNH  , _GetInst() } }
	SELF:oDCVALCNH:FieldSpec := DATE_FIELD{}
	SELF:oDCVALCNH:HyperLabel := HyperLabel{#VALCNH , "Fone:" , NULL_STRING , "RHSEL_FONE"}

	SELF:oDCESCRAIS := COMBOBOX{SELF , ResourceID{ RHSELPAG02_ESCRAIS  , _GetInst() } }
	SELF:oDCESCRAIS:FillUsing( SELF:PEGRHESC() )
	SELF:oDCESCRAIS:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCESCRAIS:HyperLabel := HyperLabel{#ESCRAIS , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCreserv := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_RESERV  , _GetInst() } }
	SELF:oDCreserv:FieldSpec := PADRAO_CHAR_12{}
	SELF:oDCreserv:HyperLabel := HyperLabel{#reserv , "Ctps:" , NULL_STRING , "RHSEL_CTPS"}

	SELF:oDCRESECAT := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_RESECAT  , _GetInst() } }
	SELF:oDCRESECAT:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCRESECAT:HyperLabel := HyperLabel{#RESECAT , "Categoria:" , NULL_STRING , "RHSEL_CATEGORIA"}

	SELF:oDCFOR01 := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_FOR01  , _GetInst() } }
	SELF:oDCFOR01:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCFOR01:HyperLabel := HyperLabel{#FOR01 , "For01:" , NULL_STRING , "RHSEL_FOR01"}

	SELF:oDCFOR02 := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_FOR02  , _GetInst() } }
	SELF:oDCFOR02:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCFOR02:HyperLabel := HyperLabel{#FOR02 , "For02:" , NULL_STRING , "RHSEL_FOR02"}

	SELF:oDCFOR03 := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_FOR03  , _GetInst() } }
	SELF:oDCFOR03:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCFOR03:HyperLabel := HyperLabel{#FOR03 , "For03:" , NULL_STRING , "RHSEL_FOR03"}

	SELF:oDCAPF01 := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_APF01  , _GetInst() } }
	SELF:oDCAPF01:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCAPF01:HyperLabel := HyperLabel{#APF01 , "Apf01:" , NULL_STRING , "RHSEL_APF01"}

	SELF:oDCAPF02 := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_APF02  , _GetInst() } }
	SELF:oDCAPF02:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCAPF02:HyperLabel := HyperLabel{#APF02 , "Apf02:" , NULL_STRING , "RHSEL_APF02"}

	SELF:oDCAPF03 := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_APF03  , _GetInst() } }
	SELF:oDCAPF03:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCAPF03:HyperLabel := HyperLabel{#APF03 , "Apf03:" , NULL_STRING , "RHSEL_APF03"}

	SELF:oDCcns := rightSle{SELF , ResourceID{ RHSELPAG02_CNS  , _GetInst() } }
	SELF:oDCcns:FieldSpec := padrao_char_15{}
	SELF:oDCcns:TooltipText := "Digite o Pis"
	SELF:oDCcns:HyperLabel := HyperLabel{#cns , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCTITULO := rightSle{SELF , ResourceID{ RHSELPAG02_TITULO  , _GetInst() } }
	SELF:oDCTITULO:FieldSpec := PADRAO_CHAR_14{}
	SELF:oDCTITULO:TooltipText := "Digite o Numero RGCarteira de Identidade"
	SELF:oDCTITULO:HyperLabel := HyperLabel{#TITULO , "TITULO" , NULL_STRING , NULL_STRING}

	SELF:oDCTITUZONA := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_TITUZONA  , _GetInst() } }
	SELF:oDCTITUZONA:FieldSpec := PADRAO_CHAR_03{}
	SELF:oDCTITUZONA:HyperLabel := HyperLabel{#TITUZONA , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCSERIE2 := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_SERIE2  , _GetInst() } }
	SELF:oDCSERIE2:FieldSpec := PADRAO_CHAR_03{}
	SELF:oDCSERIE2:HyperLabel := HyperLabel{#SERIE2 , "TITUSECA" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCOC := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_OC  , _GetInst() } }
	SELF:oDCOC:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCOC:HyperLabel := HyperLabel{#OC , "Rg:" , NULL_STRING , "RHSEL_RG"}

	SELF:oDCOCEMI := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_OCEMI  , _GetInst() } }
	SELF:oDCOCEMI:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCOCEMI:HyperLabel := HyperLabel{#OCEMI , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCOCEXP := DateSle{SELF , ResourceID{ RHSELPAG02_OCEXP  , _GetInst() } }
	SELF:oDCOCEXP:FieldSpec := DATE_FIELD{}
	SELF:oDCOCEXP:HyperLabel := HyperLabel{#OCEXP , "Fone:" , NULL_STRING , "RHSEL_FONE"}

	SELF:oDCOCVAL := DateSle{SELF , ResourceID{ RHSELPAG02_OCVAL  , _GetInst() } }
	SELF:oDCOCVAL:FieldSpec := DATE_FIELD{}
	SELF:oDCOCVAL:HyperLabel := HyperLabel{#OCVAL , "Fone:" , NULL_STRING , "RHSEL_FONE"}

	SELF:oDCbanco := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_BANCO  , _GetInst() } }
	SELF:oDCbanco:FieldSpec := PADRAO_CHAR_03{}
	SELF:oDCbanco:HyperLabel := HyperLabel{#banco , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCAgencia := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_AGENCIA  , _GetInst() } }
	SELF:oDCAgencia:FieldSpec := PADRAO_CHAR_07{}
	SELF:oDCAgencia:HyperLabel := HyperLabel{#Agencia , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCCONTA := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_CONTA  , _GetInst() } }
	SELF:oDCCONTA:FieldSpec := PADRAO_CHAR_12{}
	SELF:oDCCONTA:HyperLabel := HyperLabel{#CONTA , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCCONTAFGTS := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_CONTAFGTS  , _GetInst() } }
	SELF:oDCCONTAFGTS:FieldSpec := PADRAO_CHAR_11{}
	SELF:oDCCONTAFGTS:HyperLabel := HyperLabel{#CONTAFGTS , "Serie:" , NULL_STRING , "RHSEL_SERIE"}

	SELF:oDCSC_CTPS := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CTPS  , _GetInst() } }
	SELF:oDCSC_CTPS:HyperLabel := HyperLabel{#SC_CTPS , "CTPS" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SERIE := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_SERIE  , _GetInst() } }
	SELF:oDCSC_SERIE:HyperLabel := HyperLabel{#SC_SERIE , "Serie:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_UFCTPS := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_UFCTPS  , _GetInst() } }
	SELF:oDCSC_UFCTPS:HyperLabel := HyperLabel{#SC_UFCTPS , "UF" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA  , _GetInst() } }
	SELF:oDCSC_CATEGORIA:HyperLabel := HyperLabel{#SC_CATEGORIA , "Habilitação:" , NULL_STRING , NULL_STRING}

	SELF:oDCCPF := SINGLELINEEDIT{SELF , ResourceID{ RHSELPAG02_CPF  , _GetInst() } }
	SELF:oDCCPF:FieldSpec := PADRAO_CHAR_14{}
	SELF:oDCCPF:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCCPF:Font( oFont )
	SELF:oDCCPF:HyperLabel := HyperLabel{#CPF , "Cpf:" , NULL_STRING , "RHSEL_CPF"}

	SELF:oDCSC_ESCOLA := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_ESCOLA  , _GetInst() } }
	SELF:oDCSC_ESCOLA:HyperLabel := HyperLabel{#SC_ESCOLA , "Escolaridade:" , NULL_STRING , NULL_STRING}

	SELF:oDCGroupBox1 := GROUPBOX{SELF , ResourceID{ RHSELPAG02_GROUPBOX1  , _GetInst() } }
	SELF:oDCGroupBox1:HyperLabel := HyperLabel{#GroupBox1 , "Cursos Formação" , NULL_STRING , NULL_STRING}

	SELF:oDCGroupBox2 := GROUPBOX{SELF , ResourceID{ RHSELPAG02_GROUPBOX2  , _GetInst() } }
	SELF:oDCGroupBox2:HyperLabel := HyperLabel{#GroupBox2 , "Cursos Aperfeicoamentos" , NULL_STRING , NULL_STRING}

	SELF:oCCCMDCHECKUF := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_CMDCHECKUF  , _GetInst() } }
	SELF:oCCCMDCHECKUF:HyperLabel := HyperLabel{#CMDCHECKUF , "Checar UF" , NULL_STRING , NULL_STRING}

	SELF:oDCFixedText3 := Hyperlink{SELF , ResourceID{ RHSELPAG02_FIXEDTEXT3  , _GetInst() } }
	SELF:oDCFixedText3:HyperLabel := HyperLabel{#FixedText3 , "Qualificacao Cadastral duplo click mouse" , "www9.dataprev.gov.br/Esocial/pages/qualificacao/qualificar.xhtml" , NULL_STRING}

	SELF:oCCcheckcPF := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_CHECKCPF  , _GetInst() } }
	SELF:oCCcheckcPF:TooltipText := "Checar CPF"
	SELF:oCCcheckcPF:HyperLabel := HyperLabel{#checkcPF , "CPF Checar" , NULL_STRING , NULL_STRING}

	SELF:oCCcheckcns := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_CHECKCNS  , _GetInst() } }
	SELF:oCCcheckcns:TooltipText := "Checar PIS"
	SELF:oCCcheckcns:HyperLabel := HyperLabel{#checkcns , "cns Checar" , NULL_STRING , NULL_STRING}

	SELF:oCCcheckTIT := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_CHECKTIT  , _GetInst() } }
	SELF:oCCcheckTIT:TooltipText := "Checar Numero Renavam"
	SELF:oCCcheckTIT:HyperLabel := HyperLabel{#checkTIT , "Checar Titulo Eleitor" , NULL_STRING , NULL_STRING}

	SELF:oCCbtncheckrg := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_BTNCHECKRG  , _GetInst() } }
	SELF:oCCbtncheckrg:TooltipText := "Checar Numero Renavam"
	SELF:oCCbtncheckrg:HyperLabel := HyperLabel{#btncheckrg , "RG Checar" , NULL_STRING , NULL_STRING}

	SELF:oCCcheckPIS := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_CHECKPIS  , _GetInst() } }
	SELF:oCCcheckPIS:TooltipText := "Checar PIS"
	SELF:oCCcheckPIS:HyperLabel := HyperLabel{#checkPIS , "PIS Checar" , NULL_STRING , NULL_STRING}

	SELF:oDCFixedText7 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_FIXEDTEXT7  , _GetInst() } }
	SELF:oDCFixedText7:HyperLabel := HyperLabel{#FixedText7 , "Zona" , NULL_STRING , NULL_STRING}

	SELF:oDCFixedText8 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_FIXEDTEXT8  , _GetInst() } }
	SELF:oDCFixedText8:HyperLabel := HyperLabel{#FixedText8 , "Secao" , NULL_STRING , NULL_STRING}

	SELF:oDCFixedText4 := Hyperlink{SELF , ResourceID{ RHSELPAG02_FIXEDTEXT4  , _GetInst() } }
	SELF:oDCFixedText4:HyperLabel := HyperLabel{#FixedText4 , "CNS portal duplo click mouse" , "https://portaldocidadao.saude.gov.br/portalcidadao/" , NULL_STRING}

	SELF:oDCSC_SERIE1 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_SERIE1  , _GetInst() } }
	SELF:oDCSC_SERIE1:HyperLabel := HyperLabel{#SC_SERIE1 , "Emissor:" , NULL_STRING , NULL_STRING}

	SELF:oCCCMDCHECKUF1 := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_CMDCHECKUF1  , _GetInst() } }
	SELF:oCCCMDCHECKUF1:HyperLabel := HyperLabel{#CMDCHECKUF1 , "Checar" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SERIE2 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_SERIE2  , _GetInst() } }
	SELF:oDCSC_SERIE2:HyperLabel := HyperLabel{#SC_SERIE2 , "Tipo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_UFCTPS1 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_UFCTPS1  , _GetInst() } }
	SELF:oDCSC_UFCTPS1:HyperLabel := HyperLabel{#SC_UFCTPS1 , "UF" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA1 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA1  , _GetInst() } }
	SELF:oDCSC_CATEGORIA1:HyperLabel := HyperLabel{#SC_CATEGORIA1 , "categoria:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA2 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA2  , _GetInst() } }
	SELF:oDCSC_CATEGORIA2:HyperLabel := HyperLabel{#SC_CATEGORIA2 , "Expedicao" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA3 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA3  , _GetInst() } }
	SELF:oDCSC_CATEGORIA3:HyperLabel := HyperLabel{#SC_CATEGORIA3 , "Validade" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA4 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA4  , _GetInst() } }
	SELF:oDCSC_CATEGORIA4:HyperLabel := HyperLabel{#SC_CATEGORIA4 , "Orgao Classe:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SERIE3 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_SERIE3  , _GetInst() } }
	SELF:oDCSC_SERIE3:HyperLabel := HyperLabel{#SC_SERIE3 , "Emissor:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA5 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA5  , _GetInst() } }
	SELF:oDCSC_CATEGORIA5:HyperLabel := HyperLabel{#SC_CATEGORIA5 , "Expedicao" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA6 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA6  , _GetInst() } }
	SELF:oDCSC_CATEGORIA6:HyperLabel := HyperLabel{#SC_CATEGORIA6 , "Validade" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA7 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA7  , _GetInst() } }
	SELF:oDCSC_CATEGORIA7:HyperLabel := HyperLabel{#SC_CATEGORIA7 , "Reservista" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA8 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA8  , _GetInst() } }
	SELF:oDCSC_CATEGORIA8:HyperLabel := HyperLabel{#SC_CATEGORIA8 , "categoria:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA9 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA9  , _GetInst() } }
	SELF:oDCSC_CATEGORIA9:HyperLabel := HyperLabel{#SC_CATEGORIA9 , "Banco:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA10 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA10  , _GetInst() } }
	SELF:oDCSC_CATEGORIA10:HyperLabel := HyperLabel{#SC_CATEGORIA10 , "Agencia:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA11 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA11  , _GetInst() } }
	SELF:oDCSC_CATEGORIA11:HyperLabel := HyperLabel{#SC_CATEGORIA11 , "Conta:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CATEGORIA12 := FIXEDTEXT{SELF , ResourceID{ RHSELPAG02_SC_CATEGORIA12  , _GetInst() } }
	SELF:oDCSC_CATEGORIA12:HyperLabel := HyperLabel{#SC_CATEGORIA12 , "ContaFgts:" , NULL_STRING , NULL_STRING}

	SELF:oCCescLOG1 := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_ESCLOG1  , _GetInst() } }
	SELF:oCCescLOG1:Image := ICO_FIND{}
	SELF:oCCescLOG1:HyperLabel := HyperLabel{#escLOG1 , ".." , NULL_STRING , NULL_STRING}

	SELF:oCCescLOG2 := PUSHBUTTON{SELF , ResourceID{ RHSELPAG02_ESCLOG2  , _GetInst() } }
	SELF:oCCescLOG2:Image := ICO_FIND{}
	SELF:oCCescLOG2:HyperLabel := HyperLabel{#escLOG2 , ".." , NULL_STRING , NULL_STRING}

	SELF:Caption := "DataWindow Caption"
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#RHSELPAG02 , "DataWindow Caption" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ELSE
		SELF:Use(SELF:Owner:Server)
	ENDIF


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS OC
RETURN SELF:FieldGet( #OC )

ASSIGN OC( uValue )
SELF:FieldPut( #OC , uValue )

ACCESS OCEMI
RETURN SELF:FieldGet( #OCEMI )

ASSIGN OCEMI( uValue )
SELF:FieldPut( #OCEMI , uValue )

ACCESS OCEXP
RETURN SELF:FieldGet( #OCEXP )

ASSIGN OCEXP( uValue )
SELF:FieldPut( #OCEXP , uValue )

ACCESS OCVAL
RETURN SELF:FieldGet( #OCVAL )

ASSIGN OCVAL( uValue )
SELF:FieldPut( #OCVAL , uValue )

ACCESS PIS
RETURN SELF:FieldGet( #PIS )

ASSIGN PIS( uValue )
SELF:FieldPut( #PIS , uValue )

ACCESS PROFIS
RETURN SELF:FieldGet( #PROFIS )

ASSIGN PROFIS( uValue )
SELF:FieldPut( #PROFIS , uValue )

ACCESS RESECAT
RETURN SELF:FieldGet( #RESECAT )

ASSIGN RESECAT( uValue )
SELF:FieldPut( #RESECAT , uValue )

ACCESS reserv
RETURN SELF:FieldGet( #reserv )

ASSIGN reserv( uValue )
SELF:FieldPut( #reserv , uValue )

ACCESS RG
RETURN SELF:FieldGet( #RG )

ASSIGN RG( uValue )
SELF:FieldPut( #RG , uValue )

ACCESS RGDATA
RETURN SELF:FieldGet( #RGDATA )

ASSIGN RGDATA( uValue )
SELF:FieldPut( #RGDATA , uValue )

ACCESS RGEMIS
RETURN SELF:FieldGet( #RGEMIS )

ASSIGN RGEMIS( uValue )
SELF:FieldPut( #RGEMIS , uValue )

ACCESS RGTIP
RETURN SELF:FieldGet( #RGTIP )

ASSIGN RGTIP( uValue )
SELF:FieldPut( #RGTIP , uValue )

ACCESS RGUF
RETURN SELF:FieldGet( #RGUF )

ASSIGN RGUF( uValue )
SELF:FieldPut( #RGUF , uValue )

ACCESS SERIE
RETURN SELF:FieldGet( #SERIE )

ASSIGN SERIE( uValue )
SELF:FieldPut( #SERIE , uValue )

ACCESS SERIE2
RETURN SELF:FieldGet( #SERIE2 )

ASSIGN SERIE2( uValue )
SELF:FieldPut( #SERIE2 , uValue )

ACCESS TITULO
RETURN SELF:FieldGet( #TITULO )

ASSIGN TITULO( uValue )
SELF:FieldPut( #TITULO , uValue )

ACCESS TITUZONA
RETURN SELF:FieldGet( #TITUZONA )

ASSIGN TITUZONA( uValue )
SELF:FieldPut( #TITUZONA , uValue )

ACCESS VALCNH
RETURN SELF:FieldGet( #VALCNH )

ASSIGN VALCNH( uValue )
SELF:FieldPut( #VALCNH , uValue )

END CLASS
CLASS RHSELPAG03 INHERIT DATAWINDOW 

	PROTECT oDCEX01EMP AS SINGLELINEEDIT
	PROTECT oDCEX01RAM AS SINGLELINEEDIT
	PROTECT oDCEX01TEL AS SINGLELINEEDIT
	PROTECT oDCEX01DEM AS DATESLE
	PROTECT oDCEX01ADM AS DATESLE
	PROTECT oDCEX01FUN AS SINGLELINEEDIT
	PROTECT oDCEX01ULT AS SINGLELINEEDIT
	PROTECT oDCEX01AT1 AS SINGLELINEEDIT
	PROTECT oDCEX01AT2 AS SINGLELINEEDIT
	PROTECT oDCEX02EMP AS SINGLELINEEDIT
	PROTECT oDCEX02RAM AS SINGLELINEEDIT
	PROTECT oDCEX02TEL AS SINGLELINEEDIT
	PROTECT oDCEX02ADM AS DATESLE
	PROTECT oDCEX02DEM AS DATESLE
	PROTECT oDCEX02FUN AS SINGLELINEEDIT
	PROTECT oDCEX02ULT AS SINGLELINEEDIT
	PROTECT oDCEX02AT1 AS SINGLELINEEDIT
	PROTECT oDCEX02AT2 AS SINGLELINEEDIT
	PROTECT oDCEX03EMP AS SINGLELINEEDIT
	PROTECT oDCEX03RAM AS SINGLELINEEDIT
	PROTECT oDCEX03TEL AS SINGLELINEEDIT
	PROTECT oDCEX03ADM AS DATESLE
	PROTECT oDCEX03DEM AS DATESLE
	PROTECT oDCEX03FUN AS SINGLELINEEDIT
	PROTECT oDCEX03AT1 AS SINGLELINEEDIT
	PROTECT oDCEX03AT2 AS SINGLELINEEDIT
	PROTECT oDCSC_EX01EMP AS FIXEDTEXT
	PROTECT oDCSC_EX01RAM AS FIXEDTEXT
	PROTECT oDCSC_EX01TEL AS FIXEDTEXT
	PROTECT oDCSC_EX01DEM AS FIXEDTEXT
	PROTECT oDCSC_EX01ADM AS FIXEDTEXT
	PROTECT oDCSC_EX01FUN AS FIXEDTEXT
	PROTECT oDCSC_EX01ULT AS FIXEDTEXT
	PROTECT oDCSC_EX01AT1 AS FIXEDTEXT
	PROTECT oDCEX03ULT AS SINGLELINEEDIT
	PROTECT oDCSC_EX01ULT1 AS FIXEDTEXT
	PROTECT oDCSC_EX01RAM1 AS FIXEDTEXT
	PROTECT oDCSC_EX01DEM1 AS FIXEDTEXT
	PROTECT oDCSC_EX01ADM1 AS FIXEDTEXT
	PROTECT oDCSC_EX01AT2 AS FIXEDTEXT
	PROTECT oDCSC_EX01FUN1 AS FIXEDTEXT
	PROTECT oDCSC_EX01TEL1 AS FIXEDTEXT
	PROTECT oDCSC_EX01EMP1 AS FIXEDTEXT
	PROTECT oDCSC_EX01RAM2 AS FIXEDTEXT
	PROTECT oDCSC_EX01ULT2 AS FIXEDTEXT
	PROTECT oDCSC_EX01DEM2 AS FIXEDTEXT
	PROTECT oDCSC_EX01ADM2 AS FIXEDTEXT
	PROTECT oDCSC_EX01AT3 AS FIXEDTEXT
	PROTECT oDCSC_EX01FUN2 AS FIXEDTEXT
	PROTECT oDCSC_EX01TEL2 AS FIXEDTEXT
	PROTECT oDCSC_EX01EMP2 AS FIXEDTEXT
// 	instance EX01EMP 
// 	instance EX01RAM 
// 	instance EX01TEL 
// 	instance EX01DEM 
// 	instance EX01ADM 
// 	instance EX01FUN 
// 	instance EX01ULT 
// 	instance EX01AT1 
// 	instance EX01AT2 
// 	instance EX02EMP 
// 	instance EX02RAM 
// 	instance EX02TEL 
// 	instance EX02ADM 
// 	instance EX02DEM 
// 	instance EX02FUN 
// 	instance EX02ULT 
// 	instance EX02AT1 
// 	instance EX02AT2 
// 	instance EX03EMP 
// 	instance EX03RAM 
// 	instance EX03TEL 
// 	instance EX03ADM 
// 	instance EX03DEM 
// 	instance EX03FUN 
// 	instance EX03AT1 
// 	instance EX03AT2 
// 	instance EX03ULT 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS EX01ADM() 
RETURN SELF:FieldGet(#EX01ADM)


ASSIGN EX01ADM(uValue) 
SELF:FieldPut(#EX01ADM, uValue)
RETURN EX01ADM := uValue


ACCESS EX01AT1() 
RETURN SELF:FieldGet(#EX01AT1)


ASSIGN EX01AT1(uValue) 
SELF:FieldPut(#EX01AT1, uValue)
RETURN EX01AT1 := uValue


ACCESS EX01AT2() 
RETURN SELF:FieldGet(#EX01AT2)


ASSIGN EX01AT2(uValue) 
SELF:FieldPut(#EX01AT2, uValue)
RETURN EX01AT2 := uValue


ACCESS EX01DEM() 
RETURN SELF:FieldGet(#EX01DEM)


ASSIGN EX01DEM(uValue) 
SELF:FieldPut(#EX01DEM, uValue)
RETURN EX01DEM := uValue


ACCESS EX01EMP() 
RETURN SELF:FieldGet(#EX01EMP)


ASSIGN EX01EMP(uValue) 
SELF:FieldPut(#EX01EMP, uValue)
RETURN EX01EMP := uValue


ACCESS EX01FUN() 
RETURN SELF:FieldGet(#EX01FUN)


ASSIGN EX01FUN(uValue) 
SELF:FieldPut(#EX01FUN, uValue)
RETURN EX01FUN := uValue


ACCESS EX01RAM() 
RETURN SELF:FieldGet(#EX01RAM)


ASSIGN EX01RAM(uValue) 
SELF:FieldPut(#EX01RAM, uValue)
RETURN EX01RAM := uValue


ACCESS EX01TEL() 
RETURN SELF:FieldGet(#EX01TEL)


ASSIGN EX01TEL(uValue) 
SELF:FieldPut(#EX01TEL, uValue)
RETURN EX01TEL := uValue


ACCESS EX01ULT() 
RETURN SELF:FieldGet(#EX01ULT)


ASSIGN EX01ULT(uValue) 
SELF:FieldPut(#EX01ULT, uValue)
RETURN EX01ULT := uValue


ACCESS EX02ADM() 
RETURN SELF:FieldGet(#EX02ADM)


ASSIGN EX02ADM(uValue) 
SELF:FieldPut(#EX02ADM, uValue)
RETURN EX02ADM := uValue


ACCESS EX02AT1() 
RETURN SELF:FieldGet(#EX02AT1)


ASSIGN EX02AT1(uValue) 
SELF:FieldPut(#EX02AT1, uValue)
RETURN EX02AT1 := uValue


ACCESS EX02AT2() 
RETURN SELF:FieldGet(#EX02AT2)


ASSIGN EX02AT2(uValue) 
SELF:FieldPut(#EX02AT2, uValue)
RETURN EX02AT2 := uValue


ACCESS EX02DEM() 
RETURN SELF:FieldGet(#EX02DEM)


ASSIGN EX02DEM(uValue) 
SELF:FieldPut(#EX02DEM, uValue)
RETURN EX02DEM := uValue


ACCESS EX02EMP() 
RETURN SELF:FieldGet(#EX02EMP)


ASSIGN EX02EMP(uValue) 
SELF:FieldPut(#EX02EMP, uValue)
RETURN EX02EMP := uValue


ACCESS EX02FUN() 
RETURN SELF:FieldGet(#EX02FUN)


ASSIGN EX02FUN(uValue) 
SELF:FieldPut(#EX02FUN, uValue)
RETURN EX02FUN := uValue


ACCESS EX02RAM() 
RETURN SELF:FieldGet(#EX02RAM)


ASSIGN EX02RAM(uValue) 
SELF:FieldPut(#EX02RAM, uValue)
RETURN EX02RAM := uValue


ACCESS EX02TEL() 
RETURN SELF:FieldGet(#EX02TEL)


ASSIGN EX02TEL(uValue) 
SELF:FieldPut(#EX02TEL, uValue)
RETURN EX02TEL := uValue


ACCESS EX02ULT() 
RETURN SELF:FieldGet(#EX02ULT)


ASSIGN EX02ULT(uValue) 
SELF:FieldPut(#EX02ULT, uValue)
RETURN EX02ULT := uValue


ACCESS EX03ADM() 
RETURN SELF:FieldGet(#EX03ADM)


ASSIGN EX03ADM(uValue) 
SELF:FieldPut(#EX03ADM, uValue)
RETURN EX03ADM := uValue


ACCESS EX03AT1() 
RETURN SELF:FieldGet(#EX03AT1)


ASSIGN EX03AT1(uValue) 
SELF:FieldPut(#EX03AT1, uValue)
RETURN EX03AT1 := uValue


ACCESS EX03AT2() 
RETURN SELF:FieldGet(#EX03AT2)


ASSIGN EX03AT2(uValue) 
SELF:FieldPut(#EX03AT2, uValue)
RETURN EX03AT2 := uValue


ACCESS EX03DEM() 
RETURN SELF:FieldGet(#EX03DEM)


ASSIGN EX03DEM(uValue) 
SELF:FieldPut(#EX03DEM, uValue)
RETURN EX03DEM := uValue


ACCESS EX03EMP() 
RETURN SELF:FieldGet(#EX03EMP)


ASSIGN EX03EMP(uValue) 
SELF:FieldPut(#EX03EMP, uValue)
RETURN EX03EMP := uValue


ACCESS EX03FUN() 
RETURN SELF:FieldGet(#EX03FUN)


ASSIGN EX03FUN(uValue) 
SELF:FieldPut(#EX03FUN, uValue)
RETURN EX03FUN := uValue


ACCESS EX03RAM() 
RETURN SELF:FieldGet(#EX03RAM)


ASSIGN EX03RAM(uValue) 
SELF:FieldPut(#EX03RAM, uValue)
RETURN EX03RAM := uValue


ACCESS EX03TEL() 
RETURN SELF:FieldGet(#EX03TEL)


ASSIGN EX03TEL(uValue) 
SELF:FieldPut(#EX03TEL, uValue)
RETURN EX03TEL := uValue


ACCESS EX03ULT() 
RETURN SELF:FieldGet(#EX03ULT)


ASSIGN EX03ULT(uValue) 
SELF:FieldPut(#EX03ULT, uValue)
RETURN EX03ULT := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"RHSELPAG03",_GetInst()},iCtlID)

oDCEX01EMP := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX01EMP,_GetInst()}}
oDCEX01EMP:FieldSpec := PADRAO_CHAR_40{}
oDCEX01EMP:HyperLabel := HyperLabel{#EX01EMP,"Ex01emp:",NULL_STRING,"RHSEL_EX01EMP"}

oDCEX01RAM := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX01RAM,_GetInst()}}
oDCEX01RAM:FieldSpec := PADRAO_CHAR_12{}
oDCEX01RAM:HyperLabel := HyperLabel{#EX01RAM,"Ex01ram:",NULL_STRING,"RHSEL_EX01RAM"}

oDCEX01TEL := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX01TEL,_GetInst()}}
oDCEX01TEL:FieldSpec := PADRAO_CHAR_12{}
oDCEX01TEL:HyperLabel := HyperLabel{#EX01TEL,"Ex01tel:",NULL_STRING,"RHSEL_EX01TEL"}

oDCEX01DEM := DateSle{SELF,ResourceID{RHSELPAG03_EX01DEM,_GetInst()}}
oDCEX01DEM:FieldSpec := DATE_FIELD{}
oDCEX01DEM:HyperLabel := HyperLabel{#EX01DEM,"Ex01dem:",NULL_STRING,"RHSEL_EX01DEM"}

oDCEX01ADM := DateSle{SELF,ResourceID{RHSELPAG03_EX01ADM,_GetInst()}}
oDCEX01ADM:FieldSpec := DATE_FIELD{}
oDCEX01ADM:HyperLabel := HyperLabel{#EX01ADM,"Ex01adm:",NULL_STRING,"RHSEL_EX01ADM"}

oDCEX01FUN := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX01FUN,_GetInst()}}
oDCEX01FUN:FieldSpec := PADRAO_CHAR_50{}
oDCEX01FUN:HyperLabel := HyperLabel{#EX01FUN,"Ex01fun:",NULL_STRING,"RHSEL_EX01FUN"}

oDCEX01ULT := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX01ULT,_GetInst()}}
oDCEX01ULT:FieldSpec := PADRAO_NUM_12_2{}
oDCEX01ULT:HyperLabel := HyperLabel{#EX01ULT,"Ex01ult:",NULL_STRING,"RHSEL_EX01ULT"}

oDCEX01AT1 := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX01AT1,_GetInst()}}
oDCEX01AT1:FieldSpec := PADRAO_CHAR_100{}
oDCEX01AT1:HyperLabel := HyperLabel{#EX01AT1,"Ex01at1:",NULL_STRING,"RHSEL_EX01AT1"}

oDCEX01AT2 := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX01AT2,_GetInst()}}
oDCEX01AT2:FieldSpec := PADRAO_CHAR_100{}
oDCEX01AT2:HyperLabel := HyperLabel{#EX01AT2,"Ex01at2:",NULL_STRING,"RHSEL_EX01AT2"}

oDCEX02EMP := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX02EMP,_GetInst()}}
oDCEX02EMP:FieldSpec := PADRAO_CHAR_40{}
oDCEX02EMP:HyperLabel := HyperLabel{#EX02EMP,"Ex02emp:",NULL_STRING,"RHSEL_EX02EMP"}

oDCEX02RAM := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX02RAM,_GetInst()}}
oDCEX02RAM:FieldSpec := PADRAO_CHAR_12{}
oDCEX02RAM:HyperLabel := HyperLabel{#EX02RAM,"Ex02ram:",NULL_STRING,"RHSEL_EX02RAM"}

oDCEX02TEL := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX02TEL,_GetInst()}}
oDCEX02TEL:FieldSpec := PADRAO_CHAR_12{}
oDCEX02TEL:HyperLabel := HyperLabel{#EX02TEL,"Ex02tel:",NULL_STRING,"RHSEL_EX02TEL"}

oDCEX02ADM := DateSle{SELF,ResourceID{RHSELPAG03_EX02ADM,_GetInst()}}
oDCEX02ADM:FieldSpec := DATE_FIELD{}
oDCEX02ADM:HyperLabel := HyperLabel{#EX02ADM,"Ex02adm:",NULL_STRING,"RHSEL_EX02ADM"}

oDCEX02DEM := DateSle{SELF,ResourceID{RHSELPAG03_EX02DEM,_GetInst()}}
oDCEX02DEM:FieldSpec := DATE_FIELD{}
oDCEX02DEM:HyperLabel := HyperLabel{#EX02DEM,"Ex02dem:",NULL_STRING,"RHSEL_EX02DEM"}

oDCEX02FUN := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX02FUN,_GetInst()}}
oDCEX02FUN:FieldSpec := PADRAO_CHAR_50{}
oDCEX02FUN:HyperLabel := HyperLabel{#EX02FUN,"Ex02fun:",NULL_STRING,"RHSEL_EX02FUN"}

oDCEX02ULT := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX02ULT,_GetInst()}}
oDCEX02ULT:FieldSpec := PADRAO_NUM_12_2{}
oDCEX02ULT:HyperLabel := HyperLabel{#EX02ULT,"Ex02ult:",NULL_STRING,"RHSEL_EX02ULT"}

oDCEX02AT1 := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX02AT1,_GetInst()}}
oDCEX02AT1:FieldSpec := PADRAO_CHAR_100{}
oDCEX02AT1:HyperLabel := HyperLabel{#EX02AT1,"Ex02at1:",NULL_STRING,"RHSEL_EX02AT1"}

oDCEX02AT2 := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX02AT2,_GetInst()}}
oDCEX02AT2:FieldSpec := PADRAO_CHAR_100{}
oDCEX02AT2:HyperLabel := HyperLabel{#EX02AT2,"Ex02at2:",NULL_STRING,"RHSEL_EX02AT2"}

oDCEX03EMP := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX03EMP,_GetInst()}}
oDCEX03EMP:FieldSpec := PADRAO_CHAR_40{}
oDCEX03EMP:HyperLabel := HyperLabel{#EX03EMP,"Ex03emp:",NULL_STRING,"RHSEL_EX03EMP"}

oDCEX03RAM := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX03RAM,_GetInst()}}
oDCEX03RAM:FieldSpec := PADRAO_CHAR_12{}
oDCEX03RAM:HyperLabel := HyperLabel{#EX03RAM,"Ex03ram:",NULL_STRING,"RHSEL_EX03RAM"}

oDCEX03TEL := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX03TEL,_GetInst()}}
oDCEX03TEL:FieldSpec := PADRAO_CHAR_12{}
oDCEX03TEL:HyperLabel := HyperLabel{#EX03TEL,"Ex03tel:",NULL_STRING,"RHSEL_EX03TEL"}

oDCEX03ADM := DateSle{SELF,ResourceID{RHSELPAG03_EX03ADM,_GetInst()}}
oDCEX03ADM:FieldSpec := DATE_FIELD{}
oDCEX03ADM:HyperLabel := HyperLabel{#EX03ADM,"Ex03adm:",NULL_STRING,"RHSEL_EX03ADM"}

oDCEX03DEM := DateSle{SELF,ResourceID{RHSELPAG03_EX03DEM,_GetInst()}}
oDCEX03DEM:FieldSpec := DATE_FIELD{}
oDCEX03DEM:HyperLabel := HyperLabel{#EX03DEM,"Ex03dem:",NULL_STRING,"RHSEL_EX03DEM"}

oDCEX03FUN := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX03FUN,_GetInst()}}
oDCEX03FUN:FieldSpec := PADRAO_CHAR_50{}
oDCEX03FUN:HyperLabel := HyperLabel{#EX03FUN,"Ex03fun:",NULL_STRING,"RHSEL_EX03FUN"}

oDCEX03AT1 := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX03AT1,_GetInst()}}
oDCEX03AT1:FieldSpec := PADRAO_CHAR_100{}
oDCEX03AT1:HyperLabel := HyperLabel{#EX03AT1,"Ex02at1:",NULL_STRING,"RHSEL_EX02AT1"}

oDCEX03AT2 := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX03AT2,_GetInst()}}
oDCEX03AT2:FieldSpec := PADRAO_CHAR_100{}
oDCEX03AT2:HyperLabel := HyperLabel{#EX03AT2,"Ex02at2:",NULL_STRING,"RHSEL_EX02AT2"}

oDCSC_EX01EMP := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01EMP,_GetInst()}}
oDCSC_EX01EMP:HyperLabel := HyperLabel{#SC_EX01EMP,"Empresa",NULL_STRING,NULL_STRING}

oDCSC_EX01RAM := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01RAM,_GetInst()}}
oDCSC_EX01RAM:HyperLabel := HyperLabel{#SC_EX01RAM,"Ramo",NULL_STRING,NULL_STRING}

oDCSC_EX01TEL := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01TEL,_GetInst()}}
oDCSC_EX01TEL:HyperLabel := HyperLabel{#SC_EX01TEL,"Telefone:",NULL_STRING,NULL_STRING}

oDCSC_EX01DEM := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01DEM,_GetInst()}}
oDCSC_EX01DEM:HyperLabel := HyperLabel{#SC_EX01DEM,"Demitido",NULL_STRING,NULL_STRING}

oDCSC_EX01ADM := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01ADM,_GetInst()}}
oDCSC_EX01ADM:HyperLabel := HyperLabel{#SC_EX01ADM,"Admitido",NULL_STRING,NULL_STRING}

oDCSC_EX01FUN := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01FUN,_GetInst()}}
oDCSC_EX01FUN:HyperLabel := HyperLabel{#SC_EX01FUN,"Funcao",NULL_STRING,NULL_STRING}

oDCSC_EX01ULT := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01ULT,_GetInst()}}
oDCSC_EX01ULT:HyperLabel := HyperLabel{#SC_EX01ULT,"Ultimo Salario",NULL_STRING,NULL_STRING}

oDCSC_EX01AT1 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01AT1,_GetInst()}}
oDCSC_EX01AT1:HyperLabel := HyperLabel{#SC_EX01AT1,"Atividades",NULL_STRING,NULL_STRING}

oDCEX03ULT := SingleLineEdit{SELF,ResourceID{RHSELPAG03_EX03ULT,_GetInst()}}
oDCEX03ULT:FieldSpec := PADRAO_NUM_12_2{}
oDCEX03ULT:HyperLabel := HyperLabel{#EX03ULT,"Ex03ult:",NULL_STRING,"RHSEL_EX03ULT"}

oDCSC_EX01ULT1 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01ULT1,_GetInst()}}
oDCSC_EX01ULT1:HyperLabel := HyperLabel{#SC_EX01ULT1,"Ultimo Salario",NULL_STRING,NULL_STRING}

oDCSC_EX01RAM1 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01RAM1,_GetInst()}}
oDCSC_EX01RAM1:HyperLabel := HyperLabel{#SC_EX01RAM1,"Ramo",NULL_STRING,NULL_STRING}

oDCSC_EX01DEM1 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01DEM1,_GetInst()}}
oDCSC_EX01DEM1:HyperLabel := HyperLabel{#SC_EX01DEM1,"Demitido",NULL_STRING,NULL_STRING}

oDCSC_EX01ADM1 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01ADM1,_GetInst()}}
oDCSC_EX01ADM1:HyperLabel := HyperLabel{#SC_EX01ADM1,"Admitido",NULL_STRING,NULL_STRING}

oDCSC_EX01AT2 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01AT2,_GetInst()}}
oDCSC_EX01AT2:HyperLabel := HyperLabel{#SC_EX01AT2,"Atividades",NULL_STRING,NULL_STRING}

oDCSC_EX01FUN1 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01FUN1,_GetInst()}}
oDCSC_EX01FUN1:HyperLabel := HyperLabel{#SC_EX01FUN1,"Funcao",NULL_STRING,NULL_STRING}

oDCSC_EX01TEL1 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01TEL1,_GetInst()}}
oDCSC_EX01TEL1:HyperLabel := HyperLabel{#SC_EX01TEL1,"Telefone:",NULL_STRING,NULL_STRING}

oDCSC_EX01EMP1 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01EMP1,_GetInst()}}
oDCSC_EX01EMP1:HyperLabel := HyperLabel{#SC_EX01EMP1,"Empresa",NULL_STRING,NULL_STRING}

oDCSC_EX01RAM2 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01RAM2,_GetInst()}}
oDCSC_EX01RAM2:HyperLabel := HyperLabel{#SC_EX01RAM2,"Ramo",NULL_STRING,NULL_STRING}

oDCSC_EX01ULT2 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01ULT2,_GetInst()}}
oDCSC_EX01ULT2:HyperLabel := HyperLabel{#SC_EX01ULT2,"Ultimo Salario",NULL_STRING,NULL_STRING}

oDCSC_EX01DEM2 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01DEM2,_GetInst()}}
oDCSC_EX01DEM2:HyperLabel := HyperLabel{#SC_EX01DEM2,"Demitido",NULL_STRING,NULL_STRING}

oDCSC_EX01ADM2 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01ADM2,_GetInst()}}
oDCSC_EX01ADM2:HyperLabel := HyperLabel{#SC_EX01ADM2,"Admitido",NULL_STRING,NULL_STRING}

oDCSC_EX01AT3 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01AT3,_GetInst()}}
oDCSC_EX01AT3:HyperLabel := HyperLabel{#SC_EX01AT3,"Atividades",NULL_STRING,NULL_STRING}

oDCSC_EX01FUN2 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01FUN2,_GetInst()}}
oDCSC_EX01FUN2:HyperLabel := HyperLabel{#SC_EX01FUN2,"Funcao",NULL_STRING,NULL_STRING}

oDCSC_EX01TEL2 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01TEL2,_GetInst()}}
oDCSC_EX01TEL2:HyperLabel := HyperLabel{#SC_EX01TEL2,"Telefone:",NULL_STRING,NULL_STRING}

oDCSC_EX01EMP2 := FixedText{SELF,ResourceID{RHSELPAG03_SC_EX01EMP2,_GetInst()}}
oDCSC_EX01EMP2:HyperLabel := HyperLabel{#SC_EX01EMP2,"Empresa",NULL_STRING,NULL_STRING}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#RHSELPAG03,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


END CLASS
CLASS RHSELPAG04 INHERIT DATAWINDOW 

	PROTECT oDCFUNC01 AS SINGLELINEEDIT
	PROTECT oDCSALARIO AS SINGLELINEEDIT
	PROTECT oDCFUNC02 AS SINGLELINEEDIT
	PROTECT oDCOBSEN01 AS SINGLELINEEDIT
	PROTECT oDCOBSEN02 AS SINGLELINEEDIT
	PROTECT oDCOBSEN03 AS SINGLELINEEDIT
	PROTECT oDCSC_FUNC01 AS FIXEDTEXT
	PROTECT oDCSC_SALARIO AS FIXEDTEXT
	PROTECT oDCSC_OBSEN01 AS FIXEDTEXT
// 	instance FUNC01 
// 	instance SALARIO 
// 	instance FUNC02 
// 	instance OBSEN01 
// 	instance OBSEN02 
// 	instance OBSEN03 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS FUNC01() 
RETURN SELF:FieldGet(#FUNC01)


ASSIGN FUNC01(uValue) 
SELF:FieldPut(#FUNC01, uValue)
RETURN FUNC01 := uValue


ACCESS FUNC02() 
RETURN SELF:FieldGet(#FUNC02)


ASSIGN FUNC02(uValue) 
SELF:FieldPut(#FUNC02, uValue)
RETURN FUNC02 := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"RHSELPAG04",_GetInst()},iCtlID)

oDCFUNC01 := SingleLineEdit{SELF,ResourceID{RHSELPAG04_FUNC01,_GetInst()}}
oDCFUNC01:FieldSpec := PADRAO_CHAR_50{}
oDCFUNC01:HyperLabel := HyperLabel{#FUNC01,"Func01:",NULL_STRING,"RHSEL_FUNC01"}

oDCSALARIO := SingleLineEdit{SELF,ResourceID{RHSELPAG04_SALARIO,_GetInst()}}
oDCSALARIO:FieldSpec := PADRAO_NUM_12_2{}
oDCSALARIO:HyperLabel := HyperLabel{#SALARIO,"Salario:",NULL_STRING,"RHSEL_SALARIO"}

oDCFUNC02 := SingleLineEdit{SELF,ResourceID{RHSELPAG04_FUNC02,_GetInst()}}
oDCFUNC02:FieldSpec := PADRAO_CHAR_50{}
oDCFUNC02:HyperLabel := HyperLabel{#FUNC02,"Func02:",NULL_STRING,"RHSEL_FUNC02"}

oDCOBSEN01 := SingleLineEdit{SELF,ResourceID{RHSELPAG04_OBSEN01,_GetInst()}}
oDCOBSEN01:FieldSpec := PADRAO_CHAR_100{}
oDCOBSEN01:HyperLabel := HyperLabel{#OBSEN01,"Obsen01:",NULL_STRING,"RHSEL_OBSEN01"}

oDCOBSEN02 := SingleLineEdit{SELF,ResourceID{RHSELPAG04_OBSEN02,_GetInst()}}
oDCOBSEN02:FieldSpec := PADRAO_CHAR_100{}
oDCOBSEN02:HyperLabel := HyperLabel{#OBSEN02,"Obsen02:",NULL_STRING,"RHSEL_OBSEN02"}

oDCOBSEN03 := SingleLineEdit{SELF,ResourceID{RHSELPAG04_OBSEN03,_GetInst()}}
oDCOBSEN03:FieldSpec := PADRAO_CHAR_100{}
oDCOBSEN03:HyperLabel := HyperLabel{#OBSEN03,"Obsen03:",NULL_STRING,"RHSEL_OBSEN03"}

oDCSC_FUNC01 := FixedText{SELF,ResourceID{RHSELPAG04_SC_FUNC01,_GetInst()}}
oDCSC_FUNC01:HyperLabel := HyperLabel{#SC_FUNC01,"Funcao Pretendida",NULL_STRING,NULL_STRING}

oDCSC_SALARIO := FixedText{SELF,ResourceID{RHSELPAG04_SC_SALARIO,_GetInst()}}
oDCSC_SALARIO:HyperLabel := HyperLabel{#SC_SALARIO,"Salario Pretendido",NULL_STRING,NULL_STRING}

oDCSC_OBSEN01 := FixedText{SELF,ResourceID{RHSELPAG04_SC_OBSEN01,_GetInst()}}
oDCSC_OBSEN01:HyperLabel := HyperLabel{#SC_OBSEN01,"Observações Entrevista",NULL_STRING,NULL_STRING}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#RHSELPAG04,"DataWindow Caption",NULL_STRING,NULL_STRING}

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS OBSEN01() 
RETURN SELF:FieldGet(#OBSEN01)


ASSIGN OBSEN01(uValue) 
SELF:FieldPut(#OBSEN01, uValue)
RETURN OBSEN01 := uValue


ACCESS OBSEN02() 
RETURN SELF:FieldGet(#OBSEN02)


ASSIGN OBSEN02(uValue) 
SELF:FieldPut(#OBSEN02, uValue)
RETURN OBSEN02 := uValue


ACCESS OBSEN03() 
RETURN SELF:FieldGet(#OBSEN03)


ASSIGN OBSEN03(uValue) 
SELF:FieldPut(#OBSEN03, uValue)
RETURN OBSEN03 := uValue


ACCESS SALARIO() 
RETURN SELF:FieldGet(#SALARIO)


ASSIGN SALARIO(uValue) 
SELF:FieldPut(#SALARIO, uValue)
RETURN SALARIO := uValue


END CLASS
STATIC DEFINE RHSELPAG02_BTNCHECKRG := 148
