#region DEFINES
STATIC DEFINE JTRE_ANTERIOR := 156
STATIC DEFINE JTRE_AREA := 117
STATIC DEFINE JTRE_AVAGER := 170
STATIC DEFINE JTRE_AVALIACAO := 135
STATIC DEFINE JTRE_BUSCACURSO := 150
STATIC DEFINE JTRE_BUSCADATA := 154
STATIC DEFINE JTRE_BUSCAFUN := 157
STATIC DEFINE JTRE_BUSCANUMERO := 151
STATIC DEFINE JTRE_BUSCAREFER := 152
STATIC DEFINE JTRE_CARGA := 115
STATIC DEFINE JTRE_CERT := 140
STATIC DEFINE JTRE_CERTIFICADO := 158
STATIC DEFINE JTRE_CMDANALISE := 169
STATIC DEFINE JTRE_CMDANUAL := 175
STATIC DEFINE JTRE_CMDAVALIA := 171
STATIC DEFINE JTRE_CMDINCO := 176
STATIC DEFINE JTRE_CMDTIPO := 166
STATIC DEFINE JTRE_CNOME := 133
STATIC DEFINE JTRE_COMPARECEU := 134
STATIC DEFINE JTRE_COPIAR := 165
STATIC DEFINE JTRE_CURSO := 112
STATIC DEFINE JTRE_DATACUR := 183
STATIC DEFINE JTRE_DATAFIM := 184
STATIC DEFINE JTRE_DESCUR := 113
STATIC DEFINE JTRE_DESPRO := 164
STATIC DEFINE JTRE_ESCCUR := 147
STATIC DEFINE JTRE_ESCCUR1 := 163
STATIC DEFINE JTRE_ESCESC := 144
STATIC DEFINE JTRE_ESCINS := 142
STATIC DEFINE JTRE_ESCINS1 := 182
STATIC DEFINE JTRE_ESCO := 159
STATIC DEFINE JTRE_ESCOLHER := 136
STATIC DEFINE JTRE_ESCRES := 143
STATIC DEFINE JTRE_ESCRES1 := 185
STATIC DEFINE JTRE_ESCRES2 := 186
STATIC DEFINE JTRE_ESCRES3 := 187
STATIC DEFINE JTRE_ESCRES4 := 188
STATIC DEFINE JTRE_ESCSOL := 179
STATIC DEFINE JTRE_ESCSOL1 := 189
STATIC DEFINE JTRE_EXCLUIR := 125
STATIC DEFINE JTRE_FT11 := 122
STATIC DEFINE JTRE_FT12 := 130
STATIC DEFINE JTRE_FT13 := 131
STATIC DEFINE JTRE_HORFIM := 110
STATIC DEFINE JTRE_HORINI := 109
STATIC DEFINE JTRE_IMPORTAR := 138
STATIC DEFINE JTRE_INSTRU := 121
STATIC DEFINE JTRE_JTREINF := 132
STATIC DEFINE JTRE_JTRI := 128
STATIC DEFINE JTRE_NESCOLA := 120
STATIC DEFINE JTRE_NFUNC := 126
STATIC DEFINE JTRE_NINSTU := 119
STATIC DEFINE JTRE_NOMSOL := 181
STATIC DEFINE JTRE_NOVO := 124
STATIC DEFINE JTRE_NUMSOL := 178
STATIC DEFINE JTRE_OBJETIVO := 193
STATIC DEFINE JTRE_PARTI := 127
STATIC DEFINE JTRE_PEGCURDES := 148
STATIC DEFINE JTRE_PEGCURDES1 := 162
STATIC DEFINE JTRE_PEGESC := 173
STATIC DEFINE JTRE_PEGINS := 172
STATIC DEFINE JTRE_PEGSOL := 180
STATIC DEFINE JTRE_PEGSOL2 := 190
STATIC DEFINE JTRE_PEGSOL3 := 191
STATIC DEFINE JTRE_PEGSOL4 := 192
STATIC DEFINE JTRE_PORCURSO := 149
STATIC DEFINE JTRE_PORDATA := 153
STATIC DEFINE JTRE_PORNUMERO := 145
STATIC DEFINE JTRE_PORREFER := 146
STATIC DEFINE JTRE_PRO := 161
STATIC DEFINE JTRE_PROXIMO := 155
STATIC DEFINE JTRE_PT := 111
STATIC DEFINE JTRE_REFER := 114
STATIC DEFINE JTRE_RESPO := 118
STATIC DEFINE JTRE_SC_CARGA := 105
STATIC DEFINE JTRE_SC_CURSO := 104
STATIC DEFINE JTRE_SC_CURSO1 := 160
STATIC DEFINE JTRE_SC_DATACUR := 101
STATIC DEFINE JTRE_SC_DESCUR1 := 139
STATIC DEFINE JTRE_SC_DESCUR2 := 141
STATIC DEFINE JTRE_SC_DESCUR3 := 167
STATIC DEFINE JTRE_SC_HORFIM := 103
STATIC DEFINE JTRE_SC_HORFIM1 := 137
STATIC DEFINE JTRE_SC_HORINI := 102
STATIC DEFINE JTRE_SC_NINSTU := 107
STATIC DEFINE JTRE_SC_NINSTU1 := 177
STATIC DEFINE JTRE_SC_NINSTU2 := 194
STATIC DEFINE JTRE_SC_PARTI := 123
STATIC DEFINE JTRE_SC_REFER := 129
STATIC DEFINE JTRE_SC_RESPO := 106
STATIC DEFINE JTRE_SC_TREIN := 100
STATIC DEFINE JTRE_THESINGLELINEEDIT11 := 130 
STATIC DEFINE JTRE_TIPCUR := 116
STATIC DEFINE JTRE_TIPDIS := 174
STATIC DEFINE JTRE_TIPOANA := 168
STATIC DEFINE JTRE_TREIN := 108
#endregion

PARTIAL CLASS JTRE INHERIT MYDataWindow
PROTECT oDBTREIN AS DataColumn
PROTECT oDBPT AS DataColumn
PROTECT oDBCURSO AS DataColumn
PROTECT oDBDESCUR AS DataColumn
PROTECT oDBCARGA AS DataColumn
PROTECT oDBTIPCUR AS DataColumn
PROTECT oDCSC_TREIN AS FIXEDTEXT
PROTECT oDCSC_DATACUR AS FIXEDTEXT
PROTECT oDCSC_HORINI AS FIXEDTEXT
PROTECT oDCSC_HORFIM AS FIXEDTEXT
PROTECT oDCSC_CURSO AS FIXEDTEXT
PROTECT oDCSC_CARGA AS FIXEDTEXT
PROTECT oDCSC_RESPO AS FIXEDTEXT
PROTECT oDCSC_NINSTU AS FIXEDTEXT
PROTECT oDCTREIN AS SINGLELINEEDIT
PROTECT oDCHORINI AS rightSle
PROTECT oDCHORFIM AS rightSle
PROTECT oDCPT AS rightSle
PROTECT oDCCURSO AS SINGLELINEEDIT
PROTECT oDCDESCUR AS SINGLELINEEDIT
PROTECT oDCREFER AS SINGLELINEEDIT
PROTECT oDCCARGA AS rightSle
PROTECT oDCTIPCUR AS SINGLELINEEDIT
PROTECT oDCAREA AS COMBOBOX
PROTECT oDCRESPO AS SINGLELINEEDIT
PROTECT oDCNINSTU AS rightSle
PROTECT oDCNESCOLA AS rightSle
PROTECT oDCINSTRU AS SINGLELINEEDIT
PROTECT oDCFT11 AS FIXEDTEXT
PROTECT oDCSC_PARTI AS FIXEDTEXT
PROTECT oCCNovo AS PUSHBUTTON
PROTECT oCCEXCLUIR AS PUSHBUTTON
PROTECT oDCNFUNC AS rightSle
PROTECT oDCPARTI AS rightSle
PROTECT oSFJTRI AS JTRI
PROTECT oDCSC_REFER AS FIXEDTEXT
PROTECT oDCFT12 AS FIXEDTEXT
PROTECT oDCFT13 AS FIXEDTEXT
PROTECT oSFJTREINF AS JTREINF
PROTECT oDCCNOME AS SINGLELINEEDIT
PROTECT oCCCompareceu AS PUSHBUTTON
PROTECT oCCAvaliacao AS PUSHBUTTON
PROTECT oCCEscolher AS PUSHBUTTON
PROTECT oDCSC_HORFIM1 AS FIXEDTEXT
PROTECT oCCImportar AS PUSHBUTTON
PROTECT oDCSC_DESCUR1 AS FIXEDTEXT
PROTECT oDCcert AS SINGLELINEEDIT
PROTECT oDCSC_DESCUR2 AS FIXEDTEXT
PROTECT oCCEscins AS PUSHBUTTON
PROTECT oCCESCRES AS PUSHBUTTON
PROTECT oCCESCESC AS PUSHBUTTON
PROTECT oCCpornumero AS PUSHBUTTON
PROTECT oCCporrefer AS PUSHBUTTON
PROTECT oCCesccur AS PUSHBUTTON
PROTECT oCCpegcurdes AS PUSHBUTTON
PROTECT oCCporcurso AS PUSHBUTTON
PROTECT oCCbuscacurso AS PUSHBUTTON
PROTECT oCCbuscanumero AS PUSHBUTTON
PROTECT oCCbuscarefer AS PUSHBUTTON
PROTECT oCCpordata AS PUSHBUTTON
PROTECT oCCbuscadata AS PUSHBUTTON
PROTECT oCCProximo AS PUSHBUTTON
PROTECT oCCAnterior AS PUSHBUTTON
PROTECT oCCbuscaFUN AS PUSHBUTTON
PROTECT oCCcertificado AS PUSHBUTTON
PROTECT oCCEsco AS PUSHBUTTON
PROTECT oDCSC_CURSO1 AS FIXEDTEXT
PROTECT oDCPRO AS SINGLELINEEDIT
PROTECT oCCpegcurdes1 AS PUSHBUTTON
PROTECT oCCesccur1 AS PUSHBUTTON
PROTECT oDCDESPRO AS SINGLELINEEDIT
PROTECT oCCcopiar AS PUSHBUTTON
PROTECT oCCcmdtIPO AS PUSHBUTTON
PROTECT oDCSC_DESCUR3 AS FIXEDTEXT
PROTECT oDCTIPOANA AS SINGLELINEEDIT
PROTECT oCCcmdAnalise AS PUSHBUTTON
PROTECT oDCAVAGER AS SINGLELINEEDIT
PROTECT oCCcmdavalia AS PUSHBUTTON
PROTECT oCCPEGINS AS PUSHBUTTON
PROTECT oCCbtnPEGESC AS PUSHBUTTON
PROTECT oDCTIPDIS AS SINGLELINEEDIT
PROTECT oCCcmdAnual AS PUSHBUTTON
PROTECT oCCcmdinco AS PUSHBUTTON
PROTECT oDCSC_NINSTU1 AS FIXEDTEXT
PROTECT oDCNUMSOL AS rightSle
PROTECT oCCESCSOL AS PUSHBUTTON
PROTECT oCCPEGSOL AS PUSHBUTTON
PROTECT oDCNOMSOL AS SINGLELINEEDIT
PROTECT oCCEscins1 AS PUSHBUTTON
PROTECT oDCdatacur AS DateSle
PROTECT oDCdatafim AS DateSle
PROTECT oCCESCRES1 AS PUSHBUTTON
PROTECT oCCESCRES2 AS PUSHBUTTON
PROTECT oCCESCRES3 AS PUSHBUTTON
PROTECT oCCESCRES4 AS PUSHBUTTON
PROTECT oCCescSOL1 AS PUSHBUTTON
PROTECT oCCPEGSOL2 AS PUSHBUTTON
PROTECT oCCPEGSOL3 AS PUSHBUTTON
PROTECT oCCPEGSOL4 AS PUSHBUTTON
PROTECT oDCOBJETIVO AS SINGLELINEEDIT
PROTECT oDCSC_NINSTU2 AS FIXEDTEXT

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS AREA
RETURN SELF:FieldGet( #AREA )

ASSIGN AREA( uValue )
SELF:FieldPut( #AREA , uValue )

ACCESS AVAGER
RETURN SELF:FieldGet( #AVAGER )

ASSIGN AVAGER( uValue )
SELF:FieldPut( #AVAGER , uValue )

ACCESS CARGA
RETURN SELF:FieldGet( #CARGA )

ASSIGN CARGA( uValue )
SELF:FieldPut( #CARGA , uValue )

ACCESS cert
RETURN SELF:FieldGet( #cert )

ASSIGN cert( uValue )
SELF:FieldPut( #cert , uValue )

ACCESS CNOME
RETURN SELF:FieldGet( #CNOME )

ASSIGN CNOME( uValue )
SELF:FieldPut( #CNOME , uValue )

ACCESS CURSO
RETURN SELF:FieldGet( #CURSO )

ASSIGN CURSO( uValue )
SELF:FieldPut( #CURSO , uValue )

ACCESS datacur
RETURN SELF:FieldGet( #datacur )

ASSIGN datacur( uValue )
SELF:FieldPut( #datacur , uValue )

ACCESS datafim
RETURN SELF:FieldGet( #datafim )

ASSIGN datafim( uValue )
SELF:FieldPut( #datafim , uValue )

ACCESS DESCUR
RETURN SELF:FieldGet( #DESCUR )

ASSIGN DESCUR( uValue )
SELF:FieldPut( #DESCUR , uValue )

ACCESS DESPRO
RETURN SELF:FieldGet( #DESPRO )

ASSIGN DESPRO( uValue )
SELF:FieldPut( #DESPRO , uValue )

METHOD ESCRES1( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,1}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NINSTU",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("INSTRU",oESCMP04:NOME)
ENDIF	

METHOD ESCRES2( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,10}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NINSTU",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("INSTRU",oESCMP04:NOME)
ENDIF	

METHOD ESCRES3( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,97}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NINSTU",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("INSTRU",oESCMP04:NOME)
ENDIF		

METHOD ESCRES4( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,99}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NINSTU",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("INSTRU",oESCMP04:NOME)
ENDIF	

METHOD escSOL1( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,1}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NUMSOL",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("NOMSOL",oESCMP04:NOME)
ENDIF	

ACCESS HORFIM
RETURN SELF:FieldGet( #HORFIM )

ASSIGN HORFIM( uValue )
SELF:FieldPut( #HORFIM , uValue )

ACCESS HORINI
RETURN SELF:FieldGet( #HORINI )

ASSIGN HORINI( uValue )
SELF:FieldPut( #HORINI , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JTRE" , _GetInst()},iCtlID)

	SELF:oDCSC_TREIN := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_TREIN  , _GetInst() } }
	SELF:oDCSC_TREIN:HyperLabel := HyperLabel{#SC_TREIN , "Treinamento:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATACUR := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_DATACUR  , _GetInst() } }
	SELF:oDCSC_DATACUR:HyperLabel := HyperLabel{#SC_DATACUR , "Data:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HORINI := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_HORINI  , _GetInst() } }
	SELF:oDCSC_HORINI:HyperLabel := HyperLabel{#SC_HORINI , "Hora Inicial" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HORFIM := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_HORFIM  , _GetInst() } }
	SELF:oDCSC_HORFIM:HyperLabel := HyperLabel{#SC_HORFIM , "Hora Final" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CURSO := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_CURSO  , _GetInst() } }
	SELF:oDCSC_CURSO:HyperLabel := HyperLabel{#SC_CURSO , "Curso:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CARGA := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_CARGA  , _GetInst() } }
	SELF:oDCSC_CARGA:HyperLabel := HyperLabel{#SC_CARGA , "Carga Horária:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RESPO := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_RESPO  , _GetInst() } }
	SELF:oDCSC_RESPO:HyperLabel := HyperLabel{#SC_RESPO , "Responsável:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NINSTU := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_NINSTU  , _GetInst() } }
	SELF:oDCSC_NINSTU:HyperLabel := HyperLabel{#SC_NINSTU , "instrutor" , NULL_STRING , NULL_STRING}

	SELF:oDCTREIN := SINGLELINEEDIT{SELF , ResourceID{ JTRE_TREIN  , _GetInst() } }
	SELF:oDCTREIN:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCTREIN:Background := Brush{ Color{ 253 , 254 , 220 } }
	SELF:oDCTREIN:HyperLabel := HyperLabel{#TREIN , "Trein:" , NULL_STRING , "TREIN_TREIN"}

	SELF:oDCHORINI := rightSle{SELF , ResourceID{ JTRE_HORINI  , _GetInst() } }
	SELF:oDCHORINI:FieldSpec := PADRAO_NUM_05_2{}
	SELF:oDCHORINI:HyperLabel := HyperLabel{#HORINI , "Horini:" , NULL_STRING , "TREIN_HORINI"}

	SELF:oDCHORFIM := rightSle{SELF , ResourceID{ JTRE_HORFIM  , _GetInst() } }
	SELF:oDCHORFIM:FieldSpec := PADRAO_NUM_05_2{}
	SELF:oDCHORFIM:HyperLabel := HyperLabel{#HORFIM , "Horfim:" , NULL_STRING , "TREIN_HORFIM"}

	SELF:oDCPT := rightSle{SELF , ResourceID{ JTRE_PT  , _GetInst() } }
	SELF:oDCPT:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCPT:HyperLabel := HyperLabel{#PT , "PT" , NULL_STRING , "TREIN_HORFIM"}

	SELF:oDCCURSO := SINGLELINEEDIT{SELF , ResourceID{ JTRE_CURSO  , _GetInst() } }
	SELF:oDCCURSO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCCURSO:HyperLabel := HyperLabel{#CURSO , "Curso:" , NULL_STRING , "TREIN_CURSO"}

	SELF:oDCDESCUR := SINGLELINEEDIT{SELF , ResourceID{ JTRE_DESCUR  , _GetInst() } }
	SELF:oDCDESCUR:FieldSpec := PADRAO_CHAR_120{}
	SELF:oDCDESCUR:HyperLabel := HyperLabel{#DESCUR , "Curso:" , NULL_STRING , "TREIN_DESCUR"}

	SELF:oDCREFER := SINGLELINEEDIT{SELF , ResourceID{ JTRE_REFER  , _GetInst() } }
	SELF:oDCREFER:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCREFER:HyperLabel := HyperLabel{#REFER , "Refer:" , NULL_STRING , "TREIN_REFER"}

	SELF:oDCCARGA := rightSle{SELF , ResourceID{ JTRE_CARGA  , _GetInst() } }
	SELF:oDCCARGA:FieldSpec := PADRAO_NUM_08_2{}
	SELF:oDCCARGA:HyperLabel := HyperLabel{#CARGA , "Carga:" , NULL_STRING , "TREIN_CARGA"}

	SELF:oDCTIPCUR := SINGLELINEEDIT{SELF , ResourceID{ JTRE_TIPCUR  , _GetInst() } }
	SELF:oDCTIPCUR:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPCUR:HyperLabel := HyperLabel{#TIPCUR , "Trein:" , NULL_STRING , "TREIN_TREIN"}

	SELF:oDCAREA := COMBOBOX{SELF , ResourceID{ JTRE_AREA  , _GetInst() } }
	SELF:oDCAREA:FillUsing( SELF:ComboPEGMP05() )
	SELF:oDCAREA:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCAREA:HyperLabel := HyperLabel{#AREA , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCRESPO := SINGLELINEEDIT{SELF , ResourceID{ JTRE_RESPO  , _GetInst() } }
	SELF:oDCRESPO:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCRESPO:HyperLabel := HyperLabel{#RESPO , "Respo:" , NULL_STRING , "TREIN_RESPO"}

	SELF:oDCNINSTU := rightSle{SELF , ResourceID{ JTRE_NINSTU  , _GetInst() } }
	SELF:oDCNINSTU:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNINSTU:HyperLabel := HyperLabel{#NINSTU , "Ninstu:" , NULL_STRING , "TREIN_NINSTU"}

	SELF:oDCNESCOLA := rightSle{SELF , ResourceID{ JTRE_NESCOLA  , _GetInst() } }
	SELF:oDCNESCOLA:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNESCOLA:HyperLabel := HyperLabel{#NESCOLA , "Ninstu:" , NULL_STRING , "TREIN_NINSTU"}

	SELF:oDCINSTRU := SINGLELINEEDIT{SELF , ResourceID{ JTRE_INSTRU  , _GetInst() } }
	SELF:oDCINSTRU:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCINSTRU:HyperLabel := HyperLabel{#INSTRU , "Instru:" , NULL_STRING , "TREIN_INSTRU"}

	SELF:oDCFT11 := FIXEDTEXT{SELF , ResourceID{ JTRE_FT11  , _GetInst() } }
	SELF:oDCFT11:HyperLabel := HyperLabel{#FT11 , "Func." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PARTI := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_PARTI  , _GetInst() } }
	SELF:oDCSC_PARTI:HyperLabel := HyperLabel{#SC_PARTI , "Part." , NULL_STRING , NULL_STRING}

	SELF:oCCNovo := PUSHBUTTON{SELF , ResourceID{ JTRE_NOVO  , _GetInst() } }
	SELF:oCCNovo:HyperLabel := HyperLabel{#Novo , "&Novo" , NULL_STRING , NULL_STRING}

	SELF:oCCEXCLUIR := PUSHBUTTON{SELF , ResourceID{ JTRE_EXCLUIR  , _GetInst() } }
	SELF:oCCEXCLUIR:HyperLabel := HyperLabel{#EXCLUIR , "Excluir" , NULL_STRING , NULL_STRING}

	SELF:oDCNFUNC := rightSle{SELF , ResourceID{ JTRE_NFUNC  , _GetInst() } }
	SELF:oDCNFUNC:FieldSpec := padrao_num_08{}
	SELF:oDCNFUNC:HyperLabel := HyperLabel{#NFUNC , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCPARTI := rightSle{SELF , ResourceID{ JTRE_PARTI  , _GetInst() } }
	SELF:oDCPARTI:FieldSpec := padrao_num_08{}
	SELF:oDCPARTI:HyperLabel := HyperLabel{#PARTI , "Parti:" , NULL_STRING , "TREIN_PARTI"}

	SELF:oDCSC_REFER := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_REFER  , _GetInst() } }
	SELF:oDCSC_REFER:HyperLabel := HyperLabel{#SC_REFER , "Referente:" , NULL_STRING , NULL_STRING}

	SELF:oDCFT12 := FIXEDTEXT{SELF , ResourceID{ JTRE_FT12  , _GetInst() } }
	SELF:oDCFT12:HyperLabel := HyperLabel{#FT12 , "Data Final" , NULL_STRING , NULL_STRING}

	SELF:oDCFT13 := FIXEDTEXT{SELF , ResourceID{ JTRE_FT13  , _GetInst() } }
	SELF:oDCFT13:HyperLabel := HyperLabel{#FT13 , "Escola" , NULL_STRING , NULL_STRING}

	SELF:oDCCNOME := SINGLELINEEDIT{SELF , ResourceID{ JTRE_CNOME  , _GetInst() } }
	SELF:oDCCNOME:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCCNOME:FocusSelect := FSEL_HOME
	SELF:oDCCNOME:HyperLabel := HyperLabel{#CNOME , "Instru:" , NULL_STRING , "TREIN_INSTRU"}

	SELF:oCCCompareceu := PUSHBUTTON{SELF , ResourceID{ JTRE_COMPARECEU  , _GetInst() } }
	SELF:oCCCompareceu:HyperLabel := HyperLabel{#Compareceu , "Compareceu" , NULL_STRING , NULL_STRING}

	SELF:oCCAvaliacao := PUSHBUTTON{SELF , ResourceID{ JTRE_AVALIACAO  , _GetInst() } }
	SELF:oCCAvaliacao:HyperLabel := HyperLabel{#Avaliacao , "Avaliação" , NULL_STRING , NULL_STRING}

	SELF:oCCEscolher := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCOLHER  , _GetInst() } }
	SELF:oCCEscolher:HyperLabel := HyperLabel{#Escolher , "Escolher Participante" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HORFIM1 := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_HORFIM1  , _GetInst() } }
	SELF:oDCSC_HORFIM1:HyperLabel := HyperLabel{#SC_HORFIM1 , "Prg Trein." , NULL_STRING , NULL_STRING}

	SELF:oCCImportar := PUSHBUTTON{SELF , ResourceID{ JTRE_IMPORTAR  , _GetInst() } }
	SELF:oCCImportar:HyperLabel := HyperLabel{#Importar , "Importar" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESCUR1 := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_DESCUR1  , _GetInst() } }
	SELF:oDCSC_DESCUR1:HyperLabel := HyperLabel{#SC_DESCUR1 , "Requer Certificado" , NULL_STRING , NULL_STRING}

	SELF:oDCcert := SINGLELINEEDIT{SELF , ResourceID{ JTRE_CERT  , _GetInst() } }
	SELF:oDCcert:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCcert:Background := Brush{ Color{ 253 , 254 , 220 } }
	SELF:oDCcert:HyperLabel := HyperLabel{#cert , "Trein:" , NULL_STRING , "TREIN_TREIN"}

	SELF:oDCSC_DESCUR2 := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_DESCUR2  , _GetInst() } }
	SELF:oDCSC_DESCUR2:HyperLabel := HyperLabel{#SC_DESCUR2 , "TIPO" , NULL_STRING , NULL_STRING}

	SELF:oCCEscins := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCINS  , _GetInst() } }
	SELF:oCCEscins:HyperLabel := HyperLabel{#Escins , "Escolher Instrutor" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCRES  , _GetInst() } }
	SELF:oCCESCRES:HyperLabel := HyperLabel{#ESCRES , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCESCESC := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCESC  , _GetInst() } }
	SELF:oCCESCESC:HyperLabel := HyperLabel{#ESCESC , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCpornumero := PUSHBUTTON{SELF , ResourceID{ JTRE_PORNUMERO  , _GetInst() } }
	SELF:oCCpornumero:Image := ico_az{}
	SELF:oCCpornumero:HyperLabel := HyperLabel{#pornumero , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCporrefer := PUSHBUTTON{SELF , ResourceID{ JTRE_PORREFER  , _GetInst() } }
	SELF:oCCporrefer:Image := ico_az{}
	SELF:oCCporrefer:HyperLabel := HyperLabel{#porrefer , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCesccur := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCCUR  , _GetInst() } }
	SELF:oCCesccur:HyperLabel := HyperLabel{#esccur , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCpegcurdes := PUSHBUTTON{SELF , ResourceID{ JTRE_PEGCURDES  , _GetInst() } }
	SELF:oCCpegcurdes:HyperLabel := HyperLabel{#pegcurdes , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCporcurso := PUSHBUTTON{SELF , ResourceID{ JTRE_PORCURSO  , _GetInst() } }
	SELF:oCCporcurso:Image := ico_az{}
	SELF:oCCporcurso:HyperLabel := HyperLabel{#porcurso , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscacurso := PUSHBUTTON{SELF , ResourceID{ JTRE_BUSCACURSO  , _GetInst() } }
	SELF:oCCbuscacurso:Image := ico_find{}
	SELF:oCCbuscacurso:HyperLabel := HyperLabel{#buscacurso , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscanumero := PUSHBUTTON{SELF , ResourceID{ JTRE_BUSCANUMERO  , _GetInst() } }
	SELF:oCCbuscanumero:Image := ico_find{}
	SELF:oCCbuscanumero:HyperLabel := HyperLabel{#buscanumero , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscarefer := PUSHBUTTON{SELF , ResourceID{ JTRE_BUSCAREFER  , _GetInst() } }
	SELF:oCCbuscarefer:Image := ico_find{}
	SELF:oCCbuscarefer:HyperLabel := HyperLabel{#buscarefer , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCpordata := PUSHBUTTON{SELF , ResourceID{ JTRE_PORDATA  , _GetInst() } }
	SELF:oCCpordata:Image := ico_az{}
	SELF:oCCpordata:HyperLabel := HyperLabel{#pordata , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscadata := PUSHBUTTON{SELF , ResourceID{ JTRE_BUSCADATA  , _GetInst() } }
	SELF:oCCbuscadata:Image := ico_find{}
	SELF:oCCbuscadata:HyperLabel := HyperLabel{#buscadata , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCProximo := PUSHBUTTON{SELF , ResourceID{ JTRE_PROXIMO  , _GetInst() } }
	SELF:oCCProximo:Image := ico_next{}
	SELF:oCCProximo:HyperLabel := HyperLabel{#Proximo , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCAnterior := PUSHBUTTON{SELF , ResourceID{ JTRE_ANTERIOR  , _GetInst() } }
	SELF:oCCAnterior:Image := ico_previous{}
	SELF:oCCAnterior:HyperLabel := HyperLabel{#Anterior , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscaFUN := PUSHBUTTON{SELF , ResourceID{ JTRE_BUSCAFUN  , _GetInst() } }
	SELF:oCCbuscaFUN:Image := ico_find{}
	SELF:oCCbuscaFUN:HyperLabel := HyperLabel{#buscaFUN , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCcertificado := PUSHBUTTON{SELF , ResourceID{ JTRE_CERTIFICADO  , _GetInst() } }
	SELF:oCCcertificado:HyperLabel := HyperLabel{#certificado , "certificado" , NULL_STRING , NULL_STRING}

	SELF:oCCEsco := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCO  , _GetInst() } }
	SELF:oCCEsco:HyperLabel := HyperLabel{#Esco , "Escolher Ativos" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CURSO1 := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_CURSO1  , _GetInst() } }
	SELF:oDCSC_CURSO1:HyperLabel := HyperLabel{#SC_CURSO1 , "Procedimento" , NULL_STRING , NULL_STRING}

	SELF:oDCPRO := SINGLELINEEDIT{SELF , ResourceID{ JTRE_PRO  , _GetInst() } }
	SELF:oDCPRO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCPRO:HyperLabel := HyperLabel{#PRO , "Curso:" , NULL_STRING , "TREIN_CURSO"}

	SELF:oCCpegcurdes1 := PUSHBUTTON{SELF , ResourceID{ JTRE_PEGCURDES1  , _GetInst() } }
	SELF:oCCpegcurdes1:HyperLabel := HyperLabel{#pegcurdes1 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCesccur1 := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCCUR1  , _GetInst() } }
	SELF:oCCesccur1:HyperLabel := HyperLabel{#esccur1 , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCDESPRO := SINGLELINEEDIT{SELF , ResourceID{ JTRE_DESPRO  , _GetInst() } }
	SELF:oDCDESPRO:FieldSpec := PADRAO_CHAR_120{}
	SELF:oDCDESPRO:HyperLabel := HyperLabel{#DESPRO , "Curso:" , NULL_STRING , "TREIN_DESCUR"}

	SELF:oCCcopiar := PUSHBUTTON{SELF , ResourceID{ JTRE_COPIAR  , _GetInst() } }
	SELF:oCCcopiar:HyperLabel := HyperLabel{#copiar , "Copiar-->" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdtIPO := PUSHBUTTON{SELF , ResourceID{ JTRE_CMDTIPO  , _GetInst() } }
	SELF:oCCcmdtIPO:HyperLabel := HyperLabel{#cmdtIPO , "Int Ext" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESCUR3 := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_DESCUR3  , _GetInst() } }
	SELF:oDCSC_DESCUR3:HyperLabel := HyperLabel{#SC_DESCUR3 , "Analise Eficacia" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPOANA := SINGLELINEEDIT{SELF , ResourceID{ JTRE_TIPOANA  , _GetInst() } }
	SELF:oDCTIPOANA:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPOANA:Background := Brush{ Color{ 253 , 254 , 220 } }
	SELF:oDCTIPOANA:HyperLabel := HyperLabel{#TIPOANA , "Trein:" , NULL_STRING , "TREIN_TREIN"}

	SELF:oCCcmdAnalise := PUSHBUTTON{SELF , ResourceID{ JTRE_CMDANALISE  , _GetInst() } }
	SELF:oCCcmdAnalise:HyperLabel := HyperLabel{#cmdAnalise , "Interno Externo Nao" , NULL_STRING , NULL_STRING}

	SELF:oDCAVAGER := SINGLELINEEDIT{SELF , ResourceID{ JTRE_AVAGER  , _GetInst() } }
	SELF:oDCAVAGER:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCAVAGER:Background := Brush{ Color{ 253 , 254 , 220 } }
	SELF:oDCAVAGER:HyperLabel := HyperLabel{#AVAGER , "Trein:" , NULL_STRING , "TREIN_TREIN"}

	SELF:oCCcmdavalia := PUSHBUTTON{SELF , ResourceID{ JTRE_CMDAVALIA  , _GetInst() } }
	SELF:oCCcmdavalia:HyperLabel := HyperLabel{#cmdavalia , "Avaliação" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGINS := PUSHBUTTON{SELF , ResourceID{ JTRE_PEGINS  , _GetInst() } }
	SELF:oCCPEGINS:HyperLabel := HyperLabel{#PEGINS , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnPEGESC := PUSHBUTTON{SELF , ResourceID{ JTRE_BTNPEGESC  , _GetInst() } }
	SELF:oCCbtnPEGESC:HyperLabel := HyperLabel{#btnPEGESC , "-->" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPDIS := SINGLELINEEDIT{SELF , ResourceID{ JTRE_TIPDIS  , _GetInst() } }
	SELF:oDCTIPDIS:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPDIS:HyperLabel := HyperLabel{#TIPDIS , "Trein:" , NULL_STRING , "TREIN_TREIN"}

	SELF:oCCcmdAnual := PUSHBUTTON{SELF , ResourceID{ JTRE_CMDANUAL  , _GetInst() } }
	SELF:oCCcmdAnual:HyperLabel := HyperLabel{#cmdAnual , "Anual" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdinco := PUSHBUTTON{SELF , ResourceID{ JTRE_CMDINCO  , _GetInst() } }
	SELF:oCCcmdinco:HyperLabel := HyperLabel{#cmdinco , "Incorparado" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NINSTU1 := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_NINSTU1  , _GetInst() } }
	SELF:oDCSC_NINSTU1:HyperLabel := HyperLabel{#SC_NINSTU1 , "Solicitante" , NULL_STRING , NULL_STRING}

	SELF:oDCNUMSOL := rightSle{SELF , ResourceID{ JTRE_NUMSOL  , _GetInst() } }
	SELF:oDCNUMSOL:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNUMSOL:TooltipText := "Numero do Solicitante do Curso"
	SELF:oDCNUMSOL:HyperLabel := HyperLabel{#NUMSOL , "Ninstu:" , NULL_STRING , "TREIN_NINSTU"}

	SELF:oCCESCSOL := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCSOL  , _GetInst() } }
	SELF:oCCESCSOL:HyperLabel := HyperLabel{#ESCSOL , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCPEGSOL := PUSHBUTTON{SELF , ResourceID{ JTRE_PEGSOL  , _GetInst() } }
	SELF:oCCPEGSOL:HyperLabel := HyperLabel{#PEGSOL , "-->" , NULL_STRING , NULL_STRING}

	SELF:oDCNOMSOL := SINGLELINEEDIT{SELF , ResourceID{ JTRE_NOMSOL  , _GetInst() } }
	SELF:oDCNOMSOL:FieldSpec := PADRAO_CHAR_30{}
	SELF:oDCNOMSOL:TooltipText := "Nome do Solicitabnte"
	SELF:oDCNOMSOL:HyperLabel := HyperLabel{#NOMSOL , "Instru:" , NULL_STRING , "TREIN_INSTRU"}

	SELF:oCCEscins1 := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCINS1  , _GetInst() } }
	SELF:oCCEscins1:HyperLabel := HyperLabel{#Escins1 , "Escolher Solicitante" , NULL_STRING , NULL_STRING}

	SELF:oDCdatacur := DateSle{SELF , ResourceID{ JTRE_DATACUR  , _GetInst() } }
	SELF:oDCdatacur:FieldSpec := date_field{}
	SELF:oDCdatacur:HyperLabel := HyperLabel{#datacur , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCdatafim := DateSle{SELF , ResourceID{ JTRE_DATAFIM  , _GetInst() } }
	SELF:oDCdatafim:FieldSpec := date_field{}
	SELF:oDCdatafim:HyperLabel := HyperLabel{#datafim , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES1 := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCRES1  , _GetInst() } }
	SELF:oCCESCRES1:HyperLabel := HyperLabel{#ESCRES1 , "1" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES2 := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCRES2  , _GetInst() } }
	SELF:oCCESCRES2:HyperLabel := HyperLabel{#ESCRES2 , "10" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES3 := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCRES3  , _GetInst() } }
	SELF:oCCESCRES3:HyperLabel := HyperLabel{#ESCRES3 , "97" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES4 := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCRES4  , _GetInst() } }
	SELF:oCCESCRES4:HyperLabel := HyperLabel{#ESCRES4 , "99" , NULL_STRING , NULL_STRING}

	SELF:oCCescSOL1 := PUSHBUTTON{SELF , ResourceID{ JTRE_ESCSOL1  , _GetInst() } }
	SELF:oCCescSOL1:HyperLabel := HyperLabel{#escSOL1 , "01" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGSOL2 := PUSHBUTTON{SELF , ResourceID{ JTRE_PEGSOL2  , _GetInst() } }
	SELF:oCCPEGSOL2:HyperLabel := HyperLabel{#PEGSOL2 , "10" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGSOL3 := PUSHBUTTON{SELF , ResourceID{ JTRE_PEGSOL3  , _GetInst() } }
	SELF:oCCPEGSOL3:HyperLabel := HyperLabel{#PEGSOL3 , "97" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGSOL4 := PUSHBUTTON{SELF , ResourceID{ JTRE_PEGSOL4  , _GetInst() } }
	SELF:oCCPEGSOL4:HyperLabel := HyperLabel{#PEGSOL4 , "99" , NULL_STRING , NULL_STRING}

	SELF:oDCOBJETIVO := SINGLELINEEDIT{SELF , ResourceID{ JTRE_OBJETIVO  , _GetInst() } }
	SELF:oDCOBJETIVO:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCOBJETIVO:TooltipText := "Nome do Solicitabnte"
	SELF:oDCOBJETIVO:HyperLabel := HyperLabel{#OBJETIVO , "Instru:" , NULL_STRING , "TREIN_INSTRU"}

	SELF:oDCSC_NINSTU2 := FIXEDTEXT{SELF , ResourceID{ JTRE_SC_NINSTU2  , _GetInst() } }
	SELF:oDCSC_NINSTU2:HyperLabel := HyperLabel{#SC_NINSTU2 , "Objetivo" , NULL_STRING , NULL_STRING}

	SELF:Caption := "Treinamento"
	SELF:Menu := STANDARDSHELLMENU{}
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#JTRE , "Treinamento" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBTREIN := DataColumn{PADRAO_NUM_08{}}
	SELF:oDBTREIN:Width := 7
	SELF:oDBTREIN:HyperLabel := SELF:oDCTREIN:HyperLabel
	SELF:oDBTREIN:Caption := "Trein:"
	SELF:Browser:AddColumn(SELF:oDBTREIN)

	SELF:oDBPT := DataColumn{PADRAO_NUM_08{}}
	SELF:oDBPT:Width := 12
	SELF:oDBPT:HyperLabel := SELF:oDCPT:HyperLabel
	SELF:oDBPT:Caption := "PT"
	SELF:Browser:AddColumn(SELF:oDBPT)

	SELF:oDBCURSO := DataColumn{PADRAO_CHAR_20{}}
	SELF:oDBCURSO:Width := 7
	SELF:oDBCURSO:HyperLabel := SELF:oDCCURSO:HyperLabel
	SELF:oDBCURSO:Caption := "Curso:"
	SELF:Browser:AddColumn(SELF:oDBCURSO)

	SELF:oDBDESCUR := DataColumn{PADRAO_CHAR_120{}}
	SELF:oDBDESCUR:Width := 8
	SELF:oDBDESCUR:HyperLabel := SELF:oDCDESCUR:HyperLabel
	SELF:oDBDESCUR:Caption := "Curso:"
	SELF:Browser:AddColumn(SELF:oDBDESCUR)

	SELF:oDBCARGA := DataColumn{PADRAO_NUM_08_2{}}
	SELF:oDBCARGA:Width := 7
	SELF:oDBCARGA:HyperLabel := SELF:oDCCARGA:HyperLabel
	SELF:oDBCARGA:Caption := "Carga:"
	SELF:Browser:AddColumn(SELF:oDBCARGA)

	SELF:oDBTIPCUR := DataColumn{PADRAO_CHAR_01{}}
	SELF:oDBTIPCUR:Width := 8
	SELF:oDBTIPCUR:HyperLabel := SELF:oDCTIPCUR:HyperLabel
	SELF:oDBTIPCUR:Caption := "Trein:"
	SELF:Browser:AddColumn(SELF:oDBTIPCUR)

	SELF:ViewAs(#FormView)

	SELF:oSFJTRI := JTRI{SELF , JTRE_JTRI }
	SELF:oSFJTRI:Show()
	SELF:oSFJTREINF := JTREINF{SELF , JTRE_JTREINF }
	SELF:oSFJTREINF:Show()

	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS INSTRU
RETURN SELF:FieldGet( #INSTRU )

ASSIGN INSTRU( uValue )
SELF:FieldPut( #INSTRU , uValue )

ACCESS NESCOLA
RETURN SELF:FieldGet( #NESCOLA )

ASSIGN NESCOLA( uValue )
SELF:FieldPut( #NESCOLA , uValue )

ACCESS NFUNC
RETURN SELF:FieldGet( #NFUNC )

ASSIGN NFUNC( uValue )
SELF:FieldPut( #NFUNC , uValue )

ACCESS NINSTU
RETURN SELF:FieldGet( #NINSTU )

ASSIGN NINSTU( uValue )
SELF:FieldPut( #NINSTU , uValue )

ACCESS NOMSOL
RETURN SELF:FieldGet( #NOMSOL )

ASSIGN NOMSOL( uValue )
SELF:FieldPut( #NOMSOL , uValue )

ACCESS NUMSOL
RETURN SELF:FieldGet( #NUMSOL )

ASSIGN NUMSOL( uValue )
SELF:FieldPut( #NUMSOL , uValue )

ACCESS OBJETIVO
RETURN SELF:FieldGet( #OBJETIVO )

ASSIGN OBJETIVO( uValue )
SELF:FieldPut( #OBJETIVO , uValue )

ACCESS PARTI
RETURN SELF:FieldGet( #PARTI )

ASSIGN PARTI( uValue )
SELF:FieldPut( #PARTI , uValue )

METHOD PEGSOL2( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,10}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NUMSOL",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("NOMSOL",oESCMP04:NOME)
ENDIF	

METHOD PEGSOL3( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,97}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NUMSOL",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("NOMSOL",oESCMP04:NOME)
ENDIF		

METHOD PEGSOL4( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,99}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NUMSOL",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("NOMSOL",oESCMP04:NOME)
ENDIF		

ACCESS PRO
RETURN SELF:FieldGet( #PRO )

ASSIGN PRO( uValue )
SELF:FieldPut( #PRO , uValue )

ACCESS PT
RETURN SELF:FieldGet( #PT )

ASSIGN PT( uValue )
SELF:FieldPut( #PT , uValue )

ACCESS REFER
RETURN SELF:FieldGet( #REFER )

ASSIGN REFER( uValue )
SELF:FieldPut( #REFER , uValue )

ACCESS RESPO
RETURN SELF:FieldGet( #RESPO )

ASSIGN RESPO( uValue )
SELF:FieldPut( #RESPO , uValue )

ACCESS TIPCUR
RETURN SELF:FieldGet( #TIPCUR )

ASSIGN TIPCUR( uValue )
SELF:FieldPut( #TIPCUR , uValue )

ACCESS TIPDIS
RETURN SELF:FieldGet( #TIPDIS )

ASSIGN TIPDIS( uValue )
SELF:FieldPut( #TIPDIS , uValue )

ACCESS TIPOANA
RETURN SELF:FieldGet( #TIPOANA )

ASSIGN TIPOANA( uValue )
SELF:FieldPut( #TIPOANA , uValue )

ACCESS TREIN
RETURN SELF:FieldGet( #TREIN )

ASSIGN TREIN( uValue )
SELF:FieldPut( #TREIN , uValue )

END CLASS
STATIC DEFINE JTRE_BTNPEGESC := 173
