PARTIAL CLASS XJAC2
METHOD CALCULAR() 
LOCAL nVAL1,nVAL2,nVAL3 AS FLOAT
LOCAL nAEP AS DWORD
LOCAL oACDI AS USEREDE
LOCAL aDAD AS ARRAY
nVAL1 :=SELF:SERVER:X01
nVAL1+=SELF:SERVER:X02
nVAL1+=SELF:SERVER:X03
nVAL1+=SELF:SERVER:X04
nVAL1+=SELF:SERVER:X05
nVAL1+=SELF:SERVER:X06
nVAL1+=SELF:SERVER:X07
nVAL1+=SELF:SERVER:X08
nVAL1+=SELF:SERVER:X09
nVAL1+=SELF:SERVER:X10
nVAL2 :=SELF:SERVER:X11
nVAL2+=SELF:SERVER:X12
nVAL2+=SELF:SERVER:X13
nVAL2+=SELF:SERVER:X14
nVAL2+=SELF:SERVER:X15
nVAL2+=SELF:SERVER:X16
nVAL2+=SELF:SERVER:X17
nVAL2+=SELF:SERVER:X18
nVAL2+=SELF:SERVER:X19
nVAL2+=SELF:SERVER:X20
nVAL3 :=SELF:SERVER:X21
nVAL3+=SELF:SERVER:X22
nVAL3+=SELF:SERVER:X23
nVAL3+=SELF:SERVER:X24
nVAL3+=SELF:SERVER:X25
nVAL3+=SELF:SERVER:X26
nVAL3+=SELF:SERVER:X27
nVAL3+=SELF:SERVER:X28
nVAL3+=SELF:SERVER:X29
nVAL3+=SELF:SERVER:X30
SELF:SERVER:SUMX:=(nVAL1+nVAL2+nVAL3)
SELF:SERVER:MEDX:=DIVIDIR(SELF:SERVER:SUMX,30,10,4)


nVAL1 :=SELF:SERVER:R01
nVAL1+=SELF:SERVER:R02
nVAL1+=SELF:SERVER:R03
nVAL1+=SELF:SERVER:R04
nVAL1+=SELF:SERVER:R05
nVAL1+=SELF:SERVER:R06
nVAL1+=SELF:SERVER:R07
nVAL1+=SELF:SERVER:R08
nVAL1+=SELF:SERVER:R09
nVAL1+=SELF:SERVER:R10
nVAL2 :=SELF:SERVER:R11
nVAL2+=SELF:SERVER:R12
nVAL2+=SELF:SERVER:R13
nVAL2+=SELF:SERVER:R14
nVAL2+=SELF:SERVER:R15
nVAL2+=SELF:SERVER:R16
nVAL2+=SELF:SERVER:R17
nVAL2+=SELF:SERVER:R18
nVAL2+=SELF:SERVER:R19
nVAL2+=SELF:SERVER:R20
nVAL3 :=SELF:SERVER:R21
nVAL3+=SELF:SERVER:R22
nVAL3+=SELF:SERVER:R23
nVAL3+=SELF:SERVER:R24
nVAL3+=SELF:SERVER:R25
nVAL3+=SELF:SERVER:R26
nVAL3+=SELF:SERVER:R27
nVAL3+=SELF:SERVER:R28
nVAL3+=SELF:SERVER:R29
nVAL3+=SELF:SERVER:R30
SELF:SERVER:SUMR:=nVAL1+nVAL2+nVAL3
SELF:SERVER:MEDR:=DIVIDIR(SELF:SERVER:SUMR,30,8,4)
SELF:SERVER:SIGMA:=DIVIDIR(SELF:SERVER:MEDR,2.326,12,4)

nVAL1:=(SELF:SERVER:MAX)-(SELF:SERVER:MEDX)
nVAL2:=3*(SELF:SERVER:SIGMA)
SELF:SERVER:PPKA:=DIVIDIR(nVAL1,nVAL2)

nVAL1:=(SELF:SERVER:MEDX)-(SELF:SERVER:MIN)
nVAL2:=3*(SELF:SERVER:SIGMA)
SELF:SERVER:PPKB:=DIVIDIR(nVAL1,nVAL2)

nVAL1:=IF(SELF:SERVER:PPKA>SELF:SERVER:PPKB,SELF:SERVER:PPKB,SELF:SERVER:PPKA)
SELF:SERVER:PPK:=nVAL1



nVAL1:=(SELF:SERVER:MAX)-(SELF:SERVER:MIN)
nVAL2:=6*(SELF:SERVER:SIGMA)
SELF:SERVER:PP:=DIVIDIR(nVAL1,nVAL2)



nVAL1:=(SELF:SERVER:MEDR)*.577
nVAL2:=(SELF:SERVER:MEDX)-nVAL1
SELF:SERVER:LIC:=TRUNCAR(nVAL2,3)


nVAL1:=(SELF:SERVER:MEDR)*.577
nVAL2:=(SELF:SERVER:MEDX)+nVAL1
SELF:SERVER:LSC:=TRUNCAR(nVAL2,3)

nAEP:=SELF:SERVER:ACP
aDAD:={zCURINI,"ACDI.DBF",zCURDIR}
oACDI:=USEREDE{aDAD}
IF oACDI:nERRO=0
   oACDI:SETORDER(4) //AEP
   oACDI:GoTop()
   oACDI:SEEK(nAEP)
   WHILE oACDI:FIELDGET("AEP")=nAEP .AND. ! oACDI:EOF
         oACDI:FIELDPUT("LSC",SELF:SERVER:LSC)
         oACDI:FIELDPUT("LIC",SELF:SERVER:LIC)
         oACDI:SKIP()
    ENDDO
    oACDI:CLOSE()
ENDIF
SELF:CALMAXMIN("AEPX.DBF","AEPR.DBF")

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","AEP")	

METHOD PEGACD 
LOCAL oACDI,oACD AS USEREDE
LOCAL nAEP,nACD AS DWORD
LOCAL W AS BYTE
LOCAL aDAD,Aval AS ARRAY
LOCAL cMED,cVAL AS STRING


IF ! MDG("Importar Media")
	RETURN
ENDIF
aVAL:={}
FOR W:=1 TO 30
    AAdd(aVAL,{0,0})
NEXT W
W       :=1
nACD:=SELF:ACD
nAEP:=SELF:SERVER:ACP
aDAD:={zCURINI,"ACDI.DBF",zCURDIR}
oACDI:=USEREDE{aDAD}
IF oACDI:nERRO=0
   oACDI:SETORDER(2)
   oACDI:GOTOP()
   oACDI:SEEK(Str(nACD,8))
   WHILE oACDI:FIELDGET("ACD")=nACD .AND. W<31 .AND. ! oACDI:EOF
         oACDI:FIELDPUT("AEP",nAEP)
         oACDI:FIELDPUT("ORDEM",W)
         aVAL[W][1]:=oACDI:FIELDGET("MEDX")
         aVAL[W][2]:=oACDI:FIELDGET("VALR")
         W++
         oACDI:SKIP()
   ENDDO
   oACDI:CLOSE()
ENDIF

aDAD:={zCURINI,"ACD.DBF",zCURDIR}
oACD:=USEREDE{aDAD}
IF oACD:nERRO=0
   oACD:GOTOP()
   oACD:SEEK(nACD)
   IF oACD:FOUND
       SELF:SERVER:CLIENTE :=oACD:FIELDGET("CLIENTE")
       SELF:SERVER:CLINOME :=oACD:FIELDGET("CLINOME")
       SELF:SERVER:DESENHO	:=oACD:FIELDGET("DESENHO")
       SELF:SERVER:DESCRI	:=oACD:FIELDGET("DESCRI")
       SELF:SERVER:CARAC  	:=oACD:FIELDGET("CARAC")
       SELF:SERVER:INSTRU	:=oACD:FIELDGET("INSTRU")
       SELF:SERVER:DESCII	:=oACD:FIELDGET("DESCII")
       SELF:SERVER:MIN   	:=oACD:FIELDGET("MIN")
       SELF:SERVER:MAX    	:=oACD:FIELDGET("MAX")
       SELF:SERVER:SEQ:=oACD:FIELDGET("SEQ")
       SELF:SERVER:SSQ:=oACD:FIELDGET("SSQ")
       SELF:SERVER:OPERACAO:=oACD:FIELDGET("OPERACAO")
       SELF:SERVER:REVD:=oACD:FIELDGET("REVD")
       SELF:SERVER:DATAR:=oACD:FIELDGET("DATAR")
   ENDIF
   oACD:CLOSE()
ENDIF

FOR w:=1 TO 30
    CVAL:="X"+StrZero(W,2)
	CMED:="R"+StrZero(W,2)
	SELF:SERVER:FIELDPUT(cVAL,aVAL[W][1])
	SELF:SERVER:FIELDPUT(cMED,aVAL[W][2])	
NEXT w	


SELF:CALCULAR()




METHOD PEGACD02 
LOCAL oACDI,oACD AS USEREDE
LOCAL nAEP,nACD AS DWORD
LOCAL nVAL,nVAL2 AS FLOAT
LOCAL W AS BYTE
LOCAL aVAL,aDAD AS ARRAY
LOCAL cMED,cVAL AS STRING

IF ! MDG("Importar Lançamentos")
   RETURN
ENDIF
IF ! MDG("Isto recalcular as medias- Continuar")
	RETURN
ENDIF
	
aVAL:={}
FOR W:=1 TO 30
    AAdd(aVAL,{0,0})
NEXT W
W :=1
nACD:=SELF:ACD
nAEP:=SELF:SERVER:ACP
aDAD:={zCURINI,"ACDI.DBF",zCURDIR}
oACDI:=USEREDE{aDAD}
IF oACDI:nERRO=0
     oACDI:SETORDER(2)
     oACDI:GOTOP()
     oACDI:SEEK(Str(nACD,8))
     WHILE oACDI:FIELDGET("ACD")=nACD .AND. W<31 .AND. ! oACDI:EOF
         nVAL:=oACDI:FIELDGET("VAL01")
         nVAL+=oACDI:FIELDGET("VAL02")
         nVAL+=oACDI:FIELDGET("VAL03")
         nVAL+=oACDI:FIELDGET("VAL04")
         nVAL+=oACDI:FIELDGET("VAL05")
         nVAL2:=DIVIDIR(nVAL,5)
         oACDI:FIELDPUT("MEDX",nVAL2)


         nVAL :=oACDI:FIELDGET("VAL01")
          IF oACDI:FIELDGET("VAL02")<nVAL
              nVAL :=oACDI:FIELDGET("VAL02")
          ENDIF
          IF oACDI:FIELDGET("VAL03")<nVAL
              nVAL :=oACDI:FIELDGET("VAL03")
          ENDIF
          IF oACDI:FIELDGET("VAL04")<nVAL
              nVAL :=oACDI:FIELDGET("VAL04")
          ENDIF
          IF oACDI:FIELDGET("VAL05")<nVAL
              nVAL :=oACDI:FIELDGET("VAL05")
          ENDIF

         nVAL2 :=oACDI:FIELDGET("VAL01")
          IF oACDI:FIELDGET("VAL02")>nVAL2
              nVAL2 :=oACDI:FIELDGET("VAL02")
          ENDIF
          IF oACDI:FIELDGET("VAL03")>nVAL2
              nVAL2 :=oACDI:FIELDGET("VAL03")
          ENDIF
          IF oACDI:FIELDGET("VAL04")>nVAL2
              nVAL2 :=oACDI:FIELDGET("VAL04")
          ENDIF
          IF oACDI:FIELDGET("VAL05")>nVAL2
              nVAL2 :=oACDI:FIELDGET("VAL05")
          ENDIF

         oACDI:FIELDPUT("VALR",FloatFormat(nVAL2-nVAL,2,3))

         oACDI:FIELDPUT("AEP",nAEP)
         oACDI:FIELDPUT("ORDEM",W)
         aVAL[W][1]:=oACDI:FIELDGET("MEDX")
         aVAL[W][2]:=oACDI:FIELDGET("VALR")
           W++
           oACDI:SKIP()
     ENDDO
     oACDI:CLOSE()
ENDIF


aDAD:={zCURINI,"ACD.DBF",zCURDIR}
oACD:=USEREDE{aDAD}
IF oACD:nERRO=0
     oACD:GOTOP()
     oACD:SEEK(nACD)
     IF oACD:FOUND
          SELF:SERVER:CLIENTE     :=oACD:FIELDGET("CLIENTE")
          SELF:SERVER:CLINOME    :=oACD:FIELDGET("CLINOME")
          SELF:SERVER:DESENHO	:=oACD:FIELDGET("DESENHO")
          SELF:SERVER:DESCRI	:=oACD:FIELDGET("DESCRI")
          SELF:SERVER:CARAC        	:=oACD:FIELDGET("CARAC")
          SELF:SERVER:INSTRU	:=oACD:FIELDGET("INSTRU")
          SELF:SERVER:DESCII	:=oACD:FIELDGET("DESCII")
          SELF:SERVER:MIN     		:=oACD:FIELDGET("MIN")
          SELF:SERVER:MAX      	:=oACD:FIELDGET("MAX")
          SELF:SERVER:SEQ:=oACD:FIELDGET("SEQ")
          SELF:SERVER:SSQ:=oACD:FIELDGET("SSQ")
          SELF:SERVER:OPERACAO:=oACD:FIELDGET("OPERACAO")
          SELF:SERVER:REVD:=oACD:FIELDGET("REVD")
          SELF:SERVER:DATAR:=oACD:FIELDGET("DATAR")
     ENDIF
     oACD:CLOSE()
ENDIF

FOR w:=1 TO 30
    CVAL:="X"+StrZero(W,2)
	CMED:="R"+StrZero(W,2)
	SELF:SERVER:FIELDPUT(cVAL,aVAL[W][1])
	SELF:SERVER:FIELDPUT(cMED,aVAL[W][2])	
NEXT w	

SELF:CALCULAR()











END CLASS
