PARTIAL CLASS JACD
METHOD ALTERAR  
SELF:oSFJACDI:VIEWFORM()

METHOD Alterar1( ) 
	SELF:oSFJACDI:SERVER:VAL01:=CONVD(SELF:Server:CONV,SELF:mVAL01,9,4)
	SELF:oSFJACDI:SERVER:VAL02:=CONVD(SELF:Server:CONV,SELF:mVAL02,9,4)
	SELF:oSFJACDI:SERVER:VAL03:=CONVD(SELF:Server:CONV,SELF:mVAL03,9,4)
	SELF:oSFJACDI:SERVER:VAL04:=CONVD(SELF:Server:CONV,SELF:mVAL04,9,4)
	SELF:oSFJACDI:SERVER:VAL05:=CONVD(SELF:Server:CONV,SELF:mVAL05,9,4)
	SELF:oSFJACDI:SERVER:VALR:=CONVD(SELF:Server:CONV,SELF:mVALR,10,4)
	SELF:oSFJACDI:SERVER:MEDX:=CONVD(SELF:Server:CONV,SELF:mVALX,10,4)

METHOD ANTERIOR 
SELF:oSFJACDI:Browser:SuspendUpdate()
SELF:oSFJACDI:SkipPrevious()
IF SELF:oSFJACDI:Server:bof
	SELF:oSFJACDI:Skipnext()
ENDIF
SELF:oSFJACDI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nACD AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nACD:=SELF:Server:ACD
nACD++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT(#ACD,nACD)
SELF:SERVER:FIELDPUT(#DATA,Today())
SELF:SERVER:commit()
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
RETURN

METHOD btnPEGMA01 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:FIELDGET("CLIENTE"),ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:FIELDPUT("CLINOME",aCLI[2])
ENDIF

METHOD btnPEGMS01 
LOCAL aPRO AS ARRAY
aPRO:=PEGMS01(SELF:SERVER:DESENHO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:SERVER:FIELDPUT("DESCRI",aPRO[2])
ENDIF



METHOD btnPEGMS06 
LOCAL aPRO AS ARRAY	
aPRO:=PEGMS06(SELF:SERVER:DESENHO,SELF:SERVER:SEQ,SELF:SERVER:SSQ,zcurini,zcurdir)
IF aPRO[1]=.T.
   SELF:SERVER:OPERACAO:=aPRO[2]
ENDIF

METHOD buscanum( ) 
	SELF:KeyFind()

METHOD CALCULAR 
LOCAL nVAL,nVAL2 AS FLOAT
LOCAL aUSO AS ARRAY
LOCAL K AS WORD
IF ! MDG("Calcular Medias")
    RETU .F.
ENDIF	
SELF:oSFJACDI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJACDI:SERVER:GOTOP()
WHILE !  SELF:oSFJACDI:SERVER:EOF
	IF Empty(SELF:oSFJACDI:SERVER:VAL01)
       SELF:oSFJACDI:SERVER:resetnotification()		
	   alert("Valor 01 Em Branco Ordem:"+Str(SELF:oSFJACDI:SERVER:ORDEM))	
	   RETU
	ENDIF	
	IF Empty(SELF:oSFJACDI:SERVER:VAL02)
   	   SELF:oSFJACDI:SERVER:resetnotification()
	   alert("Valor 02 Em Branco Ordem:"+Str(SELF:oSFJACDI:SERVER:ORDEM))	
	   RETU
	ENDIF	
	IF Empty(SELF:oSFJACDI:SERVER:VAL03)
   	   SELF:oSFJACDI:SERVER:resetnotification()
	   alert("Valor 03 Em Branco Ordem:"+Str(SELF:oSFJACDI:SERVER:ORDEM))	
	   RETU
	ENDIF	
	IF Empty(SELF:oSFJACDI:SERVER:VAL04)
	   SELF:oSFJACDI:SERVER:resetnotification()
	   alert("Valor 04 Em Branco Ordem:"+Str(SELF:oSFJACDI:SERVER:ORDEM))	
	   RETU
	ENDIF	
	IF Empty(SELF:oSFJACDI:SERVER:VAL05)
   	   SELF:oSFJACDI:SERVER:resetnotification()
	   alert("Valor 05 Em Branco Ordem:"+Str(SELF:oSFJACDI:SERVER:ORDEM))	
	   RETU
	ENDIF	
    nVAL:=SELF:oSFJACDI:SERVER:VAL01
    nVAL+=SELF:oSFJACDI:SERVER:VAL02
    nVAL+=SELF:oSFJACDI:SERVER:VAL03
    nVAL+=SELF:oSFJACDI:SERVER:VAL04
    nVAL+=SELF:oSFJACDI:SERVER:VAL05
    nVAL2:=DIVIDIR(nVAL,5,10,4)
    SELF:oSFJACDI:SERVER:MEDX:=nVAL2
    aUSO:={SELF:oSFJACDI:SERVER:VAL01,SELF:oSFJACDI:SERVER:VAL02,SELF:oSFJACDI:SERVER:VAL03,SELF:oSFJACDI:SERVER:VAL04,SELF:oSFJACDI:SERVER:VAL05}
    nVAL2:=Abs(SELF:oSFJACDI:SERVER:VAL01-SELF:oSFJACDI:SERVER:VAL02)
    FOR  K:=2 TO 5
         nVAL:=Abs(aUSO[1]-aUSO[K])
         nVAL2:=IF(nVAL>nVAL2,nVAL,nVAL2)
    NEXT K
    FOR  K:=3 TO 5
         nVAL:=Abs(aUSO[2]-aUSO[K])
         nVAL2:=IF(nVAL>nVAL2,nVAL,nVAL2)
    NEXT K
    FOR  K:=4 TO 5
         nVAL:=Abs(aUSO[3]-aUSO[K])
         nVAL2:=IF(nVAL>nVAL2,nVAL,nVAL2)
    NEXT K
    FOR K:=5 TO 5
        nVAL:=Abs(aUSO[4]-aUSO[K])
        nVAL2:=IF(nVAL>nVAL2,nVAL,nVAL2)
    NEXT K
    SELF:oSFJACDI:SERVER:VALR:=nVAL2
    SELF:oSFJACDI:SERVER:SKIP()
ENDDO
SELF:oSFJACDI:SERVER:GOTOP()
SELF:oSFJACDI:SERVER:commit()
SELF:oSFJACDI:SERVER:resetnotification()
SELF:oSFJACDI:SERVER:notify(notifyappend) //Contas do Livro

METHOD Calcular1( ) 
IF ! MDG("Converte para 60/100")	
   RETU .F.
ENDIF
SELF:oSFJACDI:SERVER:GOTOP()
WHILE !  SELF:oSFJACDI:SERVER:EOF
    SELF:oSFJACDI:SERVER:FIELDPUT("VAL01",CONVD(SELF:Server:FIELDGET("VAL01"),9,4))
	SELF:oSFJACDI:SERVER:FIELDPUT("VAL02",CONVD(SELF:Server:FIELDGET("VAL02"),9,4))
	SELF:oSFJACDI:SERVER:FIELDPUT("VAL03",CONVD(SELF:Server:FIELDGET("VAL03"),9,4))
	SELF:oSFJACDI:SERVER:FIELDPUT("VAL04",CONVD(SELF:Server:FIELDGET("VAL04"),9,4))
	SELF:oSFJACDI:SERVER:FIELDPUT("VAL05",CONVD(SELF:Server:FIELDGET("VAL05"),9,4))
	SELF:oSFJACDI:SERVER:FIELDPUT("VALR",CONVD(SELF:Server:FIELDGET("VALR"),10,4))
	SELF:oSFJACDI:SERVER:FIELDPUT("MEDX",CONVD(SELF:Server:FIELDGET("MEDX"),10,4))
    SELF:oSFJACDI:SERVER:SKIP()
ENDDO
	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","ACD")	


METHOD DELETE() 
GRAVALOG(SELF:SERVER:ACD,"DEL","ACD")	
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
   SELF:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJACDI:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJACDI:SERVER:gotop()
   WHILE ! SELF:oSFJACDI:SERVER:eof
	 	SELF:oSFJACDI:SERVER:delete()
	 	SELF:oSFJACDI:SERVER:skip()	
      ENDDO
	SELF:oSFJACDI:SERVER:resetnotification()
	SELF:oSFJACDI:SERVER:notify(notifyfilechange)
	SELF:server:delete()
	SELF:server:unlock()
	SELF:SERVER:RESETNOTIFICATION()
	SELF:SERVER:Notify(notifyfilechange)
	IF ! SELF:SERVER:BOF
	   SELF:SERVER:Skip(-1)
	ENDIF	
ENDIF	



	


METHOD DELETEITENS() 
   SELF:oSFJACDI:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJACDI:SERVER:gotop()
   WHILE ! SELF:oSFJACDI:SERVER:eof
	 	SELF:oSFJACDI:SERVER:delete()
	 	SELF:oSFJACDI:SERVER:skip()	
      ENDDO
	SELF:oSFJACDI:SERVER:resetnotification()
	SELF:oSFJACDI:SERVER:notify(notifyfilechange)
SELF:oDCcontador:TextValue:=Str(0)

METHOD DUPLICAR() 
LOCAL nACD AS DWORD
LOCAL nFIELD,J,K AS WORD
LOCAL aITENS,aTMP,aDADOS,aDAD AS ARRAY
LOCAL oACDI AS USEREDE

nFIELD:=SELF:SERVER:FCOUNT
nACD:=SELF:Server:ACD
aDADOS:={}
FOR J:=1 TO nFIELD
    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
NEXT J
aITENS:={}
aDAD:={zCURINI,"ACDI.DBF",zCURDIR}
oACDI:=USEREDE{aDAD}
IF oACDI:nERRO=0
     nFIELD:=oACDI:FCOUNT
     oACDI:GOTOP()
     oACDI:SEEK(nACD)
     WHILE oACDI:FIELDGET("ACD")=nACD .AND. ! oACDI:EOF
          aTMP:={}
  	      FOR J:=1 TO nFIELD
	          AAdd(aTMP,oACDI:FIELDGET(J))
          NEXT J
          AAdd(aITENS,aTMP)
          oACDI:SKIP()
    ENDDO
ENDIF
SELF:server:setorder(1)
SELF:server:gobottom()
nACD:=SELF:Server:ACD
nACD++
SUPER:SERVER:APPEND()
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    SELF:SERVER:FIELDPUT(J,aDADOS[J])
NEXT J
SELF:SERVER:FIELDPUT("ACD",nACD)
IF oACDI:USED
     nFIELD:=oACDI:FCOUNT
     FOR K:=1 TO ALen(aITENS)
         oACDI:APPEND()
   	     FOR J:=1 TO nFIELD
             oACDI:FIELDPUT(J,aITENS[K][J])
         NEXT J
         oACDI:FIELDPUT("ACD",nACD)
         oACDI:FIELDPUT("AEP",0)
         oACDI:FIELDPUT("ACP",0)
     NEXT K
     oACDI:CLOSE()
ENDIF
SELF:server:gotop()
SELF:server:gobottom()
RETURN

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF	

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD EXCLUIR 
IF  MDG("Apagar Registro") .AND. SELF:oSFJACDI:server:LockCurrentRecord()
    SELF:oSFJACDI:server:delete()
    SELF:oSFJACDI:server:unlock()
    SELF:oSFJACDI:server:skipex(-1)
//    SELF:oSFJACDI:server:skip(-1)
//    IF SELF:oSFJACDI:server:BOF
//      SELF:oSFJACDI:server:GOTOP()
//    ENDIF
ENDIF	
SELF:ORDENAR()

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("DESENHO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()
	

METHOD LANC30() 
SELF:NOVOX(30,.T.)	

METHOD LANC33() 
SELF:NOVOX(33,.T.)	

METHOD ListBoxSelect( oControlEvent ) 
	LOCAL oControl AS Control
//	LOCAL uValue AS USUAL
	oControl := IIf( oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control )
	SUPER:ListBoxSelect( oControlEvent )
	DO CASE
      CASE oCONTROL:NAMESYM==#INSTRU
 			  SELF:SERVER:DESCII:=SELF:oDCINSTRU:textvalue	
   ENDCASE
	//Put your changes here
RETURN NIL

METHOD NOVO() 
SELF:NOVOX(1,.F.)

METHOD NOVOX(nELE,lZER) 
LOCAL nACD AS DWORD
LOCAL dDATA AS DATE
LOCAL nHORA AS FLOAT
LOCAL cVAR AS STRING
LOCAL X AS BYTE
dDATA:=CToD(SELF:oDCmDATA:TextValue)
cVAR:=SELF:oDCmHORA:TextValue
cVAR:=Left(cVAR,5)
cVAR:=StrTran(cVAR,":",".")
nHORA:=FloatFormat(Val(cVAR),5,2)
nACD:=SELF:SERVER:FIELDGET("ACD")
FOR X := 1 TO nELE
	SELF:oSFJACDI:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJACDI:SERVER:APPEND()
	SELF:oSFJACDI:SERVER:ACD:=nACD
	SELF:oSFJACDI:SERVER:HORA:=nHORA
	SELF:oSFJACDI:SERVER:DATA:=dDATA
	SELF:oSFJACDI:SERVER:VAL01:=CONVD(SELF:Server:CONV,SELF:mVAL01,9,4)
	SELF:oSFJACDI:SERVER:VAL02:=CONVD(SELF:Server:CONV,SELF:mVAL02,9,4)
	SELF:oSFJACDI:SERVER:VAL03:=CONVD(SELF:Server:CONV,SELF:mVAL03,9,4)
	SELF:oSFJACDI:SERVER:VAL04:=CONVD(SELF:Server:CONV,SELF:mVAL04,9,4)
	SELF:oSFJACDI:SERVER:VAL05:=CONVD(SELF:Server:CONV,SELF:mVAL05,9,4)
	SELF:oSFJACDI:SERVER:VALR:=CONVD(SELF:Server:CONV,SELF:mVALR,10,4)
	SELF:oSFJACDI:SERVER:MEDX:=CONVD(SELF:Server:CONV,SELF:mVALX,10,4)
	SELF:oSFJACDI:SERVER:commit()
	SELF:oSFJACDI:SERVER:resetnotification()
	SELF:oSFJACDI:SERVER:notify(notifyappend) //Contas do Livro
NEXT X
SELF:ORDENAR()
SELF:oDCmVAL01:SetFocus()


METHOD ORDENAR() 
LOCAL nCONTADOR AS WORD	
nCONTADOR:=0
SELF:oSFJACDI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJACDI:SERVER:GOTOP()
WHILE ! SELF:oSFJACDI:Server:EOF
	nCONTADOR:=nCONTADOR+1
	SELF:oSFJACDI:SERVER:FIELDPUT("ORDEM",nCONTADOR)
	SELF:oSFJACDI:SERVER:commit()
	SELF:oSFJACDI:SERVER:SKIP()
ENDDO	
SELF:oSFJACDI:SERVER:resetnotification()
SELF:oSFJACDI:SERVER:notify(notifyfilechange)
SELF:oDCcontador:TextValue:=Str(nCONTADOR)


METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJACDI:Browser:SuspendUpdate()
SELF:oSFJACDI:SkipNext()
IF SELF:oSFJACDI:Server:Eof
	SELF:oSFJACDI:SkipPrevious()
ENDIF
SELF:oSFJACDI:Browser:RestoreUpdate()

METHOD TABINS 
RETU MTD02("TIPINS",3)

METHOD TABULAR  
SELF:oSFJACDI:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJACDI:Server:COMMIT()



END CLASS
