PARTIAL CLASS JACP
METHOD APPEND() 
local nACP as dword
self:server:setorder(1)
self:server:gobottom()
nACP:=self:Server:ACP
nACP++
super:append()
self:SERVER:FIELDPUT(#ACP,nACP)
self:SERVER:FIELDPUT(#DATA,TODAY())
return

METHOD btnPEGMA01 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:FIELDGET("CLIENTE"),ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:FIELDPUT("CLINOME",aCLI[2])
ENDIF

METHOD btnPEGMS01 
LOCAL aPRO AS ARRAY
aPRO:=PEGMS01(SELF:SERVER:DESENHO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:SERVER:FIELDPUT("DESCRI",aPRO[2])
ENDIF

METHOD btnPEGMS06 
LOCAL aPRO AS ARRAY	
aPRO:=PEGMS06(SELF:SERVER:DESENHO,SELF:SERVER:SEQ,SELF:SERVER:SSQ,zcurini,zcurdir)
IF aPRO[1]=.T.
   SELF:SERVER:OPERACAO:=aPRO[2]
ENDIF

METHOD buscanum( ) 
	SELF:KeyFind()

METHOD CALCULAR() 
LOCAL nVAL1,nVAL2,nVAL3 AS FLOAT
LOCAL oACDI AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nACP AS DWORD


nVAL1 :=SELF:SERVER:X01
nVAL1+=SELF:SERVER:X02
nVAL1+=SELF:SERVER:X03
nVAL1+=SELF:SERVER:X04
nVAL1+=SELF:SERVER:X05
nVAL1+=SELF:SERVER:X06
nVAL1+=SELF:SERVER:X07
nVAL1+=SELF:SERVER:X08
nVAL1+=SELF:SERVER:X09
nVAL1+=SELF:SERVER:X10
nVAL2 :=SELF:SERVER:X11
nVAL2+=SELF:SERVER:X12
nVAL2+=SELF:SERVER:X13
nVAL2+=SELF:SERVER:X14
nVAL2+=SELF:SERVER:X15
nVAL2+=SELF:SERVER:X16
nVAL2+=SELF:SERVER:X17
nVAL2+=SELF:SERVER:X18
nVAL2+=SELF:SERVER:X19
nVAL2+=SELF:SERVER:X20
nVAL3 :=SELF:SERVER:X21
nVAL3+=SELF:SERVER:X22
nVAL3+=SELF:SERVER:X23
nVAL3+=SELF:SERVER:X24
nVAL3+=SELF:SERVER:X25
nVAL3+=SELF:SERVER:X26
nVAL3+=SELF:SERVER:X27
nVAL3+=SELF:SERVER:X28
nVAL3+=SELF:SERVER:X29
nVAL3+=SELF:SERVER:X30
SELF:SERVER:SUMX:=(nVAL1+nVAL2+nVAL3)

SELF:SERVER:MEDX:=DIVIDIR(SELF:SERVER:SUMX,30,10,4)


nVAL1 :=SELF:SERVER:R01
nVAL1+=SELF:SERVER:R02
nVAL1+=SELF:SERVER:R03
nVAL1+=SELF:SERVER:R04
nVAL1+=SELF:SERVER:R05
nVAL1+=SELF:SERVER:R06
nVAL1+=SELF:SERVER:R07
nVAL1+=SELF:SERVER:R08
nVAL1+=SELF:SERVER:R09
nVAL1+=SELF:SERVER:R10
nVAL2 :=SELF:SERVER:R11
nVAL2+=SELF:SERVER:R12
nVAL2+=SELF:SERVER:R13
nVAL2+=SELF:SERVER:R14
nVAL2+=SELF:SERVER:R15
nVAL2+=SELF:SERVER:R16
nVAL2+=SELF:SERVER:R17
nVAL2+=SELF:SERVER:R18
nVAL2+=SELF:SERVER:R19
nVAL2+=SELF:SERVER:R20
nVAL3 :=SELF:SERVER:R21
nVAL3+=SELF:SERVER:R22
nVAL3+=SELF:SERVER:R23
nVAL3+=SELF:SERVER:R24
nVAL3+=SELF:SERVER:R25
nVAL3+=SELF:SERVER:R26
nVAL3+=SELF:SERVER:R27
nVAL3+=SELF:SERVER:R28
nVAL3+=SELF:SERVER:R29
nVAL3+=SELF:SERVER:R30
SELF:SERVER:SUMR:=(nVAL1+nVAL2+nVAL3)
SELF:SERVER:MEDR:=DIVIDIR(SELF:SERVER:SUMR,30,8,4)
SELF:SERVER:SIGMA:=DIVIDIR(SELF:SERVER:MEDR,2.326,14,6)


nVAL1:=(SELF:SERVER:MAX)-(SELF:SERVER:MEDX)
IF nVAL1<0
   ALERT("Valor Maximo Menor que a Media")
   nVAL1:=0
ENDIF
nVAL2:=3*(SELF:SERVER:SIGMA)
nVAL3:=DIVIDIR(nVAL1,nVAL2,12,4)
IF nVAL3>9999999
   ALERT("PPKA Superior a 999999, Valor Zerado")
   SELF:SERVER:PPKA:=0
ELSE
  IF nVAL3<0
     ALERT("PPKA menor que 0, Valor Zerado")
     SELF:SERVER:PPKA:=0
  ELSE
     SELF:SERVER:PPKA:=nVAL3
  ENDIF
ENDIF

nVAL1:=(SELF:SERVER:MEDX)-(SELF:SERVER:MIN)
nVAL2:=3*(SELF:SERVER:SIGMA)
nVAL3:=DIVIDIR(nVAL1,nVAL2)
IF nVAL3>9999999
   ALERT("PPKB Superior a 999999, Valor Zerado")
   SELF:SERVER:PPKB:=0
ELSE
	 IF nVAL3<0
	      ALERT("PPKB Menor que 0 , Valor Zerado")
	      SELF:SERVER:PPKB:=0
	  ELSE
	       SELF:SERVER:PPKB:=FloatFormat(nVAL3,12,4)
	  ENDIF
ENDIF

nVAL1:=IF(SELF:SERVER:PPKA>SELF:SERVER:PPKB,SELF:SERVER:PPKB,SELF:SERVER:PPKA)
IF nVAL1>9999999
    alert("PPK Superior a 999999, Valor Zerado")
   SELF:SERVER:PPK:=0
ELSE
    IF nVAL1<0
          alert("PPK Menor que 0 , Valor Zerado")
         SELF:SERVER:PPK:=0
    ELSE
        SELF:SERVER:PPK:=FloatFormat(nVAL1,12,4)
    ENDIF	
ENDIF


nVAL1:=(SELF:SERVER:MAX)-(SELF:SERVER:MIN)
nVAL2:=6*(SELF:SERVER:SIGMA)
nVAL3:=DIVIDIR(nVAL1,nVAL2)
IF nVAL3>9999999
    alert("PP Superior a 999999, Valor Zerado")
   SELF:SERVER:PP:=0
ELSE
    IF nVAL3<0
        alert("PP Inferior a 0, Valor Zerado")
         SELF:SERVER:PP:=0
    ELSE
	    SELF:SERVER:PP:=FloatFormat(nVAL3,12,4)
    ENDIF
ENDIF


nVAL1:=(SELF:SERVER:MEDR)*.577
nVAL2:=(SELF:SERVER:MEDX)-nVAL1
SELF:SERVER:LIC:=TRUNCAR(nVAL2,3)


nVAL1:=(SELF:SERVER:MEDR)*.577
nVAL2:=(SELF:SERVER:MEDX)+nVAL1
SELF:SERVER:LSC:=TRUNCAR(nVAL2,3)


nACP:=SELF:SERVER:ACP
aDAD:={zCURINI,"ACDI.DBF",zCURDIR}
oACDI:=USEREDE{aDAD}
IF oACDI:nERRO=0
   oACDI:SETORDER(3) //ACP
   oACDI:SEEK(nACP)
   WHILE oACDI:FIELDGET("ACP")=nACP .AND. ! oACDI:EOF
         oACDI:FIELDPUT("LSC",SELF:SERVER:LSC)
         oACDI:FIELDPUT("LIC",SELF:SERVER:LIC)
         oACDI:SKIP()
   ENDDO
   oACDI:CLOSE()
ENDIF


SELF:CALMAXMIN("ACPX.DBF","ACPR.DBF")

METHOD Calcular1( ) 
LOCAL X AS WORD
LOCAL cCAMPO AS STRING
IF MDG("Converte os Lancamentos")
   RETU	
ENDIF	
FOR X:=1 TO 30	
	cCAMPO:="R"+StrZero(X,2,0)
	SELF:SERVER:FIELDUT(cCAMPO,CONVD(SELF:SERVER:FIELDGET(cCAMPO),9,4))
	cCAMPO:="X"+StrZero(X,2,0)
	SELF:SERVER:FIELDUT(cCAMPO,CONVD(SELF:SERVER:FIELDGET(cCAMPO),9,4))
NEXT X	

METHOD CALMAXMIN(cARQ1,cARQ2) 
LOCAL nVAL,nXMAX,nXMIN,nRMAX,nRMIN,nVAL1,nVAL2 AS FLOAT
LOCAL nLIC,nLSC,nMAX,nMIN
LOCAL nFE,nFX,nFR AS BYTE
LOCAL x AS BYTE
LOCAL aDAD AS ARRAY
LOCAL oACPX,oACPR AS USEREDE

nLIC:=SELF:SERVER:FIELDGET("LIC")
nLSC:=SELF:SERVER:FIELDGET("LSC")
nMAX:=SELF:SERVER:FIELDGET("MAX")
nMIN:=SELF:SERVER:FIELDGET("MIN")

aDAD:={ZCURINI,cARQ1,ZCURDIR}
oACPX:=USEREDE{aDAD}
IF oACPX:nERRO=0
   oACPX:SETORDER(2)
   oACPX:GOTOP()
   oACPX:SEEK(SELF:SERVER:acp)
   WHILE oACPX:FIELDGET("ACP")=SELF:SERVER:aCP  .AND. ! oACPX:EoF
   	   oACPX:DELETE()
   	   oACPX:SKIP()
  ENDDO
  oACPX:SETORDER(1)
ENDIF	

aDAD:={ZCURINI,cARQ2,ZCURDIR}
oACPR:=USEREDE{aDAD}
IF oACPR:nERRO=0
   oACPR:SETORDER(2)
   oACPR:GOTOP()
   oACPR:SEEK(SELF:SERVER:acp)
   WHILE oACPR:FIELDGET("ACP")=SELF:SERVER:aCP  .AND. ! oACPR:EoF
   	   oACPR:DELETE()
   	   oACPR:SKIP()
  ENDDO
  oACPR:SETORDER(1)
ENDIF	

nVAL1:=SELF:SERVER:MEDR*2.114
SELF:SERVER:RLSC:=FloatFormat(nVAL1,10,4)

nXMAX:=0
nXMIN:=0
nRMAX:=0
nRMIN:=0
nVAL1:=0
nFE:=0
nFX:=0
nFR:=0
FOR X:=1 TO 30
	 nVAL:=SELF:SERVER:FIELDGET("X"+StrZero(X,2))
	 oACPX:GOTOP()
	 IF ! oACPX:SEEK(Str(ACP,8)+Str(nVAL,10,4))
	 	oACPX:APPEND()
	 	oACPX:FIELDPUT("ACP",SELF:SERVER:ACP)
	 	oACPX:FIELDPUT("VALOR",nVAL)	
	 	oACPX:FIELDPUT("QTDE",1)	
    	oACPX:FIELDPUT("TOTAL",nVAL)
	 ELSE
	 	oACPX:FIELDPUT("QTDE",oACPX:FIELDGET("QTDE")+1)	
	 	oACPX:FIELDPUT("TOTAL",oACPX:FIELDGET("QTDE")*nVAL)	
     ENDIF	
 	 nVAL2:=(nVAL-SELF:SERVER:medx)^2
 	 nVAL1+=nVAL2
     IF nVAL>nXMAX .OR. nXMAX=0
	 	 nXMAX:=nVAL
	 ENDIF	
	 IF nVAL<nXMIN .OR. nXMIN=0
	 	 nXMIN:=nVAL
	 ENDIF			
	 IF nVAL>nMAX
	 	nFE+=1
	 ENDIF	
	 IF nVAL<nMIN
	 	nFE+=1
	 ENDIF	
	 IF nVAL>nLSC
	 	nFX+=1
	 ENDIF	
	 IF INT(nVAL*1000)<INT(nLIC*1000) //corrige Float erro decimais numeros iguais
	 	nFX+=1
	 ENDIF		
	 nVAL:=SELF:SERVER:FIELDGET("R"+StrZero(X,2))
	 oACPR:GOTOP()
	 IF ! oACPR:SEEK(Str(ACP,8)+Str(nVAL,10,4))
	 	oACPR:APPEND()
	 	oACPR:FIELDPUT("ACP",SELF:SERVER:ACP)
	 	oACPR:FIELDPUT("VALOR",nVAL)	
	 	oACPR:FIELDPUT("QTDE",1)	
    	oACPR:FIELDPUT("TOTAL",nVAL)
	 ELSE
	 	oACPR:FIELDPUT("QTDE",oACPR:FIELDGET("QTDE")+1)	
	 	oACPR:FIELDPUT("TOTAL",oACPR:FIELDGET("QTDE")*nVAL)	
     ENDIF
	 IF nVAL>nRMAX .OR. nRMAX=0
	 	 nRMAX:=nVAL
	 ENDIF	
	 IF nVAL<nRMIN .OR. nRMIN=0
	 	 nRMIN:=nVAL
	 ENDIF
	 IF nVAL>SELF:SERVER:FIELDGET("rLSC")
	 	nFR+=1
	 ENDIF
NEXT X	
nVAL2:=FloatFormat(nVAL1/29,10,4)
nVAL1:=SQRT(nVAL2)
SELF:SERVER:RMIN   :=nRMIN
SELF:SERVER:RMAX   :=nRMAX
SELF:SERVER:XMAX   :=nXMAX
SELF:SERVER:XMIN   :=nxMIN
SELF:SERVER:desv   :=nVAL1
SELF:SERVER:FORAE:= nFE
SELF:SERVER:FORAX:= nFX
SELF:SERVER:FORAR:= nFR


nXMAX:=0
nRMAX:=0
nFX:=0
nFR:=0

IF oACPX:nERRO=0 .AND. oACPR:nERRO=0
   oACPX:SETORDER(2)
   oACPX:GOTOp()
   oACPX:SEEK(SELF:SERVER:acp)
   WHILE oACPX:FIELDGET("ACP")=SELF:SERVER:aCP  .AND. ! oACPX:EoF
   	   IF oACPX:FIELDGET("QTDE")>nFX
   	   	  nFX:=oACPX:FIELDGET("QTDE")
   	   	  nXMAX:=oACPX:FIELDGET("VALOR")
  	   ENDIF
   	   oACPX:SKIP()
   ENDDO	
   oACPX:CLOSE()

   oACPR:SETORDER(2)
   oACPR:GOTOp()
   oACPR:SEEK(SELF:SERVER:acp)
   WHILE oACPR:FIELDGET("ACP")=SELF:SERVER:aCP  .AND. ! oACPR:EoF
   	   IF oACPR:FIELDGET("QTDE")>nFR
   	   	  nFR:=oACPR:FIELDGET("QTDE")
   	   	  nRMAX:=oACPR:FIELDGET("VALOR")
  	   ENDIF
   	   oACPR:SKIP()
   ENDDO	
   oACPX:CLOSE()
   oACPR:CLOSE()
ENDIF	
	
SELF:SERVER:MODAX:=nXMAX
SELF:SERVER:MODAR:=nRMAX


METHOD cmdAnual( ) 
SELF:server:FIELDPUT("DISTNOR",SIMNAO(SELF:SERVER:FIELDGET("DISTNOR"),{"S","N"," "}))		

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","ACP")	


METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF	

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD escres1( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("ELANUM",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("ELANOM",oESCMP04:NOME)
ENDIF

METHOD escres2( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("RESNUM",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("RESNOM",oESCMP04:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("DESENHO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()

METHOD ListBoxSelect( oControlEvent ) 
	LOCAL oControl AS Control
//	LOCAL uValue AS USUAL
	oControl := IIf( oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control )
	SUPER:ListBoxSelect( oControlEvent )
	DO CASE
	       CASE oCONTROL:NAMESYM==#INSTRU
			 SELF:SERVER:DESCII:=SELF:oDCINSTRU:textvalue	
	 ENDCASE
	//Put your changes here
RETURN NIL


METHOD PEGACD 
LOCAL oACDI,oACD AS USEREDE
LOCAL nACP,nACD AS DWORD
LOCAL W AS BYTE
LOCAL aDAD,aVAL AS ARRAY
LOCAL cMED,cVAL AS STRING

IF ! MDG("Importar Medias")
   RETURN
ENDIF

aVAL:={}
FOR W:=1 TO 30
      AAdd(aVAL,{0,0})
NEXT W
W       :=1
nACD:=SELF:ACD
nACP:=SELF:SERVER:ACP
aDAD:={zCURINI,"ACDI.DBF",zCURDIR}
oACDI:=USEREDE{aDAD}
IF oACDI:nERRO=0
     oACDI:SETORDER(2)
     oACDI:GOTOP()
     oACDI:SEEK(Str(nACD,8))
     WHILE oACDI:FIELDGET("ACD")=nACD .AND. W<31 .AND. ! oACDI:EOF
         oACDI:FIELDPUT("ACP",nACP)
         oACDI:FIELDPUT("ORDEM",W)
         aVAL[W][1]:=oACDI:FIELDGET("MEDX")
         aVAL[W][2]:=oACDI:FIELDGET("VALR")
           W++
           oACDI:SKIP()
     ENDDO
     oACDI:CLOSE()
ENDIF

aDAD:={zCURINI,"ACD.DBF",zCURDIR}
oACD:=USEREDE{aDAD}
IF oACD:nERRO=0
    oACD:GOTOP()
    oACD:SEEK(nACD)
    IF oACD:FOUND
       SELF:SERVER:CLIENTE   :=oACD:FIELDGET("CLIENTE")
       SELF:SERVER:CLINOME   :=oACD:FIELDGET("CLINOME")
       SELF:SERVER:DESENHO	:=oACD:FIELDGET("DESENHO")
       SELF:SERVER:DESCRI	:=oACD:FIELDGET("DESCRI")
       SELF:SERVER:CARAC     :=oACD:FIELDGET("CARAC")
       SELF:SERVER:INSTRU	:=oACD:FIELDGET("INSTRU")
       SELF:SERVER:DESCII	:=oACD:FIELDGET("DESCII")
       SELF:SERVER:MIN     	:=oACD:FIELDGET("MIN")
       SELF:SERVER:MAX      	:=oACD:FIELDGET("MAX")
       SELF:SERVER:SEQ:=oACD:FIELDGET("SEQ")
       SELF:SERVER:SSQ:=oACD:FIELDGET("SSQ")
       SELF:SERVER:OPERACAO:=oACD:FIELDGET("OPERACAO")
       SELF:SERVER:REVD:=oACD:FIELDGET("REVD")
       SELF:SERVER:DATAR:=oACD:FIELDGET("DATAR")
     ENDIF
     oACD:CLOSE()
ENDIF

FOR w:=1 TO 30
    CVAL:="X"+StrZero(W,2)
	CMED:="R"+StrZero(W,2)
	SELF:SERVER:FIELDPUT(cVAL,aVAL[W][1])
	SELF:SERVER:FIELDPUT(cMED,aVAL[W][2])	
NEXT w	



SELF:CALCULAR()



METHOD PEGACD02 
LOCAL oACDI,oACD AS USEREDE
LOCAL nACP,nACD AS DWORD
LOCAL nVAL,nVAL2 AS FLOAT
LOCAL W AS BYTE
LOCAL aVAL,aDAD AS ARRAY
LOCAL cMED,cVAL AS STRING

IF ! MDG("Importar Lançamentos")
   RETURN
ENDIF
IF ! MDG("Isto recalcular as medias- Continuar")
	RETURN
ENDIF

aVAL:={}
FOR W:=1 TO 30
      AAdd(aVAL,{0,0})
NEXT W
W       :=1
nACD:=SELF:ACD
nACP:=SELF:SERVER:ACP
aDAD:={zCURINI,"ACDI.DBF",zCURDIR}
oACDI:=USEREDE{aDAD}
IF oACDI:nERRO=0
     oACDI:SETORDER(2)
     oACDI:GOTOP()
     oACDI:SEEK(Str(nACD,8))
     WHILE oACDI:FIELDGET("ACD")=nACD .AND. W<31 .AND. ! oACDI:EOF
         nVAL:=oACDI:FIELDGET("VAL01")
         nVAL+=oACDI:FIELDGET("VAL02")
         nVAL+=oACDI:FIELDGET("VAL03")
         nVAL+=oACDI:FIELDGET("VAL04")
         nVAL+=oACDI:FIELDGET("VAL05")
         nVAL2:=nVAL/5
         oACDI:FIELDPUT("MEDX",nVAL2)
         nVAL :=oACDI:FIELDGET("VAL01")
          IF oACDI:FIELDGET("VAL02")<nVAL
              nVAL :=oACDI:FIELDGET("VAL02")
          ENDIF
          IF oACDI:FIELDGET("VAL03")<nVAL
              nVAL :=oACDI:FIELDGET("VAL03")
          ENDIF
          IF oACDI:FIELDGET("VAL04")<nVAL
              nVAL :=oACDI:FIELDGET("VAL04")
          ENDIF
          IF oACDI:FIELDGET("VAL05")<nVAL
              nVAL :=oACDI:FIELDGET("VAL05")
          ENDIF
         nVAL2 :=oACDI:FIELDGET("VAL01")
          IF oACDI:FIELDGET("VAL02")>nVAL2
              nVAL2 :=oACDI:FIELDGET("VAL02")
          ENDIF
          IF oACDI:FIELDGET("VAL03")>nVAL2
              nVAL2 :=oACDI:FIELDGET("VAL03")
          ENDIF
          IF oACDI:FIELDGET("VAL04")>nVAL2
              nVAL2 :=oACDI:FIELDGET("VAL04")
          ENDIF
          IF oACDI:FIELDGET("VAL05")>nVAL2
              nVAL2 :=oACDI:FIELDGET("VAL05")
          ENDIF


         oACDI:FIELDPUT("VALR",FloatFormat(nVAL2-nVAL,2,2))

         oACDI:FIELDPUT("ACP",nACP)
         oACDI:FIELDPUT("ORDEM",W)
         aVAL[W][1]:=oACDI:FIELDGET("MEDX")
         aVAL[W][2]:=oACDI:FIELDGET("VALR")
           W++
           oACDI:SKIP()
     ENDDO
     oACDI:CLOSE()
ENDIF


aDAD:={zCURINI,"ACD.DBF",zCURDIR}
oACD:=USEREDE{aDAD}
IF oACD:nERRO=0
   oACD:GOTOP()
   oACD:SEEK(nACD)
   IF oACD:FOUND
          SELF:SERVER:CLIENTE     :=oACD:FIELDGET("CLIENTE")
          SELF:SERVER:CLINOME    :=oACD:FIELDGET("CLINOME")
          SELF:SERVER:DESENHO	:=oACD:FIELDGET("DESENHO")
          SELF:SERVER:DESCRI	:=oACD:FIELDGET("DESCRI")
          SELF:SERVER:CARAC        	:=oACD:FIELDGET("CARAC")
          SELF:SERVER:INSTRU	:=oACD:FIELDGET("INSTRU")
          SELF:SERVER:DESCII	:=oACD:FIELDGET("DESCII")
          SELF:SERVER:MIN     		:=oACD:FIELDGET("MIN")
          SELF:SERVER:MAX      	:=oACD:FIELDGET("MAX")
	      SELF:SERVER:SEQ:=oACD:FIELDGET("SEQ")
          SELF:SERVER:SSQ:=oACD:FIELDGET("SSQ")
          SELF:SERVER:OPERACAO:=oACD:FIELDGET("OPERACAO")
          SELF:SERVER:REVD:=oACD:FIELDGET("REVD")
          SELF:SERVER:DATAR:=oACD:FIELDGET("DATAR")
     ENDIF
     oACD:CLOSE()
ENDIF

FOR w:=1 TO 30
    CVAL:="X"+StrZero(W,2)
	CMED:="R"+StrZero(W,2)
	SELF:SERVER:FIELDPUT(cVAL,aVAL[W][1])
	SELF:SERVER:FIELDPUT(cMED,aVAL[W][2])	
NEXT w	



SELF:CALCULAR()








METHOD PEGela( ) 
LOCAL aTEC,aCOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:SERVER:FIELDGET("elanum"),ZCURINI,ZCURDIR,acom)
IF aTEC[1]=.T.
   SELF:SERVER:FIELDPUT("elanom",aTEC[2])	
ENDIF		

METHOD PEGres( ) 
LOCAL aTEC,aCOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:SERVER:FIELDGET("resnum"),ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:SERVER:FIELDPUT("resnom",aTEC[2])	
ENDIF		


METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   FabCenterWindow( SELF )
 RETURN SELF

METHOD TABINS 
RETU MTD02("TIPINS",3)

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
