FUNC CONVD(lCONV,nVALOR,nCAS,nDEC)
LOCAL nRETU,nVAL1,nVAL2 AS FLOAT
IF ValType(nCAS)#"N"
   nDEC:=18
ENDIF	
IF ValType(nDEC)#"N"
   nDEC:=2	
ENDIF	
nRETU:=nVALOR
IF lCONV
	nVAL1:=INT(nVALOR)
	nVAL2:=nVALOR-nVAL1
	nRETU:=FloatFormat(nVAL1+(nVAL2*100/60),nCAS,nDEC)
ENDIF	
RETU nRETU




