PARTIAL CLASS JGC
METHOD APPEND() 
LOCAL nGC AS DWORD
SELF:server:clearfilter()
SELF:server:setorder(1)
SELF:server:gobottom()
nGC:=SELF:Server:GC
nGC++
SUPER:append()
SELF:SERVER:FIELDPUT(#GC,nGC)
RETURN

METHOD btnpegma01 
LOCAL aCLI
aCLI:=PEGMA01(SELF:SERVER:CLIENTE,zcurini,zcurdir)
IF aCLI[1]=.T.
   SELF:SERVER:CLINOME:=aCLI[2]
ENDIF
	
	

METHOD btnpegms01 
LOCAL APRO AS ARRAY
aPRO:=PEGMS01(SELF:SERVER:CODIGO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:SERVER:NOME:=aPRO[2]
ENDIF

METHOD btnpegms06 
LOCAL aPRO AS ARRAY	
aPRO:=PEGMS06(SELF:SERVER:CODIGO,SELF:SERVER:SEQ,SELF:SERVER:SSQ,zcurini,zcurdir)
IF aPRO[1]=.T.
   SELF:SERVER:CARACO:=aPRO[2]
ENDIF

METHOD buscaNUM( ) 
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Localizar GC","Digite Nº GC"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","GC")	


METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("NOME",oESC:NOME)
ENDIF		

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()
	

METHOD Impacp( ) 
		SELF:importar("ACP.DBF")

METHOD Impaep( ) 
	SELF:importar("AC2.DBF")

METHOD IMPORTAR(cARQ)	
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nNUMERO AS DWORD
IF cARQ="ACP.DBF"
   nNUMERO:=SELF:SERVER:FIELDGET("ACP")
ELSE
   nNUMERO:=SELF:SERVER:FIELDGET("AEP")
ENDIF	
aDAD:={zCURINI,cARQ,zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOTOP()
IF oSERVER:SEEK(nNUMERO)
   SELF:SERVER:FIELDPUT("CLIENTE",oSERVER:FIELDGET("CLIENTE"))
   SELF:SERVER:FIELDPUT("CLINOME",oSERVER:FIELDGET("CLINOME"))
   SELF:SERVER:FIELDPUT("CODIGO",oSERVER:FIELDGET("DESENHO"))
   SELF:SERVER:FIELDPUT("NOME",oSERVER:FIELDGET("DESCRI"))
   SELF:SERVER:FIELDPUT("SEQ",oSERVER:FIELDGET("SEQ"))
   SELF:SERVER:FIELDPUT("SSQ",oSERVER:FIELDGET("SSQ"))
   SELF:SERVER:FIELDPUT("CARAC",oSERVER:FIELDGET("OPERACAO"))
   SELF:SERVER:FIELDPUT("ESPEC",oSERVER:FIELDGET("CARAC"))
   SELF:SERVER:FIELDPUT("CODME04",oSERVER:FIELDGET("INSTRU"))
   SELF:SERVER:FIELDPUT("NOMME04",oSERVER:FIELDGET("DESCII"))
   SELF:SERVER:FIELDPUT("LIC",oSERVER:FIELDGET("LIC"))
   SELF:SERVER:FIELDPUT("LSC",oSERVER:FIELDGET("LSC"))
   SELF:SERVER:FIELDPUT("LSCR",oSERVER:FIELDGET("RLSC"))
   SELF:SERVER:FIELDPUT("LIE",oSERVER:FIELDGET("MIN"))
   SELF:SERVER:FIELDPUT("LSE",oSERVER:FIELDGET("MAX"))
//   SELF:SERVER:FIELDPUT("",oSERVER:FIELDGET(""))
ENDIF


oSERVER:CLOSE()

METHOD ListBoxSelect( oControlEvent ) 
	LOCAL oControl AS Control
//	LOCAL uValue AS USUAL
	oControl := IIf( oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control )
	SUPER:ListBoxSelect( oControlEvent )
	//Put your changes here
	DO CASE
      CASE oCONTROL:NAMESYM==#CODME04
 			 SELF:SERVER:NOMME04:=SELF:oDCCODME04:textvalue
      CASE oCONTROL:NAMESYM==#CODME01
 			 SELF:SERVER:NOMME01:=SELF:oDCCODME01:textvalue	
	ENDCASE
RETURN NIL

METHOD PEGMP01() 
RETU PEGCOMBO("MP01.DBF","NOME","CODIGO")

METHOD PORNUM() 
	SELF:server:SETORDER(1)

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
FabCenterWindow( SELF )
 RETURN SELF

METHOD TABINS 
RETU MTD02("TIPINS",3)

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
