PARTIAL CLASS JOPAE
METHOD APPEND() 
LOCAL nOPAE AS DWORD
LOCAL oESC AS XESCCOD	
LOCAL cCODIGO AS STRING
LOCAL oPAEI AS USEREDE
LOCAL aDAD AS ARRAY
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF ! oESC:LOK
   RETURN	
ENDIF	
//
SELF:SERVER:SUSPENDNOTIFICATION()
cCODIGO:=AllTrim(oESC:CODIGO)
SELF:server:setorder(1)
SELF:server:gobottom()
nOPAE:=SELF:Server:FIELDGET("OPAE")
nOPAE++
SUPER:append()
SELF:SERVER:FIELDPUT("OPAE",nOPAE)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("CODIGO",cCODIGO)
SELF:server:resetnotification()
SELF:server:notify(notifyappend)
//
aDAD:={zCURINI,"PAEI.DBF",zCURDIR}
oPAEI:=USEREDE{aDAD}
IF oPAEI:nERRO#0
   RETU
ENDIF
SELF:oSFJOPAI:SERVER:SUSPENDNOTIFICATION()
oPAEI:GOTOP()
oPAEi:SEEK(cCODIGO)
WHILE ! oPAEI:EOF
 	IF oPAEI:FIELDGET("DESENHO")=cCODIGO
    	SELF:oSFJOPAI:SERVER:APPEND()	
    	SELF:oSFJOPAI:SERVER:FIELDPUT("OPAE",nOPAE)
        SELF:oSFJOPAI:SERVER:FIELDPUT("ESPEC",oPAEI:FIELDGET("ESPEC"))
	    SELF:oSFJOPAI:SERVER:commit()
	 ENDIF
	oPAEI:SKIP()
ENDDO
oPAEI:CLOSE()
SELF:oSFJOPAI:SERVER:resetnotification()
SELF:oSFJOPAI:SERVER:notify(notifyfilechange)	
SELF:oSFJOPAI:SERVER:GOTOP()
//SELF:oSFJOPAI:Browser:REFRESH()
RETURN

METHOD buscanum( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","PAE")	


METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
    SELF:oSFJOPAI:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJOPAI:SERVER:gotop()
    WHILE ! SELF:oSFJOPAI:SERVER:eof
	 	SELF:oSFJOPAI:SERVER:delete()
	 	SELF:oSFJOPAI:SERVER:skip()	
      ENDDO
	SELF:oSFJOPAI:SERVER:resetnotification()
	SELF:oSFJOPAI:SERVER:notify(notifyfilechange)	
	SELF:server:skipex(-1)
ENDIF	

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
ENDIF

METHOD ESCRES( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("CODMP04",oESCMP04:NUMERO)
//   SELF:SERVER:FIELDPUT("INSNOM",oESCMP04:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()
	

METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
PARTIAL CLASS XJPAI
METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","PAE")	


END CLASS
