PARTIAL CLASS JPAC
METHOD APPEND() 
LOCAL nPAC AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nPAC:=SELF:Server:PAC
nPAC++
SUPER:append()
SELF:SERVER:FIELDPUT(#PAC,nPAC)
SELF:SERVER:FIELDPUT(#DATA,Today())
RETURN

METHOD btnPEGMA01 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:FIELDGET("CLIENTE"),ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:FIELDPUT("CLINOME",aCLI[2])
ENDIF

METHOD btnPEGMS01 
LOCAL aPRO AS ARRAY
aPRO:=PEGMS01(SELF:SERVER:CODIGO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:SERVER:FIELDPUT("NOME",aPRO[2])
ENDIF

METHOD btnPEGMS06
LOCAL ASEQ AS ARRAY	
aSEQ:=PEGMS06(SELF:SERVER:CODIGO,SELF:SERVER:SEQ,SELF:SERVER:SSQ,ZCURINI,ZCURDIR)
IF aSEQ[1]=.T.
   SELF:SERVER:DESSEQ:=aSEQ[2]
ENDIF

METHOD buscanum( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","OUT")	


METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("NOME",oESC:NOME)
ENDIF		

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()
	

METHOD IMPACP( ) 
LOCAL oACP AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"ACP.DBF",zCURDIR}
oACP:=USEREDE{aDAD}
IF oACP:nERRO=0
   IF oACP:SEEK(SELF:sERVER:ACP)
      SELF:SERVER:DATA   :=oACP:FIELDGET("DATA")
      SELF:SERVER:CLIENTE:=oACP:FIELDGET("CLIENTE")
      SELF:SERVER:CLINOME:=oACP:FIELDGET("CLINOME")
      SELF:SERVER:CODIGO :=oACP:FIELDGET("DESENHO")
      SELF:SERVER:NOME   :=oACP:FIELDGET("DESCRI")
      SELF:SERVER:INSTRU :=oACP:FIELDGET("INSTRU")
      SELF:SERVER:DESCII :=oACP:FIELDGET("DESCII")
      SELF:SERVER:CARAC  :=oACP:FIELDGET("CARAC")
      SELF:SERVER:MEDX   :=oACP:FIELDGET("MEDX")
      SELF:SERVER:MEDR   :=oACP:FIELDGET("MEDR")
      SELF:SERVER:PP     :=oACP:FIELDGET("PP")
      SELF:SERVER:PPK    :=oACP:FIELDGET("PPK")
      SELF:SERVER:RMIN   :=oACP:FIELDGET("RMIN")
      SELF:SERVER:RMAX   :=oACP:FIELDGET("RMAX")
      SELF:SERVER:XMAX   :=oACP:FIELDGET("XMAX")
      SELF:SERVER:XMIN   :=oACP:FIELDGET("XMIN")
  ENDIF
  oACP:CLOSE()
ENDIF


METHOD IMPACP2( ) 
LOCAL oACP AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"ACP.DBF",zCURDIR}
oACP:=USEREDE{aDAD}
IF oACP:nERRO=0
IF oACP:SEEK(SELF:sERVER:nACP)
   SELF:SERVER:NXMED   :=oACP:FIELDGET("MEDX")
   SELF:SERVER:NRMED   :=oACP:FIELDGET("MEDR")
   SELF:SERVER:NPP     :=oACP:FIELDGET("PP")
   SELF:SERVER:NPPK    :=oACP:FIELDGET("PPK")
   SELF:SERVER:NRMIN   :=oACP:FIELDGET("RMIN")
   SELF:SERVER:NRMAX   :=oACP:FIELDGET("RMAX")
   SELF:SERVER:NXMAX   :=oACP:FIELDGET("XMAX")
   SELF:SERVER:NXMIN   :=oACP:FIELDGET("xMIN")
ENDIF
oACP:CLOSE()
ENDIF

METHOD IMPAEP( ) 	
LOCAL aDAD AS ARRAY	
LOCAL oAEP AS USEREDE
aDAD:={zCURINI,"AC2.DBF",zCURDIR}
oAEP:=USEREDE{aDAD}
IF oAEP:nERRO#0
	RETU
ENDIF	
IF oAEP:SEEK(SELF:SERVER:AEP)
   SELF:SERVER:DATA   :=oAEP:FIELDGET("DATA")
   SELF:SERVER:CLIENTE:=oAEP:FIELDGET("CLIENTE")
   SELF:SERVER:CLINOME:=oAEP:FIELDGET("CLINOME")
   SELF:SERVER:CODIGO :=oAEP:FIELDGET("DESENHO")
   SELF:SERVER:NOME   :=oAEP:FIELDGET("DESCRI")
   SELF:SERVER:INSTRU :=oAEP:FIELDGET("INSTRU")
   SELF:SERVER:DESCII :=oAEP:FIELDGET("DESCII")
   SELF:SERVER:CARAC  :=oAEP:FIELDGET("CARAC")
   SELF:SERVER:MEDX   :=oAEP:FIELDGET("MEDX")
   SELF:SERVER:MEDR   :=oAEP:FIELDGET("MEDR")
   SELF:SERVER:PP     :=oAEP:FIELDGET("PP")
   SELF:SERVER:PPK    :=oAEP:FIELDGET("PPK")
   SELF:SERVER:RMIN   :=oAEP:FIELDGET("RMIN")
   SELF:SERVER:RMAX   :=oAEP:FIELDGET("RMAX")
   SELF:SERVER:XMAX   :=oAEP:FIELDGET("XMAX")
   SELF:SERVER:XMIN   :=oAEP:FIELDGET("xMIN")
ENDIF
oAEP:CLOSE()

METHOD IMPAEP2( ) 
LOCAL oAEP AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"AC2.DBF",zCURDIR}
oAEP:=USEREDE{aDAD}
IF oAEP:nERRO#0
	RETU
ENDIF	
IF oAEP:SEEK(SELF:SERVER:nAEP)
   SELF:SERVER:NXMED   :=oAEP:FIELDGET("MEDX")
   SELF:SERVER:NRMED   :=oAEP:FIELDGET("MEDR")
   SELF:SERVER:NPP     :=oAEP:FIELDGET("PP")
   SELF:SERVER:NPPK    :=oAEP:FIELDGET("PPK")
   SELF:SERVER:NRMIN   :=oAEP:FIELDGET("RMIN")
   SELF:SERVER:NRMAX   :=oAEP:FIELDGET("RMAX")
   SELF:SERVER:NXMAX   :=oAEP:FIELDGET("XMAX")
   SELF:SERVER:NXMIN   :=oAEP:FIELDGET("xMIN")
ENDIF
oAEP:CLOSE()


	
	
	

METHOD ListBoxSelect( oControlEvent ) 
	LOCAL oControl AS Control
//	LOCAL uValue AS USUAL
	LOCAL aSET AS ARRAY
	oControl := IIf( oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control )
	SUPER:ListBoxSelect( oControlEvent )
	//Put your changes here
	DO CASE
   	       CASE oCONTROL:NAMESYM==#SETCOD
                             aSET:=PEGMD02(SELF:SERVER:SETCOD,"CRRS02",3)
                             IF aSET[1]=.T.
                                  SELF:SERVER:SETOR:=aSET[2]
                              ENDIF
	       CASE oCONTROL:NAMESYM==#INSTRU
			 SELF:SERVER:DESCII:=SELF:oDCINSTRU:textvalue	
	ENDCASE
RETURN NIL


METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
FabCenterWindow( SELF )
 RETURN SELF

METHOD TABINS 
RETU MTD02("TIPINS",3)

METHOD TABSET 
RETU MTD02("CRRS02",1)

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
