PARTIAL CLASS JRI
METHOD ALTERAR  
self:oSFJRII:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJRII:Browser:SuspendUpdate()
SELF:oSFJRII:SkipPREVIOUS()
IF SELF:oSFJRII:Server:BOF
	SELF:oSFJRII:SkipNEXT()
ENDIF
SELF:oSFJRII:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nRI AS DWORD
LOCAL x AS BYTE
SELF:SERVER:SUSPENDNOTIFICATION()
SELF:server:setorder(1)
SELF:server:gobottom()
nRI:=SELF:Server:RI
nRI++
SUPER:append()
SELF:SERVER:FIELDPUT(#RI,nRI)
SELF:server:FIELDPUT(#data,Today())
SELF:SERVER:FIELDGET("LAUDOF","")
SELF:SERVER:FIELDGET("ORIGEM","A")
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
SELF:oSFJRII:SERVER:SUSPENDNOTIFICATION()
FOR x:=1 TO 25
     SELF:oSFJRII:SERVER:APPEND()
     SELF:oSFJRII:SERVER:RI:=nRI
     SELF:oSFJRII:SERVER:ITEM:=x
NEXT x
SELF:oSFJRII:SERVER:resetnotification()
SELF:oSFJRII:SERVER:notify(notifyfilechange)
SELF:oSFJRII:SERVER:gotop()
RETURN

METHOD btnPEGMA01 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:FIELDGET("CLIENTE"),ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:FIELDPUT("CLINOME",aCLI[2])
ENDIF

METHOD btnPEGMS01 
LOCAL aPRO AS ARRAY
aPRO:=PEGMS01(SELF:SERVER:DESENHO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:SERVER:FIELDPUT("DESCRI",aPRO[2])
ENDIF

METHOD buscanum( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD cmdescmp2( ) 
	LOCAL oESC AS XESCNUM
oESC:=XESCNUM{SELF,"FLUXO.DBF"}
oESC:SHOW()
IF oESC:LOK
//     SELF:oSFJSEQ:SERVER:FIELDPUT("FLUXO",oESC:NUMERO)
   	SELF:oSFJRII:SERVER:FIELDPUT("TIPINSP",CHR(oESC:NUMERO))
ENDIF

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","RI")	


METHOD cmdlaudo( ) 
IF Empty(SELF:SERVER:FIELDGET("DATAD"))
   alert("Falta Data do Desenho")
   RETU
ENDIF
IF Empty(SELF:SERVER:FIELDGET("DATAR"))
   alert("Falta Data Revisão")
   RETU
ENDIF
SELF:SERVER:FIELDPUT("LAUDOF",SIMNAO(SELF:SERVER:FIELDGET("LAUDOF"),{"A","R","C","G"}))	

METHOD cmdlaudo1( )  

METHOD cmdlaudoitem( ) 
IF Empty(SELF:SERVER:FIELDGET("DATAD"))
   alert("Falta Data do Desenho")
   RETU
ENDIF
IF Empty(SELF:SERVER:FIELDGET("DATAR"))
   alert("Falta Data Revisão")
   RETU
ENDIF	
SELF:oSFJRII:SERVER:FIELDPUT("LAUDO",SIMNAO(SELF:oSFJRII:FIELDGET("LAUDO"),{"A","R","G"}))


METHOD cmdlaudoitem1( ) 
	SELF:oSFJRII:SERVER:FIELDPUT("TIPINSP",SIMNAO(SELF:oSFJRII:FIELDGET("TIPINSP"),{"I","P","O","C","S","|","I","Ø"," "}))

METHOD cmdorigem( ) 
	SELF:SERVER:FIELDPUT("ORIGEM",SIMNAO(SELF:SERVER:FIELDGET("ORIGEM"),{"A","P"}))	

METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
    SELF:oSFJRII:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJRII:SERVER:gotop()
    WHILE ! SELF:oSFJRII:SERVER:eof
	 	SELF:oSFJRII:SERVER:delete()
	 	SELF:oSFJRII:SERVER:skip()	
      ENDDO
	SELF:oSFJRII:SERVER:resetnotification()
	SELF:oSFJRII:SERVER:notify(notifyfilechange)
	SELF:server:skip(-1)	
ENDIF	


METHOD escava( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("INSNUM",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("INSMOM",oESCMP04:NOME)
ENDIF	

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF oesc:lok
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF		

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("INSNUM",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("INSNOM",oESCMP04:NOME)
ENDIF

METHOD EXCLUIR 
SELF:oSFJRII:SERVER:SUSPENDNOTIFICATION()
IF MDG("Apagar Registro") .AND. SELF:oSFJRII:server:LockCurrentRecord()
    SELF:oSFJRII:server:delete()
    SELF:oSFJRII:server:unlock()
    SELF:oSFJRII:server:skip(-1)
ENDIF	
SELF:oSFJRII:SERVER:resetnotification()
SELF:oSFJRII:SERVER:notify(notifyfilechange)
SELF:RENUM()
SELF:oSFJRII:Browser:REFRESH()

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("DESENHO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()

METHOD INCLUIR 
LOCAL nRI AS DWORD
LOCAL nITEM AS DWORD
IF Empty(SELF:SERVER:FIELDGET("DATAD"))
   alert("Falta Data do Desenho")
   RETU
ENDIF
IF Empty(SELF:SERVER:FIELDGET("DATAR"))
   alert("Falta Data Revisão")
   RETU
ENDIF
nRI:=SELF:SERVER:RI
nITEM:=Val(SELF:oDCnPOS:TextValue)
IF nITEM=0
   SELF:oSFJRII:SERVER:GOBOTTOM()
   nITEM:=SELF:oSFJRII:SERVER:ITEM
   nITEM++
   SELF:oSFJRII:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJRII:SERVER:APPEND()
   SELF:oSFJRII:SERVER:RI:=nRI
   SELF:oSFJRII:SERVER:ITEM:=nITEM
   SELF:oSFJRII:SERVER:commit()
   SELF:oSFJRII:SERVER:resetnotification()
   SELF:oSFJRII:SERVER:notify(notifyappend)
ELSE
  SELF:oSFJRII:SERVER:SUSPENDNOTIFICATION()	
  SELF:oSFJRII:SERVER:GOTOP()
   WHILE !  oSFJRII:server:EOF
  	   IF SELF:oSFJRII:server:ITEM=nITEM-1
          SELF:oSFJRII:SERVER:APPEND()
          SELF:oSFJRII:SERVER:RI:=nRI
          SELF:oSFJRII:SERVER:ITEM:=nITEM
          SELF:oSFJRII:SERVER:commit()
          EXIT
       ENDIF
       SELF:oSFJRII:server:SKIP()
   ENDDO
   SELF:oSFJRII:SERVER:resetnotification()
   SELF:oSFJRII:SERVER:notify(notifyfilechange)
   SELF:RENUM()
ENDIF
SELF:oSFJRII:Browser:REFRESH()



METHOD PEGins( ) 
LOCAL aTEC,ACOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:SERVER:FIELDGET("insnum"),ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:SERVER:FIELDPUT("insnom",aTEC[2])	
ENDIF		

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   SELF:oDCisos:Caption:=CHR(62)
   SELF:oDCisoi:Caption:=CHR(128)
   SELF:oDCisop:Caption:=CHR(57)
   SELF:oDCisoo:Caption:=CHR(129)
   SELF:oDCisoc:Caption:=CHR(69)
FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
self:oSFJRII:Browser:SuspendUpdate()
self:oSFJRII:SkipNext()
IF self:oSFJRII:Server:Eof
	self:oSFJRII:SkipPrevious()
ENDIF
self:oSFJRII:Browser:RestoreUpdate()

METHOD RENUM 
LOCAL nITEM AS WORD
nITEM:=1
SELF:oSFJRII:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJRII:server:GOTOP()
WHILE !  oSFJRII:server:EOF
  SELF:oSFJRII:server:ITEM:=nITEM
  SELF:oSFJRII:server:SKIP()
   nITEM++
ENDDO
SELF:oSFJRII:server:GOTOP()
SELF:oSFJRII:SERVER:resetnotification()
SELF:oSFJRII:SERVER:notify(notifyfilechange)

METHOD TABULAR  
SELF:oSFJRII:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJRII:Server:COMMIT()


METHOD XDuplicar(cARQI) 
LOCAL nRI AS DWORD
LOCAL nFIELD,J,K AS WORD
LOCAL aITENS,aTMP,aDADOS,aDAD AS ARRAY
LOCAL oRII AS USEREDE

nFIELD:=SELF:SERVER:FCOUNT
nRI:=SELF:Server:FIELDGET("RI")
aDADOS:={}
FOR J:=1 TO nFIELD
    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
NEXT J
aITENS:={}
aDAD:={zCURINI,cARQI,zCURDIR}
oRII:=USEREDE{aDAD}
IF oRII:nERRO=0
     nFIELD:=oRII:FCOUNT
     oRII:GOTOP()
     oRII:SEEK(nRI)
     WHILE oRII:FIELDGET("RI")=nRI .AND. ! oRII:EOF
          aTMP:={}
  	      FOR J:=1 TO nFIELD
	          AAdd(aTMP,oRII:FIELDGET(J))
          NEXT J
          AAdd(aITENS,aTMP)
          oRII:SKIP()
    ENDDO
ENDIF
SELF:server:setorder(1)
SELF:server:gobottom()
nRI:=SELF:Server:RI
nRI++
SUPER:SERVER:APPEND()
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    SELF:SERVER:FIELDPUT(J,aDADOS[J])
NEXT J
SELF:SERVER:FIELDPUT("RI",nRI)
IF oRII:USED
     nFIELD:=oRII:FCOUNT
     FOR K:=1 TO ALen(aITENS)
         oRII:APPEND()
   	     FOR J:=1 TO nFIELD
             oRII:FIELDPUT(J,aITENS[K][J])
         NEXT J
         oRII:FIELDPUT("LAUDO","")
         oRII:FIELDPUT("RI",nRI)
     NEXT K
     oRII:CLOSE()
ENDIF
SELF:server:gotop()
SELF:server:gobottom()
RETURN







END CLASS
PARTIAL CLASS XJRI
METHOD Duplicar 
	SELF:XDuplicar("RII.DBF")


END CLASS
