PARTIAL CLASS JRRL
METHOD APPEND() 
LOCAL nRRS AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nRRS:=SELF:Server:RRS
nRRS++
SUPER:append()
SELF:SERVER:FIELDPUT("RRS",nRRS)
SELF:server:FIELDPUT("data",Today())
SELF:server:FIELDPUT("K01",0.5908)
SELF:server:FIELDPUT("K02",0.5231)
SELF:server:FIELDPUT("K03",0.3146)
SELF:server:FIELDPUT("K04",1.41)
RETURN

METHOD ASSINAR() 
LOCAL aCAMPOS AS ARRAY
LOCAL aDIZ AS ARRAY
LOCAL X AS WORD
aCAMPOS:={"CLIENTE","CLINOME","DESENHO","DESCRI","DESCII","CARAC","ESPEC","AVA","AVAN",;
    "AVB","AVBN","AVC","AVCN"}
aDIZ:={"Nº Cliente","Nome Cliente","DESENHO","Descriçao Desenho","Descriçao Ins","Caracteristica","Espeçie",;
       "Nome Aval A","Nº Aval A","Nome Aval B","Nº Aval B","Nome Aval C","Nº Aval C"}
FOR X:=1 TO 13
	IF Empty(SELF:SERVER:FIELDGET(aCAMPOs[X]))
	   IF ! MDG("Campo "+Adiz[x]+" Não Preenchido - Continuar")
	      RETU
	   ENDIF
	ENDIF	
NEXT
IF ! Empty(SELF:SERVER:FIELDGET("DATASS"))
   alert("Ja Assinada")
   RETU
ENDIF
SELF:SERVER:FIELDPUT("NUMASS",ZFOLHA)
SELF:SERVER:FIELDPUT("NOMASS",ZNOMEFOLHA)
SELF:SERVER:FIELDPUT("DATASS",Today())


METHOD btnpegma01 
LOCAL Acli AS ARRAY	
aCLI:=PEGMA01(SELF:SERVER:CLIENTE,zcurini,zcurdir)
IF aCLI[1]=.T.
   SELF:SERVER:CLINOME:=aCLI[2]
ENDIF

METHOD btnpegms01 
LOCAL apro AS ARRAY	
aPRO:=PEGMS01(SELF:SERVER:DESENHO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
  SELF:SERVER:DESCRI:=aPRO[2]
ENDIF

METHOD buscanum( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","RR")	


METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD Duplicar( ) 
LOCAL aVAL AS ARRAY
aVAL:={}

AAdd(aVAL,SELF:SERVER:FIELDGET("CLIENTE"))
AAdd(aVAL,SELF:SERVER:FIELDGET("CLINOME"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESENHO"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESCRI"))
AAdd(aVAL,SELF:SERVER:FIELDGET("INSTRU"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESCII"))
AAdd(aVAL,SELF:SERVER:FIELDGET("CARAC"))
AAdd(aVAL,SELF:SERVER:FIELDGET("ESPEC"))
AAdd(aVAL,SELF:SERVER:FIELDGET("TOLMIN"))
AAdd(aVAL,SELF:SERVER:FIELDGET("TOLMAX"))

SELF:APPEND()	

SELF:SERVER:FIELDPUT("CLIENTE",aVAL[1])
SELF:SERVER:FIELDPUT("CLINOME",aVAL[2])
SELF:SERVER:FIELDPUT("DESENHO",aVAL[3])
SELF:SERVER:FIELDPUT("DESCRI",aVAL[4])
SELF:SERVER:FIELDPUT("INSTRU",aVAL[5])
SELF:SERVER:FIELDPUT("DESCII",aVAL[6])
SELF:SERVER:FIELDPUT("CARAC",aVAL[7])
SELF:SERVER:FIELDPUT("ESPEC",aVAL[8])
SELF:SERVER:FIELDPUT("TOLMIN",aVAL[9])
SELF:SERVER:FIELDPUT("TOLMAX",aVAL[10])
	
	
//duplicava tambem as cotas	
//LOCAL nRRS,NREG,NFIELD AS DWORD
//LOCAL J AS WORD
//LOCAL aDADOS AS ARRAY
//nFIELD:=SELF:SERVER:FCOUNT
//nREG:=SELF:Server:recno
//aDADOS:={}
//FOR J=1 TO nFIELD
//    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
//NEXT J
//SELF:server:setorder(1)
//SELF:server:gobottom()
//nRRS:=SELF:Server:FIELDGET("RRS")
//nRRS++
//SUPER:SERVER:APPEND()
//FOR J=1 TO nFIELD
//    SELF:SERVER:FIELDPUT(J,aDADOS[J])
//NEXT J
//SELF:SERVER:FIELDPUT("RRS",nRRS)
//RETURN	

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF		

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("DESENHO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()

METHOD ListBoxSelect( oControlEvent ) 
	LOCAL oControl AS Control
//	LOCAL uValue AS USUAL
	oControl := IIf( oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control )
	SUPER:ListBoxSelect( oControlEvent )
	//Put your changes here
	DO CASE
	       CASE oCONTROL:NAMESYM==#INSTRU
			 SELF:SERVER:DESCII:=SELF:oDCINSTRU:textvalue	
	ENDCASE
RETURN NIL


METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   FabCenterWindow( SELF )
 RETURN SELF

METHOD TABINS 
RETU MTD02("TIPINS",3)

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
PARTIAL CLASS TabControl1_Page1
METHOD escava( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("AVAN",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("AVA",oESCMP04:NOME)
ENDIF


METHOD pegavA 
LOCAL ATEC,ACOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:SERVER:AVAN,ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:SERVER:AVA:=aTEC[2]
ENDIF



END CLASS
PARTIAL CLASS TabControl1_Page2
METHOD escavB( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("AVBN",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("AVB",oESCMP04:NOME)
ENDIF

METHOD pegavB 
LOCAL ATEC,ACOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:SERVER:AVBN,ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:SERVER:AVB:=aTEC[2]
ENDIF

END CLASS
PARTIAL CLASS TabControl1_Page3
METHOD escavc( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF ! IsNil(oESCMP04:NOME)
   SELF:SERVER:FIELDPUT("AVCN",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("AVC",oESCMP04:NOME)
ENDIF



METHOD pegavc 
LOCAL ATEC,aCOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:SERVER:AVcN,ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:SERVER:AVc:=aTEC[2]
ENDIF

END CLASS
PARTIAL CLASS TabControl1_Page4
METHOD CALCRP 
LOCAL nVAL AS FLOAT
nVAL:=SELF:SERVER:AMA01
nVAL+=SELF:SERVER:AMAA01
nVAL+=SELF:SERVER:AMAAA01
nVAL+=SELF:SERVER:AMB01
nVAL+=SELF:SERVER:AMBB01
nVAL+=SELF:SERVER:AMBBB01
nVAL+=SELF:SERVER:AMC01
nVAL+=SELF:SERVER:AMCC01
nVAL+=SELF:SERVER:AMCCC01
nVAL:=nVAL/9
SELF:SERVER:M01:=nVAL


nVAL:=SELF:SERVER:AMA02
nVAL+=SELF:SERVER:AMAA02
nVAL+=SELF:SERVER:AMAAA02
nVAL+=SELF:SERVER:AMB02
nVAL+=SELF:SERVER:AMBB02
nVAL+=SELF:SERVER:AMBBB02
nVAL+=SELF:SERVER:AMC02
nVAL+=SELF:SERVER:AMCC02
nVAL+=SELF:SERVER:AMCCC02
nVAL:=nVAL/9
SELF:SERVER:M02:=nVAL


nVAL:=SELF:SERVER:AMA03
nVAL+=SELF:SERVER:AMAA03
nVAL+=SELF:SERVER:AMAAA03
nVAL+=SELF:SERVER:AMB03
nVAL+=SELF:SERVER:AMBB03
nVAL+=SELF:SERVER:AMBBB03
nVAL+=SELF:SERVER:AMC03
nVAL+=SELF:SERVER:AMCC03
nVAL+=SELF:SERVER:AMCCC03
nVAL:=nVAL/9
SELF:SERVER:M03:=nVAL

nVAL:=SELF:SERVER:AMA04
nVAL+=SELF:SERVER:AMAA04
nVAL+=SELF:SERVER:AMAAA04
nVAL+=SELF:SERVER:AMB04
nVAL+=SELF:SERVER:AMBB04
nVAL+=SELF:SERVER:AMBBB04
nVAL+=SELF:SERVER:AMC04
nVAL+=SELF:SERVER:AMCC04
nVAL+=SELF:SERVER:AMCCC04
nVAL:=nVAL/9
SELF:SERVER:M04:=nVAL

nVAL:=SELF:SERVER:AMA05
nVAL+=SELF:SERVER:AMAA05
nVAL+=SELF:SERVER:AMAAA05
nVAL+=SELF:SERVER:AMB05
nVAL+=SELF:SERVER:AMBB05
nVAL+=SELF:SERVER:AMBBB05
nVAL+=SELF:SERVER:AMC05
nVAL+=SELF:SERVER:AMCC05
nVAL+=SELF:SERVER:AMCCC05
nVAL:=nVAL/9
SELF:SERVER:M05:=nVAL

nVAL:=SELF:SERVER:AMA06
nVAL+=SELF:SERVER:AMAA06
nVAL+=SELF:SERVER:AMAAA06
nVAL+=SELF:SERVER:AMB06
nVAL+=SELF:SERVER:AMBB06
nVAL+=SELF:SERVER:AMBBB06
nVAL+=SELF:SERVER:AMC06
nVAL+=SELF:SERVER:AMCC06
nVAL+=SELF:SERVER:AMCCC06
nVAL:=nVAL/9
SELF:SERVER:M06:=nVAL


nVAL:=SELF:SERVER:AMA07
nVAL+=SELF:SERVER:AMAA07
nVAL+=SELF:SERVER:AMAAA07
nVAL+=SELF:SERVER:AMB07
nVAL+=SELF:SERVER:AMBB07
nVAL+=SELF:SERVER:AMBBB07
nVAL+=SELF:SERVER:AMC07
nVAL+=SELF:SERVER:AMCC07
nVAL+=SELF:SERVER:AMCCC07
nVAL:=nVAL/9
SELF:SERVER:M07:=nVAL

nVAL:=SELF:SERVER:AMA08
nVAL+=SELF:SERVER:AMAA08
nVAL+=SELF:SERVER:AMAAA08
nVAL+=SELF:SERVER:AMB08
nVAL+=SELF:SERVER:AMBB08
nVAL+=SELF:SERVER:AMBBB08
nVAL+=SELF:SERVER:AMC08
nVAL+=SELF:SERVER:AMCC08
nVAL+=SELF:SERVER:AMCCC08
nVAL:=nVAL/9
SELF:SERVER:M08:=nVAL

nVAL:=SELF:SERVER:AMA09
nVAL+=SELF:SERVER:AMAA09
nVAL+=SELF:SERVER:AMAAA09
nVAL+=SELF:SERVER:AMB09
nVAL+=SELF:SERVER:AMBB09
nVAL+=SELF:SERVER:AMBBB09
nVAL+=SELF:SERVER:AMC09
nVAL+=SELF:SERVER:AMCC09
nVAL+=SELF:SERVER:AMCCC09
nVAL:=nVAL/9
SELF:SERVER:M09:=nVAL


nVAL:=SELF:SERVER:AMA10
nVAL+=SELF:SERVER:AMAA10
nVAL+=SELF:SERVER:AMAAA10
nVAL+=SELF:SERVER:AMB10
nVAL+=SELF:SERVER:AMBB10
nVAL+=SELF:SERVER:AMBBB10
nVAL+=SELF:SERVER:AMC10
nVAL+=SELF:SERVER:AMCC10
nVAL+=SELF:SERVER:AMCCC10
nVAL:=nVAL/9
SELF:SERVER:M10:=nVAL




nVAL:=SELF:SERVER:M01
nVAL:=IF(SELF:SERVER:M02>nVAL,SELF:SERVER:M02,nVAL)
nVAL:=IF(SELF:SERVER:M03>nVAL,SELF:SERVER:M03,nVAL)
nVAL:=IF(SELF:SERVER:M04>nVAL,SELF:SERVER:M04,nVAL)
nVAL:=IF(SELF:SERVER:M05>nVAL,SELF:SERVER:M05,nVAL)
nVAL:=IF(SELF:SERVER:M06>nVAL,SELF:SERVER:M06,nVAL)
nVAL:=IF(SELF:SERVER:M07>nVAL,SELF:SERVER:M07,nVAL)
nVAL:=IF(SELF:SERVER:M08>nVAL,SELF:SERVER:M08,nVAL)
nVAL:=IF(SELF:SERVER:M09>nVAL,SELF:SERVER:M09,nVAL)
nVAL:=IF(SELF:SERVER:M10>nVAL,SELF:SERVER:M10,nVAL)
SELF:SERVER:RPMAX:=nVAL


nVAL:=SELF:SERVER:M01
nVAL:=IF(SELF:SERVER:M02<nVAL,SELF:SERVER:M02,nVAL)
nVAL:=IF(SELF:SERVER:M03<nVAL,SELF:SERVER:M03,nVAL)
nVAL:=IF(SELF:SERVER:M04<nVAL,SELF:SERVER:M04,nVAL)
nVAL:=IF(SELF:SERVER:M05<nVAL,SELF:SERVER:M05,nVAL)
nVAL:=IF(SELF:SERVER:M06<nVAL,SELF:SERVER:M06,nVAL)
nVAL:=IF(SELF:SERVER:M07<nVAL,SELF:SERVER:M07,nVAL)
nVAL:=IF(SELF:SERVER:M08<nVAL,SELF:SERVER:M08,nVAL)
nVAL:=IF(SELF:SERVER:M09<nVAL,SELF:SERVER:M09,nVAL)
nVAL:=IF(SELF:SERVER:M10<nVAL,SELF:SERVER:M10,nVAL)
SELF:SERVER:RPMIN:=nVAL

nVAL:=Abs(SELF:SERVER:RPMAX-SELF:SERVER:RPMIN)
SELF:SERVER:RP:=nVAL


METHOD Calcular( ) 
LOCAL nVAL AS FLOAT
LOCAL nVAL2 AS FLOAT
LOCAL nVAL3 AS FLOAT
LOCAL nVAL4 AS FLOAT
LOCAL nVAL5 AS FLOAT


SELF:SERVER:TOTAA:=0
SELF:SERVER:TOTAB:=0
SELF:SERVER:TOTAC:=0
SELF:SERVER:TOTBA:=0
SELF:SERVER:TOTBB:=0
SELF:SERVER:TOTBC:=0
SELF:SERVER:TOTCA:=0
SELF:SERVER:TOTCB:=0
SELF:SERVER:TOTCC:=0
SELF:SERVER:MEDAA:=0
SELF:SERVER:MEDBB:=0
SELF:SERVER:MEDCC:=0
SELF:SERVER:TOTALA:=0
SELF:SERVER:TOTALB:=0
SELF:SERVER:TOTALC:=0
SELF:SERVER:MEDIA:=0
SELF:SERVER:MEDIB:=0
SELF:SERVER:MEDIC:=0
SELF:SERVER:MEDSOM:=0
SELF:SERVER:MEDMED:=0
SELF:SERVER:DIFMED:=0
SELF:SERVER:VE:=0
SELF:SERVER:VA:=0
SELF:SERVER:VP:=0
SELF:SERVER:VT:=0
SELF:SERVER:RR:=0
SELF:SERVER:PVE:=0
SELF:SERVER:PVA:=0
SELF:SERVER:PRR:=0

nVAL:=0
nVAL :=SELF:SERVER:AMA01
nVAL+=SELF:SERVER:AMA02
nVAL+=SELF:SERVER:AMA03
nVAL+=SELF:SERVER:AMA04
nVAL+=SELF:SERVER:AMA05
nVAL2:=0
nVAL2:=SELF:SERVER:AMA06
nVAL2+=SELF:SERVER:AMA07
nVAL2+=SELF:SERVER:AMA08
nVAL2+=SELF:SERVER:AMA09
nVAL2+=SELF:SERVER:AMA10
SELF:SERVER:TOTAA:=nVAL+nVAL2

nVAL:=0
nVAL :=SELF:SERVER:AMAA01
nVAL+=SELF:SERVER:AMAA02
nVAL+=SELF:SERVER:AMAA03
nVAL+=SELF:SERVER:AMAA04
nVAL+=SELF:SERVER:AMAA05
nVAL2:=0
nVAL2:=SELF:SERVER:AMAA06
nVAL2+=SELF:SERVER:AMAA07
nVAL2+=SELF:SERVER:AMAA08
nVAL2+=SELF:SERVER:AMAA09
nVAL2+=SELF:SERVER:AMAA10
SELF:SERVER:TOTAB:=nVAL+nVAL2


nVAL:=0
nVAL :=SELF:SERVER:AMAAA01
nVAL+=SELF:SERVER:AMAAA02
nVAL+=SELF:SERVER:AMAAA03
nVAL+=SELF:SERVER:AMAAA04
nVAL+=SELF:SERVER:AMAAA05
nVAL2:=0
nVAL2:=SELF:SERVER:AMAAA06
nVAL2+=SELF:SERVER:AMAAA07
nVAL2+=SELF:SERVER:AMAAA08
nVAL2+=SELF:SERVER:AMAAA09
nVAL2+=SELF:SERVER:AMAAA10
SELF:SERVER:TOTAC:=nVAL+nVAL2


nVAL:=0
nVAL :=SELF:SERVER:AMB01
nVAL+=SELF:SERVER:AMB02
nVAL+=SELF:SERVER:AMB03
nVAL+=SELF:SERVER:AMB04
nVAL+=SELF:SERVER:AMB05
nVAL2:=0
nVAL2 :=SELF:SERVER:AMB06
nVAL2+=SELF:SERVER:AMB07
nVAL2+=SELF:SERVER:AMB08
nVAL2+=SELF:SERVER:AMB09
nVAL2+=SELF:SERVER:AMB10
SELF:SERVER:TOTBA:=nVAL+nVAL2

nVAL:=0
nVAL :=SELF:SERVER:AMBB01
nVAL+=SELF:SERVER:AMBB02
nVAL+=SELF:SERVER:AMBB03
nVAL+=SELF:SERVER:AMBB04
nVAL+=SELF:SERVER:AMBB05
nVAL2:=0
nVAL2:=SELF:SERVER:AMBB06
nVAL2+=SELF:SERVER:AMBB07
nVAL2+=SELF:SERVER:AMBB08
nVAL2+=SELF:SERVER:AMBB09
nVAL2+=SELF:SERVER:AMBB10
SELF:SERVER:TOTBB:=nVAL+nVAL2


nVAL:=0
nVAL :=SELF:SERVER:AMBBB01
nVAL+=SELF:SERVER:AMBBB02
nVAL+=SELF:SERVER:AMBBB03
nVAL+=SELF:SERVER:AMBBB04
nVAL+=SELF:SERVER:AMBBB05
nVAL2:=0
nVAL2 :=SELF:SERVER:AMBBB06
nVAL2+=SELF:SERVER:AMBBB07
nVAL2+=SELF:SERVER:AMBBB08
nVAL2+=SELF:SERVER:AMBBB09
nVAL2+=SELF:SERVER:AMBBB10
SELF:SERVER:TOTBC:=nVAL+nVAL2


nVAL:=0
nVAL :=SELF:SERVER:AMC01
nVAL+=SELF:SERVER:AMC02
nVAL+=SELF:SERVER:AMC03
nVAL+=SELF:SERVER:AMC04
nVAL+=SELF:SERVER:AMC05
nVAL2:=0
nVAL2 :=SELF:SERVER:AMC06
nVAL2+=SELF:SERVER:AMC07
nVAL2+=SELF:SERVER:AMC08
nVAL2+=SELF:SERVER:AMC09
nVAL2+=SELF:SERVER:AMC10
SELF:SERVER:TOTCA:=nVAL+nVAL2


nVAL:=0
nVAL :=SELF:SERVER:AMCC01
nVAL+=SELF:SERVER:AMCC02
nVAL+=SELF:SERVER:AMCC03
nVAL+=SELF:SERVER:AMCC04
nVAL+=SELF:SERVER:AMCC05
nVAL2:=0
nVAL2 :=SELF:SERVER:AMCC06
nVAL2+=SELF:SERVER:AMCC07
nVAL2+=SELF:SERVER:AMCC08
nVAL2+=SELF:SERVER:AMCC09
nVAL2+=SELF:SERVER:AMCC10
SELF:SERVER:TOTCB:=nVAL+nVAL2


nVAL:=0
nVAL :=SELF:SERVER:AMCCC01
nVAL+=SELF:SERVER:AMCCC02
nVAL+=SELF:SERVER:AMCCC03
nVAL+=SELF:SERVER:AMCCC04
nVAL+=SELF:SERVER:AMCCC05
nVAL2:=0
nVAL2 :=SELF:SERVER:AMCCC06
nVAL2+=SELF:SERVER:AMCCC07
nVAL2+=SELF:SERVER:AMCCC08
nVAL2+=SELF:SERVER:AMCCC09
nVAL2+=SELF:SERVER:AMCCC10
SELF:SERVER:TOTCC:=nVAL+nVAL2




nVAL :=SELF:SERVER:TOTAA
nVAL+=SELF:SERVER:TOTAB
nVAL+=SELF:SERVER:TOTAC
SELF:SERVER:TOTALA:=nVAL
SELF:SERVER:MEDIA:=(nVAL/30)

nVAL:=(SELF:SERVER:TOTBA+SELF:SERVER:TOTBB+SELF:SERVER:TOTBC)
SELF:SERVER:TOTALB:=nVAL
SELF:SERVER:MEDIB:=(nVAL/30)


nVAL:=(SELF:SERVER:TOTCA+SELF:SERVER:TOTCB+SELF:SERVER:TOTCC)
SELF:SERVER:TOTALC:=nVAL
SELF:SERVER:MEDIC:=(nVAL/30)

 nVAL2:=Abs(SELF:SERVER:AMA01   -SELF:SERVER:AMAA01)
 nVAL3:=Abs(SELF:SERVER:AMA01   -SELF:SERVER:AMAAA01)
 nVAL4:=Abs(SELF:SERVER:AMAA01-SELF:SERVER:AMAAA01)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA01:=nVAL

 nVAL2:=Abs(SELF:SERVER:AMA02   -SELF:SERVER:AMAA02)
 nVAL3:=Abs(SELF:SERVER:AMA02   -SELF:SERVER:AMAAA02)
 nVAL4:=Abs(SELF:SERVER:AMAA02-SELF:SERVER:AMAAA02)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA02:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMA03   -SELF:SERVER:AMAA03)
 nVAL3:=Abs(SELF:SERVER:AMA03   -SELF:SERVER:AMAAA03)
 nVAL4:=Abs(SELF:SERVER:AMAA03-SELF:SERVER:AMAAA03)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA03:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMA04   -SELF:SERVER:AMAA04)
 nVAL3:=Abs(SELF:SERVER:AMA04   -SELF:SERVER:AMAAA04)
 nVAL4:=Abs(SELF:SERVER:AMAA04-SELF:SERVER:AMAAA04)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA04:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMA05   -SELF:SERVER:AMAA05)
 nVAL3:=Abs(SELF:SERVER:AMA05   -SELF:SERVER:AMAAA05)
 nVAL4:=Abs(SELF:SERVER:AMAA05-SELF:SERVER:AMAAA05)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA05:=nVAL

 nVAL2:=Abs(SELF:SERVER:AMA06   -SELF:SERVER:AMAA06)
 nVAL3:=Abs(SELF:SERVER:AMA06   -SELF:SERVER:AMAAA06)
 nVAL4:=Abs(SELF:SERVER:AMAA06-SELF:SERVER:AMAAA06)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA06:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMA07   -SELF:SERVER:AMAA07)
 nVAL3:=Abs(SELF:SERVER:AMA07   -SELF:SERVER:AMAAA07)
 nVAL4:=Abs(SELF:SERVER:AMAA07-SELF:SERVER:AMAAA07)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA07:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMA08   -SELF:SERVER:AMAA08)
 nVAL3:=Abs(SELF:SERVER:AMA08   -SELF:SERVER:AMAAA08)
 nVAL4:=Abs(SELF:SERVER:AMAA08-SELF:SERVER:AMAAA08)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA08:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMA09   -SELF:SERVER:AMAA09)
 nVAL3:=Abs(SELF:SERVER:AMA09   -SELF:SERVER:AMAAA09)
 nVAL4:=Abs(SELF:SERVER:AMAA09-SELF:SERVER:AMAAA09)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA09:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMA10   -SELF:SERVER:AMAA10)
 nVAL3:=Abs(SELF:SERVER:AMA10   -SELF:SERVER:AMAAA10)
 nVAL4:=Abs(SELF:SERVER:AMAA10-SELF:SERVER:AMAAA10)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFA10:=nVAL



 nVAL2:=Abs(SELF:SERVER:AMB01   -SELF:SERVER:AMBB01)
 nVAL3:=Abs(SELF:SERVER:AMB01   -SELF:SERVER:AMBBB01)
 nVAL4:=Abs(SELF:SERVER:AMBB01-SELF:SERVER:AMBBB01)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB01:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMB02   -SELF:SERVER:AMBB02)
 nVAL3:=Abs(SELF:SERVER:AMB02   -SELF:SERVER:AMBBB02)
 nVAL4:=Abs(SELF:SERVER:AMBB02-SELF:SERVER:AMBBB02)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB02:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMB03   -SELF:SERVER:AMBB03)
 nVAL3:=Abs(SELF:SERVER:AMB03   -SELF:SERVER:AMBBB03)
 nVAL4:=Abs(SELF:SERVER:AMBB03-SELF:SERVER:AMBBB03)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB03:=nVAL

 nVAL2:=Abs(SELF:SERVER:AMB04   -SELF:SERVER:AMBB04)
 nVAL3:=Abs(SELF:SERVER:AMB04   -SELF:SERVER:AMBBB04)
 nVAL4:=Abs(SELF:SERVER:AMBB04-SELF:SERVER:AMBBB04)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB04:=nVAL

 nVAL2:=Abs(SELF:SERVER:AMB05   -SELF:SERVER:AMBB05)
 nVAL3:=Abs(SELF:SERVER:AMB05   -SELF:SERVER:AMBBB05)
 nVAL4:=Abs(SELF:SERVER:AMBB05-SELF:SERVER:AMBBB05)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB05:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMB06   -SELF:SERVER:AMBB06)
 nVAL3:=Abs(SELF:SERVER:AMB06   -SELF:SERVER:AMBBB06)
 nVAL4:=Abs(SELF:SERVER:AMBB06-SELF:SERVER:AMBBB06)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB06:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMB07   -SELF:SERVER:AMBB07)
 nVAL3:=Abs(SELF:SERVER:AMB07   -SELF:SERVER:AMBBB07)
 nVAL4:=Abs(SELF:SERVER:AMBB07-SELF:SERVER:AMBBB07)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB07:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMB08   -SELF:SERVER:AMBB08)
 nVAL3:=Abs(SELF:SERVER:AMB08   -SELF:SERVER:AMBBB08)
 nVAL4:=Abs(SELF:SERVER:AMBB08-SELF:SERVER:AMBBB08)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB08:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMB09   -SELF:SERVER:AMBB09)
 nVAL3:=Abs(SELF:SERVER:AMB09   -SELF:SERVER:AMBBB09)
 nVAL4:=Abs(SELF:SERVER:AMBB09-SELF:SERVER:AMBBB09)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB09:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMB10   -SELF:SERVER:AMBB10)
 nVAL3:=Abs(SELF:SERVER:AMB10   -SELF:SERVER:AMBBB10)
 nVAL4:=Abs(SELF:SERVER:AMBB10-SELF:SERVER:AMBBB10)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFB10:=nVAL



 nVAL2:=Abs(SELF:SERVER:AMC01   -SELF:SERVER:AMCC01)
 nVAL3:=Abs(SELF:SERVER:AMC01   -SELF:SERVER:AMCCC01)
 nVAL4:=Abs(SELF:SERVER:AMCC01-SELF:SERVER:AMCCC01)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC01:=nVAL

 nVAL2:=Abs(SELF:SERVER:AMC02   -SELF:SERVER:AMCC02)
 nVAL3:=Abs(SELF:SERVER:AMC02   -SELF:SERVER:AMCCC02)
 nVAL4:=Abs(SELF:SERVER:AMCC02-SELF:SERVER:AMCCC02)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC02:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMC03   -SELF:SERVER:AMCC03)
 nVAL3:=Abs(SELF:SERVER:AMC03   -SELF:SERVER:AMCCC03)
 nVAL4:=Abs(SELF:SERVER:AMCC03-SELF:SERVER:AMCCC03)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC03:=nVAL



 nVAL2:=Abs(SELF:SERVER:AMC04   -SELF:SERVER:AMCC04)
 nVAL3:=Abs(SELF:SERVER:AMC04   -SELF:SERVER:AMCCC04)
 nVAL4:=Abs(SELF:SERVER:AMCC04-SELF:SERVER:AMCCC04)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC04:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMC05   -SELF:SERVER:AMCC05)
 nVAL3:=Abs(SELF:SERVER:AMC05   -SELF:SERVER:AMCCC05)
 nVAL4:=Abs(SELF:SERVER:AMCC05-SELF:SERVER:AMCCC05)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC05:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMC06   -SELF:SERVER:AMCC06)
 nVAL3:=Abs(SELF:SERVER:AMC06   -SELF:SERVER:AMCCC06)
 nVAL4:=Abs(SELF:SERVER:AMCC06-SELF:SERVER:AMCCC06)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC06:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMC07   -SELF:SERVER:AMCC07)
 nVAL3:=Abs(SELF:SERVER:AMC07   -SELF:SERVER:AMCCC07)
 nVAL4:=Abs(SELF:SERVER:AMCC07-SELF:SERVER:AMCCC07)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC07:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMC08   -SELF:SERVER:AMCC08)
 nVAL3:=Abs(SELF:SERVER:AMC08   -SELF:SERVER:AMCCC08)
 nVAL4:=Abs(SELF:SERVER:AMCC08-SELF:SERVER:AMCCC08)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC08:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMC09   -SELF:SERVER:AMCC09)
 nVAL3:=Abs(SELF:SERVER:AMC09   -SELF:SERVER:AMCCC09)
 nVAL4:=Abs(SELF:SERVER:AMCC09-SELF:SERVER:AMCCC09)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC09:=nVAL


 nVAL2:=Abs(SELF:SERVER:AMC10   -SELF:SERVER:AMCC10)
 nVAL3:=Abs(SELF:SERVER:AMC10   -SELF:SERVER:AMCCC10)
 nVAL4:=Abs(SELF:SERVER:AMCC10-SELF:SERVER:AMCCC10)
 nVAL:=IF(nVAL2>nVAL3,nVAL2,nVAL3)
 nVAL:=IF(nVAL>nVAL4 ,nVAL   ,nVAL4)
SELF:SERVER:DIFC10:=nVAL

nVAL:=0
nVAL+=SELF:SERVER:DIFA01
nVAL+=SELF:SERVER:DIFA02
nVAL+=SELF:SERVER:DIFA03
nVAL+=SELF:SERVER:DIFA04
nVAL+=SELF:SERVER:DIFA05
nVAL+=SELF:SERVER:DIFA06
nVAL+=SELF:SERVER:DIFA07
nVAL+=SELF:SERVER:DIFA08
nVAL+=SELF:SERVER:DIFA09
nVAL+=SELF:SERVER:DIFA10
SELF:SERVER:MEDAA:=(nVAL/10)

nVAL:=0
nVAL+=SELF:SERVER:DIFB01
nVAL+=SELF:SERVER:DIFB02
nVAL+=SELF:SERVER:DIFB03
nVAL+=SELF:SERVER:DIFB04
nVAL+=SELF:SERVER:DIFB05
nVAL+=SELF:SERVER:DIFB06
nVAL+=SELF:SERVER:DIFB07
nVAL+=SELF:SERVER:DIFB08
nVAL+=SELF:SERVER:DIFB09
nVAL+=SELF:SERVER:DIFB10
SELF:SERVER:MEDBB:=(nVAL/10)

nVAL:=0
nVAL+=SELF:SERVER:DIFC01
nVAL+=SELF:SERVER:DIFC02
nVAL+=SELF:SERVER:DIFC03
nVAL+=SELF:SERVER:DIFC04
nVAL+=SELF:SERVER:DIFC05
nVAL+=SELF:SERVER:DIFC06
nVAL+=SELF:SERVER:DIFC07
nVAL+=SELF:SERVER:DIFC08
nVAL+=SELF:SERVER:DIFC09
nVAL+=SELF:SERVER:DIFC10
SELF:SERVER:MEDCC:=(nVAL/10)



nVAL:=(SELF:SERVER:MEDAA+SELF:SERVER:MEDBB+SELF:SERVER:MEDCC)
SELF:SERVER:MEDSOM:=nVAL
SELF:SERVER:MEDMED:=(nVAL/3)

nVAL  :=IF(SELF:SERVER:MEDIA>SELF:SERVER:MEDIB,SELF:SERVER:MEDIA,SELF:SERVER:MEDIB)
nVAL2:=IF(nVAL>SELF:SERVER:MEDIC,nVAL,SELF:SERVER:MEDIC)
SELF:SERVER:XMAX:=nVAL2

nVAL:=IF(SELF:SERVER:MEDIA<SELF:SERVER:MEDIB,SELF:SERVER:MEDIA,SELF:SERVER:MEDIB)
nVAL2:=IF(nVAL<SELF:SERVER:MEDIC,nVAL,SELF:SERVER:MEDIC)
SELF:SERVER:XMIN:=nVAL2

SELF:SERVER:DIFMED:=Abs(SELF:SERVER:XMAX-SELF:SERVER:XMIN)



SELF:CALCRP()


nVAL:=SELF:SERVER:MEDMED*SELF:SERVER:FIELDGET("K01")
SELF:SERVER:VE:=nVAL

nVAL2:=SELF:SERVER:DIFMED*SELF:SERVER:FIELDGET("K02")
nVAL3:=SELF:SERVER:VE
nVAL4:=(nVAL2*nVAL2)
nVAL5:=((nVAL3*nVAL3) /10)
IF nVAL4>nVAL5
    nVAL:=SQRT(nVAL4-nVAL5)
ELSE
   nVAL:=0
ENDIF
SELF:SERVER:VA:=nVAL

nVAL2:=SELF:SERVER:VE
nVAL3:=SELF:SERVER:VA
nVAL:=SQRT((nVAL2*nVAL2)+( nVAL3*nVAL3) )
SELF:SERVER:RR:=nVAL


nVAL:=SELF:SERVER:RP*SELF:SERVER:FIELDGET("K03")
SELF:SERVER:VP:=nVAL

nVAL2:=SELF:SERVER:RR
nVAL3:=SELF:SERVER:VP
nVAL:=SQRT((nVAL2*nVAL2)+( nVAL3*nVAL3) )
SELF:SERVER:VT:=nVAL



nVAL:=SELF:SERVER:VE/SELF:SERVER:VT*100
SELF:sERVER:PVE:=nVAL


nVAL:=SELF:SERVER:VA/SELF:SERVER:VT*100
SELF:sERVER:PVA:=nVAL


nVAL:=SELF:SERVER:RR/SELF:SERVER:VT*100
SELF:sERVER:PRR:=nVAL


nVAL:=SELF:SERVER:FIELDGET("K04")*(SELF:SERVER:VP/SELF:SERVER:RR)
SELF:sERVER:NCP:=nVAL

nVAL:=SELF:SERVER:VP/SELF:SERVER:VT*100
SELF:sERVER:PVP:=nVAL

IF SELF:SERVER:FIELDGET("VT")>(Abs(SELF:SERVER:FIELDGET("TOLMIN"))+Abs(SELF:SERVER:FIELDGET("TOLMAX")))
   alert("VT > Tolerancia")
ENDIF
RETU NIL

METHOD fatanov( ) 
SELF:server:FIELDPUT("K01",0.5908)
SELF:server:FIELDPUT("K02",0.5231)
SELF:server:FIELDPUT("K03",0.3146)
SELF:server:FIELDPUT("K04",1.41)

METHOD fatant( ) 
SELF:server:FIELDPUT("K01",3.05)
SELF:server:FIELDPUT("K02",2.70)
SELF:server:FIELDPUT("K03",1.62)	
SELF:server:FIELDPUT("K04",0)	


END CLASS
