PARTIAL CLASS Xjrrs
METHOD btnpegms01 
LOCAL apro AS ARRAY	
aPRO:=PEGMS01(SELF:SERVER:DESENHO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
  SELF:SERVER:DESCRI:=aPRO[2]
ENDIF

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF		


END CLASS
