PARTIAL CLASS JTEEP
METHOD APPEND() 
local nTEEP as dword
self:server:setorder(1)
self:server:gobottom()
nTEEP:=self:Server:TEEP
nTEEP++
super:append()
self:SERVER:FIELDPUT(#TEEP,nTEEP)
return


METHOD btnpegma01 
LOCAL Acli AS ARRAY	
aCLI:=PEGMA01(SELF:SERVER:CLIENTE,zcurini,zcurdir)
IF aCLI[1]=.T.
   SELF:SERVER:CLINOME:=aCLI[2]
ENDIF

METHOD buscanum( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CP","TEEP")	


METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	


METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF oesc:lok
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
//    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF		

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("DESENHO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()

METHOD IMPACP() 
LOCAL oACP AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"ACP.DBF",zCURDIR}
oACP:=USEREDE{aDAD}
IF oACP:nERRO=0	
   oACP:GOTOP()
   oACP:SEEK(SELF:SERVER:ACP)
   IF oACP:FOUND
       SELF:SERVER:PP:=oACP:FIELDGET("PP")
       SELF:SERVER:PPK:=oACP:FIELDGET("PPK")
   ENDIF
   oACP:CLOSE()
ENDIF



METHOD IMPAEP() 
LOCAL oAEP AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"AEP.DBF",zCURDIR}
oAEP:=USEREDE{aDAD}
IF oAEP:nERRO=0
   oAEP:GOTOP()
   IF oAEP:SEEK(SELF:SERVER:AEP)
      SELF:SERVER:CP:=oAEP:FIELDGET("PP")
      SELF:SERVER:CPK:=oAEP:FIELDGET("PPK")
   ENDIF
   oAEP:CLOSE()
ENDIF

METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
