CLASS XINDEXAR INHERIT INDEXAR	

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("QUA",15)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	

METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
CRIANTX({ZCURINI,"AC2.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ACD.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ACDI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ACP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ACPR.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ACPX.DBF",ZCURDIR})
CRIANTX({ZCURINI,"AEPR.DBF",ZCURDIR})
CRIANTX({ZCURINI,"AEPX.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CII.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CIC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CICI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"PAC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RII.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RRL.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RRS.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RRM.DBF",ZCURDIR})
CRIANTX({ZCURINI,"OPAE.DBF",ZCURDIR})
CRIANTX({ZCURINI,"PAEI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"PAEE.DBF",ZCURDIR})
CRIANTX({ZCURINI,"TEEP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"GC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"GCTEMP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"GCTEM.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRTAUM.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()	

END CLASS
PARTIAL CLASS XJAC2 INHERIT JACP

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",4)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"AC2.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:Caption:="Analise Estabilidade de Processo"
SELF:odcfixedtext22:Caption:="CPKA"
SELF:odcfixedtext23:Caption:="CPKB"
SELF:odcfixedtext24:Caption:="CPK"
SELF:odcsc_sigma1:Caption:="CP"
SELF:SHOW()	

END CLASS
CLASS XJACD INHERIT JACD

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",6)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ACD.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ACDI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:USE(oSERVER)
SELF:OSFJACDI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJACDI,#ACD)
SELF:SHOW()

END CLASS
CLASS XJACP INHERIT JACP

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ACP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJCI INHERIT JCI

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",10)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"CII.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:USE(oSERVER)
SELF:OSFJCII:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJCII,#CI)
SELF:SHOW()	

END CLASS
CLASS XJCIC INHERIT JCIC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("QUA",11)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CIC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"CICI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:USE(oSERVER)
SELF:OSFJCICI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJCICI,#DESENHO)
SELF:oSFJCICI:VIEWTABLE()
SELF:SHOW()	



END CLASS
CLASS XJCICIMP INHERIT JCICIMP	

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("QUA",12)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:SHOW()	

END CLASS
CLASS XJCRTAUM INHERIT JCRTAUM

CONSTRUCTOR(oOWNER) 	
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",21)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRTAUM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	
	

END CLASS
CLASS XJGC INHERIT JGC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",13)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"GC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJOPAE INHERIT JOPAE

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("QUA",16)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OPAE.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"OPAI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJOPAI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJOPAI,#OPAE)
SELF:oSFJOPAI:VIEWTABLE()
SELF:SHOW()	


END CLASS
CLASS XJPAC INHERIT JPAC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",5)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PAC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	


END CLASS
CLASS XJPAEE INHERIT JPAEE	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",18)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PAEE.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJPAEI INHERIT JPAEI

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",17)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PAEI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
PARTIAL CLASS XJPAI INHERIT JPAI

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("QUA",11)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CIC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"PAEI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:USE(oSERVER)
SELF:OSFJPAEI:USE(oSERVE2)
SELF:SetSelectiveRelation(OSFJPAEI,#DESENHO)
SELF:OSFJPAEI:VIEWTABLE()
SELF:SHOW()	

END CLASS
PARTIAL CLASS XJRI INHERIT JRI

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("QUA",9)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"RII.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJRII:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRII,"RI")
SELF:SHOW()

END CLASS
CLASS XJRIFEC INHERIT JRI

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL oSERVE2 AS USEMANA5
LOCAL aDAD AS ARRAY
LOCAL oJAN AS JMESANO

oJAN:=JMESANO{oOWNER}
oJAN:SHOW()
aDAD:={zCURINI,"RI"+OJAN:cCOMP,zCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF	
aDAD:={zCURINI,"R1I"+OJAN:cCOMP,zCURDIR,aDIR}
oSERVE2:=USEMANA5{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJRII:USE(oSERVE2)
//SELF:OSFJRII:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJRRL INHERIT JRRL

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RRL.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
PARTIAL CLASS XJRRS INHERIT JRRS

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RRS.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJTEEP INHERIT JTEEP

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("QUA",7)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"TEEP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	


END CLASS
