PARTIAL CLASS jpcorte
METHOD ALTERAR( ) 
    SELF:oSFjpcortei:SERVER:Commit()	
	SELF:oSFJPCORTEI:ViewForm()

METHOD ANTERIOR 
//SELF:oSFJPCORTEI:Browser:SuspendUpdate()
IF SELF:oSFJPCORTEI:Server:bof
   SELF:oSFJPCORTEI:SkipPrevious()
ENDIF
//SELF:oSFJPCORTEI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nNUMERO AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:FIELDGET("NUMERO")
nNUMERO++
SUPER:append()
SELF:SERVER:FIELDPUT("NUMERO",nNUMERO)
SELF:SERVER:FIELDPUT("DATA",Today())
RETURN SELF

METHOD atuforlx( ) 
	IMPFOR(.f.)

METHOD AtuLogixMu( ) 
	IMPCOD(3,3,.f.)

METHOD buscaov( ) 
	SELF:KeyFind()

METHOD cmdAnual( ) 
	SELF:server:FIELDPUT("LANCADO",SIMNAO(SELF:SERVER:FIELDGET("lancado")))		

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
   SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
//	alert("imprimir")
   SELF:SERVER:COMMIT()
   SELF:oSFjpcortei:SERVER:Commit()	
   SELF:XWRPTGRP("PE","PC")	

METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
   SELF:oSFJPCORTEI:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJPCORTEI:SERVER:gotop()
   WHILE ! SELF:oSFJPCORTEI:SERVER:eof
	 	SELF:oSFJPCORTEI:SERVER:delete()
	 	SELF:oSFJPCORTEI:SERVER:skip()	
      ENDDO
	SELF:oSFJPCORTEI:SERVER:resetnotification()
	SELF:oSFJPCORTEI:SERVER:notify(notifyfilechange)
	SELF:server:delete()
	SELF:server:unlock()
	IF ! SELF:SERVER:BOF
	   SELF:SERVER:Skip(-1)
	ENDIF
ENDIF		

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MU01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
    SELF:pegcod()
ENDIF			

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MB01.DBF"}
oESC:SHOW()	
IF Oesc:LOK
    SELF:SERVER:FIELDPUT("NFORN",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("MFORN",oESC:NOME)
ENDIF

METHOD escforU( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MB01.DBF"}
oESC:SHOW()	
IF Oesc:LOK
    SELF:SERVER:FIELDPUT("NFORNU",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("MFORNU",oESC:NOME)
ENDIF

METHOD escMP( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MU01.DBF"}
oESC:SHOW()	
IF OESC:LOK
	SELF:CODIGOTMP:=OESC:CODIGO
	SELF:DESCRICAOTMP:=OESC:NOME
	SELF:pegcod1()
ENDIF			

METHOD EXCLUIR 
IF  MDG("Apagar Registro") .AND. SELF:oSFJPCORTEI:server:LockCurrentRecord()
    SELF:oSFJPCORTEI:SERVER:SUSPENDNOTIFICATION()	
    SELF:oSFJPCORTEI:server:delete()
    SELF:oSFJPCORTEI:server:unlock()
	SELF:oSFJPCORTEI:SERVER:resetnotification()
	SELF:oSFJPCORTEI:SERVER:notify(notifyFILECHANGE)
    SELF:oSFJPCORTEI:server:GOTOP()		
	WHILE ! SELF:oSFJPCORTEI:serveR:EOf
		SELF:oSFJPCORTEI:server:Skip()
    ENDDO		
    SELF:oSFJPCORTEI:server:GOTOP()
ENDIF

METHOD NOVO() 
LOCAL NNUMERO AS DWORD
NNUMERO:=SELF:SERVER:FIELDGET("NUMERO")
SELF:oSFJPCORTEI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJPCORTEI:SERVER:APPEND()
SELF:oSFJPCORTEI:SERVER:FIELDPUT("NUMERO",nNUMERO)
SELF:oSFJPCORTEI:SERVER:commit()
SELF:oSFJPCORTEI:SERVER:resetnotification()
SELF:oSFJPCORTEI:SERVER:notify(notifyFILECHANGE)

METHOD PEGAR( ) 
LOCAL nCOMPED AS DWORD
LOCAL nCOMITE AS WORD
LOCAL AFORN AS ARRAY
LOCAL oConn AS SQLConnection
LOCAL oREG AS SQLSelect
LOCAL cSQL AS STRING
LOCAL oStmt AS SQLStatement

nCOMPED:=SELF:PEPED
nCOMITE:=SELF:PEITE

IF nCOMPED=0 .OR. nCOMITE=0
   alert("AR ou Item nao Podem ser zero")
   RETU	
ENDIF
AltD()
oConn := SQLConnection{}
IF ! oConn:connect("ol_logix","","")
   alert("Erro na Conecção")
   RETU
ENDIF	

cSQL:= "set isolation to dirty read"
oStmt := SQLStatement{cSQL,oConn}
oSTMT:Execute()

CSQL:=" SELECT * "
CSQL+=" FROM aviso_rec "
csql+=" where num_aviso_rec=" +Trim(Str(NCOMPED))  +" AND num_seq="+  Trim(Str(NCOMITE))


Oreg:= SQLSelect{cSQL,oconn}
IF ! oREG:EOF
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("CODIGO",oREG:FIELDGET("cod_item"))
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("DESCRICAO",oREG:FIELDGET("den_item"))
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("COMPRAS",nCOMPED)
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("COMITEM",nCOMITE)
ENDIF	
oREG:CLOSE()
aFORN:=PEGMU01(SELF:oSFJPCORTEI:SERVER:FIELDGET("CODIGO"),ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("APLICACAO",aFORN[3])
ENDIF	

METHOD PEGARA( ) 
	SELF:pegARPRI(1)

METHOD PEGARF( ) 
	SELF:pegARPRI(3)     //tras ar


METHOD PEGARPRI(nORDEM) 
LOCAL oConn AS SQLConnection
LOCAL oREG AS SQLSelect
LOCAL cSQL AS STRING
LOCAL nFORN AS DWORD
LOCAL cCGC AS STRING
LOCAL aDAD AS ARRAY
LOCAL oMB01 AS USEMANA5
LOCAL oStmt AS SQLStatement

oConn := SQLConnection{}
IF ! oConn:connect("ol_logix","","")
   alert("Erro na Conecção")
  RETU
ENDIF	

cSQL:= "set isolation to dirty read"
oStmt := SQLStatement{cSQL,oConn}
oSTMT:Execute()

IF nORDEM<4
	CSQL:=" SELECT aviso_rec.*, "
	CSQL+=" nf_sup.num_nf, nf_sup.cod_fornecedor "
	CSQL+=" ,fornecedor.raz_social,cnpjcpf(fornecedor.num_cgc_cpf) AS cgc"
	CSQL+=" FROM "
	CSQL+=" aviso_rec INNER JOIN nf_sup ON aviso_rec.num_aviso_rec = nf_sup.num_aviso_rec "
	CSQL+=" LEFT JOIN fornecedor ON nf_sup.cod_fornecedor=fornecedor.cod_fornecedor "
	
	DO CASE
	   CASE nORDEM=1 //busca crm
	     csql+=" where aviso_rec.num_aviso_rec=" +Trim(Str(SELF:SERVER:FIELDGET("CRM")))  +" AND aviso_rec.num_seq="+  Trim(Str(SELF:SERVER:FIELDGET("CRMITEM")))
	   CASE nORDEM=2 //busca rastro
	 	 csql+=" where aviso_rec.NUM_LOTE='"+Trim(SELF:SERVER:FIELDGET("RASTRO"))+ "'"
	   CASE nORDEM=3 //busca nf
		 csql+=" where nf_sup.num_nf=" +Trim(Str(SELF:SERVER:FIELDGET("NFUSINA")))
		 csql+=" AND aviso_rec.num_seq="+Trim(Str(SELF:CRMITEMU))
		 SELF:CRMITEM:=SELF:CRMITEMU
	ENDCASE
ELSE
   DO CASE
   	  CASE nORDEM=4
   	  	   cSQL:="SELECT fornecedor.raz_social,cnpjcpf(fornecedor.num_cgc_cpf) AS cgc from fornecedor where cod_fornecedor= '"+Trim(SELF:SERVER:FIELDGET("LXFORNU"))+"'"
   	  CASE nORDEM=5
   	  	   cSQL:="SELECT fornecedor.raz_social,cnpjcpf(fornecedor.num_cgc_cpf) AS cgc from fornecedor where cod_fornecedor= '"+Trim(SELF:SERVER:FIELDGET("LXFORNC"))+"'"
   END CASE
ENDIF
	

cCGC:=""
Oreg:= SQLSelect{cSQL,oconn}
AltD()
IF ! oREG:EOF
   DO CASE	
     CASE nORDEM=1 //busca ar/seq grava rastro e NF
     	  SELF:SERVER:FIELDPUT("RASTRO",oREG:FIELDGET("NUM_LOTE"))
    	  SELF:SERVER:FIELDPUT("NFUSINA",oREG:FIELDGET("num_nf"))
    	  SELF:SERVER:FIELDPUT("CRMTIPO","A")
    	  SELF:SERVER:FIELDPUT("LXFORNU",oREG:FIELDGET("cod_fornecedor"))
     CASE nORDEM=2 //busca rastro lote grava ar/seq e nf
    	  SELF:SERVER:FIELDPUT("CRM",oREG:FIELDGET("num_aviso_rec"))
      	  SELF:SERVER:FIELDPUT("CRMITEM",oREG:FIELDGET("num_seq"))
    	  SELF:SERVER:FIELDPUT("NFUSINA",oREG:FIELDGET("num_nf"))
      	  SELF:SERVER:FIELDPUT("CRMTIPO","R")
	      SELF:SERVER:FIELDPUT("LXFORNU",oREG:FIELDGET("cod_fornecedor"))
     CASE nORDEM=3 //busca nf grava ar/seq rastro
   	  	  SELF:SERVER:FIELDPUT("CRM",oREG:FIELDGET("num_aviso_rec"))
	  	  SELF:SERVER:FIELDPUT("CRMITEM",SELF:CRMITEMU)
     	  SELF:SERVER:FIELDPUT("RASTRO",oREG:FIELDGET("NUM_LOTE"))
     	  SELF:SERVER:FIELDPUT("LXFORNU",oREG:FIELDGET("cod_fornecedor"))
     	  SELF:SERVER:FIELDPUT("CRMTIPO","N")
   ENDCASE

   IF nORDEM<4
	   SELF:SERVER:FIELDPUT("CODIGO",oREG:FIELDGET("cod_item"))
   ENDIF
   IF nORDEM<5
	   IF Empty(SELF:server:FIELDGET("MFORNU"))
	  	  SELF:SERVER:FIELDPUT("MFORNU",FIXSTR(oREG:FIELDGET("raz_social")))
	   ENDIF	
   ENDIF
   IF nORDEM=5
	   IF Empty(SELF:server:FIELDGET("MFORN"))
	  	  SELF:SERVER:FIELDPUT("MFORN",FIXSTR(oREG:FIELDGET("raz_social")))
	   ENDIF	

   ENDIF	

   cCGC:=FIXSTR(oREG:FIELDGET("cgc"))

ENDIF
oREG:CLOSE()	


IF Len(cCGC)>0
   aDAD:={zCURINI,"MB01",zCURDIR,aDIR}
   oMB01:=USEMANA5{aDAD}
   IF oMB01:nERRO#0
      RETU SELF
   ENDIF
   oMB01:SETORDER(3) //CGC
   nFORN:=0
   oMB01:GOTOP()
   IF oMB01:SEEK(cCGC)
   	  IF nORDEM<5
	      SELF:SERVER:FIELDPUT("NFORNU",oMB01:FIELDGET("NUMERO"))	
	      IF Empty(SELF:server:FIELDGET("MFORNU"))
	         SELF:SERVER:FIELDPUT("MFORNU",oMB01:FIELDGET("NOME"))
	      ENDIF
	  ENDIF
	  IF nORDEM=5
	      SELF:SERVER:FIELDPUT("NFORN",oMB01:FIELDGET("NUMERO"))	
	      IF Empty(SELF:server:FIELDGET("MFORN"))
	         SELF:SERVER:FIELDPUT("MFORN",oMB01:FIELDGET("NOME"))
	      ENDIF
	  ENDIF
   ENDIF
   oMB01:CLOSE()
ENDIF

IF nORDEM<5
  SELF:Peglxdiz( ) //pega codigo logix
ENDIF
//SELF:pegcod()


METHOD PEGARR( ) 
	SELF:PEGARPRI(2)

METHOD pegcod( ) 
LOCAL aFORN AS ARRAY	
aFORN:=PEGMU01(SELF:SERVER:FIELDGET("CODIGO"),ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:FIELDPUT("DESCRICAO",aFORN[2])
ENDIF	

METHOD pegcod1( ) 
LOCAL aFORN AS ARRAY	
aFORN:=PEGMU01(SELF:CODIGOTMP,ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:DESCRICAOTMP:=aFORN[2]
   SELF:APLICACAOTMP:=aFORN[3]
ENDIF		

METHOD PEGCRM(nORDEM,eBUSCA) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF	
oSERVER:SetOrder(nORDEM)
IF oSERVER:SEEK(eBUSCA)
   DO CASE	
     CASE nORDEM=1 //busca crm grava rastro e NF
     	  SELF:SERVER:FIELDPUT("RASTRO",oSERVER:FIELDGET("RASTRO"))
    	  SELF:SERVER:FIELDPUT("NFUSINA",oSERVER:FIELDGET("NRNOTA"))
     CASE nORDEM=3 //busca rastro grava crm e nf
    	  SELF:SERVER:FIELDPUT("CRM",oSERVER:FIELDGET("CRM"))
    	  SELF:SERVER:FIELDPUT("NFUSINA",oSERVER:FIELDGET("NRNOTA"))
     CASE nORDEM=4 //busca nf grava crm rastro
     	  SELF:SERVER:FIELDPUT("RASTRO",oSERVER:FIELDGET("RASTRO"))
     	  SELF:SERVER:FIELDPUT("CRM",oSERVER:FIELDGET("CRM"))
   ENDCASE
   SELF:SERVER:FIELDPUT("NFORNU",oSERVER:FIELDGET("CLIFOR"))	
   SELF:SERVER:FIELDPUT("MFORNU",oSERVER:FIELDGET("NOMEF"))
   SELF:SERVER:FIELDPUT("CODIGO",oSERVER:FIELDGET("CBUSCA"))	
ENDIF	
oSERVER:CLOSE()
SELF:PEGCOD()


METHOD pegcrmn( ) 
	SELF:pegcrm(1,SELF:SERVER:FIELDGET("CRM"))

METHOD pegcrmn1( ) 
		SELF:PEGRIRM(1,SELF:SERVER:FIELDGET("CRM"))

METHOD pegcrmn2( ) 
   SELF:PEGRIRM(4,SELF:SERVER:FIELDGET("NFUSINA"))

METHOD pegcrmr( ) 
	SELF:pegcrm(3,AllTrim(SELF:SERVER:FIELDGET("RASTRO")))

METHOD pegcrmr1( ) 
	SELF:PEGRIRM(2,AllTrim(SELF:SERVER:FIELDGET("RASTRO")))

METHOD pegcrmr2( ) 
			SELF:pegcrm(4,Str(SELF:SERVER:FIELDGET("USINANF"),8))

METHOD pegfor( ) 
LOCAL aFORN AS ARRAY	
aFORN:=PEGMB01(SELF:SERVER:FIELDGET("NFORN"),ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:FIELDPUT("MFORN",aFORN[2])
   SELF:SERVER:FIELDPUT("AC",aFORN[10])
ENDIF

METHOD pegforU( ) 
LOCAL aFORN AS ARRAY	
aFORN:=PEGMB01(SELF:SERVER:FIELDGET("NFORNU"),ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:FIELDPUT("MFORNU",aFORN[2])
ENDIF	

METHOD Peglxdiz( ) 
LOCAL oConn AS SQLConnection
LOCAL oREG AS SQLSelect
LOCAL cSQL AS STRING
LOCAL oStmt AS SQLStatement

oConn := SQLConnection{}
IF ! oConn:connect("ol_logix","","")
   alert("Erro na Conecção")
   RETU
ENDIF	

cSQL:= "set isolation to dirty read"
oStmt := SQLStatement{cSQL,oConn}
oSTMT:Execute()

CSQL:=" SELECT den_item "
CSQL+=" FROM item "
csql+=" where cod_empresa='01' and cod_item='" +Trim(SELF:SERVER:FIELDGET("CODIGO"))  +"'"


Oreg:= SQLSelect{cSQL,oconn}
IF ! oREG:EOF
   SELF:SERVER:FIELDPUT("DESCRICAO",FIXSTR(oREG:FIELDGET("den_item")))	
ENDIF	
oREG:CLOSE()


METHOD Peglxforc( ) 
//	alert("peglxforc")
		SELF:PEGARPRI(5)

METHOD Peglxforu( ) 
//	alert("peglxforu")
	SELF:PEGARPRI(4)

METHOD pegMP( ) 
SELF:oSFJPCORTEI:SERVER:FIELDPUT("CODIGO",SELF:CODIGOTMP)
SELF:oSFJPCORTEI:SERVER:FIELDPUT("DESCRICAO",SELF:DESCRICAOTMP)
SELF:oSFJPCORTEI:SERVER:FIELDPUT("APLICACAO",SELF:APLICACAOTMP)		

METHOD PEGPED() 
LOCAL oMW01,oMW02 AS USEREDE
LOCAL nERRO  AS WORD
LOCAL aDAD,aFORN AS ARRAY
LOCAL nCOMPED AS DWORD
LOCAL nCOMITE AS WORD
nCOMPED:=SELF:PEPED
nCOMITE:=SELF:PEITE
IF nCOMPED=0 .OR. nCOMITE=0
   alert("Pedido ou Item nao Podem ser zero")
   RETU	
ENDIF
nERRO:=0
aDAD:={zCURINI,"MW01.DBF",zCURDIR}
oMW01:=USEREDE{aDAD}
IF oMW01:nERRO#0
   RETU	
ENDIF	
oMW01:GOTOP()
IF ! oMW01:SEEK(nCOMPED)
   nERRO:=1
ELSE
   IF oMW01:FIELDGET("COMFOR")<>SELF:SERVER:FIELDGET("NFORN")
   	  nERRO:=2
   ENDIF
ENDIF	
oMW01:CLOSE()
IF nERRO=1
   alert("Pedido Nao Encontrado")
   RETU
ENDIF	
IF nERRO=2
   alert("Fornecedor Diferente do Pedido")	
   RETU
ENDIF	
aDAD:={zCURINI,"MW02.DBF",zCURDIR}
oMW02:=USEREDE{aDAD}
IF oMW02:nERRO#0
   RETU	
ENDIF	
oMW02:GOTOP()
IF ! oMW02:SEEK(Str(nCOMPED,8)+Str(nCOMITE,3))
   nERRO:=3
ELSE
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("CODIGO",oMW02:FIELDGET("ITECOD"))
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("DESCRICAO",oMW02:FIELDGET("ITENOM"))
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("COMPRAS",nCOMPED)
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("COMITEM",nCOMITE)
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("PE",oMW02:FIELDGET("PRGENT"))
ENDIF
oMW02:CLOSE()
IF nERRO=3
   alert("Item Pedido Nao Encontrado")
   RETU
ENDIF	
aFORN:=PEGMU01(SELF:oSFJPCORTEI:SERVER:FIELDGET("CODIGO"),ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:oSFJPCORTEI:SERVER:FIELDPUT("APLICACAO",aFORN[3])
ENDIF

METHOD PEGRIRM(nORDEM,eBUSCA) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"RIRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF	
oSERVER:SetOrder(nORDEM)
IF oSERVER:SEEK(eBUSCA)
   DO CASE
      CASE nORDEM=1   //busca rIRM grava rastro e NF
   	       SELF:SERVER:FIELDPUT("RASTRO",oSERVER:FIELDGET("RASTRO"))
   	       SELF:SERVER:FIELDPUT("NFUSINA",oSERVER:FIELDGET("NRNOTA"))
      CASE nORDEM=2    //busca rastro grava RIRM nf
   	        SELF:SERVER:FIELDPUT("CRM",oSERVER:FIELDGET("RIRM"))
            SELF:SERVER:FIELDPUT("NFUSINA",oSERVER:FIELDGET("NRNOTA"))
      CASE nORDEM=4
           SELF:SERVER:FIELDPUT("RASTRO",oSERVER:FIELDGET("RASTRO"))
           SELF:SERVER:FIELDPUT("CRM",oSERVER:FIELDGET("RIRM"))
   ENDCASE
   SELF:SERVER:FIELDPUT("NFORNU",oSERVER:FIELDGET("NFORN"))	
   SELF:SERVER:FIELDPUT("MFORNU",oSERVER:FIELDGET("FORNE"))
   SELF:SERVER:FIELDPUT("CODIGO",oSERVER:FIELDGET("DESENHO"))	
ENDIF	
oSERVER:CLOSE()
SELF:PEGCOD()

METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   SELF:CRMITEM:=1
   SELF:CRMITEMU:=1
	    FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
//SELF:oSFJPCORTEI:Browser:SuspendUpdate()
IF SELF:oSFJPCORTEI:Server:Eof
   SELF:oSFJPCORTEI:SkipNext()
ENDIF
//SELF:oSFJPCORTEI:Browser:RestoreUpdate()

METHOD Tabular( ) 
   SELF:oSFjpcortei:SERVER:Commit()
	SELF:oSFJPCORTEI:viewtable()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFjpcortei:SERVER:Commit()


END CLASS
