PARTIAL CLASS JPRNECT
METHOD Anterior( ) 
IF ! SELF:serveR:Bof
   SELF:server:skip(-1)
ENDIF	

METHOD BuscaCO() 
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Localizar ","Digite o Codigo "}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK("C"+oBUSCA:cBUSCA)
ENDIF

METHOD Buscamp() 
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Localizar ","Digite o Codigo "}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK("M"+oBUSCA:cBUSCA)
ENDIF

METHOD CALC01( ) 
	SELF:CALCULAR(1)

METHOD CALC02( ) 
	SELF:CALCULAR(2)

METHOD CALC03( ) 
	SELF:CALCULAR(3)

METHOD CALC04( ) 
	SELF:CALCULAR(4)

METHOD CALC05( ) 
	SELF:CALCULAR(5)

METHOD CALC06( ) 
	SELF:CALCULAR(6)

METHOD CALC07( ) 
	SELF:CALCULAR(7)

METHOD CALC08( ) 
	SELF:CALCULAR(8)

METHOD CALC09() 
	SELF:CALCULAR(9)

METHOD CALC10( ) 
	SELF:CALCULAR(10)

METHOD CALC11( ) 
	SELF:CALCULAR(11)

METHOD CALC12( ) 
	SELF:CALCULAR(12)

METHOD CALC13( ) 
	SELF:CALCULAR(13)

METHOD CALC14( ) 
	SELF:CALCULAR(14)

METHOD CALC15( ) 
	SELF:CALCULAR(15)

METHOD CALC16( ) 
	SELF:CALCULAR(16)

METHOD CALC17( ) 
	SELF:CALCULAR(17)

METHOD CALC18( ) 
	SELF:CALCULAR(18)

METHOD CALC19( ) 
	SELF:CALCULAR(19)

METHOD CALC20( ) 
	SELF:CALCULAR(20)

METHOD CALCULAR(nSEN) 	
LOCAL X AS DWORD
LOCAL nPARC,nQTDE AS FLOAT
LOCAL cVAR AS STRING
nQTDE:=SELF:SERVER:FIELDGET("QTDINI")
FOR X:=1 TO 20
	cVAR:="QTDI"+StrZero(X,2)
    SELF:SERVER:FIELDPUT(cVAR,0)
NEXT X
FOR X:=1 TO nSEN
   nPARC:=CALCNEC(nQTDE/(nSEN+1-X))	
   cVAR:="QTDI"+StrZero(X,2)
   SELF:SERVER:FIELDPUT(cVAR,nPARC)
   nQTDE-=nPARC
NEXT X	
SELF:DIASPRG(nSEN)	

	
	
	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("PE","PE")	

METHOD dias( ) 
LOCAL nDIAS AS FLOAT
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Digite qtde Dias ","Digite Informação"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU
ENDIF	
ndias:=INT(Val(oBUSCA:cBUSCA))
IF nDIAS>0
   SELF:SERVER:FIELDPUT("DIASPR",nDIAS)
   SELF:DIASPRG(SELF:SERVER:FIELDGET("SEMANAS"))
ELSE
   alert("Dias Precisa ser maior que 0")
ENDIF

METHOD diasprg(nSEM) 
LOCAL nPOS,nPOSGRV,X,nDINT AS DWORD
LOCAL nQTDE AS FLOAT
LOCAL dDATA AS DATE
LOCAL cVAR AS STRING
nPOS:=nSEM
nPOSGRV:=1
nDINT:=SELF:SERVER:FIELDGET("DIASPR")
nQTDE:=SELF:SERVER:FIELDGET("QTDSAL")
FOR X:=1 TO 20
    cVAR:="QTDT"+StrZero(X,2)
    nQTDE-=SELF:SERVER:FIELDGET(cVAR)		
    IF nPOS>0 .AND. nQTDE<0
       cVAR:="DATA"+StrZero(X,2)
       dDATA:=SELF:SERVER:FIELDGET(cVAR)	
       dDATA:=dDATA-ndINT
       IF DoW(dDATA)=1 //Domingo
          dDATA--	
       ENDIF	
       IF DoW(dDATA)=7 //Sabado
    	  dDATA-=2
       ENDIF	
       cVAR:="QTDI"+StrZero(nPOSGRV,2)
       nQTDE+=SELF:SERVER:FIELDGET(cVAR)	
       cVAR:="DATR"+StrZero(nPOSGRV,2)
       SELF:server:FIELDPUT(cVAR,dDATA)	
       nPOS--
       nPOSGRV++
    ENDIF
NEXT X	

METHOD ESTOQUE() 
LOCAL oBUSCA AS XBUSCA
LOCAL nESTOQUE AS FLOAT
oBUSCA:=XBUSCA{SELF,"Digite o Estoque ","Digite o Estoque "}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
	nESTOQUE:=INT(Val(oBUSCA:cBUSCA))
	IF nESTOQUE>0 .OR. MDG("Zerar o Estoque")
  	   SELF:SERVER:FIELDPUT("QTDEST",nESTOQUE)
  	ENDIF
ENDIF	
SELF:RECALC()

METHOD ESTPROC() 
LOCAL oBUSCA AS XBUSCA
LOCAL nESTOQUE AS FLOAT
oBUSCA:=XBUSCA{SELF,"Digite o Estoque Processo","Digite o Estoque Processo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
	nESTOQUE:=INT(Val(oBUSCA:cBUSCA))
	IF nESTOQUE>0 .OR. MDG("Zerar o Estoque")
 	   SELF:SERVER:FIELDPUT("QTDPRO",nESTOQUE)
 	ENDIF
ENDIF	
SELF:RECALC()

METHOD imprimir( ) 
SELF:XWRPTGRP("PE","")			


METHOD PegEstq( ) 
	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	    FabCenterWindow( SELF )
 RETURN SELF

METHOD Proximo( ) 
IF ! SELF:serveR:eof
   SELF:server:skip()
ENDIF		

METHOD RECALC() 
LOCAL nESTOQUE,nITEM AS FLOAT
LOCAL cVAR AS STRING
LOCAL X AS DWORD
nESTOQUE:=SELF:SERVER:FIELDGET("QTDEST")	
nESTOQUE+=SELF:SERVER:FIELDGET("QTDPRO")
SELF:SERVER:FIELDPUT("QTDSAL",nESTOQUE)	
nESTOQUE:=SELF:SERVER:FIELDGET("QTDTOT")
nESTOQUE-=SELF:SERVER:FIELDGET("QTDSAL")
SELF:SERVER:FIELDPUT("QTDINI",nESTOQUE)	
nESTOQUE:=SELF:SERVER:FIELDGET("QTDSAL")
FOR X:=1 TO 20
    cVAR:="QTDT"+StrZero(X,2)
    nITEM:=SELF:SERVER:FIELDGET(cVAR)
	cVAR:="QTDI"+StrZero(X,2)
	IF nESTOQUE>0
       IF nESTOQUE>nITEM
          nESTOQUE-=nITEM
          nITEM:=CALCNEC(nITEM)
       ELSE
          nITEM:=nITEM-nESTOQUE
          nESTOQUE:=0
          nITEM:=CALCNEC(nITEM)
       ENDIF
    ELSE
       nITEM:=CALCNEC(nITEM)
    ENDIF
    SELF:SERVER:FIELDPUT(cVAR,nITEM)	
NEXT X	

METHOD sair( ) 
	SELF:EndWindow()

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
