CLASS XIMPLXOP01 INHERIT implxop01

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
SUPER(oOWNER)
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:D01:=DToC(dDATA)
SELF:D02:=DToC(dDATA+7)
SELF:D03:=DToC(dDATA+14)
SELF:SHOW()

END CLASS
CLASS XINDEXAR INHERIT INDEXAR

CONSTRUCTOR(oOWNER) 
IF ! entramenu("PCP",90)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()		
	

METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
 CRIANTX({ZCURINI,"OSCRT.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRG.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRG.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRA.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRH.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRI.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRB.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRS.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRR.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"OSPRO.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"PRNEC.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"PRNECA.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"PRNECI.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"PRNECT.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"PCORTE.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"PCORTEI.DBF",ZCURDIR})
 CRIANTX({ZCURINI,"ESTQINT.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()

END CLASS
CLASS XJESTQINT INHERIT Jestqint

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",12)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ESTQINT.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
PARTIAL CLASS XJIMPDEL INHERIT JIMPEDI	

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:CAMINHO:=PEGINIVAL(ZCURINI,"DELFOR","CAMINHO")+"Progentr."
SELF:Caption:="DELFOR"
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+147)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCDIMPF:DISABLE()
SELF:ODCDIMPI:Disable()
SELF:oDCsemordem:DISABLE()
SELF:oDCsqllogix:Disable()
SELF:oDCsqlserver:Disable()
SELF:oDCsemana:Disable()
SELF:OCCACUSEMANA:Disable()
SELF:oDCchkstk:DISABLE()
SELF:SHOW()						
	


END CLASS
PARTIAL CLASS XJIMPEDD INHERIT JIMPEDI

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:Caption:="Diaria"
SELF:CAMINHO:=PEGINIVAL(ZCURINI,"CD049.DBF","CAMINHO")+"CD049.DBF"
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+6)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCsqllogix:Disable()
//SELF:oDCsemana:Disable()
//SELF:oCCAcuSemana:Disable()
SELF:oDCchklog:ENABLE()
SELF:semana:=20
//SELF:oDCchkstk:DISABLE()
SELF:SHOW()						

END CLASS
PARTIAL CLASS XJIMPEDM INHERIT JIMPEDI	

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:CAMINHO:=PEGINIVAL(ZCURINI,"CD111.DBF","CAMINHO")+"CD111.DBF"
SELF:Caption:="Semanal"
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+147)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCsqllogix:Disable()
SELF:oDCchklog:ENABLE()
SELF:oDCsemana:Disable()
SELF:oCCAcuSemana:Disable()
SELF:semana:=0
SELF:SHOW()					

END CLASS
PARTIAL CLASS XJIMPELE INHERIT JIMPEDI		

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:CAPTION:="Elec XLS/DBF"
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
SELF:SEMANA:=20
SELF:CAMINHO:=PEGINIVAL(ZCURINI,"ELECTROLUX","CAMINHO")
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+147)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCsqllogix:Disable()
SELF:oDCsqlserver:Disable()
SELF:oDCDIMPF:DISABLE()
SELF:ODCDIMPI:Disable()
SELF:oDCchkstk:DISABLE()
SELF:SHOW()					
	

END CLASS
PARTIAL CLASS XJIMPLOG INHERIT JIMPEDI

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:CAPTION:="Integrado"
SELF:CAMINHO:=""
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+20)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCsemordem:DISABLE()
SELF:oDCsqlserver:Disable()
SELF:oDCDIMPF:DISABLE()
SELF:ODCDIMPI:Disable()
SELF:oDCcaminho:Disable()
SELF:oCCcmdescarq:Disable()
SELF:sqllogix:=.T.
SELF:ODCSQLlogix:DISABLE()
SELF:oDCsemana:Disable()
SELF:OCCACUSEMANA:Disable()
SELF:oDCchkstk:DISABLE()
SELF:SHOW()					

END CLASS
PARTIAL CLASS XJIMPORD INHERIT JIMPEDI		

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:CAMINHO:=PEGINIVAL(ZCURINI,"ORDERS","CAMINHO")+"Pedido."
SELF:caption:="Orders"
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+6)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCDIMPF:DISABLE()
SELF:ODCDIMPI:Disable()
SELF:oDCsemordem:DISABLE()
SELF:oDCsqllogix:Disable()
SELF:oDCsqlserver:Disable()
SELF:oDCsemana:Disable()
SELF:OCCACUSEMANA:Disable()
SELF:oDCchkstk:DISABLE()
SELF:SHOW()						
	

END CLASS
CLASS XJNECINI INHERIT 	JNECINI

CONSTRUCTOR(oOWNER) 
//LOCAL oSERVER AS USEREDE
//LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",6)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:oDCimpsem:VALUE:=.T.
SELF:ODCIMPOS:VALUE:=.T.
SELF:ODCIMPOPSAL:VALUE:=.T.
SELF:ODCIMPavulso:VALUE:=.T.
SELF:oDCSemanas:Value:="20"
SELF:SHOW()

END CLASS
CLASS XJOS2 INHERIT JOSP	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",4)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OSPR2.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
CLASS XJOSC INHERIT JOSC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OSCRT.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()


END CLASS
CLASS XJOSELE INHERIT JOSP	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OSPRH.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()


END CLASS
CLASS XJOSELS INHERIT JOSP		

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OSPRI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()



END CLASS
CLASS XJOSLXD INHERIT JOSP	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OSPRS.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()


END CLASS
CLASS XJOSLXS INHERIT JOSP		

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OSPRR.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
CLASS XJOSP INHERIT JOSP	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OSPRG.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
CLASS XJPCORTE INHERIT JPCORTE

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PCORTE.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"PCORTEI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
   oSERVER:CLOSE()
   RETU SELF
ENDIF

SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJPCORTEI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJPCORTEI,"NUMERO")
SELF:oSFJPCORTEI:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJPCORTEI:viewtable()
SELF:SHOW()		
	

END CLASS
CLASS XJPE INHERIT JPE

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",9)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PE.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"PE01.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"PRNECT.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
   RETU SELF
ENDIF
oSERVE2:SetOrder(2)
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJPE01:USE(oSERVE2)
SELF:SetSelectiveRelation(OSFJPE01,"PEDIDO")
SELF:OSFJPE01:Browser:SetStandardStyLe(gBsreadonly)
SELF:oSFJPE01:VIEWTABLE()
SELF:oSFJNEC:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJNEC,"TIPPED+CODIGO")
SELF:oSFJNEC:VIEWFORM()
SELF:SHOW()		

END CLASS
CLASS XJPRNEC INHERIT JPRNEC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",7)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PRNEC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"PRNECI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
   oSERVER:CLOSE()
   RETU SELF
ENDIF

SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJPRNECI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJPRNECI,"CODIGO")
SELF:oSFJPRNECI:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJPRNECI:viewtable()
SELF:SHOW()	


END CLASS
CLASS XJPRNECA INHERIT JPRNECA	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",10)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PRNECA.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJPRNECT INHERIT JPRNECT

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",8)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PRNECT.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:SHOW()	

END CLASS
PARTIAL CLASS XPDGMB INHERIT JIMPEDI		

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:CAPTION:="Diaria TXT"
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
SELF:CAMINHO:=PEGINIVAL(ZCURINI,"PDGMB","CAMINHO")
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+6)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCsemordem:DISABLE()
SELF:oDCsqllogix:Disable()
SELF:oDCsqlserver:Disable()
//SELF:oDCsemana:Disable()
//SELF:OCCACUSEMANA:Disable()
SELF:semana:=20
SELF:oDCchkstk:DISABLE()
SELF:SHOW()						

END CLASS
PARTIAL CLASS XPMGMB INHERIT JIMPEDI			

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:CAPTION:="Semanal TXT"
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
SELF:CAMINHO:=PEGINIVAL(ZCURINI,"PMGMB","CAMINHO")
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+147)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCsemordem:DISABLE()
SELF:oDCsqllogix:Disable()
SELF:oDCsqlserver:Disable()
//SELF:oDCsemana:Disable()
SELF:OCCACUSEMANA:Disable()
SELF:oDCchkstk:DISABLE()
SELF:semana:=20
SELF:SHOW()					

END CLASS
PARTIAL CLASS XTXTELEDIR INHERIT JIMPEDI			

CONSTRUCTOR(oOWNER) 
LOCAL dDATA AS DATE	
IF ! entramenu("PCP",5)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:CAPTION:="Diaria ELE-TXT"
SELF:ateplanta:=Repl("Z",12)
SELF:ApagarANT:=.T.
SELF:Ponto:=.T.
SELF:CAMINHO:=PEGINIVAL(ZCURINI,"PDGMB","CAMINHO")
dDATA:=Today()
WHILE DoW(dDATA)#2
  dDATA--
ENDDO	
SELF:DINI:=DToC(dDATA)
SELF:DFIM:=DToC(dDATA+6)
SELF:DIMPI:=DToC(dDATA-1)
SELF:DIMPF:=DToC(dDATA)
SELF:oDCsemordem:DISABLE()
SELF:oDCsqllogix:Disable()
SELF:oDCsqlserver:Disable()
//SELF:oDCsemana:Disable()
//SELF:OCCACUSEMANA:Disable()
SELF:oDCchklog:DISABLE()
SELF:semana:=20
SELF:oDCchkstk:DISABLE()
SELF:oCCExportar:Disable()
SELF:SHOW()						

END CLASS
CLASS ZJPRO INHERIT XJPRO	
CONSTRUCTOR(oOWNER) 
//LOCAL oSERVER AS USEREDE
//LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",11)
	RETU SELF
ENDIF	
SUPER(oOWNER,"",zcurINI,zcurDIR,adir)
SELF:oDCCODIGOINT:ENABLE()
SELF:oCCcmdesccom:DISABLE()
SELF:oCCcmdesccom1:DISABLE()
SELF:oCCcmdesccom2:DISABLE()
SELF:SHOW()			


END CLASS
