PARTIAL CLASS JRRS
METHOD APPEND() 
LOCAL nRRS AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nRRS:=SELF:Server:FIELDGET("RRS")
nRRS++
SUPER:append()
SELF:SERVER:FIELDPUT("RRS",nRRS)
SELF:server:FIELDPUT("data",Today())
SELF:server:FIELDPUT("K01",0.8862)
SELF:server:FIELDPUT("K02",0.7071)
SELF:server:FIELDPUT("K03",0.4030)
RETURN .T.

METHOD ASSINAR() 
LOCAL oBUSCA AS XBUSCA
LOCAL dDATA AS DATE
LOCAL aCAMPOS AS ARRAY
LOCAL aDIZ AS ARRAY
LOCAL X AS WORD
aCAMPOS:={"CLIENTE","CLINOME","DESENHO","DESCRI","DESCII","CARAC","ESPEC","AVA","AVAN","AVB","AVBN"}
aDIZ:={"Nº Cliente","Nome Cliente","DESENHO","Descriçao Desenho","Descriçao Ins","Caracteristica","Espeçie",;
       "Nome Aval A","Nº Aval A","Nome Aval B","Nº Aval B"}
FOR X:=1 TO 11
	IF Empty(SELF:SERVER:FIELDGET(aCAMPOs[X]))
	   IF ! MDG("Campo "+Adiz[x]+"Não Preenchido - Continuar")
	      RETURN .F.
	   ENDIF
	ENDIF	
NEXT


IF ! Empty(SELF:SERVER:FIELDGET("DATASS"))
   alert("Ja Assinada")
   RETURN .F.
ENDIF
oBUSCA:=XBUSCA{SELF,"Informe a Data","Digite Data",DToC(Today())}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETURN .F.
ENDIF
dDATA:=CToD(oBUSCA:cBUSCA)
IF ! IsDate(dDATA)
   RETU .F.
ENDIF
SELF:SERVER:FIELDPUT("NUMASS",ZFOLHA)
SELF:SERVER:FIELDPUT("NOMASS",ZNOMEFOLHA)
SELF:SERVER:FIELDPUT("DATASS",dDATA)


METHOD buscanum( ) 
	SELF:KeyFind()

METHOD calcular() 

LOCAL nVAL AS FLOAT
LOCAL nVAL2 AS FLOAT
LOCAL nVAL3 AS FLOAT
LOCAL nVAL4 AS FLOAT
LOCAL nVAL5 AS FLOAT

SELF:SERVER:TOTAA:=0
SELF:SERVER:TOTAB:=0
SELF:SERVER:TOTBA:=0
SELF:SERVER:TOTBB:=0
SELF:SERVER:MEDAA:=0
SELF:SERVER:MEDBB:=0
SELF:SERVER:TOTALA:=0
SELF:SERVER:TOTALB:=0
SELF:SERVER:MEDIA:=0
SELF:SERVER:MEDIB:=0
SELF:SERVER:MEDSOM:=0
SELF:SERVER:MEDMED:=0
SELF:SERVER:DIFMED:=0
SELF:SERVER:VE:=0
SELF:SERVER:VA:=0
SELF:SERVER:VP:=0
SELF:SERVER:VT:=0
SELF:SERVER:RR:=0
SELF:SERVER:PRR:=0
nVAL:=0
nVAL :=SELF:SERVER:AMA01
nVAL+=SELF:SERVER:AMA02
nVAL+=SELF:SERVER:AMA03
nVAL+=SELF:SERVER:AMA04
nVAL+=SELF:SERVER:AMA05
SELF:SERVER:TOTAA:=nVAL
nVAL:=0
nVAL :=SELF:SERVER:AMAA01
nVAL+=SELF:SERVER:AMAA02
nVAL+=SELF:SERVER:AMAA03
nVAL+=SELF:SERVER:AMAA04
nVAL+=SELF:SERVER:AMAA05
SELF:SERVER:TOTAB:=nVAL

nVAL:=0
nVAL :=SELF:SERVER:AMB01
nVAL+=SELF:SERVER:AMB02
nVAL+=SELF:SERVER:AMB03
nVAL+=SELF:SERVER:AMB04
nVAL+=SELF:SERVER:AMB05
SELF:SERVER:TOTBA:=nVAL
nVAL:=0
nVAL :=SELF:SERVER:AMBB01
nVAL+=SELF:SERVER:AMBB02
nVAL+=SELF:SERVER:AMBB03
nVAL+=SELF:SERVER:AMBB04
nVAL+=SELF:SERVER:AMBB05
SELF:SERVER:TOTBB:=nVAL
nVAL:=(SELF:SERVER:TOTAA+SELF:SERVER:TOTAB)
SELF:SERVER:TOTALA:=nVAL
SELF:SERVER:MEDIA:=(nVAL/10)
nVAL:=(SELF:SERVER:TOTBA+SELF:SERVER:TOTBB)
SELF:SERVER:TOTALB:=nVAL
SELF:SERVER:MEDIB:=(nVAL/10)
SELF:SERVER:DIFA01:=Abs(SELF:SERVER:AMA01-SELF:SERVER:AMAA01)
SELF:SERVER:DIFA02:=Abs(SELF:SERVER:AMA02-SELF:SERVER:AMAA02)
SELF:SERVER:DIFA03:=Abs(SELF:SERVER:AMA03-SELF:SERVER:AMAA03)
SELF:SERVER:DIFA04:=Abs(SELF:SERVER:AMA04-SELF:SERVER:AMAA04)
SELF:SERVER:DIFA05:=Abs(SELF:SERVER:AMA05-SELF:SERVER:AMAA05)
SELF:SERVER:DIFB01:=Abs(SELF:SERVER:AMB01-SELF:SERVER:AMBB01)
SELF:SERVER:DIFB02:=Abs(SELF:SERVER:AMB02-SELF:SERVER:AMBB02)
SELF:SERVER:DIFB03:=Abs(SELF:SERVER:AMB03-SELF:SERVER:AMBB03)
SELF:SERVER:DIFB04:=Abs(SELF:SERVER:AMB04-SELF:SERVER:AMBB04)
SELF:SERVER:DIFB05:=Abs(SELF:SERVER:AMB05-SELF:SERVER:AMBB05)
nVAL:=0
nVAL+=SELF:SERVER:DIFA01
nVAL+=SELF:SERVER:DIFA02
nVAL+=SELF:SERVER:DIFA03
nVAL+=SELF:SERVER:DIFA04
nVAL+=SELF:SERVER:DIFA05
SELF:SERVER:MEDAA:=(nVAL/5)
nVAL:=0
nVAL+=SELF:SERVER:DIFB01
nVAL+=SELF:SERVER:DIFB02
nVAL+=SELF:SERVER:DIFB03
nVAL+=SELF:SERVER:DIFB04
nVAL+=SELF:SERVER:DIFB05
SELF:SERVER:MEDBB:=(nVAL/5)
nVAL:=(SELF:SERVER:MEDAA+SELF:SERVER:MEDBB)
SELF:SERVER:MEDSOM:=nVAL
SELF:SERVER:MEDMED:=(nVAL/2)
nVAL:=Abs(SELF:SERVER:MEDIA-SELF:SERVER:MEDIB)
SELF:SERVER:DIFMED:=nVAL


nVAL:=SELF:SERVER:AMA01
nVAL+=SELF:SERVER:AMAA01
nVAL+=SELF:SERVER:AMB01
nVAL+=SELF:SERVER:AMBB01
nVAL:=nVAL/4
SELF:SERVER:M01:=nVAL

nVAL:=SELF:SERVER:AMA02
nVAL+=SELF:SERVER:AMAA02
nVAL+=SELF:SERVER:AMB02
nVAL+=SELF:SERVER:AMBB02
nVAL:=nVAL/4
SELF:SERVER:M02:=nVAL

nVAL:=SELF:SERVER:AMA03
nVAL+=SELF:SERVER:AMAA03
nVAL+=SELF:SERVER:AMB03
nVAL+=SELF:SERVER:AMBB03
nVAL:=nVAL/4
SELF:SERVER:M03:=nVAL


nVAL:=SELF:SERVER:AMA04
nVAL+=SELF:SERVER:AMAA04
nVAL+=SELF:SERVER:AMB04
nVAL+=SELF:SERVER:AMBB04
nVAL:=nVAL/4
SELF:SERVER:M04:=nVAL

nVAL:=SELF:SERVER:AMA05
nVAL+=SELF:SERVER:AMAA05
nVAL+=SELF:SERVER:AMB05
nVAL+=SELF:SERVER:AMBB05
nVAL:=nVAL/4
SELF:SERVER:M05:=nVAL





nVAL:=SELF:SERVER:M01
nVAL:=IF(SELF:SERVER:M02>nVAL,SELF:SERVER:M02,nVAL)
nVAL:=IF(SELF:SERVER:M03>nVAL,SELF:SERVER:M03,nVAL)
nVAL:=IF(SELF:SERVER:M04>nVAL,SELF:SERVER:M04,nVAL)
nVAL:=IF(SELF:SERVER:M05>nVAL,SELF:SERVER:M05,nVAL)
SELF:SERVER:RPMAX:=nVAL


nVAL:=SELF:SERVER:M01
nVAL:=IF(SELF:SERVER:M02<nVAL,SELF:SERVER:M02,nVAL)
nVAL:=IF(SELF:SERVER:M03<nVAL,SELF:SERVER:M03,nVAL)
nVAL:=IF(SELF:SERVER:M04<nVAL,SELF:SERVER:M04,nVAL)
nVAL:=IF(SELF:SERVER:M05<nVAL,SELF:SERVER:M05,nVAL)
SELF:SERVER:RPMIN:=nVAL

nVAL:=Abs(SELF:SERVER:RPMAX-SELF:SERVER:RPMIN)
SELF:SERVER:RP:=nVAL








//nVAL:=SELF:SERVER:MEDMED*4.56 valido 31/12/2002
//nVAL:=SELF:SERVER:MEDMED*0.8862
nVAL:=SELF:SERVER:MEDMED*SELF:SERVER:FIELDGET("K01")
SELF:SERVER:VE:=nVAL
//nVAL2:=SELF:SERVER:DIFMED*3.65 valido 31/12/2002
//nVAL2:=SELF:SERVER:DIFMED*0.7071
nVAL2:=SELF:SERVER:DIFMED*SELF:SERVER:FIELDGET("K02")
nVAL3:=SELF:SERVER:VE
nVAL4:=(nVAL2*nVAL2)
nVAL5:=(nVAL3*nVAL3)
nVAL5:= FloatFormat(nVAL5 /10,15,9)
nVAL:=SQrt(Abs(nVAL4-nVAL5))
SELF:SERVER:VA:=nVAL

nVAL2:=SELF:SERVER:VE
nVAL3:=SELF:SERVER:VA
nVAL:=SQrt((nVAL2*nVAL2)+( nVAL3*nVAL3) )
SELF:SERVER:RR:=nVAL


//nVAL:=SELF:SERVER:RP*2.08 31/12/2002
//nVAL:=SELF:SERVER:RP*0.4030
nVAL:=SELF:SERVER:RP*SELF:SERVER:FIELDGET("K03")
SELF:SERVER:VP:=nVAL

nVAL2:=SELF:SERVER:RR
nVAL3:=SELF:SERVER:VP
nVAL:=SQrt((nVAL2*nVAL2)+( nVAL3*nVAL3) )
SELF:SERVER:VT:=nVAL
IF nVAL>0  //'Evitar Divisao por zero
   nVAL:=SELF:SERVER:RR/nVAL*100
ELSE
   nVAL:=0
ENDIF
SELF:sERVER:PRR:=nVAL

SELF:SERVER:FIELDPUT("XMAX",SELF:SERVER:FIELDGET("MEDIA"))
SELF:SERVER:FIELDPUT("XMIN",SELF:SERVER:FIELDGET("MEDIA"))

IF SELF:SERVER:FIELDGET("MEDIB")<SELF:SERVER:FIELDGET("MEDIA")
   SELF:SERVER:FIELDPUT("XMIN",SELF:SERVER:FIELDGET("MEDIB"))	
ENDIF
IF SELF:SERVER:FIELDGET("MEDIB")>SELF:SERVER:FIELDGET("MEDIA")
   SELF:SERVER:FIELDPUT("XMAX",SELF:SERVER:FIELDGET("MEDIB"))	
ENDIF

IF SELF:SERVER:FIELDGET("VT")>(Abs(SELF:SERVER:FIELDGET("TOLMIN"))+Abs(SELF:SERVER:FIELDGET("TOLMAX")))
   alert("VT > Tolerancia")
ENDIF

RETU NIL

METHOD cmdChecar( ) 
SELF:gotop()
WHILE ! SELF:SERVER:Eof
   SELF:pegavA()
   SELF:PEGAVB()
   SELF:btnPEGMA01()
   SELF:btnPEGMS01()	
   SELF:Skip()
ENDDO
	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD cmdDuplicar( ) 
LOCAL aVAL AS ARRAY
aVAL:={}

AAdd(aVAL,SELF:SERVER:FIELDGET("CLIENTE"))
AAdd(aVAL,SELF:SERVER:FIELDGET("CLINOME"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESENHO"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESCRI"))
AAdd(aVAL,SELF:SERVER:FIELDGET("INSTRU"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESCII"))
AAdd(aVAL,SELF:SERVER:FIELDGET("CARAC"))
AAdd(aVAL,SELF:SERVER:FIELDGET("ESPEC"))
AAdd(aVAL,SELF:SERVER:FIELDGET("TOLMIN"))
AAdd(aVAL,SELF:SERVER:FIELDGET("TOLMAX"))

SELF:APPEND()	

SELF:SERVER:FIELDPUT("CLIENTE",aVAL[1])
SELF:SERVER:FIELDPUT("CLINOME",aVAL[2])
SELF:SERVER:FIELDPUT("DESENHO",aVAL[3])
SELF:SERVER:FIELDPUT("DESCRI",aVAL[4])
SELF:SERVER:FIELDPUT("INSTRU",aVAL[5])
SELF:SERVER:FIELDPUT("DESCII",aVAL[6])
SELF:SERVER:FIELDPUT("CARAC",aVAL[7])
SELF:SERVER:FIELDPUT("ESPEC",aVAL[8])
SELF:SERVER:FIELDPUT("TOLMIN",aVAL[9])
SELF:SERVER:FIELDPUT("TOLMAX",aVAL[10])


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD escava( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("AVAN",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("AVA",oESCMP04:NOME)
ENDIF

METHOD escAVB( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("AVBN",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("AVB",oESCMP04:NOME)
ENDIF

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF		

METHOD escfor 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD fatanov( ) 
SELF:server:FIELDPUT("K01",0.8862)
SELF:server:FIELDPUT("K02",0.7071)
SELF:server:FIELDPUT("K03",0.4030)


METHOD fatant( ) 
SELF:server:FIELDPUT("K01",4.56)
SELF:server:FIELDPUT("K02",3.65)
SELF:server:FIELDPUT("K03",2.08)	

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("DESENHO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .F.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()

METHOD ListBoxSelect( oControlEvent ) 
	LOCAL oControl AS Control
	oControl := IIf( oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control )
	SUPER:ListBoxSelect( oControlEvent )
	//Put your changes here
	DO CASE
	       CASE oCONTROL:NAMESYM==#INSTRU
			 SELF:SERVER:DESCII:=SELF:oDCINSTRU:textvalue	
	ENDCASE
RETURN NIL


METHOD pegavA 
LOCAL ATEC,ACOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:SERVER:AVAN,ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:SERVER:AVA:=aTEC[2]
ENDIF


METHOD pegavB 
LOCAL ATEC,ACOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:SERVER:AVBN,ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:SERVER:AVB:=aTEC[2]
ENDIF

METHOD btnpegma01 
LOCAL Acli AS ARRAY	
aCLI:=PEGMA01(SELF:SERVER:CLIENTE,zcurini,zcurdir)
IF aCLI[1]=.T.
   SELF:SERVER:CLINOME:=aCLI[2]
ENDIF

METHOD btnpegms01 
LOCAL apro AS ARRAY	
aPRO:=PEGMS01(SELF:SERVER:DESENHO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
  SELF:SERVER:FIELDPUT("DESCRI",aPRO[2])
ENDIF

METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	    FabCenterWindow( SELF )
 RETURN SELF

METHOD TABINS 
RETU MTD02("TIPINS",3)

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
