PARTIAL CLASS JCS
METHOD APPEND 
LOCAL nCS AS DWORD
SELF:SERVER:GOTOP()
nCS:=SELF:SERVER:CS
nCS++
SUPER:APPEND()
SELF:SERVER:CS:=nCS
SELF:SERVER:DATA:=Today()
SELF:SERVER:TECNICO:=ZFOLHA
SELF:SERVER:TECNOME:=ZUSER

METHOD busca( ) 
	SELF:KeyFind()
//LOCAL oBUSCA AS XBUSCA
//oBUSCA:=XBUSCA{SELF,"Localizar","Digite o Nº "}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD DELETE 
IF SELF:SERVER:LANCADA
   alert("Correção Já Lançada")	
   RETUrn .f.
ENDIF	
SUPER:Delete()
RETUrn .t.	

METHOD escFER 
LOCAL oESC AS XESCFER
oESC:=XESCFER{SELF,"FERRAM.DBF",1}
oESC:SHOW()	
IF oESC:LOK
	SELF:SERVER:FIELDPUT("FERRAM",oESC:NUMERO)
	SELF:SERVER:FIELDPUT("NOME",oESC:NOME)	
    SELF:SERVER:FIELDPUT("TIPO","F")
ENDIF


METHOD escME01 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"ME01.DBF"}
oESC:SHOW()	
IF oESC:LOK
	SELF:SERVER:FIELDPUT("FERRAM",oESC:NUMERO)
	SELF:SERVER:FIELDPUT("NOME",oESC:NOME)	
    SELF:SERVER:FIELDPUT("TIPO","M")
ENDIF


METHOD GRAVASALDO 
LOCAL aDAD AS ARRAY
LOCAL OFERRAM AS USEREDE	
LOCAL cCODIGO AS STRING
IF SELF:SERVER:FIELDGET("LANCADA")
   alert("Correção Já Lançada")	
   RETUrn .f.
ENDIF	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("FERRAM"))
aDAD:={zCURINI,IF(SELF:SERVER:FIELDGET("TIPO")="F","FERRAM.DBF","ME01.DBF"),zCURDIR}
oFERRAM:=USEREDE{aDAD}
IF oFERRAM:nERRO#0
   alert("Erro ao abrir cadastro de ferramenta/Maquina")
    RETUrn .f.
ENDIF
oFERRAM:GOTOP()
IF !oFERRAM:SEEK(cCODIGO)
    oFERRAM:CLOSE()
    alert("Erro  Ferramenta/Maquina não encontrada")
	RETUrn .f.
ENDIF
oFERRAM:FIELDPUT("QTDEBASE",SELF:SERVER:FIELDGET("QTDEBASE"))     //1
oFERRAM:FIELDPUT("QTDESALDO",SELF:SERVER:FIELDGET("QTDESALDO"))     //1
oFERRAM:FIELDPUT("QTDEPED",SELF:SERVER:FIELDGET("QTDEPED"))       //2
oFERRAM:FIELDPUT("QTDEURG",SELF:SERVER:FIELDGET("QTDEURG"))       //3
oFERRAM:FIELDPUT("DATASALDO",SELF:SERVER:FIELDGET("DATASALDO"))     //4
oFERRAM:FIELDPUT("DATAPED",SELF:SERVER:FIELDGET("DATAPED"))       //5
oFERRAM:FIELDPUT("DATAURG",SELF:SERVER:FIELDGET("DATAURG"))       //6
oFERRAM:FIELDPUT("QTDETOT",SELF:SERVER:FIELDGET("QTDETOT"))	      //7
oFERRAM:FIELDPUT("HRSAL",SELF:SERVER:FIELDGET("HRSAL"))         //8
oFERRAM:FIELDPUT("HRBAS",SELF:SERVER:FIELDGET("HRBAS"))         //8
oFERRAM:FIELDPUT("HRPRE",SELF:SERVER:FIELDGET("HRPRE"))         //9
oFERRAM:FIELDPUT("HRURG",SELF:SERVER:FIELDGET("HRURG"))         //10
oFERRAM:FIELDPUT("HRSAL",SELF:SERVER:FIELDGET("HRSAL"))         //11
oFERRAM:FIELDPUT("DATHPED",SELF:SERVER:FIELDGET("DATHPED"))       //12
oFERRAM:FIELDPUT("DATHURG",SELF:SERVER:FIELDGET("DATHURG"))	      //13
oFERRAM:FIELDPUT("DATHSAL",SELF:SERVER:FIELDGET("DATHSAL"))	      //13
oFERRAM:FIELDPUT("HRTOT",SELF:SERVER:FIELDGET("HRTOT"))	      //14
oFERRAM:CLOSE()
SELF:SERVER:LANCADA:=.T.
SELF:SERVER:LANCDAT:=Today()
SELF:SERVER:LANCUSR:=ZFOLHA	

METHOD PEGASALDO 
LOCAL aDAD AS ARRAY
LOCAL OFERRAM AS USEREDE	
LOCAL cCODIGO AS STRING
IF SELF:SERVER:FIELDGET("LANCADA")
   alert("Correção Já Lançada")	
   RETUrn .f.
ENDIF	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("FERRAM"))
aDAD:={zCURINI,IF(SELF:SERVER:FIELDGET("TIPO")="F","FERRAM.DBF","ME01.DBF"),zCURDIR}
oFERRAM:=USEREDE{aDAD}
IF oFERRAM:nERRO#0
   alert("Erro ao abrir cadastro de ferramenta/Maquina")
    RETUrn .f.
ENDIF
oFERRAM:GOTOP()
IF !oFERRAM:SEEK(cCODIGO)
    oFERRAM:CLOSE()
    alert("Erro  Ferramenta/Maquina não encontrada")
	RETUrn .f.
ENDIF
oFERRAM:FIELDPUT("QTDEBASE",SELF:SERVER:FIELDGET("QTDEBASE"))     //1
oFERRAM:FIELDPUT("QTDESALDO",SELF:SERVER:FIELDGET("QTDESALDO"))     //1
oFERRAM:FIELDPUT("QTDEPED",SELF:SERVER:FIELDGET("QTDEPED"))       //2
oFERRAM:FIELDPUT("QTDEURG",SELF:SERVER:FIELDGET("QTDEURG"))       //3
oFERRAM:FIELDPUT("DATASALDO",SELF:SERVER:FIELDGET("DATASALDO"))     //4
oFERRAM:FIELDPUT("DATAPED",SELF:SERVER:FIELDGET("DATAPED"))       //5
oFERRAM:FIELDPUT("DATAURG",SELF:SERVER:FIELDGET("DATAURG"))       //6
oFERRAM:FIELDPUT("QTDETOT",SELF:SERVER:FIELDGET("QTDETOT"))	      //7
oFERRAM:FIELDPUT("HRSAL",SELF:SERVER:FIELDGET("HRSAL"))         //8
oFERRAM:FIELDPUT("HRBAS",SELF:SERVER:FIELDGET("HRBAS"))         //8
oFERRAM:FIELDPUT("HRPRE",SELF:SERVER:FIELDGET("HRPRE"))         //9
oFERRAM:FIELDPUT("HRURG",SELF:SERVER:FIELDGET("HRURG"))         //10
oFERRAM:FIELDPUT("HRSAL",SELF:SERVER:FIELDGET("HRSAL"))         //11
oFERRAM:FIELDPUT("DATHPED",SELF:SERVER:FIELDGET("DATHPED"))       //12
oFERRAM:FIELDPUT("DATHURG",FERRAM:FIELDGET("DATHURG"))	      //13
oFERRAM:FIELDPUT("DATHSAL",SELF:SERVER:FIELDGET("DATHSAL"))	      //13
oFERRAM:FIELDPUT("HRTOT",SELF:SERVER:FIELDGET("HRTOT"))	      //14
oFERRAM:FIELDPUT("NOME",SELF:SERVER:FIELDGET("NOME")) //15
oFERRAM:CLOSE()
	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
