PARTIAL CLASS JFAPU
METHOD ALTERAR  
SELF:oSFJFAPUI:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJFAPUI:Browser:SuspendUpdate()
SELF:oSFJFAPUI:SkipPrevious()
IF SELF:oSFJFAPUI:Server:bof
	SELF:oSFJFAPUI:Skipnext()
ENDIF
SELF:oSFJFAPUI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nSEQ AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nSEQ:=SELF:Server:FIELDGET("SEQ")
nSEQ++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("SEQ",nSEQ)
SELF:SERVER:commit()
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
RETURN .t.

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD EXCLUIR 
IF  MDG("Apagar Registro") .AND. SELF:oSFJFAPUI:server:LockCurrentRecord()
    SELF:oSFJFAPUI:server:delete()
    SELF:oSFJFAPUI:server:unlock()
    SELF:oSFJFAPUI:server:skip(-1)
    IF SELF:oSFJFAPUI:server:BOF
          SELF:oSFJFAPUI:server:GOTOP()
    ENDIF
ENDIF	

METHOD INCLUIR 
LOCAL nSEQ AS DWORD
nSEQ:=SELF:SERVER:SEQ
SELF:oSFJFAPUI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJFAPUI:SERVER:APPEND()
SELF:oSFJFAPUI:SERVER:SEQ:=nSEQ
SELF:oSFJFAPUI:SERVER:commit()
SELF:oSFJFAPUI:SERVER:resetnotification()
SELF:oSFJFAPUI:SERVER:notify(notifyappend)

METHOD LIBERAR  
SELF:SERVER:PCPDAT:=Today()
SELF:SERVER:PCPNUM:=ZFOLHA
SELF:SERVER:PCPLIB:=.T.	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJFAPUI:Browser:SuspendUpdate()
SELF:oSFJFAPUI:SkipNext()
IF SELF:oSFJFAPUI:Server:Eof
	SELF:oSFJFAPUI:SkipPrevious()
ENDIF
SELF:oSFJFAPUI:Browser:RestoreUpdate()

METHOD TABULAR  
SELF:oSFJFAPUI:VIEWTABLE()


METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJFAPUI:SERVER:Commit()


END CLASS
PARTIAL CLASS XJFAPU
METHOD cmdAPURAR 
IF SELF:SERVER:FIELDGET("APURADO")
    alert("Já apurado")
    RETURN .f.
ENDIF
IF ! SELF:SERVER:FIELDGET("PCPLIB")
	alert("Não Liberada PCP")
   RETURN .f.
ENDIF	
IF  ! MDG("Deseja Apurar")
    RETURN .f.
ENDIF
APURARUSO(SELF:SERVER:FIELDGET("SEQ"),"FERRAM.DBF","FAPUFER.DBF",SELF:SERVER:FIELDGET("DINI"),SELF:SERVER:FIELDGET("DFIM"))
SELF:SERVER:FIELDPUT("APURADO",.T.)
RETURN .t.

METHOD DELETE() 
LOCAL nSEQ AS DWORD
IF SELF:SERVER:APURADO
   alert("Apuraçao jà Efetuada")	
   RETURN .f.
ENDIF	
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	nSEQ:=SELF:Server:FIELDGET("SEQ")
	SELF:oSFJFAPUI:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJFAPUI:server:GOTOP()	
	WHILE ! oSFJFAPUI:server:EOF
 		SELF:oSFJFAPUI:server:delete()
	ENDDO	
	SELF:oSFJFAPUI:SERVER:resetnotification()
	SELF:oSFJFAPUI:SERVER:notify(notifyfilechange)	
    SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
    DELETESEQ(nSEQ,"FAPUFER.DBF")	
    DELETESEQ(nSEQ,"FAPUBAI.DBF")	
ENDIF		

END CLASS
PARTIAL CLASS XJMAPU
METHOD cmdAPURAR 
IF SELF:SERVER:FIELDGET("APURADO")
    alert("Já apurado")
    RETURN .f.
ENDIF
IF  ! MDG("Deseja Apurar")
    RETURN .f.
ENDIF
IF ! SELF:SERVER:FIELDGET("PCPLIB")
	alert("Não Liberada PCP")
   RETURN .f.
ENDIF	
APURARUSO(SELF:SERVER:FIELDGET("SEQ"),"ME01.DBF","FAPUMAQ.DBF",SELF:SERVER:FIELDGET("DINI"),SELF:SERVER:FIELDGET("DFIM"))
SELF:SERVER:FIELDPUT("APURADO",.T.)
RETURN .t.


METHOD DELETE() 	
LOCAL nSEQ AS DWORD    
Nseq:=0
IF SELF:SERVER:APURADO
   alert("Apuraçao jà Efetuada")	
   RETURN .f.
ENDIF	
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SEQ:=SELF:Server:FIELDGET("SEQ")
    SELF:oSFJFAPUI:SERVER:SUSPENDNOTIFICATION()
    SELF:oSFJFAPUI:server:GOTOP()	
    WHILE ! oSFJFAPUI:server:EOF
 	  SELF:oSFJFAPUI:server:delete()
    ENDDO	
    SELF:oSFJFAPUI:SERVER:resetnotification()
    SELF:oSFJFAPUI:SERVER:notify(notifyfilechange)
    SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
   DELETESEQ(nSEQ,"FAPUMAQ.DBF")	
   DELETESEQ(nSEQ,"MAPUBAI.DBF")	
ENDIF	


END CLASS
FUNCTION APURARUSO(nSEQ,cARQ,cAPU,dINI,dFIM)
LOCAL oFERRAM,oFAPUFER,OFAPUI AS USEREDE
LOCAL nQTDE AS DWORD
LOCAL nHORAS AS FLOAT
LOCAL cDIRE,cFERRAM,cVAR AS STRING
LOCAL aDAD AS ARRAY


IF Month(dINI)=Month(dFIM)
   cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(Year(dINI),4)+"\"	
   cVAR:="Y3"+Right(StrZero(Year(dINI),4),2)+StrZero(Month(dINI),2)
   IF cARQ="FERRAM.DBF"
      SOMAFER(cVAR,nSEQ,dINI,dFIM,cDIRE)
   ENDIF
   IF cARQ="ME01"
      SOMAMAQ(cVAR,nSEQ,dINI,dFIM,cDIRE)
   ENDIF
ELSE
	cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(Year(dINI),4)+"\"
   cVAR:="Y3"+Right(StrZero(Year(dINI),4),2)+StrZero(Month(dINI),2)
   SOMAFER(cVAR,nSEQ,dINI,dFIM,cDIRE)
	cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(Year(dFIM),4)+"\"
   cVAR:="Y3"+Right(StrZero(Year(dFIM),4),2)+StrZero(Month(dFIM),2)
   IF cARQ="FERRAM.DBF"
      SOMAFER(cVAR,nSEQ,dINI,dFIM,cDIRE)
   ENDIF
   IF cARQ="ME01.DBF"
      SOMAMAQ(cVAR,nSEQ,dINI,dFIM,cDIRE)
   ENDIF
ENDIF




//Apurador
aDAD:={zCURINI,cAPU,zCURDIR}
oFAPUFER:=USEREDE{aDAD}
IF oFAPUFER:nERRO#0
   alert("Erro ao abrir "+cAPU)
   RETURN .f.
ENDIF

//Resultados Avulso
aDAD:={zCURINI,IF(cARQ="ME01.DBF","MAPUI.DBF","FAPUI.DBF"),zCURDIR}
oFAPUI:=USEREDE{aDAD}
IF oFAPUI:nERRO=0
   oFAPUI:GOTOP()
   oFAPUI:SEEK(nSEQ)
   WHILE nSEQ=oFAPUI:FIELDGET("SEQ") .AND. ! Eof()
	   OFAPUFER:Append()
	   OFAPUFER:FIELDPUT("SEQ",nSEQ)
	   OFAPUFER:FIELDPUT("FERRAM",oFAPUI:FIELDGET("FERRAM"))
	   OFAPUFER:FIELDPUT("QTDE",oFAPUI:FIELDGET("QTDE"))
	   OFAPUFER:FIELDPUT("HORAS",oFAPUI:FIELDGET("HORAS"))
	   oFAPUI:SKIP()	
   ENDDO
   oFAPUI:CLOSE()
ELSE
   alert("Erro ao abrir Entradas Avulsos ")
ENDIF	




//Ferramenta ou Maquina
aDAD:={zCURINI,cARQ,zCURDIR}
oFERRAM:=USEREDE{aDAD}
IF oFERRAM:nERRO#0
   oFAPUFER:CLOSE()	
   alert("Erro ao abrir "+cARQ)
   RETURN .f.
ENDIF


oFAPUFER:SETORDER(2)
oFAPUFER:GOTOP()
WHILE ! oFAPUFER:EOF
      cFERRAM:=oFAPUFER:FIELDGET("FERRAM")
      nQTDE:=0
      nHORAS:=0
		WHILE ! oFAPUFER:EOF .AND. oFAPUFER:FIELDGET("FERRAM")=cFERRAM
         nQTDE+=oFAPUFER:FIELDGET("QTDE")	
         nHORAS+=oFAPUFER:FIELDGET("HORAS")	
         oFAPUFER:SKIP()
      ENDDO
      oFERRAM:GOTOP()
      IF oFERRAM:SEEK(cFERRAM)
         IF nQTDE>0
            oFERRAM:FIELDPUT("QTDESALDO",nQTDE)
            oFERRAM:FIELDPUT("QTDETOT",oFERRAM:FIELDGET("QTDETOT")+nQTDE)
            oFERRAM:FIELDPUT("DATASALDO",dFIM)
            IF oFERRAM:FIELDGET("QTDESALDO")>(oFERRAM:FIELDGET("QTDEBASE")*.8) .AND. Empty(oFERRAM:FIELDGET("QTDEPED"))
               oFERRAM:FIELDPUT("QTDEPED",nQTDE)
               oFERRAM:FIELDPUT("DATAPED",dFIM)
            ENDIF
            IF oFERRAM:FIELDGET("QTDESALDO")>(oFERRAM:FIELDGET("QTDEBASE")*1.3) .AND. Empty(oFERRAM:FIELDGET("QTDEURG"))
               oFERRAM:FIELDPUT("QTDEURG",nQTDE)
               oFERRAM:FIELDPUT("DATAURG",dFIM)
            ENDIF
            oFERRAM:FIELDPUT("SITUACAO","A")
            IF Empty(oFERRAM:FIELDGET("DATAATV"))
               oFERRAM:FIELDPUT("DATAATV",dFIM)
            ENDIF
	   	   oFERRAM:FIELDPUT("DATADES",CToD(Space(8)))
      		oFERRAM:FIELDPUT("DATAOUT",CToD(Space(8)))
      		oFERRAM:FIELDPUT("DATADEV",CToD(Space(8)))
         ELSE
            IF oFERRAM:FIELDGET("SITUACAO")<>"O" .AND. oFERRAM:FIELDGET("SITUACAO")<>"D"
               oFERRAM:FIELDPUT("SITUACAO","I")
               IF Empty(oFERRAM:FIELDGET("DATADES"))
                  oFERRAM:FIELDPUT("DATADES",dFIM)
     		      ENDIF
     		      oFERRAM:FIELDPUT("DATAATV",CToD(Space(8)))
     		      oFERRAM:FIELDPUT("DATAOUT",CToD(Space(8)))
     		      oFERRAM:FIELDPUT("DATADEV",CToD(Space(8)))
            ENDIF
         ENDIF
         IF nHORAS>0
            oFERRAM:FIELDPUT("HRSAL",nHORAS)
            oFERRAM:FIELDPUT("HRTOT",oFERRAM:FIELDGET("HRTOT")+nHORAS)
            oFERRAM:FIELDPUT("DATHSAL",dFIM)
            IF oFERRAM:FIELDGET("HRSAL")>(oFERRAM:FIELDGET("HRBAS")*.8) .AND. Empty(oFERRAM:FIELDGET("HRPRE"))
               oFERRAM:FIELDPUT("HRPRE",nHORAS)
               oFERRAM:FIELDPUT("DATHPED",dFIM)
            ENDIF
            IF oFERRAM:FIELDGET("HRSAL")>(oFERRAM:FIELDGET("HRBAS")*1.3) .AND. Empty(oFERRAM:FIELDGET("HRURG"))
               oFERRAM:FIELDPUT("HRURG",nHORAS)
               oFERRAM:FIELDPUT("DATHURG",dFIM)
            ENDIF
         ENDIF	
     ENDIF
ENDDO
oFERRAM:CLOSE()
oFAPUFER:CLOSE()

FUNCTION DELETESEQ(nSEQ,cARQ)
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,cARQ,zCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO=0
    oARQ:GOTOP()
    oARQ:SEEK(Str(nSEQ,3))
    WHILE ! oARQ:EOF .AND. nSEQ=oARQ:FIELDGET("SEQ")
           oARQ:DELETE()
           oARQ:SKIP()
    ENDDO
    oARQ:CLOSE()
ENDIF

FUNC SOMAFER(cARQ AS STRING,nORD AS DWORD, dINI AS DATE, dFIM AS DATE,cDIRE AS STRING)
LOCAL oARQ AS DBSERVER
LOCAL oMS06,oFAPUFER AS USEREDE
LOCAL cCODIGO AS STRING
LOCAL nSEQ,nSSQ AS WORD
LOCAL nQTDE AS DWORD
LOCAL nHORAS AS FLOAT
LOCAL aRET AS ARRAY
IF ! File(cDIRE+cARQ+".DBF")
	cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5EMP")
   cARQ:="MY03"
ENDIF
IF ! File(cDIRE+cARQ+".DBF")
   alert("Falta Arquivo: "+Carq)
   RETU NIL
ENDIF
aRET:={zCURINI,"MS06.DBF",zCURDIR}
oMS06:=USEREDE{aRET}
IF oMS06:nERRO#0
    alert("Erro Abrindo:  MS06")
   RETU NIL
ENDIF
aRET:={zCURINI,"FAPUFER.DBF",zCURDIR}
oFAPUFER:=USEREDE{aRET}
IF oFAPUFER:nERRO#0
    alert("Erro Abrindo: FAPUFER")
   oMS06:cLOSE()
   RETU NIL
ENDIF
oARQ:=DBSERVER{cDIRE+cARQ }
IF ! oARQ:USED
   alert("Erro Abrindo: "+Carq)
   oMS06:CLOSE()
   oFAPUFER:CLOSE()
   RETU NIL
ENDIF
oARQ:createindex("TEMP01","CODIGO+STR(SEQ,3)+STR(SSQ,3)")
oARQ:GOTOP()
WHILE ! oARQ:EOF
      cCODIGO:=oARQ:FIELDGET("CODIGO")
      nSEQ   :=oARQ:FIELDGET("SEQ")
      nSSQ   :=oARQ:FIELDGET("SSQ")
      nQTDE  := 0
      nHORAS := 0
      WHILE cCODIGO=oARQ:FIELDGET("CODIGO")  .AND. nSEQ=oARQ:FIELDGET("SEQ")  .AND. nSSQ=oARQ:FIELDGET("SSQ")  .AND. ! oARQ:EOF
           IF oARQ:FIELDGET("DATOPR")>=dINI .AND. oARQ:FIELDGET("DATOPR")<=dFIM
           	 IF oARQ:FIELDGET("BXMY03")<>"N"
                nQTDE+=oARQ:FIELDGET("QTDDE")
                nHORAS+=CHOR(oARQ:FIELDGET("FIMOPR")+IF(oARQ:FIELDGET("VIRADA")="S",24,0))-CHOR(oARQ:FIELDGET("INIOPR"))-oARQ:FIELDGET("PARADA")-(CHOR(oARQ:FIELDGET("ALMFIM"))-CHOR(oARQ:FIELDGET("ALMINI")))
             ENDIF
           ENDIF
           oARQ:SKIP()
      ENDDO
      oMS06:GOTOP()
      IF oMS06:SEEK(cCODIGO+Str(nSEQ,3)+Str(nSSQ,3))
           IF ! Empty(oMS06:FIELDGET("FERRAMEN")) .AND. nQTDE>0
           	   oFAPUFER:gotop()
           	   IF ! oFAPUFER:Seek(Str(Nord,3)+oMS06:FIELDGET("FERRAMEN"))
                  oFAPUFER:APPEND()
                  oFAPUFER:FIELDPUT("SEQ",nORD)
                  oFAPUFER:FIELDPUT("FERRAM",oMS06:FIELDGET("FERRAMEN"))
           	   ENDIF
               oFAPUFER:FIELDPUT("QTDE",oFAPUFER:FIELDGET("QTDE")+nQTDE)
               oFAPUFER:FIELDPUT("HORAS",oFAPUFER:FIELDGET("HORAS")+nHORAS)
          ENDIF		
          IF ! Empty(oMS06:FIELDGET("FERRAME2")) .AND. nQTDE>0
           	   oFAPUFER:gotop()
           	   IF ! oFAPUFER:Seek(Str(Nord,3)+oMS06:FIELDGET("FERRAME2"))
                  oFAPUFER:APPEND()
                  oFAPUFER:FIELDPUT("SEQ",nORD)
                  oFAPUFER:FIELDPUT("FERRAM",oMS06:FIELDGET("FERRAME2"))
           	   ENDIF
               oFAPUFER:FIELDPUT("QTDE",oFAPUFER:FIELDGET("QTDE")+nQTDE)
               oFAPUFER:FIELDPUT("HORAS",oFAPUFER:FIELDGET("HORAS")+nHORAS)
          ENDIF		
          IF ! Empty(oMS06:FIELDGET("FERRAME3")) .AND. nQTDE>0
           	   oFAPUFER:gotop()
           	   IF ! oFAPUFER:Seek(Str(Nord,3)+oMS06:FIELDGET("FERRAME3"))
                  oFAPUFER:APPEND()
                  oFAPUFER:FIELDPUT("SEQ",nORD)
                  oFAPUFER:FIELDPUT("FERRAM",oMS06:FIELDGET("FERRAME3"))
           	   ENDIF
               oFAPUFER:FIELDPUT("QTDE",oFAPUFER:FIELDGET("QTDE")+nQTDE)
               oFAPUFER:FIELDPUT("HORAS",oFAPUFER:FIELDGET("HORAS")+nHORAS)
          ENDIF		
          IF ! Empty(oMS06:FIELDGET("FERRAME4")) .AND. nQTDE>0
           	   oFAPUFER:gotop()
           	   IF ! oFAPUFER:Seek(Str(Nord,3)+oMS06:FIELDGET("FERRAME4"))
                  oFAPUFER:APPEND()
                  oFAPUFER:FIELDPUT("SEQ",nORD)
                  oFAPUFER:FIELDPUT("FERRAM",oMS06:FIELDGET("FERRAME4"))
           	   ENDIF
               oFAPUFER:FIELDPUT("QTDE",oFAPUFER:FIELDGET("QTDE")+nQTDE)
               oFAPUFER:FIELDPUT("HORAS",oFAPUFER:FIELDGET("HORAS")+nHORAS)
          ENDIF		
      ENDIF
ENDDO
oARQ:CLOSE()
oMS06:CLOSE()
oFAPUFER:CLOSE()
RETU NIL

FUNC SOMAMAQ(cARQ AS STRING,nORD AS DWORD, dINI AS DATE, dFIM AS DATE,cDIRE AS STRING)
LOCAL oARQ AS DBSERVER
LOCAL oFAPUFER AS USEREDE
LOCAL cCODIGO AS STRING
LOCAL nQTDE AS DWORD
LOCAL nHORAS AS FLOAT
LOCAL aRET AS ARRAY
IF ! File(cDIRE+cARQ+".DBF")
	cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5EMP")
   cARQ:="MY03"
ENDIF
IF ! File(cDIRE+cARQ+".DBF")
   alert("Falta Arquivo: "+Carq)
   RETU NIL
ENDIF
aRET:={zCURINI,"FAPUMAQ.DBF",zCURDIR}
oFAPUFER:=USEREDE{aRET}
IF oFAPUFER:nERRO#0
   alert("Erro Abrindo: FAPUMAQ")
   RETU NIL
ENDIF
oARQ:=DBSERVER{cDIRE+cARQ }
IF ! oARQ:USED
   alert("Erro Abrindo: "+Carq)
   oFAPUFER:CLOSE()
   RETU NIL
ENDIF
oARQ:createindex("TEMP01","CODMAQ")
oARQ:GOTOP()
WHILE ! oARQ:EOF
    cCODIGO:=oARQ:FIELDGET("CODMAQ")
    nQTDE  := 0
    nHORAS := 0
    WHILE cCODIGO=oARQ:FIELDGET("CODMAQ") .AND. ! oARQ:EOF
       IF oARQ:FIELDGET("DATOPR")>=dINI .AND. oARQ:FIELDGET("DATOPR")<=dFIM
       	 IF oARQ:FIELDGET("BXMY03")<>"N"
             nQTDE+=oARQ:FIELDGET("QTDDE")
             nHORAS+=CHOR(oARQ:FIELDGET("FIMOPR")+IF(oARQ:FIELDGET("VIRADA")="S",24,0))-CHOR(oARQ:FIELDGET("INIOPR"))-oARQ:FIELDGET("PARADA")-(CHOR(oARQ:FIELDGET("ALMFIM"))-CHOR(oARQ:FIELDGET("ALMINI")))
          ENDIF
       ENDIF
       oARQ:SKIP()
    ENDDO
    oFAPUFER:gotop()
    IF ! oFAPUFER:Seek(Str(Nord,3)+cCODIGO)
       oFAPUFER:APPEND()
       oFAPUFER:FIELDPUT("SEQ",nORD)
       oFAPUFER:FIELDPUT("FERRAM",cCODIGO)
    ENDIF
    oFAPUFER:FIELDPUT("QTDE",oFAPUFER:FIELDGET("QTDE")+nQTDE)
    oFAPUFER:FIELDPUT("HORAS",oFAPUFER:FIELDGET("HORAS")+nHORAS)
ENDDO
oARQ:CLOSE()
oFAPUFER:CLOSE()
RETU NIL	

