PARTIAL CLASS JFERGRP
METHOD ALTERAR  
SELF:oSFJFERGI:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJFERGI:Browser:SuspendUpdate()
SELF:oSFJFERGI:SkipPREVIOUS()
IF SELF:oSFJFERGI:Server:BOF
	SELF:oSFJFERGI:SkipNEXT()
ENDIF
SELF:oSFJFERGI:Browser:RestoreUpdate()

METHOD ANTERIOR1 
SELF:SERVER:SKIP()
IF SELF:SERVER:EOF
	SELF:SERVER:GoBottom()
ENDIF	

METHOD BALANCO 
LOCAL oJAN AS XBUSCA
oJAN:=XBUSCA{SELF,"Digite Valor","Estoque Inicial"}
oJAN:SHOW()
IF oJAN:lOK
	SELF:oSFJFERGI:server:FIELDPUT("ESTQINI",Val(oJAN:cBUSCA))
	SELF:oSFJFERGI:server:FIELDPUT("ESTQENT",0)
	SELF:oSFJFERGI:server:FIELDPUT("ESTQSAI",0)	
	SELF:oSFJFERGI:server:FIELDPUT("ESTQSAL",Val(oJAN:cbusca))
	SELF:oSFJFERGI:server:FIELDPUT("DATABALAN",Today())
ENDIF

METHOD CANCELAR() 
	SELF:ENDWINDOW()
	

METHOD Cancelar1( ) 
		SELF:ENDWINDOW()

METHOD DELETar() 
IF ! MDG("Apagar Registro") .AND. SELF:server:LockCurrentRecord()
	RETU SELF
ENDIF	
GRAVALOG(SELF:SERVER:FIELDGET("GRUPO"),"DEL","GRUPO")	
SELF:oSFJFERGI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJFERGI:server:GOTOP()	
WHILE ! oSFJFERGI:server:EOF
 	SELF:oSFJFERGI:server:delete()
ENDDO	
SELF:server:delete()
SELF:server:unlock()
SELF:SERVER:SKIP(-1)
IF SELF:SERVER:BOF
   SELF:SERVER:GOTOP()
ENDIF	
SELF:oSFJFERGI:SERVER:resetnotification()
SELF:oSFJFERGI:SERVER:notify(notifyfilechange)	
SELF:oSFJFERGI:Browser:REFRESH()

METHOD ENTRADA 
LOCAL oMOV AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nESTQXXX,nESTQYYY,VAR1,VAR2,VAR3 AS FLOAT
LOCAL xDIAS AS DWORD
LOCAL oJAN AS XBUSCA
            
xdias:=0
oJAN:=XBUSCA{SELF,"Digite Valor","Qtde Entrada"}
oJAN:SHOW()
IF ! oJAN:lOK
	RETURN .f.
ENDIF	

aDAD:={zCURINI,"FE99.DBF",zCURDIR}
oMOV:=USEREDE{aDAD}
IF oMOV:nERRO#0
   alert("Erro Abrindo: FE99.DBF")
   RETU NIL
ENDIF


//Gravando o Estoque
SELF:oSFJFERGI:SERVER:SUSPENDNOTIFICATION()
nESTQXXX := 0
nESTQYYY := 0
SELF:oSFJFERGI:SERVER:FIELDPUT("ESTQENT",SELF:oSFJFERGI:SERVER:FIELDGET("ESTQENT")+Val(oJAN:CBUSCA))
//Gravando o Saldo de Estoque Anterior
nESTQXXX := SELF:oSFJFERGI:SERVER:FIELDGET("ESTQSAL")
SELF:oSFJFERGI:SERVER:FIELDPUT("ESTQSAL",SELF:oSFJFERGI:SERVER:FIELDGET("ESTQINI") + SELF:oSFJFERGI:SERVER:FIELDGET("ESTQENT") - SELF:oSFJFERGI:SERVER:FIELDGET("ESTQSAI"))
//Gravando o Saldo de Estoque Atual
nESTQYYY       := SELF:oSFJFERGI:SERVER:FIELDGET("ESTQSAL")
SELF:oSFJFERGI:SERVER:FIELDPUT("SAIMIN",SELF:oSFJFERGI:SERVER:FIELDGET("SAIMIN")+ Val(oJAN:CBUSCA))
//Calculando o Estoque Minimo
VAR1:=0
IF ! Empty(SELF:oSFJFERGI:SERVER:FIELDGET("DATMIN"))
    xDIAS:= Today() - SELF:oSFJFERGI:SERVER:FIELDGET("DATMIN")
ENDIF
IF xDIAS>0
   VAR1:= SELF:oSFJFERGI:SERVER:FIELDGET("SAIMIN") / xDIAS
ENDIF
VAR2 := SELF:oSFJFERGI:SERVER:FIELDGET("DIASENT") * VAR1
VAR3 := SELF:oSFJFERGI:SERVER:FIELDGET("DIASEST") * VAR1
SELF:oSFJFERGI:SERVER:FIELDPUT("ESTQMIN",VAR2 + VAR3)
IF xDIAS > 30 // zMEDIA Balancei o Saldo quando maior que a media
   SELF:oSFJFERGI:SERVER:FIELDPUT("DATMIN",Today() - 30) // *ZMEDIA
  	SELF:oSFJFERGI:SERVER:FIELDPUT("SAIMIN",VAR1 * 30)  // *ZMEDIA
ELSE
   SELF:oSFJFERGI:SERVER:FIELDPUT("DATMIN",Today()) // *ZMEDIA
ENDIF
oMOV:APPEND()
oMOV:FIELDPUT("ARQUIVO","RO")
oMOV:FIELDPUT("DOCUMENTO",Str(0,8)+SELF:SERVER:FIELDGET("GRUPO")+"/"+SELF:oSFJFERGI:SERVER:FIELDGET("CODIGO"))
oMOV:FIELDPUT("DATA",Today())
oMOV:FIELDPUT("USUARIO",ZUSER)
oMOV:FIELDPUT("QTDE",Val(oJAN:CBUSCA))
oMOV:FIELDPUT("OLDQTDE",0)
oMOV:FIELDPUT("NUMERO",0)
oMOV:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("GRUPO")+"/"+SELF:OsfjFERGI:SERVER:FIELDGET("CODIGO"))
oMOV:FIELDPUT("ESTQXXX",nESTQXXX)
oMOV:FIELDPUT("ESTQYYY",nESTQYYY)
SELF:oSFJFERGI:SERVER:resetnotification()
SELF:oSFJFERGI:SERVER:notify(notifyfilechange)	
oMOV:CLOSE()


METHOD EXCLUIR 
SELF:oSFJFERGI:SERVER:SUSPENDNOTIFICATION()
IF MDG("Apagar Registro") .AND. SELF:oSFJFERGI:server:LockCurrentRecord()
    SELF:oSFJFERGI:server:delete()
    SELF:oSFJFERGI:server:unlock()
    SELF:oSFJFERGI:server:skip(-1)
    IF SELF:oSFJFERGI:SERVER:EOF
       SELF:oSFJFERGI:GOTOP()	
    ENDIF
 ENDIF	
SELF:oSFJFERGI:SERVER:resetnotification()
SELF:oSFJFERGI:SERVER:notify(notifyfilechange)
SELF:oSFJFERGI:Browser:REFRESH()

METHOD INCLUIR 
LOCAL cDESENHO AS STRING
cDESENHO:=SELF:SERVER:FIELDGET("GRUPO")
SELF:oSFJFERGI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJFERGI:SERVER:APPEND()
SELF:oSFJFERGI:SERVER:FIELDPUT("FERRAM",cDESENHO)
SELF:oSFJFERGI:SERVER:commit()
SELF:oSFJFERGI:SERVER:resetnotification()
SELF:oSFJFERGI:SERVER:notify(notifyappend)
SELF:oSFJFERGI:Browser:REFRESH()

METHOD localizareg(oOWNER) 
LOCAL oNOVAFER AS xBUSCA
oNOVAFER:=xBUSCA{oOWNER,"Localizar","Digite o Codigo "}
oNOVAFER:lMES:=.T.
oNOVAFER:SHOW()
IF oNOVAFER:lOK
	SELF:server:setorder(1)
	SELF:server:gotop()
	SELF:server:seek(oNOVAFER:cBUSCA)
	IF SELF:server:eof
	  SELF:server:gotop()
	ENDIF
ENDIF
RETURN .t.

METHOD novo(oOWNER) 
LOCAL oNOVAFER AS xBUSCA
oNOVAFER:=xBUSCA{oOWNER,"Localizar","Digite o Codigo "}
oNOVAFER:lMES:=.T.
oNOVAFER:SHOW()
IF oNOVAFER:lOK
	SELF:server:setorder(1)
	SELF:server:gotop()
	IF ! SELF:server:seek(oNOVAFER:cBUSCA)
		SELF:SERVER:SUSPENDNOTIFICATION()
	    SELF:server:append()
	    SELF:SERVER:FIELDPUT("GRUPO",oNOVAFER:cBUSCA)
		SELF:SERVER:resetnotification()
		SELF:SERVER:notify(notifyappend)
	ELSE
	    alert("Já Cadastrado")
	ENDIF	
ENDIF
RETURN .t.

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJFERGI:Browser:SuspendUpdate()
SELF:oSFJFERGI:SkipNext()
IF SELF:oSFJFERGI:Server:Eof
	SELF:oSFJFERGI:SkipPrevious()
ENDIF
SELF:oSFJFERGI:Browser:RestoreUpdate()

METHOD PROXIMO1 
SELF:SERVER:SKIP(-1)
IF SELF:SERVER:BOF
	SELF:SERVER:GoTOP()
ENDIF	

METHOD SAIDA 
LOCAL oMOV AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nESTQXXX,nESTQYYY,VAR1,VAR2,VAR3 AS FLOAT
LOCAL xDIAS AS DWORD
LOCAL oJAN AS XBUSCA
              
xdias:=0
oJAN:=XBUSCA{SELF,"Digite Valor","Qtde Saida"}
oJAN:SHOW()
IF ! oJAN:lOK
	RETURN .f.
ENDIF	

aDAD:={zCURINI,"FE99.DBF",zCURDIR}
oMOV:=USEREDE{aDAD}
IF oMOV:nERRO#0
   alert("Erro Abrindo: FE99.DBF")
   RETU NIL
ENDIF


//Gravando o Estoque
SELF:oSFJFERGI:SERVER:SUSPENDNOTIFICATION()
nESTQXXX := 0
nESTQYYY := 0
SELF:oSFJFERGI:SERVER:FIELDPUT("ESTQSAI",SELF:oSFJFERGI:SERVER:FIELDGET("ESTQSAI")+Val(oJAN:CBUSCA))
//Gravando o Saldo de Estoque Anterior
nESTQXXX := SELF:oSFJFERGI:SERVER:FIELDGET("ESTQSAL")
SELF:oSFJFERGI:SERVER:FIELDPUT("ESTQSAL",SELF:oSFJFERGI:SERVER:FIELDGET("ESTQINI") + SELF:oSFJFERGI:SERVER:FIELDGET("ESTQENT") - SELF:oSFJFERGI:SERVER:FIELDGET("ESTQSAI"))
//Gravando o Saldo de Estoque Atual
nESTQYYY       := SELF:oSFJFERGI:SERVER:FIELDGET("ESTQSAL")
SELF:oSFJFERGI:SERVER:FIELDPUT("SAIMIN",SELF:oSFJFERGI:SERVER:FIELDGET("SAIMIN")-Val(oJAN:CBUSCA))
//Calculando o Estoque Minimo
VAR1:=0
IF ! Empty(SELF:oSFJFERGI:SERVER:FIELDGET("DATMIN"))
    xDIAS:= Today() - SELF:oSFJFERGI:SERVER:FIELDGET("DATMIN")
ENDIF
IF xDIAS>0
   VAR1:= SELF:oSFJFERGI:SERVER:FIELDGET("SAIMIN") / xDIAS
ENDIF
VAR2 := SELF:oSFJFERGI:SERVER:FIELDGET("DIASENT") * VAR1
VAR3 := SELF:oSFJFERGI:SERVER:FIELDGET("DIASEST") * VAR1
SELF:oSFJFERGI:SERVER:FIELDPUT("ESTQMIN",VAR2 + VAR3)
IF xDIAS > 30 // zMEDIA Balancei o Saldo quando maior que a media
   SELF:oSFJFERGI:SERVER:FIELDPUT("DATMIN",Today() - 30) // *ZMEDIA
  	SELF:oSFJFERGI:SERVER:FIELDPUT("SAIMIN",VAR1 * 30)  // *ZMEDIA
ELSE
   SELF:oSFJFERGI:SERVER:FIELDPUT("DATMIN",Today()) // *ZMEDIA
ENDIF
oMOV:APPEND()
oMOV:FIELDPUT("ARQUIVO","FERGRP")
oMOV:FIELDPUT("DOCUMENTO",Str(0,8)+SELF:SERVER:FIELDGET("GRUPO")+"/"+SELF:oSFJFERGI:SERVER:FIELDGET("CODIGO"))
oMOV:FIELDPUT("DATA",Today())
oMOV:FIELDPUT("USUARIO",ZUSER)
oMOV:FIELDPUT("QTDE",Val(oJAN:CBUSCA))
oMOV:FIELDPUT("OLDQTDE",0)
oMOV:FIELDPUT("NUMERO",0)
oMOV:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("GRUPO")+"/"+SELF:OsfjFERGI:SERVER:FIELDGET("CODIGO"))
oMOV:FIELDPUT("ESTQXXX",nESTQXXX)
oMOV:FIELDPUT("ESTQYYY",nESTQYYY)
SELF:oSFJFERGI:SERVER:resetnotification()
SELF:oSFJFERGI:SERVER:notify(notifyfilechange)	
oMOV:CLOSE()

METHOD TABULAR  
SELF:oSFJFERGI:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJFERGI:SERVER:COMMIT()




END CLASS
