#region DEFINES
STATIC DEFINE JFER_ALTERAR := 114 
STATIC DEFINE JFER_ANTERIOR := 112 
STATIC DEFINE JFER_BUSCA := 106 
STATIC DEFINE JFER_CLIENTE := 117 
STATIC DEFINE JFER_CMDCALCULAR := 105 
STATIC DEFINE JFER_DATAATI := 110 
STATIC DEFINE JFER_DATAE := 116 
STATIC DEFINE JFER_EXCLUIR := 115 
STATIC DEFINE JFER_FERRAM := 104 
STATIC DEFINE JFER_INCLUIR := 116 
STATIC DEFINE JFER_JFERRAMI := 110 
STATIC DEFINE JFER_NOME := 100 
STATIC DEFINE JFER_NUMERO := 108 
STATIC DEFINE JFER_PORCOD := 109 
STATIC DEFINE JFER_PROXIMO := 111 
STATIC DEFINE JFER_SC_DATAE := 114 
STATIC DEFINE JFER_SC_FERRAM := 102 
STATIC DEFINE JFER_SC_NOME := 103 
STATIC DEFINE JFER_TABCONTROL1 := 101 
STATIC DEFINE JFER_TABULAR := 113 
STATIC DEFINE JFER_TEXTO := 107 
STATIC DEFINE JFER_THEFIXEDTEXT19 := 138 
STATIC DEFINE JFER_THEFIXEDTEXT20 := 146 
STATIC DEFINE JFER_THEGROUPBOX1 := 112 
STATIC DEFINE JFER_THERADIOBUTTON5 := 108 
STATIC DEFINE JFER_THERADIOBUTTON7 := 110 
STATIC DEFINE TABCONTROL1_PAGE1_CLIENTE := 103 
STATIC DEFINE TABCONTROL1_PAGE1_COGCLI := 102 
STATIC DEFINE TABCONTROL1_PAGE1_CONTABIL := 112 
STATIC DEFINE TABCONTROL1_PAGE1_DATAATV := 108 
STATIC DEFINE TABCONTROL1_PAGE1_DATADES := 107 
STATIC DEFINE TABCONTROL1_PAGE1_DATADEV := 105 
STATIC DEFINE TABCONTROL1_PAGE1_DATAOUT := 106 
STATIC DEFINE TABCONTROL1_PAGE1_ESCFOR := 113 
STATIC DEFINE TABCONTROL1_PAGE1_ESTOQUE := 129 
STATIC DEFINE TABCONTROL1_PAGE1_ESTOQUECOD := 131 
STATIC DEFINE TABCONTROL1_PAGE1_ESTOQUEGER := 130 
STATIC DEFINE TABCONTROL1_PAGE1_GRUPO := 100 
STATIC DEFINE TABCONTROL1_PAGE1_NAEMPRESA := 120 
STATIC DEFINE TABCONTROL1_PAGE1_NAO := 116 
STATIC DEFINE TABCONTROL1_PAGE1_OBS := 109 
STATIC DEFINE TABCONTROL1_PAGE1_PEGCLI := 128 
STATIC DEFINE TABCONTROL1_PAGE1_PROPRIA := 114 
STATIC DEFINE TABCONTROL1_PAGE1_RADIOBUTTON10 := 124 
STATIC DEFINE TABCONTROL1_PAGE1_RADIOBUTTON11 := 125 
STATIC DEFINE TABCONTROL1_PAGE1_RADIOBUTTON12 := 126 
STATIC DEFINE TABCONTROL1_PAGE1_RADIOBUTTON13 := 127 
STATIC DEFINE TABCONTROL1_PAGE1_RADIOBUTTON6 := 118 
STATIC DEFINE TABCONTROL1_PAGE1_RADIOBUTTON7 := 119 
STATIC DEFINE TABCONTROL1_PAGE1_RADIOBUTTON8 := 121 
STATIC DEFINE TABCONTROL1_PAGE1_RADIOBUTTON9 := 122 
STATIC DEFINE TABCONTROL1_PAGE1_SC_CLIENTE := 104 
STATIC DEFINE TABCONTROL1_PAGE1_SC_GRUPO := 101 
STATIC DEFINE TABCONTROL1_PAGE1_SIM := 115 
STATIC DEFINE TABCONTROL1_PAGE1_SITUACAO := 123 
STATIC DEFINE TABCONTROL1_PAGE1_THEFIXEDTEXT5 := 110 
STATIC DEFINE TABCONTROL1_PAGE1_THEFIXEDTEXT6 := 111 
STATIC DEFINE TABCONTROL1_PAGE1_TIPOFER := 117 
STATIC DEFINE TABCONTROL1_PAGE2_CMDCALCULAR := 124 
STATIC DEFINE TABCONTROL1_PAGE2_DATAPED := 114 
STATIC DEFINE TABCONTROL1_PAGE2_DATASALDO := 115 
STATIC DEFINE TABCONTROL1_PAGE2_DATAURG := 112 
STATIC DEFINE TABCONTROL1_PAGE2_DATHPED := 103 
STATIC DEFINE TABCONTROL1_PAGE2_DATHSAL := 106 
STATIC DEFINE TABCONTROL1_PAGE2_DATHURG := 100 
STATIC DEFINE TABCONTROL1_PAGE2_GROUPBOX1 := 120 
STATIC DEFINE TABCONTROL1_PAGE2_GROUPBOX2 := 110 
STATIC DEFINE TABCONTROL1_PAGE2_GROUPBOX3 := 137 
STATIC DEFINE TABCONTROL1_PAGE2_GROUPBOX4 := 147 
STATIC DEFINE TABCONTROL1_PAGE2_HRBAS := 109 
STATIC DEFINE TABCONTROL1_PAGE2_HRPRE := 104 
STATIC DEFINE TABCONTROL1_PAGE2_HRSAL := 107 
STATIC DEFINE TABCONTROL1_PAGE2_HRTOT := 140 
STATIC DEFINE TABCONTROL1_PAGE2_HRURG := 101 
STATIC DEFINE TABCONTROL1_PAGE2_PREVER := 127 
STATIC DEFINE TABCONTROL1_PAGE2_QTDEBASE := 122 
STATIC DEFINE TABCONTROL1_PAGE2_QTDEPED := 116 
STATIC DEFINE TABCONTROL1_PAGE2_QTDESALDO := 117 
STATIC DEFINE TABCONTROL1_PAGE2_QTDETOT := 134 
STATIC DEFINE TABCONTROL1_PAGE2_QTDEURG := 113 
STATIC DEFINE TABCONTROL1_PAGE2_RB1 := 126 
STATIC DEFINE TABCONTROL1_PAGE2_RB2 := 125 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT10 := 102 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT11 := 105 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT12 := 108 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT13 := 111 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT14 := 133 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT15 := 144 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT16 := 136 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT17 := 145 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT18 := 146 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT4 := 123 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT6 := 121 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT7 := 119 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT8 := 118 
STATIC DEFINE TABCONTROL1_PAGE2_THEFIXEDTEXT9 := 130 
STATIC DEFINE TABCONTROL1_PAGE2_VDBAS := 135 
STATIC DEFINE TABCONTROL1_PAGE2_VDDPRE := 131 
STATIC DEFINE TABCONTROL1_PAGE2_VDDURG := 128 
STATIC DEFINE TABCONTROL1_PAGE2_VDHBAS := 143 
STATIC DEFINE TABCONTROL1_PAGE2_VDHDPRE := 139 
STATIC DEFINE TABCONTROL1_PAGE2_VDHDURG := 138 
STATIC DEFINE TABCONTROL1_PAGE2_VDHPRE := 142 
STATIC DEFINE TABCONTROL1_PAGE2_VDHURG := 141 
STATIC DEFINE TABCONTROL1_PAGE2_VDPRE := 132 
STATIC DEFINE TABCONTROL1_PAGE2_VDURG := 129 
STATIC DEFINE TABCONTROL1_PAGE3_DATAT := 122 
STATIC DEFINE TABCONTROL1_PAGE3_ESCRES := 118 
STATIC DEFINE TABCONTROL1_PAGE3_FIXEDBITMAP1 := 105 
STATIC DEFINE TABCONTROL1_PAGE3_FIXEDTEXT2 := 112 
STATIC DEFINE TABCONTROL1_PAGE3_FIXEDTEXT3 := 113 
STATIC DEFINE TABCONTROL1_PAGE3_FIXEDTEXT4 := 114 
STATIC DEFINE TABCONTROL1_PAGE3_FIXEDTEXT5 := 115 
STATIC DEFINE TABCONTROL1_PAGE3_FIXEDTEXT6 := 116 
STATIC DEFINE TABCONTROL1_PAGE3_FIXEDTEXT7 := 117 
STATIC DEFINE TABCONTROL1_PAGE3_FOTO := 121 
STATIC DEFINE TABCONTROL1_PAGE3_GROUPBOX1 := 102 
STATIC DEFINE TABCONTROL1_PAGE3_GROUPBOX2 := 104 
STATIC DEFINE TABCONTROL1_PAGE3_MEDA := 106 
STATIC DEFINE TABCONTROL1_PAGE3_MEDB := 107 
STATIC DEFINE TABCONTROL1_PAGE3_MEDC := 108 
STATIC DEFINE TABCONTROL1_PAGE3_MEDD := 109 
STATIC DEFINE TABCONTROL1_PAGE3_MEDH := 110 
STATIC DEFINE TABCONTROL1_PAGE3_PEGAVA := 119 
STATIC DEFINE TABCONTROL1_PAGE3_PESO := 111 
STATIC DEFINE TABCONTROL1_PAGE3_SC_DESTINO2 := 120 
STATIC DEFINE TABCONTROL1_PAGE3_VISUALNOM := 101 
STATIC DEFINE TABCONTROL1_PAGE3_VISUALNUM := 100 
STATIC DEFINE TABCONTROL1_PAGE3_VISUALOBS := 103 
STATIC DEFINE TABCONTROL1_PAGE4_ALMOFADA := 120 
STATIC DEFINE TABCONTROL1_PAGE4_ALTERAR := 105 
STATIC DEFINE TABCONTROL1_PAGE4_ALTURA := 119 
STATIC DEFINE TABCONTROL1_PAGE4_ANTERIOR := 103 
STATIC DEFINE TABCONTROL1_PAGE4_BALANCO := 101 
STATIC DEFINE TABCONTROL1_PAGE4_CODMP01 := 135 
STATIC DEFINE TABCONTROL1_PAGE4_ENTRADA := 100 
STATIC DEFINE TABCONTROL1_PAGE4_ESCMAT := 134 
STATIC DEFINE TABCONTROL1_PAGE4_ESCPRENSA := 132 
STATIC DEFINE TABCONTROL1_PAGE4_ESCPROD := 128 
STATIC DEFINE TABCONTROL1_PAGE4_ESPMAT := 125 
STATIC DEFINE TABCONTROL1_PAGE4_EXCLUIR := 106 
STATIC DEFINE TABCONTROL1_PAGE4_FOTO := 139 
STATIC DEFINE TABCONTROL1_PAGE4_INCLUIR := 107 
STATIC DEFINE TABCONTROL1_PAGE4_JFERGI := 108 
STATIC DEFINE TABCONTROL1_PAGE4_LARG := 124 
STATIC DEFINE TABCONTROL1_PAGE4_MATCOD := 122 
STATIC DEFINE TABCONTROL1_PAGE4_MATNOM := 123 
STATIC DEFINE TABCONTROL1_PAGE4_OPERN := 115 
STATIC DEFINE TABCONTROL1_PAGE4_PASSOFER := 126 
STATIC DEFINE TABCONTROL1_PAGE4_PECA := 112 
STATIC DEFINE TABCONTROL1_PAGE4_PECAN := 116 
STATIC DEFINE TABCONTROL1_PAGE4_PECAROL := 127 
STATIC DEFINE TABCONTROL1_PAGE4_PEGCOD := 129 
STATIC DEFINE TABCONTROL1_PAGE4_PEGMAT := 133 
STATIC DEFINE TABCONTROL1_PAGE4_PEGPRENSA := 131 
STATIC DEFINE TABCONTROL1_PAGE4_PEGSEQ := 130 
STATIC DEFINE TABCONTROL1_PAGE4_PINOS := 121 
STATIC DEFINE TABCONTROL1_PAGE4_PRENSA := 117 
STATIC DEFINE TABCONTROL1_PAGE4_PRENSAN := 118 
STATIC DEFINE TABCONTROL1_PAGE4_PROXIMO := 102 
STATIC DEFINE TABCONTROL1_PAGE4_SC_ALMOFADA := 105 
STATIC DEFINE TABCONTROL1_PAGE4_SC_ALTURA := 104 
STATIC DEFINE TABCONTROL1_PAGE4_SC_CLIENTE1 := 136 
STATIC DEFINE TABCONTROL1_PAGE4_SC_DESTINO2 := 138 
STATIC DEFINE TABCONTROL1_PAGE4_SC_ESPMAT := 109 
STATIC DEFINE TABCONTROL1_PAGE4_SC_LARG := 108 
STATIC DEFINE TABCONTROL1_PAGE4_SC_MATCOD := 107 
STATIC DEFINE TABCONTROL1_PAGE4_SC_PASSOFER := 110 
STATIC DEFINE TABCONTROL1_PAGE4_SC_PECA := 100 
STATIC DEFINE TABCONTROL1_PAGE4_SC_PECAROL := 111 
STATIC DEFINE TABCONTROL1_PAGE4_SC_PINOS := 106 
STATIC DEFINE TABCONTROL1_PAGE4_SC_PRENSA := 103 
STATIC DEFINE TABCONTROL1_PAGE4_SC_SEQ := 101 
STATIC DEFINE TABCONTROL1_PAGE4_SC_SSQ := 102 
STATIC DEFINE TABCONTROL1_PAGE4_SEQ := 113 
STATIC DEFINE TABCONTROL1_PAGE4_SSQ := 114 
STATIC DEFINE TABCONTROL1_PAGE4_TABULAR := 104 
STATIC DEFINE TABCONTROL1_PAGE4_VERPCP := 137 
STATIC DEFINE TABCONTROL1_PAGE5_CMDTIPALMO := 183 
STATIC DEFINE TABCONTROL1_PAGE5_ESC11 := 118 
STATIC DEFINE TABCONTROL1_PAGE5_ESC12 := 119 
STATIC DEFINE TABCONTROL1_PAGE5_ESC13 := 120 
STATIC DEFINE TABCONTROL1_PAGE5_ESC14 := 121 
STATIC DEFINE TABCONTROL1_PAGE5_ESC15 := 122 
STATIC DEFINE TABCONTROL1_PAGE5_ESC16 := 123 
STATIC DEFINE TABCONTROL1_PAGE5_ESC17 := 124 
STATIC DEFINE TABCONTROL1_PAGE5_ESC18 := 125 
STATIC DEFINE TABCONTROL1_PAGE5_ESC21 := 133 
STATIC DEFINE TABCONTROL1_PAGE5_ESC22 := 132 
STATIC DEFINE TABCONTROL1_PAGE5_ESC23 := 131 
STATIC DEFINE TABCONTROL1_PAGE5_ESC24 := 130 
STATIC DEFINE TABCONTROL1_PAGE5_ESC25 := 129 
STATIC DEFINE TABCONTROL1_PAGE5_ESC26 := 128 
STATIC DEFINE TABCONTROL1_PAGE5_ESC27 := 127 
STATIC DEFINE TABCONTROL1_PAGE5_ESC28 := 126 
STATIC DEFINE TABCONTROL1_PAGE5_ESC31 := 141 
STATIC DEFINE TABCONTROL1_PAGE5_ESC32 := 140 
STATIC DEFINE TABCONTROL1_PAGE5_ESC33 := 139 
STATIC DEFINE TABCONTROL1_PAGE5_ESC34 := 138 
STATIC DEFINE TABCONTROL1_PAGE5_ESC35 := 137 
STATIC DEFINE TABCONTROL1_PAGE5_ESC36 := 136 
STATIC DEFINE TABCONTROL1_PAGE5_ESC37 := 135 
STATIC DEFINE TABCONTROL1_PAGE5_ESC38 := 134 
STATIC DEFINE TABCONTROL1_PAGE5_ESC41 := 149 
STATIC DEFINE TABCONTROL1_PAGE5_ESC42 := 148 
STATIC DEFINE TABCONTROL1_PAGE5_ESC43 := 147 
STATIC DEFINE TABCONTROL1_PAGE5_ESC44 := 146 
STATIC DEFINE TABCONTROL1_PAGE5_ESC45 := 145 
STATIC DEFINE TABCONTROL1_PAGE5_ESC46 := 144 
STATIC DEFINE TABCONTROL1_PAGE5_ESC47 := 143 
STATIC DEFINE TABCONTROL1_PAGE5_ESC48 := 142 
STATIC DEFINE TABCONTROL1_PAGE5_ESC51 := 157 
STATIC DEFINE TABCONTROL1_PAGE5_ESC52 := 156 
STATIC DEFINE TABCONTROL1_PAGE5_ESC53 := 155 
STATIC DEFINE TABCONTROL1_PAGE5_ESC54 := 154 
STATIC DEFINE TABCONTROL1_PAGE5_ESC55 := 153 
STATIC DEFINE TABCONTROL1_PAGE5_ESC56 := 152 
STATIC DEFINE TABCONTROL1_PAGE5_ESC57 := 151 
STATIC DEFINE TABCONTROL1_PAGE5_ESC58 := 150 
STATIC DEFINE TABCONTROL1_PAGE5_ESC61 := 165 
STATIC DEFINE TABCONTROL1_PAGE5_ESC62 := 164 
STATIC DEFINE TABCONTROL1_PAGE5_ESC63 := 163 
STATIC DEFINE TABCONTROL1_PAGE5_ESC64 := 162 
STATIC DEFINE TABCONTROL1_PAGE5_ESC65 := 161 
STATIC DEFINE TABCONTROL1_PAGE5_ESC66 := 160 
STATIC DEFINE TABCONTROL1_PAGE5_ESC67 := 159 
STATIC DEFINE TABCONTROL1_PAGE5_ESC68 := 158 
STATIC DEFINE TABCONTROL1_PAGE5_ESC71 := 173 
STATIC DEFINE TABCONTROL1_PAGE5_ESC72 := 172 
STATIC DEFINE TABCONTROL1_PAGE5_ESC73 := 171 
STATIC DEFINE TABCONTROL1_PAGE5_ESC74 := 170 
STATIC DEFINE TABCONTROL1_PAGE5_ESC75 := 169 
STATIC DEFINE TABCONTROL1_PAGE5_ESC76 := 168 
STATIC DEFINE TABCONTROL1_PAGE5_ESC77 := 167 
STATIC DEFINE TABCONTROL1_PAGE5_ESC78 := 166 
STATIC DEFINE TABCONTROL1_PAGE5_ESC81 := 181 
STATIC DEFINE TABCONTROL1_PAGE5_ESC82 := 180 
STATIC DEFINE TABCONTROL1_PAGE5_ESC83 := 179 
STATIC DEFINE TABCONTROL1_PAGE5_ESC84 := 178 
STATIC DEFINE TABCONTROL1_PAGE5_ESC85 := 177 
STATIC DEFINE TABCONTROL1_PAGE5_ESC86 := 176 
STATIC DEFINE TABCONTROL1_PAGE5_ESC87 := 175 
STATIC DEFINE TABCONTROL1_PAGE5_ESC88 := 174 
STATIC DEFINE TABCONTROL1_PAGE5_ESQL01 := 109 
STATIC DEFINE TABCONTROL1_PAGE5_ESQL02 := 110 
STATIC DEFINE TABCONTROL1_PAGE5_ESQL03 := 111 
STATIC DEFINE TABCONTROL1_PAGE5_ESQL04 := 112 
STATIC DEFINE TABCONTROL1_PAGE5_ESQL05 := 113 
STATIC DEFINE TABCONTROL1_PAGE5_ESQL06 := 114 
STATIC DEFINE TABCONTROL1_PAGE5_ESQL07 := 115 
STATIC DEFINE TABCONTROL1_PAGE5_ESQL08 := 116 
STATIC DEFINE TABCONTROL1_PAGE5_ESQTIP := 182 
STATIC DEFINE TABCONTROL1_PAGE5_FIXEDTEXT2 := 107 
STATIC DEFINE TABCONTROL1_PAGE5_OBST01 := 100 
STATIC DEFINE TABCONTROL1_PAGE5_PRATILE := 117 
STATIC DEFINE TABCONTROL1_PAGE5_PUSHBUTTON65 := 184 
STATIC DEFINE TABCONTROL1_PAGE5_RADIOBUTTON1 := 102 
STATIC DEFINE TABCONTROL1_PAGE5_RADIOBUTTON2 := 103 
STATIC DEFINE TABCONTROL1_PAGE5_RADIOBUTTON3 := 105 
STATIC DEFINE TABCONTROL1_PAGE5_RADIOBUTTON4 := 106 
STATIC DEFINE TABCONTROL1_PAGE5_SC_DATAT2 := 108 
STATIC DEFINE TABCONTROL1_PAGE5_USADEMI := 101 
STATIC DEFINE TABCONTROL1_PAGE5_USADISP := 104 
#endregion

PARTIAL class JFER inherit MYDataWindow 

	PROTECT oDBFERRAM as DataColumn
	PROTECT oDBCLIENTE as DataColumn
	PROTECT oDBNUMERO as DataColumn
	protect oDCNOME as SINGLELINEEDIT
	protect oDCTabControl1 as TABCONTROL
	protect oTPTABCONTROL1_PAGE1 as TABCONTROL1_PAGE1
	protect oTPTABCONTROL1_PAGE2 as TABCONTROL1_PAGE2
	protect oTPTABCONTROL1_PAGE3 as TABCONTROL1_PAGE3
	protect oTPTABCONTROL1_PAGE4 as TABCONTROL1_PAGE4
	protect oTPTABCONTROL1_PAGE5 as TABCONTROL1_PAGE5
	protect oDCSC_FERRAM as FIXEDTEXT
	protect oDCSC_NOME as FIXEDTEXT
	protect oDCFERRAM as SINGLELINEEDIT
	protect oCCcmdCalcular as PUSHBUTTON
	protect oCCbusca as PUSHBUTTON
	protect oDCTEXTO as FIXEDTEXT
	protect oDCNUMERO as SINGLELINEEDIT
	protect oCCporCOD as PUSHBUTTON
	protect oCCProximo as PUSHBUTTON
	protect oCCAnterior as PUSHBUTTON
	protect oCCTabular as PUSHBUTTON
	protect oCCAlterar as PUSHBUTTON
	protect oCCExcluir as PUSHBUTTON
	protect oCCIncluir as PUSHBUTTON
// 	instance NOME 
// 	instance FERRAM 
// 	instance NUMERO 
// 	instance CLIENTE 
	protect oSFjferrami as jferrami

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS CLASSE() 
RETURN self:FieldGet(#CLASSE)


access CLIENTE() 
return self:FieldGet(#CLIENTE)


assign CLIENTE(uValue) 
self:FieldPut(#CLIENTE, uValue)
return CLIENTE := uValue


ACCESS DATAATI() 
RETURN self:FieldGet(#DATAATI)


ACCESS DATAE() 
RETURN self:FieldGet(#DATAE)


ACCESS DATAP() 
RETURN self:FieldGet(#DATAP)


METHOD Excluir( ) 
SELF:oSFJFERRAMI:SERVER:SUSPENDNOTIFICATION()
IF MDG("Apagar Registro") .AND. SELF:oSFJFERRAMI:server:LockCurrentRecord()
    SELF:oSFJFERRAMI:server:delete()
    SELF:oSFJFERRAMI:server:unlock()
    SELF:oSFJFERRAMI:server:skip(-1)
    IF SELF:oSFJFERRAMI:SERVER:EOF
       SELF:oSFJFERRAMI:GOTOP()	
    ENDIF
 ENDIF	
SELF:oSFJFERRAMI:SERVER:resetnotification()
SELF:oSFJFERRAMI:SERVER:notify(notifyfilechange)
SELF:oSFJFERRAMI:Browser:REFRESH()	

access FERRAM() 
return self:FieldGet(#FERRAM)


assign FERRAM(uValue) 
self:FieldPut(#FERRAM, uValue)
return FERRAM := uValue


METHOD Incluir( ) 
LOCAL cDESENHO AS STRING
cDESENHO:=SELF:SERVER:FIELDGET("FERRAM")
SELF:oSFJFERRAMI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJFERRAMI:SERVER:APPEND()
SELF:oSFJFERRAMI:SERVER:FIELDPUT("FERRAM",cDESENHO)
SELF:oSFJFERRAMI:SERVER:commit()
SELF:oSFJFERRAMI:SERVER:resetnotification()
SELF:oSFJFERRAMI:SERVER:notify(notifyappend)
SELF:oSFJFERRAMI:Browser:REFRESH()	

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
local dim aFonts[1] AS OBJECT
local dim aBrushes[1] AS OBJECT

self:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JFER",_GetInst()},iCtlID)

aFonts[1] := Font{,12,"Times New Roman"}
aFonts[1]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCNOME := SingleLineEdit{self,ResourceID{JFER_NOME,_GetInst()}}
oDCNOME:FieldSpec := PADRAO_CHAR_40{}
oDCNOME:HyperLabel := HyperLabel{#NOME,"Nome:",NULL_STRING,"FERRAM_NOME"}

oDCTabControl1 := TabControl{self,ResourceID{JFER_TABCONTROL1,_GetInst()}}
oDCTabControl1:HyperLabel := HyperLabel{#TabControl1,"Cadastro de Ferramentas",NULL_STRING,NULL_STRING}

oDCSC_FERRAM := FixedText{self,ResourceID{JFER_SC_FERRAM,_GetInst()}}
oDCSC_FERRAM:HyperLabel := HyperLabel{#SC_FERRAM,"Ferramenta",NULL_STRING,NULL_STRING}

oDCSC_NOME := FixedText{self,ResourceID{JFER_SC_NOME,_GetInst()}}
oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME,"Descriçao da Ferramenta",NULL_STRING,NULL_STRING}

oDCFERRAM := SingleLineEdit{self,ResourceID{JFER_FERRAM,_GetInst()}}
oDCFERRAM:FieldSpec := PADRAO_CHAR_24{}
oDCFERRAM:HyperLabel := HyperLabel{#FERRAM,"Ferram:",NULL_STRING,"FERRAM_FERRAM"}
oDCFERRAM:BackGround := aBrushes[1]
oDCFERRAM:Font(aFonts[1], FALSE)

oCCcmdCalcular := PushButton{self,ResourceID{JFER_CMDCALCULAR,_GetInst()}}
oCCcmdCalcular:HyperLabel := HyperLabel{#cmdCalcular,"Calcular",NULL_STRING,NULL_STRING}

oCCbusca := PushButton{self,ResourceID{JFER_BUSCA,_GetInst()}}
oCCbusca:Image := ICO_FIND{}
oCCbusca:HyperLabel := HyperLabel{#busca,NULL_STRING,NULL_STRING,NULL_STRING}

oDCTEXTO := FixedText{self,ResourceID{JFER_TEXTO,_GetInst()}}
oDCTEXTO:HyperLabel := HyperLabel{#TEXTO,"Numero",NULL_STRING,NULL_STRING}

oDCNUMERO := SingleLineEdit{self,ResourceID{JFER_NUMERO,_GetInst()}}
oDCNUMERO:FieldSpec := PADRAO_NUM_08{}
oDCNUMERO:HyperLabel := HyperLabel{#NUMERO,"Numero",NULL_STRING,"FERRAM_FERRAM"}
oDCNUMERO:BackGround := aBrushes[1]
oDCNUMERO:Font(aFonts[1], FALSE)

oCCporCOD := PushButton{self,ResourceID{JFER_PORCOD,_GetInst()}}
oCCporCOD:Image := ICO_AZ{}
oCCporCOD:HyperLabel := HyperLabel{#porCOD,NULL_STRING,NULL_STRING,NULL_STRING}
oCCporCOD:TooltipText := "Ordenar Por Numero"

oCCProximo := PushButton{self,ResourceID{JFER_PROXIMO,_GetInst()}}
oCCProximo:HyperLabel := HyperLabel{#Proximo,NULL_STRING,NULL_STRING,NULL_STRING}
oCCProximo:Image := ICO_NEXT{}
oCCProximo:TooltipText := "Avança um Codigo"

oCCAnterior := PushButton{self,ResourceID{JFER_ANTERIOR,_GetInst()}}
oCCAnterior:HyperLabel := HyperLabel{#Anterior,NULL_STRING,NULL_STRING,NULL_STRING}
oCCAnterior:Image := ICO_PREVIOUS{}
oCCAnterior:TooltipText := "Retorno um Codigo"

oCCTabular := PushButton{self,ResourceID{JFER_TABULAR,_GetInst()}}
oCCTabular:HyperLabel := HyperLabel{#Tabular,"Tabular",NULL_STRING,NULL_STRING}
oCCTabular:TooltipText := "Visualiza Todos os Codigo do Grupo"

oCCAlterar := PushButton{self,ResourceID{JFER_ALTERAR,_GetInst()}}
oCCAlterar:HyperLabel := HyperLabel{#Alterar,"Alterar",NULL_STRING,NULL_STRING}
oCCAlterar:TooltipText := "Altera o Codigo em Destaque"

oCCExcluir := PushButton{self,ResourceID{JFER_EXCLUIR,_GetInst()}}
oCCExcluir:HyperLabel := HyperLabel{#Excluir,"Excluir",NULL_STRING,NULL_STRING}
oCCExcluir:TooltipText := "Exclui o o Codigo em Destaque da Lista "

oCCIncluir := PushButton{self,ResourceID{JFER_INCLUIR,_GetInst()}}
oCCIncluir:HyperLabel := HyperLabel{#Incluir,"Incluir",NULL_STRING,NULL_STRING}
oCCIncluir:TooltipText := "Inclui um Codigo para o Grupo"

self:Caption := "Cadastro de Ferramentas"
self:HyperLabel := HyperLabel{#JFER,"Cadastro de Ferramentas",NULL_STRING,NULL_STRING}
self:Menu := STANDARDSHELLMENU{}
self:ClipperKeys := True

if !IsNil(oServer)
	self:Use(oServer)
endif
self:Browser := DataBrowser{self}

oDBFERRAM := DataColumn{PADRAO_CHAR_24{}}
oDBFERRAM:Width := 23
oDBFERRAM:HyperLabel := oDCFERRAM:HyperLabel 
oDBFERRAM:Caption := "Ferram:"
oDBFERRAM:BackGround := aBrushes[1]
self:Browser:AddColumn(oDBFERRAM)

oDBCLIENTE := DataColumn{PADRAO_NUM_08{}}
oDBCLIENTE:Width := 9
oDBCLIENTE:HyperLabel := HyperLabel{#CLIENTE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"} 
oDBCLIENTE:Caption := "Cliente:"
self:Browser:AddColumn(oDBCLIENTE)

oDBNUMERO := DataColumn{PADRAO_NUM_08{}}
oDBNUMERO:Width := 13
oDBNUMERO:HyperLabel := oDCNUMERO:HyperLabel 
oDBNUMERO:Caption := "Numero"
oDBNUMERO:BackGround := aBrushes[1]
self:Browser:AddColumn(oDBNUMERO)


self:ViewAs(#FormView)
oTPTABCONTROL1_PAGE1 := TABCONTROL1_PAGE1{self, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE1,"Basico",oTPTABCONTROL1_PAGE1,0)
oTPTABCONTROL1_PAGE2 := TABCONTROL1_PAGE2{self, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE2,"Preventiva/Vida Util",oTPTABCONTROL1_PAGE2,0)
oTPTABCONTROL1_PAGE3 := TABCONTROL1_PAGE3{self, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE3,"Dimensões/Elaborador",oTPTABCONTROL1_PAGE3,0)
oTPTABCONTROL1_PAGE4 := TABCONTROL1_PAGE4{self, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE4,"Tecnicas",oTPTABCONTROL1_PAGE4,0)
oTPTABCONTROL1_PAGE5 := TABCONTROL1_PAGE5{self, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE5,"Tecnicas II",oTPTABCONTROL1_PAGE5,0)
oDCTabControl1:SelectTab(#TABCONTROL1_PAGE1)

oSFjferrami := jferrami{self,JFER_JFERRAMI}
oSFjferrami:show()

self:PostInit(oWindow,iCtlID,oServer,uExtra)

return self


access NOME() 
return self:FieldGet(#NOME)


assign NOME(uValue) 
self:FieldPut(#NOME, uValue)
return NOME := uValue


access NUMERO() 
return self:FieldGet(#NUMERO)


assign NUMERO(uValue) 
self:FieldPut(#NUMERO, uValue)
return NUMERO := uValue


METHOD Proximo( ) 
SELF:oSFJFERRAMI:SkipNext()
IF SELF:oSFJFERRAMI:Server:Eof
	SELF:oSFJFERRAMI:SkipPrevious()
ENDIF


METHOD Tabular( ) 
	SELF:oSFJFERRAMI:VIEWTABLE()

END CLASS
PARTIAL class TabControl1_Page1 inherit DATAWINDOW 

	protect oDCGRUPO as SINGLELINEEDIT
	protect oDCSC_GRUPO as FIXEDTEXT
	protect oDCCOGCLI as SINGLELINEEDIT
	protect oDCCLIENTE as RIGHTSLE
	protect oDCSC_CLIENTE as FIXEDTEXT
	protect oDCDATADEV as DATESLE
	protect oDCDATAOUT as DATESLE
	protect oDCDATADES as DATESLE
	protect oDCDATAATV as DATESLE
	protect oDCOBS as SINGLELINEEDIT
	protect oDCtheFixedText5 as FIXEDTEXT
	protect oDCtheFixedText6 as FIXEDTEXT
	protect oDCCONTABIL as SINGLELINEEDIT
	protect oCCescfor as PUSHBUTTON
	protect oDCPROPRIA as RADIOBUTTONGROUP
	protect oCCSim as RADIOBUTTON
	protect oCCNao as RADIOBUTTON
	protect oDCTIPOFER as RADIOBUTTONGROUP
	protect oCCRadioButton6 as RADIOBUTTON
	protect oCCRadioButton7 as RADIOBUTTON
	protect oDCNAEMPRESA as RADIOBUTTONGROUP
	protect oCCRadioButton8 as RADIOBUTTON
	protect oCCRadioButton9 as RADIOBUTTON
	protect oDCSITUACAO as RADIOBUTTONGROUP
	protect oCCRadioButton10 as RADIOBUTTON
	protect oCCRadioButton11 as RADIOBUTTON
	protect oCCRadioButton12 as RADIOBUTTON
	protect oCCRadioButton13 as RADIOBUTTON
	protect oCCpegcli as PUSHBUTTON
	protect oCCEstoque as PUSHBUTTON
	protect oCCEstoqueGer as PUSHBUTTON
	protect oCCEstoqueCod as PUSHBUTTON
// 	instance GRUPO 
// 	instance COGCLI 
// 	instance CLIENTE 
// 	instance DATADEV 
// 	instance DATAOUT 
// 	instance DATADES 
// 	instance DATAATV 
// 	instance OBS 
// 	instance CONTABIL 
// 	instance PROPRIA 
// 	instance TIPOFER 
// 	instance NAEMPRESA 
// 	instance SITUACAO 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

access CLIENTE() 
return self:FieldGet(#CLIENTE)


assign CLIENTE(uValue) 
self:FieldPut(#CLIENTE, uValue)
return CLIENTE := uValue


access COGCLI() 
return self:FieldGet(#COGCLI)


assign COGCLI(uValue) 
self:FieldPut(#COGCLI, uValue)
return COGCLI := uValue


access CONTABIL() 
return self:FieldGet(#CONTABIL)


assign CONTABIL(uValue) 
self:FieldPut(#CONTABIL, uValue)
return CONTABIL := uValue


access DATAATV() 
return self:FieldGet(#DATAATV)


assign DATAATV(uValue) 
self:FieldPut(#DATAATV, uValue)
return DATAATV := uValue


access DATADES() 
return self:FieldGet(#DATADES)


assign DATADES(uValue) 
self:FieldPut(#DATADES, uValue)
return DATADES := uValue


access DATADEV() 
return self:FieldGet(#DATADEV)


assign DATADEV(uValue) 
self:FieldPut(#DATADEV, uValue)
return DATADEV := uValue


access DATAOUT() 
return self:FieldGet(#DATAOUT)


assign DATAOUT(uValue) 
self:FieldPut(#DATAOUT, uValue)
return DATAOUT := uValue


access GRUPO() 
return self:FieldGet(#GRUPO)


assign GRUPO(uValue) 
self:FieldPut(#GRUPO, uValue)
return GRUPO := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

self:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabControl1_Page1",_GetInst()},iCtlID)

oDCGRUPO := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE1_GRUPO,_GetInst()}}
oDCGRUPO:FieldSpec := PADRAO_CHAR_24{}
oDCGRUPO:HyperLabel := HyperLabel{#GRUPO,"Grupo:",NULL_STRING,"FERRAM_GRUPO"}

oDCSC_GRUPO := FixedText{self,ResourceID{TABCONTROL1_PAGE1_SC_GRUPO,_GetInst()}}
oDCSC_GRUPO:HyperLabel := HyperLabel{#SC_GRUPO,"Grupo/Final",NULL_STRING,NULL_STRING}

oDCCOGCLI := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE1_COGCLI,_GetInst()}}
oDCCOGCLI:FieldSpec := PADRAO_CHAR_12{}
oDCCOGCLI:HyperLabel := HyperLabel{#COGCLI,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCCLIENTE := rightSle{self,ResourceID{TABCONTROL1_PAGE1_CLIENTE,_GetInst()}}
oDCCLIENTE:FieldSpec := PADRAO_NUM_08{}
oDCCLIENTE:HyperLabel := HyperLabel{#CLIENTE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCSC_CLIENTE := FixedText{self,ResourceID{TABCONTROL1_PAGE1_SC_CLIENTE,_GetInst()}}
oDCSC_CLIENTE:HyperLabel := HyperLabel{#SC_CLIENTE,"Cliente:",NULL_STRING,NULL_STRING}

oDCDATADEV := DateSle{self,ResourceID{TABCONTROL1_PAGE1_DATADEV,_GetInst()}}
oDCDATADEV:FieldSpec := DATE_FIELD{}
oDCDATADEV:HyperLabel := HyperLabel{#DATADEV,"Datap:",NULL_STRING,"FERRAM_DATAP"}

oDCDATAOUT := DateSle{self,ResourceID{TABCONTROL1_PAGE1_DATAOUT,_GetInst()}}
oDCDATAOUT:FieldSpec := DATE_FIELD{}
oDCDATAOUT:HyperLabel := HyperLabel{#DATAOUT,"Datap:",NULL_STRING,"FERRAM_DATAP"}

oDCDATADES := DateSle{self,ResourceID{TABCONTROL1_PAGE1_DATADES,_GetInst()}}
oDCDATADES:FieldSpec := DATE_FIELD{}
oDCDATADES:HyperLabel := HyperLabel{#DATADES,"Datap:",NULL_STRING,"FERRAM_DATAP"}

oDCDATAATV := DateSle{self,ResourceID{TABCONTROL1_PAGE1_DATAATV,_GetInst()}}
oDCDATAATV:FieldSpec := DATE_FIELD{}
oDCDATAATV:HyperLabel := HyperLabel{#DATAATV,"Datap:",NULL_STRING,"FERRAM_DATAP"}

oDCOBS := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE1_OBS,_GetInst()}}
oDCOBS:FieldSpec := PADRAO_CHAR_50{}
oDCOBS:HyperLabel := HyperLabel{#OBS,"Ferram:",NULL_STRING,"FERRAM_FERRAM"}

oDCtheFixedText5 := FixedText{self,ResourceID{TABCONTROL1_PAGE1_THEFIXEDTEXT5,_GetInst()}}
oDCtheFixedText5:HyperLabel := HyperLabel{#theFixedText5,"Observação",NULL_STRING,NULL_STRING}

oDCtheFixedText6 := FixedText{self,ResourceID{TABCONTROL1_PAGE1_THEFIXEDTEXT6,_GetInst()}}
oDCtheFixedText6:HyperLabel := HyperLabel{#theFixedText6,"Nº Ativo/Contabil",NULL_STRING,NULL_STRING}

oDCCONTABIL := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE1_CONTABIL,_GetInst()}}
oDCCONTABIL:FieldSpec := PADRAO_CHAR_08{}
oDCCONTABIL:HyperLabel := HyperLabel{#CONTABIL,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oCCescfor := PushButton{self,ResourceID{TABCONTROL1_PAGE1_ESCFOR,_GetInst()}}
oCCescfor:HyperLabel := HyperLabel{#escfor,"...",NULL_STRING,NULL_STRING}

oCCSim := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_SIM,_GetInst()}}
oCCSim:HyperLabel := HyperLabel{#Sim,"Sim",NULL_STRING,NULL_STRING}

oCCNao := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_NAO,_GetInst()}}
oCCNao:HyperLabel := HyperLabel{#Nao,"Nao",NULL_STRING,NULL_STRING}

oCCRadioButton6 := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_RADIOBUTTON6,_GetInst()}}
oCCRadioButton6:HyperLabel := HyperLabel{#RadioButton6,"Ferramenta",NULL_STRING,NULL_STRING}

oCCRadioButton7 := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_RADIOBUTTON7,_GetInst()}}
oCCRadioButton7:HyperLabel := HyperLabel{#RadioButton7,"Dispositivo",NULL_STRING,NULL_STRING}

oCCRadioButton8 := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_RADIOBUTTON8,_GetInst()}}
oCCRadioButton8:HyperLabel := HyperLabel{#RadioButton8,"Sim",NULL_STRING,NULL_STRING}

oCCRadioButton9 := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_RADIOBUTTON9,_GetInst()}}
oCCRadioButton9:HyperLabel := HyperLabel{#RadioButton9,"Nao",NULL_STRING,NULL_STRING}

oCCRadioButton10 := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_RADIOBUTTON10,_GetInst()}}
oCCRadioButton10:HyperLabel := HyperLabel{#RadioButton10,"Ativa",NULL_STRING,NULL_STRING}

oCCRadioButton11 := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_RADIOBUTTON11,_GetInst()}}
oCCRadioButton11:HyperLabel := HyperLabel{#RadioButton11,"Inativa",NULL_STRING,NULL_STRING}

oCCRadioButton12 := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_RADIOBUTTON12,_GetInst()}}
oCCRadioButton12:HyperLabel := HyperLabel{#RadioButton12,"Outros",NULL_STRING,NULL_STRING}

oCCRadioButton13 := RadioButton{self,ResourceID{TABCONTROL1_PAGE1_RADIOBUTTON13,_GetInst()}}
oCCRadioButton13:HyperLabel := HyperLabel{#RadioButton13,"Devoluçäo",NULL_STRING,NULL_STRING}

oCCpegcli := PushButton{self,ResourceID{TABCONTROL1_PAGE1_PEGCLI,_GetInst()}}
oCCpegcli:HyperLabel := HyperLabel{#pegcli,"-->",NULL_STRING,NULL_STRING}

oCCEstoque := PushButton{self,ResourceID{TABCONTROL1_PAGE1_ESTOQUE,_GetInst()}}
oCCEstoque:HyperLabel := HyperLabel{#Estoque,"Estoque Grupo",NULL_STRING,NULL_STRING}

oCCEstoqueGer := PushButton{self,ResourceID{TABCONTROL1_PAGE1_ESTOQUEGER,_GetInst()}}
oCCEstoqueGer:HyperLabel := HyperLabel{#EstoqueGer,"Estoque Grupo Geral",NULL_STRING,NULL_STRING}

oCCEstoqueCod := PushButton{self,ResourceID{TABCONTROL1_PAGE1_ESTOQUECOD,_GetInst()}}
oCCEstoqueCod:HyperLabel := HyperLabel{#EstoqueCod,"Estoque Codigo ",NULL_STRING,NULL_STRING}

oDCPROPRIA := RadioButtonGroup{self,ResourceID{TABCONTROL1_PAGE1_PROPRIA,_GetInst()}}
oDCPROPRIA:FillUsing({ ;
						{oCCSim,"S"}, ;
						{oCCNao,"N"} ;
						})
oDCPROPRIA:HyperLabel := HyperLabel{#PROPRIA,"Propria",NULL_STRING,NULL_STRING}
oDCPROPRIA:FieldSpec := PADRAO_CHAR_01{}

oDCTIPOFER := RadioButtonGroup{self,ResourceID{TABCONTROL1_PAGE1_TIPOFER,_GetInst()}}
oDCTIPOFER:FillUsing({ ;
						{oCCRadioButton6,"F"}, ;
						{oCCRadioButton7,"D"} ;
						})
oDCTIPOFER:HyperLabel := HyperLabel{#TIPOFER,"Tipo",NULL_STRING,NULL_STRING}
oDCTIPOFER:FieldSpec := PADRAO_CHAR_01{}

oDCNAEMPRESA := RadioButtonGroup{self,ResourceID{TABCONTROL1_PAGE1_NAEMPRESA,_GetInst()}}
oDCNAEMPRESA:FillUsing({ ;
							{oCCRadioButton8,"S"}, ;
							{oCCRadioButton9,"N"} ;
							})
oDCNAEMPRESA:HyperLabel := HyperLabel{#NAEMPRESA,"Considerar Em Estoque",NULL_STRING,NULL_STRING}
oDCNAEMPRESA:FieldSpec := PADRAO_CHAR_01{}

oDCSITUACAO := RadioButtonGroup{self,ResourceID{TABCONTROL1_PAGE1_SITUACAO,_GetInst()}}
oDCSITUACAO:FillUsing({ ;
						{oCCRadioButton10,"A"}, ;
						{oCCRadioButton11,"I"}, ;
						{oCCRadioButton12,"O"}, ;
						{oCCRadioButton13,"D"} ;
						})
oDCSITUACAO:HyperLabel := HyperLabel{#SITUACAO,"Situaçäo",NULL_STRING,NULL_STRING}
oDCSITUACAO:FieldSpec := PADRAO_CHAR_01{}

self:Caption := "DataWindow Caption"
self:HyperLabel := HyperLabel{#TabControl1_Page1,"DataWindow Caption",NULL_STRING,NULL_STRING}
self:ClipperKeys := True

if !IsNil(oServer)
	self:Use(oServer)
else
	self:Use(self:Owner:Server)
endif

self:PostInit(oWindow,iCtlID,oServer,uExtra)

return self


access NAEMPRESA() 
return self:FieldGet(#NAEMPRESA)


assign NAEMPRESA(uValue) 
self:FieldPut(#NAEMPRESA, uValue)
return NAEMPRESA := uValue


access OBS() 
return self:FieldGet(#OBS)


assign OBS(uValue) 
self:FieldPut(#OBS, uValue)
return OBS := uValue


access PROPRIA() 
return self:FieldGet(#PROPRIA)


assign PROPRIA(uValue) 
self:FieldPut(#PROPRIA, uValue)
return PROPRIA := uValue


access SITUACAO() 
return self:FieldGet(#SITUACAO)


assign SITUACAO(uValue) 
self:FieldPut(#SITUACAO, uValue)
return SITUACAO := uValue


access TIPOFER() 
return self:FieldGet(#TIPOFER)


assign TIPOFER(uValue) 
self:FieldPut(#TIPOFER, uValue)
return TIPOFER := uValue


END CLASS
PARTIAL class TabControl1_Page2 inherit DATAWINDOW 

	protect oDCDATHURG as SINGLELINEEDIT
	protect oDCHRURG as SINGLELINEEDIT
	protect oDCtheFixedText10 as FIXEDTEXT
	protect oDCDATHPED as SINGLELINEEDIT
	protect oDCHRPRE as SINGLELINEEDIT
	protect oDCtheFixedText11 as FIXEDTEXT
	protect oDCDATHSAL as SINGLELINEEDIT
	protect oDCHRSAL as SINGLELINEEDIT
	protect oDCtheFixedText12 as FIXEDTEXT
	protect oDCHRBAS as RIGHTSLE
	protect oDCGroupBox2 as GROUPBOX
	protect oDCtheFixedText13 as FIXEDTEXT
	protect oDCDATAURG as SINGLELINEEDIT
	protect oDCQTDEURG as SINGLELINEEDIT
	protect oDCDATAPED as SINGLELINEEDIT
	protect oDCDATASALDO as SINGLELINEEDIT
	protect oDCQTDEPED as SINGLELINEEDIT
	protect oDCQTDESALDO as SINGLELINEEDIT
	protect oDCtheFixedText8 as FIXEDTEXT
	protect oDCtheFixedText7 as FIXEDTEXT
	protect oDCGroupBox1 as GROUPBOX
	protect oDCtheFixedText6 as FIXEDTEXT
	protect oDCQTDEBASE as RIGHTSLE
	protect oDCtheFixedText4 as FIXEDTEXT
	protect oCCcmdCalcular as PUSHBUTTON
	protect oCCRB2 as RADIOBUTTON
	protect oCCRB1 as RADIOBUTTON
	protect oDCPREVER as RADIOBUTTONGROUP
	protect oDCVDDURG as SINGLELINEEDIT
	protect oDCVDURG as SINGLELINEEDIT
	protect oDCtheFixedText9 as FIXEDTEXT
	protect oDCVDDPRE as SINGLELINEEDIT
	protect oDCVDPRE as SINGLELINEEDIT
	protect oDCtheFixedText14 as FIXEDTEXT
	protect oDCQTDETOT as SINGLELINEEDIT
	protect oDCVDBAS as RIGHTSLE
	protect oDCtheFixedText16 as FIXEDTEXT
	protect oDCGroupBox3 as GROUPBOX
	protect oDCVDHDURG as SINGLELINEEDIT
	protect oDCVDHDPRE as SINGLELINEEDIT
	protect oDCHRTOT as SINGLELINEEDIT
	protect oDCVDHURG as SINGLELINEEDIT
	protect oDCVDHPRE as SINGLELINEEDIT
	protect oDCVDHBAS as RIGHTSLE
	protect oDCtheFixedText15 as FIXEDTEXT
	protect oDCtheFixedText17 as FIXEDTEXT
	protect oDCtheFixedText18 as FIXEDTEXT
	protect oDCGroupBox4 as GROUPBOX
// 	instance DATHURG 
// 	instance HRURG 
// 	instance DATHPED 
// 	instance HRPRE 
// 	instance DATHSAL 
// 	instance HRSAL 
// 	instance HRBAS 
// 	instance DATAURG 
// 	instance QTDEURG 
// 	instance DATAPED 
// 	instance DATASALDO 
// 	instance QTDEPED 
// 	instance QTDESALDO 
// 	instance QTDEBASE 
// 	instance PREVER 
// 	instance VDDURG 
// 	instance VDURG 
// 	instance VDDPRE 
// 	instance VDPRE 
// 	instance QTDETOT 
// 	instance VDBAS 
// 	instance VDHDURG 
// 	instance VDHDPRE 
// 	instance HRTOT 
// 	instance VDHURG 
// 	instance VDHPRE 
// 	instance VDHBAS 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

access DATAPED() 
return self:FieldGet(#DATAPED)


assign DATAPED(uValue) 
self:FieldPut(#DATAPED, uValue)
return DATAPED := uValue


access DATASALDO() 
return self:FieldGet(#DATASALDO)


assign DATASALDO(uValue) 
self:FieldPut(#DATASALDO, uValue)
return DATASALDO := uValue


access DATAURG() 
return self:FieldGet(#DATAURG)


assign DATAURG(uValue) 
self:FieldPut(#DATAURG, uValue)
return DATAURG := uValue


access DATHPED() 
return self:FieldGet(#DATHPED)


assign DATHPED(uValue) 
self:FieldPut(#DATHPED, uValue)
return DATHPED := uValue


access DATHSAL() 
return self:FieldGet(#DATHSAL)


assign DATHSAL(uValue) 
self:FieldPut(#DATHSAL, uValue)
return DATHSAL := uValue


access DATHURG() 
return self:FieldGet(#DATHURG)


assign DATHURG(uValue) 
self:FieldPut(#DATHURG, uValue)
return DATHURG := uValue


access HRBAS() 
return self:FieldGet(#HRBAS)


assign HRBAS(uValue) 
self:FieldPut(#HRBAS, uValue)
return HRBAS := uValue


access HRPRE() 
return self:FieldGet(#HRPRE)


assign HRPRE(uValue) 
self:FieldPut(#HRPRE, uValue)
return HRPRE := uValue


access HRSAL() 
return self:FieldGet(#HRSAL)


assign HRSAL(uValue) 
self:FieldPut(#HRSAL, uValue)
return HRSAL := uValue


access HRTOT() 
return self:FieldGet(#HRTOT)


assign HRTOT(uValue) 
self:FieldPut(#HRTOT, uValue)
return HRTOT := uValue


access HRURG() 
return self:FieldGet(#HRURG)


assign HRURG(uValue) 
self:FieldPut(#HRURG, uValue)
return HRURG := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
local dim aFonts[1] AS OBJECT
local dim aBrushes[1] AS OBJECT

self:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabControl1_Page2",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Times New Roman"}
aFonts[1]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCDATHURG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_DATHURG,_GetInst()}}
oDCDATHURG:FieldSpec := DATE_FIELD{}
oDCDATHURG:HyperLabel := HyperLabel{#DATHURG,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATHURG:BackGround := aBrushes[1]
oDCDATHURG:Font(aFonts[1], FALSE)

oDCHRURG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_HRURG,_GetInst()}}
oDCHRURG:FieldSpec := PADRAO_NUM_09_2{}
oDCHRURG:HyperLabel := HyperLabel{#HRURG,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCHRURG:BackGround := aBrushes[1]
oDCHRURG:Font(aFonts[1], FALSE)

oDCtheFixedText10 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT10,_GetInst()}}
oDCtheFixedText10:HyperLabel := HyperLabel{#theFixedText10,"Critica",NULL_STRING,NULL_STRING}

oDCDATHPED := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_DATHPED,_GetInst()}}
oDCDATHPED:FieldSpec := DATE_FIELD{}
oDCDATHPED:HyperLabel := HyperLabel{#DATHPED,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATHPED:BackGround := aBrushes[1]
oDCDATHPED:Font(aFonts[1], FALSE)

oDCHRPRE := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_HRPRE,_GetInst()}}
oDCHRPRE:FieldSpec := PADRAO_NUM_09_2{}
oDCHRPRE:HyperLabel := HyperLabel{#HRPRE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCHRPRE:BackGround := aBrushes[1]
oDCHRPRE:Font(aFonts[1], FALSE)

oDCtheFixedText11 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT11,_GetInst()}}
oDCtheFixedText11:HyperLabel := HyperLabel{#theFixedText11,"Preventiva",NULL_STRING,NULL_STRING}

oDCDATHSAL := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_DATHSAL,_GetInst()}}
oDCDATHSAL:FieldSpec := DATE_FIELD{}
oDCDATHSAL:HyperLabel := HyperLabel{#DATHSAL,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATHSAL:BackGround := aBrushes[1]
oDCDATHSAL:Font(aFonts[1], FALSE)

oDCHRSAL := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_HRSAL,_GetInst()}}
oDCHRSAL:FieldSpec := PADRAO_NUM_09_2{}
oDCHRSAL:HyperLabel := HyperLabel{#HRSAL,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCHRSAL:BackGround := aBrushes[1]
oDCHRSAL:Font(aFonts[1], FALSE)

oDCtheFixedText12 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT12,_GetInst()}}
oDCtheFixedText12:HyperLabel := HyperLabel{#theFixedText12,"Saldo",NULL_STRING,NULL_STRING}

oDCHRBAS := rightSle{self,ResourceID{TABCONTROL1_PAGE2_HRBAS,_GetInst()}}
oDCHRBAS:FieldSpec := PADRAO_NUM_09_2{}
oDCHRBAS:HyperLabel := HyperLabel{#HRBAS,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCGroupBox2 := GroupBox{self,ResourceID{TABCONTROL1_PAGE2_GROUPBOX2,_GetInst()}}
oDCGroupBox2:HyperLabel := HyperLabel{#GroupBox2,"Posição de Preventiva Horas",NULL_STRING,NULL_STRING}

oDCtheFixedText13 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT13,_GetInst()}}
oDCtheFixedText13:HyperLabel := HyperLabel{#theFixedText13,"Referencia:",NULL_STRING,NULL_STRING}

oDCDATAURG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_DATAURG,_GetInst()}}
oDCDATAURG:FieldSpec := DATE_FIELD{}
oDCDATAURG:HyperLabel := HyperLabel{#DATAURG,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATAURG:BackGround := aBrushes[1]
oDCDATAURG:Font(aFonts[1], FALSE)

oDCQTDEURG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_QTDEURG,_GetInst()}}
oDCQTDEURG:FieldSpec := PADRAO_NUM_08{}
oDCQTDEURG:HyperLabel := HyperLabel{#QTDEURG,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCQTDEURG:BackGround := aBrushes[1]
oDCQTDEURG:Font(aFonts[1], FALSE)

oDCDATAPED := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_DATAPED,_GetInst()}}
oDCDATAPED:FieldSpec := DATE_FIELD{}
oDCDATAPED:HyperLabel := HyperLabel{#DATAPED,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATAPED:BackGround := aBrushes[1]
oDCDATAPED:Font(aFonts[1], FALSE)

oDCDATASALDO := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_DATASALDO,_GetInst()}}
oDCDATASALDO:FieldSpec := DATE_FIELD{}
oDCDATASALDO:HyperLabel := HyperLabel{#DATASALDO,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATASALDO:BackGround := aBrushes[1]
oDCDATASALDO:Font(aFonts[1], FALSE)

oDCQTDEPED := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_QTDEPED,_GetInst()}}
oDCQTDEPED:FieldSpec := PADRAO_NUM_08{}
oDCQTDEPED:HyperLabel := HyperLabel{#QTDEPED,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCQTDEPED:BackGround := aBrushes[1]
oDCQTDEPED:Font(aFonts[1], FALSE)

oDCQTDESALDO := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_QTDESALDO,_GetInst()}}
oDCQTDESALDO:FieldSpec := PADRAO_NUM_08{}
oDCQTDESALDO:HyperLabel := HyperLabel{#QTDESALDO,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCQTDESALDO:BackGround := aBrushes[1]
oDCQTDESALDO:Font(aFonts[1], FALSE)

oDCtheFixedText8 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT8,_GetInst()}}
oDCtheFixedText8:HyperLabel := HyperLabel{#theFixedText8,"Critica",NULL_STRING,NULL_STRING}

oDCtheFixedText7 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT7,_GetInst()}}
oDCtheFixedText7:HyperLabel := HyperLabel{#theFixedText7,"Preventiva",NULL_STRING,NULL_STRING}

oDCGroupBox1 := GroupBox{self,ResourceID{TABCONTROL1_PAGE2_GROUPBOX1,_GetInst()}}
oDCGroupBox1:HyperLabel := HyperLabel{#GroupBox1,"Posição de Preventiva Quantidade",NULL_STRING,NULL_STRING}

oDCtheFixedText6 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT6,_GetInst()}}
oDCtheFixedText6:HyperLabel := HyperLabel{#theFixedText6,"Saldo",NULL_STRING,NULL_STRING}

oDCQTDEBASE := rightSle{self,ResourceID{TABCONTROL1_PAGE2_QTDEBASE,_GetInst()}}
oDCQTDEBASE:FieldSpec := PADRAO_NUM_09{}
oDCQTDEBASE:HyperLabel := HyperLabel{#QTDEBASE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCtheFixedText4 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT4,_GetInst()}}
oDCtheFixedText4:HyperLabel := HyperLabel{#theFixedText4,"Referencia:",NULL_STRING,NULL_STRING}

oCCcmdCalcular := PushButton{self,ResourceID{TABCONTROL1_PAGE2_CMDCALCULAR,_GetInst()}}
oCCcmdCalcular:HyperLabel := HyperLabel{#cmdCalcular,"Calcular",NULL_STRING,NULL_STRING}

oCCRB2 := RadioButton{self,ResourceID{TABCONTROL1_PAGE2_RB2,_GetInst()}}
oCCRB2:HyperLabel := HyperLabel{#RB2,"Não",NULL_STRING,NULL_STRING}

oCCRB1 := RadioButton{self,ResourceID{TABCONTROL1_PAGE2_RB1,_GetInst()}}
oCCRB1:HyperLabel := HyperLabel{#RB1,"Sim",NULL_STRING,NULL_STRING}

oDCVDDURG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_VDDURG,_GetInst()}}
oDCVDDURG:FieldSpec := PADRAO_NUM_08{}
oDCVDDURG:HyperLabel := HyperLabel{#VDDURG,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCVDDURG:BackGround := aBrushes[1]
oDCVDDURG:Font(aFonts[1], FALSE)

oDCVDURG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_VDURG,_GetInst()}}
oDCVDURG:FieldSpec := PADRAO_NUM_08{}
oDCVDURG:HyperLabel := HyperLabel{#VDURG,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCVDURG:BackGround := aBrushes[1]
oDCVDURG:Font(aFonts[1], FALSE)

oDCtheFixedText9 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT9,_GetInst()}}
oDCtheFixedText9:HyperLabel := HyperLabel{#theFixedText9,"Critica",NULL_STRING,NULL_STRING}

oDCVDDPRE := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_VDDPRE,_GetInst()}}
oDCVDDPRE:FieldSpec := PADRAO_NUM_08{}
oDCVDDPRE:HyperLabel := HyperLabel{#VDDPRE,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCVDDPRE:BackGround := aBrushes[1]
oDCVDDPRE:Font(aFonts[1], FALSE)

oDCVDPRE := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_VDPRE,_GetInst()}}
oDCVDPRE:FieldSpec := PADRAO_NUM_08{}
oDCVDPRE:HyperLabel := HyperLabel{#VDPRE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCVDPRE:BackGround := aBrushes[1]
oDCVDPRE:Font(aFonts[1], FALSE)

oDCtheFixedText14 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT14,_GetInst()}}
oDCtheFixedText14:HyperLabel := HyperLabel{#theFixedText14,"Preventiva",NULL_STRING,NULL_STRING}

oDCQTDETOT := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_QTDETOT,_GetInst()}}
oDCQTDETOT:FieldSpec := PADRAO_NUM_10{}
oDCQTDETOT:HyperLabel := HyperLabel{#QTDETOT,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCQTDETOT:BackGround := aBrushes[1]
oDCQTDETOT:Font(aFonts[1], FALSE)

oDCVDBAS := rightSle{self,ResourceID{TABCONTROL1_PAGE2_VDBAS,_GetInst()}}
oDCVDBAS:FieldSpec := PADRAO_NUM_07{}
oDCVDBAS:HyperLabel := HyperLabel{#VDBAS,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCtheFixedText16 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT16,_GetInst()}}
oDCtheFixedText16:HyperLabel := HyperLabel{#theFixedText16,"Referencia:",NULL_STRING,NULL_STRING}

oDCGroupBox3 := GroupBox{self,ResourceID{TABCONTROL1_PAGE2_GROUPBOX3,_GetInst()}}
oDCGroupBox3:HyperLabel := HyperLabel{#GroupBox3,"Posição Vida Util Quantidade",NULL_STRING,NULL_STRING}

oDCVDHDURG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_VDHDURG,_GetInst()}}
oDCVDHDURG:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHDURG:HyperLabel := HyperLabel{#VDHDURG,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCVDHDURG:BackGround := aBrushes[1]
oDCVDHDURG:Font(aFonts[1], FALSE)

oDCVDHDPRE := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_VDHDPRE,_GetInst()}}
oDCVDHDPRE:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHDPRE:HyperLabel := HyperLabel{#VDHDPRE,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCVDHDPRE:BackGround := aBrushes[1]
oDCVDHDPRE:Font(aFonts[1], FALSE)

oDCHRTOT := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_HRTOT,_GetInst()}}
oDCHRTOT:FieldSpec := PADRAO_NUM_09_2{}
oDCHRTOT:HyperLabel := HyperLabel{#HRTOT,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCHRTOT:BackGround := aBrushes[1]
oDCHRTOT:Font(aFonts[1], FALSE)

oDCVDHURG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_VDHURG,_GetInst()}}
oDCVDHURG:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHURG:HyperLabel := HyperLabel{#VDHURG,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCVDHURG:BackGround := aBrushes[1]
oDCVDHURG:Font(aFonts[1], FALSE)

oDCVDHPRE := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE2_VDHPRE,_GetInst()}}
oDCVDHPRE:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHPRE:HyperLabel := HyperLabel{#VDHPRE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCVDHPRE:BackGround := aBrushes[1]
oDCVDHPRE:Font(aFonts[1], FALSE)

oDCVDHBAS := rightSle{self,ResourceID{TABCONTROL1_PAGE2_VDHBAS,_GetInst()}}
oDCVDHBAS:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHBAS:HyperLabel := HyperLabel{#VDHBAS,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCtheFixedText15 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT15,_GetInst()}}
oDCtheFixedText15:HyperLabel := HyperLabel{#theFixedText15,"Critica",NULL_STRING,NULL_STRING}

oDCtheFixedText17 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT17,_GetInst()}}
oDCtheFixedText17:HyperLabel := HyperLabel{#theFixedText17,"Preventiva",NULL_STRING,NULL_STRING}

oDCtheFixedText18 := FixedText{self,ResourceID{TABCONTROL1_PAGE2_THEFIXEDTEXT18,_GetInst()}}
oDCtheFixedText18:HyperLabel := HyperLabel{#theFixedText18,"Referencia:",NULL_STRING,NULL_STRING}

oDCGroupBox4 := GroupBox{self,ResourceID{TABCONTROL1_PAGE2_GROUPBOX4,_GetInst()}}
oDCGroupBox4:HyperLabel := HyperLabel{#GroupBox4,"Posição Vida Util Horas",NULL_STRING,NULL_STRING}

oDCPREVER := RadioButtonGroup{self,ResourceID{TABCONTROL1_PAGE2_PREVER,_GetInst()}}
oDCPREVER:FillUsing({ ;
						{oCCRB2,"N"}, ;
						{oCCRB1,"S"} ;
						})
oDCPREVER:HyperLabel := HyperLabel{#PREVER,"Requer Preventiva",NULL_STRING,NULL_STRING}
oDCPREVER:FieldSpec := PADRAO_CHAR_01{}

self:Caption := "DataWindow Caption"
self:HyperLabel := HyperLabel{#TabControl1_Page2,"DataWindow Caption",NULL_STRING,NULL_STRING}
self:ClipperKeys := True

if !IsNil(oServer)
	self:Use(oServer)
else
	self:Use(self:Owner:Server)
endif

self:PostInit(oWindow,iCtlID,oServer,uExtra)

return self


access PREVER() 
return self:FieldGet(#PREVER)


assign PREVER(uValue) 
self:FieldPut(#PREVER, uValue)
return PREVER := uValue


access QTDEBASE() 
return self:FieldGet(#QTDEBASE)


assign QTDEBASE(uValue) 
self:FieldPut(#QTDEBASE, uValue)
return QTDEBASE := uValue


access QTDEPED() 
return self:FieldGet(#QTDEPED)


assign QTDEPED(uValue) 
self:FieldPut(#QTDEPED, uValue)
return QTDEPED := uValue


access QTDESALDO() 
return self:FieldGet(#QTDESALDO)


assign QTDESALDO(uValue) 
self:FieldPut(#QTDESALDO, uValue)
return QTDESALDO := uValue


access QTDETOT() 
return self:FieldGet(#QTDETOT)


assign QTDETOT(uValue) 
self:FieldPut(#QTDETOT, uValue)
return QTDETOT := uValue


access QTDEURG() 
return self:FieldGet(#QTDEURG)


assign QTDEURG(uValue) 
self:FieldPut(#QTDEURG, uValue)
return QTDEURG := uValue


access VDBAS() 
return self:FieldGet(#VDBAS)


assign VDBAS(uValue) 
self:FieldPut(#VDBAS, uValue)
return VDBAS := uValue


access VDDPRE() 
return self:FieldGet(#VDDPRE)


assign VDDPRE(uValue) 
self:FieldPut(#VDDPRE, uValue)
return VDDPRE := uValue


access VDDURG() 
return self:FieldGet(#VDDURG)


assign VDDURG(uValue) 
self:FieldPut(#VDDURG, uValue)
return VDDURG := uValue


access VDHBAS() 
return self:FieldGet(#VDHBAS)


assign VDHBAS(uValue) 
self:FieldPut(#VDHBAS, uValue)
return VDHBAS := uValue


access VDHDPRE() 
return self:FieldGet(#VDHDPRE)


assign VDHDPRE(uValue) 
self:FieldPut(#VDHDPRE, uValue)
return VDHDPRE := uValue


access VDHDURG() 
return self:FieldGet(#VDHDURG)


assign VDHDURG(uValue) 
self:FieldPut(#VDHDURG, uValue)
return VDHDURG := uValue


access VDHPRE() 
return self:FieldGet(#VDHPRE)


assign VDHPRE(uValue) 
self:FieldPut(#VDHPRE, uValue)
return VDHPRE := uValue


access VDHURG() 
return self:FieldGet(#VDHURG)


assign VDHURG(uValue) 
self:FieldPut(#VDHURG, uValue)
return VDHURG := uValue


access VDPRE() 
return self:FieldGet(#VDPRE)


assign VDPRE(uValue) 
self:FieldPut(#VDPRE, uValue)
return VDPRE := uValue


access VDURG() 
return self:FieldGet(#VDURG)


assign VDURG(uValue) 
self:FieldPut(#VDURG, uValue)
return VDURG := uValue


END CLASS
PARTIAL class TABCONTROL1_PAGE3 inherit DATAWINDOW 

	protect oDCVISUALNUM as RIGHTSLE
	protect oDCVISUALNOM as SINGLELINEEDIT
	protect oDCGroupBox1 as GROUPBOX
	protect oDCVISUALOBS as SINGLELINEEDIT
	protect oDCGroupBox2 as GROUPBOX
	protect oDCMEDA as RIGHTSLE
	protect oDCMEDB as RIGHTSLE
	protect oDCMEDC as RIGHTSLE
	protect oDCMEDD as RIGHTSLE
	protect oDCMEDH as RIGHTSLE
	protect oDCPESO as RIGHTSLE
	protect oDCFixedText2 as FIXEDTEXT
	protect oDCFixedText3 as FIXEDTEXT
	protect oDCFixedText4 as FIXEDTEXT
	protect oDCFixedText5 as FIXEDTEXT
	protect oDCFixedText6 as FIXEDTEXT
	protect oDCFixedText7 as FIXEDTEXT
	protect oCCESCRES as PUSHBUTTON
	protect oCCPEGAVA as PUSHBUTTON
	protect oDCSC_DESTINO2 as FIXEDTEXT
	protect oCCfoto as PUSHBUTTON
	protect oDCDATAT as DATESLE
// 	instance VISUALNUM 
// 	instance VISUALNOM 
// 	instance VISUALOBS 
// 	instance MEDA 
// 	instance MEDB 
// 	instance MEDC 
// 	instance MEDD 
// 	instance MEDH 
// 	instance PESO 
// 	instance DATAT 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

access DATAT() 
return self:FieldGet(#DATAT)


assign DATAT(uValue) 
self:FieldPut(#DATAT, uValue)
return DATAT := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
local dim aFonts[1] AS OBJECT
local dim aBrushes[1] AS OBJECT

self:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TABCONTROL1_PAGE3",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Times New Roman"}
aFonts[1]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCVISUALNUM := rightSle{self,ResourceID{TABCONTROL1_PAGE3_VISUALNUM,_GetInst()}}
oDCVISUALNUM:FieldSpec := PADRAO_NUM_08{}
oDCVISUALNUM:HyperLabel := HyperLabel{#VISUALNUM,"Ro:",NULL_STRING,"RO_RO"}

oDCVISUALNOM := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE3_VISUALNOM,_GetInst()}}
oDCVISUALNOM:FieldSpec := PADRAO_CHAR_40{}
oDCVISUALNOM:HyperLabel := HyperLabel{#VISUALNOM,"Ro:",NULL_STRING,"RO_RO"}
oDCVISUALNOM:BackGround := aBrushes[1]
oDCVISUALNOM:Font(aFonts[1], FALSE)

oDCGroupBox1 := GroupBox{self,ResourceID{TABCONTROL1_PAGE3_GROUPBOX1,_GetInst()}}
oDCGroupBox1:HyperLabel := HyperLabel{#GroupBox1,"Elaborador",NULL_STRING,NULL_STRING}

oDCVISUALOBS := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE3_VISUALOBS,_GetInst()}}
oDCVISUALOBS:FieldSpec := PADRAO_CHAR_50{}
oDCVISUALOBS:HyperLabel := HyperLabel{#VISUALOBS,"Ro:",NULL_STRING,"RO_RO"}

oDCGroupBox2 := GroupBox{self,ResourceID{TABCONTROL1_PAGE3_GROUPBOX2,_GetInst()}}
oDCGroupBox2:HyperLabel := HyperLabel{#GroupBox2,"Dimensoes",NULL_STRING,NULL_STRING}

oDCMEDA := rightSle{self,ResourceID{TABCONTROL1_PAGE3_MEDA,_GetInst()}}
oDCMEDA:FieldSpec := PADRAO_NUM_07_3{}
oDCMEDA:HyperLabel := HyperLabel{#MEDA,"Ro:",NULL_STRING,"RO_RO"}

oDCMEDB := rightSle{self,ResourceID{TABCONTROL1_PAGE3_MEDB,_GetInst()}}
oDCMEDB:FieldSpec := PADRAO_NUM_07_3{}
oDCMEDB:HyperLabel := HyperLabel{#MEDB,"Ro:",NULL_STRING,"RO_RO"}

oDCMEDC := rightSle{self,ResourceID{TABCONTROL1_PAGE3_MEDC,_GetInst()}}
oDCMEDC:FieldSpec := PADRAO_NUM_07_3{}
oDCMEDC:HyperLabel := HyperLabel{#MEDC,"Ro:",NULL_STRING,"RO_RO"}

oDCMEDD := rightSle{self,ResourceID{TABCONTROL1_PAGE3_MEDD,_GetInst()}}
oDCMEDD:FieldSpec := PADRAO_NUM_07_3{}
oDCMEDD:HyperLabel := HyperLabel{#MEDD,"Ro:",NULL_STRING,"RO_RO"}

oDCMEDH := rightSle{self,ResourceID{TABCONTROL1_PAGE3_MEDH,_GetInst()}}
oDCMEDH:FieldSpec := PADRAO_NUM_07_3{}
oDCMEDH:HyperLabel := HyperLabel{#MEDH,"Ro:",NULL_STRING,"RO_RO"}

oDCPESO := rightSle{self,ResourceID{TABCONTROL1_PAGE3_PESO,_GetInst()}}
oDCPESO:FieldSpec := PADRAO_NUM_07_3{}
oDCPESO:HyperLabel := HyperLabel{#PESO,"Ro:",NULL_STRING,"RO_RO"}

oDCFixedText2 := FixedText{self,ResourceID{TABCONTROL1_PAGE3_FIXEDTEXT2,_GetInst()}}
oDCFixedText2:HyperLabel := HyperLabel{#FixedText2,"A",NULL_STRING,NULL_STRING}

oDCFixedText3 := FixedText{self,ResourceID{TABCONTROL1_PAGE3_FIXEDTEXT3,_GetInst()}}
oDCFixedText3:HyperLabel := HyperLabel{#FixedText3,"B",NULL_STRING,NULL_STRING}

oDCFixedText4 := FixedText{self,ResourceID{TABCONTROL1_PAGE3_FIXEDTEXT4,_GetInst()}}
oDCFixedText4:HyperLabel := HyperLabel{#FixedText4,"C",NULL_STRING,NULL_STRING}

oDCFixedText5 := FixedText{self,ResourceID{TABCONTROL1_PAGE3_FIXEDTEXT5,_GetInst()}}
oDCFixedText5:HyperLabel := HyperLabel{#FixedText5,"D",NULL_STRING,NULL_STRING}

oDCFixedText6 := FixedText{self,ResourceID{TABCONTROL1_PAGE3_FIXEDTEXT6,_GetInst()}}
oDCFixedText6:HyperLabel := HyperLabel{#FixedText6,"H",NULL_STRING,NULL_STRING}

oDCFixedText7 := FixedText{self,ResourceID{TABCONTROL1_PAGE3_FIXEDTEXT7,_GetInst()}}
oDCFixedText7:HyperLabel := HyperLabel{#FixedText7,"Peso",NULL_STRING,NULL_STRING}

oCCESCRES := PushButton{self,ResourceID{TABCONTROL1_PAGE3_ESCRES,_GetInst()}}
oCCESCRES:HyperLabel := HyperLabel{#ESCRES,"...",NULL_STRING,NULL_STRING}

oCCPEGAVA := PushButton{self,ResourceID{TABCONTROL1_PAGE3_PEGAVA,_GetInst()}}
oCCPEGAVA:HyperLabel := HyperLabel{#PEGAVA,"-->",NULL_STRING,NULL_STRING}

oDCSC_DESTINO2 := FixedText{self,ResourceID{TABCONTROL1_PAGE3_SC_DESTINO2,_GetInst()}}
oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2,"Foto",NULL_STRING,NULL_STRING}

oCCfoto := PushButton{self,ResourceID{TABCONTROL1_PAGE3_FOTO,_GetInst()}}
oCCfoto:HyperLabel := HyperLabel{#foto,NULL_STRING,NULL_STRING,NULL_STRING}
oCCfoto:Image := ICO_CAMERA{}

oDCDATAT := DateSle{self,ResourceID{TABCONTROL1_PAGE3_DATAT,_GetInst()}}
oDCDATAT:FieldSpec := DATE_FIELD{}
oDCDATAT:HyperLabel := HyperLabel{#DATAT,"Datat:",NULL_STRING,"FERRAM_DATAT"}

self:Caption := "DataWindow Caption"
self:HyperLabel := HyperLabel{#TABCONTROL1_PAGE3,"DataWindow Caption",NULL_STRING,NULL_STRING}
self:ClipperKeys := True

if !IsNil(oServer)
	self:Use(oServer)
else
	self:Use(self:Owner:Server)
endif

self:PostInit(oWindow,iCtlID,oServer,uExtra)

return self


access MEDA() 
return self:FieldGet(#MEDA)


assign MEDA(uValue) 
self:FieldPut(#MEDA, uValue)
return MEDA := uValue


access MEDB() 
return self:FieldGet(#MEDB)


assign MEDB(uValue) 
self:FieldPut(#MEDB, uValue)
return MEDB := uValue


access MEDC() 
return self:FieldGet(#MEDC)


assign MEDC(uValue) 
self:FieldPut(#MEDC, uValue)
return MEDC := uValue


access MEDD() 
return self:FieldGet(#MEDD)


assign MEDD(uValue) 
self:FieldPut(#MEDD, uValue)
return MEDD := uValue


access MEDH() 
return self:FieldGet(#MEDH)


assign MEDH(uValue) 
self:FieldPut(#MEDH, uValue)
return MEDH := uValue


access PESO() 
return self:FieldGet(#PESO)


assign PESO(uValue) 
self:FieldPut(#PESO, uValue)
return PESO := uValue


access VISUALNOM() 
return self:FieldGet(#VISUALNOM)


assign VISUALNOM(uValue) 
self:FieldPut(#VISUALNOM, uValue)
return VISUALNOM := uValue


access VISUALNUM() 
return self:FieldGet(#VISUALNUM)


assign VISUALNUM(uValue) 
self:FieldPut(#VISUALNUM, uValue)
return VISUALNUM := uValue


access VISUALOBS() 
return self:FieldGet(#VISUALOBS)


assign VISUALOBS(uValue) 
self:FieldPut(#VISUALOBS, uValue)
return VISUALOBS := uValue


END CLASS
PARTIAL class TabControl1_Page4 inherit DATAWINDOW 

	PROTECT oDBPECA as DataColumn
	PROTECT oDBSEQ as DataColumn
	PROTECT oDBSSQ as DataColumn
	PROTECT oDBOPERN as DataColumn
	PROTECT oDBPECAN as DataColumn
	PROTECT oDBPRENSA as DataColumn
	PROTECT oDBPRENSAN as DataColumn
	PROTECT oDBALTURA as DataColumn
	PROTECT oDBALMOFADA as DataColumn
	PROTECT oDBPINOS as DataColumn
	PROTECT oDBMATCOD as DataColumn
	PROTECT oDBMATNOM as DataColumn
	PROTECT oDBLARG as DataColumn
	PROTECT oDBESPMAT as DataColumn
	PROTECT oDBPASSOFER as DataColumn
	PROTECT oDBPECAROL as DataColumn
	protect oDCSC_PECA as FIXEDTEXT
	protect oDCSC_SEQ as FIXEDTEXT
	protect oDCSC_SSQ as FIXEDTEXT
	protect oDCSC_PRENSA as FIXEDTEXT
	protect oDCSC_ALTURA as FIXEDTEXT
	protect oDCSC_ALMOFADA as FIXEDTEXT
	protect oDCSC_PINOS as FIXEDTEXT
	protect oDCSC_MATCOD as FIXEDTEXT
	protect oDCSC_LARG as FIXEDTEXT
	protect oDCSC_ESPMAT as FIXEDTEXT
	protect oDCSC_PASSOFER as FIXEDTEXT
	protect oDCSC_PECAROL as FIXEDTEXT
	protect oDCPECA as SINGLELINEEDIT
	protect oDCSEQ as RIGHTSLE
	protect oDCSSQ as RIGHTSLE
	protect oDCOPERN as SINGLELINEEDIT
	protect oDCPECAN as SINGLELINEEDIT
	protect oDCPRENSA as SINGLELINEEDIT
	protect oDCPRENSAN as SINGLELINEEDIT
	protect oDCALTURA as SINGLELINEEDIT
	protect oDCALMOFADA as SINGLELINEEDIT
	protect oDCPINOS as SINGLELINEEDIT
	protect oDCMATCOD as SINGLELINEEDIT
	protect oDCMATNOM as SINGLELINEEDIT
	protect oDCLARG as SINGLELINEEDIT
	protect oDCESPMAT as SINGLELINEEDIT
	protect oDCPASSOFER as SINGLELINEEDIT
	protect oDCPECAROL as SINGLELINEEDIT
	protect oCCescprod as PUSHBUTTON
	protect oCCpegcod as PUSHBUTTON
	protect oCCpegseq as PUSHBUTTON
	protect oCCpegprensa as PUSHBUTTON
	protect oCCescprensa as PUSHBUTTON
	protect oCCpegmat as PUSHBUTTON
	protect oCCescmat as PUSHBUTTON
	protect oDCCODMP01 as COMBOBOX
	protect oDCSC_CLIENTE1 as FIXEDTEXT
	protect oCCVERPCP as PUSHBUTTON
	protect oDCSC_DESTINO2 as FIXEDTEXT
	protect oCCfoto as PUSHBUTTON
// 	instance PECA 
// 	instance SEQ 
// 	instance SSQ 
// 	instance OPERN 
// 	instance PECAN 
// 	instance PRENSA 
// 	instance PRENSAN 
// 	instance ALTURA 
// 	instance ALMOFADA 
// 	instance PINOS 
// 	instance MATCOD 
// 	instance MATNOM 
// 	instance LARG 
// 	instance ESPMAT 
// 	instance PASSOFER 
// 	instance PECAROL 
// 	instance CODMP01 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

access ALMOFADA() 
return self:FieldGet(#ALMOFADA)


assign ALMOFADA(uValue) 
self:FieldPut(#ALMOFADA, uValue)
return ALMOFADA := uValue


access ALTURA() 
return self:FieldGet(#ALTURA)


assign ALTURA(uValue) 
self:FieldPut(#ALTURA, uValue)
return ALTURA := uValue


access CODMP01() 
return self:FieldGet(#CODMP01)


assign CODMP01(uValue) 
self:FieldPut(#CODMP01, uValue)
return CODMP01 := uValue


access ESPMAT() 
return self:FieldGet(#ESPMAT)


assign ESPMAT(uValue) 
self:FieldPut(#ESPMAT, uValue)
return ESPMAT := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

self:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabControl1_Page4",_GetInst()},iCtlID)

oDCSC_PECA := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_PECA,_GetInst()}}
oDCSC_PECA:HyperLabel := HyperLabel{#SC_PECA,"Peca:",NULL_STRING,NULL_STRING}

oDCSC_SEQ := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_SEQ,_GetInst()}}
oDCSC_SEQ:HyperLabel := HyperLabel{#SC_SEQ,"Seq:",NULL_STRING,NULL_STRING}

oDCSC_SSQ := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_SSQ,_GetInst()}}
oDCSC_SSQ:HyperLabel := HyperLabel{#SC_SSQ,"Ssq:",NULL_STRING,NULL_STRING}

oDCSC_PRENSA := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_PRENSA,_GetInst()}}
oDCSC_PRENSA:HyperLabel := HyperLabel{#SC_PRENSA,"Prensa:",NULL_STRING,NULL_STRING}

oDCSC_ALTURA := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_ALTURA,_GetInst()}}
oDCSC_ALTURA:HyperLabel := HyperLabel{#SC_ALTURA,"Altura:",NULL_STRING,NULL_STRING}

oDCSC_ALMOFADA := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_ALMOFADA,_GetInst()}}
oDCSC_ALMOFADA:HyperLabel := HyperLabel{#SC_ALMOFADA,"Almofada:",NULL_STRING,NULL_STRING}

oDCSC_PINOS := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_PINOS,_GetInst()}}
oDCSC_PINOS:HyperLabel := HyperLabel{#SC_PINOS,"Pinos:",NULL_STRING,NULL_STRING}

oDCSC_MATCOD := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_MATCOD,_GetInst()}}
oDCSC_MATCOD:HyperLabel := HyperLabel{#SC_MATCOD,"Material",NULL_STRING,NULL_STRING}

oDCSC_LARG := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_LARG,_GetInst()}}
oDCSC_LARG:HyperLabel := HyperLabel{#SC_LARG,"Largura:",NULL_STRING,NULL_STRING}

oDCSC_ESPMAT := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_ESPMAT,_GetInst()}}
oDCSC_ESPMAT:HyperLabel := HyperLabel{#SC_ESPMAT,"Espessura",NULL_STRING,NULL_STRING}

oDCSC_PASSOFER := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_PASSOFER,_GetInst()}}
oDCSC_PASSOFER:HyperLabel := HyperLabel{#SC_PASSOFER,"Passo Ferramenta:",NULL_STRING,NULL_STRING}

oDCSC_PECAROL := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_PECAROL,_GetInst()}}
oDCSC_PECAROL:HyperLabel := HyperLabel{#SC_PECAROL,"Qtdde Peças Rolo",NULL_STRING,NULL_STRING}

oDCPECA := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_PECA,_GetInst()}}
oDCPECA:FieldSpec := PADRAO_CHAR_24{}
oDCPECA:HyperLabel := HyperLabel{#PECA,"Peca:",NULL_STRING,"FERRAM_PECA"}

oDCSEQ := rightSle{self,ResourceID{TABCONTROL1_PAGE4_SEQ,_GetInst()}}
oDCSEQ:FieldSpec := PADRAO_NUM_03{}
oDCSEQ:HyperLabel := HyperLabel{#SEQ,"Seq:",NULL_STRING,"FERRAM_SEQ"}

oDCSSQ := rightSle{self,ResourceID{TABCONTROL1_PAGE4_SSQ,_GetInst()}}
oDCSSQ:FieldSpec := PADRAO_NUM_03{}
oDCSSQ:HyperLabel := HyperLabel{#SSQ,"Ssq:",NULL_STRING,"FERRAM_SSQ"}

oDCOPERN := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_OPERN,_GetInst()}}
oDCOPERN:FieldSpec := PADRAO_CHAR_40{}
oDCOPERN:HyperLabel := HyperLabel{#OPERN,"Opern:",NULL_STRING,"FERRAM_OPERN"}

oDCPECAN := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_PECAN,_GetInst()}}
oDCPECAN:FieldSpec := PADRAO_CHAR_24{}
oDCPECAN:HyperLabel := HyperLabel{#PECAN,"Pecan:",NULL_STRING,"FERRAM_PECAN"}

oDCPRENSA := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_PRENSA,_GetInst()}}
oDCPRENSA:FieldSpec := PADRAO_CHAR_04{}
oDCPRENSA:HyperLabel := HyperLabel{#PRENSA,"Prensa:",NULL_STRING,"FERRAM_PRENSA"}

oDCPRENSAN := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_PRENSAN,_GetInst()}}
oDCPRENSAN:FieldSpec := PADRAO_CHAR_40{}
oDCPRENSAN:HyperLabel := HyperLabel{#PRENSAN,"Prensan:",NULL_STRING,"FERRAM_PRENSAN"}

oDCALTURA := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_ALTURA,_GetInst()}}
oDCALTURA:FieldSpec := PADRAO_CHAR_30{}
oDCALTURA:HyperLabel := HyperLabel{#ALTURA,"Altura:",NULL_STRING,"FERRAM_ALTURA"}

oDCALMOFADA := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_ALMOFADA,_GetInst()}}
oDCALMOFADA:FieldSpec := PADRAO_CHAR_20{}
oDCALMOFADA:HyperLabel := HyperLabel{#ALMOFADA,"Almofada:",NULL_STRING,"FERRAM_ALMOFADA"}

oDCPINOS := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_PINOS,_GetInst()}}
oDCPINOS:FieldSpec := PADRAO_CHAR_30{}
oDCPINOS:HyperLabel := HyperLabel{#PINOS,"Pinos:",NULL_STRING,"FERRAM_PINOS"}

oDCMATCOD := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_MATCOD,_GetInst()}}
oDCMATCOD:FieldSpec := PADRAO_CHAR_24{}
oDCMATCOD:HyperLabel := HyperLabel{#MATCOD,"Matcod:",NULL_STRING,"FERRAM_MATCOD"}

oDCMATNOM := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_MATNOM,_GetInst()}}
oDCMATNOM:FieldSpec := PADRAO_CHAR_100{}
oDCMATNOM:HyperLabel := HyperLabel{#MATNOM,"Matnom:",NULL_STRING,"FERRAM_MATNOM"}

oDCLARG := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_LARG,_GetInst()}}
oDCLARG:FieldSpec := PADRAO_CHAR_30{}
oDCLARG:HyperLabel := HyperLabel{#LARG,"Larg:",NULL_STRING,"FERRAM_LARG"}

oDCESPMAT := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_ESPMAT,_GetInst()}}
oDCESPMAT:FieldSpec := PADRAO_CHAR_30{}
oDCESPMAT:HyperLabel := HyperLabel{#ESPMAT,"Espmat:",NULL_STRING,"FERRAM_ESPMAT"}

oDCPASSOFER := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_PASSOFER,_GetInst()}}
oDCPASSOFER:FieldSpec := PADRAO_CHAR_25{}
oDCPASSOFER:HyperLabel := HyperLabel{#PASSOFER,"Passofer:",NULL_STRING,"FERRAM_PASSOFER"}

oDCPECAROL := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE4_PECAROL,_GetInst()}}
oDCPECAROL:FieldSpec := PADRAO_CHAR_05{}
oDCPECAROL:HyperLabel := HyperLabel{#PECAROL,"Pecarol:",NULL_STRING,"FERRAM_PECAROL"}

oCCescprod := PushButton{self,ResourceID{TABCONTROL1_PAGE4_ESCPROD,_GetInst()}}
oCCescprod:HyperLabel := HyperLabel{#escprod,"...",NULL_STRING,NULL_STRING}

oCCpegcod := PushButton{self,ResourceID{TABCONTROL1_PAGE4_PEGCOD,_GetInst()}}
oCCpegcod:HyperLabel := HyperLabel{#pegcod,"-->",NULL_STRING,NULL_STRING}

oCCpegseq := PushButton{self,ResourceID{TABCONTROL1_PAGE4_PEGSEQ,_GetInst()}}
oCCpegseq:HyperLabel := HyperLabel{#pegseq,"-->",NULL_STRING,NULL_STRING}

oCCpegprensa := PushButton{self,ResourceID{TABCONTROL1_PAGE4_PEGPRENSA,_GetInst()}}
oCCpegprensa:HyperLabel := HyperLabel{#pegprensa,"-->",NULL_STRING,NULL_STRING}

oCCescprensa := PushButton{self,ResourceID{TABCONTROL1_PAGE4_ESCPRENSA,_GetInst()}}
oCCescprensa:HyperLabel := HyperLabel{#escprensa,"...",NULL_STRING,NULL_STRING}

oCCpegmat := PushButton{self,ResourceID{TABCONTROL1_PAGE4_PEGMAT,_GetInst()}}
oCCpegmat:HyperLabel := HyperLabel{#pegmat,"-->",NULL_STRING,NULL_STRING}

oCCescmat := PushButton{self,ResourceID{TABCONTROL1_PAGE4_ESCMAT,_GetInst()}}
oCCescmat:HyperLabel := HyperLabel{#escmat,"...",NULL_STRING,NULL_STRING}

oDCCODMP01 := combobox{self,ResourceID{TABCONTROL1_PAGE4_CODMP01,_GetInst()}}
oDCCODMP01:FillUsing(Self:PEGMP01( ))
oDCCODMP01:HyperLabel := HyperLabel{#CODMP01,NULL_STRING,NULL_STRING,NULL_STRING}
oDCCODMP01:FieldSpec := PADRAO_CHAR_12{}

oDCSC_CLIENTE1 := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_CLIENTE1,_GetInst()}}
oDCSC_CLIENTE1:HyperLabel := HyperLabel{#SC_CLIENTE1,"Tabela Mão de obra",NULL_STRING,NULL_STRING}

oCCVERPCP := PushButton{self,ResourceID{TABCONTROL1_PAGE4_VERPCP,_GetInst()}}
oCCVERPCP:HyperLabel := HyperLabel{#VERPCP,"Ver Composicao Sequencia",NULL_STRING,NULL_STRING}

oDCSC_DESTINO2 := FixedText{self,ResourceID{TABCONTROL1_PAGE4_SC_DESTINO2,_GetInst()}}
oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2,"Foto Peca",NULL_STRING,NULL_STRING}

oCCfoto := PushButton{self,ResourceID{TABCONTROL1_PAGE4_FOTO,_GetInst()}}
oCCfoto:HyperLabel := HyperLabel{#foto,NULL_STRING,NULL_STRING,NULL_STRING}
oCCfoto:Image := ICO_CAMERA{}

self:Caption := "DataWindow Caption"
self:HyperLabel := HyperLabel{#TabControl1_Page4,"DataWindow Caption",NULL_STRING,NULL_STRING}
self:ClipperKeys := True

if !IsNil(oServer)
	self:Use(oServer)
else
	self:Use(self:Owner:Server)
endif
self:Browser := DataBrowser{self}

oDBPECA := DataColumn{PADRAO_CHAR_24{}}
oDBPECA:Width := 6
oDBPECA:HyperLabel := oDCPECA:HyperLabel 
oDBPECA:Caption := "Peca:"
self:Browser:AddColumn(oDBPECA)

oDBSEQ := DataColumn{PADRAO_NUM_03{}}
oDBSEQ:Width := 5
oDBSEQ:HyperLabel := oDCSEQ:HyperLabel 
oDBSEQ:Caption := "Seq:"
self:Browser:AddColumn(oDBSEQ)

oDBSSQ := DataColumn{PADRAO_NUM_03{}}
oDBSSQ:Width := 5
oDBSSQ:HyperLabel := oDCSSQ:HyperLabel 
oDBSSQ:Caption := "Ssq:"
self:Browser:AddColumn(oDBSSQ)

oDBOPERN := DataColumn{PADRAO_CHAR_40{}}
oDBOPERN:Width := 7
oDBOPERN:HyperLabel := oDCOPERN:HyperLabel 
oDBOPERN:Caption := "Opern:"
self:Browser:AddColumn(oDBOPERN)

oDBPECAN := DataColumn{PADRAO_CHAR_24{}}
oDBPECAN:Width := 7
oDBPECAN:HyperLabel := oDCPECAN:HyperLabel 
oDBPECAN:Caption := "Pecan:"
self:Browser:AddColumn(oDBPECAN)

oDBPRENSA := DataColumn{PADRAO_CHAR_04{}}
oDBPRENSA:Width := 8
oDBPRENSA:HyperLabel := oDCPRENSA:HyperLabel 
oDBPRENSA:Caption := "Prensa:"
self:Browser:AddColumn(oDBPRENSA)

oDBPRENSAN := DataColumn{PADRAO_CHAR_40{}}
oDBPRENSAN:Width := 9
oDBPRENSAN:HyperLabel := oDCPRENSAN:HyperLabel 
oDBPRENSAN:Caption := "Prensan:"
self:Browser:AddColumn(oDBPRENSAN)

oDBALTURA := DataColumn{PADRAO_CHAR_30{}}
oDBALTURA:Width := 8
oDBALTURA:HyperLabel := oDCALTURA:HyperLabel 
oDBALTURA:Caption := "Altura:"
self:Browser:AddColumn(oDBALTURA)

oDBALMOFADA := DataColumn{PADRAO_CHAR_20{}}
oDBALMOFADA:Width := 10
oDBALMOFADA:HyperLabel := oDCALMOFADA:HyperLabel 
oDBALMOFADA:Caption := "Almofada:"
self:Browser:AddColumn(oDBALMOFADA)

oDBPINOS := DataColumn{PADRAO_CHAR_30{}}
oDBPINOS:Width := 7
oDBPINOS:HyperLabel := oDCPINOS:HyperLabel 
oDBPINOS:Caption := "Pinos:"
self:Browser:AddColumn(oDBPINOS)

oDBMATCOD := DataColumn{PADRAO_CHAR_24{}}
oDBMATCOD:Width := 8
oDBMATCOD:HyperLabel := oDCMATCOD:HyperLabel 
oDBMATCOD:Caption := "Matcod:"
self:Browser:AddColumn(oDBMATCOD)

oDBMATNOM := DataColumn{PADRAO_CHAR_100{}}
oDBMATNOM:Width := 8
oDBMATNOM:HyperLabel := oDCMATNOM:HyperLabel 
oDBMATNOM:Caption := "Matnom:"
self:Browser:AddColumn(oDBMATNOM)

oDBLARG := DataColumn{PADRAO_CHAR_30{}}
oDBLARG:Width := 6
oDBLARG:HyperLabel := oDCLARG:HyperLabel 
oDBLARG:Caption := "Larg:"
self:Browser:AddColumn(oDBLARG)

oDBESPMAT := DataColumn{PADRAO_CHAR_30{}}
oDBESPMAT:Width := 8
oDBESPMAT:HyperLabel := oDCESPMAT:HyperLabel 
oDBESPMAT:Caption := "Espmat:"
self:Browser:AddColumn(oDBESPMAT)

oDBPASSOFER := DataColumn{PADRAO_CHAR_25{}}
oDBPASSOFER:Width := 10
oDBPASSOFER:HyperLabel := oDCPASSOFER:HyperLabel 
oDBPASSOFER:Caption := "Passofer:"
self:Browser:AddColumn(oDBPASSOFER)

oDBPECAROL := DataColumn{PADRAO_CHAR_05{}}
oDBPECAROL:Width := 9
oDBPECAROL:HyperLabel := oDCPECAROL:HyperLabel 
oDBPECAROL:Caption := "Pecarol:"
self:Browser:AddColumn(oDBPECAROL)


self:ViewAs(#FormView)

self:PostInit(oWindow,iCtlID,oServer,uExtra)

return self


access LARG() 
return self:FieldGet(#LARG)


assign LARG(uValue) 
self:FieldPut(#LARG, uValue)
return LARG := uValue


access MATCOD() 
return self:FieldGet(#MATCOD)


assign MATCOD(uValue) 
self:FieldPut(#MATCOD, uValue)
return MATCOD := uValue


access MATNOM() 
return self:FieldGet(#MATNOM)


assign MATNOM(uValue) 
self:FieldPut(#MATNOM, uValue)
return MATNOM := uValue


access OPERN() 
return self:FieldGet(#OPERN)


assign OPERN(uValue) 
self:FieldPut(#OPERN, uValue)
return OPERN := uValue


access PASSOFER() 
return self:FieldGet(#PASSOFER)


assign PASSOFER(uValue) 
self:FieldPut(#PASSOFER, uValue)
return PASSOFER := uValue


access PECA() 
return self:FieldGet(#PECA)


assign PECA(uValue) 
self:FieldPut(#PECA, uValue)
return PECA := uValue


access PECAN() 
return self:FieldGet(#PECAN)


assign PECAN(uValue) 
self:FieldPut(#PECAN, uValue)
return PECAN := uValue


access PECAROL() 
return self:FieldGet(#PECAROL)


assign PECAROL(uValue) 
self:FieldPut(#PECAROL, uValue)
return PECAROL := uValue


access PINOS() 
return self:FieldGet(#PINOS)


assign PINOS(uValue) 
self:FieldPut(#PINOS, uValue)
return PINOS := uValue


access PRENSA() 
return self:FieldGet(#PRENSA)


assign PRENSA(uValue) 
self:FieldPut(#PRENSA, uValue)
return PRENSA := uValue


access PRENSAN() 
return self:FieldGet(#PRENSAN)


assign PRENSAN(uValue) 
self:FieldPut(#PRENSAN, uValue)
return PRENSAN := uValue


access SEQ() 
return self:FieldGet(#SEQ)


assign SEQ(uValue) 
self:FieldPut(#SEQ, uValue)
return SEQ := uValue


access SSQ() 
return self:FieldGet(#SSQ)


assign SSQ(uValue) 
self:FieldPut(#SSQ, uValue)
return SSQ := uValue


END CLASS
PARTIAL class TabControl1_Page5 inherit DATAWINDOW 

	protect oDCOBST01 as SINGLELINEEDIT
	protect oDCUSADEMI as RADIOBUTTONGROUP
	protect oCCRadioButton1 as RADIOBUTTON
	protect oCCRadioButton2 as RADIOBUTTON
	protect oDCUSADISP as RADIOBUTTONGROUP
	protect oCCRadioButton3 as RADIOBUTTON
	protect oCCRadioButton4 as RADIOBUTTON
	protect oDCFixedText2 as FIXEDTEXT
	protect oDCSC_DATAT2 as FIXEDTEXT
	protect oDCESQL01 as SINGLELINEEDIT
	protect oDCESQL02 as SINGLELINEEDIT
	protect oDCESQL03 as SINGLELINEEDIT
	protect oDCESQL04 as SINGLELINEEDIT
	protect oDCESQL05 as SINGLELINEEDIT
	protect oDCESQL06 as SINGLELINEEDIT
	protect oDCESQL07 as SINGLELINEEDIT
	protect oDCESQL08 as SINGLELINEEDIT
	protect oDCPRATILE as SINGLELINEEDIT
	protect oCCesc11 as PUSHBUTTON
	protect oCCesc12 as PUSHBUTTON
	protect oCCesc13 as PUSHBUTTON
	protect oCCesc14 as PUSHBUTTON
	protect oCCesc15 as PUSHBUTTON
	protect oCCesc16 as PUSHBUTTON
	protect oCCesc17 as PUSHBUTTON
	protect oCCesc18 as PUSHBUTTON
	protect oCCesc28 as PUSHBUTTON
	protect oCCesc27 as PUSHBUTTON
	protect oCCesc26 as PUSHBUTTON
	protect oCCesc25 as PUSHBUTTON
	protect oCCesc24 as PUSHBUTTON
	protect oCCesc23 as PUSHBUTTON
	protect oCCesc22 as PUSHBUTTON
	protect oCCesc21 as PUSHBUTTON
	protect oCCesc38 as PUSHBUTTON
	protect oCCesc37 as PUSHBUTTON
	protect oCCesc36 as PUSHBUTTON
	protect oCCesc35 as PUSHBUTTON
	protect oCCesc34 as PUSHBUTTON
	protect oCCesc33 as PUSHBUTTON
	protect oCCesc32 as PUSHBUTTON
	protect oCCesc31 as PUSHBUTTON
	protect oCCesc48 as PUSHBUTTON
	protect oCCesc47 as PUSHBUTTON
	protect oCCesc46 as PUSHBUTTON
	protect oCCesc45 as PUSHBUTTON
	protect oCCesc44 as PUSHBUTTON
	protect oCCesc43 as PUSHBUTTON
	protect oCCesc42 as PUSHBUTTON
	protect oCCesc41 as PUSHBUTTON
	protect oCCesc58 as PUSHBUTTON
	protect oCCesc57 as PUSHBUTTON
	protect oCCesc56 as PUSHBUTTON
	protect oCCesc55 as PUSHBUTTON
	protect oCCesc54 as PUSHBUTTON
	protect oCCesc53 as PUSHBUTTON
	protect oCCesc52 as PUSHBUTTON
	protect oCCesc51 as PUSHBUTTON
	protect oCCesc68 as PUSHBUTTON
	protect oCCesc67 as PUSHBUTTON
	protect oCCesc66 as PUSHBUTTON
	protect oCCesc65 as PUSHBUTTON
	protect oCCesc64 as PUSHBUTTON
	protect oCCesc63 as PUSHBUTTON
	protect oCCesc62 as PUSHBUTTON
	protect oCCesc61 as PUSHBUTTON
	protect oCCesc78 as PUSHBUTTON
	protect oCCesc77 as PUSHBUTTON
	protect oCCesc76 as PUSHBUTTON
	protect oCCesc75 as PUSHBUTTON
	protect oCCesc74 as PUSHBUTTON
	protect oCCesc73 as PUSHBUTTON
	protect oCCesc72 as PUSHBUTTON
	protect oCCesc71 as PUSHBUTTON
	protect oCCesc88 as PUSHBUTTON
	protect oCCesc87 as PUSHBUTTON
	protect oCCesc86 as PUSHBUTTON
	protect oCCesc85 as PUSHBUTTON
	protect oCCesc84 as PUSHBUTTON
	protect oCCesc83 as PUSHBUTTON
	protect oCCesc82 as PUSHBUTTON
	protect oCCesc81 as PUSHBUTTON
	protect oDCESQTIP as SINGLELINEEDIT
	protect oCCcmdtipalmo as PUSHBUTTON
	protect oCCPushButton65 as PUSHBUTTON
// 	instance OBST01 
// 	instance USADEMI 
// 	instance USADISP 
// 	instance ESQL01 
// 	instance ESQL02 
// 	instance ESQL03 
// 	instance ESQL04 
// 	instance ESQL05 
// 	instance ESQL06 
// 	instance ESQL07 
// 	instance ESQL08 
// 	instance PRATILE 
// 	instance ESQTIP 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

access ESQL01() 
return self:FieldGet(#ESQL01)


assign ESQL01(uValue) 
self:FieldPut(#ESQL01, uValue)
return ESQL01 := uValue


access ESQL02() 
return self:FieldGet(#ESQL02)


assign ESQL02(uValue) 
self:FieldPut(#ESQL02, uValue)
return ESQL02 := uValue


access ESQL03() 
return self:FieldGet(#ESQL03)


assign ESQL03(uValue) 
self:FieldPut(#ESQL03, uValue)
return ESQL03 := uValue


access ESQL04() 
return self:FieldGet(#ESQL04)


assign ESQL04(uValue) 
self:FieldPut(#ESQL04, uValue)
return ESQL04 := uValue


access ESQL05() 
return self:FieldGet(#ESQL05)


assign ESQL05(uValue) 
self:FieldPut(#ESQL05, uValue)
return ESQL05 := uValue


access ESQL06() 
return self:FieldGet(#ESQL06)


assign ESQL06(uValue) 
self:FieldPut(#ESQL06, uValue)
return ESQL06 := uValue


access ESQL07() 
return self:FieldGet(#ESQL07)


assign ESQL07(uValue) 
self:FieldPut(#ESQL07, uValue)
return ESQL07 := uValue


access ESQL08() 
return self:FieldGet(#ESQL08)


assign ESQL08(uValue) 
self:FieldPut(#ESQL08, uValue)
return ESQL08 := uValue


access ESQTIP() 
return self:FieldGet(#ESQTIP)


assign ESQTIP(uValue) 
self:FieldPut(#ESQTIP, uValue)
return ESQTIP := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
local dim aFonts[3] AS OBJECT
local dim aBrushes[1] AS OBJECT

self:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabControl1_Page5",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Wingdings"}
aFonts[1]:Bold := TRUE
aFonts[2] := Font{,8,"Wingdings"}
aFonts[3] := Font{,10,"Times New Roman"}
aFonts[3]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCOBST01 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_OBST01,_GetInst()}}
oDCOBST01:FieldSpec := PADRAO_CHAR_40{}
oDCOBST01:HyperLabel := HyperLabel{#OBST01,"Obst01:",NULL_STRING,"FERRAM_OBST01"}

oCCRadioButton1 := RadioButton{self,ResourceID{TABCONTROL1_PAGE5_RADIOBUTTON1,_GetInst()}}
oCCRadioButton1:HyperLabel := HyperLabel{#RadioButton1,"Sim",NULL_STRING,NULL_STRING}

oCCRadioButton2 := RadioButton{self,ResourceID{TABCONTROL1_PAGE5_RADIOBUTTON2,_GetInst()}}
oCCRadioButton2:HyperLabel := HyperLabel{#RadioButton2,"Não",NULL_STRING,NULL_STRING}

oCCRadioButton3 := RadioButton{self,ResourceID{TABCONTROL1_PAGE5_RADIOBUTTON3,_GetInst()}}
oCCRadioButton3:HyperLabel := HyperLabel{#RadioButton3,"Sim",NULL_STRING,NULL_STRING}

oCCRadioButton4 := RadioButton{self,ResourceID{TABCONTROL1_PAGE5_RADIOBUTTON4,_GetInst()}}
oCCRadioButton4:HyperLabel := HyperLabel{#RadioButton4,"Não",NULL_STRING,NULL_STRING}

oDCFixedText2 := FixedText{self,ResourceID{TABCONTROL1_PAGE5_FIXEDTEXT2,_GetInst()}}
oDCFixedText2:HyperLabel := HyperLabel{#FixedText2,"Obs",NULL_STRING,NULL_STRING}

oDCSC_DATAT2 := FixedText{self,ResourceID{TABCONTROL1_PAGE5_SC_DATAT2,_GetInst()}}
oDCSC_DATAT2:HyperLabel := HyperLabel{#SC_DATAT2,"Pratileira",NULL_STRING,NULL_STRING}

oDCESQL01 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQL01,_GetInst()}}
oDCESQL01:FieldSpec := PADRAO_CHAR_08{}
oDCESQL01:HyperLabel := HyperLabel{#ESQL01,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQL01:BackGround := aBrushes[1]
oDCESQL01:Font(aFonts[1], FALSE)

oDCESQL02 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQL02,_GetInst()}}
oDCESQL02:FieldSpec := PADRAO_CHAR_08{}
oDCESQL02:HyperLabel := HyperLabel{#ESQL02,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQL02:BackGround := aBrushes[1]
oDCESQL02:Font(aFonts[1], FALSE)

oDCESQL03 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQL03,_GetInst()}}
oDCESQL03:FieldSpec := PADRAO_CHAR_08{}
oDCESQL03:HyperLabel := HyperLabel{#ESQL03,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQL03:BackGround := aBrushes[1]
oDCESQL03:Font(aFonts[1], FALSE)

oDCESQL04 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQL04,_GetInst()}}
oDCESQL04:FieldSpec := PADRAO_CHAR_08{}
oDCESQL04:HyperLabel := HyperLabel{#ESQL04,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQL04:BackGround := aBrushes[1]
oDCESQL04:Font(aFonts[1], FALSE)

oDCESQL05 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQL05,_GetInst()}}
oDCESQL05:FieldSpec := PADRAO_CHAR_08{}
oDCESQL05:HyperLabel := HyperLabel{#ESQL05,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQL05:BackGround := aBrushes[1]
oDCESQL05:Font(aFonts[1], FALSE)

oDCESQL06 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQL06,_GetInst()}}
oDCESQL06:FieldSpec := PADRAO_CHAR_08{}
oDCESQL06:HyperLabel := HyperLabel{#ESQL06,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQL06:BackGround := aBrushes[1]
oDCESQL06:Font(aFonts[1], FALSE)

oDCESQL07 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQL07,_GetInst()}}
oDCESQL07:FieldSpec := PADRAO_CHAR_08{}
oDCESQL07:HyperLabel := HyperLabel{#ESQL07,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQL07:BackGround := aBrushes[1]
oDCESQL07:Font(aFonts[1], FALSE)

oDCESQL08 := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQL08,_GetInst()}}
oDCESQL08:FieldSpec := PADRAO_CHAR_08{}
oDCESQL08:HyperLabel := HyperLabel{#ESQL08,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQL08:BackGround := aBrushes[1]
oDCESQL08:Font(aFonts[1], FALSE)

oDCPRATILE := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_PRATILE,_GetInst()}}
oDCPRATILE:FieldSpec := PADRAO_CHAR_05{}
oDCPRATILE:HyperLabel := HyperLabel{#PRATILE,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}

oCCesc11 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC11,_GetInst()}}
oCCesc11:HyperLabel := HyperLabel{#esc11,"l",NULL_STRING,NULL_STRING}
oCCesc11:Font(aFonts[2], FALSE)

oCCesc12 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC12,_GetInst()}}
oCCesc12:HyperLabel := HyperLabel{#esc12,"l",NULL_STRING,NULL_STRING}
oCCesc12:Font(aFonts[2], FALSE)

oCCesc13 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC13,_GetInst()}}
oCCesc13:HyperLabel := HyperLabel{#esc13,"l",NULL_STRING,NULL_STRING}
oCCesc13:Font(aFonts[2], FALSE)

oCCesc14 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC14,_GetInst()}}
oCCesc14:HyperLabel := HyperLabel{#esc14,"l",NULL_STRING,NULL_STRING}
oCCesc14:Font(aFonts[2], FALSE)

oCCesc15 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC15,_GetInst()}}
oCCesc15:HyperLabel := HyperLabel{#esc15,"l",NULL_STRING,NULL_STRING}
oCCesc15:Font(aFonts[2], FALSE)

oCCesc16 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC16,_GetInst()}}
oCCesc16:HyperLabel := HyperLabel{#esc16,"l",NULL_STRING,NULL_STRING}
oCCesc16:Font(aFonts[2], FALSE)

oCCesc17 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC17,_GetInst()}}
oCCesc17:HyperLabel := HyperLabel{#esc17,"l",NULL_STRING,NULL_STRING}
oCCesc17:Font(aFonts[2], FALSE)

oCCesc18 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC18,_GetInst()}}
oCCesc18:HyperLabel := HyperLabel{#esc18,"l",NULL_STRING,NULL_STRING}
oCCesc18:Font(aFonts[2], FALSE)

oCCesc28 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC28,_GetInst()}}
oCCesc28:HyperLabel := HyperLabel{#esc28,"l",NULL_STRING,NULL_STRING}
oCCesc28:Font(aFonts[2], FALSE)

oCCesc27 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC27,_GetInst()}}
oCCesc27:HyperLabel := HyperLabel{#esc27,"l",NULL_STRING,NULL_STRING}
oCCesc27:Font(aFonts[2], FALSE)

oCCesc26 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC26,_GetInst()}}
oCCesc26:HyperLabel := HyperLabel{#esc26,"l",NULL_STRING,NULL_STRING}
oCCesc26:Font(aFonts[2], FALSE)

oCCesc25 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC25,_GetInst()}}
oCCesc25:HyperLabel := HyperLabel{#esc25,"l",NULL_STRING,NULL_STRING}
oCCesc25:Font(aFonts[2], FALSE)

oCCesc24 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC24,_GetInst()}}
oCCesc24:HyperLabel := HyperLabel{#esc24,"l",NULL_STRING,NULL_STRING}
oCCesc24:Font(aFonts[2], FALSE)

oCCesc23 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC23,_GetInst()}}
oCCesc23:HyperLabel := HyperLabel{#esc23,"l",NULL_STRING,NULL_STRING}
oCCesc23:Font(aFonts[2], FALSE)

oCCesc22 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC22,_GetInst()}}
oCCesc22:HyperLabel := HyperLabel{#esc22,"l",NULL_STRING,NULL_STRING}
oCCesc22:Font(aFonts[2], FALSE)

oCCesc21 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC21,_GetInst()}}
oCCesc21:HyperLabel := HyperLabel{#esc21,"l",NULL_STRING,NULL_STRING}
oCCesc21:Font(aFonts[2], FALSE)

oCCesc38 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC38,_GetInst()}}
oCCesc38:HyperLabel := HyperLabel{#esc38,"l",NULL_STRING,NULL_STRING}
oCCesc38:Font(aFonts[2], FALSE)

oCCesc37 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC37,_GetInst()}}
oCCesc37:HyperLabel := HyperLabel{#esc37,"l",NULL_STRING,NULL_STRING}
oCCesc37:Font(aFonts[2], FALSE)

oCCesc36 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC36,_GetInst()}}
oCCesc36:HyperLabel := HyperLabel{#esc36,"l",NULL_STRING,NULL_STRING}
oCCesc36:Font(aFonts[2], FALSE)

oCCesc35 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC35,_GetInst()}}
oCCesc35:HyperLabel := HyperLabel{#esc35,"l",NULL_STRING,NULL_STRING}
oCCesc35:Font(aFonts[2], FALSE)

oCCesc34 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC34,_GetInst()}}
oCCesc34:HyperLabel := HyperLabel{#esc34,"l",NULL_STRING,NULL_STRING}
oCCesc34:Font(aFonts[2], FALSE)

oCCesc33 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC33,_GetInst()}}
oCCesc33:HyperLabel := HyperLabel{#esc33,"l",NULL_STRING,NULL_STRING}
oCCesc33:Font(aFonts[2], FALSE)

oCCesc32 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC32,_GetInst()}}
oCCesc32:HyperLabel := HyperLabel{#esc32,"l",NULL_STRING,NULL_STRING}
oCCesc32:Font(aFonts[2], FALSE)

oCCesc31 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC31,_GetInst()}}
oCCesc31:HyperLabel := HyperLabel{#esc31,"l",NULL_STRING,NULL_STRING}
oCCesc31:Font(aFonts[2], FALSE)

oCCesc48 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC48,_GetInst()}}
oCCesc48:HyperLabel := HyperLabel{#esc48,"l",NULL_STRING,NULL_STRING}
oCCesc48:Font(aFonts[2], FALSE)

oCCesc47 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC47,_GetInst()}}
oCCesc47:HyperLabel := HyperLabel{#esc47,"l",NULL_STRING,NULL_STRING}
oCCesc47:Font(aFonts[2], FALSE)

oCCesc46 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC46,_GetInst()}}
oCCesc46:HyperLabel := HyperLabel{#esc46,"l",NULL_STRING,NULL_STRING}
oCCesc46:Font(aFonts[2], FALSE)

oCCesc45 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC45,_GetInst()}}
oCCesc45:HyperLabel := HyperLabel{#esc45,"l",NULL_STRING,NULL_STRING}
oCCesc45:Font(aFonts[2], FALSE)

oCCesc44 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC44,_GetInst()}}
oCCesc44:HyperLabel := HyperLabel{#esc44,"l",NULL_STRING,NULL_STRING}
oCCesc44:Font(aFonts[2], FALSE)

oCCesc43 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC43,_GetInst()}}
oCCesc43:HyperLabel := HyperLabel{#esc43,"l",NULL_STRING,NULL_STRING}
oCCesc43:Font(aFonts[2], FALSE)

oCCesc42 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC42,_GetInst()}}
oCCesc42:HyperLabel := HyperLabel{#esc42,"l",NULL_STRING,NULL_STRING}
oCCesc42:Font(aFonts[2], FALSE)

oCCesc41 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC41,_GetInst()}}
oCCesc41:HyperLabel := HyperLabel{#esc41,"l",NULL_STRING,NULL_STRING}
oCCesc41:Font(aFonts[2], FALSE)

oCCesc58 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC58,_GetInst()}}
oCCesc58:HyperLabel := HyperLabel{#esc58,"l",NULL_STRING,NULL_STRING}
oCCesc58:Font(aFonts[2], FALSE)

oCCesc57 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC57,_GetInst()}}
oCCesc57:HyperLabel := HyperLabel{#esc57,"l",NULL_STRING,NULL_STRING}
oCCesc57:Font(aFonts[2], FALSE)

oCCesc56 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC56,_GetInst()}}
oCCesc56:HyperLabel := HyperLabel{#esc56,"l",NULL_STRING,NULL_STRING}
oCCesc56:Font(aFonts[2], FALSE)

oCCesc55 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC55,_GetInst()}}
oCCesc55:HyperLabel := HyperLabel{#esc55,"l",NULL_STRING,NULL_STRING}
oCCesc55:Font(aFonts[2], FALSE)

oCCesc54 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC54,_GetInst()}}
oCCesc54:HyperLabel := HyperLabel{#esc54,"l",NULL_STRING,NULL_STRING}
oCCesc54:Font(aFonts[2], FALSE)

oCCesc53 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC53,_GetInst()}}
oCCesc53:HyperLabel := HyperLabel{#esc53,"l",NULL_STRING,NULL_STRING}
oCCesc53:Font(aFonts[2], FALSE)

oCCesc52 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC52,_GetInst()}}
oCCesc52:HyperLabel := HyperLabel{#esc52,"l",NULL_STRING,NULL_STRING}
oCCesc52:Font(aFonts[2], FALSE)

oCCesc51 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC51,_GetInst()}}
oCCesc51:HyperLabel := HyperLabel{#esc51,"l",NULL_STRING,NULL_STRING}
oCCesc51:Font(aFonts[2], FALSE)

oCCesc68 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC68,_GetInst()}}
oCCesc68:HyperLabel := HyperLabel{#esc68,"l",NULL_STRING,NULL_STRING}
oCCesc68:Font(aFonts[2], FALSE)

oCCesc67 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC67,_GetInst()}}
oCCesc67:HyperLabel := HyperLabel{#esc67,"l",NULL_STRING,NULL_STRING}
oCCesc67:Font(aFonts[2], FALSE)

oCCesc66 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC66,_GetInst()}}
oCCesc66:HyperLabel := HyperLabel{#esc66,"l",NULL_STRING,NULL_STRING}
oCCesc66:Font(aFonts[2], FALSE)

oCCesc65 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC65,_GetInst()}}
oCCesc65:HyperLabel := HyperLabel{#esc65,"l",NULL_STRING,NULL_STRING}
oCCesc65:Font(aFonts[2], FALSE)

oCCesc64 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC64,_GetInst()}}
oCCesc64:HyperLabel := HyperLabel{#esc64,"l",NULL_STRING,NULL_STRING}
oCCesc64:Font(aFonts[2], FALSE)

oCCesc63 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC63,_GetInst()}}
oCCesc63:HyperLabel := HyperLabel{#esc63,"l",NULL_STRING,NULL_STRING}
oCCesc63:Font(aFonts[2], FALSE)

oCCesc62 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC62,_GetInst()}}
oCCesc62:HyperLabel := HyperLabel{#esc62,"l",NULL_STRING,NULL_STRING}
oCCesc62:Font(aFonts[2], FALSE)

oCCesc61 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC61,_GetInst()}}
oCCesc61:HyperLabel := HyperLabel{#esc61,"l",NULL_STRING,NULL_STRING}
oCCesc61:Font(aFonts[2], FALSE)

oCCesc78 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC78,_GetInst()}}
oCCesc78:HyperLabel := HyperLabel{#esc78,"l",NULL_STRING,NULL_STRING}
oCCesc78:Font(aFonts[2], FALSE)

oCCesc77 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC77,_GetInst()}}
oCCesc77:HyperLabel := HyperLabel{#esc77,"l",NULL_STRING,NULL_STRING}
oCCesc77:Font(aFonts[2], FALSE)

oCCesc76 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC76,_GetInst()}}
oCCesc76:HyperLabel := HyperLabel{#esc76,"l",NULL_STRING,NULL_STRING}
oCCesc76:Font(aFonts[2], FALSE)

oCCesc75 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC75,_GetInst()}}
oCCesc75:HyperLabel := HyperLabel{#esc75,"l",NULL_STRING,NULL_STRING}
oCCesc75:Font(aFonts[2], FALSE)

oCCesc74 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC74,_GetInst()}}
oCCesc74:HyperLabel := HyperLabel{#esc74,"l",NULL_STRING,NULL_STRING}
oCCesc74:Font(aFonts[2], FALSE)

oCCesc73 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC73,_GetInst()}}
oCCesc73:HyperLabel := HyperLabel{#esc73,"l",NULL_STRING,NULL_STRING}
oCCesc73:Font(aFonts[2], FALSE)

oCCesc72 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC72,_GetInst()}}
oCCesc72:HyperLabel := HyperLabel{#esc72,"l",NULL_STRING,NULL_STRING}
oCCesc72:Font(aFonts[2], FALSE)

oCCesc71 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC71,_GetInst()}}
oCCesc71:HyperLabel := HyperLabel{#esc71,"l",NULL_STRING,NULL_STRING}
oCCesc71:Font(aFonts[2], FALSE)

oCCesc88 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC88,_GetInst()}}
oCCesc88:HyperLabel := HyperLabel{#esc88,"l",NULL_STRING,NULL_STRING}
oCCesc88:Font(aFonts[2], FALSE)

oCCesc87 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC87,_GetInst()}}
oCCesc87:HyperLabel := HyperLabel{#esc87,"l",NULL_STRING,NULL_STRING}
oCCesc87:Font(aFonts[2], FALSE)

oCCesc86 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC86,_GetInst()}}
oCCesc86:HyperLabel := HyperLabel{#esc86,"l",NULL_STRING,NULL_STRING}
oCCesc86:Font(aFonts[2], FALSE)

oCCesc85 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC85,_GetInst()}}
oCCesc85:HyperLabel := HyperLabel{#esc85,"l",NULL_STRING,NULL_STRING}
oCCesc85:Font(aFonts[2], FALSE)

oCCesc84 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC84,_GetInst()}}
oCCesc84:HyperLabel := HyperLabel{#esc84,"l",NULL_STRING,NULL_STRING}
oCCesc84:Font(aFonts[2], FALSE)

oCCesc83 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC83,_GetInst()}}
oCCesc83:HyperLabel := HyperLabel{#esc83,"l",NULL_STRING,NULL_STRING}
oCCesc83:Font(aFonts[2], FALSE)

oCCesc82 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC82,_GetInst()}}
oCCesc82:HyperLabel := HyperLabel{#esc82,"l",NULL_STRING,NULL_STRING}
oCCesc82:Font(aFonts[2], FALSE)

oCCesc81 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_ESC81,_GetInst()}}
oCCesc81:HyperLabel := HyperLabel{#esc81,"l",NULL_STRING,NULL_STRING}
oCCesc81:Font(aFonts[2], FALSE)

oDCESQTIP := SingleLineEdit{self,ResourceID{TABCONTROL1_PAGE5_ESQTIP,_GetInst()}}
oDCESQTIP:FieldSpec := PADRAO_CHAR_01{}
oDCESQTIP:HyperLabel := HyperLabel{#ESQTIP,NULL_STRING,NULL_STRING,"FERRAM_DATAT"}
oDCESQTIP:BackGround := aBrushes[1]
oDCESQTIP:Font(aFonts[3], FALSE)

oCCcmdtipalmo := PushButton{self,ResourceID{TABCONTROL1_PAGE5_CMDTIPALMO,_GetInst()}}
oCCcmdtipalmo:HyperLabel := HyperLabel{#cmdtipalmo,"Tipo Almofados 4x6/8x8",NULL_STRING,NULL_STRING}

oCCPushButton65 := PushButton{self,ResourceID{TABCONTROL1_PAGE5_PUSHBUTTON65,_GetInst()}}
oCCPushButton65:HyperLabel := HyperLabel{#PushButton65,"Importar",NULL_STRING,NULL_STRING}

oDCUSADEMI := RadioButtonGroup{self,ResourceID{TABCONTROL1_PAGE5_USADEMI,_GetInst()}}
oDCUSADEMI:FillUsing({ ;
						{oCCRadioButton1,"S"}, ;
						{oCCRadioButton2,"N"} ;
						})
oDCUSADEMI:HyperLabel := HyperLabel{#USADEMI,"Usa Limitadores",NULL_STRING,NULL_STRING}
oDCUSADEMI:FieldSpec := PADRAO_CHAR_01{}

oDCUSADISP := RadioButtonGroup{self,ResourceID{TABCONTROL1_PAGE5_USADISP,_GetInst()}}
oDCUSADISP:FillUsing({ ;
						{oCCRadioButton3,"S"}, ;
						{oCCRadioButton4,"N"} ;
						})
oDCUSADISP:HyperLabel := HyperLabel{#USADISP,"Usa Dispositivos de Controle",NULL_STRING,NULL_STRING}
oDCUSADISP:FieldSpec := PADRAO_CHAR_01{}

self:Caption := "DataWindow Caption"
self:HyperLabel := HyperLabel{#TabControl1_Page5,"DataWindow Caption",NULL_STRING,NULL_STRING}
self:ClipperKeys := True

if !IsNil(oServer)
	self:Use(oServer)
else
	self:Use(self:Owner:Server)
endif

self:PostInit(oWindow,iCtlID,oServer,uExtra)

return self


access OBST01() 
return self:FieldGet(#OBST01)


assign OBST01(uValue) 
self:FieldPut(#OBST01, uValue)
return OBST01 := uValue


access PRATILE() 
return self:FieldGet(#PRATILE)


assign PRATILE(uValue) 
self:FieldPut(#PRATILE, uValue)
return PRATILE := uValue


access USADEMI() 
return self:FieldGet(#USADEMI)


assign USADEMI(uValue) 
self:FieldPut(#USADEMI, uValue)
return USADEMI := uValue


access USADISP() 
return self:FieldGet(#USADISP)


assign USADISP(uValue) 
self:FieldPut(#USADISP, uValue)
return USADISP := uValue


END CLASS
