FUNC DIFHORAS(H1,H2)
LOCAL nRETU AS FLOAT
nRETU:=0
IF ISNIL(H1)
    RETU nRETU
ENDIF
IF ISNIL(H2)
     RETU nRETU
ENDIF
IF H2<H1 //Saida Menor que Entrada
     RETU nRETU
ENDIF
nRETU:=FLOATFORMAT(CHOR(H2)-CHOR(H1),5,2)
RETU nRETU

FUNC PEGFERRAM(cCODIGO)
LOCAL aRETU:={.F.,"",0,"",""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(cCODIGO)
     RETU aRETU
ENDIF
aDAD:={zCURINI,"FERRAM.DBF",zCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
   RETU ARETU
ENDIF
IF oARQ:USED
    oARQ:GOTOP()
    IF oARQ:SEEK(cCODIGO,.F.)
//         ERRORBOX("Achei"+Ccodigo)
        aRETU[1]:=.T.
        aRETU[2]:=oARQ:FIELDGET("NOME")
        aRETU[3]:=oARQ:FIELDGET("CLIENTE")
        aRETU[4]:=oARQ:FIELDGET("COGCLI")
        aRETU[5]:=oARQ:FIELDGET("TIPOFER")
    ENDIF
    oARQ:CLOSE()
ENDIF
RETU aRETU



