PARTIAL CLASS JLVF
METHOD APPEND() 
alert("Incluisão somente gerando uma ocorrencia")
RETURN .f.

METHOD busca( ) 
	SELF:KeyFind()
//LOCAL oBUSCA AS xBUSCA
//oBUSCA:=xBUSCA{SELF,"Localizar","Digite o Nº "}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF
	

METHOD CHECAR 
LOCAL aDAD AS ARRAY
LOCAL oLVFP AS USEREDE	
LOCAL nITEM AS WORD
LOCAL aRETU AS ARRAY


aRETU:=PEGFERRAM(SELF:SERVER:FIELDGET("FERRAM"))

nITEM:=0
aDAD:={zCURINI,"LVFP.DBF",zCURDIR}
oLVFP:=USEREDE{aDAD}
IF oLVFP:nERRO#0
   RETURN .f.
ENDIF
SELF:oSFJLVFI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJLVFI:GOTOP()
WHILE ! SELF:oSFJLVFI:SERVER:eof
	SELF:oSFJLVFI:SERVER:delete()
	SELF:oSFJLVFI:SERVER:skip()	
ENDDO
oLVFP:GOTOP()
WHILE ! oLVFP:EOF
 	nITEM++
 	IF Empty(oLVFP:FIELDGET("GRUPO")) .OR. oLVFP:FIELDGET("GRUPO")=ARETU[5]  //Tipo (F)er (D)ispo
    	SELF:oSFJLVFI:SERVER:APPEND()	
    	SELF:oSFJLVFI:SERVER:FIELDPUT("LVF",SELF:SERVER:LVF)
  	    SELF:oSFJLVFI:SERVER:FIELDPUT("ITEM",nITEM)
        SELF:oSFJLVFI:SERVER:FIELDPUT("DESCRI",oLVFP:FIELDGET("DESCRI"))
	    SELF:oSFJLVFI:SERVER:commit()
	 ENDIF
	oLVFP:SKIP()
ENDDO
oLVFP:CLOSE()
SELF:oSFJLVFI:SERVER:resetnotification()
SELF:oSFJLVFI:SERVER:notify(notifyfilechange)	
	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("FR","LVF")	

METHOD DELETE() 
alert("Incluisão somente apagando a ocorrencia")


METHOD EditFocusChange(oEditFocusChangeEvent) 
	LOCAL oControl AS Control
//	LOCAL lGotFocus AS LOGIC
	LOCAL aFER AS ARRAY	
	oControl := IIf(oEditFocusChangeEvent == NULL_OBJECT, NULL_OBJECT, oEditFocusChangeEvent:Control)
	IIf(oEditFocusChangeEvent == NULL_OBJECT, FALSE, oEditFocusChangeEvent:GotFocus)      //lGotFocus :=
	SUPER:EditFocusChange(oEditFocusChangeEvent)
	//Put your changes here
	DO CASE	
      CASE oCONTROL:NAMESYM==#LVF
           aFER:=PEGRO(SELF:SERVER:LVF)
           IF aFER[1]=.T.
              SELF:SERVER:FERRAM:=aFER[2]
              SELF:SERVER:NOME:=aFER[3]
           ENDIF
           IF Empty(SELF:SERVER:AREA)
              SELF:SERVER:AREA:=aFER[4]
              SELF:SERVER:DESCRI:=aFER[5]
           ENDIF
           IF Empty(SELF:SERVER:TECNICO)
              SELF:SERVER:TECNICO:=aFER[6]
              SELF:SERVER:TECNOME:=aFER[7]
           ENDIF
	ENDCASE
	RETURN NIL


METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("TECNICO",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("TECNOME",oESCMP04:NOME)
ENDIF

METHOD EXCLUIR 
LOCAL nITEM AS WORD
nITEM:=1
IF  MDG("Apagar Registro") .AND. SELF:oSFJLVFI:server:LockCurrentRecord()
    SELF:oSFJLVFI:server:delete()
    SELF:oSFJLVFI:server:unlock()
    SELF:oSFJLVFI:server:skip(-1)
 ENDIF	
 SELF:oSFJLVFI:server:GOTOP()
 WHILE !  oSFJLVFI:server:EOF
	 SELF:oSFJLVFI:server:ITEM:=nITEM
	SELF:oSFJLVFI:server:SKIP()
         nITEM++
ENDDO
 SELF:oSFJLVFI:server:GOTOP()

METHOD IMPRO 
LOCAL oRO AS USEREDE	
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"RO.DBF",zCURDIR}
oRO:=USEREDE{aDAD}
IF oRO:nERRO#0
    RETU SELF
ENDIF	
oRO:GOTOP()
IF oRO:SEEK(SELF:sERVER:RO)
  	SELF:SERVER:FIELDPUT("DATA",oRO:FIELDGET("DATA"))
   	SELF:SERVER:FIELDPUT("TECNICO",oRO:FIELDGET("TECNICO"))
   	SELF:SERVER:FIELDPUT("TECNOME",oRO:FIELDGET("TECNOME"))
   	SELF:SERVER:FIELDPUT("AREA",oRO:FIELDGET("AREA"))
   	SELF:SERVER:FIELDPUT("DESCRI",oRO:FIELDGET("DESCRI"))
ENDIF
oRO:Close()
		

METHOD INCLUIR 
LOCAL nLVF AS DWORD
LOCAL nITEM AS DWORD
nLVF:=SELF:SERVER:LVF
SELF:oSFJLVFI:SERVER:GOBOTTOM()
nITEM:=SELF:oSFJLVFI:SERVER:ITEM
nITEM++
SELF:oSFJLVFI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJLVFI:SERVER:APPEND()
SELF:oSFJLVFI:SERVER:LVF:=nLVF
SELF:oSFJLVFI:SERVER:ITEM:=nITEM
SELF:oSFJLVFI:SERVER:commit()
SELF:oSFJLVFI:SERVER:resetnotification()
SELF:oSFJLVFI:SERVER:notify(notifyappend)

METHOD ListBoxSelect( oControlEvent ) 
	LOCAL oControl AS Control
	LOCAL aRESP AS ARRAY
	oControl := IIf( oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control )
	SUPER:ListBoxSelect( oControlEvent )
	//Put your changes here
	DO CASE
	       CASE oCONTROL:NAMESYM==#AREA
                             aRESP:=PEGMP05(SELF:SERVER:AREA,ZCURINI,ZCURDIR)
                             IF aRESP[1]=.T.
                                  SELF:SERVER:DESCRI:=aRESP[4]
                             ENDIF
	ENDCASE
RETURN NIL


METHOD NORMAL 
IF SELF:oSFJLVFI:server:OPER01="S"
   SELF:oSFJLVFI:server:OPER01:="N"
ELSE
   SELF:oSFJLVFI:server:OPER01:="S"
ENDIF

METHOD pegcli( ) 
LOCAL aFER AS ARRAY	
   aFER:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
            IF aFER[1]=.T.
               SELF:SERVER:CLINOME:=aFER[2]
            ENDIF		

METHOD pegfer( ) 
LOCAL aFER AS ARRAY
           aFER:=PEGFERRAM(SELF:SERVER:FERRAM)
           IF aFER[1]=.T.
              SELF:SERVER:NOME:=aFER[2]
              IF ! Empty(aFER[3])
                 SELF:SERVER:CLIENTE:=aFER[3]
                 aFER:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
                 IF aFER[1]=.T.
   	              SELF:SERVER:CLINOME:=aFER[2]
                 ENDIF
             ENDIF
           ENDIF
METHOD PEGTEC( ) 
LOCAL aFER,aCOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
            aFER:=PEGMP04(SELF:SERVER:TECNICO,ZCURINI,ZCURDIR,aCOM)
            IF aFER[1]=.T.
               SELF:SERVER:TECNOME:=aFER[2]
            ENDIF
	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF ) 
        SELF:oDCAREA:FillUsing(PEGCOMBO("MP05.DBF","DESCRI","CODIGO"))

 RETURN SELF

METHOD REPARAR 
IF SELF:oSFJLVFI:server:OPER02="S"
   SELF:oSFJLVFI:server:OPER02:="N"
ELSE
   SELF:oSFJLVFI:server:OPER02:="S"
ENDIF


METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJLVFI:SERVER:COMMIT()


END CLASS
FUNC PEGRO(nRO)
LOCAL aRETU:={.F.,"","","","",0,""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(nRO)
     RETU aRETU
ENDIF
aDAD:={zCURINI,"RO.DBF",zCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
oARQ:SEEK(nRO)
IF oARQ:FOUND
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("FERRAM")
   aRETU[3]:=oARQ:FIELDGET("NOME")
   aRETU[4]:=oARQ:FIELDGET("AREA")
   aRETU[5]:=oARQ:FIELDGET("DESCRI")
   aRETU[6]:=oARQ:FIELDGET("TECNICO")
   aRETU[7]:=oARQ:FIELDGET("TECNOME")
ENDIF
oARQ:CLOSE()
RETU aRETU


