PARTIAL CLASS JLVM
METHOD APPEND() 
alert("Incluisão somente gerando uma ocorrencia")
RETU .T.

METHOD busca( ) 
	SELF:KeyFind()
//LOCAL oBUSCA AS xBUSCA
//oBUSCA:=xBUSCA{SELF,"Localizar","Digite o Nº "}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF
	

METHOD CHECAR 
LOCAL aDAD AS ARRAY
LOCAL oLVMP AS USEREDE	
LOCAL nITEM AS WORD
LOCAL cGRUPO AS STRING

cGRUPO:=""
aDAD:=PEGME01(AllTrim(SELF:SERVER:NUMERO),ZCURINI,ZCURDIR)
IF ! aDAD[1]
   RETUrn .f.
ENDIF	
cGRUPO:=aDAD[7] //Joga Variavel Fixar Problema Comparacao ARQUIVO
SELF:SERVER:FIELDPUT("NOME",aDAD[2])
SELF:SERVER:FIELDPUT("CONTABIL",aDAD[3])
SELF:SERVER:FIELDPUT("SETOR",aDAD[4])
SELF:SERVER:FIELDPUT("FABRICANTE",aDAD[5])	
SELF:SERVER:FIELDPUT("MODELO",aDAD[6])			


nITEM:=0
aDAD:={zCURINI,"LVMP.DBF",zCURDIR}
oLVMP:=USEREDE{aDAD}
IF oLVMP:nERRO#0
   RETUrn .f.
ENDIF
SELF:oSFJLVMI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJLVMI:GOTOP()
WHILE ! SELF:oSFJLVMI:SERVER:eof
	SELF:oSFJLVMI:SERVER:delete()
	SELF:oSFJLVMI:SERVER:skip()	
ENDDO
oLVMP:GOTOP()
WHILE ! oLVMP:EOF
	IF Empty(oLVMP:FIELDGET("GRUPO")) .OR. (cGRUPO=oLVMP:FIELDGET("GRUPO"))
	 	nITEM++
    	SELF:oSFJLVMI:SERVER:APPEND()	
	   	SELF:oSFJLVMI:SERVER:FIELDPUT("LVM",SELF:SERVER:LVM)
	   	SELF:oSFJLVMI:SERVER:FIELDPUT("ITEM",nITEM)
	    SELF:oSFJLVMI:SERVER:FIELDPUT("DESCRI",oLVMP:FIELDGET("DESCRI"))
		SELF:oSFJLVMI:SERVER:commit()
	ENDIF
	oLVMP:SKIP()
ENDDO
oLVMP:CLOSE()
SELF:oSFJLVMI:SERVER:resetnotification()
SELF:oSFJLVMI:SERVER:notify(notifyfilechange)
	
	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("FR","LVM")	

METHOD DELETE() 
alert("Incluisão somente apagando a ocorrencia")
RETU .T.

METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("TECNICO",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("TECNOME",oESCMP04:NOME)
ENDIF

METHOD EXCLUIR 
LOCAL nITEM AS WORD
nITEM:=1
IF  MDG("Apagar Registro") .AND. SELF:oSFJLVMI:server:LockCurrentRecord()
    SELF:oSFJLVMI:server:delete()
    SELF:oSFJLVMI:server:unlock()
    SELF:oSFJLVMI:server:skip(-1)
 ENDIF	
 SELF:oSFJLVMI:server:GOTOP()
 WHILE !  oSFJLVMI:server:EOF
	 SELF:oSFJLVMI:server:ITEM:=nITEM
	SELF:oSFJLVMI:server:SKIP()
         nITEM++
ENDDO
SELF:oSFJLVMI:server:GOTOP()




METHOD IMPRO 
LOCAL oRO AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"RO.DBF",zCURDIR}
oRO:=USEREDE{aDAD}
IF oRO:nERRO#0
    RETU SELF
ENDIF	
oRO:GOTOP()
IF oRO:SEEK(SELF:sERVER:RO)
   SELF:SERVER:DATA:=oRO:FIELDGET("DATA")
   SELF:SERVER:HORAS:=oRO:FIELDGET("HORA")
   SELF:SERVER:TECNICO:=oRO:FIELDGET("TECNICO")
   SELF:SERVER:TECNOME:=oRO:FIELDGET("TECNOME")
   IF oRO:FIELDGET("FERRAM")<>SELF:SERVER:NUMERO
   	  SELF:SERVER:NOME:=oRO:FIELDGET("NOME")
   	  SELF:SERVER:NUMERO:=oRO:FIELDGET("FERRAM")
   ENDIF		
ENDIF
oRO:Close()


METHOD INCLUIR 
LOCAL nLVF AS DWORD
LOCAL nITEM AS DWORD
nLVF:=SELF:SERVER:LVF
SELF:oSFJLVMI:SERVER:GOBOTTOM()
nITEM:=SELF:oSFJLVMI:SERVER:ITEM
nITEM++
SELF:oSFJLVMI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJLVMI:SERVER:APPEND()
SELF:oSFJLVMI:SERVER:LVF:=nLVF
SELF:oSFJLVMI:SERVER:ITEM:=nITEM
SELF:oSFJLVMI:SERVER:commit()
SELF:oSFJLVMI:SERVER:resetnotification()
SELF:oSFJLVMI:SERVER:notify(notifyappend)

METHOD NAOAPL 
IF SELF:oSFJLVMI:server:OPER03="S"
   SELF:oSFJLVMI:server:OPER03:="N"
ELSE
   SELF:oSFJLVMI:server:OPER03:="S"
ENDIF

METHOD NORMAL 
IF SELF:oSFJLVMI:server:OPER01="S"
   SELF:oSFJLVMI:server:OPER01:="N"
ELSE
   SELF:oSFJLVMI:server:OPER01:="S"
ENDIF

METHOD pegtec( ) 
LOCAL aFER,aCOM AS ARRAY	
aCOM:={zMES,zANO,ZEMPRESA}
   aFER:=PEGMP04(SELF:SERVER:TECNICO,ZCURINI,ZCURDIR,aCOM)
            IF aFER[1]=.T.
               SELF:SERVER:TECNOME:=aFER[2]
            ENDIF	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD REPARAR 
IF SELF:oSFJLVMI:server:OPER02="S"
   SELF:oSFJLVMI:server:OPER02:="N"
ELSE
   SELF:oSFJLVMI:server:OPER02:="S"
ENDIF

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJLVMI:Server:COMMIT()



END CLASS
