#region DEFINES
STATIC DEFINE JME01_BUSCA := 107 
STATIC DEFINE JME01_FABRICANTE := 105 
STATIC DEFINE JME01_NOME := 101 
STATIC DEFINE JME01_NUMERO := 103 
STATIC DEFINE JME01_ORDEM := 108 
STATIC DEFINE JME01_SC_FERRAM := 100 
STATIC DEFINE JME01_SC_FERRAM1 := 104 
STATIC DEFINE JME01_SC_NOME := 102 
STATIC DEFINE JME01_TABME01 := 106 
STATIC DEFINE TABME01_DATAATV := 113 
STATIC DEFINE TABME01_DATADES := 111 
STATIC DEFINE TABME01_DATADEV := 107 
STATIC DEFINE TABME01_DATAOUT := 109 
STATIC DEFINE TABME01_FOTO := 117 
STATIC DEFINE TABME01_GROUPBOX3 := 106 
STATIC DEFINE TABME01_GRUPO := 119 
STATIC DEFINE TABME01_LUB01 := 104 
STATIC DEFINE TABME01_LUB02 := 102 
STATIC DEFINE TABME01_LUB03 := 100 
STATIC DEFINE TABME01_LUB04 := 103 
STATIC DEFINE TABME01_LUB05 := 101 
STATIC DEFINE TABME01_LUBRI := 105 
STATIC DEFINE TABME01_PAGE2_CMDCALCULAR := 124 
STATIC DEFINE TABME01_PAGE2_DATAPED := 114 
STATIC DEFINE TABME01_PAGE2_DATASALDO := 115 
STATIC DEFINE TABME01_PAGE2_DATAURG := 112 
STATIC DEFINE TABME01_PAGE2_DATHPED := 103 
STATIC DEFINE TABME01_PAGE2_DATHSAL := 106 
STATIC DEFINE TABME01_PAGE2_DATHURG := 100 
STATIC DEFINE TABME01_PAGE2_GROUPBOX1 := 120 
STATIC DEFINE TABME01_PAGE2_GROUPBOX2 := 110 
STATIC DEFINE TABME01_PAGE2_GROUPBOX3 := 137 
STATIC DEFINE TABME01_PAGE2_GROUPBOX4 := 147 
STATIC DEFINE TABME01_PAGE2_HRBAS := 109 
STATIC DEFINE TABME01_PAGE2_HRPRE := 104 
STATIC DEFINE TABME01_PAGE2_HRSAL := 107 
STATIC DEFINE TABME01_PAGE2_HRTOT := 140 
STATIC DEFINE TABME01_PAGE2_HRURG := 101 
STATIC DEFINE TABME01_PAGE2_PREVER := 127 
STATIC DEFINE TABME01_PAGE2_QTDEBASE := 122 
STATIC DEFINE TABME01_PAGE2_QTDEPED := 116 
STATIC DEFINE TABME01_PAGE2_QTDESALDO := 117 
STATIC DEFINE TABME01_PAGE2_QTDETOT := 134 
STATIC DEFINE TABME01_PAGE2_QTDEURG := 113 
STATIC DEFINE TABME01_PAGE2_RB1 := 126 
STATIC DEFINE TABME01_PAGE2_RB2 := 125 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT10 := 102 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT11 := 105 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT12 := 108 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT13 := 111 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT14 := 133 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT15 := 144 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT16 := 136 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT17 := 145 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT18 := 146 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT4 := 123 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT6 := 121 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT7 := 119 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT8 := 118 
STATIC DEFINE TABME01_PAGE2_THEFIXEDTEXT9 := 130 
STATIC DEFINE TABME01_PAGE2_VDBAS := 135 
STATIC DEFINE TABME01_PAGE2_VDDPRE := 131 
STATIC DEFINE TABME01_PAGE2_VDDURG := 128 
STATIC DEFINE TABME01_PAGE2_VDHBAS := 143 
STATIC DEFINE TABME01_PAGE2_VDHDPRE := 139 
STATIC DEFINE TABME01_PAGE2_VDHDURG := 138 
STATIC DEFINE TABME01_PAGE2_VDHPRE := 142 
STATIC DEFINE TABME01_PAGE2_VDHURG := 141 
STATIC DEFINE TABME01_PAGE2_VDPRE := 132 
STATIC DEFINE TABME01_PAGE2_VDURG := 129 
STATIC DEFINE TABME01_PAGE3_ESCRES := 118 
STATIC DEFINE TABME01_PAGE3_FIXEDBITMAP1 := 105 
STATIC DEFINE TABME01_PAGE3_FIXEDTEXT2 := 112 
STATIC DEFINE TABME01_PAGE3_FIXEDTEXT3 := 113 
STATIC DEFINE TABME01_PAGE3_FIXEDTEXT4 := 114 
STATIC DEFINE TABME01_PAGE3_FIXEDTEXT5 := 115 
STATIC DEFINE TABME01_PAGE3_FIXEDTEXT6 := 116 
STATIC DEFINE TABME01_PAGE3_FIXEDTEXT7 := 117 
STATIC DEFINE TABME01_PAGE3_GROUPBOX1 := 102 
STATIC DEFINE TABME01_PAGE3_GROUPBOX2 := 104 
STATIC DEFINE TABME01_PAGE3_MEDA := 106 
STATIC DEFINE TABME01_PAGE3_MEDB := 107 
STATIC DEFINE TABME01_PAGE3_MEDC := 108 
STATIC DEFINE TABME01_PAGE3_MEDD := 109 
STATIC DEFINE TABME01_PAGE3_MEDH := 110 
STATIC DEFINE TABME01_PAGE3_PEGAVA := 119 
STATIC DEFINE TABME01_PAGE3_PESO := 111 
STATIC DEFINE TABME01_PAGE3_VISUALNOM := 101 
STATIC DEFINE TABME01_PAGE3_VISUALNUM := 100 
STATIC DEFINE TABME01_PAGE3_VISUALOBS := 103 
STATIC DEFINE TABME01_SC_DESTINO2 := 116 
STATIC DEFINE TABME01_SC_GRUPO := 120 
STATIC DEFINE TABME01_SITUACAO := 115 
STATIC DEFINE TABME01_THERADIOBUTTON1 := 114 
STATIC DEFINE TABME01_THERADIOBUTTON2 := 112 
STATIC DEFINE TABME01_THERADIOBUTTON3 := 108 
STATIC DEFINE TABME01_THERADIOBUTTON4 := 110 
STATIC DEFINE TABME01_TIPO := 118 
#endregion

PARTIAL CLASS JME01 INHERIT MYDataWindow 

	PROTECT oDBNUMERO AS DataColumn
	PROTECT oDBNOME AS DataColumn
	PROTECT oDBFABRICANTE AS DataColumn
	PROTECT oDCSC_FERRAM AS FIXEDTEXT
	PROTECT oDCNOME AS SINGLELINEEDIT
	PROTECT oDCSC_NOME AS FIXEDTEXT
	PROTECT oDCNUMERO AS SINGLELINEEDIT
	PROTECT oDCSC_FERRAM1 AS FIXEDTEXT
	PROTECT oDCFABRICANTE AS SINGLELINEEDIT
	PROTECT oDCTABME01 AS TABCONTROL
	PROTECT oTPTABME01 AS TABME01
	PROTECT oTPTABME01_PAGE2 AS TABME01_PAGE2
	PROTECT oTPTABME01_PAGE3 AS TABME01_PAGE3
	PROTECT oCCbusca AS PUSHBUTTON
	PROTECT oCCordem AS PUSHBUTTON
// 	instance NOME 
// 	instance NUMERO 
// 	instance FABRICANTE 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS FABRICANTE() 
RETURN SELF:FieldGet(#FABRICANTE)


ASSIGN FABRICANTE(uValue) 
SELF:FieldPut(#FABRICANTE, uValue)
RETURN FABRICANTE := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[2] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JME01",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Times New Roman"}
aFonts[1]:Bold := TRUE
aFonts[2] := Font{,12,"Times New Roman"}
aFonts[2]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCSC_FERRAM := FixedText{SELF,ResourceID{JME01_SC_FERRAM,_GetInst()}}
oDCSC_FERRAM:HyperLabel := HyperLabel{#SC_FERRAM,"Codigo:",NULL_STRING,NULL_STRING}

oDCNOME := SingleLineEdit{SELF,ResourceID{JME01_NOME,_GetInst()}}
oDCNOME:FieldSpec := PADRAO_CHAR_40{}
oDCNOME:HyperLabel := HyperLabel{#NOME,"Nome:",NULL_STRING,"ME01_NOME"}
oDCNOME:BackGround := aBrushes[1]
oDCNOME:Font(aFonts[1], FALSE)

oDCSC_NOME := FixedText{SELF,ResourceID{JME01_SC_NOME,_GetInst()}}
oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME,"Descriçao:",NULL_STRING,NULL_STRING}

oDCNUMERO := SingleLineEdit{SELF,ResourceID{JME01_NUMERO,_GetInst()}}
oDCNUMERO:FieldSpec := PADRAO_CHAR_04{}
oDCNUMERO:HyperLabel := HyperLabel{#NUMERO,"Numero",NULL_STRING,"ME01_NUMERO"}
oDCNUMERO:BackGround := aBrushes[1]
oDCNUMERO:Font(aFonts[2], FALSE)

oDCSC_FERRAM1 := FixedText{SELF,ResourceID{JME01_SC_FERRAM1,_GetInst()}}
oDCSC_FERRAM1:HyperLabel := HyperLabel{#SC_FERRAM1,"Fabricante",NULL_STRING,NULL_STRING}

oDCFABRICANTE := SingleLineEdit{SELF,ResourceID{JME01_FABRICANTE,_GetInst()}}
oDCFABRICANTE:FieldSpec := PADRAO_CHAR_20{}
oDCFABRICANTE:HyperLabel := HyperLabel{#FABRICANTE,"Ferram:",NULL_STRING,"ME01_NUMERO"}
oDCFABRICANTE:BackGround := aBrushes[1]
oDCFABRICANTE:Font(aFonts[1], FALSE)

oDCTABME01 := TabControl{SELF,ResourceID{JME01_TABME01,_GetInst()}}
oDCTABME01:HyperLabel := HyperLabel{#TABME01,NULL_STRING,NULL_STRING,NULL_STRING}

oCCbusca := PushButton{SELF,ResourceID{JME01_BUSCA,_GetInst()}}
oCCbusca:Image := ICO_FIND{}
oCCbusca:HyperLabel := HyperLabel{#busca,NULL_STRING,NULL_STRING,NULL_STRING}

oCCordem := PushButton{SELF,ResourceID{JME01_ORDEM,_GetInst()}}
oCCordem:Image := ico_az{}
oCCordem:HyperLabel := HyperLabel{#ordem,NULL_STRING,NULL_STRING,NULL_STRING}
oCCordem:TooltipText := "Ordenar Por Numero"

SELF:Caption := "Cadastro de Maquinas e Equipamentos"
SELF:HyperLabel := HyperLabel{#JME01,"Cadastro de Maquinas e Equipamentos",NULL_STRING,NULL_STRING}
SELF:Menu := STANDARDSHELLMENU{}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ENDIF
SELF:Browser := DataBrowser{SELF}

oDBNUMERO := DataColumn{PADRAO_CHAR_04{}}
oDBNUMERO:Width := 14
oDBNUMERO:HyperLabel := oDCNUMERO:HyperLabel 
oDBNUMERO:Caption := "Numero"
oDBNUMERO:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBNUMERO)

oDBNOME := DataColumn{PADRAO_CHAR_40{}}
oDBNOME:Width := 18
oDBNOME:HyperLabel := oDCNOME:HyperLabel 
oDBNOME:Caption := "Nome:"
oDBNOME:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBNOME)

oDBFABRICANTE := DataColumn{PADRAO_CHAR_20{}}
oDBFABRICANTE:Width := 28
oDBFABRICANTE:HyperLabel := oDCFABRICANTE:HyperLabel 
oDBFABRICANTE:Caption := "Ferram:"
oDBFABRICANTE:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBFABRICANTE)


SELF:ViewAs(#FormView)
oTPTABME01 := TABME01{SELF, 0}
oDCTABME01:AppendTab(#TABME01,"Basico",oTPTABME01,0)
oTPTABME01_PAGE2 := TABME01_PAGE2{SELF, 0}
oDCTABME01:AppendTab(#TABME01_PAGE2,"Preventiva/VidaUtil",oTPTABME01_PAGE2,0)
oTPTABME01_PAGE3 := TABME01_PAGE3{SELF, 0}
oDCTABME01:AppendTab(#TABME01_PAGE3,"Dimensões/Elaborador",oTPTABME01_PAGE3,0)
oDCTABME01:SelectTab(#TABME01)

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS NOME() 
RETURN SELF:FieldGet(#NOME)


ASSIGN NOME(uValue) 
SELF:FieldPut(#NOME, uValue)
RETURN NOME := uValue


ACCESS NUMERO() 
RETURN SELF:FieldGet(#NUMERO)


ASSIGN NUMERO(uValue) 
SELF:FieldPut(#NUMERO, uValue)
RETURN NUMERO := uValue


METHOD ordem( ) 
	SELF:KeyFind()

END CLASS
PARTIAL CLASS TABME01 INHERIT DATAWINDOW 

	PROTECT oDCLUB03 AS CHECKBOX
	PROTECT oDCLUB05 AS CHECKBOX
	PROTECT oDCLUB02 AS CHECKBOX
	PROTECT oDCLUB04 AS CHECKBOX
	PROTECT oDCLUB01 AS CHECKBOX
	PROTECT oDCLUBRI AS CHECKBOX
	PROTECT oDCGroupBox3 AS GROUPBOX
	PROTECT oDCDATADEV AS DATESLE
	PROTECT oCCtheRadioButton3 AS RADIOBUTTON
	PROTECT oDCDATAOUT AS DATESLE
	PROTECT oCCtheRadioButton4 AS RADIOBUTTON
	PROTECT oDCDATADES AS DATESLE
	PROTECT oCCtheRadioButton2 AS RADIOBUTTON
	PROTECT oDCDATAATV AS DATESLE
	PROTECT oCCtheRadioButton1 AS RADIOBUTTON
	PROTECT oDCSITUACAO AS RADIOBUTTONGROUP
	PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
	PROTECT oCCfoto AS PUSHBUTTON
	PROTECT oDCTIPO AS COMBOBOX
	PROTECT oDCGRUPO AS COMBOBOXEX
	PROTECT oDCSC_GRUPO AS FIXEDTEXT
// 	instance LUB03 
// 	instance LUB05 
// 	instance LUB02 
// 	instance LUB04 
// 	instance LUB01 
// 	instance LUBRI 
// 	instance DATADEV 
// 	instance DATAOUT 
// 	instance DATADES 
// 	instance DATAATV 
// 	instance SITUACAO 
// 	instance TIPO 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS DATAATV() 
RETURN SELF:FieldGet(#DATAATV)


ASSIGN DATAATV(uValue) 
SELF:FieldPut(#DATAATV, uValue)
RETURN DATAATV := uValue


ACCESS DATADES() 
RETURN SELF:FieldGet(#DATADES)


ASSIGN DATADES(uValue) 
SELF:FieldPut(#DATADES, uValue)
RETURN DATADES := uValue


ACCESS DATADEV() 
RETURN SELF:FieldGet(#DATADEV)


ASSIGN DATADEV(uValue) 
SELF:FieldPut(#DATADEV, uValue)
RETURN DATADEV := uValue


ACCESS DATAOUT() 
RETURN SELF:FieldGet(#DATAOUT)


ASSIGN DATAOUT(uValue) 
SELF:FieldPut(#DATAOUT, uValue)
RETURN DATAOUT := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TABME01",_GetInst()},iCtlID)

oDCLUB03 := CheckBox{SELF,ResourceID{TABME01_LUB03,_GetInst()}}
oDCLUB03:HyperLabel := HyperLabel{#LUB03,"Pneumatica",NULL_STRING,"ME01_LUB03"}
oDCLUB03:FieldSpec := LOGIC_FIELD{}

oDCLUB05 := CheckBox{SELF,ResourceID{TABME01_LUB05,_GetInst()}}
oDCLUB05:HyperLabel := HyperLabel{#LUB05,"Cx. Engrenagem",NULL_STRING,"ME01_LUB05"}
oDCLUB05:FieldSpec := LOGIC_FIELD{}

oDCLUB02 := CheckBox{SELF,ResourceID{TABME01_LUB02,_GetInst()}}
oDCLUB02:HyperLabel := HyperLabel{#LUB02,"de Graxa",NULL_STRING,"ME01_LUB02"}
oDCLUB02:FieldSpec := LOGIC_FIELD{}

oDCLUB04 := CheckBox{SELF,ResourceID{TABME01_LUB04,_GetInst()}}
oDCLUB04:HyperLabel := HyperLabel{#LUB04,"Hidraulica",NULL_STRING,"ME01_LUB04"}
oDCLUB04:FieldSpec := LOGIC_FIELD{}

oDCLUB01 := CheckBox{SELF,ResourceID{TABME01_LUB01,_GetInst()}}
oDCLUB01:HyperLabel := HyperLabel{#LUB01,"Do Fuso",NULL_STRING,"ME01_LUB01"}
oDCLUB01:FieldSpec := LOGIC_FIELD{}

oDCLUBRI := CheckBox{SELF,ResourceID{TABME01_LUBRI,_GetInst()}}
oDCLUBRI:HyperLabel := HyperLabel{#LUBRI,"Requer Lubrificação",NULL_STRING,"ME01_LUBRI"}
oDCLUBRI:FieldSpec := LOGIC_FIELD{}

oDCGroupBox3 := GroupBox{SELF,ResourceID{TABME01_GROUPBOX3,_GetInst()}}
oDCGroupBox3:HyperLabel := HyperLabel{#GroupBox3,"Dados Para Lubrificação",NULL_STRING,NULL_STRING}

oDCDATADEV := DateSle{SELF,ResourceID{TABME01_DATADEV,_GetInst()}}
oDCDATADEV:FieldSpec := DATE_FIELD{}
oDCDATADEV:HyperLabel := HyperLabel{#DATADEV,"Datap:",NULL_STRING,"FERRAM_DATAP"}

oCCtheRadioButton3 := RadioButton{SELF,ResourceID{TABME01_THERADIOBUTTON3,_GetInst()}}
oCCtheRadioButton3:HyperLabel := HyperLabel{#theRadioButton3,"Devolvida",NULL_STRING,NULL_STRING}

oDCDATAOUT := DateSle{SELF,ResourceID{TABME01_DATAOUT,_GetInst()}}
oDCDATAOUT:FieldSpec := DATE_FIELD{}
oDCDATAOUT:HyperLabel := HyperLabel{#DATAOUT,"Datap:",NULL_STRING,"FERRAM_DATAP"}

oCCtheRadioButton4 := RadioButton{SELF,ResourceID{TABME01_THERADIOBUTTON4,_GetInst()}}
oCCtheRadioButton4:HyperLabel := HyperLabel{#theRadioButton4,"Outras",NULL_STRING,NULL_STRING}

oDCDATADES := DateSle{SELF,ResourceID{TABME01_DATADES,_GetInst()}}
oDCDATADES:FieldSpec := DATE_FIELD{}
oDCDATADES:HyperLabel := HyperLabel{#DATADES,"Datap:",NULL_STRING,"FERRAM_DATAP"}

oCCtheRadioButton2 := RadioButton{SELF,ResourceID{TABME01_THERADIOBUTTON2,_GetInst()}}
oCCtheRadioButton2:HyperLabel := HyperLabel{#theRadioButton2,"Inativa",NULL_STRING,NULL_STRING}

oDCDATAATV := DateSle{SELF,ResourceID{TABME01_DATAATV,_GetInst()}}
oDCDATAATV:FieldSpec := DATE_FIELD{}
oDCDATAATV:HyperLabel := HyperLabel{#DATAATV,"Datap:",NULL_STRING,"FERRAM_DATAP"}

oCCtheRadioButton1 := RadioButton{SELF,ResourceID{TABME01_THERADIOBUTTON1,_GetInst()}}
oCCtheRadioButton1:HyperLabel := HyperLabel{#theRadioButton1,"Ativa",NULL_STRING,NULL_STRING}

oDCSC_DESTINO2 := FixedText{SELF,ResourceID{TABME01_SC_DESTINO2,_GetInst()}}
oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2,"Foto",NULL_STRING,NULL_STRING}

oCCfoto := PushButton{SELF,ResourceID{TABME01_FOTO,_GetInst()}}
oCCfoto:HyperLabel := HyperLabel{#foto,NULL_STRING,NULL_STRING,NULL_STRING}
oCCfoto:Image := ICO_CAMERA{}

oDCTIPO := combobox{SELF,ResourceID{TABME01_TIPO,_GetInst()}}
oDCTIPO:FieldSpec := PADRAO_CHAR_01{}
oDCTIPO:FillUsing(SELF:TABTIPO( ))
oDCTIPO:HyperLabel := HyperLabel{#TIPO,NULL_STRING,NULL_STRING,NULL_STRING}

oDCGRUPO := comboboxex{SELF,ResourceID{TABME01_GRUPO,_GetInst()}}
oDCGRUPO:FieldSpec := PADRAO_CHAR_03{}
oDCGRUPO:FillUsing(SELF:PEGGRU( ))
oDCGRUPO:HyperLabel := HyperLabel{#GRUPO,NULL_STRING,NULL_STRING,NULL_STRING}

oDCSC_GRUPO := FixedText{SELF,ResourceID{TABME01_SC_GRUPO,_GetInst()}}
oDCSC_GRUPO:HyperLabel := HyperLabel{#SC_GRUPO,"Grupo:",NULL_STRING,NULL_STRING}

oDCSITUACAO := RadioButtonGroup{SELF,ResourceID{TABME01_SITUACAO,_GetInst()}}
oDCSITUACAO:FillUsing({ ;
						{oCCtheRadioButton3,"D"}, ;
						{oCCtheRadioButton4,"O"}, ;
						{oCCtheRadioButton2,"I"}, ;
						{oCCtheRadioButton1,"A"} ;
						})
oDCSITUACAO:HyperLabel := HyperLabel{#SITUACAO,"Situação",NULL_STRING,NULL_STRING}
oDCSITUACAO:FieldSpec := PADRAO_CHAR_01{}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TABME01,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS LUB01() 
RETURN SELF:FieldGet(#LUB01)


ASSIGN LUB01(uValue) 
SELF:FieldPut(#LUB01, uValue)
RETURN LUB01 := uValue


ACCESS LUB02() 
RETURN SELF:FieldGet(#LUB02)


ASSIGN LUB02(uValue) 
SELF:FieldPut(#LUB02, uValue)
RETURN LUB02 := uValue


ACCESS LUB03() 
RETURN SELF:FieldGet(#LUB03)


ASSIGN LUB03(uValue) 
SELF:FieldPut(#LUB03, uValue)
RETURN LUB03 := uValue


ACCESS LUB04() 
RETURN SELF:FieldGet(#LUB04)


ASSIGN LUB04(uValue) 
SELF:FieldPut(#LUB04, uValue)
RETURN LUB04 := uValue


ACCESS LUB05() 
RETURN SELF:FieldGet(#LUB05)


ASSIGN LUB05(uValue) 
SELF:FieldPut(#LUB05, uValue)
RETURN LUB05 := uValue


ACCESS LUBRI() 
RETURN SELF:FieldGet(#LUBRI)


ASSIGN LUBRI(uValue) 
SELF:FieldPut(#LUBRI, uValue)
RETURN LUBRI := uValue


ACCESS SITUACAO() 
RETURN SELF:FieldGet(#SITUACAO)


ASSIGN SITUACAO(uValue) 
SELF:FieldPut(#SITUACAO, uValue)
RETURN SITUACAO := uValue


ACCESS TIPO() 
RETURN SELF:FieldGet(#TIPO)


ASSIGN TIPO(uValue) 
SELF:FieldPut(#TIPO, uValue)
RETURN TIPO := uValue


END CLASS
CLASS TABME01_Page2 INHERIT DATAWINDOW 

	PROTECT oDCDATHURG AS SINGLELINEEDIT
	PROTECT oDCHRURG AS SINGLELINEEDIT
	PROTECT oDCtheFixedText10 AS FIXEDTEXT
	PROTECT oDCDATHPED AS SINGLELINEEDIT
	PROTECT oDCHRPRE AS SINGLELINEEDIT
	PROTECT oDCtheFixedText11 AS FIXEDTEXT
	PROTECT oDCDATHSAL AS SINGLELINEEDIT
	PROTECT oDCHRSAL AS SINGLELINEEDIT
	PROTECT oDCtheFixedText12 AS FIXEDTEXT
	PROTECT oDCHRBAS AS RIGHTSLE
	PROTECT oDCGroupBox2 AS GROUPBOX
	PROTECT oDCtheFixedText13 AS FIXEDTEXT
	PROTECT oDCDATAURG AS SINGLELINEEDIT
	PROTECT oDCQTDEURG AS SINGLELINEEDIT
	PROTECT oDCDATAPED AS SINGLELINEEDIT
	PROTECT oDCDATASALDO AS SINGLELINEEDIT
	PROTECT oDCQTDEPED AS SINGLELINEEDIT
	PROTECT oDCQTDESALDO AS SINGLELINEEDIT
	PROTECT oDCtheFixedText8 AS FIXEDTEXT
	PROTECT oDCtheFixedText7 AS FIXEDTEXT
	PROTECT oDCGroupBox1 AS GROUPBOX
	PROTECT oDCtheFixedText6 AS FIXEDTEXT
	PROTECT oDCQTDEBASE AS RIGHTSLE
	PROTECT oDCtheFixedText4 AS FIXEDTEXT
	PROTECT oCCcmdCalcular AS PUSHBUTTON
	PROTECT oCCRB2 AS RADIOBUTTON
	PROTECT oCCRB1 AS RADIOBUTTON
	PROTECT oDCPREVER AS RADIOBUTTONGROUP
	PROTECT oDCVDDURG AS SINGLELINEEDIT
	PROTECT oDCVDURG AS SINGLELINEEDIT
	PROTECT oDCtheFixedText9 AS FIXEDTEXT
	PROTECT oDCVDDPRE AS SINGLELINEEDIT
	PROTECT oDCVDPRE AS SINGLELINEEDIT
	PROTECT oDCtheFixedText14 AS FIXEDTEXT
	PROTECT oDCQTDETOT AS SINGLELINEEDIT
	PROTECT oDCVDBAS AS RIGHTSLE
	PROTECT oDCtheFixedText16 AS FIXEDTEXT
	PROTECT oDCGroupBox3 AS GROUPBOX
	PROTECT oDCVDHDURG AS SINGLELINEEDIT
	PROTECT oDCVDHDPRE AS SINGLELINEEDIT
	PROTECT oDCHRTOT AS SINGLELINEEDIT
	PROTECT oDCVDHURG AS SINGLELINEEDIT
	PROTECT oDCVDHPRE AS SINGLELINEEDIT
	PROTECT oDCVDHBAS AS RIGHTSLE
	PROTECT oDCtheFixedText15 AS FIXEDTEXT
	PROTECT oDCtheFixedText17 AS FIXEDTEXT
	PROTECT oDCtheFixedText18 AS FIXEDTEXT
	PROTECT oDCGroupBox4 AS GROUPBOX
// 	instance DATHURG 
// 	instance HRURG 
// 	instance DATHPED 
// 	instance HRPRE 
// 	instance DATHSAL 
// 	instance HRSAL 
// 	instance HRBAS 
// 	instance DATAURG 
// 	instance QTDEURG 
// 	instance DATAPED 
// 	instance DATASALDO 
// 	instance QTDEPED 
// 	instance QTDESALDO 
// 	instance QTDEBASE 
// 	instance PREVER 
// 	instance VDDURG 
// 	instance VDURG 
// 	instance VDDPRE 
// 	instance VDPRE 
// 	instance QTDETOT 
// 	instance VDBAS 
// 	instance VDHDURG 
// 	instance VDHDPRE 
// 	instance HRTOT 
// 	instance VDHURG 
// 	instance VDHPRE 
// 	instance VDHBAS 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS DATAPED() 
RETURN SELF:FieldGet(#DATAPED)


ASSIGN DATAPED(uValue) 
SELF:FieldPut(#DATAPED, uValue)
RETURN DATAPED := uValue


ACCESS DATASALDO() 
RETURN SELF:FieldGet(#DATASALDO)


ASSIGN DATASALDO(uValue) 
SELF:FieldPut(#DATASALDO, uValue)
RETURN DATASALDO := uValue


ACCESS DATAURG() 
RETURN SELF:FieldGet(#DATAURG)


ASSIGN DATAURG(uValue) 
SELF:FieldPut(#DATAURG, uValue)
RETURN DATAURG := uValue


ACCESS DATHPED() 
RETURN SELF:FieldGet(#DATHPED)


ASSIGN DATHPED(uValue) 
SELF:FieldPut(#DATHPED, uValue)
RETURN DATHPED := uValue


ACCESS DATHSAL() 
RETURN SELF:FieldGet(#DATHSAL)


ASSIGN DATHSAL(uValue) 
SELF:FieldPut(#DATHSAL, uValue)
RETURN DATHSAL := uValue


ACCESS DATHURG() 
RETURN SELF:FieldGet(#DATHURG)


ASSIGN DATHURG(uValue) 
SELF:FieldPut(#DATHURG, uValue)
RETURN DATHURG := uValue


ACCESS HRBAS() 
RETURN SELF:FieldGet(#HRBAS)


ASSIGN HRBAS(uValue) 
SELF:FieldPut(#HRBAS, uValue)
RETURN HRBAS := uValue


ACCESS HRPRE() 
RETURN SELF:FieldGet(#HRPRE)


ASSIGN HRPRE(uValue) 
SELF:FieldPut(#HRPRE, uValue)
RETURN HRPRE := uValue


ACCESS HRSAL() 
RETURN SELF:FieldGet(#HRSAL)


ASSIGN HRSAL(uValue) 
SELF:FieldPut(#HRSAL, uValue)
RETURN HRSAL := uValue


ACCESS HRTOT() 
RETURN SELF:FieldGet(#HRTOT)


ASSIGN HRTOT(uValue) 
SELF:FieldPut(#HRTOT, uValue)
RETURN HRTOT := uValue


ACCESS HRURG() 
RETURN SELF:FieldGet(#HRURG)


ASSIGN HRURG(uValue) 
SELF:FieldPut(#HRURG, uValue)
RETURN HRURG := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[1] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TABME01_Page2",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Times New Roman"}
aFonts[1]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCDATHURG := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_DATHURG,_GetInst()}}
oDCDATHURG:FieldSpec := DATE_FIELD{}
oDCDATHURG:HyperLabel := HyperLabel{#DATHURG,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATHURG:BackGround := aBrushes[1]
oDCDATHURG:Font(aFonts[1], FALSE)

oDCHRURG := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_HRURG,_GetInst()}}
oDCHRURG:FieldSpec := PADRAO_NUM_09_2{}
oDCHRURG:HyperLabel := HyperLabel{#HRURG,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCHRURG:BackGround := aBrushes[1]
oDCHRURG:Font(aFonts[1], FALSE)

oDCtheFixedText10 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT10,_GetInst()}}
oDCtheFixedText10:HyperLabel := HyperLabel{#theFixedText10,"Critica",NULL_STRING,NULL_STRING}

oDCDATHPED := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_DATHPED,_GetInst()}}
oDCDATHPED:FieldSpec := DATE_FIELD{}
oDCDATHPED:HyperLabel := HyperLabel{#DATHPED,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATHPED:BackGround := aBrushes[1]
oDCDATHPED:Font(aFonts[1], FALSE)

oDCHRPRE := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_HRPRE,_GetInst()}}
oDCHRPRE:FieldSpec := PADRAO_NUM_09_2{}
oDCHRPRE:HyperLabel := HyperLabel{#HRPRE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCHRPRE:BackGround := aBrushes[1]
oDCHRPRE:Font(aFonts[1], FALSE)

oDCtheFixedText11 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT11,_GetInst()}}
oDCtheFixedText11:HyperLabel := HyperLabel{#theFixedText11,"Preventiva",NULL_STRING,NULL_STRING}

oDCDATHSAL := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_DATHSAL,_GetInst()}}
oDCDATHSAL:FieldSpec := DATE_FIELD{}
oDCDATHSAL:HyperLabel := HyperLabel{#DATHSAL,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATHSAL:BackGround := aBrushes[1]
oDCDATHSAL:Font(aFonts[1], FALSE)

oDCHRSAL := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_HRSAL,_GetInst()}}
oDCHRSAL:FieldSpec := PADRAO_NUM_09_2{}
oDCHRSAL:HyperLabel := HyperLabel{#HRSAL,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCHRSAL:BackGround := aBrushes[1]
oDCHRSAL:Font(aFonts[1], FALSE)

oDCtheFixedText12 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT12,_GetInst()}}
oDCtheFixedText12:HyperLabel := HyperLabel{#theFixedText12,"Saldo",NULL_STRING,NULL_STRING}

oDCHRBAS := rightSle{SELF,ResourceID{TABME01_PAGE2_HRBAS,_GetInst()}}
oDCHRBAS:FieldSpec := PADRAO_NUM_09_2{}
oDCHRBAS:HyperLabel := HyperLabel{#HRBAS,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCGroupBox2 := GroupBox{SELF,ResourceID{TABME01_PAGE2_GROUPBOX2,_GetInst()}}
oDCGroupBox2:HyperLabel := HyperLabel{#GroupBox2,"Posição de Preventiva Horas",NULL_STRING,NULL_STRING}

oDCtheFixedText13 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT13,_GetInst()}}
oDCtheFixedText13:HyperLabel := HyperLabel{#theFixedText13,"Referencia:",NULL_STRING,NULL_STRING}

oDCDATAURG := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_DATAURG,_GetInst()}}
oDCDATAURG:FieldSpec := DATE_FIELD{}
oDCDATAURG:HyperLabel := HyperLabel{#DATAURG,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATAURG:BackGround := aBrushes[1]
oDCDATAURG:Font(aFonts[1], FALSE)

oDCQTDEURG := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_QTDEURG,_GetInst()}}
oDCQTDEURG:FieldSpec := PADRAO_NUM_12{}
oDCQTDEURG:HyperLabel := HyperLabel{#QTDEURG,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCQTDEURG:BackGround := aBrushes[1]
oDCQTDEURG:Font(aFonts[1], FALSE)

oDCDATAPED := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_DATAPED,_GetInst()}}
oDCDATAPED:FieldSpec := DATE_FIELD{}
oDCDATAPED:HyperLabel := HyperLabel{#DATAPED,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATAPED:BackGround := aBrushes[1]
oDCDATAPED:Font(aFonts[1], FALSE)

oDCDATASALDO := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_DATASALDO,_GetInst()}}
oDCDATASALDO:FieldSpec := DATE_FIELD{}
oDCDATASALDO:HyperLabel := HyperLabel{#DATASALDO,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCDATASALDO:BackGround := aBrushes[1]
oDCDATASALDO:Font(aFonts[1], FALSE)

oDCQTDEPED := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_QTDEPED,_GetInst()}}
oDCQTDEPED:FieldSpec := PADRAO_NUM_12{}
oDCQTDEPED:HyperLabel := HyperLabel{#QTDEPED,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCQTDEPED:BackGround := aBrushes[1]
oDCQTDEPED:Font(aFonts[1], FALSE)

oDCQTDESALDO := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_QTDESALDO,_GetInst()}}
oDCQTDESALDO:FieldSpec := PADRAO_NUM_12{}
oDCQTDESALDO:HyperLabel := HyperLabel{#QTDESALDO,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCQTDESALDO:BackGround := aBrushes[1]
oDCQTDESALDO:Font(aFonts[1], FALSE)

oDCtheFixedText8 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT8,_GetInst()}}
oDCtheFixedText8:HyperLabel := HyperLabel{#theFixedText8,"Critica",NULL_STRING,NULL_STRING}

oDCtheFixedText7 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT7,_GetInst()}}
oDCtheFixedText7:HyperLabel := HyperLabel{#theFixedText7,"Preventiva",NULL_STRING,NULL_STRING}

oDCGroupBox1 := GroupBox{SELF,ResourceID{TABME01_PAGE2_GROUPBOX1,_GetInst()}}
oDCGroupBox1:HyperLabel := HyperLabel{#GroupBox1,"Posição de Preventiva Quantidade",NULL_STRING,NULL_STRING}

oDCtheFixedText6 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT6,_GetInst()}}
oDCtheFixedText6:HyperLabel := HyperLabel{#theFixedText6,"Saldo",NULL_STRING,NULL_STRING}

oDCQTDEBASE := rightSle{SELF,ResourceID{TABME01_PAGE2_QTDEBASE,_GetInst()}}
oDCQTDEBASE:FieldSpec := PADRAO_NUM_12{}
oDCQTDEBASE:HyperLabel := HyperLabel{#QTDEBASE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCtheFixedText4 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT4,_GetInst()}}
oDCtheFixedText4:HyperLabel := HyperLabel{#theFixedText4,"Referencia:",NULL_STRING,NULL_STRING}

oCCcmdCalcular := PushButton{SELF,ResourceID{TABME01_PAGE2_CMDCALCULAR,_GetInst()}}
oCCcmdCalcular:HyperLabel := HyperLabel{#cmdCalcular,"Calcular",NULL_STRING,NULL_STRING}

oCCRB2 := RadioButton{SELF,ResourceID{TABME01_PAGE2_RB2,_GetInst()}}
oCCRB2:HyperLabel := HyperLabel{#RB2,"Não",NULL_STRING,NULL_STRING}

oCCRB1 := RadioButton{SELF,ResourceID{TABME01_PAGE2_RB1,_GetInst()}}
oCCRB1:HyperLabel := HyperLabel{#RB1,"Sim",NULL_STRING,NULL_STRING}

oDCVDDURG := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_VDDURG,_GetInst()}}
oDCVDDURG:FieldSpec := PADRAO_NUM_12{}
oDCVDDURG:HyperLabel := HyperLabel{#VDDURG,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCVDDURG:BackGround := aBrushes[1]
oDCVDDURG:Font(aFonts[1], FALSE)

oDCVDURG := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_VDURG,_GetInst()}}
oDCVDURG:FieldSpec := PADRAO_NUM_12{}
oDCVDURG:HyperLabel := HyperLabel{#VDURG,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCVDURG:BackGround := aBrushes[1]
oDCVDURG:Font(aFonts[1], FALSE)

oDCtheFixedText9 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT9,_GetInst()}}
oDCtheFixedText9:HyperLabel := HyperLabel{#theFixedText9,"Critica",NULL_STRING,NULL_STRING}

oDCVDDPRE := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_VDDPRE,_GetInst()}}
oDCVDDPRE:FieldSpec := PADRAO_NUM_12{}
oDCVDDPRE:HyperLabel := HyperLabel{#VDDPRE,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCVDDPRE:BackGround := aBrushes[1]
oDCVDDPRE:Font(aFonts[1], FALSE)

oDCVDPRE := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_VDPRE,_GetInst()}}
oDCVDPRE:FieldSpec := PADRAO_NUM_12{}
oDCVDPRE:HyperLabel := HyperLabel{#VDPRE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCVDPRE:BackGround := aBrushes[1]
oDCVDPRE:Font(aFonts[1], FALSE)

oDCtheFixedText14 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT14,_GetInst()}}
oDCtheFixedText14:HyperLabel := HyperLabel{#theFixedText14,"Preventiva",NULL_STRING,NULL_STRING}

oDCQTDETOT := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_QTDETOT,_GetInst()}}
oDCQTDETOT:FieldSpec := PADRAO_NUM_12{}
oDCQTDETOT:HyperLabel := HyperLabel{#QTDETOT,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCQTDETOT:BackGround := aBrushes[1]
oDCQTDETOT:Font(aFonts[1], FALSE)

oDCVDBAS := rightSle{SELF,ResourceID{TABME01_PAGE2_VDBAS,_GetInst()}}
oDCVDBAS:FieldSpec := PADRAO_NUM_12{}
oDCVDBAS:HyperLabel := HyperLabel{#VDBAS,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCtheFixedText16 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT16,_GetInst()}}
oDCtheFixedText16:HyperLabel := HyperLabel{#theFixedText16,"Referencia:",NULL_STRING,NULL_STRING}

oDCGroupBox3 := GroupBox{SELF,ResourceID{TABME01_PAGE2_GROUPBOX3,_GetInst()}}
oDCGroupBox3:HyperLabel := HyperLabel{#GroupBox3,"Posição Vida Util Quantidade",NULL_STRING,NULL_STRING}

oDCVDHDURG := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_VDHDURG,_GetInst()}}
oDCVDHDURG:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHDURG:HyperLabel := HyperLabel{#VDHDURG,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCVDHDURG:BackGround := aBrushes[1]
oDCVDHDURG:Font(aFonts[1], FALSE)

oDCVDHDPRE := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_VDHDPRE,_GetInst()}}
oDCVDHDPRE:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHDPRE:HyperLabel := HyperLabel{#VDHDPRE,"Datap:",NULL_STRING,"FERRAM_DATAP"}
oDCVDHDPRE:BackGround := aBrushes[1]
oDCVDHDPRE:Font(aFonts[1], FALSE)

oDCHRTOT := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_HRTOT,_GetInst()}}
oDCHRTOT:FieldSpec := PADRAO_NUM_09_2{}
oDCHRTOT:HyperLabel := HyperLabel{#HRTOT,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCHRTOT:BackGround := aBrushes[1]
oDCHRTOT:Font(aFonts[1], FALSE)

oDCVDHURG := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_VDHURG,_GetInst()}}
oDCVDHURG:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHURG:HyperLabel := HyperLabel{#VDHURG,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCVDHURG:BackGround := aBrushes[1]
oDCVDHURG:Font(aFonts[1], FALSE)

oDCVDHPRE := SingleLineEdit{SELF,ResourceID{TABME01_PAGE2_VDHPRE,_GetInst()}}
oDCVDHPRE:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHPRE:HyperLabel := HyperLabel{#VDHPRE,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}
oDCVDHPRE:BackGround := aBrushes[1]
oDCVDHPRE:Font(aFonts[1], FALSE)

oDCVDHBAS := rightSle{SELF,ResourceID{TABME01_PAGE2_VDHBAS,_GetInst()}}
oDCVDHBAS:FieldSpec := PADRAO_NUM_09_2{}
oDCVDHBAS:HyperLabel := HyperLabel{#VDHBAS,"Cliente:",NULL_STRING,"FERRAM_CLIENTE"}

oDCtheFixedText15 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT15,_GetInst()}}
oDCtheFixedText15:HyperLabel := HyperLabel{#theFixedText15,"Critica",NULL_STRING,NULL_STRING}

oDCtheFixedText17 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT17,_GetInst()}}
oDCtheFixedText17:HyperLabel := HyperLabel{#theFixedText17,"Preventiva",NULL_STRING,NULL_STRING}

oDCtheFixedText18 := FixedText{SELF,ResourceID{TABME01_PAGE2_THEFIXEDTEXT18,_GetInst()}}
oDCtheFixedText18:HyperLabel := HyperLabel{#theFixedText18,"Referencia:",NULL_STRING,NULL_STRING}

oDCGroupBox4 := GroupBox{SELF,ResourceID{TABME01_PAGE2_GROUPBOX4,_GetInst()}}
oDCGroupBox4:HyperLabel := HyperLabel{#GroupBox4,"Posição Vida Util Horas",NULL_STRING,NULL_STRING}

oDCPREVER := RadioButtonGroup{SELF,ResourceID{TABME01_PAGE2_PREVER,_GetInst()}}
oDCPREVER:FillUsing({ ;
						{oCCRB2,"N"}, ;
						{oCCRB1,"S"} ;
						})
oDCPREVER:HyperLabel := HyperLabel{#PREVER,"Requer Preventiva",NULL_STRING,NULL_STRING}
oDCPREVER:FieldSpec := PADRAO_CHAR_01{}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TABME01_Page2,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS PREVER() 
RETURN SELF:FieldGet(#PREVER)


ASSIGN PREVER(uValue) 
SELF:FieldPut(#PREVER, uValue)
RETURN PREVER := uValue


ACCESS QTDEBASE() 
RETURN SELF:FieldGet(#QTDEBASE)


ASSIGN QTDEBASE(uValue) 
SELF:FieldPut(#QTDEBASE, uValue)
RETURN QTDEBASE := uValue


ACCESS QTDEPED() 
RETURN SELF:FieldGet(#QTDEPED)


ASSIGN QTDEPED(uValue) 
SELF:FieldPut(#QTDEPED, uValue)
RETURN QTDEPED := uValue


ACCESS QTDESALDO() 
RETURN SELF:FieldGet(#QTDESALDO)


ASSIGN QTDESALDO(uValue) 
SELF:FieldPut(#QTDESALDO, uValue)
RETURN QTDESALDO := uValue


ACCESS QTDETOT() 
RETURN SELF:FieldGet(#QTDETOT)


ASSIGN QTDETOT(uValue) 
SELF:FieldPut(#QTDETOT, uValue)
RETURN QTDETOT := uValue


ACCESS QTDEURG() 
RETURN SELF:FieldGet(#QTDEURG)


ASSIGN QTDEURG(uValue) 
SELF:FieldPut(#QTDEURG, uValue)
RETURN QTDEURG := uValue


ACCESS VDBAS() 
RETURN SELF:FieldGet(#VDBAS)


ASSIGN VDBAS(uValue) 
SELF:FieldPut(#VDBAS, uValue)
RETURN VDBAS := uValue


ACCESS VDDPRE() 
RETURN SELF:FieldGet(#VDDPRE)


ASSIGN VDDPRE(uValue) 
SELF:FieldPut(#VDDPRE, uValue)
RETURN VDDPRE := uValue


ACCESS VDDURG() 
RETURN SELF:FieldGet(#VDDURG)


ASSIGN VDDURG(uValue) 
SELF:FieldPut(#VDDURG, uValue)
RETURN VDDURG := uValue


ACCESS VDHBAS() 
RETURN SELF:FieldGet(#VDHBAS)


ASSIGN VDHBAS(uValue) 
SELF:FieldPut(#VDHBAS, uValue)
RETURN VDHBAS := uValue


ACCESS VDHDPRE() 
RETURN SELF:FieldGet(#VDHDPRE)


ASSIGN VDHDPRE(uValue) 
SELF:FieldPut(#VDHDPRE, uValue)
RETURN VDHDPRE := uValue


ACCESS VDHDURG() 
RETURN SELF:FieldGet(#VDHDURG)


ASSIGN VDHDURG(uValue) 
SELF:FieldPut(#VDHDURG, uValue)
RETURN VDHDURG := uValue


ACCESS VDHPRE() 
RETURN SELF:FieldGet(#VDHPRE)


ASSIGN VDHPRE(uValue) 
SELF:FieldPut(#VDHPRE, uValue)
RETURN VDHPRE := uValue


ACCESS VDHURG() 
RETURN SELF:FieldGet(#VDHURG)


ASSIGN VDHURG(uValue) 
SELF:FieldPut(#VDHURG, uValue)
RETURN VDHURG := uValue


ACCESS VDPRE() 
RETURN SELF:FieldGet(#VDPRE)


ASSIGN VDPRE(uValue) 
SELF:FieldPut(#VDPRE, uValue)
RETURN VDPRE := uValue


ACCESS VDURG() 
RETURN SELF:FieldGet(#VDURG)


ASSIGN VDURG(uValue) 
SELF:FieldPut(#VDURG, uValue)
RETURN VDURG := uValue


END CLASS
PARTIAL CLASS TABME01_Page3 INHERIT DATAWINDOW 

	PROTECT oDCVISUALNUM AS RIGHTSLE
	PROTECT oDCVISUALNOM AS SINGLELINEEDIT
	PROTECT oDCGroupBox1 AS GROUPBOX
	PROTECT oDCVISUALOBS AS SINGLELINEEDIT
	PROTECT oDCGroupBox2 AS GROUPBOX
	PROTECT oDCMEDA AS RIGHTSLE
	PROTECT oDCMEDB AS RIGHTSLE
	PROTECT oDCMEDC AS RIGHTSLE
	PROTECT oDCMEDD AS RIGHTSLE
	PROTECT oDCMEDH AS RIGHTSLE
	PROTECT oDCPESO AS RIGHTSLE
	PROTECT oDCFixedText2 AS FIXEDTEXT
	PROTECT oDCFixedText3 AS FIXEDTEXT
	PROTECT oDCFixedText4 AS FIXEDTEXT
	PROTECT oDCFixedText5 AS FIXEDTEXT
	PROTECT oDCFixedText6 AS FIXEDTEXT
	PROTECT oDCFixedText7 AS FIXEDTEXT
	PROTECT oCCescres AS PUSHBUTTON
	PROTECT oCCPEGAVA AS PUSHBUTTON
// 	instance VISUALNUM 
// 	instance VISUALNOM 
// 	instance VISUALOBS 
// 	instance MEDA 
// 	instance MEDB 
// 	instance MEDC 
// 	instance MEDD 
// 	instance MEDH 
// 	instance PESO 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TABME01_Page3",_GetInst()},iCtlID)

aBrushes[1] := Brush{Color{255,255,200}}

oDCVISUALNUM := rightSle{SELF,ResourceID{TABME01_PAGE3_VISUALNUM,_GetInst()}}
oDCVISUALNUM:FieldSpec := PADRAO_NUM_08{}
oDCVISUALNUM:HyperLabel := HyperLabel{#VISUALNUM,"Ro:",NULL_STRING,"RO_RO"}

oDCVISUALNOM := SingleLineEdit{SELF,ResourceID{TABME01_PAGE3_VISUALNOM,_GetInst()}}
oDCVISUALNOM:FieldSpec := PADRAO_CHAR_40{}
oDCVISUALNOM:HyperLabel := HyperLabel{#VISUALNOM,"Ro:",NULL_STRING,"RO_RO"}
oDCVISUALNOM:BackGround := aBrushes[1]

oDCGroupBox1 := GroupBox{SELF,ResourceID{TABME01_PAGE3_GROUPBOX1,_GetInst()}}
oDCGroupBox1:HyperLabel := HyperLabel{#GroupBox1,"Elaborador",NULL_STRING,NULL_STRING}

oDCVISUALOBS := SingleLineEdit{SELF,ResourceID{TABME01_PAGE3_VISUALOBS,_GetInst()}}
oDCVISUALOBS:FieldSpec := PADRAO_CHAR_100{}
oDCVISUALOBS:HyperLabel := HyperLabel{#VISUALOBS,"Ro:",NULL_STRING,"RO_RO"}

oDCGroupBox2 := GroupBox{SELF,ResourceID{TABME01_PAGE3_GROUPBOX2,_GetInst()}}
oDCGroupBox2:HyperLabel := HyperLabel{#GroupBox2,"Dimensoes",NULL_STRING,NULL_STRING}

oDCMEDA := rightSle{SELF,ResourceID{TABME01_PAGE3_MEDA,_GetInst()}}
oDCMEDA:FieldSpec := PADRAO_NUM_12_3{}
oDCMEDA:HyperLabel := HyperLabel{#MEDA,"Ro:",NULL_STRING,"RO_RO"}

oDCMEDB := rightSle{SELF,ResourceID{TABME01_PAGE3_MEDB,_GetInst()}}
oDCMEDB:FieldSpec := PADRAO_NUM_12_3{}
oDCMEDB:HyperLabel := HyperLabel{#MEDB,"Ro:",NULL_STRING,"RO_RO"}

oDCMEDC := rightSle{SELF,ResourceID{TABME01_PAGE3_MEDC,_GetInst()}}
oDCMEDC:FieldSpec := PADRAO_NUM_12_3{}
oDCMEDC:HyperLabel := HyperLabel{#MEDC,"Ro:",NULL_STRING,"RO_RO"}

oDCMEDD := rightSle{SELF,ResourceID{TABME01_PAGE3_MEDD,_GetInst()}}
oDCMEDD:FieldSpec := PADRAO_NUM_12_3{}
oDCMEDD:HyperLabel := HyperLabel{#MEDD,"Ro:",NULL_STRING,"RO_RO"}

oDCMEDH := rightSle{SELF,ResourceID{TABME01_PAGE3_MEDH,_GetInst()}}
oDCMEDH:FieldSpec := PADRAO_NUM_12_3{}
oDCMEDH:HyperLabel := HyperLabel{#MEDH,"Ro:",NULL_STRING,"RO_RO"}

oDCPESO := rightSle{SELF,ResourceID{TABME01_PAGE3_PESO,_GetInst()}}
oDCPESO:FieldSpec := PADRAO_NUM_12_3{}
oDCPESO:HyperLabel := HyperLabel{#PESO,"Ro:",NULL_STRING,"RO_RO"}

oDCFixedText2 := FixedText{SELF,ResourceID{TABME01_PAGE3_FIXEDTEXT2,_GetInst()}}
oDCFixedText2:HyperLabel := HyperLabel{#FixedText2,"A",NULL_STRING,NULL_STRING}

oDCFixedText3 := FixedText{SELF,ResourceID{TABME01_PAGE3_FIXEDTEXT3,_GetInst()}}
oDCFixedText3:HyperLabel := HyperLabel{#FixedText3,"B",NULL_STRING,NULL_STRING}

oDCFixedText4 := FixedText{SELF,ResourceID{TABME01_PAGE3_FIXEDTEXT4,_GetInst()}}
oDCFixedText4:HyperLabel := HyperLabel{#FixedText4,"C",NULL_STRING,NULL_STRING}

oDCFixedText5 := FixedText{SELF,ResourceID{TABME01_PAGE3_FIXEDTEXT5,_GetInst()}}
oDCFixedText5:HyperLabel := HyperLabel{#FixedText5,"D",NULL_STRING,NULL_STRING}

oDCFixedText6 := FixedText{SELF,ResourceID{TABME01_PAGE3_FIXEDTEXT6,_GetInst()}}
oDCFixedText6:HyperLabel := HyperLabel{#FixedText6,"H",NULL_STRING,NULL_STRING}

oDCFixedText7 := FixedText{SELF,ResourceID{TABME01_PAGE3_FIXEDTEXT7,_GetInst()}}
oDCFixedText7:HyperLabel := HyperLabel{#FixedText7,"Peso",NULL_STRING,NULL_STRING}

oCCescres := PushButton{SELF,ResourceID{TABME01_PAGE3_ESCRES,_GetInst()}}
oCCescres:HyperLabel := HyperLabel{#escres,"...",NULL_STRING,NULL_STRING}

oCCPEGAVA := PushButton{SELF,ResourceID{TABME01_PAGE3_PEGAVA,_GetInst()}}
oCCPEGAVA:HyperLabel := HyperLabel{#PEGAVA,"-->",NULL_STRING,NULL_STRING}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TABME01_Page3,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS MEDA() 
RETURN SELF:FieldGet(#MEDA)


ASSIGN MEDA(uValue) 
SELF:FieldPut(#MEDA, uValue)
RETURN MEDA := uValue


ACCESS MEDB() 
RETURN SELF:FieldGet(#MEDB)


ASSIGN MEDB(uValue) 
SELF:FieldPut(#MEDB, uValue)
RETURN MEDB := uValue


ACCESS MEDC() 
RETURN SELF:FieldGet(#MEDC)


ASSIGN MEDC(uValue) 
SELF:FieldPut(#MEDC, uValue)
RETURN MEDC := uValue


ACCESS MEDD() 
RETURN SELF:FieldGet(#MEDD)


ASSIGN MEDD(uValue) 
SELF:FieldPut(#MEDD, uValue)
RETURN MEDD := uValue


ACCESS MEDH() 
RETURN SELF:FieldGet(#MEDH)


ASSIGN MEDH(uValue) 
SELF:FieldPut(#MEDH, uValue)
RETURN MEDH := uValue


METHOD PEGAVA( ) 
LOCAL ACLI,aCOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
	        	aCLI:=PEGMP04(SELF:SERVER:VISUALNUM,ZCURINI,ZCURDIR,aCOM)
		    IF aCLI[1]=.T.
        	   SELF:SERVER:FIELDPUT("VISUALNOM",aCLI[2])
		    ENDIF
	

ACCESS PESO() 
RETURN SELF:FieldGet(#PESO)


ASSIGN PESO(uValue) 
SELF:FieldPut(#PESO, uValue)
RETURN PESO := uValue


ACCESS VISUALNOM() 
RETURN SELF:FieldGet(#VISUALNOM)


ASSIGN VISUALNOM(uValue) 
SELF:FieldPut(#VISUALNOM, uValue)
RETURN VISUALNOM := uValue


ACCESS VISUALNUM() 
RETURN SELF:FieldGet(#VISUALNUM)


ASSIGN VISUALNUM(uValue) 
SELF:FieldPut(#VISUALNUM, uValue)
RETURN VISUALNUM := uValue


ACCESS VISUALOBS() 
RETURN SELF:FieldGet(#VISUALOBS)


ASSIGN VISUALOBS(uValue) 
SELF:FieldPut(#VISUALOBS, uValue)
RETURN VISUALOBS := uValue


END CLASS
