PARTIAL CLASS JME01
METHOD APPEND() 
alert("Incluisão Bloqueada")
RETURN .f.


METHOD busca( ) 
	SELF:KeyFind()

METHOD cmdcalcular() 
IF SELF:SERVER:QTDESALDO >0
   IF SELF:SERVER:QTDESALDO>(SELF:SERVER:QTDEBASE*.8) .AND. Empty(SELF:SERVER:QTDEPED)
      SELF:SERVER:QTDEPED:=SELF:SERVER:QTDESALDO
   ENDIF
   IF SELF:SERVER:QTDESALDO>(SELF:SERVER:QTDEBASE*1.3) .AND. Empty(SELF:SERVER:QTDEURG)
      SELF:SERVER:QTDEURG:=SELF:SERVER:QTDESALDO
   ENDIF
   IF SELF:SERVER:QTDESALDO>(SELF:SERVER:QTDEBASE*.8) .AND. Empty(SELF:SERVER:DATAPED)
      SELF:SERVER:DATAPED:=Today()
   ENDIF
   IF SELF:SERVER:QTDESALDO>(SELF:SERVER:QTDEBASE*1.3) .AND. Empty(SELF:SERVER:DATAURG)
      SELF:SERVER:DATAURG:=Today()
   ENDIF
   SELF:SERVER:SITUACAO:="A"
   IF Empty(SELF:SERVER:DATAATV)
      SELF:SERVER:DATAATV:=Today()
   ENDIF
 ELSE
   IF SELF:SERVER:SITUACAO<>"O" .AND. SELF:SERVER:SITUACAO<>"D"
      SELF:SERVER:SITUACAO:="I"
      IF Empty(SELF:SERVER:DATADES)
         SELF:SERVER:DATADES:=Today()
      ENDIF
   ENDIF
 ENDIF
 //Calcula Horas Preventiva
 IF SELF:SERVER:HRSAL>0
    IF SELF:SERVER:FIELDGET("HRSAL")>(SELF:SERVER:FIELDGET("HRBAS")*.8) .AND. Empty(SELF:SERVER:FIELDGET("HRPRE"))
       SELF:SERVER:FIELDPUT("HRPRE",SELF:SERVER:HRSAL)
    ENDIF
    IF SELF:SERVER:FIELDGET("HRSAL")>(SELF:SERVER:FIELDGET("HRBAS")*1.3) .AND. Empty(SELF:SERVER:FIELDGET("HRURG"))
       SELF:SERVER:FIELDPUT("HRURG",SELF:SERVER:HRSAL)
    ENDIF
    IF SELF:SERVER:FIELDGET("HRSAL")>(SELF:SERVER:FIELDGET("HRBAS")*.8) .AND. Empty(SELF:SERVER:FIELDGET("DATHPED"))
       SELF:SERVER:FIELDPUT("DATHPED",SELF:SERVER:DATHSAL)
    ENDIF
    IF SELF:SERVER:FIELDGET("HRSAL")>(SELF:SERVER:FIELDGET("HRBAS")*1.3) .AND. Empty(SELF:SERVER:FIELDGET("DATHURG"))
       SELF:SERVER:FIELDPUT("DATHURG",SELF:SERVER:DATHSAL)
    ENDIF
 ENDIF

 //Calcula Vida Quantidade
 IF SELF:SERVER:QTDETOT>0
    IF SELF:SERVER:FIELDGET("QTDETOT")>(SELF:SERVER:FIELDGET("VDBAS")*.8) .AND. Empty(SELF:SERVER:FIELDGET("VDPRE"))
       SELF:SERVER:FIELDPUT("VDPRE",SELF:SERVER:QTDETOT)
    ENDIF
    IF SELF:SERVER:FIELDGET("QTDETOT")>(SELF:SERVER:FIELDGET("VDBAS")*1.3) .AND. Empty(SELF:SERVER:FIELDGET("VDURG"))
       SELF:SERVER:FIELDPUT("VDURG",SELF:SERVER:QTDETOT)
    ENDIF
    IF SELF:SERVER:FIELDGET("QTDETOT")>(SELF:SERVER:FIELDGET("VDBAS")*.8) .AND. Empty(SELF:SERVER:FIELDGET("VDDPRE"))
       SELF:SERVER:FIELDPUT("VDDPRE",SELF:SERVER:DATHSAL)
    ENDIF
    IF SELF:SERVER:FIELDGET("QTDETOT")>(SELF:SERVER:FIELDGET("VDBAS")*1.3) .AND. Empty(SELF:SERVER:FIELDGET("VDDURG"))
       SELF:SERVER:FIELDPUT("VDDURG",SELF:SERVER:DATHSAL)
    ENDIF
 ENDIF


 //Calcula Vida Horas
 IF SELF:SERVER:HRTOT>0
    IF SELF:SERVER:FIELDGET("HRTOT")>(SELF:SERVER:FIELDGET("VDHBAS")*.8) .AND. Empty(SELF:SERVER:FIELDGET("VDHPRE"))
       SELF:SERVER:FIELDPUT("VDHPRE",SELF:SERVER:HRTOT)
    ENDIF
    IF SELF:SERVER:FIELDGET("HRTOT")>(SELF:SERVER:FIELDGET("VDHBAS")*1.3) .AND. Empty(SELF:SERVER:FIELDGET("VDHURG"))
       SELF:SERVER:FIELDPUT("VDHURG",SELF:SERVER:HRTOT)
    ENDIF
    IF SELF:SERVER:FIELDGET("HRTOT")>(SELF:SERVER:FIELDGET("VDHBAS")*.8) .AND. Empty(SELF:SERVER:FIELDGET("VDHDPRE"))
       SELF:SERVER:FIELDPUT("VDHDPRE",SELF:SERVER:DATHSAL)
    ENDIF
    IF SELF:SERVER:FIELDGET("HTTOT")>(SELF:SERVER:FIELDGET("VDHBAS")*1.3) .AND. Empty(SELF:SERVER:FIELDGET("VDHDURG"))
       SELF:SERVER:FIELDPUT("VDHDURG",SELF:SERVER:DATHSAL)
    ENDIF
 ENDIF


//Zera Se Necessario Preventiva
IF SELF:SERVER:QTDESALDO<(SELF:SERVER:QTDEBASE*.8)
   SELF:SERVER:QTDEPED:=0
   SELF:SERVER:DATAPED:=CToD(Space(8))
ENDIF
IF SELF:SERVER:QTDESALDO<(SELF:SERVER:QTDEBASE*1.3)
   SELF:SERVER:QTDEURG:=0
   SELF:SERVER:DATAURG:=CToD(Space(8))
ENDIF
IF SELF:SERVER:FIELDGET("HRSAL")<(SELF:SERVER:FIELDGET("HRBAS")*.8)
   SELF:SERVER:FIELDPUT("HRPRE",0)
   SELF:SERVER:FIELDPUT("DATHPED",CToD(Space(8)))
ENDIF
IF SELF:SERVER:FIELDGET("HRSAL")<(SELF:SERVER:FIELDGET("HRBAS")*1.3)
   SELF:SERVER:FIELDPUT("HRURG",0)
   SELF:SERVER:FIELDPUT("DATHURG",CToD(Space(8)))
ENDIF

//Zera Vida Util
IF SELF:SERVER:QTDETOT<(SELF:SERVER:VDBAS*.8)
   SELF:SERVER:VDPRE:=0
   SELF:SERVER:VDDPRE:=CToD(Space(8))
ENDIF
IF SELF:SERVER:QTDETOT<(SELF:SERVER:VDBAS*1.3)
   SELF:SERVER:VDURG:=0
   SELF:SERVER:VDDURG:=CToD(Space(8))
ENDIF
IF SELF:SERVER:FIELDGET("HRTOT")<(SELF:SERVER:FIELDGET("VDHBAS")*.8)
   SELF:SERVER:FIELDPUT("VDHPRE",0)
   SELF:SERVER:FIELDPUT("VDHDPRE",CToD(Space(8)))
ENDIF
IF SELF:SERVER:FIELDGET("HRTOT")<(SELF:SERVER:FIELDGET("VDHBAS")*1.3)
   SELF:SERVER:FIELDPUT("VDHURG",0)
   SELF:SERVER:FIELDPUT("VDHDURG",CToD(Space(8)))
ENDIF

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("FR","MQ")	

METHOD DELETE() 
alert("Exclusão Bloqueada")
RETURN .f.

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
	 FabCenterWindow( SELF )

 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
PARTIAL CLASS TABME01
METHOD foto( ) 
LOCAL nFout AS PTR
LOCAL cARQ,CCODIGO AS STRING
cARQ:=PEGINIVAL(ZCURINI,"PATH","IMGJPG")
CCODIGO:=SELF:SERVER:FIELDGET("NUMERO")
nFout := ShellExecute(SELF:owner:handle(),String2Psz("open"),String2Psz("IMGJPG"),String2Psz(CCODIGO+"#{IMGME01}"),String2Psz(carq),SW_SHOWNORMAL)  
ShellExecuteErro(nFout) 
		

METHOD PEGGRU 
RETU MTD02("GRUPOMAQ",3)

METHOD TABTIPO 
RETU MTD02("TIPOEQI",1)

END CLASS
PARTIAL CLASS TABME01_Page3
METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:lOK
   SELF:SERVER:FIELDPUT("VISUALNUM",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("VISUALNOM",oESCMP04:NOME)
ENDIF


END CLASS
