PARTIAL CLASS JRL
METHOD ALTERAR  
SELF:oSFJRLI:VIEWFORM()


METHOD ANTERIOR 
SELF:oSFJRLI:Browser:SuspendUpdate()
SELF:oSFJRLI:SkipPrevious()
IF SELF:oSFJRLI:Server:bof
  SELF:oSFJRLI:Skipnext()
ENDIF
SELF:oSFJRLI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nRL AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nRL:=SELF:Server:FIELDGET("RL")
nRL++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("RL",nRL)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:commit()
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
RETURN .t.

METHOD busca( ) 
	SELF:KeyFind()
//LOCAL oBUSCA AS xBUSCA
//oBUSCA:=xBUSCA{SELF,"Localizar","Digite o Nº "}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF
	

METHOD CHECAR  
LOCAL aDAD AS ARRAY
LOCAL oME01 AS USEREDE	
LOCAL nITEM AS WORD



nITEM:=0
aDAD:={zCURINI,"ME01.DBF",zCURDIR}
oME01:=USEREDE{aDAD}
IF oME01:nERRO#0
   RETUrn .f.
ENDIF
SELF:oSFJRLI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJRLI:GOTOP()
WHILE ! SELF:oSFJRLI:SERVER:eof
	SELF:oSFJRLI:SERVER:delete()
	SELF:oSFJRLI:SERVER:skip()	
ENDDO
oME01:GOTOP()
WHILE ! oME01:EOF
 	nITEM++
 	IF oME01:FIELDGET("LUBRI")
	  	SELF:oSFJRLI:SERVER:APPEND()	
    	SELF:oSFJRLI:SERVER:FIELDPUT("RL",SELF:SERVER:RL)
    	SELF:oSFJRLI:SERVER:FIELDPUT("CODME01",oME01:FIELDGET("NUMERO"))
  	 	IF ! oME01:FIELDGET("LUB01")
   	    	SELF:oSFJRLI:SERVER:FIELDPUT("LUB01","A")
  	 	ENDIF	
  	 	IF ! oME01:FIELDGET("LUB02")
   	    	SELF:oSFJRLI:SERVER:FIELDPUT("LUB02","A")
  	 	ENDIF	
  	 	IF ! oME01:FIELDGET("LUB03")
   	    	SELF:oSFJRLI:SERVER:FIELDPUT("LUB03","A")
  	 	ENDIF	
  	 	IF ! oME01:FIELDGET("LUB04")
   	    	SELF:oSFJRLI:SERVER:FIELDPUT("LUB04","A")
  	 	ENDIF	
  	 	IF ! oME01:FIELDGET("LUB05")
   	    	SELF:oSFJRLI:SERVER:FIELDPUT("LUB05","A")
  	 	ENDIF	
    	SELF:oSFJRLI:SERVER:commit()
	ENDIF
	oME01:SKIP()
ENDDO
oME01:CLOSE()
SELF:oSFJRLI:SERVER:resetnotification()
SELF:oSFJRLI:SERVER:notify(notifyfilechange)
	
		

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("FR","RL")	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJRLI:Browser:SuspendUpdate()
SELF:oSFJRLI:SkipNext()
IF SELF:oSFJRLI:Server:Eof
	SELF:oSFJRLI:SkipPrevious()
ENDIF
SELF:oSFJRLI:Browser:RestoreUpdate()

METHOD TABULAR  
SELF:oSFJRLI:VIEWTABLE()


METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJRLI:SERVER:Commit()


END CLASS
PARTIAL CLASS XJRL
METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:oSFJRLI:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJRLI:server:GOTOP()	
	WHILE ! oSFJRLI:server:EOF
 		SELF:oSFJRLI:server:delete()
	ENDDO	
	SELF:oSFJRLI:SERVER:resetnotification()
	SELF:oSFJRLI:SERVER:notify(notifyfilechange)	
    SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF		


END CLASS
