CLASS XINDEXAR INHERIT INDEXAR	

CONSTRUCTOR(oOWNER) 
IF ! entramenu("FER",7)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	



METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
CRIANTX({ZCURINI,"FERRAM.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FERRAMI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FERGI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FERGRP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CS.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RO.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ROI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RL.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RLI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"SM.DBF",ZCURDIR})
CRIANTX({ZCURINI,"LVF.DBF",ZCURDIR})
CRIANTX({ZCURINI,"LVFI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"LVFP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"LVM.DBF",ZCURDIR})
CRIANTX({ZCURINI,"LVMI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"LVMP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FAPU.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FAPUI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"MAPU.DBF",ZCURDIR})
CRIANTX({ZCURINI,"MAPUI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FAPUFER.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FAPUBAI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FAPUMAQ.DBF",ZCURDIR})
CRIANTX({ZCURINI,"MAPUBAI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ME01CR.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FERHG.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FERHGI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FE02.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FE99.DBF",ZCURDIR})
CRIANTX({ZCURINI,"FERNF.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()	

END CLASS
CLASS XJCMMACU INHERIT jcmmacu	

CONSTRUCTOR(oOWNER) 
IF ! entramenu("FER",14)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:oDCANO:textvalue:=Str(Year(Today()),4)
SELF:oDCmes:textvalue:=Str(Month(Today()),2)
SELF:SHOW()	
	
	

END CLASS
CLASS XJCS INHERIT JCS	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",12)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CS.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()



END CLASS
PARTIAL CLASS XJFAPU INHERIT JFAPU	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",6)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"FAPU.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"FAPUI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:oCCLiberar:DISABLE()
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJFAPUI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJFAPUI,#SEQ)
SELF:Caption:="Apurar Uso de Ferramentas"
SELF:SHOW()	
	

END CLASS
CLASS XJFE02 INHERIT JFE02

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",18)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"FE02.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
CLASS XJFER INHERIT JFER	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"FERRAM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"FERRAMI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJFERRAMI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJFERRAMI,"FERRAM")
SELF:SHOW()		


END CLASS
CLASS XJFERGRP INHERIT JFERGRP
	

CONSTRUCTOR(oOWNER,Cbusca) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",13)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"FERGRP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"FERGI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJFERGI:USE(oSERVE2)
SELF:oSFJFERGI:VIEWTABLE()
SELF:SetSelectiveRelation(oSFJFERGI,"GRUPO")
IF ValType(cBUSCA)="C"
//   alert(cBUSCA)
   SELF:SERVER:GOTOP()
   IF ! SELF:SERVER:SEEK(AllTrim(cBUSCA))
   	  IF MDG("Incluir Grupo" +cBUSCA)
   	  	 SELF:SERVER:APPEND()
   	  	 SELF:SERVER:FIELDPUT("GRUPO",cBUSCA)
   	  	 SELF:SERVER:Commit()
   	  ELSE
         SELF:SERVER:GOTOP()	
   	  ENDIF
   ENDIF	
ENDIF		
SELF:SHOW()	

END CLASS
CLASS XJFERHG INHERIT JFERHG

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",20)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"FERHG.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"FERHGI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:OSFJFERHGI:USE(oSERVE2)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SetSelectiveRelation(oSFJFERHGI,"OS")
SELF:OSFJFERHGI:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		




END CLASS
CLASS XJLVF INHERIT JLVF

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"LVF.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"LVFI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJLVFI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJLVFI,#LVF)
SELF:SHOW()		

END CLASS
CLASS XJLVFP INHERIT JLVFP

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",4)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"LVFP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
CLASS XJLVM INHERIT JLVM

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",10)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"LVM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"LVMI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJLVMI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJLVMI,#LVM)
SELF:SHOW()		

END CLASS
CLASS XJLVMP INHERIT JLVMP	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",11)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"LVMP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
PARTIAL CLASS XJMAPU INHERIT JFAPU		

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",8)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MAPU.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MAPUI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:oCCLiberar:DISABLE()
SELF:OSFJFAPUI:USE(oSERVE2)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SetSelectiveRelation(oSFJFAPUI,#SEQ)
SELF:Caption:="Apurar Uso de Maquinas"
SELF:SHOW()	
	
	



END CLASS
CLASS XJME01 INHERIT JME01	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",9)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ME01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
CLASS XJME01CR INHERIT JME01CR

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL oBUSCA AS XBUSCA
LOCAL cVAR AS STRING
oBUSCA:=XBUSCA{SELF,"Ano de Trabalho","Digite o Ano para Cronograma",StrZero(Year(Today()),4) }
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU SELF
ENDIF	
ZANO:=Val(oBUSCA:cBUSCA)
ZCANO:=Str(ZANO,4)
IF ! entramenu("FER",19)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ME01CR.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
cVAR:="CANO='"+ZCANO+"'"
//cVAR:="ANO=ZANO"
oSERVER:SETFILTER(cVAR)
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
PARTIAL CLASS XJRL INHERIT JRL

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",17)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RL.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"RLI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJRLI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRLI,"RL")
SELF:SHOW()

END CLASS
CLASS XJRO INHERIT JRO

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RO.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ROI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJROI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJROI,#RO)
SELF:SHOW()

END CLASS
CLASS XJROAPUD INHERIT JROAPUD

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",21)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ROAPUD.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:SHOW()


END CLASS
CLASS XJSM INHERIT JSM

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",5)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"SM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
CLASS XLFAPU INHERIT JFAPU		

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"FAPU.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"FAPUI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:OSFJFAPUI:USE(oSERVE2)
SELF:oCCLiberar:ENABLE()
SELF:OSFJFAPUI:DISABLE()
SELF:ODCDFIM:Disable()
SELF:oDCDINI:DISABLE()
SELF:oCCAlterar:DISABLE()
SELF:oCCcmdApurar:DISABLE()
SELF:oCCExcluir:DISABLE()
SELF:oCCIncluir:DISABLE()
SELF:oCCTabular:disable()
SELF:oCCProximo:disable()
SELF:oCCAnterior:DISABLE()
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SetSelectiveRelation(oSFJFAPUI,#SEQ)
SELF:Caption:="Liberar Apuração Uso de Ferramentas"
SELF:SHOW()	
	
	
	
	
	
	
	


END CLASS
CLASS XLMAPU INHERIT JFAPU		


CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("FER",16)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MAPU.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MAPUI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:OSFJFAPUI:USE(oSERVE2)
SELF:oCCLiberar:ENABLE()
SELF:OSFJFAPUI:DISABLE()
SELF:ODCDFIM:Disable()
SELF:oDCDINI:DISABLE()
SELF:oCCAlterar:DISABLE()
SELF:oCCcmdApurar:DISABLE()
SELF:oCCExcluir:DISABLE()
SELF:oCCIncluir:DISABLE()
SELF:oCCTabular:disable()
SELF:oCCProximo:disable()
SELF:oCCAnterior:DISABLE()
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SetSelectiveRelation(oSFJFAPUI,#SEQ)
SELF:Caption:="Liberar Apuração Uso de Maquinas"
SELF:SHOW()	
END CLASS

