CLASS XJBTI INHERIT JBTI

METHOD ALTERAR  
SELF:oSFJBTII:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJBTII:Browser:SuspendUpdate()
SELF:oSFJBTII:SkipPrevious()
IF SELF:oSFJBTII:Server:bof
	SELF:oSFJBTII:Skipnext()
ENDIF
SELF:oSFJBTII:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nBTI AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nBTI:=SELF:Server:BTI
nBTI++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("BTI",nBTI)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:commit()
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
RETURN  .T.

METHOD buscaov( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("V1","BREA")	


METHOD DELETE() 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
GRAVALOG(SELF:SERVER:BTIA,"DEL","BTI")	
SELF:oSFJBTII:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJBTII:server:GOTOP()	
WHILE ! oSFJBTII:server:EOF
 	SELF:oSFJBTII:server:delete()
ENDDO	
SELF:server:delete()
SELF:server:unlock()
SELF:server:skipEX(-1)
SELF:oSFJBTII:SERVER:resetnotification()
SELF:oSFJBTII:SERVER:notify(notifyfilechange)	


METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("NOME",oESC:NOME)
ENDIF			

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF		

METHOD EXCLUIR 
IF ! MDG("Apagar Registro") .AND. SELF:oSFJBTII:server:LockCurrentRecord()
	RETU SELF
ENDIF	
SELF:oSFJBTII:server:delete()
SELF:oSFJBTII:server:unlock()
SELF:oSFJBTII:server:skip(-1)
IF SELF:oSFJBTII:server:BOF
   SELF:oSFJBTII:server:GOTOP()
ENDIF
	

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .F.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()
	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("VIA",10)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"BTI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"BTII.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJBTII:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJBTII,"BTI")
SELF:oSFJBTII:VIEWTABLE()
SELF:SHOW()

METHOD NOVO 
SELF:oSFJBTII:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJBTII:SERVER:APPEND()
SELF:oSFJBTII:SERVER:BTI:=SELF:SERVER:BTI
SELF:oSFJBTII:SERVER:commit()
SELF:oSFJBTII:SERVER:resetnotification()
SELF:oSFJBTII:SERVER:notify(notifyappend) //Contas do Livro

METHOD btnPEGMA01( ) 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:CLINOME:=aCLI[2]
ENDIF

METHOD btnPEGMS01( ) 
LOCAL aPRO AS ARRAY
aPRO:=PEGMS01(SELF:SERVER:CODIGO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:SERVER:NOME:=aPRO[2]
ENDIF

METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	   FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJBTII:Browser:SuspendUpdate()
SELF:oSFJBTII:SkipNext()
IF SELF:oSFJBTII:Server:Eof
	SELF:oSFJBTII:SkipPrevious()
ENDIF
SELF:oSFJBTII:Browser:RestoreUpdate()

METHOD TABULAR  
SELF:oSFJBTII:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFjbtii:SERVER:Commit()



END CLASS
