PARTIAL CLASS CDTAB_Page5
METHOD ListBoxSelect(oControlEvent) 
	LOCAL oControl AS Control
    LOCAL aRESP AS ARRAY
	oControl := IIf(oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control)
	SUPER:ListBoxSelect(oControlEvent)
	//Put your changes here
	DO CASE
	       CASE oCONTROL:NAMESYM==#SETOR
                             aRESP:=PEGMP05(SELF:SERVER:SETOR,ZCURINI,ZCURDIR)
                             IF aRESP[1]=.T.
                                  SELF:SERVER:RESPO:=aRESP[2]
                                  SELF:SERVER:CARGO:=aRESP[3]
                             ENDIF
	ENDCASE
	
	RETURN NIL


METHOD comboPEGMP05()
RETU PEGCOMBO("MP05.DBF","DESCRI","CODIGO")

END CLASS
PARTIAL CLASS CDTAB_Page6
METHOD cmdimppeca( ) 
		SELF:server:FIELDPUT("IMPOSTO",SIMNAO(SELF:SERVER:FIELDGET("IMPOSTO")))		

METHOD cmdimppeca1( ) 
	SELF:server:FIELDPUT("FRETE",SIMNAO(SELF:SERVER:FIELDGET("FRETE"),{"R","E","T"}))		

METHOD cmdimppeca2( ) 
SELF:server:FIELDPUT("IMPfer",SIMNAO(SELF:SERVER:FIELDGET("IMPfer")))		

METHOD escres( ) 
	LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NUMPRE",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("NOMPRE",oESCMP04:NOME)
ENDIF

METHOD pegres( ) 
LOCAL aUSO AS ARRAY	
aUSO:=PEGMP04(SELF:SERVER:FIELDGET("NUMPRE"),ZCURINI,ZCURDIR,{ZMES,ZANO,ZEMPRESA})
IF aUSO[1]=.T.
   SELF:SERVER:FIELDPUT("NOMPRE",aUSO[2])
ENDIF


END CLASS
PARTIAL CLASS CDTAB01
METHOD Emailfim( ) 
LOCAL aERRO AS ARRAY	
IF ! Empty(SELF:SERVER:FIELDGET("DATAeMI"))
	alert("Condiçao de Desenvolvimento Já Fechada","Erro Fechamento")
	IF ! MDG("Remarcar a Data Para Hoje")
  	   RETU .F.
  	ENDIF
ENDIF	
SELF:SERVER:FIELDPUT("FUNNUM",zfolha)
SELF:SERVER:FIELDPUT("FUNNOM",ZNOMEFOLHA)
SELF:SERVER:FIELDPUT("DATAeMI",Today())
AERRO:={}
AAdd(aERRO," Condiçao de Desenvolvimento No:"+StrTRIM(SELF:SERVER:FIELDGET("CD"),8,0))
AAdd(aERRO," Produto:"+SELF:SERVER:FIELDGET("PECA")+"-"+SELF:SERVER:FIELDGET("NOME"))
AAdd(aERRO," Cliente:"+SELF:SERVER:FIELDGET("CLINOME"))
AAdd(aERRO,"Concluida: "+DToC(Today()))
EMAILINT("CD000002",ZUSER,aERRO,ZCURINI,zCURDIR)	

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF		

METHOD escmc02( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MC02.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("COMPRADOR",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("COMPNOME",oESC:NOME)
ENDIF		

METHOD ESCRES( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("FUNNUM",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("FUNNOM",oESCMP04:NOME)
ENDIF	

METHOD btnPEGMA01( ) 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:CLINOME:=aCLI[2]
   SELF:SERVER:CLICOGN:=aCLI[3]
   SELF:SERVER:FIELDPUTZ("CODCLI",aCLI[6])
ENDIF

METHOD PEGMC02( ) 
LOCAL aCLI AS ARRAY
aCLI:=PEGMC(SELF:SERVER:COMPRADOR,"MC02.DBF")
IF aCLI[1]=.T.
   SELF:SERVER:COMPNOME:=aCLI[2]
ENDIF	


END CLASS
