PARTIAL CLASS jcdapuprd
METHOD buscaov( ) 
	SELF:KeyFind()

END CLASS
CLASS XJAPUPRD INHERIT jcdapuprd

METHOD chkclipro( ) 
LOCAL oPROGWIN AS PROGWIN
LOCAL nPOS,nLASTREC AS DWORD
LOCAL nPERC AS INT

oProgWin := ProgWin{}
oProgWin:Caption:="Checar Clientes Produtos"
oProgWin:SHOW()
nPOS:=1
nLASTREC:=SELF:SERVER:RECCOUNT


alert("Operacao Pode Demorar conf Qtde CD")	
SELF:SERVER:GOTOP()
WHILE ! SELF:SERVER:EOF
	
	
   nPerc := INT(100* nPOS/ nLASTREC)
   nPOS++
   oProgWin:oDcProgBar:Position := nPerc

   oProgWin:oDCMessage:textValue:=SELF:SERVER:FIELDGET("CODIGO")
	
   IF Empty(SELF:SERVER:FIELDGET("CODIGOINT"))		
      SELF:PEGMS01()
   ENDIF

  IF Empty(SELF:SERVER:FIELDGET("COGCLI"))	
      SELF:btnPEGMA01()
   ENDIF

   SELF:SERVER:SKIP()
ENDDO	
SELF:SERVER:GOTOP()

oPROGWIN:EndDialog()
alert("Checagem Concluida")
	

METHOD esccod( ) 
	LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
//    SELF:SERVER:FIELDPUT("NOME",oESC:NOME)
ENDIF			

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
ENDIF			

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("VIA",13)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CDAPUPRD.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		

METHOD btnPEGMA01( ) 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
//   SELF:SERVER:CLINOME:=aCLI[2]
   SELF:SERVER:FIELDPUT("COGCLI",aCLI[3])
ENDIF

METHOD PEGMS01( ) 
LOCAL aPRO AS ARRAY
IF Empty(SELF:SERVER:FIELDGET("CODIGOINT")) .OR. Empty(SELF:SERVER:FIELDGET("CLIENTE"))
   aPRO:=PEGMSEXT(SELF:SERVER:FIELDGET("CODIGO"),.F.)
   IF aPRO[1]
   	  IF Empty(SELF:SERVER:FIELDGET("CLIENTE")) .AND. ! Empty(aPRO[4])
         SELF:SERVER:FIELDPUT("CLIENTE",aPRO[4])
   	  ENDIF	
   	  IF Empty(SELF:SERVER:FIELDGET("CODIGOINT")) .AND. ! Empty(aPRO[7])
         SELF:SERVER:FIELDPUT("CODIGOINT",aPRO[7])
      ENDIF
   ENDIF	
ENDIF

METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
		   FabCenterWindow( SELF )
	RETURN NIL


METHOD PushButton2( ) 
LOCAL X AS WORD	
FOR x:=1 TO 12
    SELF:SERVER:FIELDPUT("PRC"+StrZero(X,2),SELF:PRECO)
NEXT x	


END CLASS
