CLASS XJFEROS INHERIT JFEROS


METHOD APPEND( ) 
LOCAL nOV AS DWORD	
SELF:server:setorder(1)
SELF:server:gobottom()
nOV:=SELF:Server:FIELDGET("FEROS")
nOV++
SUPER:append()
SELF:SERVER:FIELDPUT("FEROS",nOV)
SELF:SERVER:FIELDPUT("CHAVE",Str(nOV,8))
SELF:SERVER:FIELDPUT("DATAOS",ZDATA)
SELF:SERVER:FIELDPUT("NOME","FERRAMENTAL")
SELF:SERVER:FIELDPUT("CLASSIPI","8207.30.00")
SELF:SERVER:FIELDPUT("CONSUMO","N")
SELF:SERVER:FIELDPUT("SOMANF","S")
SELF:SERVER:FIELDPUT("QTDE",1)
GRAVALOG(Str(nOV),"INC","FEROS")	


METHOD buscaov( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("ME","NF")	


METHOD cmdtipo( ) 
	SELF:server:FIELDPUT("SOMANF",SIMNAO(SELF:SERVER:FIELDGET("SOMANF")))		

METHOD cmdtipo1( ) 
	SELF:server:FIELDPUT("CONSUMO",SIMNAO(SELF:SERVER:FIELDGET("CONSUMO")))		

METHOD cmdtipo2( ) 
  SELF:server:FIELDPUT("TIPO",SIMNAO(SELF:SERVER:FIELDGET("TIPO"),{"F","M"}))		

METHOD DELETE( ) 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
GRAVALOG(SELF:SERVER:FIELDGET("FEROS"),"DEL","FEROS")	
SELF:server:delete()
SELF:server:unlock()
SELF:server:skipEX(-1)


METHOD duplicar(nTIPO) 
LOCAL nFEROS AS DWORD
LOCAL nFIELD AS DWORD
LOCAL nANTIGO,nDIGCTR AS DWORD
LOCAL J AS WORD
LOCAL aDADOS AS ARRAY
LOCAL cREVISAO AS STRING


IF ! MDG("Duplicar Registro")
    RETURN   .F.
ENDIF
AltD()

aDADOS:={}
nFIELD:=SELF:SERVER:FCOUNT
nANTIGO:=SELF:Server:FIELDGET("FEROS")
cREVISAO:=SELF:Server:FIELDGET("REVISAO")
FOR J:=1 TO nFIELD
    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
NEXT J

IF nTIPO=2
   nFEROS:=SELF:Server:FIELDGET("FEROS")
   SELF:server:setorder(1)
   WHILE nFEROS=SELF:SERVER:FIELDGET("FEROS") .AND. ! SELF:SERVER:EOF
       cREVISAO:=SELF:SERVER:FIELDGET("REVISAO")
       SELF:SERVER:SKIP()
   ENDDO
   IF Empty(cREVISAO)
   	  cREVISAO:="A"
   ELSE
      nDIGCTR:=Asc(cREVISAO)	
      cREVISAO:=Chr(nDIGCTR+1)
   ENDIF	
ELSE	
	SELF:server:setorder(1)
	SELF:server:gobottom()
	nFEROS:=SELF:Server:FIELDGET("FEROS")
	nFEROS++
	cREVISAO:=" "	
ENDIF	

//Grava Campos
SUPER:SERVER:APPEND()
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    SELF:SERVER:FIELDPUT(J,aDADOS[J])
NEXT J
//Grava Complementos
SELF:SERVER:FIELDPUT("FEROS",nFEROS)
SELF:SERVER:FIELDPUT("ANTIGO",nANTIGO)
SELF:SERVER:FIELDPUT("REVISAO",cREVISAO)
SELF:SERVER:FIELDPUT("CHAVE",Str(nFEROS,8)+cREVISAO)
//Posiciona
SELF:server:gotop()
IF nTIPO=2
   SELF:server:SEEK(Str(nFEROS,8)+cREVISAO)	
ELSE	
   SELF:server:gobottom()
ENDIF	
RETURN  .T.


METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:btnPEGMA01()
ENDIF

CONSTRUCTOR(oOWNER) 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE		
IF ! entramenu("VIA",11)
	RETU SELF
ENDIF		
aDAD:={zCURINI,"FEROS.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oserver)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		


METHOD btnPEGMA01( ) 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:FIELDGET("CLIENTE"),ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:FIELDPUT("COGcli",aCLI[3])
ENDIF	

METHOD porov( ) 
	SELF:KeyFinD()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	   FabCenterWindow( SELF )
 RETURN SELF

METHOD PushButton10( ) 
	SELF:duplicar(2)

METHOD PushButton6( ) 
SELF:SERVER:FIELDPUT("VALORMER",SELF:SERVER:FIELDGET("QTDE")*SELF:SERVER:FIELDGET("PRECO"))
SELF:SERVER:FIELDPUT("VALORIPI",SELF:SERVER:FIELDGET("BASEIPI")*SELF:SERVER:FIELDGET("IPI")/100)
IF SELF:SERVER:FIELDGET("SOMANF")="S"
   SELF:SERVER:FIELDPUT("VALORTOT",SELF:SERVER:FIELDGET("VALORMER")+SELF:SERVER:FIELDGET("VALORIPI"))	
ELSE
   SELF:SERVER:FIELDPUT("VALORTOT",SELF:SERVER:FIELDGET("VALORMER"))		
ENDIF	

SELF:SERVER:FIELDPUT("VALORICM",SELF:SERVER:FIELDGET("BASEICM")*SELF:SERVER:FIELDGET("ICM")/100)

METHOD PushButton7( ) 
	SELF:SERVER:FIELDPUT("BASEICM",SELF:SERVER:FIELDGET("VALORMER"))

METHOD PushButton8( ) 
		SELF:SERVER:FIELDPUT("BASEIPI",SELF:SERVER:FIELDGET("VALORMER"))

METHOD PushButton9( ) 
	SELF:duplicar(1)

METHOD Timer() 
   SELF:SERVER:COMMIT()




END CLASS
