#region DEFINES
STATIC DEFINE JFEROS_ADTODATA := 127
STATIC DEFINE JFEROS_ADTOVALOR := 126
STATIC DEFINE JFEROS_ANTIGO := 160
STATIC DEFINE JFEROS_BASEICM := 119
STATIC DEFINE JFEROS_BASEIPI := 113
STATIC DEFINE JFEROS_BUSCAOV := 162
STATIC DEFINE JFEROS_CLASSIPI := 117
STATIC DEFINE JFEROS_CLIENTE := 100
STATIC DEFINE JFEROS_CMDTIPO := 165
STATIC DEFINE JFEROS_CMDTIPO1 := 166
STATIC DEFINE JFEROS_CMDTIPO2 := 178
STATIC DEFINE JFEROS_CODIPI := 114
STATIC DEFINE JFEROS_COGCLI := 101
STATIC DEFINE JFEROS_CONSUMO := 158
STATIC DEFINE JFEROS_DATANF := 107
STATIC DEFINE JFEROS_DATAOS := 102
STATIC DEFINE JFEROS_DATAPE := 103
STATIC DEFINE JFEROS_DATAPRZ := 104
STATIC DEFINE JFEROS_ESCFOR := 164
STATIC DEFINE JFEROS_FEROS := 157
STATIC DEFINE JFEROS_FERRAM := 108
STATIC DEFINE JFEROS_GP11PDATA := 125
STATIC DEFINE JFEROS_GP11PREV := 124
STATIC DEFINE JFEROS_ICM := 120
STATIC DEFINE JFEROS_IPI := 115
STATIC DEFINE JFEROS_NFPGVCTO := 181
STATIC DEFINE JFEROS_NOME := 109
STATIC DEFINE JFEROS_NRNOTA := 106
STATIC DEFINE JFEROS_OBS := 128
STATIC DEFINE JFEROS_OBS2 := 129
STATIC DEFINE JFEROS_PEDIDOCLI := 105
STATIC DEFINE JFEROS_PEGMA01 := 163 
STATIC DEFINE JFEROS_POROV := 161
STATIC DEFINE JFEROS_PPAPDATA := 123
STATIC DEFINE JFEROS_PPAPPREV := 122
STATIC DEFINE JFEROS_PRECO := 111
STATIC DEFINE JFEROS_PUSHBUTTON10 := 177
STATIC DEFINE JFEROS_PUSHBUTTON6 := 167
STATIC DEFINE JFEROS_PUSHBUTTON7 := 168
STATIC DEFINE JFEROS_PUSHBUTTON8 := 169
STATIC DEFINE JFEROS_PUSHBUTTON9 := 171
STATIC DEFINE JFEROS_QTDE := 110
STATIC DEFINE JFEROS_REVISAO := 130
STATIC DEFINE JFEROS_SC_ANTIGO := 156
STATIC DEFINE JFEROS_SC_BASEICM := 144
STATIC DEFINE JFEROS_SC_BASEIPI := 145
STATIC DEFINE JFEROS_SC_CLASSIPI := 154
STATIC DEFINE JFEROS_SC_CLIENTE := 132
STATIC DEFINE JFEROS_SC_CODIPI := 153
STATIC DEFINE JFEROS_SC_CONSUMO := 148
STATIC DEFINE JFEROS_SC_CONSUMO1 := 180
STATIC DEFINE JFEROS_SC_DATANF := 137
STATIC DEFINE JFEROS_SC_DATANF1 := 182
STATIC DEFINE JFEROS_SC_DATAOS := 135
STATIC DEFINE JFEROS_SC_DATAOS1 := 172
STATIC DEFINE JFEROS_SC_DATAOS2 := 173
STATIC DEFINE JFEROS_SC_DATAOS3 := 174
STATIC DEFINE JFEROS_SC_DATAOS4 := 175
STATIC DEFINE JFEROS_SC_DATAPE := 136
STATIC DEFINE JFEROS_SC_DATAPRZ := 138
STATIC DEFINE JFEROS_SC_FEROS := 131
STATIC DEFINE JFEROS_SC_FERRAM := 133
STATIC DEFINE JFEROS_SC_ICM := 146
STATIC DEFINE JFEROS_SC_IPI := 147
STATIC DEFINE JFEROS_SC_NOME := 134
STATIC DEFINE JFEROS_SC_NRNOTA := 139
STATIC DEFINE JFEROS_SC_NRNOTA1 := 170
STATIC DEFINE JFEROS_SC_OBS := 152
STATIC DEFINE JFEROS_SC_PEDIDOCLI := 155
STATIC DEFINE JFEROS_SC_PRECO := 151
STATIC DEFINE JFEROS_SC_PRECO1 := 176
STATIC DEFINE JFEROS_SC_QTDE := 150
STATIC DEFINE JFEROS_SC_SOMANF := 149
STATIC DEFINE JFEROS_SC_VALORICM := 141
STATIC DEFINE JFEROS_SC_VALORIPI := 142
STATIC DEFINE JFEROS_SC_VALORMER := 140
STATIC DEFINE JFEROS_SC_VALORTOT := 143
STATIC DEFINE JFEROS_SOMANF := 159
STATIC DEFINE JFEROS_TIPO := 179
STATIC DEFINE JFEROS_VALORICM := 121
STATIC DEFINE JFEROS_VALORIPI := 116
STATIC DEFINE JFEROS_VALORMER := 112
STATIC DEFINE JFEROS_VALORTOT := 118
#endregion

PARTIAL CLASS jferos INHERIT MYDataWindow
PROTECT oDBFEROS AS DataColumn
PROTECT oDBCLIENTE AS DataColumn
PROTECT oDBCOGCLI AS DataColumn
PROTECT oDBFERRAM AS DataColumn
PROTECT oDBDATAPRZ AS DataColumn
PROTECT oDBNRNOTA AS DataColumn
PROTECT oDBPEDIDOCLI AS DataColumn
PROTECT oDCCLIENTE AS rightSle
PROTECT oDCCOGCLI AS SINGLELINEEDIT
PROTECT oDCDATAOS AS DateSle
PROTECT oDCDATAPE AS DateSle
PROTECT oDCDATAPRZ AS DateSle
PROTECT oDCPEDIDOCLI AS SINGLELINEEDIT
PROTECT oDCNRNOTA AS rightSle
PROTECT oDCDATANF AS DateSle
PROTECT oDCFERRAM AS SINGLELINEEDIT
PROTECT oDCNOME AS SINGLELINEEDIT
PROTECT oDCQTDE AS rightSle
PROTECT oDCPRECO AS rightSle
PROTECT oDCVALORMER AS rightSle
PROTECT oDCBASEIPI AS rightSle
PROTECT oDCCODIPI AS SINGLELINEEDIT
PROTECT oDCIPI AS rightSle
PROTECT oDCVALORIPI AS rightSle
PROTECT oDCCLASSIPI AS SINGLELINEEDIT
PROTECT oDCVALORTOT AS rightSle
PROTECT oDCBASEICM AS rightSle
PROTECT oDCICM AS rightSle
PROTECT oDCVALORICM AS rightSle
PROTECT oDCPPAPPREV AS DateSle
PROTECT oDCPPAPDATA AS DateSle
PROTECT oDCGP11PREV AS DateSle
PROTECT oDCGP11PDATA AS DateSle
PROTECT oDCADTOVALOR AS rightSle
PROTECT oDCADTODATA AS DateSle
PROTECT oDCOBS AS MULTILINEEDIT
PROTECT oDCOBS2 AS MULTILINEEDIT
PROTECT oDCrevisao AS rightSle
PROTECT oDCSC_FEROS AS FIXEDTEXT
PROTECT oDCSC_CLIENTE AS FIXEDTEXT
PROTECT oDCSC_FERRAM AS FIXEDTEXT
PROTECT oDCSC_NOME AS FIXEDTEXT
PROTECT oDCSC_DATAOS AS FIXEDTEXT
PROTECT oDCSC_DATAPE AS FIXEDTEXT
PROTECT oDCSC_DATANF AS FIXEDTEXT
PROTECT oDCSC_DATAPRZ AS FIXEDTEXT
PROTECT oDCSC_NRNOTA AS FIXEDTEXT
PROTECT oDCSC_VALORMER AS FIXEDTEXT
PROTECT oDCSC_VALORICM AS FIXEDTEXT
PROTECT oDCSC_VALORIPI AS FIXEDTEXT
PROTECT oDCSC_VALORTOT AS FIXEDTEXT
PROTECT oDCSC_BASEICM AS FIXEDTEXT
PROTECT oDCSC_BASEIPI AS FIXEDTEXT
PROTECT oDCSC_ICM AS FIXEDTEXT
PROTECT oDCSC_IPI AS FIXEDTEXT
PROTECT oDCSC_CONSUMO AS FIXEDTEXT
PROTECT oDCSC_SOMANF AS FIXEDTEXT
PROTECT oDCSC_QTDE AS FIXEDTEXT
PROTECT oDCSC_PRECO AS FIXEDTEXT
PROTECT oDCSC_OBS AS FIXEDTEXT
PROTECT oDCSC_CODIPI AS FIXEDTEXT
PROTECT oDCSC_CLASSIPI AS FIXEDTEXT
PROTECT oDCSC_PEDIDOCLI AS FIXEDTEXT
PROTECT oDCSC_ANTIGO AS FIXEDTEXT
PROTECT oDCFEROS AS SINGLELINEEDIT
PROTECT oDCCONSUMO AS SINGLELINEEDIT
PROTECT oDCSOMANF AS SINGLELINEEDIT
PROTECT oDCANTIGO AS SINGLELINEEDIT
PROTECT oCCporov AS PUSHBUTTON
PROTECT oCCbuscaov AS PUSHBUTTON
PROTECT oCCbtnpegma01 AS PUSHBUTTON
PROTECT oCCescfor AS PUSHBUTTON
PROTECT oCCcmdtipo AS PUSHBUTTON
PROTECT oCCcmdtipo1 AS PUSHBUTTON
PROTECT oCCPushButton6 AS PUSHBUTTON
PROTECT oCCPushButton7 AS PUSHBUTTON
PROTECT oCCPushButton8 AS PUSHBUTTON
PROTECT oDCSC_NRNOTA1 AS FIXEDTEXT
PROTECT oCCPushButton9 AS PUSHBUTTON
PROTECT oDCSC_DATAOS1 AS FIXEDTEXT
PROTECT oDCSC_DATAOS2 AS FIXEDTEXT
PROTECT oDCSC_DATAOS3 AS FIXEDTEXT
PROTECT oDCSC_DATAOS4 AS FIXEDTEXT
PROTECT oDCSC_PRECO1 AS FIXEDTEXT
PROTECT oCCPushButton10 AS PUSHBUTTON
PROTECT oCCcmdtipo2 AS PUSHBUTTON
PROTECT oDCTIPO AS SINGLELINEEDIT
PROTECT oDCSC_CONSUMO1 AS FIXEDTEXT
PROTECT oDCNFPGVCTO AS DateSle
PROTECT oDCSC_DATANF1 AS FIXEDTEXT

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS ADTODATA
RETURN SELF:FieldGet( #ADTODATA )

ASSIGN ADTODATA( uValue )
SELF:FieldPut( #ADTODATA , uValue )

ACCESS ADTOVALOR
RETURN SELF:FieldGet( #ADTOVALOR )

ASSIGN ADTOVALOR( uValue )
SELF:FieldPut( #ADTOVALOR , uValue )

ACCESS ANTIGO
RETURN SELF:FieldGet( #ANTIGO )

ASSIGN ANTIGO( uValue )
SELF:FieldPut( #ANTIGO , uValue )

ACCESS BASEICM
RETURN SELF:FieldGet( #BASEICM )

ASSIGN BASEICM( uValue )
SELF:FieldPut( #BASEICM , uValue )

ACCESS BASEIPI
RETURN SELF:FieldGet( #BASEIPI )

ASSIGN BASEIPI( uValue )
SELF:FieldPut( #BASEIPI , uValue )

ACCESS CLASSIPI
RETURN SELF:FieldGet( #CLASSIPI )

ASSIGN CLASSIPI( uValue )
SELF:FieldPut( #CLASSIPI , uValue )

ACCESS CLIENTE
RETURN SELF:FieldGet( #CLIENTE )

ASSIGN CLIENTE( uValue )
SELF:FieldPut( #CLIENTE , uValue )

ACCESS CODIPI
RETURN SELF:FieldGet( #CODIPI )

ASSIGN CODIPI( uValue )
SELF:FieldPut( #CODIPI , uValue )

ACCESS COGCLI
RETURN SELF:FieldGet( #COGCLI )

ASSIGN COGCLI( uValue )
SELF:FieldPut( #COGCLI , uValue )

ACCESS CONSUMO
RETURN SELF:FieldGet( #CONSUMO )

ASSIGN CONSUMO( uValue )
SELF:FieldPut( #CONSUMO , uValue )

ACCESS DATANF
RETURN SELF:FieldGet( #DATANF )

ASSIGN DATANF( uValue )
SELF:FieldPut( #DATANF , uValue )

ACCESS DATAOS
RETURN SELF:FieldGet( #DATAOS )

ASSIGN DATAOS( uValue )
SELF:FieldPut( #DATAOS , uValue )

ACCESS DATAPE
RETURN SELF:FieldGet( #DATAPE )

ASSIGN DATAPE( uValue )
SELF:FieldPut( #DATAPE , uValue )

ACCESS DATAPRZ
RETURN SELF:FieldGet( #DATAPRZ )

ASSIGN DATAPRZ( uValue )
SELF:FieldPut( #DATAPRZ , uValue )

ACCESS FEROS
RETURN SELF:FieldGet( #FEROS )

ASSIGN FEROS( uValue )
SELF:FieldPut( #FEROS , uValue )

ACCESS FERRAM
RETURN SELF:FieldGet( #FERRAM )

ASSIGN FERRAM( uValue )
SELF:FieldPut( #FERRAM , uValue )

ACCESS GP11PDATA
RETURN SELF:FieldGet( #GP11PDATA )

ASSIGN GP11PDATA( uValue )
SELF:FieldPut( #GP11PDATA , uValue )

ACCESS GP11PREV
RETURN SELF:FieldGet( #GP11PREV )

ASSIGN GP11PREV( uValue )
SELF:FieldPut( #GP11PREV , uValue )

ACCESS ICM
RETURN SELF:FieldGet( #ICM )

ASSIGN ICM( uValue )
SELF:FieldPut( #ICM , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"jferos" , _GetInst()},iCtlID)

	SELF:oDCCLIENTE := rightSle{SELF , ResourceID{ JFEROS_CLIENTE  , _GetInst() } }
	SELF:oDCCLIENTE:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCCLIENTE:HyperLabel := HyperLabel{#CLIENTE , "Cliente:" , NULL_STRING , "FEROS_CLIENTE"}

	SELF:oDCCOGCLI := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_COGCLI  , _GetInst() } }
	SELF:oDCCOGCLI:FieldSpec := PADRAO_CHAR_12{}
	SELF:oDCCOGCLI:HyperLabel := HyperLabel{#COGCLI , "Cogcli:" , NULL_STRING , "FEROS_COGCLI"}

	SELF:oDCDATAOS := DateSle{SELF , ResourceID{ JFEROS_DATAOS  , _GetInst() } }
	SELF:oDCDATAOS:FieldSpec := date_field{}
	SELF:oDCDATAOS:HyperLabel := HyperLabel{#DATAOS , "Dataos:" , NULL_STRING , "FEROS_DATAOS"}

	SELF:oDCDATAPE := DateSle{SELF , ResourceID{ JFEROS_DATAPE  , _GetInst() } }
	SELF:oDCDATAPE:FieldSpec := date_field{}
	SELF:oDCDATAPE:HyperLabel := HyperLabel{#DATAPE , "Datape:" , NULL_STRING , "FEROS_DATAPE"}

	SELF:oDCDATAPRZ := DateSle{SELF , ResourceID{ JFEROS_DATAPRZ  , _GetInst() } }
	SELF:oDCDATAPRZ:FieldSpec := date_field{}
	SELF:oDCDATAPRZ:HyperLabel := HyperLabel{#DATAPRZ , "Dataprz:" , NULL_STRING , "FEROS_DATAPRZ"}

	SELF:oDCPEDIDOCLI := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_PEDIDOCLI  , _GetInst() } }
	SELF:oDCPEDIDOCLI:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCPEDIDOCLI:HyperLabel := HyperLabel{#PEDIDOCLI , "Pedidocli:" , NULL_STRING , "FEROS_PEDIDOCLI"}

	SELF:oDCNRNOTA := rightSle{SELF , ResourceID{ JFEROS_NRNOTA  , _GetInst() } }
	SELF:oDCNRNOTA:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNRNOTA:HyperLabel := HyperLabel{#NRNOTA , "Nrnota:" , NULL_STRING , "FEROS_NRNOTA"}

	SELF:oDCDATANF := DateSle{SELF , ResourceID{ JFEROS_DATANF  , _GetInst() } }
	SELF:oDCDATANF:FieldSpec := DATE_FIELD{}
	SELF:oDCDATANF:HyperLabel := HyperLabel{#DATANF , "Datanf:" , NULL_STRING , "FEROS_DATANF"}

	SELF:oDCFERRAM := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_FERRAM  , _GetInst() } }
	SELF:oDCFERRAM:FieldSpec := PADRAO_CHAR_24{}
	SELF:oDCFERRAM:HyperLabel := HyperLabel{#FERRAM , "Ferram:" , NULL_STRING , "FEROS_FERRAM"}

	SELF:oDCNOME := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_NOME  , _GetInst() } }
	SELF:oDCNOME:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCNOME:HyperLabel := HyperLabel{#NOME , "Nome:" , NULL_STRING , "FEROS_NOME"}

	SELF:oDCQTDE := rightSle{SELF , ResourceID{ JFEROS_QTDE  , _GetInst() } }
	SELF:oDCQTDE:FieldSpec := PADRAO_NUM_02{}
	SELF:oDCQTDE:HyperLabel := HyperLabel{#QTDE , "Qtde:" , NULL_STRING , "FEROS_QTDE"}

	SELF:oDCPRECO := rightSle{SELF , ResourceID{ JFEROS_PRECO  , _GetInst() } }
	SELF:oDCPRECO:FieldSpec := PADRAO_NUM_12_2{}
	SELF:oDCPRECO:HyperLabel := HyperLabel{#PRECO , "Preco:" , NULL_STRING , "FEROS_PRECO"}

	SELF:oDCVALORMER := rightSle{SELF , ResourceID{ JFEROS_VALORMER  , _GetInst() } }
	SELF:oDCVALORMER:FieldSpec := PADRAO_NUM_12_2{}
	SELF:oDCVALORMER:HyperLabel := HyperLabel{#VALORMER , "Valormer:" , NULL_STRING , "FEROS_VALORMER"}

	SELF:oDCBASEIPI := rightSle{SELF , ResourceID{ JFEROS_BASEIPI  , _GetInst() } }
	SELF:oDCBASEIPI:FieldSpec := PADRAO_NUM_12_2{}
	SELF:oDCBASEIPI:HyperLabel := HyperLabel{#BASEIPI , "Baseipi:" , NULL_STRING , "FEROS_BASEIPI"}

	SELF:oDCCODIPI := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_CODIPI  , _GetInst() } }
	SELF:oDCCODIPI:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCCODIPI:HyperLabel := HyperLabel{#CODIPI , "Codipi:" , NULL_STRING , "FEROS_CODIPI"}

	SELF:oDCIPI := rightSle{SELF , ResourceID{ JFEROS_IPI  , _GetInst() } }
	SELF:oDCIPI:FieldSpec := PADRAO_NUM_05_2{}
	SELF:oDCIPI:HyperLabel := HyperLabel{#IPI , "Ipi:" , NULL_STRING , "FEROS_IPI"}

	SELF:oDCVALORIPI := rightSle{SELF , ResourceID{ JFEROS_VALORIPI  , _GetInst() } }
	SELF:oDCVALORIPI:FieldSpec := PADRAO_NUM_12_2{}
	SELF:oDCVALORIPI:HyperLabel := HyperLabel{#VALORIPI , "Valoripi:" , NULL_STRING , "FEROS_VALORIPI"}

	SELF:oDCCLASSIPI := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_CLASSIPI  , _GetInst() } }
	SELF:oDCCLASSIPI:FieldSpec := PADRAO_CHAR_10{}
	SELF:oDCCLASSIPI:HyperLabel := HyperLabel{#CLASSIPI , "Classipi:" , NULL_STRING , "FEROS_CLASSIPI"}

	SELF:oDCVALORTOT := rightSle{SELF , ResourceID{ JFEROS_VALORTOT  , _GetInst() } }
	SELF:oDCVALORTOT:FieldSpec := PADRAO_NUM_12_2{}
	SELF:oDCVALORTOT:HyperLabel := HyperLabel{#VALORTOT , "Valortot:" , NULL_STRING , "FEROS_VALORTOT"}

	SELF:oDCBASEICM := rightSle{SELF , ResourceID{ JFEROS_BASEICM  , _GetInst() } }
	SELF:oDCBASEICM:FieldSpec := PADRAO_NUM_12_2{}
	SELF:oDCBASEICM:HyperLabel := HyperLabel{#BASEICM , "Baseicm:" , NULL_STRING , "FEROS_BASEICM"}

	SELF:oDCICM := rightSle{SELF , ResourceID{ JFEROS_ICM  , _GetInst() } }
	SELF:oDCICM:FieldSpec := PADRAO_NUM_05_2{}
	SELF:oDCICM:HyperLabel := HyperLabel{#ICM , "Icm:" , NULL_STRING , "FEROS_ICM"}

	SELF:oDCVALORICM := rightSle{SELF , ResourceID{ JFEROS_VALORICM  , _GetInst() } }
	SELF:oDCVALORICM:FieldSpec := PADRAO_NUM_12_2{}
	SELF:oDCVALORICM:HyperLabel := HyperLabel{#VALORICM , "Valoricm:" , NULL_STRING , "FEROS_VALORICM"}

	SELF:oDCPPAPPREV := DateSle{SELF , ResourceID{ JFEROS_PPAPPREV  , _GetInst() } }
	SELF:oDCPPAPPREV:FieldSpec := date_field{}
	SELF:oDCPPAPPREV:HyperLabel := HyperLabel{#PPAPPREV , "Dataos:" , NULL_STRING , "FEROS_DATAOS"}

	SELF:oDCPPAPDATA := DateSle{SELF , ResourceID{ JFEROS_PPAPDATA  , _GetInst() } }
	SELF:oDCPPAPDATA:FieldSpec := date_field{}
	SELF:oDCPPAPDATA:HyperLabel := HyperLabel{#PPAPDATA , "Dataos:" , NULL_STRING , "FEROS_DATAOS"}

	SELF:oDCGP11PREV := DateSle{SELF , ResourceID{ JFEROS_GP11PREV  , _GetInst() } }
	SELF:oDCGP11PREV:FieldSpec := date_field{}
	SELF:oDCGP11PREV:HyperLabel := HyperLabel{#GP11PREV , "Dataos:" , NULL_STRING , "FEROS_DATAOS"}

	SELF:oDCGP11PDATA := DateSle{SELF , ResourceID{ JFEROS_GP11PDATA  , _GetInst() } }
	SELF:oDCGP11PDATA:FieldSpec := date_field{}
	SELF:oDCGP11PDATA:HyperLabel := HyperLabel{#GP11PDATA , "Dataos:" , NULL_STRING , "FEROS_DATAOS"}

	SELF:oDCADTOVALOR := rightSle{SELF , ResourceID{ JFEROS_ADTOVALOR  , _GetInst() } }
	SELF:oDCADTOVALOR:FieldSpec := PADRAO_NUM_12_2{}
	SELF:oDCADTOVALOR:HyperLabel := HyperLabel{#ADTOVALOR , "Preco:" , NULL_STRING , "FEROS_PRECO"}

	SELF:oDCADTODATA := DateSle{SELF , ResourceID{ JFEROS_ADTODATA  , _GetInst() } }
	SELF:oDCADTODATA:FieldSpec := date_field{}
	SELF:oDCADTODATA:HyperLabel := HyperLabel{#ADTODATA , "Dataos:" , NULL_STRING , "FEROS_DATAOS"}

	SELF:oDCOBS := MULTILINEEDIT{SELF , ResourceID{ JFEROS_OBS  , _GetInst() } }
	SELF:oDCOBS:FieldSpec := PADRAO_CHAR_255{}
	SELF:oDCOBS:HyperLabel := HyperLabel{#OBS , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCOBS2 := MULTILINEEDIT{SELF , ResourceID{ JFEROS_OBS2  , _GetInst() } }
	SELF:oDCOBS2:FieldSpec := PADRAO_CHAR_255{}
	SELF:oDCOBS2:HyperLabel := HyperLabel{#OBS2 , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCrevisao := rightSle{SELF , ResourceID{ JFEROS_REVISAO  , _GetInst() } }
	SELF:oDCrevisao:FieldSpec := padrao_char_01{}
	SELF:oDCrevisao:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCrevisao:Font( oFont )
	SELF:oDCrevisao:HyperLabel := HyperLabel{#revisao , "Nrnota:" , NULL_STRING , "FEROS_NRNOTA"}

	SELF:oDCSC_FEROS := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_FEROS  , _GetInst() } }
	SELF:oDCSC_FEROS:HyperLabel := HyperLabel{#SC_FEROS , "Nº" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CLIENTE := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_CLIENTE  , _GetInst() } }
	SELF:oDCSC_CLIENTE:HyperLabel := HyperLabel{#SC_CLIENTE , "Cliente:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_FERRAM := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_FERRAM  , _GetInst() } }
	SELF:oDCSC_FERRAM:HyperLabel := HyperLabel{#SC_FERRAM , "Ferramenta:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_NOME  , _GetInst() } }
	SELF:oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME , "Nome:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAOS := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATAOS  , _GetInst() } }
	SELF:oDCSC_DATAOS:HyperLabel := HyperLabel{#SC_DATAOS , "Data:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAPE := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATAPE  , _GetInst() } }
	SELF:oDCSC_DATAPE:HyperLabel := HyperLabel{#SC_DATAPE , "Pedido" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATANF := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATANF  , _GetInst() } }
	SELF:oDCSC_DATANF:HyperLabel := HyperLabel{#SC_DATANF , "Data:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAPRZ := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATAPRZ  , _GetInst() } }
	SELF:oDCSC_DATAPRZ:HyperLabel := HyperLabel{#SC_DATAPRZ , "Prazo" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NRNOTA := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_NRNOTA  , _GetInst() } }
	SELF:oDCSC_NRNOTA:HyperLabel := HyperLabel{#SC_NRNOTA , "Nrnota:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_VALORMER := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_VALORMER  , _GetInst() } }
	SELF:oDCSC_VALORMER:HyperLabel := HyperLabel{#SC_VALORMER , "Mercadoria:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_VALORICM := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_VALORICM  , _GetInst() } }
	SELF:oDCSC_VALORICM:HyperLabel := HyperLabel{#SC_VALORICM , "ICM" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_VALORIPI := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_VALORIPI  , _GetInst() } }
	SELF:oDCSC_VALORIPI:HyperLabel := HyperLabel{#SC_VALORIPI , "IPI" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_VALORTOT := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_VALORTOT  , _GetInst() } }
	SELF:oDCSC_VALORTOT:HyperLabel := HyperLabel{#SC_VALORTOT , "Total" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_BASEICM := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_BASEICM  , _GetInst() } }
	SELF:oDCSC_BASEICM:HyperLabel := HyperLabel{#SC_BASEICM , "Base ICMS:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_BASEIPI := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_BASEIPI  , _GetInst() } }
	SELF:oDCSC_BASEIPI:HyperLabel := HyperLabel{#SC_BASEIPI , "Base IPI" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ICM := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_ICM  , _GetInst() } }
	SELF:oDCSC_ICM:HyperLabel := HyperLabel{#SC_ICM , "ICM %" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_IPI := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_IPI  , _GetInst() } }
	SELF:oDCSC_IPI:HyperLabel := HyperLabel{#SC_IPI , "Ipi:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CONSUMO := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_CONSUMO  , _GetInst() } }
	SELF:oDCSC_CONSUMO:HyperLabel := HyperLabel{#SC_CONSUMO , "Consumo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SOMANF := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_SOMANF  , _GetInst() } }
	SELF:oDCSC_SOMANF:HyperLabel := HyperLabel{#SC_SOMANF , "Soma IPI NF" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTDE := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_QTDE  , _GetInst() } }
	SELF:oDCSC_QTDE:HyperLabel := HyperLabel{#SC_QTDE , "Qtde:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PRECO := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_PRECO  , _GetInst() } }
	SELF:oDCSC_PRECO:HyperLabel := HyperLabel{#SC_PRECO , "Preco:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_OBS := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_OBS  , _GetInst() } }
	SELF:oDCSC_OBS:HyperLabel := HyperLabel{#SC_OBS , "Obs:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CODIPI := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_CODIPI  , _GetInst() } }
	SELF:oDCSC_CODIPI:HyperLabel := HyperLabel{#SC_CODIPI , "Codipi:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CLASSIPI := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_CLASSIPI  , _GetInst() } }
	SELF:oDCSC_CLASSIPI:HyperLabel := HyperLabel{#SC_CLASSIPI , "Classificacao NCM/IPI" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PEDIDOCLI := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_PEDIDOCLI  , _GetInst() } }
	SELF:oDCSC_PEDIDOCLI:HyperLabel := HyperLabel{#SC_PEDIDOCLI , "Pedidocli:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ANTIGO := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_ANTIGO  , _GetInst() } }
	SELF:oDCSC_ANTIGO:HyperLabel := HyperLabel{#SC_ANTIGO , "Antigo:" , NULL_STRING , NULL_STRING}

	SELF:oDCFEROS := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_FEROS  , _GetInst() } }
	SELF:oDCFEROS:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCFEROS:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCFEROS:Font( oFont )
	SELF:oDCFEROS:HyperLabel := HyperLabel{#FEROS , "Feros:" , NULL_STRING , "FEROS_FEROS"}

	SELF:oDCCONSUMO := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_CONSUMO  , _GetInst() } }
	SELF:oDCCONSUMO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCCONSUMO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCCONSUMO:Font( oFont )
	SELF:oDCCONSUMO:HyperLabel := HyperLabel{#CONSUMO , "Consumo:" , NULL_STRING , "FEROS_CONSUMO"}

	SELF:oDCSOMANF := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_SOMANF  , _GetInst() } }
	SELF:oDCSOMANF:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCSOMANF:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCSOMANF:Font( oFont )
	SELF:oDCSOMANF:HyperLabel := HyperLabel{#SOMANF , "Somanf:" , NULL_STRING , "FEROS_SOMANF"}

	SELF:oDCANTIGO := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_ANTIGO  , _GetInst() } }
	SELF:oDCANTIGO:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCANTIGO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCANTIGO:Font( oFont )
	SELF:oDCANTIGO:HyperLabel := HyperLabel{#ANTIGO , "Antigo:" , NULL_STRING , "FEROS_ANTIGO"}

	SELF:oCCporov := PUSHBUTTON{SELF , ResourceID{ JFEROS_POROV  , _GetInst() } }
	SELF:oCCporov:TooltipText := "Clique para ordenar por Numero"
	SELF:oCCporov:Image := ICO_AZ{}
	SELF:oCCporov:HyperLabel := HyperLabel{#porov , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscaov := PUSHBUTTON{SELF , ResourceID{ JFEROS_BUSCAOV  , _GetInst() } }
	SELF:oCCbuscaov:TooltipText := "Clique Para Localizar Por Numero"
	SELF:oCCbuscaov:Image := ICO_FIND{}
	SELF:oCCbuscaov:HyperLabel := HyperLabel{#buscaov , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbtnpegma01 := PUSHBUTTON{SELF , ResourceID{ JFEROS_BTNPEGMA01  , _GetInst() } }
	SELF:oCCbtnpegma01:HyperLabel := HyperLabel{#btnpegma01 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCescfor := PUSHBUTTON{SELF , ResourceID{ JFEROS_ESCFOR  , _GetInst() } }
	SELF:oCCescfor:HyperLabel := HyperLabel{#escfor , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCcmdtipo := PUSHBUTTON{SELF , ResourceID{ JFEROS_CMDTIPO  , _GetInst() } }
	SELF:oCCcmdtipo:HyperLabel := HyperLabel{#cmdtipo , "Sim/Nao" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdtipo1 := PUSHBUTTON{SELF , ResourceID{ JFEROS_CMDTIPO1  , _GetInst() } }
	SELF:oCCcmdtipo1:HyperLabel := HyperLabel{#cmdtipo1 , "Sim/Nao" , NULL_STRING , NULL_STRING}

	SELF:oCCPushButton6 := PUSHBUTTON{SELF , ResourceID{ JFEROS_PUSHBUTTON6  , _GetInst() } }
	SELF:oCCPushButton6:HyperLabel := HyperLabel{#PushButton6 , "Calcular os Valores" , NULL_STRING , NULL_STRING}

	SELF:oCCPushButton7 := PUSHBUTTON{SELF , ResourceID{ JFEROS_PUSHBUTTON7  , _GetInst() } }
	SELF:oCCPushButton7:HyperLabel := HyperLabel{#PushButton7 , "=" , NULL_STRING , NULL_STRING}

	SELF:oCCPushButton8 := PUSHBUTTON{SELF , ResourceID{ JFEROS_PUSHBUTTON8  , _GetInst() } }
	SELF:oCCPushButton8:HyperLabel := HyperLabel{#PushButton8 , "=" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NRNOTA1 := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_NRNOTA1  , _GetInst() } }
	SELF:oDCSC_NRNOTA1:HyperLabel := HyperLabel{#SC_NRNOTA1 , "Revisao" , NULL_STRING , NULL_STRING}

	SELF:oCCPushButton9 := PUSHBUTTON{SELF , ResourceID{ JFEROS_PUSHBUTTON9  , _GetInst() } }
	SELF:oCCPushButton9:HyperLabel := HyperLabel{#PushButton9 , "Duplicar" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAOS1 := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATAOS1  , _GetInst() } }
	SELF:oDCSC_DATAOS1:HyperLabel := HyperLabel{#SC_DATAOS1 , "PPAP Desenv" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAOS2 := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATAOS2  , _GetInst() } }
	SELF:oDCSC_DATAOS2:HyperLabel := HyperLabel{#SC_DATAOS2 , "PPAP Real" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAOS3 := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATAOS3  , _GetInst() } }
	SELF:oDCSC_DATAOS3:HyperLabel := HyperLabel{#SC_DATAOS3 , "GP11" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAOS4 := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATAOS4  , _GetInst() } }
	SELF:oDCSC_DATAOS4:HyperLabel := HyperLabel{#SC_DATAOS4 , "GP11 Prev" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PRECO1 := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_PRECO1  , _GetInst() } }
	SELF:oDCSC_PRECO1:HyperLabel := HyperLabel{#SC_PRECO1 , "Adiantamento" , NULL_STRING , NULL_STRING}

	SELF:oCCPushButton10 := PUSHBUTTON{SELF , ResourceID{ JFEROS_PUSHBUTTON10  , _GetInst() } }
	SELF:oCCPushButton10:HyperLabel := HyperLabel{#PushButton10 , "Revisao" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdtipo2 := PUSHBUTTON{SELF , ResourceID{ JFEROS_CMDTIPO2  , _GetInst() } }
	SELF:oCCcmdtipo2:HyperLabel := HyperLabel{#cmdtipo2 , "Ferramenta/Modificado" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPO := SINGLELINEEDIT{SELF , ResourceID{ JFEROS_TIPO  , _GetInst() } }
	SELF:oDCTIPO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCTIPO:Font( oFont )
	SELF:oDCTIPO:HyperLabel := HyperLabel{#TIPO , "Consumo:" , NULL_STRING , "FEROS_CONSUMO"}

	SELF:oDCSC_CONSUMO1 := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_CONSUMO1  , _GetInst() } }
	SELF:oDCSC_CONSUMO1:HyperLabel := HyperLabel{#SC_CONSUMO1 , "Tipo:" , NULL_STRING , NULL_STRING}

	SELF:oDCNFPGVCTO := DateSle{SELF , ResourceID{ JFEROS_NFPGVCTO  , _GetInst() } }
	SELF:oDCNFPGVCTO:FieldSpec := DATE_FIELD{}
	SELF:oDCNFPGVCTO:HyperLabel := HyperLabel{#NFPGVCTO , "Datanf:" , NULL_STRING , "FEROS_DATANF"}

	SELF:oDCSC_DATANF1 := FIXEDTEXT{SELF , ResourceID{ JFEROS_SC_DATANF1  , _GetInst() } }
	SELF:oDCSC_DATANF1:HyperLabel := HyperLabel{#SC_DATANF1 , "Vcto" , NULL_STRING , NULL_STRING}

	SELF:Caption := "Controle OS Ferramenta"
	SELF:Menu := STANDARDSHELLMENU{}
	SELF:HyperLabel := HyperLabel{#jferos , "Controle OS Ferramenta" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBFEROS := DataColumn{PADRAO_NUM_08{}}
	SELF:oDBFEROS:Width := 7
	SELF:oDBFEROS:HyperLabel := SELF:oDCFEROS:HyperLabel
	SELF:oDBFEROS:Caption := "Feros:"
	SELF:Browser:AddColumn(SELF:oDBFEROS)

	SELF:oDBCLIENTE := DataColumn{PADRAO_NUM_08{}}
	SELF:oDBCLIENTE:Width := 9
	SELF:oDBCLIENTE:HyperLabel := SELF:oDCCLIENTE:HyperLabel
	SELF:oDBCLIENTE:Caption := "Cliente:"
	SELF:Browser:AddColumn(SELF:oDBCLIENTE)

	SELF:oDBCOGCLI := DataColumn{PADRAO_CHAR_12{}}
	SELF:oDBCOGCLI:Width := 16
	SELF:oDBCOGCLI:HyperLabel := SELF:oDCCOGCLI:HyperLabel
	SELF:oDBCOGCLI:Caption := "Cogcli:"
	SELF:Browser:AddColumn(SELF:oDBCOGCLI)

	SELF:oDBFERRAM := DataColumn{PADRAO_CHAR_24{}}
	SELF:oDBFERRAM:Width := 18
	SELF:oDBFERRAM:HyperLabel := SELF:oDCFERRAM:HyperLabel
	SELF:oDBFERRAM:Caption := "Ferram:"
	SELF:Browser:AddColumn(SELF:oDBFERRAM)

	SELF:oDBDATAPRZ := DataColumn{date_field{}}
	SELF:oDBDATAPRZ:Width := 13
	SELF:oDBDATAPRZ:HyperLabel := SELF:oDCDATAPRZ:HyperLabel
	SELF:oDBDATAPRZ:Caption := "Dataprz:"
	SELF:Browser:AddColumn(SELF:oDBDATAPRZ)

	SELF:oDBNRNOTA := DataColumn{PADRAO_NUM_08{}}
	SELF:oDBNRNOTA:Width := 16
	SELF:oDBNRNOTA:HyperLabel := SELF:oDCNRNOTA:HyperLabel
	SELF:oDBNRNOTA:Caption := "Nrnota:"
	SELF:Browser:AddColumn(SELF:oDBNRNOTA)

	SELF:oDBPEDIDOCLI := DataColumn{PADRAO_CHAR_20{}}
	SELF:oDBPEDIDOCLI:Width := 11
	SELF:oDBPEDIDOCLI:HyperLabel := SELF:oDCPEDIDOCLI:HyperLabel
	SELF:oDBPEDIDOCLI:Caption := "Pedidocli:"
	SELF:Browser:AddColumn(SELF:oDBPEDIDOCLI)

	SELF:ViewAs(#FormView)


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS IPI
RETURN SELF:FieldGet( #IPI )

ASSIGN IPI( uValue )
SELF:FieldPut( #IPI , uValue )

ACCESS NFPGVCTO
RETURN SELF:FieldGet( #NFPGVCTO )

ASSIGN NFPGVCTO( uValue )
SELF:FieldPut( #NFPGVCTO , uValue )

ACCESS NOME
RETURN SELF:FieldGet( #NOME )

ASSIGN NOME( uValue )
SELF:FieldPut( #NOME , uValue )

ACCESS NRNOTA
RETURN SELF:FieldGet( #NRNOTA )

ASSIGN NRNOTA( uValue )
SELF:FieldPut( #NRNOTA , uValue )

ACCESS OBS
RETURN SELF:FieldGet( #OBS )

ASSIGN OBS( uValue )
SELF:FieldPut( #OBS , uValue )

ACCESS OBS2
RETURN SELF:FieldGet( #OBS2 )

ASSIGN OBS2( uValue )
SELF:FieldPut( #OBS2 , uValue )

ACCESS PEDIDOCLI
RETURN SELF:FieldGet( #PEDIDOCLI )

ASSIGN PEDIDOCLI( uValue )
SELF:FieldPut( #PEDIDOCLI , uValue )

ACCESS PPAPDATA
RETURN SELF:FieldGet( #PPAPDATA )

ASSIGN PPAPDATA( uValue )
SELF:FieldPut( #PPAPDATA , uValue )

ACCESS PPAPPREV
RETURN SELF:FieldGet( #PPAPPREV )

ASSIGN PPAPPREV( uValue )
SELF:FieldPut( #PPAPPREV , uValue )

ACCESS PRECO
RETURN SELF:FieldGet( #PRECO )

ASSIGN PRECO( uValue )
SELF:FieldPut( #PRECO , uValue )

ACCESS QTDE
RETURN SELF:FieldGet( #QTDE )

ASSIGN QTDE( uValue )
SELF:FieldPut( #QTDE , uValue )

ACCESS revisao
RETURN SELF:FieldGet( #revisao )

ASSIGN revisao( uValue )
SELF:FieldPut( #revisao , uValue )

ACCESS SOMANF
RETURN SELF:FieldGet( #SOMANF )

ASSIGN SOMANF( uValue )
SELF:FieldPut( #SOMANF , uValue )

ACCESS TIPO
RETURN SELF:FieldGet( #TIPO )

ASSIGN TIPO( uValue )
SELF:FieldPut( #TIPO , uValue )

ACCESS VALORICM
RETURN SELF:FieldGet( #VALORICM )

ASSIGN VALORICM( uValue )
SELF:FieldPut( #VALORICM , uValue )

ACCESS VALORIPI
RETURN SELF:FieldGet( #VALORIPI )

ASSIGN VALORIPI( uValue )
SELF:FieldPut( #VALORIPI , uValue )

ACCESS VALORMER
RETURN SELF:FieldGet( #VALORMER )

ASSIGN VALORMER( uValue )
SELF:FieldPut( #VALORMER , uValue )

ACCESS VALORTOT
RETURN SELF:FieldGet( #VALORTOT )

ASSIGN VALORTOT( uValue )
SELF:FieldPut( #VALORTOT , uValue )

END CLASS
STATIC DEFINE JFEROS_BTNPEGMA01 := 163
