GLOBAL cREQUEROP AS STRING

FUNC TRANSFER(nVIA)
LOCAL oSERVER,oSERVE2,oSERVE3 AS USEREDE
LOCAL dSERVER,dSERVE2,dSERVE3 AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nOV,nOVNEW AS DWORD
LOCAL cCAMPO AS STRING
LOCAL nFIELD,J AS WORD

aDAD:={zCURINI,"VPORC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU .F.
ENDIF
aDAD:={zCURINI,"VMS03.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU .F.
ENDIF
aDAD:={zCURINI,"VMS06.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
   RETU .F.
ENDIF
aDAD:={zCURINI,"VFORC.DBF",zCURDIR}
dSERVER:=USEREDE{aDAD}
IF dSERVER:nERRO#0
	oSERVER:Close() //Origem
	oSERVE2:CLOSE()
	oSERVE3:CLOSE()
   RETU .F.
ENDIF
aDAD:={zCURINI,"VFMS03.DBF",zCURDIR}
dSERVE2:=USEREDE{aDAD}
IF dSERVE2:nERRO#0
	oSERVER:Close() //Fecha Origem
	oSERVE2:CLOSE()
	oSERVE3:CLOSE()	
	dSERVER:Close() //Fecha Destino
   RETU .F.
ENDIF
aDAD:={zCURINI,"VFMS06.DBF",zCURDIR}
dSERVE3:=USEREDE{aDAD}
IF dSERVE3:nERRO#0
	oSERVER:Close() //Fecha Origem
	oSERVE2:CLOSE()
	oSERVE3:CLOSE()	
	dSERVER:Close() //Fecha Destino
	dSERVE2:CLOSE()
   RETU .F.
ENDIF
oSERVER:SETORDER(3) //viabilidade
oSERVER:GOTOP()
IF ! oSERVER:sEEK(nVIA)
	alert("Viabilidade Não Cadastrado","Erro Item")
	oSERVER:Close() //Fecha Origem
	oSERVE2:CLOSE()
	oSERVE3:CLOSE()	
	dSERVER:Close() //Fecha Destino
	dSERVE2:CLOSE()
	dSERVE3:CLOSE()	
   RETU .F.	
ENDIF	

nOV:=oSERVER:FIELDGET("OV")
nOVNEW:=nOV
dSERVER:GoBottom()
nOVNEW:=dSERVER:FIELDGET("OV")
nOVNEW:=nOVNEW+1
nFIELD:=dSERVER:FCOUNT
dSERVER:Append()
FOR J:=1 TO nFIELD
	cCAMPO:=dSERVER:FieldName(J)
    dSERVER:FIELDPUT(cCAMPO,oSERVER:FIELDGET(cCAMPO))
NEXT J
dSERVER:FIELDPUT("OV",nOVNEW)
dSERVER:FIELDPUT("OVORI",nOV)
oSERVER:Delete()
oSERVER:CLOSE()
dSERVER:CLOSE()

nFIELD:=dSERVE2:FCOUNT
oSERVE2:SETORDER(1) //OV
oSERVE2:GOTOP()
oSERVE2:SEEK(nOV)
WHILE oSERVE2:FIELDGET("OV")=nOV .AND. ! oSERVE2:EoF
   dSERVE2:Append()
   FOR J:=1 TO nFIELD
       cCAMPO:=dSERVE2:FieldName(J)
       dSERVE2:FIELDPUT(cCAMPO,oSERVE2:FIELDGET(cCAMPO))
   NEXT J
   dSERVE2:FIELDPUT("OV",nOVNEW)
//   dSERVE2:FIELDPUT("OVORI",nOV)
   oSERVE2:Delete()
   oSERVE2:SKIP()
ENDDO	
oSERVE2:CLOSE()
dSERVE2:CLOSE()

nFIELD:=dSERVE3:FCOUNT
oSERVE3:SETORDER(1) //OV
oSERVE3:GOTOP()
oSERVE3:SEEK(nOV)
WHILE oSERVE3:FIELDGET("OV")=nOV .AND. ! oSERVE3:EoF
   dSERVE3:Append()
   FOR J:=1 TO nFIELD
       cCAMPO:=dSERVE3:FieldName(J)
       dSERVE3:FIELDPUT(cCAMPO,oSERVE3:FIELDGET(cCAMPO))
   NEXT J
   dSERVE3:FIELDPUT("OV",nOVNEW)
//   dSERVE3:FIELDPUT("OVORI",nOV)
   oSERVE3:Delete()
   oSERVE3:SKIP()
ENDDO	
oSERVE3:CLOSE()
dSERVE3:CLOSE()
RETU .T.


