CLASS XJCPP INHERIT ZJCPP

METHOD APPEND() 
SUPER:append()
GRAVALOG(SELF:SERVER:NUMERO,"INC","MC02")	
RETURN   .T.

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MC","COMP")	

METHOD DELETE() 
GRAVALOG(SELF:SERVER:NUMERO,"DEL","MC02")		
SUPER:DELETE()
RETURN  .T.

CONSTRUCTOR(oOWNER) 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE	
IF ! entramenu("VIA",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MC02.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	




END CLASS
CLASS XJCPV INHERIT ZJCPP	

METHOD APPEND() 
SUPER:append()
GRAVALOG(SELF:SERVER:NUMERO,"INC","MC01")	
RETURN  .T.

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MC","VEND")	


METHOD DELETE() 
GRAVALOG(SELF:SERVER:NUMERO,"DEL","MC01")		
SUPER:DELETE()
RETURN  .T.

CONSTRUCTOR(oOWNER) 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE	
IF ! entramenu("VIA",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MC01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS ZJCPP  INHERIT JCPP

METHOD buscaov( ) 
	SELF:KEYFIND()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

CONSTRUCTOR(oOWNER) 
SUPER(oOWNER)

METHOD porov( ) 
	SELF:KEYFIND()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	   FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
