#region DEFINES
STATIC DEFINE JNP_ANO := 127
STATIC DEFINE JNP_BUSCAOV := 140
STATIC DEFINE JNP_CLIENTE := 115
STATIC DEFINE JNP_CLINOME := 116
STATIC DEFINE JNP_CODIGO := 113
STATIC DEFINE JNP_COMPNOME := 122
STATIC DEFINE JNP_COMPRADOR := 135
STATIC DEFINE JNP_DESANUAL := 123
STATIC DEFINE JNP_ESCCOD := 130
STATIC DEFINE JNP_ESCFOR := 129
STATIC DEFINE JNP_ESCMC02 := 134
STATIC DEFINE JNP_FOTO := 138
STATIC DEFINE JNP_NOME := 114
STATIC DEFINE JNP_NP := 112
STATIC DEFINE JNP_OS := 124
STATIC DEFINE JNP_PEGMA01 := 132 
STATIC DEFINE JNP_PEGMC02 := 133
STATIC DEFINE JNP_PEGMS01 := 131 
STATIC DEFINE JNP_PENDENTE := 128
STATIC DEFINE JNP_POROV := 139
STATIC DEFINE JNP_PRAZO := 136
STATIC DEFINE JNP_PRCICM := 119
STATIC DEFINE JNP_PRSICM := 118
STATIC DEFINE JNP_QTDMES := 121
STATIC DEFINE JNP_SC_ANO := 126
STATIC DEFINE JNP_SC_CLIENTE := 103
STATIC DEFINE JNP_SC_CODIGO := 101
STATIC DEFINE JNP_SC_COMPNOME := 109
STATIC DEFINE JNP_SC_DESANUAL := 110
STATIC DEFINE JNP_SC_DESTINO2 := 137
STATIC DEFINE JNP_SC_NOME := 102
STATIC DEFINE JNP_SC_NP := 100
STATIC DEFINE JNP_SC_OS := 111
STATIC DEFINE JNP_SC_PRAZO := 107
STATIC DEFINE JNP_SC_PRSICM := 105
STATIC DEFINE JNP_SC_PRSICM1 := 125
STATIC DEFINE JNP_SC_QTDMES := 108
STATIC DEFINE JNP_SC_VEICULO := 104
STATIC DEFINE JNP_SC_VLFER := 106
STATIC DEFINE JNP_VEICULO := 117
STATIC DEFINE JNP_VLFER := 120
#endregion

PARTIAL CLASS JNP INHERIT MYDataWindow
PROTECT oDBNP AS DataColumn
PROTECT oDBCODIGO AS DataColumn
PROTECT oDBNOME AS DataColumn
PROTECT oDBCLIENTE AS DataColumn
PROTECT oDBCLINOME AS DataColumn
PROTECT oDBVEICULO AS DataColumn
PROTECT oDBPRSICM AS DataColumn
PROTECT oDBPRCICM AS DataColumn
PROTECT oDBVLFER AS DataColumn
PROTECT oDBQTDMES AS DataColumn
PROTECT oDBOS AS DataColumn
PROTECT oDCSC_NP AS FIXEDTEXT
PROTECT oDCSC_CODIGO AS FIXEDTEXT
PROTECT oDCSC_NOME AS FIXEDTEXT
PROTECT oDCSC_CLIENTE AS FIXEDTEXT
PROTECT oDCSC_VEICULO AS FIXEDTEXT
PROTECT oDCSC_PRSICM AS FIXEDTEXT
PROTECT oDCSC_VLFER AS FIXEDTEXT
PROTECT oDCSC_PRAZO AS FIXEDTEXT
PROTECT oDCSC_QTDMES AS FIXEDTEXT
PROTECT oDCSC_COMPNOME AS FIXEDTEXT
PROTECT oDCSC_DESANUAL AS FIXEDTEXT
PROTECT oDCSC_OS AS FIXEDTEXT
PROTECT oDCNP AS SINGLELINEEDIT
PROTECT oDCCODIGO AS SINGLELINEEDIT
PROTECT oDCNOME AS SINGLELINEEDIT
PROTECT oDCCLIENTE AS SINGLELINEEDIT
PROTECT oDCCLINOME AS SINGLELINEEDIT
PROTECT oDCVEICULO AS SINGLELINEEDIT
PROTECT oDCPRSICM AS SINGLELINEEDIT
PROTECT oDCPRCICM AS SINGLELINEEDIT
PROTECT oDCVLFER AS SINGLELINEEDIT
PROTECT oDCQTDMES AS SINGLELINEEDIT
PROTECT oDCCOMPNOME AS SINGLELINEEDIT
PROTECT oDCDESANUAL AS SINGLELINEEDIT
PROTECT oDCOS AS SINGLELINEEDIT
PROTECT oDCSC_PRSICM1 AS FIXEDTEXT
PROTECT oDCSC_ANO AS FIXEDTEXT
PROTECT oDCANO AS SINGLELINEEDIT
PROTECT oDCPENDENTE AS CHECKBOX
PROTECT oCCescfor AS PUSHBUTTON
PROTECT oCCESCCOD AS PUSHBUTTON
PROTECT oCCbtnPEGMS01 AS PUSHBUTTON
PROTECT oCCbtnPEGMA01 AS PUSHBUTTON
PROTECT oCCPEGMC02 AS PUSHBUTTON
PROTECT oCCESCMC02 AS PUSHBUTTON
PROTECT oDCCOMPRADOR AS SINGLELINEEDIT
PROTECT oDCPRAZO AS DateSle
PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
PROTECT oCCfoto AS PUSHBUTTON
PROTECT oCCporov AS PUSHBUTTON
PROTECT oCCbuscaov AS PUSHBUTTON

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS ANO
RETURN SELF:FieldGet( #ANO )

ASSIGN ANO( uValue )
SELF:FieldPut( #ANO , uValue )

ACCESS CLIENTE
RETURN SELF:FieldGet( #CLIENTE )

ASSIGN CLIENTE( uValue )
SELF:FieldPut( #CLIENTE , uValue )

ACCESS CLINOME
RETURN SELF:FieldGet( #CLINOME )

ASSIGN CLINOME( uValue )
SELF:FieldPut( #CLINOME , uValue )

ACCESS CODIGO
RETURN SELF:FieldGet( #CODIGO )

ASSIGN CODIGO( uValue )
SELF:FieldPut( #CODIGO , uValue )

ACCESS COMPNOME
RETURN SELF:FieldGet( #COMPNOME )

ASSIGN COMPNOME( uValue )
SELF:FieldPut( #COMPNOME , uValue )

ACCESS COMPRADOR
RETURN SELF:FieldGet( #COMPRADOR )

ASSIGN COMPRADOR( uValue )
SELF:FieldPut( #COMPRADOR , uValue )

ACCESS DESANUAL
RETURN SELF:FieldGet( #DESANUAL )

ASSIGN DESANUAL( uValue )
SELF:FieldPut( #DESANUAL , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JNP" , _GetInst()},iCtlID)

	SELF:oDCSC_NP := FIXEDTEXT{SELF , ResourceID{ JNP_SC_NP  , _GetInst() } }
	SELF:oDCSC_NP:HyperLabel := HyperLabel{#SC_NP , "Np:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CODIGO := FIXEDTEXT{SELF , ResourceID{ JNP_SC_CODIGO  , _GetInst() } }
	SELF:oDCSC_CODIGO:HyperLabel := HyperLabel{#SC_CODIGO , "Codigo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME := FIXEDTEXT{SELF , ResourceID{ JNP_SC_NOME  , _GetInst() } }
	SELF:oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME , "Nome:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CLIENTE := FIXEDTEXT{SELF , ResourceID{ JNP_SC_CLIENTE  , _GetInst() } }
	SELF:oDCSC_CLIENTE:HyperLabel := HyperLabel{#SC_CLIENTE , "Cliente:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_VEICULO := FIXEDTEXT{SELF , ResourceID{ JNP_SC_VEICULO  , _GetInst() } }
	SELF:oDCSC_VEICULO:HyperLabel := HyperLabel{#SC_VEICULO , "Veiculo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PRSICM := FIXEDTEXT{SELF , ResourceID{ JNP_SC_PRSICM  , _GetInst() } }
	SELF:oDCSC_PRSICM:HyperLabel := HyperLabel{#SC_PRSICM , "Preço com ICM" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_VLFER := FIXEDTEXT{SELF , ResourceID{ JNP_SC_VLFER  , _GetInst() } }
	SELF:oDCSC_VLFER:HyperLabel := HyperLabel{#SC_VLFER , "Ferramenta" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PRAZO := FIXEDTEXT{SELF , ResourceID{ JNP_SC_PRAZO  , _GetInst() } }
	SELF:oDCSC_PRAZO:HyperLabel := HyperLabel{#SC_PRAZO , "Prazo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTDMES := FIXEDTEXT{SELF , ResourceID{ JNP_SC_QTDMES  , _GetInst() } }
	SELF:oDCSC_QTDMES:HyperLabel := HyperLabel{#SC_QTDMES , "Qtd Mensal" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_COMPNOME := FIXEDTEXT{SELF , ResourceID{ JNP_SC_COMPNOME  , _GetInst() } }
	SELF:oDCSC_COMPNOME:HyperLabel := HyperLabel{#SC_COMPNOME , "Comprador" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESANUAL := FIXEDTEXT{SELF , ResourceID{ JNP_SC_DESANUAL  , _GetInst() } }
	SELF:oDCSC_DESANUAL:HyperLabel := HyperLabel{#SC_DESANUAL , "Desconto Anual" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_OS := FIXEDTEXT{SELF , ResourceID{ JNP_SC_OS  , _GetInst() } }
	SELF:oDCSC_OS:HyperLabel := HyperLabel{#SC_OS , "Os:" , NULL_STRING , NULL_STRING}

	SELF:oDCNP := SINGLELINEEDIT{SELF , ResourceID{ JNP_NP  , _GetInst() } }
	SELF:oDCNP:FieldSpec := padrao_num_08{}
	SELF:oDCNP:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCNP:Font( oFont )
	SELF:oDCNP:HyperLabel := HyperLabel{#NP , "Np:" , NULL_STRING , "Np_NP"}

	SELF:oDCCODIGO := SINGLELINEEDIT{SELF , ResourceID{ JNP_CODIGO  , _GetInst() } }
	SELF:oDCCODIGO:FieldSpec := padrao_char_24{}
	SELF:oDCCODIGO:HyperLabel := HyperLabel{#CODIGO , "Codigo:" , NULL_STRING , "Np_CODIGO"}

	SELF:oDCNOME := SINGLELINEEDIT{SELF , ResourceID{ JNP_NOME  , _GetInst() } }
	SELF:oDCNOME:FieldSpec := padrao_char_40{}
	SELF:oDCNOME:HyperLabel := HyperLabel{#NOME , "Nome:" , NULL_STRING , "Np_NOME"}

	SELF:oDCCLIENTE := SINGLELINEEDIT{SELF , ResourceID{ JNP_CLIENTE  , _GetInst() } }
	SELF:oDCCLIENTE:FieldSpec := padrao_num_08{}
	SELF:oDCCLIENTE:HyperLabel := HyperLabel{#CLIENTE , "Cliente:" , NULL_STRING , "Np_CLIENTE"}

	SELF:oDCCLINOME := SINGLELINEEDIT{SELF , ResourceID{ JNP_CLINOME  , _GetInst() } }
	SELF:oDCCLINOME:FieldSpec := padrao_char_40{}
	SELF:oDCCLINOME:HyperLabel := HyperLabel{#CLINOME , "Clinome:" , NULL_STRING , "Np_CLINOME"}

	SELF:oDCVEICULO := SINGLELINEEDIT{SELF , ResourceID{ JNP_VEICULO  , _GetInst() } }
	SELF:oDCVEICULO:FieldSpec := padrao_char_20{}
	SELF:oDCVEICULO:HyperLabel := HyperLabel{#VEICULO , "Veiculo:" , NULL_STRING , "Np_VEICULO"}

	SELF:oDCPRSICM := SINGLELINEEDIT{SELF , ResourceID{ JNP_PRSICM  , _GetInst() } }
	SELF:oDCPRSICM:FieldSpec := padrao_num_10_4{}
	SELF:oDCPRSICM:HyperLabel := HyperLabel{#PRSICM , "Prsicm:" , NULL_STRING , "Np_PRSICM"}

	SELF:oDCPRCICM := SINGLELINEEDIT{SELF , ResourceID{ JNP_PRCICM  , _GetInst() } }
	SELF:oDCPRCICM:FieldSpec := padrao_num_10_4{}
	SELF:oDCPRCICM:HyperLabel := HyperLabel{#PRCICM , "Prcicm:" , NULL_STRING , "Np_PRCICM"}

	SELF:oDCVLFER := SINGLELINEEDIT{SELF , ResourceID{ JNP_VLFER  , _GetInst() } }
	SELF:oDCVLFER:FieldSpec := padrao_num_12_2{}
	SELF:oDCVLFER:HyperLabel := HyperLabel{#VLFER , "Vlfer:" , NULL_STRING , "Np_VLFER"}

	SELF:oDCQTDMES := SINGLELINEEDIT{SELF , ResourceID{ JNP_QTDMES  , _GetInst() } }
	SELF:oDCQTDMES:FieldSpec := padrao_num_08{}
	SELF:oDCQTDMES:HyperLabel := HyperLabel{#QTDMES , "Qtdmes:" , NULL_STRING , "Np_QTDMES"}

	SELF:oDCCOMPNOME := SINGLELINEEDIT{SELF , ResourceID{ JNP_COMPNOME  , _GetInst() } }
	SELF:oDCCOMPNOME:FieldSpec := padrao_char_40{}
	SELF:oDCCOMPNOME:HyperLabel := HyperLabel{#COMPNOME , "Compnome:" , NULL_STRING , "Np_COMPNOME"}

	SELF:oDCDESANUAL := SINGLELINEEDIT{SELF , ResourceID{ JNP_DESANUAL  , _GetInst() } }
	SELF:oDCDESANUAL:FieldSpec := padrao_num_01{}
	SELF:oDCDESANUAL:HyperLabel := HyperLabel{#DESANUAL , "Desanual:" , NULL_STRING , "Np_DESANUAL"}

	SELF:oDCOS := SINGLELINEEDIT{SELF , ResourceID{ JNP_OS  , _GetInst() } }
	SELF:oDCOS:FieldSpec := padrao_char_20{}
	SELF:oDCOS:HyperLabel := HyperLabel{#OS , "Os:" , NULL_STRING , "Np_OS"}

	SELF:oDCSC_PRSICM1 := FIXEDTEXT{SELF , ResourceID{ JNP_SC_PRSICM1  , _GetInst() } }
	SELF:oDCSC_PRSICM1:HyperLabel := HyperLabel{#SC_PRSICM1 , "Preço Sem Icm" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ANO := FIXEDTEXT{SELF , ResourceID{ JNP_SC_ANO  , _GetInst() } }
	SELF:oDCSC_ANO:HyperLabel := HyperLabel{#SC_ANO , "Ano:" , NULL_STRING , NULL_STRING}

	SELF:oDCANO := SINGLELINEEDIT{SELF , ResourceID{ JNP_ANO  , _GetInst() } }
	SELF:oDCANO:FieldSpec := padrao_num_04{}
	SELF:oDCANO:HyperLabel := HyperLabel{#ANO , "Ano:" , NULL_STRING , "Np_ANO"}

	SELF:oDCPENDENTE := CHECKBOX{SELF , ResourceID{ JNP_PENDENTE  , _GetInst() } }
	SELF:oDCPENDENTE:FieldSpec := logic_field{}
	SELF:oDCPENDENTE:HyperLabel := HyperLabel{#PENDENTE , "Pendente" , NULL_STRING , "Np_PENDENTE"}

	SELF:oCCescfor := PUSHBUTTON{SELF , ResourceID{ JNP_ESCFOR  , _GetInst() } }
	SELF:oCCescfor:HyperLabel := HyperLabel{#escfor , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCESCCOD := PUSHBUTTON{SELF , ResourceID{ JNP_ESCCOD  , _GetInst() } }
	SELF:oCCESCCOD:HyperLabel := HyperLabel{#ESCCOD , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCbtnPEGMS01 := PUSHBUTTON{SELF , ResourceID{ JNP_BTNPEGMS01  , _GetInst() } }
	SELF:oCCbtnPEGMS01:HyperLabel := HyperLabel{#btnPEGMS01 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnPEGMA01 := PUSHBUTTON{SELF , ResourceID{ JNP_BTNPEGMA01  , _GetInst() } }
	SELF:oCCbtnPEGMA01:HyperLabel := HyperLabel{#btnPEGMA01 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGMC02 := PUSHBUTTON{SELF , ResourceID{ JNP_PEGMC02  , _GetInst() } }
	SELF:oCCPEGMC02:HyperLabel := HyperLabel{#PEGMC02 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCESCMC02 := PUSHBUTTON{SELF , ResourceID{ JNP_ESCMC02  , _GetInst() } }
	SELF:oCCESCMC02:HyperLabel := HyperLabel{#ESCMC02 , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCCOMPRADOR := SINGLELINEEDIT{SELF , ResourceID{ JNP_COMPRADOR  , _GetInst() } }
	SELF:oDCCOMPRADOR:FieldSpec := padrao_char_05{}
	SELF:oDCCOMPRADOR:HyperLabel := HyperLabel{#COMPRADOR , "Cliente:" , NULL_STRING , "Np_CLIENTE"}

	SELF:oDCPRAZO := DateSle{SELF , ResourceID{ JNP_PRAZO  , _GetInst() } }
	SELF:oDCPRAZO:FieldSpec := date_field{}
	SELF:oDCPRAZO:HyperLabel := HyperLabel{#PRAZO , "Qtdmes:" , NULL_STRING , "Np_QTDMES"}

	SELF:oDCSC_DESTINO2 := FIXEDTEXT{SELF , ResourceID{ JNP_SC_DESTINO2  , _GetInst() } }
	SELF:oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2 , "Foto" , NULL_STRING , NULL_STRING}

	SELF:oCCfoto := PUSHBUTTON{SELF , ResourceID{ JNP_FOTO  , _GetInst() } }
	SELF:oCCfoto:Image := ico_camera{}
	SELF:oCCfoto:HyperLabel := HyperLabel{#foto , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCporov := PUSHBUTTON{SELF , ResourceID{ JNP_POROV  , _GetInst() } }
	SELF:oCCporov:TooltipText := "Clique para ordenar por Numero"
	SELF:oCCporov:Image := ICO_AZ{}
	SELF:oCCporov:HyperLabel := HyperLabel{#porov , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCbuscaov := PUSHBUTTON{SELF , ResourceID{ JNP_BUSCAOV  , _GetInst() } }
	SELF:oCCbuscaov:TooltipText := "Clique Para Localizar Por Numero"
	SELF:oCCbuscaov:Image := ICO_FIND{}
	SELF:oCCbuscaov:HyperLabel := HyperLabel{#buscaov , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:Caption := "Novos Pedidos"
	SELF:Menu := STANDARDSHELLMENU{}
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#JNP , "Novos Pedidos" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBNP := DataColumn{padrao_num_08{}}
	SELF:oDBNP:Width := 4
	SELF:oDBNP:HyperLabel := SELF:oDCNP:HyperLabel
	SELF:oDBNP:Caption := "Np:"
	SELF:Browser:AddColumn(SELF:oDBNP)

	SELF:oDBCODIGO := DataColumn{padrao_char_24{}}
	SELF:oDBCODIGO:Width := 8
	SELF:oDBCODIGO:HyperLabel := SELF:oDCCODIGO:HyperLabel
	SELF:oDBCODIGO:Caption := "Codigo:"
	SELF:Browser:AddColumn(SELF:oDBCODIGO)

	SELF:oDBNOME := DataColumn{padrao_char_40{}}
	SELF:oDBNOME:Width := 6
	SELF:oDBNOME:HyperLabel := SELF:oDCNOME:HyperLabel
	SELF:oDBNOME:Caption := "Nome:"
	SELF:Browser:AddColumn(SELF:oDBNOME)

	SELF:oDBCLIENTE := DataColumn{padrao_num_08{}}
	SELF:oDBCLIENTE:Width := 9
	SELF:oDBCLIENTE:HyperLabel := SELF:oDCCLIENTE:HyperLabel
	SELF:oDBCLIENTE:Caption := "Cliente:"
	SELF:Browser:AddColumn(SELF:oDBCLIENTE)

	SELF:oDBCLINOME := DataColumn{padrao_char_40{}}
	SELF:oDBCLINOME:Width := 9
	SELF:oDBCLINOME:HyperLabel := SELF:oDCCLINOME:HyperLabel
	SELF:oDBCLINOME:Caption := "Clinome:"
	SELF:Browser:AddColumn(SELF:oDBCLINOME)

	SELF:oDBVEICULO := DataColumn{padrao_char_20{}}
	SELF:oDBVEICULO:Width := 9
	SELF:oDBVEICULO:HyperLabel := SELF:oDCVEICULO:HyperLabel
	SELF:oDBVEICULO:Caption := "Veiculo:"
	SELF:Browser:AddColumn(SELF:oDBVEICULO)

	SELF:oDBPRSICM := DataColumn{padrao_num_10_4{}}
	SELF:oDBPRSICM:Width := 8
	SELF:oDBPRSICM:HyperLabel := SELF:oDCPRSICM:HyperLabel
	SELF:oDBPRSICM:Caption := "Prsicm:"
	SELF:Browser:AddColumn(SELF:oDBPRSICM)

	SELF:oDBPRCICM := DataColumn{padrao_num_10_4{}}
	SELF:oDBPRCICM:Width := 8
	SELF:oDBPRCICM:HyperLabel := SELF:oDCPRCICM:HyperLabel
	SELF:oDBPRCICM:Caption := "Prcicm:"
	SELF:Browser:AddColumn(SELF:oDBPRCICM)

	SELF:oDBVLFER := DataColumn{padrao_num_12_2{}}
	SELF:oDBVLFER:Width := 7
	SELF:oDBVLFER:HyperLabel := SELF:oDCVLFER:HyperLabel
	SELF:oDBVLFER:Caption := "Vlfer:"
	SELF:Browser:AddColumn(SELF:oDBVLFER)

	SELF:oDBQTDMES := DataColumn{padrao_num_08{}}
	SELF:oDBQTDMES:Width := 8
	SELF:oDBQTDMES:HyperLabel := SELF:oDCQTDMES:HyperLabel
	SELF:oDBQTDMES:Caption := "Qtdmes:"
	SELF:Browser:AddColumn(SELF:oDBQTDMES)

	SELF:oDBOS := DataColumn{padrao_char_20{}}
	SELF:oDBOS:Width := 4
	SELF:oDBOS:HyperLabel := SELF:oDCOS:HyperLabel
	SELF:oDBOS:Caption := "Os:"
	SELF:Browser:AddColumn(SELF:oDBOS)

	SELF:ViewAs(#FormView)


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NOME
RETURN SELF:FieldGet( #NOME )

ASSIGN NOME( uValue )
SELF:FieldPut( #NOME , uValue )

ACCESS NP
RETURN SELF:FieldGet( #NP )

ASSIGN NP( uValue )
SELF:FieldPut( #NP , uValue )

ACCESS OS
RETURN SELF:FieldGet( #OS )

ASSIGN OS( uValue )
SELF:FieldPut( #OS , uValue )

ACCESS PENDENTE
RETURN SELF:FieldGet( #PENDENTE )

ASSIGN PENDENTE( uValue )
SELF:FieldPut( #PENDENTE , uValue )

ACCESS PRAZO
RETURN SELF:FieldGet( #PRAZO )

ASSIGN PRAZO( uValue )
SELF:FieldPut( #PRAZO , uValue )

ACCESS PRCICM
RETURN SELF:FieldGet( #PRCICM )

ASSIGN PRCICM( uValue )
SELF:FieldPut( #PRCICM , uValue )

ACCESS PRSICM
RETURN SELF:FieldGet( #PRSICM )

ASSIGN PRSICM( uValue )
SELF:FieldPut( #PRSICM , uValue )

ACCESS QTDMES
RETURN SELF:FieldGet( #QTDMES )

ASSIGN QTDMES( uValue )
SELF:FieldPut( #QTDMES , uValue )

ACCESS VEICULO
RETURN SELF:FieldGet( #VEICULO )

ASSIGN VEICULO( uValue )
SELF:FieldPut( #VEICULO , uValue )

ACCESS VLFER
RETURN SELF:FieldGet( #VLFER )

ASSIGN VLFER( uValue )
SELF:FieldPut( #VLFER , uValue )

END CLASS
STATIC DEFINE JNP_BTNPEGMS01 := 131
STATIC DEFINE JNP_BTNPEGMA01 := 132
