PARTIAL CLASS JORCA
METHOD ALTERAR  
SELF:oSFJORCAI:VIEWFORM()

END CLASS
CLASS XJORCA INHERIT JORCA
	

METHOD ANTERIOR 
SELF:oSFJORCAI:Browser:SuspendUpdate()
SELF:oSFJORCAI:SkipPrevious()
IF SELF:oSFJORCAI:Server:bof
	SELF:oSFJORCAI:Skipnext()
ENDIF
SELF:oSFJORCAI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nORCA AS DWORD
LOCAL cTEM AS STRING
SELF:server:setorder(1)
SELF:server:gobottom()
nORCA:=SELF:Server:ORCA
nORCA++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("ORCA",nORCA)
cTEM:=PEGINIVAL(ZCURINI,"ORCAOBS","REFER")
SELF:SERVER:FIELDPUT("REFER",CTEM)
cTEM:=PEGINIVAL(ZCURINI,"ORCAOBS","ORC")
SELF:SERVER:FIELDPUT("ORC",CTEM)
cTEM:=PEGINIVAL(ZCURINI,"ORCAOBS","PRAZO")
SELF:SERVER:FIELDPUT("PRAZO",CTEM)
cTEM:=PEGINIVAL(ZCURINI,"ORCAOBS","CVAL")
SELF:SERVER:FIELDPUT("CVAL",CTEM)
cTEM:=PEGINIVAL(ZCURINI,"ORCAOBS","CPAG")
SELF:SERVER:FIELDPUT("CPAG",CTEM)
cTEM:=PEGINIVAL(ZCURINI,"ORCAOBS","CFER")
SELF:SERVER:FIELDPUT("CFER",CTEM)
cTEM:=PEGINIVAL(ZCURINI,"ORCAOBS","OBS01")
SELF:SERVER:FIELDPUT("OBS01",CTEM)
cTEM:=PEGINIVAL(ZCURINI,"ORCAOBS","OBS02")
SELF:SERVER:FIELDPUT("OBS02",CTEM)
SELF:SERVER:commit()
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
GRAVALOG(SELF:SERVER:ORCA,"INC","ORCA")	
RETURN .T.

METHOD buscacod( ) 
LOCAL oBUSCA AS XBUSCA
LOCAL lCONTINUA AS LOGIC
LOCAL cCODIGO,cDESC AS STRING
lCONTINUA:=.T.
oBUSCA:=XBUSCA{SELF,"Localizar Desenho","Digite o Codigo do Desenho"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU SELF
ENDIF
cCODIGO:=Upper(oBUSCA:cBUSCA)
SELF:SERVER:GOTOP()
WHILE lCONTINUA
    SELF:oSFJORCAI:server:GOTOP()	
    WHILE ! oSFJORCAI:server:EOF
       cDESC:=Upper(SELF:oSFJORCAI:SERVER:FIELDGET("DESCR"))
       IF At(cCODIGO,cDESC)>0
       	  alert("Encontrado "+cDESC)
       	  IF ! MDG("Continuar")
       	  	 lCONTINUA:=.F.
       	  ENDIF	
       ENDIF	
 	   SELF:oSFJORCAI:server:SKIP()
    ENDDO	
    SELF:SERVER:SKIP()
    IF SELF:SERVER:EOF
       lCONTINUA:=.F.
       SELF:SERVER:GOBOTTOM()
    ENDIF	
ENDDO
	

METHOD buscaov( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("V1","ORCA")	


METHOD DELETE() 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
GRAVALOG(SELF:SERVER:ORCA,"DEL","ORCA")	
SELF:oSFJORCAI:server:GOTOP()	
WHILE ! oSFJORCAI:server:EOF
 	SELF:oSFJORCAI:server:delete()
    SELF:oSFJORCAI:server:SKIP()
ENDDO	
SELF:oSFJORCAI:SERVER:SUSPENDNOTIFICATION()
SUPER:delete()
SELF:server:skipEX(-1)
SELF:oSFJORCAI:SERVER:resetnotification()
SELF:oSFJORCAI:SERVER:notify(notifyfilechange)	
//SELF:RENUM()

METHOD Duplicar() 
LOCAL nORCA AS DWORD
LOCAL nFIELD,J,K AS WORD
LOCAL aITENS,aTMP,aDADOS AS ARRAY
LOCAL cREVI AS STRING

nFIELD:=SELF:SERVER:FCOUNT
nORCA:=SELF:Server:FIELDGET("ORCA")
aDADOS:={}
FOR J:=1 TO nFIELD
    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
NEXT J
aITENS:={}
nFIELD:=SELF:oSFJORCAI:server:FCOUNT
SELF:oSFJORCAI:server:GOTOP()
WHILE ! oSFJORCAI:server:EOF
    aTMP:={}
    FOR J:=1 TO nFIELD
       AAdd(aTMP,SELF:oSFJORCAI:server:FIELDGET(J))
    NEXT J
    AAdd(aITENS,aTMP)
   SELF:oSFJORCAI:server:SKIP()
ENDDO
SELF:server:setorder(1)
SELF:server:gobottom()
nORCA:=SELF:Server:ORCA
nORCA++
SUPER:SERVER:APPEND()
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    SELF:SERVER:FIELDPUT(J,aDADOS[J])
NEXT J
SELF:SERVER:FIELDPUT("ORCA",nORCA)
IF Empty(SELF:SERVER:FIELDGET("REVI"))
   cREVI:="A"
ELSE
   cREVI:=Chr(Asc(SELF:SERVER:FIELDGET("REVI"))+1)
ENDIF	
SELF:SERVER:FIELDPUT("REVI",cREVI)
nFIELD:=SELF:oSFJORCAI:server:FCOUNT
FOR K:=1 TO ALen(aITENS)
    SELF:oSFJORCAI:server:APPEND()
    FOR J:=1 TO nFIELD
        SELF:oSFJORCAI:server:FIELDPUT(J,aITENS[K][J])
    NEXT J
    SELF:oSFJORCAI:server:FIELDPUT("ORCA",nORCA)
NEXT K
SELF:server:gotop()
SELF:server:gobottom()
RETURN .T.
          

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD EXCLUIR 
IF ! MDG("Apagar Registro") .AND. SELF:oSFJORCAI:server:LockCurrentRecord()
	RETU SELF
ENDIF	
GRAVALOG(SELF:SERVER:ORCA,"DEL","ORCAI")		
SELF:oSFJORCAI:server:delete()
SELF:oSFJORCAI:server:unlock()
SELF:oSFJORCAI:server:skip(-1)
IF SELF:oSFJORCAI:server:BOF
   SELF:oSFJORCAI:server:GOTOP()
ENDIF


METHOD EXPORTAR  
LOCAL aDAD AS ARRAY
LOCAL oVIABILI AS USEREDE	
aDAD:={zCURINI,"VIABILI.DBF",zCURDIR}
oVIABILI:=USEREDE{aDAD}
IF oVIABILI:nERRO#0
   alert("Erro Abrindo Viabili")
ENDIF	
oVIABILI:GOTOP()
IF oVIABILI:SEEK(SELF:oSFJORCAI:SERVER:FIELDGET("VIABILI"))
	IF Empty(oVIABILI:FIELDGET("VALORUNI"))
       oVIABILI:FIELDPUT("VALORUNI",SELF:oSFJORCAI:SERVER:FIELDGET("VALPEC"))
    ENDIF
	IF Empty(oVIABILI:FIELDGET("QTDEANO"))
       oVIABILI:FIELDPUT("QTDEANO",SELF:oSFJORCAI:SERVER:FIELDGET("QTDDE"))
    ENDIF
	IF Empty(oVIABILI:FIELDGET("VALORFER"))
       oVIABILI:FIELDPUT("VALORFER",SELF:oSFJORCAI:SERVER:FIELDGET("FERRA"))	
    ENDIF
	IF Empty(oVIABILI:FIELDGET("DATAEC"))
       oVIABILI:FIELDPUT("DATAEC",Today())	
    ENDIF
	IF Empty(oVIABILI:FIELDGET("DESORC"))
       oVIABILI:FIELDPUT("DESORC",SELF:oSFJORCAI:SERVER:FIELDGET("DESENHO"))	
    ENDIF
	IF Empty(oVIABILI:FIELDGET("DESORCREV"))
       oVIABILI:FIELDPUT("DESORCREV",SELF:oSFJORCAI:SERVER:FIELDGET("REV"))	
    ENDIF
	IF Empty(oVIABILI:FIELDGET("DESORCDAT"))
       oVIABILI:FIELDPUT("DESORCDAT",SELF:oSFJORCAI:SERVER:FIELDGET("DATAREV"))	
    ENDIF
ENDIF
oVIABILI:CLOSE()	

METHOD IMPORTAR  
LOCAL aDAD AS ARRAY
LOCAL oVIABILI AS USEREDE	
aDAD:={zCURINI,"VIABILI.DBF",zCURDIR}
oVIABILI:=USEREDE{aDAD}
IF oVIABILI:nERRO#0
   alert("Erro Abrindo Viabili")
ENDIF	
oVIABILI:GOTOP()
IF oVIABILI:SEEK(SELF:VIABILI)
	oVIABILI:FIELDPUT("ORCAMENTO",SELF:SERVER:FIELDGET("ORCA"))
    oVIABILI:FIELDPUT("ITEM",SELF:oSFJORCAI:SERVER:FIELDGET("ORD"))

//	SELF:oSFJORCAI:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJORCAI:SERVER:FIELDPUT("DESCR",AllTrim(oVIABILI:FIELDGET("DESENHO"))+" "+AllTrim(oVIABILI:FIELDGET("DENOMINA")))
    SELF:oSFJORCAI:SERVER:FIELDPUT("VALPEC",oVIABILI:FIELDGET("FVALORUNI")) //Pega os valores Final	
    SELF:oSFJORCAI:SERVER:FIELDPUT("FERRA",oVIABILI:FIELDGET("FVALORFER"))	
    IF Empty(SELF:oSFJORCAI:SERVER:FIELDGET("VALPEC"))                        //Senão os padroes
       SELF:oSFJORCAI:SERVER:FIELDPUT("VALPEC",oVIABILI:FIELDGET("VALORUNI"))	
    ENDIF
    IF Empty(SELF:oSFJORCAI:SERVER:FIELDGET("FERRA"))
	   SELF:oSFJORCAI:SERVER:FIELDPUT("FERRA",oVIABILI:FIELDGET("VALORFER"))	
    ENDIF	
    SELF:oSFJORCAI:SERVER:FIELDPUT("VIABILI",SELF:FIELDGET("VIABILI"))
    SELF:oSFJORCAI:SERVER:FIELDPUT("QTDDE",oVIABILI:FIELDGET("QTDEANO"))	
    SELF:oSFJORCAI:SERVER:FIELDPUT("LOTEMIN",oVIABILI:FIELDGET("LOTEMIN"))	
    SELF:oSFJORCAI:SERVER:FIELDPUT("DESENHO",oVIABILI:FIELDGET("DESORC"))	
    SELF:oSFJORCAI:SERVER:FIELDPUT("REV",oVIABILI:FIELDGET("DESORCREV"))	
    SELF:oSFJORCAI:SERVER:FIELDPUT("DATAREV",oVIABILI:FIELDGET("DESORCDAT"))	
	SELF:oSFJORCAI:SERVER:commit()
//	SELF:oSFJORCAI:SERVER:resetnotification()
//	SELF:oSFJORCAI:SERVER:notify(notifyfilechange) //Contas do Livro
	
ENDIF
oVIABILI:CLOSE()	


CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("VIA",4)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ORCA.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ORCAI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJORCAI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJORCAI,"ORCA")
SELF:oSFJORCAI:VIEWTABLE()
SELF:SHOW()



METHOD NOVO 
LOCAL nORCA AS DWORD
nORCA:=SELF:SERVER:ORCA
SELF:oSFJORCAI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJORCAI:SERVER:APPEND()
SELF:oSFJORCAI:SERVER:ORCA:=nORCA
SELF:oSFJORCAI:SERVER:UNID:="PC"
SELF:oSFJORCAI:SERVER:UNIPEC:="R$"
SELF:oSFJORCAI:SERVER:QTDDE:=0
SELF:oSFJORCAI:SERVER:FERRA:=0
SELF:oSFJORCAI:SERVER:commit()
SELF:oSFJORCAI:SERVER:resetnotification()
SELF:oSFJORCAI:SERVER:notify(notifyappend) //Contas do Livro
GRAVALOG(nORCA,"INC","ORCAI")	
SELF:RENUM()

METHOD btnPEGMA01 
LOCAL aCLI AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:CLINOME:=aCLI[2]
ENDIF


METHOD porov( ) 
SELF:KEYFIND()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	   FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJORCAI:Browser:SuspendUpdate()
SELF:oSFJORCAI:SkipNext()
IF SELF:oSFJORCAI:Server:Eof
	SELF:oSFJORCAI:SkipPrevious()
ENDIF
SELF:oSFJORCAI:Browser:RestoreUpdate()

METHOD RENUM 
LOCAL nITEM AS WORD
LOCAL aDAD AS ARRAY
LOCAL oVIABILI AS USEREDE	
aDAD:={zCURINI,"VIABILI.DBF",zCURDIR}
oVIABILI:=USEREDE{aDAD}
IF oVIABILI:nERRO#0
   alert("Erro Abrindo Viabili")
   RETURN .F.
ENDIF	
nITEM:=1
SELF:oSFJORCAI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJORCAI:server:GOTOP()
WHILE ! oSFJORCAI:server:EOF
  SELF:oSFJORCAI:server:ORD:=nITEM
  IF ! Empty(SELF:oSFJORCAI:SERVER:VIABILI)
	oVIABILI:GOTOP()
	IF oVIABILI:SEEK(SELF:oSFJORCAI:SERVER:VIABILI)
       oVIABILI:FIELDPUT("ORCAMENTO",SELF:SERVER:ORCA)
       oVIABILI:FIELDPUT("ITEM",SELF:oSFJORCAI:SERVER:ORD)		
  	ENDIF
  ENDIF	
  SELF:oSFJORCAI:server:SKIP()
  nITEM++
ENDDO
SELF:oSFJORCAI:server:GOTOP()
SELF:oSFJORCAI:SERVER:resetnotification()
SELF:oSFJORCAI:SERVER:notify(notifyfilechange)
oVIABILI:CLOSE()	






METHOD TABULAR  
SELF:oSFJORCAI:VIEWTABLE()



METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJORCAI:SERVER:COMMIT()



END CLASS
