#region DEFINES
STATIC DEFINE JANVIA_BUSCAOV := 135
STATIC DEFINE JANVIA_CHKCLIPRO := 149
STATIC DEFINE JANVIA_CLIENTE := 102
STATIC DEFINE JANVIA_CLINOME := 103
STATIC DEFINE JANVIA_CMDHOJE := 126
STATIC DEFINE JANVIA_CODIGOINT := 150
STATIC DEFINE JANVIA_COMCOMP := 110
STATIC DEFINE JANVIA_COMPRADOR := 105
STATIC DEFINE JANVIA_CONDICIONAL := 129
STATIC DEFINE JANVIA_DATAEC := 100
STATIC DEFINE JANVIA_DATAS := 145
STATIC DEFINE JANVIA_DATAV := 146
STATIC DEFINE JANVIA_DENOMINA := 109
STATIC DEFINE JANVIA_DESENHO := 106
STATIC DEFINE JANVIA_DISPE := 162 
STATIC DEFINE JANVIA_DUPLICAR := 123
STATIC DEFINE JANVIA_EDITAR := 130
STATIC DEFINE JANVIA_EDITAR1 := 154
STATIC DEFINE JANVIA_EMAIL := 140
STATIC DEFINE JANVIA_EMAILVCT := 141
STATIC DEFINE JANVIA_ESCCOD := 142
STATIC DEFINE JANVIA_ESCFOR := 134
STATIC DEFINE JANVIA_FECCODIGO := 158
STATIC DEFINE JANVIA_FESP := 138 
STATIC DEFINE JANVIA_FIXEDTEXT22 := 128
STATIC DEFINE JANVIA_FOTO := 148
STATIC DEFINE JANVIA_FT13 := 120
STATIC DEFINE JANVIA_FT16 := 121
STATIC DEFINE JANVIA_GPS := 108
STATIC DEFINE JANVIA_JVIAREV := 152
STATIC DEFINE JANVIA_JVIII := 127
STATIC DEFINE JANVIA_MATM := 144 
STATIC DEFINE JANVIA_NESI := 168 
STATIC DEFINE JANVIA_NOVAREV := 155
STATIC DEFINE JANVIA_NOVAREV1 := 156
STATIC DEFINE JANVIA_OBSE02 := 166 
STATIC DEFINE JANVIA_OBSF01 := 142 
STATIC DEFINE JANVIA_OBSI03 := 174 
STATIC DEFINE JANVIA_OBSM02 := 152 
STATIC DEFINE JANVIA_OBSO01 := 178 
STATIC DEFINE JANVIA_OBST01 := 160 
STATIC DEFINE JANVIA_OV := 114
STATIC DEFINE JANVIA_OVORI := 122
STATIC DEFINE JANVIA_PAGE1_CMDHOJE1 := 100 
STATIC DEFINE JANVIA_PAGE1_COPIA := 107 
STATIC DEFINE JANVIA_PAGE1_DESMARCAR := 110 
STATIC DEFINE JANVIA_PAGE1_FDATA := 101 
STATIC DEFINE JANVIA_PAGE1_FVALORFER := 108 
STATIC DEFINE JANVIA_PAGE1_FVALORUNI := 105 
STATIC DEFINE JANVIA_PAGE1_ITEM := 116 
STATIC DEFINE JANVIA_PAGE1_ORCAMENTO := 118 
STATIC DEFINE JANVIA_PAGE1_QTDENEG := 103 
STATIC DEFINE JANVIA_PAGE1_RAB28 := 112 
STATIC DEFINE JANVIA_PAGE1_RADIOBUTTON6 := 113 
STATIC DEFINE JANVIA_PAGE1_RADIOBUTTON7 := 111 
STATIC DEFINE JANVIA_PAGE1_RB28 := 114 
STATIC DEFINE JANVIA_PAGE1_SC_CLIENTE1 := 104 
STATIC DEFINE JANVIA_PAGE1_SC_CLIENTE2 := 102 
STATIC DEFINE JANVIA_PAGE1_SITUACAO := 115 
STATIC DEFINE JANVIA_PAGE1_THEFIXEDTEXT15 := 123 
STATIC DEFINE JANVIA_PAGE1_THEFIXEDTEXT16 := 121 
STATIC DEFINE JANVIA_PAGE1_THEFIXEDTEXT17 := 119 
STATIC DEFINE JANVIA_PAGE1_THEFIXEDTEXT18 := 106 
STATIC DEFINE JANVIA_PAGE1_THEFIXEDTEXT19 := 109 
STATIC DEFINE JANVIA_PAGE1_THEFIXEDTEXT20 := 117 
STATIC DEFINE JANVIA_PAGE1_VALORFER := 122 
STATIC DEFINE JANVIA_PAGE1_VALORUNI := 120 
STATIC DEFINE JANVIA_PAGE2_OBSG01 := 100 
STATIC DEFINE JANVIA_PAGE2_OBSG02 := 101 
STATIC DEFINE JANVIA_PAGE2_OBSG03 := 102 
STATIC DEFINE JANVIA_PAGE2_OBSG04 := 103 
STATIC DEFINE JANVIA_PAGE2_OBSG05 := 104 
STATIC DEFINE JANVIA_PAGE2_OBSG06 := 105 
STATIC DEFINE JANVIA_PAGE2_OBSG07 := 106 
STATIC DEFINE JANVIA_PAGE2_OBSG08 := 107 
STATIC DEFINE JANVIA_PAGE3_COMVEND := 110 
STATIC DEFINE JANVIA_PAGE3_GROUPBOX1 := 104 
STATIC DEFINE JANVIA_PAGE3_INCDATA := 108 
STATIC DEFINE JANVIA_PAGE3_INCHORA := 109 
STATIC DEFINE JANVIA_PAGE3_INCUSER := 107 
STATIC DEFINE JANVIA_PAGE3_OBSCUS01 := 100 
STATIC DEFINE JANVIA_PAGE3_OBSCUS02 := 101 
STATIC DEFINE JANVIA_PAGE3_OBSCUS03 := 102 
STATIC DEFINE JANVIA_PAGE3_OBSVEN := 103 
STATIC DEFINE JANVIA_PAGE3_SC_COMPRADOR := 112 
STATIC DEFINE JANVIA_PAGE3_SC_INCHORA := 106 
STATIC DEFINE JANVIA_PAGE3_THEFIXEDTEXT14 := 105 
STATIC DEFINE JANVIA_PAGE3_VENDEDOR := 111 
STATIC DEFINE JANVIA_PAGE4_CANCELADO := 132 
STATIC DEFINE JANVIA_PAGE4_CMDHOJE1 := 110 
STATIC DEFINE JANVIA_PAGE4_COPIA := 114 
STATIC DEFINE JANVIA_PAGE4_DECLINADO := 133 
STATIC DEFINE JANVIA_PAGE4_DECLMOT := 135 
STATIC DEFINE JANVIA_PAGE4_DESMARCAR := 116 
STATIC DEFINE JANVIA_PAGE4_DESORC := 130 
STATIC DEFINE JANVIA_PAGE4_DESORCDAT := 126 
STATIC DEFINE JANVIA_PAGE4_DESORCREV := 128 
STATIC DEFINE JANVIA_PAGE4_ESCFOR := 136 
STATIC DEFINE JANVIA_PAGE4_FDATA := 105 
STATIC DEFINE JANVIA_PAGE4_FOLLOWUP := 134 
STATIC DEFINE JANVIA_PAGE4_FVALORFER := 102 
STATIC DEFINE JANVIA_PAGE4_FVALORUNI := 103 
STATIC DEFINE JANVIA_PAGE4_ITEM := 107 
STATIC DEFINE JANVIA_PAGE4_OBSCLI := 124 
STATIC DEFINE JANVIA_PAGE4_ORCAMENTO := 106 
STATIC DEFINE JANVIA_PAGE4_QTDENEG := 104 
STATIC DEFINE JANVIA_PAGE4_RAB28 := 118 
STATIC DEFINE JANVIA_PAGE4_RADIOBUTTON6 := 119 
STATIC DEFINE JANVIA_PAGE4_RADIOBUTTON7 := 117 
STATIC DEFINE JANVIA_PAGE4_RB28 := 120 
STATIC DEFINE JANVIA_PAGE4_SC_CLIENTE1 := 112 
STATIC DEFINE JANVIA_PAGE4_SC_CLIENTE2 := 111 
STATIC DEFINE JANVIA_PAGE4_SC_DESENHO := 131 
STATIC DEFINE JANVIA_PAGE4_SC_REV := 129 
STATIC DEFINE JANVIA_PAGE4_SC_REV1 := 127 
STATIC DEFINE JANVIA_PAGE4_SITUACAO := 121 
STATIC DEFINE JANVIA_PAGE4_THEFIXEDTEXT14 := 125 
STATIC DEFINE JANVIA_PAGE4_THEFIXEDTEXT15 := 109 
STATIC DEFINE JANVIA_PAGE4_THEFIXEDTEXT16 := 108 
STATIC DEFINE JANVIA_PAGE4_THEFIXEDTEXT17 := 123 
STATIC DEFINE JANVIA_PAGE4_THEFIXEDTEXT18 := 113 
STATIC DEFINE JANVIA_PAGE4_THEFIXEDTEXT19 := 115 
STATIC DEFINE JANVIA_PAGE4_THEFIXEDTEXT20 := 122 
STATIC DEFINE JANVIA_PAGE4_VALORFER := 100 
STATIC DEFINE JANVIA_PAGE4_VALORUNI := 101 
STATIC DEFINE JANVIA_PAGEA_AM := 118 
STATIC DEFINE JANVIA_PAGEA_CMDAM := 119 
STATIC DEFINE JANVIA_PAGEA_CMDAM1 := 132 
STATIC DEFINE JANVIA_PAGEA_CMDAM2 := 135 
STATIC DEFINE JANVIA_PAGEA_CMDAM3 := 138 
STATIC DEFINE JANVIA_PAGEA_CMDAM4 := 139 
STATIC DEFINE JANVIA_PAGEA_CMDCODESF := 129 
STATIC DEFINE JANVIA_PAGEA_CMDPR := 123 
STATIC DEFINE JANVIA_PAGEA_CMDTIPO := 126 
STATIC DEFINE JANVIA_PAGEA_COT01 := 112 
STATIC DEFINE JANVIA_PAGEA_COT02 := 110 
STATIC DEFINE JANVIA_PAGEA_COT03 := 111 
STATIC DEFINE JANVIA_PAGEA_COT04 := 109 
STATIC DEFINE JANVIA_PAGEA_COT05 := 128 
STATIC DEFINE JANVIA_PAGEA_COT06 := 127 
STATIC DEFINE JANVIA_PAGEA_COT07 := 130 
STATIC DEFINE JANVIA_PAGEA_DUNS := 102 
STATIC DEFINE JANVIA_PAGEA_EAC := 100 
STATIC DEFINE JANVIA_PAGEA_ENVELOPE := 101 
STATIC DEFINE JANVIA_PAGEA_GI := 133 
STATIC DEFINE JANVIA_PAGEA_LOTEMIN := 105 
STATIC DEFINE JANVIA_PAGEA_NORMAT := 104 
STATIC DEFINE JANVIA_PAGEA_PR := 122 
STATIC DEFINE JANVIA_PAGEA_PROJETO := 103 
STATIC DEFINE JANVIA_PAGEA_QTEDANO := 107 
STATIC DEFINE JANVIA_PAGEA_SC_DESENHO3 := 108 
STATIC DEFINE JANVIA_PAGEA_SC_DESENHO4 := 106 
STATIC DEFINE JANVIA_PAGEA_SC_EAC := 114 
STATIC DEFINE JANVIA_PAGEA_SC_EAC1 := 116 
STATIC DEFINE JANVIA_PAGEA_SC_EAC2 := 117 
STATIC DEFINE JANVIA_PAGEA_SC_EAC3 := 120 
STATIC DEFINE JANVIA_PAGEA_SC_EAC4 := 121 
STATIC DEFINE JANVIA_PAGEA_SC_EAC5 := 125 
STATIC DEFINE JANVIA_PAGEA_SC_EAC6 := 134 
STATIC DEFINE JANVIA_PAGEA_SC_EAC7 := 136 
STATIC DEFINE JANVIA_PAGEA_SC_NORMAT := 115 
STATIC DEFINE JANVIA_PAGEA_SC_REV2 := 131 
STATIC DEFINE JANVIA_PAGEA_SEGMENTO := 137 
STATIC DEFINE JANVIA_PAGEA_THEGROUPBOX1 := 113 
STATIC DEFINE JANVIA_PAGEA_TIPOVIA := 124 
STATIC DEFINE JANVIA_PECA := 107
STATIC DEFINE JANVIA_PEDCLI := 104
STATIC DEFINE JANVIA_PEGMA01 := 138 
STATIC DEFINE JANVIA_PEGMS01 := 139
STATIC DEFINE JANVIA_POROV := 136
STATIC DEFINE JANVIA_PRZCLI := 101
STATIC DEFINE JANVIA_RB29 := 168 
STATIC DEFINE JANVIA_REQ01 := 170 
STATIC DEFINE JANVIA_REV := 151
STATIC DEFINE JANVIA_RFQN := 144
STATIC DEFINE JANVIA_SC_CLIENTE := 115
STATIC DEFINE JANVIA_SC_COMPRADOR := 117
STATIC DEFINE JANVIA_SC_DATAS := 112
STATIC DEFINE JANVIA_SC_DATAV := 116
STATIC DEFINE JANVIA_SC_DENOMINA := 118
STATIC DEFINE JANVIA_SC_DESENHO := 119
STATIC DEFINE JANVIA_SC_DESENHO1 := 132
STATIC DEFINE JANVIA_SC_DESENHO2 := 133
STATIC DEFINE JANVIA_SC_DESENHO3 := 143
STATIC DEFINE JANVIA_SC_DESTINO2 := 147
STATIC DEFINE JANVIA_SC_OV := 111
STATIC DEFINE JANVIA_SITUACAO := 157
STATIC DEFINE JANVIA_TABCONTROL1 := 137
STATIC DEFINE JANVIA_TABULAR := 131
STATIC DEFINE JANVIA_TABULAR1 := 153
STATIC DEFINE JANVIA_THEFIXEDTEXT11 := 124
STATIC DEFINE JANVIA_THEFIXEDTEXT12 := 125
STATIC DEFINE JANVIA_THEFIXEDTEXT21 := 172 
STATIC DEFINE JANVIA_THEFIXEDTEXT24 := 166 
STATIC DEFINE JANVIA_THEFIXEDTEXT29 := 150 
STATIC DEFINE JANVIA_THEFIXEDTEXT38 := 113
STATIC DEFINE JANVIA_THERADIOBUTTON11 := 134 
STATIC DEFINE JANVIA_THERADIOBUTTON13 := 140 
STATIC DEFINE JANVIA_THERADIOBUTTON14 := 146 
STATIC DEFINE JANVIA_THERADIOBUTTON16 := 148 
STATIC DEFINE JANVIA_THERADIOBUTTON18 := 154 
STATIC DEFINE JANVIA_THERADIOBUTTON20 := 158 
STATIC DEFINE JANVIA_THERADIOBUTTON23 := 164 
STATIC DEFINE JANVIA_THERADIOBUTTON25 := 170 
STATIC DEFINE JANVIA_THERADIOBUTTON26 := 176 
STATIC DEFINE JANVIA_THESINGLELINEEDIT17 := 148 
STATIC DEFINE JANVIA_THESINGLELINEEDIT26 := 154 
STATIC DEFINE JANVIA_THESINGLELINEEDIT28 := 136 
STATIC DEFINE JANVIA_TRATS := 156 
STATIC DEFINE JANVIA_VIAVEL := 132 
#endregion

PARTIAL CLASS JANVIA INHERIT MYDataWindow
PROTECT oDBOV AS DataColumn
PROTECT oDBDATAS AS DataColumn
PROTECT oDBCLIENTE AS DataColumn
PROTECT oDBCLINOME AS DataColumn
PROTECT oDBDESENHO AS DataColumn
PROTECT oDBDENOMINA AS DataColumn
PROTECT oDBSITUACAO AS DataColumn
PROTECT oDCDATAEC AS DateSle
PROTECT oDCPRZCLI AS DateSle
PROTECT oDCCLIENTE AS rightSle
PROTECT oDCCLINOME AS SINGLELINEEDIT
PROTECT oDCPEDCLI AS SINGLELINEEDIT
PROTECT oDCCOMPRADOR AS COMBOBOX
PROTECT oDCDESENHO AS SINGLELINEEDIT
PROTECT oDCPECA AS SINGLELINEEDIT
PROTECT oDCGPS AS SINGLELINEEDIT
PROTECT oDCDENOMINA AS SINGLELINEEDIT
PROTECT oDCCOMCOMP AS SINGLELINEEDIT
PROTECT oDCSC_OV AS FIXEDTEXT
PROTECT oDCSC_DATAS AS FIXEDTEXT
PROTECT oDCtheFixedText38 AS FIXEDTEXT
PROTECT oDCOV AS SINGLELINEEDIT
PROTECT oDCSC_CLIENTE AS FIXEDTEXT
PROTECT oDCSC_DATAV AS FIXEDTEXT
PROTECT oDCSC_COMPRADOR AS FIXEDTEXT
PROTECT oDCSC_DENOMINA AS FIXEDTEXT
PROTECT oDCSC_DESENHO AS FIXEDTEXT
PROTECT oDCFT13 AS FIXEDTEXT
PROTECT oDCFT16 AS FIXEDTEXT
PROTECT oDCOVORI AS SINGLELINEEDIT
PROTECT oCCDuplicar AS PUSHBUTTON
PROTECT oDCtheFixedText11 AS FIXEDTEXT
PROTECT oDCtheFixedText12 AS FIXEDTEXT
PROTECT oCCcmdHoje AS PUSHBUTTON
PROTECT oSFJVIII AS JVIII
PROTECT oDCFixedText22 AS FIXEDTEXT
PROTECT oCCCondicional AS PUSHBUTTON
PROTECT oCCEditar AS PUSHBUTTON
PROTECT oCCTabular AS PUSHBUTTON
PROTECT oDCSC_DESENHO1 AS FIXEDTEXT
PROTECT oDCSC_DESENHO2 AS FIXEDTEXT
PROTECT oCCescfor AS PUSHBUTTON
PROTECT oCCbuscaov AS PUSHBUTTON
PROTECT oCCporov AS PUSHBUTTON
PROTECT oDCTabControl1 AS TABCONTROL
PROTECT oTPJANVIA_PAGE2 AS JANVIA_PAGE2
PROTECT oTPJANVIA_PAGE3 AS JANVIA_PAGE3
PROTECT oTPJANVIA_PAGE4 AS JANVIA_PAGE4
PROTECT oTPJANVIA_PAGEA AS JANVIA_PAGEA
PROTECT oCCbtnpegma01 AS PUSHBUTTON
PROTECT oCCpegms01 AS PUSHBUTTON
PROTECT oCCEmail AS PUSHBUTTON
PROTECT oCCEmailvct AS PUSHBUTTON
PROTECT oCCesccod AS PUSHBUTTON
PROTECT oDCSC_DESENHO3 AS FIXEDTEXT
PROTECT oDCRFQN AS SINGLELINEEDIT
PROTECT oDCDATAS AS DateSle
PROTECT oDCDATAV AS DateSle
PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
PROTECT oCCfoto AS PUSHBUTTON
PROTECT oCCchkclipro AS PUSHBUTTON
PROTECT oDCCODIGOINT AS SINGLELINEEDIT
PROTECT oDCrev AS SINGLELINEEDIT
PROTECT oSFJVIAREV AS JVIAREV
PROTECT oCCTabular1 AS PUSHBUTTON
PROTECT oCCEditar1 AS PUSHBUTTON
PROTECT oCCnovarev AS PUSHBUTTON
PROTECT oCCnovarev1 AS PUSHBUTTON
PROTECT oCCFECCODIGO AS PUSHBUTTON

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS CLIENTE
RETURN SELF:FieldGet( #CLIENTE )

ASSIGN CLIENTE( uValue )
SELF:FieldPut( #CLIENTE , uValue )

ACCESS CLINOME
RETURN SELF:FieldGet( #CLINOME )

ASSIGN CLINOME( uValue )
SELF:FieldPut( #CLINOME , uValue )

ACCESS CODIGOINT
RETURN SELF:FieldGet( #CODIGOINT )

ASSIGN CODIGOINT( uValue )
SELF:FieldPut( #CODIGOINT , uValue )

ACCESS COMCOMP
RETURN SELF:FieldGet( #COMCOMP )

ASSIGN COMCOMP( uValue )
SELF:FieldPut( #COMCOMP , uValue )

ACCESS COMPRADOR
RETURN SELF:FieldGet( #COMPRADOR )

ASSIGN COMPRADOR( uValue )
SELF:FieldPut( #COMPRADOR , uValue )

ACCESS DATAEC
RETURN SELF:FieldGet( #DATAEC )

ASSIGN DATAEC( uValue )
SELF:FieldPut( #DATAEC , uValue )

ACCESS DATAS
RETURN SELF:FieldGet( #DATAS )

ASSIGN DATAS( uValue )
SELF:FieldPut( #DATAS , uValue )

ACCESS DATAV
RETURN SELF:FieldGet( #DATAV )

ASSIGN DATAV( uValue )
SELF:FieldPut( #DATAV , uValue )

ACCESS DENOMINA
RETURN SELF:FieldGet( #DENOMINA )

ASSIGN DENOMINA( uValue )
SELF:FieldPut( #DENOMINA , uValue )

ACCESS DESENHO
RETURN SELF:FieldGet( #DESENHO )

ASSIGN DESENHO( uValue )
SELF:FieldPut( #DESENHO , uValue )

ACCESS DISPE() 
RETURN SELF:FieldGet(#DISPE)


ACCESS DISPO() 
RETURN SELF:FieldGet(#DISPO)


ACCESS FESP() 
RETURN SELF:FieldGet(#FESP)


ACCESS GPS
RETURN SELF:FieldGet( #GPS )

ASSIGN GPS( uValue )
SELF:FieldPut( #GPS , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JANVIA" , _GetInst()},iCtlID)

	SELF:oDCDATAEC := DateSle{SELF , ResourceID{ JANVIA_DATAEC  , _GetInst() } }
	SELF:oDCDATAEC:FieldSpec := date_field{}
	SELF:oDCDATAEC:HyperLabel := HyperLabel{#DATAEC , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCPRZCLI := DateSle{SELF , ResourceID{ JANVIA_PRZCLI  , _GetInst() } }
	SELF:oDCPRZCLI:FieldSpec := date_field{}
	SELF:oDCPRZCLI:HyperLabel := HyperLabel{#PRZCLI , "Przcli:" , NULL_STRING , "VIABILI_PRZCLI"}

	SELF:oDCCLIENTE := rightSle{SELF , ResourceID{ JANVIA_CLIENTE  , _GetInst() } }
	SELF:oDCCLIENTE:FieldSpec := padrao_num_08{}
	SELF:oDCCLIENTE:HyperLabel := HyperLabel{#CLIENTE , "Cliente" , NULL_STRING , NULL_STRING}

	SELF:oDCCLINOME := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_CLINOME  , _GetInst() } }
	SELF:oDCCLINOME:FieldSpec := padrao_char_50{}
	SELF:oDCCLINOME:FocusSelect := FSEL_HOME
	SELF:oDCCLINOME:HyperLabel := HyperLabel{#CLINOME , "Cliente:" , NULL_STRING , "VIABILI_CLIENTE"}

	SELF:oDCPEDCLI := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_PEDCLI  , _GetInst() } }
	SELF:oDCPEDCLI:FieldSpec := padrao_char_20{}
	SELF:oDCPEDCLI:HyperLabel := HyperLabel{#PEDCLI , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCCOMPRADOR := COMBOBOX{SELF , ResourceID{ JANVIA_COMPRADOR  , _GetInst() } }
	SELF:oDCCOMPRADOR:FillUsing( SELF:PEGMC02() )
	SELF:oDCCOMPRADOR:FieldSpec := padrao_char_05{}
	SELF:oDCCOMPRADOR:HyperLabel := HyperLabel{#COMPRADOR , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCDESENHO := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_DESENHO  , _GetInst() } }
	SELF:oDCDESENHO:FieldSpec := padrao_char_20{}
	SELF:oDCDESENHO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCDESENHO:Font( oFont )
	SELF:oDCDESENHO:HyperLabel := HyperLabel{#DESENHO , "Desenho:" , NULL_STRING , "VIABILI_DESENHO"}

	SELF:oDCPECA := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_PECA  , _GetInst() } }
	SELF:oDCPECA:FieldSpec := padrao_char_20{}
	SELF:oDCPECA:HyperLabel := HyperLabel{#PECA , "Desenho:" , NULL_STRING , "VIABILI_DESENHO"}

	SELF:oDCGPS := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_GPS  , _GetInst() } }
	SELF:oDCGPS:FieldSpec := padrao_char_20{}
	SELF:oDCGPS:HyperLabel := HyperLabel{#GPS , "Desenho:" , NULL_STRING , "VIABILI_DESENHO"}

	SELF:oDCDENOMINA := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_DENOMINA  , _GetInst() } }
	SELF:oDCDENOMINA:FieldSpec := padrao_char_100{}
	SELF:oDCDENOMINA:HyperLabel := HyperLabel{#DENOMINA , "Denomina:" , NULL_STRING , "VIABILI_DENOMINA"}

	SELF:oDCCOMCOMP := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_COMCOMP  , _GetInst() } }
	SELF:oDCCOMCOMP:FieldSpec := padrao_char_40{}
	SELF:oDCCOMCOMP:HyperLabel := HyperLabel{#COMCOMP , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_OV := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_OV  , _GetInst() } }
	SELF:oDCSC_OV:HyperLabel := HyperLabel{#SC_OV , "Ov:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAS := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_DATAS  , _GetInst() } }
	SELF:oDCSC_DATAS:HyperLabel := HyperLabel{#SC_DATAS , "Solicitação" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText38 := FIXEDTEXT{SELF , ResourceID{ JANVIA_THEFIXEDTEXT38  , _GetInst() } }
	SELF:oDCtheFixedText38:HyperLabel := HyperLabel{#theFixedText38 , "Vencimento" , NULL_STRING , NULL_STRING}

	SELF:oDCOV := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_OV  , _GetInst() } }
	SELF:oDCOV:FieldSpec := padrao_num_08{}
	SELF:oDCOV:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCOV:Font( oFont )
	SELF:oDCOV:HyperLabel := HyperLabel{#OV , "Ov:" , NULL_STRING , "VIABILI_OV"}

	SELF:oDCSC_CLIENTE := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_CLIENTE  , _GetInst() } }
	SELF:oDCSC_CLIENTE:HyperLabel := HyperLabel{#SC_CLIENTE , "Cliente:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAV := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_DATAV  , _GetInst() } }
	SELF:oDCSC_DATAV:HyperLabel := HyperLabel{#SC_DATAV , "Datav:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_COMPRADOR := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_COMPRADOR  , _GetInst() } }
	SELF:oDCSC_COMPRADOR:HyperLabel := HyperLabel{#SC_COMPRADOR , "Comprador:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DENOMINA := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_DENOMINA  , _GetInst() } }
	SELF:oDCSC_DENOMINA:HyperLabel := HyperLabel{#SC_DENOMINA , "Denominação:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESENHO := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_DESENHO  , _GetInst() } }
	SELF:oDCSC_DESENHO:HyperLabel := HyperLabel{#SC_DESENHO , "Desenho:" , NULL_STRING , NULL_STRING}

	SELF:oDCFT13 := FIXEDTEXT{SELF , ResourceID{ JANVIA_FT13  , _GetInst() } }
	SELF:oDCFT13:HyperLabel := HyperLabel{#FT13 , "Original" , NULL_STRING , NULL_STRING}

	SELF:oDCFT16 := FIXEDTEXT{SELF , ResourceID{ JANVIA_FT16  , _GetInst() } }
	SELF:oDCFT16:HyperLabel := HyperLabel{#FT16 , "Entrega" , NULL_STRING , NULL_STRING}

	SELF:oDCOVORI := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_OVORI  , _GetInst() } }
	SELF:oDCOVORI:FieldSpec := padrao_num_08{}
	SELF:oDCOVORI:Background := Brush{ Color{ 255 , 255 , 220 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCOVORI:Font( oFont )
	SELF:oDCOVORI:HyperLabel := HyperLabel{#OVORI , "Ov:" , NULL_STRING , "VIABILI_OV"}

	SELF:oCCDuplicar := PUSHBUTTON{SELF , ResourceID{ JANVIA_DUPLICAR  , _GetInst() } }
	SELF:oCCDuplicar:HyperLabel := HyperLabel{#Duplicar , "Duplicar" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText11 := FIXEDTEXT{SELF , ResourceID{ JANVIA_THEFIXEDTEXT11  , _GetInst() } }
	SELF:oDCtheFixedText11:HyperLabel := HyperLabel{#theFixedText11 , "Nº Orc Cli" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText12 := FIXEDTEXT{SELF , ResourceID{ JANVIA_THEFIXEDTEXT12  , _GetInst() } }
	SELF:oDCtheFixedText12:HyperLabel := HyperLabel{#theFixedText12 , "Prazo Cliente" , NULL_STRING , NULL_STRING}

	SELF:oCCcmdHoje := PUSHBUTTON{SELF , ResourceID{ JANVIA_CMDHOJE  , _GetInst() } }
	SELF:oCCcmdHoje:HyperLabel := HyperLabel{#cmdHoje , "H" , NULL_STRING , NULL_STRING}

	SELF:oDCFixedText22 := FIXEDTEXT{SELF , ResourceID{ JANVIA_FIXEDTEXT22  , _GetInst() } }
	SELF:oDCFixedText22:HyperLabel := HyperLabel{#FixedText22 , "Lista de Verificação" , NULL_STRING , NULL_STRING}

	SELF:oCCCondicional := PUSHBUTTON{SELF , ResourceID{ JANVIA_CONDICIONAL  , _GetInst() } }
	SELF:oCCCondicional:HyperLabel := HyperLabel{#Condicional , "Condicional" , NULL_STRING , NULL_STRING}

	SELF:oCCEditar := PUSHBUTTON{SELF , ResourceID{ JANVIA_EDITAR  , _GetInst() } }
	SELF:oCCEditar:HyperLabel := HyperLabel{#Editar , "Editar" , NULL_STRING , NULL_STRING}

	SELF:oCCTabular := PUSHBUTTON{SELF , ResourceID{ JANVIA_TABULAR  , _GetInst() } }
	SELF:oCCTabular:HyperLabel := HyperLabel{#Tabular , "Tabular" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESENHO1 := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_DESENHO1  , _GetInst() } }
	SELF:oDCSC_DESENHO1:HyperLabel := HyperLabel{#SC_DESENHO1 , "PECA" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESENHO2 := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_DESENHO2  , _GetInst() } }
	SELF:oDCSC_DESENHO2:HyperLabel := HyperLabel{#SC_DESENHO2 , "GPS" , NULL_STRING , NULL_STRING}

	SELF:oCCescfor := PUSHBUTTON{SELF , ResourceID{ JANVIA_ESCFOR  , _GetInst() } }
	SELF:oCCescfor:HyperLabel := HyperLabel{#escfor , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCbuscaov := PUSHBUTTON{SELF , ResourceID{ JANVIA_BUSCAOV  , _GetInst() } }
	SELF:oCCbuscaov:Image := ico_find{}
	SELF:oCCbuscaov:HyperLabel := HyperLabel{#buscaov , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCporov := PUSHBUTTON{SELF , ResourceID{ JANVIA_POROV  , _GetInst() } }
	SELF:oCCporov:Image := ico_az{}
	SELF:oCCporov:HyperLabel := HyperLabel{#porov , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCTabControl1 := TABCONTROL{SELF , ResourceID{ JANVIA_TABCONTROL1  , _GetInst() } }
	SELF:oDCTabControl1:HyperLabel := HyperLabel{#TabControl1 , "Solicitação de Análisde de Viabilidade" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnpegma01 := PUSHBUTTON{SELF , ResourceID{ JANVIA_BTNPEGMA01  , _GetInst() } }
	SELF:oCCbtnpegma01:HyperLabel := HyperLabel{#btnpegma01 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCpegms01 := PUSHBUTTON{SELF , ResourceID{ JANVIA_PEGMS01  , _GetInst() } }
	SELF:oCCpegms01:HyperLabel := HyperLabel{#pegms01 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCEmail := PUSHBUTTON{SELF , ResourceID{ JANVIA_EMAIL  , _GetInst() } }
	SELF:oCCEmail:HyperLabel := HyperLabel{#Email , "Email" , NULL_STRING , NULL_STRING}

	SELF:oCCEmailvct := PUSHBUTTON{SELF , ResourceID{ JANVIA_EMAILVCT  , _GetInst() } }
	SELF:oCCEmailvct:HyperLabel := HyperLabel{#Emailvct , "Email" , NULL_STRING , NULL_STRING}

	SELF:oCCesccod := PUSHBUTTON{SELF , ResourceID{ JANVIA_ESCCOD  , _GetInst() } }
	SELF:oCCesccod:HyperLabel := HyperLabel{#esccod , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESENHO3 := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_DESENHO3  , _GetInst() } }
	SELF:oDCSC_DESENHO3:HyperLabel := HyperLabel{#SC_DESENHO3 , "RFQN" , NULL_STRING , NULL_STRING}

	SELF:oDCRFQN := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_RFQN  , _GetInst() } }
	SELF:oDCRFQN:FieldSpec := padrao_char_15{}
	SELF:oDCRFQN:HyperLabel := HyperLabel{#RFQN , "Przcli:" , NULL_STRING , "VIABILI_PRZCLI"}

	SELF:oDCDATAS := DateSle{SELF , ResourceID{ JANVIA_DATAS  , _GetInst() } }
	SELF:oDCDATAS:FieldSpec := date_field{}
	SELF:oDCDATAS:HyperLabel := HyperLabel{#DATAS , "Data" , NULL_STRING , NULL_STRING}

	SELF:oDCDATAV := DateSle{SELF , ResourceID{ JANVIA_DATAV  , _GetInst() } }
	SELF:oDCDATAV:FieldSpec := date_field{}
	SELF:oDCDATAV:HyperLabel := HyperLabel{#DATAV , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO2 := FIXEDTEXT{SELF , ResourceID{ JANVIA_SC_DESTINO2  , _GetInst() } }
	SELF:oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2 , "Foto" , NULL_STRING , NULL_STRING}

	SELF:oCCfoto := PUSHBUTTON{SELF , ResourceID{ JANVIA_FOTO  , _GetInst() } }
	SELF:oCCfoto:Image := ICO_CAMERA{}
	SELF:oCCfoto:HyperLabel := HyperLabel{#foto , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCchkclipro := PUSHBUTTON{SELF , ResourceID{ JANVIA_CHKCLIPRO  , _GetInst() } }
	SELF:oCCchkclipro:TooltipText := "Verificar os Nomes Clientes Produtos"
	SELF:oCCchkclipro:HyperLabel := HyperLabel{#chkclipro , "Checar Cliente Produto" , NULL_STRING , NULL_STRING}

	SELF:oDCCODIGOINT := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_CODIGOINT  , _GetInst() } }
	SELF:oDCCODIGOINT:FieldSpec := padrao_char_24{}
	SELF:oDCCODIGOINT:TooltipText := "Codigo do Produto"
	SELF:oDCCODIGOINT:HyperLabel := HyperLabel{#CODIGOINT , "Peca:" , NULL_STRING , "CD_PECA"}

	SELF:oDCrev := SINGLELINEEDIT{SELF , ResourceID{ JANVIA_REV  , _GetInst() } }
	SELF:oDCrev:FieldSpec := padrao_char_01{}
	SELF:oDCrev:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCrev:Font( oFont )
	SELF:oDCrev:HyperLabel := HyperLabel{#rev , "Ov:" , NULL_STRING , "VIABILI_OV"}

	SELF:oCCTabular1 := PUSHBUTTON{SELF , ResourceID{ JANVIA_TABULAR1  , _GetInst() } }
	SELF:oCCTabular1:HyperLabel := HyperLabel{#Tabular1 , "Tabular" , NULL_STRING , NULL_STRING}

	SELF:oCCEditar1 := PUSHBUTTON{SELF , ResourceID{ JANVIA_EDITAR1  , _GetInst() } }
	SELF:oCCEditar1:HyperLabel := HyperLabel{#Editar1 , "Editar" , NULL_STRING , NULL_STRING}

	SELF:oCCnovarev := PUSHBUTTON{SELF , ResourceID{ JANVIA_NOVAREV  , _GetInst() } }
	SELF:oCCnovarev:HyperLabel := HyperLabel{#novarev , "Nova Revisao" , NULL_STRING , NULL_STRING}

	SELF:oCCnovarev1 := PUSHBUTTON{SELF , ResourceID{ JANVIA_NOVAREV1  , _GetInst() } }
	SELF:oCCnovarev1:HyperLabel := HyperLabel{#novarev1 , "Fechar Esta Viabilidade" , NULL_STRING , NULL_STRING}

	SELF:oCCFECCODIGO := PUSHBUTTON{SELF , ResourceID{ JANVIA_FECCODIGO  , _GetInst() } }
	SELF:oCCFECCODIGO:HyperLabel := HyperLabel{#FECCODIGO , "Fechar V. deste Desenho" , NULL_STRING , NULL_STRING}

	SELF:Caption := "Solicitação de Análisde de Viabilidade"
	SELF:Menu := STANDARDSHELLMENU{}
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#JANVIA , "Solicitação de Análisde de Viabilidade" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBOV := DataColumn{padrao_num_08{}}
	SELF:oDBOV:Width := 13
	SELF:oDBOV:HyperLabel := SELF:oDCOV:HyperLabel
	SELF:oDBOV:Caption := "Ov:"
	SELF:Browser:AddColumn(SELF:oDBOV)

	SELF:oDBDATAS := DataColumn{date_field{}}
	SELF:oDBDATAS:Width := 18
	SELF:oDBDATAS:HyperLabel := SELF:oDCDATAS:HyperLabel
	SELF:oDBDATAS:Caption := "Data"
	SELF:Browser:AddColumn(SELF:oDBDATAS)

	SELF:oDBCLIENTE := DataColumn{padrao_num_08{}}
	SELF:oDBCLIENTE:Width := 9
	SELF:oDBCLIENTE:HyperLabel := SELF:oDCCLIENTE:HyperLabel
	SELF:oDBCLIENTE:Caption := "Cliente"
	SELF:Browser:AddColumn(SELF:oDBCLIENTE)

	SELF:oDBCLINOME := DataColumn{padrao_char_50{}}
	SELF:oDBCLINOME:Width := 19
	SELF:oDBCLINOME:HyperLabel := SELF:oDCCLINOME:HyperLabel
	SELF:oDBCLINOME:Caption := "Cliente:"
	SELF:Browser:AddColumn(SELF:oDBCLINOME)

	SELF:oDBDESENHO := DataColumn{padrao_char_20{}}
	SELF:oDBDESENHO:Width := 26
	SELF:oDBDESENHO:HyperLabel := SELF:oDCDESENHO:HyperLabel
	SELF:oDBDESENHO:Caption := "Desenho:"
	SELF:Browser:AddColumn(SELF:oDBDESENHO)

	SELF:oDBDENOMINA := DataColumn{padrao_char_100{}}
	SELF:oDBDENOMINA:Width := 27
	SELF:oDBDENOMINA:HyperLabel := SELF:oDCDENOMINA:HyperLabel
	SELF:oDBDENOMINA:Caption := "Denomina:"
	SELF:Browser:AddColumn(SELF:oDBDENOMINA)

	SELF:oDBSITUACAO := DataColumn{4}
	SELF:oDBSITUACAO:Width := 4
	SELF:oDBSITUACAO:HyperLabel := HyperLabel{#SITUACAO,"A", NULL_STRING, NULL_STRING}
	SELF:oDBSITUACAO:Caption := "A"
	SELF:Browser:AddColumn(SELF:oDBSITUACAO)

	SELF:ViewAs(#FormView)

	SELF:oSFJVIII := JVIII{SELF , JANVIA_JVIII }
	SELF:oSFJVIII:Show()
	SELF:oSFJVIAREV := JVIAREV{SELF , JANVIA_JVIAREV }
	SELF:oSFJVIAREV:Show()
	SELF:oTPJANVIA_PAGE2 := JANVIA_PAGE2{SELF , 0}
	SELF:oDCTabControl1:AppendTab(#JANVIA_PAGE2 , "Obs Geral" , SELF:oTPJANVIA_PAGE2 , 0)
	SELF:oTPJANVIA_PAGE3 := JANVIA_PAGE3{SELF , 0}
	SELF:oDCTabControl1:AppendTab(#JANVIA_PAGE3 , "Obs Custo/Vendas" , SELF:oTPJANVIA_PAGE3 , 0)
	SELF:oTPJANVIA_PAGE4 := JANVIA_PAGE4{SELF , 0}
	SELF:oDCTabControl1:AppendTab(#JANVIA_PAGE4 , "Fechamento" , SELF:oTPJANVIA_PAGE4 , 0)
	SELF:oTPJANVIA_PAGEA := JANVIA_PAGEA{SELF , 0}
	SELF:oDCTabControl1:AppendTab(#JANVIA_PAGEA , "Cotacao/Est." , SELF:oTPJANVIA_PAGEA , 0)
	SELF:oDCTabControl1:SelectTab(#JANVIA_PAGE2)

	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS MATM() 
RETURN SELF:FieldGet(#MATM)


ACCESS MATS() 
RETURN SELF:FieldGet(#MATS)


ACCESS OBSE01() 
RETURN SELF:FieldGet(#OBSE01)


ACCESS OBSE02() 
RETURN SELF:FieldGet(#OBSE02)


ACCESS OBSF01() 
RETURN SELF:FieldGet(#OBSF01)


ACCESS OBSF02() 
RETURN SELF:FieldGet(#OBSF02)


ACCESS OBSI01() 
RETURN SELF:FieldGet(#OBSI01)


ACCESS OBSI02() 
RETURN SELF:FieldGet(#OBSI02)


ACCESS OBSI03() 
RETURN SELF:FieldGet(#OBSI03)


ACCESS OBSM01() 
RETURN SELF:FieldGet(#OBSM01)


ACCESS OBSM02() 
RETURN SELF:FieldGet(#OBSM02)


ACCESS OBSO01() 
RETURN SELF:FieldGet(#OBSO01)


ACCESS OBSO02() 
RETURN SELF:FieldGet(#OBSO02)


ACCESS OBST01() 
RETURN SELF:FieldGet(#OBST01)


ACCESS OBST02() 
RETURN SELF:FieldGet(#OBST02)


ACCESS OV
RETURN SELF:FieldGet( #OV )

ASSIGN OV( uValue )
SELF:FieldPut( #OV , uValue )

ACCESS OVORI
RETURN SELF:FieldGet( #OVORI )

ASSIGN OVORI( uValue )
SELF:FieldPut( #OVORI , uValue )

ACCESS PECA
RETURN SELF:FieldGet( #PECA )

ASSIGN PECA( uValue )
SELF:FieldPut( #PECA , uValue )

ACCESS PEDCLI
RETURN SELF:FieldGet( #PEDCLI )

ASSIGN PEDCLI( uValue )
SELF:FieldPut( #PEDCLI , uValue )

METHOD PEGMC02() 
RETU PEGCOMBO("MC02.DBF","COGNOME","NUMERO")


ACCESS PRZCLI
RETURN SELF:FieldGet( #PRZCLI )

ASSIGN PRZCLI( uValue )
SELF:FieldPut( #PRZCLI , uValue )

ACCESS REQ01() 
RETURN SELF:FieldGet(#REQ01)


ACCESS REQ02() 
RETURN SELF:FieldGet(#REQ02)


ACCESS REQC() 
RETURN SELF:FieldGet(#REQC)


ACCESS rev
RETURN SELF:FieldGet( #rev )

ASSIGN rev( uValue )
SELF:FieldPut( #rev , uValue )

ACCESS RFQN
RETURN SELF:FieldGet( #RFQN )

ASSIGN RFQN( uValue )
SELF:FieldPut( #RFQN , uValue )

ACCESS SITUACAO
RETURN SELF:FieldGet( #SITUACAO )

ASSIGN SITUACAO( uValue )
SELF:FieldPut( #SITUACAO , uValue )

ACCESS TRATM() 
RETURN SELF:FieldGet(#TRATM)


ACCESS TRATS() 
RETURN SELF:FieldGet(#TRATS)


END CLASS
PARTIAL CLASS JANVIA_Page1 INHERIT DATAWINDOW 

	PROTECT oCCcmdHoje1 AS PUSHBUTTON
	PROTECT oDCFDATA AS DATESLE
	PROTECT oDCSC_CLIENTE2 AS FIXEDTEXT
	PROTECT oDCQTDENEG AS RIGHTSLE
	PROTECT oDCSC_CLIENTE1 AS FIXEDTEXT
	PROTECT oDCFVALORUNI AS RIGHTSLE
	PROTECT oDCtheFixedText18 AS FIXEDTEXT
	PROTECT oCCcopia AS PUSHBUTTON
	PROTECT oDCFVALORFER AS RIGHTSLE
	PROTECT oDCtheFixedText19 AS FIXEDTEXT
	PROTECT oCCdesmarcar AS PUSHBUTTON
	PROTECT oCCRadioButton7 AS RADIOBUTTON
	PROTECT oCCRaB28 AS RADIOBUTTON
	PROTECT oCCRadioButton6 AS RADIOBUTTON
	PROTECT oCCRB28 AS RADIOBUTTON
	PROTECT oDCSITUACAO AS RADIOBUTTONGROUP
	PROTECT oDCITEM AS RIGHTSLE
	PROTECT oDCtheFixedText20 AS FIXEDTEXT
	PROTECT oDCORCAMENTO AS RIGHTSLE
	PROTECT oDCtheFixedText17 AS FIXEDTEXT
	PROTECT oDCVALORUNI AS RIGHTSLE
	PROTECT oDCtheFixedText16 AS FIXEDTEXT
	PROTECT oDCVALORFER AS RIGHTSLE
	PROTECT oDCtheFixedText15 AS FIXEDTEXT
// 	instance FDATA 
// 	instance QTDENEG 
// 	instance FVALORUNI 
// 	instance FVALORFER 
// 	instance SITUACAO 
// 	instance ITEM 
// 	instance ORCAMENTO 
// 	instance VALORUNI 
// 	instance VALORFER 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS FDATA() 
RETURN SELF:FieldGet(#FDATA)


ASSIGN FDATA(uValue) 
SELF:FieldPut(#FDATA, uValue)
RETURN FDATA := uValue


ACCESS FVALORFER() 
RETURN SELF:FieldGet(#FVALORFER)


ASSIGN FVALORFER(uValue) 
SELF:FieldPut(#FVALORFER, uValue)
RETURN FVALORFER := uValue


ACCESS FVALORUNI() 
RETURN SELF:FieldGet(#FVALORUNI)


ASSIGN FVALORUNI(uValue) 
SELF:FieldPut(#FVALORUNI, uValue)
RETURN FVALORUNI := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JANVIA_Page1",_GetInst()},iCtlID)

oCCcmdHoje1 := PushButton{SELF,ResourceID{JANVIA_PAGE1_CMDHOJE1,_GetInst()}}
oCCcmdHoje1:HyperLabel := HyperLabel{#cmdHoje1,"H",NULL_STRING,NULL_STRING}

oDCFDATA := DateSle{SELF,ResourceID{JANVIA_PAGE1_FDATA,_GetInst()}}
oDCFDATA:FieldSpec := DATE_FIELD{}
oDCFDATA:HyperLabel := HyperLabel{#FDATA,NULL_STRING,NULL_STRING,NULL_STRING}

oDCSC_CLIENTE2 := FixedText{SELF,ResourceID{JANVIA_PAGE1_SC_CLIENTE2,_GetInst()}}
oDCSC_CLIENTE2:HyperLabel := HyperLabel{#SC_CLIENTE2,"Data:",NULL_STRING,NULL_STRING}

oDCQTDENEG := rightSle{SELF,ResourceID{JANVIA_PAGE1_QTDENEG,_GetInst()}}
oDCQTDENEG:FieldSpec := PADRAO_NUM_08{}
oDCQTDENEG:HyperLabel := HyperLabel{#QTDENEG,NULL_STRING,NULL_STRING,NULL_STRING}

oDCSC_CLIENTE1 := FixedText{SELF,ResourceID{JANVIA_PAGE1_SC_CLIENTE1,_GetInst()}}
oDCSC_CLIENTE1:HyperLabel := HyperLabel{#SC_CLIENTE1,"Qtde Neg.",NULL_STRING,NULL_STRING}

oDCFVALORUNI := rightSle{SELF,ResourceID{JANVIA_PAGE1_FVALORUNI,_GetInst()}}
oDCFVALORUNI:FieldSpec := PADRAO_NUM_12_4{}
oDCFVALORUNI:HyperLabel := HyperLabel{#FVALORUNI,NULL_STRING,NULL_STRING,NULL_STRING}

oDCtheFixedText18 := FixedText{SELF,ResourceID{JANVIA_PAGE1_THEFIXEDTEXT18,_GetInst()}}
oDCtheFixedText18:HyperLabel := HyperLabel{#theFixedText18,"Vl.Unidade",NULL_STRING,NULL_STRING}

oCCcopia := PushButton{SELF,ResourceID{JANVIA_PAGE1_COPIA,_GetInst()}}
oCCcopia:HyperLabel := HyperLabel{#copia,"Copia",NULL_STRING,NULL_STRING}

oDCFVALORFER := rightSle{SELF,ResourceID{JANVIA_PAGE1_FVALORFER,_GetInst()}}
oDCFVALORFER:HyperLabel := HyperLabel{#FVALORFER,NULL_STRING,NULL_STRING,NULL_STRING}
oDCFVALORFER:FieldSpec := PADRAO_NUM_12_2{}

oDCtheFixedText19 := FixedText{SELF,ResourceID{JANVIA_PAGE1_THEFIXEDTEXT19,_GetInst()}}
oDCtheFixedText19:HyperLabel := HyperLabel{#theFixedText19,"Vl.Ferramenta",NULL_STRING,NULL_STRING}

oCCdesmarcar := PushButton{SELF,ResourceID{JANVIA_PAGE1_DESMARCAR,_GetInst()}}
oCCdesmarcar:HyperLabel := HyperLabel{#desmarcar,"Desmarcar",NULL_STRING,NULL_STRING}

oCCRadioButton7 := RadioButton{SELF,ResourceID{JANVIA_PAGE1_RADIOBUTTON7,_GetInst()}}
oCCRadioButton7:HyperLabel := HyperLabel{#RadioButton7,"Recotação",NULL_STRING,NULL_STRING}

oCCRaB28 := RadioButton{SELF,ResourceID{JANVIA_PAGE1_RAB28,_GetInst()}}
oCCRaB28:HyperLabel := HyperLabel{#RaB28,"Reprovado",NULL_STRING,NULL_STRING}

oCCRadioButton6 := RadioButton{SELF,ResourceID{JANVIA_PAGE1_RADIOBUTTON6,_GetInst()}}
oCCRadioButton6:HyperLabel := HyperLabel{#RadioButton6,"Excluida",NULL_STRING,NULL_STRING}

oCCRB28 := RadioButton{SELF,ResourceID{JANVIA_PAGE1_RB28,_GetInst()}}
oCCRB28:HyperLabel := HyperLabel{#RB28,"Aprovado",NULL_STRING,NULL_STRING}

oDCITEM := rightSle{SELF,ResourceID{JANVIA_PAGE1_ITEM,_GetInst()}}
oDCITEM:FieldSpec := PADRAO_NUM_03{}
oDCITEM:HyperLabel := HyperLabel{#ITEM,NULL_STRING,NULL_STRING,NULL_STRING}

oDCtheFixedText20 := FixedText{SELF,ResourceID{JANVIA_PAGE1_THEFIXEDTEXT20,_GetInst()}}
oDCtheFixedText20:HyperLabel := HyperLabel{#theFixedText20,"Item",NULL_STRING,NULL_STRING}

oDCORCAMENTO := rightSle{SELF,ResourceID{JANVIA_PAGE1_ORCAMENTO,_GetInst()}}
oDCORCAMENTO:FieldSpec := PADRAO_NUM_08{}
oDCORCAMENTO:HyperLabel := HyperLabel{#ORCAMENTO,"Recotação",NULL_STRING,NULL_STRING}

oDCtheFixedText17 := FixedText{SELF,ResourceID{JANVIA_PAGE1_THEFIXEDTEXT17,_GetInst()}}
oDCtheFixedText17:HyperLabel := HyperLabel{#theFixedText17,"Orçamento",NULL_STRING,NULL_STRING}

oDCVALORUNI := rightSle{SELF,ResourceID{JANVIA_PAGE1_VALORUNI,_GetInst()}}
oDCVALORUNI:FieldSpec := PADRAO_NUM_12_4{}
oDCVALORUNI:HyperLabel := HyperLabel{#VALORUNI,NULL_STRING,NULL_STRING,NULL_STRING}

oDCtheFixedText16 := FixedText{SELF,ResourceID{JANVIA_PAGE1_THEFIXEDTEXT16,_GetInst()}}
oDCtheFixedText16:HyperLabel := HyperLabel{#theFixedText16,"Vl.Unidade",NULL_STRING,NULL_STRING}

oDCVALORFER := rightSle{SELF,ResourceID{JANVIA_PAGE1_VALORFER,_GetInst()}}
oDCVALORFER:HyperLabel := HyperLabel{#VALORFER,NULL_STRING,NULL_STRING,NULL_STRING}
oDCVALORFER:FieldSpec := PADRAO_NUM_12_2{}

oDCtheFixedText15 := FixedText{SELF,ResourceID{JANVIA_PAGE1_THEFIXEDTEXT15,_GetInst()}}
oDCtheFixedText15:HyperLabel := HyperLabel{#theFixedText15,"Vl.Ferramenta",NULL_STRING,NULL_STRING}

oDCSITUACAO := RadioButtonGroup{SELF,ResourceID{JANVIA_PAGE1_SITUACAO,_GetInst()}}
oDCSITUACAO:FillUsing({ ;
						{oCCRadioButton7,"E"}, ;
						{oCCRaB28,"R"}, ;
						{oCCRadioButton6,"X"}, ;
						{oCCRB28,"A"} ;
						})
oDCSITUACAO:HyperLabel := HyperLabel{#SITUACAO,"Fechamento no Cliente",NULL_STRING,NULL_STRING}
oDCSITUACAO:FieldSpec := PADRAO_CHAR_01{}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#JANVIA_Page1,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS ITEM() 
RETURN SELF:FieldGet(#ITEM)


ASSIGN ITEM(uValue) 
SELF:FieldPut(#ITEM, uValue)
RETURN ITEM := uValue


ACCESS ORCAMENTO() 
RETURN SELF:FieldGet(#ORCAMENTO)


ASSIGN ORCAMENTO(uValue) 
SELF:FieldPut(#ORCAMENTO, uValue)
RETURN ORCAMENTO := uValue


ACCESS QTDENEG() 
RETURN SELF:FieldGet(#QTDENEG)


ASSIGN QTDENEG(uValue) 
SELF:FieldPut(#QTDENEG, uValue)
RETURN QTDENEG := uValue


ACCESS SITUACAO() 
RETURN SELF:FieldGet(#SITUACAO)


ASSIGN SITUACAO(uValue) 
SELF:FieldPut(#SITUACAO, uValue)
RETURN SITUACAO := uValue


ACCESS VALORFER() 
RETURN SELF:FieldGet(#VALORFER)


ASSIGN VALORFER(uValue) 
SELF:FieldPut(#VALORFER, uValue)
RETURN VALORFER := uValue


ACCESS VALORUNI() 
RETURN SELF:FieldGet(#VALORUNI)


ASSIGN VALORUNI(uValue) 
SELF:FieldPut(#VALORUNI, uValue)
RETURN VALORUNI := uValue


END CLASS
CLASS JANVIA_Page2 INHERIT DATAWINDOW 

	PROTECT oDCOBSG01 AS SINGLELINEEDIT
	PROTECT oDCOBSG02 AS SINGLELINEEDIT
	PROTECT oDCOBSG03 AS SINGLELINEEDIT
	PROTECT oDCOBSG04 AS SINGLELINEEDIT
	PROTECT oDCOBSG05 AS SINGLELINEEDIT
	PROTECT oDCOBSG06 AS SINGLELINEEDIT
	PROTECT oDCOBSG07 AS SINGLELINEEDIT
	PROTECT oDCOBSG08 AS SINGLELINEEDIT
// 	instance OBSG01 
// 	instance OBSG02 
// 	instance OBSG03 
// 	instance OBSG04 
// 	instance OBSG05 
// 	instance OBSG06 
// 	instance OBSG07 
// 	instance OBSG08 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JANVIA_Page2",_GetInst()},iCtlID)

oDCOBSG01 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE2_OBSG01,_GetInst()}}
oDCOBSG01:FieldSpec := padrao_char_80{}
oDCOBSG01:HyperLabel := HyperLabel{#OBSG01,"Obsg01:",NULL_STRING,"VIABILI_OBSG01"}

oDCOBSG02 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE2_OBSG02,_GetInst()}}
oDCOBSG02:FieldSpec := padrao_char_80{}
oDCOBSG02:HyperLabel := HyperLabel{#OBSG02,"Obsg02:",NULL_STRING,"VIABILI_OBSG02"}

oDCOBSG03 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE2_OBSG03,_GetInst()}}
oDCOBSG03:FieldSpec := padrao_char_80{}
oDCOBSG03:HyperLabel := HyperLabel{#OBSG03,"Obsg03:",NULL_STRING,"VIABILI_OBSG03"}

oDCOBSG04 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE2_OBSG04,_GetInst()}}
oDCOBSG04:HyperLabel := HyperLabel{#OBSG04,"Obsg04:",NULL_STRING,"VIABILI_OBSG04"}
oDCOBSG04:FieldSpec := padrao_char_80{}

oDCOBSG05 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE2_OBSG05,_GetInst()}}
oDCOBSG05:FieldSpec := padrao_char_80{}
oDCOBSG05:HyperLabel := HyperLabel{#OBSG05,"Obsg05:",NULL_STRING,"VIABILI_OBSG05"}

oDCOBSG06 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE2_OBSG06,_GetInst()}}
oDCOBSG06:FieldSpec := padrao_char_80{}
oDCOBSG06:HyperLabel := HyperLabel{#OBSG06,"Obsg06:",NULL_STRING,"VIABILI_OBSG06"}

oDCOBSG07 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE2_OBSG07,_GetInst()}}
oDCOBSG07:FieldSpec := padrao_char_80{}
oDCOBSG07:HyperLabel := HyperLabel{#OBSG07,"Obsg07:",NULL_STRING,"VIABILI_OBSG07"}

oDCOBSG08 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE2_OBSG08,_GetInst()}}
oDCOBSG08:FieldSpec := padrao_char_80{}
oDCOBSG08:HyperLabel := HyperLabel{#OBSG08,"Obsg08:",NULL_STRING,"VIABILI_OBSG08"}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#JANVIA_Page2,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS OBSG01() 
RETURN SELF:FieldGet(#OBSG01)


ASSIGN OBSG01(uValue) 
SELF:FieldPut(#OBSG01, uValue)
RETURN OBSG01 := uValue


ACCESS OBSG02() 
RETURN SELF:FieldGet(#OBSG02)


ASSIGN OBSG02(uValue) 
SELF:FieldPut(#OBSG02, uValue)
RETURN OBSG02 := uValue


ACCESS OBSG03() 
RETURN SELF:FieldGet(#OBSG03)


ASSIGN OBSG03(uValue) 
SELF:FieldPut(#OBSG03, uValue)
RETURN OBSG03 := uValue


ACCESS OBSG04() 
RETURN SELF:FieldGet(#OBSG04)


ASSIGN OBSG04(uValue) 
SELF:FieldPut(#OBSG04, uValue)
RETURN OBSG04 := uValue


ACCESS OBSG05() 
RETURN SELF:FieldGet(#OBSG05)


ASSIGN OBSG05(uValue) 
SELF:FieldPut(#OBSG05, uValue)
RETURN OBSG05 := uValue


ACCESS OBSG06() 
RETURN SELF:FieldGet(#OBSG06)


ASSIGN OBSG06(uValue) 
SELF:FieldPut(#OBSG06, uValue)
RETURN OBSG06 := uValue


ACCESS OBSG07() 
RETURN SELF:FieldGet(#OBSG07)


ASSIGN OBSG07(uValue) 
SELF:FieldPut(#OBSG07, uValue)
RETURN OBSG07 := uValue


ACCESS OBSG08() 
RETURN SELF:FieldGet(#OBSG08)


ASSIGN OBSG08(uValue) 
SELF:FieldPut(#OBSG08, uValue)
RETURN OBSG08 := uValue


END CLASS
PARTIAL CLASS JANVIA_Page3 INHERIT DATAWINDOW 

	PROTECT oDBOBSCUS01 AS DataColumn
	PROTECT oDBOBSCUS02 AS DataColumn
	PROTECT oDBOBSCUS03 AS DataColumn
	PROTECT oDBOBSVEN AS DataColumn
	PROTECT oDBINCUSER AS DataColumn
	PROTECT oDBINCDATA AS DataColumn
	PROTECT oDBINCHORA AS DataColumn
	PROTECT oDCOBSCUS01 AS SINGLELINEEDIT
	PROTECT oDCOBSCUS02 AS SINGLELINEEDIT
	PROTECT oDCOBSCUS03 AS SINGLELINEEDIT
	PROTECT oDCOBSVEN AS SINGLELINEEDIT
	PROTECT oDCGroupBox1 AS GROUPBOX
	PROTECT oDCtheFixedText14 AS FIXEDTEXT
	PROTECT oDCSC_INCHORA AS FIXEDTEXT
	PROTECT oDCINCUSER AS SINGLELINEEDIT
	PROTECT oDCINCDATA AS SINGLELINEEDIT
	PROTECT oDCINCHORA AS SINGLELINEEDIT
	PROTECT oDCCOMVEND AS SINGLELINEEDIT
	PROTECT oDCVENDEDOR AS COMBOBOX
	PROTECT oDCSC_COMPRADOR AS FIXEDTEXT
// 	instance OBSCUS01 
// 	instance OBSCUS02 
// 	instance OBSCUS03 
// 	instance OBSVEN 
// 	instance INCUSER 
// 	instance INCDATA 
// 	instance INCHORA 
// 	instance COMVEND 
// 	instance VENDEDOR 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS COMVEND() 
RETURN SELF:FieldGet(#COMVEND)


ASSIGN COMVEND(uValue) 
SELF:FieldPut(#COMVEND, uValue)
RETURN COMVEND := uValue


ACCESS INCDATA() 
RETURN SELF:FieldGet(#INCDATA)


ASSIGN INCDATA(uValue) 
SELF:FieldPut(#INCDATA, uValue)
RETURN INCDATA := uValue


ACCESS INCHORA() 
RETURN SELF:FieldGet(#INCHORA)


ASSIGN INCHORA(uValue) 
SELF:FieldPut(#INCHORA, uValue)
RETURN INCHORA := uValue


ACCESS INCUSER() 
RETURN SELF:FieldGet(#INCUSER)


ASSIGN INCUSER(uValue) 
SELF:FieldPut(#INCUSER, uValue)
RETURN INCUSER := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[1] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JANVIA_Page3",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Times New Roman"}
aFonts[1]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCOBSCUS01 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE3_OBSCUS01,_GetInst()}}
oDCOBSCUS01:FieldSpec := padrao_char_100{}
oDCOBSCUS01:HyperLabel := HyperLabel{#OBSCUS01,"Obscus01:",NULL_STRING,"VIABILI_OBSCUS01"}
oDCOBSCUS01:TooltipText := "Observação para Custo"

oDCOBSCUS02 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE3_OBSCUS02,_GetInst()}}
oDCOBSCUS02:FieldSpec := padrao_char_100{}
oDCOBSCUS02:HyperLabel := HyperLabel{#OBSCUS02,"Obscus02:",NULL_STRING,"VIABILI_OBSCUS02"}
oDCOBSCUS02:TooltipText := "Observação para Custo"

oDCOBSCUS03 := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE3_OBSCUS03,_GetInst()}}
oDCOBSCUS03:FieldSpec := padrao_char_100{}
oDCOBSCUS03:HyperLabel := HyperLabel{#OBSCUS03,"Obscus03:",NULL_STRING,"VIABILI_OBSCUS03"}
oDCOBSCUS03:TooltipText := "Observação para Custo"

oDCOBSVEN := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE3_OBSVEN,_GetInst()}}
oDCOBSVEN:FieldSpec := padrao_char_100{}
oDCOBSVEN:HyperLabel := HyperLabel{#OBSVEN,"Obsg01:",NULL_STRING,"VIABILI_OBSG01"}
oDCOBSVEN:TooltipText := "Observação para Vendas"

oDCGroupBox1 := GroupBox{SELF,ResourceID{JANVIA_PAGE3_GROUPBOX1,_GetInst()}}
oDCGroupBox1:HyperLabel := HyperLabel{#GroupBox1,"Custo",NULL_STRING,NULL_STRING}

oDCtheFixedText14 := FixedText{SELF,ResourceID{JANVIA_PAGE3_THEFIXEDTEXT14,_GetInst()}}
oDCtheFixedText14:HyperLabel := HyperLabel{#theFixedText14,"Vendas",NULL_STRING,NULL_STRING}

oDCSC_INCHORA := FixedText{SELF,ResourceID{JANVIA_PAGE3_SC_INCHORA,_GetInst()}}
oDCSC_INCHORA:HyperLabel := HyperLabel{#SC_INCHORA,"Aberta Por:",NULL_STRING,NULL_STRING}

oDCINCUSER := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE3_INCUSER,_GetInst()}}
oDCINCUSER:FieldSpec := padrao_char_10{}
oDCINCUSER:HyperLabel := HyperLabel{#INCUSER,"Incuser:",NULL_STRING,"VIABILI_INCUSER"}
oDCINCUSER:TooltipText := "Usuario que Abriu a viabilidade"
oDCINCUSER:BackGround := aBrushes[1]
oDCINCUSER:Font(aFonts[1], FALSE)

oDCINCDATA := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE3_INCDATA,_GetInst()}}
oDCINCDATA:FieldSpec := date_field{}
oDCINCDATA:HyperLabel := HyperLabel{#INCDATA,"Incdata:",NULL_STRING,"VIABILI_INCDATA"}
oDCINCDATA:TooltipText := "Data Abertura Viabilidade"
oDCINCDATA:BackGround := aBrushes[1]
oDCINCDATA:Font(aFonts[1], FALSE)

oDCINCHORA := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE3_INCHORA,_GetInst()}}
oDCINCHORA:FieldSpec := padrao_char_10{}
oDCINCHORA:HyperLabel := HyperLabel{#INCHORA,"Inchora:",NULL_STRING,"VIABILI_INCHORA"}
oDCINCHORA:TooltipText := "Hora Abertura Viabilidade"
oDCINCHORA:BackGround := aBrushes[1]
oDCINCHORA:Font(aFonts[1], FALSE)

oDCCOMVEND := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE3_COMVEND,_GetInst()}}
oDCCOMVEND:FieldSpec := padrao_char_40{}
oDCCOMVEND:HyperLabel := HyperLabel{#COMVEND,NULL_STRING,NULL_STRING,NULL_STRING}

oDCVENDEDOR := combobox{SELF,ResourceID{JANVIA_PAGE3_VENDEDOR,_GetInst()}}
oDCVENDEDOR:HyperLabel := HyperLabel{#VENDEDOR,NULL_STRING,NULL_STRING,NULL_STRING}
oDCVENDEDOR:FillUsing(SELF:PEGMC01( ))
oDCVENDEDOR:FieldSpec := padrao_char_05{}

oDCSC_COMPRADOR := FixedText{SELF,ResourceID{JANVIA_PAGE3_SC_COMPRADOR,_GetInst()}}
oDCSC_COMPRADOR:HyperLabel := HyperLabel{#SC_COMPRADOR,"Vendedor:",NULL_STRING,NULL_STRING}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#JANVIA_Page3,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF
SELF:Browser := DataBrowser{SELF}

oDBOBSCUS01 := DataColumn{padrao_char_100{}}
oDBOBSCUS01:Width := 10
oDBOBSCUS01:HyperLabel := oDCOBSCUS01:HyperLabel 
oDBOBSCUS01:Caption := "Obscus01:"
SELF:Browser:AddColumn(oDBOBSCUS01)

oDBOBSCUS02 := DataColumn{padrao_char_100{}}
oDBOBSCUS02:Width := 10
oDBOBSCUS02:HyperLabel := oDCOBSCUS02:HyperLabel 
oDBOBSCUS02:Caption := "Obscus02:"
SELF:Browser:AddColumn(oDBOBSCUS02)

oDBOBSCUS03 := DataColumn{padrao_char_100{}}
oDBOBSCUS03:Width := 10
oDBOBSCUS03:HyperLabel := oDCOBSCUS03:HyperLabel 
oDBOBSCUS03:Caption := "Obscus03:"
SELF:Browser:AddColumn(oDBOBSCUS03)

oDBOBSVEN := DataColumn{padrao_char_100{}}
oDBOBSVEN:Width := 8
oDBOBSVEN:HyperLabel := oDCOBSVEN:HyperLabel 
oDBOBSVEN:Caption := "Obsg01:"
SELF:Browser:AddColumn(oDBOBSVEN)

oDBINCUSER := DataColumn{padrao_char_10{}}
oDBINCUSER:Width := 9
oDBINCUSER:HyperLabel := oDCINCUSER:HyperLabel 
oDBINCUSER:Caption := "Incuser:"
oDBINCUSER:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBINCUSER)

oDBINCDATA := DataColumn{date_field{}}
oDBINCDATA:Width := 9
oDBINCDATA:HyperLabel := oDCINCDATA:HyperLabel 
oDBINCDATA:Caption := "Incdata:"
oDBINCDATA:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBINCDATA)

oDBINCHORA := DataColumn{padrao_char_10{}}
oDBINCHORA:Width := 9
oDBINCHORA:HyperLabel := oDCINCHORA:HyperLabel 
oDBINCHORA:Caption := "Inchora:"
oDBINCHORA:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBINCHORA)


SELF:ViewAs(#FormView)

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


METHOD ListBoxSelect(oControlEvent) 
	LOCAL oControl AS Control
	LOCAL aCOM AS ARRAY
	oControl := IIf(oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control)
	SUPER:ListBoxSelect(oControlEvent)
	//Put your changes here
	 DO CASE
	       CASE oCONTROL:NAMESYM==#VENDEDOR
                             aCOM:=PEGMC(SELF:SERVER:COMPRADOR,"MC01.DBF")
                             IF aCOM[1]=.T.
                                  SELF:SERVER:COMVEND:=aCOM[2]
                             ENDIF
        ENDCASE
	RETURN NIL


ACCESS OBSCUS01() 
RETURN SELF:FieldGet(#OBSCUS01)


ASSIGN OBSCUS01(uValue) 
SELF:FieldPut(#OBSCUS01, uValue)
RETURN OBSCUS01 := uValue


ACCESS OBSCUS02() 
RETURN SELF:FieldGet(#OBSCUS02)


ASSIGN OBSCUS02(uValue) 
SELF:FieldPut(#OBSCUS02, uValue)
RETURN OBSCUS02 := uValue


ACCESS OBSCUS03() 
RETURN SELF:FieldGet(#OBSCUS03)


ASSIGN OBSCUS03(uValue) 
SELF:FieldPut(#OBSCUS03, uValue)
RETURN OBSCUS03 := uValue


ACCESS OBSVEN() 
RETURN SELF:FieldGet(#OBSVEN)


ASSIGN OBSVEN(uValue) 
SELF:FieldPut(#OBSVEN, uValue)
RETURN OBSVEN := uValue


ACCESS VENDEDOR() 
RETURN SELF:FieldGet(#VENDEDOR)


ASSIGN VENDEDOR(uValue) 
SELF:FieldPut(#VENDEDOR, uValue)
RETURN VENDEDOR := uValue


END CLASS
PARTIAL CLASS JANVIA_Page4 INHERIT DATAWINDOW 

	PROTECT oDCVALORFER AS RIGHTSLE
	PROTECT oDCVALORUNI AS RIGHTSLE
	PROTECT oDCFVALORFER AS RIGHTSLE
	PROTECT oDCFVALORUNI AS RIGHTSLE
	PROTECT oDCQTDENEG AS RIGHTSLE
	PROTECT oDCFDATA AS DATESLE
	PROTECT oDCORCAMENTO AS RIGHTSLE
	PROTECT oDCITEM AS RIGHTSLE
	PROTECT oDCtheFixedText16 AS FIXEDTEXT
	PROTECT oDCtheFixedText15 AS FIXEDTEXT
	PROTECT oCCcmdHoje1 AS PUSHBUTTON
	PROTECT oDCSC_CLIENTE2 AS FIXEDTEXT
	PROTECT oDCSC_CLIENTE1 AS FIXEDTEXT
	PROTECT oDCtheFixedText18 AS FIXEDTEXT
	PROTECT oCCcopia AS PUSHBUTTON
	PROTECT oDCtheFixedText19 AS FIXEDTEXT
	PROTECT oCCdesmarcar AS PUSHBUTTON
	PROTECT oCCRadioButton7 AS RADIOBUTTON
	PROTECT oCCRaB28 AS RADIOBUTTON
	PROTECT oCCRadioButton6 AS RADIOBUTTON
	PROTECT oCCRB28 AS RADIOBUTTON
	PROTECT oDCSITUACAO AS RADIOBUTTONGROUP
	PROTECT oDCtheFixedText20 AS FIXEDTEXT
	PROTECT oDCtheFixedText17 AS FIXEDTEXT
	PROTECT oDCOBSCLI AS SINGLELINEEDIT
	PROTECT oDCtheFixedText14 AS FIXEDTEXT
	PROTECT oDCDESORCDAT AS DATESLE
	PROTECT oDCSC_REV1 AS FIXEDTEXT
	PROTECT oDCDESORCREV AS SINGLELINEEDIT
	PROTECT oDCSC_REV AS FIXEDTEXT
	PROTECT oDCDESORC AS SINGLELINEEDIT
	PROTECT oDCSC_DESENHO AS FIXEDTEXT
	PROTECT oDCCANCELADO AS CHECKBOX
	PROTECT oDCDECLINADO AS CHECKBOX
	PROTECT oDCFOLLOWUP AS CHECKBOX
	PROTECT oDCDECLMOT AS RIGHTSLE
	PROTECT oCCescfor AS PUSHBUTTON
// 	instance VALORFER 
// 	instance VALORUNI 
// 	instance FVALORFER 
// 	instance FVALORUNI 
// 	instance QTDENEG 
// 	instance FDATA 
// 	instance ORCAMENTO 
// 	instance ITEM 
// 	instance SITUACAO 
// 	instance OBSCLI 
// 	instance DESORCDAT 
// 	instance DESORCREV 
// 	instance DESORC 
// 	instance CANCELADO 
// 	instance DECLINADO 
// 	instance FOLLOWUP 
// 	instance DECLMOT 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS CANCELADO() 
RETURN SELF:FieldGet(#CANCELADO)


ASSIGN CANCELADO(uValue) 
SELF:FieldPut(#CANCELADO, uValue)
RETURN CANCELADO := uValue


ACCESS DECLINADO() 
RETURN SELF:FieldGet(#DECLINADO)


ASSIGN DECLINADO(uValue) 
SELF:FieldPut(#DECLINADO, uValue)
RETURN DECLINADO := uValue


ACCESS DECLMOT() 
RETURN SELF:FieldGet(#DECLMOT)


ASSIGN DECLMOT(uValue) 
SELF:FieldPut(#DECLMOT, uValue)
RETURN DECLMOT := uValue


ACCESS DESORC() 
RETURN SELF:FieldGet(#DESORC)


ASSIGN DESORC(uValue) 
SELF:FieldPut(#DESORC, uValue)
RETURN DESORC := uValue


ACCESS DESORCDAT() 
RETURN SELF:FieldGet(#DESORCDAT)


ASSIGN DESORCDAT(uValue) 
SELF:FieldPut(#DESORCDAT, uValue)
RETURN DESORCDAT := uValue


ACCESS DESORCREV() 
RETURN SELF:FieldGet(#DESORCREV)


ASSIGN DESORCREV(uValue) 
SELF:FieldPut(#DESORCREV, uValue)
RETURN DESORCREV := uValue


METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"DECLMOT.DBF"}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("DECLMOT",oESC:NUMERO)
ENDIF

ACCESS FDATA() 
RETURN SELF:FieldGet(#FDATA)


ASSIGN FDATA(uValue) 
SELF:FieldPut(#FDATA, uValue)
RETURN FDATA := uValue


ACCESS FOLLOWUP() 
RETURN SELF:FieldGet(#FOLLOWUP)


ASSIGN FOLLOWUP(uValue) 
SELF:FieldPut(#FOLLOWUP, uValue)
RETURN FOLLOWUP := uValue


ACCESS FVALORFER() 
RETURN SELF:FieldGet(#FVALORFER)


ASSIGN FVALORFER(uValue) 
SELF:FieldPut(#FVALORFER, uValue)
RETURN FVALORFER := uValue


ACCESS FVALORUNI() 
RETURN SELF:FieldGet(#FVALORUNI)


ASSIGN FVALORUNI(uValue) 
SELF:FieldPut(#FVALORUNI, uValue)
RETURN FVALORUNI := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JANVIA_Page4",_GetInst()},iCtlID)

oDCVALORFER := rightSle{SELF,ResourceID{JANVIA_PAGE4_VALORFER,_GetInst()}}
oDCVALORFER:HyperLabel := HyperLabel{#VALORFER,NULL_STRING,NULL_STRING,NULL_STRING}
oDCVALORFER:FieldSpec := padrao_num_12_2{}

oDCVALORUNI := rightSle{SELF,ResourceID{JANVIA_PAGE4_VALORUNI,_GetInst()}}
oDCVALORUNI:FieldSpec := padrao_num_12_4{}
oDCVALORUNI:HyperLabel := HyperLabel{#VALORUNI,NULL_STRING,NULL_STRING,NULL_STRING}

oDCFVALORFER := rightSle{SELF,ResourceID{JANVIA_PAGE4_FVALORFER,_GetInst()}}
oDCFVALORFER:HyperLabel := HyperLabel{#FVALORFER,NULL_STRING,NULL_STRING,NULL_STRING}
oDCFVALORFER:FieldSpec := PADRAO_NUM_12_2{}

oDCFVALORUNI := rightSle{SELF,ResourceID{JANVIA_PAGE4_FVALORUNI,_GetInst()}}
oDCFVALORUNI:FieldSpec := PADRAO_NUM_12_4{}
oDCFVALORUNI:HyperLabel := HyperLabel{#FVALORUNI,NULL_STRING,NULL_STRING,NULL_STRING}

oDCQTDENEG := rightSle{SELF,ResourceID{JANVIA_PAGE4_QTDENEG,_GetInst()}}
oDCQTDENEG:FieldSpec := PADRAO_NUM_08{}
oDCQTDENEG:HyperLabel := HyperLabel{#QTDENEG,NULL_STRING,NULL_STRING,NULL_STRING}

oDCFDATA := DateSle{SELF,ResourceID{JANVIA_PAGE4_FDATA,_GetInst()}}
oDCFDATA:FieldSpec := DATE_FIELD{}
oDCFDATA:HyperLabel := HyperLabel{#FDATA,NULL_STRING,NULL_STRING,NULL_STRING}

oDCORCAMENTO := rightSle{SELF,ResourceID{JANVIA_PAGE4_ORCAMENTO,_GetInst()}}
oDCORCAMENTO:FieldSpec := PADRAO_NUM_08{}
oDCORCAMENTO:HyperLabel := HyperLabel{#ORCAMENTO,"Recotação",NULL_STRING,NULL_STRING}

oDCITEM := rightSle{SELF,ResourceID{JANVIA_PAGE4_ITEM,_GetInst()}}
oDCITEM:FieldSpec := PADRAO_NUM_03{}
oDCITEM:HyperLabel := HyperLabel{#ITEM,NULL_STRING,NULL_STRING,NULL_STRING}

oDCtheFixedText16 := FixedText{SELF,ResourceID{JANVIA_PAGE4_THEFIXEDTEXT16,_GetInst()}}
oDCtheFixedText16:HyperLabel := HyperLabel{#theFixedText16,"Vl.Unidade",NULL_STRING,NULL_STRING}

oDCtheFixedText15 := FixedText{SELF,ResourceID{JANVIA_PAGE4_THEFIXEDTEXT15,_GetInst()}}
oDCtheFixedText15:HyperLabel := HyperLabel{#theFixedText15,"Vl.Ferramenta",NULL_STRING,NULL_STRING}

oCCcmdHoje1 := PushButton{SELF,ResourceID{JANVIA_PAGE4_CMDHOJE1,_GetInst()}}
oCCcmdHoje1:HyperLabel := HyperLabel{#cmdHoje1,"H",NULL_STRING,NULL_STRING}

oDCSC_CLIENTE2 := FixedText{SELF,ResourceID{JANVIA_PAGE4_SC_CLIENTE2,_GetInst()}}
oDCSC_CLIENTE2:HyperLabel := HyperLabel{#SC_CLIENTE2,"Data:",NULL_STRING,NULL_STRING}

oDCSC_CLIENTE1 := FixedText{SELF,ResourceID{JANVIA_PAGE4_SC_CLIENTE1,_GetInst()}}
oDCSC_CLIENTE1:HyperLabel := HyperLabel{#SC_CLIENTE1,"Qtde Neg.",NULL_STRING,NULL_STRING}

oDCtheFixedText18 := FixedText{SELF,ResourceID{JANVIA_PAGE4_THEFIXEDTEXT18,_GetInst()}}
oDCtheFixedText18:HyperLabel := HyperLabel{#theFixedText18,"Vl.Unidade",NULL_STRING,NULL_STRING}

oCCcopia := PushButton{SELF,ResourceID{JANVIA_PAGE4_COPIA,_GetInst()}}
oCCcopia:HyperLabel := HyperLabel{#copia,"Copia",NULL_STRING,NULL_STRING}

oDCtheFixedText19 := FixedText{SELF,ResourceID{JANVIA_PAGE4_THEFIXEDTEXT19,_GetInst()}}
oDCtheFixedText19:HyperLabel := HyperLabel{#theFixedText19,"Vl.Ferramenta",NULL_STRING,NULL_STRING}

oCCdesmarcar := PushButton{SELF,ResourceID{JANVIA_PAGE4_DESMARCAR,_GetInst()}}
oCCdesmarcar:HyperLabel := HyperLabel{#desmarcar,"Desmarcar",NULL_STRING,NULL_STRING}

oCCRadioButton7 := RadioButton{SELF,ResourceID{JANVIA_PAGE4_RADIOBUTTON7,_GetInst()}}
oCCRadioButton7:HyperLabel := HyperLabel{#RadioButton7,"Recotação",NULL_STRING,NULL_STRING}

oCCRaB28 := RadioButton{SELF,ResourceID{JANVIA_PAGE4_RAB28,_GetInst()}}
oCCRaB28:HyperLabel := HyperLabel{#RaB28,"Reprovado",NULL_STRING,NULL_STRING}

oCCRadioButton6 := RadioButton{SELF,ResourceID{JANVIA_PAGE4_RADIOBUTTON6,_GetInst()}}
oCCRadioButton6:HyperLabel := HyperLabel{#RadioButton6,"Excluida",NULL_STRING,NULL_STRING}

oCCRB28 := RadioButton{SELF,ResourceID{JANVIA_PAGE4_RB28,_GetInst()}}
oCCRB28:HyperLabel := HyperLabel{#RB28,"Aprovado",NULL_STRING,NULL_STRING}

oDCtheFixedText20 := FixedText{SELF,ResourceID{JANVIA_PAGE4_THEFIXEDTEXT20,_GetInst()}}
oDCtheFixedText20:HyperLabel := HyperLabel{#theFixedText20,"Item",NULL_STRING,NULL_STRING}

oDCtheFixedText17 := FixedText{SELF,ResourceID{JANVIA_PAGE4_THEFIXEDTEXT17,_GetInst()}}
oDCtheFixedText17:HyperLabel := HyperLabel{#theFixedText17,"Orçamento",NULL_STRING,NULL_STRING}

oDCOBSCLI := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE4_OBSCLI,_GetInst()}}
oDCOBSCLI:FieldSpec := padrao_char_50{}
oDCOBSCLI:HyperLabel := HyperLabel{#OBSCLI,"Obsg01:",NULL_STRING,"VIABILI_OBSG01"}
oDCOBSCLI:TooltipText := "Observação para Vendas"

oDCtheFixedText14 := FixedText{SELF,ResourceID{JANVIA_PAGE4_THEFIXEDTEXT14,_GetInst()}}
oDCtheFixedText14:HyperLabel := HyperLabel{#theFixedText14,"Status Cliente",NULL_STRING,NULL_STRING}

oDCDESORCDAT := DateSle{SELF,ResourceID{JANVIA_PAGE4_DESORCDAT,_GetInst()}}
oDCDESORCDAT:FieldSpec := DATE_FIELD{}
oDCDESORCDAT:HyperLabel := HyperLabel{#DESORCDAT,"Data",NULL_STRING,"CDI_REV"}

oDCSC_REV1 := FixedText{SELF,ResourceID{JANVIA_PAGE4_SC_REV1,_GetInst()}}
oDCSC_REV1:HyperLabel := HyperLabel{#SC_REV1,"Data",NULL_STRING,NULL_STRING}

oDCDESORCREV := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE4_DESORCREV,_GetInst()}}
oDCDESORCREV:FieldSpec := padrao_char_20{}
oDCDESORCREV:HyperLabel := HyperLabel{#DESORCREV,"Rev:",NULL_STRING,"CDI_REV"}

oDCSC_REV := FixedText{SELF,ResourceID{JANVIA_PAGE4_SC_REV,_GetInst()}}
oDCSC_REV:HyperLabel := HyperLabel{#SC_REV,"Rev:",NULL_STRING,NULL_STRING}

oDCDESORC := SingleLineEdit{SELF,ResourceID{JANVIA_PAGE4_DESORC,_GetInst()}}
oDCDESORC:FieldSpec := padrao_char_24{}
oDCDESORC:HyperLabel := HyperLabel{#DESORC,"Desenho:",NULL_STRING,"CDI_DESENHO"}

oDCSC_DESENHO := FixedText{SELF,ResourceID{JANVIA_PAGE4_SC_DESENHO,_GetInst()}}
oDCSC_DESENHO:HyperLabel := HyperLabel{#SC_DESENHO,"Desenho:",NULL_STRING,NULL_STRING}

oDCCANCELADO := CheckBox{SELF,ResourceID{JANVIA_PAGE4_CANCELADO,_GetInst()}}
oDCCANCELADO:HyperLabel := HyperLabel{#CANCELADO,"Cancelado",NULL_STRING,NULL_STRING}
oDCCANCELADO:FieldSpec := LOGIC_FIELD{}

oDCDECLINADO := CheckBox{SELF,ResourceID{JANVIA_PAGE4_DECLINADO,_GetInst()}}
oDCDECLINADO:HyperLabel := HyperLabel{#DECLINADO,"Declinado",NULL_STRING,NULL_STRING}
oDCDECLINADO:FieldSpec := LOGIC_FIELD{}

oDCFOLLOWUP := CheckBox{SELF,ResourceID{JANVIA_PAGE4_FOLLOWUP,_GetInst()}}
oDCFOLLOWUP:HyperLabel := HyperLabel{#FOLLOWUP,"FollowUP",NULL_STRING,NULL_STRING}
oDCFOLLOWUP:FieldSpec := LOGIC_FIELD{}

oDCDECLMOT := rightSle{SELF,ResourceID{JANVIA_PAGE4_DECLMOT,_GetInst()}}
oDCDECLMOT:FieldSpec := PADRAO_NUM_03{}
oDCDECLMOT:HyperLabel := HyperLabel{#DECLMOT,"Recotação",NULL_STRING,NULL_STRING}

oCCescfor := PushButton{SELF,ResourceID{JANVIA_PAGE4_ESCFOR,_GetInst()}}
oCCescfor:HyperLabel := HyperLabel{#escfor,"...",NULL_STRING,NULL_STRING}

oDCSITUACAO := RadioButtonGroup{SELF,ResourceID{JANVIA_PAGE4_SITUACAO,_GetInst()}}
oDCSITUACAO:FillUsing({ ;
						{oCCRadioButton7,"E"}, ;
						{oCCRaB28,"R"}, ;
						{oCCRadioButton6,"X"}, ;
						{oCCRB28,"A"} ;
						})
oDCSITUACAO:HyperLabel := HyperLabel{#SITUACAO,"Fechamento no Cliente",NULL_STRING,NULL_STRING}
oDCSITUACAO:FieldSpec := PADRAO_CHAR_01{}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#JANVIA_Page4,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS ITEM() 
RETURN SELF:FieldGet(#ITEM)


ASSIGN ITEM(uValue) 
SELF:FieldPut(#ITEM, uValue)
RETURN ITEM := uValue


ACCESS OBSCLI() 
RETURN SELF:FieldGet(#OBSCLI)


ASSIGN OBSCLI(uValue) 
SELF:FieldPut(#OBSCLI, uValue)
RETURN OBSCLI := uValue


ACCESS ORCAMENTO() 
RETURN SELF:FieldGet(#ORCAMENTO)


ASSIGN ORCAMENTO(uValue) 
SELF:FieldPut(#ORCAMENTO, uValue)
RETURN ORCAMENTO := uValue


ACCESS QTDENEG() 
RETURN SELF:FieldGet(#QTDENEG)


ASSIGN QTDENEG(uValue) 
SELF:FieldPut(#QTDENEG, uValue)
RETURN QTDENEG := uValue


ACCESS SITUACAO() 
RETURN SELF:FieldGet(#SITUACAO)


ASSIGN SITUACAO(uValue) 
SELF:FieldPut(#SITUACAO, uValue)
RETURN SITUACAO := uValue


ACCESS VALORFER() 
RETURN SELF:FieldGet(#VALORFER)


ASSIGN VALORFER(uValue) 
SELF:FieldPut(#VALORFER, uValue)
RETURN VALORFER := uValue


ACCESS VALORUNI() 
RETURN SELF:FieldGet(#VALORUNI)


ASSIGN VALORUNI(uValue) 
SELF:FieldPut(#VALORUNI, uValue)
RETURN VALORUNI := uValue


END CLASS
PARTIAL CLASS JANVIA_Pagea INHERIT DATAWINDOW 

	PROTECT oDCEAC AS SINGLELINEEDIT
	PROTECT oDCENVELOPE AS SINGLELINEEDIT
	PROTECT oDCDUNS AS SINGLELINEEDIT
	PROTECT oDCPROJETO AS SINGLELINEEDIT
	PROTECT oDCNORMAT AS SINGLELINEEDIT
	PROTECT oDCLOTEMIN AS SINGLELINEEDIT
	PROTECT oDCSC_DESENHO4 AS FIXEDTEXT
	PROTECT oDCQTEDANO AS SINGLELINEEDIT
	PROTECT oDCSC_DESENHO3 AS FIXEDTEXT
	PROTECT oDCCOT04 AS CHECKBOX
	PROTECT oDCCOT02 AS CHECKBOX
	PROTECT oDCCOT03 AS CHECKBOX
	PROTECT oDCCOT01 AS CHECKBOX
	PROTECT oDCtheGroupBox1 AS GROUPBOX
	PROTECT oDCSC_EAC AS FIXEDTEXT
	PROTECT oDCSC_NORMAT AS FIXEDTEXT
	PROTECT oDCSC_EAC1 AS FIXEDTEXT
	PROTECT oDCSC_EAC2 AS FIXEDTEXT
	PROTECT oDCAM AS SINGLELINEEDIT
	PROTECT oCCcmdAM AS PUSHBUTTON
	PROTECT oDCSC_EAC3 AS FIXEDTEXT
	PROTECT oDCSC_EAC4 AS FIXEDTEXT
	PROTECT oDCPR AS SINGLELINEEDIT
	PROTECT oCCCMDPR AS PUSHBUTTON
	PROTECT oDCTIPOVIA AS SINGLELINEEDIT
	PROTECT oDCSC_EAC5 AS FIXEDTEXT
	PROTECT oCCcmdtipo AS PUSHBUTTON
	PROTECT oDCCOT06 AS CHECKBOX
	PROTECT oDCCOT05 AS CHECKBOX
	PROTECT oCCcmdcodesf AS PUSHBUTTON
	PROTECT oDCCOT07 AS CHECKBOX
	PROTECT oDCSC_REV2 AS FIXEDTEXT
	PROTECT oCCcmdAM1 AS PUSHBUTTON
	PROTECT oDCGI AS SINGLELINEEDIT
	PROTECT oDCSC_EAC6 AS FIXEDTEXT
	PROTECT oCCcmdAM2 AS PUSHBUTTON
	PROTECT oDCSC_EAC7 AS FIXEDTEXT
	PROTECT oDCSEGMENTO AS SINGLELINEEDIT
	PROTECT oCCcmdAM3 AS PUSHBUTTON
	PROTECT oCCcmdAM4 AS PUSHBUTTON
// 	instance EAC 
// 	instance ENVELOPE 
// 	instance DUNS 
// 	instance PROJETO 
// 	instance NORMAT 
// 	instance LOTEMIN 
// 	instance QTEDANO 
// 	instance COT04 
// 	instance COT02 
// 	instance COT03 
// 	instance COT01 
// 	instance AM 
// 	instance PR 
// 	instance TIPOVIA 
// 	instance COT06 
// 	instance COT05 
// 	instance COT07 
// 	instance GI 
// 	instance SEGMENTO 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS AM() 
RETURN SELF:FieldGet(#AM)


ASSIGN AM(uValue) 
SELF:FieldPut(#AM, uValue)
RETURN AM := uValue


METHOD cmdAM1( ) 
	SELF:server:FIELDPUT("GI",SIMNAO(SELF:SERVER:FIELDGET("GI"),{"A","B","C"}))		

METHOD cmdAM2( ) 
	SELF:server:FIELDPUT("SEGMENTO","LA")

METHOD cmdAM3( ) 
		SELF:server:FIELDPUT("SEGMENTO","LB")

METHOD cmdAM4( ) 
		SELF:server:FIELDPUT("SEGMENTO","2R")

ACCESS COT01() 
RETURN SELF:FieldGet(#COT01)


ASSIGN COT01(uValue) 
SELF:FieldPut(#COT01, uValue)
RETURN COT01 := uValue


ACCESS COT02() 
RETURN SELF:FieldGet(#COT02)


ASSIGN COT02(uValue) 
SELF:FieldPut(#COT02, uValue)
RETURN COT02 := uValue


ACCESS COT03() 
RETURN SELF:FieldGet(#COT03)


ASSIGN COT03(uValue) 
SELF:FieldPut(#COT03, uValue)
RETURN COT03 := uValue


ACCESS COT04() 
RETURN SELF:FieldGet(#COT04)


ASSIGN COT04(uValue) 
SELF:FieldPut(#COT04, uValue)
RETURN COT04 := uValue


ACCESS COT05() 
RETURN SELF:FieldGet(#COT05)


ASSIGN COT05(uValue) 
SELF:FieldPut(#COT05, uValue)
RETURN COT05 := uValue


ACCESS COT06() 
RETURN SELF:FieldGet(#COT06)


ASSIGN COT06(uValue) 
SELF:FieldPut(#COT06, uValue)
RETURN COT06 := uValue


ACCESS COT07() 
RETURN SELF:FieldGet(#COT07)


ASSIGN COT07(uValue) 
SELF:FieldPut(#COT07, uValue)
RETURN COT07 := uValue


ACCESS DUNS() 
RETURN SELF:FieldGet(#DUNS)


ASSIGN DUNS(uValue) 
SELF:FieldPut(#DUNS, uValue)
RETURN DUNS := uValue


ACCESS EAC() 
RETURN SELF:FieldGet(#EAC)


ASSIGN EAC(uValue) 
SELF:FieldPut(#EAC, uValue)
RETURN EAC := uValue


ACCESS ENVELOPE() 
RETURN SELF:FieldGet(#ENVELOPE)


ASSIGN ENVELOPE(uValue) 
SELF:FieldPut(#ENVELOPE, uValue)
RETURN ENVELOPE := uValue


ACCESS GI() 
RETURN SELF:FieldGet(#GI)


ASSIGN GI(uValue) 
SELF:FieldPut(#GI, uValue)
RETURN GI := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[4] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JANVIA_Pagea",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Times New Roman"}
aFonts[1]:Bold := TRUE
aFonts[2] := Font{,12,"Times New Roman"}
aFonts[3] := Font{,12,"Times New Roman"}
aFonts[3]:Bold := TRUE
aFonts[4] := Font{,12,"Times New Roman"}
aFonts[4]:Bold := TRUE
aFonts[4]:Italic := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCEAC := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_EAC,_GetInst()}}
oDCEAC:FieldSpec := PADRAO_CHAR_35{}
oDCEAC:HyperLabel := HyperLabel{#EAC,"Eac:",NULL_STRING,"VIABILI_EAC"}

oDCENVELOPE := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_ENVELOPE,_GetInst()}}
oDCENVELOPE:FieldSpec := padrao_char_05{}
oDCENVELOPE:HyperLabel := HyperLabel{#ENVELOPE,"Rev:",NULL_STRING,"CDI_REV"}

oDCDUNS := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_DUNS,_GetInst()}}
oDCDUNS:FieldSpec := PADRAO_CHAR_30{}
oDCDUNS:HyperLabel := HyperLabel{#DUNS,"Eac:",NULL_STRING,"VIABILI_EAC"}

oDCPROJETO := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_PROJETO,_GetInst()}}
oDCPROJETO:FieldSpec := PADRAO_CHAR_20{}
oDCPROJETO:HyperLabel := HyperLabel{#PROJETO,"Normat:",NULL_STRING,"VIABILI_NORMAT"}

oDCNORMAT := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_NORMAT,_GetInst()}}
oDCNORMAT:FieldSpec := PADRAO_CHAR_10{}
oDCNORMAT:HyperLabel := HyperLabel{#NORMAT,"Normat:",NULL_STRING,"VIABILI_NORMAT"}

oDCLOTEMIN := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_LOTEMIN,_GetInst()}}
oDCLOTEMIN:FieldSpec := PADRAO_NUM_08{}
oDCLOTEMIN:HyperLabel := HyperLabel{#LOTEMIN,NULL_STRING,NULL_STRING,NULL_STRING}
oDCLOTEMIN:BackGround := aBrushes[1]
oDCLOTEMIN:Font(aFonts[1], FALSE)

oDCSC_DESENHO4 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_DESENHO4,_GetInst()}}
oDCSC_DESENHO4:HyperLabel := HyperLabel{#SC_DESENHO4,"Lote Minimo",NULL_STRING,NULL_STRING}

oDCQTEDANO := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_QTEDANO,_GetInst()}}
oDCQTEDANO:FieldSpec := PADRAO_NUM_08{}
oDCQTEDANO:HyperLabel := HyperLabel{#QTEDANO,NULL_STRING,NULL_STRING,NULL_STRING}
oDCQTEDANO:BackGround := aBrushes[1]
oDCQTEDANO:Font(aFonts[1], FALSE)

oDCSC_DESENHO3 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_DESENHO3,_GetInst()}}
oDCSC_DESENHO3:HyperLabel := HyperLabel{#SC_DESENHO3,"Quantidade Anual",NULL_STRING,NULL_STRING}

oDCCOT04 := CheckBox{SELF,ResourceID{JANVIA_PAGEA_COT04,_GetInst()}}
oDCCOT04:HyperLabel := HyperLabel{#COT04,"Somente Mâo de Obra",NULL_STRING,NULL_STRING}
oDCCOT04:FieldSpec := LOGIC_FIELD{}

oDCCOT02 := CheckBox{SELF,ResourceID{JANVIA_PAGEA_COT02,_GetInst()}}
oDCCOT02:HyperLabel := HyperLabel{#COT02,"Peça",NULL_STRING,NULL_STRING}
oDCCOT02:FieldSpec := LOGIC_FIELD{}

oDCCOT03 := CheckBox{SELF,ResourceID{JANVIA_PAGEA_COT03,_GetInst()}}
oDCCOT03:HyperLabel := HyperLabel{#COT03,"Material e Mão de Obra",NULL_STRING,NULL_STRING}
oDCCOT03:FieldSpec := LOGIC_FIELD{}

oDCCOT01 := CheckBox{SELF,ResourceID{JANVIA_PAGEA_COT01,_GetInst()}}
oDCCOT01:HyperLabel := HyperLabel{#COT01,"Peça e Ferramental",NULL_STRING,NULL_STRING}
oDCCOT01:FieldSpec := LOGIC_FIELD{}

oDCtheGroupBox1 := GroupBox{SELF,ResourceID{JANVIA_PAGEA_THEGROUPBOX1,_GetInst()}}
oDCtheGroupBox1:HyperLabel := HyperLabel{#theGroupBox1,"Cotar",NULL_STRING,NULL_STRING}

oDCSC_EAC := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_EAC,_GetInst()}}
oDCSC_EAC:HyperLabel := HyperLabel{#SC_EAC,"Estimativa Anual",NULL_STRING,NULL_STRING}

oDCSC_NORMAT := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_NORMAT,_GetInst()}}
oDCSC_NORMAT:HyperLabel := HyperLabel{#SC_NORMAT,"Norma",NULL_STRING,NULL_STRING}

oDCSC_EAC1 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_EAC1,_GetInst()}}
oDCSC_EAC1:HyperLabel := HyperLabel{#SC_EAC1,"Duns",NULL_STRING,NULL_STRING}

oDCSC_EAC2 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_EAC2,_GetInst()}}
oDCSC_EAC2:HyperLabel := HyperLabel{#SC_EAC2,"Projeto",NULL_STRING,NULL_STRING}

oDCAM := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_AM,_GetInst()}}
oDCAM:FieldSpec := PADRAO_CHAR_01{}
oDCAM:HyperLabel := HyperLabel{#AM,"Eac:",NULL_STRING,"VIABILI_EAC"}
oDCAM:BackGround := aBrushes[1]
oDCAM:Font(aFonts[2], FALSE)

oCCcmdAM := PushButton{SELF,ResourceID{JANVIA_PAGEA_CMDAM,_GetInst()}}
oCCcmdAM:HyperLabel := HyperLabel{#cmdAM,"Sim/Nao",NULL_STRING,NULL_STRING}

oDCSC_EAC3 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_EAC3,_GetInst()}}
oDCSC_EAC3:HyperLabel := HyperLabel{#SC_EAC3,"Amostra",NULL_STRING,NULL_STRING}

oDCSC_EAC4 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_EAC4,_GetInst()}}
oDCSC_EAC4:HyperLabel := HyperLabel{#SC_EAC4,"Produto",NULL_STRING,NULL_STRING}

oDCPR := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_PR,_GetInst()}}
oDCPR:FieldSpec := PADRAO_CHAR_01{}
oDCPR:HyperLabel := HyperLabel{#PR,"Eac:",NULL_STRING,"VIABILI_EAC"}
oDCPR:BackGround := aBrushes[1]
oDCPR:Font(aFonts[3], FALSE)

oCCCMDPR := PushButton{SELF,ResourceID{JANVIA_PAGEA_CMDPR,_GetInst()}}
oCCCMDPR:HyperLabel := HyperLabel{#CMDPR,"(N)ovo Mod.F(E)rramenta Mod(P)roduto p(R)ototipo",NULL_STRING,NULL_STRING}

oDCTIPOVIA := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_TIPOVIA,_GetInst()}}
oDCTIPOVIA:FieldSpec := PADRAO_CHAR_01{}
oDCTIPOVIA:HyperLabel := HyperLabel{#TIPOVIA,"Eac:",NULL_STRING,"VIABILI_EAC"}
oDCTIPOVIA:BackGround := aBrushes[1]
oDCTIPOVIA:Font(aFonts[4], FALSE)

oDCSC_EAC5 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_EAC5,_GetInst()}}
oDCSC_EAC5:HyperLabel := HyperLabel{#SC_EAC5,"Considerar Apuraçao Relatorios",NULL_STRING,NULL_STRING}

oCCcmdtipo := PushButton{SELF,ResourceID{JANVIA_PAGEA_CMDTIPO,_GetInst()}}
oCCcmdtipo:HyperLabel := HyperLabel{#cmdtipo,"Sim/Nao",NULL_STRING,NULL_STRING}

oDCCOT06 := CheckBox{SELF,ResourceID{JANVIA_PAGEA_COT06,_GetInst()}}
oDCCOT06:HyperLabel := HyperLabel{#COT06,"Prototipo",NULL_STRING,NULL_STRING}
oDCCOT06:FieldSpec := LOGIC_FIELD{}

oDCCOT05 := CheckBox{SELF,ResourceID{JANVIA_PAGEA_COT05,_GetInst()}}
oDCCOT05:HyperLabel := HyperLabel{#COT05,"Prototipo e Ferramental",NULL_STRING,NULL_STRING}
oDCCOT05:FieldSpec := LOGIC_FIELD{}

oCCcmdcodesf := PushButton{SELF,ResourceID{JANVIA_PAGEA_CMDCODESF,_GetInst()}}
oCCcmdcodesf:HyperLabel := HyperLabel{#cmdcodesf,"Verificar Codigo Produto na Estimativa",NULL_STRING,NULL_STRING}

oDCCOT07 := CheckBox{SELF,ResourceID{JANVIA_PAGEA_COT07,_GetInst()}}
oDCCOT07:HyperLabel := HyperLabel{#COT07,"Embalagem",NULL_STRING,NULL_STRING}
oDCCOT07:FieldSpec := LOGIC_FIELD{}

oDCSC_REV2 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_REV2,_GetInst()}}
oDCSC_REV2:HyperLabel := HyperLabel{#SC_REV2,"Envelope",NULL_STRING,NULL_STRING}

oCCcmdAM1 := PushButton{SELF,ResourceID{JANVIA_PAGEA_CMDAM1,_GetInst()}}
oCCcmdAM1:HyperLabel := HyperLabel{#cmdAM1,"ABC",NULL_STRING,NULL_STRING}

oDCGI := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_GI,_GetInst()}}
oDCGI:FieldSpec := PADRAO_CHAR_01{}
oDCGI:HyperLabel := HyperLabel{#GI,"Eac:",NULL_STRING,"VIABILI_EAC"}
oDCGI:BackGround := aBrushes[1]
oDCGI:Font(aFonts[2], FALSE)

oDCSC_EAC6 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_EAC6,_GetInst()}}
oDCSC_EAC6:HyperLabel := HyperLabel{#SC_EAC6,"GrauInteresse",NULL_STRING,NULL_STRING}

oCCcmdAM2 := PushButton{SELF,ResourceID{JANVIA_PAGEA_CMDAM2,_GetInst()}}
oCCcmdAM2:HyperLabel := HyperLabel{#cmdAM2,"LA",NULL_STRING,NULL_STRING}

oDCSC_EAC7 := FixedText{SELF,ResourceID{JANVIA_PAGEA_SC_EAC7,_GetInst()}}
oDCSC_EAC7:HyperLabel := HyperLabel{#SC_EAC7,"Segmento",NULL_STRING,NULL_STRING}

oDCSEGMENTO := SingleLineEdit{SELF,ResourceID{JANVIA_PAGEA_SEGMENTO,_GetInst()}}
oDCSEGMENTO:FieldSpec := PADRAO_CHAR_02{}
oDCSEGMENTO:HyperLabel := HyperLabel{#SEGMENTO,"Eac:",NULL_STRING,"VIABILI_EAC"}
oDCSEGMENTO:BackGround := aBrushes[1]
oDCSEGMENTO:Font(aFonts[2], FALSE)

oCCcmdAM3 := PushButton{SELF,ResourceID{JANVIA_PAGEA_CMDAM3,_GetInst()}}
oCCcmdAM3:HyperLabel := HyperLabel{#cmdAM3,"LB",NULL_STRING,NULL_STRING}

oCCcmdAM4 := PushButton{SELF,ResourceID{JANVIA_PAGEA_CMDAM4,_GetInst()}}
oCCcmdAM4:HyperLabel := HyperLabel{#cmdAM4,"2R",NULL_STRING,NULL_STRING}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#JANVIA_Pagea,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS LOTEMIN() 
RETURN SELF:FieldGet(#LOTEMIN)


ASSIGN LOTEMIN(uValue) 
SELF:FieldPut(#LOTEMIN, uValue)
RETURN LOTEMIN := uValue


ACCESS NORMAT() 
RETURN SELF:FieldGet(#NORMAT)


ASSIGN NORMAT(uValue) 
SELF:FieldPut(#NORMAT, uValue)
RETURN NORMAT := uValue


ACCESS PR() 
RETURN SELF:FieldGet(#PR)


ASSIGN PR(uValue) 
SELF:FieldPut(#PR, uValue)
RETURN PR := uValue


ACCESS PROJETO() 
RETURN SELF:FieldGet(#PROJETO)


ASSIGN PROJETO(uValue) 
SELF:FieldPut(#PROJETO, uValue)
RETURN PROJETO := uValue


ACCESS QTEDANO() 
RETURN SELF:FieldGet(#QTEDANO)


ASSIGN QTEDANO(uValue) 
SELF:FieldPut(#QTEDANO, uValue)
RETURN QTEDANO := uValue


ACCESS SEGMENTO() 
RETURN SELF:FieldGet(#SEGMENTO)


ASSIGN SEGMENTO(uValue) 
SELF:FieldPut(#SEGMENTO, uValue)
RETURN SEGMENTO := uValue


ACCESS TIPOVIA() 
RETURN SELF:FieldGet(#TIPOVIA)


ASSIGN TIPOVIA(uValue) 
SELF:FieldPut(#TIPOVIA, uValue)
RETURN TIPOVIA := uValue


END CLASS
STATIC DEFINE JANVIA_BTNPEGMA01 := 138
