CLASS XJANVIA INHERIT JANVIA

METHOD APPEND() 
LOCAL nOV AS DWORD
LOCAL aERRO AS ARRAY
LOCAL oBUSCA AS xBUSCA
LOCAL aGMFI AS ARRAY
oBUSCA:=XBUSCA{SELF,"Incluir Viabilidade","Digite O Codigo do Desenho"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETURN .F.	
ENDIF
SELF:server:setorder(2)
SELF:SERVER:GOTOP()
IF SELF:SERVER:SEEK(oBUSCA:cBUSCA)
   WHILE AllTrim(SELF:SERVER:FIELDGET("DESENHO"))=AllTrim(oBUSCA:cBUSCA) .and. ! SELF:server:Eof
   	   SELF:server:skip()
   ENDDO
   SELF:SERVER:SKIP(-1)
   alert("Desenho Ja cadastrado")
   RETURN .F.	
ENDIF	

aGMFI:=PEGGMFI(oBUSCA:cBUSCA)


SELF:server:setorder(1)
SELF:server:gobottom()
nOV:=SELF:Server:OV
nOV++
SUPER:append()
SELF:SERVER:FIELDPUT("OV",nOV)
SELF:SERVER:FIELDPUT("DATAS",ZDATA)
SELF:SERVER:FIELDPUT("DATAV",ZDATA)
SELF:SERVER:FIELDPUT("INCUSER",ZUSER)
SELF:SERVER:FIELDPUT("INCDATA",Today())
SELF:SERVER:FIELDPUT("INCHORA",Time())
SELF:SERVER:FIELDPUT("DESENHO",AllTrim(oBUSCA:cBUSCA))
SELF:SERVER:FIELDPUT("PECA",AllTrim(oBUSCA:cBUSCA))
SELF:server:FIELDPUT("TIPOVIA","S")
IF aGMFI[1]
   SELF:SERVER:FIELDPUT("DENOMINA",aGMFI[2])
ELSE
   SELF:SERVER:FIELDPUT("DENOMINA",AllTrim(oBUSCA:cBUSCA))
ENDIF	
GRAVALOG(Str(SELF:SERVER:OV),"INC","VIABILI")	
aERRO:={}
AAdd(aERRO," Viabilidade No:"+StrTRIM(SELF:server:FIELDGET("OV"),8,0))
AAdd(aERRO,"Aberta: "+DToC(Today()))
AAdd(aERRO,"Desenho:"+SELF:server:FIELDGET("DESENHO"))
EMAILINT("VIA00001",ZUSER,aERRO,ZCURINI,zCURDIR)	
SELF:novo("I","Abertura Nova OP")
RETURN .T.

METHOD Buscaov() 
SELF:KeyFind()

METHOD chkclipro( ) 
LOCAL aCLI AS ARRAY
LOCAL OPROGWIN AS PROGWIN
alert("Operacao Pode Demorar conf Qtde CD")	
oPROGWIN:=PROGWIN{SELF}
oPROGWIN:SHOW()	
oPROGWIN:NTOTAL:=SELF:SERVER:RECCOUNT
oPROGWIN:reset()
SELF:oSFJVIAREV:SERVER:SUSPENDNOTIFICATION()
SELF:SERVER:GOTOP()
WHILE ! SELF:SERVER:EOF
	oPROGWIN:TITULO(Str(OV,8),.T.)
   IF Empty(SELF:SERVER:FIELDGET("CLINOME")) //.OR.Empty(SELF:SERVER:FIELDGET("CLICOGN"))	
      aCLI:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
      IF aCLI[1]=.T.
         SELF:SERVER:CLINOME:=aCLI[2]
      ENDIF	
   ENDIF
   IF Empty(SELF:SERVER:FIELDGET("DENOMINA")) .OR. Val(SELF:SERVER:FIELDGET("CODIGOINT"))=0		
      SELF:PEGMS01()
   ENDIF
   SELF:SERVER:SKIP()
   oPROGWIN:SKIP(1)
ENDDO	
SELF:SERVER:GOTOP()
SELF:oSFJVIAREV:SERVER:resetnotification()
oPROGWIN:EndDialog()
alert("Checagem Concluida")


METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDHOJE 
	SELF:SERVER:DATAEC:=Today()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("V1","VIA")	


METHOD CONDICIONAL 
LOCAL aERRO AS ARRAY
LOCAL cTIPO,cDADO AS STRING
IF SELF:oSFJVIII:server:APROVACAO="S"
   SELF:oSFJVIII:server:APROVACAO:="N"
ELSE
   SELF:oSFJVIII:server:FIELDPUT("APROVACAO","S")
   SELF:oSFJVIII:server:FIELDPUT("APRUSER",ZUSER)
   SELF:oSFJVIII:server:FIELDPUT("APRDATA",Today())
   SELF:oSFJVIII:server:FIELDPUT("APRTIME",Time())
   aERRO:={}
   cTIPO:=SELF:oSFJVIII:SERVER:FIELDGET("TIPO")
   cDADO:=SELF:oSFJVIII:SERVER:FIELDGET("APROBS")
   AAdd(aERRO," Viabilidade No:"+StrTRIM(SELF:server:FIELDGET("OV"),8,0))
   DO CASE
      CASE cTIPO="D"
   	       AAdd(aERRO,"Desenho: "+cDADO)
   	       EMAILINT("VIA00002",ZUSER,aERRO,ZCURINI,zCURDIR)	
      CASE cTIPO="N"
   	       AAdd(aERRO,"Norma: "+cDADO)
   	       EMAILINT("VIA00002",ZUSER,aERRO,ZCURINI,zCURDIR)	
   ENDCASE	
ENDIF



METHOD DELETE() 
LOCAL aERRO AS ARRAY	
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	RETU SELF
ENDIF	
GRAVALOG(SELF:SERVER:OV,"DEL","VIABILI")	
SELF:server:delete()
SELF:server:unlock()
SELF:server:skipEX(-1)
aERRO:={}
AAdd(aERRO," Viabilidade No:"+StrTRIM(SELF:server:FIELDGET("OV"),8,0))
AAdd(aERRO,"Apagada: "+DToC(Today()))
EMAILINT("VIA00003",ZUSER,aERRO,ZCURINI,zCURDIR)	



METHOD Duplicar( ) 
	SELF:xduplicar(0)

METHOD editar() 
SELF:oSFJVIII:VIEWform()		
	
	

METHOD Editar1( ) 
	SELF:oSFJVIAREV:VIEWform()		

METHOD EMAIL 
LOCAL aERRO AS ARRAY
LOCAL cTIPO,cDADO,cDAD2 AS STRING
   aERRO:={}
   cTIPO:=SELF:oSFJVIII:SERVER:FIELDGET("TIPO")
   cDADO:=SELF:oSFJVIII:SERVER:FIELDGET("APROBS")
   cDAD2:=SELF:oSFJVIII:SERVER:FIELDGET("DADO")
   AAdd(aERRO," Viabilidade No:"+StrTRIM(SELF:server:FIELDGET("OV"),8,0))
   DO CASE
      CASE cTIPO="D"
   	       AAdd(aERRO,"Desenho: "+cDADO)
      CASE cTIPO="N"
   	       AAdd(aERRO,"Norma: "+cDADO)
   ENDCASE	
   AAdd(aERRO,cDAD2)
   EMAILINT("VIA00004",ZUSER,aERRO,ZCURINI,zCURDIR)	




METHOD EMAILVCT 
LOCAL aERRO AS ARRAY	
aERRO:={}
AAdd(aERRO," Viabilidade No:"+StrTRIM(SELF:server:FIELDGET("OV"),8,0))
AAdd(aERRO,"Aberta: "+DToC(SELF:SERVER:FIELDGET("DATAV")))
EMAILINT("VIA00005",ZUSER,aERRO,ZCURINI,zCURDIR)	


METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DENOMINA",oESC:NOME)
ENDIF				

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
    SELF:btnPEGMA01()
ENDIF

METHOD FECCODIGO() 
LOCAL nRECNO AS DWORD
LOCAL cCODIGO AS STRING
nRECNO:=SELF:SERVER:RECNO	
cCODIGO:=SELF:SERVER:FIELDGET("DESENHO")
SELF:SERVER:SETORDER(2)
SELF:SERVER:GOTOP()
SELF:SERVER:SEEK(cCODIGO)
WHILE cCODIGO=SELF:SERVER:FIELDGET("DESENHO") .AND. ! SELF:SERVER:EOF
   IF MDG("Fechar Tambem Viabilidade:"+Str(SELF:SERVER:FIELDGET("OV"))+" "+cCODIGO)
  	  IF TRANSFER(SELF:SERVER:FIELDGET("OV"))
         SELF:NOVO("F","Fechamento Viabilidade")	
      ENDIF
   ENDIF
   SELF:SERVER:Skip()
ENDDO
SELF:SERVER:GOTO(nRECNO)

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("PECA"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .F.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()	

CONSTRUCTOR(oOWNER) 	
LOCAL oSERVER,oSERVE2,oSERVE3 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("VIA",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"VIABILI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"VIABIII.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"VIAREV.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
	oSERVE2:CLOSE()
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
oSERVE2:SetOrder(2)
oSERVE2:SetFilter("TIPO<>'C'")
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)

SELF:OSFJVIII:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJVIII,"OV")
SELF:OSFJVIII:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJVIII:ViewTable()	

SELF:OSFJVIAREV:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJVIAREV,"OV")
SELF:oSFJVIAREV:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJVIAREV:ViewTable()	
SELF:SHOW()

METHOD ListBoxSelect( oControlEvent ) 
	LOCAL oControl AS Control
	LOCAL aCOM AS ARRAY
	oControl := IIf( oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control )
	SUPER:ListBoxSelect( oControlEvent )
	//Put your changes here
        DO CASE
	       CASE oCONTROL:NAMESYM==#COMPRADOR
                             aCOM:=PEGMC(SELF:SERVER:COMPRADOR,"MC02.DBF")
                             IF aCOM[1]=.T.
                                  SELF:SERVER:COMCOMP:=aCOM[2]
                             ENDIF
        ENDCASE
RETURN NIL


METHOD novarev( ) 
LOCAL cDIGCTR AS STRING
LOCAL nDIGCTR AS DWORD
LOCAL nOVOLD AS DWORD
IF ! MDG("Abrir Nova Revisao")
   RETURN .F.
ENDIF	
//IF MDG("Fechar Planilha de Orcamento")
   SELF:novarev1( )
//ENDIF
nOVOLD:=SELF:SERVER:FIELDGET("OV")
SELF:xDuplicar(1)
cDIGCTR:=SELF:SERVER:FIELDGET("REV")		
IF Empty(cDIGCTR)
   cDIGCTR:="A"
ELSE
   nDIGCTR:=Asc(cDIGCTR)	
   cDIGCTR:=Chr(nDIGCTR+1)
ENDIF		
SELF:SERVER:FIELDPUT("REV",cDIGCTR)	
SELF:NOVO("R","Nova Revisao de "+Str(nOVOLD))	

METHOD novarev1( ) 
IF MDG("Fechar Planilha de Orcamento desta Viabilidade")	
	IF TRANSFER(SELF:SERVER:FIELDGET("OV"))
  	   SELF:NOVO("F","Fechamento Viabilidade")	
  	ENDIF
    SELF:FECCODIGO()
ENDIF	

METHOD novo(cOPR,cDESC) 
SELF:oSFJVIAREV:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVIAREV:SERVER:APPEND()
SELF:oSFJVIAREV:SERVER:FIELDPUT("OV",SELF:SERVER:FIELDGET("OV"))
SELF:oSFJVIAREV:SERVER:FIELDPUT("REV",SELF:SERVER:FIELDGET("REV"))
SELF:oSFJVIAREV:SERVER:FIELDPUT("DATA",Today())
SELF:oSFJVIAREV:SERVER:FIELDPUT("HORA",Time())
SELF:oSFJVIAREV:SERVER:FIELDPUT("OPR",cOPR)
SELF:oSFJVIAREV:SERVER:FIELDPUT("MOTIVO",cDESC)
SELF:oSFJVIAREV:SERVER:FIELDPUT("USUARIO",ZUSER)
SELF:oSFJVIAREV:SERVER:commit()
SELF:oSFJVIAREV:SERVER:resetnotification()
SELF:oSFJVIAREV:SERVER:notify(notifyappend) //Contas do Livro

METHOD btnPEGMA01 
LOCAL aCLI AS ARRAY
LOCAL aCOM AS ARRAY
aCLI:=PEGMA01(SELF:SERVER:FIELDGET("CLIENTE"),ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:SERVER:FIELDPUT("CLINOME",aCLI[2])
   SELF:SERVER:FIELDPUT("CLICOGN",aCLI[3])
   IF ! Empty(aCLI[4])
      SELF:SERVER:FIELDPUT("COMPRADOR",aCLI[4])
      aCOM:=PEGMC(SELF:SERVER:FIELDGET("COMPRADOR"),"MC02.DBF")
   	  IF aCOM[1]=.T.
         IF Empty(SELF:SERVER:FIELDGET("COMCOMP"))
            SELF:SERVER:FIELDPUT("COMCOMP",aCOM[2])
         ENDIF
      ENDIF
   ENDIF
ENDIF

METHOD PEGMS01 
LOCAL aPRO AS ARRAY
LOCAL cCODIGO AS STRING
cCODIGO:=AllTrim(SELF:SERVER:DESENHO)
aPRO:=PEGMSEXT(cCODIGO,.T.)
IF aPRO[1]=.T.
   IF Empty(SELF:SERVER:FIELDGET("DENOMINA")) .AND. ! Empty(aPRO[2])
      SELF:SERVER:FIELDPUT("DENOMINA",aPRO[2])
   ENDIF
   IF Empty(SELF:SERVER:FIELDGET("NORMAT"))	 .AND. ! Empty(aPRO[3])
      SELF:SERVER:FIELDPUT("NORMAT",aPRO[3])
   ENDIF
   IF Val(SELF:SERVER:FIELDGET("CODIGOINT"))=0 .AND. ! Empty(aPRO[7])
      SELF:SERVER:FIELDPUT("CODIGOINT",aPRO[7])
   ENDIF
ENDIF	




METHOD POROV 
SELF:KEYFIND()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	   FabCenterWindow( SELF )
 RETURN SELF

METHOD tabular() 
SELF:oSFJVIII:ViewTable()	

METHOD Tabular1( ) 
	SELF:oSFJVIAREV:ViewTable()	

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJVIII:SERVER:Commit()


METHOD xDuplicar(nTIPO) 
LOCAL nOVORI AS DWORD
LOCAL nFIELD AS WORD
LOCAL nREG AS DWORD
LOCAL aERRO AS ARRAY
LOCAL J AS WORD
LOCAL aDADOS AS ARRAY
LOCAL oBUSCA AS xBUSCA


IF nTIPO=0
   IF ! MDG("Duplicar Registro")
      RETURN   .F.
   ENDIF
   oBUSCA:=XBUSCA{SELF,"Duplicar Viabilidade","Digite O Codigo do Desenho"}
   oBUSCA:lMES:=.T.
   oBUSCA:SHOW()
   IF ! oBUSCA:lOK
      RETURN .F.	
   ENDIF
   nREG:=SELF:SERVER:RECNO
   SELF:server:setorder(2)
   SELF:SERVER:GOTOP()
   IF SELF:SERVER:SEEK(oBUSCA:cBUSCA)
      WHILE AllTrim(SELF:SERVER:FIELDGET("DESENHO"))=AllTrim(oBUSCA:cBUSCA) .and. ! SELF:server:Eof
   	      SELF:server:skip()
      ENDDO
      SELF:SERVER:SKIP(-1)
      alert("Desenho Ja cadastrado")
      RETURN .F.	
   ENDIF	
   SELF:SERVER:GOTO(nREG)
ENDIF

aDADOS:={}
nOVORI:=SELF:Server:OV
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
NEXT J

SELF:server:setorder(1)
SELF:server:gobottom()
nOV:=SELF:Server:OV
nOV++

SUPER:SERVER:APPEND()
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    SELF:SERVER:FIELDPUT(J,aDADOS[J])
NEXT J
SELF:SERVER:FIELDPUT("OV",nOV)
SELF:SERVER:FIELDPUT("OVORI",nOVORI)
SELF:SERVER:FIELDPUT("DATAS",ZDATA)
SELF:SERVER:FIELDPUT("DATAV",ZDATA)
SELF:SERVER:FIELDPUT("DATAEC",CToD(Space(8)))
SELF:SERVER:FIELDPUT("INCUSER",ZUSER)
SELF:SERVER:FIELDPUT("INCDATA",Today())
SELF:SERVER:FIELDPUT("INCHORA",Time())
IF nTIPO=0
   SELF:SERVER:FIELDPUT("DESENHO",AllTrim(oBUSCA:cBUSCA))
   SELF:SERVER:FIELDPUT("PECA",AllTrim(oBUSCA:cBUSCA))
   SELF:SERVER:FIELDPUT("DENOMINA",AllTrim(oBUSCA:cBUSCA))
ENDIF
SELF:SERVER:FIELDPUT("ORCAMENTO",0)
SELF:SERVER:FIELDPUT("ITEM",0)
//Campos a ser preenchido estimativa
SELF:SERVER:FIELDPUT("DATAPRE",CToD(Space(8)))
SELF:SERVER:FIELDPUT("QTDEANO",0)
SELF:SERVER:FIELDPUT("LOTEMIN",0)
GRAVALOG(Str(SELF:SERVER:OV),"DUP","VIABILI")	
aERRO:={}
AAdd(aERRO," Viabilidade No:"+StrTRIM(SELF:server:FIELDGET("OV"),8,0))
AAdd(aERRO,"Aberta: "+DToC(Today()))
AAdd(aERRO,"Desenho:"+SELF:server:FIELDGET("DESENHO"))
EMAILINT("VIA00001",ZUSER,aERRO,ZCURINI,zCURDIR)

SELF:server:gotop()
SELF:server:gobottom()
IF nTIPO=0
   SELF:novo("D","Duplicacao da OP "+Str(Novori))
ENDIF
RETURN .T.


END CLASS
