PARTIAL CLASS JANVIA_Page1
METHOD cmdHoje1( ) 
		SELF:server:FDATA:=Today()

END CLASS
PARTIAL CLASS JANVIA_Page3
METHOD PEGMC01() 
RETU PEGCOMBO("MC01.DBF","COGNOME","NUMERO")

END CLASS
PARTIAL CLASS JANVIA_Page4
METHOD cmdHoje1( ) 
		SELF:SERVER:FIELDPUT("FDATA",Today())

METHOD copia( ) 
	SELF:server:FVALORFER:=SELF:server:VALORFER
	SELF:SERVER:FVALORUNI:=SELF:SERVER:VALORUNI	

METHOD desmarcar( ) 
	SELF:SERVER:FIELDPUT("SITUACAO"," ")
	SELF:server:FIELDPUT("FDATA",CToD(Space(8)))
	

END CLASS
PARTIAL CLASS JANVIA_Pagea
METHOD cmdAM( ) 
SELF:server:FIELDPUT("AM",SIMNAO(SELF:SERVER:FIELDGET("AM")))		

METHOD cmdcodesf( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL cCODIGO AS STRING
LOCAL nOV AS DWORD
nOV:=SELF:SERVER:FIELDGET("OV")
cCODIGO:=""
aDAD:={zCURINI,"ESF.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD,,.T.}   //Leitura
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:SetOrder(3) //Nº Viabilidade
oSERVER:GOTOP()
IF oSERVER:SEEK(nOV)
   cCODIGO:=oSERVER:FIELDGET("CODIGO")
ENDIF
oSERVER:CLOSE()
IF ! Empty(cCODIGO)
   alert(cCODIGO)	
ELSE
   alert("Nao Encontrado")
ENDIF	
	

METHOD cmdpr( ) 
SELF:server:FIELDPUT("PR",SIMNAO(SELF:SERVER:FIELDGET("PR"),{"N","E","P","R"}))		


METHOD cmdTIPO( ) 
SELF:server:FIELDPUT("TIPOVIA",SIMNAO(SELF:SERVER:FIELDGET("TIPOVIA")))		


END CLASS
