CLASS XINDEXAR INHERIT INDEXAR	

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("VIA",7)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	

METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
CRIANTX({ZCURINI,"ORCA.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ORCAI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"VIABILI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"VIAREV.DBF",ZCURDIR})
CRIANTX({ZCURINI,"VIABIII.DBF",ZCURDIR})
CRIANTX({ZCURINI,"NP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CD.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CDI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"BTI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"BTII.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CDAPUPRD.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()

END CLASS
CLASS XJANCLI INHERIT JANCLI

METHOD APPEND() 
LOCAL nOV AS DWORD	
SELF:server:setorder(1)
SELF:server:gobottom()
nOV:=SELF:Server:FIELDGET("NUMERO")
nOV++
SUPER:append(.T.)
SELF:SERVER:FIELDPUT("NUMERO",nOV)
GRAVALOG(Str(nOV),"INC","MA01")	
//LOCAL oTB AS TEXTBOX
//Otb:=TEXTBOX{,"Erro","Operaçao Bloqueada "}
//Otb:show()

METHOD DELETE() 
LOCAL oTB AS TEXTBOX
Otb:=TEXTBOX{,"Erro","Operaçao Bloqueada "}
Otb:show()	

CONSTRUCTOR(oOWNER) 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE	
IF ! entramenu("VIA",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MA01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:oDCCOMPRADOR:READONLY:= FALSE
SELF:oDCCOMPRADOR:ENABLE()
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:oDCNOME:READONLY:=FALSE
SELF:oDCNOME:ENABLE()
SELF:oDCCOGNOME:READONLY:=FALSE
SELF:oDCCOGNOME:ENABLE()
SELF:oDCESTADO:READONLY:=FALSE
SELF:oDCESTADO:ENABLE()
SELF:SHOW()	

END CLASS
CLASS XJDELMOT INHERIT JESC


METHOD APPEND() 
LOCAL nNUMERO AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:NUMERO
nNUMERO++
SUPER:append()
SELF:SERVER:FIELDPUT("NUMERO",nNUMERO)
RETURN  .T.

CONSTRUCTOR(oOWNER) 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE		
IF ! entramenu("VIA",14)
	RETU SELF
ENDIF		
aDAD:={zCURINI,"DECLMOT.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oserver)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJMP05 INHERIT JMP05

METHOD APPEND() 
LOCAL oTB AS TEXTBOX
Otb:=TEXTBOX{,"Erro","Operaçao Bloqueada "}
Otb:show()

METHOD DELETE() 
LOCAL oTB AS TEXTBOX
Otb:=TEXTBOX{,"Erro","Operaçao Bloqueada "}
Otb:show()	

CONSTRUCTOR(oOWNER) 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE		
IF ! entramenu("VIA",5)
	RETU SELF
ENDIF		
aDAD:={zCURINI,"MP05.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oserver)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJOSC INHERIT JOSC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PCP",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"OSCRT.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oServer)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()


END CLASS
