FUNC PEGMB01(nFORNECEDO AS DWORD,cCURINI AS STRING,cCURDIR AS STRING)
LOCAL aRETU:={.F.,"","","","","","","","",""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(nFORNECEDO)
   RETU aRETU
ENDIF
aDAD:={cCURINI,"MB01.DBF",cCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(nFORNECEDO,.F.)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("NOME")
   aRETU[3]:=oARQ:FIELDGET("COGNOME")
   aRETU[4]:=oARQ:FIELDGET("TELEFAX")
   aRETU[5]:=oARQ:FIELDGET("TELEFONE")
   aRETU[6]:=oARQ:FIELDGET("RESPF")
   aRETU[7]:=oARQ:FIELDGET("CARGOR")
   aRETU[8]:=oARQ:FIELDGET("EMAIL")
   aRETU[9]:=oARQ:FIELDGET("CONCEITO")
   aRETU[10]:=oARQ:FIELDGET("CONPCP")
ENDIF
oARQ:CLOSE()
RETU aRETU



