FUNCTION PEGMC(eNUMERO AS USUAL,cARQ AS STRING)
LOCAL aRETU:={.F.,"",""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(eNUMERO)
    RETU aRETU
ENDIF
aDAD:={ZCURINI,cARQ,ZCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(eNUMERO)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("NOME")
   aRETU[3]:=oARQ:FIELDGET("COGNOME")
ENDIF
oARQ:CLOSE()
RETU aRETU



