FUNC MTD02(cTAB AS STRING,nLEN AS BYTE)
LOCAL oDBF AS USEREDE
LOCAL aTAB,aDAD AS ARRAY
aTAB:={}
aDAD:={ZCURINI,"MD02.DBF",ZCURDIR}
oDBF:=USEREDE{aDAD}
IF oDBF:nERRO=0
   oDBF:GOTOP()
   oDBF:SEEK(cTAB)
   WHILE ! oDBF:EOF .AND. AllTrim(oDBF:FIELDGET("CODIGO"))==AllTrim(cTAB)
        AAdd(aTAB,{oDBF:FIELDGET("DESCRICAO"),Left(ODBF:FIELDGET("CODIGO1"),nLEN)})
        oDBF:SKIP()
   ENDDO
ENDIF
RETU aTAB

FUNC MTD02A(cTAB AS STRING,nLEN AS BYTE)
LOCAL oDBF AS USEREDE
LOCAL aTAB,aDAD AS ARRAY
aTAB:={}
aDAD:={ZCURINI,"MD02.DBF",ZCURDIR}
oDBF:=USEREDE{aDAD}
IF oDBF:nERRO=0
   oDBF:GOTOP()
   oDBF:SEEK(cTAB)
   WHILE ! oDBF:EOF .AND. AllTrim(oDBF:FIELDGET("CODIGO"))==AllTrim(cTAB)
        AAdd(aTAB,{oDBF:FIELDGET("DESCRICAO"),Left(ODBF:FIELDGET("DESCRICAO"),nLEN)})
        oDBF:SKIP()
   ENDDO
ENDIF
RETU aTAB

FUNC PEGMD02(eCHAVE AS STRING,cTABELA AS STRING,nLEN AS BYTE)
LOCAL aRETU:={.F.,""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(eCHAVE) .OR. IsNil(cTABELA) .OR. IsNil(nLEN)
   RETU aRETU
ENDIF
aDAD:={ZCURINI,"MD02.DBF",ZCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF  oARQ:SEEK(PadR(cTABELA,12)+eCHAVE)
    aRETU[1]:=.T.
    aRETU[2]:=SubStr(oARQ:FIELDGET("DESCRICAO"),1,nLEN)
ENDIF
oARQ:CLOSE()
RETU aRETU



