FUNC PEGME04(cCODIGO AS STRING,cCURINI AS STRING,cCURDIR AS STRING)
LOCAL aRETU:={.F.,"","",""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(cCODIGO)
     RETU aRETU
ENDIF
aDAD:={cCURINI,"ME04.DBF",cCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
oARQ:SEEK(cCODIGO)
IF oARQ:FOUND
    aRETU[1]:=.T.
    aRETU[2]:=oARQ:FIELDGET("NOMTIPO")
    aRETU[3]:=oARQ:FIELDGET("CODTIPO")
    aRETU[4]:=oARQ:FIELDGET("TIPO")
ENDIF
oARQ:CLOSE()
RETU aRETU



