FUNC PEGMP03(cCODIGO,cCURINI AS STRING,cCURDIR AS STRING)
LOCAL aRETU:={.F.,"","","","","","","","",""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(cCODIGO)
   RETU aRETU
ENDIF
aDAD:={cCURINI,"MP03.DBF",cCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(cCODIGO)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("NOME")
   aRETU[3]:=oARQ:FIELDGET("APLICACAO")
   aRETU[4]:=oARQ:FIELDGET("NORMA")
   aRETU[5]:=oARQ:FIELDGET("TIPTRA")
   aRETU[6]:=oARQ:FIELDGET("SUBAPL")
   aRETU[7]:=oARQ:FIELDGET("SUBPROD")
   aRETU[8]:=oARQ:FIELDGET("NOM2")
   aRETU[9]:=oARQ:FIELDGET("CLASSIPI")
   aRETU[10]:=oARQ:FIELDGET("CODIGOINT")
ENDIF
oARQ:CLOSE()
RETU aRETU





