FUNCTION PEGNOMESEXO(cNOMESEXO AS STRING,cCURINI AS STRING,cCURDIR AS STRING,aCOM AS ARRAY)
//exemplo para colar
//LOCAL aDAD,acom AS ARRAY
//aCOM:={zMES,zANO,ZEMPRESA}
//aDAD:=PEGMP04(SELF:SERVER:FIELDGET("NOME"),ZCURINI,ZCURDIR,acom)
//IF aDAD[1]=.T.
//   SELF:SERVER:FIELDPUT("SEXO",aDAD[2])
//ENDIF
LOCAL aRETU:={.F.,""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nPOSNOMESEXO AS DWORD
IF IsNil(CNOMESEXO)
   RETU aRETU
ENDIF
	nPOSNOMESEXO :=At(" ",cNOMESEXO)
		IF nPOSNOMESEXO>0
		   cNOMESEXO:=SubStr(cNOMESEXO,1,nPOSNOMESEXO-1)
		ENDIF
aDAD:={cCURINI,"NOMESEXO.DBF",cCURDIR}
oARQ:=USEREDE{aDAD,,,,aCOM}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(CNOMESEXO)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("CLASSIFICA")
ENDIF
oARQ:CLOSE()
RETU aRETU


FUNCTION PEGMP04(nTECNICO AS DWORD,cCURINI AS STRING,cCURDIR AS STRING,aCOM AS ARRAY)
LOCAL aRETU:={.F.,"",CToD(Space(8)),CToD(Space(8))}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(nTECNICO)
   RETU aRETU
ENDIF
aDAD:={cCURINI,"MP04.DBF",cCURDIR}
oARQ:=USEREDE{aDAD,,,,aCOM}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(nTECNICO)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("NOMTEC")
   aRETU[3]:=oARQ:FIELDGET("ADMITIDO")
   aRETU[4]:=oARQ:FIELDGET("DEMITIDO")
ENDIF
oARQ:CLOSE()
RETU aRETU



