FUNC PEGMP05(cAREA AS STRING,cCURINI AS STRING,cCURDIR AS STRING)
LOCAL aRETU:={.F.,"","",""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(cAREA)
    RETU aRETU
ENDIF
aDAD:={cCURINI,"MP05.DBF",cCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(cAREA)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("RESPON")
   aRETU[3]:=oARQ:FIELDGET("CARGO")
   aRETU[4]:=oARQ:FIELDGET("DESCRI")
ENDIF
oARQ:CLOSE()
RETU aRETU







