FUNC PEGMQ01(cCODIGO,Ccurini,ccurdir)
RETU PEGMUMT(cCODIGO,Ccurini,ccurdir,"MQ01.DBF")	

FUNC PEGMR01(cCODIGO,Ccurini,ccurdir)
RETU PEGMUMT(cCODIGO,Ccurini,ccurdir,"MR01.DBF")	

FUNC PEGMT01(cCODIGO,Ccurini,ccurdir)
RETU PEGMUMT(cCODIGO,Ccurini,ccurdir,"MT01.DBF")	

FUNC PEGMU01(cCODIGO,Ccurini,ccurdir)
RETU PEGMUMT(cCODIGO,Ccurini,ccurdir,"MU01.DBF")	

FUNC PEGMUMT(cCODIGO,Ccurini AS STRING,ccurdir AS STRING,Carq)
LOCAL aRETU:={.F.,"","","","",0,""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={cCURINI,cARQ,cCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(cCODIGO,.F.)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("NOME")+" "+AllTrim(oARQ:FIELDGET("NOM2"))
   aRETU[3]:=oARQ:FIELDGET("APLICACAO")
   aRETU[4]:=oARQ:FIELDGET("UNIDADE")
   aRETU[5]:=oARQ:FIELDGET("INSTRU")
   aRETU[6]:=oARQ:FIELDGET("PESLIQ")
   aRETU[7]:=oARQ:FIELDGET("CLASSIPI")
ENDIF
oARQ:CLOSE()
RETU aRETU


FUNC PEGMW05(cCODIGO,Ccurini,ccurdir)
RETU PEGMUMT(cCODIGO,Ccurini,ccurdir,"MW05.DBF")	

FUNC PEGMW07(cCODIGO,Ccurini,ccurdir)
RETU PEGMUMT(cCODIGO,Ccurini,ccurdir,"MW07.DBF")	


