FUNCTION PEGGMFI(cCODIGO)
LOCAL aRETU AS ARRAY
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE
LOCAL cNOME,cDELIVERY,cSTOCK AS STRING
cCODIGO:=AllTrim(TIRAOUT(cCODIGO))
aRETU:={.F.,"","",""}
aDAD:={zCURINI,"PECASGM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO=0
   oSERVER:GOTOP()
   IF oSERVER:SEEK(cCODIGO)
   	  cNOME:=oSERVER:FIELDGET("PART_NAME")
   	  cDELIVERY:=oSERVER:FIELDGET("DLOC")
      cSTOCK:=oSERVER:FIELDGET("DOCK_STCK")
   	  aRETU:={.T.,cNOME,cDELIVERY,cSTOCK}
   ENDIF	
   oSERVER:CLOSE()
ENDIF
IF ! aRETU[1]
   aDAD:={zCURINI,"PECASEL.DBF",zCURDIR}
   oSERVER:=USEREDE{aDAD}
   IF oSERVER:nERRO=0
      oSERVER:GOTOP()
      IF oSERVER:SEEK(cCODIGO)
     	 cNOME:=oSERVER:FIELDGET("PART_NAME")
   	     aRETU:={.T.,cNOME,"",""}
      ENDIF	
      oSERVER:CLOSE()
  ENDIF
ENDIF
IF ! aRETU[1]
   aDAD:={zCURINI,"PECASFI.DBF",zCURDIR}
   oSERVER:=USEREDE{aDAD}
   IF oSERVER:nERRO=0
      oSERVER:GOTOP()
      IF oSERVER:SEEK(cCODIGO)
     	 cNOME:=oSERVER:FIELDGET("PART_NAME")
   	     aRETU:={.T.,cNOME,"",""}
      ENDIF	
      oSERVER:CLOSE()
  ENDIF
ENDIF
IF ! aRETU[1]
   aDAD:={zCURINI,"VIABILI.DBF",zCURDIR}
   oSERVER:=USEREDE{aDAD}
   IF oSERVER:nERRO=0
   	  oSERVER:SETORDER(2)
      oSERVER:GOTOP()
      IF oSERVER:SEEK(cCODIGO)
     	 cNOME:=oSERVER:FIELDGET("DENOMINA")
   	     aRETU:={.T.,cNOME,"",""}
      ENDIF	
      oSERVER:CLOSE()
  ENDIF
ENDIF
RETU aRETU




