FUNC ENVIARIF(cERRO,cCODIGO,nOS,nPF)
LOCAL aERRO AS ARRAY
aERRO:={}
AAdd(aERRO,"OS No:"+StrTRIM(nOS,8,0))
AAdd(aERRO,"PF No:"+StrTRIM(nPF,8,0))
AAdd(aERRO,"Produto:"+AllTrim(cCODIGO))
EMAILINT(cERRO,ZUSER,aERRO,ZCURINI,zCURDIR)		
	






