CLASS jESCos INHERIT _jESCos
	EXPORT LOK AS LOGIC
	EXPORT nOS AS WORD

METHOD Busca( ) 
LOCAL cCODIGO AS STRING
cCODIGO:=FIXSTR(SELF:CBUSCA)
IF ! Empty(cCODIGO)
   SELF:oSFjosc:SERVER:setorder(4)	
   SELF:oSFjosc:SERVER:GOTOP()
   SELF:oSFjosc:SERVER:SEEK(cCODIGO)
ENDIF	

METHOD Busca1( ) 
LOCAL cCODIGO AS STRING
cCODIGO:=FIXSTR(SELF:CODIGOINT)
IF ! Empty(cCODIGO)
   SELF:oSFjosc:SERVER:setorder(5)	
   SELF:oSFjosc:SERVER:GOTOP()
   SELF:oSFjosc:SERVER:SEEK(cCODIGO)
ENDIF	
	



METHOD Escolher( ) 

	SELF:oDCOS:Value:=Str(SELF:oSFjosc:SERVER:FIELDGET("OS"))
	SELF:oDCCBUSCA:Value:=SELF:oSFjosc:SERVER:FIELDGET("CODIGO")
	SELF:oDCCODIGOINT:VALUE:=SELF:oSFjosc:SERVER:FIELDGET("CODIGOINT")
	
		SELF:LOK:=.F.
	nOS:=FIXNUM(SELF:OS)
	AltD()
    IF nOS>0
	   SELF:LOK:=.T.
    ENDIF		
	SELF:EndWindow()




CONSTRUCTOR(oOWNER) 
LOCAL oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
LOK:=.F.
aDAD:={ZCURINI,"OSCRT.DBF",ZCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
   RETU SELF
ENDIF
SUPER(oOWNER)
SELF:oSFJOSC:USE(oSERVE2)
SELF:oSFjOSC:SERVER:GOTOP()
SELF:oSFjosc:VIEWTABLE()
SELF:oSFjosc:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		


METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
	    FabCenterWindow( SELF )
	RETURN NIL


METHOD sair( ) 
	SELF:LOK:=.F.
	nOS:=0
	SELF:EndWindow()


END CLASS
