CLASS XINDEXAR INHERIT INDEXAR

CONSTRUCTOR(oOWNER) 
IF ! entramenu("FIN",90)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:SHOW()	



METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
CRIANTX({ZCURINI,"RIF.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RIFI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RIFPR.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()


END CLASS
