CLASS XJEP INHERIT JEP

METHOD ALTERA2  
SELF:oSFJSEQ:VIEWFORM()

METHOD ALTERAR  
SELF:oSFJVCE:VIEWFORM()

METHOD ANTERIO2 
SELF:oSFJSEQ:Browser:SuspendUpdate()
IF SELF:oSFJSEQ:Server:BOF
    SELF:oSFJSEQ:SkipPREVIOUS()
ENDIF
SELF:oSFJSEQ:Browser:RestoreUpdate()

METHOD ANTERIOR 
SELF:oSFJVCE:Browser:SuspendUpdate()
IF SELF:oSFJVCE:Server:BOF
     SELF:oSFJVCE:SkipPREVIOUS()
ENDIF
SELF:oSFJVCE:Browser:RestoreUpdate()

METHOD APPEND(oOWNER) 
LOCAL oBUSCA AS XBUSCA
LOCAL nOV,nVIA AS DWORD
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL oERRO AS ERRORBOX

oBUSCA:=xBUSCA{SELF,"Nova Estimativa","Digite o Nº da Viabilidade"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU
ENDIF
nVIA:=Val(oBUSCA:cBUSCA)
IF nVIA=0
   oERRO:=ERRORBOX{oOWNER,"Viabilidade Em Branco"}
   oERRO:SHOW()		
ENDIF	
aDAD:={zCURINI,"VIABILI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF
oSERVER:GOTOP()
IF ! oSERVER:SEEK(nVIA)
   oSERVER:CLOSE()
   oERRO:=ERRORBOX{oOWNER,"Viabilidade Nao Encontrada"}
   oERRO:SHOW()		
   RETU SELF
ENDIF
IF Empty(oSERVER:FIELDGET("DATAPRE"))
   oSERVER:CLOSE()
   oERRO:=ERRORBOX{oOWNER,"Marcar Viabilidade Como Preenchida"}
   oERRO:SHOW()		
   RETU SELF	
ENDIF	
IF Empty(oSERVER:FIELDGET("QTDEANO"))
   oSERVER:CLOSE()
   alert("Lote Anual Não Preenchido Viabilidade","Erro")
   RETU SELF	
ENDIF	
IF Empty(oSERVER:FIELDGET("LOTEMIN"))
   oSERVER:CLOSE()
   alert("Lote Minimo Não Preenchido Viabilidade","Erro")
   RETU SELF	
ENDIF	
IF ! Empty(oSERVER:FIELDGET("ORCAMENTO"))
   oSERVER:CLOSE()
   oERRO:=ERRORBOX{oOWNER,"Viabilidade esta Fechada C/Orcamento"}
   oERRO:SHOW()		
   RETU SELF	
ENDIF	
SELF:SERVER:GOTOP()
SELF:SERVER:SETORDER(2)
IF SELF:SERVER:SEEK(AllTrim(oSERVER:FIELDGET("DESENHO")))
   oSERVER:CLOSE()
   oERRO:=ERRORBOX{oOWNER,"Ja existe Estimativa Este Desenho"}
   oERRO:SHOW()		
   RETU SELF	
ENDIF	
SELF:SERVER:APPEND()
//nOV:=SELF:SERVER:RECNO
nOV:=nVIA //Numero estimativa  = viabilidade
SELF:SERVER:FIELDPUT("OV",nOV)
SELF:SERVER:FIELDPUT("VIABILI",nVIA)
SELF:SERVER:FIELDPUT("CLIENTE",oSERVER:FIELDGET("CLIENTE"))
SELF:SERVER:FIELDPUT("LANU",oSERVER:FIELDGET("QTDEANO"))
SELF:SERVER:FIELDPUT("LMES",oSERVER:FIELDGET("QTDEANO")/12)
SELF:SERVER:FIELDPUT("LMIN",oSERVER:FIELDGET("LOTEMIN"))
SELF:SERVER:FIELDPUT("CODIGO",AllTrim(oSERVER:FIELDGET("DESENHO")))
SELF:SERVER:FIELDPUT("NOME",oSERVER:FIELDGET("DENOMINA"))
SELF:SERVER:FIELDPUT("PRAZO",oSERVER:FIELDGET("DATAV"))
SELF:SERVER:FIELDPUT("DUNS",oSERVER:FIELDGET("DUNS"))
SELF:SERVER:FIELDPUT("PROJETO",oSERVER:FIELDGET("PROJETO"))
oSERVER:CLOSE()
aDAD:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aDAD[1]=.T.
   SELF:SERVER:FIELDPUT("COGCLI",aDAD[3])
ENDIF
SELF:SERVER:Commit()
SELF:SERVER:SETORDER(1)
SELF:SERVER:GOTOP()
SELF:SERVER:SEEK(nOV)
SELF:GRAVATUDO()

METHOD Buscaov() 
SELF:KeyFind()	
//LOCAL oBUSCA AS xBUSCA
//oBUSCA:=xBUSCA{SELF,"Localizar Planilha","Digite Nº Planilha"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF

METHOD CHECAR 
SELF:oSFJVCE:SERVER:GOTOP()
WHILE ! SELF:oSFJVCE:SERVER:EOF	
  IF Empty(SELF:oSFJVCE:SERVER:FIELDGET("TIPOENT"))
  	 alert("Tipo em Branco")
  ENDIF
  SELF:oSFJVCE:SERVER:SKIP()
ENDDO
	
SELF:oSFJseq:SERVER:GOTOP()
WHILE ! SELF:oSFJseq:SERVER:EOF	
  IF Empty(SELF:oSFJseq:SERVER:FIELDGET("PCHORA"))
  	 alert("PC/HR em Branco")
  ENDIF
  IF Empty(SELF:oSFJseq:SERVER:FIELDGET("HRFER"))
  	 alert("Hora Ferramenta em Branco")
  ENDIF
  IF Empty(SELF:oSFJseq:SERVER:FIELDGET("CODMP01"))
  	 alert("Codigo Maquina em Branco")
  ENDIF
  SELF:oSFJseq:SERVER:SKIP()
ENDDO
	

METHOD CMDANUAL 
LOCAL oBUSCA AS XBUSCA
LOCAL cVALOR
IF ! Empty(SELF:server:FIELDGET("DATAPRE")) .AND. SELF:SERVER:FIELDGET("QTDEANO")>0
	alert("Ja preenchida")
	RETU
ENDIF
cVALOR:=Val(SELF:SERVER:FIELDGET("EAC"))
cVALOR:=Str(cVALOR)
oBUSCA:=XBUSCA{SELF,"Lote Anual","Digite qtde Lote Anual",cVALOR}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK	
	SELF:SERVER:FIELDPUT("QTDEANO",Val(oBUSCA:cBUSCA))
	SELF:GRAVATUDO()
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD cmdescmp01() 
LOCAL oESCMP01 AS Xescolhemp
LOCAL oBUSCA AS XBUSCA

oESCMP01:=Xescolhemp{SELF,"E"}
oESCMP01:SHOW()
IF oESCMP01:ARETU[1]=.T.
  SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP01",oESCMP01:aRETU[2])
  SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP01",oESCMP01:aRETU[3])
  SELF:oSFJSEQ:SERVER:FIELDPUT("CODFOLHA",oESCMP01:aRETU[5])
  oBUSCA:=XBUSCA{SELF,"Forneca qtde/Pchora","Confirme PC/HORA",Str(SELF:oSFJSEQ:SERVER:FIELDGET("PCHORA"))}
  oBUSCA:lMES:=.T.
  oBUSCA:SHOW()
  IF oBUSCA:lOK
     SELF:oSFJSEQ:SERVER:FIELDPUT("PCHORA",INT(Val(oBUSCA:cBUSCA)))
  ENDIF
  SELF:GRAVATUDO()
ENDIF

METHOD cmdescMP02() 
LOCAL oESCMP02 AS Xescolhemp
oESCMP02:=Xescolhemp{SELF,"H"}
oESCMP02:SHOW()
IF oESCMP02:ARETU[1]=.T.
     SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP02",oESCMP02:aRETU[2])
     SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP02",oESCMP02:aRETU[3])
     SELF:GRAVATUDO()
ENDIF


METHOD cmdescMP02B() 
LOCAL oESCMP02 AS Xescolhemp
oESCMP02:=Xescolhemp{SELF,"H"}
oESCMP02:SHOW()
IF oESCMP02:ARETU[1]=.T.
     SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP02B",oESCMP02:aRETU[2])
     SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP02B",oESCMP02:aRETU[3])
     SELF:GRAVATUDO()
ENDIF

METHOD cmdescmp2( ) 
LOCAL oESC AS XESCNUM
oESC:=XESCNUM{SELF,"FLUXO.DBF"}
oESC:SHOW()
IF oESC:LOK
     SELF:oSFJSEQ:SERVER:FIELDPUT("FLUXO",oESC:NUMERO)
ENDIF
	

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CU","ESP")	


METHOD cmdtCO() 
     SELF:oSFJVCE:SERVER:TIPOENT:="C"	
   SELF:GRAVATUDO()

METHOD cmdtETI() 
     SELF:oSFJVCE:SERVER:TIPOENT:="I"	
        SELF:GRAVATUDO()

METHOD cmdtMP() 
     SELF:oSFJVCE:SERVER:TIPOENT:="M"	
        SELF:GRAVATUDO()

METHOD cmdtTR() 
     SELF:oSFJVCE:SERVER:TIPOENT:="T"	
        SELF:GRAVATUDO()

METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	GRAVALOG(SELF:Server:OV,"DEL","VPORC")	
	SELF:oSFJVCE:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJVCE:server:GOTOP()
	WHILE !  oSFJVCE:server:EOF
		SELF:oSFJVCE:server:DELETE()
		SELF:oSFJVCE:server:SKIP()
	ENDDO
    SELF:oSFJVCE:server:GOTOP()
	SELF:oSFJVCE:SERVER:resetnotification()


	SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJSEQ:server:GOTOP()
	WHILE !  oSFJSEQ:server:EOF
		SELF:oSFJSEQ:server:DELETE()
		SELF:oSFJSEQ:server:SKIP()
	ENDDO
   SELF:oSFJSEQ:server:GOTOP()
	SELF:oSFJSEQ:SERVER:resetnotification()
	
	SELF:server:delete()
	SELF:server:unlock()

    SELF:server:GoBottom()
 	SELF:SERVER:GOTOP()

ENDIF
   SELF:GRAVATUDO()

METHOD editarVIA 
SELF:oSFJVIII:ViewForm()	

METHOD EmailVIA 
LOCAL aERRO AS ARRAY
LOCAL cTIPO,cDADO AS STRING
aERRO:={}
cTIPO:=SELF:oSFJVIII:SERVER:FIELDGET("TIPO")
cDADO:=SELF:oSFJVIII:SERVER:FIELDGET("DADO")
AAdd(aERRO," Viabilidade No:"+StrTRIM(SELF:server:FIELDGET("OV"),8,0))
DO CASE
   CASE cTIPO="C"
   	    AAdd(aERRO,"Cotação: "+cDADO)
   	    EMAILINT("CUSTO001",ZUSER,aERRO,ZCURINI,zCURDIR)	
   	    alert("Email Enviado","Email")
   CASE cTIPO="D"
   	    AAdd(aERRO,"Desenho: "+cDADO)
   	    EMAILINT("CUSTO002",ZUSER,aERRO,ZCURINI,zCURDIR)	
   	    alert("Email Enviado","Email")
   CASE cTIPO="N"
   	    AAdd(aERRO,"Norma: "+cDADO)
   	    EMAILINT("CUSTO002",ZUSER,aERRO,ZCURINI,zCURDIR)	
   	    alert("Email Enviado","Email")
ENDCASE		



METHOD escc() 
LOCAL oESCMT01 AS Xescolhemp
oESCMT01:=Xescolhemp{SELF,"C"}
oESCMT01:SHOW()
IF oESCMT01:LOK
     SELF:oSFJVCE:SERVER:TIPOENT:="C"
     SELF:oSFJVCE:SERVER:CODCOMP:=oESCMT01:aRETU[2]
     SELF:oSFJVCE:SERVER:NOMECOMP:=oESCMT01:aRETU[3]
     SELF:oSFJVCE:SERVER:PRECO:=oESCMT01:aRETU[4]
     IF SELF:oSFJVCE:SERVER:QTDDE==0
          SELF:oSFJVCE:SERVER:QTDDE:=1
     ENDIF
     SELF:oSFJVCE:SERVER:TOTAL:=SELF:oSFJVCE:SERVER:PRECO*SELF:oSFJVCE:SERVER:QTDDE
        SELF:GRAVATUDO()
ENDIF

METHOD escI() 
LOCAL oESCMP03 AS Xescolhemp
oESCMP03:=Xescolhemp{SELF,"I"}
oESCMP03:SHOW()
IF oESCMP03:ARETU[1]=.T.
     SELF:oSFJVCE:SERVER:TIPOENT:="I"
     SELF:oSFJVCE:SERVER:CODCOMP:=oESCMP03:aRETU[2]
     SELF:oSFJVCE:SERVER:NOMECOMP:=oESCMP03:aRETU[3]
     SELF:oSFJVCE:SERVER:PRECO:=oESCMP03:aRETU[4]
     IF SELF:oSFJVCE:SERVER:QTDDE=0
          SELF:oSFJVCE:SERVER:QTDDE:=1
     ENDIF
     SELF:oSFJVCE:SERVER:TOTAL:=SELF:oSFJVCE:SERVER:PRECO*SELF:oSFJVCE:SERVER:QTDDE
        SELF:GRAVATUDO()
ENDIF

METHOD escm() 
LOCAL oESCMU01 AS Xescolhemp
oESCMU01:=Xescolhemp{SELF,"M"}
oESCMU01:SHOW()
IF oESCMU01:ARETU[1]=.T.
     SELF:oSFJVCE:SERVER:TIPOENT:="M"
     SELF:oSFJVCE:SERVER:CODCOMP:=oESCMU01:aRETU[2]
     SELF:oSFJVCE:SERVER:NOMECOMP:=oESCMU01:aRETU[3]
     SELF:oSFJVCE:SERVER:PRECO:=oESCMU01:aRETU[4]
     IF SELF:oSFJVCE:SERVER:QTDDE=0
          SELF:oSFJVCE:SERVER:QTDDE:=1
     ENDIF
     SELF:oSFJVCE:SERVER:TOTAL:=SELF:oSFJVCE:SERVER:PRECO*SELF:oSFJVCE:SERVER:QTDDE
        SELF:GRAVATUDO()
ENDIF

METHOD escT() 
LOCAL oESCMP03 AS Xescolhemp
oESCMP03:=Xescolhemp{SELF,"T"}
oESCMP03:SHOW()
IF oESCMP03:ARETU[1]=.T.
     SELF:oSFJVCE:SERVER:TIPOENT:="T"
     SELF:oSFJVCE:SERVER:CODCOMP:=oESCMP03:aRETU[2]
     SELF:oSFJVCE:SERVER:NOMECOMP:=oESCMP03:aRETU[3]
     SELF:oSFJVCE:SERVER:PRECO:=oESCMP03:aRETU[4]
     IF SELF:oSFJVCE:SERVER:QTDDE=0
          SELF:oSFJVCE:SERVER:QTDDE:=1
     ENDIF
     SELF:oSFJVCE:SERVER:TOTAL:=SELF:oSFJVCE:SERVER:PRECO*SELF:oSFJVCE:SERVER:QTDDE
        SELF:GRAVATUDO()
ENDIF

METHOD EXCLUI2 
IF ! MDG("Apagar Registro") .AND. SELF:oSFJSEQ:server:LockCurrentRecord()
   RETU
ENDIF
SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJSEQ:server:delete()
SELF:oSFJSEQ:server:unlock()
 IF !   SELF:oSFJSEQ:server:bof
      SELF:oSFJSEQ:server:skip(-1)
 ELSE
      IF ! SELF:oSFJSEQ:server:eof
          SELF:oSFJSEQ:server:skip()
       ENDIF
 ENDIF
 SELF:oSFJSEQ:SERVER:resetnotification()
SELF:oSFJSEQ:SERVER:notify(notifyfilechange)
SELF:oSFJSEQ:Browser:refresH()
   SELF:GRAVATUDO()

METHOD EXCLUIR 
IF ! MDG("Apagar Registro") .AND. SELF:oSFJVCE:server:LockCurrentRecord()
   RETU
ENDIF
SELF:oSFJVCE:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVCE:server:delete()
SELF:oSFJVCE:server:unlock()
IF ! SELF:oSFJVCE:server:bof
   SELF:oSFJVCE:server:skip(-1)
ELSE
  IF ! SELF:oSFJVCE:server:eof
     SELF:oSFJVCE:server:skip()
  ENDIF
ENDIF
SELF:oSFJVCE:SERVER:resetnotification()
SELF:oSFJVCE:SERVER:notify(notifyfilechange)
SELF:oSFJVCE:Browser:refresH()
   SELF:GRAVATUDO()

METHOD EXCLUIRVIA 
IF ! MDG("Apagar Registro") .AND. SELF:oSFJVIII:server:LockCurrentRecord()
   RETU
ENDIF
SELF:oSFJVIII:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVIII:server:delete()
SELF:oSFJVIII:server:unlock()
IF !   SELF:oSFJVIII:server:bof
   SELF:oSFJVIII:server:skip(-1)
ELSE
  IF ! SELF:oSFJVIII:server:eof
      SELF:oSFJVIII:server:skip()
  ENDIF
ENDIF
SELF:oSFJVIII:SERVER:resetnotification()
SELF:oSFJVIII:SERVER:notify(notifyfilechange)
SELF:oSFJVIII:Browser:refresh()
   SELF:GRAVATUDO()

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()


METHOD GRAVATUDO() 
SELF:SERVER:Commit()	
SELF:oSFJVCE:SERVER:commit()
SELF:oSFJSEQ:SERVER:commit()
SELF:RegisterTimer(300,FALSE)

METHOD Imp 
SELF:oSFJVCE:SERVER:FIELDPUT("ORIGEM","Internacional")	
   SELF:GRAVATUDO()

METHOD ImpEst( ) 
LOCAL nOV,nRECNO,X,nOVTMP AS DWORD
LOCAL oBUSCA AS XBUSCA
LOCAL aSEQ,aCOM,aTMP,aDAD AS ARRAY
LOCAL oESF,oMS03,oMS06 AS USEREDE
aSEQ:={}
aCOM:={}
nOV:=SELF:SERVER:FIELDGET("OV")
nRECNO:=SELF:SERVER:ReCNO
oBUSCA:=XBUSCA{SELF,"Importar Desenho Desenho","Digite o Codigo do Desenho"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU .F.
ENDIF
SELF:SERVER:SETORDER(2)
SELF:SERVER:GOTOP()
IF SELF:SERVER:SEEK(AllTrim(oBUSCA:cBUSCA))
   SELF:oSFJVCE:SERVER:GOTOP()
   WHILE ! SELF:OSFJVCE:SERVER:EOF
     aTMP:={}
     AAdd(aTMP,SELF:oSFJVCE:SERVER:FIELDGET("TIPOENT"))
     AAdd(aTMP,SELF:oSFJVCE:SERVER:FIELDGET("CODCOMP"))
     AAdd(aTMP,SELF:oSFJVCE:SERVER:FIELDGET("NOMECOMP"))
     AAdd(aTMP,SELF:oSFJVCE:SERVER:FIELDGET("ORIGEM"))
     AAdd(aTMP,SELF:oSFJVCE:SERVER:FIELDGET("QTDDE"))
     SELF:oSFJVCE:SERVER:Skip()
     AAdd(aCOM,aTMP)
   ENDDO
   SELF:oSFJSEQ:SERVER:GOTOP()
   WHILE ! SELF:OSFJSEQ:SERVER:EOF
     aTMP:={}
     AAdd(aTMP,SELF:oSFJSEQ:SERVER:FIELDGET("SEQ"))
     AAdd(aTMP,SELF:oSFJSEQ:SERVER:FIELDGET("SSQ"))
     AAdd(aTMP,SELF:oSFJSEQ:SERVER:FIELDGET("DESCRI"))
     AAdd(aTMP,SELF:oSFJSEQ:SERVER:FIELDGET("PCHORA"))
     AAdd(aTMP,SELF:oSFJSEQ:SERVER:FIELDGET("HRFER"))
     AAdd(aTMP,SELF:oSFJSEQ:SERVER:FIELDGET("CODFOLHA"))
     AAdd(aTMP,SELF:oSFJSEQ:SERVER:FIELDGET("CODMP01"))
     AAdd(aTMP,SELF:oSFJSEQ:SERVER:FIELDGET("NOMMP01"))
     SELF:oSFJSEQ:SERVER:Skip()
     AAdd(aSEQ,aTMP)
   ENDDO
ELSE //Procura Fechadas
   aDAD:={zCURINI,"ESF.DBF",zCURDIR}
   oESF:=USEREDE{aDAD,,.T.}   //Leitura
   IF oESF:nERRO#0
      RETU SELF
   ENDIF	
   oESF:SetOrder(2)
   oESF:GOTOP()
   IF ! oESF:Seek(AllTrim(oBUSCA:cBUSCA))
   	  oESF:CLOSE()
   	  RETU SELF
   ENDIF	
   nOVTMP:=oESF:FIELDGET("OV")
   oESF:CLOSE()
   aDAD:={zCURINI,"ESFMS03.DBF",zCURDIR}
   oMS03:=USEREDE{aDAD,,.T.}   //Leitura
   IF oMS03:nERRO#0
      RETU SELF
   ENDIF
   oMS03:GOTOP()
   oMS03:SEEK(nOVTMP)
   WHILE nOVTMP=oMS03:FIELDGET("OV") .AND. ! oMS03:EoF
     aTMP:={}
     AAdd(aTMP,oMS03:FIELDGET("TIPOENT"))
     AAdd(aTMP,oMS03:FIELDGET("CODCOMP"))
     AAdd(aTMP,oMS03:FIELDGET("NOMECOMP"))
     AAdd(aTMP,oMS03:FIELDGET("ORIGEM"))
     AAdd(aTMP,oMS03:FIELDGET("QTDDE"))
     oMS03:SKIP()
     AAdd(aCOM,aTMP)
   ENDDO
   oMS03:CLOSE()
   aDAD:={zCURINI,"ESFMS06.DBF",zCURDIR}
   oMS06:=USEREDE{aDAD,,.T.}   //Leitura
   IF oMS06:nERRO#0
      RETU SELF
   ENDIF	
   oMS06:GOTOP()
   oMS06:SEEK(nOVTMP)
   WHILE nOVTMP=oMS06:FIELDGET("OV") .AND. ! oMS06:EoF
 	 aTMP:={}
     AAdd(aTMP,oMS06:FIELDGET("SEQ"))
     AAdd(aTMP,oMS06:FIELDGET("SSQ"))
     AAdd(aTMP,oMS06:FIELDGET("DESCRI"))
     AAdd(aTMP,oMS06:FIELDGET("PCHORA"))
     AAdd(aTMP,oMS06:FIELDGET("HRFER"))
     AAdd(aTMP,oMS06:FIELDGET("CODFOLHA"))
     AAdd(aTMP,oMS06:FIELDGET("CODMP01"))
     AAdd(aTMP,oMS06:FIELDGET("NOMMP01"))
     oMS06:SKIP()
     AAdd(aSEQ,aTMP)
   ENDDO
   oMS06:CLOSE()
ENDIF	
SELF:SERVER:GOTO(nRECNO)	
SELF:oSFJVCE:SERVER:SUSPENDNOTIFICATION()
FOR X:=1 TO Len(aCOM)
    SELF:oSFJVCE:SERVER:APPEND()
    SELF:oSFJVCE:SERVER:FIELDPUT("OV",nOV)
	SELF:oSFJVCE:SERVER:FIELDPUT("TIPOENT",aCOM[X][1])
	SELF:oSFJVCE:SERVER:FIELDPUT("CODCOMP",aCOM[X][2])
	SELF:oSFJVCE:SERVER:FIELDPUT("NOMECOMP",aCOM[X][3])
	SELF:oSFJVCE:SERVER:FIELDPUT("ORIGEM",aCOM[X][4])
	SELF:oSFJVCE:SERVER:FIELDPUT("QTDE",aCOM[X][5])
	SELF:oSFJVCE:SERVER:commit()
NEXT X	
SELF:oSFJVCE:SERVER:resetnotification()
SELF:oSFJVCE:SERVER:notify(notifyappend)
SELF:OSFJVCE:Browser:REFRESH()
SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
FOR X:=1 TO Len(aSEQ)
    SELF:oSFJSEQ:SERVER:APPEND()
    SELF:oSFJSEQ:SERVER:FIELDPUT("OV",nOV)
	SELF:oSFJSEQ:SERVER:FIELDPUT("SEQ",aSEQ[X][1])
	SELF:oSFJSEQ:SERVER:FIELDPUT("SSQ",aSEQ[X][2])
	SELF:oSFJSEQ:SERVER:FIELDPUT("DESCRI",aSEQ[X][3])
	SELF:oSFJSEQ:SERVER:FIELDPUT("PCHORA",aSEQ[X][4])
	SELF:oSFJSEQ:SERVER:FIELDPUT("HRFER",aSEQ[X][5])
	SELF:oSFJSEQ:SERVER:FIELDPUT("CODFOLHA",aSEQ[X][6])
	SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP01",aSEQ[X][7])
	SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP01",aSEQ[X][8])	
	SELF:oSFJSEQ:SERVER:commit()	
NEXT X	
SELF:oSFJSEQ:SERVER:resetnotification()
SELF:oSFJSEQ:SERVER:notify(notifyappend)
SELF:OSFJSEQ:Browser:REFRESH()
SELF:GRAVATUDO()

METHOD IMPMANA5 
LOCAL oMS01,oMS03,oMS06 AS USEMANA5
LOCAL aRET AS ARRAY
LOCAL nOV AS DWORD
LOCAL cCODIGO AS STRING
LOCAL oBUSCA AS XBUSCA

nOV:=SELF:SERVER:OV
cCODIGO:=AllTrim(SELF:SERVER:CODIGO)


oBUSCA:=XBUSCA{SELF,"Confirme o Codigo","Confirme Codigo Produto Importacao",cCODIGO}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   cCODIGO:=Upper(oBUSCA:cBUSCA)
ENDIF



aRET:={zCURINI,"MS01",zCURDIR,aDIR}
oMS01:=USEMANA5{aRET}
IF oMS01:nERRO=0	
	oMS01:GOTOP()
	IF oMS01:SEEK(cCODIGO)
		IF Empty(SELF:SERVER:CLIENTE)
    		SELF:SERVER:CLIENTE:=oMS01:FIELDGET("FORNECEDO")
        ENDIF
		IF Empty(SELF:SERVER:NOME)
    		SELF:SERVER:NOME:=oMS01:FIELDGET("NOME")
        ENDIF		
	ENDIF		
	oMS01:CLOSE()
ENDIF	
aRET:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aRET[1]=.T.
   SELF:SERVER:COGCLI:=aRET[3]
ENDIF
aRET:={zCURINI,"MS03",zCURDIR,aDIR}
oMS03:=USEMANA5{aRET}
IF oMS03:nERRO=0
	oMS03:SetOrder(2)
	oMS03:GOTOP()
	oMS03:SEEK(cCODIGO)
	SELF:oSFJVCE:SERVER:SUSPENDNOTIFICATION()
	WHILE AllTrim(oMS03:FIELDGET("CODIGO"))=cCODIGO .AND. ! oMS03:EoF
		IF oMS03:FIELDGET("TIPOENT")="M" .OR. oMS03:FIELDGET("TIPOENT")="C"
			aRET:=VS3PRECO(oMS03:FIELDGET("TIPOENT"),oMS03:FIELDGET("CODCOMP"),.F.)
			SELF:oSFJVCE:SERVER:APPEND()			
			SELF:oSFJVCE:SERVER:OV:=nOV
//			SELF:OSFJVCE:SERVER:CODIGO:=cCODIGO
			SELF:OSFJVCE:SERVER:TIPOENT:=oMS03:FIELDGET("TIPOENT")
			SELF:OSFJVCE:SERVER:CODCOMP:=oMS03:FIELDGET("CODCOMP")
			SELF:OSFJVCE:SERVER:QTDDE:=oMS03:FIELDGET("QTDDE")
			SELF:OSFJVCE:SERVER:NOMECOMP:=aRET[2]
            SELF:OSFJVCE:SERVER:ORIGEM:="Nacional"
			SELF:OSFJVCE:SERVER:PRECO:=aRET[1]										
			SELF:OSFJVCE:SERVER:TOTAL:=aRET[1]*oMS03:FIELDGET("QTDDE")			
			SELF:oSFJVCE:SERVER:commit()
		ENDIF	
	   oMS03:SKIP()
   ENDDO
	SELF:oSFJVCE:SERVER:resetnotification()
	SELF:oSFJVCE:SERVER:notify(notifyappend)		
	oMS03:CLOSE()
ENDIF
aRET:={zCURINI,"MS06",zCURDIR,aDIR}
oMS06:=USEMANA5{aRET}
IF oMS06:nERRO=0
	oMS06:SetOrder(2)
	oMS06:GOTOP()
	oMS06:SEEK(cCODIGO)
	SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
	WHILE AllTrim(oMS06:FIELDGET("CODIGO"))=cCODIGO .AND. ! oMS06:EoF
			IF oMS06:FIELDGET("SEQ")<>99 .AND. oMS06:FIELDGET("SSQ")<>99
	 			SELF:oSFJSEQ:SERVER:APPEND()			
				SELF:oSFJSEQ:SERVER:OV:=nOV
//				SELF:OSFJSEQ:SERVER:CODIGO:=cCODIGO
				SELF:OSFJSEQ:SERVER:SEQ:=oMS06:FIELDGET("SEQ")
				SELF:OSFJSEQ:SERVER:SSQ:=oMS06:FIELDGET("SSQ")
				SELF:OSFJSEQ:SERVER:DESCRI:=oMS06:FIELDGET("DESCRI")
				
				SELF:OSFJSEQ:SERVER:CODMP01:=oMS06:FIELDGET("CODMP01")
				aRET:=VS3PRECO("E",oMS06:FIELDGET("CODMP01"),.F.)
				SELF:OSFJSEQ:SERVER:NOMMP01:=aRET[2]
                SELF:OSFJSEQ:SERVER:CODFOLHA:=aRET[4]				
				
				SELF:OSFJSEQ:SERVER:CODMP02:=oMS06:FIELDGET("CODMP02")
				aRET:=VS3PRECO("H",oMS06:FIELDGET("CODMP02"),.F.)				
				SELF:OSFJSEQ:SERVER:NOMMP02:=aRET[2]
				
				SELF:OSFJSEQ:SERVER:CODMP02B:=oMS06:FIELDGET("CODMP02B")
				aRET:=VS3PRECO("H",oMS06:FIELDGET("CODMP02B"),.F.)				
				SELF:OSFJSEQ:SERVER:NOMMP02B:=aRET[2]
				
				SELF:OSFJSEQ:SERVER:CODMP02C:=oMS06:FIELDGET("CODMP02C")
	        	aRET:=VS3PRECO("H",oMS06:FIELDGET("CODMP02C"),.F.)
				SELF:OSFJSEQ:SERVER:NOMMP02C:=aRET[2]
				
				SELF:OSFJSEQ:SERVER:CODMP02D:=oMS06:FIELDGET("CODMP02D")
				aRET:=VS3PRECO("H",oMS06:FIELDGET("CODMP02D"),.F.)				
				SELF:OSFJSEQ:SERVER:NOMMP02D:=aRET[2]
				
				SELF:OSFJSEQ:SERVER:CODMP03:=oMS06:FIELDGET("CODMP03")				
				aRET:=VS3PRECO("T",oMS06:FIELDGET("CODMP03"),.F.)									
				SELF:OSFJSEQ:SERVER:NOMMP03:=aRET[2]
				
				SELF:OSFJSEQ:SERVER:PCHORA:=oMS06:FIELDGET("PCHORA")
				SELF:OSFJSEQ:SERVER:AREA:=oMS06:FIELDGET("AREA")
				SELF:oSFJSEQ:SERVER:commit()
			ENDIF
  			oMS06:SKIP()	
   ENDDO
	SELF:oSFJSEQ:SERVER:resetnotification()
	SELF:oSFJSEQ:SERVER:notify(notifyappend)
	oMS06:CLOSE()
ENDIF
GRAVALOG(SELF:SERVER:OV,"IMP","ESP")		
   SELF:GRAVATUDO()

METHOD INCLUI2 
LOCAL nOV AS DWORD
//LOCAL oBUSCA AS XBUSCA
nOV:=SELF:SERVER:OV
SELF:oSFJSEQ:SERVER:GOBOTTOM()
SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJSEQ:SERVER:APPEND()
SELF:oSFJSEQ:SERVER:OV:=nOV
SELF:oSFJSEQ:SERVER:commit()
SELF:oSFJSEQ:SERVER:resetnotification()
SELF:oSFJSEQ:SERVER:notify(NOTIFYFILECHANGE)
SELF:oSFJSEQ:Browser:refresh()
   SELF:GRAVATUDO()
//oBUSCA:=XBUSCA{SELF,"Forneça Sub-Codigo Maquina","Confirme SubCodmarq",SELF:odcsub:TextValue}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF  oBUSCA:lOK
//	SELF:oDCSUB:TextValue:=oBUSCA:cBUSCA
//	SELF:SUBMAQ()
//ENDIF	

METHOD INCLUIR 
LOCAL nOV AS DWORD
LOCAL oBUSCA AS XBUSCA
LOCAL cTIPOENT AS STRING
cTIPOENT:="M"
nOV:=SELF:SERVER:OV


oBUSCA:=XBUSCA{SELF,"Forneca o Tipo","Digite o Tipo (M)atPrima (C)omponente (T)rat. ET(I)",cTIPOENT}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   cTIPOENT:=Upper(oBUSCA:cBUSCA)
ENDIF


SELF:oSFJVCE:SERVER:GOBOTTOM()
SELF:oSFJVCE:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVCE:SERVER:APPEND()
SELF:oSFJVCE:SERVER:FIELDPUT("OV",nOV)
SELF:oSFJVCE:SERVER:FIELDPUT("ORIGEM","Nacional")
SELF:oSFJVCE:SERVER:FIELDPUT("TIPOENT",Ctipoent)
SELF:oSFJVCE:SERVER:commit()
SELF:oSFJVCE:SERVER:resetnotification()
SELF:oSFJVCE:SERVER:notify(notifyappend)
SELF:OSFJVCE:GOTOP()
   SELF:GRAVATUDO()

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4,oVIABIII AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",5)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ESP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ESPMS03.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"ESPMS06.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
   RETU SELF
ENDIF
aDAD:={zCURINI,"VIABIII.DBF",zCURDIR}
oVIABIII:=USEREDE{aDAD}
IF oVIABIII:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
	oSERVE3:CLOSE()
   RETU SELF
ENDIF

aDAD:={zCURINI,"VIAREV.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
    oSERVE3:CLOSE()
	oSERVE2:CLOSE()
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF


oVIABIII:SetOrder(2)
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJVCE:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJVCE,"OV")
SELF:OSFJSEQ:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJSEQ,"OV")
SELF:OSFJVIII:USE(oVIABIII)
SELF:SetSelectiveRelation(oSFJVIII,"VIABILI")
SELF:oSFJVIII:VIEWTABLE()	


SELF:OSFJVIAREV:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJVIAREV,"VIABILI")
SELF:oSFJVIAREV:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJVIAREV:ViewTable()	


SELF:SHOW()		









METHOD NAC 
SELF:oSFJVCE:SERVER:FIELDPUT("ORIGEM","Nacional")	
   SELF:GRAVATUDO()

METHOD NOVOVIA 
//LOCAL nOV AS DWORD
LOCAL nITEM AS WORD
//nOV:=SELF:SERVER:OV
SELF:oSFJVIII:SERVER:GOBOTTOM()
nITEM:=SELF:oSFJVIII:SERVER:ITEM
nITEM++
SELF:oSFJVIII:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVIII:SERVER:APPEND()
SELF:oSFJVIII:SERVER:FIELDPUT("OV",SELF:SERVER:FIELDGET("VIABILI"))
SELF:oSFJVIII:server:FIELDPUT("ITEM",nITEM)
SELF:oSFJVIII:SERVER:commit()
SELF:oSFJVIII:SERVER:resetnotification()
SELF:oSFJVIII:SERVER:notify(notifyappend)
   SELF:GRAVATUDO()

METHOD POROV 
	SELF:KeyFind()
//	SELF:SERVER:SETORDER(1)

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIM2 
SELF:oSFJSEQ:Browser:SuspendUpdate()
IF ! SELF:oSFJSEQ:Server:Eof
    SELF:oSFJSEQ:SkipNext()
ENDIF
SELF:oSFJSEQ:Browser:RestoreUpdate()

METHOD PROXIMO 
SELF:oSFJVCE:Browser:SuspendUpdate()
IF ! SELF:oSFJVCE:Server:Eof
    SELF:oSFJVCE:SkipNext()
ENDIF
SELF:oSFJVCE:Browser:RestoreUpdate()

METHOD SITUACAOVIA 
IF SELF:oSFJVIII:server:SITUACAO="S"
   SELF:oSFJVIII:server:SITUACAO:="N"
ELSE
   SELF:oSFJVIII:server:FIELDPUT("SITUACAO","S")
   SELF:oSFJVIII:server:FIELDPUT("SITUSER",ZUSER)
   SELF:oSFJVIII:server:FIELDPUT("SITDATA",Today())
   SELF:oSFJVIII:server:FIELDPUT("SITHOTA",Time())
ENDIF
   SELF:GRAVATUDO()

METHOD SubMaq( ) 
LOCAL aDAD AS ARRAY
LOCAL oARQ AS  USEMANA5
LOCAL obusca AS xbusca
LOCAL lACHEI AS LOGIC
lACHEI:=.F.
IF Empty(Val(SELF:oDCSUB:TextValue))
   alert("Codigo Maquina Nao Preenchido","Erro Preenchimento")
   IF MDG("Limpar Informações da Maquina")
   	  SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP01","")
      SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP01","")
      SELF:oSFJSEQ:SERVER:FIELDPUT("CODFOLHA",0)
   ENDIF	
   RETU
ENDIF
aDAD:={zCURINI,"MP01",zCURDIR,aDIR}
oARQ:=USEMANA5{aDAD}
IF oARQ:USED
   oARQ:SetOrder(3)
   oARQ:GOTOP()
   IF oarq:Seek(Val(SELF:oDCSUB:TextValue))
      SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP01",oARQ:FIELDGET("CODIGO"))
      SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP01",oARQ:FIELDGET("NOME"))
      SELF:oSFJSEQ:SERVER:FIELDPUT("CODFOLHA",Val(SELF:oDCSUB:TextValue))
      lACHEI:=.T.
   ENDIF	
   OARQ:CLOSE()
   IF ! lACHEI
      alert("Sub Código Máquina Nao Cadastrado","Erro Preenchimento")
      RETU
   ELSE
      oBUSCA:=XBUSCA{SELF,"Forneça qtde Pc/Hora","Confirme PC/HORA",Str(SELF:oSFJSEQ:SERVER:FIELDGET("PCHORA"))}
      oBUSCA:lMES:=.T.
      oBUSCA:SHOW()
      IF oBUSCA:lOK
         SELF:oSFJSEQ:SERVER:FIELDPUT("PCHORA",INT(Val(oBUSCA:cBUSCA)))
      ENDIF
      oBUSCA:=XBUSCA{SELF,"Forneça Hora Ferramenta","Confirme HoraFerramenta",Str(SELF:oSFJSEQ:SERVER:FIELDGET("HRFER"))}
      oBUSCA:lMES:=.T.
      oBUSCA:SHOW()
      IF oBUSCA:lOK
         SELF:oSFJSEQ:SERVER:FIELDPUT("HRFER",INT(Val(oBUSCA:cBUSCA)))
      ENDIF
   ENDIF
ENDIF
SELF:GRAVATUDO()

METHOD TABULA2  
SELF:oSFJSEQ:VIEWTABLE()

METHOD TABULAR  
SELF:oSFJVCE:VIEWTABLE()

METHOD tabularVIA 
SELF:oSFJVIII:VIEWTABLE()	

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJSEQ:SERVER:COMMIT()
   SELF:oSFJVCE:SERVER:COMMIT()


METHOD VERPCP 
LOCAL oJAN AS XJPRO
oJAN:=XJPRO{SELF,SELF:SERVER:FIELDGET("CODIGO"),zcurINI,zcurDIR,adir}
oJAN:SHOW()


END CLASS
