CLASS XESF INHERIT xJEX

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,Oserve4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",7)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ESF.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD,,.T.}   //Leitura
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ESFMS03.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD,,.T.}   //Leitura
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"ESFMS06.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD,,.T.}   //Leitura
IF oSERVE3:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
   RETU SELF
ENDIF

aDAD:={zCURINI,"VIAREV.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
    oSERVE3:CLOSE()
	oSERVE2:CLOSE()
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF


SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJVCE:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJVCE,"OV")
SELF:oSFJVCE:Browser:SetStandardStyle(GBSREADONLY)
SELF:OSFJSEQ:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJSEQ,"OV")
SELF:oSFJSEQ:Browser:SetStandardStyle(GBSREADONLY)


SELF:OSFJVIAREV:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJVIAREV,"VIABILI")
SELF:oSFJVIAREV:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJVIAREV:ViewTable()	

SELF:SHOW()		

END CLASS
CLASS XESO INHERIT xJEX

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",8)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ESO.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD,,.T.}   //Leitura
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ESOMS03.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD,,.T.}    //Leitura
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"ESOMS06.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD,,.T.}    //Leitura
IF oSERVE3:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
   RETU SELF
ENDIF

aDAD:={zCURINI,"VIAREV.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
    oSERVE3:CLOSE()
	oSERVE2:CLOSE()
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF


SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJVCE:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJVCE,"OV")
SELF:oSFJVCE:Browser:SetStandardStyle(GBSREADONLY)
SELF:OSFJSEQ:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJSEQ,"OV")
SELF:oSFJSEQ:Browser:SetStandardStyle(GBSREADONLY)


SELF:OSFJVIAREV:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJVIAREV,"VIABILI")
SELF:oSFJVIAREV:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJVIAREV:ViewTable()	

SELF:SHOW()		

END CLASS
CLASS xjex INHERIT jex

METHOD APPEND(oOWNER) 
alert("Operação Bloqueada")	


METHOD Buscaov() 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD DELETE(oOWNER) 
alert("Operação Bloqueada")

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()


CONSTRUCTOR(oOWNER) 
SUPER(oOWNER)	
	

METHOD POROV 
SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJSEQ:SERVER:COMMIT()
   SELF:oSFJVCE:SERVER:Commit()



END CLASS
