PARTIAL CLASS TabControl1_Page1
METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("DESENHO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()
	

END CLASS
PARTIAL CLASS TabControl1_Page2
METHOD cmdFESP( ) 
SELF:server:FIELDPUT("FESP",SIMNAO(SELF:SERVER:FIELDGET("FESP")))	

METHOD cmdviAVEL( ) 
SELF:server:FIELDPUT("VIAVEL",SIMNAO(SELF:SERVER:FIELDGET("VIAVEL")))	

END CLASS
PARTIAL CLASS TabControl1_Page3
METHOD cmdMATM( ) 
SELF:server:FIELDPUT("MATM",SIMNAO(SELF:SERVER:FIELDGET("MATM")))	

METHOD cmdMATS( ) 
SELF:server:FIELDPUT("MATS",SIMNAO(SELF:SERVER:FIELDGET("MATS")))	

METHOD cmdTRATM( ) 
SELF:server:FIELDPUT("TRATM",SIMNAO(SELF:SERVER:FIELDGET("TRATM")))	

METHOD cmdTRATS( ) 
SELF:server:FIELDPUT("TRATS",SIMNAO(SELF:SERVER:FIELDGET("TRATS")))	

END CLASS
PARTIAL CLASS TabControl1_Page4
METHOD cmdDISPE( ) 
SELF:server:FIELDPUT("DISPE",SIMNAO(SELF:SERVER:FIELDGET("DISPE")))	

METHOD cmdREQC( ) 
SELF:server:FIELDPUT("REQC",SIMNAO(SELF:SERVER:FIELDGET("REQC")))	

METHOD cmdRISCO( ) 
SELF:server:FIELDPUT("RISCO",SIMNAO(SELF:SERVER:FIELDGET("RISCO")))	


END CLASS
