CLASS XASSESP INHERIT xJIMP
	

CONSTRUCTOR(oOWNER) 
LOCAL aDAD,aDA2 AS ARRAY
LOCAL aERRO AS ARRAY
IF ! entramenu("CUS",6)
	RETU SELF
ENDIF		
SUPER(oOWNER)
SELF:oDCGeraplan:VALUE:=.T.
SELF:SHOW()
IF ! SELF:LOk
	RETU SELF
ENDIF	
IF SELF:oDCGeraplan:VALUE
   aDAD:={"ESP.DBF","ESPMS03.DBF","ESPMS06.DBF"}
   aDA2:={"VPORC.DBF","VMS03.DBF","VMS06.DBF"}
   TRANSFER(aDAD,aDA2,SELF:CCODIGO,.F.,.T.,.F.)
   GRAVALOG(SELF:CCODIGO,"ASS","ESP")	
   aERRO:={}
   AAdd(aERRO," Produto:"+SELF:CCODIGO)
   AAdd(aERRO," Assinada: "+DToC(Today()))
   EMAILINT("CUSTO005",ZUSER,aERRO,ZCURINI,zCURDIR)	
ENDIF
aDAD:={"ESP.DBF","ESPMS03.DBF","ESPMS06.DBF"}
aDA2:={"ESF.DBF","ESFMS03.DBF","ESFMS06.DBF"}
TRANSFER(aDAD,aDA2,SELF:CCODIGO,.F.,.T.,.T.)
GRAVALOG(SELF:CCODIGO,"ASS","ESP")	


END CLASS
CLASS xJIMP INHERIT JIMP	

METHOD Cancelar( ) 
	lOK:=.F.
	SELF:EndDialog()

METHOD cmbBuscaVia( ) 
LOCAL nVIA AS DWORD	
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE
nVIA:=Val(SELF:oDCnVIABILIDADE:TextValue)
IF nVIA=0
	alert("Nº Viabilidade Em Branco")
	RETU SELF
ENDIF	
aDAD:={zCURINI,"VIABILI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF
oSERVER:GOTOP()
IF ! oSERVER:SEEK(nVIA)
   oSERVER:CLOSE()
   alert("Viabilidade Nao Encontrada")
   RETU SELF
ENDIF	
SELF:oDCCODIGO:TextValue:=oSERVER:FIELDGET("DESENHO")
oSERVER:CLOSE()

CONSTRUCTOR(oOWNER) 
SUPER(oOWNER)	
	

METHOD Ok(oOWNER) 
	IF ValType(oDCCODIGO:TEXTValue)="C"
		Lok:=.t.
	 	Ccodigo:=AllTrim(oDCCODIGO:TextValue)
  		SELF:EndDialog()	
	ELSE
      alert("Falta Preencher Codigo")
   ENDIF


METHOD PostInit(oParent,uExtra) 
	//Put your PostInit additions here
	 FabCenterWindow( SELF )
	RETURN NIL


END CLASS
CLASS XREVESP INHERIT xJIMP

CONSTRUCTOR(oOWNER) 
LOCAL aDAD,aDA2,aERRO AS ARRAY
IF ! entramenu("CUS",20)
	RETU SELF
ENDIF			
SUPER(oOWNER)
SELF:oDCGeraplan:HIDE()
SELF:SHOW()
IF ! SELF:lok
	RETU SELF
ENDIF	
aDAD:={"ESF.DBF","ESFMS03.DBF","ESFMS06.DBF"}
aDA2:={"ESP.DBF","ESPMS03.DBF","ESPMS06.DBF"}
TRANSFER(aDAD,aDA2,SELF:CCODIGO,.T.,.T.,.F.)
aDAD:={"ESF.DBF","ESFMS03.DBF","ESFMS06.DBF"}
aDA2:={"ESO.DBF","ESOMS03.DBF","ESOMS06.DBF"}
TRANSFER(aDAD,aDA2,SELF:CCODIGO,.F.,.T.,.T.)
aERRO:={}
AAdd(aERRO," Produto:"+SELF:CCODIGO)
AAdd(aERRO," Nova Revisao: "+DToC(Today()))
EMAILINT("CUSTO005",ZUSER,aERRO,ZCURINI,zCURDIR)	
GRAVALOG(SELF:CCODIGO,"REV","ESP")	



END CLASS
