CLASS XJCOM INHERIT ZJMT

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",10)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MT01",ZCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
IF PEGINIVAL(ZCURINI,"PRECOS","MANUAL")="S"
	SELF:oDCULTPRC:READONLY:=FALSE
    SELF:oDCULTPRC:ENABLE()
ENDIF	
SELF:SHOW()			

END CLASS
CLASS XJMP INHERIT ZJMT

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",9)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MU01",ZCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)

IF PEGINIVAL(ZCURINI,"PRECOS","MANUAL")="S"
	SELF:oDCULTPRC:READONLY:=FALSE
    SELF:oDCULTPRC:ENABLE()
ENDIF	
//SELF:oDCESTADO:READONLY:=FALSE
//SELF:oDCESTADO:ENABLE()
SELF:SHOW()			

END CLASS
CLASS XJMT INHERIT ZJMT

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("CUS",4)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ETI",ZCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS ZJMT INHERIT JMT

METHOD APPEND(oOWNER) 
alert("Operacao Bloqueada")	


METHOD buscaov( ) 
	SELF:KeyFind()

METHOD cmdCOPIA() 
SELF:SERVER:FIELDPUT("CUSTF",SELF:SERVER:FIELGET("ULTPRC"))

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CU","MT")	


METHOD DELETE(oOWNER) 
alert("Operação Bloqueada")



CONSTRUCTOR(Oowner) 
SUPER(Oowner)


METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
