CLASS XJMM INHERIT JMM

METHOD APPEND() 
alert("Operação Bloqueada")


METHOD buscacod( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MP","")	


METHOD DELETE(oOWNER) 
alert("Operação Bloqueada")

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("CUS",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MP01",zCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		

METHOD porcod( ) 
SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
