CLASS XJMK INHERIT JMK

METHOD APPEND() 
LOCAL nSEQ AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nSEQ:=SELF:Server:SEQ
nSEQ++
SUPER:append()
SELF:SERVER:FIELDPUT(#SEQ,nSEQ)
GRAVALOG(SELF:Server:SEQ,"INC","VMARK")	
RETURN

METHOD buscacod( ) 
	 SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CU","CUS")	


METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	GRAVALOG(SELF:Server:SEQ,"DEL","VMARK")	
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)	
ENDIF	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("CUS",14)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"VMARK.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		

METHOD porcod( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
