CLASS XJESC INHERIT ZJPO

METHOD Emailfim( ) 
SELF:SERVER:FIELDPUT("ELANUM",ZFOLHA)
SELF:SERVER:FIELDPUT("ELANOM",ZNOMEFOLHA)
SELF:SERVER:FIELDPUT("ELADAT",Today())
SELF:SERVER:FIELDPUT("ELAHOR",Time())	
SELF:GRAVATUDO()	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oserve4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",22)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ESC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ESCMS03.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"ESCMS06.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
   RETU SELF
ENDIF
aDAD:={zCURINI,"VIAREV.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
    oSERVE3:CLOSE()
	oSERVE2:CLOSE()
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF


SUPER(oOWNER,,oSERVER)
SELF:OSFJVCO:USE(oSERVE2)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SetSelectiveRelation(oSFJVCO,"OV")
SELF:OSFJSEQ:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJSEQ,"OV")


SELF:OSFJVIAREV:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJVIAREV,"VIABILI")
SELF:oSFJVIAREV:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJVIAREV:ViewTable()	

SELF:SHOW()			

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CU","AC")	


END CLASS
CLASS XJPO INHERIT ZJPO

METHOD Emailfim( ) 
LOCAL aERRO AS ARRAY	
aERRO:={}
AAdd(aERRO," Planilha Orçamento:"+StrTRIM(SELF:SERVER:FIELDGET("OV"),8,0))
AAdd(aERRO," Produto:"+SELF:SERVER:FIELDGET("CODIGO")+"-"+SELF:SERVER:FIELDGET("NOME"))
AAdd(aERRO," Cliente:"+SELF:SERVER:FIELDGET("COGCLI"))
AAdd(aERRO,"Concluida: "+DToC(Today()))
EMAILINT("CUS00006",ZUSER,aERRO,ZCURINI,zCURDIR)	
SELF:SERVER:FIELDPUT("ELANUM",ZFOLHA)
SELF:SERVER:FIELDPUT("ELANOM",ZNOMEFOLHA)
SELF:SERVER:FIELDPUT("ELADAT",Today())
SELF:SERVER:FIELDPUT("ELAHOR",Time())	
SELF:SERVER:Commit()
SELF:GRAVATUDO()

	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oserve4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"VPORC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"VMS03.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"VMS06.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
   RETU SELF
ENDIF
aDAD:={zCURINI,"VIAREV.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
    oSERVE3:CLOSE()
	oSERVE2:CLOSE()
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF


SUPER(oOWNER,,oSERVER)
SELF:OSFJVCO:USE(oSERVE2)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SetSelectiveRelation(oSFJVCO,"OV")
SELF:OSFJSEQ:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJSEQ,"OV")


SELF:OSFJVIAREV:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJVIAREV,"VIABILI")
SELF:oSFJVIAREV:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJVIAREV:ViewTable()	

SELF:SHOW()		


END CLASS
CLASS XJPOF INHERIT ZJPO

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"VFORC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"VFMS03.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"VFMS06.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
	oSERVER:Close() //Fecha Master
	oSERVE2:CLOSE()
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:OSFJVCO:USE(oSERVE2)
SELF:OSFJVCO:Browser:SetStandardStyle(gBsreadonly)

SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SetSelectiveRelation(oSFJVCO,"OV")
SELF:OSFJSEQ:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJSEQ,"OV")
SELF:OSFJSEQ:Browser:SetStandardStyle(gBsreadonly)


SELF:oCCImpEst:DISABLE()
SELF:oCCImpEst1:DISABLE()
SELF:oCCImpEst2:DISABLE()
SELF:oCCImportar:DISABLE()
SELF:oDCPVEN2:DISABLE()
SELF:oDCPREF:DISABLE()
SELF:oDCDLUC:DISABLE()
SELF:oDCDPRE:DISABLE()
SELF:oDCSUBTOT01:DISABLE()
SELF:oDCSUBTOT02:DISABLE()
SELF:oDCREV:DISABLE()
SELF:oCCescfor:DISABLE()
SELF:oCCesccod:DISABLE()
SELF:oCCescC:DISABLE()
SELF:oCCescM:DISABLE()
SELF:oCCescI:DISABLE()
SELF:oCCCmdtotal2:DISABLE()
SELF:oCCcmdtco:DISABLE()
SELF:oCCcmdtmp:DISABLE()
SELF:oCCcmdtTR:DISABLE()
SELF:oCCcmdETI:DISABLE()
SELF:oDCVFERHR:DISABLE()
SELF:oDCVFERID:DISABLE()
SELF:oCCcmdescmp01:DISABLE()
SELF:oCCcmdescmp02:DISABLE()
SELF:oCCcmdescmp02b:DISABLE()
SELF:oDCSUB:DISABLE()
SELF:oCCSubMaq:DISABLE()
SELF:oDCPROJETO:DISABLE()
SELF:oDCDUNS:DISABLE()
SELF:oDCNIVELDAT:DISABLE()
SELF:oDCVIGENDAT:DISABLE()
SELF:oDCDATA:DISABLE()
SELF:oDCUSUMEDIO:DISABLE()
SELF:oCCcmdPreco:DISABLE()
SELF:oDCvalpreco:DISABLE()
SELF:oCCCmdgrvprc:DISABLE()
SELF:oCCemailfim:DISABLE()
SELF:oDCELADAT:DISABLE()
SELF:oDCELANOM:DISABLE()
SELF:oDCELANUM:DISABLE()
SELF:oDCELAHOR:DISABLE()
SELF:oCCPEGCOD:DISABLE()
SELF:oCCPEGCLI:DISABLE()
SELF:oCCPEGMEN:DISABLE()
SELF:oDCPUF:DISABLE()
SELF:oDCPICM:DISABLE()
SELF:oDCPMAK:DISABLE()
//oDCJEPTAB:DISABLE()
SELF:oTPJETTAB_01:DISABLE()
SELF:oTPJETTAB_02:DISABLE()
SELF:oTPJETTAB_03:DISABLE()
SELF:oTPJEPTAB_PAGE4:DISABLE()
SELF:oCCpegpreco:DISABLE()
SELF:oDCPCPRGMED:DISABLE()
SELF:oCCImppfcom:DISABLE()
SELF:oCCImppfseq:DISABLE()
SELF:oDCTIPOIMP:DISABLE()
SELF:oCCchecktemp:DISABLE()
SELF:oDCppis:DISABLE()
SELF:oDCPCON:DISABLE()
SELF:oCCcmdCalcularB:DISABLE()
SELF:oDCTIPMEDIA:DISABLE()
SELF:oCCcmdpiscon:DISABLE()
SELF:oCCNac:DISABLE()
SELF:oCCImp:DISABLE()
SELF:oCCescT:DISABLE()
SELF:oCCVerPcp:DISABLE()
SELF:oDCPRRJ:DISABLE()
SELF:oDCLICM:DISABLE()
SELF:oCCcmdICM:DISABLE()
SELF:oDCPLUC:DISABLE()
SELF:oCCpluc10:DISABLE()
SELF:oCCpluc20:DISABLE()
SELF:oDCCAPPRO:DISABLE()
SELF:oDCVIABILI:DISABLE()
SELF:oDCDATACALC:DISABLE()
SELF:oCCDUPLICAR:DISABLE()
SELF:oCCcmdpiscon1:DISABLE()
SELF:oCCcmdpiscon2:DISABLE()
SELF:oCCcmdpiscon3:DISABLE()
SELF:oDCOVORI:DISABLE()
SELF:oCCcmdpfsn:DISABLE()
SELF:oDCPISCON:DISABLE()
SELF:oDCVTERI:DISABLE()
SELF:oDCVTERL:DISABLE()
SELF:oDCOVREV:DISABLE()
SELF:oDCCLIENTE:DISABLE()
//oDCtheGroupBox1 AS GROUPBOX
SELF:oDCOV:DISABLE()
SELF:oDCCOGCLI:DISABLE()
SELF:oDCLANU:DISABLE()
SELF:oDCLMES:DISABLE()
SELF:oDCLMIN:DISABLE()
SELF:oDCCODIGO:DISABLE()
SELF:oDCNOME:DISABLE()
SELF:oDCPRAZO:DISABLE()
SELF:oCCTABULAR:DISABLE()
SELF:oCCALTERAR:DISABLE()
SELF:oCCIncluir:DISABLE()
SELF:oCCExcluir:DISABLE()
SELF:oCCTABULA2:DISABLE()
SELF:oCCALTERA2:DISABLE()
SELF:oCCINCLUI2:DISABLE()
SELF:oCCEXCLUI2:DISABLE()
SELF:oCCcmdCalcularA:DISABLE()
SELF:oDCVCOM:DISABLE()
SELF:oDCVCOMI:DISABLE()
SELF:oDCVCOML:DISABLE()
SELF:oDCVFER:DISABLE()
SELF:oDCVMAT:DISABLE()
SELF:oDCVMATI:DISABLE()
SELF:oDCVMATL:DISABLE()
SELF:oDCVTER:DISABLE()
SELF:oDCVMAOO:DISABLE()
SELF:oDCVMAOM:DISABLE()
SELF:oDCVREJ:DISABLE()
SELF:oDCPMAR:DISABLE()
SELF:oDCFMAR:DISABLE()
SELF:oCCcmdMarkup:DISABLE()
SELF:oDCPVEN:DISABLE()
SELF:OCCCMDESCMP2:DISABLE()

SELF:SHOW()		

END CLASS
CLASS ZJPO INHERIT JPO

METHOD ALTERA2  
SELF:oSFJSEQ:VIEWFORM()

METHOD ALTERAR  
self:oSFJVCO:VIEWFORM()


METHOD ANTERIO2 
SELF:oSFJSEQ:Browser:SuspendUpdate()
IF SELF:oSFJSEQ:Server:BOF
    SELF:oSFJSEQ:SERVER:SkipPREVIOUS()
ENDIF
SELF:oSFJSEQ:Browser:RestoreUpdate()


METHOD ANTERIOR 
SELF:oSFJVCO:Browser:SuspendUpdate()
IF SELF:oSFJVCO:Server:BOF
     SELF:oSFJVCO:SERVER:SkipPREVIOUS()
ENDIF
SELF:oSFJVCO:Browser:RestoreUpdate()


METHOD APPEND() 
LOCAL nOV AS DWORD
LOCAL nVfERID,nPIS,nCONFINS AS FLOAT
LOCAL cPISCON AS STRING

nVFERID:=Val(PEGINIVAL(ZCURINI,"VALORES","VFERID"))
cPISCON:=PEGINIVAL(ZCURINI,"VALORES","PISCON")
nPIS:=Val(PEGINIVAL(ZCURINI,"VALORES","PIS"))
nCONFINS:=Val(PEGINIVAL(ZCURINI,"VALORES","CONFINS"))


SELF:SERVER:SUSPENDNOTIFICATION()
SELF:server:setorder(1)
SELF:server:gobottom()
nOV:=SELF:Server:OV
nOV++
SUPER:append()
SELF:SERVER:FIELDPUT("OV",nOV)
SELF:SERVER:FIELDPUT("VFERID",nVfERID)
SELF:SERVER:FIELDPUT("PRRJ",1)
SELF:SERVER:FIELDPUT("PLUC",10)
SELF:SERVER:FIELDPUT("LCIM",.T.)
SELF:SERVER:FIELDPUT("PISCON",cPISCON)
SELF:SERVER:FIELDPUT("PIS",nPIS)
SELF:SERVER:FIELDPUT("CONFINS",nCONFINS)
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
GRAVALOG(SELF:Server:OV,"INC","VPORC")	
SELF:GRAVATUDO()
RETURN

METHOD Buscaov() 
SELF:KeyFind()

METHOD checktemp 
LOCAL oMS06 AS USEMANA5
LOCAL aRET AS ARRAY
LOCAL cCHAVE,cMEDIA AS STRING
LOCAL oBUSCA AS XBUSCA

oBUSCA:=XBUSCA{SELF,"Escolher Media","(P)adrão (M)edia (I)nterna","P"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU	
ENDIF
cMEDIA:=oBUSCA:cBUSCA
IF Empty(Cmedia)
   cMEDIA:="P"
ELSE
   cMEDIA:=Upper(cMEDIA)
ENDIF	
IF ! cMEDIA $ "PMI"
   RETU
ENDIF	


aRET:={zCURINI,"MS06",zCURDIR,aDIR}
oMS06:=USEMANA5{aRET}
IF oMS06:nERRO#0
   RETU
ENDIF
SELF:oSFJSEQ:server:GOTOP()
WHILE !  oSFJSEQ:server:EOF
     cCHAVE:=PadR(SELF:SERVER:FIELDGET("CODIGO"),24)
     cCHAVE+=Str(SELF:OSFJSEQ:SERVER:FIELDGET("SEQ"),3)
     cCHAVE+=Str(SELF:OSFJSEQ:SERVER:FIELDGET("SSQ"),3)
	 oMS06:GOTOP()
	 IF oMS06:SEEK(CCHAVE)	
   	    DO CASE
	       CASE CMEDIA="P"
                SELF:OSFJSEQ:SERVER:FIELDPUT("PCMEDIA",INT(oMS06:FIELDGET("PCHORA")))
  		   CASE CMEDIA="M"
                SELF:OSFJSEQ:SERVER:FIELDPUT("PCMEDIA",INT(oMS06:FIELDGET("PCHORMED")))
 		   CASE CMEDIA="I"
                SELF:OSFJSEQ:SERVER:FIELDPUT("PCMEDIA",INT(oMS06:FIELDGET("PCHORAMD")))
     	ENDCASE		
        IF Empty(SELF:OSFJSEQ:SERVER:PCMEDIA)
           SELF:OSFJSEQ:SERVER:PCMEDIA:=oMS06:FIELDGET("PCHORA")
        ENDIF	
     ENDIF
	SELF:oSFJSEQ:server:SKIP()
ENDDO
oMS06:CLOSE()

SELF:CLIMEDMS01(SELF:SERVER:FIELDGET("CODIGO"))
SELF:zerApreco()
//SELF:GRAVATUDO()
	

METHOD CLIMEDMS01(cCODIGO) 
LOCAL oMS01 AS USEMANA5	
LOCAL aRET AS ARRAY
aRET:={zCURINI,"MS01",zCURDIR,aDIR}
oMS01:=USEMANA5{aRET}
IF oMS01:nERRO=0	
	oMS01:GOTOP()
	IF oMS01:SEEK(CCODIGO)
		SELF:SERVER:CLIENTE:=oMS01:FIELDGET("FORNECEDO")
		SELF:SERVER:NOME:=oMS01:FIELDGET("NOME")
		SELF:SERVER:FIELDPUT("PCPRGMED",oMS01:FIELDGET("PCPRGMED"))
	ENDIF		
	oMS01:CLOSE()
ENDIF	
aRET:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aRET[1]=.T.
   SELF:SERVER:COGCLI:=aRET[3]
ENDIF
SELF:GRAVATUDO()

	

METHOD CMDCALCULAR(nTIPO) 
LOCAL nVAL01,nVAL02,nVAL03,nVAL04,nVAL05,nVAL06,nVALH,nHRFER,nFATOR AS FLOAT
LOCAL nIMPOSTOS,nIMPTER AS FLOAT
LOCAL aVAL,aPRC AS ARRAY
LOCAL cPCHORA AS STRING

nHRFER:=0
cPCHORA:="PCHORA"
IF nTIPO=2
   cPCHORA:="PCMEDIA"	
ENDIF


IF Empty(SELF:SERVER:FIELDGET("PMAR"))
	alert("Sem % Markup")
	IF ! MDG("Continuar")
	   RETU
    ENDIF		
ENDIF	

IF Empty(SELF:SERVER:FIELDGET("PRRJ"))
	alert("Sem % Refugo Rejeição")
	IF ! MDG("Continuar")
	   RETU
    ENDIF		
ENDIF	

IF Empty(SELF:SERVER:FIELDGET("PLUC"))
	alert("Sem % Lucro")
	IF ! MDG("Continuar")
	   RETU
    ENDIF		
ENDIF	


IF Empty(SELF:SERVER:FIELDGET("PICM")) .AND. SELF:SERVER:FIELDGET("LICM")
	alert("ICMS Em Branco - Check Cliente/Markup")
	IF ! MDG("Continuar")
	   RETU
    ENDIF			
ENDIF	

//Materia Prima Componente
nIMPOSTOS:=0
nIMPOSTOS:=Val(PEGINIVAL(ZCURINI,"VALORES","ICM"))
IF SELF:SERVER:FIELDGET("PISCON")="S"
   nIMPOSTOS+=Val(PEGINIVAL(ZCURINI,"VALORES","PIS"))
   nIMPOSTOS+=Val(PEGINIVAL(ZCURINI,"VALORES","CONFINS"))
ENDIF

//Terceiros
nIMPTER:=0
IF SELF:SERVER:FIELDGET("PISCON")="S"
   nIMPTER+=Val(PEGINIVAL(ZCURINI,"VALORES","PIS"))
   nIMPTER+=Val(PEGINIVAL(ZCURINI,"VALORES","CONFINS"))
ENDIF		


SELF:POINTER:=POINTER{POINTERHOURGLASS}
IF SELF:server:LANU>0
   SELF:server:Lmes:=INT((SELF:server:Lanu)/12)
ENDIF

//Fixa Valores Iniciais
nVAL01:=0
nVAL02:=0
nVAL03:=0
nVAL04:=0
nVAL05:=0
nVAL06:=0


//Calculando a Composicao
SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVCO:server:GOTOP()
WHILE !  oSFJVCO:server:EOF
   IF ! Empty(SELF:oSFJVCO:SERVER:TIPOENT) .AND. ! Empty(SELF:oSFJVCO:SERVER:CODCOMP)
   	  aPRC:=VS3PRECO(SELF:oSFJVCO:SERVER:TIPOENT,SELF:oSFJVCO:SERVER:CODCOMP,.T.)	
      IF Empty(SELF:oSFJVCO:server:preco) .AND. aPRC[1]>0
         SELF:oSFJVCO:server:preco:=aPRC[1]
         SELF:oSFJVCO:server:ULTDATA:=aPRC[5]
         SELF:oSFJVCO:server:ULTUND:=aPRC[6]
      ENDIF	
      IF aPRC[1]>0
         IF aPRC[1]<>SELF:oSFJVCO:server:FIELDGET("preco")
            alert("Preco Calculo Diferente Ultimo Preço "+SELF:oSFJVCO:SERVER:CODCOMP)
            IF ! MDG("Atual->"+Str(aPRC[1],10,5)+" Informado-> "+Str(SELF:oSFJVCO:server:FIELDGET("preco"),10,5),"Atualizar")
               IF ! MDG("Continuar")
         	      SELF:POINTER:=POINTER{}
	              RETU
               ENDIF			
            ELSE
              SELF:oSFJVCO:server:preco:=aPRC[1]
              SELF:oSFJVCO:server:ULTDATA:=aPRC[5]
              SELF:oSFJVCO:server:ULTUND:=aPRC[6]
            ENDIF
         ENDIF	
      ENDIF
   ENDIF
   IF IsNumeric(SELF:oSFJVCO:server:qtdde) .and. IsNumeric(SELF:oSFJVCO:server:preco)
	  //IF SELF:oSFJVCO:server:TIPOENT=="T".AND.SELF:SERVER:FIELDGET("PISCON")="S"    //Terceiros
      //
      // ELSE
          SELF:oSFJVCO:server:TOTAL:=SELF:oSFJVCO:server:qtdde*SELF:oSFJVCO:server:preco
      // ENDIF
   ELSE
      SELF:oSFJVCO:server:TOTAL:=0
   ENDIF
   DO CASE
   	  CASE Empty(SELF:oSFJVCO:server:TIPOENT)
    	   alert("Tipo Em Branco: "+SELF:oSFJVCO:SERVER:CODCOMP)
           IF ! MDG("Continuar")
         	  SELF:POINTER:=POINTER{}
   	          RETU
           ENDIF			
	  CASE SELF:oSFJVCO:server:TIPOENT=="M" //MateriaPRima
 		   nVAL01+=SELF:oSFJVCO:server:TOTAL
  	  CASE SELF:oSFJVCO:server:TIPOENT=="C" //Componente
 		   nVAL02+=SELF:oSFJVCO:server:TOTAL
  	  CASE SELF:oSFJVCO:server:TIPOENT=="T"     //Terceiros
 		   nVAL03+=SELF:oSFJVCO:server:TOTAL
  	  CASE SELF:oSFJVCO:server:TIPOENT=="I"     //ETI
 		   nVAL03+=SELF:oSFJVCO:server:TOTAL
  	  CASE SELF:oSFJVCO:server:TIPOENT=="F"  //Ferramenta		
 		   nVAL04+=SELF:oSFJVCO:server:TOTAL
    ENDCASE
	SELF:oSFJVCO:server:SKIP()
ENDDO
SELF:oSFJVCO:server:GOTOP()
SELF:oSFJVCO:SERVER:resetnotification()
SELF:oSFJVCO:SERVER:Notify(NOTIFYFILECHANGE)

 //Calculando a Sequencia
 SELF:oSFJSEQ:server:SUSPENDNOTIFICATION()
 SELF:oSFJSEQ:server:GOTOP()
 WHILE !  oSFJSEQ:server:EOF
     IF ! Empty(SELF:oSFJSEQ:SERVER:CODFOLHA)
     	IF Empty(SELF:oSFJSEQ:SERVER:PCHORA)
     	   alert("SudCod-Maquina Sem Pc/HORA:"+Str(SELF:oSFJSEQ:SERVER:CODFOLHA))
   	       IF ! MDG("Continuar")
	          RETU
           ENDIF			
     	ENDIF
 	 ENDIF
     nVALH:=0
     IF ! Empty(SELF:oSFJSEQ:SERVER:FIELDGET(cPCHORA))
        nVALH:=FloatFormat(1/SELF:oSFJSEQ:SERVER:FIELDGET(cPCHORA),10,8)
        SELF:oSFJSEQ:SERVER:FIELDPUT("qtdde",1/SELF:oSFJSEQ:SERVER:FIELDGET(cPCHORA))
     ELSE
        SELF:oSFJSEQ:SERVER:FIELDPUT("qtdde",0)
     ENDIF
     IF ! Empty(SELF:oSFJSEQ:SERVER:CODMP01)
     	IF Empty(SELF:oSFJSEQ:SERVER:PCHORA)
     	   alert("Maquina Sem Pc/HORA:"+SELF:oSFJSEQ:SERVER:CODMP01)
   	       IF ! MDG("Continuar")
	          RETU
           ENDIF			
     	ENDIF
        aVAL:=VS3PRECO("E",SELF:oSFJSEQ:SERVER:CODMP01,.F.) //Equipamento

        IF aVAL[1]>0
           IF aVAL[1]<>SELF:oSFJSEQ:server:FIELDGET("preco")
              alert("Preco Calculo Diferente Ultimo Preço "+SELF:oSFJSEQ:SERVER:CODMP01)
              IF ! MDG("Atual->"+Str(aVAL[1],10,5)+" Informado-> "+Str(SELF:oSFJSEQ:server:FIELDGET("preco"),10,5),"Atualizar")
                 IF ! MDG("Continuar")
         	        SELF:POINTER:=POINTER{}
  	                RETU
                 ENDIF			
              ELSE
                 SELF:oSFJSEQ:SERVER:FIELDPUT("PRECO",aVAL[1])
                 SELF:oSFJSEQ:SERVER:FIELDPUT("TOTAL",aVAL[1]*nVALH)
                 SELF:oSFJSEQ:SERVER:FIELDPUT("CODFOLHA",aVAL[4])
              ENDIF	
           ENDIF
        ELSE
           alert("Preco Maquina Nao Encontrado:"+SELF:oSFJSEQ:SERVER:CODMP01)
           IF MDG("Zerar Valores Preenchidos")
              SELF:oSFJSEQ:SERVER:FIELDPUT("PRECO",0)
              SELF:oSFJSEQ:SERVER:FIELDPUT("TOTAL",0)
           ENDIF
           IF ! MDG("Continuar")
         	  SELF:POINTER:=POINTER{}
              RETU
           ENDIF
        ENDIF	
        nFATOR:=SELF:oSFJSEQ:SERVER:FIELDGET("FATOR")
        IF nFATOR<>0
           SELF:oSFJSEQ:SERVER:FIELDPUT("TOTAL",Round(nFATOR*nVALH*SELF:oSFJSEQ:SERVER:FIELDGET("PRECO"),4))
           nVAL06+=Round(nFATOR*nVALH*SELF:oSFJSEQ:SERVER:FIELDGET("PRECO"),4)
        ELSE
           SELF:oSFJSEQ:SERVER:FIELDPUT("TOTAL",Round(nVALH*SELF:oSFJSEQ:SERVER:FIELDGET("PRECO"),4))
           nVAL06+=Round(nVALH*SELF:oSFJSEQ:SERVER:FIELDGET("PRECO"),4)
        ENDIF
		SELF:OSFJSEQ:SERVER:COGMP01:=aVAL[7]				
     ENDIF
     IF ! Empty(SELF:oSFJSEQ:SERVER:CODMP02)
        aVAL:=VS3PRECO("H",SELF:oSFJSEQ:SERVER:CODMP02,.F.) //Homem
        nVAL05+=Round(nVALH*aVAL[1],4)
     ENDIF
     IF ! Empty(SELF:oSFJSEQ:SERVER:CODMP02B)
        aVAL:=VS3PRECO("H",SELF:oSFJSEQ:SERVER:CODMP02B,.F.) //2o Homem
        nVAL05+=Round(nVALH*aVAL[1],4)
     ENDIF
     IF ! Empty(SELF:oSFJSEQ:SERVER:CODMP03) //Terceiros
        aVAL:=VS3PRECO("T",SELF:oSFJSEQ:SERVER:CODMP03,.F.)
        nVAL03+=Round(nVALH*aVAL[1],4)
     ENDIF
     nHRFER+=SELF:oSFJSEQ:SERVER:HRFER
	 SELF:oSFJSEQ:server:SKIP()
ENDDO
SELF:oSFJSEQ:server:GOTOP()
SELF:oSFJSEQ:server:resetnotification()
SELF:oSFJSEQ:SERVER:Notify(NOTIFYFILECHANGE)


nVAL04+=nHRFER*SELF:SERVER:VFERID


//Grava a Composiçao/Sequencia
SELF:SERVER:VMAT:=nVAL01
SELF:SERVER:VCOM:=nVAL02
SELF:SERVER:VTER:=nVAL03
SELF:SERVER:VFER:=nVAL04
SELF:SERVER:VMAOO:=nVAL05
SELF:SERVER:VMAOM:=nVAL06
SELF:SERVER:VFERHR:=nHRFER			


DO CASE
   CASE SELF:server:VCOM>0
        SELF:server:VCOMI:=Round((SELF:server:VCOM)*(nIMPOSTOS/100),4)
        SELF:server:VCOML:=SELF:SERVER:VCOM-SELF:SERVER:VCOMI
   CASE SELF:server:VCOM<0
        SELF:server:VCOMI:=Round((SELF:server:VCOM)*(nIMPOSTOS/100),4)
        SELF:server:VCOML:=SELF:SERVER:VCOM+SELF:SERVER:VCOMI
   OTHERWISE
        SELF:server:VCOMI:=0
        SELF:server:VCOML:=0
ENDCASE
DO CASE
   CASE SELF:server:VMAT>0
        SELF:server:VMATI:=Round((SELF:server:VMAT)*(nIMPOSTOS/100),4)
        SELF:server:VMATL:=SELF:SERVER:VMAT-SELF:SERVER:VMATI
   CASE SELF:server:VMAT<0
        SELF:server:VMATI:=Round((SELF:server:VMAT)*(nIMPOSTOS/100),4)
        SELF:server:VMATL:=SELF:SERVER:VMAT+SELF:SERVER:VMATI
   OTHERWISE
        SELF:server:VMATI:=0
        SELF:server:VMATL:=0
ENDCASE
DO CASE
   CASE SELF:server:VTER>0
       SELF:server:VTERI:=Round((SELF:server:VTER)*(nIMPTER/100),4)
       SELF:server:VTERL:=SELF:SERVER:VTER-SELF:SERVER:VTERI
   CASE SELF:server:VTER<0
       SELF:server:VTERI:=Round((SELF:server:VTER)*(nIMPTER/100),4)
       SELF:server:VTERL:=SELF:SERVER:VTER+SELF:SERVER:VTERI
   OTHERWISE
      SELF:server:VTERI:=0
      SELF:server:VTERL:=0
ENDCASE

SELF:SERVER:SUBTOT01:=SELF:SERVER:VCOML+SELF:SERVER:VMATL+SELF:SERVER:VTERL+;
SELF:SERVER:VMAOO+SELF:SERVER:VMAOM
IF SELF:SERVER:SUBTOT01>0
   SELF:server:vrej:=Round(SELF:SERVER:SUBTOT01*SELF:SERVER:PRRJ/100,4)
ELSE
   SELF:server:vrej:=0
ENDIF						
SELF:SERVER:SUBTOT02:=SELF:SERVER:SUBTOT01+SELF:SERVER:VREJ
IF SELF:SERVER:SUBTOT02>0 .AND. SELF:SERVER:PMAR>0
   SELF:SERVER:FMAR:=Round(100/(100-SELF:SERVER:PMAR) ,4)
   SELF:server:vMAR:=Round(SELF:SERVER:SUBTOT02*SELF:SERVER:FMAR,4)
ELSE
   SELF:server:vMAR:=0
ENDIF
IF SELF:server:vMAR>0
   SELF:SERVER:PVEN:=Round(SELF:server:vMAR,4)
ELSE
   SELF:SERVER:PVEN:=Round(SELF:SERVER:SUBTOT02,4)
ENDIF	
IF SELF:server:PVEN>0
   SELF:SERVER:PVEN2:=Round(SELF:server:PVEN*((100-PICM)/100),4)
ELSE
   SELF:SERVER:PVEN2:=0
ENDIF	
IF SELF:server:PVEN>0 .AND. SELF:server:PREF>0
   //Calcular Markup pelo preco de vendas
   nVAL01:=SELF:server:PREF*SELF:SERVER:PMAR/100	
   //Soma o Markup ao Preco Industrial
   nVAL02:=SELF:server:PVEN+nVAL01
   //Calcula a Diferença (Lucro)
   nVAL03:=SELF:server:PREF-nVAL02
   IF nVAL03>0		 //Preço de Venda Referente ao Lucro
	  SELF:SERVER:DLUC:=Round(nVAL03/SELF:SERVER:PREF*100,4)-100
	  SELF:SERVER:DPRE:=0
   ELSE
	  SELF:SERVER:DPRE:=Round(SELF:SERVER:PREF/nVAL03*100,4)-100
   	  SELF:SERVER:DLUC:=0		
   ENDIF	
ENDIF	
IF nTIPO=1
   SELF:SERVER:FIELDPUT("TIPMEDIA","H")	
ELSE
   SELF:SERVER:FIELDPUT("TIPMEDIA","M")		
ENDIF
SELF:SERVER:FIELDPUT("DATACALC",Today())		
AltD()

nVAL01:=SELF:SERVER:FIELDGET("PPIS")+SELF:SERVER:FIELDGET("PICM")+SELF:SERVER:FIELDGET("PCON")
nVAL02:=Round(SELF:SERVER:FIELDGET("PVEN")*nVAL01/100,4)
SELF:SERVER:FIELDPUT("VSIMP",SELF:SERVER:FIELDGET("PVEN")-nVAL02)

SELF:SERVER:FIELDPUT("DATACALC",Today())		

SELF:GRAVATUDO()
SELF:POINTER:=POINTER{}


METHOD CMDCALCULARA() 
SELF:CMDCALCULAR(1)

METHOD CMDCALCULARB() 
SELF:CMDCALCULAR(2)

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD cmdescmp01() 
LOCAL oESCMP01 AS Xescolhemp
LOCAL oBUSCA AS XBUSCA
oESCMP01:=Xescolhemp{SELF,"E"}
oESCMP01:SHOW()
IF oESCMP01:ARETU[1]=.T.
   SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP01",oESCMP01:aRETU[2])
   SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP01",oESCMP01:aRETU[3])
   SELF:oSFJSEQ:SERVER:FIELDPUT("CODFOLHA",oESCMP01:aRETU[5])
   oBUSCA:=XBUSCA{SELF,"Forneca qtde Pc/Hora","Confirme PC/HORA",Str(SELF:oSFJSEQ:SERVER:FIELDGET("PCHORA"))}
   oBUSCA:lMES:=.T.
   oBUSCA:SHOW()
   IF oBUSCA:lOK
      SELF:oSFJSEQ:SERVER:FIELDPUT("PCHORA",INT(Val(oBUSCA:cBUSCA)))
   ENDIF
   SELF:zerApreco()
ENDIF


METHOD cmdescMP02() 
LOCAL oESCMP02 AS Xescolhemp
oESCMP02:=Xescolhemp{SELF,"H"}
oESCMP02:SHOW()
IF oESCMP02:ARETU[1]=.T.
   SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP02",oESCMP02:aRETU[2])
    SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP02",oESCMP02:aRETU[3])
    SELF:zerApreco()
ENDIF



METHOD cmdescMP02B() 
LOCAL oESCMP02 AS Xescolhemp
oESCMP02:=Xescolhemp{SELF,"H"}
oESCMP02:SHOW()
IF oESCMP02:ARETU[1]=.T.
     SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP02B",oESCMP02:aRETU[2])
     SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP02B",oESCMP02:aRETU[3])
    SELF:zerApreco()
ENDIF



METHOD cmdescmp2( ) 
LOCAL oESC AS XESCNUM
oESC:=XESCNUM{SELF,"FLUXO.DBF"}
oESC:SHOW()
IF oESC:LOK
     SELF:oSFJSEQ:SERVER:FIELDPUT("FLUXO",oESC:NUMERO)
ENDIF
	

METHOD cmdETI( ) 
	 SELF:oSFJVCO:SERVER:TIPOENT:="I"

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD Cmdgrvprc( ) 
LOCAL aPRC AS ARRAY	
aPRC:=VS3PRECO(SELF:oSFJVCO:SERVER:TIPOENT,SELF:oSFJVCO:SERVER:CODCOMP,.T.)	
IF aPRC[1]>0
   SELF:oSFJVCO:server:preco:=aPRC[1]
   SELF:oSFJVCO:server:ULTDATA:=aPRC[5]
   SELF:oSFJVCO:server:ULTUND:=aPRC[6]
ELSE
  IF SELF:valpreco>0
     SELF:oSFJVCO:server:preco:=SELF:valpreco
     SELF:oSFJVCO:server:ULTDATA:=Today()
  ENDIF
ENDIF	
SELF:cmdtotal() //Ja Chama Zerar e Gravatudo em sequencia
//SELF:zerApreco()
//SELF:GRAVATUDO()

METHOD cmdICM( ) 
IF SELF:SERVER:FIELDGET("LICM")
   SELF:SERVER:FIELDPUT("LICM",.F.)
   SELF:SERVER:FIELDPUT("PICM",0)
ELSE
   SELF:SERVER:FIELDPUT("LICM",.T.)
ENDIF	
SELF:cmdMarkup(.F.)
//SELF:GRAVATUDO()

METHOD cmdMarkup(lTIPO) 
LOCAL nMAR,nICMS,nTOT AS FLOAT
//LOCAL oSERVER AS USEREDE
IF ValType(lTIPO)#"L"
   lTIPO:=.T.
ENDIF	
IF lTIPO
   SELF:PEGCLI()
ENDIF
nMAR:=PEGMARKUP()	
IF nMAR>0
   SELF:SERVER:FIELDPUT("PMAK",nMAR)
ENDIF
nICMS:=PEGICMS(SELF:SERVER:FIELDGET("PUF"))	
IF nICMS>0 .AND. SELF:SERVER:FIELDGET("LICM")
   SELF:SERVER:FIELDPUT("PICM",nICMS)
ENDIF
IF ! SELF:SERVER:FIELDGET("LICM")
   SELF:SERVER:FIELDPUT("PICM",0)
ENDIF	
nTOT:=SELF:SERVER:FIELDGET("PICM")
nTOT+=SELF:SERVER:FIELDGET("PMAK")
nTOT+=SELF:SERVER:FIELDGET("PLUC")
nTOT+=SELF:SERVER:FIELDGET("PPIS")
nTOT+=SELF:SERVER:FIELDGET("PCON")
SELF:SERVER:FIELDPUT("PMAR",nTOT)
IF SELF:SERVER:SUBTOT02>0 .AND. SELF:SERVER:PMAR>0
   SELF:SERVER:FMAR:=Round(100/(100-SELF:SERVER:PMAR) ,4)
ENDIF
SELF:SERVER:FIELDPUT("VMAR",0)
SELF:zerApreco()
//SELF:GRAVATUDO()

METHOD cmdpfsn( ) 
LOCAL cTIPO AS STRING
cTIPO:=	SELF:SERVER:FIELDGET("PISCON")
//alert(cTIPO)
cTIPO:=SIMNAO(cTIPO)
//alert(cTIPO)
SELF:server:FIELDPUT("PISCON",cTIPO)	
SELF:SERVER:Commit()		
//alert(SELF:SERVER:FIELDGET("PISCON"))
SELF:zerApreco()

METHOD cmdpiscon( ) 
	SELF:server:FIELDPUT("ppis",.65)
	SELF:server:FIELDPUT("pcon",3)
	SELF:cmdMarkup(.F.)


METHOD cmdpiscon1( ) 
	SELF:server:FIELDPUT("ppis",1.65)
	SELF:server:FIELDPUT("pcon",7.6)
	SELF:cmdMarkup(.F.)


METHOD cmdpiscon2( ) 
LOCAL nPIS,nFIN AS FLOAT	
LOCAL cCLIENTE AS STRING
LOCAL cTEM AS STRING

cCLIENTE:=AllTrim(Str(SELF:SERVER:FIELDGET("CLIENTE")))



cTEM:=PEGINIVAL(ZCURINI,cCLIENTE,"TEM")
IF CTEM="SIM"
   nPIS:=Val(PEGINIVAL(ZCURINI,cCLIENTE,"PIS"))
   nFIN:=Val(PEGINIVAL(ZCURINI,cCLIENTE,"CONFINS"))
   SELF:server:FIELDPUT("ppis",nPIS)
   SELF:server:FIELDPUT("pcon",nFIN)
ELSE
   alert("Ver Custo.ini para especifar aliquota Para o Cliente")
ENDIF
SELF:cmdMarkup(.F.)


METHOD cmdpiscon3( ) 
    SELF:server:FIELDPUT("ppis",0)
	SELF:server:FIELDPUT("pcon",0)
	SELF:cmdMarkup(.F.)


METHOD cmdPreco( ) 
LOCAL aVAL AS ARRAY	
aVAL:=VS3PRECO(SELF:oSFJVCO:SERVER:TIPOENT,SELF:oSFJVCO:SERVER:CODCOMP,.T.)
SELF:valpreco:=aVAL[1]
SELF:GRAVATUDO()

METHOD cmdtCO() 
     SELF:oSFJVCO:SERVER:TIPOENT:="C"	
     SELF:GRAVATUDO()

METHOD cmdtETI() 
     SELF:oSFJVCO:SERVER:TIPOENT:="I"	
     SELF:GRAVATUDO()

METHOD cmdtMP() 
     SELF:oSFJVCO:SERVER:TIPOENT:="M"	
     SELF:GRAVATUDO()

METHOD CMDTOTAL 
     IF SELF:oSFJVCO:SERVER:QTDDE=0
          SELF:oSFJVCO:SERVER:QTDDE:=1
     ENDIF
     IF SELF:oSFJVCO:SERVER:PRECO=0
          SELF:oSFJVCO:SERVER:PRECO:=1
     ENDIF
     IF IsNumeric(SELF:oSFJVCO:SERVER:PRECO) .AND. IsNumeric(SELF:oSFJVCO:SERVER:QTDDE)
        SELF:oSFJVCO:SERVER:TOTAL:=SELF:oSFJVCO:SERVER:PRECO*SELF:oSFJVCO:SERVER:QTDDE
    ELSE
        SELF:oSFJVCO:server:TOTAL:=0
     ENDIF
 SELF:zerApreco()
// SELF:GRAVATUDO()

METHOD CMDTOTAL2 
	SELF:CMDTOTAL()

METHOD cmdtTR() 
     SELF:oSFJVCO:SERVER:TIPOENT:="T"	
     SELF:GRAVATUDO()

METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	GRAVALOG(SELF:Server:OV,"DEL","VPORC")	
	SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJVCO:server:GOTOP()
	WHILE !  oSFJVCO:server:EOF
		SELF:oSFJVCO:server:DELETE()
		SELF:oSFJVCO:server:SKIP()
	ENDDO
    SELF:oSFJVCO:server:GOTOP()
	SELF:oSFJVCO:SERVER:resetnotification()


	SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
	SELF:oSFJSEQ:server:GOTOP()
	WHILE !  oSFJSEQ:server:EOF
		SELF:oSFJSEQ:server:DELETE()
		SELF:oSFJSEQ:server:SKIP()
	ENDDO
   SELF:oSFJSEQ:server:GOTOP()
	SELF:oSFJSEQ:SERVER:resetnotification()
	
	SELF:server:delete()
	SELF:server:unlock()
	IF ! SELF:SERVER:BOF
   	SELF:server:skip(-1)
   ENDIF	
	
ENDIF
SELF:GRAVATUDO()

METHOD Duplicar() 
LOCAL nOV,nOVORI AS DWORD
LOCAL nFIELD,J,K AS WORD
LOCAL aITECOM,aITESEQ,aTMP,aDADOS AS ARRAY

IF ! MDG("Duplicar "+Str(SELF:SERVER:FIELDGET("OV")))	
   RETU
ENDIF
	

nFIELD:=SELF:SERVER:FCOUNT
nOV:=SELF:Server:FIELDGET("OV")
nOVORI:=nOV
aDADOS:={}
FOR J:=1 TO nFIELD
    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
NEXT J

aITECOM:={}
nFIELD:=SELF:oSFJVCO:server:FCOUNT
SELF:oSFJVCO:server:GOTOP()
WHILE ! oSFJVCO:server:EOF
    aTMP:={}
    FOR J:=1 TO nFIELD
       AAdd(aTMP,SELF:oSFJVCO:server:FIELDGET(J))
    NEXT J
    AAdd(aITECOM,aTMP)
   SELF:oSFJVCO:server:SKIP()
ENDDO

aITESEQ:={}
nFIELD:=SELF:oSFJSEQ:server:FCOUNT
SELF:oSFJSEQ:server:GOTOP()
WHILE ! oSFJSEQ:server:EOF
    aTMP:={}
    FOR J:=1 TO nFIELD
       AAdd(aTMP,SELF:oSFJSEQ:server:FIELDGET(J))
    NEXT J
    AAdd(aITESEQ,aTMP)
   SELF:oSFJSEQ:server:SKIP()
ENDDO
SELF:server:setorder(1)
SELF:server:gobottom()
nOV:=SELF:Server:OV
nOV++
SUPER:SERVER:APPEND()
SELF:SERVER:FIELDPUT("OV",nOV)   //Grava Fixar Numero
SELF:SERVER:Commit()
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    SELF:SERVER:FIELDPUT(J,aDADOS[J])
NEXT J
SELF:SERVER:FIELDPUT("OV",nOV)
SELF:SERVER:FIELDPUT("OVORI",nOVORI)
SELF:server:FIELDPUT("VIABILI",0)
SELF:server:FIELDPUT("OVREV","")
SELF:SERVER:Commit()

SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
nFIELD:=SELF:oSFJVCO:server:FCOUNT
FOR K:=1 TO ALen(aITECOM)
    SELF:oSFJVCO:server:APPEND()
    FOR J:=1 TO nFIELD
        SELF:oSFJVCO:server:FIELDPUT(J,aITECOM[K][J])
    NEXT J
    SELF:oSFJVCO:server:FIELDPUT("OV",nOV)
NEXT K
SELF:oSFJVCO:Commit()
SELF:oSFJVCO:SERVER:resetnotification()
SELF:oSFJVCO:SERVER:notify(NOTIFYFILECHANGE)




SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
nFIELD:=SELF:oSFJSEQ:server:FCOUNT
FOR K:=1 TO ALen(aITESEQ)
    SELF:oSFJSEQ:server:APPEND()
    FOR J:=1 TO nFIELD
        SELF:oSFJSEQ:server:FIELDPUT(J,aITESEQ[K][J])
    NEXT J
    SELF:oSFJSEQ:server:FIELDPUT("OV",nOV)
NEXT K
SELF:oSFJSEQ:Commit()
SELF:oSFJSEQ:SERVER:resetnotification()
SELF:oSFJSEQ:SERVER:notify(NOTIFYFILECHANGE)


SELF:server:gotop()
SELF:server:gobottom()
//SELF:zerApreco()
SELF:GRAVATUDO()
alert("Duplicada "+Str(nOV)+" para "+Str(SELF:SERVER:FIELDGET("OV")) )	
RETURN



METHOD escC() 
LOCAL oESCMT01 AS Xescolhemp
oESCMT01:=Xescolhemp{SELF,"C"}
oESCMT01:SHOW()
IF oESCMT01:ARETU[1]=.T.
     SELF:oSFJVCO:SERVER:TIPOENT:="C"
     SELF:oSFJVCO:SERVER:CODCOMP:=oESCMT01:aRETU[2]
     SELF:oSFJVCO:SERVER:NOMECOMP:=oESCMT01:aRETU[3]
     SELF:oSFJVCO:SERVER:PRECO:=oESCMT01:aRETU[4]
     SELF:CMDTOTAL() //Ja Chama Zerar e Gravatudo em sequencia
ENDIF



METHOD esccod() 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("NOME",oESC:NOME)
ENDIF
SELF:GRAVATUDO()

METHOD ESCFOR 
LOCAL oESC AS XESCNUM	
//LOCAL aFORN AS ARRAY
oESC:=XESCNUM{SELF,"MA01.DBF",3}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:PEGCLI()
ENDIF

METHOD EscI() 
LOCAL oESCMP03 AS Xescolhemp
oESCMP03:=Xescolhemp{SELF,"I"}
oESCMP03:SHOW()
IF oESCMP03:ARETU[1]=.T.
     SELF:oSFJVCO:SERVER:TIPOENT:="I"
     SELF:oSFJVCO:SERVER:CODCOMP:=oESCMP03:aRETU[2]
     SELF:oSFJVCO:SERVER:NOMECOMP:=oESCMP03:aRETU[3]
     SELF:oSFJVCO:SERVER:PRECO:=oESCMP03:aRETU[4]
     SELF:CMDTOTAL()      //Ja Chama Zerar e Gravatudo em sequencia
ENDIF


METHOD escM() 
LOCAL oESCMU01 AS Xescolhemp
oESCMU01:=Xescolhemp{SELF,"M"}
oESCMU01:SHOW()
IF oESCMU01:ARETU[1]=.T.
     SELF:oSFJVCO:SERVER:TIPOENT:="M"
     SELF:oSFJVCO:SERVER:CODCOMP:=oESCMU01:aRETU[2]
     SELF:oSFJVCO:SERVER:NOMECOMP:=oESCMU01:aRETU[3]
     SELF:oSFJVCO:SERVER:PRECO:=oESCMU01:aRETU[4]
     SELF:CMDTOTAL()      //Ja Chama Zerar e Gravatudo em sequencia
ENDIF

METHOD EscT() 
LOCAL oESCMP03 AS Xescolhemp
oESCMP03:=Xescolhemp{SELF,"T"}
oESCMP03:SHOW()
IF oESCMP03:ARETU[1]=.T.
     SELF:oSFJVCO:SERVER:TIPOENT:="T"
     SELF:oSFJVCO:SERVER:CODCOMP:=oESCMP03:aRETU[2]
     SELF:oSFJVCO:SERVER:NOMECOMP:=oESCMP03:aRETU[3]
     SELF:oSFJVCO:SERVER:PRECO:=oESCMP03:aRETU[4]
     SELF:CMDTOTAL()  //Ja Chama Zerar e Gravatudo em sequencia
ENDIF

METHOD EXCLUI2 
IF ! MDG("Apagar Registro") .AND. SELF:oSFJSEQ:server:LockCurrentRecord()
   RETU
ENDIF
SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJSEQ:server:delete()
SELF:oSFJSEQ:server:unlock()
SELF:oSFJSEQ:SERVER:resetnotification()
SELF:oSFJSEQ:SERVER:notify(notifyfilechange)
SELF:oSFJSEQ:server:GOTOP()		
WHILE ! SELF:oSFJSEQ:serveR:EOf
	SELF:oSFJSEQ:server:Skip()
ENDDO		
SELF:oSFJSEQ:server:GOTOP()
SELF:oSFJSEQ:Browser:refresH()
SELF:zerApreco()

METHOD EXCLUIR 
IF ! MDG("Apagar Registro") .AND. SELF:oSFJVCO:server:LockCurrentRecord()
   RETU
ENDIF
SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVCO:server:delete()
SELF:oSFJVCO:server:unlock()
SELF:oSFJVCO:SERVER:resetnotification()
SELF:oSFJVCO:SERVER:notify(notifyfilechange)
SELF:oSFJVCO:server:GOTOP()		
WHILE ! SELF:oSFJVCO:serveR:EOf
	SELF:oSFJVCO:server:Skip()
ENDDO		
SELF:oSFJVCO:server:GOTOP()
SELF:oSFJVCO:Browser:refresH()
SELF:zerApreco()

METHOD FOTO() 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()


METHOD GRAVAMS03(aCAM) 
LOCAL aRET AS ARRAY
IF IsNil(acam[3]) //Sem  Codigo
   RETU .F.
ENDIF
IF Empty(aCAM[3])
   RETU .F.
ENDIF	
aCAM[1]:=FIXSTR(aCAM[1]) //Codigo Produdo
aCAM[3]:=FIXSTR(aCAM[3]) //Codigo Componente/MP
aCAM[4]:=FIXSTR(aCAM[4]) //Nome Componente/MP
aCAM[8]:=FIXSTR(aCAM[8]) //Baixa
aCAM[11]:=FIXSTR(aCAM[11]) //Opcao
aCAM[5]:=FIXNUM(aCAM[5])	 //Peso
aCAM[9]:=FIXNUM(aCAM[9])	//Seq
aCAM[10]:=FIXNUM(aCAM[10])	 //ssq
IF Acam[2]="T"
   aCAM[3]:=aCAM[1]	
ENDIF	
aRET:=VS3PRECO(aCAM[2],aCAM[3],.F.)
SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVCO:SERVER:APPEND()			
SELF:oSFJVCO:SERVER:OV:=SELF:SERVER:OV
//SELF:OSFJVCO:SERVER:CODIGO:=SELF:SERVER:CODIGO
SELF:OSFJVCO:SERVER:TIPOENT:=IF(aCAM[2]="I","T",aCAM[2])
SELF:OSFJVCO:SERVER:CODCOMP:=aCAM[3]
SELF:OSFJVCO:SERVER:QTDDE:=aCAM[5]
SELF:OSFJVCO:SERVER:NOMECOMP:=aRET[2]
SELF:oSFJVCO:server:preco:=aRET[1]
SELF:oSFJVCO:server:ULTDATA:=aRET[5]
SELF:oSFJVCO:server:ULTUND:=aRET[6]		
SELF:OSFJVCO:SERVER:TOTAL:=aRET[1]*aCAM[5]
SELF:oSFJVCO:SERVER:commit()
SELF:oSFJVCO:SERVER:resetnotification()
SELF:oSFJVCO:SERVER:notify(notifyfilechange)


METHOD GRAVATUDO() 
SELF:SERVER:Commit()
SELF:oSFJSEQ:SERVER:Commit()
SELF:oSFJVCO:SERVER:Commit()	
SELF:RegisterTimer(300,FALSE)

METHOD Imp 
SELF:oSFJVCo:SERVER:FIELDPUT("ORIGEM","Internacional")	
SELF:GRAVATUDO()

METHOD IMPEST 
LOCAL nOVTMP AS DWORD
LOCAL oBUSCA AS XBUSCA	
LOCAL aDAD AS ARRAY
LOCAL oESF AS USEREDE
nOVTMP:=0
oBUSCA:=XBUSCA{SELF,"Importar Desenho Desenho","Digite o Codigo do Desenho"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU .F.
ENDIF
aDAD:={zCURINI,"VFORC.DBF",zCURDIR}
oESF:=USEREDE{aDAD}
IF oESF:nERRO#0
   RETU SELF
ENDIF	
oESF:SetOrder(2)
oESF:GOTOP()
IF oESF:Seek(AllTrim(oBUSCA:cBUSCA))
   nOVTMP:=oESF:FIELDGET("OV")
ENDIF
oESF:CLOSE()	
IF nOVTMP>0
   SELF:IMPESTX(nOVTMP)	
ENDIF	

METHOD ImpEst1( ) 
LOCAL nOVTMP AS DWORD
LOCAL oBUSCA AS XBUSCA	
LOCAL aDAD AS ARRAY
LOCAL oESF AS USEREDE
nOVTMP:=0
oBUSCA:=XBUSCA{SELF,"Digite o Nº Viabilidade",""}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU .F.
ENDIF
aDAD:={zCURINI,"VFORC.DBF",zCURDIR}
oESF:=USEREDE{aDAD}
IF oESF:nERRO#0
   RETU SELF
ENDIF	
oESF:SetOrder(3)
oESF:GOTOP()
IF oESF:Seek(Val(oBUSCA:cBUSCA))
   nOVTMP:=oESF:FIELDGET("OV")
ENDIF
oESF:CLOSE()	
IF nOVTMP>0
   SELF:IMPESTX(nOVTMP)	
ENDIF		

METHOD ImpEst2( ) 
LOCAL nOVTMP AS DWORD
LOCAL oBUSCA AS XBUSCA	
LOCAL aDAD AS ARRAY
LOCAL oESF AS USEREDE
nOVTMP:=0
oBUSCA:=XBUSCA{SELF,"Digite o Nº Orçamento Fechado",""}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU .F.
ENDIF
aDAD:={zCURINI,"VFORC.DBF",zCURDIR}
oESF:=USEREDE{aDAD}
IF oESF:nERRO#0
   RETU SELF
ENDIF	
oESF:SetOrder(1)
oESF:GOTOP()
IF oESF:Seek(Val(oBUSCA:cBUSCA))
   nOVTMP:=oESF:FIELDGET("OV")
ENDIF
oESF:CLOSE()	
IF nOVTMP>0
   SELF:IMPESTX(nOVTMP)	
ENDIF			

METHOD ImpEstX(nOVTMP) 
LOCAL nOV,nFIELD,X AS DWORD
LOCAL aDAD AS ARRAY
LOCAL oMS03,oMS06 AS USEREDE   //OESF
LOCAL cNAME AS STRING


nOV:=SELF:SERVER:FIELDGET("OV")
//oESF:CLOSE()
aDAD:={zCURINI,"VFMS03.DBF",zCURDIR}
oMS03:=USEREDE{aDAD,,.T.}   //Leitura
IF oMS03:nERRO#0
   RETU SELF
ENDIF
SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
nFIELD:=oMS03:FCOUNT
oMS03:GOTOP()
oMS03:SEEK(nOVTMP)
WHILE nOVTMP=oMS03:FIELDGET("OV") .AND. ! oMS03:EoF
     SELF:oSFJVCO:SERVER:APPEND()
     FOR X:=1 TO nFIELD
     	 cNAME:=oMS03:FieldName(X)
   	     SELF:oSFJVCO:SERVER:FIELDPUT(CNAME,oMS03:FIELDGET(cNAME))
     NEXT X
     SELF:oSFJVCO:SERVER:FIELDPUT("OV",nOV)
     SELF:oSFJVCO:SERVER:commit()
     oMS03:SKIP()
ENDDO
oMS03:CLOSE()
SELF:oSFJVCO:SERVER:resetnotification()
SELF:oSFJVCO:SERVER:notify(notifyappend)
SELF:OSFJVCO:Browser:REFRESH()

aDAD:={zCURINI,"VFMS06.DBF",zCURDIR}
oMS06:=USEREDE{aDAD,,.T.}   //Leitura
IF oMS06:nERRO#0
   RETU SELF
ENDIF	
SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
oMS06:GOTOP()
oMS06:SEEK(nOVTMP)
WHILE nOVTMP=oMS06:FIELDGET("OV") .AND. ! oMS06:EoF
    FOR X:=1 TO nFIELD
     	cNAME:=oMS06:FieldName(X)
   	    SELF:oSFJSEQ:SERVER:FIELDPUT(CNAME,oMS06:FIELDGET(cNAME))
	NEXT X	
	SELF:oSFJSEQ:SERVER:FIELDPUT("OV",nOV)
	SELF:oSFJSEQ:SERVER:commit()	
    oMS06:SKIP()
ENDDO
oMS06:CLOSE()
SELF:oSFJSEQ:SERVER:resetnotification()
SELF:oSFJSEQ:SERVER:notify(notifyappend)
SELF:OSFJSEQ:Browser:REFRESH()
SELF:GRAVATUDO()	

METHOD IMPORTAR() 
LOCAL oMS03 AS USEMANA5
LOCAL oMS06 AS USEMANA5
LOCAL aRET AS ARRAY
LOCAL nOV AS DWORD
LOCAL cCODIGO,cMEDIA AS STRING
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Localizar Desenho","Digite o Codigo do Desenho",SELF:SERVER:FIELDGET("CODIGO")}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU	
ENDIF
cCODIGO:=AllTrim(oBUSCA:cBUSCA)


oBUSCA:=XBUSCA{SELF,"Escolher Media","(P)adrão (M)edia (I)nterna","P"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU	
ENDIF
cMEDIA:=oBUSCA:cBUSCA
IF Empty(Cmedia)
   cMEDIA:="P"
ELSE
   cMEDIA:=Upper(cMEDIA)
ENDIF	
IF ! cMEDIA $ "PMI"
   RETU
ENDIF	


SELF:POINTER:=POINTER{POINTERHOURGLASS}
nOV:=SELF:Server:OV


SELF:SERVER:FIELDPUT("CODIGO",CCODIGO)
nOV:=SELF:SERVER:OV

SELF:CLIMEDMS01(cCODIGO)

	
aRET:={zCURINI,"MS03",zCURDIR,aDIR}
oMS03:=USEMANA5{aRET}
IF oMS03:nERRO=0
	oMS03:SetOrder(2)
	oMS03:GOTOP()
	oMS03:SEEK(CCODIGO)
	SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
	WHILE AllTrim(oMS03:FIELDGET("CODIGO"))=CCODIGO .AND. ! oMS03:EoF
		IF oMS03:FIELDGET("TIPOENT")="M" .OR. oMS03:FIELDGET("TIPOENT")="C" .OR. oMS03:FIELDGET("TIPOENT")="T" .OR. oMS03:FIELDGET("TIPOENT")="I"
			aRET:=VS3PRECO(oMS03:FIELDGET("TIPOENT"),oMS03:FIELDGET("CODCOMP"),.F.)
			SELF:oSFJVCO:SERVER:APPEND()			
			SELF:oSFJVCO:SERVER:OV:=nOV
//			SELF:OSFJVCO:SERVER:CODIGO:=cCODIGO
			SELF:OSFJVCO:SERVER:TIPOENT:=oMS03:FIELDGET("TIPOENT")
			SELF:OSFJVCO:SERVER:CODCOMP:=oMS03:FIELDGET("CODCOMP")
			SELF:OSFJVCO:SERVER:QTDDE:=oMS03:FIELDGET("QTDDE")
			SELF:OSFJVCO:SERVER:NOMECOMP:=aRET[2]
            SELF:oSFJVCO:server:preco:=aRET[1]
            SELF:oSFJVCO:server:ULTDATA:=aRET[5]
            SELF:oSFJVCO:server:ULTUND:=aRET[6]		
			SELF:OSFJVCO:SERVER:TOTAL:=aRET[1]*oMS03:FIELDGET("QTDDE")			
			SELF:oSFJVCO:SERVER:commit()
		ENDIF	
	   oMS03:SKIP()
   ENDDO
	SELF:oSFJVCO:SERVER:resetnotification()
	SELF:oSFJVCO:SERVER:notify(notifyappend)		
	oMS03:CLOSE()
ENDIF


aRET:={zCURINI,"MS06",zCURDIR,aDIR}
oMS06:=USEMANA5{aRET}
IF oMS06:nERRO=0
	oMS06:SetOrder(1)
	oMS06:GOTOP()
	oMS06:SEEK(CCODIGO)
	SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
	WHILE AllTrim(oMS06:FIELDGET("CODIGO"))=CCODIGO .AND. ! oMS06:EoF
			IF oMS06:FIELDGET("SEQ")<>99 .AND. oMS06:FIELDGET("SSQ")<>99
	 			SELF:oSFJSEQ:SERVER:APPEND()			
				SELF:oSFJSEQ:SERVER:OV:=nOV
//				SELF:OSFJSEQ:SERVER:CODIGO:=CCODIGO
				SELF:OSFJSEQ:SERVER:SEQ:=oMS06:FIELDGET("SEQ")
				SELF:OSFJSEQ:SERVER:SSQ:=oMS06:FIELDGET("SSQ")
				IF Empty(SELF:OSFJSEQ:SERVER:DESCRI:=oMS06:FIELDGET("NOMER"))
  				   SELF:OSFJSEQ:SERVER:DESCRI:=oMS06:FIELDGET("DESCRI")
  				ELSE
  				   SELF:OSFJSEQ:SERVER:DESCRI:=oMS06:FIELDGET("NOMER")				
				ENDIF
				SELF:OSFJSEQ:SERVER:CODMP01:=oMS06:FIELDGET("CODMP01")
				aRET:=VS3PRECO("E",oMS06:FIELDGET("CODMP01"),.F.)
				SELF:OSFJSEQ:SERVER:NOMMP01:=aRET[2]
				SELF:OSFJSEQ:SERVER:COGMP01:=aRET[7]				
				SELF:OSFJSEQ:SERVER:CODMP02:=oMS06:FIELDGET("CODMP02")
				aRET:=VS3PRECO("H",oMS06:FIELDGET("CODMP02"),.F.)				
				SELF:OSFJSEQ:SERVER:NOMMP02:=aRET[2]
				SELF:OSFJSEQ:SERVER:CODMP02B:=oMS06:FIELDGET("CODMP02B")
				aRET:=VS3PRECO("H",oMS06:FIELDGET("CODMP02B"),.F.)				
				SELF:OSFJSEQ:SERVER:NOMMP02B:=aRET[2]
				SELF:OSFJSEQ:SERVER:CODMP02C:=oMS06:FIELDGET("CODMP02C")
	        	aRET:=VS3PRECO("H",oMS06:FIELDGET("CODMP02C"),.F.)
				SELF:OSFJSEQ:SERVER:NOMMP02C:=aRET[2]
				SELF:OSFJSEQ:SERVER:CODMP02D:=oMS06:FIELDGET("CODMP02D")
				aRET:=VS3PRECO("H",oMS06:FIELDGET("CODMP02D"),.F.)				
				SELF:OSFJSEQ:SERVER:NOMMP02D:=aRET[2]
				SELF:OSFJSEQ:SERVER:CODMP03:=oMS06:FIELDGET("CODMP03")				
				aRET:=VS3PRECO("T",oMS06:FIELDGET("CODMP03"),.F.)									
				SELF:OSFJSEQ:SERVER:NOMMP03:=aRET[2]
			    SELF:OSFJSEQ:SERVER:PCHORA:=oMS06:FIELDGET("PCHORA")				
				DO CASE
				    CASE CMEDIA="P"
                        SELF:OSFJSEQ:SERVER:FIELDPUT("PCMEDIA",INT(oMS06:FIELDGET("PCHORA")))
				    CASE CMEDIA="M"
                        SELF:OSFJSEQ:SERVER:FIELDPUT("PCMEDIA",INT(oMS06:FIELDGET("PCHORMED")))
				    CASE CMEDIA="I"
                        SELF:OSFJSEQ:SERVER:FIELDPUT("PCMEDIA",INT(oMS06:FIELDGET("PCHORAMD")))
  				ENDCASE		
  			    IF Empty(SELF:OSFJSEQ:SERVER:PCMEDIA)
                   SELF:OSFJSEQ:SERVER:PCMEDIA:=oMS06:FIELDGET("PCHORA")
  			    ENDIF	
				SELF:OSFJSEQ:SERVER:AREA:=oMS06:FIELDGET("AREA")
				SELF:oSFJSEQ:SERVER:commit()
			ENDIF
  			oMS06:SKIP()	
   ENDDO
	SELF:oSFJSEQ:SERVER:resetnotification()
	SELF:oSFJSEQ:SERVER:notify(notifyappend)
	oMS06:CLOSE()
ENDIF
GRAVALOG(SELF:Server:OV,"IMP","VPORC")	
SELF:SERVER:FIELDPUT("TIPOIMP","1") //PCP Produçao
SELF:PEGCLI()
//SELF:GRAVATUDO()
SELF:POINTER:=POINTER{}

METHOD imppfcom 	
LOCAL oJAN AS XJPFDIA
LOCAL cCODIGO,cPF,cOPCAO,cSQL AS STRING
LOCAL nPF AS DWORD
LOCAL oConn AS SQLConnection
LOCAL oREG AS SQLSelect
LOCAL aCAM AS ARRAY
LOCAL nHORAS AS FLOAT


//nOV:=SELF:SERVER:FIELDGET("OV")

cCODIGO:=SELF:SERVER:FIELDGET("CODIGO")
IF Empty(cCODIGO)
   alert("Prencha Codigo Produto")	
   RETU
ENDIF	
SELF:SERVER:FIELDPUT("CODIGO",AllTrim(cCODIGO))

oJAN:=XJPFDIA{SELF}
oJAN:SHOW()
IF ! oJAN:lOK
  RETU
ENDIF		

//cCODPF:=oJAN:cCODIGO
nPF:=oJAN:NPF
cPF:=AllTrim(Str(nPF))

IF Empty(cPF)
  RETU
ENDIF	
IF Empty(cCODIGO)
   RETU
ENDIF	

SELF:POINTER:=POINTER{POINTERHOURGLASS}
	
//Componentes
cSQL:="SELECT * FROM PFMS03 WHERE PF="+cPF

oConn := SQLConnection{}
oConn:connect("pf","","")

oreg:= SQLSelect{cSQL,oconn}

WHILE ! OREG:EoF
      aCAM:={}
      AAdd(aCAM,cCODIGO) //1
      AAdd(aCAM,"C")                     //2
      AAdd(aCAM,oREG:FIELDGET("CODCOMP"))  //3
      AAdd(aCAM,oREG:FIELDGET("DESCRI"))  //4
      AAdd(aCAM,oREG:FIELDGET("QTDDE"))  //5
      AAdd(aCAM,"0")         //6
      AAdd(aCAM,"0")         //7
      AAdd(aCAM,oREG:FIELDGET("BAIXAC"))         //8
      AAdd(aCAM,oREG:FIELDGET("SEQ"))  //9
      AAdd(aCAM,oREG:FIELDGET("SSQ"))  //10
      IF ! IsNil(oREG:FIELDGET("OPCAO"))     //Verifica nil necessita str
         AAdd(aCAM,Str(oREG:FIELDGET("OPCAO"),1))         //11
      ELSE
         AAdd(aCAM," ")
      ENDIF
      SELF:GRAVAMS03(aCAM)
      Oreg:Skip()
ENDDO
oREG:Close()
oConn:Disconnect()


//Materia Prima
cSQL:="SELECT * FROM PF WHERE PF="+cPF

oConn := SQLConnection{}
oConn:connect("pf","","")

oreg:= SQLSelect{cSQL,oconn}
aCAM:={}
AAdd(aCAM,cCODIGO) //1
AAdd(aCAM,"M")                     //2
AAdd(aCAM,oREG:FIELDGET("CODMU011"))  //3
AAdd(aCAM,oREG:FIELDGET("NOMMU011"))  //4
AAdd(aCAM,oREG:FIELDGET("PESMU011"))  //5
AAdd(aCAM,"0")         //6
AAdd(aCAM,"0")         //7
AAdd(aCAM,"N")         //8
AAdd(aCAM,oREG:FIELDGET("SEQMU011"))  //9
AAdd(aCAM,oREG:FIELDGET("SSQMU011"))  //10
AAdd(aCAM,"1")         //11
SELF:GRAVAMS03(aCAM)

aCAM:={}
AAdd(aCAM,cCODIGO) //1
AAdd(aCAM,"M")                     //2
AAdd(aCAM,oREG:FIELDGET("CODMU012"))  //3
AAdd(aCAM,oREG:FIELDGET("NOMMU012"))  //4
AAdd(aCAM,oREG:FIELDGET("PESMU012"))  //5
AAdd(aCAM,"0")         //6
AAdd(aCAM,"0")         //7
AAdd(aCAM,"S")         //8
AAdd(aCAM,oREG:FIELDGET("SEQMU012"))  //9
AAdd(aCAM,oREG:FIELDGET("SSQMU012"))  //10
AAdd(aCAM,"2")         //11
SELF:GRAVAMS03(aCAM)

aCAM:={}
AAdd(aCAM,CCODIGO) //1
AAdd(aCAM,"M")                     //2
AAdd(aCAM,oREG:FIELDGET("CODMU013"))  //3
AAdd(aCAM,oREG:FIELDGET("NOMMU013"))  //4
AAdd(aCAM,oREG:FIELDGET("PESMU013"))  //5
AAdd(aCAM,"0")         //6
AAdd(aCAM,"0")         //7
AAdd(aCAM,"S")         //8
AAdd(aCAM,oREG:FIELDGET("SEQMU013"))  //9
AAdd(aCAM,oREG:FIELDGET("SSQMU013"))  //10
AAdd(aCAM,"3")         //11
SELF:GRAVAMS03(aCAM)

oREG:Close()
oConn:Disconnect()


//Tratamentos
cSQL:="SELECT * FROM PFS WHERE PF="+cPF

oConn := SQLConnection{}
oConn:connect("pf","","")

oreg:= SQLSelect{cSQL,oconn}

WHILE ! OREG:EoF
     nHORAS := 0
     cOPCAO := "1"
     IF oREG:FIELDGET("PCHORA") > 0
        nHORAS := 1 / oREG:FIELDGET("PCHORA")
     ENDIF
     IF ! IsNil(oREG:FIELDGET("OPCAO"))
        cOPCAO := Str(oREG:FIELDGET("OPCAO"))
     ENDIF

     aCAM:={}
     AAdd(aCAM,cCODIGO) //1
     AAdd(aCAM,"I")                     //2
     AAdd(aCAM,oREG:FIELDGET("CODMP03"))  //3
     AAdd(aCAM,oREG:FIELDGET("DESCRI"))  //4
     AAdd(aCAM,nHORAS)  //5
     AAdd(aCAM,"0")         //6
     AAdd(aCAM,"0")         //7
     AAdd(aCAM,"N")         //8
     AAdd(aCAM,oREG:FIELDGET("SEQ"))  //9
     AAdd(aCAM,oREG:FIELDGET("SSQ"))  //10
     AAdd(aCAM,cOPCAO)         //11

     SELF:GRAVAMS03(aCAM)

     Oreg:Skip()
ENDDO
oREG:Close()
oConn:Disconnect()
SELF:SERVER:FIELDPUT("TIPOIMP","2") //Processo Fabricaçao

SELF:CLIMEDMS01(cCODIGO)	
SELF:PEGCLI()
	
SELF:zerApreco()	
//SELF:GRAVATUDO()	
SELF:POINTER:=POINTER{}	
alert("Termino Importaçäo","Encerrado")

METHOD imppfseq 
LOCAL oJAN AS XJPFDIA
LOCAL cCODIGO,cPF,cSQL AS STRING
LOCAL nPF,nOV AS DWORD
LOCAL oConn AS SQLConnection
LOCAL oREG AS SQLSelect
LOCAL aRET AS ARRAY
nOV:=SELF:SERVER:FIELDGET("OV")

cCODIGO:=SELF:SERVER:FIELDGET("CODIGO")
IF Empty(cCODIGO)
   alert("Prencha Codigo Produto")	
   RETU
ENDIF	
SELF:SERVER:FIELDPUT("CODIGO",AllTrim(cCODIGO))

oJAN:=XJPFDIA{SELF}
oJAN:SHOW()
IF ! oJAN:lOK
  RETU
ENDIF		

//cCODPF:=oJAN:cCODIGO
nPF:=oJAN:NPF
cPF:=AllTrim(Str(nPF))

IF Empty(cPF)
  RETU
ENDIF	
IF Empty(cCODIGO)
   RETU
ENDIF	

SELF:POINTER:=POINTER{POINTERHOURGLASS}
cSQL:="SELECT * FROM PFS WHERE PF="+cPF+" ORDER BY SEQ,SSQ"

oConn := SQLConnection{}
oConn:connect("pf","","")
oreg:= SQLSelect{cSQL,oconn}
SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
WHILE ! OREG:EoF
   SELF:oSFJSEQ:SERVER:APPEND()
   SELF:oSFJSEQ:SERVER:FIELDPUT("OV",nOV)
//   SELF:OSFJSEQ:SERVER:CODIGO:=CCODIGO
   SELF:OSFJSEQ:SERVER:SEQ:=FIXNUM(oREG:FIELDGET("SEQ"))
   SELF:OSFJSEQ:SERVER:SSQ:=FIXNUM(oREG:FIELDGET("SSQ"))
   SELF:OSFJSEQ:SERVER:DESCRI:=FIXSTR(oREG:FIELDGET("DESCRI"))
   SELF:OSFJSEQ:SERVER:CODMP01:=FIXSTR(oREG:FIELDGET("CODMP01"))
   aRET:=VS3PRECO("E",SELF:OSFJSEQ:SERVER:CODMP01,.F.)
   SELF:OSFJSEQ:SERVER:NOMMP01:=aRET[2]				
   SELF:OSFJSEQ:SERVER:COGMP01:=aRET[7]
   SELF:OSFJSEQ:SERVER:CODMP02:=FIXSTR(oREG:FIELDGET("CODMP02"))
   aRET:=VS3PRECO("H",SELF:OSFJSEQ:SERVER:CODMP02,.F.)				
   SELF:OSFJSEQ:SERVER:NOMMP02:=aRET[2]
   SELF:OSFJSEQ:SERVER:CODMP02B:=FIXSTR(oREG:FIELDGET("CODMP02B"))
   aRET:=VS3PRECO("H",SELF:OSFJSEQ:SERVER:CODMP02B,.F.)				
   SELF:OSFJSEQ:SERVER:NOMMP02B:=aRET[2]
   SELF:OSFJSEQ:SERVER:CODMP02C:=FIXSTR(oREG:FIELDGET("CODMP02C"))
   aRET:=VS3PRECO("H",SELF:OSFJSEQ:SERVER:CODMP02C,.F.)				
   SELF:OSFJSEQ:SERVER:NOMMP02C:=aRET[2]
   SELF:OSFJSEQ:SERVER:CODMP02D:=FIXSTR(oREG:FIELDGET("CODMP02D"))
   aRET:=VS3PRECO("H",SELF:OSFJSEQ:SERVER:CODMP02D,.F.)				
   SELF:OSFJSEQ:SERVER:NOMMP02D:=aRET[2]
   SELF:OSFJSEQ:SERVER:CODMP03:=FIXSTR(oREG:FIELDGET("CODMP03"))
   aRET:=VS3PRECO("T",SELF:OSFJSEQ:SERVER:CODMP03,.F.)				
   SELF:OSFJSEQ:SERVER:NOMMP03:=aRET[2]
   SELF:OSFJSEQ:SERVER:PCHORA:=FIXNUM(oREG:FIELDGET("PCHORA"))
   SELF:oSFJSEQ:SERVER:commit()
   Oreg:Skip()
ENDDO
oREG:Close()
oConn:Disconnect()
SELF:oSFJSEQ:SERVER:resetnotification()
SELF:oSFJSEQ:SERVER:notify(notifyfilechange)
SELF:POINTER:=POINTER{}
SELF:SERVER:FIELDPUT("TIPOIMP","2") //Processo Fabricaçao

SELF:CLIMEDMS01(cCODIGO)
SELF:PEGCLI()
SELF:checktemp()
SELF:zerApreco()
//SELF:GRAVATUDO()
alert("Termino Importaçäo","Encerrado")



METHOD INCLUI2 
	LOCAL nOV AS DWORD
nOV:=SELF:SERVER:OV
SELF:oSFJSEQ:SERVER:GOBOTTOM()
SELF:oSFJSEQ:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJSEQ:SERVER:APPEND()
SELF:oSFJSEQ:SERVER:OV:=nOV
SELF:oSFJSEQ:SERVER:commit()
SELF:oSFJSEQ:SERVER:resetnotification()
SELF:oSFJSEQ:SERVER:notify(notifyappend)
SELF:zerApreco()
//SELF:GRAVATUDO()

METHOD INCLUIR 
LOCAL nOV AS DWORD
LOCAL cTIPOENT AS STRING
LOCAL oBUSCA AS XBUSCA
nOV:=SELF:SERVER:OV


oBUSCA:=XBUSCA{SELF,"Forneca o Tipo","Digite o Tipo (M)atPrima (C)omponente (T)rat. ET(I)",cTIPOENT}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   cTIPOENT:=Upper(oBUSCA:cBUSCA)
ENDIF
SELF:oSFJVCO:SERVER:GOBOTTOM()
SELF:oSFJVCO:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJVCO:SERVER:APPEND()
SELF:oSFJVCO:SERVER:OV:=nOV
SELF:oSFJVCo:SERVER:FIELDPUT("ORIGEM","Nacional")
SELF:oSFJVCo:SERVER:FIELDPUT("TIPOENT",cTIPOENT)
SELF:oSFJVCO:SERVER:commit()
SELF:oSFJVCO:SERVER:resetnotification()
SELF:oSFJVCO:SERVER:notify(notifyappend)
SELF:zerApreco()
//SELF:GRAVATUDO()


CONSTRUCTOR(Oowner) 
SUPER(Oowner)	

METHOD nac 
SELF:oSFJVCo:SERVER:FIELDPUT("ORIGEM","Nacional")
SELF:GRAVATUDO()

METHOD PEGCLI 
LOCAL aRET AS ARRAY	
aRET:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aRET[1]=.T.
   SELF:SERVER:COGCLI:=aRET[3]
   SELF:SERVER:PUF:=aRET[5]
ENDIF
IF MDG("Verificar Pis/Confins Cliente")
   SELF:cmdpiscon2()
ENDIF	
SELF:cmdMarkup(.F.) //Evitar loop recursivo
SELF:GRAVATUDO()
	

METHOD PEGCOD 
LOCAL aRET AS ARRAY
aRET:=PEGMSEXT(SELF:SERVER:CODIGO,.T.)
IF aRET[1]=.T. .AND. ! Empty(aRET[2])
   SELF:SERVER:FIELDPUT("NOME",aRET[2])
ENDIF
SELF:GRAVATUDO()	

METHOD PEGMES 
		IF SELF:server:LANU>0
			   SELF:server:Lmes:=INT((SELF:server:Lanu)/12)
			ENDIF
		SELF:GRAVATUDO()
		

METHOD PegPreco( ) 
LOCAL aPRC AS ARRAY
aPRC:=MS02PRC(SELF:SERVER:FIELDGET("CODIGO"),SELF:SERVER:FIELDGET("CLIENTE"),.F.,.T.,,ZCURINI,ZCURDIR,aDIR)	
IF aPRC[1]>0
   SELF:SERVER:FIELDPUT("PREF",aPRC[1])
ENDIF
SELF:GRAVATUDO()

METHOD pluc10 
SELF:SERVER:FIELDPUT("PLUC",10)	
SELF:cmdMarkup(.F.)
//SELF:GRAVATUDO()

METHOD pluc20 
SELF:SERVER:FIELDPUT("PLUC",20)	
SELF:cmdMarkup(.F.)
//SELF:GRAVATUDO()

METHOD POROV 
SELF:KeyFind()


METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIM2 
SELF:oSFJSEQ:Browser:SuspendUpdate()
IF ! SELF:oSFJSEQ:Server:Eof
    SELF:oSFJSEQ:SERVER:Skip()
ENDIF
SELF:oSFJSEQ:Browser:RestoreUpdate()

METHOD PROXIMO 
SELF:oSFJVCO:Browser:SuspendUpdate()
IF ! SELF:oSFJVCO:Server:Eof
    SELF:oSFJVCO:SERVER:Skip()
ENDIF
SELF:oSFJVCO:Browser:RestoreUpdate()

METHOD SubMaq( ) 
LOCAL aDAD AS ARRAY
LOCAL oARQ AS  USEMANA5
LOCAL oBUSCA AS XBUSCA
LOCAL lACHEI AS LOGIC
lACHEI:=.F.
IF Empty(Val(SELF:oDCSUB:TextValue))
   alert("Codigo Maquina Nao Preenchido","Erro Preenchimento")
   IF MDG("Limpar Informações da Maquina")
   	  SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP01","")
      SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP01","")
      SELF:oSFJSEQ:SERVER:FIELDPUT("CODFOLHA",0)
   ENDIF	
   RETU
ENDIF
aDAD:={zCURINI,"MP01",zCURDIR,aDIR}
oARQ:=USEMANA5{aDAD}
IF oARQ:USED
   oARQ:SetOrder(3)
   oARQ:GOTOP()
   IF oarq:Seek(Val(SELF:oDCSUB:TextValue))
      SELF:oSFJSEQ:SERVER:FIELDPUT("CODMP01",oARQ:FIELDGET("CODIGO"))
      SELF:oSFJSEQ:SERVER:FIELDPUT("NOMMP01",oARQ:FIELDGET("NOME"))
      SELF:oSFJSEQ:SERVER:FIELDPUT("CODFOLHA",Val(SELF:oDCSUB:TextValue))
      lACHEI:=.T.
   ENDIF	
   OARQ:CLOSE()
   IF lACHEI
      oBUSCA:=XBUSCA{SELF,"Forneca qtde Pc/Hora","Confirme PC/HORA",Str(SELF:oSFJSEQ:SERVER:FIELDGET("PCHORA"))}
      oBUSCA:lMES:=.T.
      oBUSCA:SHOW()
      IF oBUSCA:lOK
         SELF:oSFJSEQ:SERVER:FIELDPUT("PCHORA",INT(Val(oBUSCA:cBUSCA)))
      ENDIF
   ELSE
	  alert("Sub Codigo Maquina Nao Cadastrado","Erro Preenchimento")
      RETU
   ENDIF
ENDIF
SELF:zerApreco()


METHOD TABULA2  
Self:oSFJSEQ:VIEWTABLE()

METHOD TABULAR  
SELF:oSFJVCO:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()


METHOD VERPCP 
LOCAL oJAN AS XJPRO
oJAN:=XJPRO{SELF,SELF:SERVER:FIELDGET("CODIGO"),zcurINI,zcurDIR,adir}
oJAN:SHOW()

METHOD zerApreco() 
SELF:SERVER:FIELDPUT("PVEN",0)
SELF:SERVER:FIELDPUT("PVEN2",0)
SELF:SERVER:FIELDPUT("DATACALC",Space(8))
SELF:GRAVATUDO()


END CLASS
