CLASS XINDEXAR INHERIT INDEXAR	

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("CUS",19)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	

METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
//Custo
CRIANTX({ZCURINI,"VPORC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"VMS03.DBF",ZCURDIR})
CRIANTX({ZCURINI,"VMS06.DBF",ZCURDIR})

//Custo Fechados
CRIANTX({ZCURINI,"VFORC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"VFMS03.DBF",ZCURDIR})
CRIANTX({ZCURINI,"VFMS06.DBF",ZCURDIR})


//Estimativa Em Abero
CRIANTX({ZCURINI,"ESP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ESPMS03.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ESPMS06.DBF",ZCURDIR})
//Estimativa Fechadas
CRIANTX({ZCURINI,"ESF.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ESFMS03.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ESFMS06.DBF",ZCURDIR})
//Estimativas Antigas
CRIANTX({ZCURINI,"ESO.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ESOMS03.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ESOMS06.DBF",ZCURDIR})

//Analise de Custos
CRIANTX({ZCURINI,"ESC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ESCMS03.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ESCMS06.DBF",ZCURDIR})

//Vmark
CRIANTX({ZCURINI,"VMARK.DBF",ZCURDIR})
//fluxo
CRIANTX({ZCURINI,"FLUXO.DBF",ZCURDIR})

//Viabilidade
CRIANTX({ZCURINI,"VIABILI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"VIABIII.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()	

END CLASS
CLASS XJANCLI INHERIT JANCLI

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL aDAD AS ARRAY
IF ! entramenu("CUS",13)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MA01",ZCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			

END CLASS
CLASS XJMP05 INHERIT JMP05

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("CUS",17)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MP05",ZCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			

END CLASS
CLASS ZJPRO INHERIT XJPRO

CONSTRUCTOR(oOWNER,cCODIGO) 
SUPER(oOWNER,cCODIGO,zcurINI,zcurDIR,adir)
SELF:SHOW()
	



END CLASS
