CLASS XJTEC INHERIT JTEC	

METHOD APPEND(oOWNER) 
alert("Operação Bloqueada")



METHOD DELETE(oOWNER) 
alert("Operação Bloqueada")



CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("CUS",18)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MP04",ZCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			

METHOD TABSET 
RETU MTD02("SETINS",3)


END CLASS
