PARTIAL CLASS JADP
METHOD ALTERAR  
SELF:oSFJADPI:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJADPI:Browser:SuspendUpdate()
SELF:oSFJADPI:SkipPREVIOUS()
IF SELF:oSFJADPI:Server:BOF
	SELF:oSFJADPI:SkipNEXT()
ENDIF
SELF:oSFJADPI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nADP AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nADP:=SELF:Server:ADP
nADP++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("ADP",nADP)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("INSNUM",ZFOLHA)
SELF:PEGINS()
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
RETURN  .t.

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("ADP","")	

METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
   SELF:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJADPI:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJADPI:SERVER:gotop()
   WHILE ! SELF:oSFJADPI:SERVER:eof
	 	SELF:oSFJADPI:SERVER:delete()
	 	SELF:oSFJADPI:SERVER:skip()	
      ENDDO
	SELF:oSFJADPI:SERVER:resetnotification()
	SELF:oSFJADPI:SERVER:notify(notifyfilechange)
	SELF:server:delete()
	SELF:server:unlock()
	SELF:SERVER:RESETNOTIFICATION()
	SELF:SERVER:Notify(notifyfilechange)
	SELF:SERVER:SKIPEX(-1)
ENDIF	

METHOD EXCLUIR 
IF  MDG("Apagar Registro") .AND. SELF:oSFJADPI:server:LockCurrentRecord()
    SELF:oSFJADPI:SERVER:SUSPENDNOTIFICATION()	
    SELF:oSFJADPI:server:delete()
    SELF:oSFJADPI:server:unlock()
    SELF:oSFJADPI:SERVER:resetnotification()
	SELF:oSFJADPI:SERVER:notify(notifyfilechange)
	SELF:oSFJADPI:Browser:refresh()
ENDIF	

METHOD INCLUIR 
LOCAL nADP AS DWORD
nADP:=SELF:SERVER:FIELDGET("ADP")
SELF:oSFJADPI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJADPI:SERVER:APPEND()
SELF:oSFJADPI:SERVER:FIELDPUT("ADP",nADP)
SELF:oSFJADPI:SERVER:commit()
SELF:oSFJADPI:SERVER:resetnotification()
SELF:oSFJADPI:SERVER:notify(notifyappend)
SELF:oSFJADPI:Browser:refresh()

METHOD laudo 
IF SELF:oSFJADPI:server:LAUDO="A"
   SELF:oSFJADPI:server:LAUDO:="R"
ELSE
   SELF:oSFJADPI:server:LAUDO:="A"
ENDIF

METHOD PEGINS	
LOCAL aUSO AS ARRAY	
LOCAL ACOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
           aUSO:=PEGMP04(SELF:SERVER:FIELDGET("INSNUM"),ZCURINI,ZCURDIR,ACOM)
           IF aUSO[1]=.T.
              SELF:SERVER:FIELDPUT("INSNOME",aUSO[2])
           ENDIF

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
      FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJADPI:Browser:SuspendUpdate()
SELF:oSFJADPI:SkipNext()
IF SELF:oSFJADPI:Server:Eof
	SELF:oSFJADPI:SkipPrevious()
ENDIF
SELF:oSFJADPI:Browser:RestoreUpdate()

METHOD TABULAR  
SELF:oSFJADPI:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
PARTIAL CLASS tabadp01
METHOD esccod() 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("NOME",oESC:NOME)
ENDIF

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF,ZCURINI,ZCURDIR}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("INSNUM",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("INSNOME",oESCMP04:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()	

METHOD ListBoxSelect(oControlEvent) 
LOCAL oControl AS Control
LOCAL aRESP AS ARRAY
oControl := IIf(oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control)
SUPER:ListBoxSelect(oControlEvent)
//Put your changes here
DO CASE
   CASE oCONTROL:NAMESYM==#AREA
        aRESP:=PEGMP05(SELF:SERVER:AREA,ZCURINI,ZCURDIR)
        IF aRESP[1]=.T.
           SELF:SERVER:RESPO:=aRESP[2]
        ENDIF
ENDCASE
RETURN NIL

METHOD PEGAREA() 
RETU PEGCOMBO("MP05.DBF","DESCRI","CODIGO")

METHOD PEGCLI 
LOCAL aUSO AS ARRAY
aUSO:=PEGMA01(SELF:SERVER:FIELDGET("CLIENTE"),zcurini,zcurdir)
IF aUSO[1]=.T.
    SELF:SERVER:CLINOME:=aUSO[2]
ENDIF

METHOD PEGCod 
LOCAL Apro AS ARRAY	
aPRO:=PEGMS01(SELF:SERVER:CODIGO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:SERVER:NOME:=aPRO[2]
ENDIF

METHOD PEGINS	
LOCAL aUSO AS ARRAY	
LOCAL ACOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
aUSO:=PEGMP04(SELF:SERVER:FIELDGET("INSNUM"),ZCURINI,ZCURDIR,ACOM)
IF aUSO[1]=.T.
   SELF:SERVER:FIELDPUT("INSNOME",aUSO[2])
ENDIF



END CLASS
