PARTIAL CLASS crrsseqtab1
METHOD cmdAnual( ) 
IF Empty(SELF:SERVER:FIELDGET("ANUAL")) .OR. SELF:SERVER:FIELDGET("ANUAL")="N"
   SELF:SERVER:FIELDPUT("ANUAL","S")
ELSE
   SELF:SERVER:FIELDPUT("ANUAL","N")	
ENDIF	

METHOD cmdSemes( ) 
IF Empty(SELF:SERVER:FIELDGET("SEMES")) .OR. SELF:SERVER:FIELDGET("SEMES")="N"
   SELF:SERVER:FIELDPUT("SEMES","S")
ELSE
   SELF:SERVER:FIELDPUT("SEMES","N")	
ENDIF	

METHOD Somafun( ) 
	SELF:server:FIELDPUT("NUMFUN",SELF:SERVER:FIELDGET("NUMREG")+SELF:SERVER:FIELDGET("NUMTEM"))

END CLASS
PARTIAL CLASS JCRRSSEQ
METHOD APPEND() 
LOCAL nSEQ AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nSEQ:=SELF:Server:SEQ
nSEQ++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("SEQ",nSEQ)
SELF:SERVER:commit()
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
RETURN  .t.

METHOD APUANU 
SELF:APURAR(2)

METHOD apurar(nTIPO) 
LOCAL aDAD,aSET,aVAL AS ARRAY
LOCAL X,nSEQ,nSEQINI,nDEV,nSUC,nRET,nPRO,nPOSUSO AS DWORD
LOCAL dINI,dFIM AS DATE
LOCAL cVAR AS STRING
LOCAL oCRRSAPS AS USEREDE
LOCAL nLASTREC AS DWORD
LOCAL nPERC AS INT
LOCAL nPOS AS DWORD




nSEQ:=SELF:SERVER:FIELDGET("SEQ")
nSEQINI:=SELF:SERVER:FIELDGET("SEQ")
cVAR:=IF(nTIPO=1,"SEM","ANU")
aSET:={}
aVAL:={}
dINI:=CToD(Space(8))     
dFIM:=CToD(Space(8))


aDAD:={zCURINI,"CRRSAPS.DBF",zCURDIR}
oCRRSAPS:=USEREDE{aDAD}
IF oCRRSAPS:nERRO#0
   RETURN .t.
ENDIF

SELF:POINTER:=POINTER{POINTERHOURGLASS}
nPRO:=0
nRET:=0
nSUC:=0
nDEV:=0
nLASTREC:=SELF:SERVER:RecCount
nPOS:=0

SELF:SERVER:GOTOP()
WHILE ! SELF:SERVER:EOF
	
    nPerc := INT(100* nPOS/ nLASTREC)
    SELF:oDcProgBar:Position := nPerc
	nPOS++

	IF SELF:SERVER:FIELDGET(IF(nTIPO=1,"SEMES","ANUAL"))="S"
	   IF Empty(dINI)
	   	  dINI:=SELF:SERVER:FIELDGET("DIAINI")
       ENDIF	
       dFIM:=SELF:SERVER:FIELDGET("DIAFIM")
       nPRO+=SELF:SERVER:FIELDGET("PRODMES")
       nRET+=SELF:SERVER:FIELDGET("RET")
       nSUC+=SELF:SERVER:FIELDGET("SUC")
       nDEV+=SELF:SERVER:FIELDGET("DEV")
       nSEQ:=SELF:SERVER:FIELDGET("SEQ")
       oCRRSAPS:GOTOP()
       oCRRSAPS:SEEK(Str(nseq,3))
       WHILE  nSEQ=oCRRSAPS:FIELDGET("SEQ") .AND. ! oCRRSAPS:EOF
       	   nPOSUSO:=AScan(aSET,oCRRSAPS:FIELDGET("SETCOD"))
       	   IF nPOSUSO>0
       	   	  aVAL[nPOSUSO][1]+=oCRRSAPS:FIELDGET("QTDE")
       	   	  aVAL[nPOSUSO][2]+=oCRRSAPS:FIELDGET("RET")
       	   	  aVAL[nPOSUSO][3]+=oCRRSAPS:FIELDGET("SUC")
       	   	  aVAL[nPOSUSO][4]+=oCRRSAPS:FIELDGET("DEV")
       	   ELSE
       	   	  AAdd(Aset,oCRRSAPS:FIELDGET("SETCOD"))
       	   	  AAdd(AVAL,{oCRRSAPS:FIELDGET("QTDE"),oCRRSAPS:FIELDGET("RET"),oCRRSAPS:FIELDGET("SUC"),oCRRSAPS:FIELDGET("DEV")})
           ENDIF	
   	       oCRRSAPS:SKIP()
       ENDDO
   ENDIF
   SELF:SERVER:SKIP()	
ENDDO	
SELF:SERVER:GOTOP()	
SELF:SERVER:SEEK(nSEQINI)
SELF:SERVER:FIELDPUT(cVAR+"PRO",nPRO)
SELF:SERVER:FIELDPUT(cVAR+"RET",nRET)
SELF:SERVER:FIELDPUT(cVAR+"SUC",nSUC)
SELF:SERVER:FIELDPUT(cVAR+"DEV",nDEV)
SELF:SERVER:FIELDPUT(cVAR+"TOT",nDEV+nRET+nSUC)
SELF:SERVER:FIELDPUT(cVAR+"INI",dINI)
SELF:SERVER:FIELDPUT(cVAR+"FIM",dFIM)
SELF:SERVER:FIELDPUT(cVAR+"PPM",CALCPPM(SELF:SERVER:FIELDGET(cVAR+"TOT"),SELF:SERVER:FIELDGET(cVAR+"PRO")))
SELF:SERVER:FIELDPUT(cVAR+"PPMRET",CALCPPM(SELF:SERVER:FIELDGET(cVAR+"RET"),SELF:SERVER:FIELDGET(cVAR+"PRO")))
SELF:SERVER:FIELDPUT(cVAR+"PPMDEV",CALCPPM(SELF:SERVER:FIELDGET(cVAR+"DEV"),SELF:SERVER:FIELDGET(cVAR+"PRO")))
SELF:SERVER:FIELDPUT(cVAR+"PPMSUC",CALCPPM(SELF:SERVER:FIELDGET(cVAR+"SUC"),SELF:SERVER:FIELDGET(cVAR+"PRO")))
FOR X:=1 TO Len(aSET)
  oCRRSAPS:GOTOP()
  IF oCRRSAPS:SEEK(Str(nseqINI,3)+ASET[X])
     oCRRSAPS:FIELDPUT(cVAR+"PRO",aVAL[X][1])
     oCRRSAPS:FIELDPUT(cVAR+"RET",aVAL[X][2])
     oCRRSAPS:FIELDPUT(cVAR+"SUC",aVAL[X][3])
     oCRRSAPS:FIELDPUT(cVAR+"DEV",aVAL[X][4])
     oCRRSAPS:FIELDPUT(cVAR+"TOT",aVAL[X][2]+aVAL[X][3]+aVAL[X][4])
     oCRRSAPS:FIELDPUT(cVAR+"PPM",CALCPPM(oCRRSAPS:FIELDGET(cVAR+"TOT"),oCRRSAPS:FIELDGET(cVAR+"PRO")))
     oCRRSAPS:FIELDPUT(cVAR+"PPMRET",CALCPPM(oCRRSAPS:FIELDGET(cVAR+"RET"),oCRRSAPS:FIELDGET(cVAR+"PRO")))
     oCRRSAPS:FIELDPUT(cVAR+"PPMDEV",CALCPPM(oCRRSAPS:FIELDGET(cVAR+"DEV"),oCRRSAPS:FIELDGET(cVAR+"PRO")))
     oCRRSAPS:FIELDPUT(cVAR+"PPMSUC",CALCPPM(oCRRSAPS:FIELDGET(cVAR+"SUC"),oCRRSAPS:FIELDGET(cVAR+"PRO")))
  ENDIF	
NEXT X
oCRRSAPS:CLOSE()
SELF:POINTER:=POINTER{POINTERARROW}
alert("Apuracao Concluida")
SELF:oDCApurando:Caption:=""

METHOD Apurarcli( ) 
	SELF:ApurarcliX(0)

METHOD Apurarcli1( ) 
		SELF:ApurarcliX(1)

METHOD ApurarcliX(nTIPO ) 
LOCAL oCRRSAPC AS USEREDE
LOCAL oARQ AS DBSERVER
LOCAL aDAD AS ARRAY	
LOCAL cVAR,cDIRE AS STRING
LOCAL nQTDE,nTOTAL AS FLOAT
LOCAL nSEQ,nCLIENTE AS DWORD
LOCAL dINI,dFIM AS DATE
    LOCAL nLASTREC AS DWORD
    LOCAL nPOS AS DWORD
    LOCAL nPERC AS INT


SELF:POINTER:=POINTER{POINTERHOURGLASS}
nSEQ:=SELF:SERVER:FIELDGET("SEQ")
LIMPARSEQ("CRRSAPC.DBF",Str(nSEQ,3),nSEQ)
nTOTAL:=0
dINI:=SELF:SERVER:DIAINI
dFIM:=SELF:SERVER:DIAFIM

aDAD:={zCURINI,"CRRSAPC.DBF",zCURDIR}
oCRRSAPC:=USEREDE{aDAD}
IF oCRRSAPC:nERRO#0
   RETURN .f.
ENDIF	

IF nTIPO=0
   cVAR:="M2"+Right(StrZero(Year(dINI),4),2)+StrZero(Month(dINI),2)
   cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(Year(dINI),4)+"\"
ELSE
   cVAR:="IC"+Right(StrZero(Year(dINI),4),2)+StrZero(Month(dINI),2)
   cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(Year(dINI),4)+"\"
   //cDIRE:=PEGINIVAL(ZCURINI,"PATH","MANA5PRO")	
ENDIF

oARQ := DBSERVER{cDIRE+cVAR+".DBF",DBSHARED,,"DBFCDX"}
IF nTIPO=0
   oARQ:SetOrder(2)
ELSE
   oARQ:SetOrder(6)	
ENDIF

IF ! oARQ:USED
    oCRRSAPC:CLOSE()
    RETURN .f.
ENDIF

nLASTREC:=OARQ:RecCount
nPOS:=0


oARQ:GOTOP()
WHILE ! oARQ:EOF
	

	nQTDE:=0
	nCLIENTE:=OARQ:FIELDGET("FORNECEDO")
    SELF:oDCApurando:Caption:="Apurando Cliente: "+Str(nCLIENTE)
    WHILE oARQ:FIELDGET("FORNECEDO")=nCLIENTE .AND. ! oARQ:EOF
    	 nPerc := INT(100* nPOS/ nLASTREC)
          SELF:oDcProgBar:Position := nPerc
  	      nPOS++

    	  IF nTIPO=0
             IF oARQ:FIELDGET("APURA")<>"N" .AND. oARQ:FIELDGET("ESPECIE")<>"NFC" .AND. oARQ:FIELDGET("TIPOENT")=="P"
                IF oARQ:FIELDGET("DATA")>=dINI .AND. oARQ:FIELDGET("DATA")<=dFIM
                    DO CASE
                       CASE oARQ:FIELDGET("UNID")="ML"
                            nQTDE+=oARQ:FIELDGET("QTDE")*1000
                       CASE oARQ:FIELDGET("UNID")="CT"
                            nQTDE+=oARQ:FIELDGET("QTDE")*100
                       OTHERWISE
                            nQTDE+=oARQ:FIELDGET("QTDE")
                    ENDCASE
                 ENDIF
              ENDIF
           ELSE
           	 IF oARQ:FIELDGET("DATA")>=dINI .AND. oARQ:FIELDGET("DATA")<=dFIM
                nQTDE+=oARQ:FIELDGET("QTDE")
           	 ENDIF	
           ENDIF	
           oARQ:SKIP()
      ENDDO
      IF nQTDE>0
      	 nTOTAL+=nQTDE
      	 oCRRSAPC:GOTOP()
	     IF ! oCRRSAPC:SEEK(Str(nSEQ,3)+Str(nCLIENTE,8))
	        oCRRSAPC:Append()
	        oCRRSAPC:FIELDPUT("SEQ",nSEQ)
	        oCRRSAPC:FIELDPUT("CLIENTE",nCLIENTE)
	     ELSE
	      	WHILE ! oCRRSAPC:RLOCK()    
	      		NOP
	      	ENDDO	
	     ENDIF	
         oCRRSAPC:FIELDPUT("QTDE",nQTDE)	
         oCRRSAPC:UNLOCK()	
      ENDIF	
ENDDO
oARQ:CLOSE()
oCRRSAPC:CLOSE()
SELF:POINTER:=POINTER{POINTERARROW}
alert("Apuracao Cliente Concluida")
SELF:oDCApurando:Caption:=""	
	

METHOD Apurarerr( ) 
LOCAL aDAD AS ARRAY
LOCAL oRNC,oRNCI,oCRRSAPS AS USEREDE	
LOCAL nDEVTOT,nRETTOT,nSUCTOT,nSEQ,nRNC AS DWORD
    LOCAL nLASTREC AS DWORD
    LOCAL nPOS AS DWORD
    LOCAL nPERC AS INT


SELF:POINTER:=POINTER{POINTERHOURGLASS}
SELF:CRIASET(2)
nSEQ:=SELF:SERVER:FIELDGET("SEQ")
aDAD:={zCURINI,"CRRSAPS.DBF",zCURDIR}
oCRRSAPS:=USEREDE{aDAD}
IF oCRRSAPS:nERRO#0
   RETURN .f.
ENDIF
aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oRNC:=USEREDE{aDAD}
IF oRNC:nERRO#0
  oCRRSAPS:CLOSE()
   RETURN .f.
ENDIF
aDAD:={zCURINI,"RNCI.DBF",zCURDIR}
oRNCI:=USEREDE{aDAD}
IF oRNCI:nERRO#0
   oRNC:CLOSE()
   oCRRSAPS:CLOSE()
   RETURN .f.
ENDIF


nDEVTOT:=0
nRETTOT:=0
nSUCTOT:=0
nLASTREC:=ORNC:RecCount
nPOS:=0

oRNC:SETORDER(2)
oRNC:GOTOP()
oRNC:SEEK(SELF:SERVER:DIAINI)
WHILE ! oRNC:EOF .AND. (SELF:SERVER:DIAFIM)>=(oRNC:FIELDGET("DATA"))
	nPerc := INT(100* nPOS/ nLASTREC)
    SELF:oDcProgBar:Position := nPerc
	nPOS++

	 nRNC:=oRNC:FIELDGET("RNC")
	 SELF:oDCApurando:Caption:="Apurando RNC: "+Str(nRNC)
     IF oRNC:FIELDGET("TIPCAD")=="C"
	    oRNCI:GOTOP()
   	    oRNCI:SEEK(nRNC)
    	WHILE oRNCI:FIELDGET("RNC")=nRNC .AND. ! oRNCI:EOF
              IF oRNC:FIELDGET("TIPCAD")=="C"
                 DO CASE
	                CASE oRNC:FIELDGET("CODRET")=="R"
   	                     nRETTOT+=oRNCI:FIELDGET("QTNC")
       	            CASE oRNC:FIELDGET("CODRET")=="S"
         	             nSUCTOT+=oRNCI:FIELDGET("QTNC")
            	    CASE oRNC:FIELDGET("CODRET")=="D" .OR. oRNC:FIELDGET("CODRET")=="E"
         	             nDEVTOT+=oRNCI:FIELDGET("QTNC")
    	         ENDCASE
              	 oCRRSAPS:GOTOP()
                 IF  oCRRSAPS:SEEK(Str(NSEQ,3)+oRNCI:FIELDGET("SETCOD"))
                 	DO CASE
	                   CASE oRNC:FIELDGET("CODRET")=="R"
   	                    	oCRRSAPS:FIELDPUT("RET",oRNCI:FIELDGET("QTNC")+oCRRSAPS:FIELDGET("RET"))
       	               CASE oRNC:FIELDGET("CODRET")=="S"
   	                        oCRRSAPS:FIELDPUT("SUC",oRNCI:FIELDGET("QTNC")+oCRRSAPS:FIELDGET("SUC"))
            	       CASE oRNC:FIELDGET("CODRET")=="D" .OR. oRNC:FIELDGET("CODRET")=="E"
   	                        oCRRSAPS:FIELDPUT("DEV",oRNCI:FIELDGET("QTNC")+oCRRSAPS:FIELDGET("DEV"))
    	            ENDCASE
    	         ENDIF
               ENDIF
               oRNCI:SKIP()
  	      ENDDO
 	   ENDIF
      oRNC:SKIP()
ENDDO
oRNC:CLOSE()
oRNCI:CLOSE()
oCRRSAPS:CLOSE()

SELF:PPMSET()

SELF:SERVER:FIELDPUT("RET",nRETTOT)
SELF:SERVER:FIELDPUT("SUC",nSUCTOT)
SELF:SERVER:FIELDPUT("DEV",nDEVTOT)	
SELF:CALCULAR()	
SELF:POINTER:=POINTER{POINTERARROW}
alert("Apuracao RNC Concluida")
SELF:oDCApurando:Caption:=""

METHOD Apurarmy( ) 
LOCAL oARQ AS DBSERVER	
LOCAL cVAR,cDIRE AS STRING
LOCAL nTOTAL AS DWORD
    LOCAL nLASTREC AS DWORD
    LOCAL nPOS AS DWORD
    LOCAL nPERC AS INT

cVAR:="MY"+Right(StrZero(Year(SELF:SERVER:DIAINI),4),2)+StrZero(Month(SELF:SERVER:DIAINI),2)
cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(Year(SELF:SERVER:DIAINI),4)+"\"
      
nTOTAL:=0


SELF:POINTER:=POINTER{POINTERHOURGLASS}
oARQ := DBSERVER{cDIRE+cVAR+".DBF",DBSHARED}
IF ! oARQ:USED
    RETURN .f.
ENDIF

nLASTREC:=OARQ:RecCount
nPOS:=0

oARQ:GOTOP()
WHILE ! oARQ:EoF
   nPerc := INT(100* nPOS/ nLASTREC)
    SELF:oDcProgBar:Position := nPerc
	nPOS++

	SELF:oDCApurando:Caption:="Apurando Entrada Estoque: "+Str(oARQ:RecNo)
	IF oARQ:FIELDGET("TIPO1")="E" .AND. oARQ:FIELDGET("TIPO2")="P"
       nTOTAL+=oARQ:FIELDGET("QTDE")		
	ENDIF	
	oARQ:SKIP()
ENDDO	
oARQ:CLOSE()
SELF:SERVER:FIELDPUT("PRODMY",nTOTAL)
SELF:POINTER:=POINTER{}
alert("Apuracao Entrada de Estoque Concluida")
SELF:oDCApurando:Caption:=""

METHOD Apurarprd( ) 
	SELF:Apurarprdx(0)

METHOD Apurarprd1( ) 
		SELF:Apurarprdx(1)

METHOD Apurarprdx(Ntipo ) 
LOCAL oMS01,oMS01X,oCRRSAPP,oCRRSAPS AS USEREDE
LOCAL oARQ AS DBSERVER
LOCAL aDAD AS ARRAY	
LOCAL cVAR,cDIRE,cCODIGO,cSEQAREA,cNOME,cPRODUSO AS STRING
LOCAL nQTDE,nTOTAL AS FLOAT
LOCAL nSEQ AS DWORD
LOCAL dINI,dFIM AS DATE
LOCAL J AS BYTE
    LOCAL nLASTREC AS DWORD
    LOCAL nPOS AS DWORD
    LOCAL nPERC AS INT


SELF:POINTER:=POINTER{POINTERHOURGLASS}
SELF:criaset(1)
nSEQ:=SELF:SERVER:FIELDGET("SEQ")
LIMPARSEQ("CRRSAPP.DBF",Str(nSEQ,3),nSEQ)
nTOTAL:=0
dINI:=SELF:SERVER:DIAINI
dFIM:=SELF:SERVER:DIAFIM

aDAD:={zCURINI,"MS01.DBF",zCURDIR}
oMS01:=USEREDE{aDAD}
IF oMS01:nERRO#0
   RETURN .f.
ENDIF	


aDAD:={zCURINI,"MS01X.DBF",zCURDIR}
oMS01X:=USEREDE{aDAD}
IF oMS01X:nERRO#0
   oMS01:CLOSE()
   RETURN .f.
ENDIF	

aDAD:={zCURINI,"CRRSAPP.DBF",zCURDIR}
oCRRSAPP:=USEREDE{aDAD}
IF oCRRSAPP:nERRO#0
   oMS01:CLOSE()
   oMS01X:CLOSE()
   RETURN .f.
ENDIF	
aDAD:={zCURINI,"CRRSAPS.DBF",zCURDIR}
oCRRSAPS:=USEREDE{aDAD}
IF oCRRSAPS:nERRO#0
   oMS01:CLOSE()
   oMS01X:CLOSE()
   oCRRSAPP:Close()
   RETURN .f.
ENDIF



IF nTIPO=0
   cVAR:="M2"+Right(StrZero(Year(dINI),4),2)+StrZero(Month(dINI),2)
   cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(Year(dINI),4)+"\"
ELSE
   cVAR:="IC"+Right(StrZero(Year(dINI),4),2)+StrZero(Month(dINI),2)
   cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(Year(dINI),4)+"\"
   //cDIRE:=PEGINIVAL(ZCURINI,"PATH","MANA5PRO")	
ENDIF

IF ! File(cDIRE+cVAR+".DBF")
   IF nTIPO=0	
      alert("Notas Fiscais de Saida ainda nao fechadas")
      alert("Apure apos o fechamento")
   ELSE
      alert("IAC ainda nao importadas")
      alert("Importe o IAC ANTES")
   ENDIF
   oMS01:CLOSE()
   oMS01X:CLOSE()
   oCRRSAPP:CLOSE()
   oCRRSAPS:close()
   RETURN .f.
ENDIF	

//oSERVER:=DBSERVER{CARQ,,,"DBFCDX"}
//IF ! oSERVER:USED
//   RETU SELF
//ENDIF

oARQ := DBSERVER{cDIRE+cVAR+".DBF",DBSHARED,,"DBFCDX"}
IF ! oARQ:USED
    oMS01:CLOSE()
    oMS01X:CLOSE()
    oCRRSAPP:CLOSE()
    oCRRSAPS:close()
    RETURN .f.
ENDIF
OARQ:SetIndex(cDIRE+cVAR+".CDX")

//oARQ:SETINDEX(cDIRE+CVAR+".CDX")
IF nTIPO=0
   oARQ:SETORDER(5)	 //codigo
ELSE
   oARQ:SETORDER(3)  //codigo		
ENDIF


oMS01:SETORDER(2) //Codigo
oMS01X:SETORDER(2) //Codigo


nLASTREC:=OARQ:RecCount
nPOS:=0

oARQ:GOTOP()

WHILE Empty(oARQ:FIELDGET("CODIGO")) .AND. ! oARQ:EOF
	oARQ:SKIP()
ENDDO	

AltD()
WHILE ! oARQ:EOF
	
      cCODIGO:=AllTrim(oARQ:FIELDGET("CODIGO"))
      SELF:oDCApurando:Caption:="Apurando Produto: "+cCODIGO
      cSEQAREA:=""
      cNOME:=""
      cPRODUSO:=""
      oMS01:GOTOP()
      IF oMS01:SEEK(cCODIGO)
         cSEQAREA:=oMS01:FIELDGET("SEQAREA")
         cNOME:=oMS01:FIELDGET("NOME")
         cPRODUSO:=oMS01:FIELDGET("PRODUSO")
      ELSE
      	 oMS01X:GOTOP()
         IF oMS01:SEEK(cCODIGO)
            cSEQAREA:=oMS01:FIELDGET("SEQAREA")
            cNOME:=oMS01:FIELDGET("NOME")
            cPRODUSO:=oMS01:FIELDGET("PRODUSO")
         ENDIF
      ENDIF
      nQTDE:=0
      WHILE AllTrim(oARQ:FIELDGET("CODIGO"))=cCODIGO .AND. ! oARQ:EOF
      		nPerc := INT(100* nPOS/ nLASTREC)
            SELF:oDcProgBar:Position := nPerc
	        nPOS++
      	   IF nTIPO=0
              IF oARQ:FIELDGET("APURA")<>"N" .AND. oARQ:FIELDGET("ESPECIE")<>"NFC" .AND. oARQ:FIELDGET("TIPOENT")=="P"
                 IF oARQ:FIELDGET("DATA")>=dINI .AND. oARQ:FIELDGET("DATA")<=dFIM
                    DO CASE
                       CASE oARQ:FIELDGET("UNID")="ML"
                            nQTDE+=oARQ:FIELDGET("QTDE")*1000
                       CASE oARQ:FIELDGET("UNID")="CT"
                            nQTDE+=oARQ:FIELDGET("QTDE")*100
                       OTHERWISE
                            nQTDE+=oARQ:FIELDGET("QTDE")
                    ENDCASE
                 ENDIF
              ENDIF
           ELSE
           	  IF oARQ:FIELDGET("DATA")>=dINI .AND. oARQ:FIELDGET("DATA")<=dFIM
           	  	 nQTDE+=oARQ:FIELDGET("QTDE")
           	  ENDIF	
           ENDIF	
           oARQ:SKIP()
      ENDDO
      IF nQTDE>0
      	 nTOTAL+=nQTDE
      	 oCRRSAPP:GOTOP()
	     IF ! oCRRSAPP:SEEK(Str(nSEQ,3)+cCODIGO)
	        oCRRSAPP:Append()
	        oCRRSAPP:FIELDPUT("SEQ",nSEQ)
	        oCRRSAPP:FIELDPUT("CODIGO",cCODIGO)
	        oCRRSAPP:FIELDPUT("NOME",cNOME)
	        oCRRSAPP:FIELDPUT("PRODUSO",cPRODUSO)	
	        oCRRSAPP:FIELDPUT("QTDE",nQTDE)
	      ENDIF
	      FOR J:= 1 TO 9
	          IF At(Chr(48+J),cSEQAREA)>0
	          	 oCRRSAPP:FIELDPUT("SET"+StrZero(J,2),nQTDE)	
                 IF OCRRSAPS:SEEK(Str(nseq,3)+Str(J,1))
                    OcrRSAPS:FIELDPUT("QTDE",oCRRSAPS:FIELDGET("QTDE")+nQTDE)
                 ENDIF	
              ENDIF
	      NEXT J
      ENDIF	
ENDDO
oARQ:CLOSE()
oMS01:CLOSE()
oMS01X:CLOSE()

oCRRSAPP:CLOSE()
oCRRSAPs:CLOSE()
SELF:SERVER:FIELDPUT("PRODMES",nTOTAL)
SELF:SERVER:FIELDPUT("PRODNF",nTOTAL)
SELF:CALCULAR()
SELF:PPMSET()
SELF:POINTER:=POINTER{POINTERARROW}
alert("Apuracao Producao Concluida")
SELF:oDCApurando:Caption:=""

METHOD apurarsint54( ) 
LOCAL oMS01,oMS01X,oCRRSAPP,oCRRSAPS,oARQ AS USEREDE
LOCAL aDAD AS ARRAY	
LOCAL cCODIGO,cSEQAREA,cNOME,cPRODUSO AS STRING
LOCAL nQTDE,nTOTAL AS FLOAT
LOCAL nSEQ AS DWORD
//LOCAL dINI,dFIM AS DATE
LOCAL J AS BYTE
    LOCAL nLASTREC AS DWORD
    LOCAL nPOS AS DWORD
    LOCAL nPERC AS INT



SELF:POINTER:=POINTER{POINTERHOURGLASS}
SELF:criaset(1)
nSEQ:=SELF:SERVER:FIELDGET("SEQ")
LIMPARSEQ("CRRSAPP.DBF",Str(nSEQ,3),nSEQ)
nTOTAL:=0
//dINI:=SELF:SERVER:DIAINI
//dFIM:=SELF:SERVER:DIAFIM
aDAD:={zCURINI,"MS01.DBF",zCURDIR}
oMS01:=USEREDE{aDAD}
IF oMS01:nERRO#0
   RETURN .f.
ENDIF	
aDAD:={zCURINI,"MS01X.DBF",zCURDIR}
oMS01X:=USEREDE{aDAD}
IF oMS01X:nERRO#0
   oMS01:CLOSE()
   RETURN .f.
ENDIF	
aDAD:={zCURINI,"CRRSAPP.DBF",zCURDIR}
oCRRSAPP:=USEREDE{aDAD}
IF oCRRSAPP:nERRO#0
   oMS01:CLOSE()
   oMS01X:CLOSE()
   RETURN .f.
ENDIF	
aDAD:={zCURINI,"CRRSAPS.DBF",zCURDIR}
oCRRSAPS:=USEREDE{aDAD}
IF oCRRSAPS:nERRO#0
   oMS01:CLOSE()
   oCRRSAPP:Close()
   oMS01X:CLOSE()
   RETURN .f.
ENDIF

aDAD:={zCURINI,"SINT54.DBF",zCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    oMS01:CLOSE()
    oMS01X:CLOSE()
    oCRRSAPP:CLOSE()
    oCRRSAPS:close()
    RETURN .f.
ENDIF



oARQ:SETORDER(4) //codigo


oMS01:SETORDER(2) //Codigo
oMS01:GOTOP()



AltD()
nLASTREC:=oMS01:RecCount
nPOS:=0

oARQ:GOTOP()
WHILE ! oARQ:EOF
      cCODIGO:=AllTrim(oARQ:FIELDGET("CODIGO"))
      SELF:oDCApurando:Caption:="Apurando Produto: "+cCODIGO


      cSEQAREA:=""
      cNOME:=""
      cPRODUSO:=""
      oMS01:GOTOP()
      IF oMS01:SEEK(cCODIGO)
         cSEQAREA:=oMS01:FIELDGET("SEQAREA")
         cNOME:=oMS01:FIELDGET("NOME")
         cPRODUSO:=oMS01:FIELDGET("PRODUSO")
      ELSE
      	 oMS01X:GOTOP()
         IF oMS01:SEEK(cCODIGO)
            cSEQAREA:=oMS01:FIELDGET("SEQAREA")
            cNOME:=oMS01:FIELDGET("NOME")
            cPRODUSO:=oMS01:FIELDGET("PRODUSO")
         ENDIF
      ENDIF

      nQTDE:=0

      WHILE AllTrim(oARQ:FIELDGET("CODIGO"))=cCODIGO .AND. ! oARQ:EOF
      		nPerc := INT(100* nPOS/ nLASTREC)
           SELF:oDcProgBar:Position := nPerc
       	   nPOS++
           IF oARQ:FIELDGET("TIPOENT")=="P"
              nQTDE+=oARQ:FIELDGET("QTDE")
           ENDIF
           oARQ:SKIP()
      ENDDO
      IF nQTDE>0
      	 nTOTAL+=nQTDE
      	 oCRRSAPP:GOTOP()
	     IF ! oCRRSAPP:SEEK(Str(nSEQ,3)+cCODIGO)
	        oCRRSAPP:Append()
	        oCRRSAPP:FIELDPUT("SEQ",nSEQ)
	        oCRRSAPP:FIELDPUT("CODIGO",cCODIGO)
	        oCRRSAPP:FIELDPUT("NOME",cNOME)
	        oCRRSAPP:FIELDPUT("PRODUSO",cPRODUSO)	
	        oCRRSAPP:FIELDPUT("QTDE",nQTDE)
	     ELSE
	      	WHILE ! oCRRSAPP:RLOCK()    
	      		NOP
	      	ENDDO	
	      ENDIF	
	      FOR J:= 1 TO 9
	          IF At(Chr(48+J),cSEQAREA)>0
	          	 oCRRSAPP:FIELDPUT("SET"+StrZero(J,2),nQTDE)	
                 IF OCRRSAPS:SEEK(Str(nseq,3)+Str(J,1))
                    OcrRSAPS:FIELDPUT("QTDE",oCRRSAPS:FIELDGET("QTDE")+nQTDE)
                 ENDIF	
              ENDIF
	      NEXT J
	      ocrrsapp:Unlock()	
      ENDIF	
ENDDO
oARQ:CLOSE()
oMS01:CLOSE()
oCRRSAPP:CLOSE()
oCRRSAPs:CLOSE()
SELF:SERVER:FIELDPUT("PRODMES",nTOTAL)
SELF:SERVER:FIELDPUT("PRODNF",nTOTAL)
SELF:CALCULAR()
SELF:PPMSET()
SELF:POINTER:=POINTER{POINTERARROW}
alert("Apuracao Producao Concluida")
SELF:oDCApurando:Caption:=""	

METHOD apurarsint55( ) 
LOCAL oCRRSAPC AS USEREDE
LOCAL oARQ AS userede
LOCAL aDAD AS ARRAY	
LOCAL nQTDE,nTOTAL AS FLOAT
LOCAL nSEQ,nCLIENTE AS DWORD
//LOCAL dINI,dFIM AS DATE
    LOCAL nLASTREC AS DWORD
    LOCAL nPOS AS DWORD
    LOCAL nPERC AS INT


SELF:POINTER:=POINTER{POINTERHOURGLASS}
nSEQ:=SELF:SERVER:FIELDGET("SEQ")
LIMPARSEQ("CRRSAPC.DBF",Str(nSEQ,3),nSEQ)
nTOTAL:=0
//dINI:=SELF:SERVER:DIAINI
//dFIM:=SELF:SERVER:DIAFIM

aDAD:={zCURINI,"CRRSAPC.DBF",zCURDIR}
oCRRSAPC:=USEREDE{aDAD}
IF oCRRSAPC:nERRO#0
   RETURN .f.
ENDIF	


aDAD:={zCURINI,"SINT54.DBF",zCURDIR}
oArq:=USEREDE{aDAD}
IF oARQ:nERRO#0
    oARQ:CLOSE()
    RETURN .f.
ENDIF
oARQ:SETORDER(5) //FORNECEDO

nLASTREC:=oARQ:RecCount
nPOS:=0

oARQ:GOTOP()
WHILE ! oARQ:EOF
	nQTDE:=0
	nCLIENTE:=OARQ:FIELDGET("FORNECEDO")
    SELF:oDCApurando:Caption:="Apurando Cliente: "+Str(nCLIENTE)
    WHILE oARQ:FIELDGET("FORNECEDO")=nCLIENTE .AND. ! oARQ:EOF
   		nPerc := INT(100* nPOS/ nLASTREC)
        SELF:oDcProgBar:Position := nPerc
	    nPOS++

        IF oARQ:FIELDGET("TIPOENT")=="P"
           nQTDE+=oARQ:FIELDGET("QTDE")
        ENDIF
        oARQ:SKIP()
    ENDDO
    IF nQTDE>0
   	   nTOTAL+=nQTDE
       oCRRSAPC:GOTOP()
	   IF ! oCRRSAPC:SEEK(Str(nSEQ,3)+Str(nCLIENTE,8))
	      oCRRSAPC:Append()
	      oCRRSAPC:FIELDPUT("SEQ",nSEQ)
	      oCRRSAPC:FIELDPUT("CLIENTE",nCLIENTE)
	   ELSE
	      WHILE ! oCRRSAPC:RLOCK()   
	      	NOP
	      ENDDO	
       ENDIF	
       oCRRSAPC:FIELDPUT("QTDE",nQTDE)	
       oCRRSAPC:UNLOCK()	
   ENDIF	
ENDDO
oARQ:CLOSE()
oCRRSAPC:CLOSE()
SELF:POINTER:=POINTER{POINTERARROW}
alert("Apuracao Cliente Concluida")
SELF:oDCApurando:Caption:=""	
		

METHOD APUSEM 
SELF:APURAR(1)

METHOD apusemacu( ) 
LOCAL oCRTS AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nSEQ,nSEQINI,nDEV,nSUC,nRET,nPRO AS DWORD
LOCAL W AS BYTE
//    LOCAL nLASTREC AS DWORD
//    LOCAL nPOS AS DWORD
//    LOCAL nPERC AS WORD


nSEQ:=SELF:SERVER:FIELDGET("SEQ")
nSEQINI:=SELF:SERVER:FIELDGET("SEQ")
aDAD:={zCURINI,"CRTS.DBF",zCURDIR}
oCRTS:=USEREDE{aDAD}
IF oCRTS:nERRO#0
   RETURN .f.
ENDIF

SELF:POINTER:=POINTER{POINTERHOURGLASS}
nPRO:=0
nRET:=0
nSUC:=0
nDEV:=0
FOR W:=1 UPTO 6
  	IF ! SELF:SERVER:BOF
       nPRO+=SELF:SERVER:FIELDGET("PRODMES")
       nRET+=SELF:SERVER:FIELDGET("RET")
       nSUC+=SELF:SERVER:FIELDGET("SUC")
       nDEV+=SELF:SERVER:FIELDGET("DEV")
    ENDIF
    SELF:SERVER:SKIP(-1)
NEXT W
IF ! oCRTS:SEEK(nSEQ)
   oCRTS:APPEND()
   oCRTS:FIELDPUT("SEQ",nSEQ)
ENDIF
oCRTS:FIELDPUT("PRODMES",nPRO)
oCRTS:FIELDPUT("RET",nRET)
oCRTS:FIELDPUT("SUC",nSUC)
oCRTS:FIELDPUT("DEV",nDEV)
oCRTS:FIELDPUT("PPMRET",CALCPPM(oCRTS:FIELDGET("RET"),oCRTS:FIELDGET("PRODMES")))
oCRTS:FIELDPUT("PPMDEV",CALCPPM(oCRTS:FIELDGET("DEV"),oCRTS:FIELDGET("PRODMES")))
oCRTS:FIELDPUT("PPMSUC",CALCPPM(oCRTS:FIELDGET("SUC"),oCRTS:FIELDGET("PRODMES")))
oCRTS:Close()
SELF:SERVER:GOTOP()
SELF:SERVER:SEEK(nSEQINI)
SELF:POINTER:=POINTER{POINTERARROW}
alert("Apuracao Semestral Acumulada Concluida")
SELF:oDCApurando:Caption:=""

METHOD Buscanum( ) 
	SELF:KeyFind()

METHOD CALCULAR 
SELF:SERVER:TOTMES:=SELF:SERVER:DEV+SELF:SERVER:SUC+SELF:SERVER:RET
SELF:SERVER:PPMRET:=CALCPPM(SELF:SERVER:RET,SELF:SERVER:PRODMES)
SELF:SERVER:PPMSUC:=CALCPPM(SELF:SERVER:SUC,SELF:SERVER:PRODMES)
SELF:SERVER:PPMDEV:=CALCPPM(SELF:SERVER:DEV,SELF:SERVER:PRODMES)
SELF:SERVER:PPMMES:=CALCPPM(SELF:SERVER:TOTMES,SELF:SERVER:PRODMES)
SELF:SERVER:COMMIT()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CRRS","")		

METHOD criaset(nTIPO) 
LOCAL aDAD AS ARRAY
LOCAL oCRRSSET,oCRRSAPS AS USEREDE
LOCAL nSEQ AS DWORD
    LOCAL nLASTREC AS DWORD
    LOCAL nPOS AS DWORD
    LOCAL nPERC AS INT


nSEQ:=SELF:SERVER:FIELDGET("SEQ")
aDAD:={zCURINI,"CRRSAPS.DBF",zCURDIR}
oCRRSAPS:=USEREDE{aDAD}
IF oCRRSAPS:nERRO#0
   RETURN .f.
ENDIF
aDAD:={zCURINI,"CRRSSET.DBF",zCURDIR}
oCRRSSET:=USEREDE{aDAD}
IF oCRRSSET:nERRO#0
   oCRRSAPS:CLOSE()
   RETURN .f.
ENDIF
SELF:POINTER:=POINTER{POINTERHOURGLASS}

nLASTREC:=OCRRSSET:RecCount
nPOS:=0

oCRRSSET:GOTOP()
WHILE ! oCRRSSET:EoF
	nPerc := INT(100* nPOS/ nLASTREC)
    SELF:oDcProgBar:Position := nPerc
	nPOS++
	
   SELF:oDCApurando:Caption:="Apurando : "+Str(oCRRSSET:RecNo)
   IF oCRRSSET:FIELDGET("GRAFICO")
   	  IF ! OCRRSAPS:SEEK(Str(nseq,3)+oCRRSSET:FIELDGET("CODIGO"))
   	  	 OCRRSAPS:Append()
         OcrRSAPS:FIELDPUT("SEQ",nSEQ)
         oCRRSAPS:FIELDPUT("SETCOD",oCRRSSET:FIELDGET("CODIGO"))
         oCRRSAPS:FIELDPUT("SETOR",oCRRSSET:FIELDGET("NOME"))
         oCRRSAPS:FIELDPUT("SETCOG",oCRRSSET:FIELDGET("COGNOME"))
      ELSE
         IF nTIPO=1
         	oCRRSAPS:FIELDPUT("QTDE",0)
         ENDIF
         IF nTIPO=2
         	oCRRSAPS:FIELDPUT("DEV",0)
         	oCRRSAPS:FIELDPUT("SUC",0)
         	oCRRSAPS:FIELDPUT("SUC",0)
         ENDIF
      ENDIF
   ENDIF
   oCRRSSET:Skip()	
ENDDO
oCRRSSET:CLOSE()	
oCRRSAPS:Close()
SELF:POINTER:=POINTER{POINTERARROW}
//alert("Apuracao Concluida") A mensagem vai nos outros
SELF:oDCApurando:Caption:=""

METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:limpar()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skipex(-1)
ENDIF	

METHOD LIMPAR 
LOCAL nSEQ AS DWORD
nSEQ:=SELF:SERVER:SEQ
SELF:oDCApurando:Caption:="Apagando Apuracao Erros"
LIMPARSEQ("CRRSAPS.DBF",Str(nSEQ,3),nSEQ)
SELF:oDCApurando:Caption:="Apagando Apuracao Produtos"
LIMPARSEQ("CRRSAPP.DBF",Str(nSEQ,3),nSEQ)
SELF:oDCApurando:Caption:="Apagando Apuracao Cliente"
LIMPARSEQ("CRRSAPC.DBF",Str(nSEQ,3),nSEQ)
//LIMPARSEQ("SEQCL.DBF",Str(nSEQ,3),nSEQ)
//LIMPARSEQ("SEQPR.DBF",Str(nSEQ,3),nSEQ)
SELF:oDCApurando:Caption:=""
alert("Apuracao Apagada")

METHOD pegcomp( ) 
	SELF:server:ano:=Year(SELF:server:DIAINI)
	SELF:server:mes:=Month(SELF:server:diafim)
	SELF:server:DESCRI:=MESSTR(SELF:server:mes,SELF:server:ano,1,2)
	SELF:server:DESCR2:=MESSTR(SELF:server:mes,SELF:server:ano,1,1)	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
      FabCenterWindow( SELF )
 RETURN SELF

METHOD PPMset() 
LOCAL aDAD AS ARRAY
LOCAL oCRRSAPS AS USEREDE
LOCAL nSEQ AS DWORD
//    LOCAL nLASTREC AS DWORD
//    LOCAL nPOS AS DWORD
//    LOCAL nPERC AS WORD


nSEQ:=SELF:SERVER:FIELDGET("SEQ")
aDAD:={zCURINI,"CRRSAPS.DBF",zCURDIR}
oCRRSAPS:=USEREDE{aDAD}
IF oCRRSAPS:nERRO#0
   RETURN .f.
ENDIF
SELF:POINTER:=POINTER{POINTERHOURGLASS}
oCRRSAPS:GOTOP()
oCRRSAPS:SEEK(Str(nSEQ,3))
WHILE oCRRSAPS:FIELDGET("SEQ")=nSEQ .AND. ! oCRRSAPS:EOF
    SELF:oDCApurando:Caption:="Apurando : "+Str(oCRRSAPS:RecNo)
	oCRRSAPS:FIELDPUT("QTDENC",oCRRSAPS:FIELDGET("DEV")+oCRRSAPS:FIELDGET("SUC")+oCRRSAPS:FIELDGET("RET"))
    oCRRSAPS:FIELDPUT("PPMRET",CALCPPM(oCRRSAPS:FIELDGET("RET"),oCRRSAPS:FIELDGET("QTDE")))
    oCRRSAPS:FIELDPUT("PPMSUC",CALCPPM(oCRRSAPS:FIELDGET("SUC"),oCRRSAPS:FIELDGET("QTDE")))
    oCRRSAPS:FIELDPUT("PPMDEV",CALCPPM(oCRRSAPS:FIELDGET("DEV"),oCRRSAPS:FIELDGET("QTDE")))
    oCRRSAPS:FIELDPUT("PPM",CALCPPM(oCRRSAPS:FIELDGET("QTDENC"),oCRRSAPS:FIELDGET("QTDE")))	
    oCRRSAPS:SKIP()
ENDDO
oCRRSAPS:CLOSE()
SELF:POINTER:=POINTER{POINTERARROW}
alert("Apuracao  Concluida")
SELF:oDCApurando:Caption:=""


	
	

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
