FUNC CALCPPM(nVAL,nVA2)
LOCAL nVA3 AS FLOAT
nVA3:=0
IF nVAL>0 .AND. nVA2>0
   nVA3:=INT(nVAL*1000000/nVA2)  //Recalculando PPM
ENDIF
RETU nVA3

FUNC checkcnq(nIND,eCHAVE,nVAL)
LOCAL oSERVER AS USEREDE
LOCAL ADAD AS ARRAY
LOCAL aRETU AS ARRAY
IF ValType(nVAL)#"N"
   nVAL:=0
ENDIF	
aRETU:={.F.,0}
aDAD:={zCURINI,"ACPNC.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0	
   oSERVER:CLOSE()
   RETU aRETU
ENDIF
oSERVER:SetOrder(nIND)
oSERVER:GOTOP()
IF oSERVER:SEEK(eCHAVE)
   aRETU[1]:=.T.
   aRETU[2]:=oSERVER:FIELDGET("VLI07")
   IF nVAL>0
   	  OSERVER:FIELDPUT("VLI07",nVAL)
   	  oserver:FIELDPUT("DATAFEC",oSERVER:FIELDGET("DATA"))
   ENDIF
ENDIF	
oSERVEr:CLOSE()
RETU aRETU

FUNCTION CMD3L(cCODIGO,cTIPO,aVAL)
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL aRETU AS ARRAY
aRETU:={.F.," ",0,"","","","",""}
//seek,Ctipo,racf,desc01-05)
aDAD:={zCURINI,"CRM3L.DBF",zCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
   RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(cCODIGO)
   aRETU[1]:=.T.
   IF cTIPO="D"
  	  aRETU[2]:="D"
      oARQ:Delete()
   ENDIF
   IF cTIPO="V"
  	  aRETU[2]:="V"
      aRETU[3]:=oARQ:FIELDGET("RACF")
   	  aRETU[4]:=oARQ:FIELDGET("DESC01")
   	  aRETU[5]:=oARQ:FIELDGET("DESC02")
   	  aRETU[6]:=oARQ:FIELDGET("DESC03")
   	  aRETU[7]:=oARQ:FIELDGET("DESC04")
   	  aRETU[8]:=oARQ:FIELDGET("DESC05")
   ENDIF	
ELSE
   aRETU[1]:=.F.
   IF cTIPO="I"
 	  aRETU[2]:="I"
   	  oARQ:Append()
   	  oARQ:FIELDPUT("CODIGO",cCODIGO)
   	  oARQ:FIELDPUT("RACF",aVAL[1])
  	  oARQ:FIELDPUT("DESC01",aVAL[2])
  	  oARQ:FIELDPUT("DESC02",aVAL[3])
  	  oARQ:FIELDPUT("DESC03",aVAL[4])
  	  oARQ:FIELDPUT("DESC04",aVAL[5])
  	  oARQ:FIELDPUT("DESC05",aVAL[6])
  	  oARQ:FIELDPUT("NVEZES",3)
   ENDIF
ENDIF
oARQ:CLOSE()
RETU aRETU

FUNC DIGANUM(nRNC,nRACF,nSAC)
IF nRNC>0
   alert("RNC Nº"+Str(nRNC),	"RNC Nº"+Str(nRNC))
ENDIF
IF nRACF>0
   alert("RACF Nº"+Str(nRACF),"RACF Nº"+Str(nRACF))	
ENDIF	
IF nSAC>0
   alert("SAC Nº"+Str(nSAC),"SAC Nº"+Str(nSAC))	
ENDIF	
	

FUNC ENVIARACF(nRNC,nRACF)
LOCAL aMAIL AS ARRAY
aMAIL:={}
AAdd(aMAIL,"RNC No:"+Str(nRNC))
AAdd(aMAIL,"RACF No:"+Str(nRACF))
EMAILINT("RACF0001",ZUSER,aMAIL,ZCURINI,zCURDIR)	
RETU .T.



FUNC ENVIARNC(nRNC,cTIPO,cCODIGO,aCAUSA)
LOCAL aMAIL AS ARRAY
LOCAL X AS WORD
aMAIL:={}
AAdd(Amail,"RNC No:"+Str(nRNC))
AAdd(Amail,"PECA No:"+AllTrim(cCODIGO))
AAdd(Amail,"Tipo:"+cTIPO)
IF ValType(aCAUSA)="A"
   AAdd(Amail,"Descrição:")
   FOR X:=1 TO 3
   	   IF ValType(aCAUSA[X])="C"
          AAdd(Amail," "+AllTrim(aCAUSA[X]))
       ENDIF
   NEXT X
ENDIF
EMAILINT("RNC00001",ZUSER,aMAIL,ZCURINI,zCURDIR)	
RETU .T.

FUNC ENVIARsac(nsac,cCODIGO,nCLIENTE,cCAUSA)
LOCAL aMAIL AS ARRAY
aMAIL:={}
AAdd(Amail," SAC No:"+Str(nSAC))
AAdd(Amail," Peca No:"+AllTrim(cCODIGO))
AAdd(Amail," Cliente No:"+Str(nCLIENTE))
AAdd(Amail," Problema:"+cCAUSA)
EMAILINT("SAC00001",ZUSER,aMAIL,ZCURINI,zCURDIR)	
RETU .T.



FUNC LIMPARSEQ(cARQ,cBUSCA,nSEQ)
LOCAL aDAD AS ARRAY
LOCAL oARQ AS USEREDE	
aDAD:={zCURINI,cARQ,zCURDIR}
oARQ:=USEREDE{aDAD,.F.}   //Abre Exclusivo Fazer Pack
IF oARQ:nERRO=0
   oARQ:GOTOP()
   oARQ:SEEK(cBUSCA)
   WHILE nSEQ=oARQ:FIELDGET("SEQ") .AND. ! oARQ:EOF
       oARQ:DELETE()
       oARQ:SKIP()
   ENDDO
   oARQ:PACK()
   oARQ:CLOSE()
ENDIF	
	

FUNC NOVOCNQ(aCAMPOS)
LOCAL nACPNC AS DWORD
LOCAL x AS BYTE
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL aUSO AS ARRAY	
//Cliente,Clinome,Codigo,Descriçao,RAT,RNC,DATA ,SAC,CompDep
//      1.      2      3         4   5    6   7 ,8,9

IF Empty(aCAMPOS[4])
   aUSO:=PEGMS01(aCAMPOS[3])
   IF aUSO[1]=.T. .AND. ! Empty(aUSO[2])
      aCAMPOS[4]:=aUSO[2]
   ENDIF	
ENDIF	
IF Empty(aCAMPOS[2])
   aUSO:=PEGMA01(aCAMPOS[1],zcurini,zcurdir)
   IF aUSO[1]=.T.
      aCAMPOS[2]:=aUSO[2]
   ENDIF
ENDIF
aDAD:={zCURINI,"ACPNC.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   oSERVER:CLOSE()
ENDIF
oSERVER:gobottom()
nACPNC:=oSERVER:FIELDGET("ACPNC")
nACPNC++
oSERVER:append()
oSERVER:FIELDPUT("ACPNC",nACPNC)
oSERVER:FIELDPUT("DATA",aCAMPOS[7])
oSERVER:FIELDPUT("CLIENTE",aCAMPOS[1])
oSERVER:FIELDPUT("CLINOME",aCAMPOS[2])
oSERVER:FIELDPUT("produto",aCAMPOS[3])
oSERVER:FIELDPUT("DESPRO",aCAMPOS[4])
oSERVER:FIELDPUT("RAT",aCAMPOS[5])
oSERVER:FIELDPUT("RNC",aCAMPOS[6])
oSERVER:FIELDPUT("SAC",aCAMPOS[8])
oSERVER:FIELDPUT("COMPETE",aCAMPOS[9])
FOR x:=1 TO 7
	oSERVER:FIELDPUT("QTI"+StrZero(X,2),0)
	oSERVER:FIELDPUT("VLI"+StrZero(X,2),0)	
NEXT X
FOR X:=1 TO 11
	oSERVER:FIELDPUT("QTE"+StrZero(X,2),0)
	oSERVER:FIELDPUT("VLE"+StrZero(X,2),0)		
NEXT X	






