PARTIAL CLASS jrat
METHOD Alteracod( ) 
LOCAL cCODIGO AS STRING
cCODIGO:=SELF:oSFJRATI:SERVER:FIELDGET("CODIGO")
cCODIGO:=AllTrim(Upper(cCODIGO))
IF Empty(cCODIGO) .OR. cCODIGO="DIVERSOS"
	SELF:oSFJRATI:SERVER:FIELDPUT("CODIGO",SELF:CODIGO)
ENDIF	

METHOD ALTERAR  
SELF:oSFJRATI:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJRATI:Browser:SuspendUpdate()
SELF:oSFJRATI:SkipPREVIOUS()
IF SELF:oSFJRATI:Server:BOF
	SELF:oSFJRATI:SkipNEXT()
ENDIF
SELF:oSFJRATI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nrat AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nrat:=SELF:Server:rat
nrat++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("RAT",nrat)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
RETURN .t.


METHOD buscaNUMERO( ) 
	SELF:KeyFind()
//LOCAL oBUSCA AS XBUSCA
//oBUSCA:=XBUSCA{SELF,"Localizar","Digite o Nº"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RAT","")		

METHOD cmdTIPO( ) 
LOCAL lVISITA,lRECCLI,lRELCLI AS LOGIC
LOCAL oBUSCA AS XBUSCA
lVISITA:=.F.
lRECCLI:=.F.
lRELCLI:=.F.
IF MDG("Reclamaçao de Cliente")
   lRECCLI:=.T.	
ELSE
   lVISITA:=.T.	
ENDIF	
IF lRECCLI
   IF MDG("Relatorio de Cliente")
   	  lRELCLI:=.T.
   ENDIF	
ENDIF	
IF ! lRECCLI
   SELF:SERVER:FIELDPUT("VISITA",lVISITA)
   SELF:SERVER:FIELDPUT("RECCLI",lRECCLI)	
   SELF:SERVER:FIELDPUT("RELCLI",lRELCLI)		
   RETURN .f.
ENDIF
IF lRELCLI	
   SELF:SERVER:FIELDPUT("VISITA",lVISITA)
   SELF:SERVER:FIELDPUT("RECCLI",lRECCLI)	
   SELF:SERVER:FIELDPUT("RELCLI",lRELCLI)	
   RETURN .f.
ENDIF
oBUSCA:=XBUSCA{SELF,"Confirmação","Confirme o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
    RETU SELF	
ENDIF
SELF:oDCCODIGO:TextValue:=OBUSCA:cBUSCA
IF SELF:INCLUIR()	
   SELF:SERVER:FIELDPUT("VISITA",lVISITA)
   SELF:SERVER:FIELDPUT("RECCLI",lRECCLI)	
   SELF:SERVER:FIELDPUT("RELCLI",lRELCLI)	
   SELF:SAC()
ELSE
   alert("Erro Preenchimento Tente Outra Vez")
ENDIF

METHOD CNQ()
LOCAL oACPNC AS USEREDE
LOCAL aDAD,aUSO AS ARRAY	
LOCAL oJAN AS jcnqext
LOCAL oJA2 AS XJCNQEXT
LOCAL nACPNC,Y AS DWORD

IF Empty(SELF:oSFJRATI:SERVER:FIELDGET("CODIGO"))
   alert("Codigo Produto em Branco")	
   RETURN .f.
ENDIF	

aDAD:={zCURINI,"ACPNC.DBF",ZCURDIR}
oACPNC:=USEREDE{aDAD}
IF oACPNC:nERRO#0
    RETURN .f.
ENDIF
oACPNC:GOTOP()
oACPNC:SETORDER(4)
IF ! oACPNC:SEEK(Str(SELF:SERVER:FIELDGET("RAT"),8)+SELF:oSFJRATI:FIELDGET("CODIGO"))
   oACPNC:SETORDER(1)		
   oACPNC:Gobottom()
   nACPNC:=oACPNC:FIELDGET("ACPNC")
   nACPNC++
   oACPNC:APPEND()
   oACPNC:FIELDPUT("ACPNC",nACPNC)
   oACPNC:FIELDPUT("DATA",SELF:SERVER:FIELDGET("DATA"))
   oACPNC:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIENTE"))
   oACPNC:FIELDPUT("CLINOME",SELF:SERVER:FIELDGET("CLINOME"))
   oACPNC:FIELDPUT("produto",SELF:oSFJRATI:SERVER:FIELDGET("CODIGO"))
   oACPNC:FIELDPUT("SAC",SELF:oSFJRATI:SERVER:FIELDGET("SAC"))
   aUSO:=PEGMS01(SELF:oSFJRATI:SERVER:FIELDGET("CODIGO"))
   IF aUSO[1]=.T. .AND. ! Empty(aUSO[2])
      oACPNC:FIELDPUT("DESPRO",aUSO[2])
   ENDIF
   oACPNC:FIELDPUT("RAT",SELF:SERVER:FIELDGET("RAT"))
   FOR Y:=1 TO 7
      oACPNC:FIELDPUT("QTI"+StrZero(Y,2),0)
      oACPNC:FIELDPUT("VLI"+StrZero(Y,2),0)	
   NEXT Y
   FOR Y:=1 TO 11
       oACPNC:FIELDPUT("QTE"+StrZero(Y,2),0)
       oACPNC:FIELDPUT("VLE"+StrZero(Y,2),0)		
   NEXT Y	
ENDIF
IF ! Empty(oACPNC:FIELDGET("DATAFEC"))
   alert("Ja Fechada")	
   oJA2:=XJCNQEXT{SELF,oACPNC}
   oJA2:SHOW()
ELSE
   oJAN:=jcnqext{SELF,,oACPNC}
   oJAN:SHOW()
ENDIF


METHOD DELETE() 
LOCAL aDAD AS ARRAY
LOCAL oACPNC AS USEREDE
	
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
   SELF:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJRATI:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJRATI:SERVER:gotop()
   WHILE ! SELF:oSFJRATI:SERVER:eof
	 	SELF:oSFJRATI:SERVER:delete()
	 	SELF:oSFJRATI:SERVER:skip()	
      ENDDO
	SELF:oSFJRATI:SERVER:resetnotification()
	SELF:oSFJRATI:SERVER:notify(notifyfilechange)
	SELF:server:delete()
	SELF:server:unlock()
	SELF:SERVER:RESETNOTIFICATION()
	SELF:SERVER:Notify(notifyfilechange)
	SELF:SERVER:SKIPex(-1)
ENDIF	

aDAD:={zCURINI,"ACPNC.DBF",ZCURDIR}
oACPNC:=USEREDE{aDAD}
IF oACPNC:nERRO#0
   RETU SELF
ENDIF
oACPNC:GOTOP()
oACPNC:SETORDER(4)
IF oACPNC:SEEK(Str(SELF:SERVER:FIELDGET("RAT"),8)+SELF:oSFJRATI:SERVER:FIELDGET("CODIGO"))
   oACPNC:DELETE()	
ENDIF
oACPNC:CLOSE()	
	

METHOD esccod() 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DENO",oESC:NOME)
ENDIF

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF

METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:oSFJRATI:SERVER:FIELDPUT("RESNUM",oESCMP04:NUMERO)
   SELF:oSFJRATI:SERVER:FIELDPUT("RESNOME",oESCMP04:NOME)
ENDIF

METHOD EXCLUIR 
IF  MDG("Apagar Registro") .AND. SELF:oSFJRATI:server:LockCurrentRecord()
    SELF:oSFJRATI:SERVER:SUSPENDNOTIFICATION()	
    SELF:oSFJRATI:server:delete()
    SELF:oSFJRATI:server:unlock()
    SELF:oSFJRATI:SERVER:resetnotification()
	SELF:oSFJRATI:SERVER:notify(notifyfilechange)
	SELF:oSFJRATI:Browser:refresh()
ENDIF	

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:oSFJRATI:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()	

METHOD INCLUIR 
LOCAL nRAT AS DWORD
LOCAL aCAMPOS AS ARRAY

IF Empty(SELF:SERVER:FIELDGET("CLIENTE"))
   alert("Cliente em Branco")	
   RETU .f.
ENDIF
IF Empty(SELF:SERVER:FIELDGET("CLINOME"))
   alert("Nome Cliente em Branco")	
   RETU .f.
ENDIF
IF Empty(SELF:CODIGO)
   alert("Codigo Produto em Branco")	
   RETU .F.
ENDIF
nRAT:=SELF:SERVER:FIELDGET("RAT")
SELF:oSFJRATI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJRATI:SERVER:APPEND()
SELF:oSFJRATI:SERVER:FIELDPUT("RAT",nRAT)
SELF:oSFJRATI:SERVER:FIELDPUT("CODIGO",SELF:CODIGO)
SELF:oSFJRATI:SERVER:commit()
SELF:oSFJRATI:SERVER:resetnotification()
SELF:oSFJRATI:SERVER:notify(notifyappend)
SELF:oSFJRATI:Browser:refresh()
aCAMPOS:={}
AAdd(aCAMPOS,SELF:SERVER:FIELDGET("CLIENTE"))
AAdd(aCAMPOS,SELF:SERVER:FIELDGET("CLINOME"))
AAdd(aCAMPOS,SELF:oSFJRATI:SERVER:FIELDGET("CODIGO"))
AAdd(aCAMPOS,"")
AAdd(Acampos,nRAT)
AAdd(aCAMPOS,0)
AAdd(aCAMPOS,SELF:SERVER:FIELDGET("DATA"))
AAdd(aCAMPOS,SELF:oSFJRATI:SERVER:FIELDGET("SAC"))
AAdd(aCAMPOS,"")
NOVOCNQ(aCAMPOS)
RETU .T.

METHOD PEGCLI 
LOCAL aUSO AS ARRAY
aUSO:=PEGMA01(SELF:SERVER:FIELDGET("CLIENTE"),zcurini,zcurdir)
IF aUSO[1]=.T.
    SELF:SERVER:CLINOME:=aUSO[2]
ENDIF


METHOD PEGRES 
LOCAL aUSO AS ARRAY
LOCAL aCOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
aUSO:=PEGMP04( SELF:oSFJRATI:SERVER:FIELDGET("RESNUM"),ZCURINI,ZCURDIR,ACOM)
IF aUSO[1]=.T.
    SELF:oSFJRATI:SERVER:FIELDPUT("RESNOME",aUSO[2])
ENDIF


METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
      FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJRATI:Browser:SuspendUpdate()
SELF:oSFJRATI:SkipNext()
IF SELF:oSFJRATI:Server:Eof
	SELF:oSFJRATI:SkipPrevious()
ENDIF
SELF:oSFJRATI:Browser:RestoreUpdate()

METHOD RACF()
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE	
LOCAL nRACF AS DWORD
LOCAL aMAIL AS ARRAY
IF ! Empty(SELF:oSFJRATI:SERVER:FIELDGET("RACF"))
   alert("Já Cadastrado RACF")
   RETURN .f.
ENDIF	
aDAD:={zCURINI,"RACF.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOBOTTOM()
nRACF:=oSERVER:FIELDGET("RACF")
nRACF++
oSERVER:APPEND()
oSERVER:FIELDPUT("RACF",nRACF)
oSERVER:FIELDPUT("DATA",Today())
oSERVER:FIELDPUT("RAT",SELF:SERVER:FIELDGET("RAT"))
oSERVER:FIELDPUT("DESENHO",SELF:oSFJRATI:SERVER:FIELDGET("CODIGO"))
oSERVER:FIELDPUT("QTL1",SELF:oSFJRATI:SERVER:FIELDGET("QTDE"))
oSERVER:FIELDPUT("RASTRO",SELF:oSFJRATI:SERVER:FIELDGET("RASTRO"))
oSERVER:FIELDPUT("DESC01",SELF:oSFJRATI:SERVER:FIELDGET("PROB01"))
oSERVER:FIELDPUT("DESC02",SELF:oSFJRATI:SERVER:FIELDGET("PROB02"))
oSERVER:FIELDPUT("DESC03",SELF:oSFJRATI:SERVER:FIELDGET("PROB03"))
oSERVER:FIELDPUT("ACAO01",SELF:oSFJRATI:SERVER:FIELDGET("ACAO01"))
oSERVER:FIELDPUT("ACAO02",SELF:oSFJRATI:SERVER:FIELDGET("ACAO02"))
oSERVER:FIELDPUT("ACAO03",SELF:oSFJRATI:SERVER:FIELDGET("ACAO03"))
oSERVER:FIELDPUT("RESPO",SELF:oSFJRATI:SERVER:FIELDGET("RESNOME"))
oSERVER:CLOSE()
SELF:oSFJRATI:SERVER:FIELDPUT("RACF",nRACF)
SELF:oSFJRATI:SERVER:FIELDPUT("LACAO",.T.)
aMAIL:={}
AAdd(aMAIL,"RAT No:"+StrTRIM(SELF:SERVER:FIELDGET("RAT"),8,0))
AAdd(aMAIL,"RACF No:"+StrTRIM(nRACF,8,0))
EMAILINT("RACF0002",ZUSER,aMAIL,ZCURINI,zCURDIR)	

METHOD SAC()
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE	
LOCAL nSAC AS DWORD
LOCAL cCAUSA AS STRING
IF ! Empty(SELF:oSFJRATI:SERVER:FIELDGET("SAC"))
   alert("Já Cadastrado Sac")
   RETURN .f.
ENDIF	
aDAD:={zCURINI,"SAC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOBOTTOM()
nSAC:=oSERVER:FIELDGET("SAC")
nSAC++
oSERVER:APPEND()
oSERVER:FIELDPUT("SAC",nSAC)
oSERVER:FIELDPUT("DATA",Today())
oSERVER:FIELDPUT("RAT",SELF:SERVER:FIELDGET("RAT"))
oSERVER:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIENTE"))
oSERVER:FIELDPUT("CLINOME",SELF:SERVER:FIELDGET("CLINOME"))
oSERVER:FIELDPUT("CODIGO",SELF:oSFJRATI:SERVER:FIELDGET("CODIGO"))
oSERVER:FIELDPUT("QTL",SELF:oSFJRATI:SERVER:FIELDGET("QTDE"))
oSERVER:FIELDPUT("RASTRO",SELF:oSFJRATI:SERVER:FIELDGET("RASTRO"))
oSERVER:FIELDPUT("DESC01",SELF:oSFJRATI:SERVER:FIELDGET("PROB01"))
oSERVER:FIELDPUT("DESC02",SELF:oSFJRATI:SERVER:FIELDGET("PROB02"))
oSERVER:FIELDPUT("DESC03",SELF:oSFJRATI:SERVER:FIELDGET("PROB03"))
oSERVER:FIELDPUT("INCUSER",ZUSER)
oSERVER:FIELDPUT("INCDATA",Today())
oSERVER:FIELDPUT("TIPO","R")

cCAUSA:=AllTrim(oSERVER:FIELDGET("DESC01"))+Chr(13)+Chr(10)
cCAUSA+=" "+AllTrim(oSERVER:FIELDGET("DESC01"))+Chr(13)+Chr(10)
cCAUSA+=" "+AllTrim(oSERVER:FIELDGET("DESC02"))+Chr(13)+Chr(10)	
cCAUSA+=" "+AllTrim(oSERVER:FIELDGET("DESC03"))+Chr(13)+Chr(10)
cCAUSA+=" "+AllTrim(oSERVER:FIELDGET("DESC04"))+Chr(13)+Chr(10)	
ENVIARsac(nSAC,oSERVER:FIELDGET("CODIGO"),oSERVER:FIELDGET("CLIENTE"),cCAUSA)	

oSERVER:CLOSE()
aDAD:={zCURINI,"SACI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF
oSERVER:APPEND()
oSERVER:FIELDPUT("SAC",nSAC)
oSERVER:FIELDPUT("PRAZO",SELF:oSFJRATI:SERVER:FIELDGET("PRAZO"))
oSERVER:FIELDPUT("RESPON",SELF:oSFJRATI:SERVER:FIELDGET("RESNOME"))
oSERVER:CLOSE()
SELF:oSFJRATI:SERVER:FIELDPUT("SAC",nSAC)
SELF:oSFJRATI:SERVER:FIELDPUT("LACAO",.T.)

METHOD TABULAR  
SELF:oSFJRATI:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJRATI:SERVER:Commit()


METHOD VerSac( ) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL oJAN AS XJSacDia
LOCAL aDAD AS ARRAY
IF Empty(SELF:oSFJRATI:SERVER:FIELDGET("SAC"))
   alert("Sac em Branco")	
   RETURN .f.
ENDIF	
IF ! entramenu("TGQ",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"SAC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOTOP()
IF ! oSERVER:SEEK(SELF:oSFJRATI:SERVER:FIELDGET("SAC"))
   OserveR:close()
   alert("Sac Não Encontrada")
   RETURN .f.
ENDIF	
aDAD:={zCURINI,"SACI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
oJAN:=XJSACDIA{SELF,oSERVER,oSERVE2}
oJAN:SHOW()		
	


END CLASS
