PARTIAL CLASS JCNQ
METHOD APPEND() 
LOCAL nNUMERO	AS DWORD
SELF:SERVER:SETORDER(1)
SELF:SERVER:GoBottom()
nNUMERO:=SELF:SERVER:FIELDGET("ACPNC")
nNUMERO:=nnumero+1
SUPER:Append()
SELF:SERVER:FIELDPUT("ACPNC",nNUMERO)
SELF:SERVER:FIELDPUT("DATA",Today())	
//alert("Operação Bloqueada")		

METHOD Buscanum 
	SELF:KEYFIND()
//LOCAL oBUSCA AS xBUSCA
//oBUSCA:=xBUSCA{SELF,"Localizar CNQ","Digite Nº"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF

METHOD BuscaRAT 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Localizar RAT","Digite Nº "}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(4)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(Str(Val(oBUSCA:cBUSCA),8))
ENDIF

METHOD BuscaRNC 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Localizar RNC","Digite Nº" }
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(3)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
ENDIF

METHOD BuscaSAC 
LOCAL oBUSCA AS xBUSCA
oBUSCA:=xBUSCA{SELF,"Localizar SAC","Digite Nº"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(5)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
ENDIF

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CNQ","")		

METHOD DELETE() 
IF ! Empty(SELF:server:FIELDGET("DATAFEC"))
   alert("Já Fechada")
   RETURN .F.
ENDIF		
IF SELF:SERVER:FIELDGET("RNC")+SELF:SERVER:FIELDGET("RAT")+SELF:SERVER:FIELDGET("SAC")>0
   alert("Possui RAT/SAC/RNC")
   RETURN .F.	
ENDIF		
SELF:SERVER:Delete()
SELF:SERVER:SKIPEX(-1)

METHOD esccod( ) 
LOCAL oESC AS XESCCOD		
IF ! Empty(SELF:server:FIELDGET("DATAFEC"))
   alert("Já Fechada")
   RETURN .F.
ENDIF		
IF SELF:SERVER:FIELDGET("RNC")+SELF:SERVER:FIELDGET("RAT")+SELF:SERVER:FIELDGET("SAC")>0
   alert("Possui RAT/SAC/RNC")
   RETURN .F.	
ENDIF	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:SERVER:FIELDPUT("PRODUTO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESPRO",oESC:NOME)
ENDIF			

METHOD escfor( ) 
LOCAL oESC AS XESCNUM		
IF ! Empty(SELF:server:FIELDGET("DATAFEC"))
   alert("Já Fechada")
   RETURN .F.
ENDIF		
IF SELF:SERVER:FIELDGET("RNC")+SELF:SERVER:FIELDGET("RAT")+SELF:SERVER:FIELDGET("SAC")>0
   alert("Possui RAT/SAC/RNC")
   RETURN .F.	
ENDIF	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("CLINOME",oESC:NOME)
ENDIF	

METHOD externo() 
LOCAL oJAN AS jcnqext
IF ! Empty(SELF:server:FIELDGET("DATAFEC"))
   alert("Já Fechada")
   RETURN .F.
ENDIF		
	oJAN:=jcnqext{SELF}
	oJAN:SHOW()

METHOD Fechar( ) 
LOCAL oJAN AS jcnqFEC
IF ! Empty(SELF:server:FIELDGET("DATAFEC"))
   alert("Já Fechada")
   RETURN .F.
ENDIF		
IF Empty(SELF:server:FIELDGET("CLIENTE"))
   alert("Cliente nao Preenchido")
   RETURN .F.
ENDIF	
IF Empty(SELF:server:FIELDGET("PRODUTO"))
   alert("Codigo nao Preenchido")
   RETURN .F.
ENDIF	
oJAN:=jcnqFEC{SELF}
oJAN:SHOW()	

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("PRODUTO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .F.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()	

METHOD interno() 
LOCAL oJAN AS jcnqint
IF ! Empty(SELF:server:FIELDGET("DATAFEC"))
   alert("Já Fechada")
   RETURN .F.
ENDIF		
oJAN:=jcnqint{SELF}
oJAN:SHOW()
	


METHOD PORNUM( ) 
	SELF:KeyFind()
//  SELF:SERVER:SETORDER(1)	

METHOD PORRAT( ) 
  SELF:SERVER:SETORDER(4)	

METHOD PORRNC( ) 
  SELF:SERVER:SETORDER(3)	

METHOD PORSAC( ) 
  SELF:SERVER:SETORDER(5)	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
      FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


METHOD VERRNC( ) 
LOCAL oRNC AS USEREDE	
LOCAL aDAD AS ARRAY
LOCAL nRNC AS DWORD
LOCAL oJAN AS JRNC4
IF ! entramenu("TGQ",10)
	RETU SELF
ENDIF	
nRNC:=SELF:server:FIELDGET("RNC")
IF ! Empty(SELF:server:FIELDGET("DATAFEC"))
   alert("Já Fechada")
   RETURN .F.
ENDIF			
IF Empty(nRNC)
   alert("Não É Custo de RNC")
   RETURN .F.
ENDIF	
aDAD:={zCURINI,"RNC.DBF",ZCURDIR}
oRNC:=USEREDE{aDAD}
IF oRNC:nERRO#0
   RETURN SELF
ENDIF
oRNC:GOTOP()
IF oRNC:Seek(nRNC)
   oJAN:=JRNC4{SELF,,oRNC}
   oJAN:SHOW()
ELSE
   alert("Rnc Não Encontrada")
ENDIF	
oRNC:CLOSE()
	

METHOD versac( ) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL oJAN AS XJSacDia
LOCAL aDAD AS ARRAY
IF ! entramenu("TGQ",15)
	RETU SELF
ENDIF	
IF ! Empty(SELF:server:FIELDGET("DATAFEC"))
   alert("Já Fechada")
   RETURN .F.
ENDIF			
IF Empty(SELF:SERVER:FIELDGET("SAC"))
   alert("Sac em Branco")	
   RETURN .F.
ENDIF	
IF ! entramenu("TGQ",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"SAC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOTOP()
IF ! oSERVER:SEEK(SELF:SERVER:FIELDGET("SAC"))
   OserveR:close()
   alert("Sac Não Encontrada")
   RETURN .F.
ENDIF	
aDAD:={zCURINI,"SACI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
oJAN:=XJSACDIA{SELF,oSERVER,oSERVE2}
oJAN:SHOW()		

END CLASS
PARTIAL CLASS jcnqext
	METHOD Calc( ) 
	LOCAL nVAL1,nVAL2 AS FLOAT
	nVAL1:=SELF:SERVER:FIELDGET("QTE07")
	nVAL2:=SELF:SERVER:FIELDGET("PCVALEXT")
	SELF:SERVER:FIELDPUT("VLE07",nVAL1*nVAL2)	

METHOD PegPreco( ) 
LOCAL aPRC AS ARRAY
LOCAL oBUSCA AS XBUSCA
aPRC:=MS02PRC(SELF:SERVER:FIELDGET("PRODUTO"),SELF:SERVER:FIELDGET("CLIENTE"),.T.,.T.,ZCURINI,ZCURDIR,aDIR)	
IF aPRC[1]>0
   SELF:SERVER:FIELDPUT("PCVALEXT",aPRC[1])
ELSE
   IF MDG("Digitar Nº Cliente")
   	 oBUSCA:=xBUSCA{SELF,"Informar Nº","Digite Nº "}
     oBUSCA:lMES:=.T.
     oBUSCA:SHOW()
     IF oBUSCA:lOK
     	aPRC:=MS02PRC(SELF:SERVER:FIELDGET("PRODUTO"),Val(oBUSCA:cBUSCA),.T.,.T.,ZCURINI,ZCURDIR,aDIR)	
        IF aPRC[1]>0
           SELF:SERVER:FIELDPUT("PCVALEXT",aPRC[1])
        ENDIF
     ENDIF
   ENDIF

ENDIF

END CLASS
PARTIAL CLASS jcnqINT
METHOD Calc( ) 
SELF:SERVER:FIELDPUT("VLI05",SELF:SERVER:FIELDGET("QTI05")*SELF:SERVER:FIELDGET("PCVALINT"))

METHOD PegPreco( ) 
LOCAL aPRC AS ARRAY
LOCAL oBUSCA AS XBUSCA
aPRC:=MS02PRC(SELF:SERVER:FIELDGET("PRODUTO"),SELF:SERVER:FIELDGET("CLIENTE"),.T.,.T.,ZCURINI,ZCURDIR,aDIR)	
IF aPRC[1]>0
   SELF:SERVER:FIELDPUT("PCVALINT",aPRC[1])
ELSE
   IF MDG("Digitar Nº Cliente")
   	 oBUSCA:=xBUSCA{SELF,"Informar Nº","Digite Nº "}
     oBUSCA:lMES:=.T.
     oBUSCA:SHOW()
     IF oBUSCA:lOK
     	aPRC:=MS02PRC(SELF:SERVER:FIELDGET("PRODUTO"),Val(oBUSCA:cBUSCA),.T.,.T.,ZCURINI,ZCURDIR,aDIR)	
        IF aPRC[1]>0
           SELF:SERVER:FIELDPUT("PCVALINT",aPRC[1])
        ENDIF
     ENDIF
   ENDIF
ENDIF	


END CLASS
