#region DEFINES
STATIC DEFINE JRACF_BUSCARACF := 114 
STATIC DEFINE JRACF_CNFFO := 122 
STATIC DEFINE JRACF_CRM := 100 
STATIC DEFINE JRACF_DATA := 113 
STATIC DEFINE JRACF_FT40 := 110 
STATIC DEFINE JRACF_FT42 := 109 
STATIC DEFINE JRACF_IMPORTAR := 111 
STATIC DEFINE JRACF_IMPRASTRO := 112 
STATIC DEFINE JRACF_PORNUM := 115 
STATIC DEFINE JRACF_QTDENC := 116 
STATIC DEFINE JRACF_RACF := 104 
STATIC DEFINE JRACF_RASTRO := 101 
STATIC DEFINE JRACF_RAT := 108 
STATIC DEFINE JRACF_REPC := 126 
STATIC DEFINE JRACF_RNC := 107 
STATIC DEFINE JRACF_SC_DATA := 103 
STATIC DEFINE JRACF_SC_RACF := 102 
STATIC DEFINE JRACF_SC_RASTRO := 105 
STATIC DEFINE JRACF_TABRACF := 106 
STATIC DEFINE JRACF_VERRNC := 116 
STATIC DEFINE RACFPAG1_CBUSCA := 101 
STATIC DEFINE RACFPAG1_CMDCRM3LA := 147 
STATIC DEFINE RACFPAG1_CMDCRM3LB := 148 
STATIC DEFINE RACFPAG1_CNFFOR := 115 
STATIC DEFINE RACFPAG1_CNFITA := 112 
STATIC DEFINE RACFPAG1_DENO := 104 
STATIC DEFINE RACFPAG1_DESCRI := 102 
STATIC DEFINE RACFPAG1_DESENHO := 103 
STATIC DEFINE RACFPAG1_EMAIL := 120 
STATIC DEFINE RACFPAG1_ESCCOD := 138 
STATIC DEFINE RACFPAG1_ESCCODX := 143 
STATIC DEFINE RACFPAG1_ESCFOR := 137 
STATIC DEFINE RACFPAG1_FAX := 119 
STATIC DEFINE RACFPAG1_FONE := 118 
STATIC DEFINE RACFPAG1_FORNECEDO := 113 
STATIC DEFINE RACFPAG1_FOTO := 145 
STATIC DEFINE RACFPAG1_FT23 := 124 
STATIC DEFINE RACFPAG1_FT24 := 129 
STATIC DEFINE RACFPAG1_FT25 := 136 
STATIC DEFINE RACFPAG1_FT26 := 134 
STATIC DEFINE RACFPAG1_FT27 := 135 
STATIC DEFINE RACFPAG1_NOMEF := 114 
STATIC DEFINE RACFPAG1_PEGCOD := 139 
STATIC DEFINE RACFPAG1_PEGCODX := 142 
STATIC DEFINE RACFPAG1_PEGFOR := 140 
STATIC DEFINE RACFPAG1_PEGFORPCP := 141 
STATIC DEFINE RACFPAG1_QTD1 := 109 
STATIC DEFINE RACFPAG1_QTD2 := 110 
STATIC DEFINE RACFPAG1_QTL1 := 105 
STATIC DEFINE RACFPAG1_QTL2 := 106 
STATIC DEFINE RACFPAG1_QTN1 := 107 
STATIC DEFINE RACFPAG1_QTN2 := 108 
STATIC DEFINE RACFPAG1_RESP := 116 
STATIC DEFINE RACFPAG1_RESPC := 117 
STATIC DEFINE RACFPAG1_SC_DENO := 132 
STATIC DEFINE RACFPAG1_SC_DESENHO := 133 
STATIC DEFINE RACFPAG1_SC_DESTINO2 := 144 
STATIC DEFINE RACFPAG1_SC_EMAIL := 121 
STATIC DEFINE RACFPAG1_SC_FAX := 122 
STATIC DEFINE RACFPAG1_SC_FONE := 123 
STATIC DEFINE RACFPAG1_SC_NOMEF := 127 
STATIC DEFINE RACFPAG1_SC_NOTAF := 126 
STATIC DEFINE RACFPAG1_SC_QTDEL := 131 
STATIC DEFINE RACFPAG1_SC_QTDENC := 130 
STATIC DEFINE RACFPAG1_SC_QTDENC1 := 146 
STATIC DEFINE RACFPAG1_SC_QTDENF := 128 
STATIC DEFINE RACFPAG1_SC_RESP := 125 
STATIC DEFINE RACFPAG1_TIPOE := 100 
STATIC DEFINE RACFPAG1_UNID := 111 
STATIC DEFINE TABRACF_PAGE2_DESC01 := 100 
STATIC DEFINE TABRACF_PAGE2_DESC02 := 101 
STATIC DEFINE TABRACF_PAGE2_DESC03 := 102 
STATIC DEFINE TABRACF_PAGE2_DESC04 := 103 
STATIC DEFINE TABRACF_PAGE2_DESC05 := 104 
STATIC DEFINE TABRACF_PAGE3_ACAO01 := 100 
STATIC DEFINE TABRACF_PAGE3_ACAO02 := 101 
STATIC DEFINE TABRACF_PAGE4_CAUSA01 := 100 
STATIC DEFINE TABRACF_PAGE4_CAUSA02 := 101 
STATIC DEFINE TABRACF_PAGE4_CAUSA03 := 102 
STATIC DEFINE TABRACF_PAGE4_CAUSA04 := 103 
STATIC DEFINE TABRACF_PAGE5_CORRE01 := 100 
STATIC DEFINE TABRACF_PAGE5_CORRE02 := 101 
STATIC DEFINE TABRACF_PAGE5_CORRE03 := 102 
STATIC DEFINE TABRACF_PAGE5_CORRE04 := 103 
STATIC DEFINE TABRACF_PAGE6_AREA := 102
STATIC DEFINE TABRACF_PAGE6_CARGO := 110
STATIC DEFINE TABRACF_PAGE6_CARGOF := 104
STATIC DEFINE TABRACF_PAGE6_DATAF := 101
STATIC DEFINE TABRACF_PAGE6_DATAI := 100
STATIC DEFINE TABRACF_PAGE6_FT22 := 107
STATIC DEFINE TABRACF_PAGE6_RESPF := 103
STATIC DEFINE TABRACF_PAGE6_RESPO := 109
STATIC DEFINE TABRACF_PAGE6_SC_CARGOF := 105
STATIC DEFINE TABRACF_PAGE6_SC_DATAI := 108
STATIC DEFINE TABRACF_PAGE6_SC_RESPF := 106
STATIC DEFINE TABRACF_PAGE7_APRO := 107 
STATIC DEFINE TABRACF_PAGE7_CMDDEMERITO := 114 
STATIC DEFINE TABRACF_PAGE7_CMDEFICAZ := 113 
STATIC DEFINE TABRACF_PAGE7_DATAE := 100 
STATIC DEFINE TABRACF_PAGE7_DEMERITO := 115 
STATIC DEFINE TABRACF_PAGE7_DESCRI01 := 103 
STATIC DEFINE TABRACF_PAGE7_EFICAZ := 112 
STATIC DEFINE TABRACF_PAGE7_NOTA := 102 
STATIC DEFINE TABRACF_PAGE7_RADIOBUTTON2 := 108 
STATIC DEFINE TABRACF_PAGE7_RADIOBUTTON3 := 109 
STATIC DEFINE TABRACF_PAGE7_RADIOBUTTON6 := 110 
STATIC DEFINE TABRACF_PAGE7_RADIOBUTTON7 := 111 
STATIC DEFINE TABRACF_PAGE7_SC_DATAE := 104 
STATIC DEFINE TABRACF_PAGE7_SC_DATAE1 := 116 
STATIC DEFINE TABRACF_PAGE7_SC_NOTA := 105 
STATIC DEFINE TABRACF_PAGE7_SC_VERI := 106 
STATIC DEFINE TABRACF_PAGE7_VERI := 101 
#endregion

PARTIAL CLASS JRACF INHERIT MYDataWindow 

	PROTECT oDBRACF AS DataColumn
	PROTECT oDCCRM AS RIGHTSLE
	PROTECT oDCRASTRO AS SINGLELINEEDIT
	PROTECT oDCSC_RACF AS FIXEDTEXT
	PROTECT oDCSC_DATA AS FIXEDTEXT
	PROTECT oDCRACF AS SINGLELINEEDIT
	PROTECT oDCSC_RASTRO AS FIXEDTEXT
	PROTECT oDCTabRacf AS TABCONTROL
	PROTECT oTPRACFPAG1 AS RACFPAG1
	PROTECT oTPTABRACF_PAGE2 AS TABRACF_PAGE2
	PROTECT oTPTABRACF_PAGE3 AS TABRACF_PAGE3
	PROTECT oTPTABRACF_PAGE4 AS TABRACF_PAGE4
	PROTECT oTPTABRACF_PAGE5 AS TABRACF_PAGE5
	PROTECT oTPTABRACF_PAGE6 AS TABRACF_PAGE6
	PROTECT oTPTABRACF_PAGE7 AS TABRACF_PAGE7
	PROTECT oDCRNC AS SINGLELINEEDIT
	PROTECT oDCRAT AS SINGLELINEEDIT
	PROTECT oDCFT42 AS FIXEDTEXT
	PROTECT oDCFT40 AS FIXEDTEXT
	PROTECT oCCIMPORTAR AS PUSHBUTTON
	PROTECT oCCIMPrastro AS PUSHBUTTON
	PROTECT oDCDATA AS SINGLELINEEDIT
	PROTECT oCCbuscaRACF AS PUSHBUTTON
	PROTECT oCCPORNUM AS PUSHBUTTON
	PROTECT oCCVERRNC AS PUSHBUTTON
// 	instance CRM 
// 	instance RASTRO 
// 	instance RACF 
// 	instance RNC 
// 	instance RAT 
// 	instance DATA 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS CRM() 
RETURN SELF:FieldGet(#CRM)


ASSIGN CRM(uValue) 
SELF:FieldPut(#CRM, uValue)
RETURN CRM := uValue


ACCESS DATA() 
RETURN SELF:FieldGet(#DATA)


ASSIGN DATA(uValue) 
SELF:FieldPut(#DATA, uValue)
RETURN DATA := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[3] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JRACF",_GetInst()},iCtlID)

aFonts[1] := Font{,12,"Times New Roman"}
aFonts[1]:Bold := TRUE
aFonts[2] := Font{,10,"Times New Roman"}
aFonts[2]:Bold := TRUE
aFonts[3] := Font{,10,"Trebuchet MS"}
aFonts[3]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCCRM := rightSle{SELF,ResourceID{JRACF_CRM,_GetInst()}}
oDCCRM:FieldSpec := PADRAO_NUM_08{}
oDCCRM:HyperLabel := HyperLabel{#CRM,NULL_STRING,NULL_STRING,NULL_STRING}

oDCRASTRO := SingleLineEdit{SELF,ResourceID{JRACF_RASTRO,_GetInst()}}
oDCRASTRO:FieldSpec := PADRAO_CHAR_20{}
oDCRASTRO:HyperLabel := HyperLabel{#RASTRO,"Rastro:",NULL_STRING,"RACF_RASTRO"}

oDCSC_RACF := FixedText{SELF,ResourceID{JRACF_SC_RACF,_GetInst()}}
oDCSC_RACF:HyperLabel := HyperLabel{#SC_RACF,"RACF",NULL_STRING,NULL_STRING}

oDCSC_DATA := FixedText{SELF,ResourceID{JRACF_SC_DATA,_GetInst()}}
oDCSC_DATA:HyperLabel := HyperLabel{#SC_DATA,"Data:",NULL_STRING,NULL_STRING}

oDCRACF := SingleLineEdit{SELF,ResourceID{JRACF_RACF,_GetInst()}}
oDCRACF:FieldSpec := PADRAO_NUM_08{}
oDCRACF:HyperLabel := HyperLabel{#RACF,"Racf:",NULL_STRING,"RACF_RACF"}
oDCRACF:BackGround := aBrushes[1]
oDCRACF:Font(aFonts[1], FALSE)

oDCSC_RASTRO := FixedText{SELF,ResourceID{JRACF_SC_RASTRO,_GetInst()}}
oDCSC_RASTRO:HyperLabel := HyperLabel{#SC_RASTRO,"Rastreabilidade:",NULL_STRING,NULL_STRING}

oDCTabRacf := TabControl{SELF,ResourceID{JRACF_TABRACF,_GetInst()}}
oDCTabRacf:HyperLabel := HyperLabel{#TabRacf,NULL_STRING,NULL_STRING,NULL_STRING}

oDCRNC := SingleLineEdit{SELF,ResourceID{JRACF_RNC,_GetInst()}}
oDCRNC:FieldSpec := PADRAO_NUM_08{}
oDCRNC:HyperLabel := HyperLabel{#RNC,NULL_STRING,NULL_STRING,NULL_STRING}
oDCRNC:BackGround := aBrushes[1]
oDCRNC:Font(aFonts[2], FALSE)

oDCRAT := SingleLineEdit{SELF,ResourceID{JRACF_RAT,_GetInst()}}
oDCRAT:FieldSpec := PADRAO_NUM_08{}
oDCRAT:HyperLabel := HyperLabel{#RAT,NULL_STRING,NULL_STRING,NULL_STRING}
oDCRAT:Font(aFonts[3], FALSE)
oDCRAT:BackGround := aBrushes[1]

oDCFT42 := FixedText{SELF,ResourceID{JRACF_FT42,_GetInst()}}
oDCFT42:HyperLabel := HyperLabel{#FT42,"RAT",NULL_STRING,NULL_STRING}

oDCFT40 := FixedText{SELF,ResourceID{JRACF_FT40,_GetInst()}}
oDCFT40:HyperLabel := HyperLabel{#FT40,"CRM",NULL_STRING,NULL_STRING}

oCCIMPORTAR := PushButton{SELF,ResourceID{JRACF_IMPORTAR,_GetInst()}}
oCCIMPORTAR:HyperLabel := HyperLabel{#IMPORTAR,"Imp",NULL_STRING,NULL_STRING}

oCCIMPrastro := PushButton{SELF,ResourceID{JRACF_IMPRASTRO,_GetInst()}}
oCCIMPrastro:HyperLabel := HyperLabel{#IMPrastro,"Imp",NULL_STRING,NULL_STRING}

oDCDATA := SingleLineEdit{SELF,ResourceID{JRACF_DATA,_GetInst()}}
oDCDATA:FieldSpec := DATE_FIELD{}
oDCDATA:HyperLabel := HyperLabel{#DATA,"Racf:",NULL_STRING,"RACF_RACF"}
oDCDATA:BackGround := aBrushes[1]
oDCDATA:Font(aFonts[2], FALSE)

oCCbuscaRACF := PushButton{SELF,ResourceID{JRACF_BUSCARACF,_GetInst()}}
oCCbuscaRACF:Image := ico_find{}
oCCbuscaRACF:HyperLabel := HyperLabel{#buscaRACF,NULL_STRING,NULL_STRING,NULL_STRING}

oCCPORNUM := PushButton{SELF,ResourceID{JRACF_PORNUM,_GetInst()}}
oCCPORNUM:Image := ico_az{}
oCCPORNUM:HyperLabel := HyperLabel{#PORNUM,NULL_STRING,NULL_STRING,NULL_STRING}

oCCVERRNC := PushButton{SELF,ResourceID{JRACF_VERRNC,_GetInst()}}
oCCVERRNC:HyperLabel := HyperLabel{#VERRNC,"RNC",NULL_STRING,NULL_STRING}

SELF:Caption := "Requerimento de Ação Corretiva ao Fornecedor"
SELF:HyperLabel := HyperLabel{#JRACF,"Requerimento de Ação Corretiva ao Fornecedor",NULL_STRING,NULL_STRING}
SELF:Menu := STANDARDSHELLMENU{}

IF !IsNil(oServer)
	SELF:Use(oServer)
ENDIF
SELF:Browser := DataBrowser{SELF}

oDBRACF := DataColumn{PADRAO_NUM_08{}}
oDBRACF:Width := 6
oDBRACF:HyperLabel := oDCRACF:HyperLabel 
oDBRACF:Caption := "Racf:"
oDBRACF:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBRACF)


SELF:ViewAs(#FormView)
oTPRACFPAG1 := RACFPAG1{SELF, 0}
oDCTabRacf:AppendTab(#RACFPAG1,"Dados",oTPRACFPAG1,0)
oTPTABRACF_PAGE2 := TABRACF_PAGE2{SELF, 0}
oDCTabRacf:AppendTab(#TABRACF_PAGE2,"Descrição Não Conformidade",oTPTABRACF_PAGE2,0)
oTPTABRACF_PAGE3 := TABRACF_PAGE3{SELF, 0}
oDCTabRacf:AppendTab(#TABRACF_PAGE3,"1º Ação de Contenção",oTPTABRACF_PAGE3,0)
oTPTABRACF_PAGE4 := TABRACF_PAGE4{SELF, 0}
oDCTabRacf:AppendTab(#TABRACF_PAGE4,"2º Causa do Problema",oTPTABRACF_PAGE4,0)
oTPTABRACF_PAGE5 := TABRACF_PAGE5{SELF, 0}
oDCTabRacf:AppendTab(#TABRACF_PAGE5,"3º Ação Corretiva",oTPTABRACF_PAGE5,0)
oTPTABRACF_PAGE6 := TABRACF_PAGE6{SELF, 0}
oDCTabRacf:AppendTab(#TABRACF_PAGE6,"4º Implantação",oTPTABRACF_PAGE6,0)
oTPTABRACF_PAGE7 := TABRACF_PAGE7{SELF, 0}
oDCTabRacf:AppendTab(#TABRACF_PAGE7,"5º 6ª 7ª Efetivação/Apr/Desc",oTPTABRACF_PAGE7,0)
oDCTabRacf:SelectTab(#RACFPAG1)

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


METHOD PORNUM( ) 
	SELF:KeyFind()

ACCESS RACF() 
RETURN SELF:FieldGet(#RACF)


ASSIGN RACF(uValue) 
SELF:FieldPut(#RACF, uValue)
RETURN RACF := uValue


ACCESS RASTRO() 
RETURN SELF:FieldGet(#RASTRO)


ASSIGN RASTRO(uValue) 
SELF:FieldPut(#RASTRO, uValue)
RETURN RASTRO := uValue


ACCESS RAT() 
RETURN SELF:FieldGet(#RAT)


ASSIGN RAT(uValue) 
SELF:FieldPut(#RAT, uValue)
RETURN RAT := uValue


ACCESS RNC() 
RETURN SELF:FieldGet(#RNC)


ASSIGN RNC(uValue) 
SELF:FieldPut(#RNC, uValue)
RETURN RNC := uValue


METHOD VERRNC( ) 
LOCAL oRNC AS USEREDE	
LOCAL aDAD AS ARRAY
LOCAL nRNC AS DWORD
LOCAL oJAN AS JRNC4
IF ! entramenu("TGQ",10)
	RETU SELF
ENDIF	
nRNC:=SELF:server:FIELDGET("RNC")
IF ! Empty(SELF:server:FIELDGET("DATAE"))
   alert("Já Efetivada")
   RETURN .F.
ENDIF			
IF Empty(nRNC)
   alert("RNC=0")
   RETURN .F.
ENDIF	
aDAD:={zCURINI,"RNC.DBF",ZCURDIR}
oRNC:=USEREDE{aDAD}
IF oRNC:nERRO#0
   RETU SELF
ENDIF
oRNC:GOTOP()
IF oRNC:Seek(nRNC)
   oJAN:=JRNC4{SELF,,oRNC}
   oJAN:SHOW()
ELSE
   alert("Rnc Não Encontrada")
ENDIF	
oRNC:CLOSE()		

END CLASS
PARTIAL CLASS RacfPag1 INHERIT DATAWINDOW 

	PROTECT oDCTIPOE AS COMBOBOX
	PROTECT oDCCBUSCA AS SINGLELINEEDIT
	PROTECT oDCDESCRI AS SINGLELINEEDIT
	PROTECT oDCDESENHO AS SINGLELINEEDIT
	PROTECT oDCDENO AS SINGLELINEEDIT
	PROTECT oDCQTL1 AS RIGHTSLE
	PROTECT oDCQTL2 AS RIGHTSLE
	PROTECT oDCQTN1 AS RIGHTSLE
	PROTECT oDCQTN2 AS RIGHTSLE
	PROTECT oDCQTD1 AS RIGHTSLE
	PROTECT oDCQTD2 AS RIGHTSLE
	PROTECT oDCUNID AS SINGLELINEEDIT
	PROTECT oDCCNFITA AS SINGLELINEEDIT
	PROTECT oDCFORNECEDO AS RIGHTSLE
	PROTECT oDCNOMEF AS SINGLELINEEDIT
	PROTECT oDCCNFFOR AS SINGLELINEEDIT
	PROTECT oDCRESP AS SINGLELINEEDIT
	PROTECT oDCRESPC AS SINGLELINEEDIT
	PROTECT oDCFONE AS SINGLELINEEDIT
	PROTECT oDCFAX AS SINGLELINEEDIT
	PROTECT oDCEMAIL AS SINGLELINEEDIT
	PROTECT oDCSC_EMAIL AS FIXEDTEXT
	PROTECT oDCSC_FAX AS FIXEDTEXT
	PROTECT oDCSC_FONE AS FIXEDTEXT
	PROTECT oDCFT23 AS FIXEDTEXT
	PROTECT oDCSC_RESP AS FIXEDTEXT
	PROTECT oDCSC_NOTAF AS FIXEDTEXT
	PROTECT oDCSC_NOMEF AS FIXEDTEXT
	PROTECT oDCSC_QTDENF AS FIXEDTEXT
	PROTECT oDCFT24 AS FIXEDTEXT
	PROTECT oDCSC_QTDENC AS FIXEDTEXT
	PROTECT oDCSC_QTDEL AS FIXEDTEXT
	PROTECT oDCSC_DENO AS FIXEDTEXT
	PROTECT oDCSC_DESENHO AS FIXEDTEXT
	PROTECT oDCFT26 AS FIXEDTEXT
	PROTECT oDCFT27 AS FIXEDTEXT
	PROTECT oDCFT25 AS FIXEDTEXT
	PROTECT oCCescfor AS PUSHBUTTON
	PROTECT oCCesccod AS PUSHBUTTON
	PROTECT oCCpegcod AS PUSHBUTTON
	PROTECT oCCpegfor AS PUSHBUTTON
	PROTECT oCCpegforpcp AS PUSHBUTTON
	PROTECT oCCpegcodX AS PUSHBUTTON
	PROTECT oCCesccodX AS PUSHBUTTON
	PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
	PROTECT oCCfoto AS PUSHBUTTON
	PROTECT oDCSC_QTDENC1 AS FIXEDTEXT
	PROTECT oCCcmdCrm3LA AS PUSHBUTTON
	PROTECT oCCcmdCrm3LB AS PUSHBUTTON
// 	instance TIPOE 
// 	instance CBUSCA 
// 	instance DESCRI 
// 	instance DESENHO 
// 	instance DENO 
// 	instance QTL1 
// 	instance QTL2 
// 	instance QTN1 
// 	instance QTN2 
// 	instance QTD1 
// 	instance QTD2 
// 	instance UNID 
// 	instance CNFITA 
// 	instance FORNECEDO 
// 	instance NOMEF 
// 	instance CNFFOR 
// 	instance RESP 
// 	instance RESPC 
// 	instance FONE 
// 	instance FAX 
// 	instance EMAIL 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS CBUSCA() 
RETURN SELF:FieldGet(#CBUSCA)


ASSIGN CBUSCA(uValue) 
SELF:FieldPut(#CBUSCA, uValue)
RETURN CBUSCA := uValue


ACCESS CNFFOR() 
RETURN SELF:FieldGet(#CNFFOR)


ASSIGN CNFFOR(uValue) 
SELF:FieldPut(#CNFFOR, uValue)
RETURN CNFFOR := uValue


ACCESS CNFITA() 
RETURN SELF:FieldGet(#CNFITA)


ASSIGN CNFITA(uValue) 
SELF:FieldPut(#CNFITA, uValue)
RETURN CNFITA := uValue


ACCESS DENO() 
RETURN SELF:FieldGet(#DENO)


ASSIGN DENO(uValue) 
SELF:FieldPut(#DENO, uValue)
RETURN DENO := uValue


ACCESS DESCRI() 
RETURN SELF:FieldGet(#DESCRI)


ASSIGN DESCRI(uValue) 
SELF:FieldPut(#DESCRI, uValue)
RETURN DESCRI := uValue


ACCESS DESENHO() 
RETURN SELF:FieldGet(#DESENHO)


ASSIGN DESENHO(uValue) 
SELF:FieldPut(#DESENHO, uValue)
RETURN DESENHO := uValue


ACCESS EMAIL() 
RETURN SELF:FieldGet(#EMAIL)


ASSIGN EMAIL(uValue) 
SELF:FieldPut(#EMAIL, uValue)
RETURN EMAIL := uValue


ACCESS FAX() 
RETURN SELF:FieldGet(#FAX)


ASSIGN FAX(uValue) 
SELF:FieldPut(#FAX, uValue)
RETURN FAX := uValue


ACCESS FONE() 
RETURN SELF:FieldGet(#FONE)


ASSIGN FONE(uValue) 
SELF:FieldPut(#FONE, uValue)
RETURN FONE := uValue


ACCESS FORNECEDO() 
RETURN SELF:FieldGet(#FORNECEDO)


ASSIGN FORNECEDO(uValue) 
SELF:FieldPut(#FORNECEDO, uValue)
RETURN FORNECEDO := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"RacfPag1",_GetInst()},iCtlID)

oDCTIPOE := combobox{SELF,ResourceID{RACFPAG1_TIPOE,_GetInst()}}
oDCTIPOE:FillUsing(SELF:TABTIPO( ))
oDCTIPOE:HyperLabel := HyperLabel{#TIPOE,NULL_STRING,NULL_STRING,NULL_STRING}
oDCTIPOE:FieldSpec := PADRAO_CHAR_01{}

oDCCBUSCA := SingleLineEdit{SELF,ResourceID{RACFPAG1_CBUSCA,_GetInst()}}
oDCCBUSCA:FieldSpec := PADRAO_CHAR_24{}
oDCCBUSCA:HyperLabel := HyperLabel{#CBUSCA,NULL_STRING,NULL_STRING,NULL_STRING}

oDCDESCRI := SingleLineEdit{SELF,ResourceID{RACFPAG1_DESCRI,_GetInst()}}
oDCDESCRI:FieldSpec := PADRAO_CHAR_100{}
oDCDESCRI:HyperLabel := HyperLabel{#DESCRI,NULL_STRING,NULL_STRING,NULL_STRING}

oDCDESENHO := SingleLineEdit{SELF,ResourceID{RACFPAG1_DESENHO,_GetInst()}}
oDCDESENHO:FieldSpec := PADRAO_CHAR_24{}
oDCDESENHO:HyperLabel := HyperLabel{#DESENHO,"Desenho:",NULL_STRING,"RACF_DESENHO"}

oDCDENO := SingleLineEdit{SELF,ResourceID{RACFPAG1_DENO,_GetInst()}}
oDCDENO:FieldSpec := PADRAO_CHAR_40{}
oDCDENO:HyperLabel := HyperLabel{#DENO,"Deno:",NULL_STRING,"RACF_DENO"}

oDCQTL1 := rightSle{SELF,ResourceID{RACFPAG1_QTL1,_GetInst()}}
oDCQTL1:FieldSpec := PADRAO_NUM_07{}
oDCQTL1:HyperLabel := HyperLabel{#QTL1,NULL_STRING,NULL_STRING,NULL_STRING}

oDCQTL2 := rightSle{SELF,ResourceID{RACFPAG1_QTL2,_GetInst()}}
oDCQTL2:FieldSpec := PADRAO_NUM_07{}
oDCQTL2:HyperLabel := HyperLabel{#QTL2,NULL_STRING,NULL_STRING,NULL_STRING}

oDCQTN1 := rightSle{SELF,ResourceID{RACFPAG1_QTN1,_GetInst()}}
oDCQTN1:FieldSpec := PADRAO_NUM_07{}
oDCQTN1:HyperLabel := HyperLabel{#QTN1,NULL_STRING,NULL_STRING,NULL_STRING}

oDCQTN2 := rightSle{SELF,ResourceID{RACFPAG1_QTN2,_GetInst()}}
oDCQTN2:FieldSpec := PADRAO_NUM_07{}
oDCQTN2:HyperLabel := HyperLabel{#QTN2,NULL_STRING,NULL_STRING,NULL_STRING}

oDCQTD1 := rightSle{SELF,ResourceID{RACFPAG1_QTD1,_GetInst()}}
oDCQTD1:FieldSpec := PADRAO_NUM_07{}
oDCQTD1:HyperLabel := HyperLabel{#QTD1,NULL_STRING,NULL_STRING,NULL_STRING}

oDCQTD2 := rightSle{SELF,ResourceID{RACFPAG1_QTD2,_GetInst()}}
oDCQTD2:FieldSpec := PADRAO_NUM_07{}
oDCQTD2:HyperLabel := HyperLabel{#QTD2,NULL_STRING,NULL_STRING,NULL_STRING}

oDCUNID := SingleLineEdit{SELF,ResourceID{RACFPAG1_UNID,_GetInst()}}
oDCUNID:FieldSpec := PADRAO_CHAR_03{}
oDCUNID:HyperLabel := HyperLabel{#UNID,NULL_STRING,NULL_STRING,NULL_STRING}

oDCCNFITA := SingleLineEdit{SELF,ResourceID{RACFPAG1_CNFITA,_GetInst()}}
oDCCNFITA:FieldSpec := PADRAO_CHAR_08{}
oDCCNFITA:HyperLabel := HyperLabel{#CNFITA,NULL_STRING,NULL_STRING,NULL_STRING}

oDCFORNECEDO := rightSle{SELF,ResourceID{RACFPAG1_FORNECEDO,_GetInst()}}
oDCFORNECEDO:FieldSpec := PADRAO_NUM_08{}
oDCFORNECEDO:HyperLabel := HyperLabel{#FORNECEDO,NULL_STRING,NULL_STRING,NULL_STRING}

oDCNOMEF := SingleLineEdit{SELF,ResourceID{RACFPAG1_NOMEF,_GetInst()}}
oDCNOMEF:FieldSpec := PADRAO_CHAR_40{}
oDCNOMEF:HyperLabel := HyperLabel{#NOMEF,"Nomef:",NULL_STRING,"RACF_NOMEF"}

oDCCNFFOR := SingleLineEdit{SELF,ResourceID{RACFPAG1_CNFFOR,_GetInst()}}
oDCCNFFOR:FieldSpec := PADRAO_CHAR_25{}
oDCCNFFOR:HyperLabel := HyperLabel{#CNFFOR,NULL_STRING,NULL_STRING,NULL_STRING}

oDCRESP := SingleLineEdit{SELF,ResourceID{RACFPAG1_RESP,_GetInst()}}
oDCRESP:FieldSpec := PADRAO_CHAR_30{}
oDCRESP:HyperLabel := HyperLabel{#RESP,"Resp:",NULL_STRING,"RACF_RESP"}

oDCRESPC := SingleLineEdit{SELF,ResourceID{RACFPAG1_RESPC,_GetInst()}}
oDCRESPC:FieldSpec := PADRAO_CHAR_30{}
oDCRESPC:HyperLabel := HyperLabel{#RESPC,NULL_STRING,NULL_STRING,NULL_STRING}

oDCFONE := SingleLineEdit{SELF,ResourceID{RACFPAG1_FONE,_GetInst()}}
oDCFONE:FieldSpec := PADRAO_CHAR_12{}
oDCFONE:HyperLabel := HyperLabel{#FONE,"Fone:",NULL_STRING,"RACF_FONE"}

oDCFAX := SingleLineEdit{SELF,ResourceID{RACFPAG1_FAX,_GetInst()}}
oDCFAX:FieldSpec := PADRAO_CHAR_12{}
oDCFAX:HyperLabel := HyperLabel{#FAX,"Fax:",NULL_STRING,"RACF_FAX"}

oDCEMAIL := SingleLineEdit{SELF,ResourceID{RACFPAG1_EMAIL,_GetInst()}}
oDCEMAIL:FieldSpec := PADRAO_CHAR_30{}
oDCEMAIL:HyperLabel := HyperLabel{#EMAIL,"Email:",NULL_STRING,"RACF_EMAIL"}

oDCSC_EMAIL := FixedText{SELF,ResourceID{RACFPAG1_SC_EMAIL,_GetInst()}}
oDCSC_EMAIL:HyperLabel := HyperLabel{#SC_EMAIL,"Email:",NULL_STRING,NULL_STRING}

oDCSC_FAX := FixedText{SELF,ResourceID{RACFPAG1_SC_FAX,_GetInst()}}
oDCSC_FAX:HyperLabel := HyperLabel{#SC_FAX,"Fax:",NULL_STRING,NULL_STRING}

oDCSC_FONE := FixedText{SELF,ResourceID{RACFPAG1_SC_FONE,_GetInst()}}
oDCSC_FONE:HyperLabel := HyperLabel{#SC_FONE,"Fone:",NULL_STRING,NULL_STRING}

oDCFT23 := FixedText{SELF,ResourceID{RACFPAG1_FT23,_GetInst()}}
oDCFT23:HyperLabel := HyperLabel{#FT23,"Cargo",NULL_STRING,NULL_STRING}

oDCSC_RESP := FixedText{SELF,ResourceID{RACFPAG1_SC_RESP,_GetInst()}}
oDCSC_RESP:HyperLabel := HyperLabel{#SC_RESP,"Responsável:",NULL_STRING,NULL_STRING}

oDCSC_NOTAF := FixedText{SELF,ResourceID{RACFPAG1_SC_NOTAF,_GetInst()}}
oDCSC_NOTAF:HyperLabel := HyperLabel{#SC_NOTAF,"Nota Fiscal Fornecedor",NULL_STRING,NULL_STRING}

oDCSC_NOMEF := FixedText{SELF,ResourceID{RACFPAG1_SC_NOMEF,_GetInst()}}
oDCSC_NOMEF:HyperLabel := HyperLabel{#SC_NOMEF,"Fornecedor:",NULL_STRING,NULL_STRING}

oDCSC_QTDENF := FixedText{SELF,ResourceID{RACFPAG1_SC_QTDENF,_GetInst()}}
oDCSC_QTDENF:HyperLabel := HyperLabel{#SC_QTDENF,"Nossa NF/fPedido",NULL_STRING,NULL_STRING}

oDCFT24 := FixedText{SELF,ResourceID{RACFPAG1_FT24,_GetInst()}}
oDCFT24:HyperLabel := HyperLabel{#FT24,"Unid.",NULL_STRING,NULL_STRING}

oDCSC_QTDENC := FixedText{SELF,ResourceID{RACFPAG1_SC_QTDENC,_GetInst()}}
oDCSC_QTDENC:HyperLabel := HyperLabel{#SC_QTDENC,"Qtde Insp(Calculo)",NULL_STRING,NULL_STRING}

oDCSC_QTDEL := FixedText{SELF,ResourceID{RACFPAG1_SC_QTDEL,_GetInst()}}
oDCSC_QTDEL:HyperLabel := HyperLabel{#SC_QTDEL,"Quantidade Lote",NULL_STRING,NULL_STRING}

oDCSC_DENO := FixedText{SELF,ResourceID{RACFPAG1_SC_DENO,_GetInst()}}
oDCSC_DENO:HyperLabel := HyperLabel{#SC_DENO,"Denominação:",NULL_STRING,NULL_STRING}

oDCSC_DESENHO := FixedText{SELF,ResourceID{RACFPAG1_SC_DESENHO,_GetInst()}}
oDCSC_DESENHO:HyperLabel := HyperLabel{#SC_DESENHO,"Desenho:",NULL_STRING,NULL_STRING}

oDCFT26 := FixedText{SELF,ResourceID{RACFPAG1_FT26,_GetInst()}}
oDCFT26:HyperLabel := HyperLabel{#FT26,"Codigo",NULL_STRING,NULL_STRING}

oDCFT27 := FixedText{SELF,ResourceID{RACFPAG1_FT27,_GetInst()}}
oDCFT27:HyperLabel := HyperLabel{#FT27,"Descrição",NULL_STRING,NULL_STRING}

oDCFT25 := FixedText{SELF,ResourceID{RACFPAG1_FT25,_GetInst()}}
oDCFT25:HyperLabel := HyperLabel{#FT25,"Tipo",NULL_STRING,NULL_STRING}

oCCescfor := PushButton{SELF,ResourceID{RACFPAG1_ESCFOR,_GetInst()}}
oCCescfor:HyperLabel := HyperLabel{#escfor,"...",NULL_STRING,NULL_STRING}

oCCesccod := PushButton{SELF,ResourceID{RACFPAG1_ESCCOD,_GetInst()}}
oCCesccod:HyperLabel := HyperLabel{#esccod,"...",NULL_STRING,NULL_STRING}

oCCpegcod := PushButton{SELF,ResourceID{RACFPAG1_PEGCOD,_GetInst()}}
oCCpegcod:HyperLabel := HyperLabel{#pegcod,"-->",NULL_STRING,NULL_STRING}

oCCpegfor := PushButton{SELF,ResourceID{RACFPAG1_PEGFOR,_GetInst()}}
oCCpegfor:HyperLabel := HyperLabel{#pegfor,"-->",NULL_STRING,NULL_STRING}

oCCpegforpcp := PushButton{SELF,ResourceID{RACFPAG1_PEGFORPCP,_GetInst()}}
oCCpegforpcp:HyperLabel := HyperLabel{#pegforpcp,"PCP-->",NULL_STRING,NULL_STRING}

oCCpegcodX := PushButton{SELF,ResourceID{RACFPAG1_PEGCODX,_GetInst()}}
oCCpegcodX:HyperLabel := HyperLabel{#pegcodX,"-->",NULL_STRING,NULL_STRING}

oCCesccodX := PushButton{SELF,ResourceID{RACFPAG1_ESCCODX,_GetInst()}}
oCCesccodX:HyperLabel := HyperLabel{#esccodX,"...",NULL_STRING,NULL_STRING}

oDCSC_DESTINO2 := FixedText{SELF,ResourceID{RACFPAG1_SC_DESTINO2,_GetInst()}}
oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2,"Foto",NULL_STRING,NULL_STRING}

oCCfoto := PushButton{SELF,ResourceID{RACFPAG1_FOTO,_GetInst()}}
oCCfoto:HyperLabel := HyperLabel{#foto,NULL_STRING,NULL_STRING,NULL_STRING}
oCCfoto:Image := ico_camera{}

oDCSC_QTDENC1 := FixedText{SELF,ResourceID{RACFPAG1_SC_QTDENC1,_GetInst()}}
oDCSC_QTDENC1:HyperLabel := HyperLabel{#SC_QTDENC1,"Qtde Devolvida",NULL_STRING,NULL_STRING}

oCCcmdCrm3LA := PushButton{SELF,ResourceID{RACFPAG1_CMDCRM3LA,_GetInst()}}
oCCcmdCrm3LA:HyperLabel := HyperLabel{#cmdCrm3LA,"Gerar Aviso CRM",NULL_STRING,NULL_STRING}

oCCcmdCrm3LB := PushButton{SELF,ResourceID{RACFPAG1_CMDCRM3LB,_GetInst()}}
oCCcmdCrm3LB:HyperLabel := HyperLabel{#cmdCrm3LB,"Gerar Aviso CRM",NULL_STRING,NULL_STRING}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#RacfPag1,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS NOMEF() 
RETURN SELF:FieldGet(#NOMEF)


ASSIGN NOMEF(uValue) 
SELF:FieldPut(#NOMEF, uValue)
RETURN NOMEF := uValue


ACCESS QTD1() 
RETURN SELF:FieldGet(#QTD1)


ASSIGN QTD1(uValue) 
SELF:FieldPut(#QTD1, uValue)
RETURN QTD1 := uValue


ACCESS QTD2() 
RETURN SELF:FieldGet(#QTD2)


ASSIGN QTD2(uValue) 
SELF:FieldPut(#QTD2, uValue)
RETURN QTD2 := uValue


ACCESS QTL1() 
RETURN SELF:FieldGet(#QTL1)


ASSIGN QTL1(uValue) 
SELF:FieldPut(#QTL1, uValue)
RETURN QTL1 := uValue


ACCESS QTL2() 
RETURN SELF:FieldGet(#QTL2)


ASSIGN QTL2(uValue) 
SELF:FieldPut(#QTL2, uValue)
RETURN QTL2 := uValue


ACCESS QTN1() 
RETURN SELF:FieldGet(#QTN1)


ASSIGN QTN1(uValue) 
SELF:FieldPut(#QTN1, uValue)
RETURN QTN1 := uValue


ACCESS QTN2() 
RETURN SELF:FieldGet(#QTN2)


ASSIGN QTN2(uValue) 
SELF:FieldPut(#QTN2, uValue)
RETURN QTN2 := uValue


ACCESS RESP() 
RETURN SELF:FieldGet(#RESP)


ASSIGN RESP(uValue) 
SELF:FieldPut(#RESP, uValue)
RETURN RESP := uValue


ACCESS RESPC() 
RETURN SELF:FieldGet(#RESPC)


ASSIGN RESPC(uValue) 
SELF:FieldPut(#RESPC, uValue)
RETURN RESPC := uValue


ACCESS TIPOE() 
RETURN SELF:FieldGet(#TIPOE)


ASSIGN TIPOE(uValue) 
SELF:FieldPut(#TIPOE, uValue)
RETURN TIPOE := uValue


ACCESS UNID() 
RETURN SELF:FieldGet(#UNID)


ASSIGN UNID(uValue) 
SELF:FieldPut(#UNID, uValue)
RETURN UNID := uValue


END CLASS
CLASS TabRacf_Page2 INHERIT DATAWINDOW 

	PROTECT oDCDESC01 AS SINGLELINEEDIT
	PROTECT oDCDESC02 AS SINGLELINEEDIT
	PROTECT oDCDESC03 AS SINGLELINEEDIT
	PROTECT oDCDESC04 AS SINGLELINEEDIT
	PROTECT oDCDESC05 AS SINGLELINEEDIT
// 	instance DESC01 
// 	instance DESC02 
// 	instance DESC03 
// 	instance DESC04 
// 	instance DESC05 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS DESC01() 
RETURN SELF:FieldGet(#DESC01)


ASSIGN DESC01(uValue) 
SELF:FieldPut(#DESC01, uValue)
RETURN DESC01 := uValue


ACCESS DESC02() 
RETURN SELF:FieldGet(#DESC02)


ASSIGN DESC02(uValue) 
SELF:FieldPut(#DESC02, uValue)
RETURN DESC02 := uValue


ACCESS DESC03() 
RETURN SELF:FieldGet(#DESC03)


ASSIGN DESC03(uValue) 
SELF:FieldPut(#DESC03, uValue)
RETURN DESC03 := uValue


ACCESS DESC04() 
RETURN SELF:FieldGet(#DESC04)


ASSIGN DESC04(uValue) 
SELF:FieldPut(#DESC04, uValue)
RETURN DESC04 := uValue


ACCESS DESC05() 
RETURN SELF:FieldGet(#DESC05)


ASSIGN DESC05(uValue) 
SELF:FieldPut(#DESC05, uValue)
RETURN DESC05 := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabRacf_Page2",_GetInst()},iCtlID)

oDCDESC01 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE2_DESC01,_GetInst()}}
oDCDESC01:FieldSpec := PADRAO_CHAR_90{}
oDCDESC01:HyperLabel := HyperLabel{#DESC01,"Desc01:",NULL_STRING,"RACF_DESC01"}

oDCDESC02 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE2_DESC02,_GetInst()}}
oDCDESC02:FieldSpec := PADRAO_CHAR_90{}
oDCDESC02:HyperLabel := HyperLabel{#DESC02,"Desc02:",NULL_STRING,"RACF_DESC02"}

oDCDESC03 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE2_DESC03,_GetInst()}}
oDCDESC03:FieldSpec := PADRAO_CHAR_90{}
oDCDESC03:HyperLabel := HyperLabel{#DESC03,"Desc03:",NULL_STRING,"RACF_DESC03"}

oDCDESC04 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE2_DESC04,_GetInst()}}
oDCDESC04:FieldSpec := PADRAO_CHAR_90{}
oDCDESC04:HyperLabel := HyperLabel{#DESC04,"Desc03:",NULL_STRING,"RACF_DESC03"}

oDCDESC05 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE2_DESC05,_GetInst()}}
oDCDESC05:FieldSpec := PADRAO_CHAR_90{}
oDCDESC05:HyperLabel := HyperLabel{#DESC05,"Desc03:",NULL_STRING,"RACF_DESC03"}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TabRacf_Page2,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


END CLASS
CLASS TabRacf_Page3 INHERIT DATAWINDOW 

	PROTECT oDCACAO01 AS SINGLELINEEDIT
	PROTECT oDCACAO02 AS SINGLELINEEDIT
// 	instance ACAO01 
// 	instance ACAO02 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS ACAO01() 
RETURN SELF:FieldGet(#ACAO01)


ASSIGN ACAO01(uValue) 
SELF:FieldPut(#ACAO01, uValue)
RETURN ACAO01 := uValue


ACCESS ACAO02() 
RETURN SELF:FieldGet(#ACAO02)


ASSIGN ACAO02(uValue) 
SELF:FieldPut(#ACAO02, uValue)
RETURN ACAO02 := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabRacf_Page3",_GetInst()},iCtlID)

oDCACAO01 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE3_ACAO01,_GetInst()}}
oDCACAO01:FieldSpec := PADRAO_CHAR_80{}
oDCACAO01:HyperLabel := HyperLabel{#ACAO01,"Acao01:",NULL_STRING,"RACF_ACAO01"}

oDCACAO02 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE3_ACAO02,_GetInst()}}
oDCACAO02:FieldSpec := PADRAO_CHAR_80{}
oDCACAO02:HyperLabel := HyperLabel{#ACAO02,"Acao02:",NULL_STRING,"RACF_ACAO02"}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TabRacf_Page3,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


END CLASS
CLASS TabRacf_Page4 INHERIT DATAWINDOW 

	PROTECT oDCCAUSA01 AS SINGLELINEEDIT
	PROTECT oDCCAUSA02 AS SINGLELINEEDIT
	PROTECT oDCCAUSA03 AS SINGLELINEEDIT
	PROTECT oDCCAUSA04 AS SINGLELINEEDIT
// 	instance CAUSA01 
// 	instance CAUSA02 
// 	instance CAUSA03 
// 	instance CAUSA04 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS CAUSA01() 
RETURN SELF:FieldGet(#CAUSA01)


ASSIGN CAUSA01(uValue) 
SELF:FieldPut(#CAUSA01, uValue)
RETURN CAUSA01 := uValue


ACCESS CAUSA02() 
RETURN SELF:FieldGet(#CAUSA02)


ASSIGN CAUSA02(uValue) 
SELF:FieldPut(#CAUSA02, uValue)
RETURN CAUSA02 := uValue


ACCESS CAUSA03() 
RETURN SELF:FieldGet(#CAUSA03)


ASSIGN CAUSA03(uValue) 
SELF:FieldPut(#CAUSA03, uValue)
RETURN CAUSA03 := uValue


ACCESS CAUSA04() 
RETURN SELF:FieldGet(#CAUSA04)


ASSIGN CAUSA04(uValue) 
SELF:FieldPut(#CAUSA04, uValue)
RETURN CAUSA04 := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabRacf_Page4",_GetInst()},iCtlID)

oDCCAUSA01 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE4_CAUSA01,_GetInst()}}
oDCCAUSA01:FieldSpec := PADRAO_CHAR_80{}
oDCCAUSA01:HyperLabel := HyperLabel{#CAUSA01,"Causa01:",NULL_STRING,"RACF_CAUSA01"}

oDCCAUSA02 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE4_CAUSA02,_GetInst()}}
oDCCAUSA02:FieldSpec := PADRAO_CHAR_80{}
oDCCAUSA02:HyperLabel := HyperLabel{#CAUSA02,"Causa02:",NULL_STRING,"RACF_CAUSA02"}

oDCCAUSA03 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE4_CAUSA03,_GetInst()}}
oDCCAUSA03:FieldSpec := PADRAO_CHAR_80{}
oDCCAUSA03:HyperLabel := HyperLabel{#CAUSA03,"Causa03:",NULL_STRING,"RACF_CAUSA03"}

oDCCAUSA04 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE4_CAUSA04,_GetInst()}}
oDCCAUSA04:FieldSpec := PADRAO_CHAR_80{}
oDCCAUSA04:HyperLabel := HyperLabel{#CAUSA04,"Causa03:",NULL_STRING,"RACF_CAUSA03"}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TabRacf_Page4,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


END CLASS
CLASS TabRacf_Page5 INHERIT DATAWINDOW 

	PROTECT oDCCORRE01 AS SINGLELINEEDIT
	PROTECT oDCCORRE02 AS SINGLELINEEDIT
	PROTECT oDCCORRE03 AS SINGLELINEEDIT
	PROTECT oDCCORRE04 AS SINGLELINEEDIT
// 	instance CORRE01 
// 	instance CORRE02 
// 	instance CORRE03 
// 	instance CORRE04 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS CORRE01() 
RETURN SELF:FieldGet(#CORRE01)


ASSIGN CORRE01(uValue) 
SELF:FieldPut(#CORRE01, uValue)
RETURN CORRE01 := uValue


ACCESS CORRE02() 
RETURN SELF:FieldGet(#CORRE02)


ASSIGN CORRE02(uValue) 
SELF:FieldPut(#CORRE02, uValue)
RETURN CORRE02 := uValue


ACCESS CORRE03() 
RETURN SELF:FieldGet(#CORRE03)


ASSIGN CORRE03(uValue) 
SELF:FieldPut(#CORRE03, uValue)
RETURN CORRE03 := uValue


ACCESS CORRE04() 
RETURN SELF:FieldGet(#CORRE04)


ASSIGN CORRE04(uValue) 
SELF:FieldPut(#CORRE04, uValue)
RETURN CORRE04 := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabRacf_Page5",_GetInst()},iCtlID)

oDCCORRE01 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE5_CORRE01,_GetInst()}}
oDCCORRE01:FieldSpec := PADRAO_CHAR_80{}
oDCCORRE01:HyperLabel := HyperLabel{#CORRE01,"Corre01:",NULL_STRING,"RACF_CORRE01"}

oDCCORRE02 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE5_CORRE02,_GetInst()}}
oDCCORRE02:FieldSpec := PADRAO_CHAR_80{}
oDCCORRE02:HyperLabel := HyperLabel{#CORRE02,"Corre02:",NULL_STRING,"RACF_CORRE02"}

oDCCORRE03 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE5_CORRE03,_GetInst()}}
oDCCORRE03:FieldSpec := PADRAO_CHAR_80{}
oDCCORRE03:HyperLabel := HyperLabel{#CORRE03,"Corre03:",NULL_STRING,"RACF_CORRE03"}

oDCCORRE04 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE5_CORRE04,_GetInst()}}
oDCCORRE04:FieldSpec := PADRAO_CHAR_80{}
oDCCORRE04:HyperLabel := HyperLabel{#CORRE04,"Corre03:",NULL_STRING,"RACF_CORRE03"}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TabRacf_Page5,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


END CLASS
PARTIAL CLASS TabRacf_Page6 INHERIT DATAWINDOW
PROTECT oDCdatai AS DateSle
PROTECT oDCdataf AS DateSle
PROTECT oDCAREA AS COMBOBOX
PROTECT oDCRESPF AS SINGLELINEEDIT
PROTECT oDCCARGOF AS SINGLELINEEDIT
PROTECT oDCSC_CARGOF AS FIXEDTEXT
PROTECT oDCSC_RESPF AS FIXEDTEXT
PROTECT oDCFT22 AS FIXEDTEXT
PROTECT oDCSC_DATAI AS FIXEDTEXT
PROTECT oDCRESPO AS SINGLELINEEDIT
PROTECT oDCCARGO AS SINGLELINEEDIT

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS AREA
RETURN SELF:FieldGet( #AREA )

ASSIGN AREA( uValue )
SELF:FieldPut( #AREA , uValue )

ACCESS CARGO
RETURN SELF:FieldGet( #CARGO )

ASSIGN CARGO( uValue )
SELF:FieldPut( #CARGO , uValue )

ACCESS CARGOF
RETURN SELF:FieldGet( #CARGOF )

ASSIGN CARGOF( uValue )
SELF:FieldPut( #CARGOF , uValue )

ACCESS dataf
RETURN SELF:FieldGet( #dataf )

ASSIGN dataf( uValue )
SELF:FieldPut( #dataf , uValue )

ACCESS datai
RETURN SELF:FieldGet( #datai )

ASSIGN datai( uValue )
SELF:FieldPut( #datai , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"TabRacf_Page6" , _GetInst()},iCtlID)

	SELF:oDCdatai := DateSle{SELF , ResourceID{ TABRACF_PAGE6_DATAI  , _GetInst() } }
	SELF:oDCdatai:FieldSpec := date_field{}
	SELF:oDCdatai:HyperLabel := HyperLabel{#datai , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCdataf := DateSle{SELF , ResourceID{ TABRACF_PAGE6_DATAF  , _GetInst() } }
	SELF:oDCdataf:FieldSpec := date_field{}
	SELF:oDCdataf:HyperLabel := HyperLabel{#dataf , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCAREA := COMBOBOX{SELF , ResourceID{ TABRACF_PAGE6_AREA  , _GetInst() } }
	SELF:oDCAREA:FillUsing( SELF:comboPEGMP05() )
	SELF:oDCAREA:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCAREA:HyperLabel := HyperLabel{#AREA , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCRESPF := SINGLELINEEDIT{SELF , ResourceID{ TABRACF_PAGE6_RESPF  , _GetInst() } }
	SELF:oDCRESPF:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCRESPF:HyperLabel := HyperLabel{#RESPF , "Respf:" , NULL_STRING , "RACF_RESPF"}

	SELF:oDCCARGOF := SINGLELINEEDIT{SELF , ResourceID{ TABRACF_PAGE6_CARGOF  , _GetInst() } }
	SELF:oDCCARGOF:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCCARGOF:HyperLabel := HyperLabel{#CARGOF , "Cargof:" , NULL_STRING , "RACF_CARGOF"}

	SELF:oDCSC_CARGOF := FIXEDTEXT{SELF , ResourceID{ TABRACF_PAGE6_SC_CARGOF  , _GetInst() } }
	SELF:oDCSC_CARGOF:HyperLabel := HyperLabel{#SC_CARGOF , "Cargo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RESPF := FIXEDTEXT{SELF , ResourceID{ TABRACF_PAGE6_SC_RESPF  , _GetInst() } }
	SELF:oDCSC_RESPF:HyperLabel := HyperLabel{#SC_RESPF , "Responsável:" , NULL_STRING , NULL_STRING}

	SELF:oDCFT22 := FIXEDTEXT{SELF , ResourceID{ TABRACF_PAGE6_FT22  , _GetInst() } }
	SELF:oDCFT22:HyperLabel := HyperLabel{#FT22 , "Data Referencia" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAI := FIXEDTEXT{SELF , ResourceID{ TABRACF_PAGE6_SC_DATAI  , _GetInst() } }
	SELF:oDCSC_DATAI:HyperLabel := HyperLabel{#SC_DATAI , "Data Implantação:" , NULL_STRING , NULL_STRING}

	SELF:oDCRESPO := SINGLELINEEDIT{SELF , ResourceID{ TABRACF_PAGE6_RESPO  , _GetInst() } }
	SELF:oDCRESPO:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCRESPO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCRESPO:Font( oFont )
	SELF:oDCRESPO:HyperLabel := HyperLabel{#RESPO , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCCARGO := SINGLELINEEDIT{SELF , ResourceID{ TABRACF_PAGE6_CARGO  , _GetInst() } }
	SELF:oDCCARGO:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCCARGO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Trebuchet MS" }
	oFont:Bold := TRUE
	SELF:oDCCARGO:Font( oFont )
	SELF:oDCCARGO:HyperLabel := HyperLabel{#CARGO , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:Caption := "DataWindow Caption"
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#TabRacf_Page6 , "DataWindow Caption" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ELSE
		SELF:Use(SELF:Owner:Server)
	ENDIF


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS RESPF
RETURN SELF:FieldGet( #RESPF )

ASSIGN RESPF( uValue )
SELF:FieldPut( #RESPF , uValue )

ACCESS RESPO
RETURN SELF:FieldGet( #RESPO )

ASSIGN RESPO( uValue )
SELF:FieldPut( #RESPO , uValue )

END CLASS
CLASS TabRacf_Page7 INHERIT DATAWINDOW 

	PROTECT oDCdatae AS DATESLE
	PROTECT oDCVERI AS SINGLELINEEDIT
	PROTECT oDCNOTA AS SINGLELINEEDIT
	PROTECT oDCDESCRI01 AS SINGLELINEEDIT
	PROTECT oDCSC_DATAE AS FIXEDTEXT
	PROTECT oDCSC_NOTA AS FIXEDTEXT
	PROTECT oDCSC_VERI AS FIXEDTEXT
	PROTECT oDCAPRO AS RADIOBUTTONGROUP
	PROTECT oCCRadioButton2 AS RADIOBUTTON
	PROTECT oCCRadioButton3 AS RADIOBUTTON
	PROTECT oCCRadioButton6 AS RADIOBUTTON
	PROTECT oCCRadioButton7 AS RADIOBUTTON
	PROTECT oDCEFICAZ AS SINGLELINEEDIT
	PROTECT oCCcmdEficaz AS PUSHBUTTON
	PROTECT oCCcmdDemerito AS PUSHBUTTON
	PROTECT oDCDEMERITO AS SINGLELINEEDIT
	PROTECT oDCSC_DATAE1 AS FIXEDTEXT
// 	instance datae 
// 	instance VERI 
// 	instance NOTA 
// 	instance DESCRI01 
// 	instance APRO 
// 	instance EFICAZ 
// 	instance DEMERITO 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS APRO() 
RETURN SELF:FieldGet(#APRO)


ASSIGN APRO(uValue) 
SELF:FieldPut(#APRO, uValue)
RETURN APRO := uValue


METHOD cmdDemerito( ) 
SELF:SERVER:FIELDPUT("DEMERITO",SIMNAO(SELF:SERVER:FIELDGET("DEMERITO")))	

METHOD cmdEficaz( ) 
SELF:SERVER:FIELDPUT("EFICAZ",SIMNAO(SELF:SERVER:FIELDGET("EFICAZ")))	

METHOD cmdEficaz1( )  

ACCESS datae() 
RETURN SELF:FieldGet(#datae)


ASSIGN datae(uValue) 
SELF:FieldPut(#datae, uValue)
RETURN datae := uValue


ACCESS DEMERITO() 
RETURN SELF:FieldGet(#DEMERITO)


ASSIGN DEMERITO(uValue) 
SELF:FieldPut(#DEMERITO, uValue)
RETURN DEMERITO := uValue


ACCESS DESCRI01() 
RETURN SELF:FieldGet(#DESCRI01)


ASSIGN DESCRI01(uValue) 
SELF:FieldPut(#DESCRI01, uValue)
RETURN DESCRI01 := uValue


ACCESS EFICAZ() 
RETURN SELF:FieldGet(#EFICAZ)


ASSIGN EFICAZ(uValue) 
SELF:FieldPut(#EFICAZ, uValue)
RETURN EFICAZ := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[1] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabRacf_Page7",_GetInst()},iCtlID)

aFonts[1] := Font{,10,"Times New Roman"}
aFonts[1]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCdatae := DateSle{SELF,ResourceID{TABRACF_PAGE7_DATAE,_GetInst()}}
oDCdatae:FieldSpec := date_field{}
oDCdatae:HyperLabel := HyperLabel{#datae,NULL_STRING,NULL_STRING,NULL_STRING}

oDCVERI := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE7_VERI,_GetInst()}}
oDCVERI:FieldSpec := PADRAO_CHAR_25{}
oDCVERI:HyperLabel := HyperLabel{#VERI,"Veri:",NULL_STRING,"RACF_VERI"}

oDCNOTA := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE7_NOTA,_GetInst()}}
oDCNOTA:FieldSpec := PADRAO_CHAR_08{}
oDCNOTA:HyperLabel := HyperLabel{#NOTA,"Nota:",NULL_STRING,"RACF_NOTA"}

oDCDESCRI01 := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE7_DESCRI01,_GetInst()}}
oDCDESCRI01:FieldSpec := PADRAO_CHAR_50{}
oDCDESCRI01:HyperLabel := HyperLabel{#DESCRI01,"Veri:",NULL_STRING,"RACF_VERI"}

oDCSC_DATAE := FixedText{SELF,ResourceID{TABRACF_PAGE7_SC_DATAE,_GetInst()}}
oDCSC_DATAE:HyperLabel := HyperLabel{#SC_DATAE,"Data:",NULL_STRING,NULL_STRING}

oDCSC_NOTA := FixedText{SELF,ResourceID{TABRACF_PAGE7_SC_NOTA,_GetInst()}}
oDCSC_NOTA:HyperLabel := HyperLabel{#SC_NOTA,"Notas:",NULL_STRING,NULL_STRING}

oDCSC_VERI := FixedText{SELF,ResourceID{TABRACF_PAGE7_SC_VERI,_GetInst()}}
oDCSC_VERI:HyperLabel := HyperLabel{#SC_VERI,"Verificado Por:",NULL_STRING,NULL_STRING}

oCCRadioButton2 := RadioButton{SELF,ResourceID{TABRACF_PAGE7_RADIOBUTTON2,_GetInst()}}
oCCRadioButton2:HyperLabel := HyperLabel{#RadioButton2,"Condicional",NULL_STRING,NULL_STRING}

oCCRadioButton3 := RadioButton{SELF,ResourceID{TABRACF_PAGE7_RADIOBUTTON3,_GetInst()}}
oCCRadioButton3:HyperLabel := HyperLabel{#RadioButton3,"Devolução",NULL_STRING,NULL_STRING}

oCCRadioButton6 := RadioButton{SELF,ResourceID{TABRACF_PAGE7_RADIOBUTTON6,_GetInst()}}
oCCRadioButton6:HyperLabel := HyperLabel{#RadioButton6,"Atraso",NULL_STRING,NULL_STRING}

oCCRadioButton7 := RadioButton{SELF,ResourceID{TABRACF_PAGE7_RADIOBUTTON7,_GetInst()}}
oCCRadioButton7:HyperLabel := HyperLabel{#RadioButton7,"Excesso",NULL_STRING,NULL_STRING}

oDCEFICAZ := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE7_EFICAZ,_GetInst()}}
oDCEFICAZ:FieldSpec := PADRAO_CHAR_01{}
oDCEFICAZ:HyperLabel := HyperLabel{#EFICAZ,NULL_STRING,NULL_STRING,NULL_STRING}
oDCEFICAZ:BackGround := aBrushes[1]
oDCEFICAZ:Font(aFonts[1], FALSE)

oCCcmdEficaz := PushButton{SELF,ResourceID{TABRACF_PAGE7_CMDEFICAZ,_GetInst()}}
oCCcmdEficaz:HyperLabel := HyperLabel{#cmdEficaz,"Eficaz (S)im(N)ão",NULL_STRING,NULL_STRING}

oCCcmdDemerito := PushButton{SELF,ResourceID{TABRACF_PAGE7_CMDDEMERITO,_GetInst()}}
oCCcmdDemerito:HyperLabel := HyperLabel{#cmdDemerito,"Demerito (S)im(N)ão",NULL_STRING,NULL_STRING}

oDCDEMERITO := SingleLineEdit{SELF,ResourceID{TABRACF_PAGE7_DEMERITO,_GetInst()}}
oDCDEMERITO:FieldSpec := PADRAO_CHAR_01{}
oDCDEMERITO:HyperLabel := HyperLabel{#DEMERITO,NULL_STRING,NULL_STRING,NULL_STRING}
oDCDEMERITO:BackGround := aBrushes[1]
oDCDEMERITO:Font(aFonts[1], FALSE)

oDCSC_DATAE1 := FixedText{SELF,ResourceID{TABRACF_PAGE7_SC_DATAE1,_GetInst()}}
oDCSC_DATAE1:HyperLabel := HyperLabel{#SC_DATAE1,"Descriçao",NULL_STRING,NULL_STRING}

oDCAPRO := RadioButtonGroup{SELF,ResourceID{TABRACF_PAGE7_APRO,_GetInst()}}
oDCAPRO:FillUsing({ ;
					{oCCRadioButton2,"C"}, ;
					{oCCRadioButton3,"D"}, ;
					{oCCRadioButton6,"A"}, ;
					{oCCRadioButton7,"E"} ;
					})
oDCAPRO:HyperLabel := HyperLabel{#APRO,"Disposição",NULL_STRING,NULL_STRING}
oDCAPRO:FieldSpec := PADRAO_CHAR_01{}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TabRacf_Page7,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS NOTA() 
RETURN SELF:FieldGet(#NOTA)


ASSIGN NOTA(uValue) 
SELF:FieldPut(#NOTA, uValue)
RETURN NOTA := uValue


ACCESS VERI() 
RETURN SELF:FieldGet(#VERI)


ASSIGN VERI(uValue) 
SELF:FieldPut(#VERI, uValue)
RETURN VERI := uValue


END CLASS
