PARTIAL CLASS JRACF
METHOD APPEND() 
LOCAL nRACF AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nRACF:=SELF:Server:RACF
nRACF++
SUPER:append()
SELF:SERVER:FIELDPUT("RACF",nRACF)
SELF:SERVER:FIELDPUT("INCUSER",ZUSER)
SELF:SERVER:FIELDPUT("INCDATA",Today())
SELF:SERVER:FIELDPUT("DATA",Today())
RETURN    .t.

METHOD buscaRACF( ) 
	SELF:KeyFind()
//LOCAL oBUSCA AS XBUSCA
//oBUSCA:=XBUSCA{SELF,"Localizar","Digite o Nº"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF
	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RACF","")		

METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skipEX(-1)
ENDIF	

METHOD IMPORTAR() 
LOCAL oCRM AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oCRM:=USEREDE{aDAD}
IF oCRM:nERRO#0
	RETURN .f.
ENDIF
oCRM:GOTOP()
IF oCRM:SEEK(SELF:CRM)
   SELF:SERVER:TIPOE:=oCRM:FIELDGET("TIPOE")
   SELF:SERVER:CBUSCA:=oCRM:FIELDGET("CBUSCA")
   SELF:SERVER:DESCRI:=oCRM:FIELDGET("DESCRI")
   IF ! Empty(oCRM:FIELDGET("PRODUTO"))
      SELF:SERVER:DESENHO:=oCRM:FIELDGET("PRODUTO")
   ELSE
      SELF:SERVER:DESENHO:=oCRM:FIELDGET("APLICACAO")
   ENDIF
   SELF:SERVER:UNID:=oCRM:FIELDGET("UNID")
   SELF:SERVER:QTL1:=oCRM:FIELDGET("QTDE")
   SELF:SERVER:CNFITA:=oCRM:FIELDGET("PEDIDO")
   SELF:SERVER:RASTRO:=oCRM:FIELDGET("RASTRO")
   SELF:SERVER:FORNECEDO:=oCRM:FIELDGET("CLIFOR")
   SELF:SERVER:NOMEF:=oCRM:FIELDGET("NOMEF")
   IF Empty(oCRM:FIELDGET("NRNOTB"))
      SELF:SERVER:CNFFOR:=Str(oCRM:FIELDGET("NRNOTA"))
   ELSE
      SELF:SERVER:CNFFOR:=Str(oCRM:FIELDGET("NRNOTA"),8)+"/"+Str(oCRM:FIELDGET("NRNOTB"),8)	
   ENDIF
   aDAD:=PEGMS01(SELF:SERVER:DESENHO)
   IF aDAD[1]=.T. .AND. ! Empty(aDAD[2])
      SELF:SERVER:DENO:=aDAD[2]
   ENDIF
ENDIF
oCRM:CLOSE()








METHOD IMPRastro() 
LOCAL oCRM AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oCRM:=USEREDE{aDAD}
IF oCRM:nERRO#0
	RETURN .f.
ENDIF
oCRM:SetOrder(3)
oCRM:GOTOP()
IF oCRM:SEEK(AllTrim(SELF:SERVER:RASTRO))
   SELF:SERVER:TIPOE:=oCRM:FIELDGET("TIPOE")
   SELF:SERVER:CBUSCA:=oCRM:FIELDGET("CBUSCA")
   SELF:SERVER:DESCRI:=oCRM:FIELDGET("DESCRI")
   IF ! Empty(oCRM:FIELDGET("PRODUTO"))
      SELF:SERVER:DESENHO:=oCRM:FIELDGET("PRODUTO")
   ELSE
      SELF:SERVER:DESENHO:=oCRM:FIELDGET("APLICACAO")
   ENDIF
   SELF:SERVER:UNID:=oCRM:FIELDGET("UNID")
   SELF:SERVER:QTL1:=oCRM:FIELDGET("QTDE")
   SELF:SERVER:CNFITA:=oCRM:FIELDGET("PEDIDO")
   SELF:SERVER:CRM:=oCRM:FIELDGET("CRM")
   SELF:SERVER:FORNECEDO:=oCRM:FIELDGET("CLIFOR")
   SELF:SERVER:NOMEF:=oCRM:FIELDGET("NOMEF")
   IF Empty(oCRM:FIELDGET("NRNOTB"))
      SELF:SERVER:CNFFOR:=Str(oCRM:FIELDGET("NRNOTA"))
   ELSE
      SELF:SERVER:CNFFOR:=Str(oCRM:FIELDGET("NRNOTA"),8)+"/"+Str(oCRM:FIELDGET("NRNOTB"),8)	
   ENDIF
   aDAD:=PEGMS01(SELF:SERVER:DESENHO)
   IF aDAD[1]=.T. .AND. ! Empty(aDAD[2])
      SELF:SERVER:DENO:=aDAD[2]
   ENDIF
ENDIF
oCRM:CLOSE()








METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
      FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
PARTIAL CLASS RACFPAG1
METHOD CMDCRM3L(cCODIGO) 	
LOCAL aVAL AS ARRAY
aVAL:={}
AAdd(aVAL,SELF:SERVER:FIELDGET("RACF"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESC01"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESC02"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESC03"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESC04"))
AAdd(aVAL,SELF:SERVER:FIELDGET("DESC05"))
CMD3L(cCODIGO,"I",aVAL)

METHOD cmdCrm3LA( ) 
	SELF:CMDCRM3L(SELF:SERVER:FIELDGET("CBUSCA"))

METHOD cmdCrm3LB( ) 
SELF:CMDCRM3L(SELF:SERVER:FIELDGET("DESENHO"))

METHOD esccod() 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DENO",oESC:NOME)
ENDIF


METHOD esccodX( ) 
LOCAL oESC AS XESCCOD	
LOCAL cARQ AS STRING
cARQ:="XXXX"
DO CASE
   CASE SELF:SERVER:FIELDGET("TIPOE")="C"
   	    cARQ:="MT01.DBF"
   CASE SELF:SERVER:FIELDGET("TIPOE")="M"
   	    cARQ:="MU01.DBF"
   CASE SELF:SERVER:FIELDGET("TIPOE")="T"
   	    cARQ:="MP03.DBF"
ENDCASE
oESC:=XESCCOD{SELF,cARQ}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:SERVER:FIELDPUT("CBUSCA",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF
SELF:PEGCODX()

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MB01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:NUMERO)
    SELF:SERVER:FIELDPUT("FORnecedo",oESC:NUMERO)
    SELF:server:FIELDPUT("NOMEF",oESC:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("DESENHO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()	

METHOD pegcod( ) 
LOCAL aPRO AS ARRAY	
aPRO:=PEGMS01(SELF:SERVER:DESENHO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:SERVER:FIELDPUT("DENO",aPRO[2])
   SELF:SERVER:FIELDPUT("REVISAO",aPRO[5])
ENDIF
	

METHOD pegcodX( ) 
LOCAL aPRO AS ARRAY	
aPRO:={.F.,"",""}
DO CASE
   CASE SELF:SERVER:FIELDGET("TIPOE")="C"
        aPRO:=PEGMT01(SELF:SERVER:FIELDGET("CBUSCA"),ZCURINI,ZCURDIR)
   CASE SELF:SERVER:FIELDGET("TIPOE")="M"
        aPRO:=PEGMU01(SELF:SERVER:FIELDGET("CBUSCA"),ZCURINI,ZCURDIR)
   CASE SELF:SERVER:FIELDGET("TIPOE")="T"
        aPRO:=PEGMP03(SELF:SERVER:FIELDGET("CBUSCA"),ZCURINI,ZCURDIR)
ENDCASE
IF aPRO[1]=.T.
   SELF:SERVER:FIELDPUT("DESCRI",aPRO[2])
   IF Empty(SELF:SERVER:FIELDGET("DESENHO"))
      SELF:SERVER:FIELDPUT("DESENHO",aPRO[3])
      SELF:pegcod()
   ENDIF
ENDIF
	

METHOD pegfor( ) 
LOCAL Aforn AS ARRAY	
	            aFORN:=PEGMB01(SELF:SERVER:FORNECEDO,ZCURINI,ZCURDIR)
            IF aFORN[1]=.T.
               SELF:SERVER:FAX:=aFORN[4]
               SELF:SERVER:FONE:=aFORN[5]
               SELF:SERVER:NOMEF:=aFORN[2]
               SELF:SERVER:RESP:=aFORN[6]
               SELF:SERVER:RESPC:=aFORN[7]
 			   SELF:SERVER:EMAIL:=aFORN[8]
            ENDIF

METHOD pegforpcp( ) 
LOCAL Aforn AS ARRAY	
            aFORN:=PEGMB012(SELF:SERVER:FORNECEDO,ZCURINI,ZCURDIR)
            IF aFORN[1]=.T.
               SELF:SERVER:FAX:=aFORN[4]
               SELF:SERVER:FONE:=aFORN[5]
               SELF:SERVER:NOMEF:=aFORN[2]
               SELF:SERVER:RESP:=aFORN[6]
               SELF:SERVER:RESPC:=aFORN[7]
 			   SELF:SERVER:EMAIL:=aFORN[8]
            ENDIF	

METHOD TABTIPO 
RETU MTD02("MW0503",1)

END CLASS
PARTIAL CLASS TabRacf_Page6
METHOD ListBoxSelect(oControlEvent) 
	LOCAL oControl AS Control
	LOCAL aRESP AS ARRAY	
	oControl := IIf(oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control)
	SUPER:ListBoxSelect(oControlEvent)
	//Put your changes here
    DO CASE
       CASE oCONTROL:NAMESYM==#AREA
            aRESP:=PEGMP05(SELF:SERVER:AREA,ZCURINI,ZCURDIR)
            IF aRESP[1]=.T.
               SELF:SERVER:RESPO:=aRESP[2]
               SELF:SERVER:CARGO:=aRESP[3]
            ENDIF
	ENDCASE	
	RETURN NIL




METHOD ComboPEGMP05() 
RETU PEGCOMBO("MP05.DBF","DESCRI","CODIGO")


END CLASS
FUNC PEGMB012(nFORNECEDO AS DWORD,cCURINI AS STRING,cCURDIR AS STRING)
LOCAL aRETU:={.F.,"","","","","","","",""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
IF IsNil(nFORNECEDO)
   RETU aRETU
ENDIF
aDAD:={cCURINI,"MB01.DBF",cCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
    RETU aRETU
ENDIF
oARQ:GOTOP()
IF oARQ:SEEK(nFORNECEDO,.F.)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("NOME")
   aRETU[3]:=oARQ:FIELDGET("COGNOME")
   aRETU[4]:=oARQ:FIELDGET("TELFAXPCP")
   aRETU[5]:=oARQ:FIELDGET("TELPCP")
   aRETU[6]:=oARQ:FIELDGET("RESPPCP")
   aRETU[7]:=oARQ:FIELDGET("CARGOPCP")
   aRETU[8]:=oARQ:FIELDGET("EMAILPCP")
   aRETU[9]:=oARQ:FIELDGET("CONCEITO")
ENDIF
oARQ:CLOSE()
RETU aRETU

