PARTIAL CLASS JRNC
METHOD ABRERACF() 
LOCAL nRACF AS DWORD
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE
  aDAD:={zCURINI,"RACF.DBF",zCURDIR}
   oSERVER:=USEREDE{aDAD}
   IF oSERVER:nERRO#0
      RETU SELF
   ENDIF
   oSERVER:GOBOTTOM()
   nRACF:=oSERVER:FIELDGET("RACF")
   nRACF++
   oSERVER:APPEND()
   oSERVER:FIELDPUT("RACF",nRACF)
   oSERVER:FIELDPUT("DATA",Today())
   oSERVER:FIELDPUT("RNC",SELF:SERVER:FIELDGET("RNC"))
   oSERVER:FIELDPUT("FORNECEDO",SELF:SERVER:FIELDGET("CLIFOR"))
   oSERVER:FIELDPUT("NOMEF",SELF:SERVER:FIELDGET("NOME"))
   oSERVER:FIELDPUT("DENO",SELF:SERVER:FIELDGET("CODIGO"))
   oSERVER:FIELDPUT("DESENHO",SELF:SERVER:FIELDGET("DESCRI"))
   oSERVER:FIELDPUT("QTL1",SELF:SERVER:FIELDGET("QTL"))
   oSERVER:FIELDPUT("QTN1",SELF:SERVER:FIELDGET("QTLN"))
   oSERVER:FIELDPUT("CNFITA",SELF:SERVER:FIELDGET("NFIC"))
   oSERVER:FIELDPUT("DESC01",SELF:SERVER:FIELDGET("DEC01"))
   oSERVER:FIELDPUT("DESC02",SELF:SERVER:FIELDGET("DEC02"))
   oSERVER:FIELDPUT("DESC03",SELF:SERVER:FIELDGET("DEC03"))
   oSERVER:FIELDPUT("ACAO01",SELF:SERVER:FIELDGET("ACAO01"))
   oSERVER:FIELDPUT("ACAO02",SELF:SERVER:FIELDGET("ACAO02"))
   oSERVER:FIELDPUT("ACAO03",SELF:SERVER:FIELDGET("ACAO03"))
   oSERVER:FIELDPUT("ACAO04",SELF:SERVER:FIELDGET("ACAO04"))
   oSERVER:FIELDPUT("AREA",SELF:SERVER:FIELDGET("AREA"))
   oSERVER:FIELDPUT("RESPO",SELF:SERVER:FIELDGET("RESPO"))
   oSERVER:FIELDPUT("CARGO",SELF:SERVER:FIELDGET("CARGO"))
   oSERVER:FIELDPUT("UNID",SELF:SERVER:FIELDGET("UNID"))
   oSERVER:CLOSE()
   SELF:SERVER:FIELDPUT("NRACF",nRACF)
  ENVIARACF(SELF:SERVER:FIELDGET("RNC"),nRACF)
RETURN .t.


METHOD ABRESAC() 
LOCAL nSAC AS DWORD
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE
   aDAD:={zCURINI,"SAC.DBF",zCURDIR}
   oSERVER:=USEREDE{aDAD}
   IF oSERVER:nERRO#0
      RETU SELF
   ENDIF
   oSERVER:GOBOTTOM()
   nSAC:=oSERVER:FIELDGET("SAC")
   nSAC++
   oSERVER:APPEND()
   oSERVER:FIELDPUT("SAC",nSAC)
   oSERVER:FIELDPUT("DATA",Today())
   oSERVER:FIELDPUT("RNC",SELF:SERVER:FIELDGET("RNC"))
   oSERVER:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIFOR"))
   oSERVER:FIELDPUT("CLINOME",SELF:SERVER:FIELDGET("NOME"))
   oSERVER:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("CODIGO"))
   oSERVER:FIELDPUT("NOME",SELF:SERVER:FIELDGET("DESCRI"))
   oSERVER:FIELDPUT("QTL",SELF:SERVER:FIELDGET("QTL"))
   oSERVER:FIELDPUT("QTN",SELF:SERVER:FIELDGET("QTLN"))
   oSERVER:FIELDPUT("DESC01",SELF:SERVER:FIELDGET("DEC01"))
   oSERVER:FIELDPUT("DESC02",SELF:SERVER:FIELDGET("DEC02"))
   oSERVER:FIELDPUT("DESC03",SELF:SERVER:FIELDGET("DEC03"))
   oSERVER:FIELDPUT("TIPO","P")
   oSERVER:CLOSE()
   SELF:SERVER:FIELDPUT("NSAC",nSAC)


METHOD ANTERIOR 
SELF:oSFJRNCI:Browser:SuspendUpdate()
SELF:oSFJRNCI:SkipPREVIOUS()
IF SELF:oSFJRNCI:Server:BOF
	SELF:oSFJRNCI:SkipNEXT()
ENDIF
SELF:oSFJRNCI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nRNC AS DWORD
LOCAL oINC AS jrncinc
SELF:server:setorder(1)
SELF:server:gobottom()
nRNC:=SELF:Server:RNC
nRNC++
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("RNC",nRNC)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("DATAD",Today())
SELF:SERVER:FIELDPUT("INCUSER",ZUSER)
SELF:SERVER:FIELDPUT("INCDATA",Today())
SELF:SERVER:FIELDPUT("RAC","N")
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)
oINC:=jrncinc{SELF}
oINC:SHOW()
IF SELF:SERVER:FIELDGET("CODRNC")="C"
   SELF:ABRESAC()
ENDIF	
IF SELF:SERVER:FIELDGET("CODRNC")="F"
   SELF:ABRERACF()
ENDIF	
IF SELF:SERVER:FIELDGET("DISPO")="R" .AND. Empty(SELF:sERVER:FIELDGET("NSAC"))	
   IF SELF:SERVER:FIELDGET("QTL")=SELF:SERVER:FIELDGET("QTLN")
     SELF:ABRESAC()
   ENDIF
ENDIF	
IF SELF:SERVER:FIELDGET("DISPO")="U" .AND. Empty(SELF:sERVER:FIELDGET("NSAC"))	
   IF DIVIDIR(SELF:SERVER:FIELDGET("QTLN")/SELF:SERVER:FIELDGET("QTL"),18,2)>=0.20
     SELF:ABRESAC()
   ENDIF
ENDIF	
ENVIARNC(NRNC,"Avulsa","",{"","",""})

METHOD Buscanum 
	SELF:KeyFind()
//LOCAL oBUSCA AS xBUSCA
//oBUSCA:=xBUSCA{SELF,"Localizar RNC","Digite Nº"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF

METHOD buscaRNC( ) 
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Localizar","Digite o Nº"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
ENDIF


METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD cmdgrvnc( ) 
	 SELF:oSFJRNCI:SERVER:FIELDPUT("QTNC",SELF:oDCNAOCONF:Value)
	

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RNC","")		

METHOD CRIARACF 	
IF Empty(SELF:SERVER:FIELDGET("NRACF"))
   SELF:ABRERACF()
   SELF:SERVER:FIELDPUT("RAC","S")
ENDIF		

METHOD CRIASAC 
IF Empty(SELF:SERVER:FIELDGET("NSAC"))
   SELF:ABRESAC()
   SELF:SERVER:FIELDPUT("RAC","S")
ENDIF	

METHOD DELETE() 
IF ! Empty(SELF:SERVER:FIELDGET("FECDATA"))
   alert("Exclusão Bloqueada RNC Já Fechada","Exclusão Bloqueada RNC Já Fechada")
   RETURN .f.
ENDIF	
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
   SELF:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJRNCI:SERVER:SUSPENDNOTIFICATION()
   SELF:oSFJRNCI:SERVER:gotop()
   WHILE ! SELF:oSFJRNCI:SERVER:eof
	 	SELF:oSFJRNCI:SERVER:delete()
	 	SELF:oSFJRNCI:SERVER:skip()	
      ENDDO
	SELF:oSFJRNCI:SERVER:resetnotification()
	SELF:oSFJRNCI:SERVER:notify(notifyfilechange)
	SELF:server:delete()
	SELF:server:unlock()
	SELF:SERVER:RESETNOTIFICATION()
	SELF:SERVER:Notify(notifyfilechange)
	SELF:SERVER:SKIPEX(-1)
ENDIF	

METHOD esccoderr( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"CRRSERR.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:oSFJRNCI:SERVER:FIELDPUT("CODERR",oESC:CODIGO)
ENDIF	

METHOD escsetcod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"CRRSSET.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:oSFJRNCI:SERVER:FIELDPUT("SETCOD",oESC:CODIGO)
ENDIF		

METHOD EXCLUIR 
IF  MDG("Apagar Registro") .AND. SELF:oSFJRNCI:server:LockCurrentRecord()
	SELF:oSFJRNCI:SERVER:SUSPENDNOTIFICATION()
    SELF:oSFJRNCI:server:delete()
    SELF:oSFJRNCI:server:unlock()
    SELF:oSFJRNCI:SERVER:resetnotification()
    SELF:oSFJRNCI:SERVER:notify(notifydelete)
    SELF:oSFJRNCI:Browser:refresh()
ENDIF	


METHOD INCLUIR 
LOCAL nRNC AS DWORD	
nRNC:=SELF:SERVER:RNC
SELF:oSFJRNCI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJRNCI:SERVER:APPEND()
SELF:oSFJRNCI:SERVER:RNC:=nRNC
SELF:oSFJRNCI:SERVER:commit()
SELF:oSFJRNCI:SERVER:resetnotification()
SELF:oSFJRNCI:SERVER:notify(notifyappend)
SELF:oSFJRNCI:Browser:refresh()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
      FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJRNCI:Browser:SuspendUpdate()
SELF:oSFJRNCI:SkipNext()
IF SELF:oSFJRNCI:Server:Eof
	SELF:oSFJRNCI:SkipPrevious()
ENDIF
SELF:oSFJRNCI:Browser:RestoreUpdate()

METHOD Timer() 
   SELF:SERVER:COMMIT()


METHOD VERSAC( ) 
	LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL oJAN AS XJSacDia
LOCAL aDAD AS ARRAY
IF Empty(SELF:SERVER:FIELDGET("NSAC"))
   alert("Sac em Branco")	
   RETURN .f.
ENDIF	
IF ! entramenu("TGQ",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"SAC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOTOP()
IF ! oSERVER:SEEK(SELF:SERVER:FIELDGET("NSAC"))
   OserveR:close()
   alert("Sac Não Encontrada")
   RETURN .f.
ENDIF	
aDAD:={zCURINI,"SACI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
oJAN:=XJSACDIA{SELF,oSERVER,oSERVE2}
oJAN:SHOW()		
	

END CLASS
PARTIAL CLASS TabControl1_Page1
METHOD esccod() 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:NOME)
ENDIF

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
IF SELF:SERVER:FIELDGET("TIPCAD")="F" .OR. SELF:SERVER:FIELDGET("TIPCAD")="C"
   IF SELF:SERVER:FIELDGET("TIPCAD")="F"	
  	  oESC:=XESCNUM{SELF,"MB01.DBF"}
   ELSE
  	  oESC:=XESCNUM{SELF,"MA01.DBF"}
   ENDIF	
	oESC:SHOW()	
	IF ! IsNil(oESC:NUMERO)
	    SELF:SERVER:FIELDPUT("CLIFOR",oESC:NUMERO)
	    SELF:SERVER:FIELDPUT("NOME",oESC:NOME)
	ENDIF
ENDIF

METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("ABRNUM",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("ABRNOM",oESCMP04:NOME)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("CODIGO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()	

METHOD btnPEGMA01 
LOCAL aFORN,aCLI AS ARRAY	
           IF SELF:SERVER:TIPCAD="F"
              aFORN:=PEGMB01(SELF:SERVER:CLIFOR,ZCURINI,ZCURDIR)
              IF aFORN[1]=.T.
                 SELF:SERVER:NOME:=aFORN[2]
  	           ENDIF
           ENDIF
           IF SELF:SERVER:TIPCAD="C"
              aCLI:=PEGMA01(SELF:SERVER:CLIFOR,ZCURINI,ZCURDIR)
              IF aCLI[1]=.T.
                 SELF:SERVER:NOME:=aCLI[2]
   	        ENDIF
           ENDIF


METHOD btnPEGMP04 
LOCAL aTEC AS ARRAY
LOCAL ACOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
           aTEC:=PEGMP04(SELF:SERVER:ABRNUM,ZCURINI,ZCURDIR,ACOM)
           IF aTEC[1]=.T.
              SELF:SERVER:ABRNOM:=aTEC[2]
           ENDIF


METHOD btnPEGMS01 
LOCAL aPRO AS ARRAY	
            aPRO:=PEGMS01(SELF:SERVER:CODIGO)
            IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
               SELF:SERVER:DESCRI:=aPRO[2]
            ENDIF
	



END CLASS
PARTIAL CLASS TabControl1_Page2
METHOD ListBoxSelect(oControlEvent) 
	LOCAL oControl AS Control
	LOCAL aRESP AS ARRAY
	oControl := IIf(oControlEvent == NULL_OBJECT, NULL_OBJECT, oControlEvent:Control)
	SUPER:ListBoxSelect(oControlEvent)
	//Put your changes here
	DO CASE
	       CASE oCONTROL:NAMESYM==#AREA
                             aRESP:=PEGMP05(SELF:SERVER:AREA,ZCURINI,ZCURDIR)
                             IF aRESP[1]=.T.
                                  SELF:SERVER:RESPO:=aRESP[2]
                                  SELF:SERVER:CARGO:=aRESP[3]
                             ENDIF
	ENDCASE
	RETURN NIL


METHOD comboPEGMP05() 
RETU PEGCOMBO("MP05.DBF","DESCRI","CODIGO")

END CLASS
PARTIAL CLASS TabControl1_Page4
METHOD Calc( ) 
SELF:SERVER:FIELDPUT("VALSUC",SELF:SERVER:FIELDGET("QTDSUC")*SELF:SERVER:FIELDGET("PECSUC"))	

METHOD CNQ( ) 
LOCAL oACPNC AS USEREDE
LOCAL aDAD AS ARRAY	
LOCAL oJANINT AS jcnqINT
LOCAL oJANEXT AS JCNQEXT
LOCAL nACPNC,Y AS DWORD


SELF:SERVER:Commit()
aDAD:={zCURINI,"ACPNC.DBF",ZCURDIR}
oACPNC:=USEREDE{aDAD}
IF oACPNC:nERRO#0
    RETURN .f.
ENDIF
oACPNC:GOTOP()
oACPNC:SETORDER(3)
IF ! oACPNC:SEEK(SELF:SERVER:FIELDGET("RNC"))
    oACPNC:SETORDER(1)		
    oACPNC:Gobottom()
    nACPNC:=oACPNC:FIELDGET("ACPNC")
    nACPNC++
	oACPNC:APPEND()
    oACPNC:FIELDPUT("ACPNC",nACPNC)
    oACPNC:FIELDPUT("DATA",SELF:SERVER:FIELDGET("DATA"))
    oACPNC:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIFOR"))
    oACPNC:FIELDPUT("CLINOME",SELF:SERVER:FIELDGET("NOME"))
    oACPNC:FIELDPUT("produto",SELF:SERVER:FIELDGET("CODIGO"))
    oACPNC:FIELDPUT("DESPRO",SELF:SERVER:FIELDGET("DESCRI"))
    oACPNC:FIELDPUT("RNC",SELF:SERVER:FIELDGET("RNC"))
    oACPNC:FIELDPUT("SAC",SELF:SERVER:FIELDGET("NSAC"))
    FOR Y:=1 TO 7
       	oACPNC:FIELDPUT("QTI"+StrZero(Y,2),0)
       	oACPNC:FIELDPUT("VLI"+StrZero(Y,2),0)	
    NEXT Y
    FOR Y:=1 TO 11
        oACPNC:FIELDPUT("QTE"+StrZero(Y,2),0)
       	oACPNC:FIELDPUT("VLE"+StrZero(Y,2),0)		
    NEXT Y	
ENDIF
IF ! Empty(oACPNC:FIELDGET("DATAFEC"))
   alert("Ja Fechada")	
   RETURN .f.
ENDIF	
IF SELF:SERVER:FIELDGET("CODRNC")="C"
   oJANEXT:=jcnqEXT{SELF,,oACPNC}
   oJANEXT:SHOW()
ELSE	
   oJANINT:=jcnqINT{SELF,,oACPNC}
   oJANINT:SHOW()
ENDIF
	

METHOD EditFocusChange(oEditFocusChangeEvent) 
	LOCAL oControl AS Control
//	LOCAL lGotFocus AS LOGIC
	LOCAL aTEC  AS ARRAY
    LOCAL acom AS ARRAY
	oControl := IIf(oEditFocusChangeEvent == NULL_OBJECT, NULL_OBJECT, oEditFocusChangeEvent:Control)
	 IIf(oEditFocusChangeEvent == NULL_OBJECT, FALSE, oEditFocusChangeEvent:GotFocus)        //lGotFocus :=
	SUPER:EditFocusChange(oEditFocusChangeEvent)
	//Put your changes here
	aCOM:={zMES,zANO,ZEMPRESA}
   DO CASE
      CASE oCONTROL:NAMESYM==#RETOPR
           aTEC:=PEGMP04(SELF:SERVER:RETOPR,ZCURINI,ZCURDIR,acom)
           IF aTEC[1]=.T.
              SELF:SERVER:RETNOM:=aTEC[2]
           ENDIF
      CASE oCONTROL:NAMESYM==#RETOP2
           aTEC:=PEGMP04(SELF:SERVER:RETOP2,ZCURINI,ZCURDIR,acom)
           IF aTEC[1]=.T.
              SELF:SERVER:RETNO2:=aTEC[2]
           ENDIF
      CASE oCONTROL:NAMESYM==#RETOP3
           aTEC:=PEGMP04(SELF:SERVER:RETOP3,ZCURINI,ZCURDIR,acom)
           IF aTEC[1]=.T.
              SELF:SERVER:RETNO3:=aTEC[2]
           ENDIF

	 ENDCASE
RETURN NIL
	



METHOD escrea1() 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("RETOPR",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("RETNOM",oESCMP04:NOME)
ENDIF

METHOD escrea2() 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("RETOP2",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("RETNO2",oESCMP04:NOME)
ENDIF

METHOD escrea3() 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("RETOP3",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("RETNO3",oESCMP04:NOME)
ENDIF

METHOD PegPreco( ) 
LOCAL aPRC AS ARRAY
LOCAL oBUSCA AS XBUSCA
aPRC:=MS02PRC(SELF:SERVER:FIELDGET("CODIGO"),SELF:SERVER:FIELDGET("CLIFOR"),.T.,.T.,ZCURINI,ZCURDIR,aDIR)	
IF aPRC[1]>0
   SELF:SERVER:FIELDPUT("PECSUC",aPRC[1])
ELSE
   IF MDG("Digitar Nº Cliente")
   	 oBUSCA:=xBUSCA{SELF,"Informar Nº","Digite Nº "}
     oBUSCA:lMES:=.T.
     oBUSCA:SHOW()
     IF oBUSCA:lOK
		aPRC:=MS02PRC(SELF:SERVER:FIELDGET("CODIGO"),SELF:SERVER:FIELDGET("CLIFOR"),.T.,.T.,ZCURINI,ZCURDIR,aDIR)	
		IF aPRC[1]>0
		   SELF:SERVER:FIELDPUT("PECSUC",aPRC[1])
		ENDIF
     ENDIF
   ENDIF
ENDIF	


END CLASS
