#region DEFINES
STATIC DEFINE JRNC_ANTERIOR := 112 
STATIC DEFINE JRNC_BUSCANUM := 126 
STATIC DEFINE JRNC_CMDGRVNC := 124 
STATIC DEFINE JRNC_CODRNC := 100 
STATIC DEFINE JRNC_DATA := 117 
STATIC DEFINE JRNC_ESCCODERR := 114 
STATIC DEFINE JRNC_ESCSETCOD := 113 
STATIC DEFINE JRNC_EXCLUIR := 107 
STATIC DEFINE JRNC_FECDATA := 118 
STATIC DEFINE JRNC_FIXEDTEXT1 := 115 
STATIC DEFINE JRNC_FIXEDTEXT2 := 116 
STATIC DEFINE JRNC_FIXEDTEXT4 := 121 
STATIC DEFINE JRNC_FIXEDTEXT5 := 123 
STATIC DEFINE JRNC_INCLUIR := 108 
STATIC DEFINE JRNC_JRNCI := 106 
STATIC DEFINE JRNC_LAUDO := 166 
STATIC DEFINE JRNC_NAOCONF := 122 
STATIC DEFINE JRNC_NRACF := 119 
STATIC DEFINE JRNC_NSAC := 120 
STATIC DEFINE JRNC_PORNUM := 127 
STATIC DEFINE JRNC_PROXIMO := 111 
STATIC DEFINE JRNC_RB1 := 104 
STATIC DEFINE JRNC_RB2 := 105 
STATIC DEFINE JRNC_RB3 := 102 
STATIC DEFINE JRNC_RB4 := 103 
STATIC DEFINE JRNC_RNC := 101 
STATIC DEFINE JRNC_SC_CODIGO1 := 109 
STATIC DEFINE JRNC_TABCONTROL1 := 110 
STATIC DEFINE JRNC_THESINGLELINEEDIT36 := 188 
STATIC DEFINE JRNC_VERSAC := 125 
STATIC DEFINE TABCONTROL1_PAGE1_ABRNOM := 134
STATIC DEFINE TABCONTROL1_PAGE1_ABRNUM := 135
STATIC DEFINE TABCONTROL1_PAGE1_CLIFOR := 129
STATIC DEFINE TABCONTROL1_PAGE1_CODIGO := 121
STATIC DEFINE TABCONTROL1_PAGE1_DESCRI := 122
STATIC DEFINE TABCONTROL1_PAGE1_ESCCOD := 140
STATIC DEFINE TABCONTROL1_PAGE1_ESCFOR := 139
STATIC DEFINE TABCONTROL1_PAGE1_ESCRES := 138
STATIC DEFINE TABCONTROL1_PAGE1_FOTO := 145
STATIC DEFINE TABCONTROL1_PAGE1_FT26 := 102
STATIC DEFINE TABCONTROL1_PAGE1_NFC := 131
STATIC DEFINE TABCONTROL1_PAGE1_NFIC := 127
STATIC DEFINE TABCONTROL1_PAGE1_NOME := 130
STATIC DEFINE TABCONTROL1_PAGE1_OFC := 125
STATIC DEFINE TABCONTROL1_PAGE1_PED := 128
STATIC DEFINE TABCONTROL1_PAGE1_PEGMA01 := 142 
STATIC DEFINE TABCONTROL1_PAGE1_PEGMP04 := 143 
STATIC DEFINE TABCONTROL1_PAGE1_PEGMS01 := 141 
STATIC DEFINE TABCONTROL1_PAGE1_QTL := 136
STATIC DEFINE TABCONTROL1_PAGE1_QTLN := 137
STATIC DEFINE TABCONTROL1_PAGE1_RASTRO := 124
STATIC DEFINE TABCONTROL1_PAGE1_RB15 := 117
STATIC DEFINE TABCONTROL1_PAGE1_RB16 := 116
STATIC DEFINE TABCONTROL1_PAGE1_RB17 := 119
STATIC DEFINE TABCONTROL1_PAGE1_RB18 := 120
STATIC DEFINE TABCONTROL1_PAGE1_REVI := 123
STATIC DEFINE TABCONTROL1_PAGE1_RIC := 132
STATIC DEFINE TABCONTROL1_PAGE1_SC_CODIGO := 113
STATIC DEFINE TABCONTROL1_PAGE1_SC_DESCRI := 112
STATIC DEFINE TABCONTROL1_PAGE1_SC_DESTINO2 := 144
STATIC DEFINE TABCONTROL1_PAGE1_SC_NFC := 103
STATIC DEFINE TABCONTROL1_PAGE1_SC_NFIC := 106
STATIC DEFINE TABCONTROL1_PAGE1_SC_NOME := 104
STATIC DEFINE TABCONTROL1_PAGE1_SC_OFC := 109
STATIC DEFINE TABCONTROL1_PAGE1_SC_PED := 105
STATIC DEFINE TABCONTROL1_PAGE1_SC_QTL := 101
STATIC DEFINE TABCONTROL1_PAGE1_SC_QTL2 := 100
STATIC DEFINE TABCONTROL1_PAGE1_SC_RASTRO := 110
STATIC DEFINE TABCONTROL1_PAGE1_SC_REVI := 111
STATIC DEFINE TABCONTROL1_PAGE1_SC_RIC := 114
STATIC DEFINE TABCONTROL1_PAGE1_SC_SETOR := 108
STATIC DEFINE TABCONTROL1_PAGE1_SC_SETOR1 := 107
STATIC DEFINE TABCONTROL1_PAGE1_SETOR := 126
STATIC DEFINE TABCONTROL1_PAGE1_TIPCAD := 115
STATIC DEFINE TABCONTROL1_PAGE1_TIPERR := 118
STATIC DEFINE TABCONTROL1_PAGE1_UNID := 133
STATIC DEFINE TABCONTROL1_PAGE2_AREA := 116
STATIC DEFINE TABCONTROL1_PAGE2_CARGO := 106
STATIC DEFINE TABCONTROL1_PAGE2_CODRET := 105
STATIC DEFINE TABCONTROL1_PAGE2_CRIARACF := 118
STATIC DEFINE TABCONTROL1_PAGE2_CRIASAC := 120
STATIC DEFINE TABCONTROL1_PAGE2_DATAD := 111
STATIC DEFINE TABCONTROL1_PAGE2_DEC01 := 108
STATIC DEFINE TABCONTROL1_PAGE2_DEC02 := 109
STATIC DEFINE TABCONTROL1_PAGE2_DEC03 := 110
STATIC DEFINE TABCONTROL1_PAGE2_DISPO := 127
STATIC DEFINE TABCONTROL1_PAGE2_FT27 := 114
STATIC DEFINE TABCONTROL1_PAGE2_FT28 := 113
STATIC DEFINE TABCONTROL1_PAGE2_FT29 := 115
STATIC DEFINE TABCONTROL1_PAGE2_FT30 := 122
STATIC DEFINE TABCONTROL1_PAGE2_GB1 := 112
STATIC DEFINE TABCONTROL1_PAGE2_NRACF := 117
STATIC DEFINE TABCONTROL1_PAGE2_NSAC := 119
STATIC DEFINE TABCONTROL1_PAGE2_OUTROS := 132
STATIC DEFINE TABCONTROL1_PAGE2_RAC := 121
STATIC DEFINE TABCONTROL1_PAGE2_RB10 := 131
STATIC DEFINE TABCONTROL1_PAGE2_RB14 := 128
STATIC DEFINE TABCONTROL1_PAGE2_RB19 := 104
STATIC DEFINE TABCONTROL1_PAGE2_RB20 := 103
STATIC DEFINE TABCONTROL1_PAGE2_RB21 := 102
STATIC DEFINE TABCONTROL1_PAGE2_RB22 := 101
STATIC DEFINE TABCONTROL1_PAGE2_RB23 := 100
STATIC DEFINE TABCONTROL1_PAGE2_RB5 := 130
STATIC DEFINE TABCONTROL1_PAGE2_RB6 := 126
STATIC DEFINE TABCONTROL1_PAGE2_RB7 := 124
STATIC DEFINE TABCONTROL1_PAGE2_RB8 := 129
STATIC DEFINE TABCONTROL1_PAGE2_RB9 := 125
STATIC DEFINE TABCONTROL1_PAGE2_RESPO := 107
STATIC DEFINE TABCONTROL1_PAGE2_SC_DATAD := 123
STATIC DEFINE TABCONTROL1_PAGE3_ACAO01 := 111 
STATIC DEFINE TABCONTROL1_PAGE3_ACAO02 := 112 
STATIC DEFINE TABCONTROL1_PAGE3_ACAO03 := 113 
STATIC DEFINE TABCONTROL1_PAGE3_ACAO04 := 114 
STATIC DEFINE TABCONTROL1_PAGE3_DATAR := 116 
STATIC DEFINE TABCONTROL1_PAGE3_DIST01 := 117 
STATIC DEFINE TABCONTROL1_PAGE3_DIST02 := 118 
STATIC DEFINE TABCONTROL1_PAGE3_FT20 := 103 
STATIC DEFINE TABCONTROL1_PAGE3_GB3 := 104 
STATIC DEFINE TABCONTROL1_PAGE3_LAUDO := 119 
STATIC DEFINE TABCONTROL1_PAGE3_OBS01 := 108 
STATIC DEFINE TABCONTROL1_PAGE3_OBS02 := 109 
STATIC DEFINE TABCONTROL1_PAGE3_RB12 := 106 
STATIC DEFINE TABCONTROL1_PAGE3_RB13 := 107 
STATIC DEFINE TABCONTROL1_PAGE3_RBG3 := 105 
STATIC DEFINE TABCONTROL1_PAGE3_REFDOC := 115 
STATIC DEFINE TABCONTROL1_PAGE3_RESP := 110 
STATIC DEFINE TABCONTROL1_PAGE3_SC_DATAR := 102 
STATIC DEFINE TABCONTROL1_PAGE3_SC_OBS01 := 100 
STATIC DEFINE TABCONTROL1_PAGE3_SC_RESP := 101 
STATIC DEFINE TABCONTROL1_PAGE4_CALC := 132 
STATIC DEFINE TABCONTROL1_PAGE4_CNQ := 100 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT25 := 116 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT26 := 117 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT27 := 118 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT28 := 119 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT29 := 155 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT30 := 156 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT31 := 136 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT32 := 131 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT33 := 142 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT34 := 144 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT35 := 137 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT37 := 150 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT38 := 152 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT39 := 151 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT40 := 147 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT41 := 121 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT42 := 122 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT43 := 123 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT44 := 124 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT45 := 125 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT46 := 126 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT47 := 127 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT48 := 128 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT49 := 159 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT50 := 166 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT51 := 165 
STATIC DEFINE TABCONTROL1_PAGE4_FIXEDTEXT52 := 164 
STATIC DEFINE TABCONTROL1_PAGE4_GROUPBOX1 := 115 
STATIC DEFINE TABCONTROL1_PAGE4_GROUPBOX2 := 120 
STATIC DEFINE TABCONTROL1_PAGE4_GROUPBOX3 := 153 
STATIC DEFINE TABCONTROL1_PAGE4_GROUPBOX4 := 129 
STATIC DEFINE TABCONTROL1_PAGE4_GROUPBOX5 := 157 
STATIC DEFINE TABCONTROL1_PAGE4_GROUPBOX6 := 138 
STATIC DEFINE TABCONTROL1_PAGE4_MATCOD := 113 
STATIC DEFINE TABCONTROL1_PAGE4_MATNOM := 114 
STATIC DEFINE TABCONTROL1_PAGE4_PECSUC := 134 
STATIC DEFINE TABCONTROL1_PAGE4_PEGPRECO := 133 
STATIC DEFINE TABCONTROL1_PAGE4_QTDSUC := 135 
STATIC DEFINE TABCONTROL1_PAGE4_REHDF := 160 
STATIC DEFINE TABCONTROL1_PAGE4_REHDI := 161 
STATIC DEFINE TABCONTROL1_PAGE4_REHHF := 163 
STATIC DEFINE TABCONTROL1_PAGE4_REHHI := 162 
STATIC DEFINE TABCONTROL1_PAGE4_REHTH := 158 
STATIC DEFINE TABCONTROL1_PAGE4_REHVL := 154 
STATIC DEFINE TABCONTROL1_PAGE4_REIDF := 145 
STATIC DEFINE TABCONTROL1_PAGE4_REIDI := 146 
STATIC DEFINE TABCONTROL1_PAGE4_REIHF := 149 
STATIC DEFINE TABCONTROL1_PAGE4_REIHI := 148 
STATIC DEFINE TABCONTROL1_PAGE4_REIQT := 139 
STATIC DEFINE TABCONTROL1_PAGE4_REITH := 143 
STATIC DEFINE TABCONTROL1_PAGE4_REIVL := 141 
STATIC DEFINE TABCONTROL1_PAGE4_RETDF := 110 
STATIC DEFINE TABCONTROL1_PAGE4_RETDI := 108 
STATIC DEFINE TABCONTROL1_PAGE4_RETHF := 109 
STATIC DEFINE TABCONTROL1_PAGE4_RETHI := 107 
STATIC DEFINE TABCONTROL1_PAGE4_RETTH := 111 
STATIC DEFINE TABCONTROL1_PAGE4_RETVL := 112 
STATIC DEFINE TABCONTROL1_PAGE4_SC_REIQT := 140 
STATIC DEFINE TABCONTROL1_PAGE4_SELDF := 104 
STATIC DEFINE TABCONTROL1_PAGE4_SELDI := 102 
STATIC DEFINE TABCONTROL1_PAGE4_SELHF := 103 
STATIC DEFINE TABCONTROL1_PAGE4_SELHI := 101 
STATIC DEFINE TABCONTROL1_PAGE4_SELTH := 105 
STATIC DEFINE TABCONTROL1_PAGE4_SELVL := 106 
STATIC DEFINE TABCONTROL1_PAGE4_VALSUC := 130 
#endregion

PARTIAL CLASS JRNC INHERIT MYDataWindow 

	PROTECT oDBRNC AS DataColumn
	PROTECT oDBDATA AS DataColumn
	PROTECT oDBFECDATA AS DataColumn
	PROTECT oDBNRACF AS DataColumn
	PROTECT oDBNSAC AS DataColumn
	PROTECT oDCCODRNC AS RADIOBUTTONGROUP
	PROTECT oDCRNC AS SINGLELINEEDIT
	PROTECT oCCRB3 AS RADIOBUTTON
	PROTECT oCCRB4 AS RADIOBUTTON
	PROTECT oCCRB1 AS RADIOBUTTON
	PROTECT oCCRB2 AS RADIOBUTTON
	PROTECT oCCExcluir AS PUSHBUTTON
	PROTECT oCCIncluir AS PUSHBUTTON
	PROTECT oDCSC_CODIGO1 AS FIXEDTEXT
	PROTECT oDCTabControl1 AS TABCONTROL
	PROTECT oTPTABCONTROL1_PAGE1 AS TABCONTROL1_PAGE1
	PROTECT oTPTABCONTROL1_PAGE2 AS TABCONTROL1_PAGE2
	PROTECT oTPTABCONTROL1_PAGE3 AS TABCONTROL1_PAGE3
	PROTECT oTPTABCONTROL1_PAGE4 AS TABCONTROL1_PAGE4
	PROTECT oCCProximo AS PUSHBUTTON
	PROTECT oCCAnterior AS PUSHBUTTON
	PROTECT oCCescsetcod AS PUSHBUTTON
	PROTECT oCCesccoderr AS PUSHBUTTON
	PROTECT oDCFixedText1 AS FIXEDTEXT
	PROTECT oDCFixedText2 AS FIXEDTEXT
	PROTECT oDCDATA AS SINGLELINEEDIT
	PROTECT oDCFECDATA AS SINGLELINEEDIT
	PROTECT oDCNRACF AS SINGLELINEEDIT
	PROTECT oDCNSAC AS SINGLELINEEDIT
	PROTECT oDCFixedText4 AS FIXEDTEXT
	PROTECT oDCNAOCONF AS SINGLELINEEDIT
	PROTECT oDCFixedText5 AS FIXEDTEXT
	PROTECT oCCcmdgrvnc AS PUSHBUTTON
	PROTECT oCCVERSAC AS PUSHBUTTON
	PROTECT oCCBuscanum AS PUSHBUTTON
	PROTECT oCCPORNUM AS PUSHBUTTON
// 	instance CODRNC 
// 	instance RNC 
// 	instance DATA 
// 	instance FECDATA 
// 	instance NRACF 
// 	instance NSAC 
// 	instance NAOCONF 
	PROTECT oSFJRNCI AS JRNCI

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS CODRNC() 
RETURN SELF:FieldGet(#CODRNC)


ASSIGN CODRNC(uValue) 
SELF:FieldPut(#CODRNC, uValue)
RETURN CODRNC := uValue


ACCESS DATA() 
RETURN SELF:FieldGet(#DATA)


ASSIGN DATA(uValue) 
SELF:FieldPut(#DATA, uValue)
RETURN DATA := uValue


ACCESS FECDATA() 
RETURN SELF:FieldGet(#FECDATA)


ASSIGN FECDATA(uValue) 
SELF:FieldPut(#FECDATA, uValue)
RETURN FECDATA := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  
LOCAL DIM aFonts[2] AS OBJECT
LOCAL DIM aBrushes[1] AS OBJECT

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"JRNC",_GetInst()},iCtlID)

aFonts[1] := Font{,12,"Times New Roman"}
aFonts[1]:Bold := TRUE
aFonts[2] := Font{,10,"Times New Roman"}
aFonts[2]:Bold := TRUE
aBrushes[1] := Brush{Color{255,255,200}}

oDCRNC := SingleLineEdit{SELF,ResourceID{JRNC_RNC,_GetInst()}}
oDCRNC:FieldSpec := padrao_num_08{}
oDCRNC:HyperLabel := HyperLabel{#RNC,"Rnc:",NULL_STRING,"RNC_RNC"}
oDCRNC:BackGround := aBrushes[1]
oDCRNC:Font(aFonts[1], FALSE)

oCCRB3 := RadioButton{SELF,ResourceID{JRNC_RB3,_GetInst()}}
oCCRB3:HyperLabel := HyperLabel{#RB3,"Final",NULL_STRING,NULL_STRING}

oCCRB4 := RadioButton{SELF,ResourceID{JRNC_RB4,_GetInst()}}
oCCRB4:HyperLabel := HyperLabel{#RB4,"Cliente",NULL_STRING,NULL_STRING}

oCCRB1 := RadioButton{SELF,ResourceID{JRNC_RB1,_GetInst()}}
oCCRB1:HyperLabel := HyperLabel{#RB1,"Recebimento",NULL_STRING,NULL_STRING}

oCCRB2 := RadioButton{SELF,ResourceID{JRNC_RB2,_GetInst()}}
oCCRB2:HyperLabel := HyperLabel{#RB2,"Processo",NULL_STRING,NULL_STRING}

oCCExcluir := PushButton{SELF,ResourceID{JRNC_EXCLUIR,_GetInst()}}
oCCExcluir:HyperLabel := HyperLabel{#Excluir,"Excluir",NULL_STRING,NULL_STRING}

oCCIncluir := PushButton{SELF,ResourceID{JRNC_INCLUIR,_GetInst()}}
oCCIncluir:HyperLabel := HyperLabel{#Incluir,"Incluir",NULL_STRING,NULL_STRING}

oDCSC_CODIGO1 := FixedText{SELF,ResourceID{JRNC_SC_CODIGO1,_GetInst()}}
oDCSC_CODIGO1:HyperLabel := HyperLabel{#SC_CODIGO1,"RNC",NULL_STRING,NULL_STRING}

oDCTabControl1 := TabControl{SELF,ResourceID{JRNC_TABCONTROL1,_GetInst()}}
oDCTabControl1:HyperLabel := HyperLabel{#TabControl1,"Registro de Não Conformidade",NULL_STRING,NULL_STRING}

oCCProximo := PushButton{SELF,ResourceID{JRNC_PROXIMO,_GetInst()}}
oCCProximo:HyperLabel := HyperLabel{#Proximo,"Próximo",NULL_STRING,NULL_STRING}
oCCProximo:Image := ico_next{}

oCCAnterior := PushButton{SELF,ResourceID{JRNC_ANTERIOR,_GetInst()}}
oCCAnterior:HyperLabel := HyperLabel{#Anterior,"Anterior",NULL_STRING,NULL_STRING}
oCCAnterior:Image := ico_previous{}

oCCescsetcod := PushButton{SELF,ResourceID{JRNC_ESCSETCOD,_GetInst()}}
oCCescsetcod:HyperLabel := HyperLabel{#escsetcod,"Setor",NULL_STRING,NULL_STRING}

oCCesccoderr := PushButton{SELF,ResourceID{JRNC_ESCCODERR,_GetInst()}}
oCCesccoderr:HyperLabel := HyperLabel{#esccoderr,"Erro",NULL_STRING,NULL_STRING}

oDCFixedText1 := FixedText{SELF,ResourceID{JRNC_FIXEDTEXT1,_GetInst()}}
oDCFixedText1:HyperLabel := HyperLabel{#FixedText1,"Abertura",NULL_STRING,NULL_STRING}

oDCFixedText2 := FixedText{SELF,ResourceID{JRNC_FIXEDTEXT2,_GetInst()}}
oDCFixedText2:HyperLabel := HyperLabel{#FixedText2,"Fechamento",NULL_STRING,NULL_STRING}

oDCDATA := SingleLineEdit{SELF,ResourceID{JRNC_DATA,_GetInst()}}
oDCDATA:FieldSpec := date_field{}
oDCDATA:HyperLabel := HyperLabel{#DATA,"Data",NULL_STRING,"RNC_RNC"}
oDCDATA:BackGround := aBrushes[1]
oDCDATA:Font(aFonts[2], FALSE)

oDCFECDATA := SingleLineEdit{SELF,ResourceID{JRNC_FECDATA,_GetInst()}}
oDCFECDATA:FieldSpec := date_field{}
oDCFECDATA:HyperLabel := HyperLabel{#FECDATA,"Fech.",NULL_STRING,"RNC_RNC"}
oDCFECDATA:Font(aFonts[2], FALSE)
oDCFECDATA:BackGround := aBrushes[1]

oDCNRACF := SingleLineEdit{SELF,ResourceID{JRNC_NRACF,_GetInst()}}
oDCNRACF:FieldSpec := padrao_num_08{}
oDCNRACF:HyperLabel := HyperLabel{#NRACF,"Racf",NULL_STRING,NULL_STRING}
oDCNRACF:BackGround := aBrushes[1]
oDCNRACF:Font(aFonts[2], FALSE)

oDCNSAC := SingleLineEdit{SELF,ResourceID{JRNC_NSAC,_GetInst()}}
oDCNSAC:FieldSpec := padrao_num_08{}
oDCNSAC:HyperLabel := HyperLabel{#NSAC,"Sac",NULL_STRING,NULL_STRING}
oDCNSAC:BackGround := aBrushes[1]
oDCNSAC:Font(aFonts[2], FALSE)

oDCFixedText4 := FixedText{SELF,ResourceID{JRNC_FIXEDTEXT4,_GetInst()}}
oDCFixedText4:HyperLabel := HyperLabel{#FixedText4,"RACF",NULL_STRING,NULL_STRING}

oDCNAOCONF := SingleLineEdit{SELF,ResourceID{JRNC_NAOCONF,_GetInst()}}
oDCNAOCONF:FieldSpec := PADRAO_NUM_08{}
oDCNAOCONF:HyperLabel := HyperLabel{#NAOCONF,NULL_STRING,NULL_STRING,NULL_STRING}

oDCFixedText5 := FixedText{SELF,ResourceID{JRNC_FIXEDTEXT5,_GetInst()}}
oDCFixedText5:HyperLabel := HyperLabel{#FixedText5,"Qtde Nao Conforme",NULL_STRING,NULL_STRING}

oCCcmdgrvnc := PushButton{SELF,ResourceID{JRNC_CMDGRVNC,_GetInst()}}
oCCcmdgrvnc:HyperLabel := HyperLabel{#cmdgrvnc,"<---",NULL_STRING,NULL_STRING}

oCCVERSAC := PushButton{SELF,ResourceID{JRNC_VERSAC,_GetInst()}}
oCCVERSAC:HyperLabel := HyperLabel{#VERSAC,"SAC",NULL_STRING,NULL_STRING}

oCCBuscanum := PushButton{SELF,ResourceID{JRNC_BUSCANUM,_GetInst()}}
oCCBuscanum:Image := ico_find{}
oCCBuscanum:HyperLabel := HyperLabel{#Buscanum,NULL_STRING,NULL_STRING,NULL_STRING}

oCCPORNUM := PushButton{SELF,ResourceID{JRNC_PORNUM,_GetInst()}}
oCCPORNUM:Image := ico_az{}
oCCPORNUM:HyperLabel := HyperLabel{#PORNUM,NULL_STRING,NULL_STRING,NULL_STRING}

oDCCODRNC := RadioButtonGroup{SELF,ResourceID{JRNC_CODRNC,_GetInst()}}
oDCCODRNC:FillUsing({ ;
						{oCCRB3,"F"}, ;
						{oCCRB4,"C"}, ;
						{oCCRB1,"R"}, ;
						{oCCRB2,"P"} ;
						})
oDCCODRNC:HyperLabel := HyperLabel{#CODRNC,"Tipo de Não Conformidade",NULL_STRING,NULL_STRING}
oDCCODRNC:FieldSpec := padrao_char_01{}

SELF:Caption := "Registro de Não Conformidade"
SELF:HyperLabel := HyperLabel{#JRNC,"Registro de Não Conformidade",NULL_STRING,NULL_STRING}
SELF:Menu := STANDARDSHELLMENU{}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ENDIF
SELF:Browser := DataBrowser{SELF}

oDBRNC := DataColumn{padrao_num_08{}}
oDBRNC:Width := 11
oDBRNC:HyperLabel := oDCRNC:HyperLabel 
oDBRNC:Caption := "Rnc:"
oDBRNC:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBRNC)

oDBDATA := DataColumn{date_field{}}
oDBDATA:Width := 13
oDBDATA:HyperLabel := oDCDATA:HyperLabel 
oDBDATA:Caption := "Data"
oDBDATA:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBDATA)

oDBFECDATA := DataColumn{date_field{}}
oDBFECDATA:Width := 9
oDBFECDATA:HyperLabel := oDCFECDATA:HyperLabel 
oDBFECDATA:Caption := "Fech."
oDBFECDATA:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBFECDATA)

oDBNRACF := DataColumn{padrao_num_08{}}
oDBNRACF:Width := 11
oDBNRACF:HyperLabel := oDCNRACF:HyperLabel 
oDBNRACF:Caption := "Racf"
oDBNRACF:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBNRACF)

oDBNSAC := DataColumn{padrao_num_08{}}
oDBNSAC:Width := 11
oDBNSAC:HyperLabel := oDCNSAC:HyperLabel 
oDBNSAC:Caption := "Sac"
oDBNSAC:BackGround := aBrushes[1]
SELF:Browser:AddColumn(oDBNSAC)


SELF:ViewAs(#FormView)

oSFJRNCI := JRNCI{SELF,JRNC_JRNCI}
oSFJRNCI:show()
oTPTABCONTROL1_PAGE1 := TABCONTROL1_PAGE1{SELF, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE1,"A",oTPTABCONTROL1_PAGE1,0)
oTPTABCONTROL1_PAGE2 := TABCONTROL1_PAGE2{SELF, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE2,"B",oTPTABCONTROL1_PAGE2,0)
oTPTABCONTROL1_PAGE3 := TABCONTROL1_PAGE3{SELF, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE3,"C",oTPTABCONTROL1_PAGE3,0)
oTPTABCONTROL1_PAGE4 := TABCONTROL1_PAGE4{SELF, 0}
oDCTabControl1:AppendTab(#TABCONTROL1_PAGE4,"D",oTPTABCONTROL1_PAGE4,0)
oDCTabControl1:SelectTab(#TABCONTROL1_PAGE1)

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS LAUDO() 
RETURN SELF:FieldGet(#LAUDO)


ACCESS NAOCONF() 
RETURN SELF:FieldGet(#NAOCONF)


ASSIGN NAOCONF(uValue) 
SELF:FieldPut(#NAOCONF, uValue)
RETURN NAOCONF := uValue


ACCESS NRACF() 
RETURN SELF:FieldGet(#NRACF)


ASSIGN NRACF(uValue) 
SELF:FieldPut(#NRACF, uValue)
RETURN NRACF := uValue


ACCESS NSAC() 
RETURN SELF:FieldGet(#NSAC)


ASSIGN NSAC(uValue) 
SELF:FieldPut(#NSAC, uValue)
RETURN NSAC := uValue


METHOD PORNUM( ) 
	SELF:KeyFind()

ACCESS RNC() 
RETURN SELF:FieldGet(#RNC)


ASSIGN RNC(uValue) 
SELF:FieldPut(#RNC, uValue)
RETURN RNC := uValue


END CLASS
PARTIAL CLASS TabControl1_Page1 INHERIT DATAWINDOW
PROTECT oDCSC_QTL2 AS FIXEDTEXT
PROTECT oDCSC_QTL AS FIXEDTEXT
PROTECT oDCFT26 AS FIXEDTEXT
PROTECT oDCSC_NFC AS FIXEDTEXT
PROTECT oDCSC_NOME AS FIXEDTEXT
PROTECT oDCSC_PED AS FIXEDTEXT
PROTECT oDCSC_NFIC AS FIXEDTEXT
PROTECT oDCSC_SETOR1 AS FIXEDTEXT
PROTECT oDCSC_SETOR AS FIXEDTEXT
PROTECT oDCSC_OFC AS FIXEDTEXT
PROTECT oDCSC_RASTRO AS FIXEDTEXT
PROTECT oDCSC_REVI AS FIXEDTEXT
PROTECT oDCSC_DESCRI AS FIXEDTEXT
PROTECT oDCSC_CODIGO AS FIXEDTEXT
PROTECT oDCSC_RIC AS FIXEDTEXT
PROTECT oDCTIPCAD AS RADIOBUTTONGROUP
PROTECT oCCRB16 AS RADIOBUTTON
PROTECT oCCRB15 AS RADIOBUTTON
PROTECT oDCTIPERR AS RADIOBUTTONGROUP
PROTECT oCCRB17 AS RADIOBUTTON
PROTECT oCCRB18 AS RADIOBUTTON
PROTECT oDCCODIGO AS SINGLELINEEDIT
PROTECT oDCDESCRI AS SINGLELINEEDIT
PROTECT oDCREVI AS SINGLELINEEDIT
PROTECT oDCRASTRO AS SINGLELINEEDIT
PROTECT oDCOFC AS SINGLELINEEDIT
PROTECT oDCSETOR AS SINGLELINEEDIT
PROTECT oDCNFIC AS SINGLELINEEDIT
PROTECT oDCPED AS SINGLELINEEDIT
PROTECT oDCCLIFOR AS rightSle
PROTECT oDCNOME AS SINGLELINEEDIT
PROTECT oDCNFC AS SINGLELINEEDIT
PROTECT oDCRIC AS SINGLELINEEDIT
PROTECT oDCUNID AS SINGLELINEEDIT
PROTECT oDCABRNOM AS SINGLELINEEDIT
PROTECT oDCABRNUM AS rightSle
PROTECT oDCQTL AS SINGLELINEEDIT
PROTECT oDCQTLN AS SINGLELINEEDIT
PROTECT oCCESCRES AS PUSHBUTTON
PROTECT oCCESCFOR AS PUSHBUTTON
PROTECT oCCesccod AS PUSHBUTTON
PROTECT oCCbtnpegms01 AS PUSHBUTTON
PROTECT oCCbtnpegma01 AS PUSHBUTTON
PROTECT oCCbtnpegmp04 AS PUSHBUTTON
PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
PROTECT oCCfoto AS PUSHBUTTON

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS ABRNOM
RETURN SELF:FieldGet( #ABRNOM )

ASSIGN ABRNOM( uValue )
SELF:FieldPut( #ABRNOM , uValue )

ACCESS ABRNUM
RETURN SELF:FieldGet( #ABRNUM )

ASSIGN ABRNUM( uValue )
SELF:FieldPut( #ABRNUM , uValue )

ACCESS CLIFOR
RETURN SELF:FieldGet( #CLIFOR )

ASSIGN CLIFOR( uValue )
SELF:FieldPut( #CLIFOR , uValue )

ACCESS CODIGO
RETURN SELF:FieldGet( #CODIGO )

ASSIGN CODIGO( uValue )
SELF:FieldPut( #CODIGO , uValue )

ACCESS DESCRI
RETURN SELF:FieldGet( #DESCRI )

ASSIGN DESCRI( uValue )
SELF:FieldPut( #DESCRI , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"TabControl1_Page1" , _GetInst()},iCtlID)

	SELF:oDCSC_QTL2 := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_QTL2  , _GetInst() } }
	SELF:oDCSC_QTL2:HyperLabel := HyperLabel{#SC_QTL2 , "Qtde Lote n/c:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTL := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_QTL  , _GetInst() } }
	SELF:oDCSC_QTL:HyperLabel := HyperLabel{#SC_QTL , "Qtde Lote:" , NULL_STRING , NULL_STRING}

	SELF:oDCFT26 := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_FT26  , _GetInst() } }
	SELF:oDCFT26:HyperLabel := HyperLabel{#FT26 , "Unid." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NFC := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_NFC  , _GetInst() } }
	SELF:oDCSC_NFC:HyperLabel := HyperLabel{#SC_NFC , "Nota Fiscal Cliente/Fornecedor" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_NOME  , _GetInst() } }
	SELF:oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME , "Cliente/Fornecedor" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PED := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_PED  , _GetInst() } }
	SELF:oDCSC_PED:HyperLabel := HyperLabel{#SC_PED , "Pedido No.:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NFIC := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_NFIC  , _GetInst() } }
	SELF:oDCSC_NFIC:HyperLabel := HyperLabel{#SC_NFIC , "NF Itaesbra" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SETOR1 := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_SETOR1  , _GetInst() } }
	SELF:oDCSC_SETOR1:HyperLabel := HyperLabel{#SC_SETOR1 , "Aberto Por" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SETOR := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_SETOR  , _GetInst() } }
	SELF:oDCSC_SETOR:HyperLabel := HyperLabel{#SC_SETOR , "Setor:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_OFC := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_OFC  , _GetInst() } }
	SELF:oDCSC_OFC:HyperLabel := HyperLabel{#SC_OFC , "O.F." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RASTRO := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_RASTRO  , _GetInst() } }
	SELF:oDCSC_RASTRO:HyperLabel := HyperLabel{#SC_RASTRO , "Rastro:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_REVI := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_REVI  , _GetInst() } }
	SELF:oDCSC_REVI:HyperLabel := HyperLabel{#SC_REVI , "Revisão:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESCRI := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_DESCRI  , _GetInst() } }
	SELF:oDCSC_DESCRI:HyperLabel := HyperLabel{#SC_DESCRI , "Descrição:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CODIGO := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_CODIGO  , _GetInst() } }
	SELF:oDCSC_CODIGO:HyperLabel := HyperLabel{#SC_CODIGO , "Codigo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RIC := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_RIC  , _GetInst() } }
	SELF:oDCSC_RIC:HyperLabel := HyperLabel{#SC_RIC , "Relatório /Inspeção Cliente" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPCAD := RADIOBUTTONGROUP{SELF , ResourceID{ TABCONTROL1_PAGE1_TIPCAD  , _GetInst() } }
	SELF:oDCTIPCAD:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPCAD:HyperLabel := HyperLabel{#TIPCAD , "Tipo" , NULL_STRING , NULL_STRING}

	SELF:oCCRB16 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_RB16  , _GetInst() } }
	SELF:oCCRB16:HyperLabel := HyperLabel{#RB16 , "Fornecedor" , NULL_STRING , NULL_STRING}

	SELF:oCCRB15 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_RB15  , _GetInst() } }
	SELF:oCCRB15:HyperLabel := HyperLabel{#RB15 , "Cliente" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPERR := RADIOBUTTONGROUP{SELF , ResourceID{ TABCONTROL1_PAGE1_TIPERR  , _GetInst() } }
	SELF:oDCTIPERR:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPERR:HyperLabel := HyperLabel{#TIPERR , "Tipo do Erro" , NULL_STRING , NULL_STRING}

	SELF:oCCRB17 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_RB17  , _GetInst() } }
	SELF:oCCRB17:HyperLabel := HyperLabel{#RB17 , "Interno" , NULL_STRING , NULL_STRING}

	SELF:oCCRB18 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_RB18  , _GetInst() } }
	SELF:oCCRB18:HyperLabel := HyperLabel{#RB18 , "Externo" , NULL_STRING , NULL_STRING}

	SELF:oDCCODIGO := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_CODIGO  , _GetInst() } }
	SELF:oDCCODIGO:FieldSpec := PADRAO_CHAR_24{}
	SELF:oDCCODIGO:HyperLabel := HyperLabel{#CODIGO , "Codigo:" , NULL_STRING , "RNC_CODIGO"}

	SELF:oDCDESCRI := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_DESCRI  , _GetInst() } }
	SELF:oDCDESCRI:FieldSpec := PADRAO_CHAR_30{}
	SELF:oDCDESCRI:HyperLabel := HyperLabel{#DESCRI , "Descri:" , NULL_STRING , "RNC_DESCRI"}

	SELF:oDCREVI := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_REVI  , _GetInst() } }
	SELF:oDCREVI:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCREVI:HyperLabel := HyperLabel{#REVI , "Revi:" , NULL_STRING , "RNC_REVI"}

	SELF:oDCRASTRO := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_RASTRO  , _GetInst() } }
	SELF:oDCRASTRO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCRASTRO:HyperLabel := HyperLabel{#RASTRO , "Rastro:" , NULL_STRING , "RNC_RASTRO"}

	SELF:oDCOFC := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_OFC  , _GetInst() } }
	SELF:oDCOFC:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCOFC:HyperLabel := HyperLabel{#OFC , "Ofc:" , NULL_STRING , "RNC_OFC"}

	SELF:oDCSETOR := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_SETOR  , _GetInst() } }
	SELF:oDCSETOR:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCSETOR:HyperLabel := HyperLabel{#SETOR , "Setor:" , NULL_STRING , "RNC_SETOR"}

	SELF:oDCNFIC := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_NFIC  , _GetInst() } }
	SELF:oDCNFIC:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCNFIC:HyperLabel := HyperLabel{#NFIC , "Nfic:" , NULL_STRING , "RNC_NFIC"}

	SELF:oDCPED := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_PED  , _GetInst() } }
	SELF:oDCPED:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCPED:HyperLabel := HyperLabel{#PED , "Ped:" , NULL_STRING , "RNC_PED"}

	SELF:oDCCLIFOR := rightSle{SELF , ResourceID{ TABCONTROL1_PAGE1_CLIFOR  , _GetInst() } }
	SELF:oDCCLIFOR:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCCLIFOR:HyperLabel := HyperLabel{#CLIFOR , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCNOME := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_NOME  , _GetInst() } }
	SELF:oDCNOME:FieldSpec := PADRAO_CHAR_50{}
	SELF:oDCNOME:HyperLabel := HyperLabel{#NOME , "Nome:" , NULL_STRING , "RNC_NOME"}

	SELF:oDCNFC := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_NFC  , _GetInst() } }
	SELF:oDCNFC:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCNFC:HyperLabel := HyperLabel{#NFC , "Nfc:" , NULL_STRING , "RNC_NFC"}

	SELF:oDCRIC := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_RIC  , _GetInst() } }
	SELF:oDCRIC:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCRIC:HyperLabel := HyperLabel{#RIC , "Ric:" , NULL_STRING , "RNC_RIC"}

	SELF:oDCUNID := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_UNID  , _GetInst() } }
	SELF:oDCUNID:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCUNID:HyperLabel := HyperLabel{#UNID , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCABRNOM := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_ABRNOM  , _GetInst() } }
	SELF:oDCABRNOM:FieldSpec := PADRAO_CHAR_30{}
	SELF:oDCABRNOM:HyperLabel := HyperLabel{#ABRNOM , "Abrnom:" , NULL_STRING , "RNC_ABRNOM"}

	SELF:oDCABRNUM := rightSle{SELF , ResourceID{ TABCONTROL1_PAGE1_ABRNUM  , _GetInst() } }
	SELF:oDCABRNUM:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCABRNUM:HyperLabel := HyperLabel{#ABRNUM , "Abrnum:" , NULL_STRING , "RNC_ABRNUM"}

	SELF:oDCQTL := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_QTL  , _GetInst() } }
	SELF:oDCQTL:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTL:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCQTL:Font( oFont )
	SELF:oDCQTL:HyperLabel := HyperLabel{#QTL , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oDCQTLN := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE1_QTLN  , _GetInst() } }
	SELF:oDCQTLN:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTLN:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCQTLN:Font( oFont )
	SELF:oDCQTLN:HyperLabel := HyperLabel{#QTLN , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oCCESCRES := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_ESCRES  , _GetInst() } }
	SELF:oCCESCRES:HyperLabel := HyperLabel{#ESCRES , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCESCFOR := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_ESCFOR  , _GetInst() } }
	SELF:oCCESCFOR:HyperLabel := HyperLabel{#ESCFOR , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCesccod := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_ESCCOD  , _GetInst() } }
	SELF:oCCesccod:HyperLabel := HyperLabel{#esccod , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCbtnpegms01 := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_BTNPEGMS01  , _GetInst() } }
	SELF:oCCbtnpegms01:HyperLabel := HyperLabel{#btnpegms01 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnpegma01 := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_BTNPEGMA01  , _GetInst() } }
	SELF:oCCbtnpegma01:HyperLabel := HyperLabel{#btnpegma01 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnpegmp04 := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_BTNPEGMP04  , _GetInst() } }
	SELF:oCCbtnpegmp04:HyperLabel := HyperLabel{#btnpegmp04 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO2 := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE1_SC_DESTINO2  , _GetInst() } }
	SELF:oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2 , "Foto" , NULL_STRING , NULL_STRING}

	SELF:oCCfoto := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE1_FOTO  , _GetInst() } }
	SELF:oCCfoto:Image := ico_camera{}
	SELF:oCCfoto:HyperLabel := HyperLabel{#foto , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCTIPCAD:FillUsing({ ;
	                         {SELF:oCCRB16, "F"}, ;
	                         {SELF:oCCRB15, "C"} ;
	                         })

	SELF:oDCTIPERR:FillUsing({ ;
	                         {SELF:oCCRB17, "I"}, ;
	                         {SELF:oCCRB18, "E"} ;
	                         })

	SELF:Caption := "Basico"
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#TabControl1_Page1 , "Basico" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ELSE
		SELF:Use(SELF:Owner:Server)
	ENDIF


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NFC
RETURN SELF:FieldGet( #NFC )

ASSIGN NFC( uValue )
SELF:FieldPut( #NFC , uValue )

ACCESS NFIC
RETURN SELF:FieldGet( #NFIC )

ASSIGN NFIC( uValue )
SELF:FieldPut( #NFIC , uValue )

ACCESS NOME
RETURN SELF:FieldGet( #NOME )

ASSIGN NOME( uValue )
SELF:FieldPut( #NOME , uValue )

ACCESS OFC
RETURN SELF:FieldGet( #OFC )

ASSIGN OFC( uValue )
SELF:FieldPut( #OFC , uValue )

ACCESS PED
RETURN SELF:FieldGet( #PED )

ASSIGN PED( uValue )
SELF:FieldPut( #PED , uValue )

ACCESS QTL
RETURN SELF:FieldGet( #QTL )

ASSIGN QTL( uValue )
SELF:FieldPut( #QTL , uValue )

ACCESS QTLN
RETURN SELF:FieldGet( #QTLN )

ASSIGN QTLN( uValue )
SELF:FieldPut( #QTLN , uValue )

ACCESS RASTRO
RETURN SELF:FieldGet( #RASTRO )

ASSIGN RASTRO( uValue )
SELF:FieldPut( #RASTRO , uValue )

ACCESS REVI
RETURN SELF:FieldGet( #REVI )

ASSIGN REVI( uValue )
SELF:FieldPut( #REVI , uValue )

ACCESS RIC
RETURN SELF:FieldGet( #RIC )

ASSIGN RIC( uValue )
SELF:FieldPut( #RIC , uValue )

ACCESS SETOR
RETURN SELF:FieldGet( #SETOR )

ASSIGN SETOR( uValue )
SELF:FieldPut( #SETOR , uValue )

ACCESS TIPCAD
RETURN SELF:FieldGet( #TIPCAD )

ASSIGN TIPCAD( uValue )
SELF:FieldPut( #TIPCAD , uValue )

ACCESS TIPERR
RETURN SELF:FieldGet( #TIPERR )

ASSIGN TIPERR( uValue )
SELF:FieldPut( #TIPERR , uValue )

ACCESS UNID
RETURN SELF:FieldGet( #UNID )

ASSIGN UNID( uValue )
SELF:FieldPut( #UNID , uValue )

END CLASS
PARTIAL CLASS TabControl1_Page2 INHERIT DATAWINDOW
PROTECT oCCRB23 AS RADIOBUTTON
PROTECT oCCRB22 AS RADIOBUTTON
PROTECT oCCRB21 AS RADIOBUTTON
PROTECT oCCRB20 AS RADIOBUTTON
PROTECT oCCRB19 AS RADIOBUTTON
PROTECT oDCCODRET AS RADIOBUTTONGROUP
PROTECT oDCCARGO AS SINGLELINEEDIT
PROTECT oDCRESPO AS SINGLELINEEDIT
PROTECT oDCDEC01 AS SINGLELINEEDIT
PROTECT oDCDEC02 AS SINGLELINEEDIT
PROTECT oDCDEC03 AS SINGLELINEEDIT
PROTECT oDCDATAD AS DATETIMEPICKER
PROTECT oDCGB1 AS GROUPBOX
PROTECT oDCFT28 AS FIXEDTEXT
PROTECT oDCFT27 AS FIXEDTEXT
PROTECT oDCFT29 AS FIXEDTEXT
PROTECT oDCAREA AS COMBOBOX
PROTECT oDCNRACF AS SINGLELINEEDIT
PROTECT oCCcriaRACF AS PUSHBUTTON
PROTECT oDCNSAC AS SINGLELINEEDIT
PROTECT oCCcriaSAC AS PUSHBUTTON
PROTECT oDCRAC AS SINGLELINEEDIT
PROTECT oDCFT30 AS FIXEDTEXT
PROTECT oDCSC_DATAD AS FIXEDTEXT
PROTECT oCCRB7 AS RADIOBUTTON
PROTECT oCCRB9 AS RADIOBUTTON
PROTECT oCCRB6 AS RADIOBUTTON
PROTECT oDCDISPO AS RADIOBUTTONGROUP
PROTECT oCCRB14 AS RADIOBUTTON
PROTECT oCCRB8 AS RADIOBUTTON
PROTECT oCCRB5 AS RADIOBUTTON
PROTECT oCCRB10 AS RADIOBUTTON
PROTECT oCCOutros AS RADIOBUTTON

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS AREA
RETURN SELF:FieldGet( #AREA )

ASSIGN AREA( uValue )
SELF:FieldPut( #AREA , uValue )

ACCESS CARGO
RETURN SELF:FieldGet( #CARGO )

ASSIGN CARGO( uValue )
SELF:FieldPut( #CARGO , uValue )

ACCESS CODRET
RETURN SELF:FieldGet( #CODRET )

ASSIGN CODRET( uValue )
SELF:FieldPut( #CODRET , uValue )

ACCESS DEC01
RETURN SELF:FieldGet( #DEC01 )

ASSIGN DEC01( uValue )
SELF:FieldPut( #DEC01 , uValue )

ACCESS DEC02
RETURN SELF:FieldGet( #DEC02 )

ASSIGN DEC02( uValue )
SELF:FieldPut( #DEC02 , uValue )

ACCESS DEC03
RETURN SELF:FieldGet( #DEC03 )

ASSIGN DEC03( uValue )
SELF:FieldPut( #DEC03 , uValue )

ACCESS DISPO
RETURN SELF:FieldGet( #DISPO )

ASSIGN DISPO( uValue )
SELF:FieldPut( #DISPO , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"TabControl1_Page2" , _GetInst()},iCtlID)

	SELF:oCCRB23 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB23  , _GetInst() } }
	SELF:oCCRB23:HyperLabel := HyperLabel{#RB23 , "Aprovado Condicional" , NULL_STRING , NULL_STRING}

	SELF:oCCRB22 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB22  , _GetInst() } }
	SELF:oCCRB22:HyperLabel := HyperLabel{#RB22 , "Retrabalho" , NULL_STRING , NULL_STRING}

	SELF:oCCRB21 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB21  , _GetInst() } }
	SELF:oCCRB21:HyperLabel := HyperLabel{#RB21 , "Sucata" , NULL_STRING , NULL_STRING}

	SELF:oCCRB20 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB20  , _GetInst() } }
	SELF:oCCRB20:HyperLabel := HyperLabel{#RB20 , "Dev. Sucata" , NULL_STRING , NULL_STRING}

	SELF:oCCRB19 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB19  , _GetInst() } }
	SELF:oCCRB19:HyperLabel := HyperLabel{#RB19 , "Dev.Retrabalho" , NULL_STRING , NULL_STRING}

	SELF:oDCCODRET := RADIOBUTTONGROUP{SELF , ResourceID{ TABCONTROL1_PAGE2_CODRET  , _GetInst() } }
	SELF:oDCCODRET:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCCODRET:HyperLabel := HyperLabel{#CODRET , "Tipo" , NULL_STRING , NULL_STRING}

	SELF:oDCCARGO := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE2_CARGO  , _GetInst() } }
	SELF:oDCCARGO:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCCARGO:HyperLabel := HyperLabel{#CARGO , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCRESPO := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE2_RESPO  , _GetInst() } }
	SELF:oDCRESPO:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCRESPO:HyperLabel := HyperLabel{#RESPO , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCDEC01 := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE2_DEC01  , _GetInst() } }
	SELF:oDCDEC01:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC01:HyperLabel := HyperLabel{#DEC01 , "Dec01:" , NULL_STRING , "RNC_DEC01"}

	SELF:oDCDEC02 := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE2_DEC02  , _GetInst() } }
	SELF:oDCDEC02:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC02:HyperLabel := HyperLabel{#DEC02 , "Dec02:" , NULL_STRING , "RNC_DEC02"}

	SELF:oDCDEC03 := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE2_DEC03  , _GetInst() } }
	SELF:oDCDEC03:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC03:HyperLabel := HyperLabel{#DEC03 , "Dec03:" , NULL_STRING , "RNC_DEC03"}

	SELF:oDCDATAD := DATETIMEPICKER{SELF , ResourceID{ TABCONTROL1_PAGE2_DATAD  , _GetInst() } }
	SELF:oDCDATAD:FieldSpec := DATE_FIELD{}
	SELF:oDCDATAD:HyperLabel := HyperLabel{#DATAD , "11/04/2018" , NULL_STRING , NULL_STRING}

	SELF:oDCGB1 := GROUPBOX{SELF , ResourceID{ TABCONTROL1_PAGE2_GB1  , _GetInst() } }
	SELF:oDCGB1:HyperLabel := HyperLabel{#GB1 , "Descrição do Problema" , NULL_STRING , NULL_STRING}

	SELF:oDCFT28 := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE2_FT28  , _GetInst() } }
	SELF:oDCFT28:HyperLabel := HyperLabel{#FT28 , "Cargo" , NULL_STRING , NULL_STRING}

	SELF:oDCFT27 := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE2_FT27  , _GetInst() } }
	SELF:oDCFT27:HyperLabel := HyperLabel{#FT27 , "Responsável" , NULL_STRING , NULL_STRING}

	SELF:oDCFT29 := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE2_FT29  , _GetInst() } }
	SELF:oDCFT29:HyperLabel := HyperLabel{#FT29 , "Área" , NULL_STRING , NULL_STRING}

	SELF:oDCAREA := COMBOBOX{SELF , ResourceID{ TABCONTROL1_PAGE2_AREA  , _GetInst() } }
	SELF:oDCAREA:FillUsing( SELF:comboPEGMP05() )
	SELF:oDCAREA:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCAREA:HyperLabel := HyperLabel{#AREA , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCNRACF := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE2_NRACF  , _GetInst() } }
	SELF:oDCNRACF:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNRACF:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCNRACF:Font( oFont )
	SELF:oDCNRACF:HyperLabel := HyperLabel{#NRACF , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCcriaRACF := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_CRIARACF  , _GetInst() } }
	SELF:oCCcriaRACF:HyperLabel := HyperLabel{#criaRACF , "RACF" , NULL_STRING , NULL_STRING}

	SELF:oDCNSAC := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE2_NSAC  , _GetInst() } }
	SELF:oDCNSAC:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNSAC:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCNSAC:Font( oFont )
	SELF:oDCNSAC:HyperLabel := HyperLabel{#NSAC , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCcriaSAC := PUSHBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_CRIASAC  , _GetInst() } }
	SELF:oCCcriaSAC:HyperLabel := HyperLabel{#criaSAC , "Sac" , NULL_STRING , NULL_STRING}

	SELF:oDCRAC := SINGLELINEEDIT{SELF , ResourceID{ TABCONTROL1_PAGE2_RAC  , _GetInst() } }
	SELF:oDCRAC:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCRAC:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 10 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCRAC:Font( oFont )
	SELF:oDCRAC:HyperLabel := HyperLabel{#RAC , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCFT30 := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE2_FT30  , _GetInst() } }
	SELF:oDCFT30:HyperLabel := HyperLabel{#FT30 , "Requer Ação Sim Não" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATAD := FIXEDTEXT{SELF , ResourceID{ TABCONTROL1_PAGE2_SC_DATAD  , _GetInst() } }
	SELF:oDCSC_DATAD:HyperLabel := HyperLabel{#SC_DATAD , "Data:" , NULL_STRING , NULL_STRING}

	SELF:oCCRB7 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB7  , _GetInst() } }
	SELF:oCCRB7:HyperLabel := HyperLabel{#RB7 , "Sucatar" , NULL_STRING , NULL_STRING}

	SELF:oCCRB9 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB9  , _GetInst() } }
	SELF:oCCRB9:HyperLabel := HyperLabel{#RB9 , "Devolver ao Fornecedor" , NULL_STRING , NULL_STRING}

	SELF:oCCRB6 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB6  , _GetInst() } }
	SELF:oCCRB6:HyperLabel := HyperLabel{#RB6 , "Aprovar Condicional" , NULL_STRING , NULL_STRING}

	SELF:oDCDISPO := RADIOBUTTONGROUP{SELF , ResourceID{ TABCONTROL1_PAGE2_DISPO  , _GetInst() } }
	SELF:oDCDISPO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCDISPO:HyperLabel := HyperLabel{#DISPO , "Disposição" , NULL_STRING , NULL_STRING}

	SELF:oCCRB14 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB14  , _GetInst() } }
	SELF:oCCRB14:HyperLabel := HyperLabel{#RB14 , "Seleção" , NULL_STRING , NULL_STRING}

	SELF:oCCRB8 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB8  , _GetInst() } }
	SELF:oCCRB8:HyperLabel := HyperLabel{#RB8 , "Solicitar Aprovaçào com Desvios" , NULL_STRING , NULL_STRING}

	SELF:oCCRB5 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB5  , _GetInst() } }
	SELF:oCCRB5:HyperLabel := HyperLabel{#RB5 , "Retrabalhar" , NULL_STRING , NULL_STRING}

	SELF:oCCRB10 := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_RB10  , _GetInst() } }
	SELF:oCCRB10:HyperLabel := HyperLabel{#RB10 , "Devolucao do Cliente" , NULL_STRING , NULL_STRING}

	SELF:oCCOutros := RADIOBUTTON{SELF , ResourceID{ TABCONTROL1_PAGE2_OUTROS  , _GetInst() } }
	SELF:oCCOutros:HyperLabel := HyperLabel{#Outros , "Outros" , NULL_STRING , NULL_STRING}

	SELF:oDCCODRET:FillUsing({ ;
	                         {SELF:oCCRB23, "A"}, ;
	                         {SELF:oCCRB22, "R"}, ;
	                         {SELF:oCCRB21, "S"}, ;
	                         {SELF:oCCRB20, "E"}, ;
	                         {SELF:oCCRB19, "D"}, ;
	                         {SELF:oCCOutros, "Outros"} ;
	                         })

	SELF:oDCDISPO:FillUsing({ ;
	                        {SELF:oCCRB7, "U"}, ;
	                        {SELF:oCCRB9, "D"}, ;
	                        {SELF:oCCRB6, "A"}, ;
	                        {SELF:oCCRB14, "E"}, ;
	                        {SELF:oCCRB8, "S"}, ;
	                        {SELF:oCCRB5, "R"}, ;
	                        {SELF:oCCRB10, "C"} ;
	                        })

	SELF:Caption := "DataWindow Caption"
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#TabControl1_Page2 , "DataWindow Caption" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ELSE
		SELF:Use(SELF:Owner:Server)
	ENDIF


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NRACF
RETURN SELF:FieldGet( #NRACF )

ASSIGN NRACF( uValue )
SELF:FieldPut( #NRACF , uValue )

ACCESS NSAC
RETURN SELF:FieldGet( #NSAC )

ASSIGN NSAC( uValue )
SELF:FieldPut( #NSAC , uValue )

ACCESS RAC
RETURN SELF:FieldGet( #RAC )

ASSIGN RAC( uValue )
SELF:FieldPut( #RAC , uValue )

ACCESS RESPO
RETURN SELF:FieldGet( #RESPO )

ASSIGN RESPO( uValue )
SELF:FieldPut( #RESPO , uValue )

END CLASS
CLASS TabControl1_Page3 INHERIT DATAWINDOW 

	PROTECT oDCSC_OBS01 AS FIXEDTEXT
	PROTECT oDCSC_RESP AS FIXEDTEXT
	PROTECT oDCSC_DATAR AS FIXEDTEXT
	PROTECT oDCFT20 AS FIXEDTEXT
	PROTECT oDCGB3 AS GROUPBOX
	PROTECT oDCRBG3 AS RADIOBUTTONGROUP
	PROTECT oCCRB12 AS RADIOBUTTON
	PROTECT oCCRB13 AS RADIOBUTTON
	PROTECT oDCOBS01 AS SINGLELINEEDIT
	PROTECT oDCOBS02 AS SINGLELINEEDIT
	PROTECT oDCRESP AS SINGLELINEEDIT
	PROTECT oDCACAO01 AS SINGLELINEEDIT
	PROTECT oDCACAO02 AS SINGLELINEEDIT
	PROTECT oDCACAO03 AS SINGLELINEEDIT
	PROTECT oDCACAO04 AS SINGLELINEEDIT
	PROTECT oDCREFDOC AS SINGLELINEEDIT
	PROTECT oDCDATAR AS DATETIMEPICKER
	PROTECT oDCDIST01 AS SINGLELINEEDIT
	PROTECT oDCDIST02 AS SINGLELINEEDIT
	PROTECT oDCLAUDO AS RADIOBUTTONGROUP
// 	instance RBG3 
// 	instance OBS01 
// 	instance OBS02 
// 	instance RESP 
// 	instance ACAO01 
// 	instance ACAO02 
// 	instance ACAO03 
// 	instance ACAO04 
// 	instance REFDOC 
// 	instance DIST01 
// 	instance DIST02 
// 	instance LAUDO 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

ACCESS ACAO01() 
RETURN SELF:FieldGet(#ACAO01)


ASSIGN ACAO01(uValue) 
SELF:FieldPut(#ACAO01, uValue)
RETURN ACAO01 := uValue


ACCESS ACAO02() 
RETURN SELF:FieldGet(#ACAO02)


ASSIGN ACAO02(uValue) 
SELF:FieldPut(#ACAO02, uValue)
RETURN ACAO02 := uValue


ACCESS ACAO03() 
RETURN SELF:FieldGet(#ACAO03)


ASSIGN ACAO03(uValue) 
SELF:FieldPut(#ACAO03, uValue)
RETURN ACAO03 := uValue


ACCESS ACAO04() 
RETURN SELF:FieldGet(#ACAO04)


ASSIGN ACAO04(uValue) 
SELF:FieldPut(#ACAO04, uValue)
RETURN ACAO04 := uValue


ACCESS DIST01() 
RETURN SELF:FieldGet(#DIST01)


ASSIGN DIST01(uValue) 
SELF:FieldPut(#DIST01, uValue)
RETURN DIST01 := uValue


ACCESS DIST02() 
RETURN SELF:FieldGet(#DIST02)


ASSIGN DIST02(uValue) 
SELF:FieldPut(#DIST02, uValue)
RETURN DIST02 := uValue


CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabControl1_Page3",_GetInst()},iCtlID)

oDCSC_OBS01 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE3_SC_OBS01,_GetInst()}}
oDCSC_OBS01:HyperLabel := HyperLabel{#SC_OBS01,"Observação",NULL_STRING,NULL_STRING}

oDCSC_RESP := FixedText{SELF,ResourceID{TABCONTROL1_PAGE3_SC_RESP,_GetInst()}}
oDCSC_RESP:HyperLabel := HyperLabel{#SC_RESP,"Responsável pela Não Conformidade:",NULL_STRING,NULL_STRING}

oDCSC_DATAR := FixedText{SELF,ResourceID{TABCONTROL1_PAGE3_SC_DATAR,_GetInst()}}
oDCSC_DATAR:HyperLabel := HyperLabel{#SC_DATAR,"Data:",NULL_STRING,NULL_STRING}

oDCFT20 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE3_FT20,_GetInst()}}
oDCFT20:HyperLabel := HyperLabel{#FT20,"Referente ao Documento",NULL_STRING,NULL_STRING}

oDCGB3 := GroupBox{SELF,ResourceID{TABCONTROL1_PAGE3_GB3,_GetInst()}}
oDCGB3:HyperLabel := HyperLabel{#GB3,"Distruibuição de Cópias Para",NULL_STRING,NULL_STRING}

oCCRB12 := RadioButton{SELF,ResourceID{TABCONTROL1_PAGE3_RB12,_GetInst()}}
oCCRB12:HyperLabel := HyperLabel{#RB12,"Satisfatório",NULL_STRING,NULL_STRING}

oCCRB13 := RadioButton{SELF,ResourceID{TABCONTROL1_PAGE3_RB13,_GetInst()}}
oCCRB13:HyperLabel := HyperLabel{#RB13,"Insatisfatório",NULL_STRING,NULL_STRING}

oDCOBS01 := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_OBS01,_GetInst()}}
oDCOBS01:FieldSpec := PADRAO_CHAR_100{}
oDCOBS01:HyperLabel := HyperLabel{#OBS01,"Obs01:",NULL_STRING,"RNC_OBS01"}

oDCOBS02 := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_OBS02,_GetInst()}}
oDCOBS02:FieldSpec := PADRAO_CHAR_100{}
oDCOBS02:HyperLabel := HyperLabel{#OBS02,"Obs02:",NULL_STRING,"RNC_OBS02"}

oDCRESP := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_RESP,_GetInst()}}
oDCRESP:FieldSpec := PADRAO_CHAR_30{}
oDCRESP:HyperLabel := HyperLabel{#RESP,"RACF",NULL_STRING,"RNC_RESP"}

oDCACAO01 := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_ACAO01,_GetInst()}}
oDCACAO01:FieldSpec := PADRAO_CHAR_60{}
oDCACAO01:HyperLabel := HyperLabel{#ACAO01,"Acao01:",NULL_STRING,"RNC_ACAO01"}

oDCACAO02 := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_ACAO02,_GetInst()}}
oDCACAO02:FieldSpec := PADRAO_CHAR_60{}
oDCACAO02:HyperLabel := HyperLabel{#ACAO02,"Acao02:",NULL_STRING,"RNC_ACAO02"}

oDCACAO03 := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_ACAO03,_GetInst()}}
oDCACAO03:FieldSpec := PADRAO_CHAR_60{}
oDCACAO03:HyperLabel := HyperLabel{#ACAO03,"Acao03:",NULL_STRING,"RNC_ACAO03"}

oDCACAO04 := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_ACAO04,_GetInst()}}
oDCACAO04:FieldSpec := PADRAO_CHAR_60{}
oDCACAO04:HyperLabel := HyperLabel{#ACAO04,"Acao04:",NULL_STRING,"RNC_ACAO04"}

oDCREFDOC := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_REFDOC,_GetInst()}}
oDCREFDOC:FieldSpec := PADRAO_CHAR_15{}
oDCREFDOC:HyperLabel := HyperLabel{#REFDOC,NULL_STRING,NULL_STRING,NULL_STRING}

oDCDATAR := DateTimePicker{SELF,ResourceID{TABCONTROL1_PAGE3_DATAR,_GetInst()}}
oDCDATAR:FieldSpec := DATE_FIELD{}
oDCDATAR:HyperLabel := HyperLabel{#DATAR,NULL_STRING,NULL_STRING,NULL_STRING}

oDCDIST01 := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_DIST01,_GetInst()}}
oDCDIST01:FieldSpec := PADRAO_CHAR_60{}
oDCDIST01:HyperLabel := HyperLabel{#DIST01,"Dist01:",NULL_STRING,"RNC_DIST01"}

oDCDIST02 := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE3_DIST02,_GetInst()}}
oDCDIST02:FieldSpec := PADRAO_CHAR_60{}
oDCDIST02:HyperLabel := HyperLabel{#DIST02,"Dist02:",NULL_STRING,"RNC_DIST02"}

oDCRBG3 := RadioButtonGroup{SELF,ResourceID{TABCONTROL1_PAGE3_RBG3,_GetInst()}}
oDCRBG3:HyperLabel := HyperLabel{#RBG3,"Açòes a serem Tomadas/Responsáveis/Prazos:(instruções)         ",NULL_STRING,NULL_STRING}

oDCLAUDO := RadioButtonGroup{SELF,ResourceID{TABCONTROL1_PAGE3_LAUDO,_GetInst()}}
oDCLAUDO:FillUsing({ ;
						{oCCRB12,"S"}, ;
						{oCCRB13,"I"} ;
						})
oDCLAUDO:HyperLabel := HyperLabel{#LAUDO,"Laudo",NULL_STRING,NULL_STRING}
oDCLAUDO:FieldSpec := PADRAO_CHAR_01{}

SELF:Caption := "DataWindow Caption"
SELF:HyperLabel := HyperLabel{#TabControl1_Page3,"DataWindow Caption",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS LAUDO() 
RETURN SELF:FieldGet(#LAUDO)


ASSIGN LAUDO(uValue) 
SELF:FieldPut(#LAUDO, uValue)
RETURN LAUDO := uValue


ACCESS OBS01() 
RETURN SELF:FieldGet(#OBS01)


ASSIGN OBS01(uValue) 
SELF:FieldPut(#OBS01, uValue)
RETURN OBS01 := uValue


ACCESS OBS02() 
RETURN SELF:FieldGet(#OBS02)


ASSIGN OBS02(uValue) 
SELF:FieldPut(#OBS02, uValue)
RETURN OBS02 := uValue


ACCESS RBG3() 
RETURN SELF:FieldGet(#RBG3)


ASSIGN RBG3(uValue) 
SELF:FieldPut(#RBG3, uValue)
RETURN RBG3 := uValue


ACCESS REFDOC() 
RETURN SELF:FieldGet(#REFDOC)


ASSIGN REFDOC(uValue) 
SELF:FieldPut(#REFDOC, uValue)
RETURN REFDOC := uValue


ACCESS RESP() 
RETURN SELF:FieldGet(#RESP)


ASSIGN RESP(uValue) 
SELF:FieldPut(#RESP, uValue)
RETURN RESP := uValue


END CLASS
PARTIAL CLASS TabControl1_Page4 INHERIT DATAWINDOW 

	PROTECT oCCCNQ AS PUSHBUTTON
	PROTECT oDCSELHI AS RIGHTSLE
	PROTECT oDCSELDI AS DATESLE
	PROTECT oDCSELHF AS RIGHTSLE
	PROTECT oDCSELDF AS DATESLE
	PROTECT oDCSELTH AS RIGHTSLE
	PROTECT oDCSELVL AS RIGHTSLE
	PROTECT oDCRETHI AS RIGHTSLE
	PROTECT oDCRETDI AS DATESLE
	PROTECT oDCRETHF AS RIGHTSLE
	PROTECT oDCRETDF AS DATESLE
	PROTECT oDCRETTH AS RIGHTSLE
	PROTECT oDCRETVL AS RIGHTSLE
	PROTECT oDCMATCOD AS SINGLELINEEDIT
	PROTECT oDCMATNOM AS SINGLELINEEDIT
	PROTECT oDCGroupBox1 AS GROUPBOX
	PROTECT oDCFixedText25 AS FIXEDTEXT
	PROTECT oDCFixedText26 AS FIXEDTEXT
	PROTECT oDCFixedText27 AS FIXEDTEXT
	PROTECT oDCFixedText28 AS FIXEDTEXT
	PROTECT oDCGroupBox2 AS GROUPBOX
	PROTECT oDCFixedText41 AS FIXEDTEXT
	PROTECT oDCFixedText42 AS FIXEDTEXT
	PROTECT oDCFixedText43 AS FIXEDTEXT
	PROTECT oDCFixedText44 AS FIXEDTEXT
	PROTECT oDCFixedText45 AS FIXEDTEXT
	PROTECT oDCFixedText46 AS FIXEDTEXT
	PROTECT oDCFixedText47 AS FIXEDTEXT
	PROTECT oDCFixedText48 AS FIXEDTEXT
	PROTECT oDCGroupBox4 AS GROUPBOX
	PROTECT oDCVALSUC AS RIGHTSLE
	PROTECT oDCFixedText32 AS FIXEDTEXT
	PROTECT oCCCalc AS PUSHBUTTON
	PROTECT oCCPegPreco AS PUSHBUTTON
	PROTECT oDCPECSUC AS RIGHTSLE
	PROTECT oDCQTDSUC AS RIGHTSLE
	PROTECT oDCFixedText31 AS FIXEDTEXT
	PROTECT oDCFixedText35 AS FIXEDTEXT
	PROTECT oDCGroupBox6 AS GROUPBOX
	PROTECT oDCREIQT AS RIGHTSLE
	PROTECT oDCSC_REIQT AS FIXEDTEXT
	PROTECT oDCREIVL AS RIGHTSLE
	PROTECT oDCFixedText33 AS FIXEDTEXT
	PROTECT oDCREITH AS RIGHTSLE
	PROTECT oDCFixedText34 AS FIXEDTEXT
	PROTECT oDCREIDF AS DATESLE
	PROTECT oDCREIDI AS DATESLE
	PROTECT oDCFixedText40 AS FIXEDTEXT
	PROTECT oDCREIHI AS RIGHTSLE
	PROTECT oDCREIHF AS RIGHTSLE
	PROTECT oDCFixedText37 AS FIXEDTEXT
	PROTECT oDCFixedText39 AS FIXEDTEXT
	PROTECT oDCFixedText38 AS FIXEDTEXT
	PROTECT oDCGroupBox3 AS GROUPBOX
	PROTECT oDCREHVL AS RIGHTSLE
	PROTECT oDCFixedText29 AS FIXEDTEXT
	PROTECT oDCFixedText30 AS FIXEDTEXT
	PROTECT oDCGroupBox5 AS GROUPBOX
	PROTECT oDCREHTH AS RIGHTSLE
	PROTECT oDCFixedText49 AS FIXEDTEXT
	PROTECT oDCREHDF AS DATESLE
	PROTECT oDCREHDI AS DATESLE
	PROTECT oDCREHHI AS RIGHTSLE
	PROTECT oDCREHHF AS RIGHTSLE
	PROTECT oDCFixedText52 AS FIXEDTEXT
	PROTECT oDCFixedText51 AS FIXEDTEXT
	PROTECT oDCFixedText50 AS FIXEDTEXT
// 	instance SELHI 
// 	instance SELDI 
// 	instance SELHF 
// 	instance SELDF 
// 	instance SELTH 
// 	instance SELVL 
// 	instance RETHI 
// 	instance RETDI 
// 	instance RETHF 
// 	instance RETDF 
// 	instance RETTH 
// 	instance RETVL 
// 	instance MATCOD 
// 	instance MATNOM 
// 	instance VALSUC 
// 	instance PECSUC 
// 	instance QTDSUC 
// 	instance REIQT 
// 	instance REIVL 
// 	instance REITH 
// 	instance REIDF 
// 	instance REIDI 
// 	instance REIHI 
// 	instance REIHF 
// 	instance REHVL 
// 	instance REHTH 
// 	instance REHDF 
// 	instance REHDI 
// 	instance REHHI 
// 	instance REHHF 

  //{{%UC%}} USER CODE STARTS HERE (do NOT remove this line)

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)  

SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

SUPER(oWindow,ResourceID{"TabControl1_Page4",_GetInst()},iCtlID)

oCCCNQ := PushButton{SELF,ResourceID{TABCONTROL1_PAGE4_CNQ,_GetInst()}}
oCCCNQ:HyperLabel := HyperLabel{#CNQ,"Ver CNQ",NULL_STRING,NULL_STRING}

oDCSELHI := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_SELHI,_GetInst()}}
oDCSELHI:FieldSpec := PADRAO_NUM_05_2{}
oDCSELHI:HyperLabel := HyperLabel{#SELHI,"Selhi:",NULL_STRING,"RNC_SELHI"}

oDCSELDI := DateSle{SELF,ResourceID{TABCONTROL1_PAGE4_SELDI,_GetInst()}}
oDCSELDI:FieldSpec := DATE_FIELD{}
oDCSELDI:HyperLabel := HyperLabel{#SELDI,"Seldi:",NULL_STRING,"RNC_SELDI"}

oDCSELHF := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_SELHF,_GetInst()}}
oDCSELHF:FieldSpec := PADRAO_NUM_05_2{}
oDCSELHF:HyperLabel := HyperLabel{#SELHF,"Selhf:",NULL_STRING,"RNC_SELHF"}

oDCSELDF := DateSle{SELF,ResourceID{TABCONTROL1_PAGE4_SELDF,_GetInst()}}
oDCSELDF:FieldSpec := DATE_FIELD{}
oDCSELDF:HyperLabel := HyperLabel{#SELDF,"Seldf:",NULL_STRING,"RNC_SELDF"}

oDCSELTH := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_SELTH,_GetInst()}}
oDCSELTH:FieldSpec := PADRAO_NUM_12_2{}
oDCSELTH:HyperLabel := HyperLabel{#SELTH,"Selth:",NULL_STRING,"RNC_SELTH"}

oDCSELVL := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_SELVL,_GetInst()}}
oDCSELVL:FieldSpec := PADRAO_NUM_12_2{}
oDCSELVL:HyperLabel := HyperLabel{#SELVL,"Selvl:",NULL_STRING,"RNC_SELVL"}

oDCRETHI := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_RETHI,_GetInst()}}
oDCRETHI:FieldSpec := PADRAO_NUM_05_2{}
oDCRETHI:HyperLabel := HyperLabel{#RETHI,"Rethi:",NULL_STRING,"RNC_RETHI"}

oDCRETDI := DateSle{SELF,ResourceID{TABCONTROL1_PAGE4_RETDI,_GetInst()}}
oDCRETDI:FieldSpec := DATE_FIELD{}
oDCRETDI:HyperLabel := HyperLabel{#RETDI,"Retdi:",NULL_STRING,"RNC_RETDI"}

oDCRETHF := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_RETHF,_GetInst()}}
oDCRETHF:FieldSpec := PADRAO_NUM_05_2{}
oDCRETHF:HyperLabel := HyperLabel{#RETHF,"Rethf:",NULL_STRING,"RNC_RETHF"}

oDCRETDF := DateSle{SELF,ResourceID{TABCONTROL1_PAGE4_RETDF,_GetInst()}}
oDCRETDF:FieldSpec := DATE_FIELD{}
oDCRETDF:HyperLabel := HyperLabel{#RETDF,"Retdf:",NULL_STRING,"RNC_RETDF"}

oDCRETTH := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_RETTH,_GetInst()}}
oDCRETTH:FieldSpec := PADRAO_NUM_12_2{}
oDCRETTH:HyperLabel := HyperLabel{#RETTH,"Retth:",NULL_STRING,"RNC_RETTH"}

oDCRETVL := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_RETVL,_GetInst()}}
oDCRETVL:FieldSpec := PADRAO_NUM_12_2{}
oDCRETVL:HyperLabel := HyperLabel{#RETVL,"Retvl:",NULL_STRING,"RNC_RETVL"}

oDCMATCOD := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE4_MATCOD,_GetInst()}}
oDCMATCOD:FieldSpec := PADRAO_CHAR_20{}
oDCMATCOD:HyperLabel := HyperLabel{#MATCOD,"Matcod:",NULL_STRING,"RNC_MATCOD"}

oDCMATNOM := SingleLineEdit{SELF,ResourceID{TABCONTROL1_PAGE4_MATNOM,_GetInst()}}
oDCMATNOM:FieldSpec := PADRAO_CHAR_40{}
oDCMATNOM:HyperLabel := HyperLabel{#MATNOM,"Matnom:",NULL_STRING,"RNC_MATNOM"}

oDCGroupBox1 := GroupBox{SELF,ResourceID{TABCONTROL1_PAGE4_GROUPBOX1,_GetInst()}}
oDCGroupBox1:HyperLabel := HyperLabel{#GroupBox1,"Seleção",NULL_STRING,NULL_STRING}

oDCFixedText25 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT25,_GetInst()}}
oDCFixedText25:HyperLabel := HyperLabel{#FixedText25,"Valor",NULL_STRING,NULL_STRING}

oDCFixedText26 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT26,_GetInst()}}
oDCFixedText26:HyperLabel := HyperLabel{#FixedText26,"Total Horas",NULL_STRING,NULL_STRING}

oDCFixedText27 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT27,_GetInst()}}
oDCFixedText27:HyperLabel := HyperLabel{#FixedText27,"Valor",NULL_STRING,NULL_STRING}

oDCFixedText28 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT28,_GetInst()}}
oDCFixedText28:HyperLabel := HyperLabel{#FixedText28,"Total Horas",NULL_STRING,NULL_STRING}

oDCGroupBox2 := GroupBox{SELF,ResourceID{TABCONTROL1_PAGE4_GROUPBOX2,_GetInst()}}
oDCGroupBox2:HyperLabel := HyperLabel{#GroupBox2,"Retrabalho Maquina",NULL_STRING,NULL_STRING}

oDCFixedText41 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT41,_GetInst()}}
oDCFixedText41:HyperLabel := HyperLabel{#FixedText41,"Hora",NULL_STRING,NULL_STRING}

oDCFixedText42 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT42,_GetInst()}}
oDCFixedText42:HyperLabel := HyperLabel{#FixedText42,"Data",NULL_STRING,NULL_STRING}

oDCFixedText43 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT43,_GetInst()}}
oDCFixedText43:HyperLabel := HyperLabel{#FixedText43,"Final",NULL_STRING,NULL_STRING}

oDCFixedText44 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT44,_GetInst()}}
oDCFixedText44:HyperLabel := HyperLabel{#FixedText44,"Inicial",NULL_STRING,NULL_STRING}

oDCFixedText45 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT45,_GetInst()}}
oDCFixedText45:HyperLabel := HyperLabel{#FixedText45,"Final",NULL_STRING,NULL_STRING}

oDCFixedText46 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT46,_GetInst()}}
oDCFixedText46:HyperLabel := HyperLabel{#FixedText46,"Inicial",NULL_STRING,NULL_STRING}

oDCFixedText47 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT47,_GetInst()}}
oDCFixedText47:HyperLabel := HyperLabel{#FixedText47,"Data",NULL_STRING,NULL_STRING}

oDCFixedText48 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT48,_GetInst()}}
oDCFixedText48:HyperLabel := HyperLabel{#FixedText48,"Hora",NULL_STRING,NULL_STRING}

oDCGroupBox4 := GroupBox{SELF,ResourceID{TABCONTROL1_PAGE4_GROUPBOX4,_GetInst()}}
oDCGroupBox4:HyperLabel := HyperLabel{#GroupBox4,"Material",NULL_STRING,NULL_STRING}

oDCVALSUC := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_VALSUC,_GetInst()}}
oDCVALSUC:FieldSpec := PADRAO_NUM_12_2{}
oDCVALSUC:HyperLabel := HyperLabel{#VALSUC,"Retvl:",NULL_STRING,"RNC_RETVL"}

oDCFixedText32 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT32,_GetInst()}}
oDCFixedText32:HyperLabel := HyperLabel{#FixedText32,"Total",NULL_STRING,NULL_STRING}

oCCCalc := PushButton{SELF,ResourceID{TABCONTROL1_PAGE4_CALC,_GetInst()}}
oCCCalc:HyperLabel := HyperLabel{#Calc,"Calcular",NULL_STRING,NULL_STRING}

oCCPegPreco := PushButton{SELF,ResourceID{TABCONTROL1_PAGE4_PEGPRECO,_GetInst()}}
oCCPegPreco:HyperLabel := HyperLabel{#PegPreco,"Preço",NULL_STRING,NULL_STRING}

oDCPECSUC := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_PECSUC,_GetInst()}}
oDCPECSUC:FieldSpec := PADRAO_NUM_12_4{}
oDCPECSUC:HyperLabel := HyperLabel{#PECSUC,"Retvl:",NULL_STRING,"RNC_RETVL"}

oDCQTDSUC := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_QTDSUC,_GetInst()}}
oDCQTDSUC:FieldSpec := PADRAO_NUM_08{}
oDCQTDSUC:HyperLabel := HyperLabel{#QTDSUC,"Retvl:",NULL_STRING,"RNC_RETVL"}

oDCFixedText31 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT31,_GetInst()}}
oDCFixedText31:HyperLabel := HyperLabel{#FixedText31,"Preço",NULL_STRING,NULL_STRING}

oDCFixedText35 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT35,_GetInst()}}
oDCFixedText35:HyperLabel := HyperLabel{#FixedText35,"Qtde",NULL_STRING,NULL_STRING}

oDCGroupBox6 := GroupBox{SELF,ResourceID{TABCONTROL1_PAGE4_GROUPBOX6,_GetInst()}}
oDCGroupBox6:HyperLabel := HyperLabel{#GroupBox6,"Sucata",NULL_STRING,NULL_STRING}

oDCREIQT := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REIQT,_GetInst()}}
oDCREIQT:FieldSpec := PADRAO_NUM_08{}
oDCREIQT:HyperLabel := HyperLabel{#REIQT,"Reiqt:",NULL_STRING,"RNC_REIQT"}

oDCSC_REIQT := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_SC_REIQT,_GetInst()}}
oDCSC_REIQT:HyperLabel := HyperLabel{#SC_REIQT,"QTde",NULL_STRING,NULL_STRING}

oDCREIVL := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REIVL,_GetInst()}}
oDCREIVL:FieldSpec := PADRAO_NUM_12_2{}
oDCREIVL:HyperLabel := HyperLabel{#REIVL,"Reivl:",NULL_STRING,"RNC_REIVL"}

oDCFixedText33 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT33,_GetInst()}}
oDCFixedText33:HyperLabel := HyperLabel{#FixedText33,"Valor",NULL_STRING,NULL_STRING}

oDCREITH := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REITH,_GetInst()}}
oDCREITH:FieldSpec := PADRAO_NUM_12_2{}
oDCREITH:HyperLabel := HyperLabel{#REITH,"Reith:",NULL_STRING,"RNC_REITH"}

oDCFixedText34 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT34,_GetInst()}}
oDCFixedText34:HyperLabel := HyperLabel{#FixedText34,"Total Horas",NULL_STRING,NULL_STRING}

oDCREIDF := DateSle{SELF,ResourceID{TABCONTROL1_PAGE4_REIDF,_GetInst()}}
oDCREIDF:FieldSpec := DATE_FIELD{}
oDCREIDF:HyperLabel := HyperLabel{#REIDF,"Reidf:",NULL_STRING,"RNC_REIDF"}

oDCREIDI := DateSle{SELF,ResourceID{TABCONTROL1_PAGE4_REIDI,_GetInst()}}
oDCREIDI:FieldSpec := DATE_FIELD{}
oDCREIDI:HyperLabel := HyperLabel{#REIDI,"Reidi:",NULL_STRING,"RNC_REIDI"}

oDCFixedText40 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT40,_GetInst()}}
oDCFixedText40:HyperLabel := HyperLabel{#FixedText40,"Data",NULL_STRING,NULL_STRING}

oDCREIHI := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REIHI,_GetInst()}}
oDCREIHI:FieldSpec := PADRAO_NUM_05_2{}
oDCREIHI:HyperLabel := HyperLabel{#REIHI,"Reihi:",NULL_STRING,"RNC_REIHI"}

oDCREIHF := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REIHF,_GetInst()}}
oDCREIHF:FieldSpec := PADRAO_NUM_05_2{}
oDCREIHF:HyperLabel := HyperLabel{#REIHF,"Reihf:",NULL_STRING,"RNC_REIHF"}

oDCFixedText37 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT37,_GetInst()}}
oDCFixedText37:HyperLabel := HyperLabel{#FixedText37,"Final",NULL_STRING,NULL_STRING}

oDCFixedText39 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT39,_GetInst()}}
oDCFixedText39:HyperLabel := HyperLabel{#FixedText39,"Inicial",NULL_STRING,NULL_STRING}

oDCFixedText38 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT38,_GetInst()}}
oDCFixedText38:HyperLabel := HyperLabel{#FixedText38,"Hora",NULL_STRING,NULL_STRING}

oDCGroupBox3 := GroupBox{SELF,ResourceID{TABCONTROL1_PAGE4_GROUPBOX3,_GetInst()}}
oDCGroupBox3:HyperLabel := HyperLabel{#GroupBox3,"Reinspeção",NULL_STRING,NULL_STRING}

oDCREHVL := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REHVL,_GetInst()}}
oDCREHVL:FieldSpec := PADRAO_NUM_12_2{}
oDCREHVL:HyperLabel := HyperLabel{#REHVL,"Retvl:",NULL_STRING,"RNC_RETVL"}

oDCFixedText29 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT29,_GetInst()}}
oDCFixedText29:HyperLabel := HyperLabel{#FixedText29,"Valor",NULL_STRING,NULL_STRING}

oDCFixedText30 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT30,_GetInst()}}
oDCFixedText30:HyperLabel := HyperLabel{#FixedText30,"Total Horas",NULL_STRING,NULL_STRING}

oDCGroupBox5 := GroupBox{SELF,ResourceID{TABCONTROL1_PAGE4_GROUPBOX5,_GetInst()}}
oDCGroupBox5:HyperLabel := HyperLabel{#GroupBox5,"Retrabalho Operador",NULL_STRING,NULL_STRING}

oDCREHTH := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REHTH,_GetInst()}}
oDCREHTH:FieldSpec := PADRAO_NUM_12_2{}
oDCREHTH:HyperLabel := HyperLabel{#REHTH,"Retth:",NULL_STRING,"RNC_RETTH"}

oDCFixedText49 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT49,_GetInst()}}
oDCFixedText49:HyperLabel := HyperLabel{#FixedText49,"Data",NULL_STRING,NULL_STRING}

oDCREHDF := DateSle{SELF,ResourceID{TABCONTROL1_PAGE4_REHDF,_GetInst()}}
oDCREHDF:FieldSpec := DATE_FIELD{}
oDCREHDF:HyperLabel := HyperLabel{#REHDF,"Retdf:",NULL_STRING,"RNC_RETDF"}

oDCREHDI := DateSle{SELF,ResourceID{TABCONTROL1_PAGE4_REHDI,_GetInst()}}
oDCREHDI:FieldSpec := DATE_FIELD{}
oDCREHDI:HyperLabel := HyperLabel{#REHDI,"Retdi:",NULL_STRING,"RNC_RETDI"}

oDCREHHI := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REHHI,_GetInst()}}
oDCREHHI:FieldSpec := PADRAO_NUM_05_2{}
oDCREHHI:HyperLabel := HyperLabel{#REHHI,"Rethi:",NULL_STRING,"RNC_RETHI"}

oDCREHHF := rightSle{SELF,ResourceID{TABCONTROL1_PAGE4_REHHF,_GetInst()}}
oDCREHHF:FieldSpec := PADRAO_NUM_05_2{}
oDCREHHF:HyperLabel := HyperLabel{#REHHF,"Rethf:",NULL_STRING,"RNC_RETHF"}

oDCFixedText52 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT52,_GetInst()}}
oDCFixedText52:HyperLabel := HyperLabel{#FixedText52,"Final",NULL_STRING,NULL_STRING}

oDCFixedText51 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT51,_GetInst()}}
oDCFixedText51:HyperLabel := HyperLabel{#FixedText51,"Inicial",NULL_STRING,NULL_STRING}

oDCFixedText50 := FixedText{SELF,ResourceID{TABCONTROL1_PAGE4_FIXEDTEXT50,_GetInst()}}
oDCFixedText50:HyperLabel := HyperLabel{#FixedText50,"Hora",NULL_STRING,NULL_STRING}

SELF:Caption := "Retrabalho"
SELF:HyperLabel := HyperLabel{#TabControl1_Page4,"Retrabalho",NULL_STRING,NULL_STRING}
SELF:ClipperKeys := TRUE

IF !IsNil(oServer)
	SELF:Use(oServer)
ELSE
	SELF:Use(SELF:Owner:Server)
ENDIF

SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN SELF


ACCESS MATCOD() 
RETURN SELF:FieldGet(#MATCOD)


ASSIGN MATCOD(uValue) 
SELF:FieldPut(#MATCOD, uValue)
RETURN MATCOD := uValue


ACCESS MATNOM() 
RETURN SELF:FieldGet(#MATNOM)


ASSIGN MATNOM(uValue) 
SELF:FieldPut(#MATNOM, uValue)
RETURN MATNOM := uValue


ACCESS PECSUC() 
RETURN SELF:FieldGet(#PECSUC)


ASSIGN PECSUC(uValue) 
SELF:FieldPut(#PECSUC, uValue)
RETURN PECSUC := uValue


ACCESS QTDSUC() 
RETURN SELF:FieldGet(#QTDSUC)


ASSIGN QTDSUC(uValue) 
SELF:FieldPut(#QTDSUC, uValue)
RETURN QTDSUC := uValue


ACCESS REHDF() 
RETURN SELF:FieldGet(#REHDF)


ASSIGN REHDF(uValue) 
SELF:FieldPut(#REHDF, uValue)
RETURN REHDF := uValue


ACCESS REHDI() 
RETURN SELF:FieldGet(#REHDI)


ASSIGN REHDI(uValue) 
SELF:FieldPut(#REHDI, uValue)
RETURN REHDI := uValue


ACCESS REHHF() 
RETURN SELF:FieldGet(#REHHF)


ASSIGN REHHF(uValue) 
SELF:FieldPut(#REHHF, uValue)
RETURN REHHF := uValue


ACCESS REHHI() 
RETURN SELF:FieldGet(#REHHI)


ASSIGN REHHI(uValue) 
SELF:FieldPut(#REHHI, uValue)
RETURN REHHI := uValue


ACCESS REHTH() 
RETURN SELF:FieldGet(#REHTH)


ASSIGN REHTH(uValue) 
SELF:FieldPut(#REHTH, uValue)
RETURN REHTH := uValue


ACCESS REHVL() 
RETURN SELF:FieldGet(#REHVL)


ASSIGN REHVL(uValue) 
SELF:FieldPut(#REHVL, uValue)
RETURN REHVL := uValue


ACCESS REIDF() 
RETURN SELF:FieldGet(#REIDF)


ASSIGN REIDF(uValue) 
SELF:FieldPut(#REIDF, uValue)
RETURN REIDF := uValue


ACCESS REIDI() 
RETURN SELF:FieldGet(#REIDI)


ASSIGN REIDI(uValue) 
SELF:FieldPut(#REIDI, uValue)
RETURN REIDI := uValue


ACCESS REIHF() 
RETURN SELF:FieldGet(#REIHF)


ASSIGN REIHF(uValue) 
SELF:FieldPut(#REIHF, uValue)
RETURN REIHF := uValue


ACCESS REIHI() 
RETURN SELF:FieldGet(#REIHI)


ASSIGN REIHI(uValue) 
SELF:FieldPut(#REIHI, uValue)
RETURN REIHI := uValue


ACCESS REIQT() 
RETURN SELF:FieldGet(#REIQT)


ASSIGN REIQT(uValue) 
SELF:FieldPut(#REIQT, uValue)
RETURN REIQT := uValue


ACCESS REITH() 
RETURN SELF:FieldGet(#REITH)


ASSIGN REITH(uValue) 
SELF:FieldPut(#REITH, uValue)
RETURN REITH := uValue


ACCESS REIVL() 
RETURN SELF:FieldGet(#REIVL)


ASSIGN REIVL(uValue) 
SELF:FieldPut(#REIVL, uValue)
RETURN REIVL := uValue


ACCESS RETDF() 
RETURN SELF:FieldGet(#RETDF)


ASSIGN RETDF(uValue) 
SELF:FieldPut(#RETDF, uValue)
RETURN RETDF := uValue


ACCESS RETDI() 
RETURN SELF:FieldGet(#RETDI)


ASSIGN RETDI(uValue) 
SELF:FieldPut(#RETDI, uValue)
RETURN RETDI := uValue


ACCESS RETHF() 
RETURN SELF:FieldGet(#RETHF)


ASSIGN RETHF(uValue) 
SELF:FieldPut(#RETHF, uValue)
RETURN RETHF := uValue


ACCESS RETHI() 
RETURN SELF:FieldGet(#RETHI)


ASSIGN RETHI(uValue) 
SELF:FieldPut(#RETHI, uValue)
RETURN RETHI := uValue


ACCESS RETTH() 
RETURN SELF:FieldGet(#RETTH)


ASSIGN RETTH(uValue) 
SELF:FieldPut(#RETTH, uValue)
RETURN RETTH := uValue


ACCESS RETVL() 
RETURN SELF:FieldGet(#RETVL)


ASSIGN RETVL(uValue) 
SELF:FieldPut(#RETVL, uValue)
RETURN RETVL := uValue


ACCESS SELDF() 
RETURN SELF:FieldGet(#SELDF)


ASSIGN SELDF(uValue) 
SELF:FieldPut(#SELDF, uValue)
RETURN SELDF := uValue


ACCESS SELDI() 
RETURN SELF:FieldGet(#SELDI)


ASSIGN SELDI(uValue) 
SELF:FieldPut(#SELDI, uValue)
RETURN SELDI := uValue


ACCESS SELHF() 
RETURN SELF:FieldGet(#SELHF)


ASSIGN SELHF(uValue) 
SELF:FieldPut(#SELHF, uValue)
RETURN SELHF := uValue


ACCESS SELHI() 
RETURN SELF:FieldGet(#SELHI)


ASSIGN SELHI(uValue) 
SELF:FieldPut(#SELHI, uValue)
RETURN SELHI := uValue


ACCESS SELTH() 
RETURN SELF:FieldGet(#SELTH)


ASSIGN SELTH(uValue) 
SELF:FieldPut(#SELTH, uValue)
RETURN SELTH := uValue


ACCESS SELVL() 
RETURN SELF:FieldGet(#SELVL)


ASSIGN SELVL(uValue) 
SELF:FieldPut(#SELVL, uValue)
RETURN SELVL := uValue


ACCESS VALSUC() 
RETURN SELF:FieldGet(#VALSUC)


ASSIGN VALSUC(uValue) 
SELF:FieldPut(#VALSUC, uValue)
RETURN VALSUC := uValue


END CLASS
STATIC DEFINE TABCONTROL1_PAGE1_BTNPEGMS01 := 141
STATIC DEFINE TABCONTROL1_PAGE1_BTNPEGMA01 := 142
STATIC DEFINE TABCONTROL1_PAGE1_BTNPEGMP04 := 143
