PARTIAL CLASS JRNCF
METHOD ALTERAR  
SELF:oSFJRNCI:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJRNCI:Browser:SuspendUpdate()
SELF:oSFJRNCI:SkipPREVIOUS()
IF SELF:oSFJRNCI:Server:BOF
	SELF:oSFJRNCI:SkipNEXT()
ENDIF
SELF:oSFJRNCI:Browser:RestoreUpdate()

METHOD cancelar( ) 
	SELF:endwindow()

METHOD cmdgrvnc( ) 
	 SELF:oSFJRNCI:SERVER:FIELDPUT("QTNC",SELF:oDCNAOCONF:Value)

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RNC","")		

METHOD EditFocusChange(oEditFocusChangeEvent) 
	LOCAL oControl AS Control
//	LOCAL lGotFocus AS LOGIC
	LOCAL aTEC  AS ARRAY
	LOCAL ACOM AS ARRAY
	oControl := IIf(oEditFocusChangeEvent == NULL_OBJECT, NULL_OBJECT, oEditFocusChangeEvent:Control)
    IIf(oEditFocusChangeEvent == NULL_OBJECT, FALSE, oEditFocusChangeEvent:GotFocus)      //lGotFocus :=
	SUPER:EditFocusChange(oEditFocusChangeEvent)
	//Put your changes here
	aCOM:={zMES,zANO,ZEMPRESA}
   DO CASE
      CASE oCONTROL:NAMESYM==#RETOPR
           aTEC:=PEGMP04(SELF:SERVER:RETOPR,ZCURINI,ZCURDIR,ACOM)
           IF aTEC[1]=.T.
              SELF:SERVER:RETNOM:=aTEC[2]
           ENDIF
      CASE oCONTROL:NAMESYM==#RETOP2
           aTEC:=PEGMP04(SELF:SERVER:RETOP2,ZCURINI,ZCURDIR,ACOM)
           IF aTEC[1]=.T.
              SELF:SERVER:RETNO2:=aTEC[2]
           ENDIF
      CASE oCONTROL:NAMESYM==#RETOP3
           aTEC:=PEGMP04(SELF:SERVER:RETOP3,ZCURINI,ZCURDIR,ACOM)
           IF aTEC[1]=.T.
              SELF:SERVER:RETNO3:=aTEC[2]
           ENDIF
	 ENDCASE
RETURN NIL

METHOD esccoderr( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"CRRSERR.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:oSFJRNCI:SERVER:FIELDPUT("CODERR",oESC:CODIGO)
ENDIF	
	

METHOD escrea1() 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("RETOPR",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("RETNOM",oESCMP04:NOME)
ENDIF

METHOD escrea2() 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("RETOP2",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("RETNO2",oESCMP04:NOME)
ENDIF

METHOD escrea3() 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("RETOP3",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("RETNO3",oESCMP04:NOME)
ENDIF

METHOD escsetcod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"CRRSSET.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:oSFJRNCI:SERVER:FIELDPUT("SETCOD",oESC:CODIGO)
ENDIF		

METHOD EXCLUIR 

IF MDG("Apagar Registro") .AND. SELF:oSFJRNCI:server:LockCurrentRecord()
	SELF:oSFJRNCI:SERVER:SUSPENDNOTIFICATION()
    SELF:oSFJRNCI:server:delete()
    SELF:oSFJRNCI:server:unlock()
    SELF:oSFJRNCI:server:skip(-1)
    SELF:oSFJRNCI:SERVER:resetnotification()
    SELF:oSFJRNCI:SERVER:notify(notifydelete)
    SELF:oSFJRNCI:Browser:refresh()
 ENDIF	


METHOD INCLUIR 
LOCAL nRNC AS DWORD	
nRNC:=SELF:SERVER:RNC
SELF:oSFJRNCI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJRNCI:SERVER:APPEND()
SELF:oSFJRNCI:SERVER:RNC:=nRNC
SELF:oSFJRNCI:SERVER:commit()
SELF:oSFJRNCI:SERVER:resetnotification()
SELF:oSFJRNCI:SERVER:notify(notifyappend)
SELF:oSFJRNCI:Browser:refresh()

METHOD ok( ) 
SELF:SERVER:FIELDPUT("FECUSER",ZUSER)
SELF:SERVER:FIELDPUT("FECDATA",ZDATA)
SELF:SERVER:FIELDPUT("FECHADA",.T.)
SELF:endwindow()	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	   FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJRNCI:Browser:SuspendUpdate()
SELF:oSFJRNCI:SkipNext()
IF SELF:oSFJRNCI:Server:Eof
	SELF:oSFJRNCI:SkipPrevious()
ENDIF
SELF:oSFJRNCI:Browser:RestoreUpdate()

METHOD TABULAR  
SELF:oSFJRNCI:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
