#region DEFINES
STATIC DEFINE JRNCFI_ABRNOM := 110
STATIC DEFINE JRNCFI_ABRNUM := 109
STATIC DEFINE JRNCFI_CANCELAR := 140
STATIC DEFINE JRNCFI_CLIFOR := 107
STATIC DEFINE JRNCFI_CODIGO := 100
STATIC DEFINE JRNCFI_CODRET := 127
STATIC DEFINE JRNCFI_DEC01 := 111
STATIC DEFINE JRNCFI_DEC02 := 112
STATIC DEFINE JRNCFI_DEC03 := 113
STATIC DEFINE JRNCFI_DESCRI := 101
STATIC DEFINE JRNCFI_DISPO := 132
STATIC DEFINE JRNCFI_ESCCOD := 138
STATIC DEFINE JRNCFI_ESCFOR := 117
STATIC DEFINE JRNCFI_ESCRES := 116
STATIC DEFINE JRNCFI_FOTO := 144
STATIC DEFINE JRNCFI_GB1 := 114
STATIC DEFINE JRNCFI_NOME := 108
STATIC DEFINE JRNCFI_OFC := 104
STATIC DEFINE JRNCFI_OK := 142
STATIC DEFINE JRNCFI_PEGCLI := 136
STATIC DEFINE JRNCFI_PEGCOD := 137
STATIC DEFINE JRNCFI_PEGMP04 := 135 
STATIC DEFINE JRNCFI_QTL := 105
STATIC DEFINE JRNCFI_QTLN := 106
STATIC DEFINE JRNCFI_RASTRO := 103
STATIC DEFINE JRNCFI_RB14 := 131
STATIC DEFINE JRNCFI_RB17 := 123
STATIC DEFINE JRNCFI_RB18 := 124
STATIC DEFINE JRNCFI_RB21 := 134
STATIC DEFINE JRNCFI_RB22 := 133
STATIC DEFINE JRNCFI_RB6 := 130
STATIC DEFINE JRNCFI_REVI := 102
STATIC DEFINE JRNCFI_SC_CODIGO := 122
STATIC DEFINE JRNCFI_SC_DESCRI := 121
STATIC DEFINE JRNCFI_SC_DESTINO2 := 143
STATIC DEFINE JRNCFI_SC_NOME := 119
STATIC DEFINE JRNCFI_SC_OFC := 129
STATIC DEFINE JRNCFI_SC_QTL2 := 115
STATIC DEFINE JRNCFI_SC_QTL3 := 128
STATIC DEFINE JRNCFI_SC_RASTRO := 126
STATIC DEFINE JRNCFI_SC_REVI := 120
STATIC DEFINE JRNCFI_SC_SETOR1 := 118
STATIC DEFINE JRNCFI_THEFIXEDTEXT11 := 141
STATIC DEFINE JRNCFI_THEFIXEDTEXT9 := 139
STATIC DEFINE JRNCFI_TIPERR := 125
#endregion

PARTIAL CLASS JRNCFI INHERIT DATADIALOG
PROTECT oDCCODIGO AS SINGLELINEEDIT
PROTECT oDCDESCRI AS SINGLELINEEDIT
PROTECT oDCREVI AS SINGLELINEEDIT
PROTECT oDCRASTRO AS SINGLELINEEDIT
PROTECT oDCOFC AS SINGLELINEEDIT
PROTECT oDCQTL AS rightSle
PROTECT oDCQTLN AS rightSle
PROTECT oDCCLIFOR AS rightSle
PROTECT oDCNOME AS SINGLELINEEDIT
PROTECT oDCABRNUM AS rightSle
PROTECT oDCABRNOM AS SINGLELINEEDIT
PROTECT oDCDEC01 AS SINGLELINEEDIT
PROTECT oDCDEC02 AS SINGLELINEEDIT
PROTECT oDCDEC03 AS SINGLELINEEDIT
PROTECT oDCGB1 AS GROUPBOX
PROTECT oDCSC_QTL2 AS FIXEDTEXT
PROTECT oCCESCRES AS PUSHBUTTON
PROTECT oCCESCFOR AS PUSHBUTTON
PROTECT oDCSC_SETOR1 AS FIXEDTEXT
PROTECT oDCSC_NOME AS FIXEDTEXT
PROTECT oDCSC_REVI AS FIXEDTEXT
PROTECT oDCSC_DESCRI AS FIXEDTEXT
PROTECT oDCSC_CODIGO AS FIXEDTEXT
PROTECT oCCRB17 AS RADIOBUTTON
PROTECT oCCRB18 AS RADIOBUTTON
PROTECT oDCTIPERR AS RADIOBUTTONGROUP
PROTECT oDCSC_RASTRO AS FIXEDTEXT
PROTECT oDCCODRET AS RADIOBUTTONGROUP
PROTECT oDCSC_QTL3 AS FIXEDTEXT
PROTECT oDCSC_OFC AS FIXEDTEXT
PROTECT oCCRB6 AS RADIOBUTTON
PROTECT oCCRB14 AS RADIOBUTTON
PROTECT oDCDISPO AS RADIOBUTTONGROUP
PROTECT oCCRB22 AS RADIOBUTTON
PROTECT oCCRB21 AS RADIOBUTTON
PROTECT oCCbtnPEGMP04 AS PUSHBUTTON
PROTECT oCCPEGCLI AS PUSHBUTTON
PROTECT oCCPEGCOD AS PUSHBUTTON
PROTECT oCCesccod AS PUSHBUTTON
PROTECT oDCtheFixedText9 AS FIXEDTEXT
PROTECT oCCcancelar AS PUSHBUTTON
PROTECT oDCtheFixedText11 AS FIXEDTEXT
PROTECT oCCOK AS PUSHBUTTON
PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
PROTECT oCCfoto AS PUSHBUTTON

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS ABRNOM
RETURN SELF:FieldGet( #ABRNOM )

ASSIGN ABRNOM( uValue )
SELF:FieldPut( #ABRNOM , uValue )

ACCESS ABRNUM
RETURN SELF:FieldGet( #ABRNUM )

ASSIGN ABRNUM( uValue )
SELF:FieldPut( #ABRNUM , uValue )

METHOD Cancelar( ) 
	SELF:EndWindow()

ACCESS CLIFOR
RETURN SELF:FieldGet( #CLIFOR )

ASSIGN CLIFOR( uValue )
SELF:FieldPut( #CLIFOR , uValue )

ACCESS CODIGO
RETURN SELF:FieldGet( #CODIGO )

ASSIGN CODIGO( uValue )
SELF:FieldPut( #CODIGO , uValue )

ACCESS CODRET
RETURN SELF:FieldGet( #CODRET )

ASSIGN CODRET( uValue )
SELF:FieldPut( #CODRET , uValue )

ACCESS DEC01
RETURN SELF:FieldGet( #DEC01 )

ASSIGN DEC01( uValue )
SELF:FieldPut( #DEC01 , uValue )

ACCESS DEC02
RETURN SELF:FieldGet( #DEC02 )

ASSIGN DEC02( uValue )
SELF:FieldPut( #DEC02 , uValue )

ACCESS DEC03
RETURN SELF:FieldGet( #DEC03 )

ASSIGN DEC03( uValue )
SELF:FieldPut( #DEC03 , uValue )

ACCESS DESCRI
RETURN SELF:FieldGet( #DESCRI )

ASSIGN DESCRI( uValue )
SELF:FieldPut( #DESCRI , uValue )

ACCESS DISPO
RETURN SELF:FieldGet( #DISPO )

ASSIGN DISPO( uValue )
SELF:FieldPut( #DISPO , uValue )

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:CODIGO:=oESC:CODIGO
    SELF:DESCRI:=oESC:NOME
ENDIF	

METHOD ESCFOR( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:NUMERO)
	SELF:CLIFOR:=oESC:NUMERO
	SELF:NOME:=oESC:NOME
ENDIF		

METHOD ESCRES( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:ABRNUM:=oESCMP04:NUMERO
   SELF:ABRNOM:=oESCMP04:NOME
ENDIF		

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:oDCCODIGO:TextValue)," ",""))

IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()
		

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JRNCFI" , _GetInst()},iCtlID)

	SELF:oDCCODIGO := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_CODIGO  , _GetInst() } }
	SELF:oDCCODIGO:FieldSpec := PADRAO_CHAR_24{}
	SELF:oDCCODIGO:HyperLabel := HyperLabel{#CODIGO , "Codigo:" , NULL_STRING , "RNC_CODIGO"}

	SELF:oDCDESCRI := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_DESCRI  , _GetInst() } }
	SELF:oDCDESCRI:FieldSpec := PADRAO_CHAR_30{}
	SELF:oDCDESCRI:HyperLabel := HyperLabel{#DESCRI , "RNC Final Inclusao" , NULL_STRING , "RNC_DESCRI"}

	SELF:oDCREVI := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_REVI  , _GetInst() } }
	SELF:oDCREVI:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCREVI:HyperLabel := HyperLabel{#REVI , "Revi:" , NULL_STRING , "RNC_REVI"}

	SELF:oDCRASTRO := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_RASTRO  , _GetInst() } }
	SELF:oDCRASTRO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCRASTRO:HyperLabel := HyperLabel{#RASTRO , "Rastro:" , NULL_STRING , "RNC_RASTRO"}

	SELF:oDCOFC := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_OFC  , _GetInst() } }
	SELF:oDCOFC:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCOFC:HyperLabel := HyperLabel{#OFC , "Ofc:" , NULL_STRING , "RNC_OFC"}

	SELF:oDCQTL := rightSle{SELF , ResourceID{ JRNCFI_QTL  , _GetInst() } }
	SELF:oDCQTL:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTL:HyperLabel := HyperLabel{#QTL , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oDCQTLN := rightSle{SELF , ResourceID{ JRNCFI_QTLN  , _GetInst() } }
	SELF:oDCQTLN:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTLN:HyperLabel := HyperLabel{#QTLN , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oDCCLIFOR := rightSle{SELF , ResourceID{ JRNCFI_CLIFOR  , _GetInst() } }
	SELF:oDCCLIFOR:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCCLIFOR:HyperLabel := HyperLabel{#CLIFOR , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCNOME := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_NOME  , _GetInst() } }
	SELF:oDCNOME:FieldSpec := PADRAO_CHAR_50{}
	SELF:oDCNOME:HyperLabel := HyperLabel{#NOME , "Nome:" , NULL_STRING , "RNC_NOME"}

	SELF:oDCABRNUM := rightSle{SELF , ResourceID{ JRNCFI_ABRNUM  , _GetInst() } }
	SELF:oDCABRNUM:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCABRNUM:HyperLabel := HyperLabel{#ABRNUM , "Abrnum:" , NULL_STRING , "RNC_ABRNUM"}

	SELF:oDCABRNOM := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_ABRNOM  , _GetInst() } }
	SELF:oDCABRNOM:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCABRNOM:HyperLabel := HyperLabel{#ABRNOM , "Abrnom:" , NULL_STRING , "RNC_ABRNOM"}

	SELF:oDCDEC01 := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_DEC01  , _GetInst() } }
	SELF:oDCDEC01:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC01:HyperLabel := HyperLabel{#DEC01 , "Dec01:" , NULL_STRING , "RNC_DEC01"}

	SELF:oDCDEC02 := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_DEC02  , _GetInst() } }
	SELF:oDCDEC02:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC02:HyperLabel := HyperLabel{#DEC02 , "Dec02:" , NULL_STRING , "RNC_DEC02"}

	SELF:oDCDEC03 := SINGLELINEEDIT{SELF , ResourceID{ JRNCFI_DEC03  , _GetInst() } }
	SELF:oDCDEC03:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC03:HyperLabel := HyperLabel{#DEC03 , "Dec03:" , NULL_STRING , "RNC_DEC03"}

	SELF:oDCGB1 := GROUPBOX{SELF , ResourceID{ JRNCFI_GB1  , _GetInst() } }
	SELF:oDCGB1:HyperLabel := HyperLabel{#GB1 , "Descrição do Problema" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTL2 := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_QTL2  , _GetInst() } }
	SELF:oDCSC_QTL2:HyperLabel := HyperLabel{#SC_QTL2 , "Qtde Lote n/c:" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES := PUSHBUTTON{SELF , ResourceID{ JRNCFI_ESCRES  , _GetInst() } }
	SELF:oCCESCRES:HyperLabel := HyperLabel{#ESCRES , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCESCFOR := PUSHBUTTON{SELF , ResourceID{ JRNCFI_ESCFOR  , _GetInst() } }
	SELF:oCCESCFOR:HyperLabel := HyperLabel{#ESCFOR , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SETOR1 := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_SETOR1  , _GetInst() } }
	SELF:oDCSC_SETOR1:HyperLabel := HyperLabel{#SC_SETOR1 , "Aberto Por" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_NOME  , _GetInst() } }
	SELF:oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME , "Cliente" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_REVI := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_REVI  , _GetInst() } }
	SELF:oDCSC_REVI:HyperLabel := HyperLabel{#SC_REVI , "Revisão:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESCRI := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_DESCRI  , _GetInst() } }
	SELF:oDCSC_DESCRI:HyperLabel := HyperLabel{#SC_DESCRI , "Descrição:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CODIGO := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_CODIGO  , _GetInst() } }
	SELF:oDCSC_CODIGO:HyperLabel := HyperLabel{#SC_CODIGO , "Codigo/Aplicação" , NULL_STRING , NULL_STRING}

	SELF:oCCRB17 := RADIOBUTTON{SELF , ResourceID{ JRNCFI_RB17  , _GetInst() } }
	SELF:oCCRB17:HyperLabel := HyperLabel{#RB17 , "Interno" , NULL_STRING , NULL_STRING}

	SELF:oCCRB18 := RADIOBUTTON{SELF , ResourceID{ JRNCFI_RB18  , _GetInst() } }
	SELF:oCCRB18:HyperLabel := HyperLabel{#RB18 , "Externo" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPERR := RADIOBUTTONGROUP{SELF , ResourceID{ JRNCFI_TIPERR  , _GetInst() } }
	SELF:oDCTIPERR:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPERR:HyperLabel := HyperLabel{#TIPERR , "Tipo do Erro" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RASTRO := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_RASTRO  , _GetInst() } }
	SELF:oDCSC_RASTRO:HyperLabel := HyperLabel{#SC_RASTRO , "Rastro:" , NULL_STRING , NULL_STRING}

	SELF:oDCCODRET := RADIOBUTTONGROUP{SELF , ResourceID{ JRNCFI_CODRET  , _GetInst() } }
	SELF:oDCCODRET:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCCODRET:HyperLabel := HyperLabel{#CODRET , "Tipo" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTL3 := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_QTL3  , _GetInst() } }
	SELF:oDCSC_QTL3:HyperLabel := HyperLabel{#SC_QTL3 , "Qtde Lote " , NULL_STRING , NULL_STRING}

	SELF:oDCSC_OFC := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_OFC  , _GetInst() } }
	SELF:oDCSC_OFC:HyperLabel := HyperLabel{#SC_OFC , "O.F." , NULL_STRING , NULL_STRING}

	SELF:oCCRB6 := RADIOBUTTON{SELF , ResourceID{ JRNCFI_RB6  , _GetInst() } }
	SELF:oCCRB6:HyperLabel := HyperLabel{#RB6 , "Aprovar Condicional" , NULL_STRING , NULL_STRING}

	SELF:oCCRB14 := RADIOBUTTON{SELF , ResourceID{ JRNCFI_RB14  , _GetInst() } }
	SELF:oCCRB14:HyperLabel := HyperLabel{#RB14 , "Seleção" , NULL_STRING , NULL_STRING}

	SELF:oDCDISPO := RADIOBUTTONGROUP{SELF , ResourceID{ JRNCFI_DISPO  , _GetInst() } }
	SELF:oDCDISPO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCDISPO:HyperLabel := HyperLabel{#DISPO , "Disposição" , NULL_STRING , NULL_STRING}

	SELF:oCCRB22 := RADIOBUTTON{SELF , ResourceID{ JRNCFI_RB22  , _GetInst() } }
	SELF:oCCRB22:HyperLabel := HyperLabel{#RB22 , "Retrabalho" , NULL_STRING , NULL_STRING}

	SELF:oCCRB21 := RADIOBUTTON{SELF , ResourceID{ JRNCFI_RB21  , _GetInst() } }
	SELF:oCCRB21:HyperLabel := HyperLabel{#RB21 , "Sucata" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnPEGMP04 := PUSHBUTTON{SELF , ResourceID{ JRNCFI_BTNPEGMP04  , _GetInst() } }
	SELF:oCCbtnPEGMP04:HyperLabel := HyperLabel{#btnPEGMP04 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGCLI := PUSHBUTTON{SELF , ResourceID{ JRNCFI_PEGCLI  , _GetInst() } }
	SELF:oCCPEGCLI:HyperLabel := HyperLabel{#PEGCLI , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGCOD := PUSHBUTTON{SELF , ResourceID{ JRNCFI_PEGCOD  , _GetInst() } }
	SELF:oCCPEGCOD:HyperLabel := HyperLabel{#PEGCOD , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCesccod := PUSHBUTTON{SELF , ResourceID{ JRNCFI_ESCCOD  , _GetInst() } }
	SELF:oCCesccod:HyperLabel := HyperLabel{#esccod , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText9 := FIXEDTEXT{SELF , ResourceID{ JRNCFI_THEFIXEDTEXT9  , _GetInst() } }
	SELF:oDCtheFixedText9:HyperLabel := HyperLabel{#theFixedText9 , "Cancelar" , NULL_STRING , NULL_STRING}

	SELF:oCCcancelar := PUSHBUTTON{SELF , ResourceID{ JRNCFI_CANCELAR  , _GetInst() } }
	SELF:oCCcancelar:Image := ico_sair{}
	SELF:oCCcancelar:HyperLabel := HyperLabel{#cancelar , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText11 := FIXEDTEXT{SELF , ResourceID{ JRNCFI_THEFIXEDTEXT11  , _GetInst() } }
	SELF:oDCtheFixedText11:HyperLabel := HyperLabel{#theFixedText11 , "OK" , NULL_STRING , NULL_STRING}

	SELF:oCCOK := PUSHBUTTON{SELF , ResourceID{ JRNCFI_OK  , _GetInst() } }
	SELF:oCCOK:Image := ico_ok{}
	SELF:oCCOK:HyperLabel := HyperLabel{#OK , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO2 := FIXEDTEXT{SELF , ResourceID{ JRNCFI_SC_DESTINO2  , _GetInst() } }
	SELF:oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2 , "Foto" , NULL_STRING , NULL_STRING}

	SELF:oCCfoto := PUSHBUTTON{SELF , ResourceID{ JRNCFI_FOTO  , _GetInst() } }
	SELF:oCCfoto:Image := ico_camera{}
	SELF:oCCfoto:HyperLabel := HyperLabel{#foto , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCTIPERR:FillUsing({ ;
	                         {SELF:oCCRB17, "I"}, ;
	                         {SELF:oCCRB18, "E"} ;
	                         })

	SELF:oDCCODRET:FillUsing({ ;
	                         {SELF:oCCRB22, "R"}, ;
	                         {SELF:oCCRB21, "S"} ;
	                         })

	SELF:oDCDISPO:FillUsing({ ;
	                        {SELF:oCCRB6, "A"}, ;
	                        {SELF:oCCRB14, "E"} ;
	                        })

	SELF:Caption := "RNC Final Inclusao"
	SELF:HyperLabel := HyperLabel{#JRNCFI , "RNC Final Inclusao" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NOME
RETURN SELF:FieldGet( #NOME )

ASSIGN NOME( uValue )
SELF:FieldPut( #NOME , uValue )

ACCESS OFC
RETURN SELF:FieldGet( #OFC )

ASSIGN OFC( uValue )
SELF:FieldPut( #OFC , uValue )

METHOD OK( ) 
LOCAL oSERVER,oRACF AS USEREDE
LOCAL aDAD,aCAMPOS AS ARRAY
LOCAL nRNC,nRACF,nSAC AS DWORD

nRNC:=0
nRACF:=0
nSAC:=0

IF Empty(SELF:CLIFOR)
   alert("Cliente em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:NOME)
   alert("Nome Cliente em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:CODIGO)
   alert("Codigo Produto em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:DESCRI)
   alert("Descriçao Produto em Branco")	
   RETURN .f.
ENDIF

aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF		
aDAD:={zCURINI,"RACF.DBF",zCURDIR}
oRACF:=USEREDE{aDAD}
IF oRACF:nERRO#0
   oSERVER:CLOSE()
   RETU SELF
ENDIF
oSERVER:GoBottom()
nRNC:=oSERVER:FIELDGET("RNC")
nRNC++
oSERVER:APPEND()
oSERVER:FIELDPUT("RNC",nRNC)
oSERVER:FIELDPUT("ABRNUM",SELF:ABRNUM)
oSERVER:FIELDPUT("ABRNOM",SELF:ABRNOM)
oSERVER:FIELDPUT("CLIFOR",SELF:CLIFOR)
oSERVER:FIELDPUT("CODIGO",SELF:CODIGO)
oSERVER:FIELDPUT("DEC01",SELF:DEC01)
oSERVER:FIELDPUT("DEC02",SELF:DEC02)
oSERVER:FIELDPUT("DEC03",SELF:DEC03)
oSERVER:FIELDPUT("DESCRI",SELF:DESCRI)
oSERVER:FIELDPUT("OFC",SELF:OFC)
oSERVER:FIELDPUT("REVI",SELF:REVI)
oSERVER:FIELDPUT("NOME",SELF:NOME)
oSERVER:FIELDPUT("QTLN",SELF:QTLN)
oSERVER:FIELDPUT("QTL",SELF:QTL)
oSERVER:FIELDPUT("RASTRO",SELF:RASTRO)
oSERVER:FIELDPUT("CODRNC","F") //Final
oSERVER:FIELDPUT("TIPCAD","C") //Cliente
oSERVER:FIELDPUT("DISPO",SELF:DISPO)
oSERVER:FIELDPUT("CODRET",SELF:CODRET)
oSERVER:FIELDPUT("TIPERR",SELF:TIPERR)
oSERVER:FIELDPUT("INCUSER",ZUSER)
OSERVER:FIELDPUT("INCDATA",Today())
OSERVER:FIELDPUT("DATA",Today())
oSERVER:FIELDPUT("FECHADA",.F.)
IF oSERVER:FIELDGET("TIPERR")="E"
   oRACF:GOBOTTOM()
   nRACF:=oRACF:FIELDGET("RACF")
   nRACF++
   oRACF:APPEND()
   oRACF:FIELDPUT("RACF",nRACF)
   oRACF:FIELDPUT("DATA",Today())
   oRACF:FIELDPUT("RNC",oSERVER:FIELDGET("RNC"))
   oRACF:FIELDPUT("RASTRO",oSERVER:FIELDGET("RASTRO"))
   oRACF:FIELDPUT("DESENHO",oSERVER:FIELDGET("CODIGO"))
   oRACF:FIELDPUT("DENO",oSERVER:FIELDGET("DESCRI"))
   oRACF:FIELDPUT("QTL1",oSERVER:FIELDGET("QTL"))
   oRACF:FIELDPUT("QTN1",oSERVER:FIELDGET("QTLN"))
   oRACF:FIELDPUT("DESC01",oSERVER:FIELDGET("DEC01"))
   oRACF:FIELDPUT("DESC02",oSERVER:FIELDGET("DEC02"))
   oRACF:FIELDPUT("DESC03",oSERVER:FIELDGET("DEC03"))
   oRACF:FIELDPUT("INCUSER",ZUSER)
   ORACF:FIELDPUT("INCDATA",Today())
   oSERVER:FIELDPUT("NRACF",nRACF)
   ENVIARACF(nRNC,nRACF)
ENDIF
oRACF:CLOSE()
oSERVER:CLOSE()
aCAMPOS:={}
AAdd(aCAMPOS,SELF:CLIFOR)
AAdd(aCAMPOS,SELF:NOME)
AAdd(aCAMPOS,SELF:CODIGO)
AAdd(aCAMPOS,SELF:DESCRI)
AAdd(Acampos,0)
AAdd(aCAMPOS,nRNC)
AAdd(Acampos,Today())
AAdd(aCAMPOS,nSAC)
AAdd(aCAMPOS,"")
NOVOCNQ(aCAMPOS)
ENVIARNC(NRNC,"Final",SELF:CODIGO,{SELF:DEC01,SELF:DEC02,SELF:DEC03})	
DIGANUM(nRNC,nRACF,nSAC)
SELF:ENDWINDOW()
		
		

METHOD PEGCLI( ) 
LOCAL aCLI AS ARRAY	
aCLI:=PEGMA01(SELF:CLIFOR,ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:NOME:=aCLI[2]
ENDIF	

METHOD PEGCOD( ) 
LOCAL aPRO	
aPRO:=PEGMS01(SELF:CODIGO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:DESCRI:=aPRO[2]
ENDIF		

METHOD btnPEGMP04( ) 
LOCAL aTEC AS ARRAY	
LOCAL ACOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:ABRNUM,ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:ABRNOM:=aTEC[2]
ENDIF	

METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
		   FabCenterWindow( SELF )
	RETURN NIL


ACCESS QTL
RETURN SELF:FieldGet( #QTL )

ASSIGN QTL( uValue )
SELF:FieldPut( #QTL , uValue )

ACCESS QTLN
RETURN SELF:FieldGet( #QTLN )

ASSIGN QTLN( uValue )
SELF:FieldPut( #QTLN , uValue )

ACCESS RASTRO
RETURN SELF:FieldGet( #RASTRO )

ASSIGN RASTRO( uValue )
SELF:FieldPut( #RASTRO , uValue )

ACCESS REVI
RETURN SELF:FieldGet( #REVI )

ASSIGN REVI( uValue )
SELF:FieldPut( #REVI , uValue )

ACCESS TIPERR
RETURN SELF:FieldGet( #TIPERR )

ASSIGN TIPERR( uValue )
SELF:FieldPut( #TIPERR , uValue )

END CLASS
STATIC DEFINE JRNCFI_BTNPEGMP04 := 135
