#region DEFINES
STATIC DEFINE JRNCPI_ABRNOM := 107
STATIC DEFINE JRNCPI_ABRNUM := 106
STATIC DEFINE JRNCPI_CANCELAR := 136
STATIC DEFINE JRNCPI_CLIFOR := 104
STATIC DEFINE JRNCPI_CODIGO := 100
STATIC DEFINE JRNCPI_CODRET := 126
STATIC DEFINE JRNCPI_DEC01 := 110
STATIC DEFINE JRNCPI_DEC02 := 111
STATIC DEFINE JRNCPI_DEC03 := 112
STATIC DEFINE JRNCPI_DESCRI := 101
STATIC DEFINE JRNCPI_ESCCOD := 134
STATIC DEFINE JRNCPI_ESCFOR := 116
STATIC DEFINE JRNCPI_ESCRES := 115
STATIC DEFINE JRNCPI_FOTO := 140
STATIC DEFINE JRNCPI_GB1 := 113
STATIC DEFINE JRNCPI_NOME := 105
STATIC DEFINE JRNCPI_OK := 138
STATIC DEFINE JRNCPI_PEGCLI := 131
STATIC DEFINE JRNCPI_PEGCOD := 133
STATIC DEFINE JRNCPI_PEGMP04 := 132 
STATIC DEFINE JRNCPI_QTL := 108
STATIC DEFINE JRNCPI_QTLN := 109
STATIC DEFINE JRNCPI_RASTRO := 103
STATIC DEFINE JRNCPI_RB17 := 122
STATIC DEFINE JRNCPI_RB18 := 123
STATIC DEFINE JRNCPI_RB21 := 130
STATIC DEFINE JRNCPI_RB22 := 129
STATIC DEFINE JRNCPI_RB23 := 128
STATIC DEFINE JRNCPI_REVI := 102
STATIC DEFINE JRNCPI_SC_CODIGO := 121
STATIC DEFINE JRNCPI_SC_DESCRI := 120
STATIC DEFINE JRNCPI_SC_DESTINO2 := 139
STATIC DEFINE JRNCPI_SC_NOME := 118
STATIC DEFINE JRNCPI_SC_QTL2 := 114
STATIC DEFINE JRNCPI_SC_QTL3 := 127
STATIC DEFINE JRNCPI_SC_RASTRO := 125
STATIC DEFINE JRNCPI_SC_REVI := 119
STATIC DEFINE JRNCPI_SC_SETOR1 := 117
STATIC DEFINE JRNCPI_THEFIXEDTEXT11 := 137
STATIC DEFINE JRNCPI_THEFIXEDTEXT9 := 135
STATIC DEFINE JRNCPI_TIPERR := 124
#endregion

PARTIAL CLASS JRNCPI INHERIT DATADIALOG
PROTECT oDCCODIGO AS SINGLELINEEDIT
PROTECT oDCDESCRI AS SINGLELINEEDIT
PROTECT oDCREVI AS SINGLELINEEDIT
PROTECT oDCRASTRO AS SINGLELINEEDIT
PROTECT oDCCLIFOR AS rightSle
PROTECT oDCNOME AS SINGLELINEEDIT
PROTECT oDCABRNUM AS rightSle
PROTECT oDCABRNOM AS SINGLELINEEDIT
PROTECT oDCQTL AS rightSle
PROTECT oDCQTLN AS rightSle
PROTECT oDCDEC01 AS SINGLELINEEDIT
PROTECT oDCDEC02 AS SINGLELINEEDIT
PROTECT oDCDEC03 AS SINGLELINEEDIT
PROTECT oDCGB1 AS GROUPBOX
PROTECT oDCSC_QTL2 AS FIXEDTEXT
PROTECT oCCESCRES AS PUSHBUTTON
PROTECT oCCESCFOR AS PUSHBUTTON
PROTECT oDCSC_SETOR1 AS FIXEDTEXT
PROTECT oDCSC_NOME AS FIXEDTEXT
PROTECT oDCSC_REVI AS FIXEDTEXT
PROTECT oDCSC_DESCRI AS FIXEDTEXT
PROTECT oDCSC_CODIGO AS FIXEDTEXT
PROTECT oCCRB17 AS RADIOBUTTON
PROTECT oCCRB18 AS RADIOBUTTON
PROTECT oDCTIPERR AS RADIOBUTTONGROUP
PROTECT oDCSC_RASTRO AS FIXEDTEXT
PROTECT oDCCODRET AS RADIOBUTTONGROUP
PROTECT oDCSC_QTL3 AS FIXEDTEXT
PROTECT oCCRB23 AS RADIOBUTTON
PROTECT oCCRB22 AS RADIOBUTTON
PROTECT oCCRB21 AS RADIOBUTTON
PROTECT oCCPEGCLI AS PUSHBUTTON
PROTECT oCCbtnPEGMP04 AS PUSHBUTTON
PROTECT oCCPEGCOD AS PUSHBUTTON
PROTECT oCCesccod AS PUSHBUTTON
PROTECT oDCtheFixedText9 AS FIXEDTEXT
PROTECT oCCcancelar AS PUSHBUTTON
PROTECT oDCtheFixedText11 AS FIXEDTEXT
PROTECT oCCOK AS PUSHBUTTON
PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
PROTECT oCCfoto AS PUSHBUTTON

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS ABRNOM
RETURN SELF:FieldGet( #ABRNOM )

ASSIGN ABRNOM( uValue )
SELF:FieldPut( #ABRNOM , uValue )

ACCESS ABRNUM
RETURN SELF:FieldGet( #ABRNUM )

ASSIGN ABRNUM( uValue )
SELF:FieldPut( #ABRNUM , uValue )

METHOD Cancelar( ) 
	SELF:EndWindow()

ACCESS CLIFOR
RETURN SELF:FieldGet( #CLIFOR )

ASSIGN CLIFOR( uValue )
SELF:FieldPut( #CLIFOR , uValue )

ACCESS CODIGO
RETURN SELF:FieldGet( #CODIGO )

ASSIGN CODIGO( uValue )
SELF:FieldPut( #CODIGO , uValue )

ACCESS CODRET
RETURN SELF:FieldGet( #CODRET )

ASSIGN CODRET( uValue )
SELF:FieldPut( #CODRET , uValue )

ACCESS DEC01
RETURN SELF:FieldGet( #DEC01 )

ASSIGN DEC01( uValue )
SELF:FieldPut( #DEC01 , uValue )

ACCESS DEC02
RETURN SELF:FieldGet( #DEC02 )

ASSIGN DEC02( uValue )
SELF:FieldPut( #DEC02 , uValue )

ACCESS DEC03
RETURN SELF:FieldGet( #DEC03 )

ASSIGN DEC03( uValue )
SELF:FieldPut( #DEC03 , uValue )

ACCESS DESCRI
RETURN SELF:FieldGet( #DESCRI )

ASSIGN DESCRI( uValue )
SELF:FieldPut( #DESCRI , uValue )

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:CODIGO:=oESC:CODIGO
    SELF:DESCRI:=oESC:NOME
ENDIF		

METHOD ESCFOR( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:NUMERO)
	SELF:CLIFOR:=oESC:NUMERO
	SELF:NOME:=oESC:NOME
ENDIF	

METHOD ESCRES( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:ABRNUM:=oESCMP04:NUMERO
   SELF:ABRNOM:=oESCMP04:NOME
ENDIF	

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:oDCCODIGO:TextValue)," ",""))

IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()
		

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JRNCPI" , _GetInst()},iCtlID)

	SELF:oDCCODIGO := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_CODIGO  , _GetInst() } }
	SELF:oDCCODIGO:FieldSpec := PADRAO_CHAR_24{}
	SELF:oDCCODIGO:HyperLabel := HyperLabel{#CODIGO , "Codigo:" , NULL_STRING , "RNC_CODIGO"}

	SELF:oDCDESCRI := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_DESCRI  , _GetInst() } }
	SELF:oDCDESCRI:FieldSpec := PADRAO_CHAR_30{}
	SELF:oDCDESCRI:HyperLabel := HyperLabel{#DESCRI , "Descri:" , NULL_STRING , "RNC_DESCRI"}

	SELF:oDCREVI := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_REVI  , _GetInst() } }
	SELF:oDCREVI:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCREVI:HyperLabel := HyperLabel{#REVI , "Revi:" , NULL_STRING , "RNC_REVI"}

	SELF:oDCRASTRO := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_RASTRO  , _GetInst() } }
	SELF:oDCRASTRO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCRASTRO:HyperLabel := HyperLabel{#RASTRO , "Rastro:" , NULL_STRING , "RNC_RASTRO"}

	SELF:oDCCLIFOR := rightSle{SELF , ResourceID{ JRNCPI_CLIFOR  , _GetInst() } }
	SELF:oDCCLIFOR:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCCLIFOR:HyperLabel := HyperLabel{#CLIFOR , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCNOME := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_NOME  , _GetInst() } }
	SELF:oDCNOME:FieldSpec := PADRAO_CHAR_50{}
	SELF:oDCNOME:HyperLabel := HyperLabel{#NOME , "Nome:" , NULL_STRING , "RNC_NOME"}

	SELF:oDCABRNUM := rightSle{SELF , ResourceID{ JRNCPI_ABRNUM  , _GetInst() } }
	SELF:oDCABRNUM:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCABRNUM:HyperLabel := HyperLabel{#ABRNUM , "Abrnum:" , NULL_STRING , "RNC_ABRNUM"}

	SELF:oDCABRNOM := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_ABRNOM  , _GetInst() } }
	SELF:oDCABRNOM:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCABRNOM:HyperLabel := HyperLabel{#ABRNOM , "Abrnom:" , NULL_STRING , "RNC_ABRNOM"}

	SELF:oDCQTL := rightSle{SELF , ResourceID{ JRNCPI_QTL  , _GetInst() } }
	SELF:oDCQTL:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTL:HyperLabel := HyperLabel{#QTL , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oDCQTLN := rightSle{SELF , ResourceID{ JRNCPI_QTLN  , _GetInst() } }
	SELF:oDCQTLN:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTLN:HyperLabel := HyperLabel{#QTLN , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oDCDEC01 := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_DEC01  , _GetInst() } }
	SELF:oDCDEC01:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC01:HyperLabel := HyperLabel{#DEC01 , "Dec01:" , NULL_STRING , "RNC_DEC01"}

	SELF:oDCDEC02 := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_DEC02  , _GetInst() } }
	SELF:oDCDEC02:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC02:HyperLabel := HyperLabel{#DEC02 , "Dec02:" , NULL_STRING , "RNC_DEC02"}

	SELF:oDCDEC03 := SINGLELINEEDIT{SELF , ResourceID{ JRNCPI_DEC03  , _GetInst() } }
	SELF:oDCDEC03:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC03:HyperLabel := HyperLabel{#DEC03 , "Dec03:" , NULL_STRING , "RNC_DEC03"}

	SELF:oDCGB1 := GROUPBOX{SELF , ResourceID{ JRNCPI_GB1  , _GetInst() } }
	SELF:oDCGB1:HyperLabel := HyperLabel{#GB1 , "Descrição do Problema" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTL2 := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_QTL2  , _GetInst() } }
	SELF:oDCSC_QTL2:HyperLabel := HyperLabel{#SC_QTL2 , "Qtde Lote n/c:" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES := PUSHBUTTON{SELF , ResourceID{ JRNCPI_ESCRES  , _GetInst() } }
	SELF:oCCESCRES:HyperLabel := HyperLabel{#ESCRES , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCESCFOR := PUSHBUTTON{SELF , ResourceID{ JRNCPI_ESCFOR  , _GetInst() } }
	SELF:oCCESCFOR:HyperLabel := HyperLabel{#ESCFOR , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SETOR1 := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_SETOR1  , _GetInst() } }
	SELF:oDCSC_SETOR1:HyperLabel := HyperLabel{#SC_SETOR1 , "Aberto Por" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_NOME  , _GetInst() } }
	SELF:oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME , "Cliente" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_REVI := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_REVI  , _GetInst() } }
	SELF:oDCSC_REVI:HyperLabel := HyperLabel{#SC_REVI , "Revisão:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESCRI := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_DESCRI  , _GetInst() } }
	SELF:oDCSC_DESCRI:HyperLabel := HyperLabel{#SC_DESCRI , "Descrição:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CODIGO := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_CODIGO  , _GetInst() } }
	SELF:oDCSC_CODIGO:HyperLabel := HyperLabel{#SC_CODIGO , "Codigo/Aplicação" , NULL_STRING , NULL_STRING}

	SELF:oCCRB17 := RADIOBUTTON{SELF , ResourceID{ JRNCPI_RB17  , _GetInst() } }
	SELF:oCCRB17:HyperLabel := HyperLabel{#RB17 , "Interno" , NULL_STRING , NULL_STRING}

	SELF:oCCRB18 := RADIOBUTTON{SELF , ResourceID{ JRNCPI_RB18  , _GetInst() } }
	SELF:oCCRB18:HyperLabel := HyperLabel{#RB18 , "Externo" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPERR := RADIOBUTTONGROUP{SELF , ResourceID{ JRNCPI_TIPERR  , _GetInst() } }
	SELF:oDCTIPERR:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPERR:HyperLabel := HyperLabel{#TIPERR , "Tipo do Erro" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RASTRO := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_RASTRO  , _GetInst() } }
	SELF:oDCSC_RASTRO:HyperLabel := HyperLabel{#SC_RASTRO , "Rastro:" , NULL_STRING , NULL_STRING}

	SELF:oDCCODRET := RADIOBUTTONGROUP{SELF , ResourceID{ JRNCPI_CODRET  , _GetInst() } }
	SELF:oDCCODRET:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCCODRET:HyperLabel := HyperLabel{#CODRET , "Tipo" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTL3 := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_QTL3  , _GetInst() } }
	SELF:oDCSC_QTL3:HyperLabel := HyperLabel{#SC_QTL3 , "Qtde Lote" , NULL_STRING , NULL_STRING}

	SELF:oCCRB23 := RADIOBUTTON{SELF , ResourceID{ JRNCPI_RB23  , _GetInst() } }
	SELF:oCCRB23:HyperLabel := HyperLabel{#RB23 , "Aprovado Condicional" , NULL_STRING , NULL_STRING}

	SELF:oCCRB22 := RADIOBUTTON{SELF , ResourceID{ JRNCPI_RB22  , _GetInst() } }
	SELF:oCCRB22:HyperLabel := HyperLabel{#RB22 , "Retrabalho" , NULL_STRING , NULL_STRING}

	SELF:oCCRB21 := RADIOBUTTON{SELF , ResourceID{ JRNCPI_RB21  , _GetInst() } }
	SELF:oCCRB21:HyperLabel := HyperLabel{#RB21 , "Sucata" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGCLI := PUSHBUTTON{SELF , ResourceID{ JRNCPI_PEGCLI  , _GetInst() } }
	SELF:oCCPEGCLI:HyperLabel := HyperLabel{#PEGCLI , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnPEGMP04 := PUSHBUTTON{SELF , ResourceID{ JRNCPI_BTNPEGMP04  , _GetInst() } }
	SELF:oCCbtnPEGMP04:HyperLabel := HyperLabel{#btnPEGMP04 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCPEGCOD := PUSHBUTTON{SELF , ResourceID{ JRNCPI_PEGCOD  , _GetInst() } }
	SELF:oCCPEGCOD:HyperLabel := HyperLabel{#PEGCOD , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCesccod := PUSHBUTTON{SELF , ResourceID{ JRNCPI_ESCCOD  , _GetInst() } }
	SELF:oCCesccod:HyperLabel := HyperLabel{#esccod , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText9 := FIXEDTEXT{SELF , ResourceID{ JRNCPI_THEFIXEDTEXT9  , _GetInst() } }
	SELF:oDCtheFixedText9:HyperLabel := HyperLabel{#theFixedText9 , "Cancelar" , NULL_STRING , NULL_STRING}

	SELF:oCCcancelar := PUSHBUTTON{SELF , ResourceID{ JRNCPI_CANCELAR  , _GetInst() } }
	SELF:oCCcancelar:Image := ico_sair{}
	SELF:oCCcancelar:HyperLabel := HyperLabel{#cancelar , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText11 := FIXEDTEXT{SELF , ResourceID{ JRNCPI_THEFIXEDTEXT11  , _GetInst() } }
	SELF:oDCtheFixedText11:HyperLabel := HyperLabel{#theFixedText11 , "OK" , NULL_STRING , NULL_STRING}

	SELF:oCCOK := PUSHBUTTON{SELF , ResourceID{ JRNCPI_OK  , _GetInst() } }
	SELF:oCCOK:Image := ico_ok{}
	SELF:oCCOK:HyperLabel := HyperLabel{#OK , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO2 := FIXEDTEXT{SELF , ResourceID{ JRNCPI_SC_DESTINO2  , _GetInst() } }
	SELF:oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2 , "Foto" , NULL_STRING , NULL_STRING}

	SELF:oCCfoto := PUSHBUTTON{SELF , ResourceID{ JRNCPI_FOTO  , _GetInst() } }
	SELF:oCCfoto:Image := ico_camera{}
	SELF:oCCfoto:HyperLabel := HyperLabel{#foto , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCTIPERR:FillUsing({ ;
	                         {SELF:oCCRB17, "I"}, ;
	                         {SELF:oCCRB18, "E"} ;
	                         })

	SELF:oDCCODRET:FillUsing({ ;
	                         {SELF:oCCRB23, "A"}, ;
	                         {SELF:oCCRB22, "R"}, ;
	                         {SELF:oCCRB21, "S"} ;
	                         })

	SELF:Caption := "RNC - Produto Inclusao"
	SELF:HyperLabel := HyperLabel{#JRNCPI , "RNC - Produto Inclusao" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NOME
RETURN SELF:FieldGet( #NOME )

ASSIGN NOME( uValue )
SELF:FieldPut( #NOME , uValue )

METHOD OK( ) 
LOCAL oSERVER,oRACF,oSAC AS USEREDE
LOCAL aDAD,aCAMPOS AS ARRAY
LOCAL nRNC,nRACF,nSAC AS DWORD
LOCAL lSAC
LOCAL cCAUSA AS STRING

IF Empty(SELF:CLIFOR)
   alert("Cliente em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:NOME)
   alert("Nome Cliente em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:CODIGO)
   alert("Codigo Produto em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:DESCRI)
   alert("Descriçao Produto em Branco")	
   RETURN .f.
ENDIF

nRNC:=0
nRACF:=0
nSAC:=0

IF SELF:QTL<=0
   alert("Preenher QTDE Lote")
   RETURN .f.
ENDIF
IF SELF:QTLN<=0
   alert("Preenher QTDE Lote Não Conforme")
   RETURN .f.	
ENDIF
aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF		
aDAD:={zCURINI,"RACF.DBF",zCURDIR}
oRACF:=USEREDE{aDAD}
IF oRACF:nERRO#0
   oSERVER:CLOSE()
   RETU SELF
ENDIF
aDAD:={zCURINI,"SAC.DBF",zCURDIR}
oSAC:=USEREDE{aDAD}
IF oSAC:nERRO#0
   oRACF:CLOSE()	
   oSERVER:CLOSE()
   RETU SELF
ENDIF
oSERVER:GoBottom()
nRNC:=oSERVER:FIELDGET("RNC")
nRNC++
oSERVER:APPEND()
oSERVER:FIELDPUT("RNC",nRNC)
oSERVER:FIELDPUT("ABRNUM",SELF:ABRNUM)
oSERVER:FIELDPUT("ABRNOM",SELF:ABRNOM)
oSERVER:FIELDPUT("CLIFOR",SELF:CLIFOR)
oSERVER:FIELDPUT("CODIGO",SELF:CODIGO)
oSERVER:FIELDPUT("DEC01",SELF:DEC01)
oSERVER:FIELDPUT("DEC02",SELF:DEC02)
oSERVER:FIELDPUT("DEC03",SELF:DEC03)
oSERVER:FIELDPUT("DESCRI",SELF:DESCRI)
oSERVER:FIELDPUT("REVI",SELF:REVI)
oSERVER:FIELDPUT("NOME",SELF:NOME)
oSERVER:FIELDPUT("QTL",SELF:QTL)
oSERVER:FIELDPUT("QTLN",SELF:QTLN)
oSERVER:FIELDPUT("TIPCAD","C") //Cliente
oSERVER:FIELDPUT("RASTRO",SELF:RASTRO)
IF SELF:TIPERR="E"
   oSERVER:FIELDPUT("DISPO","D") //Devolver ao fornecedor
ELSE
   oSERVER:FIELDPUT("DISPO","E") //Selecao
ENDIF
oSERVER:FIELDPUT("CODRNC","P") //Processo
oSERVER:FIELDPUT("CODRET",SELF:CODRET)
oSERVER:FIELDPUT("TIPERR",SELF:TIPERR)
oSERVER:FIELDPUT("INCUSER",ZUSER)
OSERVER:FIELDPUT("INCDATA",Today())
OSERVER:FIELDPUT("DATA",Today())
oSERVER:FIELDPUT("FECHADA",.F.)
IF oSERVER:FIELDGET("TIPERR")="E"
   oRACF:GOBOTTOM()
   nRACF:=oRACF:FIELDGET("RACF")
   nRACF++
   oRACF:APPEND()
   oRACF:FIELDPUT("RACF",nRACF)
   oRACF:FIELDPUT("DATA",Today())
   oRACF:FIELDPUT("RNC",oSERVER:FIELDGET("RNC"))
   oRACF:FIELDPUT("RASTRO",oSERVER:FIELDGET("RASTRO"))
   oRACF:FIELDPUT("CNFFOR",oSERVER:FIELDGET("NFC"))
   oRACF:FIELDPUT("DESENHO",oSERVER:FIELDGET("CODIGO"))
   oRACF:FIELDPUT("DENO",oSERVER:FIELDGET("DESCRI"))
   oRACF:FIELDPUT("QTL1",oSERVER:FIELDGET("QTL"))
   oRACF:FIELDPUT("QTN1",oSERVER:FIELDGET("QTLN"))
   oRACF:FIELDPUT("UNID",oSERVER:FIELDGET("UNID"))
   oRACF:FIELDPUT("DESC01",oSERVER:FIELDGET("DEC01"))
   oRACF:FIELDPUT("DESC02",oSERVER:FIELDGET("DEC02"))
   oRACF:FIELDPUT("DESC03",oSERVER:FIELDGET("DEC03"))
   oRACF:FIELDPUT("INCUSER",ZUSER)
   ORACF:FIELDPUT("INCDATA",Today())
   oSERVER:FIELDPUT("NRACF",nRACF)
   ENVIARACF(nRNC,nRACF)
ENDIF
oRACF:CLOSE()
lSAC:=.F.
IF oSERVER:FIELDGET("TIPERR")="I"
   IF oSERVER:FIELDGET("CODRET")="R"
      IF Oserver:FIELDGET("QTLN")=oSERVER:FIELDGET("QTL")
         lSAC:=.T.
      ENDIF
   ENDIF
   IF oSERVER:FIELDGET("CODRET")="S"
      IF oSERVER:FIELDGET("QTLN")/oSERVER:FIELDGET("QTL")>=0.20
         lSAC:=.T.
      ENDIF
   ENDIF
ENDIF
IF lSAC
   oSAC:GOBOTTOM()
   nSAC:=oSAC:FIELDGET("SAC")
   nSAC++
   oSAC:APPEND()
   oSAC:FIELDPUT("SAC",nSAC)
   oSAC:FIELDPUT("DATA",Today())
   oSAC:FIELDPUT("RNC",oSERVER:FIELDGET("RNC"))
   oSAC:FIELDPUT("RASTRO",oSERVER:FIELDGET("RASTRO"))
   oSAC:FIELDPUT("CODIGO",oSERVER:FIELDGET("CODIGO"))
   oSAC:FIELDPUT("NOME",oSERVER:FIELDGET("DESCRI"))
   oSAC:FIELDPUT("TIPO","P")
   oSAC:FIELDPUT("QTL",oSERVER:FIELDGET("QTL"))
   oSAC:FIELDPUT("QTN",oSERVER:FIELDGET("QTLN"))
   oSAC:FIELDPUT("CLIENTE",oSERVER:FIELDGET("CLIFOR"))
   oSAC:FIELDPUT("CLINOME",oSERVER:FIELDGET("NOME"))
   oSAC:FIELDPUT("DESC01",SELF:DEC01)
   oSAC:FIELDPUT("DESC02",SELF:DEC02)
   oSAC:FIELDPUT("DESC03",SELF:DEC03)
   oSAC:FIELDPUT("INCUSER",ZUSER)
   OSAC:FIELDPUT("INCDATA",Today())
   cCAUSA:=AllTrim(oSAC:FIELDGET("DESC01"))
   cCAUSA+="_"+AllTrim(oSAC:FIELDGET("DESC02"))	
   cCAUSA+="_"+AllTrim(oSAC:FIELDGET("DESC03"))	
   cCAUSA+="_"+AllTrim(oSAC:FIELDGET("DESC04"))	
   ENVIARsac(nSAC,oSAC:FIELDGET("CODIGO"),oSAC:FIELDGET("CLIENTE"),cCAUSA)	

   oSAC:CLOSE()
   oSERVER:FIELDPUT("NSAC",nSAC)
ENDIF
oSERVER:CLOSE()
aCAMPOS:={}
AAdd(aCAMPOS,SELF:CLIFOR)
AAdd(aCAMPOS,SELF:NOME)
AAdd(aCAMPOS,SELF:CODIGO)
AAdd(aCAMPOS,SELF:DESCRI)
AAdd(Acampos,0)
AAdd(aCAMPOS,nRNC)
AAdd(Acampos,Today())
AAdd(aCAMPOS,nSAC)
AAdd(aCAMPOS,"")
NOVOCNQ(aCAMPOS)
ENVIARNC(NRNC,"Processo",SELF:CODIGO,{SELF:DEC01,SELF:DEC02,SELF:DEC03})	
DIGANUM(nRNC,nRACF,nSAC)
SELF:ENDWINDOW()
		

METHOD PEGCLI( ) 
LOCAL aCLI AS ARRAY	
aCLI:=PEGMA01(SELF:CLIFOR,ZCURINI,ZCURDIR)
IF aCLI[1]=.T.
   SELF:NOME:=aCLI[2]
ENDIF
	

METHOD PEGCOD( ) 
LOCAL aPRO	
aPRO:=PEGMS01(SELF:CODIGO)
IF aPRO[1]=.T. .AND. ! Empty(aPRO[2])
   SELF:DESCRI:=aPRO[2]
ENDIF	

METHOD btnPEGMP04( ) 
LOCAL aTEC AS ARRAY
LOCAL ACOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
aTEC:=PEGMP04(SELF:ABRNUM,ZCURINI,ZCURDIR,ACOM)
IF aTEC[1]=.T.
   SELF:ABRNOM:=aTEC[2]
ENDIF
	
	

METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
		   FabCenterWindow( SELF )
	RETURN NIL


ACCESS QTL
RETURN SELF:FieldGet( #QTL )

ASSIGN QTL( uValue )
SELF:FieldPut( #QTL , uValue )

ACCESS QTLN
RETURN SELF:FieldGet( #QTLN )

ASSIGN QTLN( uValue )
SELF:FieldPut( #QTLN , uValue )

ACCESS RASTRO
RETURN SELF:FieldGet( #RASTRO )

ASSIGN RASTRO( uValue )
SELF:FieldPut( #RASTRO , uValue )

ACCESS REVI
RETURN SELF:FieldGet( #REVI )

ASSIGN REVI( uValue )
SELF:FieldPut( #REVI , uValue )

ACCESS TIPERR
RETURN SELF:FieldGet( #TIPERR )

ASSIGN TIPERR( uValue )
SELF:FieldPut( #TIPERR , uValue )

END CLASS
STATIC DEFINE JRNCPI_BTNPEGMP04 := 132
