#region DEFINES
STATIC DEFINE JRNCRI_ABRNOM := 117
STATIC DEFINE JRNCRI_ABRNUM := 116
STATIC DEFINE JRNCRI_CANCELAR := 154
STATIC DEFINE JRNCRI_CBUSCA := 102
STATIC DEFINE JRNCRI_CLIFOR := 114
STATIC DEFINE JRNCRI_CODIGO := 104
STATIC DEFINE JRNCRI_CRM := 100
STATIC DEFINE JRNCRI_DEC01 := 118
STATIC DEFINE JRNCRI_DEC02 := 119
STATIC DEFINE JRNCRI_DEC03 := 120
STATIC DEFINE JRNCRI_DESCE := 103
STATIC DEFINE JRNCRI_DESCRI := 105
STATIC DEFINE JRNCRI_DISPO := 135
STATIC DEFINE JRNCRI_ESCCOD := 149
STATIC DEFINE JRNCRI_ESCFOR := 125
STATIC DEFINE JRNCRI_ESCRES := 122
STATIC DEFINE JRNCRI_FOTO := 158
STATIC DEFINE JRNCRI_FT26 := 148
STATIC DEFINE JRNCRI_GB1 := 132
STATIC DEFINE JRNCRI_IMPORTAR := 137
STATIC DEFINE JRNCRI_IMPRASTRO := 146
STATIC DEFINE JRNCRI_NFC := 109
STATIC DEFINE JRNCRI_NOME := 115
STATIC DEFINE JRNCRI_OFC := 108
STATIC DEFINE JRNCRI_OK := 156
STATIC DEFINE JRNCRI_PED := 107
STATIC DEFINE JRNCRI_PEGCOD := 150
STATIC DEFINE JRNCRI_PEGFOR := 151
STATIC DEFINE JRNCRI_PEGMP04 := 152 
STATIC DEFINE JRNCRI_QTL := 110
STATIC DEFINE JRNCRI_QTLD1 := 112
STATIC DEFINE JRNCRI_QTLN := 111
STATIC DEFINE JRNCRI_RASTRO := 101
STATIC DEFINE JRNCRI_RB10 := 141
STATIC DEFINE JRNCRI_RB11 := 140
STATIC DEFINE JRNCRI_RB12 := 139
STATIC DEFINE JRNCRI_RB13 := 138
STATIC DEFINE JRNCRI_RB14 := 134
STATIC DEFINE JRNCRI_RB15 := 142
STATIC DEFINE JRNCRI_RB9 := 133
STATIC DEFINE JRNCRI_REVI := 106
STATIC DEFINE JRNCRI_SC_CODIGO := 131
STATIC DEFINE JRNCRI_SC_DESCRI := 130
STATIC DEFINE JRNCRI_SC_DESCRI1 := 144
STATIC DEFINE JRNCRI_SC_DESTINO2 := 157
STATIC DEFINE JRNCRI_SC_NFC := 124
STATIC DEFINE JRNCRI_SC_NOME := 126
STATIC DEFINE JRNCRI_SC_OFC := 127
STATIC DEFINE JRNCRI_SC_PED := 147
STATIC DEFINE JRNCRI_SC_QTL2 := 121
STATIC DEFINE JRNCRI_SC_QTL3 := 145
STATIC DEFINE JRNCRI_SC_QTL4 := 159
STATIC DEFINE JRNCRI_SC_RASTRO := 128
STATIC DEFINE JRNCRI_SC_REVI := 129
STATIC DEFINE JRNCRI_SC_REVI1 := 136
STATIC DEFINE JRNCRI_SC_SETOR1 := 123
STATIC DEFINE JRNCRI_THEFIXEDTEXT11 := 155
STATIC DEFINE JRNCRI_THEFIXEDTEXT9 := 153
STATIC DEFINE JRNCRI_TIPOE := 143
STATIC DEFINE JRNCRI_UNID := 113
#endregion

PARTIAL CLASS JRNCRI INHERIT DATADIALOG
PROTECT oDCCRM AS rightSle
PROTECT oDCRASTRO AS SINGLELINEEDIT
PROTECT oDCCBUSCA AS SINGLELINEEDIT
PROTECT oDCDESCE AS SINGLELINEEDIT
PROTECT oDCCODIGO AS SINGLELINEEDIT
PROTECT oDCDESCRI AS SINGLELINEEDIT
PROTECT oDCREVI AS SINGLELINEEDIT
PROTECT oDCPED AS SINGLELINEEDIT
PROTECT oDCOFC AS SINGLELINEEDIT
PROTECT oDCNFC AS SINGLELINEEDIT
PROTECT oDCQTL AS rightSle
PROTECT oDCQTLN AS rightSle
PROTECT oDCQTLD1 AS rightSle
PROTECT oDCUNID AS SINGLELINEEDIT
PROTECT oDCCLIFOR AS rightSle
PROTECT oDCNOME AS SINGLELINEEDIT
PROTECT oDCABRNUM AS rightSle
PROTECT oDCABRNOM AS SINGLELINEEDIT
PROTECT oDCDEC01 AS SINGLELINEEDIT
PROTECT oDCDEC02 AS SINGLELINEEDIT
PROTECT oDCDEC03 AS SINGLELINEEDIT
PROTECT oDCSC_QTL2 AS FIXEDTEXT
PROTECT oCCESCRES AS PUSHBUTTON
PROTECT oDCSC_SETOR1 AS FIXEDTEXT
PROTECT oDCSC_NFC AS FIXEDTEXT
PROTECT oCCESCFOR AS PUSHBUTTON
PROTECT oDCSC_NOME AS FIXEDTEXT
PROTECT oDCSC_OFC AS FIXEDTEXT
PROTECT oDCSC_RASTRO AS FIXEDTEXT
PROTECT oDCSC_REVI AS FIXEDTEXT
PROTECT oDCSC_DESCRI AS FIXEDTEXT
PROTECT oDCSC_CODIGO AS FIXEDTEXT
PROTECT oDCGB1 AS GROUPBOX
PROTECT oCCRB9 AS RADIOBUTTON
PROTECT oCCRB14 AS RADIOBUTTON
PROTECT oDCDISPO AS RADIOBUTTONGROUP
PROTECT oDCSC_REVI1 AS FIXEDTEXT
PROTECT oCCImportar AS PUSHBUTTON
PROTECT oCCRB13 AS RADIOBUTTON
PROTECT oCCRB12 AS RADIOBUTTON
PROTECT oCCRB11 AS RADIOBUTTON
PROTECT oCCRB10 AS RADIOBUTTON
PROTECT oCCRB15 AS RADIOBUTTON
PROTECT oDCTIPOE AS RADIOBUTTONGROUP
PROTECT oDCSC_DESCRI1 AS FIXEDTEXT
PROTECT oDCSC_QTL3 AS FIXEDTEXT
PROTECT oCCImprastro AS PUSHBUTTON
PROTECT oDCSC_PED AS FIXEDTEXT
PROTECT oDCFT26 AS FIXEDTEXT
PROTECT oCCesccod AS PUSHBUTTON
PROTECT oCCpegcod AS PUSHBUTTON
PROTECT oCCpegfor AS PUSHBUTTON
PROTECT oCCbtnpegmp04 AS PUSHBUTTON
PROTECT oDCtheFixedText9 AS FIXEDTEXT
PROTECT oCCcancelar AS PUSHBUTTON
PROTECT oDCtheFixedText11 AS FIXEDTEXT
PROTECT oCCOK AS PUSHBUTTON
PROTECT oDCSC_DESTINO2 AS FIXEDTEXT
PROTECT oCCfoto AS PUSHBUTTON
PROTECT oDCSC_QTL4 AS FIXEDTEXT

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS ABRNOM
RETURN SELF:FieldGet( #ABRNOM )

ASSIGN ABRNOM( uValue )
SELF:FieldPut( #ABRNOM , uValue )

ACCESS ABRNUM
RETURN SELF:FieldGet( #ABRNUM )

ASSIGN ABRNUM( uValue )
SELF:FieldPut( #ABRNUM , uValue )

METHOD cancelar( ) 
	SELF:EndWindow()

ACCESS CBUSCA
RETURN SELF:FieldGet( #CBUSCA )

ASSIGN CBUSCA( uValue )
SELF:FieldPut( #CBUSCA , uValue )

ACCESS CLIFOR
RETURN SELF:FieldGet( #CLIFOR )

ASSIGN CLIFOR( uValue )
SELF:FieldPut( #CLIFOR , uValue )

ACCESS CODIGO
RETURN SELF:FieldGet( #CODIGO )

ASSIGN CODIGO( uValue )
SELF:FieldPut( #CODIGO , uValue )

ACCESS CRM
RETURN SELF:FieldGet( #CRM )

ASSIGN CRM( uValue )
SELF:FieldPut( #CRM , uValue )

ACCESS DEC01
RETURN SELF:FieldGet( #DEC01 )

ASSIGN DEC01( uValue )
SELF:FieldPut( #DEC01 , uValue )

ACCESS DEC02
RETURN SELF:FieldGet( #DEC02 )

ASSIGN DEC02( uValue )
SELF:FieldPut( #DEC02 , uValue )

ACCESS DEC03
RETURN SELF:FieldGet( #DEC03 )

ASSIGN DEC03( uValue )
SELF:FieldPut( #DEC03 , uValue )

ACCESS DESCE
RETURN SELF:FieldGet( #DESCE )

ASSIGN DESCE( uValue )
SELF:FieldPut( #DESCE , uValue )

ACCESS DESCRI
RETURN SELF:FieldGet( #DESCRI )

ASSIGN DESCRI( uValue )
SELF:FieldPut( #DESCRI , uValue )

ACCESS DISPO
RETURN SELF:FieldGet( #DISPO )

ASSIGN DISPO( uValue )
SELF:FieldPut( #DISPO , uValue )

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:CODIGO)
    SELF:CODIGO:=oESC:CODIGO
    SELF:DESCRI:=oESC:NOME
ENDIF			

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MB01.DBF"}
oESC:SHOW()	
IF ! IsNil(oESC:NUMERO)
	SELF:CLIFOR:=oESC:NUMERO
	SELF:NOME:=oESC:NOME
ENDIF

METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:ABRNUM:=oESCMP04:NUMERO
   SELF:ABRNOM:=oESCMP04:NOME
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:oDCCODIGO:TextValue)," ",""))

IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()
		

METHOD IMPORTAR( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF	
oSERVER:GOTOP()
IF oSERVER:SEEK(SELF:CRM)
   SELF:CBUSCA:=oSERVER:FIELDGET("CBUSCA")
   SELF:CLIFOR:=oSERVER:FIELDGET("CLIFOR")
   SELF:CODIGO:=oSERVER:FIELDGET("APLICACAO")
   SELF:DESCE:=oSERVER:FIELDGET("DESCRI")
   IF Empty(oSERVER:FIELDGET("NRNOTB"))
      SELF:NFC:=Str(oSERVER:FIELDGET("NRNOTA"),8)
   ELSE
      SELF:NFC:=Str(oSERVER:FIELDGET("NRNOTA"),8)+"/"+Str(oSERVER:FIELDGET("NRNOTB"),8)	
   ENDIF
   SELF:NOME:=oSERVER:FIELDGET("NOMEF")
   SELF:QTL:=oSERVER:FIELDGET("QTDE")
   SELF:UNID:=oSERVER:FIELDGET("UNID")
   SELF:PED:=oSERVER:FIELDGET("PEDIDO")
   SELF:RASTRO:=oSERVER:FIELDGET("RASTRO")
   SELF:TIPOE:=oSERVER:FIELDGET("TIPOE")
   aDAD:=PEGMS01(SELF:CODIGO)
   IF aDAD[1]=.T. .AND. ! Empty(aDAD[2])
      SELF:DESCRI:=aDAD[2]
   ENDIF
ENDIF
oSERVER:CLOSE()



	

METHOD Imprastro( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF	
oSERVER:SetOrder(3)   //Diferente
oSERVER:GOTOP()
IF oSERVER:SEEK(AllTrim(SELF:RASTRO))   //diferente
   SELF:CBUSCA:=oSERVER:FIELDGET("CBUSCA")
   SELF:CLIFOR:=oSERVER:FIELDGET("CLIFOR")
   SELF:CODIGO:=oSERVER:FIELDGET("APLICACAO")
   SELF:DESCE:=oSERVER:FIELDGET("DESCRI")
   IF Empty(oSERVER:FIELDGET("NRNOTB"))
      SELF:NFC:=Str(oSERVER:FIELDGET("NRNOTA"),8)
   ELSE
      SELF:NFC:=Str(oSERVER:FIELDGET("NRNOTA"),8)+"/"+Str(oSERVER:FIELDGET("NRNOTB"),8)	
   ENDIF
   SELF:NOME:=oSERVER:FIELDGET("NOMEF")
   SELF:QTL:=oSERVER:FIELDGET("QTDE")
   SELF:CRM:=oSERVER:FIELDGET("CRM")  //Diferente
   SELF:UNID:=oSERVER:FIELDGET("UNID")
   SELF:PED:=oSERVER:FIELDGET("PEDIDO")
   SELF:TIPOE:=oSERVER:FIELDGET("TIPOE")
   aDAD:=PEGMS01(SELF:CODIGO)
   IF aDAD[1]=.T. .AND. ! Empty(adad[2])
      SELF:DESCRI:=aDAD[2]
   ENDIF
ENDIF
oSERVER:CLOSE()
	

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JRNCRI" , _GetInst()},iCtlID)

	SELF:oDCCRM := rightSle{SELF , ResourceID{ JRNCRI_CRM  , _GetInst() } }
	SELF:oDCCRM:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCCRM:HyperLabel := HyperLabel{#CRM , "CRM" , NULL_STRING , "RNC_REVI"}

	SELF:oDCRASTRO := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_RASTRO  , _GetInst() } }
	SELF:oDCRASTRO:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCRASTRO:HyperLabel := HyperLabel{#RASTRO , "Rastro:" , NULL_STRING , "RNC_RASTRO"}

	SELF:oDCCBUSCA := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_CBUSCA  , _GetInst() } }
	SELF:oDCCBUSCA:FieldSpec := PADRAO_CHAR_24{}
	SELF:oDCCBUSCA:HyperLabel := HyperLabel{#CBUSCA , "Codigo:" , NULL_STRING , "RNC_CODIGO"}

	SELF:oDCDESCE := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_DESCE  , _GetInst() } }
	SELF:oDCDESCE:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCDESCE:HyperLabel := HyperLabel{#DESCE , "Descriçào:" , NULL_STRING , "CRM_DESCRI"}

	SELF:oDCCODIGO := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_CODIGO  , _GetInst() } }
	SELF:oDCCODIGO:FieldSpec := PADRAO_CHAR_24{}
	SELF:oDCCODIGO:HyperLabel := HyperLabel{#CODIGO , "Codigo:" , NULL_STRING , "RNC_CODIGO"}

	SELF:oDCDESCRI := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_DESCRI  , _GetInst() } }
	SELF:oDCDESCRI:FieldSpec := PADRAO_CHAR_30{}
	SELF:oDCDESCRI:HyperLabel := HyperLabel{#DESCRI , "Descri:" , NULL_STRING , "RNC_DESCRI"}

	SELF:oDCREVI := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_REVI  , _GetInst() } }
	SELF:oDCREVI:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCREVI:HyperLabel := HyperLabel{#REVI , "Revi:" , NULL_STRING , "RNC_REVI"}

	SELF:oDCPED := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_PED  , _GetInst() } }
	SELF:oDCPED:FieldSpec := PAdrao_char_20{}
	SELF:oDCPED:HyperLabel := HyperLabel{#PED , "Ped:" , NULL_STRING , "RNC_PED"}

	SELF:oDCOFC := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_OFC  , _GetInst() } }
	SELF:oDCOFC:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCOFC:HyperLabel := HyperLabel{#OFC , "Ofc:" , NULL_STRING , "RNC_OFC"}

	SELF:oDCNFC := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_NFC  , _GetInst() } }
	SELF:oDCNFC:FieldSpec := PADRAO_CHAR_20{}
	SELF:oDCNFC:HyperLabel := HyperLabel{#NFC , "Nfc:" , NULL_STRING , "RNC_NFC"}

	SELF:oDCQTL := rightSle{SELF , ResourceID{ JRNCRI_QTL  , _GetInst() } }
	SELF:oDCQTL:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTL:HyperLabel := HyperLabel{#QTL , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oDCQTLN := rightSle{SELF , ResourceID{ JRNCRI_QTLN  , _GetInst() } }
	SELF:oDCQTLN:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTLN:HyperLabel := HyperLabel{#QTLN , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oDCQTLD1 := rightSle{SELF , ResourceID{ JRNCRI_QTLD1  , _GetInst() } }
	SELF:oDCQTLD1:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCQTLD1:HyperLabel := HyperLabel{#QTLD1 , "Qtl:" , NULL_STRING , "RNC_QTL"}

	SELF:oDCUNID := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_UNID  , _GetInst() } }
	SELF:oDCUNID:FieldSpec := PADRAO_CHAR_02{}
	SELF:oDCUNID:HyperLabel := HyperLabel{#UNID , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCCLIFOR := rightSle{SELF , ResourceID{ JRNCRI_CLIFOR  , _GetInst() } }
	SELF:oDCCLIFOR:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCCLIFOR:HyperLabel := HyperLabel{#CLIFOR , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCNOME := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_NOME  , _GetInst() } }
	SELF:oDCNOME:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCNOME:HyperLabel := HyperLabel{#NOME , "Nome:" , NULL_STRING , "RNC_NOME"}

	SELF:oDCABRNUM := rightSle{SELF , ResourceID{ JRNCRI_ABRNUM  , _GetInst() } }
	SELF:oDCABRNUM:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCABRNUM:HyperLabel := HyperLabel{#ABRNUM , "Abrnum:" , NULL_STRING , "RNC_ABRNUM"}

	SELF:oDCABRNOM := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_ABRNOM  , _GetInst() } }
	SELF:oDCABRNOM:FieldSpec := PADRAO_CHAR_40{}
	SELF:oDCABRNOM:HyperLabel := HyperLabel{#ABRNOM , "Abrnom:" , NULL_STRING , "RNC_ABRNOM"}

	SELF:oDCDEC01 := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_DEC01  , _GetInst() } }
	SELF:oDCDEC01:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC01:HyperLabel := HyperLabel{#DEC01 , "Dec01:" , NULL_STRING , "RNC_DEC01"}

	SELF:oDCDEC02 := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_DEC02  , _GetInst() } }
	SELF:oDCDEC02:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC02:HyperLabel := HyperLabel{#DEC02 , "Dec02:" , NULL_STRING , "RNC_DEC02"}

	SELF:oDCDEC03 := SINGLELINEEDIT{SELF , ResourceID{ JRNCRI_DEC03  , _GetInst() } }
	SELF:oDCDEC03:FieldSpec := PADRAO_CHAR_100{}
	SELF:oDCDEC03:HyperLabel := HyperLabel{#DEC03 , "Dec03:" , NULL_STRING , "RNC_DEC03"}

	SELF:oDCSC_QTL2 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_QTL2  , _GetInst() } }
	SELF:oDCSC_QTL2:HyperLabel := HyperLabel{#SC_QTL2 , "Qtde N/C Dev:" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES := PUSHBUTTON{SELF , ResourceID{ JRNCRI_ESCRES  , _GetInst() } }
	SELF:oCCESCRES:HyperLabel := HyperLabel{#ESCRES , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SETOR1 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_SETOR1  , _GetInst() } }
	SELF:oDCSC_SETOR1:HyperLabel := HyperLabel{#SC_SETOR1 , "Aberto Por" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NFC := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_NFC  , _GetInst() } }
	SELF:oDCSC_NFC:HyperLabel := HyperLabel{#SC_NFC , "Nota Fiscal " , NULL_STRING , NULL_STRING}

	SELF:oCCESCFOR := PUSHBUTTON{SELF , ResourceID{ JRNCRI_ESCFOR  , _GetInst() } }
	SELF:oCCESCFOR:HyperLabel := HyperLabel{#ESCFOR , "..." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NOME := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_NOME  , _GetInst() } }
	SELF:oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME , "Fornecedor" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_OFC := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_OFC  , _GetInst() } }
	SELF:oDCSC_OFC:HyperLabel := HyperLabel{#SC_OFC , "O.F." , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RASTRO := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_RASTRO  , _GetInst() } }
	SELF:oDCSC_RASTRO:HyperLabel := HyperLabel{#SC_RASTRO , "Rastro:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_REVI := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_REVI  , _GetInst() } }
	SELF:oDCSC_REVI:HyperLabel := HyperLabel{#SC_REVI , "Revisão:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESCRI := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_DESCRI  , _GetInst() } }
	SELF:oDCSC_DESCRI:HyperLabel := HyperLabel{#SC_DESCRI , "Descrição:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CODIGO := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_CODIGO  , _GetInst() } }
	SELF:oDCSC_CODIGO:HyperLabel := HyperLabel{#SC_CODIGO , "Codigo/Aplicação" , NULL_STRING , NULL_STRING}

	SELF:oDCGB1 := GROUPBOX{SELF , ResourceID{ JRNCRI_GB1  , _GetInst() } }
	SELF:oDCGB1:HyperLabel := HyperLabel{#GB1 , "Descrição do Problema" , NULL_STRING , NULL_STRING}

	SELF:oCCRB9 := RADIOBUTTON{SELF , ResourceID{ JRNCRI_RB9  , _GetInst() } }
	SELF:oCCRB9:HyperLabel := HyperLabel{#RB9 , "Devolver ao Fornecedor" , NULL_STRING , NULL_STRING}

	SELF:oCCRB14 := RADIOBUTTON{SELF , ResourceID{ JRNCRI_RB14  , _GetInst() } }
	SELF:oCCRB14:HyperLabel := HyperLabel{#RB14 , "Seleção" , NULL_STRING , NULL_STRING}

	SELF:oDCDISPO := RADIOBUTTONGROUP{SELF , ResourceID{ JRNCRI_DISPO  , _GetInst() } }
	SELF:oDCDISPO:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCDISPO:HyperLabel := HyperLabel{#DISPO , "Disposição" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_REVI1 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_REVI1  , _GetInst() } }
	SELF:oDCSC_REVI1:HyperLabel := HyperLabel{#SC_REVI1 , "CRM" , NULL_STRING , NULL_STRING}

	SELF:oCCImportar := PUSHBUTTON{SELF , ResourceID{ JRNCRI_IMPORTAR  , _GetInst() } }
	SELF:oCCImportar:HyperLabel := HyperLabel{#Importar , "Imp" , NULL_STRING , NULL_STRING}

	SELF:oCCRB13 := RADIOBUTTON{SELF , ResourceID{ JRNCRI_RB13  , _GetInst() } }
	SELF:oCCRB13:HyperLabel := HyperLabel{#RB13 , "Outros" , NULL_STRING , NULL_STRING}

	SELF:oCCRB12 := RADIOBUTTON{SELF , ResourceID{ JRNCRI_RB12  , _GetInst() } }
	SELF:oCCRB12:HyperLabel := HyperLabel{#RB12 , "Matéria Prima" , NULL_STRING , NULL_STRING}

	SELF:oCCRB11 := RADIOBUTTON{SELF , ResourceID{ JRNCRI_RB11  , _GetInst() } }
	SELF:oCCRB11:HyperLabel := HyperLabel{#RB11 , "Componente" , NULL_STRING , NULL_STRING}

	SELF:oCCRB10 := RADIOBUTTON{SELF , ResourceID{ JRNCRI_RB10  , _GetInst() } }
	SELF:oCCRB10:HyperLabel := HyperLabel{#RB10 , "Tratamento./Terceiro" , NULL_STRING , NULL_STRING}

	SELF:oCCRB15 := RADIOBUTTON{SELF , ResourceID{ JRNCRI_RB15  , _GetInst() } }
	SELF:oCCRB15:HyperLabel := HyperLabel{#RB15 , "Produto" , NULL_STRING , NULL_STRING}

	SELF:oDCTIPOE := RADIOBUTTONGROUP{SELF , ResourceID{ JRNCRI_TIPOE  , _GetInst() } }
	SELF:oDCTIPOE:FieldSpec := PADRAO_CHAR_01{}
	SELF:oDCTIPOE:HyperLabel := HyperLabel{#TIPOE , "Tipo de Entrada" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESCRI1 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_DESCRI1  , _GetInst() } }
	SELF:oDCSC_DESCRI1:HyperLabel := HyperLabel{#SC_DESCRI1 , "Codigo" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTL3 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_QTL3  , _GetInst() } }
	SELF:oDCSC_QTL3:HyperLabel := HyperLabel{#SC_QTL3 , "Qtde Lote" , NULL_STRING , NULL_STRING}

	SELF:oCCImprastro := PUSHBUTTON{SELF , ResourceID{ JRNCRI_IMPRASTRO  , _GetInst() } }
	SELF:oCCImprastro:HyperLabel := HyperLabel{#Imprastro , "Imp" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_PED := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_PED  , _GetInst() } }
	SELF:oDCSC_PED:HyperLabel := HyperLabel{#SC_PED , "Pedido No.:" , NULL_STRING , NULL_STRING}

	SELF:oDCFT26 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_FT26  , _GetInst() } }
	SELF:oDCFT26:HyperLabel := HyperLabel{#FT26 , "Unid." , NULL_STRING , NULL_STRING}

	SELF:oCCesccod := PUSHBUTTON{SELF , ResourceID{ JRNCRI_ESCCOD  , _GetInst() } }
	SELF:oCCesccod:HyperLabel := HyperLabel{#esccod , "..." , NULL_STRING , NULL_STRING}

	SELF:oCCpegcod := PUSHBUTTON{SELF , ResourceID{ JRNCRI_PEGCOD  , _GetInst() } }
	SELF:oCCpegcod:HyperLabel := HyperLabel{#pegcod , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCpegfor := PUSHBUTTON{SELF , ResourceID{ JRNCRI_PEGFOR  , _GetInst() } }
	SELF:oCCpegfor:HyperLabel := HyperLabel{#pegfor , "-->" , NULL_STRING , NULL_STRING}

	SELF:oCCbtnpegmp04 := PUSHBUTTON{SELF , ResourceID{ JRNCRI_BTNPEGMP04  , _GetInst() } }
	SELF:oCCbtnpegmp04:HyperLabel := HyperLabel{#btnpegmp04 , "-->" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText9 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_THEFIXEDTEXT9  , _GetInst() } }
	SELF:oDCtheFixedText9:HyperLabel := HyperLabel{#theFixedText9 , "Cancelar" , NULL_STRING , NULL_STRING}

	SELF:oCCcancelar := PUSHBUTTON{SELF , ResourceID{ JRNCRI_CANCELAR  , _GetInst() } }
	SELF:oCCcancelar:Image := ico_sair{}
	SELF:oCCcancelar:HyperLabel := HyperLabel{#cancelar , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText11 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_THEFIXEDTEXT11  , _GetInst() } }
	SELF:oDCtheFixedText11:HyperLabel := HyperLabel{#theFixedText11 , "OK" , NULL_STRING , NULL_STRING}

	SELF:oCCOK := PUSHBUTTON{SELF , ResourceID{ JRNCRI_OK  , _GetInst() } }
	SELF:oCCOK:Image := ico_ok{}
	SELF:oCCOK:HyperLabel := HyperLabel{#OK , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO2 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_DESTINO2  , _GetInst() } }
	SELF:oDCSC_DESTINO2:HyperLabel := HyperLabel{#SC_DESTINO2 , "Foto" , NULL_STRING , NULL_STRING}

	SELF:oCCfoto := PUSHBUTTON{SELF , ResourceID{ JRNCRI_FOTO  , _GetInst() } }
	SELF:oCCfoto:Image := ico_camera{}
	SELF:oCCfoto:HyperLabel := HyperLabel{#foto , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_QTL4 := FIXEDTEXT{SELF , ResourceID{ JRNCRI_SC_QTL4  , _GetInst() } }
	SELF:oDCSC_QTL4:HyperLabel := HyperLabel{#SC_QTL4 , "Qtde Insp Calculo:" , NULL_STRING , NULL_STRING}

	SELF:oDCDISPO:FillUsing({ ;
	                        {SELF:oCCRB9, "D"}, ;
	                        {SELF:oCCRB14, "E"} ;
	                        })

	SELF:oDCTIPOE:FillUsing({ ;
	                        {SELF:oCCRB13, "X"}, ;
	                        {SELF:oCCRB12, "M"}, ;
	                        {SELF:oCCRB11, "C"}, ;
	                        {SELF:oCCRB10, "T"}, ;
	                        {SELF:oCCRB15, "P"} ;
	                        })

	SELF:Caption := "Fornecedor"
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#JRNCRI , "Fornecedor" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NFC
RETURN SELF:FieldGet( #NFC )

ASSIGN NFC( uValue )
SELF:FieldPut( #NFC , uValue )

ACCESS NOME
RETURN SELF:FieldGet( #NOME )

ASSIGN NOME( uValue )
SELF:FieldPut( #NOME , uValue )

ACCESS OFC
RETURN SELF:FieldGet( #OFC )

ASSIGN OFC( uValue )
SELF:FieldPut( #OFC , uValue )

METHOD OK() 
LOCAL oSERVER,oRACF AS USEREDE
LOCAL aDAD,aCAMPOS AS ARRAY
LOCAL nSAC,nRNC,nRACF AS DWORD

IF Empty(SELF:CLIFOR)
   alert("Fornecedor em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:NOME)
   alert("Nome Fornecedor em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:CODIGO)
   alert("Codigo Produto em Branco")	
   RETURN .f.
ENDIF
IF Empty(SELF:DESCRI)
   alert("Descriçao Produto em Branco")	
   RETURN .f.
ENDIF

nRNC:=0
nRACF:=0
nSAC:=0

aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF		
aDAD:={zCURINI,"RACF.DBF",zCURDIR}
oRACF:=USEREDE{aDAD}
IF oRACF:nERRO#0
   oSERVER:CLOSE()
   RETU SELF
ENDIF
oSERVER:GoBottom()
nRNC:=oSERVER:FIELDGET("RNC")
nRNC++
oSERVER:APPEND()
oSERVER:FIELDPUT("RNC",nRNC)
oSERVER:FIELDPUT("ABRNUM",SELF:ABRNUM)
oSERVER:FIELDPUT("ABRNOM",SELF:ABRNOM)
oSERVER:FIELDPUT("CBUSCA",SELF:CBUSCA)
oSERVER:FIELDPUT("CLIFOR",SELF:CLIFOR)
oSERVER:FIELDPUT("CODIGO",SELF:CODIGO)
oSERVER:FIELDPUT("CRM",SELF:CRM)
oSERVER:FIELDPUT("DEC01",SELF:DEC01)
oSERVER:FIELDPUT("DEC02",SELF:DEC02)
oSERVER:FIELDPUT("DEC03",SELF:DEC03)
oSERVER:FIELDPUT("DESCE",SELF:DESCE)
oSERVER:FIELDPUT("DESCRI",SELF:DESCRI)
oSERVER:FIELDPUT("DISPO",SELF:DISPO)
oSERVER:FIELDPUT("NFC",SELF:NFC)
oSERVER:FIELDPUT("NOME",SELF:NOME)
oSERVER:FIELDPUT("QTLN",SELF:QTld1) //Acompanha Mudanca RACF antes qtln
oSERVER:FIELDPUT("RASTRO",SELF:RASTRO)
oSERVER:FIELDPUT("REVI",SELF:REVI)
oSERVER:FIELDPUT("TIPOE",SELF:TIPOE)
oSERVER:FIELDPUT("OFC",SELF:OFC)
oSERVER:FIELDPUT("QTL",SELF:QTL)
oSERVER:FIELDPUT("PED",SELF:PED)
oSERVER:FIELDPUT("UNID",SELF:UNID)
oSERVER:FIELDPUT("CODRNC","R") //Recebimento
oSERVER:FIELDPUT("CODRET","X") //Nao Classificado
oSERVER:FIELDPUT("TIPERR","E") //Externo
oSERVER:FIELDPUT("TIPCAD","F") //Fornecedor
oSERVER:FIELDPUT("INCUSER",ZUSER)
OSERVER:FIELDPUT("INCDATA",Today())
OSERVER:FIELDPUT("DATA",Today())
oSERVER:FIELDPUT("FECHADA",.F.)
oRACF:GOBOTTOM()
nRACF:=oRACF:FIELDGET("RACF")
nRACF++
oRACF:APPEND()
oRACF:FIELDPUT("RACF",nRACF)
oRACF:FIELDPUT("DATA",Today())
oRACF:FIELDPUT("RNC",oSERVER:FIELDGET("RNC"))
oRACF:FIELDPUT("CRM",oSERVER:FIELDGET("CRM"))
oRACF:FIELDPUT("TIPOE",oSERVER:FIELDGET("TIPOE"))
oRACF:FIELDPUT("CBUSCA",oSERVER:FIELDGET("CBUSCA"))
oRACF:FIELDPUT("DESCRI",oSERVER:FIELDGET("DESCE"))
oRACF:FIELDPUT("FORNECEDO",oSERVER:FIELDGET("CLIFOR"))
oRACF:FIELDPUT("NOMEF",oSERVER:FIELDGET("NOME"))
oRACF:FIELDPUT("RASTRO",oSERVER:FIELDGET("RASTRO"))
oRACF:FIELDPUT("CNFFOR",oSERVER:FIELDGET("NFC"))
oRACF:FIELDPUT("DESENHO",oSERVER:FIELDGET("CODIGO"))
oRACF:FIELDPUT("DENO",oSERVER:FIELDGET("DESCRI"))
oRACF:FIELDPUT("QTL1",oSERVER:FIELDGET("QTL"))
oRACF:FIELDPUT("QTN1",oSERVER:FIELDGET("QTLN"))
oRACF:FIELDPUT("QTd1",SELF:QTLD1)
oRACF:FIELDPUT("UNID",oSERVER:FIELDGET("UNID"))
oRACF:FIELDPUT("CNFITA",oSERVER:FIELDGET("PED"))
oRACF:FIELDPUT("DESC01",oSERVER:FIELDGET("DEC01"))
oRACF:FIELDPUT("DESC02",oSERVER:FIELDGET("DEC02"))
oRACF:FIELDPUT("DESC03",oSERVER:FIELDGET("DEC03"))
oRACF:FIELDPUT("INCUSER",ZUSER)
ORACF:FIELDPUT("INCDATA",Today())
oRACF:CLOSE()
oSERVER:FIELDPUT("NRACF",nRACF)
oSERVER:CLOSE()
aCAMPOS:={}
AAdd(aCAMPOS,SELF:CLIFOR)
AAdd(aCAMPOS,SELF:NOME)
AAdd(aCAMPOS,SELF:CODIGO)
AAdd(aCAMPOS,SELF:DESCRI)
AAdd(Acampos,0)
AAdd(aCAMPOS,nRNC)
AAdd(Acampos,Today())
AAdd(aCAMPOS,nSAC)
AAdd(aCAMPOS,"")
NOVOCNQ(aCAMPOS)
ENVIARACF(nRNC,nRACF)
ENVIARNC(NRNC,"Recebimento",SELF:CODIGO,{SELF:DEC01,SELF:DEC02,SELF:DEC03})	
DIGANUM(nRNC,nRACF,nSAC)
SELF:EndWindow()


ACCESS PED
RETURN SELF:FieldGet( #PED )

ASSIGN PED( uValue )
SELF:FieldPut( #PED , uValue )

METHOD pegcod( ) 
LOCAL aDAD AS ARRAY	
aDAD:=PEGMS01(SELF:CODIGO)
IF aDAD[1]=.T. .AND. ! Empty(aDAD[2])
   SELF:DESCRI:=aDAD[2]
ENDIF
	

METHOD pegfor( ) 
LOCAL aDAD AS ARRAY	
aDAD:=PEGMB01(SELF:CLIFOR,ZCURINI,ZCURDIR)
IF aDAD[1]=.T.
   SELF:NOME:=aDAD[2]
ENDIF


METHOD btnPEGMP04( ) 
LOCAL aDAD AS ARRAY	
LOCAL ACOM AS ARRAY
aCOM:={zMES,zANO,ZEMPRESA}
aDAD:=PEGMP04(SELF:ABRNUM,ZCURINI,ZCURDIR,ACOM)
IF aDAD[1]=.T.
   SELF:ABRNOM:=aDAD[2]
ENDIF
	

METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
		   FabCenterWindow( SELF )
	RETURN NIL


ACCESS QTL
RETURN SELF:FieldGet( #QTL )

ASSIGN QTL( uValue )
SELF:FieldPut( #QTL , uValue )

ACCESS QTLD1
RETURN SELF:FieldGet( #QTLD1 )

ASSIGN QTLD1( uValue )
SELF:FieldPut( #QTLD1 , uValue )

ACCESS QTLN
RETURN SELF:FieldGet( #QTLN )

ASSIGN QTLN( uValue )
SELF:FieldPut( #QTLN , uValue )

ACCESS RASTRO
RETURN SELF:FieldGet( #RASTRO )

ASSIGN RASTRO( uValue )
SELF:FieldPut( #RASTRO , uValue )

ACCESS REVI
RETURN SELF:FieldGet( #REVI )

ASSIGN REVI( uValue )
SELF:FieldPut( #REVI , uValue )

ACCESS TIPOE
RETURN SELF:FieldGet( #TIPOE )

ASSIGN TIPOE( uValue )
SELF:FieldPut( #TIPOE , uValue )

ACCESS UNID
RETURN SELF:FieldGet( #UNID )

ASSIGN UNID( uValue )
SELF:FieldPut( #UNID , uValue )

END CLASS
STATIC DEFINE JRNCRI_BTNPEGMP04 := 152
