CLASS XINDEXAR INHERIT INDEXAR

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("TGQ",14)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	

METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}

//IQF
CRIANTX({ZCURINI,"CRFT.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRFA.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRFOR.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRDIAS.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRSEQ.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RACFSAL.DBF",ZCURDIR})

//IQFIMPLX
CRIANTX({ZCURINI,"PE01TMP.DBF",ZCURDIR})


//SAC_RNC_RAT_RACF
CRIANTX({ZCURINI,"SAC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"SACI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RAT.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RATI.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RACF.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RNC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RNCI.DBF",ZCURDIR})

//Refugo
CRIANTX({ZCURINI,"CRRSSEQ.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRRSSET.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRRSERR.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRRSAPS.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRRSAPP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRRSAPC.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CRTS.DBF",ZCURDIR})

//Custo Nao qualidade
CRIANTX({ZCURINI,"ACPNC.DBF",ZCURDIR})

//Outros
CRIANTX({ZCURINI,"CAF.DBF",ZCURDIR})
CRIANTX({ZCURINI,"CFE.DBF",ZCURDIR})
CRIANTX({ZCURINI,"MSRD.DBF",ZCURDIR})

//Analise de Peças Devolvidas
CRIANTX({ZCURINI,"ADP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"ADPI.DBF",ZCURDIR})

SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()	

END CLASS
CLASS XJADP INHERIT JADP	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",34)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ADP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ADPI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJADPI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJADPI,"ADP")
SELF:SHOW()		

END CLASS
CLASS XJANCLI INHERIT JANCLI

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("TGQ",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MA01.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:oDCCODIGO:ENABLE()
SELF:SHOW()			


END CLASS
CLASS XJCAF INHERIT JCAF	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",30)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MB01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"CAF.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJCAFI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJCAFI,"NUMERO")
SELF:SHOW()			

END CLASS
CLASS XJCFE INHERIT JCFE

CONSTRUCTOR(oOWNER) 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE	
IF ! entramenu("TGQ",6)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CFE.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		


END CLASS
CLASS XJCNG INHERIT JCNG

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("TGQ",32)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:SHOW()			


END CLASS
CLASS XJCNQ INHERIT JCNQ	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",31)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ACPNC.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			

END CLASS
CLASS XJCNQDEP INHERIT JCNQDEP		

CONSTRUCTOR(oOWNER) 
IF ! entramenu("TGQ",31)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:mes:=StrZero(Month(Today()),2)
SELF:ANO:=StrZero(Year(Today()),4)
SELF:oCCGravar:DISABLE()
SELF:oDCvalor:DISABLE()
SELF:SHOW()			


END CLASS
PARTIAL CLASS XJCRSEQ INHERIT JTLP

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
//,oSERVE2,oSERVE3 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("TGQ",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRSEQ.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
//aDAD:={zCURINI,"CRDIAS.DBF",zCURDIR}
//oSERVE2:=USEREDE{aDAD}
//IF oSERVE2:nERRO#0
//	oSERVER:Close() //Fecha Master
//   RETU SELF
//ENDIF
//aDAD:={zCURINI,"CRFOR.DBF",zCURDIR}
//oSERVE3:=USEREDE{aDAD}
//IF oSERVE3:nERRO#0
//   oSERVE2:Close()
//   oSERVER:Close() //Fecha Master
//   RETU SELF
//ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:OSFJCRDIAS:USE(oSERVE2)
//SELF:SetSelectiveRelation(oSFJCRDIAS,"SEQ")
//SELF:OSFJCRDIAS:VIEWTABLE()
//SELF:OSFJCRFOR:USE(oSERVE3)
//SELF:SetSelectiveRelation(oSFJCRFOR,"SEQ")
//SELF:OSFJCRFOR:VIEWTABLE()
SELF:SHOW()			

END CLASS
CLASS XJERR INHERIT JSET

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",4)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRRSERR.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:SHOW()			


END CLASS
CLASS xjfor INHERIT jfor

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MB01.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			



END CLASS
CLASS XJMAR INHERIT JMAR	

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("TGQ",29)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:SHOW()		

END CLASS
CLASS XJMP05 INHERIT JMP05

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",11)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MP05.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER)
SELF:USE(oSERVER)
SELF:SHOW()			

END CLASS
CLASS XJMSRD INHERIT JMSRD

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",36)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MSRD.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			

END CLASS
CLASS XJPRDSET INHERIT jprdset

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("TGQ",5)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MS01.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			


END CLASS
CLASS XJPRDSETI INHERIT jprdset	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("TGQ",5)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MS01X.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			

END CLASS
CLASS XJRACF INHERIT JRACF

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RACF.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		

END CLASS
CLASS XJRAT INHERIT JRAT

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",16)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RAT.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"RATI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:oSFJRATI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRATI,"RAT")
SELF:OSFJrati:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJRATI:viewtable()
SELF:SHOW()		

END CLASS
CLASS XJRNC INHERIT JRNC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",10)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"RNCI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJRNCI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRNCI,"RNC")
SELF:OSFJRNCI:VIEWTABLE()
SELF:OSFJRnci:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		

END CLASS
CLASS XJRNCCF INHERIT JRNCF

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL oBUSCA AS BUSCA
LOCAL oJAN AS JRNCF2
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",20)
	RETU SELF
ENDIF	
oBUSCA:=BUSCA{oOWNER}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU SELF	
ENDIF
nRNCTEMP:=Val(oBUSCA:cBUSCA)
aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
OSERVER:SETORDER(1)
OSERVER:GOTOP()
IF ! OSERVER:SEEK(nRNCTEMP)
   oSERVER:CLOSE()
   alert("RNC Não Encontrada","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("FECHADA")
   oSERVER:CLOSE()	
   alert("RNC Já Fechada","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("CODRNC")#"C"
   oSERVER:CLOSE()	
   alert("RNC Não é de Cliente","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("TIPERR")="E"
   oSERVER:CLOSE()		
   alert("RNC De Cliente Porem Externa","Erro")
   oJAN:=JRNCF2{SELF}
   oJAN:SHOW()
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("CODRET")#"D"
   oSERVER:CLOSE()		
   alert("RNC Não Devolução Retrabalho","Erro")
   oJAN:=JRNCF2{SELF}
   oJAN:SHOW()
   RETU SELF	
ENDIF
SUPER(oOWNER,,oSERVER)
aDAD:={zCURINI,"RNCI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SELF:OSFJRNCI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRNCI,"RNC")
SELF:OSFJRNCI:VIEWTABLE()
SELF:OSFJRnci:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			

END CLASS
CLASS XJRNCCI INHERIT JRNCCI	

CONSTRUCTOR(oOWNER) 
IF ! entramenu("TGQ",19)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:UNID:="PC"
SELF:ABRNUM:=ZFOLHA
SELF:ABRNOM:=ZNOMEFOLHA
SELF:SHOW()	

END CLASS
CLASS XJRNCFF INHERIT JRNCF	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL oBUSCA AS BUSCA
LOCAL aDAD AS ARRAY
LOCAL oJAN AS JRNCF2
IF ! ENTRAMENU("TGQ",20)
	RETU SELF
ENDIF	
oBUSCA:=BUSCA{oOWNER}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU SELF	
ENDIF
nRNCTEMP:=Val(oBUSCA:cBUSCA)
aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
OSERVER:SETORDER(1)
OSERVER:GOTOP()
IF ! OSERVER:SEEK(nRNCTEMP)
   oSERVER:CLOSE()
   alert("RNC Não Encontrada","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("FECHADA")
   oSERVER:CLOSE()	
   alert("RNC Já Fechada","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("CODRNC")#"F"
   oSERVER:CLOSE()	
   alert("RNC Não é de Final","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("TIPERR")="E"
   oSERVER:CLOSE()	
   alert("RNC De Final Porem Externa","Erro")	
   oJAN:=JRNCF2{SELF}
   oJAN:SHOW()	
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("DISPO")#"E"
   oSERVER:CLOSE()		
   alert("RNC Não é De Selecao","Erro")	
   oJAN:=JRNCF2{SELF}
   oJAN:SHOW()	
   RETU SELF	
ENDIF
SUPER(oOWNER,,oSERVER)
aDAD:={zCURINI,"RNCI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SELF:OSFJRNCI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRNCI,"RNC")
SELF:OSFJRNCI:VIEWTABLE()
SELF:OSFJRnci:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()			

END CLASS
CLASS XJRNCFI INHERIT JRNCFI		

CONSTRUCTOR(oOWNER) 
IF ! entramenu("TGQ",21)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:ABRNUM:=ZFOLHA
SELF:ABRNOM:=ZNOMEFOLHA
SELF:SHOW()	

END CLASS
CLASS XJRNCPF INHERIT JRNCF

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL oBUSCA AS BUSCA
LOCAL aDAD AS ARRAY
LOCAL oJAN AS JRNCF2
IF ! ENTRAMENU("TGQ",24)
	RETU SELF
ENDIF	
oBUSCA:=BUSCA{oOWNER}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU SELF	
ENDIF
nRNCTEMP:=Val(oBUSCA:cBUSCA)
aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
OSERVER:SETORDER(1)
OSERVER:GOTOP()
IF ! OSERVER:SEEK(nRNCTEMP)
   oSERVER:CLOSE()
   alert("RNC Não Encontrada","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("FECHADA")
   oSERVER:CLOSE()	
   alert("RNC Já Fechada","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("CODRNC")#"P"
   oSERVER:CLOSE()	
   alert("RNC Não é de Processo","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("TIPERR")="E"
   oSERVER:CLOSE()		
   alert("RNC De Final Porem Externa","Erro")	
   oJAN:=JRNCF2{SELF}
   oJAN:SHOW()	
   RETU SELF	
ENDIF
SUPER(oOWNER,,oSERVER)
aDAD:={zCURINI,"RNCI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SELF:OSFJRNCI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRNCI,"RNC")
SELF:OSFJRnci:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJRNCI:VIEWTABLE()
SELF:SHOW()			
	

			

END CLASS
CLASS XJRNCPI INHERIT JRNCPI

CONSTRUCTOR(oOWNER) 	
IF ! entramenu("TGQ",23)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:ABRNUM:=ZFOLHA
SELF:ABRNOM:=ZNOMEFOLHA
SELF:SHOW()		

END CLASS
CLASS XJRNCRF INHERIT JRNCRF

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL oBUSCA AS BUSCA
LOCAL oJAN AS JRNCF2
LOCAL cCOD,cTIP AS STRING
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",18)
	RETU SELF
ENDIF	
oBUSCA:=BUSCA{oOWNER}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU SELF	
ENDIF
nRNCTEMP:=Val(oBUSCA:cBUSCA)
aDAD:={zCURINI,"RNC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
OSERVER:SETORDER(1)
OSERVER:GOTOP()
IF ! OSERVER:SEEK(nRNCTEMP)
   oSERVER:CLOSE()
   alert("RNC Não Encontrada","Erro")
   RETU SELF	
ENDIF
IF oSERVER:FIELDGET("FECHADA")
   oSERVER:CLOSE()	
   alert("RNC Já Fechada","Erro")
   RETU SELF	
ENDIF
cCOD:=oSERVER:FIELDGET("CODRNC")
cTIP:=oSERVER:FIELDGET("DISPO")
IF cCOD#"R"
   oSERVER:CLOSE()	
   alert("RNC Não é de Recebimento","Erro")
   RETU SELF	
ENDIF
IF cTIP#"E"
   oSERVER:CLOSE()		
   alert("RNC Não é de Seleção","Erro")
   oJAN:=JRNCF2{SELF}
   oJAN:SHOW()
   RETU SELF	
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:SHOW()		

END CLASS
CLASS XJRNCRI INHERIT JRNCRI

CONSTRUCTOR(oOWNER) 
IF ! entramenu("TGQ",17)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:ABRNUM:=ZFOLHA
SELF:UNID:="PC"
SELF:ABRNOM:=ZNOMEFOLHA
SELF:SHOW()	

END CLASS
CLASS XJSAC INHERIT JSAC

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"SAC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"SACI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJSACI:USE(oSERVE2)
SELF:oSFJSACI:ViewTable()
SELF:SetSelectiveRelation(oSFJSACI,"SAC")
SELF:SHOW()		


END CLASS
CLASS XJSET INHERIT JSET

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",25)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRRSSET.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:SHOW()			

END CLASS
CLASS XJTLP INHERIT JCRRSSEQ

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("TGQ",5)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRRSSEQ.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		



END CLASS
CLASS ZJPRO INHERIT XJPRO	
CONSTRUCTOR(oOWNER) 
IF ! entramenu("TGQ",12)
	RETU SELF
ENDIF	
SUPER(oOWNER,"",zcurINI,zcurDIR,adir)
SELF:SHOW()			
END CLASS
