CLASS XJCRGEC INHERIT ZJCRGEX	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",10)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRGEC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(GBSREADONLY)
SELF:SHOW()	


END CLASS
CLASS XJCRGEX INHERIT ZJCRGEX

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",10)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRGEX.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(GBSREADONLY)
SELF:SHOW()	


END CLASS
CLASS ZJCRGEX INHERIT JCRGEX

METHOD APPEND() 
LOCAL nCRGEX AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nCRGEX:=SELF:Server:CRGEX
nCRGEX++
SUPER:append()
SELF:SERVER:FIELDPUT("CRGEX",nCRGEX)
SELF:SERVER:FIELDPUT("DATA",Today())
RETURN SELF

METHOD buscacrm( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CRM","CREX")	

METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD EditFocusChange(oEditFocusChangeEvent) 
	LOCAL oControl AS Control
	//LOCAL lGotFocus AS LOGIC
	oControl := IIf(oEditFocusChangeEvent == NULL_OBJECT, NULL_OBJECT, oEditFocusChangeEvent:Control)
	 IIf(oEditFocusChangeEvent == NULL_OBJECT, FALSE, oEditFocusChangeEvent:GotFocus) //   lGotFocus :=
	SUPER:EditFocusChange(oEditFocusChangeEvent)	
	//Put your changes here
	IF oCONTROL:NAMESYM==#PESOEC .OR. oCONTROL:NAMESYM==#PESONF
	  IF ValType(SELF:SERVER:FIELDGET("PESOEC"))="N" .AND. ValType(SELF:SERVER:FIELDGET("PESONF"))="N"
   	     IF SELF:SERVER:FIELDGET("PESOEC")>0 .AND. SELF:SERVER:FIELDGET("PESONF")>0
	        SELF:SERVER:FIELDPUT("PERCEX",Round(((SELF:SERVER:PESOEC/SELF:SERVER:PESONF)-1)*100,3))
         ENDIF
      ENDIF
    ENDIF
	RETURN NIL

METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
LOCAL aFORN AS ARRAY
oESC:=XESCNUM{SELF,"MB01.DBF"}
oESC:SHOW()	
IF Oesc:LOK
    SELF:SERVER:FIELDPUT("FORNECEDO",oESC:NUMERO)
    aFORN:=PEGMB01(SELF:SERVER:FORNECEDO,ZCURINI,ZCURDIR)
    IF aFORN[1]=.T.
       SELF:SERVER:FIELDPUT("COGNOME",aFORN[3])
    ENDIF
ENDIF

METHOD pegfor( ) 
LOCAL aFORN AS ARRAY	
aFORN:=PEGMB01(SELF:SERVER:FORNECEDO,ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:COGNOME:=aFORN[3]
ENDIF
	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
