PARTIAL CLASS JCRM
METHOD APPEND(oOWNER) 
LOCAL OJCRMNEW AS JCRMnew
LOCAL aFOR,aFORN,aCLI,aPRO,aDAD,aMS01,aCRIST AS ARRAY
LOCAL cNOME,cCOGNOME,cLOTE,cPEDIDO,cSTRIMP,cRASTRO AS STRING
LOCAL oCRMNF,oAUT,oMP03I,oMT01I,oMY04,oCRMEST AS USEREDE      // ,oMU01I
LOCAL lRIST,lRIRM,llote1,lRASTRO,lCARTA,lPRECO,lCARGA,lFALTA AS LOGIC
LOCAL nRIST,nRIRM,nCRM,nRASTRO AS DWORD
LOCAL oRIRM,oRIST,oRISTI,oRIRMI AS USEREDE
//LOCAL oRUN AS APP
LOCAL aMAIL AS ARRAY
LOCAL aRASTRO AS ARRAY
LOCAL cPRODRASTRO AS STRING  
LOCAL cVORETRUN,cPARAM AS STRING

        LOCAL nFout AS PTR

aPRO:={.T.,"","","KG",""}

OJCRMNEW:=JCRMNEW{oOWNER}
oJCRMNEW:LOK:=.F.
OJCRMNEW:Show()
IF ! OJCRMNEW:LOK
	alert("Inclusão Cancelada")
	RETURN .f.
ENDIF
lRIST:=.F.
lRIRM:=.F.
llote1:=.F.
lRASTRO:=.F.
nRIST:=0
nRIRM:=0
nRASTRO:=0
cRASTRO:=""
cNOME:=""
cCOGNOME:=""

cPEDIDO:=StrTRIM(oJCRMNEW:aUSO[13],8,0)+"/"+StrTRIM(oJCRMNEW:aUSO[14],3,0)

IF (oJCRMNEW:aUSO[3]=0 .OR. oJCRMNEW:aUSO[4]=0) .AND. (oJCRMNEW:aUSO[13]=0 .OR. oJCRMNEW:aUSO[14]=0) //.AND.(oJCRMNEW:aUSO[15]=0)
   IF Empty(oJCRMNEW:aUSO[16])
	   alert("Sem Programaçao/Pedido/Req é Necessário Autorização")
	   RETU NIL	
	ENDIF
ENDIF	

	
IF oJCRMNEW:aUSO[2]=0
     alert("Codigo Cliente/Fornecedor em Branco")
     RETU NIL
ENDIF
IF oJCRMNEW:aUSO[12]=0 .AND. Empty(oJCRMNEW:aUSO[16])
   alert("Sem Número de Nota Fiscal é Necessário Autorização")
   RETU NIL
ENDIF

IF oJCRMNEW:aUSO[1]=="F"
   aFOR:=CHECKSIT(oJCRMNEW:aUSO[2])
   IF aFOR[1]        //Achou Fornecedor
      IF ! aFOR[3]  //Fornecedor Bloqueado
         RETU NIL
      ENDIF
   ENDIF
   aDAD:={zCURINI,"CRMNF.DBF",zCURDIR}
   oCRMNF:=USEREDE{aDAD}
   IF oCRMNF:nERRO=0
	  oCRMNF:GOTOP()
	  IF oCRMNF:SEEK(oJCRMNEW:aUSO[2])
   		IF (oCRMNF:FIELDGET("NRNOTA"))>oJCRMNEW:aUSO[12]
   			alert("Nota "+Str(oCRMNF:FIELDGET("NRNOTA"))+" Já Lançada")
	   		GRAVALOG(Str(oJCRMNEW:aUSO[12])+"/"+Str(oCRMNF:FIELDGET("NRNOTA")),"ERR","CRM")	
	   	ENDIF	
 		IF oJCRMNEW:aUSO[17]<oCRMNF:FIELDGET("DATA")
  			alert("Data Retroativa"+DToC(oCRMNF:FIELDGET("DATA")))
   			GRAVALOG(DToC(oJCRMNEW:aUSO[17])+"/"+DToC(oCRMNF:FIELDGET("DATA")),"ERR","CRM")	
		ENDIF
	 ELSE
   		oCRMNF:APPEND()
	   	oCRMNF:FIELDPUT("Fornecedo",oJCRMNEW:aUSO[2])
	 ENDIF
  	 oCRMNF:FIELDPUT("NRNOTA",oJCRMNEW:aUSO[12])
  	 oCRMNF:FIELDPUT("DATA",oJCRMNEW:aUSO[17])
     oCRMNF:CLOSE()	
  ENDIF
ENDIF
DO CASE
   CASE oJCRMNEW:aUSO[6]=="C"
        aPRO:=PEGMT01(oJCRMNEW:aUSO[7],zcurini,zcurdir)
        IF aPRO[1]=.F.
           IF ! oJCRMNEW:aUSO[10]  .AND. ! oJCRMNEW:aUSO[27]
              alert("Componente Não Cadastrado")
           	  RETU NIL
           ELSE
              alert("Componente Não Cadastrado/Lote Piloto/Ensaios")
              aPRO:={.F.,"","","KG",""}
           ENDIF
        ENDIF
   CASE oJCRMNEW:aUSO[6]=="M"
        aPRO:=PEGMU01(oJCRMNEW:aUSO[7],zcurini,zcurdir)
//        ALERT(oJCRMNEW:aUSO[7])
        IF aPRO[1]=.F.
           IF ! oJCRMNEW:aUSO[10]  .AND. ! oJCRMNEW:aUSO[27]
              alert("Materia Prima Não Cadastrada")
          	  RETU NIL
           ELSE	
              alert("Materia Prima Não Cadastrada/Lote Piloto/Ensaios")
       	      aPRO:={.F.,"","","KG",""}
           ENDIF
        ENDIF
   CASE oJCRMNEW:aUSO[6]=="T"
        aPRO:=PEGMP03(oJCRMNEW:aUSO[8],zCURINI,zCURDIR)
        IF aPRO[1]=.F.
     	   IF ! oJCRMNEW:aUSO[10]  .AND. ! oJCRMNEW:aUSO[27]
              alert("Tratamento Não Cadastrado")
          	  RETU NIL
           ELSE	
              alert("Tratamento Não Cadastrado/Lote Piloto/Ensaios")
       	      aPRO:={.F.,"","","KG",""}
           ENDIF
        ELSE
           IF Empty(aPRO[4])
              alert("Norma não Cadastrado")
              RETU NIL
            ENDIF
            oJCRMNEW:aUSO[7]:=aPRO[4] //NORMA
        ENDIF
   CASE oJCRMNEW:aUSO[6]=="P"
        aPRO:=PEGMS01(oJCRMNEW:aUSO[7])
        IF aPRO[1]=.F.
           alert("Produto não Cadastrado")
           IF ! oJCRMNEW:aUSO[10]  .AND. ! oJCRMNEW:aUSO[27] //Se Nao For Lote Piloto
              RETU NIL
           ELSE
              alert("Produto Não Cadastrado/Lote Piloto/Ensaio")
       	      aPRO:={.F.,"","","KG",""}
           ENDIF
        ENDIF
   CASE oJCRMNEW:aUSO[6]=="X"
   	  aPRO:={.T.,"","","KG",""}
   OTHERWISE
        alert("Tipo Não Preenchido")
        RETU NIL
ENDCASE
IF Empty(Apro[2]) .AND. ! Empty(oJCRMNEW:aUSO[23])
   aPRO[2]:=oJCRMNEW:aUSO[23]	
ENDIF
IF Empty(aPRO[3]) .AND. ! Empty(oJCRMNEW:aUSO[24])
   aPRO[3]:=oJCRMNEW:aUSO[24]	
ENDIF	

IF ValType(Apro[2])#"C"
   Apro[2]:=" "
ENDIF	
IF ValType(Apro[3])#"C"
   Apro[3]:=" "
ENDIF	

DO CASE
   CASE oJCRMNEW:aUSO[1]=="C"
        aCLI:=PEGMA01(oJCRMNEW:aUSO[2],zCURINI,zCURDIR)
        IF aCLI[1]=.T.
	        cNOME:=aCLI[2]
	        cCOGNOME:=aCLI[3]
        ELSE
           alert("Cliente  Não Cadastrado")
           RETU NIL
        ENDIF
   CASE oJCRMNEW:aUSO[1]=="F"
        aFORN:=PEGMB01(oJCRMNEW:aUSO[2],zCURINI,zCURDIR)
        IF aFORN[1]=.T.
           cNOME:=aFORN[2]
           cCOGNOME:=aFORN[3]
        ELSE
           alert("Fornecedor  Não Cadastrado")
           RETU NIL
        ENDIF
        IF Empty(aFORN[9] )
           alert("Fornecedor Sem Conceito")
           alert("Continuando sem conceito não grava ensaios")
           IF  ! MDG("Deseja Continuar lançamento")
               RETU NIL
           ENDIF
        ENDIF
    OTHERWISE
        alert("Tipo Cliente/Fornecedor Não Preenchido")
        RETU NIL
ENDCASE

lCARTA:=.F.
IF oJCRMNEW:aUSO[16]>0
	aDAD:={zCURINI,"AUT.DBF",zCURDIR}
	oAUT:=USEREDE{aDAD}
	IF oAUT:nERRO=0
	   oAUT:GOTOP()
	   IF ! oAUT:SEEK(oJCRMNEW:aUSO[16]) .AND. OJCRMNEW:auso[28]=.F.
		  oAUT:CLOSE()
		  alert("Autorizaçao Não Encontrada")
		  RETU NIL
	   ENDIF	
	   IF oAUT:FIELDGET("USADA") .AND. OJCRMNEW:auso[28]=.F.
		  oAUT:CLOSE()
    	  alert("Autorização Já Utilizada")	
		  RETU NIL
	   ENDIF	
       IF Empty(oAUT:FIELDGET("MOTIVO")) .AND. OJCRMNEW:auso[28]=.F.
		  oAUT:CLOSE()
		  alert("Autorização Sem Motivo")	
		  RETU NIL
	   ENDIF	
       lCARTA:=IF(oAUT:FIELDGET("CARTA")="S",.T.,.F.)	
       oAUT:FIELDPUT("USADA",.T.)
    ELSE
      alert("Erro Abrindo Autorizações")
      RETU NIL
   ENDIF	
ENDIF


cLOTE:=""
IF oJCRMNEW:aUSO[10]
   cLOTE:="P"
ENDIF	
IF oJCRMNEW:aUSO[27]
   cLOTE:="E"
ENDIF
IF oJCRMNEW:aUSO[1]=="F" .AND. Empty(clote)
   cLOTE:=NOVOLOTE(oJCRMNEW:aUSO[2],oJCRMNEW:aUSO[7])	
   IF aFORN[9]="C" .OR. (Val(cLOTE)=1 .AND. aFORN[9]="B")
      DO CASE
         CASE oJCRMNEW:aUSO[6]=="C" .OR. oJCRMNEW:aUSO[6]=="M"
              lRIRM:=.T.
         CASE oJCRMNEW:aUSO[6]=="T"
              lRIST:=.T.
      ENDCASE
   ENDIF
ENDIF


//Pegando Proximo Crm
SELF:server:setorder(1)
SELF:server:gobottom()
nCRM:=SELF:Server:FIELDGET("CRM")
nCRM++
SELF:SERVER:APPEND()
SELF:SERVER:FIELDPUT("CRM",nCRM)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:Commit()

//Pegando Rastro
IF Empty(OJCRMNEW:Auso[18])
   aRASTRO:=NOVORASTRO()
   nRASTRO:=ARASTRO[1]
   cRASTRO:=ARASTRO[2]
   lRASTRO:=.T.	
   OJCRMNEW:AUSO[18]:=cRASTRO
ENDIF	


//Gravando Cabeçario Rirm Gera Sempre
IF oJCRMNEW:aUSO[6]=="C" .OR. oJCRMNEW:aUSO[6]=="M" //Sempre Grava Materia Prima Componente
    //.OR.oJCRMNEW:aUSO[10].OR.oJCRMNEW:aUSO[27] //(oJCRMNEW:aUSO[6]=="C".OR.oJCRMNEW:aUSO[6]=="M")
   aDAD:={zCURINI,"RIRM.DBF",zCURDIR}
   oRIRM:=USEREDE{aDAD}
   IF oRIRM:nERRO=0
	  oRIRM:setorder(1)
      oRIRM:gobottom()
	  nRIRM:=oRIRM:FIELDGET("RIRM")
  	  nRIRM++
  	  oRIRM:APPEND()
	  oRIRM:FIELDPUT("RIRM",nRIRM)
 	  oRIRM:FIELDPUT("DATA",Today())						
 	  oRIRM:FIELDPUT("CRM",nCRM)
	  oRIRM:FIELDPUT("DESCR",aPRO[2])
	  oRIRM:FIELDPUT("APLICACAO",aPRO[3])
	  oRIRM:FIELDPUT("DESENHO",oJCRMNEW:aUSO[7])
	  oRIRM:FIELDPUT("FORNE",cNOME)
	  oRIRM:FIELDPUT("NFORN", oJCRMNEW:aUSO[2])
 	  IF oJCRMNEW:aUSO[1]=="F"
  	     oRIRM:FIELDPUT("CLASSI",aFORN[9])	
  	  ELSE
  	     oRIRM:FIELDPUT("CLASSI","_")			
      ENDIF
	  oRIRM:FIELDPUT("TIPOENT", oJCRMNEW:aUSO[6])
	  oRIRM:FIELDPUT("INSTRU",aPRO[5])		
	  oRIRM:FIELDPUT("CERT",oJCRMNEW:aUSO[9])		
  	  oRIRM:FIELDPUT("CLOTECRT",cLOTE)		
  	  oRIRM:FIELDPUT("NRNOTA",oJCRMNEW:aUSO[12])
  	  oRIRM:FIELDPUT("NRNOTB",oJCRMNEW:aUSO[19])
  	  oRIRM:FIELDPUT("DATANF",oJCRMNEW:aUSO[17])
  	  oRIRM:FIELDPUT("QTDE",oJCRMNEW:aUSO[5]+oJCRMNEW:aUSO[20])
  	  oRIRM:FIELDPUT("RASTRO",AllTrim(oJCRMNEW:aUSO[18]))
	  oRIRM:FIELDPUT("UNID","KG")		
	  oRIRM:FIELDPUT("PEDIDO",cPEDIDO)			
	  oRIRM:CLOSE()
  ENDIF	
ENDIF
//Gravando Cabeçario Rist Gera Sempre
IF oJCRMNEW:aUSO[6]=="T" //Sempre Grava Tratamento
   //.OR.oJCRMNEW:aUSO[10].OR.oJCRMNEW:aUSO[27]
   aDAD:={zCURINI,"RIST.DBF",zCURDIR}
   oRIST:=USEREDE{aDAD}
   IF oRIST:nERRO=0
   	  oRIST:setorder(1)
	  oRIST:gobottom()
  	  nRIST:=oRIST:FIELDGET("RIST")
	  nRIST++
  	  oRIST:APPEND()
      oRIST:FIELDPUT("RIST",nRIST)
      oRIST:FIELDPUT("DATA",Today())			
	  oRIst:FIELDPUT("CRM",nCRM)			
	  oRIST:FIELDPUT("DENO",aPRO[2])
	  oRIST:FIELDPUT("APLICACAO",aPRO[3])
	  oRIST:FIELDPUT("TIPO",aPRO[5])
	  oRIST:FIELDPUT("CODIGO",oJCRMNEW:aUSO[7])
  	  oRIST:FIELDPUT("FORNE",cNOME)
	  oRIST:FIELDPUT("NFORN", oJCRMNEW:aUSO[2])
	  oRIST:FIELDPUT("TIPO", oJCRMNEW:aUSO[6])
	  oRIST:FIELDPUT("CERT",oJCRMNEW:aUSO[9])				
  	  oRIST:FIELDPUT("CLOTECRT",cLOTE)			
	  oRIST:FIELDPUT("NF",oJCRMNEW:aUSO[12])	
	  oRIST:FIELDPUT("NFB",oJCRMNEW:aUSO[19])		
	  oRIST:FIELDPUT("OS",cPEDIDO)				
   	  IF oJCRMNEW:aUSO[1]=="F"
	     oRIST:FIELDPUT("CLASSI",aFORN[9])
	  ELSE
  	     oRIRM:FIELDPUT("CLASSI","_")				
	  ENDIF
  	  oRIST:FIELDPUT("DATANF",oJCRMNEW:aUSO[17])
 	  oRIST:FIELDPUT("RASTRO",AllTrim(oJCRMNEW:aUSO[18]))
      oRIST:FIELDPUT("UNID","PC")		
      oRIST:FIELDPUT("NIVEL","0.65")
	  oRIST:FIELDPUT("QTDE",oJCRMNEW:aUSO[5]+oJCRMNEW:aUSO[20])	
  	  aMS01:=PEGMS01(oRIST:FIELDGET("APLICACAO"))		
 	  IF aMS01[1]
	   	 IF ! Empty(aMS01[4])
	     	oRIST:FIELDPUT("NCLI",aMS01[4])
	      	aCRIST:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
            IF aCRIST[1]=.T.
               SELF:SERVER:CLIENTE:=aCRIST[2]
            ENDIF
         ENDIF	
         IF CLOTE="1"
            llote1:=.T.
         ENDIF
      ENDIF	
      oRIST:CLOSE()
   ENDIF
ENDIF

IF lRASTRO
   cPRODRASTRO:=""	
   IF Empty(aPRO[3])
      cPRODRASTRO:=OJCRMNEW:Auso[8]
    ELSE
      cPRODRASTRO:=APRO[3]
    ENDIF
    GRAVARASTRO(nRASTRO,nCRM,nRIRM,nRIST,cPRODRASTRO,OJCRMNEW:AUSO[11])	
ENDIF	

//Itens Rist se necessário
IF  oJCRMNEW:aUSO[6]=="T"
//lRIST.OR.((oJCRMNEW:aUSO[10].OR.oJCRMNEW:aUSO[27]).and.oJCRMNEW:aUSO[6]=="T")
   aDAD:={zCURINI,"RISTI.DBF",zCURDIR}
   oRISTI:=USEREDE{aDAD}
   IF oRISTI:nERRO=0
	  aDAD:={zCURINI,"MP03I.DBF",zCURDIR}
       oMP03I:=USEREDE{aDAD}
       IF oMP03I:nERRO=0
     	  oMP03I:GOTOP()
	      oMP03I:SEEK(oJCRMNEW:aUSO[7])
	      WHILE AllTrim(oJCRMNEW:aUSO[7])=AllTrim(oMP03I:FIELDGET("CODIGO")) .AND. ! oMP03I:EOF
               oRISTI:APPEND()
	           oRISTI:LOCKCURRENTRECORD()
	           oRISTI:FIELDPUT("RIST",nRIST)
	           oRISTI:FIELDPUT("ITEM",oMP03I:FIELDGET("ITEM"))
	           oRISTI:FIELDPUT("ESPE",oMP03I:FIELDGET("ESPE"))
	           oRISTI:FIELDPUT("ENCO",oMP03I:FIELDGET("ENCO"))
	           oRISTI:FIELDPUT("TIPA",oMP03I:FIELDGET("TIPA"))	
	           oMP03I:SKIP()
	      ENDDO
	      oMP03I:CLOSE()
	   ENDIF
	   oRISTI:CLOSE()
   ENDIF
ENDIF


IF  oJCRMNEW:aUSO[6]=="C" .OR. oJCRMNEW:aUSO[6]=="M"
//lRIRM.OR.((oJCRMNEW:aUSO[10].OR.oJCRMNEW:aUSO[27]).and.(oJCRMNEW:aUSO[6]=="C".OR.oJCRMNEW:aUSO[6]=="T"))
  	//Itens Componentes/MateriaPrima

 	  aDAD:={zCURINI,"RIRMI.DBF",zCURDIR}
      oRIRMI:=USEREDE{aDAD}
      IF oRIRMI:nERRO=0
     	 aDAD:={zCURINI,IF(oJCRMNEW:aUSO[6]=="C","MT01I.DBF","MU01I.DBF"),zCURDIR}
         oMT01I:=USEREDE{aDAD}
	     IF oMT01I:nERRO=0
            oMT01I:GOTOP()
            oMT01I:SEEK(oJCRMNEW:aUSO[7])
            WHILE AllTrim(oJCRMNEW:aUSO[7])=AllTrim(oMT01I:FIELDGET("CODIGO")) .AND. ! oMT01I:EOF
		           oRIRMI:APPEND()
		           oRIRMI:LOCKCURRENTRECORD()
		           oRIRMI:FIELDPUT("RIRM",nRIRM)
		           oRIRMI:FIELDPUT("ITEM",oMT01I:FIELDGET("ITEM"))
		           oRIRMI:FIELDPUT("ESPE",oMT01I:FIELDGET("ESPE"))
		           oRIRMI:FIELDPUT("ENCO",oMT01I:FIELDGET("ENCO"))
		           oRIRMI:FIELDPUT("TIPA",oMT01I:FIELDGET("TIPA"))
		           oRIRMI:FIELDPUT("UNIITEM",oMT01I:FIELDGET("UNIDREF"))	
                   oRIRMI:FIELDPUT("QTITEM",oMT01I:FIELDGET("QTDEREF"))		
		           oMT01I:SKIP()
		      ENDDO
		     oMT01I:CLOSE()
		 ENDIF
	     oRIRMI:CLOSE()
	 ENDIF

ENDIF



//
//APPEND/CRM/DATA ACIMA
//
SELF:SERVER:FIELDPUT("DESCRI",aPRO[2])
SELF:SERVER:FIELDPUT("APLICACAO",aPRO[3])
SELF:SERVER:FIELDPUT("CBUSCA",oJCRMNEW:aUSO[7])
SELF:SERVER:FIELDPUT("NOMEF",cNOME)
SELF:SERVER:FIELDPUT("COGNOME",cCOGNOME)
SELF:SERVER:FIELDPUT("CLIFOR",oJCRMNEW:aUSO[2])
SELF:SERVER:FIELDPUT("TIPOE",oJCRMNEW:aUSO[6])
SELF:SERVER:FIELDPUT("TIPCAD",oJCRMNEW:aUSO[1])
SELF:SERVER:FIELDPUT("QTDE",oJCRMNEW:aUSO[5]+oJCRMNEW:aUSO[20])
SELF:SERVER:FIELDPUT("QTDEA",oJCRMNEW:aUSO[5])
SELF:SERVER:FIELDPUT("QTDEB",oJCRMNEW:aUSO[20])
SELF:SERVER:FIELDPUT("QTDEPED",oJCRMNEW:aUSO[26])
SELF:SERVER:FIELDPUT("PRPED",oJCRMNEW:aUSO[3])
SELF:SERVER:FIELDPUT("PRITE",oJCRMNEW:aUSO[4])
SELF:SERVER:FIELDPUT("RIST",NRIST)
SELF:SERVER:FIELDPUT("RIRM",NRIRM)
SELF:SERVER:FIELDPUT("CERT",oJCRMNEW:aUSO[9])
SELF:SERVER:FIELDPUT("NRNOTA",oJCRMNEW:aUSO[12])
SELF:SERVER:FIELDPUT("NRNOTB",oJCRMNEW:aUSO[19])
SELF:SERVER:FIELDPUT("PEPED",oJCRMNEW:aUSO[13])
SELF:SERVER:FIELDPUT("PEITE",oJCRMNEW:aUSO[14])
SELF:SERVER:FIELDPUT("PEDIDO",cPEDIDO)
SELF:SERVER:FIELDPUT("PEREQ",oJCRMNEW:aUSO[15])
SELF:SERVER:FIELDPUT("OBS",oJCRMNEW:aUSO[11])
SELF:server:FIELDPUT("TECNICO",ZFOLHA)
SELF:SERVER:FIELDPUT("AUT",oJCRMNEW:aUSO[16])
SELF:SERVER:FIELDPUT("RASTRO",AllTrim(oJCRMNEW:aUSO[18]))
SELF:SERVER:FIELDPUT("PRECO",oJCRMNEW:aUSO[21])
SELF:SERVER:FIELDPUT("PRECOPR",oJCRMNEW:aUSO[22])
SELF:SERVER:FIELDPUT("CLOTECRT",cLOTE)		
SELF:SERVER:FIELDPUT("PRCLI",oJCRMNEW:aUSO[25])
IF SELF:TIPOE=="T"
    SELF:SERVER:FIELDPUT("PRODUTO",oJCRMNEW:aUSO[8])
ENDIF
SELF:SERVER:FIELDPUT("USERNM",ZUSER)
SELF:SERVER:FIELDPUT("USERDT",Today())
SELF:SERVER:FIELDPUT("USERHT",Time())
SELF:SERVER:FIELDPUT("NRDATA",oJCRMNEW:aUSO[17])
SELF:sERVER:FIELDPUT("UNID","KG")
SELF:SERVER:FIELDPUT("PESONFA",oJCRMNEW:aUSO[29])
SELF:SERVER:FIELDPUT("PESONFB",oJCRMNEW:aUSO[30])
SELF:SERVER:FIELDPUT("PEDCLI",oJCRMNEW:aUSO[31])
SELF:SERVER:FIELDPUT("ENTREGA",oJCRMNEW:aUSO[32])
SELF:SERVER:FIELDPUT("ENTREG2",oJCRMNEW:aUSO[33])
IF oJCRMNEW:aUSO[34]
   SELF:SERVER:FIELDPUT("TRIANGULAR","S")	
ENDIF	
SELF:SERVER:Commit()
SELF:VIEWFORM()
GRAVALOG(SELF:SERVER:CRM,"INC","CRM")	
IF ! Empty(nRIRM)
   GRAVALOG(SELF:SERVER:RIRM,"INC","CRM_RIRM")	
   alert("RIRM: "+Str(nRIRM))	
ENDIF
IF ! Empty(nRIST)
   GRAVALOG(SELF:SERVER:RIST,"INC","CRM_RIST")	
   alert("RIST: "+Str(nRIST))	
ENDIF
IF ! Empty(oJCRMNEW:aUSO[11])
   GRAVALOG(Str(SELF:SERVER:CRM)+" "+oJCRMNEW:aUSO[11],"INC","CRM")	
ENDIF
IF llote1 .AND. MDG("Imprimir RIST","Imprimir")
  	cVORETRUN:=PEGINIVAL(ZCURINI,"PATH","VORETRUN")+ "VORETRUN"
	cPARAM:=PEGINIVAL(ZCURINI,"RET_CRM07","CAMINHO")+"$NNNNNSSSN$#MANA5CRM#"
	nFout := ShellExecute(SELF:owner:handle(),String2Psz("open"),String2Psz(cVORETRUN),String2Psz(cPARAM),String2Psz(""),1)  
    ShellExecuteErro(nFout) 
//     hwnd,   lpOperation,  lpFile,   lpParameters,   lpDirectory,    SW_SHOWNORMAL = 1//fica no diretorio atual ondes estao os dbfs
ENDIF

lPRECO:=.F.
IF SELF:SERVER:FIELDGET("PRECO")<>SELF:SERVER:FIELDGET("PRECOPR")
   lPRECO:=.T.
ENDIF
lCARGA:=.F.
lFALTA:=.F.
IF SELF:SERVER:FIELDGET("QTDE")<(SELF:SERVER:FIELDGET("QTDEPED")*.9) .AND. oJCRMNEW:aUSO[6]#"T"
   lCARGA:=.T.	
   lFALTA:=.T.
ENDIF	
IF SELF:SERVER:FIELDGET("QTDE")>(SELF:SERVER:FIELDGET("QTDEPED")*1.1) .AND. oJCRMNEW:aUSO[6]#"T"
   lCARGA:=.T.	
ENDIF	
aMAIL:={}
IF lCARTA .OR. lPRECO .OR. lCARGA
   AAdd(aMAIL,"Pedido_No:"+cPEDIDO)
   AAdd(aMAIL," CRM_No:"+StrTRIM(nCRM,8,0))
   AAdd(aMAIL," Nota:"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTA"),8,0))
   IF ! Empty(SELF:SERVER:FIELDGET("NRNOTB"))
      AAdd(aMAIL,"/"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTB"),8,0))
   ENDIF
   IF lCARGA .and. oJCRMNEW:aUSO[6]<>"T" .and. oJCRMNEW:aUSO[31]#"S"
      AAdd(aMAIL," Peso:"+StrTRIM(SELF:SERVER:FIELDGET("QTDEPED"),15,6))
      AAdd(aMAIL," Peso:"+StrTRIM(SELF:SERVER:FIELDGET("QTDE"),15,6))
      AAdd(aMAIL," Fornecedor:"+StrTRIM(SELF:SERVER:FIELDGET("CLIFOR"),8,0))
      AAdd(aMAIL," Codigo:"+AllTrim(SELF:SERVER:FIELDGET("CBUSCA")))
      AAdd(aMAIL," PE:"+StrTRIM(SELF:SERVER:FIELDGET("PEPED"),8,0)+"/"+StrTRIM(SELF:SERVER:FIELDGET("PEITE"),8,0))
   	  IF lFALTA
 	  	 EMAILINT("CRM00005",ZUSER,aMAIL,ZCURINI,zCURDIR)	
      ELSE
         EMAILINT("CRM00003",ZUSER,aMAIL,ZCURINI,zCURDIR)	
      ENDIF
   ENDIF
   IF lPRECO
   	  AAdd(aMAIL," Preço:"+StrTRIM(SELF:SERVER:FIELDGET("PRECOPR"),15,6))
   	  AAdd(aMAIL," Preço:"+StrTRIM(SELF:SERVER:FIELDGET("PRECO"),15,6))
	  EMAILINT("CRM00001",ZUSER,aMAIL,ZCURINI,zCURDIR)	
   ENDIF
   IF lCARTA
 	  EMAILINT("CRM00002",ZUSER,aMAIL,ZCURINI,zCURDIR)	
 	  alert("Requer Carta Correção")
   ENDIF
ENDIF	
//Entrada MP/CO Com Programaçao
IF oJCRMNEW:aUSO[6]=="C" .OR. oJCRMNEW:aUSO[6]=="M" .AND. SELF:SERVER:FIELDGET("PEPED")>0
	aMAIL:={}
    AAdd(aMAIL,"Pedido_No:"+cPEDIDO)
    AAdd(aMAIL," CRM_No:"+StrTRIM(nCRM,8,0))
    AAdd(aMAIL," Nota:"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTA"),8,0))
    IF ! Empty(SELF:SERVER:FIELDGET("NRNOTB"))
       AAdd(aMAIL,"/"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTB"),8,0))
    ENDIF
    AAdd(aMAIL," Peso:"+StrTRIM(SELF:SERVER:FIELDGET("QTDEPED"),15,6))
    AAdd(aMAIL," Peso:"+StrTRIM(SELF:SERVER:FIELDGET("QTDE"),15,6))
    AAdd(aMAIL," Fornecedor:"+StrTRIM(SELF:SERVER:FIELDGET("CLIFOR"),8,0))
    AAdd(aMAIL," Codigo:"+AllTrim(SELF:SERVER:FIELDGET("CBUSCA")))
    AAdd(aMAIL," PE:"+StrTRIM(SELF:SERVER:FIELDGET("PEPED"),8,0)+"/"+StrTRIM(SELF:SERVER:FIELDGET("PEITE"),8,0))
    EMAILINT("CRM00007",ZUSER,aMAIL,ZCURINI,zCURDIR)	
ENDIF

IF ! Empty(SELF:SERVER:FIELDGET("PEREQ"))
   aDAD:={zCURINI,"MY04.DBF",zCURDIR}
   oMY04:=USEREDE{aDAD}
   IF oMY04:nERRO=0
      oMY04:GOTOP()
      oMY04:SEEK(SELF:SERVER:FIELDGET("PEREQ"))
      IF oMY04:FOUND
      	 IF Empty(oMY04:FIELDGET("TECNICO"))
      	 	oMY04:FIELDPUT("TECNICO",ZFOLHA)
      	 ENDIF
      	 IF Empty(oMY04:FIELDGET("RASTRO"))
      	 	oMY04:FIELDPUT("RASTRO",AllTrim(oJCRMNEW:aUSO[18]))
      	 ENDIF
      	 IF Empty(oMY04:FIELDGET("CRM"))
      	 	oMY04:FIELDPUT("CRM",nCRM)
      	 ENDIF
      ENDIF	
      oMY04:CLOSE()
   ENDIF
ENDIF


IF oJCRMNEW:aUSO[16]>0
   oAUT:FIELDPUT("CRM",nCRM)	
   oAUT:FIELDPUT("DATABX",Today())
   oAUT:Close()	
ENDIF	

IF CLOTE="1" .OR. cLOTE="P" .OR. cLOTE="E"
   alert("Realizar Ensaios")	
ENDIF	

IF oJCRMNEW:aUSO[6]=="M"
   aDAD:={zCURINI,"CRMEST.DBF",zCURDIR}
   oCRMEST:=USEREDE{aDAD}
   IF oCRMEST:nERRO=0
   	  oCRMEST:Append()
   	  oCRMEST:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("CBUSCA"))
   	  oCRMEST:FIELDPUT("UNIDADE",SELF:SERVER:FIELDGET("UNID"))
   	  oCRMEST:FIELDPUT("NOME",SELF:SERVER:FIELDGET("DESCRI"))
   	  oCRMEST:FIELDPUT("NRNOTAINI",SELF:SERVER:FIELDGET("NRNOTA"))
   	  oCRMEST:FIELDPUT("DATAFAT",SELF:SERVER:FIELDGET("DATA"))
   	  oCRMEST:FIELDPUT("OSINI",Val(StrTran(SELF:SERVER:FIELDGET("PEDIDO"),"/",".")))
   	  oCRMEST:FIELDPUT("TOTKGINI",SELF:SERVER:FIELDGET("QTDEA"))
      oCRMEST:FIELDPUT("TOTKGANT",SELF:SERVER:FIELDGET("QTDEA"))
      oCRMEST:FIELDPUT("TOTKGEST",SELF:SERVER:FIELDGET("QTDEA"))
   	  oCRMEST:FIELDPUT("TIPOCLI",SELF:SERVER:FIELDGET("TIPCAD"))
   	  oCRMEST:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIFOR"))
   	  oCRMEST:FIELDPUT("COGNOME",SELF:SERVER:FIELDGET("COGNOME"))
   	  oCRMEST:FIELDPUT("CRM",SELF:SERVER:FIELDGET("CRM"))
   	  oCRMEST:FIELDPUT("PESOREF",SELF:SERVER:FIELDGET("PESONFA"))
   	  oCRMEST:FIELDPUT("PRECO",SELF:SERVER:FIELDGET("PRECONF"))
   	  oCRMEST:FIELDPUT("TIPOENT",SELF:SERVER:FIELDGET("TIPOE"))
   	  oCRMEST:FIELDPUT("RASTRO",SELF:SERVER:FIELDGET("RASTRO"))
   	  IF Empty(SELF:SERVER:FIELDGET("PRODUTO"))
     	 oCRMEST:FIELDPUT("OBS",SELF:SERVER:FIELDGET("APLICACAO"))
      ELSE
     	 oCRMEST:FIELDPUT("OBS",SELF:SERVER:FIELDGET("PRODUTO"))
      ENDIF
      IF ! Empty(SELF:SERVER:FIELDGET("NRNOTB"))
      	 oCRMEST:Append()
   	  	 oCRMEST:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("CBUSCA"))
   	  	 oCRMEST:FIELDPUT("UNIDADE",SELF:SERVER:FIELDGET("UNID"))
   	  	 oCRMEST:FIELDPUT("NOME",SELF:SERVER:FIELDGET("DESCRI"))
   	  	 oCRMEST:FIELDPUT("NRNOTAINI",SELF:SERVER:FIELDGET("NRNOTB"))
   	  	 oCRMEST:FIELDPUT("DATAFAT",SELF:SERVER:FIELDGET("DATA"))
   	  	 oCRMEST:FIELDPUT("OSINI",Val(StrTran(SELF:SERVER:FIELDGET("PEDIDO"),"/",".")))
   	  	 oCRMEST:FIELDPUT("TOTKGINI",SELF:SERVER:FIELDGET("QTDEB"))
         oCRMEST:FIELDPUT("TOTKGANT",SELF:SERVER:FIELDGET("QTDEB"))
         oCRMEST:FIELDPUT("TOTKGEST",SELF:SERVER:FIELDGET("QTDEB"))
   	  	 oCRMEST:FIELDPUT("TIPOCLI",SELF:SERVER:FIELDGET("TIPCAD"))
   	  	 oCRMEST:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIFOR"))
   	  	 oCRMEST:FIELDPUT("COGNOME",SELF:SERVER:FIELDGET("COGNOME"))
   	  	 oCRMEST:FIELDPUT("CRM",SELF:SERVER:FIELDGET("CRM"))
   	  	 oCRMEST:FIELDPUT("PESOREF",SELF:SERVER:FIELDGET("PESONFB"))
   	  	 oCRMEST:FIELDPUT("PRECO",SELF:SERVER:FIELDGET("PRECONF"))
   	  	 oCRMEST:FIELDPUT("TIPOENT",SELF:SERVER:FIELDGET("TIPOE"))
   	  	 oCRMEST:FIELDPUT("RASTRO",SELF:SERVER:FIELDGET("RASTRO"))
   	     IF Empty(SELF:SERVER:FIELDGET("PRODUTO"))
     	    oCRMEST:FIELDPUT("OBS",SELF:SERVER:FIELDGET("APLICACAO"))
         ELSE
       	    oCRMEST:FIELDPUT("OBS",SELF:SERVER:FIELDGET("PRODUTO"))
         ENDIF
      ENDIF
      oCRMEST:CLOSE()
   ENDIF	
ENDIF

METHOD buscaCRM(oOWNER) 
	SELF:KeyFind()
//LOCAL oBUSCA AS XBUSCA
//oBUSCA:=XBUSCA{oOWNER,"Localizar","Digite NºCRM"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF

METHOD cmdAno( ) 
LOCAL cRASTRO AS STRING
LOCAL aRETU AS ARRAY
cRASTRO:=SELF:SERVER:FIELDGET("RASTRO")
aRETU:=CHECKRASTRO(cRASTRO)	
IF aRETU[1]
   SELF:SERVER:FIELDPUT("RASTRO",aRETU[2])
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CRM","CRM")	

METHOD cmdtriangular( ) 
LOCAL oJAN AS crmJanTri	
IF SELF:SERVER:FIELDGET("TRIANGULAR")="V"	
   alert("Operacao Triangular Ja Verificada")
   RETURN .f.
ENDIF	
IF SELF:SERVER:FIELDGET("TRIANGULAR")<>"S"	
   alert("Esta nao E uma Operacao Triangular")
   RETURN .f.	
ENDIF	
oJAN:=CRMJANTRI{SELF}
oJAN:SHOW()

METHOD DELETE() 
LOCAL nRIRM,nRIST,nAUT,nNRNOTA,nNRNOTB,nCRM AS DWORD
LOCAL oAUT,oCRMEST AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL cTIPO,cCODIGO AS STRING
IF ! MDG("Apagar Registro") .AND. SELF:server:LockCurrentRecord()
	RETURN .f.
ENDIF	
nRIRM:=SELF:SERVER:RIRM
nRIST:=SELF:SERVER:RIST
nAUT:=SELF:SERVER:FIELDGET("AUT")
cTIPO:=SELF:SERVER:FIELDGET("TIPOE")
nCRM:=SELF:SERVER:FIELDGET("CRM")
nNRNOTA:=SELF:SERVER:FIELDGET("NRNOTA")
nNRNOTB:=SELF:SERVER:FIELDGET("NRNOTB")
cCODIGO:=SELF:SERVER:FIELDGET("CBUSCA")
GRAVALOG(SELF:SERVER:CRM,"DEL","CRM")	
SELF:server:delete()
SELF:server:unlock()
SELF:server:skip(-1)
IF ! Empty(nRIRM)
   DELEENS("RIRM.DBF","RIRMI.DBF",nRIRM,"RIRM")
   GRAVALOG(nRIRM,"DEL","CRM_RIRM")	
ENDIF
IF ! Empty(nRIST)
   DELEENS("RIST.DBF","RISTI.DBF",nRIST,"RIST")
   GRAVALOG(nRIST,"DEL","CRM_RIST")		
ENDIF

IF nAUT>0
   aDAD:={zCURINI,"AUT.DBF",zCURDIR}
   AUT:=USEREDE{aDAD}
   IF oAUT:nERRO=0
      oAUT:GOTOP()
      IF oAUT:SEEK(nAUT)
      	 oAUT:Delete()
      ENDIF	
      oAUT:CLOSE()
   ENDIF
ENDIF



IF cTIPO="M"
   aDAD:={zCURINI,"CRMEST.DBF",zCURDIR}
   oCRMEST:=USEREDE{aDAD}
   IF oCRMEST:nERRO=0
   	  oCRMEST:SetOrder(2)
   	  oCRMEST:GOTOP()
   	  OCRMEST:SEEK(Str(nNRNOTA,8)+cCODIGO)
   	  WHILE oCRMEST:FIELDGET("CRM")=nCRM .AND. ! oCRMEST:EoF
   	  	  oCRMEST:Delete()
   	  	  oCRMEST:Skip()
  	  ENDDO
  	  OCRMEST:SEEK(Str(nNRNOTB,8)+cCODIGO)
   	  WHILE oCRMEST:FIELDGET("CRM")=nCRM .AND. ! oCRMEST:EoF
   	  	  oCRMEST:Delete()
	  	  oCRMEST:Skip()	
  	  ENDDO
      oCRMEST:CLOSE()
   ENDIF	
ENDIF

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("PRODUTO",oESC:CODIGO)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:server:FIELDGET("PRODUTO"))," ",""))
IF Empty(cCODIGO)	
  cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:server:FIELDGET("APLICACAO"))," ",""))	
ENDIF
IF Empty(cCODIGO)	
   alert("Codigo Produto/Aplicacao Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()


METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


METHOD TROCANF 
LOCAL aMAIL AS ARRAY
LOCAL oJAN AS jcrmtr

oJAN:=JCRMTR{SELF}
oJAN:SHOW()
aMAIL:={}
AAdd(aMAIL," CRM_No:"+StrTRIM(SELF:SERVER:FIELDGET("CRM"),8,0))
AAdd(aMAIL," Nota:"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTA"),8,0))
IF ! Empty(SELF:SERVER:FIELDGET("NRNOTB"))
   AAdd(aMAIL,"/"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTB"),8,0))
ENDIF
AAdd(aMAIL," Fornecedor:"+StrTRIM(SELF:SERVER:FIELDGET("CLIFOR"),8,0))
AAdd(aMAIL," Codigo:"+AllTrim(SELF:SERVER:FIELDGET("CBUSCA")))
AAdd(aMAIL," PE:"+StrTRIM(SELF:SERVER:FIELDGET("PEPED"),8,0)+"/"+StrTRIM(SELF:SERVER:FIELDGET("PEITE"),8,0))
EMAILINT("CRM00006",ZUSER,aMAIL,ZCURINI,zCURDIR)	

END CLASS
PARTIAL CLASS jCRMNEW
METHOD bloqCOD( ) 
SELF:oDCCBUSCA:disable()
SELF:oDCTIPOE:disable()
SELF:oCCTIPOC:disable()
SELF:oCCTIPOM:disable()
SELF:oCCTIPOT:disable()
SELF:oCCTIPOO:disable()
SELF:oCCTIPOP:disable()
SELF:oCCpegcod1:Disable()
SELF:oCCesccod2:Disable()
SELF:oCCescPRO1:Disable()
SELF:oDCcodavu:Disable()
SELF:oCCCMDTRAPRO:Disable()
SELF:oCCpegcod:Disable()
SELF:oCCesccod:Disable()


METHOD calcpeca 
LOCAL nPESO,nCALC AS FLOAT	
IF  SELF:ODCTIPOE:Value<>"T"
   alert("Não é Tratamento Servicos Tratamento/Serviços")	
   SELF:oDCcRASTRO:SetFocus()
   RETURN .f.
ENDIF		
nPESO:=Val(SELF:oDCPESO:TEXTVALUE)	
IF nPESO>0
   nCALC:=Val(SELF:ODCPESONFA:TextValue)	
   nCALC:=FloatFormat(nCALC/nPESO,8,2)
   SELF:ODCQTDEA:TextValue:=Str(nCALC)

   nCALC:=Val(SELF:ODCPESONFB:TextValue)	
   nCALC:=FloatFormat(nCALC/nPESO,8,2)
   SELF:ODCQTDEB:TextValue:=Str(nCALC)

ENDIF	

METHOD calcpeso 
LOCAL nPESO,nCALC AS FLOAT	
IF  SELF:ODCTIPOE:Value<>"T"
   alert("Não é Tratamento Servicos Tratamento/Serviços")	
   SELF:oDCcRASTRO:SetFocus()
   RETURN .f.
ENDIF		
nPESO:=Val(SELF:oDCPESO:TEXTVALUE)	
IF nPESO=0
   SELF:CHKPESO()
ENDIF	
IF nPESO>0
   nCALC:=Val(SELF:ODCQTDEA:TextValue)	
   nCALC:=FloatFormat(nCALC*nPESO,8,2)
   SELF:ODCPESONFA:TextValue:=Str(nCALC)
   nCALC:=Val(SELF:ODCQTDEB:TextValue)	
   nCALC:=FloatFormat(nCALC*nPESO,8,2)
   SELF:ODCPESONFB:TextValue:=Str(nCALC)
ENDIF	


METHOD CANCELAR 
lOK:= .F.	
SELF:EndWindow()
	
	


METHOD CHKCTR(nCOMPED,nCOMITE) 
LOCAL aDAD AS ARRAY	
LOCAL oMW01,oMW02 AS  USEREDE
LOCAL nERRO AS WORD
nERRO:=0
aDAD:={zCURINI,"MW01.DBF",zCURDIR}
oMW01:=USEREDE{aDAD}
IF oMW01:nERRO=0
   oMW01:GOTOP()
   IF oMW01:SEEK(nCOMPED)
   	  IF oMW01:FIELDGET("CONTRATO")#"S"
   	  	 nERRO:=3
   	  ENDIF	
   	  IF oMW01:FIELDGET("RECEBER")#"S"
   	  	 nERRO:=4
   	  ENDIF	
   ELSE
   	  nERRO:=2
   ENDIF	
ELSE
   nERRO:=1	
ENDIF
oMW01:CLOSE()

aDAD:={zCURINI,"MW02.DBF",zCURDIR}
oMW02:=USEREDE{aDAD}
IF oMW02:nERRO=0
   oMW02:GOTOP()
   oMW02:SEEK(Str(nCOMPED,8)+Str(nCOMITE,3))
   IF oMW02:FOUND
      IF oMW02:FIELDGET("BLQITEM")="S"
      	 nERRO:=7
      ENDIF	
   ELSE
     nERRO:=6
   ENDIF
ELSE
   nERRO:=5
ENDIF
oMW02:CLOSE()

IF NERRO=1
   alert("Erro checando Pedidos")
ENDIF	
IF NERRO=2
   alert("Pedido Nao Encontrado "+Str(nCOMPED))	
ENDIF	
IF nERRO=3
   alert("Pedido Nao E Contrato "+Str(nCOMPED))		
ENDIF	
IF NERRO=4
   alert("Pedido Marcado Nao Receber "+Str(nCOMPED))
ENDIF	
IF NERRO=5
   alert("Erro checando Itens Pedidos")
ENDIF	
IF NERRO=6
   alert("Item do Pedido Nao Encontrado "+Str(nCOMPED)+"."+Str(nCOMITE))	
ENDIF	
IF NERRO=7
   alert("Item do Pedido bloqueado "+Str(nCOMPED)+"."+Str(nCOMITE))	
ENDIF	
IF nERRO>0
   SELF:ZERAVAL()
ENDIF

METHOD CHKPED() 
LOCAL oMW02,oMW01,oMY04 AS USEREDE
LOCAL nPEPED,nPEITE,nCOMPED AS DWORD
LOCAL lACHEI AS LOGIC
LOCAL aDAD,APRO AS ARRAY
LOCAL nSALDO AS FLOAT
//AltD()
IF Empty(SELF:ODCPEPED)
    RETURN .f.
ENDIF
IF Empty(SELF:ODCPEITE)
   RETURN .f.
ENDIF
lACHEI:=.F.
nPEPED:=Val(SELF:oDCPEPED:TEXTVALUE)
nPEITE:=Val(SELF:ODCPEITE:TEXTVALUE)
nCOMPED:=0
aDAD:={zCURINI,"MW02.DBF",zCURDIR}
oMW02:=USEREDE{aDAD}
IF oMW02:nERRO=0
     oMW02:GOTOP()
     oMW02:SEEK(Str(nPEPED,8)+Str(nPEITE,3))
     IF oMW02:FOUND
     	IF oMW02:FIELDGET("BLQITEM")<>"S"
    	 	lACHEI:=.T.
	        SELF:oDCTIPCAD:Value:="F"
	        SELF:ODCTIPOE:VALUE:=oMW02:FIELDGET("ITETIP")
    	    IF SELF:ODCTIPOE:VALUE="T"	
        	   SELF:oDCCPRODUTO:TextValue:=oMW02:FIELDGET("ITECOD")
	           SELF:oDCCPRODUTO:Disable()
    	       SELF:oDCPESONFA:Enable()
        	   SELF:oDCPESONFB:Enable()
	        ELSE	
    	       SELF:ODCCBUSCA:TextValue:=oMW02:FIELDGET("ITECOD")
			   SELF:ODCCBUSCA:Disable()			
	        ENDIF
    	    nSALDO:=oMW02:FIELDGET("ITEQTD")-oMW02:FIELDGET("ITEENT")
	        IF nSALDO<0
    	       nSALDO:=0
	        ENDIF	
    	    SELF:ODCQTDEA:TextValue:=Str(nSALDO)
	        SELF:ODCQTDEPED:TextValue:=Str(nSALDO)
	        SELF:ODCPRECOPR:TextValue:=Str(oMW02:FIELDGET("ITEPRC"))
	        SELF:IPI:=oMW02:FIELDGET("ITEIPI")
	        SELF:oDCITEUNI:TextValue:=oMW02:FIELDGET("ITEUNI")
    	    SELF:oDCDESCRI:TextValue:=AllTrim(oMW02:FIELDGET("ITENOM"))+AllTrim(oMW02:FIELDGET("ITENO2"))
        	SELF:oDCTIPCAD:Disable()
	        SELF:ODCTIPOE:Disable()
	        SELF:oCCTIPOC:disable()
    	    SELF:oCCTIPOM:disable()
        	SELF:oCCTIPOT:disable()
	        SELF:oCCTIPOP:disable()
    	    SELF:oCCTIPOO:disable()
        	SELF:oDCPRPED:Disable()
	        SELF:oDCPRITE:Disable()
    	    SELF:oDCPEPED:Disable()
        	SELF:oDCPEITE:Disable()
	        SELF:ODCPEREQ:Disable()
    	    SELF:oDCAUT:Disable()
        	SELF:oCCCHKPED:Disable()
	        SELF:oCCCHKREQ:Disable()
    	    SELF:oCCCHKPRG:Disable()
	        SELF:oCCCHKPRC:Disable()
    	    SELF:odcpercli:TextValue:="0"
        	SELF:oDCReceber:Value:= .F.
	        SELF:oDCPEDCLI:TextValue:=oMW02:FIELDGET("PEDCLI")
    	    IF oMW02:FIELDGET("PEDCLI")="S"
        	   SELF:oDCReceber:Value:= .T.
	        ENDIF
    	    SELF:ODCPERCLI:Disable()
        	SELF:oCCESCFOR:DISABLE()
	        nCOMPED:=oMW02:FIELDGET("COMPED")
    	 ELSE
    	   oMW02:CLOSE()
           alert("Item do Pedido Bloqueado")
           SELF:ZERAVAL()
           RETURN .f.
        ENDIF
     ELSE
  	    oMW02:CLOSE()
        alert("Pedido Nao Encontrado")
        SELF:ZERAVAL()
       	RETURN .f.
     ENDIF
     oMW02:CLOSE()
ENDIF
IF nCOMPED>0
	aDAD:={zCURINI,"MW01.DBF",zCURDIR}
	oMW01:=USEREDE{aDAD}
	IF oMW01:nERRO=0
		oMW01:GOTOP()
		IF oMW01:SEEK(nCOMPED)
	       SELF:ODCCLIFOR:TextValue:=Str(oMW01:FIELDGET("COMFOR"))		
	       SELF:COGNOME:=oMW01:FIELDGET("COMCOG")
           SELF:PGTO:=oMW01:FIELDGET("COMCPAG")+"-"+AllTrim(oMW01:FIELDGET("COMCPAGD"))	
		   SELF:ODCCLIFOR:Disable()
		ENDIF	
	ENDIF
ENDIF
IF lACHEI
	aDAD:={zCURINI,"MY04.DBF",zCURDIR}
	oMY04:=USEREDE{aDAD}
	IF oMY04:nERRO=0
		oMY04:SetOrder(4)
	   oMY04:GOTOP()
	   IF oMY04:SEEK(Str(nPEPED,8)+Str(nPEITE,3))
    	  SELF:oDCTIPCAD:Value:="F"
	      SELF:ODCCLIFOR:TextValue:=Str(oMY04:FIELDGET("NUMMB01"))
     	  SELF:ODCTIPOE:VALUE:=oMY04:FIELDGET("TIPO2")
	      SELF:ODCCBUSCA:TextValue:=oMY04:FIELDGET("CODIGO")
	      SELF:ODCQTDEA:TextValue:=Str(oMY04:FIELDGET("QTDE"))
	      SELF:ODCQTDEPED:TextValue:=Str(oMY04:FIELDGET("QTDE"))	
   	      SELF:ODCNRNOTA:TextValue:=Str(oMY04:FIELDGET("NRNOTA"))
	      SELF:oDCTIPCAD:Disable()
	      SELF:ODCCLIFOR:Disable()
	      SELF:ODCTIPOE:Disable()
          SELF:ODCCBUSCA:Disable()
	      SELF:ODCQTDEA:Disable()
	      SELF:ODCNRNOTA:Disable()
	      SELF:oDCPRPED:Disable()
	      SELF:oDCPRITE:Disable()
          SELF:oDCPEPED:Disable()
    	  SELF:oDCPEITE:Disable()
	      SELF:ODCPEREQ:Disable()
	      SELF:oDCAUT:Disable()
	      SELF:oCCCHKPED:Disable()
	      SELF:oCCCHKREQ:Disable()
	      SELF:oCCCHKPRG:Disable()
      ENDIF
      oMY04:CLOSE()
   ENDIF	
ENDIF
SELF:CHKCTR(nCOMPED,nPEITE)
IF SELF:ODCTIPOE:VALUE="X"		
   SELF:ODCCBUSCA:ENABLE()
   SELF:ODCTIPOE:Enable()
ENDIF	
IF SELF:oDCTIPOE:Value="T"
   aPRO:=PEGMP03(AllTrim(SELF:oDCCPRODUTO:Value),zCURINI,zCURDIR)
   IF aPRO[1]
      SELF:oDCCBUSCA:TextValue:=aPRO[4]
      SELF:oDCCBUSCA:Disable()
   ENDIF
ENDIF
SELF:oDCmDATA:TextValue:=DToC(Today())
SELF:CHKPESO(.F.)
RETURN .f.

METHOD CHKPESO(lBUSCA) 
LOCAL cCODIGO AS STRING
LOCAL aPRO AS ARRAY
IF ValType(lBUSCA)#"L"
   lBUSCA:=.T.	
ENDIF	
cCODIGO:=SELF:oDCCPRODUTO:TextValue
IF ! SELF:XCHKPESO(cCODIGO,lBUSCA)
   aPRO:=PEGMP03(cCODIGO,ZCURINI,ZCURDIR) //Tenta SubApl
   IF aPRO[1]=.T. //Encontrou Tratamento
   	  IF ! Empty(Apro[6]) //O Sub Produto Nao esta vazio
      	  IF ! SELF:XCHKPESO(aPRO[6],lBUSCA)
      	  	 aPRO:=PEGMQ01(aPRO[7],ZCURINI,ZCURDIR) //Tenta Subproduto
      	  	 IF aPRO[1]=.T.
                SELF:PESO:=APRO[6]
      	  	 ENDIF	
      	  ENDIF	
      ELSE //sUB pRODUTO eSTA vAZIO
    	 aPRO:=PEGMQ01(aPRO[7],ZCURINI,ZCURDIR) //Tenta Subproduto
      	 IF aPRO[1]=.T.
            SELF:PESO:=APRO[6]
      	 ENDIF	
      ENDIF
   ENDIF	
ENDIF

METHOD CHKPRC() 
LOCAL oPE AS USEREDE
LOCAL nPERCLI AS LONG
LOCAL aDAD AS ARRAY
IF Empty(SELF:oDCPERCLI)
    RETURN .f.
ENDIF
nPERCLI:=Val(SELF:oDCPERCLI:TEXTVALUE)
aDAD:={zCURINI,"PEMO.DBF",zCURDIR}
oPE:=USEREDE{aDAD}
IF oPE:nERRO=0
   oPE:GOTOP()
   IF oPE:SEEK(nPERCLI)
   	  DO CASE
   	  	 CASE Empty(oPE:FIELDGET("CODIGO"))
   	  	 	  alert("Sem Codigo do Produto")
         OTHERWISE
             SELF:oDCPEPED:TextValue:="1"
             SELF:oDCPEITE:TextValue:="1"
             SELF:oDCTIPCAD:Value:="C"
             SELF:ODCCLIFOR:TextValue:=Str(oPE:FIELDGET("FORNECEDO"))
             SELF:ODCTIPOE:VALUE:=oPE:FIELDGET("TIPPED")
             SELF:ODCCBUSCA:TextValue:=oPE:FIELDGET("CODIGO")
             SELF:oDCDESCRI:TextValue:=AllTrim(oPE:FIELDGET("NOME"))+AllTrim(oPE:FIELDGET("NOM2"))
             SELF:oDCAPLICACAO:TextValue:=oPE:FIELDGET("APLICACAO")
  	         SELF:COGNOME:=oPE:FIELDGET("COGNOME")
             IF oPE:FIELDGET("TIPPED")="T"
             	SELF:oDCPESONFA:Enable()
             	SELF:oDCPESONFB:Enable()
             ENDIF
             SELF:oDCPEPED:Disable()
             SELF:oDCPEITE:Disable()
             SELF:oDCTIPCAD:Disable()
             SELF:ODCCLIFOR:Disable()
             SELF:ODCTIPOE:Disable()
             SELF:ODCCBUSCA:Disable()
             SELF:oDCPRPED:Disable()
             SELF:oDCPRITE:Disable()
             SELF:ODCPEREQ:Disable()
             SELF:oDCAUT:Disable()
             SELF:oCCCHKPED:Disable()
             SELF:oCCCHKREQ:Disable()
             SELF:oCCCHKPRG:Disable()
             SELF:oCCCHKPRC:Disable()
             SELF:oCClote:Disable()
             SELF:ODCPERCLI:Disable()
             SELF:oCCESCFOR:DISABLE()
      ENDCASE
   ELSE
   	  Ope:close()
      alert("Programação não Encontrada")
      SELF:ZERAVAL()
      RETURN .f.
   ENDIF
ENDIF
oPE:Close()
SELF:oDCmDATA:TextValue:=DToC(Today())





METHOD CHKPRG() 
LOCAL oPE01,oPE,oMW02 AS USEREDE
LOCAL nPRPED,nPRITE,nPEPED,nPEITE AS LONG
LOCAL aDAD AS ARRAY //apro
LOCAL lACHEI AS LOGIC
IF Empty(SELF:ODCPRPED)
    RETURN .f.
ENDIF
IF Empty(SELF:ODCPRITE)
   RETURN .f.
ENDIF
nPRPED:=Val(SELF:oDCPRPED:TEXTVALUE)
nPRITE:=Val(SELF:ODCPRITE:TEXTVALUE)
aDAD:={zCURINI,"PE01.DBF",zCURDIR}
oPE01:=USEREDE{aDAD}
IF oPE01:nERRO=0
   oPE01:GOTOP()
   oPE01:SEEK(Str(nPRPED,5)+Str(nPRITE,2))
   IF oPE01:FOUND
   	IF oPE01:FIELDGET("RECEBER")<>"S"
       SELF:oDCTIPCAD:Value:="F"
       SELF:ODCCLIFOR:TextValue:=Str(oPE01:FIELDGET("CLIENTE"))
       SELF:ODCTIPOE:VALUE:=oPE01:FIELDGET("TIPPED")
       SELF:ODCCBUSCA:TextValue:=oPE01:FIELDGET("CODIGO")
       SELF:ODCQTDEA:TextValue:=Str(oPE01:FIELDGET("TOTKGANT"))
       SELF:ODCQTDEPED:TextValue:=Str(oPE01:FIELDGET("TOTKGANT"))
       SELF:ODCQTDETOT:TextValue:=Str(oPE01:FIELDGET("TOTKGINI"))
       SELF:ODCQTDEANT:TextValue:=Str(oPE01:FIELDGET("TOTKGEST"))
       IF oPE01:FIELDGET("TIPPED")="T"
          SELF:oDCPESONFA:Enable()
          SELF:oDCPESONFB:Enable()
       ENDIF	
       SELF:oDCTIPCAD:Disable()
       SELF:ODCCLIFOR:Disable()
       SELF:ODCTIPOE:Disable()
       SELF:oCCTIPOC:disable()
       SELF:oCCTIPOM:disable()
       SELF:oCCTIPOT:disable()
       SELF:oCCTIPOP:disable()
       SELF:oCCTIPOO:disable()
       SELF:ODCCBUSCA:Disable()
       SELF:oDCPRPED:Disable()
       SELF:oDCPRITE:Disable()
       SELF:ODCPEREQ:Disable()
       SELF:oDCAUT:Disable()
       SELF:oCCCHKPED:Disable()
       SELF:oCCCHKREQ:Disable()
       SELF:oCCCHKPRG:Disable()
       SELF:oCCCHKPRC:Disable()
       SELF:ODCPERCLI:Disable()
       SELF:odcpercli:TextValue:="0"
       SELF:oDCReceber:Value:= .F.
       SELF:oCClote:Disable()
       SELF:oCCESCFOR:DISABLE()
     ELSE
      	oPE01:CLOSE()
        alert("Programação Já Utilizada")
        SELF:ZERAVAL()
       	RETURN .f.
     ENDIF
   ELSE
   	  oPE01:CLOSE()
      alert("Programação não Encontrada")
      SELF:ZERAVAL()
      RETURN .f.
   ENDIF
   oPE01:CLOSE()
ENDIF
aDAD:={zCURINI,"PE.DBF",zCURDIR}
oPE:=USEREDE{aDAD}
IF oPE:nERRO=0
   oPE:GOTOP()
   IF oPE:SEEK(nPRPED)
   	  DO CASE
   	  	 CASE Empty(oPE:FIELDGET("CODIGO"))
   	  	 	  alert("Sem Codigo do Produto")
   	  	 CASE oPE:FIELDGET("compras")=0
   	  	 	  alert("Sem Numero Pedido de Compras")
         OTHERWISE
             SELF:oDCPEPED:TextValue:=Str(oPE:FIELDGET("COMPRAS"))
             SELF:oDCPEITE:TextValue:=Str(oPE:FIELDGET("COMITEM"))
             SELF:oDCDESCRI:TextValue:=AllTrim(oPE:FIELDGET("NOME"))+AllTrim(oPE:FIELDGET("NOM2"))
             SELF:oDCAPLICACAO:TextValue:=oPE:FIELDGET("APLICACAO")
  	         SELF:COGNOME:=oPE:FIELDGET("COGNOME")
             SELF:oDCPEPED:Disable()
             SELF:oDCPEITE:Disable()
      ENDCASE
   ELSE
      alert("Programação não Encontrada")
      SELF:ZERAVAL()
   ENDIF
ENDIF
oPE:Close()
nPEPED:=Val(SELF:oDCPEPED:TEXTVALUE)
nPEITE:=Val(SELF:ODCPEITE:TEXTVALUE)
lACHEI:=.F.
aDAD:={zCURINI,"MW02.DBF",zCURDIR}
oMW02:=USEREDE{aDAD}
IF oMW02:nERRO=0
   oMW02:GOTOP()
   oMW02:SEEK(Str(nPEPED,8)+Str(nPEITE,3))
   IF oMW02:FOUND
      lACHEI:=.T.
        SELF:ODCPRECOPR:TextValue:=Str(oMW02:FIELDGET("ITEPRC"))
        SELF:IPI:=oMW02:FIELDGET("ITEIPI")
        SELF:oDCITEUNI:TextValue:=oMW02:FIELDGET("ITEUNI")
        SELF:oDCPEDCLI:TextValue:=oMW02:FIELDGET("PEDCLI")
        IF oMW02:FIELDGET("PEDCLI")="S"
           SELF:oDCReceber:Value:= .T.
        ENDIF
   ENDIF
   oMW02:CLOSE()
ENDIF
IF ! lACHEI //Tenta Baixados
   aDAD:={zCURINI,"MW02BX.DBF",zCURDIR}
   oMW02:=USEREDE{aDAD}
   IF oMW02:nERRO=0
      oMW02:GOTOP()
      oMW02:SEEK(Str(nPEPED,8)+Str(nPEITE,3))
      IF oMW02:FOUND
         SELF:ODCPRECOPR:TextValue:=Str(oMW02:FIELDGET("ITEPRC"))
         SELF:IPI:=oMW02:FIELDGET("ITEIPI")
         SELF:oDCITEUNI:TextValue:=oMW02:FIELDGET("ITEUNI")
         SELF:oDCPEDCLI:TextValue:=oMW02:FIELDGET("PEDCLI")
         IF oMW02:FIELDGET("PEDCLI")="S"
            SELF:oDCReceber:Value:= .T.
         ENDIF	
      ENDIF	
      oMW02:CLOSE()
   ENDIF
ENDIF	
SELF:PEGCPAG()
SELF:oDCmDATA:TextValue:=DToC(Today())
SELF:CHKCTR(nPEPED,nPEITE)

METHOD ChkRasFEC() 	
LOCAL ARETU AS ARRAY	
LOCAL oJAN AS JMESANO
oJAN:=JMESANO{SELF}
oJAN:SHOW()
aRETU:=XChkRastro(SELF,"M2"+oJAN:cCOMP,SELF:TIPOE,SELF:CBUSCA)
IF aRETU[1]
   SELF:SERVER:cRASTRO:=aRETU[2]
ENDIF	


METHOD ChkRastro  
LOCAL aRETU AS ARRAY	
aRETU:=XChkRastro(SELF,"MM02",SELF:TIPOE,SELF:CBUSCA)	
IF aRETU[1]
	SELF:SERVER:cRASTRO:=aRETU[2]
ENDIF	

METHOD CHKREQ() 
LOCAL oMY04,oMW02 AS USEREDE
LOCAL nPEREQ,nPEPED,nPEITE AS DWORD
LOCAL aDAD AS ARRAY
LOCAL lACHEI AS LOGIC
//LOCAL nSALDO AS FLOAT

IF Empty(SELF:ODCPEREQ)
   RETURN .f.
ENDIF
nPEREQ:=Val(SELF:oDCPEREQ:TEXTVALUE)
aDAD:={zCURINI,"MY04.DBF",zCURDIR}
oMY04:=USEREDE{aDAD}
IF oMY04:nERRO=0
   oMY04:GOTOP()
   oMY04:SEEK(nPEREQ)
   IF oMY04:FOUND
      SELF:oDClLOTE:Enable()
      SELF:oDCTIPCAD:Value:="F"
      SELF:ODCCLIFOR:TextValue:=Str(oMY04:FIELDGET("NUMMB01"))
      SELF:ODCTIPOE:VALUE:=oMY04:FIELDGET("TIPO2")
      SELF:ODCCBUSCA:TextValue:=oMY04:FIELDGET("CODIGO")
      SELF:ODCQTDEA:TextValue:=Str(oMY04:FIELDGET("QTDE"))
      SELF:ODCQTDEPED:TextValue:=Str(oMY04:FIELDGET("QTDE"))
      SELF:ODCNRNOTA:TextValue:=Str(oMY04:FIELDGET("NRNOTA"))
      SELF:oDCPEPED:TextValue:=Str(oMY04:FIELDGET("OS"))
      SELF:oDCPEITE:TextValue:=Str(oMY04:FIELDGET("ITEM"))
      SELF:oDCPRECOPR:TextValue:=Str(oMY04:FIELDGET("PRCMW02"))
      SELF:oDCPRECO:TextValue:=Str(oMY04:FIELDGET("PRCMy04"))
      SELF:oDCmDATA:Value:=oMY04:FIELDGET("data")
      SELF:oDCAUT:TEXTVALUE:=Str(oMY04:FIELDGET("AUT"))
      SELF:oDCTIPCAD:Disable()
      SELF:ODCCLIFOR:Disable()
      IF SELF:ODCTIPOE:VALUE="X"
         SELF:oCCpegcod1:Enable()
         SELF:oCCesccod2:Enable()
         SELF:oCCpegcod:Enable()
         SELF:oCCesccod:Enable()
         SELF:oDCcodavu:enable()
      ENDIF	
      IF SELF:ODCTIPOE:VALUE<>"X"
	     SELF:ODCTIPOE:Disable()
    	 SELF:ODCCBUSCA:Disable()
      ENDIF
      IF SELF:ODCTIPOE:VALUE="T"
         SELF:oDCPESONFA:Enable()
         SELF:oDCPESONFB:Enable()
      ENDIF
      SELF:ODCNRNOTA:Disable()
      SELF:oDCPRPED:Disable()
      SELF:oDCPRITE:Disable()
      SELF:oDCPEPED:Disable()
      SELF:oDCPEITE:Disable()
      SELF:ODCPEREQ:Disable()
      SELF:oDCAUT:Disable()
      SELF:oCCCHKPRC:Disable()
      SELF:oCCCHKPED:Disable()
      SELF:oCCCHKREQ:Disable()
      SELF:oCCCHKPRG:Disable()
      SELF:oCCESCFOR:Disable()
      SELF:ODCPERCLI:Disable()
      SELF:oDCPRECO:Disable()
      SELF:odcpercli:TextValue:="0"
      SELF:oDCReceber:Value:= .T.
      IF Omy04:FIELDGET("AUT")>0
         SELF:oDCReceber:Value:= .T.
         SELF:oDCREQAUT:Value:= .T.
      ENDIF	
      SELF:oDCReceber:Value:=.T.
  ELSE
 	  oMy04:CLOSE()
      alert("Requisiçao não Encontrada")
 	  SELF:ZERAVAL()
 	  RETURN .f.
   ENDIF
   oMY04:CLOSE()
ENDIF


nPEPED:=Val(SELF:oDCPEPED:TEXTVALUE)
nPEITE:=Val(SELF:ODCPEITE:TEXTVALUE)
lACHEI:=.F.
aDAD:={zCURINI,"MW02.DBF",zCURDIR}
oMW02:=USEREDE{aDAD}
IF oMW02:nERRO=0
   oMW02:GOTOP()
   oMW02:SEEK(Str(nPEPED,8)+Str(nPEITE,3))
   IF oMW02:FOUND
      lACHEI:=.T.
        SELF:oDCDESCRI:TextValue:=AllTrim(oMW02:FIELDGET("ITENOM"))+AllTrim(oMW02:FIELDGET("ITENO2"))
        SELF:oDCITEUNI:TextValue:=oMW02:FIELDGET("ITEUNI")
        SELF:IPI:=oMW02:FIELDGET("ITEIPI")
   ENDIF
   oMW02:CLOSE()
ENDIF
IF ! lACHEI //Tenta Baixados
   aDAD:={zCURINI,"MW02BX.DBF",zCURDIR}
   oMW02:=USEREDE{aDAD}
   IF oMW02:nERRO=0
      oMW02:GOTOP()
      oMW02:SEEK(Str(nPEPED,8)+Str(nPEITE,3))
      IF oMW02:FOUND
         SELF:oDCDESCRI:TextValue:=AllTrim(oMW02:FIELDGET("ITENOM"))+AllTrim(oMW02:FIELDGET("ITENO2"))
         SELF:oDCITEUNI:TextValue:=oMW02:FIELDGET("ITEUNI")
         SELF:IPI:=oMW02:FIELDGET("ITEIPI")
      ENDIF	
      oMW02:CLOSE()
   ENDIF
ENDIF	
aDAD:=PEGMB01(Val(SELF:oDCCLIFOR:TextValUE),ZCURINI,ZCURDIR)
IF aDAD[1]
   SELF:COGNOME:=aDAD[3]	
ENDIF	
SELF:PEGCPAG()
SELF:oDCmDATA:TextValue:=DToC(Today())




METHOD cmdALT( ) 
		SELF:cmdzera()	
		SELF:TIPCOD:="A"		


METHOD cmdAR( ) 
		SELF:cmdzera()	
		SELF:TIPCOD:="AR"


METHOD cmdb( ) 
		SELF:cmdzera()	
		SELF:TIPCOD:="B"		


METHOD cmdcrm( ) 
		SELF:cmdzera()	
		SELF:TIPCOD:=""


METHOD cmddev( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aCLI,Apro AS ARRAY
LOCAL nCRM AS DWORD
LOCAL cPEDIDO,cNOME,cCOGNOME AS STRING
aDAD:={zCURINI,"CRMDEV.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF

DO CASE
   CASE SELF:ODCTIPOE:Value=="C"
        aPRO:=PEGMT01(Trim(SELF:ODCCBUSCA:TextValue),zcurini,zcurdir)
        IF aPRO[1]=.F.
           alert("Componente Não Cadastrado")
       	  RETU NIL
        ENDIF
   CASE SELF:ODCTIPOE:Value=="M"
        aPRO:=PEGMU01(Trim(SELF:ODCCBUSCA:TextValue),zcurini,zcurdir)
        IF aPRO[1]=.F.
           alert("Materia Prima Não Cadastrada")
           RETU NIL
        ENDIF
   CASE SELF:ODCTIPOE:Value=="T"
        aPRO:=PEGMP03(Trim(SELF:ODCCPRODUTO:TextValue),zCURINI,zCURDIR)
        IF aPRO[1]=.F.
           alert("Tratamento Não Cadastrado")
           RETU NIL
        ENDIF
   CASE SELF:ODCTIPOE:Value=="P"
        aPRO:=PEGMS01(Trim(SELF:ODCCBUSCA:TextValue))
        IF aPRO[1]=.F.
           alert("Produto não Cadastrado")
           RETU NIL
        ENDIF
   CASE SELF:ODCTIPOE:Value=="X"
        aPRO:={.T.,"","","KG",""}
   OTHERWISE
        alert("Tipo Não Preenchido")
        RETU NIL
ENDCASE


DO CASE
 CASE SELF:ODCTIPCAD:Value=="C"
        aCLI:=PEGMA01(Val(SELF:ODCCLIFOR:TextValue),zCURINI,zCURDIR)
        IF aCLI[1]=.T.
	        cNOME:=aCLI[2]
	        cCOGNOME:=aCLI[3]
        ELSE
           alert("Cliente  Não Cadastrado")
           RETU NIL
        ENDIF
   CASE SELF:ODCTIPCAD:Value=="F"
        aCLI:=PEGMB01(Val(SELF:ODCCLIFOR:TextValue),zCURINI,zCURDIR)
        IF aCLI[1]=.T.
           cNOME:=aCLI[2]
           cCOGNOME:=aCLI[3]
        ELSE
           alert("Fornecedor  Não Cadastrado")
           RETU NIL
        ENDIF
ENDCASE

cPEDIDO:=StrTRIM(Val(SELF:ODCPEPED:TextValue),8,0)+"/"+StrTRIM(Val(SELF:ODCPEITE:TextValue),3,0)
	
oSERVER:setorder(1)
oSERVER:gobottom()
nCRM:=oSERVER:FIELDGET("CRM")
nCRM++
oSERVER:APPEND()
oSERVER:FIELDPUT("CRM",nCRM)
oSERVER:FIELDPUT("DATA",Today())
oSERVER:FIELDPUT("DESCRI",aPRO[2])
oSERVER:FIELDPUT("APLICACAO",aPRO[3])
oSERVER:FIELDPUT("CBUSCA",Trim(SELF:ODCCBUSCA:TextValue))
oSERVER:FIELDPUT("NOMEF",cNOME)
oSERVER:FIELDPUT("COGNOME",cCOGNOME)
oSERVER:FIELDPUT("CLIFOR",Val(SELF:ODCCLIFOR:TextValue))
oSERVER:FIELDPUT("TIPOE",SELF:ODCTIPOE:Value)
oSERVER:FIELDPUT("TIPCAD",SELF:ODCTIPCAD:Value)
oSERVER:FIELDPUT("QTDE",Val(SELF:ODCQTDEA:TextValue)+Val(SELF:ODCQTDEB:TextValue))
oSERVER:FIELDPUT("QTDEA",Val(SELF:ODCQTDEA:TextValue))
oSERVER:FIELDPUT("QTDEB",Val(SELF:ODCQTDEB:TextValue))
oSERVER:FIELDPUT("QTDEPED",Val(SELF:ODCQTDEPED:TextValue))
oSERVER:FIELDPUT("PRPED",Val(SELF:ODCPRPED:TextValue))
oSERVER:FIELDPUT("PRITE",Val(SELF:ODCPRITE:TextValue))
oSERVER:FIELDPUT("CERT",SELF:ODCCCERT:TextValue)
oSERVER:FIELDPUT("NRNOTA",Val(SELF:oDCNRNOTA:TextValue))
oSERVER:FIELDPUT("NRNOTB",Val(SELF:oDCNRNOTB:TextValue))
oSERVER:FIELDPUT("PEPED",Val(SELF:ODCPEPED:TextValue))
oSERVER:FIELDPUT("PEITE",Val(SELF:ODCPEITE:TextValue))
oSERVER:FIELDPUT("PEDIDO",cPEDIDO)
oSERVER:FIELDPUT("PEREQ",Val(SELF:ODCPEREQ:TextValue))
oSERVER:FIELDPUT("OBS",SELF:oDCOBS:TextValue)
oSERVER:FIELDPUT("TECNICO",ZFOLHA)
oSERVER:FIELDPUT("AUT",Val(SELF:ODCAUT:TextValue))
oSERVER:FIELDPUT("RASTRO",SELF:oDCcRASTRO:TextValue)
oSERVER:FIELDPUT("PRECO",Val(SELF:ODCPRECO:TextValue))
oSERVER:FIELDPUT("PRECOPR",Val(SELF:ODCPRECOPR:TextValue))
oSERVER:FIELDPUT("CLOTECRT","D")		//lOTE D DEVOLUCAO
oSERVER:FIELDPUT("PRCLI",Val(SELF:oDCPERCLI:TextValue))
IF SELF:TIPOE=="T"
    oSERVER:FIELDPUT("PRODUTO",Trim(SELF:ODCCPRODUTO:TextValue))
ENDIF
oSERVER:FIELDPUT("USERNM",ZUSER)
oSERVER:FIELDPUT("USERDT",Today())
oSERVER:FIELDPUT("USERHT",Time())
oSERVER:FIELDPUT("NRDATA",CToD(SELF:oDCmDATA:TextValue))
oSERVER:FIELDPUT("UNID","KG")
oSERVER:FIELDPUT("PESONFA",Val(SELF:ODCPESONFA:TextValue))
oSERVER:FIELDPUT("PESONFB",Val(SELF:ODCPESONFB:TextValue))
oSERVER:FIELDPUT("PEDCLI",SELF:oDCPEDCLI:TextValue)
oSERVER:FIELDPUT("ENTREGA",CToD(SELF:oDCentrega:TextValue))
oSERVER:FIELDPUT("ENTREG2",CToD(SELF:oDCentreg2:TextValue))
IF SELF:oDCtriangular:Value
   oSERVER:FIELDPUT("TRIANGULAR","S")	
ENDIF	
oSERVER:Commit()
GRAVALOG(NCRM,"INC","CRMDEV")	
alert("Devolucao Lancada")


METHOD cmdgera( ) 
SELF:cRASTRO:=CRIARASTRO(SELF:TIPCOD,SELF:RASTRONUM,SELF:RASTROANO,SELF:RASTROITEM)

METHOD cmdGERAAUT( ) 
LOCAL cMOTIVO,cMOTIV2 AS STRING
LOCAL oAUT AS USEREDE
LOCAL aDAD AS  ARRAY
LOCAL nAUT AS DWORD
cMOTIVO:="NF: "+AllTrim(Str(SELF:NRNOTA,8))+" de "+SELF:odcentrega:TextValue
IF ! IsNil(SELF:NRNOTB)
   IF SELF:NRNOTB>0
      cMOTIVO:=cMOTIVO+" NF: "+AllTrim(Str(SELF:NRNOTB,8))+" de "+SELF:odcentreg2:TextValue
   ENDIF
ENDIF	
cMOTIVO:=cMOTIVO+" "+AllTrim(Str(SELF:CLIFOR,8))+"-"+AllTrim(SELF:COGNOME)
IF Val(SELF:oDCPRECO:TextValue)>Val(SELF:oDCPRECOPR:TextValue)	
   cMOTIVO:=cMOTIVO+" Preco a Maior"	
ELSE
   cMOTIVO:=cMOTIVO+" Preco a Menor"		
ENDIF	
cMOTIV2:="Pedido: "+AllTrim(Str(SELF:PEPED,8))+"/"+AllTrim(Str(SELF:PEite,3))
cMOTIV2+=" R$ "+AllTrim(Str(SELF:precoPR,15,6))+" Faturado R$ "+AllTrim(Str(SELF:Preco,15,6))
//alert(Cmotiv2)
aDAD:={zCURINI,"AUT.DBF",zCURDIR}
oAUT:=USEREDE{aDAD}
IF oAUT:nERRO#0
   RETURN .f.
ENDIF
oAUT:GoBottom()
nAUT:=oAUT:FIELDGET("AUT")
nAUT:=nAUT+1
oAUT:Append()
oAUT:FIELDPUT("AUT",nAUT)
oAUT:FIELDPUT("MOTIVO",cMOTIVO)
oAUT:FIELDPUT("MOTIV2",cMOTIV2)
oAUT:FIELDPUT("DATA",Today())
oAUT:FIELDPUT("LIBFISCAL","N")
oAUT:CLOSE()
SELF:AUT:=nAUT
	




	

METHOD cmdmais2( ) 
SELF:oDCRASTROANO:TextValue:=Str(INCDEC(SELF:oDCRASTROANO:TextValue,1,1900,2100),4)						

METHOD cmdmenos2( ) 
SELF:oDCRASTROANO:TextValue:=Str(INCDEC(SELF:oDCRASTROANO:TextValue,-1,1900,2100),4)						

METHOD cmdmO( ) 
	SELF:cmdzera()
    SELF:TIPCOD:="MO"

METHOD cmdso( ) 
	SELF:cmdzera()
		SELF:TIPCOD:="SO"


METHOD cmdtrapro( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF SELF:ODCTIPOE:Value<>"T"
   alert("Não é Tratamento/Serviços")	
   RETURN .f.
ENDIF		
aDAD:={zCURINI,"MP03.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOTOP()
IF oSERVER:SEEK(AllTrim(SELF:oDCCPRODUTO:TextValue))
   SELF:oDCCBUSCA:TEXTVALUE:=oSERVER:FIELDGET("NORMA")
   SELF:oCCcmdtrapro:Disable()
   SELF:oDCCPRODUTO:Disable()
   SELF:oDCCBUSCA:DISABLE()
   SELF:bloqCOD()
ENDIF
oSERVER:CLOSE()	

	

METHOD cmdzera( ) 
		SELF:TIPCOD:=""
		SELF:RASTRONUM:=0
		SELF:cRASTRO:=""

METHOD desbloqCOD( ) 
SELF:oDCCBUSCA:Enable()
SELF:oDCTIPOE:Enable()
SELF:oCCTIPOC:Enable()
SELF:oCCTIPOM:Enable()
SELF:oCCTIPOT:Enable()
SELF:oCCTIPOO:Enable()
SELF:oCCTIPOP:Enable()
SELF:oCCpegcod1:Enable()
SELF:oCCesccod2:Enable()
SELF:oCCescPRO1:Enable()
SELF:oDCcodavu:Enable()
SELF:oCCCMDTRAPRO:Enable()
SELF:oCCpegcod:Enable()
SELF:oCCesccod:Enable()


METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
//LOCAL aFORN AS ARRAY
IF SELF:oDCTIPCAD:Value="F" .OR. SELF:oDCTIPCAD:Value="C"
	IF SELF:oDCTIPCAD:Value="F"
	   oESC:=XESCNUM{SELF,"MB01.DBF"}
	ELSE
	   oESC:=XESCNUM{SELF,"MA01.DBF"}
	ENDIF
	oESC:SHOW()	
	IF Oesc:lok
	    SELF:ODCCLIFOR:TextValue:=Str(oESC:NUMERO)
	ENDIF
ENDIF

METHOD escped() 
LOCAL oJAN AS Xescmw02
//LOCAL aDAD AS ARRAY
oJAN:=Xescmw02{SELF,ZCURINI,ZCURDIR,"ITETIP='T'"}
oJAN:SHOW()
IF oJAN:lOK
   SELF:oDCPePED:TextValue:=Str(oJAN:NUMERO,8)	
   SELF:oDCPEITE:TextValue:=Str(Ojan:ITEM,3)
   SELF:CHKPED()
ENDIF	

METHOD escprg() 
LOCAL oJAN AS XPEDIA
LOCAL oPE01 AS USEREDE
LOCAL aDAD AS ARRAY
oJAN:=XPEDIA{SELF,ZCURINI,ZCURDIR}
oJAN:SHOW()
IF oJAN:lOK
   SELF:oDCPRPED:TextValue:=Str(oJAN:NUMERO,8)	
   aDAD:={zCURINI,"PE01.DBF",zCURDIR}
   oPE01:=USEREDE{aDAD}
   IF oPE01:nERRO=0
      oPE01:GOTOP()
      oPE01:SEEK(Str(oJAN:NUMERO,5))
      IF oPE01:FIELDGET("PEDIDO")=oJAN:NUMERO .AND. ! oPE01:EoF
      	 SELF:oDCPRITE:TEXTVALUE:=Str(oPE01:FIELDGET("ITEM"),3)
      ENDIF
      oPE01:CLOSE()	
      SELF:CHKPRG()
   ENDIF
ENDIF	

METHOD ESCPRO( ) 
LOCAL oESC AS XESCCOD	
IF ! Empty(SELF:ODCCPRODUTO:TextValue)
   alert("Codigo Já Preencido")	
   RETURN .f.
ENDIF	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
	SELF:oDCCPRODUTO:TextValue:=Oesc:codigo
ENDIF					

METHOD ESCPRO1( ) 
LOCAL oESC AS XESCCOD	
IF SELF:ODCTIPOE:Value<>"T"
   alert("Não é Tratamento/Serviços")	
   RETURN .f.
ENDIF		
IF ! Empty(SELF:oDCCBUSCA:TextValue)
   alert("Codigo Já Preencido")	
   RETURN .f.
ENDIF	
oESC:=XESCCOD{SELF,"ETI.DBF"}
oESC:SHOW()	
IF Oesc:lok
	SELF:oDCCBUSCA:TextValue:=OESC:CODIGO
ENDIF					

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:oDCCPRODUTO:TextValue)," ",""))
IF Empty(cCODIGO)	
   cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:oDCCBUSCA:TextValue)," ",""))	
ENDIF	
IF Empty(cCODIGO)	
   alert("Codigo Produto Nao Preenchido")	
   RETURN .f.
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()
	

METHOD imprimir1( ) 
SELF:XWRPTGRP("CRM","PEMW")		


METHOD INCLUIR 
//LOCAL oARQ AS USEREDE
//LOCAL aDAD AS ARRAY	
LOCAL cARQ,cBUSCA AS STRING
LOCAL d01,d02 AS DATE
LOCAL nPESO AS FLOAT
LOCAL lAR AS LOGIC
lAR:=Val(SELF:ODCAr:TextValue)>0				
nPESO:=Val(SELF:oDCQTDEA:TextValue)+Val(SELF:oDCQTDEB:TextValue)
lOK:= .T.
aUSO:={}
IF Left(SELF:oDCCBUSCA:TextValue,2)="**"
   alert("Item com ** Verificar Pedido Compras/Programa")	
   RETURN .f.
ENDIF	
IF SELF:ODCTIPOE:Value="T"
  IF Val(SELF:oDCQTDEA:TextValue)=0
     alert("Tratamento/Serviços Requer QTDE")	
     SELF:oDCQTDEA:SetFocus()
     RETURN .f.
  ENDIF	
  IF Val(SELF:oDCPESONFA:TextValue)=0
     alert("Tratamento/Serviços Requer Peso")	
     SELF:oDCPESONFA:SetFocus()
     RETURN .f.
  ENDIF	
  IF Val(SELF:oDCQTDEB:TextValue)=0 .AND. Val(SELF:oDCPESONFB:TextValue)>0
     alert("Tratamento/Serviços Requer QTDE")	
     SELF:oDCQTDEB:SetFocus()
     RETURN .f.
  ENDIF	
  IF Val(SELF:oDCQTDEB:TextValue)>0 .AND. Val(SELF:oDCPESONFB:TextValue)=0
     alert("Tratamento/Serviços Requer Peso")	
     SELF:oDCPESONFB:SetFocus()
     RETURN .f.
  ENDIF	
ENDIF	
IF SELF:ODCTIPOE:Value="T" .and. Empty(SELF:oDCcRASTRO:TextValue)
   alert("Tratamento/Serviços Requer Rastreabilidade")	
   SELF:oDCcRASTRO:SetFocus()
   RETURN .f.
ENDIF
IF SELF:ODCTIPOE:Value<>"T" .and. ! Empty(SELF:oDCcRASTRO:TextValue)
   IF ! MDG("Aceitar Lote Indicado-->"+SELF:oDCcRASTRO:TextValue)
   	  RETURN .f.
   ENDIF	
ENDIF	
IF Val(SELF:oDCPEPED:TextValue)=0 .AND. Val(SELF:ODCAUT:TextValue)=0 .and. ! LAR
   alert("Sem Numero de Pedido","Erro")
   alert("Requer Autorização","Erro")
   SELF:oDCAUT:ENABLE()
   RETURN .f.
ENDIF
IF Val(SELF:oDCNRNOTA:TextValue)<>0 .and. Empty(SELF:odcentrega)
   alert("Falta data Entrega NrNota","Erro")
   RETURN .f.
ENDIF	
IF Val(SELF:oDCNRNOTB:TextValue)<>0 .and. Empty(SELF:odcentreg2)
   alert("Falta data Entrega NrNota-2","Erro")
   RETURN .f.
ENDIF
IF ! Empty(SELF:odcentregA) .AND. ! Empty(SELF:oDCmDATA)
   d01:=CToD(SELF:oDCMDATA:TextValue)
   d02:=CToD(SELF:oDCENTREGA:TextValue)
   IF Abs(D01-D02)>10
   	  IF ! MDG("Datas NF1-Entrega <>10 Dias - Continuar?")
   	  	  RETURN .f.
   	  ENDIF	
   ENDIF	
ENDIF	
IF ! Empty(SELF:odcentreg2) .AND. ! Empty(SELF:oDCmDATA)
   d01:=CToD(SELF:oDCMDATA:TextValue)
   d02:=CToD(SELF:oDCENTREG2:TextValue)
   IF Abs(D01-D02)>10
   	  IF ! MDG("Datas NF2-Entrega <> 10 Dias - Continuar?")
   	  	  RETURN .f.
   	  ENDIF	
   ENDIF	
ENDIF	
IF Val(SELF:oDCNRNOTA:TextValue)=0 .AND. Val(SELF:oDCNRNOTB:TextValue)=0
   alert("Necessário Numero de Nota Fiscal","Erro")
   SELF:oDCNRNOTA:SetFocus()
   RETURN .f.
ENDIF
IF Val(SELF:oDCQTDEA:TextValue)=0 .AND. Val(SELF:oDCQTDEB:TextValue)=0
   alert("Necessário Quantidade","Erro")
   SELF:oDCQTDEA:SetFocus()
   RETURN .f.
ENDIF
IF nPESO>Val(SELF:oDCQTDEPED:TextValue)*1.1 .and. (SELF:oDCCARGA:Value)<>.T. .and. Val(SELF:ODCAUT:TextValue)=0 .and. ! LAR
   alert("Carga Excessiva Requer Autorizaçäo","Erro")
   IF SELF:ODCTIPOE:Value="T"
      SELF:oDCCarga:Enable()
      SELF:ODCQTDEA:Disable()
      SELF:ODCQTDEB:Disable()
   ENDIF
   IF nPESO+Val(SELF:oDCQTDEANT:TextValue)<Val(SELF:oDCQTDETOT:TextValue)*1.1
      SELF:oDCCarga:Enable()
      SELF:ODCQTDEA:Disable()
      SELF:ODCQTDEB:Disable()
   ENDIF	
   IF Val(SELF:oDCPRPED:TEXTVALUE)>0 //Programacao Libera carga Excessiva
      SELF:oDCCarga:Enable()
   ENDIF	
   IF Val(SELF:oDCPERCLI:TEXTVALUE)>0 //Programcao Clinte Libera Carga Excessiva
      SELF:oDCCarga:Enable()
   ENDIF	
   SELF:oDCQTDEA:SetFocus()
   SELF:oDCAUT:ENABLE()
   RETURN .f.
ENDIF
IF nPESO<Val(SELF:oDCQTDEPED:TextValue)*.9 .and. (SELF:oDCCARGA:Value)<>.T.	
   alert("Carga Inferior Requer Autorizaçäo","Erro")
   SELF:oDCCarga:Enable()
   SELF:oDCAUT:ENABLE()
   SELF:ODCQTDEA:Disable()
   SELF:ODCQTDEB:Disable()
   SELF:oDCQTDEA:SetFocus()
   RETURN .f.
ENDIF
IF Val(SELF:oDCPRECO:TextValue)=0
   alert("Necessário Preço","Erro")
   SELF:ODCPRECO:SetFocus()
   RETURN .f.
ENDIF
IF Val(SELF:oDCCLIFOR:TextValue)=0
   alert("Necessário Numero Cliente/Fornecedor","Erro")
   SELF:ODCCLIFOR:SetFocus()
   RETURN .f.
ENDIF
IF Empty(SELF:oDCtipcad:TextValue)
   alert("Necessário Tipo Cliente/Fornecedor","Erro")
   RETURN .f.
ENDIF
IF Empty(SELF:oDCtipoe:TextValue)
   alert("Necessário Tipo de Entrada","Erro")
   RETURN .f.
ENDIF
IF Val(SELF:oDCPRECOPR:TextValue)=0 .AND. Val(SELF:ODCAUT:TextValue)=0 .AND. Val(SELF:oDCPERCLI:TEXTVALUE)=0
   alert("Sem Preço Compras Verifique Pedido","Erro")
   alert("Ou Numero de Autorização","Erro")
   SELF:OCCCMDGERAAUT:Enable()
   SELF:OCCCMDGERAAUT:SetFocus()
   SELF:oDCAUT:ENABLE()
   RETURN .f.
ENDIF
IF (Val(SELF:oDCPRECO:TextValue)<>Val(SELF:oDCPRECOPR:TextValue)) ;
    .and. Val(SELF:ODCAUT:TextValue)=0 ;
    .and. (SELF:oDCReceber:Value)<>.T.;
    .and. (SELF:oDCtriangular:Value)<>.T.;
    .and. Val(SELF:oDCPERCLI:TEXTVALUE)=0
   alert("Preço Diferente do Pedido","Erro")
   alert("Verifique o Preço"+Chr(13)+Chr(10)+"Nº Autorizacao"+Chr(13)+Chr(10)+"Triangular")
   SELF:OCCCMDGERAAUT:Enable()
   SELF:OCCCMDGERAAUT:SetFocus()
   SELF:oDCAUT:ENABLE()
   RETURN .f.
ENDIF
IF SELF:oDClLOTE:Value=.T. .AND. Empty(SELF:oDCAPLICACAO:TextValue) .AND. Empty(SELF:oDCDESCRI:TextValue)
   alert("Lote Piloto Requer Aplicaçao e Descriçao DO Material")
   SELF:lote( )
   RETURN .f.
ENDIF
IF SELF:oDCEnsaios:Value=.T. .AND. Empty(SELF:oDCAPLICACAO:TextValue) .AND. Empty(SELF:oDCDESCRI:TextValue)
   alert("Ensaios Avulsos Requer Aplicaçao e Descriçao DO Material")
   SELF:lote( )
   RETURN .f.
ENDIF
IF SELF:oDCEnsaios:Value=.T. .and. SELF:oDClLOTE:Value=.T.
   alert("Escolha Ensaios ou Lote Piloto")
   RETURN .f.	
ENDIF	
IF SELF:oDClLOTE:Value=.T.
   IF SELF:oDCTIPOE:Value $ "TCM"	
   ELSE	
      alert("Lote Piloto Requer Tipo Entrada M,C,T")
     RETURN .f.
   ENDIF
ENDIF
IF SELF:oDCEnsaios:Value=.T.
   IF SELF:oDCTIPOE:Value $ "TCM"	
   ELSE		
     alert("Ensaios Avulsos Requer Tipo Entrada M,C,T")
     RETURN .f.
   ENDIF
ENDIF

IF SELF:oDCTIPOE:Value $ "TCM"
   IF .NOT. checkens(SELF:ODCTIPOE:VALUE,SELF:oDCCBUSCA:TEXTVALUE)	
      RETURN .f.
   ENDIF
ENDIF

//ERRORBOX("oK","OK")
//RETU

AAdd(aUSO,SELF:ODCTIPCAD:Value)				  //01
AAdd(aUSO,Val(SELF:ODCCLIFOR:TextValue))    //02
AAdd(aUSO,Val(SELF:ODCPRPED:TextValue))     //03
AAdd(aUSO,Val(SELF:ODCPRITE:TextValue))     //04
AAdd(aUSO,Val(SELF:ODCQTDEA:TextValue))      //05
AAdd(aUSO,SELF:ODCTIPOE:Value)              //06
AAdd(aUSO,Trim(SELF:ODCCBUSCA:TextValue))   //07
AAdd(aUSO,Trim(SELF:ODCCPRODUTO:TextValue)) //08
AAdd(aUSO,SELF:ODCCCERT:TextValue)          //09
AAdd(Auso,SELF:oDClLOTE:Value)              //10
AAdd(Auso,SELF:oDCOBS:TextValue)            //11
AAdd(aUSO,Val(SELF:oDCNRNOTA:TextValue))    //12
AAdd(aUSO,Val(SELF:ODCPEPED:TextValue))     //13
AAdd(aUSO,Val(SELF:ODCPEITE:TextValue))     //14
AAdd(aUSO,Val(SELF:ODCPEREQ:TextValue))     //15
AAdd(aUSO,Val(SELF:ODCAUT:TextValue))       //16
AAdd(aUSO,CToD(SELF:oDCmDATA:TextValue))    //17
AAdd(aUSO,SELF:oDCcRASTRO:TextValue)        //18
AAdd(aUSO,Val(SELF:oDCNRNOTB:TextValue))    //19
AAdd(aUSO,Val(SELF:ODCQTDEB:TextValue))     //20
AAdd(aUSO,Val(SELF:ODCPRECO:TextValue))     //21
AAdd(aUSO,Val(SELF:ODCPRECOPR:TextValue))     //22
AAdd(aUSO,Val(SELF:oDCDESCRI:TextValue))     //23
AAdd(aUSO,Val(SELF:oDCAPLICACAO:TextValue))     //24
AAdd(aUSO,Val(SELF:oDCPERCLI:TextValue)) //25
AAdd(aUSO,Val(SELF:ODCQTDEPED:TextValue))     //26
AAdd(Auso,SELF:oDCEnsaios:Value) //27
AAdd(aUSO,SELF:oDCREQAUT:Value)//28
AAdd(aUSO,Val(SELF:ODCPESONFA:TextValue))     //29
AAdd(aUSO,Val(SELF:ODCPESONFB:TextValue))     //30
AAdd(Auso,SELF:oDCPEDCLI:TextValue)            //31
AAdd(aUSO,CToD(SELF:oDCentrega:TextValue))    //32
AAdd(aUSO,CToD(SELF:oDCentreg2:TextValue))    //33
AAdd(aUSO,SELF:oDCtriangular:Value)//34
SELF:EndWindow()

METHOD lote( ) 
	SELF:oDClLOTE:Value:=.T.
	SELF:oDCAPLICACAO:Enable()
	SELF:oDCDESCRI:ENABLE()
	SELF:oDClLOTE:Enable()
	SELF:oDCOBS:TEXTVALUE:="Outras Aplicações"

METHOD PEGCPAG 
LOCAL nCOMPED AS DWORD
nCOMPED:=Val(SELF:oDCPEPED:TEXTVALUE)	
SELF:PGTO:=PEGCPAG(nCOMPED)	

METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
    SELF:RASTROANO:=Year(Today())
     FabCenterWindow( SELF )
	RETURN NIL


METHOD TIPOC( ) 
	SELF:TIPOE:="C"

METHOD TIPOM( ) 
	SELF:TIPOE:="M"
	

METHOD TIPOO( ) 
	SELF:TIPOE:="X"

METHOD TIPOP( ) 
	SELF:TIPOE:="P"

METHOD TIPOT( ) 
SELF:TIPOE:="T"	
IF	Val(SELF:oDCPEREQ:TextValue)>0
	SELF:oDCPESONFA:Enable()
	SELF:odcpesonfb:Enable()
ENDIF

METHOD XCHKPESO(cCODIGO,lBUSCA) 
LOCAL aPRO AS ARRAY
LOCAL oJAN AS XBUSCA
IF ValType(lBUSCA)#"L"
   lBUSCA:=.T.
ENDIF	
IF ValType(cCODIGO)#"C" .OR. Empty(cCODIGO)	
   IF lBUSCA
   	  cCODIGO:=Space(24)
  	ELSE
      RETU .F.
   ENDIF
ENDIF
IF lBUSCA
   oJAN:=XBUSCA{SELF,"Codigo do Produto","Confirme o Produto",cCODIGO}
   oJAN:SHOW()
   IF ! oJAN:lOK
      RETU .F.
   ENDIF
   Ccodigo:=Ojan:cbusca
ENDIF
aPRO:=PEGMS01(cCODIGO)
IF aPRO[1]=.T.
   SELF:PESO:=APRO[6]
   RETU .T.
ENDIF	
RETU .F.

METHOD ZERAVAL 
SELF:oDCPEREQ:TEXTVALUE:="0"
SELF:oDCPEPED:TEXTVALUE:="0"
SELF:ODCPEITE:TEXTVALUE:="0"
SELF:oDCPRPED:TEXTVALUE:="0"
SELF:ODCPRITE:TEXTVALUE:="0"
SELF:oDCPERCLI:TEXTVALUE:="0"
SELF:oDCAUT:TextValue:="0"
SELF:oDCCLIFOR:TextValue:="0"
SELF:oDCPRECOPR:TEXTVALUE:="0"
SELF:oDCCarga:VALUE:=.F.
SELF:oDClLOTE:VALUE:=.F.
SELF:oDCReceber:VALUE:=.F.
SELF:oDCEnsaios:Value:=.F.
SELF:oDCREQAUT:Value:=.F.
SELF:oDCCOGNOME:Value:=""
SELF:oDCTIPOE:TEXTVALUE:=""
SELF:oDCCBUSCA:TextValue:=""
SELF:oDCPGTO:TEXTVALUE:=""
SELF:oDCDESCRI:TextValue:=""
SELF:oCCTIPOC:Enable()
SELF:oCCTIPOM:Enable()
SELF:oCCTIPOT:Enable()
SELF:oCCTIPOP:Enable()
SELF:oCCTIPOO:Enable()
SELF:oDCPEREQ:Enable()
SELF:oDCPEPED:Enable()
SELF:ODCPEITE:Enable()
SELF:oDCPRPED:Enable()
SELF:ODCPRITE:Enable()
SELF:oDCPERCLI:Enable()

	

END CLASS
FUNCTION CHECKALT(cTIPCOD,nRASTRONUM,nRASTROANO)
LOCAL oSERVER AS USEREDE
LOCAL ADAD AS ARRAY
LOCAL cBUSCA AS STRING
LOCAL nERRO AS WORD
LOCAL lRETU AS LOGIC

nERRO:=0
lRETU:=.F.
cBUSCA:=cTIPCOD+StrZero(nRASTRONUM,4)+"/"+StrZero(nRASTROANO,4)
//alert(cBUSCA)
aDAD:={zCURINI,"CRMA.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU lRETU
ENDIF
oSERVER:SetOrder(2)
oSERVER:GOTOP()
IF  oSERVER:Seek(cBUSCA)
   lRETU:=.T.
ELSE	
   nERRO:=1	
ENDIF
oSERVER:CLOSE()
IF nERRO=1
   alert("Rastro Alternativo nao Encontrado")
ENDIF
RETU lRETU

FUNCTION checkens(cTIPO,cCODIGO)
LOCAL cMES AS STRING
LOCAL aDAD AS ARRAY
LOCAL oARQ AS USEREDE
LOCAL cARQ AS STRING
AltD()
cMES:="Ensaios PARA RIRM ou Rist não Cadastrados"
IF ValType(cTIPO)#"C" .OR. ValType(cCODIGO)#"C"
   alert (cmes )
   RETU .f.
ENDIF	
CCODIGO:=AllTrim(CCODIGO)
IF Empty(cTIPO) .OR. Empty(cCODIGO)
   alert (cmes)
   RETU .f.
ENDIF	
IF CTIPO $ "TCM"
   cARQ:="MU01I"
   DO CASE
   	  CASE CTIPO="T"
   	  	 cARQ:="MP03I"
   	  CASE CTIPO="C"
   	  	 cARQ:="MT01I"
   ENDCASE
   aDAD:={zCURINI,cARQ+".DBF",zCURDIR}
   oARQ:=USEREDE{aDAD}
   IF oARQ:nERRO=0
      oARQ:GOTOP()
	  oARQ:SEEK(cCODIGO)
	  IF (cCODIGO<>AllTrim(oARQ:FIELDGET("CODIGO"))) .OR. oARQ:EOF
	  	 oARQ:CLOSE()	
	     alert("Ensaios PARA RIRM ou Rist não Cadastrados")
         RETU .F.
	  ENDIF	
	  oARQ:Close()	
   ENDIF
ENDIF
RETU .T.


FUNC DELEENS(cARQ,cARQI,nNUMERO,cCAMPO)
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,cARQ,zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETURN .f.
ENDIF
aDAD:={zCURINI,cARQI,zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETURN .f.
ENDIF	
oSERVER:GOTOP()
IF oSERVER:SEEK(nNUMERO)
   oSERVER:DELETE()
   oSERVE2:GOTOP()
   oSERVE2:sEEK(nNUMERO)
   WHILE oSERVE2:FIELDGET(cCAMPO)=nNUMERO  .AND. ! oSERVE2:EOF
	  	 oSERVE2:DELETE()
		 oSERVE2:SKIP()
   ENDDO					
ENDIF		
oSERVER:CLOSE()
oSERVE2:CLOSE()

	






FUNCTION GRAVARASTRO(nRASTRO,nCRM,nRIRM,nRIST,cCODIGO,cOBS)
LOCAL oCRMR AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"CRMR.DBF",zCURDIR}
oCRMR:=USEREDE{aDAD}
IF oCRMR:nERRO=0
    oCRMR:GOTOP()
    IF oCRMR:SEEK(nRASTRO)
       oCRMR:FIELDPUT("CRM",nCRM)
       oCRMR:FIELDPUT("RIRM",nRIRM)
       oCRMR:FIELDPUT("RIST",nRIST)
       oCRMR:FIELDPUT("PRODUTO",cCODIGO)
       oCRMR:FIELDPUT("OBS",cOBS)
    ENDIF
    oCRMR:CLOSE()

ENDIF
RETURN .f.

FUNCTION NOVOLOTE(nFORN,cCODIGO)
LOCAL nLOTE AS WORD
LOCAL cLOTE AS STRING
LOCAL aDAD AS ARRAY
LOCAL oCRML AS USEREDE
nLOTE:=0
cLOTE:="0"
aDAD:={zCURINI,"CRML.DBF",zCURDIR}
oCRML:=USEREDE{aDAD}
IF oCRML:nERRO=0
   oCRML:GOTOP()
   oCRML:SEEK(Str(nFORN,8)+CCODIGO)
   IF oCRML:FOUND
      nLOTE:=oCRML:FIELDGET("LOTE")
      nLOTE++
      IF nLOTE=11 //Era 6 Mudou 11
         nLOTE:=1
      ENDIF
      oCRML:FIELDPUT("LOTE",nLOTE)
   ELSE
      oCRML:APPEND()
      oCRML:FIELDPUT("CLIFOR",nFORN)
      oCRML:FIELDPUT("CODIGO",cCODIGO)
      oCRML:FIELDPUT("LOTE",1)
      nLOTE:=1
   ENDIF
   oCRML:CLOSE()
ENDIF
IF nlote=10	
   cLOTE:="0"
ELSE
  cLOTE:=Str(nLOTE,1)	
ENDIF
RETU cLOTE


FUNCTION NOVORASTRO()
LOCAL nRASTRO AS DWORD
LOCAL cRASTRO AS STRING
LOCAL aRETU AS ARRAY
LOCAL oCRMR AS USEREDE
LOCAL aDAD AS ARRAY
aRETU:={0,""}
aDAD:={zCURINI,"CRMR.DBF",zCURDIR}
oCRMR:=USEREDE{aDAD}
IF oCRMR:nERRO=0
    oCRMR:gobottom()
    nRASTRO:=oCRMR:FIELDGET("RASTRON")
    nRASTRO++
    oCRMR:APPEND()
    oCRMR:FIELDPUT("RASTRON",nRASTRO)
    oCRMR:FIELDPUT("RASTROA",Year(Today()))
    cRASTRO:=StrZero(nRASTRO,4)+"/"+Str(oCRMR:FIELDGET("RASTROA"),4)
    oCRMR:FIELDPUT("RASTRO",cRASTRO)
    oCRMR:FIELDPUT("DATA",Today())
    oCRMR:CLOSE()
    aRETU:={nRASTRO,cRASTRO}
ENDIF
RETU ARETU

FUNCTION PEGCPAG(nCOMPED)
LOCAL aDAD AS ARRAY
LOCAL oMW01 AS USEREDE
LOCAL lACHEI AS LOGIC
LOCAL cPGTO AS STRING
cPGTO:=""
IF nCOMPED>0
	lACHEI:=.F.
	aDAD:={zCURINI,"MW01.DBF",zCURDIR}
	oMW01:=USEREDE{aDAD}
	IF oMW01:nERRO=0
		oMW01:GOTOP()
		IF oMW01:SEEK(nCOMPED)
           CPGTO:=oMW01:FIELDGET("COMCPAG")+"-"+AllTrim(oMW01:FIELDGET("COMCPAGD"))	
           lACHEI:=.T.
		ENDIF	
	    oMW01:CLOSE()
	ENDIF	
    IF ! lACHEI
    	aDAD:={zCURINI,"MW01BX.DBF",zCURDIR}
	    oMW01:=USEREDE{aDAD}
    	IF oMW01:nERRO=0
	       oMW01:GOTOP()
 		   IF oMW01:SEEK(nCOMPED)
              CPGTO:=oMW01:FIELDGET("COMCPAG")+"-"+AllTrim(oMW01:FIELDGET("COMCPAGD"))	
              lACHEI:=.T.
    	   ENDIF	
	    oMW01:CLOSE()
    	ENDIF	
    ENDIF	
ENDIF
RETU cPGTO

	

FUNCTION XChkRastro(oOWNER,cARQ,cTIPO,cCODIGO)
LOCAL oBUSCA AS XBUSCA
LOCAL oARQ AS USEMANA5
LOCAL aDAD AS ARRAY
LOCAL nNRNOTA AS DWORD	
LOCAL cRASTRO AS STRING
LOCAL aTMP AS ARRAY
LOCAL aRETU AS ARRAY
aRETU:={.F.,""}
IF cTIPO<>"T"
   alert("Não é Tratamento Servicos Tratamento/Serviços")	
   RETU aRETU
ENDIF		





oBUSCA:=XBUSCA{oOWNER,"Codigo do Produto","Confirme o Produto",cCODIGO}
oBUSCA:SHOW()
IF ! oBUSCA:lOK
	RETU ARETU
ENDIF
Ccodigo:=AllTrim(OBUSCA:cbusca)



oBUSCA:=XBUSCA{oOWNER,"Localizar Rastro","Digite Nº Nossa Nota Fiscal"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU ARETU
ENDIF
nNRNota:=Val(oBUSCA:cBUSCA)
aDAD:={zCURINI,cARQ,zCURDIR,aDIR}
oARQ:=USEMANA5{aDAD}
IF ! oARQ:USED	
   RETU ARETU
ENDIF
oARQ:GOTOP()
oARQ:SEEK(Str(nNRNOTA,8))
WHILE nNRNOTA=oARQ:FIELDGET("NUMERO") .AND. ! oARQ:EoF
	IF oARQ:FIELDGET("TIPOENT")="T"
	   IF AllTrim(oARQ:FIELDGET("CODIGO"))=cCODIGO
          cRASTRO:=oARQ:FIELDGET("RASTRO")	
          aTMP:=CHECKRASTRO(cRASTRO)	
          IF aTMP[1]
          	 aRETU[2]:=aTMP[2]
          ENDIF	
	   ENDIF	
	ENDIF	
	oARQ:SKIP()
ENDDO	
oARQ:CLOSE()
RETU aRETU


