PARTIAL CLASS crmJanTri
METHOD Cancelar( ) 
	SELF:EndWindow()

METHOD cmdGeraAut( ) 
LOCAL cMOTIVO,cMOTIV2 AS STRING
LOCAL oAUT AS USEREDE
LOCAL aDAD AS  ARRAY
LOCAL nAUT AS DWORD
cMOTIVO:="NF: "+AllTrim(Str(SELF:SERVER:FIELDGET("NRNOTA"),8))+" de "+DToC(SELF:SERVER:FIELDGET("entrega"))
IF SELF:SERVER:FIELDGET("NRNOTB")>0
  cMOTIVO:=cMOTIVO+" NF: "+AllTrim(Str(SELF:SERVER:FIELDGET("NRNOTB"),8))+" de "+DToC(SELF:SERVER:FIELDGET("entreg2"))
ENDIF	
cMOTIVO:=cMOTIVO+" "+AllTrim(Str(SELF:SERVER:FIELDGET("CLIFOR"),8))+"-"+AllTrim(SELF:SERVER:FIELDGET("COGNOME"))
IF SELF:SERVER:FIELDGET("PRECO")>SELF:SERVER:FIELDGET("PRECOPR")
   cMOTIVO:=cMOTIVO+" Preco a Maior"	
ELSE
   cMOTIVO:=cMOTIVO+" Preco a Menor"		
ENDIF	
cMOTIV2:="Pedido: "+AllTrim(Str(SELF:SERVER:FIELDGET("PEPED"),8))+"/"+AllTrim(Str(SELF:SERVER:FIELDGET("PEite"),3))
cMOTIV2+=" R$ "+AllTrim(Str(SELF:SERVER:FIELDGET("precoPR"),15,6))+" Faturado R$ "+AllTrim(Str(SELF:SERVER:FIELDGET("Preco"),15,6))
//alert(Cmotiv2)
aDAD:={zCURINI,"AUT.DBF",zCURDIR}
oAUT:=USEREDE{aDAD}
IF oAUT:nERRO#0
   RETU
ENDIF
oAUT:GoBottom()
nAUT:=oAUT:FIELDGET("AUT")
nAUT:=nAUT+1
oAUT:Append()
oAUT:FIELDPUT("AUT",nAUT)
oAUT:FIELDPUT("MOTIVO",cMOTIVO)
oAUT:FIELDPUT("MOTIV2",cMOTIV2)
oAUT:FIELDPUT("DATA",Today())
oAUT:FIELDPUT("LIBFISCAL","N")
oAUT:FIELDPUT("USADA",.T.)
oAUT:CLOSE()
SELF:SERVER:FIELDPUT("AUT",nAUT)

METHOD INCLUIR( ) 
IF SELF:SERVER:FIELDGET("PRECO")<>SELF:SERVER:FIELDGET("PRECOPR") ;
    .AND. Empty(SELF:SERVER:FIELDGET("AUT"))
   alert("Preço Diferente do Pedido","Erro")
   alert("Verifique o Preço")
   SELF:OCCCMDGERAAUT:Enable()
   SELF:OCCCMDGERAAUT:SetFocus()
//   SELF:oDCAUT:ENABLE()
   RETU
ENDIF		
SELF:SERVER:FIELDPUT("TRIANGULAR","V")
SELF:EndWindow()

METHOD PEGCPAG 
LOCAL nCOMPED AS DWORD
nCOMPED:=SELF:SERVER:FIELDGET("PEPED")	
SELF:PGTO:=PEGCondPAG(nCOMPED)	


METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
//	AltD()
	SELF:PEGCPAG()
	 FabCenterWindow( SELF )
	RETURN NIL



END CLASS
