CLASS XJCRM INHERIT JCRM

METHOD APPEND(oOWNER) 
LOCAL OJCRMNEW AS JCRMnew
LOCAL aFOR,aFORN,aCLI,aPRO,aDAD,aMS01,aCRIST AS ARRAY
LOCAL cNOME,cCOGNOME,cLOTE,cPEDIDO,cRASTRO AS STRING
LOCAL oCRMNF,oAUT,oMP03I,oMT01I,oMY04,oCRMEST AS USEREDE
LOCAL llote1,lRASTRO,lCARTA,lPRECO,lCARGA,lFALTA AS LOGIC   //   lRIST,lRIRM
LOCAL nRIST,nRIRM,nCRM,nRASTRO AS DWORD
LOCAL oRIRM,oRIST,oRISTI,oRIRMI AS USEREDE
//LOCAL oRUN AS APP
LOCAL cVORETRUN,cPARAM AS STRING
LOCAL aMAIL AS ARRAY
LOCAL aRASTRO AS ARRAY
LOCAL cPRODRASTRO AS STRING
LOCAL nFout AS PTR

aPRO:={.T.,"","","KG",""}
aFORN:={.F.,"","","","","","","","",""}

OJCRMNEW:=JCRMNEW{oOWNER}
oJCRMNEW:LOK:=.F.
OJCRMNEW:Show()
IF ! OJCRMNEW:LOK
	alert("Inclusão Cancelada")
	RETU
ENDIF
//lRIST:=.F.
//lRIRM:=.F.
llote1:=.F.
lRASTRO:=.F.
nRIST:=0
nRIRM:=0
nRASTRO:=0
cRASTRO:=""
cNOME:=""
cCOGNOME:=""

cPEDIDO:=StrTRIM(oJCRMNEW:aUSO[13],8,0)+"/"+StrTRIM(oJCRMNEW:aUSO[14],3,0)

IF (oJCRMNEW:aUSO[3]=0 .OR. oJCRMNEW:aUSO[4]=0) .AND. (oJCRMNEW:aUSO[13]=0 .OR. oJCRMNEW:aUSO[14]=0) //.AND.(oJCRMNEW:aUSO[15]=0)
   IF Empty(oJCRMNEW:aUSO[16])
	   alert("Sem Programaçao/Pedido/Req é Necessário Autorização")
	   RETU NIL	
	ENDIF
ENDIF	

	
IF oJCRMNEW:aUSO[2]=0
     alert("Codigo Cliente/Fornecedor em Branco")
     RETU NIL
ENDIF
IF oJCRMNEW:aUSO[12]=0 .AND. Empty(oJCRMNEW:aUSO[16])
   alert("Sem Número de Nota Fiscal é Necessário Autorização")
   RETU NIL
ENDIF

IF oJCRMNEW:aUSO[1]=="F"
   aFOR:=CHECKSIT(oJCRMNEW:aUSO[2])
   IF aFOR[1]        //Achou Fornecedor
      IF ! aFOR[3]  //Fornecedor Bloqueado
         RETU NIL
      ENDIF
   ENDIF
   aDAD:={zCURINI,"CRMNF.DBF",zCURDIR}
   oCRMNF:=USEREDE{aDAD}
   IF oCRMNF:nERRO=0
	  oCRMNF:GOTOP()
	  IF oCRMNF:SEEK(oJCRMNEW:aUSO[2])
   		IF (oCRMNF:FIELDGET("NRNOTA"))>oJCRMNEW:aUSO[12]
   			alert("Nota "+Str(oCRMNF:FIELDGET("NRNOTA"))+" Já Lançada")
	   		GRAVALOG(Str(oJCRMNEW:aUSO[12])+"/"+Str(oCRMNF:FIELDGET("NRNOTA")),"ERR","CRM")	
	   	ENDIF	
 		IF oJCRMNEW:aUSO[17]<oCRMNF:FIELDGET("DATA")
  			alert("Data Retroativa"+DToC(oCRMNF:FIELDGET("DATA")))
   			GRAVALOG(DToC(oJCRMNEW:aUSO[17])+"/"+DToC(oCRMNF:FIELDGET("DATA")),"ERR","CRM")	
		ENDIF
	 ELSE
   		oCRMNF:APPEND()
	   	oCRMNF:FIELDPUT("Fornecedo",oJCRMNEW:aUSO[2])
	 ENDIF
  	 oCRMNF:FIELDPUT("NRNOTA",oJCRMNEW:aUSO[12])
  	 oCRMNF:FIELDPUT("DATA",oJCRMNEW:aUSO[17])
     oCRMNF:CLOSE()	
  ENDIF
ENDIF
DO CASE
   CASE oJCRMNEW:aUSO[6]=="C"
        aPRO:=PEGMT01(oJCRMNEW:aUSO[7],zcurini,zcurdir)
        IF aPRO[1]=.F.
           IF ! oJCRMNEW:aUSO[10]  .AND. ! oJCRMNEW:aUSO[27]
              alert("Componente Não Cadastrado")
           	  RETU NIL
           ELSE
              alert("Componente Não Cadastrado/Lote Piloto/Ensaios")
              aPRO:={.F.,"","","KG",""}
           ENDIF
        ENDIF
   CASE oJCRMNEW:aUSO[6]=="M"
        aPRO:=PEGMU01(oJCRMNEW:aUSO[7],zcurini,zcurdir)
//        ALERT(oJCRMNEW:aUSO[7])
        IF aPRO[1]=.F.
           IF ! oJCRMNEW:aUSO[10]  .AND. ! oJCRMNEW:aUSO[27]
              alert("Materia Prima Não Cadastrada")
          	  RETU NIL
           ELSE	
              alert("Materia Prima Não Cadastrada/Lote Piloto/Ensaios")
       	      aPRO:={.F.,"","","KG",""}
           ENDIF
        ENDIF
   CASE oJCRMNEW:aUSO[6]=="T"
        aPRO:=PEGMP03(oJCRMNEW:aUSO[8],zCURINI,zCURDIR)
        IF aPRO[1]=.F.
     	   IF ! oJCRMNEW:aUSO[10]  .AND. ! oJCRMNEW:aUSO[27]
              alert("Tratamento Não Cadastrado")
          	  RETU NIL
           ELSE	
              alert("Tratamento Não Cadastrado/Lote Piloto/Ensaios")
       	      aPRO:={.F.,"","","KG",""}
           ENDIF
        ELSE
           IF Empty(aPRO[4])
              alert("Norma não Cadastrado")
              RETU NIL
            ENDIF
            oJCRMNEW:aUSO[7]:=aPRO[4] //NORMA
        ENDIF
   CASE oJCRMNEW:aUSO[6]=="P"
        aPRO:=PEGMS01(oJCRMNEW:aUSO[7])
        IF aPRO[1]=.F.
           alert("Produto não Cadastrado")
           IF ! oJCRMNEW:aUSO[10]  .AND. ! oJCRMNEW:aUSO[27] //Se Nao For Lote Piloto
              RETU NIL
           ELSE
              alert("Produto Não Cadastrado/Lote Piloto/Ensaio")
       	      aPRO:={.F.,"","","KG",""}
           ENDIF
        ENDIF
   CASE oJCRMNEW:aUSO[6]=="X"
   	  aPRO:={.T.,"","","KG",""}
   OTHERWISE
        alert("Tipo Não Preenchido")
        RETU NIL
ENDCASE
IF Empty(Apro[2]) .AND. ! Empty(oJCRMNEW:aUSO[23])
   aPRO[2]:=oJCRMNEW:aUSO[23]	
ENDIF
IF Empty(aPRO[3]) .AND. ! Empty(oJCRMNEW:aUSO[24])
   aPRO[3]:=oJCRMNEW:aUSO[24]	
ENDIF	

IF ValType(Apro[2])#"C"
   Apro[2]:=" "
ENDIF	
IF ValType(Apro[3])#"C"
   Apro[3]:=" "
ENDIF	

DO CASE
   CASE oJCRMNEW:aUSO[1]=="C"
        aCLI:=PEGMA01(oJCRMNEW:aUSO[2],zCURINI,zCURDIR)
        IF aCLI[1]=.T.
	        cNOME:=aCLI[2]
	        cCOGNOME:=aCLI[3]
        ELSE
           alert("Cliente  Não Cadastrado")
           RETU NIL
        ENDIF
   CASE oJCRMNEW:aUSO[1]=="F"
        aFORN:=PEGMB01(oJCRMNEW:aUSO[2],zCURINI,zCURDIR)
        IF aFORN[1]=.T.
           cNOME:=aFORN[2]
           cCOGNOME:=aFORN[3]
        ELSE
           alert("Fornecedor  Não Cadastrado")
           RETU NIL
        ENDIF
        IF Empty(aFORN[9] )
           alert("Fornecedor Sem Conceito")
           alert("Continuando sem conceito não grava ensaios")
           IF  ! MDG("Deseja Continuar lançamento")
               RETU NIL
           ENDIF
        ENDIF
    OTHERWISE
        alert("Tipo Cliente/Fornecedor Não Preenchido")
        RETU NIL
ENDCASE

lCARTA:=.F.
IF oJCRMNEW:aUSO[16]>0
	aDAD:={zCURINI,"AUT.DBF",zCURDIR}
	oAUT:=USEREDE{aDAD}
	IF oAUT:nERRO=0
	   oAUT:GOTOP()
	   IF ! oAUT:SEEK(oJCRMNEW:aUSO[16]) .AND. OJCRMNEW:auso[28]=.F.
		  oAUT:CLOSE()
		  alert("Autorizaçao Não Encontrada")
		  RETU NIL
	   ENDIF	
	   IF oAUT:FIELDGET("USADA") .AND. OJCRMNEW:auso[28]=.F.
		  oAUT:CLOSE()
    	  alert("Autorização Já Utilizada")	
		  RETU NIL
	   ENDIF	
       IF Empty(oAUT:FIELDGET("MOTIVO")) .AND. OJCRMNEW:auso[28]=.F.
		  oAUT:CLOSE()
		  alert("Autorização Sem Motivo")	
		  RETU NIL
	   ENDIF	
       lCARTA:=IF(oAUT:FIELDGET("CARTA")="S",.T.,.F.)	
       oAUT:FIELDPUT("USADA",.T.)
    ELSE
      alert("Erro Abrindo Autorizações")
      RETU NIL
   ENDIF	
ENDIF


cLOTE:=""
IF oJCRMNEW:aUSO[10]
   cLOTE:="P"
ENDIF	
IF oJCRMNEW:aUSO[27]
   cLOTE:="E"
ENDIF
IF oJCRMNEW:aUSO[1]=="F" .AND. Empty(clote)
   cLOTE:=NOVOLOTE(oJCRMNEW:aUSO[2],oJCRMNEW:aUSO[7])	
   IF aFORN[9]="C" .OR. (Val(cLOTE)=1 .AND. aFORN[9]="B")
      DO CASE
         CASE oJCRMNEW:aUSO[6]=="C" .OR. oJCRMNEW:aUSO[6]=="M" 
         	  NOP
              //lRIRM:=.T.
         CASE oJCRMNEW:aUSO[6]=="T"  
         	  NOP
              //lRIST:=.T.
      ENDCASE
   ENDIF
ENDIF


//Pegando Proximo Crm
SELF:server:setorder(1)
SELF:server:gobottom()
nCRM:=SELF:Server:FIELDGET("CRM")
nCRM++
SELF:SERVER:APPEND()
SELF:SERVER:FIELDPUT("CRM",nCRM)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:Commit()

//Pegando Rastro
IF Empty(OJCRMNEW:Auso[18])
   aRASTRO:=NOVORASTRO()
   nRASTRO:=ARASTRO[1]
   cRASTRO:=ARASTRO[2]
   lRASTRO:=.T.	
   OJCRMNEW:AUSO[18]:=cRASTRO
ENDIF	


//Gravando Cabeçario Rirm Gera Sempre
IF oJCRMNEW:aUSO[6]=="C" .OR. oJCRMNEW:aUSO[6]=="M" //Sempre Grava Materia Prima Componente
    //.OR.oJCRMNEW:aUSO[10].OR.oJCRMNEW:aUSO[27] //(oJCRMNEW:aUSO[6]=="C".OR.oJCRMNEW:aUSO[6]=="M")
   aDAD:={zCURINI,"RIRM.DBF",zCURDIR}
   oRIRM:=USEREDE{aDAD}
   IF oRIRM:nERRO=0
	  oRIRM:setorder(1)
      oRIRM:gobottom()
	  nRIRM:=oRIRM:FIELDGET("RIRM")
  	  nRIRM++
  	  oRIRM:APPEND()
	  oRIRM:FIELDPUT("RIRM",nRIRM)
 	  oRIRM:FIELDPUT("DATA",Today())						
 	  oRIRM:FIELDPUT("CRM",nCRM)
	  oRIRM:FIELDPUT("DESCR",aPRO[2])
	  oRIRM:FIELDPUT("APLICACAO",aPRO[3])
	  oRIRM:FIELDPUT("DESENHO",oJCRMNEW:aUSO[7])
	  oRIRM:FIELDPUT("FORNE",cNOME)
	  oRIRM:FIELDPUT("NFORN", oJCRMNEW:aUSO[2])
 	  IF oJCRMNEW:aUSO[1]=="F"
  	     oRIRM:FIELDPUT("CLASSI",aFORN[9])	
  	  ELSE
  	     oRIRM:FIELDPUT("CLASSI","_")			
      ENDIF
	  oRIRM:FIELDPUT("TIPOENT", oJCRMNEW:aUSO[6])
	  oRIRM:FIELDPUT("INSTRU",aPRO[5])		
	  oRIRM:FIELDPUT("CERT",oJCRMNEW:aUSO[9])		
  	  oRIRM:FIELDPUT("CLOTECRT",cLOTE)		
  	  oRIRM:FIELDPUT("NRNOTA",oJCRMNEW:aUSO[12])
  	  oRIRM:FIELDPUT("NRNOTB",oJCRMNEW:aUSO[19])
  	  oRIRM:FIELDPUT("DATANF",oJCRMNEW:aUSO[17])
  	  oRIRM:FIELDPUT("QTDE",oJCRMNEW:aUSO[5]+oJCRMNEW:aUSO[20])
  	  oRIRM:FIELDPUT("RASTRO",AllTrim(oJCRMNEW:aUSO[18]))
	  oRIRM:FIELDPUT("UNID","KG")		
	  oRIRM:FIELDPUT("PEDIDO",cPEDIDO)			
	  oRIRM:CLOSE()
  ENDIF	
ENDIF
//Gravando Cabeçario Rist Gera Sempre
IF oJCRMNEW:aUSO[6]=="T" //Sempre Grava Tratamento
   //.OR.oJCRMNEW:aUSO[10].OR.oJCRMNEW:aUSO[27]
   aDAD:={zCURINI,"RIST.DBF",zCURDIR}
   oRIST:=USEREDE{aDAD}
   IF oRIST:nERRO=0
   	  oRIST:setorder(1)
	  oRIST:gobottom()
  	  nRIST:=oRIST:FIELDGET("RIST")
	  nRIST++
  	  oRIST:APPEND()
      oRIST:FIELDPUT("RIST",nRIST)
      oRIST:FIELDPUT("DATA",Today())			
	  oRIst:FIELDPUT("CRM",nCRM)			
	  oRIST:FIELDPUT("DENO",aPRO[2])
	  oRIST:FIELDPUT("APLICACAO",aPRO[3])
	  oRIST:FIELDPUT("TIPO",aPRO[5])
	  oRIST:FIELDPUT("CODIGO",oJCRMNEW:aUSO[7])
  	  oRIST:FIELDPUT("FORNE",cNOME)
	  oRIST:FIELDPUT("NFORN", oJCRMNEW:aUSO[2])
	  oRIST:FIELDPUT("TIPO", oJCRMNEW:aUSO[6])
	  oRIST:FIELDPUT("CERT",oJCRMNEW:aUSO[9])				
  	  oRIST:FIELDPUT("CLOTECRT",cLOTE)			
	  oRIST:FIELDPUT("NF",oJCRMNEW:aUSO[12])	
	  oRIST:FIELDPUT("NFB",oJCRMNEW:aUSO[19])		
	  oRIST:FIELDPUT("OS",cPEDIDO)				
   	  IF oJCRMNEW:aUSO[1]=="F"
	     oRIST:FIELDPUT("CLASSI",aFORN[9])
	  ELSE
  	     oRIRM:FIELDPUT("CLASSI","_")				
	  ENDIF
  	  oRIST:FIELDPUT("DATANF",oJCRMNEW:aUSO[17])
 	  oRIST:FIELDPUT("RASTRO",AllTrim(oJCRMNEW:aUSO[18]))
      oRIST:FIELDPUT("UNID","PC")		
      oRIST:FIELDPUT("NIVEL","0.65")
	  oRIST:FIELDPUT("QTDE",oJCRMNEW:aUSO[5]+oJCRMNEW:aUSO[20])	
  	  aMS01:=PEGMS01(oRIST:FIELDGET("APLICACAO"))		
 	  IF aMS01[1]
	   	 IF ! Empty(aMS01[4])
	     	oRIST:FIELDPUT("NCLI",aMS01[4])
	      	aCRIST:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
            IF aCRIST[1]=.T.
               SELF:SERVER:CLIENTE:=aCRIST[2]
            ENDIF
         ENDIF	
         IF CLOTE="1"
            llote1:=.T.
         ENDIF
      ENDIF	
      oRIST:CLOSE()
   ENDIF
ENDIF

IF lRASTRO
   cPRODRASTRO:=""	
   IF Empty(aPRO[3])
      cPRODRASTRO:=OJCRMNEW:Auso[8]
    ELSE
      cPRODRASTRO:=APRO[3]
    ENDIF
    GRAVARASTRO(nRASTRO,nCRM,nRIRM,nRIST,cPRODRASTRO,OJCRMNEW:AUSO[11])	
ENDIF	

//Itens Rist se necessário
IF  oJCRMNEW:aUSO[6]=="T"
//lRIST.OR.((oJCRMNEW:aUSO[10].OR.oJCRMNEW:aUSO[27]).and.oJCRMNEW:aUSO[6]=="T")
   aDAD:={zCURINI,"RISTI.DBF",zCURDIR}
   oRISTI:=USEREDE{aDAD}
   IF oRISTI:nERRO=0
	  aDAD:={zCURINI,"MP03I.DBF",zCURDIR}
       oMP03I:=USEREDE{aDAD}
       IF oMP03I:nERRO=0
     	  oMP03I:GOTOP()
	      oMP03I:SEEK(oJCRMNEW:aUSO[7])
	      WHILE AllTrim(oJCRMNEW:aUSO[7])=AllTrim(oMP03I:FIELDGET("CODIGO")) .AND. ! oMP03I:EOF
               oRISTI:APPEND()
	           oRISTI:LOCKCURRENTRECORD()
	           oRISTI:FIELDPUT("RIST",nRIST)
	           oRISTI:FIELDPUT("ITEM",oMP03I:FIELDGET("ITEM"))
	           oRISTI:FIELDPUT("ESPE",oMP03I:FIELDGET("ESPE"))
	           oRISTI:FIELDPUT("ENCO",oMP03I:FIELDGET("ENCO"))
	           oRISTI:FIELDPUT("TIPA",oMP03I:FIELDGET("TIPA"))	
	           oMP03I:SKIP()
	      ENDDO
	      oMP03I:CLOSE()
	   ENDIF
	   oRISTI:CLOSE()
   ENDIF
ENDIF


IF  oJCRMNEW:aUSO[6]=="C" .OR. oJCRMNEW:aUSO[6]=="M"
//lRIRM.OR.((oJCRMNEW:aUSO[10].OR.oJCRMNEW:aUSO[27]).and.(oJCRMNEW:aUSO[6]=="C".OR.oJCRMNEW:aUSO[6]=="T"))
  	//Itens Componentes/MateriaPrima

 	  aDAD:={zCURINI,"RIRMI.DBF",zCURDIR}
      oRIRMI:=USEREDE{aDAD}
      IF oRIRMI:nERRO=0
     	 aDAD:={zCURINI,IF(oJCRMNEW:aUSO[6]=="C","MT01I.DBF","MU01I.DBF"),zCURDIR}
         oMT01I:=USEREDE{aDAD}
	     IF oMT01I:nERRO=0
            oMT01I:GOTOP()
            oMT01I:SEEK(oJCRMNEW:aUSO[7])
            WHILE AllTrim(oJCRMNEW:aUSO[7])=AllTrim(oMT01I:FIELDGET("CODIGO")) .AND. ! oMT01I:EOF
		           oRIRMI:APPEND()
		           oRIRMI:LOCKCURRENTRECORD()
		           oRIRMI:FIELDPUT("RIRM",nRIRM)
		           oRIRMI:FIELDPUT("ITEM",oMT01I:FIELDGET("ITEM"))
		           oRIRMI:FIELDPUT("ESPE",oMT01I:FIELDGET("ESPE"))
		           oRIRMI:FIELDPUT("ENCO",oMT01I:FIELDGET("ENCO"))
		           oRIRMI:FIELDPUT("TIPA",oMT01I:FIELDGET("TIPA"))
		           oRIRMI:FIELDPUT("UNIITEM",oMT01I:FIELDGET("UNIDREF"))	
                   oRIRMI:FIELDPUT("QTITEM",oMT01I:FIELDGET("QTDEREF"))		
		           oMT01I:SKIP()
		      ENDDO
		     oMT01I:CLOSE()
		 ENDIF
	     oRIRMI:CLOSE()
	 ENDIF

ENDIF



//
//APPEND/CRM/DATA ACIMA
//
SELF:SERVER:FIELDPUT("DESCRI",aPRO[2])
SELF:SERVER:FIELDPUT("APLICACAO",aPRO[3])
SELF:SERVER:FIELDPUT("CBUSCA",oJCRMNEW:aUSO[7])
SELF:SERVER:FIELDPUT("NOMEF",cNOME)
SELF:SERVER:FIELDPUT("COGNOME",cCOGNOME)
SELF:SERVER:FIELDPUT("CLIFOR",oJCRMNEW:aUSO[2])
SELF:SERVER:FIELDPUT("TIPOE",oJCRMNEW:aUSO[6])
SELF:SERVER:FIELDPUT("TIPCAD",oJCRMNEW:aUSO[1])
SELF:SERVER:FIELDPUT("QTDE",oJCRMNEW:aUSO[5]+oJCRMNEW:aUSO[20])
SELF:SERVER:FIELDPUT("QTDEA",oJCRMNEW:aUSO[5])
SELF:SERVER:FIELDPUT("QTDEB",oJCRMNEW:aUSO[20])
SELF:SERVER:FIELDPUT("QTDEPED",oJCRMNEW:aUSO[26])
SELF:SERVER:FIELDPUT("PRPED",oJCRMNEW:aUSO[3])
SELF:SERVER:FIELDPUT("PRITE",oJCRMNEW:aUSO[4])
SELF:SERVER:FIELDPUT("RIST",NRIST)
SELF:SERVER:FIELDPUT("RIRM",NRIRM)
SELF:SERVER:FIELDPUT("CERT",oJCRMNEW:aUSO[9])
SELF:SERVER:FIELDPUT("NRNOTA",oJCRMNEW:aUSO[12])
SELF:SERVER:FIELDPUT("NRNOTB",oJCRMNEW:aUSO[19])
SELF:SERVER:FIELDPUT("PEPED",oJCRMNEW:aUSO[13])
SELF:SERVER:FIELDPUT("PEITE",oJCRMNEW:aUSO[14])
SELF:SERVER:FIELDPUT("PEDIDO",cPEDIDO)
SELF:SERVER:FIELDPUT("PEREQ",oJCRMNEW:aUSO[15])
SELF:SERVER:FIELDPUT("OBS",oJCRMNEW:aUSO[11])
SELF:server:FIELDPUT("TECNICO",ZFOLHA)
SELF:SERVER:FIELDPUT("AUT",oJCRMNEW:aUSO[16])
SELF:SERVER:FIELDPUT("RASTRO",AllTrim(oJCRMNEW:aUSO[18]))
SELF:SERVER:FIELDPUT("PRECO",oJCRMNEW:aUSO[21])
SELF:SERVER:FIELDPUT("PRECOPR",oJCRMNEW:aUSO[22])
SELF:SERVER:FIELDPUT("CLOTECRT",cLOTE)		
SELF:SERVER:FIELDPUT("PRCLI",oJCRMNEW:aUSO[25])
IF SELF:TIPOE=="T"
    SELF:SERVER:FIELDPUT("PRODUTO",oJCRMNEW:aUSO[8])
ENDIF
SELF:SERVER:FIELDPUT("USERNM",ZUSER)
SELF:SERVER:FIELDPUT("USERDT",Today())
SELF:SERVER:FIELDPUT("USERHT",Time())
SELF:SERVER:FIELDPUT("NRDATA",oJCRMNEW:aUSO[17])
SELF:sERVER:FIELDPUT("UNID","KG")
SELF:SERVER:FIELDPUT("PESONFA",oJCRMNEW:aUSO[29])
SELF:SERVER:FIELDPUT("PESONFB",oJCRMNEW:aUSO[30])
SELF:SERVER:FIELDPUT("PEDCLI",oJCRMNEW:aUSO[31])
SELF:SERVER:FIELDPUT("ENTREGA",oJCRMNEW:aUSO[32])
SELF:SERVER:FIELDPUT("ENTREG2",oJCRMNEW:aUSO[33])
IF oJCRMNEW:aUSO[34]
   SELF:SERVER:FIELDPUT("TRIANGULAR","S")	
ENDIF	
SELF:SERVER:Commit()
SELF:VIEWFORM()
GRAVALOG(SELF:SERVER:CRM,"INC","CRM")	
IF ! Empty(nRIRM)
   GRAVALOG(SELF:SERVER:RIRM,"INC","CRM_RIRM")	
   alert("RIRM: "+Str(nRIRM))	
ENDIF
IF ! Empty(nRIST)
   GRAVALOG(SELF:SERVER:RIST,"INC","CRM_RIST")	
   alert("RIST: "+Str(nRIST))	
ENDIF
IF ! Empty(oJCRMNEW:aUSO[11])
   GRAVALOG(Str(SELF:SERVER:CRM)+" "+oJCRMNEW:aUSO[11],"INC","CRM")	
ENDIF
IF llote1 .AND. MDG("Imprimir RIST","Imprimir")
  	cVORETRUN:=PEGINIVAL(ZCURINI,"PATH","VORETRUN")+ "VORETRUN"
	cPARAM:=PEGINIVAL(ZCURINI,"RET_CRM07","CAMINHO")+"$NNNNNSSSN$#MANA5CRM#"
	nFout := ShellExecute(SELF:owner:handle(),String2Psz("open"),String2Psz(cVORETRUN),String2Psz(cPARAM),String2Psz(""),1)
    ShellExecuteErro(nFout) 
//     hwnd,   lpOperation,  lpFile,   lpParameters,   lpDirectory,    SW_SHOWNORMAL = 1//fica no diretorio atual ondes estao os dbfs


ENDIF

lPRECO:=.F.
IF SELF:SERVER:FIELDGET("PRECO")<>SELF:SERVER:FIELDGET("PRECOPR")
   lPRECO:=.T.
ENDIF
lCARGA:=.F.
lFALTA:=.F.
IF SELF:SERVER:FIELDGET("QTDE")<(SELF:SERVER:FIELDGET("QTDEPED")*.9) .AND. oJCRMNEW:aUSO[6]#"T"
   lCARGA:=.T.	
   lFALTA:=.T.
ENDIF	
IF SELF:SERVER:FIELDGET("QTDE")>(SELF:SERVER:FIELDGET("QTDEPED")*1.1) .AND. oJCRMNEW:aUSO[6]#"T"
   lCARGA:=.T.	
ENDIF	
aMAIL:={}
IF lCARTA .OR. lPRECO .OR. lCARGA
   AAdd(aMAIL,"Pedido_No:"+cPEDIDO)
   AAdd(aMAIL," CRM_No:"+StrTRIM(nCRM,8,0))
   AAdd(aMAIL," Nota:"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTA"),8,0))
   IF ! Empty(SELF:SERVER:FIELDGET("NRNOTB"))
      AAdd(aMAIL,"/"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTB"),8,0))
   ENDIF
   IF lCARGA .and. oJCRMNEW:aUSO[6]<>"T" .and. oJCRMNEW:aUSO[31]#"S"
      AAdd(aMAIL," Peso:"+StrTRIM(SELF:SERVER:FIELDGET("QTDEPED"),15,6))
      AAdd(aMAIL," Peso:"+StrTRIM(SELF:SERVER:FIELDGET("QTDE"),15,6))
      AAdd(aMAIL," Fornecedor:"+StrTRIM(SELF:SERVER:FIELDGET("CLIFOR"),8,0))
      AAdd(aMAIL," Codigo:"+AllTrim(SELF:SERVER:FIELDGET("CBUSCA")))
      AAdd(aMAIL," PE:"+StrTRIM(SELF:SERVER:FIELDGET("PEPED"),8,0)+"/"+StrTRIM(SELF:SERVER:FIELDGET("PEITE"),8,0))
   	  IF lFALTA
 	  	 EMAILINT("CRM00005",ZUSER,aMAIL,ZCURINI,zCURDIR)	
      ELSE
         EMAILINT("CRM00003",ZUSER,aMAIL,ZCURINI,zCURDIR)	
      ENDIF
   ENDIF
   IF lPRECO
   	  AAdd(aMAIL," Preço:"+StrTRIM(SELF:SERVER:FIELDGET("PRECOPR"),15,6))
   	  AAdd(aMAIL," Preço:"+StrTRIM(SELF:SERVER:FIELDGET("PRECO"),15,6))
	  EMAILINT("CRM00001",ZUSER,aMAIL,ZCURINI,zCURDIR)	
   ENDIF
   IF lCARTA
 	  EMAILINT("CRM00002",ZUSER,aMAIL,ZCURINI,zCURDIR)	
 	  alert("Requer Carta Correção")
   ENDIF
ENDIF	
//Entrada MP/CO Com Programaçao
IF oJCRMNEW:aUSO[6]=="C" .OR. oJCRMNEW:aUSO[6]=="M" .AND. SELF:SERVER:FIELDGET("PEPED")>0
	aMAIL:={}
    AAdd(aMAIL,"Pedido_No:"+cPEDIDO)
    AAdd(aMAIL," CRM_No:"+StrTRIM(nCRM,8,0))
    AAdd(aMAIL," Nota:"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTA"),8,0))
    IF ! Empty(SELF:SERVER:FIELDGET("NRNOTB"))
       AAdd(aMAIL,"/"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTB"),8,0))
    ENDIF
    AAdd(aMAIL," Peso:"+StrTRIM(SELF:SERVER:FIELDGET("QTDEPED"),15,6))
    AAdd(aMAIL," Peso:"+StrTRIM(SELF:SERVER:FIELDGET("QTDE"),15,6))
    AAdd(aMAIL," Fornecedor:"+StrTRIM(SELF:SERVER:FIELDGET("CLIFOR"),8,0))
    AAdd(aMAIL," Codigo:"+AllTrim(SELF:SERVER:FIELDGET("CBUSCA")))
    AAdd(aMAIL," PE:"+StrTRIM(SELF:SERVER:FIELDGET("PEPED"),8,0)+"/"+StrTRIM(SELF:SERVER:FIELDGET("PEITE"),8,0))
    EMAILINT("CRM00007",ZUSER,aMAIL,ZCURINI,zCURDIR)	
ENDIF

IF ! Empty(SELF:SERVER:FIELDGET("PEREQ"))
   aDAD:={zCURINI,"MY04.DBF",zCURDIR}
   oMY04:=USEREDE{aDAD}
   IF oMY04:nERRO=0
      oMY04:GOTOP()
      oMY04:SEEK(SELF:SERVER:FIELDGET("PEREQ"))
      IF oMY04:FOUND
      	 IF Empty(oMY04:FIELDGET("TECNICO"))
      	 	oMY04:FIELDPUT("TECNICO",ZFOLHA)
      	 ENDIF
      	 IF Empty(oMY04:FIELDGET("RASTRO"))
      	 	oMY04:FIELDPUT("RASTRO",AllTrim(oJCRMNEW:aUSO[18]))
      	 ENDIF
      	 IF Empty(oMY04:FIELDGET("CRM"))
      	 	oMY04:FIELDPUT("CRM",nCRM)
      	 ENDIF
      ENDIF	
      oMY04:CLOSE()
   ENDIF
ENDIF


IF oJCRMNEW:aUSO[16]>0
   oAUT:FIELDPUT("CRM",nCRM)	
   oAUT:FIELDPUT("DATABX",Today())
   oAUT:Close()	
ENDIF	

IF CLOTE="1" .OR. cLOTE="P" .OR. cLOTE="E"
   alert("Realizar Ensaios")	
ENDIF	

IF oJCRMNEW:aUSO[6]=="M"
   aDAD:={zCURINI,"CRMEST.DBF",zCURDIR}
   oCRMEST:=USEREDE{aDAD}
   IF oCRMEST:nERRO=0
   	  oCRMEST:Append()
   	  oCRMEST:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("CBUSCA"))
   	  oCRMEST:FIELDPUT("UNIDADE",SELF:SERVER:FIELDGET("UNID"))
   	  oCRMEST:FIELDPUT("NOME",SELF:SERVER:FIELDGET("DESCRI"))
   	  oCRMEST:FIELDPUT("NRNOTAINI",SELF:SERVER:FIELDGET("NRNOTA"))
   	  oCRMEST:FIELDPUT("DATAFAT",SELF:SERVER:FIELDGET("DATA"))
   	  oCRMEST:FIELDPUT("OSINI",Val(StrTran(SELF:SERVER:FIELDGET("PEDIDO"),"/",".")))
   	  oCRMEST:FIELDPUT("TOTKGINI",SELF:SERVER:FIELDGET("QTDEA"))
      oCRMEST:FIELDPUT("TOTKGANT",SELF:SERVER:FIELDGET("QTDEA"))
      oCRMEST:FIELDPUT("TOTKGEST",SELF:SERVER:FIELDGET("QTDEA"))
   	  oCRMEST:FIELDPUT("TIPOCLI",SELF:SERVER:FIELDGET("TIPCAD"))
   	  oCRMEST:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIFOR"))
   	  oCRMEST:FIELDPUT("COGNOME",SELF:SERVER:FIELDGET("COGNOME"))
   	  oCRMEST:FIELDPUT("CRM",SELF:SERVER:FIELDGET("CRM"))
   	  oCRMEST:FIELDPUT("PESOREF",SELF:SERVER:FIELDGET("PESONFA"))
   	  oCRMEST:FIELDPUT("PRECO",SELF:SERVER:FIELDGET("PRECONF"))
   	  oCRMEST:FIELDPUT("TIPOENT",SELF:SERVER:FIELDGET("TIPOE"))
   	  oCRMEST:FIELDPUT("RASTRO",SELF:SERVER:FIELDGET("RASTRO"))
   	  IF Empty(SELF:SERVER:FIELDGET("PRODUTO"))
     	 oCRMEST:FIELDPUT("OBS",SELF:SERVER:FIELDGET("APLICACAO"))
      ELSE
     	 oCRMEST:FIELDPUT("OBS",SELF:SERVER:FIELDGET("PRODUTO"))
      ENDIF
      IF ! Empty(SELF:SERVER:FIELDGET("NRNOTB"))
      	 oCRMEST:Append()
   	  	 oCRMEST:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("CBUSCA"))
   	  	 oCRMEST:FIELDPUT("UNIDADE",SELF:SERVER:FIELDGET("UNID"))
   	  	 oCRMEST:FIELDPUT("NOME",SELF:SERVER:FIELDGET("DESCRI"))
   	  	 oCRMEST:FIELDPUT("NRNOTAINI",SELF:SERVER:FIELDGET("NRNOTB"))
   	  	 oCRMEST:FIELDPUT("DATAFAT",SELF:SERVER:FIELDGET("DATA"))
   	  	 oCRMEST:FIELDPUT("OSINI",Val(StrTran(SELF:SERVER:FIELDGET("PEDIDO"),"/",".")))
   	  	 oCRMEST:FIELDPUT("TOTKGINI",SELF:SERVER:FIELDGET("QTDEB"))
         oCRMEST:FIELDPUT("TOTKGANT",SELF:SERVER:FIELDGET("QTDEB"))
         oCRMEST:FIELDPUT("TOTKGEST",SELF:SERVER:FIELDGET("QTDEB"))
   	  	 oCRMEST:FIELDPUT("TIPOCLI",SELF:SERVER:FIELDGET("TIPCAD"))
   	  	 oCRMEST:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIFOR"))
   	  	 oCRMEST:FIELDPUT("COGNOME",SELF:SERVER:FIELDGET("COGNOME"))
   	  	 oCRMEST:FIELDPUT("CRM",SELF:SERVER:FIELDGET("CRM"))
   	  	 oCRMEST:FIELDPUT("PESOREF",SELF:SERVER:FIELDGET("PESONFB"))
   	  	 oCRMEST:FIELDPUT("PRECO",SELF:SERVER:FIELDGET("PRECONF"))
   	  	 oCRMEST:FIELDPUT("TIPOENT",SELF:SERVER:FIELDGET("TIPOE"))
   	  	 oCRMEST:FIELDPUT("RASTRO",SELF:SERVER:FIELDGET("RASTRO"))
   	     IF Empty(SELF:SERVER:FIELDGET("PRODUTO"))
     	    oCRMEST:FIELDPUT("OBS",SELF:SERVER:FIELDGET("APLICACAO"))
         ELSE
       	    oCRMEST:FIELDPUT("OBS",SELF:SERVER:FIELDGET("PRODUTO"))
         ENDIF
      ENDIF
      oCRMEST:CLOSE()
   ENDIF	
ENDIF

METHOD buscaCRM(oOWNER) 
	SELF:KeyFind()
//LOCAL oBUSCA AS XBUSCA
//oBUSCA:=XBUSCA{oOWNER,"Localizar","Digite NºCRM"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF

METHOD cmdAno( ) 
LOCAL cRASTRO AS STRING
LOCAL aRETU AS ARRAY
cRASTRO:=SELF:SERVER:FIELDGET("RASTRO")
aRETU:=CHECKRASTRO(cRASTRO)	
IF aRETU[1]
   SELF:SERVER:FIELDPUT("RASTRO",aRETU[2])
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CRM","CRM")	

METHOD cmdtriangular( ) 
LOCAL oJAN AS crmJanTri	
IF SELF:SERVER:FIELDGET("TRIANGULAR")="V"	
   alert("Operacao Triangular Ja Verificada")
   RETU
ENDIF	
IF SELF:SERVER:FIELDGET("TRIANGULAR")<>"S"	
   alert("Esta nao E uma Operacao Triangular")
   RETU	
ENDIF	
oJAN:=CRMJANTRI{SELF}
oJAN:SHOW()

METHOD DELETE() 
LOCAL nRIRM,nRIST,nAUT,nNRNOTA,nNRNOTB,nCRM AS DWORD
LOCAL oAUT,oCRMEST AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL cTIPO,cCODIGO AS STRING
IF ! MDG("Apagar Registro") .AND. SELF:server:LockCurrentRecord()
	RETURN
ENDIF	
nRIRM:=SELF:SERVER:RIRM
nRIST:=SELF:SERVER:RIST
nAUT:=SELF:SERVER:FIELDGET("AUT")
cTIPO:=SELF:SERVER:FIELDGET("TIPOE")
nCRM:=SELF:SERVER:FIELDGET("CRM")
nNRNOTA:=SELF:SERVER:FIELDGET("NRNOTA")
nNRNOTB:=SELF:SERVER:FIELDGET("NRNOTB")
cCODIGO:=SELF:SERVER:FIELDGET("CBUSCA")
GRAVALOG(SELF:SERVER:CRM,"DEL","CRM")	
SELF:server:delete()
SELF:server:unlock()
SELF:server:skip(-1)
IF ! Empty(nRIRM)
   DELEENS("RIRM.DBF","RIRMI.DBF",nRIRM,"RIRM")
   GRAVALOG(nRIRM,"DEL","CRM_RIRM")	
ENDIF
IF ! Empty(nRIST)
   DELEENS("RIST.DBF","RISTI.DBF",nRIST,"RIST")
   GRAVALOG(nRIST,"DEL","CRM_RIST")		
ENDIF

IF nAUT>0
   aDAD:={zCURINI,"AUT.DBF",zCURDIR}
   OAUT:=USEREDE{aDAD}
   IF oAUT:nERRO=0
      oAUT:GOTOP()
      IF oAUT:SEEK(nAUT)
      	 oAUT:Delete()
      ENDIF	
      oAUT:CLOSE()
   ENDIF
ENDIF



IF cTIPO="M"
   aDAD:={zCURINI,"CRMEST.DBF",zCURDIR}
   oCRMEST:=USEREDE{aDAD}
   IF oCRMEST:nERRO=0
   	  oCRMEST:SetOrder(2)
   	  oCRMEST:GOTOP()
   	  OCRMEST:SEEK(Str(nNRNOTA,8)+cCODIGO)
   	  WHILE oCRMEST:FIELDGET("CRM")=nCRM .AND. ! oCRMEST:EoF
   	  	  oCRMEST:Delete()
   	  	  oCRMEST:Skip()
  	  ENDDO
  	  OCRMEST:SEEK(Str(nNRNOTB,8)+cCODIGO)
   	  WHILE oCRMEST:FIELDGET("CRM")=nCRM .AND. ! oCRMEST:EoF
   	  	  oCRMEST:Delete()
	  	  oCRMEST:Skip()	
  	  ENDDO
      oCRMEST:CLOSE()
   ENDIF	
ENDIF

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("PRODUTO",oESC:CODIGO)
ENDIF

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:server:FIELDGET("PRODUTO"))," ",""))
IF Empty(cCODIGO)	
  cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:server:FIELDGET("APLICACAO"))," ",""))	
ENDIF
IF Empty(cCODIGO)	
   alert("Codigo Produto/Aplicacao Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()


CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


METHOD TROCANF 
LOCAL aMAIL AS ARRAY
LOCAL oJAN AS jcrmtr

oJAN:=JCRMTR{SELF}
oJAN:SHOW()
aMAIL:={}
AAdd(aMAIL," CRM_No:"+StrTRIM(SELF:SERVER:FIELDGET("CRM"),8,0))
AAdd(aMAIL," Nota:"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTA"),8,0))
IF ! Empty(SELF:SERVER:FIELDGET("NRNOTB"))
   AAdd(aMAIL,"/"+StrTRIM(SELF:SERVER:FIELDGET("NRNOTB"),8,0))
ENDIF
AAdd(aMAIL," Fornecedor:"+StrTRIM(SELF:SERVER:FIELDGET("CLIFOR"),8,0))
AAdd(aMAIL," Codigo:"+AllTrim(SELF:SERVER:FIELDGET("CBUSCA")))
AAdd(aMAIL," PE:"+StrTRIM(SELF:SERVER:FIELDGET("PEPED"),8,0)+"/"+StrTRIM(SELF:SERVER:FIELDGET("PEITE"),8,0))
EMAILINT("CRM00006",ZUSER,aMAIL,ZCURINI,zCURDIR)	


END CLASS
