CLASS XJCRMA INHERIT JCRMA

METHOD APPEND() 
LOCAL nNUMERO AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:NUMERO
nNUMERO++
SUPER:append()
SELF:SERVER:FIELDPUT("NUMERO",nNUMERO)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:RASTRONUM:=nNUMERO
SELF:RASTROANO:=Year(Today())
SELF:cmdgera()
RETURN SELF

METHOD buscar( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD cmdgera( ) 
	IF (SELF:RASTRONUM)<1
	   alert("Nº Rastro nao Pode Ser em Branco")
	   RETU
	ENDIF
	SELF:SERVER:FIELDPUT("RASTROA","A"+StrZero(SELF:RASTRONUM,4)+"/"+StrZero(SELF:RASTROANO,4))

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CRM","RAST")	

METHOD cmdmais2( ) 
SELF:oDCRASTROANO:TextValue:=Str(INCDEC(SELF:oDCRASTROANO:TextValue,1,1900,2100),4)						

METHOD cmdmenos2( ) 
SELF:oDCRASTROANO:TextValue:=Str(INCDEC(SELF:oDCRASTROANO:TextValue,-1,1900,2100),4)						


METHOD CMDMOT 
	SELF:SERVER:FIELDPUT("MOTIVO",SELF:oSFJCRMMOT:SERVER:FIELDGET("CODIGO"))

METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD ESCCLI 
LOCAL oESC AS XESCNUM	
LOCAL aFORN AS ARRAY
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:LOK
    SELF:SERVER:FIELDPUT("CLIENTE",oESC:NUMERO)
    aFORN:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
    IF aFORN[1]=.T.
       SELF:SERVER:FIELDPUT("COGCLI",aFORN[3])
    ENDIF
ENDIF

METHOD ESCCOD( ) 
LOCAL oESC AS XESCCOD	
LOCAL cARQ,cTIPO AS STRING
cTIPO:=SELF:SERVER:FIELDGET("TIPOENT")
IF Empty(cTIPO)
   alert("Especifique o Tipo")
   RETU
ENDIF	
IF cTIPO="X"
   alert("Tipo X Nao Permite Escolha")
   RETU
ENDIF	
cARQ:="MS01"
DO CASE
   CASE cTIPO="M"
   	    cARQ:="MU01"
   CASE cTIPO="C"
   	    cARQ:="MT01"
   CASE cTIPO="T"
   	    cARQ:="MP03"
ENDCASE	
oESC:=XESCCOD{SELF,cARQ+".DBF"}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
ENDIF

METHOD ESCFOR 
LOCAL oESC AS XESCNUM	
LOCAL aFORN AS ARRAY
oESC:=XESCNUM{SELF,"MB01.DBF"}
oESC:SHOW()	
IF Oesc:LOK
    SELF:SERVER:FIELDPUT("FORNECEDO",oESC:NUMERO)
    aFORN:=PEGMB01(SELF:SERVER:FORNECEDO,ZCURINI,ZCURDIR)
    IF aFORN[1]=.T.
       SELF:SERVER:FIELDPUT("COGFOR",aFORN[3])
    ENDIF
ENDIF

METHOD ESCPRO( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("PRODUTO",oESC:CODIGO)
ENDIF

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",19)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRMA.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"CRMMOT.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJCRMMOT:USE(oSERVE2)
SELF:oSFJCRMMOT:VIEWTABLE()
SELF:OSFJCRMMOT:Browser:SetStandardStyle(gBsreadonly)
SELF:RASTROANO:=Year(Today())
SELF:SHOW()	








METHOD PEGCLI( ) 
LOCAL aFORN AS ARRAY	
aFORN:=PEGMA01(SELF:SERVER:CLIENTE,ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:COGCLI:=aFORN[3]
ENDIF	

METHOD PEGCRM 
LOCAL nERRO AS WORD	
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF Empty(SELF:SERVER:FIELDGET("NF"))
   alert("Preencha o Numero da NF")
   RETU
ENDIF	
IF Empty(SELF:SERVER:FIELDGET("CODIGO"))
   alert("Preencha o Codigo")
   RETU
ENDIF	
IF Empty(SELF:SERVER:FIELDGET("PRODUTO"))
   alert("Preencha o Produto")
   RETU
ENDIF	
IF Empty(SELF:SERVER:FIELDGET("FORNECEDO"))
   alert("Preencha o Numero do Fornecedor")
   RETU
ENDIF	
IF Empty(SELF:SERVER:FIELDGET("TIPOENT"))
   alert("Preencha o Tipo de Entrada")
   RETU
ENDIF	
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
nERRO:=1 //Erro Abertura
IF oSERVER:nERRO=0
   nERRO:=0 //Abertura Ok
   oSERVER:GOTOP()
   IF oSERVER:SEEK(SELF:SERVER:FIELDGET("CRM"))
   	  IF  SELF:SERVER:FIELDGET("NF")=oSERVER:FIELDGET("NRNOTA") .OR. SELF:SERVER:FIELDGET("NF")=oSERVER:FIELDGET("NRNOTB")
   	  	  IF IF(SELF:SERVER:FIELDGET("TIPOENT")="T", ;
                AllTrim(SELF:SERVER:FIELDGET("PRODUTO"))=AllTrim(oSERVER:FIELDGET("PRODUTO")),;
                AllTrim(SELF:SERVER:FIELDGET("CODIGO"))=AllTrim(oSERVER:FIELDGET("CBUSCA")))

//            AllTrim(SELF:SERVER:FIELDGET("CODIGO"))=AllTrim(oSERVER:FIELDGET("CBUSCA")).OR. ;
//             AllTrim(SELF:SERVER:FIELDGET("PRODUTO"))=AllTrim(oSERVER:FIELDGET("CBUSCA")).OR. ;
//             AllTrim(SELF:SERVER:FIELDGET("CODIGO"))=AllTrim(oSERVER:FIELDGET("PRODUTO")).OR. ;
//             AllTrim(SELF:SERVER:FIELDGET("PRODUTO"))=AllTrim(oSERVER:FIELDGET("PRODUTO"))
             IF SELF:SERVER:FIELDGET("FORNECEDO")=oSERVER:FIELDGET("CLIFOR")
                IF SELF:SERVER:FIELDGET("TIPOENT")=oSERVER:FIELDGET("TIPOE")
                  SELF:SERVER:FIELDPUT("RASTROOK",oSERVER:FIELDGET("RASTRO"))
                  SELF:SERVER:FIELDPUT("DATAOK",oSERVER:FIELDGET("DATA"))
                ELSE
                  nERRO:=6
                ENDIF
             ELSE
             	nERRO:=5
             ENDIF
   	  	  ELSE
   	  	  	 nERRO:=4
          ENDIF	
   	  ELSE
   	  	 nERRO:=3
      ENDIF	
   ELSE
   	  nERRO:=2 //Crm Nao Localizado
   ENDIF
   oSERVER:CLOSE()
ENDIF
DO CASE
   CASE nERRO=1
   	    alert("Erro Abrindo CRM.DBF")
   CASE nERRO=2
        alert("CRM Nao Encontrado")
   CASE nERRO=3
        alert("NF Nao e o Mesmo do CRM")
   CASE nERRO=4
        alert("Produto ou Codigo Nao e o Mesmo do crm" )
    CASE nERRO=5
        alert("CRM de outro FORnecedor")
    CASE nERRO=6
        alert("Tipo de Entrada Diferente")
ENDCASE	
IF nERRO>0
   SELF:SERVER:FIELDPUT("RASTROOK","")
   SELF:SERVER:FIELDPUT("DATAOK",CToD(Space(8)))
ENDIF	



METHOD pegfor( ) 
LOCAL aFORN AS ARRAY	
aFORN:=PEGMB01(SELF:SERVER:FORNECEDO,ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:COGFOR:=aFORN[3]
ENDIF
	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


METHOD TIPOC 
	SELF:SERVER:FIELDPUT("TIPOENT","C")	
    SELF:SERVER:FIELDPUT("CODIGO","")

METHOD TIPOM 
	SELF:SERVER:FIELDPUT("TIPOENT","M")
    SELF:SERVER:FIELDPUT("CODIGO","")	

METHOD TIPOO 
	SELF:SERVER:FIELDPUT("TIPOENT","X")
    SELF:SERVER:FIELDPUT("CODIGO","")	
	
	

METHOD TIPOP 	
	SELF:SERVER:FIELDPUT("TIPOENT","P")	
    SELF:SERVER:FIELDPUT("CODIGO","")	

METHOD TIPOT 	
	SELF:SERVER:FIELDPUT("TIPOENT","T")
	    SELF:SERVER:FIELDPUT("CODIGO","")



END CLASS
