CLASS XJCRMAR INHERIT JCRMAR

METHOD buscacurso( ) 
	SELF:keyfind()

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",28)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"CRMAR.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

METHOD porcurso( ) 
	SELF:keyfind()

METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
	 FabCenterWindow( SELF )
	RETURN NIL


METHOD PushButton2( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY	
IF ! Empty(SELF:SERVER:FIELDGET("TIPOENT"))
   alert("Tipo Ja Preenchido")
   RETU	
ENDIF	
aDAD:={zCURINI,"MP03.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:SETORDER(3)
oSERVER:GOTOP()
IF oSERVER:SEEK(AllTrim(SELF:SERVER:FIELDGET("CODIGOINT")))
   SELF:SERVER:FIELDGET("CODIGO",oSERVER:FIELDGET("NORMA"))
ENDIF
oSERVER:CLOSE()	



END CLASS
