CLASS XJCRMSS INHERIT JCRMSS

METHOD APPEND() 
LOCAL nNUMERO AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:FIELDGET("NUMERO")
nNUMERO++
SUPER:append()
SELF:SERVER:FIELDPUT("NUMERO",nNUMERO)
SELF:SERVER:FIELDPUT("DATA",Today())
RETURN

METHOD BUSCAnum 	
SELF:KeyFind()


METHOD cmdagora( ) 
	SELF:SERVER:FIELDPUT("HORAENV",Time())
	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD cmdHoje( ) 
	SELF:SERVER:FIELDPUT("DATA",Today())

METHOD cmdHoje1( ) 
		SELF:SERVER:FIELDPUT("DATAENV",Today())

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CRM","SS")	


METHOD cmdtrapro( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"MP03.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:GOTOP()
IF oSERVER:SEEK(AllTrim(SELF:SERVER:FIELDGET("APLICACAO")))
   SELF:SERVER:FIELDPUT("CODIGO",oSERVER:FIELDGET("CODIGO"))
ENDIF
oSERVER:CLOSE()	
SELF:PEGETI()
	

METHOD cmdtrapro1( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"MP03.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:SETORDER(3)
oSERVER:GOTOP()
IF oSERVER:SEEK(AllTrim(SELF:SERVER:FIELDGET("CODIGOINT")))
   SELF:SERVER:FIELDPUT("CODIGO",oSERVER:FIELDGET("CODIGO"))
ENDIF
oSERVER:CLOSE()	
SELF:PEGETI()
	

METHOD DELETE() 
IF MDG("Excluir")	
  SUPER:DELETE()
ENDIF
RETURN

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("APLICACAO",oESC:CODIGO)
ENDIF						

METHOD esccod1( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"ETI.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("NORMA",oESC:CODIGO)
ENDIF							

METHOD ESCETI( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MP03.DBF"}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
ENDIF							
SELF:pegETI()

METHOD ESCFOR( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MB01.DBF"}
oESC:SHOW()	
IF Oesc:LOK
    SELF:SERVER:FIELDPUT("FORNECEDO",oESC:NUMERO)
    SELF:SERVER:FIELDPUT("FORNOME",oESC:NOME)
ENDIF	

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:server:FIELDGET("APLICACAO"))," ",""))	
IF Empty(cCODIGO)	
   alert("Codigo Produto/Aplicacao Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG",cCODIGO}
OFOTOVIEW:SHOW()	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",27)
   RETU SELF
ENDIF	
aDAD:={zCURINI,"CRMSS.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(GBSREADONLY)
SELF:SHOW()	

METHOD pegar( ) 
LOCAL oConn AS SQLConnection
LOCAL oREG AS SQLSelect
LOCAL aDAD AS ARRAY
LOCAL oMB01 AS USEMANA5
LOCAL CSQL,cCGC AS STRING     //CMIG
LOCAL oSTMT AS SQLStatement



//   cMIG:=PEGEMPMIG(zempRESA)

    aDAD:={zCURINI,"MB01",zCURDIR,aDIR}
    oMB01:=USEMANA5{aDAD}
    IF oMB01:nERRO#0
       RETU SELF
    ENDIF
    oMB01:SETORDER(3) //CGC



   oConn := SQLConnection{}
   IF ! oConn:connect("ol_logix","","")
  	  alert("Erro na Conecção")
   	  RETU
   ENDIF	

cSQL:= "set isolation to dirty read"
oStmt := SQLStatement{cSQL,oConn}
oSTMT:Execute()

  AltD()

  CSQL:=" SELECT aviso_rec.*, "
  CSQL+=" nf_sup.num_nf, nf_sup.cod_fornecedor "
  CSQL+=" FROM "
  CSQL+=" aviso_rec INNER JOIN nf_sup ON aviso_rec.num_aviso_rec = nf_sup.num_aviso_rec"
  csql+=" where aviso_rec.num_aviso_rec="
  CSQL+=AllTrim(Str(SELF:server:FIELDGET("AR")))
  Csql+=" AND  aviso_rec.num_seq="
  cSQL+=AllTrim(Str(SELF:SERVER:FIELDGET("ITEM")))


   oreg:= SQLSelect{cSQL,oconn}
   IF ! OREG:EoF	

     SELF:SERVER:FIELDPUT("DATA",OREG:FIELDGET("dat_inclusao_seq"))
     SELF:SERVER:FIELDPUT("CODIGOINT",OREG:FIELDGET("cod_item"))
     cCGC:=oREG:FIELDGET("Cod_fornecedor")

      IF SubStr(cCGC,10,4)="0000"
         cCGC:= SubStr(cCGC,1,3)+"."+SubStr(cCGC,4,3)+"."+SubStr(cCGC,7,3)+"-"+SubStr(cCGC,14,2)
      ELSE
    	 cCGC:=SubStr(CCGC,2)
         cCGC:=Left(cCGC,2)+"."+SubStr(cCGC,3,3)+"."+SubStr(cCGC,6,3)+"/"+SubStr(cCGC,9,4)+"-"+SubStr(cCGC,13,2)
      ENDIF


     oMB01:GOTOP()
     IF oMB01:SEEK(cCGC)
        SELF:SERVER:FIELDPUT("FORNECEDO",oMB01:FIELDGET("NUMERO"))
     ENDIF


   ENDIF
   Oreg:close()
   Oconn:Disconnect()
   oMB01:CLOSE()

   SELF:cmdtrapro1()
   SELF:PEGETI()
   SELF:PEGFOR()



SELF:SERVER:FIELDPUT("RASTRO",CRIARASTRO("AR",SELF:SERVER:FIELDGET("AR"),Year(Today()),SELF:SERVER:FIELDGET("ITEM")))

METHOD pegeti( ) 
LOCAL Aretu,aDAD AS ARRAY
LOCAL oCRM AS USEREDE
LOCAL cCODIGO,cNORMA AS STRING
LOCAL nLEN AS DWORD
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))

aretu:={.F.}	
aRETU:=PEGMP03(cCODIGO,zcurini,zcurdir)
IF aRETU[1]
   SELF:server:FIELDPUT("NORMA",ARETU[4])
   SELF:server:FIELDPUT("CODIGOINT",ARETU[10])
   SELF:server:FIELDPUT("APLICACAO",ARETU[3])
   aDAD:={zCURINI,"MP03I.DBF",zCURDIR}
   oCRM:=USEREDE{aDAD}
   IF oCRM:nERRO#0
      RETU
   ENDIF
   cNORMA:=AllTrim(SELF:SERVER:FIELDGET("NORMA"))
   nLEN:=Len(cNORMA)
   oCRM:GOTOP()
   oCRM:SEEK(cNORMA)
   WHILE cNORMA=SubStr(oCRM:FIELDGET("CODIGO"),1,nLEN)  .AND. ! OCRM:EOF
      IF ocrM:FIELDGET("TIPA")="SS"
         SELF:SERVER:FIELDPUT("ESPE",oCRM:FIELDGET("ESPE"))	
      ENDIF
      oCRM:Skip()
   ENDDO
   oCRM:CLOSE()	
ENDIF
	
	

METHOD pegfor( ) 
LOCAL aFORN AS ARRAY	
aFORN:=PEGMB01(SELF:SERVER:FORNECEDO,ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:FIELDPUT("FORNOME",aFORN[2])
ENDIF


METHOD PEGRIst( ) 
LOCAL oCRM AS USEREDE
//LOCAL cTIPO AS STRING
LOCAL aDAD AS ARRAY
LOCAL nCRM,nRIST AS DWORD
nRIST:=SELF:SERVER:FIELDGET("RIST")
aDAD:={zCURINI,"RIST.DBF",zCURDIR}
oCRM:=USEREDE{aDAD}
IF oCRM:nERRO#0
    RETU
ENDIF
//cTIPO:=" "
nCRM:=0
oCRM:GOTOP()
IF oCRM:SEEK(nRIST)
   SELF:SERVER:FIELDPUT("RASTRO",oCRM:FIELDGET("RASTRO"))	
   SELF:SERVER:FIELDPUT("FORNECEDO",oCRM:FIELDGET("NFORN"))	
   SELF:SERVER:FIELDPUT("FORNOME",oCRM:FIELDGET("FORNE"))	
   SELF:SERVER:FIELDPUT("NORMA",oCRM:FIELDGET("CODIGO"))	
   SELF:SERVER:FIELDPUT("APLICACAO",oCRM:FIELDGET("APLICACAO"))	
   nCRM:=oCRM:FIELDGET("CRM")
ENDIF	
oCRM:CLOSE()
IF nCRM>0
   aDAD:={zCURINI,"CRM.DBF",zCURDIR}
   oCRM:=USEREDE{aDAD}
   IF oCRM:nERRO#0
      RETU
   ENDIF
   oCRM:GOTOP()
   IF oCRM:SEEK(nCRM)
      SELF:SERVER:FIELDPUT("CODIGO",oCRM:FIELDGET("PRODUTO"))	
   ENDIF	
   oCRM:CLOSE()	
ENDIF	
   aDAD:={zCURINI,"RISTI.DBF",zCURDIR}
   oCRM:=USEREDE{aDAD}
   IF oCRM:nERRO#0
      RETU
   ENDIF
   oCRM:GOTOP()
   oCRM:SEEK(nRIST)
   WHILE oCRM:FIELDGET("RIST")=nRIST  .AND. ! OCRM:EOF
   	   IF ocrM:FIELDGET("TIPA")="SS"
          SELF:SERVER:FIELDPUT("ESPE",oCRM:FIELDGET("ESPE"))	
       ENDIF
       oCRM:Skip()
   ENDDO
   oCRM:CLOSE()	


METHOD PORNUM 
SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
