FUNCTION TEMCHKCERT(cTIPO,cCODIGO)
LOCAL lRETU AS LOGIC
LOCAL oORI AS USEREDE
LOCAL cARQ AS STRING
LOCAL aDAD AS ARRAY
cARQ:=""
lRETU:=.F.
DO CASE
   CASE cTIPO="M"
       cARQ:="MU01R.DBF"
   CASE cTIPO="C"
       cARQ:="MT01R.DBF"
   CASE cTIPO="T"
       cARQ:="MP03R.DBF"
ENDCASE
aDAD:={zCURINI,cARQ,zCURDIR}
oORI:=USEREDE{aDAD}
IF oORI:nERRO#0
    RETU {.F.,""}
ENDIF
oORI:GOTOP()
oORI:SEEK(cCODIGO)
WHILE cCODIGO=oORI:FIELDGET("CODIGO")  .AND. ! oORI:EOF
   lRETU:=.T.
   oORI:FIELDPUT("CHECADO","")	
   oORI:SKIP()
ENDDO
oORI:CLOSE()
RETU {lRETU,cARQ}



