PARTIAL CLASS XINDEXAR
CONSTRUCTOR(oOWNER) 
IF ! entramenu("CRM",6)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	

END CLASS
CLASS XJENSCO INHERIT ZJENS
		EXPORT cARQI AS STRING


CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MT01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MT01I.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

aDAD:={zCURINI,"CRMENS.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
   oSERVER:Close() //Fecha Master	
   oSERVE2:Close() //Fecha Master	
    RETU SELF
ENDIF
aDAD:={zCURINI,"Mt01r.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
	oSERVER:Close() //Fecha Master
    oSERVE2:Close() //Fecha Master	
    oSERVE3:Close() //Fecha Master	
   RETU SELF
ENDIF


SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJENSI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJENSI,"CODIGO")
SELF:oSFJENSI:VIEWTABLE()

SELF:oSFJCRMENS:use(oSERVE3)
SELF:oSFJCRMENS:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJCRMENS:VIEWTABLE()

SELF:OSFJENSR:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJENSR,"CODIGO")
SELF:oSFJENSR:VIEWTABLE()

SELF:oDCCODIGOINT:DISABLE()

SELF:SHOW()

END CLASS
CLASS XJENSETI INHERIT ZJENS	
		EXPORT cARQI AS STRING
	

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MP","ENS")	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"ETI.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MP03I.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"CRMENS.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
   oSERVER:Close() //Fecha Master	
   oSERVE2:Close() //Fecha Master	
    RETU SELF
ENDIF
aDAD:={zCURINI,"Mp03r.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
	oSERVER:Close() //Fecha Master
    oSERVE2:Close() //Fecha Master	
    oSERVE3:Close() //Fecha Master	
   RETU SELF
ENDIF


SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJENSI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJENSI,"CODIGO")
SELF:oSFJENSI:VIEWTABLE()

SELF:oSFJCRMENS:use(oSERVE3)
SELF:oSFJCRMENS:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJCRMENS:VIEWTABLE()

SELF:OSFJENSR:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJENSR,"CODIGO")
SELF:oSFJENSR:VIEWTABLE()

SELF:oDCCODIGOINT:DISABLE()
SELF:SHOW()	

END CLASS
CLASS XJENSMP INHERIT ZJENS
		EXPORT cARQI AS STRING

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MU01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MU01I.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

aDAD:={zCURINI,"CRMENS.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
   oSERVER:Close() //Fecha Master	
   oSERVE2:Close() //Fecha Master	
    RETU SELF
ENDIF

aDAD:={zCURINI,"MU01r.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
	oSERVER:Close() //Fecha Master
    oSERVE2:Close() //Fecha Master	
    oSERVE3:Close() //Fecha Master	
   RETU SELF
ENDIF

SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJENSI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJENSI,"CODIGO")
SELF:oSFJENSI:VIEWTABLE()

SELF:oSFJCRMENS:use(oSERVE3)
SELF:oSFJCRMENS:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJCRMENS:VIEWTABLE()

SELF:OSFJENSR:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJENSR,"CODIGO")
SELF:oSFJENSR:VIEWTABLE()

SELF:oDCCODIGOINT:DISABLE()

SELF:SHOW()	

END CLASS
CLASS XJENSMP03 INHERIT ZJENS		
		EXPORT cARQI AS STRING

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MP","ENS")	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MP03.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MP03I.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

aDAD:={zCURINI,"CRMENS.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
   oSERVER:Close() //Fecha Master	
   oSERVE2:Close() //Fecha Master	
    RETU SELF
ENDIF

aDAD:={zCURINI,"Mp03r.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
	oSERVER:Close() //Fecha Master
    oSERVE2:Close() //Fecha Master	
    oSERVE3:Close() //Fecha Master	
   RETU SELF
ENDIF

SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJENSI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJENSI,"NORMA")
SELF:oSFJENSI:VIEWTABLE()

SELF:oSFJCRMENS:use(oSERVE3)
SELF:oSFJCRMENS:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJCRMENS:VIEWTABLE()

SELF:OSFJENSR:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJENSR,"NORMA")
SELF:oSFJENSR:VIEWTABLE()


SELF:SHOW()	
	

END CLASS
CLASS XJENSMQ01 INHERIT ZJENS	
	EXPORT cARQI AS STRING	
	

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MQ","ENS")	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MQ01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MQ01I.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

aDAD:={zCURINI,"CRMENS.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
   oSERVER:Close() //Fecha Master	
   oSERVE2:Close() //Fecha Master	
    RETU SELF
ENDIF

aDAD:={zCURINI,"MQ01r.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
	oSERVER:Close() //Fecha Master
    oSERVE2:Close() //Fecha Master	
    oSERVE3:Close() //Fecha Master	
   RETU SELF
ENDIF

SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJENSI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJENSI,"CODIGO")
SELF:oSFJENSI:VIEWTABLE()

SELF:oSFJCRMENS:use(oSERVE3)
SELF:oSFJCRMENS:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJCRMENS:VIEWTABLE()

SELF:OSFJENSR:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJENSR,"CODIGO")
SELF:oSFJENSR:VIEWTABLE()

SELF:oDCCODIGOINT:DISABLE()

SELF:SHOW()	


END CLASS
CLASS XJENSMR01 INHERIT ZJENS		
		EXPORT cARQI AS STRING
	

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MR","ENS")	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MR01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MR01I.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

aDAD:={zCURINI,"CRMENS.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
   oSERVER:Close() //Fecha Master	
   oSERVE2:Close() //Fecha Master	
    RETU SELF
ENDIF

aDAD:={zCURINI,"MR01r.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
	oSERVER:Close() //Fecha Master
    oSERVE2:Close() //Fecha Master	
    oSERVE3:Close() //Fecha Master	
   RETU SELF
ENDIF


SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJENSI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJENSI,"CODIGO")
SELF:oSFJENSI:VIEWTABLE()

SELF:oSFJCRMENS:use(oSERVE3)
SELF:oSFJCRMENS:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJCRMENS:VIEWTABLE()

SELF:OSFJENSR:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJENSR,"CODIGO")
SELF:oSFJENSR:VIEWTABLE()

SELF:oDCCODIGOINT:DISABLE()

SELF:SHOW()	


END CLASS
CLASS XJENSMS01 INHERIT ZJENS	
	EXPORT cARQI AS STRING	
	

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MS","ENS")	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3,oSERVE4 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",15)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MS01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MS01I.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

aDAD:={zCURINI,"CRMENS.DBF",zCURDIR}
oSERVE3:=USEREDE{aDAD}
IF oSERVE3:nERRO#0
   oSERVER:Close() //Fecha Master	
   oSERVE2:Close() //Fecha Master	
    RETU SELF
ENDIF
aDAD:={zCURINI,"MS01r.DBF",zCURDIR}
oSERVE4:=USEREDE{aDAD}
IF oSERVE4:nERRO#0
	oSERVER:Close() //Fecha Master
    oSERVE2:Close() //Fecha Master	
    oSERVE3:Close() //Fecha Master	
   RETU SELF
ENDIF


SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJENSI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJENSI,"CODIGO")
SELF:oSFJENSI:VIEWTABLE()

SELF:oSFJCRMENS:use(oSERVE3)
SELF:oSFJCRMENS:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJCRMENS:VIEWTABLE()

SELF:OSFJENSR:USE(oSERVE4)
SELF:SetSelectiveRelation(oSFJENSR,"CODIGO")
SELF:oSFJENSR:VIEWTABLE()

SELF:oDCCODIGOINT:DISABLE()

SELF:SHOW()	
	

END CLASS
CLASS ZJENS INHERIT JENS

METHOD append 
	alert("Operaçao Bloqueada")

METHOD buscacodigo( ) 
SELF:KeyFind()

METHOD CHKTIPO( ) 
LOCAL cTIPA AS STRING
SELF:SERVER:GOTOP()
WHILE ! SELF:SERVER:EOF
    SELF:oSFJENSI:server:gotop()
    WHILE ! SELF:oSFJENSI:SERVER:EOF	
    	IF Empty(SELF:oSFJENSI:SERVER:FIELDGET("TIPA"))
    	   cTIPA:=TIPAR(SELF:oSFJENSI:SERVER:FIELDGET("ESPE"))
           IF ! Empty(cTIPA)
              SELF:oSFJENSI:SERVER:FIELDPUT("TIPA",cTIPA)
           ENDIF
        ENDIF		
        SELF:oSFJENSI:SERVER:Skip()
    ENDDO
    SELF:SERVER:SKIP()	
ENDDO		
SELF:SERVER:GOTOP()


METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD cmddesgp12( ) 
LOCAL cCODIGO AS STRING	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
CMDGP12(cCODIGO,"D")	


METHOD cmdesctipa( ) 
    SELF:oSFJENSI:SERVER:FIELDPUT("TIPA",SELF:oSFJCRMENS:FIELDGET("CODIGO"))	
	
	

METHOD cmdesctipa1( ) 
	    SELF:oSFJENSR:SERVER:FIELDPUT("TIPA",SELF:oSFJCRMENS:FIELDGET("CODIGO"))	

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD cmdimp( ) 
LOCAL cCODBUS AS STRING
LOCAL cCODIGO AS STRING
LOCAL aTMP,aITENS AS ARRAY
LOCAL nFIELD,J,K AS WORD


cCODBUS:=SELF:CODIMP02
cCODIGO:=SELF:SERVER:FIELDGET("CODIGO")

aITENS:={}
nFIELD:=SELF:oSFJENSR:server:FCOUNT
IF SELF:SERVER:SEEK(cCODBUS)
   SELF:oSFJENSR:Browser:REFRESH()		
   SELF:oSFJENSR:server:GOTOP()
   WHILE ! oSFJENSR:server:EOF
       aTMP:={}
       FOR J:=1 TO nFIELD
          AAdd(aTMP,SELF:oSFJENSR:server:FIELDGET(J))
       NEXT J
       AAdd(aITENS,aTMP)
       SELF:oSFJENSR:server:SKIP()
   ENDDO	
ENDIF
IF SELF:SERVER:SEEK(cCODIGO)
   SELF:oSFJENSR:SERVER:SUSPENDNOTIFICATION()
   FOR K:=1 TO ALen(aITENS)
       SELF:oSFJENSR:SERVER:APPEND()
       FOR J:=1 TO nFIELD
          SELF:oSFJENSR:server:FIELDPUT(J,aITENS[K][J])
       NEXT J
       SELF:oSFJENSR:SERVER:FIELDPUT("CODIGO",cCODIGO)
       SELF:oSFJENSR:SERVER:commit()
   NEXT K
   SELF:oSFJENSR:SERVER:resetnotification()
   SELF:oSFJENSR:SERVER:notify(notifyappend)
   SELF:oSFJENSR:Browser:REFRESH()		
ENDIF	

METHOD cmdimp1( ) 
LOCAL cCODIGO AS STRING
LOCAL aTMP,aITENS AS ARRAY
LOCAL nFIELD,J,K AS WORD
LOCAL cCODBUS AS STRING

cCODBUS:=SELF:CODIMP01
cCODIGO:=SELF:SERVER:FIELDGET("CODIGO")

IF Empty(cCODBUS)
   alert("Codigo Busca em Branco")
   RETU
ENDIF	



aITENS:={}
nFIELD:=SELF:oSFJENSI:server:FCOUNT
IF SELF:SERVER:SEEK(cCODBUS)
   SELF:oSFJENSI:Browser:REFRESH()		
   SELF:oSFJENSI:server:GOTOP()
   WHILE ! oSFJENSI:server:EOF
      aTMP:={}
      FOR J:=1 TO nFIELD
         AAdd(aTMP,SELF:oSFJENSI:server:FIELDGET(J))
      NEXT J
      AAdd(aITENS,aTMP)
     SELF:oSFJENSI:server:SKIP()
  ENDDO	
ENDIF
IF SELF:SERVER:SEEK(cCODIGO)
   SELF:oSFJENSI:SERVER:SUSPENDNOTIFICATION()
   FOR K:=1 TO ALen(aITENS)
       SELF:oSFJENSI:SERVER:APPEND()
       FOR J:=1 TO nFIELD
          SELF:oSFJENSI:server:FIELDPUT(J,aITENS[K][J])
       NEXT J
       SELF:oSFJENSI:SERVER:FIELDPUT("CODIGO",cCODIGO)
       SELF:oSFJENSI:SERVER:commit()
   NEXT K
   SELF:oSFJENSI:SERVER:resetnotification()
   SELF:oSFJENSI:SERVER:notify(notifyappend)
   SELF:oSFJENSI:Browser:REFRESH()		
ENDIF	

METHOD cmdmargp12( ) 
LOCAL cCODIGO AS STRING	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
CMDGP12(cCODIGO,"I")	

METHOD CMDRENUM( ) 
LOCAL nITEM AS DWORD
nITEM:=1	
SELF:oSFJENSI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJENSI:server:gotop()
WHILE ! SELF:oSFJENSI:SERVER:EOF	
    SELF:oSFJENSI:SERVER:FIELDPUT("ITEM",nITEM)
    SELF:oSFJENSI:SERVER:commit()
    SELF:oSFJENSI:SERVER:Skip()
    nITEM++
ENDDO
SELF:oSFJENSI:SERVER:resetnotification()
SELF:oSFJENSI:SERVER:notify(NOTIFYFILECHANGE)
SELF:oSFJENSI:server:gotop()
SELF:oSFJENSI:Browser:REFRESH()		



METHOD CMDRENUM1( ) 
	LOCAL nITEM AS DWORD
nITEM:=1	
SELF:oSFJENSR:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJENSR:server:gotop()
WHILE ! SELF:oSFJENSR:SERVER:EOF	
    SELF:oSFJENSR:SERVER:FIELDPUT("ITEM",nITEM)
    SELF:oSFJENSR:SERVER:commit()
    SELF:oSFJENSR:SERVER:Skip()
    nITEM++
ENDDO
SELF:oSFJENSR:SERVER:resetnotification()
SELF:oSFJENSR:SERVER:notify(NOTIFYFILECHANGE)
SELF:oSFJENSR:server:gotop()
SELF:oSFJENSR:Browser:REFRESH()		



METHOD cmdvergp12( ) 
LOCAL cCODIGO AS STRING
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
IF CMDGP12(cCODIGO,"V")="V"
   alert("Marcada GP12")
ELSE	
   alert("Nao Marcada GP12")
ENDIF	
	

METHOD cmdvergp13( ) 
LOCAL cCODIGO AS STRING
LOCAL aRETU AS ARRAY
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
aRETU:=CMD3L(cCODIGO,"V")
IF aRETU[1]
//   alert("Marcada 3L")
   alert(TEXTO3L(aRETU))
ELSE	
   alert("Nao Marcada 3L")
ENDIF	
	

METHOD delete 
	alert("Operaçao Bloqueada")
	

METHOD Editar( ) 
	SELF:oSFJENSI:ViewForm()

METHOD Editar1( ) 
		SELF:oSFJENSR:ViewForm()

METHOD escPF( ) 
LOCAL oJAN AS XJPFDIA
oJAN:=XJPFDIA{SELF,SELF:SERVER:FIELDGET("APLICACAO")}
oJAN:SHOW()	
IF oJAN:lOK
   SELF:nPF:=ojan:nPF
ENDIF		

METHOD Excluir( ) 
	SELF:oSFJENSI:Server:DELETE()
	SELF:oSFJENSI:SERVER:GOTOP()
	SELF:oSFJENSI:Browser:REFRESH()

METHOD Excluir1( ) 
SELF:oSFJENSI:server:gotop()
WHILE ! SELF:oSFJENSI:SERVER:EOF	
	SELF:oSFJENSI:Server:DELETE()
    SELF:oSFJENSI:SERVER:Skip()
ENDDO
SELF:oSFJENSI:server:gotop()
SELF:oSFJENSI:Browser:REFRESH()	

METHOD Excluir2( ) 
	SELF:oSFJENSR:server:gotop()
WHILE ! SELF:oSFJENSR:SERVER:EOF	
	SELF:oSFJENSR:Server:DELETE()
    SELF:oSFJENSR:SERVER:Skip()
ENDDO
SELF:oSFJENSR:server:gotop()
SELF:oSFJENSR:Browser:REFRESH()	

METHOD Excluir3( ) 
	SELF:oSFJENSR:Server:DELETE()
	SELF:oSFJENSR:SERVER:GOTOP()
	SELF:oSFJENSR:Browser:REFRESH()

METHOD ImpMC( ) 
LOCAL oConn AS SQLConnection
LOCAL oREG AS SQLSelect
LOCAL cCODIGO,cCODBUS,cSQL AS STRING
LOCAL nITEM AS DWORD
LOCAL cESPE AS STRING


cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
IF Empty(cCODIGO)
   alert("Codigo em Branco")
   RETU
ENDIF	

cCODBUS:=SELF:CODIMP01
IF Empty(cCODBUS)
   alert("Codigo Busca em Branco")
   RETU
ENDIF	


IF ! MDG("Apagar Itens Antes de Importar")
   SELF:Excluir1()
ENDIF


cSQL:="SELECT * FROM QE7010 WHERE QE7_produt='"+ AllTrim(cCODBUS) + "' AND D_E_L_E_T_<>'*'"

oConn := SQLConnection{}
IF ! oConn:connect("protheus","","")
  	  alert("Erro na Conecção")
     RETU
ENDIF

nITEM:=1
oreg:= SQLSelect{cSQL,oconn}
SELF:oSFJENSI:SERVER:SUSPENDNOTIFICATION()
WHILE ! OREG:EoF
   cESPE:=FIXSTR(oREG:FIELDGET("QE7_ENSAIO"))		
   cESPE+=" "+FIXSTR(oREG:FIELDGET("Qe7_LABOR"))	
//   cESPE+=" "+FIXSTR(oREG:FIELDGET("TOL"))	
   SELF:oSFJENSI:SERVER:APPEND()
   SELF:oSFJENSI:SERVER:FIELDPUT("CODIGO",cCODIGO)
   SELF:oSFJENSI:server:FIELDPUT("ITEM",nITEM)
   SELF:oSFJENSI:server:FIELDPUT("ESPE",cESPE)
   SELF:oSFJENSI:server:FIELDPUT("VALPAD",oREG:FIELDGET("QE7_NOMINA"))
   SELF:oSFJENSI:server:FIELDPUT("VALMAX",oREG:FIELDGET("QE7_LIE"))
   SELF:oSFJENSI:server:FIELDPUT("VALMIN",oREG:FIELDGET("QE7_LSE"))
   SELF:oSFJENSI:server:FIELDPUT("UNIDADE",oREG:FIELDGET("QE7_UNIMED"))
   SELF:oSFJENSI:server:FIELDPUT("TIPA",oREG:FIELDGET("QE7_ENSAIO"))
   SELF:oSFJENSI:SERVER:commit()
   nITEM++
   Oreg:Skip()
ENDDO
oREG:Close()
oConn:Disconnect()
SELF:oSFJENSI:SERVER:resetnotification()
SELF:oSFJENSI:SERVER:notify(NOTIFYFILECHANGE)
SELF:oSFJENSI:Browser:REFRESH()			
SELF:CMDRENUM()
	

	

METHOD IMPORTARPF(nTIPO) 
LOCAL oConn AS SQLConnection
LOCAL oREG AS SQLSelect
LOCAL cPF,cCODIGO,cCODCOMP,cSEQ,cSSQ,cSQL AS STRING
LOCAL nITEM AS DWORD
LOCAL cESPE AS STRING
LOCAL oBUSCA AS XBUSCA


cPF:=AllTrim(oDCnPF:TextValue)
IF Empty(cPF)
   alert("PF Nao Preenchido")
  RETU
ENDIF	

cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
IF Empty(cCODIGO)
   alert("Codigo em Branco")
   RETU
ENDIF	


cSEQ:=AllTrim(oDCnSEQ:TextValue)
cSSQ:=AllTrim(oDCnSSQ:TextValue)
IF nTIPO=5 .OR. nTIPO=6
   IF Empty(cseq)	
      cSEQ:="10"
   ENDIF
   IF Empty(cSSQ)
      cSSQ:="10"	
   ENDIF
ENDIF	


IF ! MDG("Apagar Itens Antes de Importar")
   SELF:Excluir1()
ENDIF


IF nTIPO=2
   oBUSCA:=XBUSCA{SELF,"Confirmação","Confirme o Codigo",cCODIGO}
   oBUSCA:lMES:=.T.
   oBUSCA:SHOW()
   IF ! oBUSCA:lOK
      RETU SELF	
   ENDIF
   cCODCOMP:=oBUSCA:cBUSCA
   IF Empty(cCODCOMP)
      alert("Codigo em Branco")
      RETU
  ENDIF	
ENDIF


DO CASE
   CASE  nTIPO=1 .OR. nTIPO=3
         cSQL:="SELECT ESPE,CARAC,TOL FROM PFC WHERE PF="+cPF+" AND SEQ="+cSEQ+" AND SSQ="+cSSQ
   CASE  nTIPO=2 .OR. nTIPO=4
         cSQL:="SELECT ESPE,CARAC,TOL FROM PFCMS03 WHERE PF="+cPF+" AND CODCOMP='"+cCODCOMP+"'"
   CASE  nTIPO=5 .OR. nTIPO=6
         cSQL:="SELECT ESPE,CARAC,TOL FROM PFCO WHERE PF="+cPF+" AND SEQ="+cSEQ+" AND SSQ="+cSSQ
ENDCASE


oConn := SQLConnection{}
IF nTIPO=1 .OR. nTIPO=2 .OR. nTIPO=5
  IF ! oConn:connect("pf","","")
  	  alert("Erro na Conecção")
     RETU
   ENDIF	
ENDIF
IF nTIPO=3 .OR. nTIPO=4 .OR. nTIPO=6
  IF ! oConn:connect("pfP","","")
  	  alert("Erro na Conecção")
     RETU
   ENDIF	
ENDIF

nITEM:=1
oreg:= SQLSelect{cSQL,oconn}
SELF:oSFJENSI:SERVER:SUSPENDNOTIFICATION()
WHILE ! OREG:EoF
   cESPE:=FIXSTR(oREG:FIELDGET("CARAC"))		
   cESPE+=" "+FIXSTR(oREG:FIELDGET("ESPE"))	
   cESPE+=" "+FIXSTR(oREG:FIELDGET("TOL"))	
   IF ! Empty(Cespe)
      SELF:oSFJENSI:SERVER:APPEND()
      SELF:oSFJENSI:SERVER:FIELDPUT("CODIGO",cCODIGO)
      SELF:oSFJENSI:server:FIELDPUT("ESPE",cESPE)
      SELF:oSFJENSI:server:FIELDPUT("ITEM",nITEM)
      SELF:oSFJENSI:SERVER:commit()
      nITEM++
   ENDIF
   Oreg:Skip()
ENDDO
oREG:Close()
oConn:Disconnect()
SELF:oSFJENSI:SERVER:resetnotification()
SELF:oSFJENSI:SERVER:notify(NOTIFYFILECHANGE)
SELF:oSFJENSI:Browser:REFRESH()			
SELF:CMDRENUM()
	



METHOD IMPPFcom( ) 
	SELF:iMPORTARPF(2)

METHOD IMPPFcom1( ) 
	SELF:IMPORTARPF(4)

METHOD IMPPFcom2( ) 
	SELF:IMPORTARPF(5)

METHOD IMPPFcom3( ) 
		SELF:IMPORTARPF(6)

METHOD IMPPFSEQ( ) 
	SELF:IMPORTARPF(1)

METHOD IMPPFSEQ1( ) 
	SELF:IMPORTARPF(3)

METHOD Incluir( ) 
LOCAL cCODIGO AS STRING	
LOCAL nITEM AS DWORD
cCODIGO:=SELF:SERVER:FIELDGET("CODIGO")
SELF:oSFJENSI:SERVER:GOBOTTOM()
nITEM:=SELF:oSFJENSI:SERVER:FIELDGET("ITEM")
nITEM++
SELF:oSFJENSI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJENSI:SERVER:APPEND()
SELF:oSFJENSI:SERVER:FIELDPUT("CODIGO",cCODIGO)
SELF:oSFJENSI:SERVER:FIELDPUT("ITEM",nITEM)
SELF:oSFJENSI:SERVER:commit()
SELF:oSFJENSI:SERVER:resetnotification()
SELF:oSFJENSI:SERVER:notify(notifyappend)
SELF:oSFJENSI:Browser:REFRESH()	

METHOD Incluir1( ) 
LOCAL cCODIGO AS STRING	
LOCAL nITEM AS DWORD
cCODIGO:=SELF:SERVER:FIELDGET("CODIGO")
SELF:oSFJENSR:SERVER:GOBOTTOM()
nITEM:=SELF:oSFJENSR:SERVER:FIELDGET("ITEM")
nITEM++
SELF:oSFJENSR:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJENSR:SERVER:APPEND()
SELF:oSFJENSR:SERVER:FIELDPUT("CODIGO",cCODIGO)
SELF:oSFJENSR:SERVER:FIELDPUT("ITEM",nITEM)
SELF:oSFJENSR:SERVER:commit()
SELF:oSFJENSR:SERVER:resetnotification()
SELF:oSFJENSR:SERVER:notify(notifyappend)
SELF:oSFJENSR:Browser:REFRESH()	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Tabular( ) 
	SELF:oSFJENSI:ViewTable()

METHOD Tabular1( ) 
		SELF:oSFJENSR:ViewTable()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJENSI:SERVER:COMMIT()
   SELF:oSFJCRMENS:SERVER:COMMIT()



END CLASS
