CLASS XJPEMO INHERIT ZJPEMO
	

METHOD CHKPED( ) 
LOCAL oSERVER AS USEREDE	
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"MW02.DBF",zCURDIR}	
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO=0
   oSERVER:GOTOP()
   IF oSERVER:SEEK(Str(SELF:SERVER:FIELDGET("COMPRAS"),8)+Str(SELF:SERVER:FIELDGET("COMITEM"),3))
      SELF:SERVER:FIELDPUT("TIPPED",oSERVER:FIELDGET("ITETIP"))
      SELF:SERVER:FIELDPUT("CODIGO",oSERVER:FIELDGET("ITECOD"))
      SELF:pegcod()
      SELF:pegforped()
      SELF:pegfor()
   ENDIF
   oSERVER:CLOSE()
ENDIF		

METHOD ESCFOR( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MA01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("FORNECEDO",OESC:NUMERO)
ENDIF
SELF:PEGFOR()


METHOD escped( ) 
	SELF:pegpedx("T")

METHOD escped1( ) 
	SELF:pegpedx("C")

METHOD escped2( ) 
	SELF:pegpedx("M")

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",23)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PEMO.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	


METHOD pegfor( ) 
LOCAL aFORN AS ARRAY
aFORN:=PEGMA01(SELF:SERVER:FIELDGET("FORNECEDO"),ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:FIELDPUT("COGNOME",aFORN[3])
ENDIF

METHOD pegforped() 


METHOD pegpedx(cTIPO) 
LOCAL oJAN AS Xescmw02
oJAN:=Xescmw02{SELF,ZCURINI,ZCURDIR,"ITETIP='"+cTIPO+"'"}
oJAN:SHOW()
IF oJAN:lOK	
	AltD()
   SELF:SERVER:FIELDPUT("COMPRAS",OJAN:NUMERO)
   SELF:SERVER:FIELDPUT("COMITEM",Ojan:ITEM)
   SELF:SERVER:FIELDPUT("CODIGO",oJAN:cCODIGO)
   SELF:SERVER:FIELDPUT("TIPPED",oJAN:cTIPO)
   SELF:pegcod()
   SELF:PEGFORPED()
   SELF:pegfor()
ENDIF		






END CLASS
CLASS XJPETR INHERIT ZJPEMO

METHOD ESCFOR( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"MB01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("FORNECEDO",OESC:NUMERO)
ENDIF
SELF:PEGFOR()	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",24)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"PETR.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

METHOD pegfor( ) 
LOCAL aFORN AS ARRAY
aFORN:=PEGMB01(SELF:SERVER:FIELDGET("FORNECEDO"),ZCURINI,ZCURDIR)
IF aFORN[1]=.T.
   SELF:SERVER:FIELDPUT("COGNOME",aFORN[3])
ENDIF


METHOD pegforped() 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE	
 aDAD:={zCURINI,"MW01.DBF",zCURDIR}
 oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO=0
   oSERVER:GOTOP()
   IF oSERVER:SEEK(SELF:SERVER:FIELDGET("COMPRAS"))
   	  SELF:SERVER:FIELDPUT("FORNECEDO",oSERVER:FIELDGET("COMFOR"))
   ENDIF	
   oSERVER:CLOSE()
ENDIF

END CLASS
CLASS ZJPEMO INHERIT JPEMO

METHOD APPEND() 
LOCAL nNUMERO AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:FIELDGET("PEDIDO")
nNUMERO++
SUPER:append()
SELF:SERVER:FIELDPUT("PEDIDO",nNUMERO)
RETURN SELF

METHOD busca( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()


METHOD DELETE() 
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
	IF SELF:SERVER:BOF
	   SELF:SERVER:GOTOP()	
	ENDIF	
ENDIF	

METHOD esccod( ) 
LOCAL oESC AS XESCCOD	
LOCAL Ctipo AS STRING
cTIPO:=SELF:server:FIELDGET("TIPPED")
DO CASE
	CASE CtipO="M"
       oESC:=XESCCOD{SELF,"MU01.DBF"}		
	CASE Ctipo="C"
       oESC:=XESCCOD{SELF,"MT01.DBF"}		
	CASE Ctipo="T"
       oESC:=XESCCOD{SELF,"MP03.DBF"}		
	OTHERWISE
       oESC:=XESCCOD{SELF,"MS01.DBF"}
ENDCASE
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("CODIGO",oESC:CODIGO)
    SELF:pegcod()
ENDIF			

METHOD esccod1( ) 
LOCAL oESC AS XESCCOD	
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("APLICACAO",oESC:CODIGO)
ENDIF		

METHOD esccod2( ) 
LOCAL oESC AS XESCNUM	
oESC:=XESCNUM{SELF,"CRMCESP.DBF"}
oESC:SHOW()	
IF Oesc:lok
    SELF:CODAVU:=OESC:NUMERO
ENDIF
SELF:pegcod1()


METHOD pegcod( ) 
LOCAL Aretu AS ARRAY
LOCAL Ctipo AS STRING
LOCAL cCODIGO AS STRING
Ctipo:=SELF:server:FIELDGET("TIPPED")
CCODIGO:=SELF:server:FIELDGET("CODIGO")
aretu:={}	
DO CASE
	CASE Ctipo="M"
       ARETU:=PEGMU01(CCODIGO,zcurini,zcurdir)
       SELF:SERVER:FIELDPUT("UNID","KG")
	CASE Ctipo="C"
       ARETU:=PEGMT01(CCODIGO,zcurini,zcurdir)
        SELF:SERVER:FIELDPUT("UNID","PC")
	CASE Ctipo="T"
       ARETU:=PEGMP03(CCODIGO,zcurini,zcurdir)
        SELF:SERVER:FIELDPUT("UNID","KG")
ENDCASE	
IF aRETU[1]
    IF Ctipo="T"	
       SELF:SERVER:FIELDPUT("NOME",SubStr(ARETU[8],1,50))
       SELF:SERVER:FIELDPUT("NOM2",SubStr(ARETU[8],51))
    ELSE
       SELF:SERVER:FIELDPUT("NOME",SubStr(ARETU[2],1,50))
       SELF:SERVER:FIELDPUT("NOM2",SubStr(ARETU[2],51))
    ENDIF
    SELF:SERVER:FIELDPUT("APLICACAO",ARETU[3])
ENDIF		

METHOD pegcod1( ) 
LOCAL oSERVER AS USEREDE	
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"CRMCESP.DBF",zCURDIR}	
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO=0
   oSERVER:GOTOP()
   IF oSERVER:SEEK(SELF:CODAVU)
      SELF:SERVER:FIELDPUT("TIPPED",oSERVER:FIELDGET("TIPOENT"))
      SELF:SERVER:FIELDPUT("CODIGO",oSERVER:FIELDGET("CODIGO"))
      SELF:SERVER:FIELDPUT("NOME",SubStr(oSERVER:FIELDGET("NOME"),1,50))
      SELF:SERVER:FIELDPUT("NOM2",SubStr(oSERVER:FIELDGET("NOME"),51))
   ENDIF
   oSERVER:CLOSE()
ENDIF			

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)      //5minx60seg
    FabCenterWindow( SELF )
 RETURN SELF

METHOD TIPOC( ) 
	SELF:SERVER:FIELDPUT("UNID","PC")
 SELF:SERVER:FIELDPUT("TIPPED","C")	

METHOD TIPOM( ) 
 SELF:SERVER:FIELDPUT("UNID","KG")
 SELF:SERVER:FIELDPUT("TIPPED","M")	

METHOD TIPOT( ) 
	SELF:SERVER:FIELDPUT("UNID","KG")
 SELF:SERVER:FIELDPUT("TIPPED","T")	


END CLASS
