CLASS XJRIRM INHERIT JRIRM	

METHOD Alterar( ) 
SELF:oSFJRIMI:SERVER:SUSPENDNOTIFICATION()
oSFJRIMI:server:GOTOP()
WHILE ! oSFJRIMI:server:EOF
  SELF:oSFJRIMI:server:qtitem:=SELF:nQTDE
  SELF:oSFJRIMI:server:SKIP()
ENDDO	
SELF:oSFJRIMI:SERVER:resetnotification()
SELF:oSFJRIMI:SERVER:notify(NOTIFYFILECHANGE)

METHOD APPEND() 
	LOCAL nRIRM AS DWORD
	LOCAL oJINC AS JRIRMINC
	LOCAL cRASTRO AS STRING
	LOCAL cLOTECRT AS STRING
	LOCAL aRASTRO AS ARRAY
	LOCAL lRASTRO AS LOGIC
	aRASTRO:={0,""}

SELF:DESABI()		
IF ! entramenu("CRM",21)
	RETU SELF
ENDIF


//local nRIRM as dword
oJINC:=JRIRMINC{SELF}
oJINC:SHOW()
IF ! OJINC:LRETU
   RETURN SELF
ENDIF	

IF oJINC:ARETU[15]="C" .OR. oJINC:ARETU[15]="M" 
	NOP
ELSE
	alert("RIRM so materia Prima ou componente")
   RETURN SELF	
ENDIF	

lRASTRO:=.F.
Crastro:=oJINC:ARETU[2]
IF Empty(CRASTRO)
   aRASTRO:=NOVORASTRO()
   cRASTRO:=ARASTRO[2]
   lRASTRO:=.T.	
ENDIF	


CLOTECRT:=oJINC:ARETU[17]
IF Empty(clotecrt)
   cLOTECRT:=NOVOLOTE(oJINC:ARETU[6],oJINC:ARETU[3])	
ENDIF	


SELF:server:setorder(1)
SELF:server:gobottom()
nRIRM:=SELF:Server:RIRM
nRIRM++
SUPER:append()
SELF:SERVER:FIELDPUT("RIRM",nRIRM)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("CLASSI",oJINC:ARETU[1])
SELF:SERVER:FIELDPUT("RASTRO",cRASTRO)
SELF:SERVER:FIELDPUT("DESENHO",oJINC:ARETU[3])
SELF:SERVER:FIELDPUT("DESCR",oJINC:ARETU[4])
SELF:SERVER:FIELDPUT("INSTRU",oJINC:ARETU[5])
SELF:SERVER:FIELDPUT("NFORN",oJINC:ARETU[6])
SELF:SERVER:FIELDPUT("FORNE",oJINC:ARETU[7])
SELF:SERVER:FIELDPUT("PEDIDO",oJINC:ARETU[8])
SELF:SERVER:FIELDPUT("NRNOTA",oJINC:ARETU[9])
SELF:SERVER:FIELDPUT("NRNOTB",oJINC:ARETU[10])
SELF:SERVER:FIELDPUT("DATANF",oJINC:ARETU[11])
SELF:SERVER:FIELDPUT("QTDE",oJINC:ARETU[12])
SELF:SERVER:FIELDPUT("CERT",oJINC:ARETU[13])
SELF:SERVER:FIELDPUT("UNID",oJINC:ARETU[14])
SELF:SERVER:FIELDPUT("TIPOENT",oJINC:ARETU[15])
SELF:SERVER:FIELDPUT("APLICACAO",oJINC:ARETU[16])
SELF:SERVER:FIELDPUT("clotecrt",CLOTECRT)
SELF:SERVER:Commit()
SELF:SERVER:gobottom()
IF lRASTRO
   GRAVARASTRO(aRASTRO[1],0,nRIRM,0,oJINC:ARETU[3],"")	
ENDIF	
SELF:criaitens()
RETURN SELF

METHOD BUSCAAVANCADA() 
	SUPER:BUSCAAVANCADA()
	SELF:DESABI()	

METHOD buscaRirm(oOWNER) 
SELF:KEYFIND()	
//LOCAL oBUSCA AS xBUSCA
//oBUSCA:=xBUSCA{oOWNER,"Localizar","Digite RIRM"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF
SELF:DESABI()

METHOD CHECKNOM 
LOCAL aPRO AS ARRAY
LOCAL lRETU AS LOGIC
lRETU:=.F.	
aPRO:={.F.,"","","","",0,""}
IF SELF:SERVER:FIELDGET("TIPOENT")=="C"
   aPRO:=PEGMT01(SELF:SERVER:FIELDGET("DESENHO"),zcurini,zcurdir)
   IF aPRO[1]=.F.
      alert("Componente Não Cadastrado")
   ELSE
      lRETU:=.T.
   ENDIF
ENDIF
IF SELF:SERVER:FIELDGET("TIPOENT")=="M"
   aPRO:=PEGMU01(SELF:SERVER:FIELDGET("DESENHO"),zcurini,zcurdir)
   IF aPRO[1]=.F.
      alert("Matéria Prima Não Cadastrada")
   ELSE
      lRETU:=.T.
   ENDIF
ENDIF
IF lRETU
   IF MDG("Código Encontrado-Atualizar Descrição/Aplicação")
      SELF:SERVER:FIELDPUT("DESCR",aPRO[2])
      SELF:SERVER:FIELDPUT("APLICACAO",APRO[3])
   ELSE
   	  lRETU:=.F.
   ENDIF	
ENDIF
RETU lRETU

METHOD CHKens( ) 
SELF:SERVER:GOTOP()
SELF:SERVER:SEEK(15342)
WHILE ! SELF:SERVER:EOF
	IF Year(SELF:SERVER:FIELDGET("data"))=2004
	   IF Empty(SELF:oSFJRIMI:SERVER:FIELDGET("ITEM"))
//	   	  AltD()
  	      SELF:criaitens()	
  	   ENDIF
    ENDIF
    SELF:SERVER:SKIP()	
ENDDO		
SELF:SERVER:GOTOP()		

METHOD CHKTIPO( ) 
SELF:SERVER:GOTOP()
WHILE ! SELF:SERVER:EOF
	SELF:subchktip()
    SELF:SERVER:SKIP()	
ENDDO		
SELF:SERVER:GOTOP()	


METHOD cmdbobina( ) 
SELF:oSFJRIMI:ViewTable()	
SELF:oSFJRIMI:server:FIELDPUT("ENCO","Executado na Liberacao da Bobina")	
SELF:oSFJRIMI:server:FIELDPUT("PULAAPU","S")	
SELF:oSFJRIMI:server:FIELDPUT("LAUDO","S")	
IF ! SELF:oSFJRIMI:SERVER:EOF
    SELF:oSFJRIMI:SERVER:SKIP()	
ENDIF		

METHOD cmdcert( ) 
SELF:oSFJRIMI:ViewTable()	
SELF:oSFJRIMI:server:FIELDPUT("ENCO","Conforme Certificado")	
SELF:oSFJRIMI:server:FIELDPUT("PULAAPU","S")	
SELF:oSFJRIMI:server:FIELDPUT("LAUDO","S")	
IF ! SELF:oSFJRIMI:SERVER:EOF
    SELF:oSFJRIMI:SERVER:SKIP()	
ENDIF	

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()
SELF:DESABI()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()
	SELF:DESABI()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CRM","RIRM")	


METHOD cmdinicia( ) 
LOCAL cCODIGO AS STRING	
LOCAL ARETU AS ARRAY
LOCAL oJAN AS Xjensrx






IF SELF:SERVER:FIELDGET("LLAUDO") .AND. ! Empty(SELF:SERVER:FIELDGET("LAUDOF"))
  IF Empty(SELF:oSFJRIMI:SERVER:FIELDGET("LAUDO"))
      alert("Laudo Item Nao Preenchido")
      SELF:SERVER:FIELDPUT("LAUDOF"," ")
      RETU
   ENDIF
   alert("Laudo Já fornecido")
   IF Empty(SELF:SERVER:FIELDGET("DATAL"))
      SELF:SERVER:FIELDPUT("DATAL",SELF:SERVER:FIELDGET("DATA"))
   ENDIF
   RETU
ENDIF	

aRETU:=TEMCHKCERT(SELF:server:FIELDGET("TIPOENT"),SELF:SERVER:FIELDGET("DESENHO"))
IF aRETU[1]
   oJAN:=Xjensrx{SELF,aRETU[2],SELF:SERVER:FIELDGET("DESENHO")}
   oJAN:SHOW()
   IF .not.oJAN:LOK
     RETU
   ENDIF
ENDIF


SELF:HABILI()
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("DESENHO"))
IF CMDGP12(cCODIGO,"V")="V"
   alert("Marcada Item Critico")	
ENDIF
aRETU:=CMD3L(cCODIGO,"V")
IF aRETU[1]
   alert(TEXTO3L(aRETU))
ENDIF	
IF SELF:SERVER:FIELDGET("CLOTECRT")="0" .or. SELF:SERVER:FIELDGET("CLOTECRT")="P"
   alert("Realizar Dimensional/Testes Fisicos/Comparacao Quimica")	
ENDIF

METHOD criaitens( ) 
LOCAL oARQ AS USEREDE
LOCAL cCODIGO,cTIPO AS STRING
LOCAL nRIRM AS DWORD
LOCAL aDAD AS ARRAY
nRIRM:=SELF:SERVER:FIELDGET("RIRM")
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("DESENHO"))
cTIPO:=SELF:SERVER:FIELDGET("TIPOENT")
SELF:oSFJRIMI:SERVER:SUSPENDNOTIFICATION()
IF cTIPO=="C" .OR. cTIPO=="M"
   aDAD:={zCURINI,IF(cTIPO=="C","MT01I.DBF","MU01I.DBF"),zCURDIR}
   oARQ:=USEREDE{aDAD}
   IF oARQ:nERRO=0
      oARQ:GOTOP()
      oARQ:SEEK(cCODIGO)
      WHILE AllTrim(cCODIGO)=AllTrim(oARQ:FIELDGET("CODIGO")) .AND. ! oARQ:EOF
            SELF:oSFJRIMI:SERVER:APPEND()
		    SELF:oSFJRIMI:SERVER:LOCKCURRENTRECORD()
		    SELF:oSFJRIMI:SERVER:FIELDPUT("RIRM",nRIRM)
		    SELF:oSFJRIMI:SERVER:FIELDPUT("ITEM",oARQ:FIELDGET("ITEM"))
		    SELF:oSFJRIMI:SERVER:FIELDPUT("ESPE",oARQ:FIELDGET("ESPE"))
		    SELF:oSFJRIMI:SERVER:FIELDPUT("ENCO",oARQ:FIELDGET("ENCO"))
		    SELF:oSFJRIMI:SERVER:FIELDPUT("TIPA",oARQ:FIELDGET("TIPA"))
		    SELF:oSFJRIMI:SERVER:FIELDPUT("UNIITEM",oARQ:FIELDGET("UNIDREF"))	
            SELF:oSFJRIMI:SERVER:FIELDPUT("QTITEM",oARQ:FIELDGET("QTDEREF"))		
		    oARQ:SKIP()
       ENDDO
	   oARQ:CLOSE()
	ENDIF
  ENDIF


SELF:oSFJRIMI:SERVER:Commit()
SELF:oSFJRIMI:SERVER:resetnotification()
SELF:oSFJRIMI:SERVER:notify(notifyfilechange)	

METHOD DELETE() 
	SELF:DESABI()	
IF ! entramenu("CRM",21)
	RETU SELF
ENDIF
IF SELF:server:FIELDGET("CRM")>0
   alert("Exclusão Somente Por CRM")
   RETU SELF
ENDIF
IF ! MDG("Apagar Registro") .AND. SELF:server:LockCurrentRecord()
	RETU SELF
ENDIF	
GRAVALOG(SELF:SERVER:RIRM,"DEL","RIRM")	
SELF:oSFJRIMI:server:GOTOP()	
WHILE ! oSFJRIMI:server:EOF
 	SELF:oSFJRIMI:server:delete()
 	SELF:oSFJRIMI:Skip()
ENDDO	
SELF:server:delete()
SELF:server:skip(-1)
IF SELF:SERVER:BOF
   SELF:SERVER:GOTOP()	
ENDIF	
SELF:oSFJRIMI:Browser:REFRESH()
//SELF:oSFJRIMI:SERVER:SUSPENDNOTIFICATION()
//SELF:oSFJRIMI:SERVER:resetnotification()
//SELF:oSFJRIMI:SERVER:notify(notifyfilechange)

METHOD DESABI() 
	oCCEditar:DISABLE()
	oCCTabular:DISABLE()
	oCCLaudo:DISABLE()
	oCCAlterar:DISABLE()
//	oCCRC:DISABLE()
	oCCTL:DISABLE()
//	oCCbuscarastro:DISABLE()
//	oCCbuscarirm:DISABLE()
	oCCpegamostra:DISABLE()
	oCCcriaitens:DISABLE()
	oCCdigcod:DISABLE()
	oCCdigdes:DISABLE()
	oCCdigapl:DISABLE()
	oCCchecknom:DISABLE()
//	oCCetiqlab:DISABLE()
	oCCcmdcert:DISABLE()
//	oCCfoto:DISABLE()
	oCCCHKTIPO:DISABLE()
	oCCsubchktip:DISABLE()
	oCCCHKens:DISABLE()
	oCCpegcla:DISABLE()
	oCCcmdbobina:Disable()
	oCCdigcod1:Disable()
//	oCCetiqIdent:Disable()
//	oCCetiqmat:DISABLE()

METHOD digAPL(oOWNER) 
LOCAL oBUSCA AS xBUSCA
IF ! Empty(SELF:SERVER:FIELDGET("APLICACAO"))
   RETU
ENDIF
oBUSCA:=xBUSCA{oOWNER,"Digitar","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:FIELDPUT("APLICACAO",oBUSCA:cBUSCA)
ENDIF

METHOD digcod(oOWNER) 
LOCAL oBUSCA AS xBUSCA
LOCAL cCODIGO AS STRING
cCODIGO:=Upper(AllTrim(SELF:SERVER:FIELDGET("DESENHO")))
IF ! Empty(cCODIGO)
   IF SELF:SERVER:FIELDGET("CLOTECTR")<>"P" .AND. ! checkespcod(cCODIGO)
      RETU	
   ENDIF
ENDIF
oBUSCA:=xBUSCA{oOWNER,"Digitar","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:FIELDPUT("DESENHO",oBUSCA:cBUSCA)
   IF ! SELF:CHECKNOM()
      IF MDG("Apagar Descrição")
         SELF:SERVER:FIELDPUT("DESCR","")
      ENDIF
      IF MDG("Apagar Aplicação")
        SELF:SERVER:FIELDPUT("APLICACAO","")
      ENDIF
   ENDIF
ENDIF

METHOD digcod1( ) 
LOCAL oESC AS XESCCOD	
IF ! Empty(SELF:SERVER:FIELDGET("APLICACAO"))
   RETU
ENDIF
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("APLICACAO",oESC:CODIGO)
ENDIF	




METHOD digDES(oOWNER) 
LOCAL oBUSCA AS xBUSCA
IF ! Empty(SELF:SERVER:FIELDGET("DESCR"))
   RETU
ENDIF
oBUSCA:=xBUSCA{oOWNER,"Digitar","Digite a descricao"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:FIELDPUT("DESCR",oBUSCA:cBUSCA)
ENDIF

METHOD Editar( ) 
SELF:oSFJRIMI:ViewForm()	

METHOD etiqIdent( ) 
LOCAL oJAN AS ETIQ02
IF Empty(SELF:SERVER:FIELDGET("LAUDOF"))
   alert("Laudo Nao fornecido")
   RETU
ENDIF
oJAN:=ETIQ02{SELF}	
oJAN:ncrm:=SELF:SERVER:FIELDGET("CRM")
oJAN:cRESPO:=SELF:SERVER:FIELDGET("RESPO")
oJAN:IMPORTAR()
oJAN:SHOW()		

METHOD etiqlab( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aPRO AS ARRAY
LOCAL oJAN AS ETIQ03
aDAD:={zCURINI,"CRME03.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oJAN:=ETIQ03{SELF,,oSERVER}
oJAN:SERVER:FIELDPUT("ESPE",SELF:oSFJRIMI:SERVER:FIELDGET("ESPE"))
oJAN:SERVER:FIELDPUT("USUARIO",ZUSER)
oJAN:SERVER:FIELDPUT("SETOR","Recebimento")
oJAN:SERVER:FIELDPUT("DATA",Today())
oJAN:SERVER:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("APLICACAO"))
oJAN:SERVER:FIELDPUT("REFNUM",SELF:SERVER:FIELDGET("RIRM"))
oJAN:SERVER:FIELDPUT("NCLI",0)
oJAN:SERVER:FIELDPUT("CLIENTE","")
IF At("/",SELF:SERVER:FIELDGET("APLICACAO"))>0
   oJAN:SERVER:FIELDPUT("NOME","")
ELSE
  aPRO:=PEGMS01(AllTrim(SELF:SERVER:FIELDGET("APLICACAO")))
  IF aPRO[1]=.T.
     oJAN:SERVER:FIELDPUT("NOME",APRO[2])
   ENDIF
ENDIF
	
oJAN:SERVER:FIELDPUT("RASTRO",SELF:SERVER:FIELDGET("RASTRO"))
oJAN:SERVER:FIELDPUT("QTAMO",SELF:OSFJRIMI:SERVER:FIELDGET("QTITEM"))
IF Empty(oJAN:SERVER:FIELDGET("QTAMO"))
   oJAN:SERVER:FIELDPUT("QTAMO",SELF:SERVER:FIELDGET("QTAMO"))	
ENDIF
oJAN:SHOW()		

METHOD etiqmat( ) 
LOCAL oJAN AS ETIQ01
IF Empty(SELF:SERVER:FIELDGET("LAUDOF"))
   alert("Laudo Nao fornecido")
   RETU
ENDIF
oJAN:=ETIQ01{SELF}	
oJAN:nrirm:=SELF:SERVER:FIELDGET("RIRM")
oJAN:CRASTRO:=SELF:SERVER:FIELDGET("RASTRO")
OJAN:MDATA:=SELF:SERVER:FIELDGET("DATAL")
oJAN:SHOW()

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("INSTRU"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Instrucao  Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()
	

METHOD gobottom() 
	SUPER:gobottom()
	SELF:DESABI()	

METHOD GOTOP() 
	SUPER:GOTOP()
	SELF:DESABI()	

METHOD HABILI() 
	oCCEditar:ENABLE()
	oCCTabular:ENABLE()
	oCCLaudo:ENABLE()
	oCCAlterar:ENABLE()
	oCCRC:ENABLE()
	oCCTL:ENABLE()
//	oCCbuscarastro:ENABLE()
//	oCCbuscarirm:ENABLE()
	oCCpegamostra:ENABLE()
	oCCcriaitens:ENABLE()
	oCCdigcod:ENABLE()
	oCCdigdes:ENABLE()
	oCCdigapl:ENABLE()
	oCCchecknom:ENABLE()
//	oCCetiqlab:ENABLE()
	oCCcmdcert:ENABLE()
//	oCCfoto:ENABLE()
	oCCCHKTIPO:ENABLE()
	oCCsubchktip:ENABLE()
	oCCCHKens:ENABLE()
	oCCpegcla:ENABLE()
	oCCcmdbobina:Enable()
	oCCdigcod1:Enable()
//	oCCetiqIdent:ENAble()
//	oCCetiqmat:ENABLE()

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",4)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RIRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"RIRMI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJRIMI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRIMI,"RIRM")
SELF:oSFJRIMI:VIEWTABLE()
//SELF:oSFJRIMI:oDCTIPA:FillUsing(SELF:TABTIPA( ))
//SELF:OSFJRIMI:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

METHOD KEYFIND() 
	SUPER:KEYFIND()	
    SELF:DESABI()

METHOD Laudo( ) 
IF SELF:SERVER:FIELDGET("LLAUDO")
   alert("Laudo Já fornecido")
   RETU
ENDIF	
IF Empty(SELF:oSFJRIMI:FIELDGET("ENCO"))
   alert("Encontrado Nao Preenchido")
   RETU
ENDIF	
SELF:oSFJRIMI:server:FIELDPUT("LAUDO",SIMNAO(oSFJRIMI:server:FIELDGET("LAUDO"),{"A","R","C","E"}))


METHOD PEGAMOSTRA 
IF Empty(SELF:SERVER:INsp)
   alert("Tipo Inspeção Não Preenchido")
   RETU	
ENDIF	
alert("Imprimir Solicitação de Teste")	
IF SELF:SERVER:INSP="A"
   DO CASE
   	  CASE SELF:SERVER:QTDE<16
   	  	  SELF:SERVER:FIELDPUT("QTAMO",SELF:SERVER:QTDE)
   	  CASE SELF:SERVER:QTDE<281
   	  	  SELF:SERVER:FIELDPUT("QTAMO",20)
   	  CASE SELF:SERVER:QTDE<1201
   	  	  SELF:SERVER:FIELDPUT("QTAMO",47)
   	  CASE SELF:SERVER:QTDE<3201
   	  	  SELF:SERVER:FIELDPUT("QTAMO",53)
   	  CASE SELF:SERVER:QTDE<10001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",68)
   	  CASE SELF:SERVER:QTDE<35001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",77)
   	  CASE SELF:SERVER:QTDE<150001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",99)
   	  CASE SELF:SERVER:QTDE<500001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",119)
   	  OTHERWISE
   	  	  SELF:SERVER:FIELDPUT("QTAMO",142)
   ENDCASE	
ENDIF
IF SELF:SERVER:INSP="B"
   DO CASE
   	  CASE SELF:SERVER:QTDE<26
   	  	  SELF:SERVER:FIELDPUT("QTAMO",SELF:SERVER:QTDE)
   	  CASE SELF:SERVER:QTDE<281
   	  	  SELF:SERVER:FIELDPUT("QTAMO",32)
   	  CASE SELF:SERVER:QTDE<3201
   	  	  SELF:SERVER:FIELDPUT("QTAMO",68)
   	  CASE SELF:SERVER:QTDE<10001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",77)
   	  CASE SELF:SERVER:QTDE<35001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",96)
   	  CASE SELF:SERVER:QTDE<150001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",119)
   	  CASE SELF:SERVER:QTDE<500001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",143)
   	  OTHERWISE
   	  	  SELF:SERVER:FIELDPUT("QTAMO",169)
   ENDCASE		
ENDIF
IF SELF:SERVER:FIELDGET("CONTIG")	
  SELF:SERVER:FIELDPUT("QTAMO",SELF:SERVER:FIELDGET("QTAMO")*2)
ENDIF	
SELF:nQTDE:=SELF:SERVER:FIELDGET("QTAMO")
IF MDG("Marcar Quantidades Todos Itens")
   SELF:Alterar()
ENDIF	

METHOD pegcla( ) 
LOCAL aRETU AS ARRAY
IF Empty(SELF:SERVER:FIELDGET("CLASSI"))
   aRETU:=PEGMB01(SELF:SERVER:FIELDGET("NFORN"),ZCURINI,ZCURDIR)
   IF aRETU[1]	
   	  SELF:SERVER:FIELDPUT("CLASSI",aRETU[9])
   ENDIF	
	
ENDIF

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)      //5minx60seg
   SELF:DESABI()
    FabCenterWindow( SELF )
 RETURN SELF

METHOD RC() 
	LOCAL oJ01 AS J01
	oJ01:=J01{SELF}
	oJ01:SHOW()

METHOD SKIPNEXT() 
	SUPER:SkipNext()
	SELF:DESABI()	

METHOD SKIPPREVIOUS() 
	SUPER:SkipPrevious()
	SELF:DESABI()	

METHOD subchktip() 
	LOCAL cTIPA AS STRING
    SELF:oSFJRIMI:server:gotop()
    WHILE ! SELF:oSFJRIMI:SERVER:EOF	
    	IF Empty(SELF:oSFJRIMI:SERVER:FIELDGET("TIPA"))
    	   cTIPA:=TIPAR(SELF:oSFJRIMI:SERVER:FIELDGET("ESPE"))
           IF ! Empty(cTIPA)
              SELF:oSFJRIMI:SERVER:FIELDPUT("TIPA",cTIPA)
           ENDIF
        ENDIF	
    	IF Empty(SELF:oSFJRIMI:SERVER:FIELDGET("PULAAPU"))	
    	   IF AllTrim(SELF:oSFJRIMI:SERVER:FIELDGET("ENCO"))="Conforme Certificado"
              SELF:oSFJRIMI:SERVER:FIELDPUT("PULAAPU","S")
          ENDIF	
    	ENDIF
        SELF:oSFJRIMI:SERVER:Skip()
    ENDDO
	

METHOD Tabular( ) 
SELF:oSFJRIMI:Viewtable()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJRIMI:Server:COMMIT()


METHOD TL() 
LOCAL oJ02 AS J02
LOCAL ADAD AS ARRAY
LOCAL oSERVER AS USEREDE
LOCAL cCODIGO AS STRING
LOCAL cVORETRUN,cPARAM AS STRING
LOCAL nFout AS PTR

//LOCAL oRUN AS APP
IF Empty(SELF:SERVER:FIELDGET("CLASSI"))
   alert("Fornecedor Nao Classificado")
   RETU	
ENDIF
IF SELF:SERVER:FIELDGET("LLAUDO") .AND. ! Empty(SELF:SERVER:FIELDGET("LAUDOF"))
   alert("Laudo Já fornecido")
    IF Empty(SELF:oSFJRIMI:SERVER:FIELDGET("LAUDO"))
      alert("Laudo Item Nao Preenchido")
      SELF:SERVER:FIELDPUT("LAUDOF"," ")
      SELF:SERVER:FIELDPUT("LLAUDO",.F.)
      RETU
   ENDIF
   IF Empty(SELF:SERVER:FIELDGET("DATAL"))
      SELF:SERVER:FIELDPUT("DATAL",SELF:SERVER:FIELDGET("DATA"))
   ENDIF
   RETU
ENDIF	
IF Empty(SELF:SERVER:FIELDGET("DATAL"))
   IF Today()-SELF:SERVER:FIELDGET("DATA")>30
   	  SELF:SERVER:FIELDPUT("DATAL",SELF:SERVER:FIELDGET("DATA"))
   ELSE
      SELF:SERVER:FIELDPUT("DATAL",Today())
   ENDIF
ENDIF
SELF:oSFJRIMI:server:gotop()
WHILE ! SELF:oSFJRIMI:server:eof
	IF Empty(SELF:oSFJRIMI:SERVER:FIELDGET("ENCO"))
	   alert("Encontrado Nao Preenchido")
	   RETU
    ENDIF		
	IF Empty(SELF:oSFJRIMI:SERVER:FIELDGET("LAUDO"))
	   alert("Laudo Nao Preenchido")
	   RETU
    ENDIF		
	SELF:oSFJRIMI:SERVER:Skip()
ENDDO	
oJ02:=J02{SELF}
oJ02:SHOW()
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO=0
   oSERVER:GoTop()
   IF oSERVER:SEEK(SELF:SERVER:FIELDGET("CRM"))
   	  oSERVER:FIELDPUT("LAUDO",SELF:SERVER:FIELDGET("LAUDOF"))
   ENDIF
   oSERVER:CLOSE()
ENDIF
SELF:server:FIELDPUT("LLAUDO",.T.)	
SELF:oSFJRIMI:SERVER:Commit()
SELF:SERVER:Commit()
IF MDG("Imprimir RIRM","Imprimir")
//   cSTRIMP:="CARETRUN.EXE "+PEGINIVAL(ZCURINI,"RET_CRM08","CAMINHO")
//   cSTRIMP+=" -X"
//   cSTRIMP+=" "+Str(SELF:SERVER:FIELDGET("RIRM"))
//   cSTRIMP+=" "+Str(SELF:SERVER:FIELDGET("RIRM"))
//   cSTRIMP+=" 1"
//   cSTRIMP+=" Z"
//   oRUN:=APP{SELF}
//   oRUN:RUN(cSTRIMP)

   cVORETRUN:=PEGINIVAL(ZCURINI,"PATH","VORETRUN")+ "VORETRUN"
	cPARAM:=PEGINIVAL(ZCURINI,"RET_CRM08","CAMINHO")+"$NNNNNSSSN$#MANA5CRM#"
	nFout := ShellExecute(SELF:owner:handle(),String2Psz("open"),String2Psz(cVORETRUN),String2Psz(cPARAM),String2Psz(""),1)
    ShellExecuteErro(nFout) 
//     hwnd,   lpOperation,  lpFile,   lpParameters,   lpDirectory,    SW_SHOWNORMAL = 1//fica no diretorio atual ondes estao os dbfs

ENDIF	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("DESENHO"))
CMD3L(cCODIGO,"D")


END CLASS
