CLASS XJRIST INHERIT JRIST

METHOD APPEND() 
	LOCAL nRIST AS DWORD
	LOCAL oJINC AS JRIrmINC
	LOCAL cRASTRO AS STRING
	LOCAL cLOTECRT AS STRING
	LOCAL aRASTRO AS ARRAY
	LOCAL lRASTRO AS LOGIC

SELF:DESABI()		
IF ! entramenu("CRM",22)
	RETU SELF
ENDIF

aRASTRO:={0,""}


//local nRIST as dword
oJINC:=JRIrmINC{SELF}
oJINC:SHOW()
IF ! OJINC:LRETU
   RETURN SELF
ENDIF	

IF oJINC:ARETU[15]="T"   
  NOP
ELSE
	alert("RIST so servicos")
   RETURN SELF	
ENDIF	

lRASTRO:=.F.
Crastro:=oJINC:ARETU[2]
IF Empty(CRASTRO)
   aRASTRO:=NOVORASTRO()
   cRASTRO:=ARASTRO[2]
   lRASTRO:=.T.	
ENDIF	

CLOTECRT:=oJINC:ARETU[17]
IF Empty(clotecrt)
   cLOTECRT:=NOVOLOTE(oJINC:ARETU[6],oJINC:ARETU[3])	
ENDIF	


SELF:server:setorder(1)
SELF:server:gobottom()
nRIST:=SELF:Server:RIST
nRIST++
SUPER:append()
SELF:SERVER:FIELDPUT("RIST",nRIST)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("RASTRO",cRASTRO)
SELF:SERVER:FIELDPUT("CLASSI",oJINC:ARETU[1])
SELF:SERVER:FIELDPUT("NFORN",oJINC:ARETU[6])
SELF:SERVER:FIELDPUT("FORNE",oJINC:ARETU[7])
SELF:SERVER:FIELDPUT("UNID",oJINC:ARETU[14])
SELF:SERVER:FIELDPUT("APLICACAO",oJINC:ARETU[16])
SELF:SERVER:FIELDPUT("os",oJINC:ARETU[8])
SELF:SERVER:FIELDPUT("NF",oJINC:ARETU[9])
SELF:SERVER:FIELDPUT("NFB",oJINC:ARETU[10])
SELF:SERVER:FIELDPUT("DATANF",oJINC:ARETU[11])
SELF:SERVER:FIELDPUT("CERT",oJINC:ARETU[13])
SELF:SERVER:FIELDPUT("QTDE",oJINC:ARETU[12])
SELF:SERVER:FIELDPUT("clotecrt",CLOTECRT)



//SELF:SERVER:FIELDPUT("DESENHO",oJINC:ARETU[3])
SELF:SERVER:FIELDPUT("DENO",oJINC:ARETU[4])
SELF:SERVER:FIELDPUT("CODIGO",oJINC:ARETU[5]) //INSTRUCAO ETI








SELF:SERVER:Commit()
SELF:SERVER:gobottom()
SELF:PEGTIPTRA( )
SELF:chkcli(.F. )
IF lRASTRO
   GRAVARASTRO(aRASTRO[1],0,nRIST,0,oJINC:ARETU[3],"")	
ENDIF	
SELF:criaitens()
RETURN SELF	
	


METHOD BUSCAAVANCADA() 
	SUPER:BUSCAAVANCADA()
	SELF:DESABI()	

METHOD buscaRiST(oOWNER) 
//LOCAL oBUSCA AS xBUSCA
//oBUSCA:=xBUSCA{oOWNER,"Localizar","Digite RIST"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(Val(oBUSCA:cBUSCA))
//ENDIF
SELF:KEYFIND()
SELF:DESABI()

METHOD chkcli(lPERG ) 
LOCAL aRET AS ARRAY	
LOCAL oBUSCA AS xBUSCA
IF ValType(lPERG)#"L"
   lPERG:=.T.	
ENDIF
IF Empty(SELF:SERVER:FIELDGET("NCLI"))	
   aRET:=PEGMS01(SELF:SERVER:FIELDGET("APLICACAO"))		
   IF aRET[1]
      IF ! Empty(aRET[4])
	     SELF:SERVER:FIELDPUT("NCLI",aRET[4])
      ENDIF		
   ENDIF
ENDIF
IF lPERG
   IF Empty(SELF:SERVER:FIELDGET("NCLI"))
      oBUSCA:=xBUSCA{SELF,"Digitar","Digite o Numero do Cliente"}
      oBUSCA:lMES:=.T.
      oBUSCA:SHOW()
      IF oBUSCA:lOK
         SELF:SERVER:FIELDPUT("NCLI",Val(oBUSCA:cBUSCA))
      ENDIF
   ENDIF
ENDIF
IF Empty(SELF:SERVER:FIELDGET("CLIENTE")) .AND. (SELF:SERVER:FIELDGET("NCLI"))>0
    aRET:=PEGMA01(SELF:SERVER:FIELDGET("NCLI"),ZCURINI,ZCURDIR)
    IF aRET[1]=.T.
       SELF:SERVER:FIELDPUT("CLIENTE",aRET[2])
    ENDIF
ENDIF

	



METHOD CHKens( ) 
SELF:SERVER:GOTOP()
SELF:SERVER:SEEK(12705)
WHILE ! SELF:SERVER:EOF
	IF Year(SELF:SERVER:FILEGET("data"))=2004
	   IF Empty(SELF:oSFJRISTI:SERVER:FIELDGET("ITEM"))
//	   	  AltD()
  	      SELF:criaitens()	
  	   ENDIF
    ENDIF
    SELF:SERVER:SKIP()	
ENDDO		
SELF:SERVER:GOTOP()		

METHOD CHKTIPO( ) 
SELF:SERVER:GOTOP()
WHILE ! SELF:SERVER:EOF
	SELF:SUBCHKTIP()
    SELF:SERVER:SKIP()	
ENDDO		
SELF:SERVER:GOTOP()	

METHOD cmdbobina( ) 
SELF:oSFJRISTI:ViewTABLE()
SELF:oSFJRISTI:server:FIELDPUT("ENCO","Executado na Liberacao da Bobina")		
SELF:oSFJRISTI:SERVER:FIELDPUT("PULAaPU","S")
SELF:oSFJRISTI:SERVER:FIELDPUT("LAUDO","S")
IF !  SELF:oSFJRISTI:SERVER:EOF
   SELF:oSFJRISTI:SERVER:Skip()
ENDIF	
	

METHOD cmdcert( ) 
SELF:oSFJRISTI:ViewTABLE()
SELF:oSFJRISTI:server:FIELDPUT("ENCO","Conforme Certificado")		
SELF:oSFJRISTI:SERVER:FIELDPUT("PULAaPU","S")
SELF:oSFJRISTI:SERVER:FIELDPUT("LAUDO","S")
IF !  SELF:oSFJRISTI:SERVER:EOF
   SELF:oSFJRISTI:SERVER:Skip()
ENDIF	



METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()
SELF:DESABI()

METHOD cmdEnvio( ) 
IF SELF:SERVER:FIELDGET("LLAUDO")
   alert("Laudo Já fornecido")
   RETU
ENDIF		
SELF:oSFJRISTI:server:FIELDPUT("LAUDO","E")
SELF:oSFJRISTI:server:FIELDPUT("DATAENV",Today())
SELF:oSFJRISTI:server:FIELDPUT("HORAENV",Time())

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()
	SELF:DESABI()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("CRM","RIST")	


METHOD cmdinicia( ) 
LOCAL cCODIGO AS STRING	
LOCAL aRETU AS ARRAY
LOCAL oJAN AS Xjensrx
IF SELF:SERVER:FIELDGET("LLAUDO") .AND. ! Empty(SELF:SERVER:FIELDGET("LAUDOF"))
   IF Empty(SELF:oSFJRISTI:SERVER:FIELDGET("LAUDO"))
      alert("Laudo Item Nao Preenchido")
      SELF:SERVER:FIELDPUT("LAUDOF"," ")
      SELF:SERVER:FIELDPUT("LLAUDO",.F.)
      RETU
   ENDIF	
   alert("Laudo Já fornecido")
   IF Empty(SELF:SERVER:FIELDGET("DATAL"))
      SELF:SERVER:FIELDPUT("DATAL",SELF:SERVER:FIELDGET("DATA"))
   ENDIF
   RETU
ENDIF		


aRETU:=TEMCHKCERT("T",SELF:SERVER:FIELDGET("CODIGO"))
IF aRETU[1]
   oJAN:=Xjensrx{SELF,aRETU[2],SELF:SERVER:FIELDGET("CODIGO")}
   oJAN:SHOW()
   IF .not.oJAN:LOK
     RETU
   ENDIF
ENDIF

SELF:HABILI()
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("APLICACAO"))
IF CMDGP12(cCODIGO,"V")="V"
   alert("Marcada Item Critico")	
ENDIF	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
IF CMDGP12(cCODIGO,"V")="V"
   alert("Marcada Item Critico")	
ENDIF	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("APLICACAO"))
aRETU:=CMD3L(cCODIGO,"V")
IF aRETU[1]
   alert(TEXTO3L(aRETU))
ELSE
   cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
   aRETU:=CMD3L(cCODIGO,"V")
   IF aRETU[1]
      alert(TEXTO3L(aRETU))
   ENDIF	
ENDIF
IF SELF:SERVER:FIELDGET("CLOTECRT")="0" .OR. SELF:SERVER:FIELDGET("CLOTECRT")="P"
   alert("Realizar Dimensional/Testes Fisicos/Comparacao Quimica")	
ENDIF

METHOD criaitens( ) 
LOCAL oARQ AS USEREDE
LOCAL cCODIGO AS STRING
LOCAL nRIST AS DWORD
LOCAL aDAD AS ARRAY
nRIST:=SELF:SERVER:FIELDGET("RIST")
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
SELF:oSFJRISTI:SERVER:SUSPENDNOTIFICATION()

   aDAD:={zCURINI,"MP03I.DBF",zCURDIR}
   oARQ:=USEREDE{aDAD}
   IF oARQ:nERRO=0
      oARQ:GOTOP()
      oARQ:SEEK(cCODIGO)
      WHILE AllTrim(cCODIGO)=AllTrim(oARQ:FIELDGET("CODIGO")) .AND. ! oARQ:EOF
            SELF:oSFJRISTI:SERVER:APPEND()
		    SELF:oSFJRISTI:SERVER:FIELDPUT("RIST",nRIST)
		    SELF:oSFJRISTI:SERVER:FIELDPUT("ITEM",oARQ:FIELDGET("ITEM"))
		    SELF:oSFJRISTI:SERVER:FIELDPUT("ESPE",oARQ:FIELDGET("ESPE"))
		    SELF:oSFJRISTI:SERVER:FIELDPUT("ENCO",oARQ:FIELDGET("ENCO"))
		    oARQ:SKIP()
       ENDDO
	   oARQ:CLOSE()
	ENDIF

SELF:oSFJRISTI:SERVER:Commit()
SELF:oSFJRISTI:SERVER:resetnotification()
SELF:oSFJRISTI:SERVER:notify(notifyfilechange)		

METHOD DELETE() 
	SELF:DESABI()	
IF ! entramenu("CRM",22)
	RETU SELF
ENDIF
IF SELF:SERVER:FIELDGET("CRM")>0	
   alert("Exclusao Somente Por CRM")	
   RETU SELF
ENDIF
IF ! MDG("Apagar Registro") .AND. SELF:server:LockCurrentRecord()
	RETU SELF
ENDIF	
GRAVALOG(SELF:SERVER:RIST,"DEL","RIST")	

SELF:oSFJRISTI:server:GOTOP()	
WHILE ! oSFJRISTI:server:EOF
 	SELF:oSFJRISTI:server:delete()
 	SELF:oSFJRISTI:Skip()
ENDDO	
SELF:server:delete()
SELF:server:unlock()
SELF:server:skip(-1)
IF SELF:SERVER:BOF
   SELF:SERVER:GOTOP()
ENDIF	
SELF:oSFJRISTI:Browser:REFRESH()
//SELF:oSFJRISTI:SERVER:SUSPENDNOTIFICATION()
//SELF:oSFJRISTI:SERVER:resetnotification()
//SELF:oSFJRISTI:SERVER:notify(notifyfilechange)	



METHOD DESABI() 
	oCCEditar:DISABLE()
	oCCTabular:DISABLE()
	oCCLaudo:DISABLE()
//	oCCAlterar:DISABLE()
//	oCCRC:DISABLE()
	oCCTL:DISABLE()
//	oCCbuscarastro:DISABLE()
//	oCCbuscarirm:DISABLE()
	oCCpegamostra:DISABLE()
	oCCcriaitens:DISABLE()
	oCCdigcod:DISABLE()
	oCCdigdes:DISABLE()
	oCCdigapl:DISABLE()
//	oCCchecknom:DISABLE()
//	oCCetiqlab:DISABLE()
	oCCcmdcert:DISABLE()
	OCCCHKCLI:Disable()
	OCCCMDENVIO:Disable()
//	oCCfoto:DISABLE()
	oCCCHKTIPO:DISABLE()
	oCCsubchktip:DISABLE()
	oCCCHKens:DISABLE()
	oCCpegcla:DISABLE()
	oCCcmdbobina:Disable()
	oCCdigapl1:Disable()
	oCCPEGTIPTRA:Disable()
//	oCCetiqIdent:Disable()
//	oCCetiqmat:DISABLE()

METHOD digAPL(oOWNER) 
LOCAL oBUSCA AS xBUSCA
IF ! Empty(SELF:SERVER:FIELDGET("APLICACAO"))
   RETU
ENDIF
oBUSCA:=xBUSCA{oOWNER,"Digitar","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:FIELDPUT("APLICACAO",oBUSCA:cBUSCA)
ENDIF

METHOD digapl1( ) 
LOCAL oESC AS XESCCOD	
IF ! Empty(SELF:SERVER:FIELDGET("APLICACAO"))
   RETU
ENDIF
oESC:=XESCCOD{SELF,"MS01.DBF"}
oESC:SHOW()	
IF Oesc:lok
   SELF:SERVER:FIELDPUT("APLICACAO",oESC:CODIGO)
ENDIF	

METHOD digcod(oOWNER) 
LOCAL oBUSCA AS xBUSCA
IF ! Empty(SELF:SERVER:FIELDGET("CODIGO")) .AND. SELF:SERVER:FIELDGET("CLOTECRT")<>"P"
   RETU
ENDIF
oBUSCA:=xBUSCA{oOWNER,"Digitar","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:FIELDPUT("CODIGO",oBUSCA:cBUSCA)
ENDIF

METHOD digDES(oOWNER) 
LOCAL oBUSCA AS xBUSCA
IF ! Empty(SELF:SERVER:FIELDGET("DENO"))
   RETU
ENDIF
oBUSCA:=xBUSCA{oOWNER,"Digitar","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:FIELDPUT("DENO",oBUSCA:cBUSCA)
ENDIF

METHOD Editar( ) 
SELF:oSFJRISTI:ViewForm()

METHOD etiqIdent( ) 
LOCAL oJAN AS ETIQ02
IF Empty(SELF:SERVER:FIELDGET("LAUDOF"))
   alert("Laudo Nao fornecido")
   RETU
ENDIF
oJAN:=ETIQ02{SELF}	
oJAN:ncrm:=SELF:SERVER:FIELDGET("CRM")
oJAN:cRESPO:=SELF:SERVER:FIELDGET("RESPO")
oJAN:IMPORTAR()
oJAN:SHOW()		

METHOD etiqlab( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aPRO AS ARRAY
LOCAL oJAN AS ETIQ03
aDAD:={zCURINI,"CRME03.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oJAN:=ETIQ03{SELF,,oSERVER}
oJAN:SERVER:FIELDPUT("ESPE",SELF:oSFJRISTI:SERVER:FIELDGET("ESPE"))
oJAN:SERVER:FIELDPUT("USUARIO",ZUSER)
oJAN:SERVER:FIELDPUT("SETOR","Recebimento")
oJAN:SERVER:FIELDPUT("DATA",Today())
oJAN:SERVER:FIELDPUT("CODIGO",SELF:SERVER:FIELDGET("APLICACAO"))
oJAN:SERVER:FIELDPUT("REFNUM",SELF:SERVER:FIELDGET("RIST"))
oJAN:SERVER:FIELDPUT("NCLI",SELF:SERVER:FIELDGET("NCLI"))
oJAN:SERVER:FIELDPUT("CLIENTE",SELF:SERVER:FIELDGET("CLIENTE"))
IF At("/",SELF:SERVER:FIELDGET("APLICACAO"))>0
   oJAN:SERVER:FIELDPUT("NOME","")
ELSE
  aPRO:=PEGMS01(AllTrim(SELF:SERVER:FIELDGET("APLICACAO")))
  IF aPRO[1]=.T.
     oJAN:SERVER:FIELDPUT("NOME",APRO[2])
  ENDIF
ENDIF
oJAN:SERVER:FIELDPUT("RASTRO",SELF:SERVER:FIELDGET("RASTRO"))
oJAN:SERVER:FIELDPUT("QTAMO",SELF:SERVER:FIELDGET("QTAMO"))
oJAN:SHOW()		

METHOD etiqmat( ) 
LOCAL oJAN AS ETIQ01
IF Empty(SELF:SERVER:FIELDGET("LAUDOF"))
   alert("Laudo Nao fornecido")
   RETU
ENDIF
oJAN:=ETIQ01{SELF}	
oJAN:nrirm:=SELF:SERVER:FIELDGET("RIST")
oJAN:CRASTRO:=SELF:SERVER:FIELDGET("RASTRO")
OJAN:MDATA:=SELF:SERVER:FIELDGET("DATAL")
oJAN:SHOW()	

METHOD foto( ) 
LOCAL oFOTOVIEW AS fotoview	
LOCAL cCODIGO AS STRING
cCODIGO:=TIRAOUT(StrTran(AllTrim(SELF:SERVER:FIELDGET("APLICACAO"))," ",""))
IF Empty(cCODIGO)	
   alert("Codigo Aplicacao Nao Preenchido")	
   RETU
ENDIF	
OFOTOVIEW:=fotoview{SELF,ZDIRFOTO+cCODIGO+".JPG"}
OFOTOVIEW:SHOW()
	

METHOD gobottom() 
	SUPER:gobottom()
	SELF:DESABI()	

METHOD GOTOP() 
	SUPER:GOTOP()
	SELF:DESABI()	

METHOD HABILI() 
	oCCEditar:ENABLE()
	oCCTabular:ENABLE()
	oCCLaudo:ENABLE()
//	oCCAlterar:ENABLE()
	oCCRC:ENABLE()
	oCCTL:ENABLE()
//	oCCbuscarastro:ENABLE()
//	oCCbuscarirm:ENABLE()
	oCCpegamostra:ENABLE()
	oCCcriaitens:ENABLE()
	oCCdigcod:ENABLE()
	oCCdigdes:ENABLE()
	oCCdigapl:ENABLE()
//	oCCchecknom:ENABLE()
//	oCCetiqlab:ENABLE()
	oCCcmdcert:ENABLE()
	OCCCHKCLI:ENABLE()
	OCCCMDENVIO:ENABLE()
//	oCCfoto:ENABLE()
	oCCCHKTIPO:ENABLE()
	oCCsubchktip:ENABLE()
	oCCCHKens:ENABLE()
	oCCpegcla:ENABLE()	
	oCCcmdbobina:Enable()
	oCCdigapl1:Enable()
	oCCPEGTIPTRA:Enable()
//	oCCetiqIdent:ENable()
//	oCCetiqmat:ENABLE()

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("CRM",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RIST.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"RISTI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJRISTI:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJRISTI,"RIST")
SELF:oSFJRISTI:VIEWTABLE()
//SELF:OSFJRISTI:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

METHOD KEYFIND() 
	SUPER:KEYFIND()	
    SELF:DESABI()

METHOD Laudo( ) 
IF SELF:SERVER:FIELDGET("LLAUDO")
   alert("Laudo Já fornecido")
   RETU
ENDIF	
IF Empty(SELF:oSFJRISTI:FIELDGET("ENCO"))
   alert("Encontrado Nao Preenchido")
   RETU
ENDIF	
SELF:oSFJRISTI:server:FIELDPUT("LAUDO",SIMNAO(oSFJRISTI:server:FIELDGET("LAUDO"),{"A","R","C","E"}))	
SELF:oSFJRISTI:Server:FIELDPUT("DATALAU",Today())



METHOD PEGAMOSTRA 
IF Empty(SELF:SERVER:FIELDGET("INSP"))
   alert("Tipo Inspeção Não Preenchido")
   RETU	
ENDIF	
alert("Imprimir Solicitação de Teste")
IF SELF:SERVER:INSP="A"
   DO CASE
   	  CASE SELF:SERVER:QTDE<16
   	  	  SELF:SERVER:FIELDPUT("QTAMO",SELF:SERVER:QTDE)
   	  CASE SELF:SERVER:QTDE<281
   	  	  SELF:SERVER:FIELDPUT("QTAMO",20)
   	  CASE SELF:SERVER:QTDE<1201
   	  	  SELF:SERVER:FIELDPUT("QTAMO",47)
   	  CASE SELF:SERVER:QTDE<3201
   	  	  SELF:SERVER:FIELDPUT("QTAMO",53)
   	  CASE SELF:SERVER:QTDE<10001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",68)
   	  CASE SELF:SERVER:QTDE<35001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",77)
   	  CASE SELF:SERVER:QTDE<150001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",99)
   	  CASE SELF:SERVER:QTDE<500001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",119)
   	  OTHERWISE
   	  	  SELF:SERVER:FIELDPUT("QTAMO",142)
   ENDCASE	
ENDIF
IF SELF:SERVER:INSP="B"
   DO CASE
   	  CASE SELF:SERVER:QTDE<26
   	  	  SELF:SERVER:FIELDPUT("QTAMO",SELF:SERVER:QTDE)
   	  CASE SELF:SERVER:QTDE<281
   	  	  SELF:SERVER:FIELDPUT("QTAMO",32)
   	  CASE SELF:SERVER:QTDE<3201
   	  	  SELF:SERVER:FIELDPUT("QTAMO",68)
   	  CASE SELF:SERVER:QTDE<10001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",77)
   	  CASE SELF:SERVER:QTDE<35001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",96)
   	  CASE SELF:SERVER:QTDE<150001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",119)
   	  CASE SELF:SERVER:QTDE<500001
   	  	  SELF:SERVER:FIELDPUT("QTAMO",143)
   	  OTHERWISE
   	  	  SELF:SERVER:FIELDPUT("QTAMO",169)
   ENDCASE		
ENDIF
IF SELF:SERVER:FIELDGET("CONTIG")	
  SELF:SERVER:FIELDPUT("QTAMO",SELF:SERVER:FIELDGET("QTAMO")*2)
ENDIF	

METHOD pegcla( ) 
LOCAL aRETU AS ARRAY
IF Empty(SELF:SERVER:FIELDGET("CLASSI"))
   aRETU:=PEGMB01(SELF:SERVER:FIELDGET("NFORN"),ZCURINI,ZCURDIR)
   IF aRETU[1]	
   	  SELF:SERVER:FIELDPUT("CLASSI",aRETU[9])
   ENDIF	
	
ENDIF

METHOD PEGTIPTRA( ) 
LOCAL aDAD AS ARRAY
aDAD:=PEGMP03(AllTrim(SELF:SERVER:APLICACAO),zCURINI,zCURDIR)
IF aDAD[1]
   SELF:SERVER:TIPO:=aDAD[5]
ENDIF


METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)      //5minx60seg
   SELF:DESABI()
    FabCenterWindow( SELF )
 RETURN SELF

METHOD RC() 
	LOCAL oJ01 AS J01
	oJ01:=J01{SELF}
	oJ01:SHOW()

METHOD SKIPNEXT() 
	SUPER:SkipNext()
	IF Empty(SELF:SERVER:FIELDGET("TIPO"))
		SELF:PEGTIPTRA()
	ENDIF	
	SELF:chkcli(.F. )
	SELF:DESABI()	

METHOD SKIPPREVIOUS() 
	SUPER:SkipPrevious()
    IF Empty(SELF:SERVER:FIELDGET("TIPO"))
		SELF:PEGTIPTRA()
	ENDIF	
	SELF:chkcli(.F. )
	SELF:DESABI()	

METHOD subchktip 
LOCAL cTIPA AS STRING	
    SELF:oSFJRISTI:server:gotop()
    WHILE ! SELF:oSFJRISTI:SERVER:EOF	
    	IF Empty(SELF:oSFJRISTI:SERVER:FIELDGET("TIPA"))
    	   cTIPA:=TIPAR(SELF:oSFJRISTI:SERVER:FIELDGET("ESPE"))
           IF ! Empty(cTIPA)
              SELF:oSFJRISTI:SERVER:FIELDPUT("TIPA",cTIPA)
           ENDIF
        ENDIF	
    	IF Empty(SELF:oSFJRISTI:SERVER:FIELDGET("PULAAPU"))	
    	   IF AllTrim(SELF:oSFJRISTI:SERVER:FIELDGET("ENCO"))="Conforme Certificado"
              SELF:oSFJRISTI:SERVER:FIELDPUT("PULAaPU","S")
          ENDIF	
    	ENDIF
	
        SELF:oSFJRISTI:SERVER:Skip()
    ENDDO


METHOD Tabular( ) 
SELF:oSFJRISTI:ViewTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJRISTI:SERVER:COMMIT()


METHOD TL() 
LOCAL oJ02 AS J02
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aRETU AS ARRAY
LOCAL cCODIGO AS STRING
//LOCAL oRUN AS APP
LOCAL cVORETRUN,cPARAM AS STRING
LOCAL nFout AS PTR
IF Empty(SELF:SERVER:FIELDGET("CLASSI"))
   alert("Fornecedor Nao Classificado")
   RETU	
ENDIF


IF SELF:SERVER:FIELDGET("LLAUDO") .AND. ! Empty(SELF:SERVER:FIELDGET("LAUDOF"))
   IF Empty(SELF:oSFJRISTI:SERVER:FIELDGET("LAUDO"))
      alert("Laudo Item Nao Preenchido")
      SELF:SERVER:FIELDPUT("LAUDOF"," ")
      SELF:SERVER:FIELDPUT("LLAUDO",.F.)
      RETU
   ENDIF	
   alert("Laudo Já fornecido")
   IF Empty(SELF:SERVER:FIELDGET("DATAL"))
      SELF:SERVER:FIELDPUT("DATAL",SELF:SERVER:FIELDGET("DATA"))
   ENDIF
   RETU
ENDIF	
IF Empty(SELF:SERVER:FIELDGET("DATAL"))
   IF Today()-SELF:SERVER:FIELDGET("DATA")>30
   	  SELF:SERVER:FIELDPUT("DATAL",SELF:SERVER:FIELDGET("DATA"))
   ELSE
      SELF:SERVER:FIELDPUT("DATAL",Today())
   ENDIF
ENDIF
SELF:oSFJRISTI:server:gotop()
WHILE ! SELF:oSFJRISTI:server:eof
	IF Empty(SELF:oSFJRISTI:SERVER:FIELDGET("ENCO"))
	   alert("Encontrado Nao Preenchido")
	   RETU
    ENDIF		
	IF Empty(SELF:oSFJRISTI:SERVER:FIELDGET("LAUDO"))
	   alert("laudo Nao Preenchido")
	   RETU
    ENDIF		
	SELF:oSFJRISTI:SERVER:Skip()
ENDDO	
oJ02:=J02{SELF}
oJ02:SHOW()
aDAD:={zCURINI,"CRM.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO=0
   oSERVER:GoTop()
   IF oSERVER:SEEK(SELF:SERVER:FIELDGET("CRM"))
   	  oSERVER:FIELDPUT("LAUDO",SELF:SERVER:FIELDGET("LAUDOF"))
   	  oSERVER:FIELDPUT("NIVEL",SELF:SERVER:FIELDGET("NIVEL"))	
   	  oSERVER:FIELDPUT("INSP",SELF:SERVER:FIELDGET("INSP"))	
   ENDIF
   oSERVER:CLOSE()
ENDIF
SELF:server:FIELDPUT("LLAUDO",.T.)
SELF:SERVER:COMMIT()
SELF:oSFJRISTI:SERVER:Commit()
IF MDG("Imprimir RIST","Imprimir")
 //  cSTRIMP:="CARETRUN.EXE "+PEGINIVAL(ZCURINI,"RET_CRM07","CAMINHO")
//   cSTRIMP+=" -X"
//   cSTRIMP+=" "+Str(SELF:SERVER:FIELDGET("RIST"))
 //  cSTRIMP+=" "+Str(SELF:SERVER:FIELDGET("RIST"))
//   cSTRIMP+=" 1"
//   cSTRIMP+=" Z"
 //  oRUN:=APP{SELF}
  //  oRUN:RUN(cSTRIMP)
  cVORETRUN:=PEGINIVAL(ZCURINI,"PATH","VORETRUN")+ "VORETRUN"
	cPARAM:=PEGINIVAL(ZCURINI,"RET_CRM07","CAMINHO")+"$NNNNNSSSN$#MANA5CRM#"
	nFout := ShellExecute(SELF:owner:handle(),String2Psz("open"),String2Psz(cVORETRUN),String2Psz(cPARAM),String2Psz(""),1)
    ShellExecuteErro(nFout) 
//     hwnd,   lpOperation,  lpFile,   lpParameters,   lpDirectory,    SW_SHOWNORMAL = 1//fica no diretorio atual ondes estao os dbfs

ENDIF	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("APLICACAO"))
aRETU:=CMD3L(cCODIGO,"D")
IF ! ARETU[1]
   cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
   aRETU:=CMD3L(cCODIGO,"D")
ENDIF


END CLASS
