CLASS ZMAIL INHERIT JMAIL
	EXPORT cCURDIR,cCURINI,cUSER
	

CONSTRUCTOR(oOWNER,oSERVER,cINI,cDIR,cUSER,lENCERRA,cHELP) 	
SUPER(oOWNER,,oSERVER)
SELF:CCURDIR:=cDIR
SELF:CCURINI:=cINI
SELF:CUSER:=cUSER
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SERVER:GOTOP()
IF ValType(lENCERRA)#"L"
   lENCERRA:=.T.	
ENDIF	
IF ValType(cHELP)="C"
   SELF:HelpDisplay:=HelpDisplay{cHELP}
ELSE
   SELF:oCCAjuda:DISABLE()
ENDIF	
IF SELF:SERVER:EOF .AND. lENCERRA
   SELF:SERVER:CLOSE()	
   SELF:EndWindow()
ENDIF	
SELF:SHOW(SHOWZOOMED)	


END CLASS
