#region DEFINES
STATIC DEFINE JMAILNEW_AJUDA := 119
STATIC DEFINE JMAILNEW_ASSUNTO := 114
STATIC DEFINE JMAILNEW_DATA := 110
STATIC DEFINE JMAILNEW_DE := 112
STATIC DEFINE JMAILNEW_DESTINO := 113
STATIC DEFINE JMAILNEW_ERRO := 109
STATIC DEFINE JMAILNEW_HORA := 111
STATIC DEFINE JMAILNEW_NUMERO := 108
STATIC DEFINE JMAILNEW_OK := 116
STATIC DEFINE JMAILNEW_SC_ASSUNTO := 106
STATIC DEFINE JMAILNEW_SC_DATA := 102
STATIC DEFINE JMAILNEW_SC_DE := 104
STATIC DEFINE JMAILNEW_SC_DESTINO := 105
STATIC DEFINE JMAILNEW_SC_DESTINO1 := 117
STATIC DEFINE JMAILNEW_SC_ERRO := 101
STATIC DEFINE JMAILNEW_SC_HORA := 103
STATIC DEFINE JMAILNEW_SC_NUMERO := 100
STATIC DEFINE JMAILNEW_SC_TEXTO := 107
STATIC DEFINE JMAILNEW_TEXTO := 115
STATIC DEFINE JMAILNEW_X2 := 118
#endregion

PARTIAL CLASS JMAILNEW INHERIT DATADIALOG
PROTECT oDCSC_NUMERO AS FIXEDTEXT
PROTECT oDCSC_ERRO AS FIXEDTEXT
PROTECT oDCSC_DATA AS FIXEDTEXT
PROTECT oDCSC_HORA AS FIXEDTEXT
PROTECT oDCSC_DE AS FIXEDTEXT
PROTECT oDCSC_DESTINO AS FIXEDTEXT
PROTECT oDCSC_ASSUNTO AS FIXEDTEXT
PROTECT oDCSC_TEXTO AS FIXEDTEXT
PROTECT oDCNUMERO AS SINGLELINEEDIT
PROTECT oDCERRO AS SINGLELINEEDIT
PROTECT oDCDATA AS SINGLELINEEDIT
PROTECT oDCHORA AS SINGLELINEEDIT
PROTECT oDCDE AS SINGLELINEEDIT
PROTECT oDCDESTINO AS SINGLELINEEDIT
PROTECT oDCASSUNTO AS SINGLELINEEDIT
PROTECT oDCTEXTO AS MULTILINEEDIT
PROTECT oCCOK AS PUSHBUTTON
PROTECT oDCSC_DESTINO1 AS FIXEDTEXT
PROTECT oDCx2 AS FIXEDTEXT
PROTECT oCCAjuda AS PUSHBUTTON

// User code starts here (DO NOT remove this line)  ##USER##

METHOD Ajuda( ) 
   SELF:HelpDisplay:Show( "MailNovo" )	

ACCESS ASSUNTO
RETURN SELF:FieldGet( #ASSUNTO )

ASSIGN ASSUNTO( uValue )
SELF:FieldPut( #ASSUNTO , uValue )

ACCESS DATA
RETURN SELF:FieldGet( #DATA )

ASSIGN DATA( uValue )
SELF:FieldPut( #DATA , uValue )

ACCESS DE
RETURN SELF:FieldGet( #DE )

ASSIGN DE( uValue )
SELF:FieldPut( #DE , uValue )

ACCESS DESTINO
RETURN SELF:FieldGet( #DESTINO )

ASSIGN DESTINO( uValue )
SELF:FieldPut( #DESTINO , uValue )

ACCESS ERRO
RETURN SELF:FieldGet( #ERRO )

ASSIGN ERRO( uValue )
SELF:FieldPut( #ERRO , uValue )

ACCESS HORA
RETURN SELF:FieldGet( #HORA )

ASSIGN HORA( uValue )
SELF:FieldPut( #HORA , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JMAILNEW" , _GetInst()},iCtlID)

	SELF:oDCSC_NUMERO := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_NUMERO  , _GetInst() } }
	SELF:oDCSC_NUMERO:HyperLabel := HyperLabel{#SC_NUMERO , "Numero:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ERRO := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_ERRO  , _GetInst() } }
	SELF:oDCSC_ERRO:HyperLabel := HyperLabel{#SC_ERRO , "Erro:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DATA := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_DATA  , _GetInst() } }
	SELF:oDCSC_DATA:HyperLabel := HyperLabel{#SC_DATA , "Data:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HORA := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_HORA  , _GetInst() } }
	SELF:oDCSC_HORA:HyperLabel := HyperLabel{#SC_HORA , "Hora:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DE := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_DE  , _GetInst() } }
	SELF:oDCSC_DE:HyperLabel := HyperLabel{#SC_DE , "De:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_DESTINO  , _GetInst() } }
	SELF:oDCSC_DESTINO:HyperLabel := HyperLabel{#SC_DESTINO , "Destino:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ASSUNTO := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_ASSUNTO  , _GetInst() } }
	SELF:oDCSC_ASSUNTO:HyperLabel := HyperLabel{#SC_ASSUNTO , "Assunto:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_TEXTO := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_TEXTO  , _GetInst() } }
	SELF:oDCSC_TEXTO:HyperLabel := HyperLabel{#SC_TEXTO , "Texto:" , NULL_STRING , NULL_STRING}

	SELF:oDCNUMERO := SINGLELINEEDIT{SELF , ResourceID{ JMAILNEW_NUMERO  , _GetInst() } }
	SELF:oDCNUMERO:FieldSpec := PADRAO_NUM_08{}
	SELF:oDCNUMERO:TooltipText := "Numero da Mensagem"
	SELF:oDCNUMERO:HyperLabel := HyperLabel{#NUMERO , "PADRAO_NUM_08" , NULL_STRING , "MAIL_NUMERO"}

	SELF:oDCERRO := SINGLELINEEDIT{SELF , ResourceID{ JMAILNEW_ERRO  , _GetInst() } }
	SELF:oDCERRO:FieldSpec := PADRAO_CHAR_08{}
	SELF:oDCERRO:TooltipText := "Codigo da Mensagem"
	SELF:oDCERRO:HyperLabel := HyperLabel{#ERRO , "PADRAO_CHAR_08" , NULL_STRING , "MAIL_ERRO"}

	SELF:oDCDATA := SINGLELINEEDIT{SELF , ResourceID{ JMAILNEW_DATA  , _GetInst() } }
	SELF:oDCDATA:FieldSpec := DATE_FIELD{}
	SELF:oDCDATA:TooltipText := "Data Criação da Mensagem"
	SELF:oDCDATA:HyperLabel := HyperLabel{#DATA , "Data" , NULL_STRING , "MAIL_DATA"}

	SELF:oDCHORA := SINGLELINEEDIT{SELF , ResourceID{ JMAILNEW_HORA  , _GetInst() } }
	SELF:oDCHORA:FieldSpec := time_long{}
	SELF:oDCHORA:TooltipText := "Hora Criaçao Mensagem"
	SELF:oDCHORA:HyperLabel := HyperLabel{#HORA , "Hora:" , NULL_STRING , "MAIL_HORA"}

	SELF:oDCDE := SINGLELINEEDIT{SELF , ResourceID{ JMAILNEW_DE  , _GetInst() } }
	SELF:oDCDE:FieldSpec := PADRAO_CHAR_12{}
	SELF:oDCDE:TooltipText := "Emitente da Mensagem"
	SELF:oDCDE:HyperLabel := HyperLabel{#DE , "De:" , NULL_STRING , "MAIL_DE"}

	SELF:oDCDESTINO := SINGLELINEEDIT{SELF , ResourceID{ JMAILNEW_DESTINO  , _GetInst() } }
	SELF:oDCDESTINO:FieldSpec := PADRAO_CHAR_12{}
	SELF:oDCDESTINO:TooltipText := "Destinatario da Mensagem"
	SELF:oDCDESTINO:HyperLabel := HyperLabel{#DESTINO , "Destino:" , NULL_STRING , "MAIL_DESTINO"}

	SELF:oDCASSUNTO := SINGLELINEEDIT{SELF , ResourceID{ JMAILNEW_ASSUNTO  , _GetInst() } }
	SELF:oDCASSUNTO:FieldSpec := PADRAO_CHAR_120{}
	SELF:oDCASSUNTO:TooltipText := "Assunto da Mensagem"
	SELF:oDCASSUNTO:HyperLabel := HyperLabel{#ASSUNTO , "Assunto:" , NULL_STRING , "MAIL_ASSUNTO"}

	SELF:oDCTEXTO := MULTILINEEDIT{SELF , ResourceID{ JMAILNEW_TEXTO  , _GetInst() } }
	SELF:oDCTEXTO:FieldSpec := MEMO_FIELD{}
	SELF:oDCTEXTO:TooltipText := "Conteudo da Mensagem"
	SELF:oDCTEXTO:HyperLabel := HyperLabel{#TEXTO , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCOK := PUSHBUTTON{SELF , ResourceID{ JMAILNEW_OK  , _GetInst() } }
	SELF:oCCOK:TooltipText := "Encerra Preenchimento da Mensagem"
	SELF:oCCOK:Image := ico_ok{}
	SELF:oCCOK:HyperLabel := HyperLabel{#OK , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DESTINO1 := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_SC_DESTINO1  , _GetInst() } }
	SELF:oDCSC_DESTINO1:HyperLabel := HyperLabel{#SC_DESTINO1 , "OK" , NULL_STRING , NULL_STRING}

	SELF:oDCx2 := FIXEDTEXT{SELF , ResourceID{ JMAILNEW_X2  , _GetInst() } }
	SELF:oDCx2:HyperLabel := HyperLabel{#x2 , "Ajuda" , NULL_STRING , NULL_STRING}

	SELF:oCCAjuda := PUSHBUTTON{SELF , ResourceID{ JMAILNEW_AJUDA  , _GetInst() } }
	SELF:oCCAjuda:TooltipText := "Clique Para Acessar a Ajuda"
	SELF:oCCAjuda:Image := ico_ajuda{}
	SELF:oCCAjuda:HyperLabel := HyperLabel{#Ajuda , NULL_STRING , NULL_STRING , "login"}

	SELF:Caption := "Nova Mensagem"
	SELF:HyperLabel := HyperLabel{#JMAILNEW , "Nova Mensagem" , NULL_STRING , "mailnovo"}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ELSE
		SELF:Use(SELF:Owner:Server)
	ENDIF


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NUMERO
RETURN SELF:FieldGet( #NUMERO )

ASSIGN NUMERO( uValue )
SELF:FieldPut( #NUMERO , uValue )

METHOD OK( ) 
IF Empty(SELF:SERVER:FIELDGET("DESTINO"))
   alert("Destino não Preenchido","Dados Incompletos")	
   RETURN .f.
ENDIF	
SELF:SERVER:FIELDPUT("DESTINO",Upper(SELF:SERVER:FIELDGET("DESTINO")))
SELF:EndWindow()
RETURN .t.

ACCESS TEXTO
RETURN SELF:FieldGet( #TEXTO )

ASSIGN TEXTO( uValue )
SELF:FieldPut( #TEXTO , uValue )

END CLASS
