CLASS XJMAILGER INHERIT ZMAIL
	//usa zmail pois tem configuracao de arquivos na inicializacao

METHOD append 
LOCAL oMAIL AS JMAILNEW
SELF:RegisterTimer(120,FALSE)
SELF:server:Append()
SELF:SERVER:FIELDPUT("NUMERO",SELF:SERVER:RECNO)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("HORA",Time())
SELF:SERVER:FIELDPUT("DE",SELF:cUSER)
SELF:SERVER:FIELDPUT("ERRO","AVULSA")
oMAIL:=Jmailnew{SELF}
oMAIL:SHOW()


METHOD Deletar( ) 
LOCAL oMAIL AS USEREDE
LOCAL aDAD AS ARRAY
IF SELF:SERVER:EOF
   RETURN .f.
ENDIF	
aDAD:={cCURINI,"MAILPG.DBF",cCURDIR}
oMAIL:=USEREDE{aDAD}
IF oMAIL:nERRO#0
   RETURN .f.
ENDIF
oMAIL:APPEND()
oMAIL:FIELDPUT("NUMERO",oMAIL:RECNO)
oMAIL:FIELDPUT("DATA",SELF:SERVER:FIELDGET("DATA"))
oMAIL:FIELDPUT("HORA",SELF:SERVER:FIELDGET("HORA"))
oMAIL:FIELDPUT("DE",SELF:SERVER:FIELDGET("DE"))
oMAIL:FIELDPUT("ERRO",SELF:SERVER:FIELDGET("ERRO"))
oMAIL:FIELDPUT("DESTINO",SELF:SERVER:FIELDGET("DESTINO"))
oMAIL:FIELDPUT("ASSUNTO",SELF:SERVER:FIELDGET("ASSUNTO"))
oMAIL:FIELDPUT("TEXTO",SELF:SERVER:FIELDGET("TEXTO"))
oMAIL:FIELDPUT("DATAOK",Today())
oMAIL:FIELDPUT("HORAOK",Time())
oMAIL:CLOSE()
SELF:SERVER:DELETE()
SELF:SERVER:SKIP(-1)
IF SELF:SERVER:BOF
   SELF:SERVER:GOTOP()	
ENDIF	
SELF:RegisterTimer(60,FALSE)
RETURN .t.
	

METHOD DELETE 
	SELF:Deletar()

METHOD INCLUIR() 
	SELF:APPEND()

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("MAI",98)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MAIL.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,oServer,ZCURINI,zCURDIR,ZUSER,,CHELP)
SELF:SHOW()

METHOD PostInit() 
	
	   FabCenterWindow( SELF )


END CLASS
