CLASS XJMAILCFG INHERIT _JMAILCFG

METHOD AJUDA 
SELF:HelpDisplay:Show( "MailCfg" )

METHOD APPEND() 
LOCAL oBUSCA AS XBUSCA
oBUSCA:=XBUSCA{SELF,"Incluir","Digite o Código"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF oBUSCA:lOK
   SELF:SERVER:SETORDER(1)
   SELF:SERVER:GOTOP()
   IF ! SELF:SERVER:SEEK(oBUSCA:cBUSCA)
   	  SUPER:append()
   	  SELF:SERVER:FIELDPUT("ERRO",oBUSCA:cBUSCA)
   ENDIF	
ENDIF

METHOD BUSCA() 
SELF:KeyFind()	
//LOCAL oBUSCA AS XBUSCA
//oBUSCA:=XBUSCA{SELF,"Localizar","Digite o Código"}
//oBUSCA:lMES:=.T.
//oBUSCA:SHOW()
//IF oBUSCA:lOK
//   SELF:SERVER:SETORDER(1)
//   SELF:SERVER:GOTOP()
//   SELF:SERVER:SEEK(oBUSCA:cBUSCA)
//ENDIF

METHOD DELETE() 	
IF  MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
   SELF:oSFJMAILPARA:SERVER:gotop()
   WHILE ! SELF:oSFJMAILPARA:SERVER:eof
	 	SELF:oSFJMAILPARA:SERVER:delete()
	 	SELF:oSFJMAILPARA:SERVER:skip()	
    ENDDO
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
	IF SELF:SERVER:BOF
	   SELF:SERVER:GOTOP()	
    ENDIF		
ENDIF		

METHOD EXCLUIR 

    SELF:oSFJMAILPARA:server:delete()
    SELF:oSFJMAILPARA:server:unlock()
    SELF:oSFJMAILPARA:server:gotop()
    SELF:oSFJMAILPARA:server:GoBottom()
    SELF:OSFJMAILPARA:Browser:Refresh()



METHOD INCLUIR(oOWNER) 
LOCAL oBUSCA AS XBUSCA
LOCAL cDESTINO AS STRING	
oBUSCA:=XBUSCA{oOWNER,"Incluir Destinatário","Digite o Nome do Destinatário"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! oBUSCA:lOK
   RETU SELF	
ENDIF	
cDESTINO:=oBUSCA:cBUSCA
SELF:oSFJMAILPARA:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJMAILPARA:SERVER:APPEND()
SELF:oSFJMAILPARA:SERVER:FIELDPUT("ERRO",SELF:SERVER:FIELDGET("ERRO"))
SELF:oSFJMAILPARA:SERVER:FIELDPUT("DESTINO",cDESTINO)
SELF:oSFJMAILPARA:SERVER:commit()
SELF:oSFJMAILPARA:SERVER:resetnotification()
SELF:oSFJMAILPARA:SERVER:notify(notifyappend)
SELF:OSFJMAILPARA:Browser:REFRESH()


CONSTRUCTOR(oOWNER) 	
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("MAI",99)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MAILERRO.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MAILPARA.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,CHELP,oSERVER)
SELF:OSFJMAILPARA:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJMAILPARA,"ERRO")
SELF:OSFJMAILPARA:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		

METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
		    FabCenterWindow( SELF )
	RETURN NIL



END CLASS
