FUNCTION EMAILINT(cERRO,cUSER,cTEXTO,cCURINI,cCURDIR)
LOCAL oMAIL,oMAILERRO,oMAILPARA AS USEREDE	
LOCAL aDAD AS ARRAY
LOCAL X AS BYTE
LOCAL cDIZ AS STRING
LOCAL cDIGA
cUSER:=Upper(cUSER)
cDIGA:=cTEXTO
cDIZ:=""
IF ValType(cDIGA)="A"
   FOR X:=1 TO Len(cDIGA)
   	   cDIZ+=cDIGA[X]+CHR(13)+CHR(10)
   NEXT X
ELSE
   cDIZ:=cTEXTO
ENDIF	
aDAD:={cCURINI,"MAIL.DBF",cCURDIR}
oMAIL:=USEREDE{aDAD}
IF oMAIL:nERRO#0
   RETU .F.
ENDIF
aDAD:={cCURINI,"MAILERRO.DBF",cCURDIR}
oMAILERRO:=USEREDE{aDAD}
IF oMAILERRO:nERRO#0
   oMAIL:CLOSE()	
   RETU .F.
ENDIF
aDAD:={cCURINI,"MAILPARA.DBF",cCURDIR}
oMAILPARA:=USEREDE{aDAD}
IF oMAILPARA:nERRO#0
   oMAIL:CLOSE()	
   oMAILERRO:CLOSE()
   RETU .F.
ENDIF
oMAILERRO:GOTOP()
IF oMAILERRO:SEEK(cERRO)
   oMAILPARA:GOTOP()
   oMAILPARA:SEEK(cERRO)
   WHILE oMAILPARA:FIELDGET("ERRO")=cERRO  .AND. .NOT. oMAILPARA:EOF
   	   oMAIL:APPEND()
   	   oMAIL:FIELDPUT("NUMERO",oMAIL:RECNO)
       oMAIL:FIELDPUT("DATA",Today())
       oMAIL:FIELDPUT("HORA",Time())
       oMAIL:FIELDPUT("DE",cUSER)
       oMAIL:FIELDPUT("ERRO",cERRO)
       oMAIL:FIELDPUT("DESTINO",oMAILPARA:FIELDGET("DESTINO"))
       oMAIL:FIELDPUT("ASSUNTO",oMAILERRO:FIELDGET("ASSUNTO"))
       oMAIL:FIELDPUT("TEXTO",cDIZ)
   	   oMAILPARA:SKIP()
   ENDDO	
ENDIF	
oMAIL:CLOSE()
oMAILERRO:CLOSE()
oMAILPARA:CLOSE()
RETU .T.



