FUNC PEGBC01(cCODIGO)
LOCAL aRETU:={.F.,"","",0,""}
LOCAL oARQ AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"BC01.DBF",zCURDIR}
oARQ:=USEREDE{aDAD}
IF oARQ:nERRO#0
   RETU aRETU
ENDIF
oARQ:SETORDER(1)
oARQ:GOTOP()
IF oARQ:SEEK(cCODIGO)
   aRETU[1]:=.T.
   aRETU[2]:=oARQ:FIELDGET("DESCRICAO")
   aRETU[3]:=oARQ:FIELDGET("ITEM")
   aRETU[4]:=oARQ:FIELDGET("VALOR")
   aRETU[5]:=oARQ:FIELDGET("TIPO")
ENDIF
oARQ:CLOSE()
RETU aRETU


