CLASS XJBC01 INHERIT JBC01

METHOD APPEND() 
SUPER:append()
GRAVALOG(SELF:SERVER:CODIGO,"INC","BC01")	
RETURN .T.

METHOD buscaov( ) 
	 SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("ZB","")	


METHOD cmdtipo( ) 
	SELF:server:FIELDPUT("TIPO",SIMNAO(SELF:SERVER:FIELDGET("TIPO"),{"D","C"}))	

METHOD DELETE() 
GRAVALOG(SELF:SERVER:CODIGO,"DEL","BC01")	
SUPER:DELETE()
RETURN .T.

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("BCO",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"BC01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:USE(oSERVER)
SELF:oDCITEM:FillUsing(PEGCOMBO("MI04.DBF","NOME","CONTA"))
SELF:SHOW()


METHOD porov( ) 
	SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
