#region DEFINES
STATIC DEFINE JBD01_BAIRRO := 103
STATIC DEFINE JBD01_BUSCANUM := 138
STATIC DEFINE JBD01_CEP := 106
STATIC DEFINE JBD01_CIDADE := 105
STATIC DEFINE JBD01_COGNOME := 100
STATIC DEFINE JBD01_CONTATO := 110
STATIC DEFINE JBD01_CONTATO1 := 114
STATIC DEFINE JBD01_DDD := 107
STATIC DEFINE JBD01_DDD1 := 111
STATIC DEFINE JBD01_DDDFAX := 115
STATIC DEFINE JBD01_EMAIL := 117
STATIC DEFINE JBD01_ENDERECO := 102
STATIC DEFINE JBD01_ESTADO := 104
STATIC DEFINE JBD01_FT20 := 135
STATIC DEFINE JBD01_FT21 := 136
STATIC DEFINE JBD01_JBF01 := 139
STATIC DEFINE JBD01_NOME := 101
STATIC DEFINE JBD01_NUMERO := 121
STATIC DEFINE JBD01_PORNUM := 137
STATIC DEFINE JBD01_RAMAL := 109
STATIC DEFINE JBD01_RAMAL1 := 113
STATIC DEFINE JBD01_SC_BAIRRO := 124
STATIC DEFINE JBD01_SC_CEP := 127
STATIC DEFINE JBD01_SC_CIDADE := 125
STATIC DEFINE JBD01_SC_COGNOME := 119
STATIC DEFINE JBD01_SC_CONTATO := 131
STATIC DEFINE JBD01_SC_DDD := 128
STATIC DEFINE JBD01_SC_ENDERECO := 123
STATIC DEFINE JBD01_SC_ESTADO := 126
STATIC DEFINE JBD01_SC_NOME := 122
STATIC DEFINE JBD01_SC_NUMERO := 120
STATIC DEFINE JBD01_SC_RAMAL := 130
STATIC DEFINE JBD01_SC_TELEFONE := 129
STATIC DEFINE JBD01_SITE := 118
STATIC DEFINE JBD01_TELEFAX := 116
STATIC DEFINE JBD01_TELEFONE := 108
STATIC DEFINE JBD01_TELEFONE1 := 112
STATIC DEFINE JBD01_THEFIXEDTEXT16 := 132
STATIC DEFINE JBD01_THEFIXEDTEXT17 := 133
STATIC DEFINE JBD01_THEFIXEDTEXT18 := 134
#endregion

PARTIAL CLASS JBD01 INHERIT MYDataWindow
PROTECT oDBNUMERO AS DataColumn
PROTECT oDBCOGNOME AS DataColumn
PROTECT oDBNOME AS DataColumn
PROTECT oDBEMAIL AS DataColumn
PROTECT oDBDDD AS DataColumn
PROTECT oDBTELEFONE AS DataColumn
PROTECT oDCCOGNOME AS SINGLELINEEDIT
PROTECT oDCNOME AS SINGLELINEEDIT
PROTECT oDCENDERECO AS SINGLELINEEDIT
PROTECT oDCBAIRRO AS SINGLELINEEDIT
PROTECT oDCESTADO AS SINGLELINEEDIT
PROTECT oDCCIDADE AS SINGLELINEEDIT
PROTECT oDCCEP AS SINGLELINEEDIT
PROTECT oDCDDD AS rightSle
PROTECT oDCTELEFONE AS rightSle
PROTECT oDCRAMAL AS SINGLELINEEDIT
PROTECT oDCCONTATO AS SINGLELINEEDIT
PROTECT oDCDDD1 AS rightSle
PROTECT oDCTELEFONE1 AS rightSle
PROTECT oDCRAMAL1 AS SINGLELINEEDIT
PROTECT oDCCONTATO1 AS SINGLELINEEDIT
PROTECT oDCDDDFAX AS rightSle
PROTECT oDCTELEFAX AS rightSle
PROTECT oDCEMAIL AS SINGLELINEEDIT
PROTECT oDCSITE AS SINGLELINEEDIT
PROTECT oDCSC_COGNOME AS FIXEDTEXT
PROTECT oDCSC_NUMERO AS FIXEDTEXT
PROTECT oDCNUMERO AS SINGLELINEEDIT
PROTECT oDCSC_NOME AS FIXEDTEXT
PROTECT oDCSC_ENDERECO AS FIXEDTEXT
PROTECT oDCSC_BAIRRO AS FIXEDTEXT
PROTECT oDCSC_CIDADE AS FIXEDTEXT
PROTECT oDCSC_ESTADO AS FIXEDTEXT
PROTECT oDCSC_CEP AS FIXEDTEXT
PROTECT oDCSC_DDD AS FIXEDTEXT
PROTECT oDCSC_TELEFONE AS FIXEDTEXT
PROTECT oDCSC_RAMAL AS FIXEDTEXT
PROTECT oDCSC_CONTATO AS FIXEDTEXT
PROTECT oDCtheFixedText16 AS FIXEDTEXT
PROTECT oDCtheFixedText17 AS FIXEDTEXT
PROTECT oDCtheFixedText18 AS FIXEDTEXT
PROTECT oDCft20 AS FIXEDTEXT
PROTECT oDCFT21 AS FIXEDTEXT
PROTECT oCCpornum AS PUSHBUTTON
PROTECT oCCbuscanum AS PUSHBUTTON
PROTECT oSFJBF01 AS JBF01
PROTECT oDCDateTimePicker1 AS DATETIMEPICKER

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS BAIRRO
RETURN SELF:FieldGet( #BAIRRO )

ASSIGN BAIRRO( uValue )
SELF:FieldPut( #BAIRRO , uValue )

ACCESS CEP
RETURN SELF:FieldGet( #CEP )

ASSIGN CEP( uValue )
SELF:FieldPut( #CEP , uValue )

ACCESS CIDADE
RETURN SELF:FieldGet( #CIDADE )

ASSIGN CIDADE( uValue )
SELF:FieldPut( #CIDADE , uValue )

ACCESS COGNOME
RETURN SELF:FieldGet( #COGNOME )

ASSIGN COGNOME( uValue )
SELF:FieldPut( #COGNOME , uValue )

ACCESS CONTATO
RETURN SELF:FieldGet( #CONTATO )

ASSIGN CONTATO( uValue )
SELF:FieldPut( #CONTATO , uValue )

ACCESS CONTATO1
RETURN SELF:FieldGet( #CONTATO1 )

ASSIGN CONTATO1( uValue )
SELF:FieldPut( #CONTATO1 , uValue )

ACCESS DDD
RETURN SELF:FieldGet( #DDD )

ASSIGN DDD( uValue )
SELF:FieldPut( #DDD , uValue )

ACCESS DDD1
RETURN SELF:FieldGet( #DDD1 )

ASSIGN DDD1( uValue )
SELF:FieldPut( #DDD1 , uValue )

ACCESS DDDFAX
RETURN SELF:FieldGet( #DDDFAX )

ASSIGN DDDFAX( uValue )
SELF:FieldPut( #DDDFAX , uValue )

ACCESS EMAIL
RETURN SELF:FieldGet( #EMAIL )

ASSIGN EMAIL( uValue )
SELF:FieldPut( #EMAIL , uValue )

ACCESS ENDERECO
RETURN SELF:FieldGet( #ENDERECO )

ASSIGN ENDERECO( uValue )
SELF:FieldPut( #ENDERECO , uValue )

ACCESS ESTADO
RETURN SELF:FieldGet( #ESTADO )

ASSIGN ESTADO( uValue )
SELF:FieldPut( #ESTADO , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JBD01" , _GetInst()},iCtlID)

	SELF:oDCCOGNOME := SINGLELINEEDIT{SELF , ResourceID{ JBD01_COGNOME  , _GetInst() } }
	SELF:oDCCOGNOME:HyperLabel := HyperLabel{#COGNOME , "Cognome:" , NULL_STRING , "MB01_COGNOME"}
	SELF:oDCCOGNOME:FieldSpec := PADRAO_CHAR_15{}

	SELF:oDCNOME := SINGLELINEEDIT{SELF , ResourceID{ JBD01_NOME  , _GetInst() } }
	SELF:oDCNOME:HyperLabel := HyperLabel{#NOME , "Nome:" , NULL_STRING , "MB01_NOME"}
	SELF:oDCNOME:FieldSpec := PADRAO_CHAR_40{}

	SELF:oDCENDERECO := SINGLELINEEDIT{SELF , ResourceID{ JBD01_ENDERECO  , _GetInst() } }
	SELF:oDCENDERECO:HyperLabel := HyperLabel{#ENDERECO , "Endereco:" , NULL_STRING , "MB01_ENDERECO"}
	SELF:oDCENDERECO:FieldSpec := PADRAO_CHAR_40{}

	SELF:oDCBAIRRO := SINGLELINEEDIT{SELF , ResourceID{ JBD01_BAIRRO  , _GetInst() } }
	SELF:oDCBAIRRO:HyperLabel := HyperLabel{#BAIRRO , "Bairro:" , NULL_STRING , "MB01_BAIRRO"}
	SELF:oDCBAIRRO:FieldSpec := PADRAO_CHAR_30{}

	SELF:oDCESTADO := SINGLELINEEDIT{SELF , ResourceID{ JBD01_ESTADO  , _GetInst() } }
	SELF:oDCESTADO:HyperLabel := HyperLabel{#ESTADO , "Numero:" , NULL_STRING , "MB01_NUMERO"}
	SELF:oDCESTADO:FieldSpec := UF_FIELD{}

	SELF:oDCCIDADE := SINGLELINEEDIT{SELF , ResourceID{ JBD01_CIDADE  , _GetInst() } }
	SELF:oDCCIDADE:HyperLabel := HyperLabel{#CIDADE , "Cidade:" , NULL_STRING , "MB01_CIDADE"}
	SELF:oDCCIDADE:FieldSpec := PAdrao_char_30{}

	SELF:oDCCEP := SINGLELINEEDIT{SELF , ResourceID{ JBD01_CEP  , _GetInst() } }
	SELF:oDCCEP:HyperLabel := HyperLabel{#CEP , "Cep:" , NULL_STRING , "MB01_CEP"}
	SELF:oDCCEP:FieldSpec := cep_field{}

	SELF:oDCDDD := rightSle{SELF , ResourceID{ JBD01_DDD  , _GetInst() } }
	SELF:oDCDDD:HyperLabel := HyperLabel{#DDD , "Ddd:" , NULL_STRING , "MB01_DDD"}
	SELF:oDCDDD:FieldSpec := ddd_field{}

	SELF:oDCTELEFONE := rightSle{SELF , ResourceID{ JBD01_TELEFONE  , _GetInst() } }
	SELF:oDCTELEFONE:HyperLabel := HyperLabel{#TELEFONE , "Telefone:" , NULL_STRING , "MB01_TELEFONE"}
	SELF:oDCTELEFONE:FieldSpec := PADRAO_CHAR_12{}

	SELF:oDCRAMAL := SINGLELINEEDIT{SELF , ResourceID{ JBD01_RAMAL  , _GetInst() } }
	SELF:oDCRAMAL:HyperLabel := HyperLabel{#RAMAL , "Ramal:" , NULL_STRING , "MB01_RAMAL"}
	SELF:oDCRAMAL:FieldSpec := padrao_char_04{}

	SELF:oDCCONTATO := SINGLELINEEDIT{SELF , ResourceID{ JBD01_CONTATO  , _GetInst() } }
	SELF:oDCCONTATO:HyperLabel := HyperLabel{#CONTATO , "Contato:" , NULL_STRING , "MB01_CONTATO"}
	SELF:oDCCONTATO:FieldSpec := padrao_char_22{}

	SELF:oDCDDD1 := rightSle{SELF , ResourceID{ JBD01_DDD1  , _GetInst() } }
	SELF:oDCDDD1:HyperLabel := HyperLabel{#DDD1 , "Ddd1:" , NULL_STRING , "MB01_DDD1"}
	SELF:oDCDDD1:FieldSpec := ddd_field{}

	SELF:oDCTELEFONE1 := rightSle{SELF , ResourceID{ JBD01_TELEFONE1  , _GetInst() } }
	SELF:oDCTELEFONE1:HyperLabel := HyperLabel{#TELEFONE1 , "Telefone1:" , NULL_STRING , "MB01_TELEFONE1"}
	SELF:oDCTELEFONE1:FieldSpec := PADRAO_CHAR_12{}

	SELF:oDCRAMAL1 := SINGLELINEEDIT{SELF , ResourceID{ JBD01_RAMAL1  , _GetInst() } }
	SELF:oDCRAMAL1:HyperLabel := HyperLabel{#RAMAL1 , "Ramal1:" , NULL_STRING , "MB01_RAMAL1"}
	SELF:oDCRAMAL1:FieldSpec := padrao_char_04{}

	SELF:oDCCONTATO1 := SINGLELINEEDIT{SELF , ResourceID{ JBD01_CONTATO1  , _GetInst() } }
	SELF:oDCCONTATO1:HyperLabel := HyperLabel{#CONTATO1 , "Contato1:" , NULL_STRING , "MB01_CONTATO1"}
	SELF:oDCCONTATO1:FieldSpec := padrao_char_22{}

	SELF:oDCDDDFAX := rightSle{SELF , ResourceID{ JBD01_DDDFAX  , _GetInst() } }
	SELF:oDCDDDFAX:HyperLabel := HyperLabel{#DDDFAX , "Dddfax:" , NULL_STRING , "MB01_DDDFAX"}
	SELF:oDCDDDFAX:FieldSpec := ddd_field{}

	SELF:oDCTELEFAX := rightSle{SELF , ResourceID{ JBD01_TELEFAX  , _GetInst() } }
	SELF:oDCTELEFAX:HyperLabel := HyperLabel{#TELEFAX , "Telefax:" , NULL_STRING , "MB01_TELEFAX"}
	SELF:oDCTELEFAX:FieldSpec := PADRAO_CHAR_12{}

	SELF:oDCEMAIL := SINGLELINEEDIT{SELF , ResourceID{ JBD01_EMAIL  , _GetInst() } }
	SELF:oDCEMAIL:HyperLabel := HyperLabel{#EMAIL , "Email" , NULL_STRING , NULL_STRING}
	SELF:oDCEMAIL:FieldSpec := email_field{}

	SELF:oDCSITE := SINGLELINEEDIT{SELF , ResourceID{ JBD01_SITE  , _GetInst() } }
	SELF:oDCSITE:HyperLabel := HyperLabel{#SITE , NULL_STRING , NULL_STRING , NULL_STRING}
	SELF:oDCSITE:FieldSpec := padrao_char_30{}

	SELF:oDCSC_COGNOME := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_COGNOME  , _GetInst() } }
	SELF:oDCSC_COGNOME:HyperLabel := HyperLabel{#SC_COGNOME , "Cognome:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_NUMERO := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_NUMERO  , _GetInst() } }
	SELF:oDCSC_NUMERO:HyperLabel := HyperLabel{#SC_NUMERO , "Numero:" , NULL_STRING , NULL_STRING}

	SELF:oDCNUMERO := SINGLELINEEDIT{SELF , ResourceID{ JBD01_NUMERO  , _GetInst() } }
	SELF:oDCNUMERO:HyperLabel := HyperLabel{#NUMERO , "Numero:" , NULL_STRING , "MB01_NUMERO"}
	SELF:oDCNUMERO:FieldSpec := PADRAO_NUM_05{}

	SELF:oDCSC_NOME := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_NOME  , _GetInst() } }
	SELF:oDCSC_NOME:HyperLabel := HyperLabel{#SC_NOME , "Nome:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ENDERECO := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_ENDERECO  , _GetInst() } }
	SELF:oDCSC_ENDERECO:HyperLabel := HyperLabel{#SC_ENDERECO , "Endereço:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_BAIRRO := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_BAIRRO  , _GetInst() } }
	SELF:oDCSC_BAIRRO:HyperLabel := HyperLabel{#SC_BAIRRO , "Bairro:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CIDADE := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_CIDADE  , _GetInst() } }
	SELF:oDCSC_CIDADE:HyperLabel := HyperLabel{#SC_CIDADE , "Cidade:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_ESTADO := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_ESTADO  , _GetInst() } }
	SELF:oDCSC_ESTADO:HyperLabel := HyperLabel{#SC_ESTADO , "Estado:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CEP := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_CEP  , _GetInst() } }
	SELF:oDCSC_CEP:HyperLabel := HyperLabel{#SC_CEP , "Cep:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DDD := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_DDD  , _GetInst() } }
	SELF:oDCSC_DDD:HyperLabel := HyperLabel{#SC_DDD , "DDD:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_TELEFONE := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_TELEFONE  , _GetInst() } }
	SELF:oDCSC_TELEFONE:HyperLabel := HyperLabel{#SC_TELEFONE , "Telefone:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_RAMAL := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_RAMAL  , _GetInst() } }
	SELF:oDCSC_RAMAL:HyperLabel := HyperLabel{#SC_RAMAL , "Ramal:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CONTATO := FIXEDTEXT{SELF , ResourceID{ JBD01_SC_CONTATO  , _GetInst() } }
	SELF:oDCSC_CONTATO:HyperLabel := HyperLabel{#SC_CONTATO , "Contato:" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText16 := FIXEDTEXT{SELF , ResourceID{ JBD01_THEFIXEDTEXT16  , _GetInst() } }
	SELF:oDCtheFixedText16:HyperLabel := HyperLabel{#theFixedText16 , "Telefone" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText17 := FIXEDTEXT{SELF , ResourceID{ JBD01_THEFIXEDTEXT17  , _GetInst() } }
	SELF:oDCtheFixedText17:HyperLabel := HyperLabel{#theFixedText17 , "Telefone" , NULL_STRING , NULL_STRING}

	SELF:oDCtheFixedText18 := FIXEDTEXT{SELF , ResourceID{ JBD01_THEFIXEDTEXT18  , _GetInst() } }
	SELF:oDCtheFixedText18:HyperLabel := HyperLabel{#theFixedText18 , "Fax:" , NULL_STRING , NULL_STRING}

	SELF:oDCft20 := FIXEDTEXT{SELF , ResourceID{ JBD01_FT20  , _GetInst() } }
	SELF:oDCft20:HyperLabel := HyperLabel{#ft20 , "Email" , NULL_STRING , NULL_STRING}

	SELF:oDCFT21 := FIXEDTEXT{SELF , ResourceID{ JBD01_FT21  , _GetInst() } }
	SELF:oDCFT21:HyperLabel := HyperLabel{#FT21 , "Site" , NULL_STRING , NULL_STRING}

	SELF:oCCpornum := PUSHBUTTON{SELF , ResourceID{ JBD01_PORNUM  , _GetInst() } }
	SELF:oCCpornum:HyperLabel := HyperLabel{#pornum , NULL_STRING , NULL_STRING , NULL_STRING}
	SELF:oCCpornum:Image := ICO_AZ{}

	SELF:oCCbuscanum := PUSHBUTTON{SELF , ResourceID{ JBD01_BUSCANUM  , _GetInst() } }
	SELF:oCCbuscanum:HyperLabel := HyperLabel{#buscanum , NULL_STRING , NULL_STRING , NULL_STRING}
	SELF:oCCbuscanum:Image := ICO_FIND{}

	SELF:oDCDateTimePicker1 := DATETIMEPICKER{SELF , ResourceID{ JBD01_DATETIMEPICKER1  , _GetInst() } }
	SELF:oDCDateTimePicker1:HyperLabel := HyperLabel{#DateTimePicker1 , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:Caption := "Cadastro de Contatos"
	SELF:HyperLabel := HyperLabel{#JBD01 , "Cadastro de Contatos" , NULL_STRING , NULL_STRING}
	SELF:Menu := STANDARDSHELLMENU{}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBNUMERO := DataColumn{PADRAO_NUM_05{}}
	SELF:oDBNUMERO:Width := 8
	SELF:oDBNUMERO:HyperLabel := SELF:oDCNUMERO:HyperLabel
	SELF:oDBNUMERO:Caption := "Numero:"
	SELF:Browser:AddColumn(SELF:oDBNUMERO)

	SELF:oDBCOGNOME := DataColumn{PADRAO_CHAR_15{}}
	SELF:oDBCOGNOME:Width := 10
	SELF:oDBCOGNOME:HyperLabel := SELF:oDCCOGNOME:HyperLabel
	SELF:oDBCOGNOME:Caption := "Cognome:"
	SELF:Browser:AddColumn(SELF:oDBCOGNOME)

	SELF:oDBNOME := DataColumn{PADRAO_CHAR_40{}}
	SELF:oDBNOME:Width := 51
	SELF:oDBNOME:HyperLabel := SELF:oDCNOME:HyperLabel
	SELF:oDBNOME:Caption := "Nome:"
	SELF:Browser:AddColumn(SELF:oDBNOME)

	SELF:oDBEMAIL := DataColumn{email_field{}}
	SELF:oDBEMAIL:Width := 17
	SELF:oDBEMAIL:HyperLabel := SELF:oDCEMAIL:HyperLabel
	SELF:oDBEMAIL:Caption := "Email"
	SELF:Browser:AddColumn(SELF:oDBEMAIL)

	SELF:oDBDDD := DataColumn{ddd_field{}}
	SELF:oDBDDD:Width := 5
	SELF:oDBDDD:HyperLabel := SELF:oDCDDD:HyperLabel
	SELF:oDBDDD:Caption := "Ddd:"
	SELF:Browser:AddColumn(SELF:oDBDDD)

	SELF:oDBTELEFONE := DataColumn{PADRAO_CHAR_12{}}
	SELF:oDBTELEFONE:Width := 10
	SELF:oDBTELEFONE:HyperLabel := SELF:oDCTELEFONE:HyperLabel
	SELF:oDBTELEFONE:Caption := "Telefone:"
	SELF:Browser:AddColumn(SELF:oDBTELEFONE)

	SELF:ViewAs(#FormView)

	SELF:oSFJBF01 := JBF01{SELF , JBD01_JBF01 }
	SELF:oSFJBF01:Show()

	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NOME
RETURN SELF:FieldGet( #NOME )

ASSIGN NOME( uValue )
SELF:FieldPut( #NOME , uValue )

ACCESS NUMERO
RETURN SELF:FieldGet( #NUMERO )

ASSIGN NUMERO( uValue )
SELF:FieldPut( #NUMERO , uValue )

ACCESS RAMAL
RETURN SELF:FieldGet( #RAMAL )

ASSIGN RAMAL( uValue )
SELF:FieldPut( #RAMAL , uValue )

ACCESS RAMAL1
RETURN SELF:FieldGet( #RAMAL1 )

ASSIGN RAMAL1( uValue )
SELF:FieldPut( #RAMAL1 , uValue )

ACCESS SITE
RETURN SELF:FieldGet( #SITE )

ASSIGN SITE( uValue )
SELF:FieldPut( #SITE , uValue )

ACCESS TELEFAX
RETURN SELF:FieldGet( #TELEFAX )

ASSIGN TELEFAX( uValue )
SELF:FieldPut( #TELEFAX , uValue )

ACCESS TELEFONE
RETURN SELF:FieldGet( #TELEFONE )

ASSIGN TELEFONE( uValue )
SELF:FieldPut( #TELEFONE , uValue )

ACCESS TELEFONE1
RETURN SELF:FieldGet( #TELEFONE1 )

ASSIGN TELEFONE1( uValue )
SELF:FieldPut( #TELEFONE1 , uValue )

END CLASS
STATIC DEFINE JBD01_DATETIMEPICKER1 := 140
