CLASS XJBE01 INHERIT jbe01

METHOD buscanum( ) 
	SELF:KEYFIND()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("ZB","")	


METHOD DELETE() 
IF ! MDG("Apagar Registro") .AND. SELF:SERVER:LockCurrentRecord()
	RETU SELF
ENDIF	
SELF:server:delete()
SELF:server:unlock()
SELF:server:skip(-1)
IF SELF:SERVER:BOF
	SELF:SErVER:GOTOP()
ENDIF	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("BCO",8)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"BE01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"BF01.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
   oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)

oSERVE2:SETORDER(3)
SELF:oSFJBF01:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJBF01,"CODIGO")
SELF:OSFJBF01:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFJBF01:VIEWTABLE()

SELF:SHOW()



METHOD pornum( ) 
	SELF:KEYFIND()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()


END CLASS
