CLASS XJMF02 INHERIT JMF02

METHOD APPEND() 
LOCAL nNRCONTA AS DWORD
SELF:SERVER:SETORDER(2)
SELF:SERVER:GOBOTTOM()
nNRCONTA:=SELF:SERVER:FIELDGET("NRCONTA")
nNRCONTA++	
SUPER:append()
SELF:SERVER:FIELDPUT("NRCONTA",nNRCONTA)
GRAVALOG(SELF:SERVER:CONTA,"INC","MF02")	
RETURN   .T.

METHOD buscanum( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("MF","")	


METHOD DELETE() 
GRAVALOG(SELF:SERVER:CONTA,"DEL","MF02")	
SUPER:DELETE()
RETURN   .T.

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("BCO",2)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MF02.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
oSERVER:SetOrder(2)
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:USE(oSERVER)
SELF:SHOW()

METHOD pornum( ) 
	SELF:KEYFIND()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
