CLASS XINDEXAR INHERIT INDEXAR	

CONSTRUCTOR(oOWNER) 
IF ! entramenu("BCO",5)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	


METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
CRIANTX({ZCURINI,"BA01.DBF",ZCURDIR})
//CRIANTX({ZCURINI,"BB01.DBF",ZCURDIR})
CRIANTX({ZCURINI,"BC01.DBF",ZCURDIR})
CRIANTX({ZCURINI,"BD01.DBF",ZCURDIR})
CRIANTX({ZCURINI,"BE01.DBF",ZCURDIR})
CRIANTX({ZCURINI,"BF01.DBF",ZCURDIR})
CRIANTX({ZCURINI,"MI04.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()	

END CLASS
CLASS XJBA01ATU INHERIT xJBA01		

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL cVAR AS STRING
LOCAL aDAD AS ARRAY
IF ! entramenu("BCO",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"BA01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"BC01.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

cVAR:="YEAR(DATA)=" + Str(ZANO)+" .AND. MONTH(DATA)="+Str(ZMES)
//cVAR:="ANO=ZANO"
oSERVER:SETFILTER(cVAR)
oSERVER:GOTOP()

SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:USE(oSERVER)
SELF:OSFJBBC01:USE(oSERVE2)
SELF:OSFJBBC01:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()

END CLASS
CLASS XJBA01FEC INHERIT xJBA01	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEMANA5
LOCAL oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL oJAN AS JMESANO
IF ! entramenu("BCO",1)
	RETU SELF
ENDIF	
oJAN:=JMESANO{oOWNER}
oJAN:SHOW()
aDAD:={zCURINI,"BA"+OJAN:cCOMP,zCURDIR,aDIR}
oSERVER:=USEMANA5{aDAD}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF	
aDAD:={zCURINI,"BC01.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:OSFJBBC01:USE(oSERVE2)
SELF:OSFJBBC01:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	


END CLASS
