CLASS XESCMP04 INHERIT ESCMP04x

CONSTRUCTOR(oOWNER,nEMPRESA) 
LOCAL oSERVE2 AS USEREDE
LOCAL aDAD,aCOM AS ARRAY
lOK:=.F.
aDAD:={zCURINI,"MP04.DBF",zCURDIR}
IF ValType(nEMPRESA)#"N"
   nEMPRESA:=ZEMPRESA	
ENDIF	
aCOM:={zMES,zANO,nEMPRESA}
oSERVE2:=USEREDE{aDAD,,,,aCOM}
IF oSERVE2:nERRO#0
   RETU SELF
ENDIF
oSERVE2:SETORDER(2)
SUPER(oOWNER)
SELF:oSFJESCMP04:USE(oSERVE2)
SELF:oSFJescmp04:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		


END CLASS
