FUNCTION BAIXAR(cARQ,cARQBX,nMES,nANO)
LOCAL oSERVER,oBAIXA AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nFIELD,J AS DWORD

//SELF:POINTER:=POINTER{POINTERHOURGLASS}

IF nANO=0 .OR. nMES=0
   alert("Necessario Mes/Ano","Erro Informação")
   RETURN .f.
ENDIF	
aDAD:={zCURINI,carq,zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETURN .f.
ENDIF
aDAD:={zCURINI,carqbx,zCURDIR}
oBAIXA:=USEREDE{aDAD}
IF oBAIXA:nERRO#0
   oSERVER:CLOSE()
   RETURN .f.
ENDIF
nFIELD:=oSERVER:FCOUNT
oSERVER:GOTOP()
WHILE ! oSERVEr:EoF
   IF oSERVER:FIELDGET("ANO")=nANO .AND. oSERVER:FIELDGET("MES")=nMES
   	/// aDADOS:={}
      oBAIXA:Append()
      FOR J:=1 TO nFIELD
       	 oBAIXA:FIELDPUT(oSERVER:FieldName(J),oSERVER:FIELDGET(oSERVER:FieldName(J)))
      NEXT J
      oBAIXA:FIELDPUT("DATABAI",Today())
      oSERVER:DELETE()
   ENDIF
   oSERVER:SKIP()
ENDDO	
oSERVER:PACK()
oSERVER:CLOSE()
oBAIXA:CLOSE()
//SELF:POINTER:=POINTER{}	
//SELF:EndWindow()

FUNC checkiacmes(nMES,NANO)
LOCAL oSERVER AS DBSERVER	
LOCAL cDRIVER,cORI,cDIRE,cARQ AS STRING
LOCAL aCHAVE AS ARRAY
LOCAL X AS WORD
LOCAL cTAG AS STRING
LOCAL cIND AS STRING
aCHAVE:={}
AAdd(aCHAVE,"NUMERO")
AAdd(aCHAVE,"STR(OS,8)+STR(OSITEM,8)")
AAdd(aCHAVE,"CODIGO")
AAdd(aCHAVE,"CODIGOINT")
AAdd(aCHAVE,"CODCLIENTE")
AAdd(aCHAVE,"STR(FORNECEDO,8)+CODIGO")


cORI:="MM02IAC"
cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(zempresa,3)+StrZero(NANO,4)+"\"
//cDIRE:=PEGINIVAL(ZCURINI,"SISTEMAS","MANA5P")+"E"+StrZero(nANO,4)+"\"
cARQ:="IC"+Right(StrZero(nANO,4),2)+StrZero(nMES,2)
IF !File( ZCURDIR + cARQ + ".DBF" )
   IF File(ZCURDIR+cORI+".DBF")	
	   SHCopy(ZCURDIR+cORI+".DBF", CDIRE+cARQ + ".DBF" )
	   cDRIVER:=PEGINIVAL(ZCURINI,"PATH","DRIVER")
	   IF IsNil(cDriver) .OR. Empty(cDRIVER)	
    	   cDriver := "DBFCDX"
	   ENDIF
	   oSERVER:=DBSERVER{cDIRE+cARQ,.F.,,cDRIVER}	
	   IF ! oSERVER:Used
   		  RETU .F.
	   ENDIF		
	   FOR X:=1 TO Len(aCHAVE)
  	       IF cDriver = "DBFCDX"
              cTAG:="M2IAC"+StrZero(X,2)
              cIND:=aCHAVE[X]
    	      //OSERVER:CreateOrder(cARQ,ZCURDIR+cARQ,eCHAVE,,.F.)
    	       Oserver:CreateOrder(cTAG,CDIRE+cARQ,cIND,,.F.)

	       ELSE
    	      oSERVER:CreateIndex(CDIRE+cARQ,cIND,,.F.)
	       ENDIF
	   NEXT X
	   oSERVER:CLOSE()
    ELSE
    	alert("Falta Arquivo " +ZCURDIR+cORI+".DBF")
    ENDIF	
ENDIF
RETU .T.

FUNCTION RDTBAIXA(cCODIGO,nSEQ,nSSQ,cARQ,cARQBX)
LOCAL oSERVER,oBAIXA AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nFIELD,J AS DWORD

cCODIGO:=AllTrim(cCODIGO)

aDAD:={zCURINI,cARQ,zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETURN .f.
ENDIF
aDAD:={zCURINI,cARQBX,zCURDIR}
oBAIXA:=USEREDE{aDAD}
IF oBAIXA:nERRO#0
   oSERVER:CLOSE()
   RETURN .f.
ENDIF
nFIELD:=oSERVER:FCOUNT
oSERVER:GOTOP()
oSERVER:SEEK(cCODIGO)
WHILE cCODIGO=AllTrim(oSERVER:FIELDGET("CODIGO")) .AND. ! oSERVEr:EoF
   IF (nSEQ=0) .OR. (nSEQ=oSERVER:FIELDGET("SEQ") .AND. nSSQ=oSERVER:FIELDGET("SSQ"))
   	  //aDADOS:={}
      oBAIXA:Append()
      FOR J:=1 TO nFIELD
          oBAIXA:FIELDPUT(oSERVER:FieldName(J),oSERVER:FIELDGET(oSERVER:FieldName(J)))
      NEXT J
      oBAIXA:FIELDPUT("DATABAI",Today())
     oSERVER:DELETE()
   ENDIF
   oSERVER:SKIP()
ENDDO	
oSERVER:PACK()
oSERVER:CLOSE()
oBAIXA:CLOSE()


