PARTIAL CLASS JRD
METHOD APPEND() 
LOCAL nSEQ AS DWORD
SELF:server:setorder(1)
SELF:server:gobottom()
nSEQ:=SELF:Server:SEQ
nSEQ++
SUPER:append()
SELF:SERVER:FIELDPUT(#SEQ,nSEQ)
RETU SELF


METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()


METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("PR","")	

METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD EQITENS() 
LOCAL oJRDE AS JRDE
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"RDE.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
nSEQ:=SELF:SERVER:FIELDGET(#SEQ)
oJRDE:=JRDE{SELF}
oJRDE:USE(oSERVER)
SELF:SetSelectiveRelation(oJRDE,Str(nSEQ,3))
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
oJRDE:SHOW()
RETU SELF

METHOD FUITENS() 
LOCAL oJRDF AS JRDF
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"RDF.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
nSEQ:=SELF:SERVER:FIELDGET(#SEQ)
oJRDF:=JRDF{SELF}
oJRDF:USE(oSERVER)
SELF:SetSelectiveRelation(oJRDF,Str(nSEQ,3))
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
oJRDF:SHOW()
RETU SELF

METHOD PAITENS() 
LOCAL oJRDP AS JRDP
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"RDP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
nSEQ:=SELF:SERVER:FIELDGET(#SEQ)
oJRDP:=JRDP{SELF}
oJRDP:USE(oSERVER)
SELF:SetSelectiveRelation(oJRDP,Str(nSEQ,3))
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
oJRDP:SHOW()
RETU SELF


METHOD PEGCOM() 
SELF:server:ano:=Year(SELF:server:DIAINI)
SELF:server:mes:=Month(SELF:server:diafim)
SELF:server:DESCRI:=MESSTR(SELF:server:mes,SELF:server:ano,1,2)
SELF:server:DESCR2:=MESSTR(SELF:server:mes,SELF:server:ano,1,1)	

METHOD POITENS() 
LOCAL oJRDPD AS JRDPD
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
aDAD:={zCURINI,"RDP.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
nSEQ:=SELF:SERVER:FIELDGET(#SEQ)
oJRDPD:=JRDPD{SELF}
oJRDPD:USE(oSERVER)
SELF:SetSelectiveRelation(oJRDPD,Str(nSEQ,3))
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
oJRDPD:SHOW()
RETU SELF

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   	    FabCenterWindow( SELF )
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()



END CLASS
