CLASS XIMPPF INHERIT jIMPPF

CONSTRUCTOR(oOWNER) 
IF ! entramenu("PRO",3)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:SHOW()	

END CLASS
CLASS XINDEXAR INHERIT INDEXAR

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("PRO",2)
	RETU SELF
ENDIF	
SUPER(oOWNER,cHELP)
SELF:SHOW()	

METHOD PushButton1() 
SELF:POINTER:=POINTER{POINTERHOURGLASS}
CRIANTX({ZCURINI,"RD.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RDE.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RDF.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RDP.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RDPD.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RDPT.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RDT.DBF",ZCURDIR})
CRIANTX({ZCURINI,"RDTBX.DBF",ZCURDIR})
CRIANTX({ZCURINI,"IACSEQ.DBF",ZCURDIR})
SELF:POINTER:=POINTER{}
SELF:ENDWINDOW()

END CLASS
CLASS XJANCLI INHERIT JANCLI

CONSTRUCTOR(oOWNER) 
LOCAL aDAD AS ARRAY
LOCAL oSERVER AS USEREDE	
IF ! entramenu("PRO",4)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MA01.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:oDCGRUPOEMP:READONLY:= FALSE
SELF:oDCGRUPOEMP:ENABLE()
SELF:oDCCODIGOINT:READONLY:=FALSE
SELF:oDCCODIGOINT:ENABLE()
SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:oDCNOME:READONLY:=FALSE
//SELF:oDCNOME:ENABLE()
//SELF:oDCCOGNOME:READONLY:=FALSE
//SELF:oDCCOGNOME:ENABLE()
//SELF:oDCESTADO:READONLY:=FALSE
//SELF:oDCESTADO:ENABLE()
SELF:SHOW()	


END CLASS
PARTIAL CLASS XJBXCOM INHERIT JMESANO

CONSTRUCTOR(oOWNER) 
LOCAL nMES,nANO AS DWORD	
IF ! entramenu("PRO",6)
	RETU SELF
ENDIF	
SUPER(oOWNER)
nMES:=Month(ZDATA)
nANO:=Year(ZDATA)
SELF:MES:=StrZero(nMES,2)
SELF:ANO:=StrZero(nANO,4)
SELF:Caption:="Baixar Competencia Tempos Apurados"
SELF:SHOW()	

END CLASS
PARTIAL CLASS XJBXNAO INHERIT JBXNAO	

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("PRO",6)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:AoCodigo:=Repl("Z",24)
SELF:SHOW()	
		

END CLASS
PARTIAL CLASS XJBXOBS INHERIT JBXNAO		

CONSTRUCTOR(oOWNER) 
IF ! entramenu("PRO",6)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:AoCodigo:=Repl("Z",24)
SELF:SHOW()	
				

END CLASS
PARTIAL CLASS XJBXSEQ INHERIT JBXSEQ

CONSTRUCTOR(oOWNER) 
IF ! ENTRAMENU("PRO",6)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:SHOW()	

END CLASS
CLASS XJIACMES INHERIT JIACMES	

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS DBSERVER
LOCAL cARQ AS STRING
LOCAL oJAN AS JMESANO
IF ! entramenu("PRO",7)
	RETU SELF
ENDIF	
oJAN:=JMESANO{oOWNER}
oJAN:SHOW()
cARQ:="IC"+StrZero(oJAN:NANO,4)+StrZero(oJAN:nMES,2)
IF ! File(cARQ+".DBF")
   alert("Mes Nao Aberto")	
   RETU SELF
ENDIF	
oSERVER:=DBSERVER{CARQ,,,"DBFCDX"}
IF ! oSERVER:USED
   RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
SELF:SERVER:GoBottom()
SELF:SHOW()

END CLASS
CLASS XJIACSEQ INHERIT JIACSEQ

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PRO",7)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"IACSEQ.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
SELF:SERVER:GoBottom()
SELF:SHOW()



END CLASS
CLASS XJRD INHERIT JRD

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("PRO",1)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RD.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
SELF:SERVER:GoBottom()
SELF:SHOW()

END CLASS
CLASS XJRDT INHERIT JRDT

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("PRO",5)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RDT.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
SELF:SHOW()	


END CLASS
CLASS XJRDTBX INHERIT JRDT

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! ENTRAMENU("PRO",5)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"RDTBX.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:ViewTable()
SELF:SHOW()	

END CLASS
PARTIAL CLASS XJRTCOM INHERIT JMESANO	

CONSTRUCTOR(oOWNER) 
LOCAL nMES,nANO AS DWORD	
IF ! entramenu("PRO",6)
	RETU SELF
ENDIF	
SUPER(oOWNER)
nMES:=Month(ZDATA)
nANO:=Year(ZDATA)
SELF:MES:=StrZero(nMES,2)
SELF:ANO:=StrZero(nANO,4)
SELF:Caption:="Retornar Competencia Tempos Apurados"
SELF:SHOW()	


END CLASS
PARTIAL CLASS XJRTSEQ INHERIT JBXSEQ	

CONSTRUCTOR(oOWNER) 
IF ! entramenu("PRO",6)
	RETU SELF
ENDIF	
SUPER(oOWNER)
SELF:SHOW()		
END CLASS

