CLASS XJCHIS INHERIT JCHIS

METHOD BNumero( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RH","HIS")	


METHOD FOTO( ) 
LOCAL cDIRFOTO AS STRING
LOCAL cCPF AS STRING
LOCAL cARQ AS STRING
LOCAL nFout AS PTR
cCPF:=SELF:SERVER:FIELDGET("CPF")
IF Valcpf(cCPF)
	cDIRFOTO :=PEGINIVAL(ZCURINI,"FOTOS","FUNJPGCPF")		
	cDIRFOTO+=StrZero(Val(TIRAOUT(cCPF)),11)+".jpg"
ENDIF
cARQ:=PEGINIVAL(ZCURINI,"PATH","IMGJPG")
nFout := ShellExecute(SELF:owner:handle(),String2Psz("open"),String2Psz("IMGJPG"),String2Psz(CCPF+"#"+cDIRFOTO+"${IMGMP04CPF}"),String2Psz(carq),SW_SHOWNORMAL)
ShellExecuteErro(nFout) 


METHOD foto1( ) 	
LOCAL OFOTOVIEW AS FOTOVIEW
LOCAL cDIRFOTO,cTITULO AS STRING	
cDIRFOTO:=PEGINIVAL(ZCURINI,"FOTOS","FUNBMP")	
CDIRFOTO:=CAMINEX(cDIRFOTO,ZMES,ZANO,ZEMPRESA)
cDIRFOTO:=cDIRFOTO+StrZero(SELF:SERVER:FIELDGET("NUMERO"),4)+".BMP"
cTITULO:=Str(SELF:SERVER:FIELDGET("NUMERO"))+"-"+SELF:SERVER:FIELDGET("NOME")
OFOTOVIEW:=fotoview{SELF,cDIRFOTO,cTITULO}
OFOTOVIEW:SHOW()

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aCOM AS ARRAY
IF ! entramenu("RH",7)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"FO_CHIS.DBF",zCURDIR}
aCOM:={zMES,zANO,ZEMPRESA}
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	


END CLASS
