PARTIAL CLASS JFUN_TAB1
METHOD PEGMP02() 
RETU PEGCOMBO("MP02.DBF","NOME","CODIGO")

METHOD PEGMP05() 
RETU PEGCOMBO("MP05.DBF","DESCRI","CODIGO")

METHOD PostInit(oWindow,iCtlID,oServer,uExtra) 
	//Put your PostInit additions here
    SELF:oDCTABTEC:FillUsing(SELF:PEGMP02( ))
    SELF:oDCAREA:FillUsing(SELF:PEGMP05())	
	RETURN NIL



END CLASS
