PARTIAL CLASS jterh
METHOD APPEND(oOWNER) 
LOCAL oBUSCA AS xBUSCA
LOCAL oERRO AS ERRORBOX
LOCAL nTECNICO AS DWORD
oBUSCA:=xBUSCA{oOWNER,"Incluier","Digite o Codigo"}
oBUSCA:lMES:=.T.
oBUSCA:SHOW()
IF ! Obusca:lOK
   RETURN .F.
ENDIF	
nTECNICO:=Val(oBUSCA:cBUSCA)
SELF:server:setorder(1)
SELF:server:gotop()
IF ! SELF:server:seek(nTECNICO)
	SELF:SERVER:SUSPENDNOTIFICATION()
    SUPER:append()
    SELF:SERVER:FIELDPUT("TECNICO",nTECNICO)
    SELF:SERVER:FIELDPUT("CNUMERO",StrZero(SELF:sERVER:TECNICO,8))
	SELF:SERVER:resetnotification()
	SELF:SERVER:notify(notifyappend)
ELSE
	oERRO:=ERRORBOX{oOWNER,"Já Cadastrado"}
    oERRO:Show()	
ENDIF	
RETURN	 .F.
	


METHOD BNumero( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("RH","CAD")	


METHOD ESCCUR 
LOCAL oJAN AS XESCCUR
oJAN:=XESCCUR{SELF,ZCURINI,ZCURDIR,"CURSO.DBF"}
oJAN:SHOW()
IF oJAN:lOK
   SELF:oDCCURSO:TextValue:=oJAN:CODIGO
ENDIF

METHOD EXCLUIR 
IF  MDG("Apagar Registro") .AND. SELF:osfjmp04c:server:LockCurrentRecord()
    SELF:osfjmp04c:server:delete()
    SELF:osfjmp04c:server:unlock()
    SELF:oSFJmp04c:server:GOTOP()		
	WHILE ! SELF:oSFJmp04c:serveR:EOf
		SELF:oSFJmp04c:server:Skip()
    ENDDO		
    SELF:oSFJmp04c:server:GOTOP()	
 ENDIF	
SELF:oSFjmp04C:Browser:REFRESH()


METHOD EXCLUIR1 
IF  MDG("Apagar Registro") .AND. SELF:osfjmp04A:server:LockCurrentRecord()
    SELF:osfjmp04A:server:delete()
    SELF:osfjmp04A:server:unlock()
    SELF:oSFJmp04A:server:GOTOP()		
	WHILE ! SELF:oSFJmp04A:serveR:EOf
		SELF:oSFJmp04A:server:Skip()
    ENDDO		
    SELF:oSFJmp04A:server:GOTOP()	
 ENDIF	
SELF:oSFjmp04A:Browser:REFRESH()

METHOD foto( ) 
LOCAL cDIRFOTO AS STRING
LOCAL cCPF AS STRING
LOCAL cARQ AS STRING
LOCAL nFout AS PTR
cCPF:=SELF:SERVER:FIELDGET("CPF")
IF Valcpf(cCPF)
	cDIRFOTO :=PEGINIVAL(ZCURINI,"FOTOS","FUNJPGCPF")		
	cDIRFOTO+=StrZero(Val(TIRAOUT(cCPF)),11)+".jpg"
ENDIF
cARQ:=PEGINIVAL(ZCURINI,"PATH","IMGJPG")
nFout := ShellExecute(SELF:owner:handle(),String2Psz("open"),String2Psz("IMGJPG"),String2Psz(CCPF+"#"+cDIRFOTO+"${IMGMP04CPF}"),String2Psz(carq),SW_SHOWNORMAL)
ShellExecuteErro(nFout) 


METHOD foto1( ) 
LOCAL OFOTOVIEW AS FOTOVIEW
LOCAL cDIRFOTO,cTITULO AS STRING
cDIRFOTO:=PEGINIVAL(ZCURINI,"FOTOS","FUNJPGCPF")		
cDIRFOTO:=cDIRFOTO+StrZero(Val(TIRAOUT(SELF:SERVER:FIELDGET("CPF"))),11)+".JPG"	
cTITULO:="CPF:"+SELF:SERVER:FIELDGET("CPF")+"-"+SELF:SERVER:FIELDGET("NOMTEC")	
OFOTOVIEW:=fotoview{SELF,cDIRFOTO,cTITULO}
OFOTOVIEW:SHOW()		

METHOD IMPORTAR( ) 	
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aCOM AS ARRAY
LOCAL nEMP AS DWORD
nEMP:=ZEMPRESA
IF SELF:OLDEMP<>0
   nEMP:=SELF:OLDEMP	
ENDIF	

aDAD:={zCURINI,"TREII.DBF",zCURDIR}
aCOM:={zMES,zANO,NEMP}
//Init(aDAD, lShareMode, lReadOnlyMode, cDriver, aCOM)
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF
SELF:osfjmp04A:SERVER:SUSPENDNOTIFICATION()
oSERVER:SetOrder(2)
oSERVER:GOTOP()
oSERVER:SEEK(SELF:antigo)
WHILE SELF:antigo=oSERVER:FIELDGET("NUMFUN"	) .AND. ! oSERVEr:EoF
   SELF:osfjmp04A:SERVER:APPEND()
   SELF:osfjmp04A:SERVER:FIELDPUT("TECNICO",SELF:SERVER:FIELDGET("TECNICO"))
   SELF:osfjmp04A:SERVER:FIELDPUT("NUMANT",oSERVER:FIELDGET("NUMFUN"))
   SELF:oSFjmp04a:SERVER:FIELDPUT("TREIN",oSERVER:FIELDGET("TREIN"))
   SELF:osfjmp04A:SERVER:commit()
   oSERVER:SKIP()
ENDDO	
oSERVER:CLOSE()
aDAD:={zCURINI,"TREIN.DBF",zCURDIR}
aCOM:={zMES,zANO,NEMP}
//Init(aDAD, lShareMode, lReadOnlyMode, cDriver, aCOM)
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF
SELF:oSFjmp04a:SERVER:GOTOP()
WHILE ! SELF:oSFjmp04a:SERVER:EOF
   oSERVER:GOTOP()
   IF oSERVER:SEEK(SELF:osfjmp04A:SERVER:FIELDGET("TREIN"))		
      SELF:osfjmp04A:SERVER:CURSO:=oSERVER:FIELDGET("CURSO")
      SELF:osfjmp04A:SERVER:DESCUR:=oSERVER:FIELDGET("DESCUR")
   ENDIF
   SELF:oSFjmp04a:SERVER:skip()
ENDDO
oSERVER:CLOSE()
SELF:osfjmp04A:SERVER:resetnotification()
SELF:osfjmp04A:SERVER:notify(notifyfilechange)
SELF:oSFjmp04A:Browser:REFRESH()

METHOD importar1( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aCOM AS ARRAY
LOCAL nEMP AS DWORD
nEMP:=ZEMPRESA
IF SELF:OLDEMP1<>0
   nEMP:=SELF:OLDEMP1
ENDIF
aDAD:={zCURINI,"MP04C.DBF",zCURDIR}
aCOM:={zMES,zANO,nEMP}
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF
SELF:osfjmp04c:SERVER:SUSPENDNOTIFICATION()
oSERVER:SetOrder(1)
oSERVER:GOTOP()
oSERVER:SEEK(SELF:antigo1)
WHILE SELF:antigo1=oSERVER:FIELDGET("TECNICO") .AND. ! oSERVEr:EoF
   SELF:osfjmp04c:SERVER:APPEND()
   SELF:osfjmp04c:SERVER:FIELDPUT("TECNICO",SELF:SERVER:FIELDGET("TECNICO"))
   SELF:osfjmp04c:SERVER:FIELDPUT("NUMANT",oSERVER:FIELDGET("TECNICO"))
   SELF:oSFjmp04c:SERVER:FIELDPUT("TREIN",oSERVER:FIELDGET("TREIN"))
   SELF:oSFjmp04c:SERVER:FIELDPUT("CURSO",oSERVER:FIELDGET("CURSO"))
   SELF:oSFjmp04c:SERVER:FIELDPUT("DESCUR",oSERVER:FIELDGET("DESCUR"))
   SELF:osfjmp04c:SERVER:commit()
   oSERVER:SKIP()
ENDDO	
oSERVER:CLOSE()
SELF:oSFjmp04c:Browser:REFRESH()

METHOD importar2( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aCOM AS ARRAY
LOCAL nEMP AS DWORD
nEMP:=ZEMPRESA
IF SELF:OLDEMP<>0
   nEMP:=SELF:OLDEMP	
ENDIF	
aDAD:={zCURINI,"MP04A.DBF",zCURDIR}
aCOM:={zMES,zANO,nEMP}
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
   RETU SELF
ENDIF
SELF:osfjMP04A:SERVER:SUSPENDNOTIFICATION()
oSERVER:SetOrder(1)
oSERVER:GOTOP()
oSERVER:SEEK(SELF:antigo)
WHILE SELF:antigo=oSERVER:FIELDGET("TECNICO") .AND. ! oSERVEr:EoF
   SELF:osfjMP04A:SERVER:APPEND()
   SELF:osfjMP04A:SERVER:FIELDPUT("TECNICO",SELF:SERVER:FIELDGET("TECNICO"))
   SELF:osfjMP04A:SERVER:FIELDPUT("NUMANT",oSERVER:FIELDGET("TECNICO"))
   SELF:oSFjMP04A:SERVER:FIELDPUT("TREIN",oSERVER:FIELDGET("TREIN"))
   SELF:oSFjMP04A:SERVER:FIELDPUT("CURSO",oSERVER:FIELDGET("CURSO"))
   SELF:oSFjMP04A:SERVER:FIELDPUT("DESCUR",oSERVER:FIELDGET("DESCUR"))
   SELF:osfjMP04A:SERVER:commit()
   oSERVER:SKIP()
ENDDO	
oSERVER:CLOSE()
SELF:oSFjMP04A:Browser:REFRESH()	

METHOD INCLUIR 
LOCAL nNUMERO AS DWORD
LOCAL cCURSO AS STRING
LOCAL aCUR AS ARRAY
LOCAL oERRO AS ERRORBOX
nNUMERO:=SELF:SERVER:TECNICO
cCURSO:=SELF:CURSO
IF Empty(SELF:CURSO)
   oERRO:=ERRORBOX{SELF,"Codigo Curso em Branco"}
   oERRO:SHOW()
   RETU NIL
ENDIF
aCUR:=PEGCUR(SELF:CURSO)
IF aCUR[1]=.F.
   oERRO:=ERRORBOX{SELF,"Curso não Cadastrado"}
   oERRO:SHOW()
   RETU NIL
ENDIF
SELF:osfjmp04c:SERVER:SUSPENDNOTIFICATION()
SELF:osfjmp04c:SERVER:APPEND()
SELF:osfjmp04c:SERVER:TECNICO:=nNUMERO
SELF:osfjmp04c:SERVER:CURSO:=cCURSO
SELF:osfjmp04c:SERVER:DESCUR:=aCUR[2]
SELF:osfjmp04c:SERVER:commit()
SELF:osfjmp04c:SERVER:resetnotification()
SELF:osfjmp04c:SERVER:notify(notifyappend)
SELF:oSFjmp04C:Browser:REFRESH()


METHOD INCLUIR1 
LOCAL nNUMERO AS DWORD
LOCAL cCURSO AS STRING
LOCAL aCUR AS ARRAY
LOCAL oERRO AS ERRORBOX
nNUMERO:=SELF:SERVER:TECNICO
cCURSO:=SELF:CURSO
IF Empty(SELF:CURSO)
   oERRO:=ERRORBOX{SELF,"Codigo Curso em Branco"}
   oERRO:SHOW()
   RETU NIL
ENDIF
aCUR:=PEGCUR(SELF:CURSO)
IF aCUR[1]=.F.
   oERRO:=ERRORBOX{SELF,"Curso não Cadastrado"}
   oERRO:SHOW()
   RETU NIL
ENDIF
SELF:osfjmp04A:SERVER:SUSPENDNOTIFICATION()
SELF:osfjmp04A:SERVER:APPEND()
SELF:osfjmp04A:SERVER:TECNICO:=nNUMERO
SELF:osfjmp04A:SERVER:CURSO:=cCURSO
SELF:osfjmp04A:SERVER:DESCUR:=aCUR[2]
SELF:osfjmp04A:SERVER:commit()
SELF:osfjmp04A:SERVER:resetnotification()
SELF:osfjmp04A:SERVER:notify(notifyappend)
SELF:oSFjmp04A:Browser:REFRESH()


METHOD matant( ) 
LOCAL nNUMERO AS DWORD	
nNUMERO:=SELF:osfjMP04A:SERVER:FIELDGET("NUMANT")
SELF:SERVER:SETORDER(1)
SELF:SERVER:GOTOP()
SELF:SERVER:SEEK(nNUMERO)
IF SELF:server:Eof
  SELF:server:gotop()
ENDIF	

METHOD matant1( ) 
LOCAL nNUMERO AS DWORD	
nNUMERO:=SELF:osfjMP04C:SERVER:FIELDGET("NUMANT")
SELF:SERVER:SETORDER(1)
SELF:SERVER:GOTOP()
SELF:SERVER:SEEK(nNUMERO)
IF SELF:server:Eof
  SELF:server:gotop()
ENDIF		

METHOD pegcurdes( ) 
LOCAL aPRO AS ARRAY
LOCAL cCOD
cCOD:=SELF:osfjmp04c:SERVER:FIELDGET("CURSO")
IF ! Empty(cCOD)
   aPRO:=PEGCUR(cCOD,ZCURINI,ZCURDIR)
   IF aPRO[1]=.T.
      SELF:osfjmp04c:SERVER:FIELDPUT("DESCUR",aPRO[2])
   ENDIF	
ENDIF		





METHOD pegcurdes1( ) 
LOCAL aPRO AS ARRAY
LOCAL cCOD
cCOD:=SELF:osfjMP04A:SERVER:FIELDGET("CURSO")
IF ! Empty(cCOD)
   aPRO:=PEGCUR(cCOD,ZCURINI,ZCURDIR)
   IF aPRO[1]=.T.
      SELF:osfjMP04A:SERVER:FIELDPUT("DESCUR",aPRO[2])
   ENDIF	
ENDIF			


METHOD PORnumero() 
SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
   SELF:OLDEMP:=ZEMPRESA
   SELF:OLDEMP1:=ZEMPRESA
    FabCenterWindow( SELF ) 
    
    oDCTABTEC:FillUsing(PEGCOMBO("MP02.DBF","NOME","CODIGO"))

oDCAREA:FillUsing(PEGCOMBO("MP05.DBF","DESCRI","CODIGO") )

oDCSETOR:FillUsing(PEGCOMBO("MP06.DBF","NOME","CODIGO"))

oDCARE2:FillUsing(PEGCOMBO("MP05.DBF","DESCRI","CODIGO") )

oDCESCRAIS:FillUsing(PEGCOMBO("RHESC.DBF","DESCRI","CODIGO"))

    
 RETURN SELF

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFjmp04a:SERVER:Commit()
   SELF:oSFjmp04c:SERVER:COMMIT()





END CLASS
