CLASS XJCHIS INHERIT JCHIS

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aCOM AS ARRAY
IF ! entramenu("RH",7)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"FO_CHIS.DBF",zCURDIR}
aCOM:={zMES,zANO,ZEMPRESA}
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	

END CLASS
CLASS XJFALTA INHERIT JFALTA	

CONSTRUCTOR(oOWNER) 
//LOCAL oSERVER AS USEFOLHA
//oSERVER:=USEFOLHA{"TABFALTA"}
//IF oSERVER:nERRO#0
//    RETU SELF
//ENDIF
//SUPER(oOWNER)
//SELF:Browser:SetStandardStyle(gBsreadonly)
//SELF:USE(oSERVER)
//SELF:SHOW()
LOCAL oSERVER AS USEREDE
LOCAL aDAD,aCOM AS ARRAY


aDAD:={zCURINI,"TABFALTA.DBF",zCURDIR}
aCOM:={zMES,zANO,ZEMPRESA}
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()	



END CLASS
CLASS XJTEC INHERIT JTERH

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER,oSERVE2,oSERVE3 AS USEREDE
LOCAL aDAD,ACOM AS ARRAY
IF ! entramenu("RH",3)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MP04.DBF",zCURDIR}
aCOM:={zMES,zANO,ZEMPRESA}
oSERVER:=USEREDE{aDAD,,,,aCOM}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"MP04C.DBF",zCURDIR}
aCOM:={zMES,zANO,ZEMPRESA}
oSERVE2:=USEREDE{aDAD,,,,aCOM}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
aDAD:={zCURINI,"MP04A.DBF",zCURDIR}
aCOM:={zMES,zANO,ZEMPRESA}
oSERVE3:=USEREDE{aDAD,,,,aCOM}
IF oSERVE3:nERRO#0
   oSERVE2:CLOSE()
   oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF

SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:oSFjmp04c:USE(oSERVE2)
SELF:SetSelectiveRelation(oSFJMP04C,"TECNICO")
SELF:oSFjmp04A:USE(oSERVE3)
SELF:SetSelectiveRelation(oSFJMP04A,"TECNICO")
SELF:SHOW()



END CLASS
