PARTIAL CLASS JME4CC
METHOD ALTERAR  
IF ! Empty(SELF:server:FIELDGET("LAUDOD"))
   alert("Já Fechada")
ENDIF	
SELF:oSFJME4CCI:VIEWFORM()

METHOD ANTERIOR 
SELF:oSFJME4CCI:Browser:SuspendUpdate()
SELF:oSFJME4CCI:SkipPREVIOUS()
IF SELF:oSFJME4CCI:Server:BOF
	SELF:oSFJME4CCI:SkipNEXT()
ENDIF
SELF:oSFJME4CCI:Browser:RestoreUpdate()
	


METHOD APPEND 
LOCAL oBUSCA AS XBUSCA
LOCAL cNUMERO AS STRING
LOCAL nNUMERO AS DWORD
IF PEGINIVAL(ZCURINI,"ME4CC.DBF","INCLUI")="N"
   alert("Inclusao Bloqueada")
   RETURN   .f.
ENDIF
SELF:SERVER:SETORDER(1)
SELF:SERVER:GoBottom()
nNUMERO:=SELF:SERVER:FIELDGET("NUMERO")
nNUMERO++
cNUMERO:=Str(nNUMERO)
oBUSCA:=XBUSCA{SELF,"Incluindo","Confirme o Numero",cNUMERO}
oBUSCA:SHOW()	
IF ! oBUSCA:lOK
   RETURN .f.
ENDIF	
nNUMERO:=Val(oBUSCA:cBUSCA)
IF nNUMERO=0
   alert("Numero Em Branco")	
   RETURN .f.
ENDIF
SELF:server:gotop()
IF SELF:server:seek(nNUMERO)
   alert("Numero Ja Cadastrado")
   RETURN .f.
ENDIF
SELF:SERVER:SUSPENDNOTIFICATION()
SUPER:append()
SELF:SERVER:FIELDPUT("NUMERO",nNUMERO)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("NUMTEC",ZFOLHA)
SELF:SERVER:resetnotification()
SELF:SERVER:notify(notifyappend)

METHOD buscaoc( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("M4","CC")	

METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:server:LockCurrentRecord()
  	 SELF:oSFJME4CCI:SERVER:SUSPENDNOTIFICATION()
    SELF:oSFJME4CCI:server:GOTOP()	
    WHILE ! oSFJME4CCI:server:EOF
		SELF:oSFJME4CCI:server:delete()
    ENDDO	
    SELF:oSFJME4CCI:SERVER:resetnotification()
    SELF:oSFJME4CCI:SERVER:notify(notifyfilechange)	
    SUPER:delete()
    SELF:server:unlock()
    SELF:server:skipEX(-1)
ENDIF	
	
	


METHOD duplicar( ) 
LOCAL nNUMERO AS DWORD
LOCAL nFIELD,J,K AS WORD
LOCAL aITENS,aTMP,aDADOS AS ARRAY

AltD()

nFIELD:=SELF:SERVER:FCOUNT
aDADOS:={}
FOR J:=1 TO nFIELD
    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
NEXT J
aITENS:={}
nFIELD:=SELF:oSFJME4CCI:server:FCOUNT
SELF:oSFJME4CCI:server:GOTOP()
WHILE ! oSFJME4CCI:server:EOF
    aTMP:={}
    FOR J:=1 TO nFIELD
       AAdd(aTMP,SELF:oSFJME4CCI:server:FIELDGET(J))
    NEXT J
    AAdd(aITENS,aTMP)
   SELF:oSFJME4CCI:server:SKIP()
ENDDO
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:FIELDGET("NUMERO")
nNUMERO++
SUPER:SERVER:APPEND()
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    SELF:SERVER:FIELDPUT(J,aDADOS[J])
NEXT J
SELF:SERVER:FIELDPUT("NUMERO",nNUMERO)
SELF:SERVER:FIELDPUT("DATA",Today())
nFIELD:=SELF:oSFJME4CCI:server:FCOUNT
FOR K:=1 TO ALen(aITENS)
    SELF:oSFJME4CCI:server:APPEND()
    FOR J:=1 TO nFIELD
        SELF:oSFJME4CCI:server:FIELDPUT(J,aITENS[K][J])
    NEXT J
    SELF:oSFJME4CCI:server:FIELDPUT("NUMERO",nNUMERO)
    SELF:oSFJME4CCI:server:FIELDPUT("LAUDO","")
    SELF:oSFJME4CCI:server:FIELDPUT("INCTOT","")
    SELF:oSFJME4CCI:server:FIELDPUT("ENCONTRA","")
    SELF:oSFJME4CCI:server:FIELDPUT("TENDENCIA","")
NEXT K
SELF:server:gotop()
SELF:server:gobottom()
RETURN .t.
	

METHOD ediINS( ) 
SELF:EDITME04(SELF:SERVER:FIELDGET("CODME04"))	

METHOD ediTIP( ) 
SELF:EDITME04(SELF:SERVER:FIELDGET("CODME04A"))	

METHOD editme04(cCODIGO) 	
LOCAL oJAN AS XJme04
IF ! entramenu("INS",1)
	RETU SELF
ENDIF	
oJAN:=XJme04{SELF,cCODIGO,zCURINI,zCURDIR}
oJAN:SHOW()	

METHOD ESCINS( ) 
LOCAL oJAN AS XESCME04
//LOCAL cFILTRO AS STRING
//cFILTRO:="CODTIPO<>'DC' .AND. CODTIPO<>'CCL'"
oJAN:=XESCME04{SELF}
oJAN:SHOW()
IF oJAN:lOK
   SELF:SERVEr:FIELDPUT("CODME04",oJAN:cCODIGO)	
   SELF:SERVER:FIELDPUT("NOMME04",oJAN:cNOME)
ENDIF	

METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("NUMTEC",oESCMP04:NUMERO)
   SELF:SERVER:FIELDPUT("NOMTEC",oESCMP04:NOME)
ENDIF

METHOD ESCTIP( ) 
LOCAL oJAN AS XESCME04
LOCAL cFILTRO AS STRING
cFILTRO:="CODTIPO='DC' .OR. CODTIPO='CCL'"
oJAN:=XESCME04{SELF,cFILTRO}
oJAN:SHOW()
IF oJAN:lOK
   SELF:SERVEr:FIELDPUT("CODME04A",oJAN:cCODIGO)	
ENDIF	

METHOD EXCLUIR 
IF ! Empty(SELF:server:FIELDGET("LAUDOD"))
   alert("Já Fechada")
ENDIF
SELF:oSFJME4CCI:SERVER:SUSPENDNOTIFICATION()
IF  MDG("Apagar Registro") .AND. SELF:oSFJME4CCI:server:LockCurrentRecord()
    SELF:oSFJME4CCI:server:delete()
    SELF:oSFJME4CCI:server:unlock()
    SELF:oSFJME4CCI:server:skip(-1)
ENDIF	
SELF:oSFJME4CCI:server:GOTOP()
WHILE !  oSFJME4CCI:server:EOF
  SELF:oSFJME4CCI:server:SKIP()
ENDDO
SELF:oSFJME4CCI:server:GOTOP()
SELF:oSFJME4CCI:SERVER:resetnotification()
SELF:oSFJME4CCI:SERVER:notify(notifyfilechange)

METHOD INCLUIR 
IF ! Empty(SELF:server:FIELDGET("LAUDOD"))
   alert("Já Fechada")
ENDIF	
SELF:oSFJME4CCI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJME4CCI:SERVER:APPEND()
SELF:oSFJME4CCI:SERVER:FIELDPUT("NUMERO",SELF:SERVER:NUMERO)
SELF:oSFJME4CCI:SERVER:commit()
SELF:oSFJME4CCI:SERVER:resetnotification()
SELF:oSFJME4CCI:SERVER:notify(notifyappend)

METHOD LaudNao( ) 
SELF:oSFJME4CCI:server:GOTOP()
WHILE !  oSFJME4CCI:server:EOF
  IF  Empty(SELF:oSFJME4CCI:server:FIELDGET("LAUDO"))
  	  alert("Não Preenchido Laudo Item")
  	  RETURN .f.
  ENDIF	
  SELF:oSFJME4CCI:server:SKIP()
ENDDO
IF Empty(SELF:SERVER:FIELDGET("LAUDOD"))
   SELF:SERVEr:FIELDPUT("LAUDOD",Today())	
ENDIF		
IF SELF:SERVER:FIELDGET("LAUDOF")="N"
   alert("Necessita Plano de Reação")
ENDIF
SELF:SERVER:FIELDPUT("NUMTEC",ZFOLHA)
SELF:SERVER:FIELDPUT("LAUDOF","N")
SELF:PEGres()

METHOD LaudoNAO( ) 
IF ! Empty(SELF:server:FIELDGET("LAUDOD"))
   alert("Já Fechada")
ENDIF	
SELF:oSFJME4CCI:server:FIELDPUT("LAUDO","N")

METHOD Laudosim( ) 
IF ! Empty(SELF:server:FIELDGET("LAUDOD"))
   alert("Já Fechada")
ENDIF	
SELF:oSFJME4CCI:server:FIELDPUT("LAUDO","S")

METHOD Laudsim( ) 
SELF:oSFJME4CCI:server:GOTOP()
WHILE !  oSFJME4CCI:server:EOF
  IF  Empty(SELF:oSFJME4CCI:server:FIELDGET("LAUDO"))
  	  alert("Não Preenchido Laudo Item")
  	  RETURN .f.
  ENDIF	
  IF  SELF:oSFJME4CCI:server:FIELDGET("LAUDO")="N"
  	  alert("Laudo Item Reprovado")
  	  RETURN .f.
  ENDIF	
  SELF:oSFJME4CCI:server:SKIP()
ENDDO
IF Empty(SELF:SERVER:FIELDGET("LAUDOD"))
   SELF:SERVEr:FIELDPUT("LAUDOD",Today())	
ENDIF		

SELF:SERVER:FIELDPUT("NUMTEC",ZFOLHA)
SELF:PEGres()
SELF:SERVER:FIELDPUT("LAUDOF","S")

METHOD PEGres	
LOCAL aUSO AS ARRAY	
aUSO:=PEGMP04(SELF:SERVER:FIELDGET("NUMTEC"),ZCURINI,ZCURDIR,{ZMES,ZANO,ZEMPRESA})
IF aUSO[1]=.T.
   SELF:SERVER:FIELDPUT("NOMTEC",aUSO[2])
ENDIF


METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
       FabCenterWindow( SELF )
 RETURN SELF

METHOD PROXIMO 
SELF:oSFJME4CCI:Browser:SuspendUpdate()
SELF:oSFJME4CCI:SkipNext()
IF SELF:oSFJME4CCI:Server:Eof
	SELF:oSFJME4CCI:SkipPrevious()
ENDIF
SELF:oSFJME4CCI:Browser:RestoreUpdate()

METHOD TABULAR  	
SELF:oSFJME4CCI:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJME4CCI:Server:COMMIT()



END CLASS
