CLASS xjrrm INHERIT jrrs

METHOD APPEND() 
LOCAL nRRS AS DWORD
IF PEGINIVAL(ZCURINI,"RRM.DBF","INCLUI")="N"
   alert("Inclusao Bloqueada")
   RETURN    .f.
ENDIF

SELF:server:setorder(1)
SELF:server:gobottom()
nRRS:=SELF:Server:FIELDGET("RRS")
nRRS++
SUPER:append()
SELF:SERVER:FIELDPUT("RRS",nRRS)
SELF:server:FIELDPUT("data",Today())
SELF:server:FIELDPUT("K01",0.8862)
SELF:server:FIELDPUT("K02",0.7071)
SELF:server:FIELDPUT("K03",0.4030)
RETURN         .t.


METHOD esccod( ) 
LOCAL oESC AS XESCME04
oESC:=XESCME04{SELF}
oESC:SHOW()	
IF Oesc:lok
    SELF:SERVER:FIELDPUT("DESENHO",oESC:CCODIGO)
    SELF:SERVER:FIELDPUT("DESCRI",oESC:CNOMTIPO)
ENDIF		

METHOD pegms01 
LOCAL apro AS ARRAY	
aPRO:=PEGME04(SELF:SERVER:DESENHO,zcurini,zcurdir)
IF aPRO[1]=.T.
  SELF:SERVER:DESCRI:=aPRO[2]
ENDIF

METHOD PushButton17( ) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL cCODIGO AS STRING
cCODIGO:=SELF:server:FIELDGET("CODIGO")
IF Empty(cCODIGO)
   RETU .F.
ENDIF	
aDAD:={zCURINI,"ME04.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
Oserver:gotop()
IF Oserver:seek(cCODIGO)
   oSERVER:FIELDPUT("RRMDATA",SELF:SERVER:FIELDGET("DATA"))
ENDIF	
oSERVER:CLOSE()


END CLASS
