PARTIAL CLASS JREQ
METHOD buscanum( ) 
	SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("M4","")	

METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:SERVER:LOCKcurrentrecord()
	SELF:server:delete()
	SELF:server:unlock()
	SELF:server:skip(-1)
ENDIF	

METHOD ediTIP( ) 
LOCAL oJAN AS XJme04
LOCAL cCODIGO AS STRING
IF ! entramenu("INS",1)
	RETU SELF
ENDIF	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
oJAN:=XJme04{SELF,cCODIGO,zCURINI,zCURDIR}
oJAN:SHOW()	
	


METHOD escres( ) 
LOCAL oESCMP04 AS XESCMP04
oESCMP04:=XESCMP04{SELF}
IF oESCMP04:LOK
   SELF:SERVER:FIELDPUT("CODOPER",oESCMP04:NUMERO)
ENDIF

METHOD ESCTIP( ) 
LOCAL oJAN AS XESCME04
LOCAL cFILTRO AS STRING
//cFILTRO:="CODTIPO='DC'.OR.CODTIPO='CCL'"
cFILTRO:=""
oJAN:=XESCME04{SELF,cFILTRO}
oJAN:SHOW()
IF oJAN:lOK
   SELF:SERVEr:FIELDPUT("CODIGO",oJAN:cCODIGO)	
ENDIF	

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
       FabCenterWindow( SELF ) 
       oDCAREA:FillUsing(PEGCOMBO("MP05.DBF","DESCRI","CODIGO"))

oDCSETOR:FillUsing(MTD02("SETINS",3))
 RETURN SELF

METHOD pronum( ) 
	SELF:KeyFind()

METHOD PushButton4() 
SELF:server:devolucao:=Today()

METHOD PushButton5() 
LOCAL ctime AS STRING
LOCAL nTIME AS FLOAT
cTIME:=Time()
cTIME:=Left(cTIME,2)+"."+SubStr(cTIME,4,2)
nTIME:=Val(cTIME)
SELF:SERVER:HORADEV:=nTIME

METHOD PushButton6() 
LOCAL ctime AS STRING
LOCAL nTIME AS FLOAT
cTIME:=Time()
cTIME:=Left(cTIME,2)+"."+SubStr(cTIME,4,2)
nTIME:=Val(cTIME)
SELF:SERVER:HORASAI:=nTIME


METHOD Timer() 
   SELF:SERVER:COMMIT()
END CLASS
PARTIAL CLASS XJREQ
METHOD APPEND() 
LOCAL nNUMERO AS DWORD
IF PEGINIVAL(ZCURINI,"ME04R.DBF","INCLUI")="N"
   alert("Inclusao Bloqueada")
   RETURN .t.
ENDIF
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:NUMERO
nNUMERO++
SUPER:append()
SELF:SERVER:FIELDPUT(#NUMERO,nNUMERO)
RETURN    .t.


END CLASS
PARTIAL CLASS XJREU
METHOD APPEND() 
LOCAL nNUMERO AS DWORD
IF PEGINIVAL(ZCURINI,"ME06R.DBF","INCLUI")="N"
   alert("Inclusao Bloqueada")
   RETURN  .f.
ENDIF
SELF:server:setorder(1)
SELF:server:gobottom()
nNUMERO:=SELF:Server:NUMERO
nNUMERO++
SUPER:append()
SELF:SERVER:FIELDPUT(#NUMERO,nNUMERO)
RETURN   .t.


END CLASS
