PARTIAL CLASS JOCC
METHOD ALTERAR  
SELF:oSFJOCCI:VIEWFORM()



METHOD ANTERIOR 
SELF:oSFJOCCI:Browser:SuspendUpdate()
SELF:oSFJOCCI:SkipPREVIOUS()
IF SELF:oSFJOCCI:Server:BOF
	SELF:oSFJOCCI:SkipNEXT()
ENDIF
SELF:oSFJOCCI:Browser:RestoreUpdate()

METHOD APPEND() 
LOCAL nOCC AS DWORD
IF PEGINIVAL(ZCURINI,"ME04C.DBF","INCLUI")="N"
   alert("Inclusao Bloqueada")
   RETURN    .f.
ENDIF
SELF:server:setorder(1)
SELF:server:gobottom()
nOCC:=SELF:Server:OCC
nOCC++
SUPER:append()
SELF:SERVER:FIELDPUT("OCC",nOCC)
SELF:sERVER:FIELDPUT("DATA",Today())
SELF:SERVER:Commit()
RETURN    .t.

METHOD ASSINAR 
IF Empty(SELF:OSFJOCCI:server:FIELDGET("LAUDO"))
   alert("Laudo Nao Fornecido")
   RETURN .f.
ENDIF	
IF ! Empty(SELF:OSFJOCCI:server:FIELDGET("ASSDAT"))
   alert("Laudo Já Assinado")
   RETURN .f.
ENDIF	
SELF:oSFJOCCI:SERVER:FIELDPUT("ASSDAT",Today())
SELF:oSFJOCCI:SERVER:FIELDPUT("ASSNOM",ZUSER)	
	

METHOD AssinarTo( ) 
SELF:oSFJOCCI:server:GOTOP()
WHILE !  SELF:oSFJOCCI:server:EOF
  SELF:ASSINAR()
  SELF:oSFJOCCI:server:SKIP()
ENDDO	

METHOD buscaoc( ) 
SELF:KeyFind()

METHOD cmddelfiltro() 
   SELF:xcmddelfiltro()	
  SELF:Browser:REFRESH()

METHOD CMDFILTRAR() 
	SELF:xCMDFILTRAR()
	SELF:Browser:REFRESH()

METHOD CMDimprimir( ) 
SELF:XWRPTGRP("M4","")	

METHOD DELETE() 
IF MDG("Apagar Registro") .AND. SELF:server:LockCurrentRecord()
    SELF:oSFJOCCI:server:GOTOP()	
    WHILE ! oSFJOCCI:server:EOF
    	SELF:oSFJOCCI:server:delete()
    	SELF:oSFJOCCI:Server:SKIP()
    ENDDO	
    SELF:server:delete()
    SELF:server:unlock()
    SELF:server:skip(-1)
    IF SELF:SERVER:BOF
       SELF:SERVER:GOTOP()
    ENDIF
    SELF:oSFJOCCI:Browser:refresh()
ENDIF	
	


METHOD duplicar( ) 
LOCAL nOCC AS DWORD
LOCAL nFIELD,J,K AS WORD
LOCAL aITENS,aTMP,aDADOS AS ARRAY


nFIELD:=SELF:SERVER:FCOUNT
aDADOS:={}
FOR J:=1 TO nFIELD
    AAdd(aDADOS,SELF:SERVER:FIELDGET(J))
NEXT J
aITENS:={}
nFIELD:=SELF:oSFJOCCI:server:FCOUNT
SELF:oSFJOCCI:server:GOTOP()
WHILE ! oSFJOCCI:server:EOF
    aTMP:={}
    FOR J:=1 TO nFIELD
       AAdd(aTMP,SELF:oSFJOCCI:server:FIELDGET(J))
    NEXT J
    AAdd(aITENS,aTMP)
   SELF:oSFJOCCI:server:SKIP()
ENDDO
SELF:server:setorder(1)
SELF:server:gobottom()
nOCC:=SELF:Server:FIELDGET("OCC")
nOCC++
SUPER:SERVER:APPEND()
nFIELD:=SELF:SERVER:FCOUNT
FOR J:=1 TO nFIELD
    SELF:SERVER:FIELDPUT(J,aDADOS[J])
NEXT J
SELF:SERVER:FIELDPUT("OCC",nOCC)
SELF:SERVER:FIELDPUT("DATA",Today())
SELF:SERVER:FIELDPUT("DATAP",CToD(Space(8)))
SELF:SERVER:FIELDPUT("CERTIFI","")
SELF:SERVER:FIELDPUT("NFCC",0)
nFIELD:=SELF:oSFJOCCI:server:FCOUNT
FOR K:=1 TO ALen(aITENS)
    SELF:oSFJOCCI:server:APPEND()
    FOR J:=1 TO nFIELD
        SELF:oSFJOCCI:server:FIELDPUT(J,aITENS[K][J])
    NEXT J
    SELF:oSFJOCCI:server:FIELDPUT("OCC",nOCC)
    SELF:oSFJOCCI:server:FIELDPUT("ENCTR","")
    SELF:oSFJOCCI:server:FIELDPUT("LAUDO","")
    SELF:oSFJOCCI:server:FIELDPUT("ASSNOM","")
    SELF:oSFJOCCI:server:FIELDPUT("ASSDAT",CToD(Space(8)))
NEXT K
SELF:server:gotop()
SELF:server:gobottom()
RETURN .t.
	

METHOD ediTIP( ) 
LOCAL oJAN AS XJme04
LOCAL cCODIGO AS STRING
IF ! entramenu("INS",1)
	RETU SELF
ENDIF	
cCODIGO:=AllTrim(SELF:SERVER:FIELDGET("CODIGO"))
oJAN:=XJme04{SELF,cCODIGO,zCURINI,zCURDIR}
oJAN:SHOW()	


METHOD escfor( ) 
LOCAL oESC AS XESCNUM	
LOCAL aFORN AS ARRAY
oESC:=XESCNUM{SELF,ZCURINI,ZCURDIR,"MB01.DBF"}
oESC:SHOW()	
IF oESC:LOK
    SELF:SERVER:FIELDPUT("CODFOR",oESC:NUMERO)
    aFORN:=PEGMB01(SELF:SERVER:CODFOR,ZCURINI,ZCURDIR)
    IF aFORN[1]=.T.
       SELF:SERVER:FIELDPUT("COGFOR",aFORN[3])
    ENDIF
ENDIF

METHOD ESCTIP( ) 
LOCAL oJAN AS XESCME04
LOCAL cFILTRO AS STRING
//cFILTRO:="CODTIPO='DC'.OR.CODTIPO='CCL'"
cFILTRO:=""
oJAN:=XESCME04{SELF,cFILTRO}
oJAN:SHOW()
IF oJAN:lOK
   SELF:SERVEr:FIELDPUT("CODIGO",oJAN:cCODIGO)	
ENDIF	

METHOD EXCLUIR 
LOCAL nITEM AS WORD
nITEM:=1
SELF:oSFJOCCI:SERVER:SUSPENDNOTIFICATION()
IF  MDG("Apagar Registro") .AND. SELF:oSFJOCCI:server:LockCurrentRecord()
    SELF:oSFJOCCI:server:delete()
    SELF:oSFJOCCI:server:unlock()
    SELF:oSFJOCCI:server:skip(-1)
ENDIF	
SELF:oSFJOCCI:server:GOTOP()
WHILE !  SELF:oSFJOCCI:server:EOF
  SELF:oSFJOCCI:server:ITEM:=nITEM
  SELF:oSFJOCCI:server:SKIP()
  nITEM++
ENDDO
SELF:oSFJOCCI:server:GOTOP()
SELF:oSFJOCCI:SERVER:resetnotification()
SELF:oSFJOCCI:SERVER:notify(notifyfilechange)
SELF:oSFJOCCI:Browser:refresh()

METHOD importar( ) 
LOCAL oSERVER,oSERVE2 AS USEREDE
LOCAL aDAD AS ARRAY
LOCAL nNFCC,nREG AS DWORD
nNFCC:=SELF:SERVER:FIELDGET("NFCC")
aDAD:={zCURINI,"ME4CC.DBF",zCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
aDAD:={zCURINI,"ME4CCI.DBF",zCURDIR}
oSERVE2:=USEREDE{aDAD}
IF oSERVE2:nERRO#0
	oSERVER:Close() //Fecha Master
   RETU SELF
ENDIF
oSERVER:GOTOP()
IF oSERVER:SEEK(nNFCC)
   SELF:SERVER:FIELDPUT("CODIGO",oSERVER:FIELDGET("CODME04A"))	
   SELF:SERVER:FIELDPUT("DATA",oSERVER:FIELDGET("DATA"))	
   oSERVE2:SEEK(nNFCC)
   WHILE nNFCC=oSERVE2:FIELDGET("NUMERO") .AND. ! oSERVE2:EoF
       SELF:INCLUIR()
       SELF:oSFJOCCI:SERVER:FIELDPUT("ESPECI",oSERVE2:FIELDGET("DIMENSAO"))
       SELF:oSFJOCCI:SERVER:FIELDPUT("ENCTR",oSERVE2:FIELDGET("ENCONTRA"))
       SELF:oSFJOCCI:SERVER:FIELDPUT("DESVIO",oSERVE2:FIELDGET("TENDENCIA"))
       SELF:oSFJOCCI:SERVER:FIELDPUT("INCTOT",oSERVE2:FIELDGET("INCTOT"))
       IF oSERVE2:FIELDGET("LAUDO")="S"
          SELF:oSFJOCCI:SERVER:FIELDPUT("LAUDO","A")
       ELSE
          SELF:oSFJOCCI:SERVER:FIELDPUT("LAUDO","R")
       ENDIF
   	   oSERVE2:SKIP()
   ENDDO	
ENDIF	
oSERVER:CLOSE()
oSERVE2:CLOSE()
nREG:=SELF:Server:RECNO
SELF:SERVER:GOTOP()
SELF:SERVER:GOTO(nREG)

	

METHOD INCLUIR 
LOCAL nOCC AS DWORD
LOCAL nITEM AS DWORD
nOCC:=SELF:SERVER:OCC
SELF:oSFJOCCI:SERVER:GOBOTTOM()
nITEM:=SELF:oSFJOCCI:SERVER:ITEM
nITEM++
SELF:oSFJOCCI:SERVER:SUSPENDNOTIFICATION()
SELF:oSFJOCCI:SERVER:APPEND()
SELF:oSFJOCCI:SERVER:OCC:=nOCC
SELF:oSFJOCCI:SERVER:ITEM:=nITEM
SELF:oSFJOCCI:SERVER:commit()
SELF:oSFJOCCI:SERVER:resetnotification()
SELF:oSFJOCCI:SERVER:notify(notifyappend)
SELF:oSFJOCCI:Browser:refresh()

METHOD Laudo( ) 
IF ! Empty(SELF:OSFJOCCI:server:FIELDGET("ASSDAT"))
   alert("Laudo Já Assinado")
   RETURN .f.
ENDIF		
SELF:OSFJOCCI:server:FIELDPUT("LAUDO",SIMNAO(SELF:OSFJOCCI:server:FIELDGET("LAUDO"),{"A","R","C"	}))

METHOD pegFOR( ) 
LOCAL aFORN AS ARRAY	
    aFORN:=PEGMB01(SELF:SERVER:CODFOR,ZCURINI,ZCURDIR)
    IF aFORN[1]=.T.
       SELF:SERVER:FIELDPUT("COGFOR",aFORN[3])
    ENDIF

METHOD poroc( ) 
 SELF:KeyFind()

METHOD PostInit() 
   SELF:RegisterTimer(300,FALSE)
       FabCenterWindow( SELF )
 RETURN SELF

METHOD proxima  
	LOCAL oINSTRUME AS USEREDE	
    LOCAL aDAD AS ARRAY	
	LOCAL lGRAVA AS LOGIC
	lGRAVA:=MDG("Atualizar Cadastro de Instrumento")
	aDAD:={ZCURINI,"ME04.DBF",ZCURDIR}
	oINSTRUME:=USEREDE{aDAD}
	IF oINSTRUME:nERRO#0
		RETU SELF
	ENDIF
    oINSTRUME:GoTop()
    IF oINSTRUME:SEEK(AllTrim(SELF:SERVER:CODIGO))
       SELF:SERVER:DATAP:=ADDMES(SELF:sERVER:DATA,oINSTRUME:FIELDGET("CALIBRAR"))
       IF lGRAVA
          oINSTRUME:FIELDPUT("CALULT",SELF:SERVER:DATA)
      	  oINSTRUME:FIELDPUT("CALPRO",ADDMES(oINSTRUME:FIELDGET("CALULT"),oINSTRUME:FIELDGET("CALIBRAR")))
       ENDIF	
    ENDIF
    oINSTRUME:Close()
		
		
	

METHOD PROXIMO 
SELF:oSFJOCCI:Browser:SuspendUpdate()
SELF:oSFJOCCI:SkipNext()
IF SELF:oSFJOCCI:Server:Eof
	SELF:oSFJOCCI:SkipPrevious()
ENDIF
SELF:oSFJOCCI:Browser:RestoreUpdate()

METHOD TABULAR  
SELF:oSFJOCCI:VIEWTABLE()

METHOD Timer() 
   SELF:SERVER:COMMIT()
   SELF:oSFJOCCI:Server:COMMIT()



END CLASS
