CLASS XJTEC INHERIT JTEC

METHOD APPEND(oOWNER) 
alert("Operação Bloqueada")

METHOD DELETE(oOWNER) 
alert("Operação Bloqueada")

CONSTRUCTOR(oOWNER) 
LOCAL oSERVER AS USEREDE
LOCAL aDAD AS ARRAY
IF ! entramenu("INS",7)
	RETU SELF
ENDIF	
aDAD:={zCURINI,"MP04.DBF",ZCURDIR}
oSERVER:=USEREDE{aDAD}
IF oSERVER:nERRO#0
    RETU SELF
ENDIF
SUPER(oOWNER,,oSERVER)
SELF:Browser:SetStandardStyle(gBsreadonly)
SELF:SHOW()		


METHOD TABSET 
RETU MTD02("SETINS",3)


END CLASS
