#region DEFINES
STATIC DEFINE JREQ_AREA := 123
STATIC DEFINE JREQ_BUSCANUM := 103
STATIC DEFINE JREQ_CODIGO := 107
STATIC DEFINE JREQ_CODOPER := 108
STATIC DEFINE JREQ_DEVOLUCAO := 117
STATIC DEFINE JREQ_EDITIP := 111
STATIC DEFINE JREQ_ESCRES := 110
STATIC DEFINE JREQ_ESCTIP := 112
STATIC DEFINE JREQ_HORADEV := 118
STATIC DEFINE JREQ_HORASAI := 116
STATIC DEFINE JREQ_NUMERO := 105
STATIC DEFINE JREQ_PRONUM := 106
STATIC DEFINE JREQ_PUSHBUTTON4 := 121
STATIC DEFINE JREQ_PUSHBUTTON5 := 119
STATIC DEFINE JREQ_PUSHBUTTON6 := 120
STATIC DEFINE JREQ_SAIDA := 102
STATIC DEFINE JREQ_SC_AREA := 122
STATIC DEFINE JREQ_SC_CODIGO := 101
STATIC DEFINE JREQ_SC_CODOPER := 104
STATIC DEFINE JREQ_SC_DEVOLUCAO := 114
STATIC DEFINE JREQ_SC_HORADEV := 115
STATIC DEFINE JREQ_SC_HORASAI := 113
STATIC DEFINE JREQ_SC_NUMERO := 100
STATIC DEFINE JREQ_SC_SAIDA := 109
STATIC DEFINE JREQ_SC_SETOR := 124
STATIC DEFINE JREQ_SETOR := 125
#endregion

PARTIAL CLASS JREQ INHERIT MYDataWindow
PROTECT oDBNUMERO AS DataColumn
PROTECT oDBCODIGO AS DataColumn
PROTECT oDBCODOPER AS DataColumn
PROTECT oDBSAIDA AS DataColumn
PROTECT oDBHORASAI AS DataColumn
PROTECT oDBDEVOLUCAO AS DataColumn
PROTECT oDBHORADEV AS DataColumn
PROTECT oDCSC_NUMERO AS FIXEDTEXT
PROTECT oDCSC_CODIGO AS FIXEDTEXT
PROTECT oDCSAIDA AS DATETIMEPICKER
PROTECT oCCbuscanum AS PUSHBUTTON
PROTECT oDCSC_CODOPER AS FIXEDTEXT
PROTECT oDCNUMERO AS SINGLELINEEDIT
PROTECT oCCpronum AS PUSHBUTTON
PROTECT oDCCODIGO AS SINGLELINEEDIT
PROTECT oDCCODOPER AS rightSle
PROTECT oDCSC_SAIDA AS FIXEDTEXT
PROTECT oCCESCRES AS PUSHBUTTON
PROTECT oCCediTIP AS PUSHBUTTON
PROTECT oCCESCTIP AS PUSHBUTTON
PROTECT oDCSC_HORASAI AS FIXEDTEXT
PROTECT oDCSC_DEVOLUCAO AS FIXEDTEXT
PROTECT oDCSC_HORADEV AS FIXEDTEXT
PROTECT oDCHORASAI AS rightSle
PROTECT oDCDEVOLUCAO AS DateSle
PROTECT oDCHORADEV AS rightSle
PROTECT oCCPushButton5 AS PUSHBUTTON
PROTECT oCCPushButton6 AS PUSHBUTTON
PROTECT oCCPushButton4 AS PUSHBUTTON
PROTECT oDCSC_AREA AS FIXEDTEXT
PROTECT oDCAREA AS COMBOBOX
PROTECT oDCSC_SETOR AS FIXEDTEXT
PROTECT oDCSETOR AS COMBOBOX

// User code starts here (DO NOT remove this line)  ##USER##

ACCESS AREA
RETURN SELF:FieldGet( #AREA )

ASSIGN AREA( uValue )
SELF:FieldPut( #AREA , uValue )

ACCESS CODIGO
RETURN SELF:FieldGet( #CODIGO )

ASSIGN CODIGO( uValue )
SELF:FieldPut( #CODIGO , uValue )

ACCESS CODOPER
RETURN SELF:FieldGet( #CODOPER )

ASSIGN CODOPER( uValue )
SELF:FieldPut( #CODOPER , uValue )

ACCESS DEVOLUCAO
RETURN SELF:FieldGet( #DEVOLUCAO )

ASSIGN DEVOLUCAO( uValue )
SELF:FieldPut( #DEVOLUCAO , uValue )

ACCESS HORADEV
RETURN SELF:FieldGet( #HORADEV )

ASSIGN HORADEV( uValue )
SELF:FieldPut( #HORADEV , uValue )

ACCESS HORASAI
RETURN SELF:FieldGet( #HORASAI )

ASSIGN HORASAI( uValue )
SELF:FieldPut( #HORASAI , uValue )

CONSTRUCTOR(oWindow,iCtlID,oServer,uExtra)
	LOCAL oFont AS Font

	SELF:PreInit(oWindow,iCtlID,oServer,uExtra)

	SUPER(oWindow , ResourceID{"JREQ" , _GetInst()},iCtlID)

	SELF:oDCSC_NUMERO := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_NUMERO  , _GetInst() } }
	SELF:oDCSC_NUMERO:HyperLabel := HyperLabel{#SC_NUMERO , "Numero:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CODIGO := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_CODIGO  , _GetInst() } }
	SELF:oDCSC_CODIGO:HyperLabel := HyperLabel{#SC_CODIGO , "Codigo:" , NULL_STRING , NULL_STRING}

	SELF:oDCSAIDA := DATETIMEPICKER{SELF , ResourceID{ JREQ_SAIDA  , _GetInst() } }
	SELF:oDCSAIDA:FieldSpec := date_field{}
	SELF:oDCSAIDA:HyperLabel := HyperLabel{#SAIDA , "Saida" , NULL_STRING , NULL_STRING}

	SELF:oCCbuscanum := PUSHBUTTON{SELF , ResourceID{ JREQ_BUSCANUM  , _GetInst() } }
	SELF:oCCbuscanum:Image := ICO_FIND{}
	SELF:oCCbuscanum:HyperLabel := HyperLabel{#buscanum , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_CODOPER := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_CODOPER  , _GetInst() } }
	SELF:oDCSC_CODOPER:HyperLabel := HyperLabel{#SC_CODOPER , "Funcionário" , NULL_STRING , NULL_STRING}

	SELF:oDCNUMERO := SINGLELINEEDIT{SELF , ResourceID{ JREQ_NUMERO  , _GetInst() } }
	SELF:oDCNUMERO:FieldSpec := padrao_num_08{}
	SELF:oDCNUMERO:Background := Brush{ Color{ 255 , 255 , 200 } }
	oFont := Font{  , 12 , "Times New Roman" }
	oFont:Bold := TRUE
	SELF:oDCNUMERO:Font( oFont )
	SELF:oDCNUMERO:HyperLabel := HyperLabel{#NUMERO , "Numero:" , NULL_STRING , "ME04R_NUMERO"}

	SELF:oCCpronum := PUSHBUTTON{SELF , ResourceID{ JREQ_PRONUM  , _GetInst() } }
	SELF:oCCpronum:Image := ICO_AZ{}
	SELF:oCCpronum:HyperLabel := HyperLabel{#pronum , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCCODIGO := SINGLELINEEDIT{SELF , ResourceID{ JREQ_CODIGO  , _GetInst() } }
	SELF:oDCCODIGO:FieldSpec := padrao_char_08{}
	SELF:oDCCODIGO:HyperLabel := HyperLabel{#CODIGO , "Código:" , NULL_STRING , "ME04R_CODIGO"}

	SELF:oDCCODOPER := rightSle{SELF , ResourceID{ JREQ_CODOPER  , _GetInst() } }
	SELF:oDCCODOPER:FieldSpec := padrao_num_08{}
	SELF:oDCCODOPER:HyperLabel := HyperLabel{#CODOPER , "Funcionario" , NULL_STRING , "ME04R_CODOPER"}

	SELF:oDCSC_SAIDA := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_SAIDA  , _GetInst() } }
	SELF:oDCSC_SAIDA:HyperLabel := HyperLabel{#SC_SAIDA , "Saida:" , NULL_STRING , NULL_STRING}

	SELF:oCCESCRES := PUSHBUTTON{SELF , ResourceID{ JREQ_ESCRES  , _GetInst() } }
	SELF:oCCESCRES:Image := ICO_FIND{}
	SELF:oCCESCRES:HyperLabel := HyperLabel{#ESCRES , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oCCediTIP := PUSHBUTTON{SELF , ResourceID{ JREQ_EDITIP  , _GetInst() } }
	SELF:oCCediTIP:HyperLabel := HyperLabel{#ediTIP , "E" , NULL_STRING , NULL_STRING}

	SELF:oCCESCTIP := PUSHBUTTON{SELF , ResourceID{ JREQ_ESCTIP  , _GetInst() } }
	SELF:oCCESCTIP:Image := ICO_FIND{}
	SELF:oCCESCTIP:HyperLabel := HyperLabel{#ESCTIP , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HORASAI := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_HORASAI  , _GetInst() } }
	SELF:oDCSC_HORASAI:HyperLabel := HyperLabel{#SC_HORASAI , "Hora Saida:" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_DEVOLUCAO := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_DEVOLUCAO  , _GetInst() } }
	SELF:oDCSC_DEVOLUCAO:HyperLabel := HyperLabel{#SC_DEVOLUCAO , "Devolução" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_HORADEV := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_HORADEV  , _GetInst() } }
	SELF:oDCSC_HORADEV:HyperLabel := HyperLabel{#SC_HORADEV , "Hora Devolução:" , NULL_STRING , NULL_STRING}

	SELF:oDCHORASAI := rightSle{SELF , ResourceID{ JREQ_HORASAI  , _GetInst() } }
	SELF:oDCHORASAI:FieldSpec := padrao_num_05_2{}
	SELF:oDCHORASAI:HyperLabel := HyperLabel{#HORASAI , "Hora" , NULL_STRING , "ME04R_HORASAI"}

	SELF:oDCDEVOLUCAO := DateSle{SELF , ResourceID{ JREQ_DEVOLUCAO  , _GetInst() } }
	SELF:oDCDEVOLUCAO:FieldSpec := date_field{}
	SELF:oDCDEVOLUCAO:HyperLabel := HyperLabel{#DEVOLUCAO , "Devolucao:" , NULL_STRING , "ME04R_DEVOLUCAO"}

	SELF:oDCHORADEV := rightSle{SELF , ResourceID{ JREQ_HORADEV  , _GetInst() } }
	SELF:oDCHORADEV:FieldSpec := padrao_num_05_2{}
	SELF:oDCHORADEV:HyperLabel := HyperLabel{#HORADEV , "Hora" , NULL_STRING , "ME04R_HORADEV"}

	SELF:oCCPushButton5 := PUSHBUTTON{SELF , ResourceID{ JREQ_PUSHBUTTON5  , _GetInst() } }
	SELF:oCCPushButton5:HyperLabel := HyperLabel{#PushButton5 , "Agora" , NULL_STRING , NULL_STRING}

	SELF:oCCPushButton6 := PUSHBUTTON{SELF , ResourceID{ JREQ_PUSHBUTTON6  , _GetInst() } }
	SELF:oCCPushButton6:HyperLabel := HyperLabel{#PushButton6 , "Agora" , NULL_STRING , NULL_STRING}

	SELF:oCCPushButton4 := PUSHBUTTON{SELF , ResourceID{ JREQ_PUSHBUTTON4  , _GetInst() } }
	SELF:oCCPushButton4:HyperLabel := HyperLabel{#PushButton4 , "Hoje" , NULL_STRING , NULL_STRING}

	SELF:oDCSC_AREA := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_AREA  , _GetInst() } }
	SELF:oDCSC_AREA:HyperLabel := HyperLabel{#SC_AREA , "Area:" , NULL_STRING , NULL_STRING}

	SELF:oDCAREA := COMBOBOX{SELF , ResourceID{ JREQ_AREA  , _GetInst() } }
	SELF:oDCAREA:FieldSpec := padrao_char_02{}
	SELF:oDCAREA:HyperLabel := HyperLabel{#AREA , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:oDCSC_SETOR := FIXEDTEXT{SELF , ResourceID{ JREQ_SC_SETOR  , _GetInst() } }
	SELF:oDCSC_SETOR:HyperLabel := HyperLabel{#SC_SETOR , "Setor:" , NULL_STRING , NULL_STRING}

	SELF:oDCSETOR := COMBOBOX{SELF , ResourceID{ JREQ_SETOR  , _GetInst() } }
	SELF:oDCSETOR:FieldSpec := padrao_char_03{}
	SELF:oDCSETOR:HyperLabel := HyperLabel{#SETOR , NULL_STRING , NULL_STRING , NULL_STRING}

	SELF:Caption := "Requisições"
	SELF:Menu := STANDARDSHELLMENU{}
	SELF:ClipperKeys := TRUE
	SELF:HyperLabel := HyperLabel{#JREQ , "Requisições" , NULL_STRING , NULL_STRING}
	IF !IsNil(oServer)
		SELF:Use(oServer)
	ENDIF

	SELF:Browser := DataBrowser{SELF}

	SELF:oDBNUMERO := DataColumn{padrao_num_08{}}
	SELF:oDBNUMERO:Width := 8
	SELF:oDBNUMERO:HyperLabel := SELF:oDCNUMERO:HyperLabel
	SELF:oDBNUMERO:Caption := "Numero:"
	SELF:Browser:AddColumn(SELF:oDBNUMERO)

	SELF:oDBCODIGO := DataColumn{padrao_char_08{}}
	SELF:oDBCODIGO:Width := 11
	SELF:oDBCODIGO:HyperLabel := SELF:oDCCODIGO:HyperLabel
	SELF:oDBCODIGO:Caption := "Código:"
	SELF:Browser:AddColumn(SELF:oDBCODIGO)

	SELF:oDBCODOPER := DataColumn{padrao_num_08{}}
	SELF:oDBCODOPER:Width := 11
	SELF:oDBCODOPER:HyperLabel := SELF:oDCCODOPER:HyperLabel
	SELF:oDBCODOPER:Caption := "Funcionario"
	SELF:Browser:AddColumn(SELF:oDBCODOPER)

	SELF:oDBSAIDA := DataColumn{date_field{}}
	SELF:oDBSAIDA:Width := 10
	SELF:oDBSAIDA:HyperLabel := SELF:oDCSAIDA:HyperLabel
	SELF:oDBSAIDA:Caption := "Saida"
	SELF:Browser:AddColumn(SELF:oDBSAIDA)

	SELF:oDBHORASAI := DataColumn{padrao_num_05_2{}}
	SELF:oDBHORASAI:Width := 9
	SELF:oDBHORASAI:HyperLabel := SELF:oDCHORASAI:HyperLabel
	SELF:oDBHORASAI:Caption := "Hora"
	SELF:Browser:AddColumn(SELF:oDBHORASAI)

	SELF:oDBDEVOLUCAO := DataColumn{date_field{}}
	SELF:oDBDEVOLUCAO:Width := 11
	SELF:oDBDEVOLUCAO:HyperLabel := SELF:oDCDEVOLUCAO:HyperLabel
	SELF:oDBDEVOLUCAO:Caption := "Devolucao:"
	SELF:Browser:AddColumn(SELF:oDBDEVOLUCAO)

	SELF:oDBHORADEV := DataColumn{padrao_num_05_2{}}
	SELF:oDBHORADEV:Width := 9
	SELF:oDBHORADEV:HyperLabel := SELF:oDCHORADEV:HyperLabel
	SELF:oDBHORADEV:Caption := "Hora"
	SELF:Browser:AddColumn(SELF:oDBHORADEV)

	SELF:ViewAs(#FormView)


	SELF:PostInit(oWindow,iCtlID,oServer,uExtra)

RETURN


ACCESS NUMERO
RETURN SELF:FieldGet( #NUMERO )

ASSIGN NUMERO( uValue )
SELF:FieldPut( #NUMERO , uValue )

ACCESS SETOR
RETURN SELF:FieldGet( #SETOR )

ASSIGN SETOR( uValue )
SELF:FieldPut( #SETOR , uValue )

END CLASS
