CLASS ICO_AJUDA INHERIT Icon

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_AJUDA", _GetInst()})

END CLASS
CLASS ICO_autook INHERIT Icon

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_autook", _GetInst()})

END CLASS
CLASS ICO_AZ INHERIT Icon

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_AZ", _GetInst()})

END CLASS
CLASS ICO_CAMERA INHERIT Icon

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_CAMERA", _GetInst()})

END CLASS
CLASS ICO_CHAVE2 INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_CHAVE2", _GetInst()})

END CLASS
CLASS ICO_delete INHERIT Icon	


	CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_delete", _GetInst()})

END CLASS
CLASS ICO_editor INHERIT Icon	

   CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_editor", _GetInst()})

END CLASS
CLASS ICO_FILTRO INHERIT Icon	

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_FILTRO", _GetInst()})

END CLASS
CLASS ICO_FIND INHERIT Icon

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_FIND", _GetInst()})

END CLASS
CLASS ICO_GRAVA INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_GRAVA", _GetInst()})

END CLASS
CLASS ICO_HAND INHERIT Icon

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_HAND", _GetInst()})

END CLASS
CLASS ICO_mail INHERIT Icon

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_mail", _GetInst()})

END CLASS
CLASS ICO_mailarq INHERIT Icon	

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_mailarq", _GetInst()})

END CLASS
CLASS ICO_NEW INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_NEW", _GetInst()})

END CLASS
CLASS ICO_NEXT INHERIT Icon	

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_NEXT", _GetInst()})

END CLASS
CLASS ICO_OK INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_OK", _GetInst()})

END CLASS
CLASS ICO_PREVIOUS INHERIT Icon	

CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_PREVIOUS", _GetInst()})

END CLASS
CLASS ICO_PRINT INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_PRINT", _GetInst()})

END CLASS
CLASS ICO_PRINTCFG INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_PRINTCFG", _GetInst()})

END CLASS
CLASS ICO_SAIR INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICO_SAIR", _GetInst()})


END CLASS
